### ISSUE TITLE
[Bug]: In iOS 18.0 devices ,while free hand drawing some points on the line was missing and after dropping it will reappear as free line

### ISSUE THREAD

**Issue by dillasugunan** [fabricjs/fabric.js#10006]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Chrome, Safari, Node.js

### Node Version (if applicable)

None

### Link To Reproduction

open canvas to draw in any browser

### Steps To Reproduce

1. choose freehand brush for drawing in canvas 
2. when we start drawing , some points won't show, but once we stop drawing it will regain what we drawn
3.

### Expected Behavior

drawing should be visible 

### Actual Behavior

https://github.com/user-attachments/assets/4c795afa-13ab-41a2-a849-b84efdfc0c55

**Comment by asturur** [comment]
i'll reopen if you can make a reproducible sample.
Also i haveIOS 17 only.
