### ISSUE TITLE
[Bug]: adding controls to polygon cause an errors

### ISSUE THREAD

**Issue by shyallegro** [fabricjs/fabric.js#10002]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Firefox

### Node Version (if applicable)

None

### Link To Reproduction

https://fabricjs.github.io/demos/poly-controls/

### Steps To Reproduce

1. in the demo above from fabric, click the polygon to add controls to the polygon
2. 
3.

### Expected Behavior

adding controls shouldn't cause an error

### Actual Behavior

```
Uncaught TypeError: l is undefined
    drawControls index.min.CzXp6mIQ.js:formatted:5757
    forEachControl index.min.CzXp6mIQ.js:formatted:5632
    drawControls index.min.CzXp6mIQ.js:formatted:5753
    _renderControls index.min.CzXp6mIQ.js:formatted:5700
    drawControls index.min.CzXp6mIQ.js:formatted:9063
    renderCanvas index.min.CzXp6mIQ.js:formatted:2033
    renderAll index.min.CzXp6mIQ.js:formatted:8556
    renderAndReset index.min.CzXp6mIQ.js:formatted:1980
    nextRenderHandle index.min.CzXp6mIQ.js:formatted:1986
```

```javascript
 this.forEachControl(
      (h, c) => {
        if (h.getVisibility(this, c)) {
          const l = this.oCoords[c];
          h.render(t, l.x, l.y, a, this)
        }
      }
    ),
```
```
Uncaught TypeError: undefined has no properties
    findControl index.min.CzXp6mIQ.js:formatted:5581
    findTarget index.min.CzXp6mIQ.js:formatted:8769
    _cacheTransformEventData index.min.CzXp6mIQ.js:formatted:9815
    __onMouseMove index.min.CzXp6mIQ.js:formatted:9820
    _onMouseMove index.min.CzXp6mIQ.js:formatted:9597
```

**Comment by lance-lfx** [comment]
Is there any update to this issue? I run into the same problem when I am trying to add poly controls using the new method createPolyControls() as shown in the demo.

TypeError: Cannot read properties of undefined (reading 'x')

**Comment by asturur** [comment]
I fixed the demo but i didn't push it up yet.
When you assign new controls to an object that is already on the canvas, you should call setCoords(), that fixed the issue in the demo

**Comment by kukudeshengge** [comment]
Hello, if the effect is not a polygon, is a combination, can achieve the same effect?
