### ISSUE TITLE
[Bug]: FabricJS v6.0.2 Can't have own object identifier (e.g. ID) because of the typescript missing type

### ISSUE THREAD

**Issue by anzhel-milenov** [fabricjs/fabric.js#10018]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### Node Version (if applicable)

None

### Link To Reproduction

v6 Typescript

### Steps To Reproduce

1. Add id as a custom additional prop to an object.
2. Try to call it, then typescript error occurs(even the id is added properly and exists in the canvas and can operate with it to select the proper object)

### Expected Behavior

I think we have to have some custom property like "ID". Objects have to be idenfiable somehow.
Especially usable, when have loadFromJSON and lose all the references to your objects. It is actually works like this, but is not allowed by the typescript

Example code:
```
this.rightLine = new Line([this.canvasWidth - this.bleedMarginInPixels, this.bleedMarginInPixels, this.canvasWidth - this.bleedMarginInPixels, this.canvasHeight - this.bleedMarginInPixels], {
      id: "right-line",
      stroke: '#FF0000',
      strokeDashArray: [5, 5],
      strokeWidth: 1,
      selectable: true, // Make the line non-selectable
      padding:20
    });
    this.canvas.add(this.rightLine);
```

```
this.canvas.getObjects().forEach(o => {
        if (o.id === 'right-line') {
          this.canvas.bringObjectToFront(o);
        }
      });
```

### Actual Behavior

It gives typescript error:
`Property 'id' does not exist on type 'FabricObject<Partial<FabricObjectProps>, SerializedObjectProps, ObjectEvents>'.ts(2339)`

**Comment by anzhel-milenov** [comment]
I did some workaround with custom .ts

```
import type { FabricObject, Canvas } from 'fabric';

declare module 'fabric' {
  export interface FabricObject {
    id?: string;
  }
}
export class FabricHelper {
  private canvas: Canvas;

  constructor(canvas: Canvas) {
    this.canvas = canvas;
  }

  public findObjectById(id: string): FabricObject | null{
    let myObject = null; 
    this.canvas.getObjects().forEach(theObject => {
      if (theObject.id === id) {
        myObject = theObject;
        return;
      }
    });
    
    return myObject;
  }

}


export default FabricHelper;

```

**Comment by asturur** [comment]
Yes extending the interface is the correct solution, for objects that have types instead of interface we need to fix
