### ISSUE TITLE
[Bug]: Custom controllers that I had previously set up are missing in version 6

### ISSUE THREAD

**Issue by alwalxed** [fabricjs/fabric.js#10023]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

N/A

### Steps To Reproduce

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

**Comment by asturur** [comment]
<img width="401" alt="image" src="https://github.com/user-attachments/assets/cdcbdf69-38c4-4ecb-8a39-08bf8bd24a49">

**Comment by alwalxed** [comment]
> <img alt="image" width="401" src="https://private-user-images.githubusercontent.com/1194048/352090107-cdcbdf69-38c4-4ecb-8a39-08bf8bd24a49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MDc4NDAsIm5iZiI6MTcyMTkwNzU0MCwicGF0aCI6Ii8xMTk0MDQ4LzM1MjA5MDEwNy1jZGNiZGY2OS0zOGM0LTRlY2ItOGEzOS0wOGJmOGJkMjRhNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMTEzOTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzExN2IxNDc2MGY0N2U1MzliNWIyNDBmMjVjZWMwZGI1MzczNWJhYjVjZGZkNWI4ODE4MjhhZTQzOTVjZmM1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AXj-hwvPiPQ_8V4rekWNHr15P19G0y38hC4b_KyuxIs">
> I see the checkbox, where is the actual code?

Sorry, but the code is private. Here is a comprehensible sample (focusing on the clone controller for simplicity)

// entry
`'use client';

import { Canvas } from 'fabric';

import { useEffect, useRef } from 'react';

import { useZustand } from '@/lib/zustand/store';

import { getCanvasOptions } from './consts/get-canvasOptions';
import { initConfig } from './helpers/init-configs';
import { initListeners } from './listeners/__init';

export function InitFabric() {
  const fabricRef = useRef<HTMLCanvasElement | null>(null);
  const setFabricRef = useZustand.use.setFabricRef();
  const { height, width } = useZustand.use.mockupDimensions();

  useEffect(() => {
    if (!fabricRef.current) return;

    try {
      const canvas = new Canvas(
        fabricRef.current.id,
        getCanvasOptions(height, width),
      );

      setFabricRef(canvas);

      initConfig();

      initListeners();

      return () => {
        setFabricRef(undefined);
        canvas.dispose();
      };
    } catch (error) {
      console.error('Error initializing canvas:', error);
    }
  }, [height, width, setFabricRef]);

  return <canvas id='canvas' ref={fabricRef} />;
}
`

// initConfig()
`import {
  setDefaultObjectStyles,
  setVisibility,
} from '../consts/styles-controllers';
import { cloneController } from '../controllers/clone';
import { deleteController } from '../controllers/delete';
import { resizeController } from '../controllers/resize';
import { rotateController } from '../controllers/rotate';
import { zIndexController } from '../controllers/zIndex';

export function initConfig() {
  setVisibility();
  setDefaultObjectStyles();
  rotateController();
  deleteController();
  resizeController();
  cloneController();
  zIndexController();
}
`

// setVisibility & setDefaultObjectStyles
`import { FabricObject, FabricText } from 'fabric';

export function setVisibility() {
  const options = {
    mt: true,
    tr: false,
    tl: false,
    ml: false,
    mr: false,
    bl: false,
    mb: true,
  };
  FabricObject.prototype.setControlsVisibility(options);
  FabricText.prototype.setControlsVisibility(options);
}

export function setDefaultObjectStyles() {
  const object = FabricObject.prototype;

  const options: Partial<FabricObject> = {
    transparentCorners: false,
    borderColor: '#0d99ff',
    scaleX: 1,
    scaleY: 1,
  };

  object.set(options);
}
`

// cloneController
`import { Control, ControlActionHandler } from 'fabric';

import { iconDataURI } from '@/resources/consts/svg-data-icons';

import { cloneObject } from '../actions/object-clone';
import { objectControl, textControl } from '../consts/aliases';
import { renderIcon } from '../helpers/icon-render';

export function cloneController() {
  let cloneImg = document.createElement('img');
  cloneImg.src = iconDataURI.clone;

  objectControl.cloneControl = new Control({
    x: -0.5,
    y: 0.5,
    sizeX: -45,
    sizeY: 45,
    actionName: 'clone',
    cursorStyle: 'copy',
    mouseUpHandler: cloneObject as ControlActionHandler,
    render: renderIcon(cloneImg),
  });

  textControl.cloneControl = new Control({
    x: -0.5,
    y: 0.5,
    sizeX: -45,
    sizeY: 45,
    actionName: 'clone',
    cursorStyle: 'copy',
    mouseUpHandler: cloneObject,
    render: renderIcon(cloneImg),
  });
}
`

// cloneObject
`import { TPointerEvent, Transform } from 'fabric';

export async function cloneObject(
  eventData: TPointerEvent,
  transform: Transform,
  x: number,
  y: number,
): Promise<boolean> {
  const target = transform.target;
  if (!target) {
    console.error('No target found.');
    return false;
  }

  const canvas = target.canvas;

  if (!canvas) {
    console.error('No canvas found.');
    return false;
  }

  try {
    const cloned = await target.clone();
    cloned.set({
      left: target.left + -10,
      top: target.top + 10,
    });

    canvas.add(cloned);
    canvas.setActiveObject(cloned);
    canvas.requestRenderAll();
    return true;
  } catch (error) {
    console.error('Error cloning object:', error);
    return false;
  }
}
`
