### ISSUE TITLE
[Bug]: Unable to place image on canvas with FabricImage.fromURL

### ISSUE THREAD

**Issue by LouieTian0209** [fabricjs/fabric.js#10020]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

18.20.3

### Link To Reproduction

https://stackblitz.com/edit/stackblitz-starters-spfsxo?file=src%2Fapp%2Ffabric-canvas%2Ffabric-canvas.component.ts

### Steps To Reproduce

1. Click on "Place Site Marker" or "Place Exclamation Marker" button in the repro demo
2. Open developer tools and click somewhere on the canvas
3. See the "Image successfully added to canvas:" message show up in console, but image was not visible.

### Expected Behavior

New image should be added on the canvas every time a click happens on canvas.

### Actual Behavior

Nothing is added onto canvas after click.

**Comment by asturur** [comment]
The images that you are adding are transparent.
By setting width and height to 50px you are just adding the top left transparent corner of each image.
Use scale to make the image smaller.
