### ISSUE TITLE
[Bug]: Large vectors are blurred when using scale/width

### ISSUE THREAD

**Issue by bitttttten** [fabricjs/fabric.js#10046]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://stackblitz.com/edit/js-rxxgfx?file=index.js

### Steps To Reproduce

1. loadSVGFromString of a square 60x60 blue. 
2. set scaleX of the object to 500.
4. add object to canvas.
5. see the blur when you expect no blur.

### Expected Behavior

I expect to see no blur, just the blue rectangle.

![Screenshot 2024-08-09 at 13 30 54](https://github.com/user-attachments/assets/3e46fe63-01ba-469a-b491-d3c20beabb44)

### Actual Behavior

https://stackblitz.com/edit/js-rxxgfx?file=index.js

Blur:

![Screenshot 2024-08-09 at 13 30 49](https://github.com/user-attachments/assets/4ca6fc54-8606-4a5b-81bd-ad3a119d4839)

**Comment by bitttttten** [comment]
Even when we draw with `objectCaching: false` the object normally draws without blur but the gap between control points and the actual rectangle still exist

**Comment by asturur** [comment]
The gap is the 1 point default strokewidth that is default svg value. Set stroke-width to 0 in your svg or set it in the resulting object.

For object caching you can give higher resolution to the cache or disable it, it depends what is your final rendering

**Comment by bitttttten** [comment]
Thanks, that makes sense!
