### ISSUE TITLE
[Bug]: Changing a textbox cursor before editing seems to silently crash the textbox

### ISSUE THREAD

**Issue by niels-van-den-broeck** [fabricjs/fabric.js#10040]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Firefox, Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/p/sandbox/jolly-feather-qs3t3w

### Steps To Reproduce

1. click anywhere outside of the existing textbox (creates a new one and enters editing on it)
2. click anywhere inside the text of that box to change your cursor
3. try to type 

### Expected Behavior

It sets the cursor to my desired location.

I've had this happen to me on numerous occasions. Not sure if they are all related to the same thing but they do show the same behaviour. 

setting selectable to false seems to cause the behaviour even quicker.

### Actual Behavior

Textbox seems frozen and can not be edited

### Error Message & Stack Trace

```bash
No logs are emitted.
```

**Comment by zhe-he** [comment]
Add these two lines to solve the problem. 
It seems that the issue is caused by the internal Fabric not updating hoverTarget and activeObject when entering and exiting edit mode.

<img width="541" alt="image" src="https://github.com/user-attachments/assets/8b2ea1eb-f06d-4962-960c-a1b2bc6624e3">

**Comment by zhe-he** [comment]
@asturur 
In this case, does Fabric need to handle it internally? Automatically clear the previously selected object while selecting the current object when the text is focused. Also... what about the triggering of selection:updated?

**Comment by asturur** [comment]
It seems to me this is a custom flow that is external to fabric.
Something i would really like to do is to remove all the internal handling of those interaction in a stack of function that gets executed one after the other and that the developer can learn to tweak. I do not want to add more logic for this particular use case because the current system just isn't customizable enough

**Comment by niels-van-den-broeck** [comment]
> It seems to me this is a custom flow that is external to fabric. Something i would really like to do is to remove all the internal handling of those interaction in a stack of function that gets executed one after the other and that the developer can learn to tweak. I do not want to add more logic for this particular use case because the current system just isn't customizable enough

So, calling enterediting programmatically is not an intended feature? 

I agree that we have a custom workflow. But I feel like this is basic behaviour provided by the api which might be necessary for other things than custom selection?

**Comment by asturur** [comment]
Yes you can call enterEditing programmatically, as long as the object is the active one. I think that is the only caveat
