### ISSUE TITLE
[Bug]: controls not updated when using setX() / setY() / rotate()

### ISSUE THREAD

**Issue by Sayene** [fabricjs/fabric.js#10052]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/p/devbox/fabric-nextjs-sandbox-forked-7lhfg6

### Steps To Reproduce

1. use setX() or setY() or rotate()  or set({scaleY, scaleX, width, height}) or scaleToWidth() or scaleToHeight()  on selected object
2. object is moving, but controls are not
tested with 6.1.0.

### Expected Behavior

controls move with object when using setX() / setY() / rotate() /  set({scaleY, scaleX, width, height}) / scaleToWidth() / scaleToHeight() 

### Actual Behavior

controls do not move with object when using setX() / setY() /   set({scaleY, scaleX, width, height}) / scaleToWidth() / scaleToHeight()

**Comment by asturur** [comment]
Not sure if to call this a bug, when updating left and top you are supposed to call setCoords on your own.

**Comment by Sayene** [comment]
Ok. if so, it must have changed somewhere in late betas and I must have missed it. Thanks for your answer

**Comment by asturur** [comment]
There has been some reduction on the calls to setCoords,
https://github.com/fabricjs/fabric.js/pull/9795/files#diff-fe6477e182894fdb5db40e4d3bffa1f12e02af91a158b9619752aca781441332L565
I think before we were safeguarded by this call here that has been removed for performance reasons
