### ISSUE TITLE
Uncaught TypeError: Cannot call method 'apply' of undefined in all.js:3135

### ISSUE THREAD

**Issue by binarysilo** [fabricjs/fabric.js#1005]
I'm receiving this error originating from all.js

Uncaught TypeError: Cannot call method 'apply' of undefined 

```
function klass() {
```

(ln: 3135) -->     this.initialize.apply(this, arguments);
    }

**Comment by saran110313** [comment]
I'm receiving this error originating from fabric.js

Uncaught TypeError: Cannot call method 'apply' of undefined

function klass() {
(ln: 3135) --> this.initialize.apply(this, arguments);
}

**Comment by asturur** [comment]
Which browser? Which Fabric version? Please create small jsfiddle showing the issue. Keeping closed for now.

**Comment by saran110313** [comment]
chrome..version1.4.4

**Comment by saran110313** [comment]
browser chrome and fabric.js version 1.4.4

**Comment by saran110313** [comment]
Uncaught TypeError: url.indexOf is not a function
how to solved this error.

**Comment by saran110313** [comment]
function klass() {
      this.initialize.apply(this, arguments);
    }

Uncaught TypeError: Cannot read property 'apply' of undefined.
how to solved this method error....

**Comment by saran110313** [comment]
Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'
how to solve this error in fabric.js

**Comment by asturur** [comment]
Please provide a jsfiddle with code on stackoverflow or google group.
We do not provide code assistance here.
Here we manage issue with the library after a bug has been discovered.
Thanks for understaning.
