### ISSUE TITLE
[Bug]: uniapp run in Android APP - 'jsdom.JSDOM is not a constructor'

### ISSUE THREAD

**Issue by TracyCai** [fabricjs/fabric.js#10060]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Node.js

### Node Version (if applicable)

21.0.0

### Link To Reproduction

'jsdom.JSDOM is not a constructor'

### Steps To Reproduce

1. node v20.16.0
2. "fabric": "^5.4.0"
3.import {
	fabric
} from 'fabric'

### Expected Behavior

normal operation

### Actual Behavior

'jsdom.JSDOM is not a constructor'

### Error Message & Stack Trace

```bash
[Bug]: Hi, we want to make a app used uniapp. after 'npm i fabric --save' and import fabirc, it can be used in browser， but it has error 'jsdom.JSDOM is not a constructor' in app. May I ask how we should fix this issue?
```

**Comment by TracyCai** [comment]
"optionalDependencies": {
        "canvas": "^2.8.0",
        "jsdom": "^19.0.0"
      }

**Comment by asturur** [comment]
I m not sure what an uniapp is.
are you running fabricJS under node?

**Comment by codon19** [comment]
> "optionalDependencies": { "canvas": "^2.8.0", "jsdom": "^19.0.0" }



> ### CheckList
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
> * [x]  I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
> * [x]  I have searched and referenced existing issues and discussions
> * [x]  I am filing a **BUG** report.
> * [x]  I have managed to reproduce the bug **after** upgrading to the **latest** version
> * [x]  I have created an accurate and minimal reproduction
> 
> ### Version
> 6.0.2
> 
> ### In What environments are you experiencing the problem?
> Node.js
> 
> ### Node Version (if applicable)
> 21.0.0
> 
> ### Link To Reproduction
> 'jsdom.JSDOM is not a constructor'
> 
> ### Steps To Reproduce
> 1. node v20.16.0
> 2. "fabric": "^5.4.0"
>    3.import {
>    fabric
>    } from 'fabric'
> 
> ### Expected Behavior
> normal operation
> 
> ### Actual Behavior
> 'jsdom.JSDOM is not a constructor'
> 
> ### Error Message & Stack Trace
> ```shell
> [Bug]: Hi, we want to make a app used uniapp. after 'npm i fabric --save' and import fabirc, it can be used in browser， but it has error 'jsdom.JSDOM is not a constructor' in app. May I ask how we should fix this issue?
> ```


You can use fabric.js in an H5 page and display the webpage through a WebView, but the native app cannot directly use fabric.js.

**Comment by asturur** [comment]
Without a reproducible case and without knowing if you installed the optional dependencies for node this issue can be closed
