### ISSUE TITLE
[Bug]: npm install is installing 5.4.0 by default

### ISSUE THREAD

**Issue by nihirv** [fabricjs/fabric.js#10062]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### Node Version (if applicable)

None

### Link To Reproduction

N/A

### Steps To Reproduce

1. npm install fabric --save

### Expected Behavior

Install the latest version of fabric (6.2.0)

### Actual Behavior

Installs version 5.4.0

On https://www.npmjs.com/package/fabric?activeTab=versions, you can see the current tag has been (accidentally?) set as 5.4.0

**Comment by asturur** [comment]
I published from github action where i unflagged 'make this the latest release' but eventually my github action ignore that flag and needs to be fixed.
I ll push another 6.x soon

**Comment by asturur** [comment]
let me do that now so we clear this issue away asap

**Comment by asturur** [comment]
i overwrote with 6.3.0 version that is as 6.2.0 + the guidelines
