### ISSUE TITLE
[Feature]: ITextEvents should be an import type

### ISSUE THREAD

**Issue by gloriousjob** [fabricjs/fabric.js#10074]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

I subclass the Textbox to add my own properties but I can't get ITextEvents to easily extend the EventSpec. The type isn't exported in fabric.

### Current State

Putting import { type ITextEvents } from 'fabric'; tosses an error of no exported types.

I end up putting this in my file (hoping it'll never change):
type ITextEvents = ObjectEvents & {
	'selection:changed': never;
	changed: never | { index: number; action: string };
	tripleclick: TPointerEventInfo;
	'editing:entered': never | { e: TPointerEvent };
	'editing:exited': never;
};

### Additional Context

I imagine adding
export type { ITextEvents } from './src/shapes/IText/ITextBehavior';
to fabric.ts will solve the problem.

**Comment by asturur** [comment]
Yes this is a forgotten export.
Needs to be exported
