### ISSUE TITLE
[Feature]:  I cannot find the full number of npm packages

### ISSUE THREAD

**Issue by xiaoli1999** [fabricjs/fabric.js#10080]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

 
I can use npm i fabric to download the package,

but this package does not include features such as Erasing.

### Current State

I want to download the full amount of Fabric JS through npm. 

Where should I find this package or document? 

The official document only requires downloading the full version of JS.

**Comment by asturur** [comment]
The eraser become its own package
https://github.com/ShaMan123/erase2d

**Comment by xiaoli1999** [comment]
> 橡皮擦成为自己的包 https://github.com/ShaMan123/erase2d

Thank you for your reply.

 I have tried and this package should be from Fabric JS 6 version. I would like to use it in Fabric JS 5.3 version. 

Do you have any other bags

**Comment by asturur** [comment]
in fabricjs 5.4 package you should find the files of the old eraser that was built inside fabricJS, i don't remember how to use it but it should be there.

**Comment by betsylotus** [comment]
> The eraser become its own package https://github.com/ShaMan123/erase2d

Fabric JS 6 version，how can i use eraser
