### ISSUE TITLE
[Bug]: Impossible to run the first Demo Plain HTML 

### ISSUE THREAD

**Issue by alexisvisco** [fabricjs/fabric.js#10084]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Plain HTML, all browsers

### Node Version (if applicable)

None

### Link To Reproduction

https://codepen.io/alexisvisco/pen/gONzLLa

### Steps To Reproduce

Demo isn't working as expected. v6 Does not works for plain HTML on all CDN.

### Expected Behavior

It should works. 

### Actual Behavior

It does not find fabric. 

### Error Message & Stack Trace

```bash
ReferenceError: fabric is not defined
    at gONzLLa?nocache=true&view=:42:18
```

**Comment by asturur** [comment]
@alexisvisco you are using the wrong url

https://cdn.jsdelivr.net/npm/fabric@6.3.0/dist/index.min.js

**Comment by alexisvisco** [comment]
@asturur the readme should be updated so ...
<img width="1054" alt="image" src="https://github.com/user-attachments/assets/e5da6f45-43d6-4b25-becd-5fcf8e833bd5">

**Comment by asturur** [comment]
Yes if that is on our readme yes.
Can you open a PR for that?
