### ISSUE TITLE
[Bug]: TS error when importing extensions

### ISSUE THREAD

**Issue by hamzawain7** [fabricjs/fabric.js#10109]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

See screen shot in steps to reproduce

### Steps To Reproduce

![image](https://github.com/user-attachments/assets/210c5117-6d27-48e1-9453-c715d06f8cb9)

### Expected Behavior

No Ts Error

### Actual Behavior

No TS error when importing extensions

### Error Message & Stack Trace

```bash
I think TS error is showing because the built 'fabric/dist-extensions/index.d.ts' file has

export * from './fabric';
//# sourceMappingURL=index.d.ts.map
```

**Comment by asturur** [comment]
Thanks for reporting this, i ll look into this asap.

**Comment by asturur** [comment]
ok i found it. I can't really bend tsc to put the files where i want, they are just in a different folder and i didn't notice.
I m fixing it and publishing a patch

**Comment by asturur** [comment]
6.4.1 should be out in minutes
