### ISSUE TITLE
[Bug]: Unable to interact when dynamically creating a canvas

### ISSUE THREAD

**Issue by overdev-l** [fabricjs/fabric.js#10119]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

20.15.1

### Link To Reproduction

https://codesandbox.io/p/devbox/yx4xrf

### Steps To Reproduce

1. Setting the background
2. Add text
3.Text cannot be selected for dragging or zooming, nor can it be edited

### Expected Behavior

After adding an element it can be selected and repositioned and scaled, and for text it can be edited.

### Actual Behavior

<img width="728" alt="image" src="https://github.com/user-attachments/assets/a9fbd549-3aa7-4a47-80b3-3a4b4dbc9487">

### Error Message & Stack Trace

```bash
none
```

**Comment by asturur** [comment]
See if you can see my forked codepen
https://codesandbox.io/p/devbox/fabric-forked-vrx6fg

Don't handle the canvas element directly, but after you initialize a fabric Canvas on top of it, just handle it's own container.

With your current code you are removing the interactivity layer from the fabric canvas
