### ISSUE TITLE
[Bug]: Create a custom control whose corner size is not yet effective

### ISSUE THREAD

**Issue by xiaoli1999** [fabricjs/fabric.js#10111]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

18.19.0

### Link To Reproduction

https://

### I'm sorry, I don't have a good grasp of the sandbox environment, so I can only submit the issue in this form

config.ts
```ts
export const controlDefault: any = {
    transparentCorners: false,
    cornerStrokeColor: '#79bbff',
    cornerColor: '#79bbff',
    cornerStyle: 'rect',
    cornerSize: 36,
    borderScaleFactor: 8,
    borderColor: '#79bbff',
    padding: 0,
    mtrOffsetY: -80
};
```

```ts
fabric.Object.prototype.set(props.control);

const size = 80

    /* 自定义删除控件 */
    const delImgElement = document.createElement('img')
    delImgElement.src = new URL('./icons/delete.png', import.meta.url).href

    const renderDeleteIcon = (ctx:any, left:any, top:any, styleOverride:any, fabricObject:any) => {
        ctx.save()
        ctx.translate(left, top)
        ctx.rotate(fabric.util.degreesToRadians(fabricObject.angle))
        ctx.drawImage(delImgElement, -size / 2, -size / 2, size, size)
        ctx.restore()
    }

    console.log(fabric.Control)

    fabric.Object.prototype.controls.deleteControl = new fabric.Control({
        x: 0.5,
        y: -0.5,
        offsetY: -size,
        offsetX: size,
        cursorStyle: 'pointer',
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        mouseUpHandler: deleteControlHandel,
        render: renderDeleteIcon,
        cornerSize: size,
    })

```

### Expected Behavior

The expectation is to delete the interaction size of the control and use the current configuration, which means that the entire control can interact and click

[
![微信图片_20240830174023](https://github.com/user-attachments/assets/ad7b5abf-46a6-41bf-a05d-06df979c9596)

### Actual Behavior

In fact, the custom control uses the default control size configured by the control. Assuming the custom control is 100 * 100 and the default control size is 20, the behavior is that interaction can only be clicked within the 20 * 20 area of the custom control.

![微信图片_20240830174436](https://github.com/user-attachments/assets/13613b3c-2856-4057-8b8a-94be2bd339ad)

**Comment by asturur** [comment]
You have specific control sizes you can change that are on the single control.
```ts
  /**
   * Sets the length of the control. If null, defaults to object's cornerSize.
   * Expects both sizeX and sizeY to be set when set.
   * @type {?Number}
   * @default null
   */
  sizeX = 0;

  /**
   * Sets the height of the control. If null, defaults to object's cornerSize.
   * Expects both sizeX and sizeY to be set when set.
   * @type {?Number}
   * @default null
   */
  sizeY = 0;
```

does this help?

**Comment by xiaoli1999** [comment]
> ```ts
> sizeX = 0
> ```

Thank you very much. I have used the method you provided and the interaction area has become normal.

```ts
fabric.Object.prototype.controls.deleteControl = new fabric.Control({
        x: 0.5,
        y: -0.5,
        offsetY: -size,
        offsetX: size,
        cursorStyle: 'pointer',
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        mouseUpHandler: deleteControlHandel,
        render: renderDeleteIcon,
        cornerSize: size,
        sizeX: size,
        sizeY: size
    })
```

I noticed that this issue occurs when the size of custom controls is different from the default controls
```ts
const defaultSize = 20
const size = 80

fabric.Object.prototype.controls.deleteControl = new fabric.Control({
        x: 0.5,
        y: -0.5,
        cornerSize: size,
    })
```

If the dimensions are consistent, it is normal
```ts
const defaultSize = 20
const size = 20

fabric.Object.prototype.controls.deleteControl = new fabric.Control({
        x: 0.5,
        y: -0.5
        cornerSize: size,
    })
```
