### ISSUE TITLE
[Bug]: Percentage gradient not working with fabric.Text

### ISSUE THREAD

**Issue by kcap** [fabricjs/fabric.js#10110]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/dornhq4L/

### Steps To Reproduce

1. Create gradient with percentage units (or gradient with pixel units and gradientTransform)
2. Add gradient to text object

### Expected Behavior

Gradient fill is visible

### Actual Behavior

Fill not visible

**Comment by kcap** [comment]
> I m reiterating that 5.x is not supported anymore.
> 
> But apart from that, what is broken in your fiddle?
> 
Oh sorry, this error appears in an older version of chrome ( 109.0.5414.168, now unsupported)
![image](https://github.com/user-attachments/assets/992ff5f1-2859-4991-8576-85cc779cfc28)

I check in latest version of chrome, it's ok

**Comment by asturur** [comment]
Yes there is an open issue for that, also pinned.
Chrome move fast and sometimes break stuff that i can't fix.
