### ISSUE TITLE
[Bug]: fabric/node toDataURL does not export Text objects to image

### ISSUE THREAD

**Issue by willdochnur** [fabricjs/fabric.js#10112]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.3.0

### In What environments are you experiencing the problem?

Node.js

### Node Version (if applicable)

20.0.0

### Link To Reproduction

https://codesandbox.io/docs/learn/sandboxes/your-first-sandbox#opening-a-github-repository-as-a-cloud-sandbox NOT FOUND! 404

### Steps To Reproduce

```
import { Point, StaticCanvas } from "fabric/node";
import { writeFileSync } from "fs";

const content = {
      version: "5.4.0",
      objects: [
        {
          type: "rect",
          version: "5.4.0",
          originX: "left",
          originY: "top",
          left: 22679.69,
          top: -5290.75,
          width: 5.01,
          height: 18.88,
          fill: "#ffcc00",
          stroke: "#000000",
          strokeWidth: 0.05,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 1941.24,
          scaleY: 2395.63,
          angle: 90,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          rx: 0,
          ry: 0
        },
        {
          type: "text",
          version: "5.4.0",
          originX: "left",
          originY: "top",
          left: -9809.91,
          top: -9327.34,
          width: 5047.34,
          height: 2267.64,
          fill: "rgba(0,0,0,1)",
          stroke: "",
          strokeWidth: 1,
          strokeDashArray: null,
          strokeLineCap: "butt",
          strokeDashOffset: 0,
          strokeLineJoin: "miter",
          strokeUniform: false,
          strokeMiterLimit: 4,
          scaleX: 3.65,
          scaleY: 3.91,
          angle: 0,
          flipX: false,
          flipY: false,
          opacity: 1,
          shadow: null,
          visible: true,
          backgroundColor: "",
          fillRule: "nonzero",
          paintFirst: "fill",
          globalCompositeOperation: "source-over",
          skewX: 0,
          skewY: 0,
          fontFamily: "sans-serif",
          fontWeight: "bold",
          fontSize: 2006.76,
          text: "TEXT",
          underline: false,
          overline: false,
          linethrough: false,
          textAlign: "left",
          fontStyle: "normal",
          lineHeight: 1.16,
          textBackgroundColor: "",
          charSpacing: 0,
          styles: [],
          direction: "ltr",
          path: null,
          pathStartOffset: 0,
          pathSide: "left",
          pathAlign: "baseline"
        }
      ]
    };
    const canvas = await new StaticCanvas(null, {
      width: 200,
      height: 200
    }).loadFromJSON(content);

    // center canvas
    canvas.zoomToPoint(new Point({ x: 100, y: 100 }), 0.004410213747205609);

    writeFileSync(
      "file.png",
      Buffer.from(
        canvas
          .toDataURL({ multiplier: 1, format: "png" })
          .replace("data:image/jpeg;base64,", "")
          .replace(/^data:image\/png;base64,/, ""),
        "base64"
      )
    );
```

### Expected Behavior

Like defined there is a text object which should exported to image ...

![image832](https://github.com/user-attachments/assets/f9fbb763-85d6-4daa-a286-87dd8b16249c)

### Actual Behavior

... but it does not.

![image](https://github.com/user-attachments/assets/a4ca3e3b-78b6-4c12-9e4a-a384e800c819)

**Comment by gloriousjob** [comment]
You're trying to use a 5.4 json export in a 6.0 canvas. Some things might happen to work but I don't think compatibility is promised (and text had some overhauls from my understanding). You should generate a new json export in 6.0 and then load that.

**Comment by asturur** [comment]
JSON exports should be compatible imho, we have been careful with that a lot

**Comment by asturur** [comment]
Look this is how it loads in browser for me on 5.x in fabricjs.com

<img width="574" alt="image" src="https://github.com/user-attachments/assets/ee24f192-38a2-4ee4-872a-43c83729fd2f">

I can't verify and i wont have time to do it myself, but for now i m blaming the font size of 2000.
I don't see a reason why this should have broken between fabric 5 and 6.
Did it ever work for you? with fontSize so large?

**Comment by willdochnur** [comment]
@asturur Firstly, your image is correct. The text has an offset and it is not centered like in my image.

Because of your hint about font size i just simplified content and tested a bit around with both versions 5.4.0 and 6.3.0 in backend and got this image exported:

![file](https://github.com/user-attachments/assets/6ddfcdac-a9e8-4119-a976-feb9681dda1e)

Is it possible that there is something missing in my Dockerfile what is required to produce texts correctly in canvas?
```
FROM minio/mc:RELEASE.2022-12-13T00-23-28Z

FROM node:20-alpine
COPY --from=0 /bin/mc /bin/mc
WORKDIR /app
ADD app .

# see https://github.com/Automattic/node-canvas/issues/866
RUN apk add --no-cache --virtual .build-deps \
    build-base \
  g++ \
  cairo-dev \
  jpeg-dev \
  pango-dev \
  giflib-dev \
    && apk add --no-cache --virtual .runtime-deps \
    cairo \
  jpeg \
  pango \
  giflib
```

**Comment by willdochnur** [comment]
I just installed additional dependency called `ttf-dejavu` and now i get my text in my test export.

**Comment by willdochnur** [comment]
I updated my dev-Dockerfile and everything works fine now (even with (my) gigantic font sizes):
```
FROM minio/mc:RELEASE.2022-12-13T00-23-28Z

FROM node:20-alpine
COPY --from=0 /bin/mc /bin/mc
WORKDIR /app
ADD app .

# see https://github.com/Automattic/node-canvas/issues/866
RUN apk add --no-cache --virtual .build-deps \
    build-base \
	g++ \
	cairo-dev \
	jpeg-dev \
	pango-dev \
	giflib-dev \
    && apk add --no-cache --virtual .runtime-deps \
    cairo \
	jpeg \
	pango \
	giflib \
	ttf-dejavu
```

Thank you for your responses and help guys!

**Comment by willdochnur** [comment]
Thank you for your responses and help guys!

**Comment by asturur** [comment]
if you use cairo and fabric on node maybe is safer to have a larger distro like ubuntu-latest.
It can be tricky to debug those things indeed. Happy you solved

**Comment by willdochnur** [comment]
@asturur Ok, thanks for the advice, but what exactly is the reason for that? Currently i think ubuntu-latest just contains much more dependencies by default. Do you know about more dependencies which could be missing in my environment?

**Comment by asturur** [comment]
The reason is that is easier to find the libraries, the compile tools, fonts are preinstalled. Just that. Is easier to verify everything works. At least keep an image around handy to make a test when something goes wrong on node alpine
