### ISSUE TITLE
[Bug]: Incorrect positioning of rotate control (MTR) on negative height values

### ISSUE THREAD

**Issue by SupremeDeity** [fabricjs/fabric.js#10131]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Firefox, Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/7kf659vs/10/

### Steps To Reproduce

1. Set height to negative
2. The mtr icon is inside the bounding

### Expected Behavior

The MTR icon should be outside the bounding box

### Actual Behavior

![image](https://github.com/user-attachments/assets/50f476e3-a156-456a-83da-098cd155ff04)

**Comment by asturur** [comment]
Maybe this bug can be fixed, but there may be others.
Width and height are supposed to be positive numbers.
I can update the documentation

**Comment by SupremeDeity** [comment]
@asturur yes ik they are supposed to be positive numbers, i just found out that it works as a easy way to keep the left, top fixed when doing shape drawing.

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/pull/8430
Check if in this PR there is something that helps you having a more integrated draw shape without too much workaronds.
negative width and negative height shouldn't be there.

I understand that when you draw from right to left or from bottom to top you have an issue.
The general logic is to keep track of which direction you moved and keep the position steady with set position by origin.

Maybe we can rework that PR and merge it at some point now that we have the extension bundle

**Comment by SupremeDeity** [comment]
@asturur oh that looks nice. Maybe I'll go take a look at that. Currently with the zoom method from the fabric tutorials site, my text and shapes get a bit blurry even with canvas reference and retinaScaling. Maybe I'll find a solution to both this width and height problem and that blur problem in that PR.
