### ISSUE TITLE
[Bug]: Controls not updating when programmatically changing object's scale

### ISSUE THREAD

**Issue by tbrown1979** [fabricjs/fabric.js#10161]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-rc4, 6.4.2

### In What environments are you experiencing the problem?

Firefox, Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/5hfsd8Ln/4/

### Steps To Reproduce

1. Make an object that has controls (just the defaults will work). 
2. Ensure it is selected as the active object.
3. Scale it, without using the controls. 
4. Notice that the object's scale will increase, the border will expand but the controls will stay in the same place.
5. Moving, scaling, or otherwise doing something on the canvas with the object will update things to look appropriate.

### Expected Behavior

This is how it worked before changes: https://jsfiddle.net/8z94w1eo/1/

I expect that when updating the scale of an object that the controls will adjust accordingly with the scale. Sometime between 5.3.1 and the latest version this behavior changed. I am using `6.0.0-rc4` locally and this behavior is present. My fiddle example uses `6.4.2`. Before upgrading my local project to `6.0.0-rc4` this worked as expected. This fiddle demonstrates the behavior beforehand: https://jsfiddle.net/8z94w1eo/1/

If this is expected behavior I'm not entirely sure how to get my desired behavior anymore. It's possible I'm updating the scale inappropriately and that is my issue, instead of a bug. I decided to report as a bug because this behavior changed sometime between 5->6 and I didn't see anything reported about it. 

### Actual Behavior

![CleanShot 2024-09-16 at 16 32 08](https://github.com/user-attachments/assets/fb619a8a-ede1-4e38-b968-55fcefe938ff)

Is what it looks like after the scale is increased by `scaleX = scaleX * 1.2` 

I would like it to look like: 

![CleanShot 2024-09-16 at 16 37 47](https://github.com/user-attachments/assets/c62df43a-2511-4c81-bfdb-52a81913e01a)

**Comment by asturur** [comment]
Read this document here, especially the first point.
http://fabricjs.com/fabric-gotchas

The way we render controls changed.
Before if you changed scale in that way controls would be correctly visible but unselectable ( because they are on a different position internally )
Now they are selectable but displayed in the wrong position.


When you change the size of an object with code, you have to update the coordinates as in the example of the document.

**Comment by asturur** [comment]
If that does not fix it, then there is a bug.

**Comment by tbrown1979** [comment]
@asturur Thank you! The method to `setCoords()` seems to resolve the problem after scaling, example fiddle here: https://jsfiddle.net/az8e69ob/
