### ISSUE TITLE
update to 1.4.0 -> button's click() event doesn't work

### ISSUE THREAD

**Issue by abit** [fabricjs/fabric.js#1017]
After update to 1.4.0 all the button's click() event stopped to work. Does it somehow relate to the update?

**Comment by TimmNL** [comment]
Hey, I don't know if this problem has been fixed, or habit found a solution for this problem, but I have the same problem right now.
The root.click catches my "click" event and manipulates it. This way my buttons won't work anymore either.
I'm also wondering why fabric has to keep track of the dom and not just the canvas.
Thanks in advance!
