### ISSUE TITLE
[Bug]: ClipPath does not work like 5.x

### ISSUE THREAD

**Issue by designlook** [fabricjs/fabric.js#10181]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Microsoft Edge

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/hb68a41L/

### Steps To Reproduce

1. Go to https://jsfiddle.net/hb68a41L/

### Expected Behavior

ClipPath not working. 

This is same code works in Fabricjs 5.x. You can see demo of it working in 5.x here
https://jsfiddle.net/scottyu/dm5sv3z9/

### Actual Behavior

ClipPath not working

### Error Message & Stack Trace

```bash
No errors
```

**Comment by asturur** [comment]
Hi @designlook, take care that loading an svg and an image are async.
If the image loads before the svg, you are setting an undefined as the clipPath.
This is a javascript async issue more than a fabricjs one.
Try to load the image inside the then function of the svg or use async await for a more straight forward code

**Comment by designlook** [comment]
You are right. I updated it to await and here's updated demo

https://jsfiddle.net/scottyu/wevah34u/2/
