### ISSUE TITLE
Line object coordinates are wrong

### ISSUE THREAD

**Issue by raichu** [fabricjs/fabric.js#1018]
With the new changes (originX and originY), the behavior of all objects is: top/left is the actual top-left coordinates of the objects. For Line objects, they still get a mysterious extra width/2 and height/2 offset when being displayed:

http://jsfiddle.net/3Anj2/1/

(try resizing it vertically BTW!)

Setting left and right to 0 explicitly seems to solve this problem. However, this probably shouldn't be required, since this problem appears when loading an SVG with lines as well.

When they are placed inside a Group, this get even bizarre. Furthermore, SVG output shows something completely different.

**Comment by Gefrierbrand** [comment]
I'm also experiencing a strange line offset even with origin set to center:
http://jsfiddle.net/oezqod01/
I'm not sure whether this is related to this bug or if i'm doing it wrong...

**Comment by asturur** [comment]
I don-t know how your jFiddle works, but please update fabricJs to latest version first, you are  still using 1.4.0.

**Comment by Gefrierbrand** [comment]
I've updated the version to 1.4.13: http://jsfiddle.net/oezqod01/1/
The issue remains. Just click somewhere in the canvas and then click somewhere else to create a line.
The the line position is slightly offset from the cursors position.

**Comment by asturur** [comment]
didn't you notice that the topleftmost coordinates you can get is 8,8?
So every line is getting an offset of 8,8.

look with this is better
http://jsfiddle.net/oezqod01/3/

Check how drawingMode in the basic brush class is obtaining coordinate from the pointer to solve your issue.

**Comment by new299** [comment]
My apologies, as this may not be the best place to comment. But this, or a similar issue, seems to be present in the CDN verison linked from the main website (1.4.0). It could be worth updating the CDN linked on the main website to 1.4.13 so new users won't encounter this issue.

**Comment by asturur** [comment]
This was an application design fault.
Yes lot of fixes happened from 1.4.0 to 1.4.13 
1.4.0 is the latest stable release, even if this 1.4.13 may look like more stable.
We are trying to get 1.5.0 soon, and that will be linked for sure.
