### ISSUE TITLE
[Bug]: Textbox rounds width when resizing, very obvious when zoomed in.

### ISSUE THREAD

**Issue by Soldier-B** [fabricjs/fabric.js#10180]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/p/devbox/fabric-vanillajs-sandbox-forked-tld2gt

### Steps To Reproduce

1. Create a canvas
2. Add an instance of Textbox to the canvas
3. Zoom in to canvas
4. Resize textbox with horizontal sizing controls

### Expected Behavior

The textbox should resize smoothly as it does when using the vertical sizing controls.

### Actual Behavior

The textbox seems to round it's width, so there is a noticeable "snapping" effect when resizing while zoomed in.

**Comment by asturur** [comment]
```
      newWidth = Math.ceil(
        Math.abs((localPoint.x * multiplier) / target.scaleX) - strokePadding,
      );
```

There is Math.ceil there indeed.
I m not sure why to be honest, you could try to open a PR to remove it and we can see what happens.

**Comment by Soldier-B** [comment]
@asturur Ok, thank you. I'll do that.
