### ISSUE TITLE
Custom group inherited from the group, and the bug of the custom layout type.

### ISSUE THREAD

**Issue by zhe-he** [fabricjs/fabric.js#10198]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/p/devbox/jfhyqr?file=%2Fsrc%2Ftest.tsx%3A27%2C25

### Steps To Reproduce

1. Create a custom layout type.
2. Create a custom group.
3. Custom group applies custom layout type.
4. Call the fromObject of the custom group, get object A, and print the layout type of A.

### Expected Behavior

The layout type of A is fit-content, not a custom layout type.

### Actual Behavior

The layout type of A should be a custom layout type.

**Comment by zhe-he** [comment]
The fromObject method of the group will create a NoopLayoutManager, which uses the data exported last time and does not recalculate during initialization. However, this will keep the layoutManager passed to the constructor always having a value.

**Comment by asturur** [comment]
The layoutManager you build should be able to serialize/deserialize.
When doing 'toObject' and 'fromObject' the layout manager type is checked and respected:

```
        const layoutClass = classRegistry.getClass<typeof LayoutManager>(
          layoutManager.type,
        );
```

Did you register your layout manager with the class registry and did you give it a different type from the original one?

**Comment by asturur** [comment]
i see how you trigger the bug. I would argue the data is kind of malformed because is missing the information.

from your class the minimal data i can get is this:

```json
{"type":"CustomGroup","version":"6.0.2","left":0,"top":0,"layoutManager":{"type":"layoutManager","strategy":"custom-layout"},"objects":[]}
```

**Comment by zhe-he** [comment]
> i see how you trigger the bug. I would argue the data is kind of malformed because is missing the information.
> 
> from your class the minimal data i can get is this:
> 
> ```json
> {"type":"CustomGroup","version":"6.0.2","left":0,"top":0,"layoutManager":{"type":"layoutManager","strategy":"custom-layout"},"objects":[]}
> ```

I did this intentionally (not passing the layoutManager when calling fromObject). The issue I want to highlight is that when I don't override the `fromObject` method of the Custom Group, the built-in fromObject method of Fabric Group secretly adds a NoopLayoutManager, preventing me from using the default layoutManager in the constructor(Custom Group).

**Comment by zhe-he** [comment]
I understand that the source code is written this way to optimize the initialization so that the group does not need to calculate its width and height through child elements. I believe this performance optimization should give way to user usability; it could be left unoptimized (because with this optimization, users need to rewrite their custom group's fromObject). I also found that Textbox calculates height during initialization, and FabricText calculates width during initialization. Their fromObject methods do not have such optimizations, so why is such an optimization made specifically for groups?

I want to change this piece of code in the source code to look like this.

[source](https://github.com/fabricjs/fabric.js/blob/master/src/shapes/Group.ts#L686-L718)
```ts
// static fromObject() {
    // ...
    const group = new this(objects, {
        ...options,
        ...hydratedOptions,
        layoutManager: new NoopLayoutManager(),
      });
      if (layoutManager) {
        const layoutClass = classRegistry.getClass<typeof LayoutManager>(
          layoutManager.type,
        );
        const strategyClass = classRegistry.getClass<typeof FitContentLayout>(
          layoutManager.strategy,
        );
        group.layoutManager = new layoutClass(new strategyClass());
      } else {
        group.layoutManager = new LayoutManager();
      }
      group.layoutManager.subscribeTargets({
        type: LAYOUT_TYPE_INITIALIZATION,
        target: group,
        targets: group.getObjects(),
      });
      group.setCoords();
      return group;
// }
```

after:
```ts
// static fromObject() {
    // ...
            let layoutM;
            if (layoutManager) {
                const layoutClass = classRegistry.getClass<typeof LayoutManager>(layoutManager.type);
                const strategyClass = classRegistry.getClass<typeof LayoutStrategy>(layoutManager.strategy);
                layoutM = new layoutClass(new strategyClass());
            } else {
                layoutM = new LayoutManager();
            }

            const group = new this(objects, {
                ...options,
                ...hydratedOptions,
                layoutManager: layoutM,
            });
            return group;
// }
```

**Comment by asturur** [comment]
Is not an optimization issue, the objects are already with an applied layout when you restore them, so the noop layout manager is kind necessary.
FromObject works with data obtained from toObject, that is the constrain we have. What is the issue for you to export also the layout manager type?

This stuff is hard to make work in all conditions/situations.

**Comment by zhe-he** [comment]
I exported the type of the layout manager, but I found that the tests do not behave as I expected; they are faking data to construct objects, which is why this issue arose. 
Since you believe this is not a problem, I will close it.

**Comment by asturur** [comment]
Is not that i do not believe this is not an issue.
If you think there is an issue in the tests point it out it should be corrected.

**Comment by zhe-he** [comment]
I made a judgment without changing the previous logic, and I submitted a PR specifically for this situation so that users no longer need to override fromObject.

**Comment by asturur** [comment]
But where is the bug?
When the group is initialized fromObject it can't run the layoutManager on serialized object, it hast to first initialize and then can run.
So the noopLayoutManager has to stay.
What i m saying is that the fromObject requires valid data and the data you are passing is not valid.

**Comment by zhe-he** [comment]
I wrote an example that follows the rules; you can comment out or uncomment line 55 to see the difference.

[demo](https://codesandbox.io/p/devbox/d2wjg3?file=%2Fsrc%2Ftest.tsx%3A54%2C54)

**Comment by asturur** [comment]
If i see your example:

```
    const b = new LayoutManager(new ToTopLeftLayout());
    const frame = new Frame([], {
      left: 50,
      top: 50,
      width: 100,
      height: 100,
      originX: "center",
      originY: "center",
      LayoutManager: a,
    });
    canvas.add(frame);
    frame.add(red);
    frame.add(yellow);
    canvas.renderAll();

    const data = frame.toObject();
    data.left += 200;
    data.layoutManager = b.toObject(); <--- assign toTopLeft in data
    (async () => {
      //
      // Open it and shield it to see the difference.
      // Frame.fromObject = Frame.overrideFromObject;
      const f = await Frame.fromObject(data);
      console.log(f.layoutManager.strategy.constructor.type) <--- logging toTopLeft after restore
      canvas.add(f);
      canvas.renderAll();
    })();
    ```
    
    Is working without the need of changing the fromObject function

**Comment by asturur** [comment]
If you want to remove the data from group you are free to do so, but that is not the fabricJS supported group, so there is no bug. Subclassing is there for a reason and doesn't have to be partial to be ok. If you need something that deviate much from the standard Group write your own fromObject function.
