### ISSUE TITLE
Support SVG as an overlay image

### ISSUE THREAD

**Issue by Reggino** [fabricjs/fabric.js#102]
When constructing a new fabric.Canvas using 

```
var fabricCanvas = new fabric.Canvas('canvas', {
    'overlayImage': '/path/to/some/local/Image.svg' 
});
```

the script works fine, but it is no longer possible to use 

```
fabricCanvas.toDataURL('png')
```

This throws a Security Error in both Chrome and Firefox.

Adding the SVG using loadSVGFromURL() does seem to work around this problem.

**Comment by RoelKint** [comment]
still not implemented

**Comment by asturur** [comment]
there is nothing to implement here.
Either load the SVG as a normal image, and use it as overlay, or put the SVG in a group shape by shape and use it as an overlay
