### ISSUE TITLE
[Bug]: 'added' fires when an object is added to a group via `.add` but not when added via group constructor array.

### ISSUE THREAD

**Issue by drinkspiller** [fabricjs/fabric.js#10203]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

(2 links, see below)

### Steps To Reproduce

1. Create a fabric.Rect instance (or other fabric.FabricObject)
2. Define an `on('added', ()>{})` handler for it 
3. Add it to a fabric.Group (and add the Group to the canvas and `renderAll`).

### Expected Behavior

A defined `on('added', ()>{})` handler will fire whether the FabricObject on which the handler is defined is added to a Group via `.add` or is added to the group when via the group's `objects` argument when the Group is constructed. 

### Actual Behavior

(following reproduction steps above)

If the Rect is added to the group via `.add`, the `added` event fires. ([demo](https://codepen.io/drinkspiller/pen/yLmgOZe?editors=0011)). 

If the Rect is added to the group via the group's `objects` argument when the Group is constructed, the `added` event does not fire ([demo](https://codepen.io/drinkspiller/pen/YzmNwbZ)).

**Comment by drinkspiller** [comment]
(friendly ping on this)

**Comment by asturur** [comment]
I know this is 2 months old now and pointless.
I added this doc page for events
https://fabricjs.com/docs/events/

I do think the added event is pointless in general in fabricJS and i m not sure it should fire at all in general, i tried to explain it in that doc between normal documentation.

What was your case for this event? can you point it out?

**Comment by drinkspiller** [comment]
Alas, I can't recall why I needed it at the time.
