### ISSUE TITLE
[Bug]: StaticCanvas.toJSON() is an alias to toObject() but doesnt take argument `propertiesToInclude` in 6.4.3

### ISSUE THREAD

**Issue by tneullas** [fabricjs/fabric.js#10220]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.4.3

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

20.11.0

### Steps To Reproduce

1. Call StaticCanvas.toJSON(['lockMovementX'])

### Expected Behavior

Expect corresponding properties to be exported

### Actual Behavior

Nothing is exported because it is now an alias to toObject() without transferring `propertiesToInclude` parameter.

### Error Message & Stack Trace

```bash
Get ts error :  Expected 0 arguments, but got 1.ts(2554)
```

**Comment by asturur** [comment]
ToJSON is a delegate is not an alias.
ToJSON is a javascript reserved method and works in that way, it takes specific arguments that come from JSON.stringify.

Have a look here and look the example of BigInt
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

**Comment by tneullas** [comment]
Thanks for the explanation @asturur , I did not know it was a reserved method.  
Though jsdoc, documentation and examples are confusing about the subject : 
http://fabricjs.com/docs/fabric.Canvas.html#toJSON

**Comment by asturur** [comment]
Yes those are the 5.3.1 docs, the newer i think have been corrected.

https://fabricjs.github.io/api/classes/canvas/#tojson

the new doc has a better description but still a wrong example.

**Comment by tneullas** [comment]
Oh, didnt know about new docs, thanks for the link and the times :)
