### ISSUE TITLE
[Bug]: zoomToPoint ts is error

### ISSUE THREAD

**Issue by vaynevayne** [fabricjs/fabric.js#10224]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### Node Version (if applicable)

None

### Link To Reproduction

https://stackblitz.com/edit/vitejs-vite-eyhjps?file=src%2FFabric.tsx

### Steps To Reproduce

![image](https://github.com/user-attachments/assets/680e1311-d537-459a-a3e9-6c0cc772ad54)

![image](https://github.com/user-attachments/assets/9ff907c6-5b89-4177-a719-9c326200fcad)

### Expected Behavior

Passing x y should be enough

### Actual Behavior

error

**Comment by vaynevayne** [comment]
second ts error 
````jsx
canvasRef.current?.on('mouse:wheel', onMouseWheelHandler);
   const onMouseWheelHandler = (opt: TPointerEventInfo) => {
      console.log('onMouseWheelHandler', opt.e.deltaY);

    };
```

![image](https://github.com/user-attachments/assets/9cb5c00e-d900-4481-9f6a-d36c9f6d796b)

**Comment by asturur** [comment]
For the first point the function requires a point not an object with x and y. You have to use `new Point(x, y)`.

For the second maybe we need to fix the types to clarify is a mousewheel event

**Comment by zhe-he** [comment]
It seems there is no issue; this problem should be closed.

<img width="519" alt="image" src="https://github.com/user-attachments/assets/18c7f475-f737-417a-bbb0-a20f81379613">

**Comment by asturur** [comment]
Yes looks like his own function has a strict type on TPointer event without the WheelEvent spec.
Thanks

**Comment by vaynevayne** [comment]
How should the type of each event be written? Is there a more uniform alias?

**Comment by asturur** [comment]
For the mousewheel event:
`TPointerEventInfo<WheelEvent>` should be the correct one.

**Comment by zhe-he** [comment]
> How should the type of each event be written? Is there a more uniform alias?

When binding events, hover the mouse over 'e', and it will show you which types are available.

Here all the e's are defined：
https://github.com/fabricjs/fabric.js/blob/master/src/EventTypeDefs.ts

**Comment by vaynevayne** [comment]
mosue:down mouse:up Not applicable mouseEvent,
I mean normalized, supporting the usage Ivent <'mouse:up'>, rather than trying it one by one

**Comment by asturur** [comment]
Is not that you have to try one by one, when you start writing your function you get the suggestion right there:

<img width="769" alt="image" src="https://github.com/user-attachments/assets/b756b836-2e85-4114-b4ba-648add57fbad">

After you have your suggestion you can move your handler out of there and type it manually just copying from the suggestion.
