### ISSUE TITLE
[Bug]: Touch interaction cleanup causes unhandled exception when canvas is disposed

### ISSUE THREAD

**Issue by Smrtnyk** [fabricjs/fabric.js#10248]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions

### Description

First of all sorry for not having a repro with direct link but this can happen on any touch device using fabric.
It is about fast user interaction on touch devices following with the disposal of the canvas.

During canvas disposal within 400ms after a touch interaction ends, an error occurs due to a pending timeout attempting to add a mouse event listener. The timeout is set in `_onTouchEnd` to handle touch-to-mouse event transition but isn't cleaned up during canvas disposal.
Reproduction:

1. On touch device, interact with canvas
2. Dispose canvas within 400ms after touch ends
3. Error occurs as timeout tries to add event listener to disposed canvas

```typescript
// In Canvas.ts, timeout is set but never cleaned up during disposal
private _onTouchEnd(e: TouchEvent) {
    if (e.touches.length > 0) return;
    // ...
    this._willAddMouseDown = setTimeout(() => { <-- this here
        addListener(this.upperCanvasEl, `${eventTypePrefix}down`, this._onMouseDown);
    }, 400);
}
```

Should we clean this timer up in here
```typescript
removeListeners() {
    if (this._willAddMouseDown) {
        clearTimeout(this._willAddMouseDown);
        this._willAddMouseDown = 0;
    }
    // existing cleanup...
}
```
If we called `canvas.dispose()` I guess we don't want anymore timer to execute

I am talking about this here
https://github.com/fabricjs/fabric.js/blob/7b88c416db49ad0116c16d60af9471c6637ce7ad/src/canvas/Canvas.ts#L698

### Current State

I am not sure if I have some nice workaround for this

for now I am thinking to do it in my destroy method

```typescript
async destroy(): Promise<void> {
        this.eventManager.destroy();
        this.zoomManager.destroy();
        this.touchManager.destroy();
        // This is an ugly hack to work around the fact that fabric does not clear the mouseDownTimeout
        // during dispose. This causes an exception to be thrown if the canvas is disposed while the mouse
        // is down. Reported this issue https://github.com/fabricjs/fabric.js/issues/10248
        // @ts-expect-error -- private property
        // eslint-disable-next-line no-underscore-dangle -- fabric naming
        const mouseDownTimeout = this.canvas._willAddMouseDown;
        if (mouseDownTimeout) {
            clearTimeout(mouseDownTimeout);
            // @ts-expect-error -- private property
            // eslint-disable-next-line no-underscore-dangle -- fabric naming
            this.canvas._willAddMouseDown = 0;
        }
        await this.canvas.dispose();
    }
```

**Comment by asturur** [comment]
Hopefully this fixes it

**Comment by Smrtnyk** [comment]
Thanks @asturur 
Do you plan to create a release any time soon?

**Comment by asturur** [comment]
If you have time to verify the fix i ll make a release as soon as it is merged.
I merged a couple of other changes recently one of which is a bit large on the clipPath rendering so i was hesistant to release

**Comment by Smrtnyk** [comment]
yeah I checked and I don't see the exception anymore
