### ISSUE TITLE
[Bug]: After adding an element to the canvas in Fabric v6, the element can only be moved and cannot be scaled or rotated

### ISSUE THREAD

**Issue by coderyqy** [fabricjs/fabric.js#10255]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### Node Version (if applicable)

None

### Link To Reproduction

Below

### Steps To Reproduce

vue3: 
```
<canvas id="canvas" width="300" height="400"></canvas>
<img id="photoImg" :src="photo" alt="" />
```

const canvas = ref<Canvas>();

function drawCanvas() {
  let image = new FabricImage("photoImg");

  canvas.value = new Canvas("canvas", {
    backgroundImage: image,
    width: 300,
    height: 400,
  });

  // 计算缩放比例
  const scaleWidth = canvas.value.width / image.width;
  const scaleHeight = canvas.value.height / image.height;

  // 选择较大的缩放比例以覆盖整个画布
  const scale = Math.max(scaleWidth, scaleHeight);

  // 设置图片的缩放
  image.set({
    scaleX: scale,
    scaleY: scale,
  });

  // 创建一个长方形
  const rect = new Rect({
    top: 30, // 距离容器顶部 30px
    left: 30, // 距离容器左侧 30px
    width: 100, // 宽 100px
    height: 60, // 高 60px
    fill: "red", // 填充 红色
    hasControls: true, // 启用缩放控制点
    hasBorders: true, // 启用边框控制点
  });

  // 在canvas画布中加入矩形（rect）。add是“添加”的意思
  canvas.value.add(rect);

  canvas.value.setActiveObject(rect);

  //   重新渲染全部
  canvas.value.renderAll();
}

### Expected Behavior

Can scale and rotate

### Actual Behavior

![image](https://github.com/user-attachments/assets/9022757f-4557-4c70-9877-203be5440bbc)

### Error Message & Stack Trace

```bash
nothing
```

**Comment by smellyshovel** [comment]
Any updates here? I also have the same issue, here's the reproduction: https://stackblitz.com/~/github.com/smellyshovel/fabric-repro

1. Select the "Square" tool
2. Draw a square by holding the LMB
3. Select the "Selection" tool (the arrow)
4. Select the drawn square

It's possible to move it, but is impossible to scale/rotate it.

It's fixable, however, if you draw a second rectangle, then select them both (in a group). After that resizing and rotation are fixed for all the rectangles which were selected as a group.

What am I missing? The `shape.setCoords();` is in place, but it doesn't help really.

**Comment by smellyshovel** [comment]
I think I found the issue. At least for me it was related to storing the `canvas` as a Vue.js `ref` (which is a Proxy under the hood). Here's the related comment: https://github.com/fabricjs/fabric.js/issues/7485#issuecomment-1008334588.

Removing the `ref` and storing the canvas as just a plain JS variable solves the issue.

**Comment by neylwalecki** [comment]
Tks! You saved me! Claude code, Gemini and Codex, no AI was able to find this issue by themselves!
