### ISSUE TITLE
fabric.Path - Ability to create empty path object and add points as need be.

### ISSUE THREAD

**Issue by paulcanning** [fabricjs/fabric.js#1025]
Regarding my post on the Google Group (https://groups.google.com/forum/#!topic/fabricjs/o7xXp_TiF0s) I would like to request the ability to create an empty Path and add points one by one.

Currently, a Path has to be created with some path data (e.g. 'M 0 0') but we are unable to add additional points to the path.

An 'addPoint()' method would be perfect and I imagine would be welcome by many users.
##

**Comment by paulcanning** [comment]
Can I ask why this was removed from the 1.5.0 milestone?

**Comment by kangax** [comment]
Lack of resources :/ We're focusing on pulling in bugs foremost and considering that 1.5 is already way too late, this won't make it this time. Unless PR, of course...

**Comment by paulcanning** [comment]
Any update on this?

**Comment by asturur** [comment]
Not yet, is on the roadmap for me, and is  feature i like much, but having hard time keeping the bug count low and improving tests

**Comment by ShaMan123** [comment]
#7141 addresses most of this issues

**Comment by ShaMan123** [comment]
This use case should be covered by #7141.
It is stale.
Reopen if necessary and mention me and the related PR.
