### ISSUE TITLE
[Bug]: When objects are added to a group, their coordinates are recalculated relative to the group. This means that the positioning of objects within a group depends on the position of the group itself. If the center of the group does not have a coordinate of 0,0, this leads to incorrect display of control squares (control points) when moving or scaling the group.

### ISSUE THREAD

**Issue by Alexeyly** [fabricjs/fabric.js#10256]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://codepen.io/alexeyly/pen/yLmxgZL?editors=1010

### Steps To Reproduce

1. Add a frame
2. Add a square
3.Place a square in a frame
4.to scale (zoom) the canvas

### Expected Behavior

https://github.com/user-attachments/assets/6cc05276-ee96-44e3-bb04-ab409410a763

### Actual Behavior

https://github.com/user-attachments/assets/7186624a-3e63-4632-bd17-71057a31c1f3

**Comment by asturur** [comment]
In fabric 5 controls of object inside groups are not supported.
