### ISSUE TITLE
[Bug]: FabricJS 6.4.3 - Canvas not updating following a programatic change

### ISSUE THREAD

**Issue by RobHedley** [fabricjs/fabric.js#10262]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Firefox, Chrome, Safari, Opera, Microsoft Edge

### Node Version (if applicable)

None

### Link To Reproduction

https://codepen.io/hedlro/pen/poMNOZq?editors=0010

### Steps To Reproduce

1. Open the codepen Example
2. Observe the blank canvas with a grey rectangle and the words 'Printable Area'
3.Now click directly on the canvas and the t-Shirt image will appear that was added to the added at thew same time as the rectangle and the text

### Expected Behavior

The canvas loads showing all 3 assets - The background image, the grey box and the 'Printable Area text'.

### Actual Behavior

The Canvas is rendered showing only the grey rectangle and the 'printable area' text. The background image only shows once the user clicks on the canvas. This is a simple example of what I have found whilst using the latest version of Fabric JS (6.4.3, which is not available to select from the version list by the way).

I have created a T-Shirt customizer and I am having this issue when the user changes the colour of the T-Shirt. When the user clicks a new colour (using a separate component), a method is called that grabs the current canvas objects, find the background image by id, set the src of the FabricImage using '.setSrc()', waits for the change to complete then runs a renderAll(). 

This appears to have no effect on the canvas as nothing changes. However if you simply click on the canvas, it updates and shows the correct colour image as the background image. I have tried a number of steps to create a work around for this, programatically clicking the canvas, setting the focus to the canvas etc but this does not trigger the correct render of the canvas. The only way of getting it to update to match its current state is to manually click on it.

I have the same issue when I try to create a preview of the printed article by taking a copy of the background image and exporting the printable area as a base64 png and then rendering the copy back image and the masked print image as the top 2 images on the canvas, hence looking to the user that the canvas is showing the finished article. The same issue occurs where I click it and nothing changes until I manually click the canvas and then it updates and shows the correct canvas state.

### Error Message & Stack Trace

```bash
There are no errors report during this bug
```

**Comment by asturur** [comment]
This is a basic misconception of how images load in the browser and in javascript in general.
It has nothing to do with fabricjs.

```ts
              const testImgObj = new Image(500, 400)
              testImgObj.src = 'https://www.yaay.me/assets/img/MerchTSRoundFront.png';
              const backImg = new FabricImage(testImgObj, {
```

Doing this will create a new FabricImage with an empty image of 500 by 400 px.
assigning the src property of the image will at some point load the image content and change the content of the img html element, but when that happnes your react hooks and fabric canvas.renderAll are done and gone.

You need to wait for the image to load, using a promise.
You can use one of the utilities provided by fabricJS too.

**Comment by RobHedley** [comment]
Thanks for the pointer @asturur. I added a loadImage function to the codepen however the only way I could get the back image to display correctly was to put the renderAll into the promise then. If I put the FabricImage, fabricRect etc in the promise return function then nothing rendered. If I load the background image using the loadImage async function but keep the creation of the FabricImages, Fabric.Rect outside of the return so the process immediately and then run the renderAll in the promise return everything works. 

Obviously this is a huge hack as I am loading an image twice, once to use the actual image the other to fire the renderAll at the correct time.

This solution will allow me to move forwards with the development and I will revisit once the Version 6 documentation has been improved and expanded.

**Comment by asturur** [comment]
i still think the issue is a generic React/JS/handing an async flow in react and has nothing to do with fabric

```js
  useEffect(() => {
    async function loadEverything() {
            if (canvas){
              const img = await fabric.util.loadImage("https://www.yaay.me/assets/img/MerchTSRoundFront.png");
              const backImg = new FabricImage(img, {
                  id: 'backImage',
                  left: 0,
                  top: 0,
                  height: 500,
                  width: 600,
                  selectable: false,
                  hasControls: false,
                  hasBorders: false,
                  cornerStrokeColor: "#ff0098"
                  });
                //backImg.crossOrigin="anonymous"
                canvas.add(backImg);
                //canvas.setActiveObject(backImg);
                  
            
                  const rectbox = new Rect({
                    width: rectboxWidth,
                    height: rectboxHeight,
                    left: rectboxX,
                    top: rectboxY,
                    stroke: 'rgba(0,0,0,0.3)',
                    strokeWidth: 2,
                    fill: 'rgba(0,0,0,0)',
                    selectable: false,
                    hasControls: false,
                    hasBorders: false
                  });
          
                  canvas.add(rectbox);
                  
                  const recttext = new FabricText('Printable Area', {
                  fontSize: 14,
                  fontFamily: 'sans-serif',
                  left: 253,
                  top: 80,
                  fill: 'rgba(0,0,0,0.3)',
                  selectable: false,
                  hasControls: false,
                  hasBorders: false
                  });
                  
                  canvas.add(recttext);
                  canvas.requestRenderAll()
          }
    }
      loadEverything();
      }, [canvas])
```

This is how i would run that code.
Doesn't this code fix the issue?

You could also have added everything inside the promise then

**Comment by RobHedley** [comment]
Hey @asturur,

Thanks for the code above. I will give it a go using the loadImage util as that is where my issue lie I believe. I am using react import to load the image.

I did place everything in the promise return but it didn't solve the issue but I will try the load util with the async function to see if that alleviates the problem.

Thank you again.

Rob
