### ISSUE TITLE
[Bug]: Text in other languages renders differently on Windows and Mac.

### ISSUE THREAD

**Issue by niketaOptimumnbrew** [fabricjs/fabric.js#10272]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [x] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.4.2

### In What environments are you experiencing the problem?

Chrome, Safari

### Node Version (if applicable)

14.20.0

### Link To Reproduction

https://codesandbox.io/p/sandbox/q4vdtv

### Steps To Reproduce

1. Take one canvas json with text objects.
2. render that json on canvas.
3. verify canvas preview after json load.

### Expected Behavior

-should show same output in window chrome and mac chrome as well as safari browser.

Window chrome browser ( should show below output in all the browser of mac)
[
![image](https://github.com/user-attachments/assets/d5d2ad43-40e2-4a80-b1f3-1859e616b36e)
](url)

Note: Using same json for all browser.
- issue only arising with other languages like Hindi , Gujarati etc. (This all are the Indian languages.)

### Actual Behavior

-it's showing different output in chrome browser on web , chrome browser on mac  and safari browser on mac.
- Text render small compare to window chrome browser and line wrap is different compared to window chrome browser.

MAC: Chrome
[
![image](https://github.com/user-attachments/assets/5ad02bda-1cae-40c6-8091-6a117d5e0111)
](url)

MAC:Safari
[
![image](https://github.com/user-attachments/assets/afff6724-4db9-4996-84cc-6c2f8cdf17ce)
](url)

**Comment by asturur** [comment]
<img width="615" alt="image" src="https://github.com/user-attachments/assets/732602ad-33e4-42a1-9543-d9d7011686b6">

**Comment by niketaOptimumnbrew** [comment]
> <img alt="image" width="615" src="https://private-user-images.githubusercontent.com/1194048/386495206-732602ad-33e4-42a1-9543-d9d7011686b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTc3MTQsIm5iZiI6MTczMTY1NzQxNCwicGF0aCI6Ii8xMTk0MDQ4LzM4NjQ5NTIwNi03MzI2MDJhZC0zM2U0LTQyYTEtOTU0My1kOWQ3MDExNjg2YjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTVUMDc1NjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE4YTRkYTcyZGE3YTg3YzY0NzU2NzlmN2FkMTE4MzQ3ZmM2YjA2ZmI4YThkMjE1OTYxN2I3YjFkZGQ2YzQ0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.s1LTJGhAQGgGWlk0qUqbT-7nzZSA6ZNF-n6jvyorslM">

Please check now.

**Comment by asturur** [comment]
We are again at the same discussion, i don't see fonts loaded. You reference fonts that the code is not loading at all. So every browser will render whatever it feels like not having the correct font loaded.

**Comment by niketaOptimumnbrew** [comment]
> We are again at the same discussion, i don't see fonts loaded. You reference fonts that the code is not loading at all. So every browser will render whatever it feels like not having the correct font loaded.


I am  loading Google Fonts using a CDN link, but the text size displays differently between browsers on Windows and other platforms. This discrepancy in text rendering causes the line wrapping to differ across platforms.

**Comment by asturur** [comment]
Can you point me where the font loading happens in the sandbox? because i can't see it.

**Comment by niketaOptimumnbrew** [comment]
> Can you point me where the font loading happens in the sandbox? because i can't see it.

![image](https://github.com/user-attachments/assets/8a7acdaf-0738-4f9c-9912-e87a97a597f6)

Please check above image.

**Comment by asturur** [comment]
Again, that is a link to a font, it can be loaded in 0.1ms or a week. you have no control over it and your JS is not going to wait for it.

**Comment by asturur** [comment]
Use the browser api to load the fonts and assign them to the document and be sure the canvas wait to render the graphics that the font is loaded.
Then if there are still differences it may boil down to:
- Different browser code
- Different Operating System settings for text rendering ( subhint, ant alias ), dpi scaling settings

**Comment by niketaOptimumnbrew** [comment]
> Again, that is a link to a font, it can be loaded in 0.1ms or a week. you have no control over it and your JS is not going to wait for it.

https://codesandbox.io/p/sandbox/charming-cache-tqccg7

Please check above link , Even after loading the font first and then rendering the text on the canvas, the issue persists.

**Comment by asturur** [comment]
https://fonts.google.com/specimen/Poppins

Poppins font does NOT SUPPORT anything outside latin ( so european languages )

**Comment by niketaOptimumnbrew** [comment]
> https://fonts.google.com/specimen/Poppins
> 
> Poppins font does NOT SUPPORT anything outside latin ( so european languages )

https://codesandbox.io/p/sandbox/charming-cache-tqccg7

Please check update code sandbox.
issue arise with Roboto-Light font also.

**Comment by asturur** [comment]
<img width="1126" alt="image" src="https://github.com/user-attachments/assets/6e4ebf1e-7d30-44a6-9376-a97836d61eba">

The text you type seems Hindi to me, and apologies if i m wrong.
The TTF file you uploaded in the sandbox does not support hindi. Robot light may support Hindi but that TTF file you uploaded does not.
You are using the wrong TTF file and the browser is using probably using a fallback offered from the OS.

As i stated before and i do not want to demonstrateanymore:
- between Operating systems font rendering may change, very slightly, also depending on user settings.
- loading the correct font for the correct text is a complicated topic
- Working with text graphic in general requires an understanding of how text and fonts work and are concepts outside javascript and fabricJS

**Comment by niketaOptimumnbrew** [comment]
> <img alt="image" width="1126" src="https://private-user-images.githubusercontent.com/1194048/386573901-6e4ebf1e-7d30-44a6-9376-a97836d61eba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NzE3MjEsIm5iZiI6MTczMTY3MTQyMSwicGF0aCI6Ii8xMTk0MDQ4LzM4NjU3MzkwMS02ZTRlYmYxZS03ZDMwLTQ0YTYtOTM3Ni1hOTc4MzZkNjFlYmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTVUMTE1MDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmZlOGFkZWYxMDEwMjI2MzhhOWIyYjdhNmI1NzE5YmU3OGQwYTYwMDk5ZjkyNTg5YTk1ODRlYTkyYzAwYjMxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WWnFx10ZUrgxFdsOHDb6D9WKZOlv3z4GuIdpEiQ8PFk">
> The text you type seems Hindi to me, and apologies if i m wrong. The TTF file you uploaded in the sandbox does not support hindi. Robot light may support Hindi but that TTF file you uploaded does not. You are using the wrong TTF file and the browser is using probably using a fallback offered from the OS.
> 
> As i stated before and i do not want to demonstrateanymore:
> 
> * between Operating systems font rendering may change, very slightly, also depending on user settings.
> * loading the correct font for the correct text is a complicated topic
> * Working with text graphic in general requires an understanding of how text and fonts work and are concepts outside javascript and fabricJS

Above one font is 'Gujarati' font not the 'Hindi' font.
Thank you, @asturur, for providing the correct explanation regarding the font.
