### ISSUE TITLE
[Bug]: DrawContext not visible to typescript

### ISSUE THREAD

**Issue by gloriousjob** [fabricjs/fabric.js#10280]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Node.js

### Node Version (if applicable)

20.15.0

### Link To Reproduction

See steps as the issue is typescript based

### Steps To Reproduce

The version of fabric is 6.5.0. Create project with a class that extends Group and try to override drawObject. The method is drawObject(
		ctx: CanvasRenderingContext2D,
		forClipping: boolean | undefined,
		context: DrawContext
	) {
   super.drawObject(ctx, forClipping, context);
   // other code not causing a problem
}

At this point, DrawContext does not resolve in vscode so an import cannot be added to the top.

### Expected Behavior

DrawContext has an import to support subclassing when overriding DrawObject.

### Actual Behavior

vscode is unable to detect the import for DrawContext. I was able to go into Fabric's Group class and find the definition of DrawContext to copy into my file to use. The export exists in Fabric.Object so it appears to be an issue of having the top level export making it visible outside the project.

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/pull/10281
This should fix it
