### ISSUE TITLE
[Bug]:  Uncaught s: fabric: No class registered for ActiveSelection

### ISSUE THREAD

**Issue by franckdsf** [fabricjs/fabric.js#10287]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

20.13.1

### Link To Reproduction

https://codesandbox.io/p/devbox/yf3g5t

### Steps To Reproduce

1. Create a react app
2. Instantiate a canvas with 2 elements
3. Set the selection to ``true``
4. Try to select more than one element

### Expected Behavior

It should correctly select the two elements.

### Actual Behavior

The ``mouse up`` event doesn't trigger, no elements are selected, the ``mouse down / mouse move`` selector is still active.
Console error : ``Uncaught s: fabric: No class registered for ActiveSelection``
(I can only see this error when building to production, the code actually works in dev mode)

### Error Message & Stack Trace

```bash
Console error : ``Uncaught s: fabric: No class registered for ActiveSelection``
(I can only see this error when building to production, the code actually works in dev mode)
```

**Comment by franckdsf** [comment]
Hey :),
I tested with version ``6.4.3`` and the code sandbox is running the version ``6.5.1``.
It might be related to this issue : https://github.com/fabricjs/fabric.js/issues/10001

**Comment by Smrtnyk** [comment]
are you importing from "fabric/es"?
in that case it doesn't work, since it is treeshaken
you would need to import only from "fabric"

**Comment by franckdsf** [comment]
Thanks for the help @Smrtnyk, but using ``fabric/es`` isn't the right way to go for production build? The package size from ``fabric`` is huge since it bundles everything and unwanted parts.

Maybe I can import the specific part related to ``class registration`` to make it work?

**Comment by Smrtnyk** [comment]
I had the same issue, and error with ActiveSelection happened
so I reverted back to not importing from fabric/es.
Maybe you can additionally import ActiveSelection where it is needed, in the main entry point or somewhere,
you would have to experiment.
For me, to avoid potential headaches with that, I just sticked with "fabric" imports, because I don't know what could be the next thing that got treeshaked

**Comment by franckdsf** [comment]
@Smrtnyk I found a fix :)
We just have to register the class ourselves to make it work.

```tsx
import { ActiveSelection, classRegistry } from 'fabric/es';
classRegistry.setClass(ActiveSelection);
```

Small example code :
```tsx
import { useEffect, useRef } from 'react';
import { ActiveSelection, Canvas, classRegistry, Rect } from 'fabric/es';

export default function CanvasComponent() {
  const canvasEl = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    if (!canvasEl.current) return;

    const options = { selection: true, width: 600, height: 600 };

    classRegistry.setClass(ActiveSelection);
    const canvas = new Canvas(canvasEl.current, options);

    // some objects
    canvas.add(new Rect({ width: 100, height: 100, top: 10, left: 10, fill: 'red' }));
    canvas.add(new Rect({ width: 100, height: 100, top: 30, left: 100, fill: 'blue' }));

    canvas.renderAll();

    return () => {
      canvas.clear();
      canvas.dispose().catch(() => null)
    }
  }, []);

  return (<canvas ref={canvasEl} />)
}
```

**Comment by Smrtnyk** [comment]
yeah but I have a bigger app and my fear was that something else might come up to surface that needs similar approach
and I didn't have enough test cases that would catch this
so didn't want to risk in production my users catching these cases.
Can you come back after some time leaving here feedback if everything was stable for you after some time?

**Comment by franckdsf** [comment]
Well, actually, I have a pretty extensive implementation of the canvas, including multiple layers, cloning, groups, overlays, zoom, animations, lasso, eraser (``@erase2d/fabric``), custom brush tools, attributes, and hooks. However, I hadn't implemented multiple selection until now.

So far, I've been exclusively using ``fabric/es`` and hadn't encountered any issues with this import until now. (I've also been consistently working with version ``6.x`` for this app, so I haven't had to deal with any breaking changes.)

I'm moving on to an even bigger version of our canvas, so I'll let you know once it's done. However, after 4–6 months of using the current implementation, I haven't encountered any issues.

**Comment by Smrtnyk** [comment]
thnx a lot @franckdsf 
I might then also give it a spin

**Comment by franckdsf** [comment]
@asturur Okay, actually, importing `ActiveSelection` wasn't enough—I had to `register` it to make it work. But now that I’ve done it, I think it actually makes sense to handle it this way. So, I believe it’s safe to close the issue. People using `fabric/es` will likely find this thread if they encounter the same problem.

Thanks for the explanation! I didn’t know much about custom class registration with Fabric, but everything makes more sense now. :)

**Comment by franckdsf** [comment]
When I import unused code, I believe the compiler automatically suppresses the import. This means I need to use the variable in some way (like registering it) to ensure it doesn’t get suppressed.

So, it’s not really a puzzle—it makes sense to me. 🧐

**Comment by asturur** [comment]
Ho right because you don't have access to the file itself, but just the built lib. i didn't think of this. This is why the /es endpoint is still not ready imho. Needs to have both explanations and a way to force some imports to be used
