### ISSUE TITLE
[Bug]: TextBox poorly rendered when overloading _renderBackground method

### ISSUE THREAD

**Issue by LegebA** [fabricjs/fabric.js#10296]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Firefox, Chrome, Safari, Opera, Microsoft Edge

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/zj2brhew/10/

### Steps To Reproduce

1. Expand the TextBox
2. Collapse the TextBox

### Expected Behavior

I want to add a box around a Fabric JS TextBox object. 

### Actual Behavior

Two lateral lines appear on both sides of the textbox when collapsing.

![image](https://github.com/user-attachments/assets/b17b2e5a-f0fc-4678-9f2f-6e9af64877d5)

**Comment by asturur** [comment]
A reproduction case on fabric 4.5.0 is not acceptable. please use the latest version.
Version 4 is not supported.
