### ISSUE TITLE
Rotate the background image

### ISSUE THREAD

**Issue by eddieyangtx** [fabricjs/fabric.js#1030]
Any way to rotate the canvas background image?

**Comment by howtomakeaturn** [comment]
for anyone seeing this issue in 2020, it's called `rotate` now

```
canvas.backgroundImage.rotate(45);
canvas.renderAll();
```

**Comment by LingaTigeen** [comment]
In my case, the background image is rotated, but the width and height is wrong it seems. I think the rotation is based on center position and once it is rotated to 90 we have to reposition it to center. Any idea?
