### ISSUE TITLE
[Bug]: Triangles and Polygons - miters get cut out and out of bounding box when increase stroke width

### ISSUE THREAD

**Issue by tsbogdanov** [fabricjs/fabric.js#10314]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://codepen.io/tsbogdanov/pen/RNbWegQ

### Steps To Reproduce

1. Draw a triangle or polygon
2. change stroke width
3. zoom canvas in

### Expected Behavior

After increasing the stroke width, the object fully stays inside its bounding box

### Actual Behavior

Object miters get cut off and out of the bounding box.

**Comment by asturur** [comment]
To get a better working version of the stroke you have to use fabric 6 feature 'exactBoudningBox'
https://fabricjs.com/api/classes/polyline/#defined-in-23

**Comment by tsbogdanov** [comment]
Which IMO does not solve the issue.

**Comment by asturur** [comment]
Why doesn't it? It should fix exactly that problem

**Comment by tsbogdanov** [comment]
Check out the example I placed in the reproduction link. It uses fabric 6 and ExactBoundingBox is set to true. 

https://codepen.io/tsbogdanov/pen/RNbWegQ
