### ISSUE TITLE
Problem with text (selected chars) and gradient

### ISSUE THREAD

**Issue by u-blusky** [fabricjs/fabric.js#10329]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.5.3

### In What environments are you experiencing the problem?

Firefox, Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/bqros8pa/

### Steps To Reproduce

1. Click "Save & load" button.

### Expected Behavior

Hi,
in version 6 I have problems with text and gradients.
In particular the problem occurs when I select characters; while if I apply the gradient to all the text it works.

The problem occurs when I save the canvas in json and reload it.
The problem occurs in Firefox and in Chrome (in my application). 
But with fiddle it works with Chrome and it doesn't work with Firefox.

### Actual Behavior

The chars  filled with gradient are black.

**Comment by aswind7** [comment]
@u-blusky  I think there is an error in the code: 
```
var sJson = JSON.stringify(canvas)
```

should be 
```
var sJson = canvas.toJSON();
```
 I've tried the new code and it works.

**Comment by u-blusky** [comment]
Hi @aswind7,
you are right. The modification you propose works correctly.
Thanks a lot,
Blu

**Comment by asturur** [comment]
in theory `var sJson = JSON.stringify(canvas)` and `var sJson = canvas.toJSON();` should give the same output.

toJSON is there only to catch a behavior of stringify.
