### ISSUE TITLE
[Bug]: When scaling group rect inside has a gap

### ISSUE THREAD

**Issue by Smrtnyk** [fabricjs/fabric.js#10333]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### Node Version (if applicable)

22.4.0

### Link To Reproduction

https://codesandbox.io/p/devbox/fabric-nextjs-sandbox-forked-v822g2

### Steps To Reproduce

1. Open codesandbox link
2. In index.tsx everything is already setup, there is a rect added to the canvas
3. Resize the added rect to be wide and tall

### Expected Behavior

Maybe I am doing something wrong but I don't expect this gap between controls and the rect in the group to be this big and to increase with resizing

### Actual Behavior

There is a gap between controls and rect inside the group when resizing
![fabric-rect](https://github.com/user-attachments/assets/54f9a8e7-7a13-404b-abff-f1cc292c383a)

**Comment by asturur** [comment]
https://fabricjs.com/docs/old-docs/gotchas/#objects-have-a-transparent-stroke-of-width-1-by-default
