### ISSUE TITLE
[Bug]: Border Radius Distortion on Rect Fabric Object When Decreasing Height

### ISSUE THREAD

**Issue by yashChapaniOB** [fabricjs/fabric.js#10343]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/YashChapani/g0xm9tqv/2/

### Steps To Reproduce

1. Create a fabric. js Rectangle Object with a fixed width and height.
2. Apply a border-radius to the rectangle.
3. Decrease the height of the rectangle significantly (e.g., reduce it to a value much smaller than the width).
4. Observe the distorted appearance of the border-radius, which may look uneven or visually incorrect, similar to the issue shown in the image.

### Expected Behavior

The rectangle's border-radius should remain proportional and smoothly rounded, regardless of the height.

### Actual Behavior

The border-radius appears distorted and behaves unexpectedly when the height of the rectangle is decreased.

### Error Message & Stack Trace

**Code :**
```bash
       const canvas = new fabric.Canvas('canvas');
        let canvasWidth = 640;
        let canvasHeight = 640;

        canvas.setWidth(canvasWidth);
        canvas.setHeight(canvasHeight);

      const rect = new fabric.Rect({
            left: 145, // Center the rectangle within the canvas
            top: 145,  // Center the rectangle within the canvas
            fill: 'blue',
            width: 350,
            height: 350,
            rx: 20, // Horizontal border radius
            ry: 20  // Vertical border radius
        });

        // Add rectangle to the canvas
        canvas.add(rect);

        canvas.renderAll();
        
   ```
   
   **Version Info :**
- Node Version : 20.16.0
- Fabric.js : 6.4.0

**Comment by asturur** [comment]
@yashChapaniOB if you open an issue and a discussion with the same exact content i will have to block your user from posting. Sorry i can't handle spam on top of everything
