### ISSUE TITLE
[Feature]: Export animated image to gifs.

### ISSUE THREAD

**Issue by abhaybisht314ecorp** [fabricjs/fabric.js#10348]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

I've created a rectangle shape and i'm adding animation to that shape using  this code, i want to convert this shape's animation into a gif image, how can i do that?
`
	util.animate({
		startValue: 0,
		endValue: 1,
		duration: 1000,
		onStart: () => {
		
		},
		onChange: (value) => {
			
		},
		onComplete: () => {
			
		},
	});
};`

### Current State

This is feature is currently not there in fabric.js

**Comment by asturur** [comment]
There is a discussion about this already.
This is not in scope for the library.
You have animation, you can export every frame and have encoded it in an mp4 or gif using available web tools

**Comment by asturur** [comment]
https://medium.com/@emma.pejko/making-gifs-in-javascript-497349bf3cc8
https://github.com/mattdesl/gifenc

on of those links ( that i didn't check deeply ) will help you for sure

**Comment by abhaybisht314ecorp** [comment]
@asturur in my code i'm recording canvas using captureStream and Media Recorder but this is only recording partial animation video and somehow force stop before animation ends.

Can you tell me what's wrong in this code.

`.      const canvasElement = canvasOverlay.current.getElement();
	const stream = canvasElement.captureStream(120);
	const mediaRecorder = new MediaRecorder(stream);
	const chunks: Blob[] = [];

	mediaRecorder.ondataavailable = (event) => {
		if (event.data.size > 0) {
			chunks.push(event.data);
		}
	};

	util.animate({
		startValue: -100,
		endValue: originalTop,
		duration: animationDuration * 1000,
		onStart: () => {
			mediaRecorder.start();
		},
		onChange: (value) => {
			annotation.set('top', value);
			canvasOverlay.current.renderAll();
		},
		onComplete: () => {
				mediaRecorder.stop();
		},
	});

	mediaRecorder.onstop = () => {
		const blob = new Blob(chunks, { type: 'image/gif' });
		const url = URL.createObjectURL(blob);
	}
`

**Comment by asturur** [comment]
I should rebuild the media recording example and find it where it is first and compare what i did.
I remember it was working reliably.
