### ISSUE TITLE
[Feature]: While exporting canvas as DataURL- Option to hide and show shapes that we want to export only

### ISSUE THREAD

**Issue by rk9155** [fabricjs/fabric.js#10368]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

While exporting canvas as .toDataURL all the objects that are present on screen at that time will become part of the exported image. We want to export only activeObjects. One option is activeObject.toDataURL but it will export only shape. We need exporting image with respect to whole canvas

### Current State

![image](https://github.com/user-attachments/assets/8ea76221-9018-4d25-8ac0-3c17fa5e5770)
![image](https://github.com/user-attachments/assets/43d8b53b-a580-4be5-95dd-121a37582f05)

**Comment by asturur** [comment]
Just hide the rest.
Before exporting loop over your objects and set the visible flag to false, save the original value somewhere, then put back the original value.
That is how you have to do it, there won't be a special option for it.
