### ISSUE TITLE
Server-Side Cropping

### ISSUE THREAD

**Issue by sarciszewski** [fabricjs/fabric.js#1081]
I'm working on an ugly hack for a project that uses Fabric, but it's probably something others will want (and I can't share my code for this, since it's for my employer):

Specify a "crop area" (like drawing a rectangle), only instead of filling the inside you fill the area outside of the rectangle with rgba(0,0,0, 0.5). Users in my implementation draw the rectangle (using mouse events), then can resize it as they please.

When you call toJSON(), it passes this as a "crop area" to the server-side API, which reduces the image. (I do this on the server side since I dynamically resize the canvas based on the viewport, and will store the proportions so we can crop the full-size image).

When you restore from JSON (in my implementation, the original picture is restored), you also redraw the "crop area" if specified.

**Comment by btzr-io** [comment]
It's there a better way to implement this in fabric js `1.7.17` or `2.0 (beta)` ??

**Comment by btzr-io** [comment]
also is there any example ( jsfiddle / jsbin /codepen ) of this? ^^

**Comment by asturur** [comment]
to crop an image in fabricjs version 2, you can specify cropx and cropy, and width and height of box. the image will be cropped then.

there is no dragging interface.

**Comment by btzr-io** [comment]
thanks, I know how to crop the image, what I want to achieve is the `interface`

**Comment by asturur** [comment]
you need to use fabric events, reverting the scale factor from the scaling event, and modify the cropx, cropy, width, height inside the scaling event manager. then you need some check to do not go out of bounds.

**Comment by btzr-io** [comment]
Ok, thanks asturur, one last question:
![crop-area](https://user-images.githubusercontent.com/14793624/28502513-1f3b9506-6fb1-11e7-86e5-417bd24e1fad.png)
( Left: how it should look ^^,  Right: can't see trough `dark-rect` 
I tried to use `globalCompositionOperation` / `clearRect()`  to cut the crop-rect, but I need to see the fabric `backgroundImage`, is there any way to achieve this?

**Comment by asturur** [comment]
My opinion is that you should extend the default image class, create a croppableImage and use that.

In the render function, draw the full image, draw over it a semi transparent dark rect, then draw on top of it the cropped image. That will make the trick.

**Comment by btzr-io** [comment]
Ok thanks, I'll try that

**Comment by robgoddes** [comment]
Hi @GordoRank, is there any available source code for your cropper application? I love the look of your cropping tool.
