### ISSUE TITLE
Borders of ellipse are not uniform

### ISSUE THREAD

**Issue by kangax** [fabricjs/fabric.js#1099]
Fabric:

![ellipse](https://f.cloud.github.com/assets/383/1928008/2417883a-7e71-11e3-93ae-43086fb73c52.png)

Kinetic:

![kinetic_elliipse](https://f.cloud.github.com/assets/383/1928010/2d0c1d3e-7e71-11e3-8180-3a889e3767da.png)

**Comment by biscuitlad** [comment]
Is this issue also fixed for rectangles?  Seems to still be there.

**Comment by asturur** [comment]
Rectangles have uniform borders.
untill you scale them, so borders are scaled as well.
You have to modify width and height if you want to have them uniform.

**Comment by biscuitlad** [comment]
But why is this deemed the right way to do it for ellipses (don't scale borders), but the wrong way to do it for rectangles?

I can't think of an instance where you would want setScaleX to give you a different border on two edges of a rectangle.  It was declared a bug for ellipses, shouldn't it be the same for rectangles?

**Comment by asturur** [comment]
if you take an ellipse and then scale it with mouse the borders are deformed, the same as a  with the rect.
This bug was because for a wrong commit, they where stretched even without scaling.

**Comment by biscuitlad** [comment]
Ah, OK.  So I guess that's the way it is.  OK, thanks.

**Comment by Rad1calDreamer** [comment]
> It could be an attribute: scaleStroke. False by default, if you ask me.
+1. Tell me, plese, how i can do it?

**Comment by asturur** [comment]
This issue is closed even if it was a feature. Please open a new issue with a detailed description. It can be done easily maybe it gets done,

**Comment by Rad1calDreamer** [comment]
@asturur future will be greate, but i need solution "now and here" (=.
i understand: [fabricjs not support resize by mouse](https://github.com/kangax/fabric.js/issues/2695#issuecomment-165996272)

but cant find solution to prevent render transform strokeWidth while object «scaling»

**Comment by asturur** [comment]
you have to modify each _render function of every class.
Between renderFill and renderStroke try to introduce a:

ctx.transform(1/this.scaleX, 0, 0, 1/this.scaleY, 0 ,0)
This may work as it may not and i take no responsibility for whatever may happen.

**Comment by Rad1calDreamer** [comment]
thx, anyway

**Comment by Rad1calDreamer** [comment]
@asturur , i find some fix in http://jsfiddle.net/bH93k/25/
But it have some strange reposition effect. What it can be?

**Comment by kabrice** [comment]
@Rad1calDreamer Thx, your jsfiddle has helped me. Have you already found an explanation about the reposition effect ?
Thx again

**Comment by Rad1calDreamer** [comment]
@kabrice hi. 
http://jsfiddle.net/bH93k/211/
that is fiddle what your want. But it works only on 1.6.4 fabricjs.
I still no update it in prodaction)

**Comment by kabrice** [comment]
@Rad1calDreamer Thank You very much. It was very helpful.
