### ISSUE TITLE
Possible Feature - Object/Background caching

### ISSUE THREAD

**Issue by GordoRank** [fabricjs/fabric.js#1102]
Within my app I have the need to have lots of Fabric objects on canvas at any given time.  To make matters worse most of them have to have shadows and/or other expensive effects added to them.

Due to this need, using Fabric as is was an impossibility.

For that reason I added a caching/rasteration rendering pipeline to Fabric.

The caching mode is initialized by setting the property `turbo` to `true` when initializing a Fabric canvas.

There are however two caveats, which is why I haven't created a pull request yet for it as I want to gauge feedback from @kangax and anyone else as to whether this is in keeping with Fabrics intentions.

The Caveats : 
1. When developing an app changing an objects properties with dot notation will not update the object. (I believe this is deprecated anyway) Instead the properties must be changed using the `object.set()` method.  This only applies to properties internal to an object like `text` or `fontSize`.  Any transform properties such as `top` or `left` can still be set with dot notation.
2. While transforming or moving an object it's z-index is ignored and the object is brought to the top of the stack for the duration of the transformation.  As soon as you let go of the mouse, it returns to it's correct place in the stack.

Upon doing some testing I realised that using `turbo` mode also has the huge benefit of making the initial loading of complex scenes with lots of objects infinitely faster.  In my example below we are talking 5 seconds versus 3 minutes!

I have uploaded two videos to YouTube to show you before and after. (Please switch the videos to HD as I recorded in 1920x1080)

NO TURBO : 

http://www.youtube.com/watch?v=Hv_UI-YhCTk

WITH TURBO : 

http://www.youtube.com/watch?v=-Ic9Pgrkbvk

In these two videos I am loading 1000 fabric objects into a canvas. 500 images and 500 I-Text objects. (For this reason the hidden textarea fix in my recent pull request #1111  is paramount as having 500 textareas added to the DOM causes a huge amount of strain)

In the first video you will see that the objects load quickly at first and then slow down to a complete crawl.  You will see me waiting for the objects to load as they pop up slowly on by one.  Eventually I gave up waiting and attempted to move an object.  The result was way less than 1 fps.

In the second video you will see that all objects are drawn to the screen pretty quickly within a few seconds and then all object manipulation happens at a fluid an constant 60fps.

Let me know what you think.  If its something that people want included in Fabric despite the two (in my opinion minor) caveats, then I will make a pull request tomorrow.

**Comment by jwmao** [comment]
@kangax , any updates for this feature? We really need this feature in my project.

**Comment by asturur** [comment]
We could make this caching different.
Make a sandwich with:
all objects under the transforming one cached as a single image,
the transforming object
all objects over the transforming one cached as a single image.

The performance problem with large canvas would stay anyway.

**Comment by jwmao** [comment]
@asturur Any possible solution that you can suggest?

**Comment by asturur** [comment]
10k objects is MUCH work.
Some speed improvement can be made with a new render logic i have in mind, but i m far from starting it.
