### ISSUE TITLE
intersectsWithObject on observe (object:moving)?

### ISSUE THREAD

**Issue by jasonify** [fabricjs/fabric.js#112]
It seems that when dragging an object intersectsWithObject does not report the correct value?

**Comment by mgohin** [comment]
I don't have an easy test case to give but I had this problem too, so I changed `intersectsWithObject` for `intersectsWithRect` and it seems to be working

**Comment by mgohin** [comment]
Here is a live example with points.
Both object are custom but extend `fabric.Rect`.

I'm going to try to reproduce on a small example.

<img width="1184" alt="image" src="https://github.com/user-attachments/assets/f4a5795a-152b-4b1b-aa67-5ae4abbf8cd7">

```
this.getCoords() = [
    {
        "x": 184.3121256194882,
        "y": 240.11726225449226
    },
    {
        "x": 118.66702533880131,
        "y": 163.35971663753963
    },
    {
        "x": 142.22627201331153,
        "y": 143.21122051178426
    },
    {
        "x": 207.87137229399843,
        "y": 219.9687661287369
    }
]

t.getCoords() = [
    {
        "x": -40.478773405749614,
        "y": -22.726386584929344
    },
    {
        "x": -106.12387368643653,
        "y": -99.48393220188196
    },
    {
        "x": -82.56462701192632,
        "y": -119.63242832763734
    },
    {
        "x": -16.919526731239408,
        "y": -42.87488271068473
    }
]

e.status = "Intersection"
```
