### ISSUE TITLE
Support multitouch gestures

### ISSUE THREAD

**Issue by Dino4674** [fabricjs/fabric.js#115]
Hi,

on this presentation http://www.slideshare.net/kangax/fabric-falsy-values-8067834, slide 36, it is mentioned a support for multitouch gestures on iOS. How is this going to work and will it be available for Android also?

Those gestures would be used for scale, rotate objects with two fingers etc?

I am planning to use this library for my iOS/Android application and for now I can obviously use only one finger which is simulating the mouse. 

When is it planed to be finished?

Tnx

**Comment by YangChueng** [comment]
Is there any demo?

**Comment by handersen** [comment]
http://fabricjs.com/touch-events/

**Comment by YangChueng** [comment]
I mean that the object just can rotate or drag through gesture only.But not touching the edge point.
Because It's hard to touch that spot accurately.And the experience is really not good.

**Comment by asturur** [comment]
you can rotate with 2 fingers, zoom with 2 fingers.

**Comment by YangChueng** [comment]
So it has been supported,yes?
Like the demo
http://fabricjs.com/touch-events/ .
Should I do something else?I have tried it on my mobile device but it doesnt work.

**Comment by handersen** [comment]
Yes multitouch works in Fabric v 1.5 like the demo at http://fabricjs.com/touch-events/   I just tried it on iPhone 5 and Ipad.  I beleive it works well.

**Comment by YangChueng** [comment]
Oh,yeah! The demo really works well.   No!
![qq 20151112155625](https://cloud.githubusercontent.com/assets/8767429/11113315/d0540fdc-8956-11e5-99b9-fad3a9c3c69c.jpg)
My code doest work.

**Comment by YangChueng** [comment]
So now I know what the problem is.But i wonder if there needs some adjustments.
I used to install fabric through bower and then the multitouch doesnt work.Then I tried to replace with the file used in the demo.(its name 'fabric_with_gestures.js').And it finally works well.
Any difference?

**Comment by asturur** [comment]
Yes, you have to build fabricjs with multitouch support.
Also refer here for the fix: #2586

**Comment by asturur** [comment]
to build fabricjs with multitouch support use:

node build.js modules=ALL  and you will get full fabricjs built.

**Comment by gabrielstuff** [comment]
@asturur how to do it via npm ? Thanks !

**Comment by asturur** [comment]
when fabric.js 1.6.3 gets released, just run "npm run build_with_gestures" i just added the command in packages.json.

**Comment by DevNIX** [comment]
I couldn't did it via npm package as a dependency of my project automatically build because they are missing files like HEADER.js. Had to git clone on another directory and paste the minified file manually in my lib folder.

**Comment by bbugh** [comment]
The link mentioned here http://fabricjs.com/touch-events/ is a 404 now, and I can't find any more recent documentation specifically about touch events. Is there a new location for this link?

**Comment by asturur** [comment]
http://fabricjs.com/touch-events

There isn't much to say about touch events.
Our integration isn't great and should be replaced with a more modern way to detect pinch and rotate.
Is unclear which is a standard library to do so.

I would have bet on hammer.js but seems like completely abandoned.

**Comment by Gerwin-prog** [comment]
Maybe we can re-open this, or another issue regarding multi-touch events? @asturur

**Comment by Rajdeepc** [comment]
My use case is when there are multiple fingers or multi touch on an object in the canvas the object should not get selected.
Whenever I place a finger updateActiveObject is getting called and e.touches length is always 1
 canvas.on({
      'selection:created': updateActiveObject
})

multi touch is not working.

**Comment by edthoms** [comment]
I added two-finger rotation to the canvas using interact.js. Very easy to do. However! when the canvas is rotated and I do some freedrawing, the drawing paths appear not directly below the pen/cursor tip, but far away, seemingly with no rhyme or reason. Any idea of what to look into to fix that issue?

**Comment by Saqib92** [comment]
I need Multi touch support? is this achiveable? 
My scenario: I have canvas for large screens, where users are giving presentations, i would like to move multiple objects with both hands, right hand to move one object and left hand to move other object. both at same time? is this we can do with fabricjs?
