### ISSUE TITLE
Fabricjs error while applying fliter on Image

### ISSUE THREAD

**Issue by anilGupta** [fabricjs/fabric.js#1154]
I am trying to load image from URL while adding image to canvas, i am applying RemoveWhite Filter on it, which generating an errors in console.

```
Security Error: The operation is insecure.
```

``` html
<div>
    <canvas id="c" width="500" height="500"></canvas>
</div>
<script type="text/javascript">
    (function() {
      var canvas = this.__canvas = new fabric.Canvas('c');
      var ImageURL = "https://www.google.co.in/images/srpr/logo11w.png";
        fabric.Image.fromURL(ImageURL, function(img) {
            img.filters.push(new fabric.Image.filters.RemoveWhite({threshold: 60, distance: 10}));
            img.applyFilters(canvas.renderAll.bind(canvas));
            canvas.add(img.set({ left: 50, top: 50, angle: 30 }).scale(0.5));
        });
    })();

</script>
```

 http://jsfiddle.net/_anil/NYCQ5/5 Link.

**Comment by divyanshjain217** [comment]
what is the workaround in this type of cases, if we still wish to use crossOrigin data?
I'm using fabric.util.loadImage function to laod image from URL but I'm getting same error.

**Comment by asturur** [comment]
the function do support crossOrigin in the arguments.
You have to specify the crossOrigin you want to use to laod when calling loadImage
