### ISSUE TITLE
Two key accented letters don't work in IText

### ISSUE THREAD

**Issue by alisspers** [fabricjs/fabric.js#1175]
Accented letters that are combined in two separate keystrokes, where you first press the accent key (like ^) and then your vowel, don't work in IText.

Accented letters added programmatically or ones with the accent already added with one keystroke (like ÅÄÖ on a Swedish keyboard) work fine.

**Comment by marcospassos** [comment]
I'm facing the same issue. I can't use ~ + a to inset ã, for instance.
