### ISSUE TITLE
Deep zoom with SVG

### ISSUE THREAD

**Issue by psled** [fabricjs/fabric.js#1191]
I'm trying to implement a deep zoom feature for large and complex SVG graphics.

The approach I have chosen is as follows:
1) parse SVG string into fabric.Object (DO NOT add it to fabric.Canvas)
2) clone fabric.Object as image in order to get raster fabric.Image (here I have to do it TWICE from some reason as long as doing it only once without previous false initial cloning / behind drawing in canvas it results with some coordinate / scale error of final raster image drawing)
3) add new raster fabric.Image object (created from original vector SVG object) into the canvas and remove its previous version (with previous scale) if present
4) repeat 2) and 3) steps each time user finish scrolling event of the image

The problem is that as long as above approach somehow works the redrawing process (cloning original SVG into its raster image version) takes a lot of time even on fast computers and, what's even worse, it completely freezes the entire UI (canvas) and prevent user from any interaction with it for at least couple of seconds.

To reproduce the problem just zoom in the image at some level and immediately after that try to execute any other action on canvas like dragging it, etc. Please notice also the long time necessary for redrawing the image TWICE each time zoom action has taken place.

http://jsfiddle.net/73ncF/2/

**Comment by ekg** [comment]
What technique did you use?

**Comment by asturur** [comment]
svg images added as images should be zoomable as normal svgs.

**Comment by ekg** [comment]
This will work with a 10GB SVG?

**Comment by psled** [comment]
Just for a remark: I opted for native development instead of web one.

Today, there is even a Wasm, so that could be useful as well.

**Comment by asturur** [comment]
The point is, if the browser can handle a 10GB image, if the computer you have can handle a 10GB image, yes.
Parsing 10GB of text is a big effort for anything involved in the process.

In this case Wasm is not usefull much. Drawing command are already native and are probably also gpu accelerated when we talk about post rasterization.
