### ISSUE TITLE
Synchronizethe free drawing path in different canvas board

### ISSUE THREAD

**Issue by sritify** [fabricjs/fabric.js#1259]
Hi, I am writing a realtime whiteboard using fabric js.
And I am now doing the task on synchronizing the free drawing path

I listen on the canvas board for object added event, when the user finish drawing one path, the event fired, and the turn the path object into JSON, and send to another canvas in another browser

Whiteboard.prototype.onObjectAdded = function(e) {
    if(e.target.type=='path'){
        this.socket.send(JSON.stringify({
            msg: 'create',
            data: {
                type: 'path',
                object: JSON.stringify(e.target),
            }
        }));
    }
}

My question here is how can I build the same object by the using the JSON received from another side?

I hardly find many information on the new Fabric.Path method....

**Comment by saran110313** [comment]
i listen to path,circle,triangle, text object added event .when the user finish drawing one path, the event fired, and the turn the path object into JSON, and send to another canvas in another browser
so added in image object added in another browser create the two object

**Comment by saran110313** [comment]
![clientside](https://cloud.githubusercontent.com/assets/10917348/12031027/1b592742-ae2d-11e5-8464-67f0542dbd2f.png)
![serverside](https://cloud.githubusercontent.com/assets/10917348/12031028/1e9ed19a-ae2d-11e5-8ff6-69ced43d2bd8.png)
image object added to server side but client side added in two image object.hiow to solved this problem
