### ISSUE TITLE
SVG: Polygon having point with negative coordinate fails to render properly

### ISSUE THREAD

**Issue by raglan-road** [fabricjs/fabric.js#1266]
The following SVG renders a curve with an arrowhead at the bottom:

``` xml
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     width="51.716px" height="57.544px" viewBox="0 0 51.716 57.544" enable-background="new 0 0 51.716 57.544" xml:space="preserve">
<g>
    <g>
        <path fill="none" stroke="#000000" stroke-width="3" stroke-miterlimit="10" d="M13.813,48.516
            c20.743-6.469,35.564-26.036,35.052-48.856"/>        
        <g>
            <polygon points="18.334,57.162 -0.01,50.715 14.745,38.051 "/>
        </g> 
    </g>
</g>
```

like so:
![arrow](https://cloud.githubusercontent.com/assets/1560925/2671936/dbe69d1e-c0e0-11e3-8288-3f9fa0b25f64.png)

Using `fabric.loadSVGFromURL()` to add this to the canvas causes this to render instead:
![broken arrow](https://cloud.githubusercontent.com/assets/1560925/2671981/4130a4a8-c0e1-11e3-97dd-37d4dd968912.png)

It seems that the negative coordinate in the `polygon`'s `point`s is causing the issue. 

Changing
`<polygon points="18.334,57.162 *-0.01*,50.715 14.745,38.051 "/>`
to
`<polygon points="18.334,57.162 *0*,50.715 14.745,38.051 "/>`
sorts the issue, so it seems like the issue is caused by the negative value.

That SVG markup was generated by Adobe Illustrator, and I am an SVG novice myself, so I have no idea if this is a common scenario or is totally bizarre, but I figured I would report the issue nonetheless.

**Comment by nikhilroy2** [comment]
how can I use polyline negative value stroke, the negative value stroke not showing me here <polyline points="50,50 150,50 150,-15 180-15 180,50 250,50 250,150 50,150" stroke="red" fill="none"></polyline>

**Comment by asturur** [comment]
What is a negative value stroke?
