### ISSUE TITLE
SVG load without grouping , miss placed

### ISSUE THREAD

**Issue by lukluk** [fabricjs/fabric.js#1281]
iam tried load SVG from kitchenshink and paste SVG , when load (as grouped) it work but when load without grouping it not work? any idea
@kangax  may be have solutions?

**Comment by deenfoxx** [comment]
@kangax, I'm not sure what you mean by different algorithms. I am considering using Fabric.js for an important project and this is stopping me. Need to be able to import an SVG into individual elements to edit (the text). But, as you can see the "Load without grouping" throws a huge bounding box on the image and the text is all outside of their bounding boxes.

Is @lukluk's code the solution? His fiddle source (http://idweb.co/luk/fabricjs_svg.js) doesn't exist anymore.

![svg-load-ungrouped](https://cloud.githubusercontent.com/assets/3209606/11192921/88cae384-8c58-11e5-97ad-675145c67b35.PNG)

![svg-load-ungrouped-bounding-boxes](https://cloud.githubusercontent.com/assets/3209606/11192926/927731f8-8c58-11e5-9b15-4479e3d599da.PNG)
