### ISSUE TITLE
Updating Multitouch Gesture support

### ISSUE THREAD

**Issue by jafferhaider** [fabricjs/fabric.js#1297]
Hi @kangax, I'm working on updating multitouch gesture support in Fabric. It's been a while since I wrote the original module. 

The current code (in the main trunk) has the following issues:
1. Scaling and rotation on pinch and rotate gestures is around the origin in the top/left of the shape. That is not intuitive. We should discuss if we want to always make it such that pinching scales and rotates around the center of the object (because that is how people are used to the pinch gesture working), or we do want this module to respect the `centeredRotation` and `centeredScaling` flags.
2. Outdated transform logic, it probably doesn't fire Fabric events as an object is modified and ignores constraints.

I've created a couple of fiddles to demonstrate the current and updated (still a work in progress) gestures module. Have a look at these on an iPad.
1. Current module in Master: http://jsfiddle.net/jafferhaider/EQcu4/2/
2. Modified module: http://jsfiddle.net/jafferhaider/NdW6e/5/
### Changes in __onMouseMove

I've had to disable dragging in `__onMouseMove` when the user has 2 or more fingers on the canvas. This is to improve UX as otherwise the object would move while the user was scaling/rotating it.

The following lines have been added in `__onMouseMove`:

``` javascript
if(typeof e.touches !== 'undefined' && e.touches.length > 1) {
    return;
}
```

Can we leave these in? Is there a better place to do this?
### Updating the model as Object transforms

The dimensions and position of the fabric.Object representation of the shape is not updated as it is scaled/rotated. What functions/code needs to be called to update the model? `_finalizeCurrentTransform`? 
### Simultaneous Scaling and Rotation (_currentTransform.action value)

It'd be great if you could review the code in `__gesturesRenderer` in the gestures module. This needs to handle both scaling and rotation transforms at the same time (ideally, drag too, in an intuitive way). AFAIK, Fabric's transform pipeline can't do both of these transforms at the same time. You'll see me update the value of `_currentTransform.action` to make Fabric do both transforms in succession. Would there be a better & faster way of doing this? Should the core be updated to handle multiple simultaneous tranforms?

Also, I'd like to keep most of the code in this function in the FabricJS core so that this module doesn't have its own set of logic/constraints on transforms. It should be able to use functions defined in the core. Right now that wasn't doable (because of the way functions are called in the core). I'm open to suggestions for refactoring etc.
### Performance

You'll notice the newer gestures module is a little slower. That is due to more going on in the gesture event handler. The original handler was pretty bare bones and ignored most constraints. 

I was thinking of using the `setInterval` / `requestAnimationFrame` technique outlined on this page: http://www.html5rocks.com/en/mobile/touch/ for smoother transforms. The code is in there in the module, but disabled for now. In my testing it resulted in a smoother experience.

Any strong opinions on whether to use or avoid this technique?

Lemme know if there are other issues with that'd prevent this module from being folded back into the main branch. I see a few pending documentation tasks for me, I'll get to those once this code has been updated and available to everyone.

**Comment by ming-cheng** [comment]
I stiill have this problem in version [3.6.0](url).What should i do.

**Comment by Gerwin-prog** [comment]
@asturur It looks like objects do not respect the 'centeredRotation' property when rotating, was this ever implemented? Am running into an issue that'd be fixed by this - and applying centered rotation on the rotating event & setting it back once it's done is hacky & very prone to breaking.

It also isn't intuitive to not rotate around the center when using gestures.
