### ISSUE TITLE
Starting IText inline editing scrolls to top of the page

### ISSUE THREAD

**Issue by ralfwahl** [fabricjs/fabric.js#1310]
When I click inside an IText field to start the inline editing, the whole document scrolls up to the start of the page, which is quite confusing for the user. I have this effect with fabric.js 1.4.4 and 1.4.5. It can be also seen  in the official IText demo http://fabricjs.com/test/misc/itext.html:
Take one of the last IText objects, e.g. "Lots of text (performance test)" and click there. The page will jump up, making the current inline editing move out of the visible screen.

This problem can be watched for example with Firefox 28/29 and Internet Explorer 11. Chrome 34 handles it better, stays at the current document scroll position.

When trying to debug the script, it seems that all the event handling starting from _onMouseUp works as expected. After leaving that fabric.js code some rerendering takes place that moves the document upward. 

Another effect is, that it works OK if I'm in fullscreen mode of one scrollable DIV containing the canvas (not the F11 overall fullscreen, just of the DIV node). In that case everything stays at place. Is there something happening on top of the document that makes some browsers scroll to that position?

Kind regards
Ralf

**Comment by filiperoberto** [comment]
It's still scrolling for me, but now to bottom. It's weird because some times textarea is appended to body and sometimes to canvas-container. When it's appended to body there is no problem, but to canvas-container it scrolls to bottom.

**Comment by FeaRCODE** [comment]
@filiperoberto @asturur I can also confirm in my configuration, the text JUMPS to the bottom of the page.

**Comment by asturur** [comment]
in the current configuration the textbox is placed wher you clicked and then follow the cursor. How are you entering the textedit? clicking or by code?

**Comment by FeaRCODE** [comment]
Clicking. I have an event that places the text box.

**Comment by murilobd** [comment]
@filiperoberto I was with this same issue and fixed with that:
```javascript
var bodyRect = document.body.getBoundingClientRect(),
        elemRect = this.canvas.upperCanvasEl.getBoundingClientRect(),
        offsetRect = elemRect.top - bodyRect.top;
this.hiddenTextarea.style.cssText = 'position: fixed !important; top: ' + offsetRect + 'px !important; left: 0px; opacity: 0; width: 0px; height: 0px; z-index: -999;';
```
