### ISSUE TITLE
fabric.NamedImage.fromURL()

### ISSUE THREAD

**Issue by Tilogorn** [fabricjs/fabric.js#1322]
Hi guys,

I've implemented an fabric.Image subclass with unique IDs according to these instructions from kangax: 
http://stackoverflow.com/questions/11272772/fabric-js-how-to-save-canvas-on-server-with-custom-attributes

I need to call fabric.NamedImage.fromURL() for my application. How can I inherit this method to the subclass?

Thanks in advance,
Daniel

**Comment by saran110313** [comment]
I'm receiving this error originating from fabric.js

Uncaught TypeError: Cannot read property 'apply' of undefined

function klass() {
(ln: 1690) --> this.initialize.apply(this, arguments);
}

**Comment by saran110313** [comment]
Uncaught TypeError: url.indexOf is not a function

 if (url.indexOf('data') !== 0 && typeof crossOrigin !== 'undefined') {
        img.crossOrigin = crossOrigin;
      }
 this function error in fabric.js
