### ISSUE TITLE
Question: Configuring FabricJS to use cloudfront URL's

### ISSUE THREAD

**Issue by abishekrsrikaanth** [fabricjs/fabric.js#1356]
I know this question has been asked a lot of times on stackoverflow and none of the question seems to have a proper answer.

Has someone been able to configure FabricJS to use assets from AWS Cloudfront with CORS configuration?

**Comment by taqimustafa** [comment]
http://jsfiddle.net/dwab4oz3/

I am having this CORS issue. How can i fix it. using AWS s3. Can you guys help ?

@Kienz @kangax @asturur

**Comment by taqimustafa** [comment]
![screenshot from 2016-10-18 02-53-04](https://cloud.githubusercontent.com/assets/8524942/19457067/068d6146-94de-11e6-9cdb-2ebc673f605e.png)

**Comment by asturur** [comment]
Hi @taqimustafa, tomorrow i'll try to ask a person i know she set up amazon s3 recently. cheers.

**Comment by dovepa** [comment]
Hello, any news ?
