### ISSUE TITLE
"Uncaught Security Error: Failed to execute 'toDataURL'...tainted canvases may not be exported" in 1.4.7 even thought images appear to be valid CORS

### ISSUE THREAD

**Issue by virtualandy** [fabricjs/fabric.js#1386]
When calling canvas.toDataURL(), I'm seeing the following error:

```
Uncaught SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': tainted canvases may not be exported.
```

even though the image being used is coming from a CORS-compliant server/endpoint. 

Here is a fiddle that demonstrates the issue: [http://jsfiddle.net/virtualandy/7Akuf/3/](http://jsfiddle.net/virtualandy/7Akuf/3/).

Hit the 'Clear' button to make the toDataURL() call. (It also logs canvas.toJSON() to the console, so you can see the image url and `crossOrigin = 'anonymous'` attributes.)
The image loads into the canvas and toJSON() works.

Have tried 1.4.5 and 1.4.7 with same results.

**Comment by fwextensions** [comment]
For anyone who lands here from a web search in the future, note that if you're just trying out Fabric.js by loading a local file into the browser, the CORS change doesn't fix anything.  The issue is that Chrome, at least, just doesn't like you reading from a canvas created from an image loaded from the local file system.  You can create image objects just fine, but if you try to do something like cloneAsImage(), it will trigger the error above.  If you use a local web server to serve the file, it should work fine.

**Comment by zaus** [comment]
Also mentioning that on the ["Kitchen Sink" demo](http://fabricjs.com/kitchensink/) this issue prevents you from loading the Google logo ('Simple' tab, 'Image' button) and then rasterizing the image.  SVG/JSON are just fine.

**Comment by LeeJim** [comment]
thanks guy,u got me a huge hint!!

**Comment by ppranayy** [comment]
Also note that if you use the function "fabric.Image.fromURL", we can set the crossOrigin attribute in the third parameter... like  fabric.Image.fromURL(url, callback, {crossOrigin:'Anonymous'}); Unless this is set, the canvas may be tainted already, and any other place might be too late to set the crossOrigin parameter. 

I found this in the context of fancyproductdesigner that is built on fabric.js, but does not pass the cross origin parameter. Add this, and things will be fine. Hope this helps!

**Comment by YangChueng** [comment]
Hey,I followed the solution,but still exist some questions;
Here's my code.
[https://jsfiddle.net/YangChueng/6de6L7Ld/4/](url)

**Comment by SanchitSahu** [comment]
@virtualandy : Were you able to fix this? Load image from URL works fine after adding the crossOrigin property set to 'anonymous'. But I am not able to export the data from the canvas and getting error "Uncaught Security Error: Failed to execute 'toDataURL'...tainted canvases may not be exported"
