### ISSUE TITLE
Touch Events not returning clientX/Y values consistantly

### ISSUE THREAD

**Issue by chief1522** [fabricjs/fabric.js#1406]
I'm writing some software that needs to handle mouse events with touch devices. I'm currently testing on a Nexus 7 using Chrome. The mouse events fire just fine, but much of the time they are missing the coordinates. 

Here's an example of what I'm seeing:
![touchprob](https://cloud.githubusercontent.com/assets/7724703/3330561/f3cc866e-f7d1-11e3-95e2-c44553485afa.jpg)

Here's the jsfiddle:
http://jsfiddle.net/5KKQ2/125/

EDIT: I just verified that this also is an issue on an iPad Air. 

Thanks,

Matt
##

**Comment by Made-of-Clay** [comment]
Has anything ever come of this? I am having the same problems as @chief1522 . Perhaps even a work-around?

**Comment by asturur** [comment]
no.
i m still waiting my touch enabled device and i have still to learn lot of
things about touch events.

the device should come monday.

you should share a failing snippet, or the code that makes the values not
consistent, so i can try it.

**Comment by Made-of-Clay** [comment]
I admit in embarrassment that I failed to look under the `event.e.touches` property for the values I wanted.... I appear to be getting consistent numbers from `event.e.touches`.
