### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by mtharrison** [fabricjs/fabric.js#1470]
I've been tinkering with fabric internals for an HTML5 game project that I'm working on. We run into problems on some devices and browsers with performance and I've tracked it down to the fact that the GPU is being swamped with each frame's call to renderAll().

We have a lot of images/text on the canvas and in a typical frame most things don't change, but the GPU is still being made to do work as if they were.

I've implemented a patch in our code to try to ameliorate this. I was interested to know if this is something you would consider for the core. 

I will explain what I've done below (I've put all this functionality under an option on a canvas e.g. `new fabric.StaticCanvas('c', {performanceMode: true})`).
- fabric.Object has a `dirty` property
- fabric.Object has a private method `_submitBoundsAsDirtyRect()`
- fabric.StaticCanvas has an array property `dirtyRects`
- fabric.StaticCanvas has a private method `recursivelyGetIntersecingObjects(x1,y1,x2,y2)`
- whenever an object's properties are altered using `.setX()`, we set it to dirty and submit its bounds to the canvas as a dirty rect using `_submitBoundsAsDirtyRect()`
- If the setter caused the object to move, we submit its starting and finishing bounds as a dirty rect
- In `renderAll()` we loop through the dirty rects and clear them, leaving everything else on canvas
- Foreach dirty rect we `recursivelyGetIntersecingObjects()` and mark them as also dirty (this is needed where objects overlap such as a stack of cards)
- We then simply filter `this._objects` on the canvas where `dirty === true` and draw only those objects
- `dirtyRects` is set to `this.dirtyRects = []`. Each of the rendered objects is set to `this.dirty = false`

I've done some tests with about:tracing and am finding for our needs the render cycle is about 5-8x faster keeping well within the desired frame budget.

![image](http://mattharrison.s3.amazonaws.com/bench2.png)
##

**Comment by ssssssssssss** [comment]
Seems like the shape cache is implemented in 1.7.x releases, but the dirty rects optimization is still missing, any progress here?

**Comment by asturur** [comment]
i left this out since there are better ways to still improve performances.

Dirty rects works good when you have few.objects on canvas. when the canvas is crowded every object touch another and the optinization is not effective.

caching the canvas in a stack of layers (what is under the moving object, what is over) may be more generally effective.

multi selections with stack order preserving can be harder but stil possible.

**Comment by jfahrenkrug** [comment]
@asturur Would you be able to provide an update on the current state of performance improvements? For example, by simply having http://fabricjs.com/test/misc/itext.html open in Chrome without doing anything, my 2018's MacBook Pro's fans are spinning like crazy. Looking at the Chrome profiler shows that it's very frequent calls to `requestAnimationFrame`. Maybe it's an old version of Fabric on that demo page, though. Any update would be appreciated!

**Comment by awehring** [comment]
When I open the itext test page that you referenced, my computer idles along (less tha 5% CPU load).
Tested with IE 11, FireFox 67 on Windows 7. Sorry, no Chrome available.

The page uses the current version 3.0 of fabric.js. You can check `fabric.version` in the browser console.

**Comment by asturur** [comment]
you should get at least 60 request of animation frame per second since there is a blinking cursor somewhere. If you exit that editing text you should get 0 requests and a quiet flame graph

**Comment by jfahrenkrug** [comment]
@asturur Thank you, I'll keep an eye on it. Maybe it was a weird browser glitch I was experiencing.
