### ISSUE TITLE
can't remove objects while iterating over the getObjects() table

### ISSUE THREAD

**Issue by radkujawa** [fabricjs/fabric.js#148]
the following code:

var obj = canvas.getObjects();
$.each(obj, function(i,val){
canvas.remove(val);
}

doesn't clear entire canvas.

**Comment by amitgaur208** [comment]
Its' not fabric JS issue, but its array iteration issue.

**Comment by Asraf-Uddin-Ahmed** [comment]
@amitgaur208 is right. It's an array iteration issue. This code is working pretty well for me.

```javascript
var arrObj = canvas.getObjects();
while(arrObj.length != 0){
  arrObj[0].remove();
}
```
