### ISSUE TITLE
svg gradient issue: gradientTransform is ignored

### ISSUE THREAD

**Issue by afdev82** [fabricjs/fabric.js#1554]
When I try to import the following svg, it seems that the "gradientTransform" is ignored.

``` xml
<svg version="1.0" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     viewBox="0 0 2834.6 2834.6" enable-background="new 0 0 2834.6 2834.6" xml:space="preserve">
<g id="Effect">
  <rect opacity="1.0" fill="#B6C0C6" width="2834.6" height="2834.6"/>
  <radialGradient id="SVGID_2_" cx="458.6157" cy="1137.1204" r="644.0953" fx="494.8075" fy="1386.5354" gradientTransform="matrix(3.321 -0.6998 0.4077 1.9347 -440.9168 -408.0598)" gradientUnits="userSpaceOnUse">
    <stop  offset="0.3301" style="stop-color:#FFFFFF;stop-opacity:0.9"/>
    <stop  offset="0.4549" style="stop-color:#F6F6F6;stop-opacity:0.8"/>
    <stop  offset="0.8525" style="stop-color:#FFFFFF;stop-opacity:0.1"/>
  </radialGradient>
  <rect fill="url(#SVGID_2_)" width="2834.6" height="2834.6"/>
</g>
</svg>
```

I'm using the latest version of fabric.

**Comment by spearsear** [comment]
I also have the requirement to fill a rect with radialgradient with transformGradient. I have the definition of the svg radialgradient defined in an object like this:

{center: {x: 0.5, y:0.5},
 focal: {x: 0.5, y: 0.5},
 radius: 0.1,
 transform: {
   rotate: 0,
   translate: {x: 0,y: 0},
   scale: {x: 1,y: 1}
},
opacity: 0.6,
stops: [
  {offset: '0', color: "rgb(255,255,255)", opacity: 1},
  {offset: '1', color: "rgb(0,0,0)", opacity: 0}
] 

I use fabric.js to dynamicly create radialgradient and fill the rectangle like this:

var rg = {
	type: 'radial',
	x1: center.x,
	y1: center.y,
	r1: 0,
	x2: focal.x,
	y2: focal.y,
	r2: radius * w,

	colorStops: (function(){
		var color_stops = {};
		for(var i=0;i<stops.length;i++){
			color_stops[stops[i].offset] = stops[i].color;
		}
		return color_stops;
	})()
}
var rect = new fabric.Rect({left: x,
	top: y,
	width: w,
	height: h,
	opacity: opacity
});

rect.setGradient('fill', rg);

My question is how to create the gradient with what is specified in gradientTransform?

I tried transform center.x,center.y and focal.x and focal.y, it worked somehow, but the gradient lost its shape. In svg, after gradientTransform, it looked somehow like an ellipse, now in fabric/canvas, it looked like a circle.

Can I create a radialGradient in fabric with a transform matrix?

btw, I also don't understand why canvas createRadialGradient need 2 radius (r1 and r2 parameter), but svg radialgradient only has one radius.

I also noticed canvg also failed to render radialgradient correctly, see issue3 at following link(radialgradient broken)

http://canvg.googlecode.com/svn/trunk/examples/index.htm

Unfortunately, the solution to load the svg as image does not work for me. I am rendering the canvas from a non svg data structure. 

Please help.

**Comment by asturur** [comment]
gradient in canvas requires two radius, while svg just one. This is like that.

FabricJs support gradient transformation trough gradient.transformMatrix attribute.

```
transform: {
   rotate: 0,
   translate: {x: 0,y: 0},
   scale: {x: 1,y: 1}
},
```

This is an identity transformation, it should not get elliptical.
Anyway try like this:
```
var rg = {
    type: 'radial',
    x1: center.x,
    y1: center.y,
    r1: 0,
    x2: focal.x,
    y2: focal.y,
    r2: radius * w,
    transformMatrix: [1,0,0,2,0,0],
    colorStops: (function(){
        var color_stops = {};
        for(var i=0;i<stops.length;i++){
            color_stops[stops[i].offset] = stops[i].color;
        }
        return color_stops;
    })()
}
```

and it should get elliptical on y axis.
(now i do not really remember if this is trasnformMatrix or gradientTransform attribute sorry.

**Comment by asturur** [comment]
in fabricjs there is a function that take this string:

"rotate(0,0.5,0.5) translate(0.02,0.21) scale(1,1)"

and gives you correct matrix.
Search for it in parser.js file.
It is called "parseTransformAttribute" or something similar.

**Comment by spearsear** [comment]
seems to be ignoring both gradientTransform and transformMatrix. I am using fabric 1.5.0

**Comment by asturur** [comment]
please prepare a jsfiddle i will look into it.


2015-07-30 19:40 GMT+02:00 spearsear <notifications@github.com>:

**Comment by spearsear** [comment]
Pls see the jsfiddle, thanks

https://jsfiddle.net/2v0es4xh/25/

**Comment by asturur** [comment]
The problem is that gradientTransform is not evenly supported in all library.
setGradient does not consider it.

After setGradient do this:

your_object.fill.gradientTransform = [a,b,c,d,e,f];

a bug.

**Comment by spearsear** [comment]
Yes, this does it, thanks

**Comment by asturur** [comment]
i will fix the bug anyway.

**Comment by byi-team** [comment]
Hi @asturur

I did start using the GradientTransform property but whenever I apply the color with stop colors to the respective SVG Path, Gradient gets distorted. Can you help me with what I am doing wrong?

I have set up a demo here. https://onlinelogomaker.indiaondesk.com/gradeintdemo/
