### ISSUE TITLE
Text stroke and text shadow render strangely

### ISSUE THREAD

**Issue by pfriedl** [fabricjs/fabric.js#1647]
Hi guys, we're loving Fabric.js right, but we've got a slight issue with text stroke and shadow. Attached is a screen grab from an earlier version of our app where we used raw JS to render text to the canvas. As you can see, the stroke is pretty solid and is an outer stroke.

The next pic is rendered using Fabric, and it looks like the stroke is inner and outer, which in my opinion doesn't look as good. Also, if you apply a shadow to text that has a stroke, it adds the shadow to the stroke, not the combined text and stroke.

Is there a particular setting or method I need to be using to get better text effects? Thanks!

![raw-js-canvas](https://cloud.githubusercontent.com/assets/1180854/4202497/448aaba8-3828-11e4-8b24-8bdfaff17182.png)

![fabric-canvas](https://cloud.githubusercontent.com/assets/1180854/4202500/4d0740d4-3828-11e4-9ad2-0e0a262ca0f6.png)

**Comment by Jossef** [comment]
@pfriedl , @asturur 

Iv'e tried to apply the workaround you came up with, but still the stroke is not outlined as you can see in this jsfiddle <kbd>fabricjs 1.5.0</kbd>:

### http://jsfiddle.net/rno7dynx/1/

any suggestions? 

Thanks!

------

![image](https://cloud.githubusercontent.com/assets/1287098/7218564/984135c2-e67f-11e4-8fb6-fc574cc9f47a.png)

```js
var gCanvas = new fabric.Canvas('canvDraw');
gCanvas.setWidth(500);
gCanvas.setHeight(500);

var myText = new fabric.Text("Some text", {
    top: 80,
    left: 80,
    fontSize: 100
});

myText.setStrokeWidth(4);
myText.setStroke('red');

myText.setFill('blue');
myText.setColor('blue');

gCanvas.add(myText);

```

**Comment by onassar** [comment]
Did anyone here find a solution to this? Running into it now :(

**Comment by asturur** [comment]
i found a solution, i subclassed the text and i changed the render to paint on a temporary canvas in this way:

prepare 2 temporary canvas that is as big as the textobject, considering scaling also.
one canvas is tempCanvas, other is compoCanvas

Fill the text in tempCanvas, remove opacity from the fill.
Now with drawImage copy the tempCanvas on compoCanvas, shadow is disabled, opacity is the multiplication of the global opacity and the opacity of the color you skipped before
Clear tempCanvas
Stroke the text on tempCanvas using the color but without transaparency
now set the globalCompoistionOperation to 'destinaton-out'
fill the text again on tempCanvas using black color
copy with drawImage the result on compoCanvas, using as opacity the global opacity multiplied by the stroke opacity you removed.
Now take compoCanvas, copy it on you real canvas using drawImage, no opacity and set the shadow.

Be carefull of chrome bug for shadow.

**Comment by onassar** [comment]
Yes this seems tricky and not very performative. Do you think you'll be able to share an example / subclasses version?

**Comment by asturur** [comment]
i have to ask to the person for which i made it.

**Comment by onassar** [comment]
Okay

**Comment by asturur** [comment]
shadow on canvas works like that.
Is directional independently of the angle of the object.

You have to write custom code in order to change it.

**Comment by vijaygurjar** [comment]
I have done with text shadow rotation with single object but not able to do with multiple objects rotation.
How to get objects rotation within group in _setShadow function?

**Comment by asturur** [comment]
you should use calcTransformMatrix for each object and then use fabric.util.qrDecompose to get scale and angle and flip.

**Comment by vijaygurjar** [comment]
I have used this way but not sure this is the right way or not because sometime its not updating. I will update if any issue. 
Thanks for your help asturur

**Comment by asturur** [comment]
You could also modify the shouldCache function to do not consider shadow.

In that case shadow will be cached and should be then fixed.

But if shadow has a large offset you would then need to increase cache size calculation
