### ISSUE TITLE
Object setWidth() and setHeight() issue

### ISSUE THREAD

**Issue by PayteR** [fabricjs/fabric.js#167]
i have problem with Fabric.js library that i cant solve for many hours... im trying programaticaly change dimensions of image with methods setWidth() and setHeight() but it didnt work properly, dimensions of control borders are changed fine but image is still in same size, you can see it on screenshot: 

<img src="http://i.stack.imgur.com/7GO7r.jpg">

im using version 0.8.8

**Comment by JuanJ0424** [comment]
I'm experiencing the same issue now but trying to set the height or width of a circle and a custom shape. So far I've tested it with squares, triangles and rectanbles.
