### ISSUE TITLE
'ReferenceError: patternSourceCanvas is not defined' in node.js

### ISSUE THREAD

**Issue by samdoidge** [fabricjs/fabric.js#1707]
Trying to add patterns to my app: `ReferenceError: patternSourceCanvas is not defined` in node.js when trying to create an image - no error in the browser. Code is taken from the [Dynamic Patterns](http://fabricjs.com/dynamic-patterns/) tutorial. 
##

**Comment by minzojian** [comment]
yes,it is true,Pattern in node is not working.
simple test like add a repeat background image like this.

`var src = 'img/checker.png';
canvas.setBackgroundColor({source: src, repeat: 'repeat'}, function () {
  canvas.renderAll();
});`

you will get nothing

**Comment by asturur** [comment]
it may be that nodecanvas lack of pattern support? did you ask on theyr github repository?

**Comment by minzojian** [comment]
yes,think so
going to do that right now

**Comment by asturur** [comment]
can you link this issue? so i can jump there. i always wanted to give a check to node canvas development.

**Comment by minzojian** [comment]
well,i just found node-canvas has soloved and support patter in 2012
https://github.com/Automattic/node-canvas/pull/145
and i just made a simple test like they guys did [there](https://github.com/Automattic/node-canvas/pull/145/commits/9927a3f01c5eb5fdbbe60924427be4e6d9885330)
yes,it works.
so,maybe it is the problem fabric using node-canvas i think

**Comment by minzojian** [comment]
well, pattern is ok,sorry about the fake alert
however,there is still a bug in  __setBgOverlayColor,
changed from
` if (color && color.source) {
        var _this = this;
        fabric.util.loadImage(color.source, function(img) {....`

to

`if (color && color.source) {
            var _this = this;
            if(color instanceof  fabric.Pattern)
            {
                this[property] = color;
                callback && callback();
            }else{
            fabric.util.loadImage(color.source, function (img) {...`

in case user directly set the dynamic pattern as the background

**Comment by mikaelwecode** [comment]
Hello! 

I tried this. And cant get it work. 

I want to do it in node.js. 

I get the same error

`ReferenceError: patternSourceCanvas is not defined`

` let patternSourceCanvas = new fabric.StaticCanvas();
    patternSourceCanvas.add(img);

    const pattern = new fabric.Pattern({
        source: function () {
            patternSourceCanvas.setDimensions({
                width: img.width,
                height: img.height
            });
            return patternSourceCanvas.getElement();
        },
        repeat: 'repeat'
    });

    const rect = new fabric.Rect({
        left: 0,
        top: 0,
        width: size.width,
        height: size.height,
        lockScalingX: true,
        lockScalingY: true,
        lockRotation: true,
        selectable: false,
        evented: false,
        fill: pattern,
    });

    return rect;
`
