### ISSUE TITLE
animation delay

### ISSUE THREAD

**Issue by heaversm** [fabricjs/fabric.js#1719]
Hi - is there a delay parameter for animations? I'm running a javascript loop to add a series of circles to the canvas, and I want them to pop in, but staggered, at a random delay.
##

**Comment by alexiskattan** [comment]
+1

**Comment by yezongyang** [comment]
+1

**Comment by Tsourdox** [comment]
+1

**Comment by charmjeh** [comment]
+1

**Comment by dellvolk** [comment]
+1

**Comment by asturur** [comment]
Are we sure it does not exists today?
