### ISSUE TITLE
window.open(canvas.toDataURL('image/png')); doesn't work in IE9

### ISSUE THREAD

**Issue by collectivetypography** [fabricjs/fabric.js#172]
window.open(canvas.toDataURL('image/png')); works fine in FF and Chrome but not in IE9.

There is a correct URL that begins with "data:image/png;base64" but IE9 doesn't render the PNG…

It is said that IE can do that:
 "Now i am using canvas.toDataURL("image/png")  to get img object of the graph plotted. This method is working fine with chrome and IE9."
source: http://social.msdn.microsoft.com/Forums/en-US/jscript/thread/36177208-25df-4056-bf3f-03413ab1d04c

**Comment by mshivas** [comment]
I ran into this issue. Failed on IE9 until I exported in jpeg format instead of PNG.

var imgURL = canvas.toDataURL({format:'jpeg',height:406, multiplier: 0.5});

**Comment by mshivas** [comment]
I ran into this issue. Failed on IE9 until I exported in jpeg format instead of PNG.

var imgURL = canvas.toDataURL({format:'png',height:406, multiplier: 0.5});  // fails in IE9
var imgURL = canvas.toDataURL({format:'jpeg',height:406, multiplier: 0.5});  // works in IE9
