### ISSUE TITLE
Texture Pattern Brush - SVG pattern image doesn't display in Safari

### ISSUE THREAD

**Issue by mobidev111** [fabricjs/fabric.js#1730]
Loading a SVG texture image works in Chrome browser, however in Safari it only displays a white line instead of the texture pattern.

Demo jsFiddle - open in Safari browser: http://jsfiddle.net/23hLLrkj/1/

Using sample code from free drawing demo: http://fabricjs.com/freedrawing/

``` javascript
   var img = new Image();
    img.src = '../assets/demo.svg'; // SVG goes here

    var texturePatternBrush = new fabric.PatternBrush(canvas);
    texturePatternBrush.source = img;

    canvas.freeDrawingBrush = texturePatternBrush;
```
##

**Comment by karcass** [comment]
I am running into a similar problem with using SVG for fills -- works on Chrome, not on Safari.  I have no trouble loading SVGs for other uses, but they don't work for fills.

**Comment by karcass** [comment]
http://fabricjs.com/kitchensink/#execute-code
```
canvas.clear();
var rect = new fabric.Rect({
  width: 50,
  height: 50,
  left: 50,
  top: 50,
});

var url = 'http://dev.w3.org/SVG/tools/svgweb/samples/svg-files/AJ_Digital_Camera.svg'

fabric.util.loadImage(url, function(img) {
    rect.fill = new fabric.Pattern({
        source: img,
        repeat: 'repeat-x',
    });
    rect.set({
        height: img.height,
        width: 3*(12 * 8),
        stroke: 'rgb(0,0,0)',
    });
    canvas.renderAll();
})
canvas.add(rect);```

**Comment by asturur** [comment]
Still not working on newer safari

**Comment by neopheus** [comment]
http://fabricjs.com/kitchensink

`canvas.clear();
var rect = new fabric.Rect({
  width: 50,
  height: 50,
  left: 50,
  top: 50,
});

var url = 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/AJ_Digital_Camera.svg'

fabric.Image.fromURL(url, function(img) {
    var patternSourceCanvas = new     fabric.StaticCanvas();
    patternSourceCanvas.add(img);
    var pattern = new fabric.Pattern({
      source: function() {
        patternSourceCanvas.setDimensions({
          width: img.getWidth(),
          height: img.getHeight()
        });
        return patternSourceCanvas.getElement();
      },
      repeat: 'repeat'
    });
    rect.set({
        height: img.height,
        width: 3*(12 * 8),
        stroke: 'rgb(0,0,0)',
        fill: pattern
    });

})
canvas.add(rect);`
