### ISSUE TITLE
fabric.Object.prototype.canvas is undefined on extended object

### ISSUE THREAD

**Issue by dmitrirussu** [fabricjs/fabric.js#1732]
I did a class on fabricJs which extend fabric.Object but when I try to call this.canvas it is undefined because on fabric.Object.prototype.canvas attribute is missing.

I solved problem doing on instance of my object 

```
  initialize: func(canvas){  
           fabric.Object.prototype.canvas = canvas
```

Is an other method to call this.canvas on my class?

Thanks

**Comment by mukeshcp** [comment]
Hi kangax,

I am using fabric js version 1.5. While include fabric js into magento & creating canvas, its gives error on Code : CANVAS_INIT_ERROR = new Error('Could not initialize canvas element');

Also if we removed prototype js, then it works fine.

Please find screen-shot of Error code in fabric js.
![image_yv](https://cloud.githubusercontent.com/assets/12266888/14249070/8b80caa2-fa95-11e5-913f-6c1bdbf7f579.png)

Can you please provide me any solution?
