### ISSUE TITLE
Background image not importing after exported canvas is stringified -> parsed

### ISSUE THREAD

**Issue by localhosted** [fabricjs/fabric.js#1733]
This will fail everytime:

```
var json  = canvas.toJSON();
 canvas.clear();

canvas.loadFromJSON(JSON.parse(JSON.stringify(json)), function(){
    canvas.renderAll();
});
```

**Comment by chiraggurav** [comment]
Thanks for help full solution, but i have one more same issues like.. i have store same way json in the database and load that json in other browser at that time background image in not showing. 

so is there any way to store background image with shapes in the json and redraw using json..

**Comment by asturur** [comment]
yes it should work, i think is just an async problem. does the image showup after you click on canvas?

**Comment by chiraggurav** [comment]
No.. image not display after some time or clicking on canvas. what i do just explain.
set background image and create share on canvas and get the json and store it to DB and load this json in different Browser at that time text or other object loaded after the json loading but image not display.. can you suggest me how its work ?
