### ISSUE TITLE
Feature Request: Scaling entire canvas

### ISSUE THREAD

**Issue by jefflembeck** [fabricjs/fabric.js#176]
I'd like to be able to call a function on the fabric.Canvas element in order to make the entire canvas/including all of its objects look like they're being zoomed in upon.

Something like:

var staging = new fabric.Canvas('c');
staging.scale(2.0);

**Comment by devbikshu** [comment]
Hi, 

How do i resize canvas through fabric canvas where i am setting an image of 1920*1080 which will vary dependents on in coming image from another html page. and also i am drawing another logo image on top of canvas. its working good but my desktop is 1366*768 when the incoming image is 1920*1080 or above this its not fitting into my desktop. How to over come this situation and i want to display canvas size as 900*500 but when i export it i should get the original canvas of 1920*1080 with my logo image on top of it.

Here is My Code 
<body>
    <div class="container"> 
<img src="akaka.gif" id="background" class="hide">
        <div style="position: relative;" id="editor">
            <canvas id="canvas" class="img-responsive"></canvas>
        </div>
    </div>
    <div class="container">
        <a class="btn btn-primary" id="save">Save</a>
        <a class="btn btn-primary" id="download">Download</a>
    </div>
</body>
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.4.0/fabric.min.js"></script>
<script>
    $(function () {
        var source = sessionStorage.getItem("source");
        $("#background").attr("src", source);
    });
    setTimeout(function () {
        var myImg = document.querySelector("#background");
        var realWidth = myImg.naturalWidth;
        var realHeight = myImg.naturalHeight;
        $("canvas").attr("width", realWidth);
        $("canvas").attr("height", realHeight);
        var source = document.getElementById('background').src;
        var canvas = new fabric.Canvas('canvas');
        canvas.width=realWidth;
        canvas.height=realHeight;
        var ctx = canvas.getContext('2d');
        var img = new Image();
        img.src = 'images/logo.png';
        var imgInstance = new fabric.Image(img, {
            width: 200
            , height: 45
        });
        canvas.add(imgInstance);
        canvas.setBackgroundImage(source, canvas.renderAll.bind(canvas), {
            backgroundImageOpacity: 0.5
            , backgroundImageStretch: false
        });
        

    }, 2000);
    $("#save").click(function(){
        function blobCallback(iconName) {
            return function (b) {
                var a = document.getElementById('download');
                a.download = iconName + ".jpg";
                a.href = window.URL.createObjectURL(b);
            }
        }
        canvas.toBlob(blobCallback('wallpaper'), 'image/vnd.microsoft.jpg', '-moz-parse-options:format=bmp;bpp=32');
    });
</script>

Thanks
