### ISSUE TITLE
  is fabric.Image.fromURL crossdomain ?

### ISSUE THREAD

**Issue by lucianopes** [fabricjs/fabric.js#1779]
Using this code :
  fabric.Image.fromURL(link_img, function(img) {
         canvas.add(img);
    });

where  link_img is a link to URL of the image all works if the image is under  my site but is not working if URL is from another site. Is the function crossdomain or i have to use another function ?

**Comment by wrteam-sagar** [comment]
after adding 

> Please as questions on google groups or stackoverflow.
> 
> ```js
> fabric.Image.fromURL(url, function (img) {
>   ...
> }, {crossOrigin: "anonymous"});
> ```

after addiing this image is not loading due to cors error. Tried to add CORS headers on which domain the site is requesting a file. but still getting cors error
