### ISSUE TITLE
fabric.Canvas.loadFromJSON callback function not working

### ISSUE THREAD

**Issue by Kienz** [fabricjs/fabric.js#184]
Since the new version of fabric (0.8.25) the callback function of loadFromJSON() didn't work.
You can see this behavior here: 
http://jsfiddle.net/Kienz/RcgWS/1/

If you use the fabric version 0.8.21 the callback function works as expected

**Comment by jwbats** [comment]
I just ran into this issue in version 2.2.2. The loadFromJSON() callback isn't firing at all. Not even with simple json that does not contain a background image.

Here's the code:

		var json = '{ "version":"2.2.2", "background":"green" }';

		canvas.loadFromJSON(json, canvas.renderAll.bind(canvas), function(o, object) {
			console.log('loadfromjson'); // this does not get printed to the console
		});

**Comment by asturur** [comment]
the callback in your case is canvas.renderAll.bind(canvas).

the other function is the reviver, and gets called when there are objects or background/overlay images.

**Comment by jwbats** [comment]
I hadn't heard of revivers before. The function isn't firing when I add a background image and a circle object. I'm finding other events to do the stuff I want to do, though. I'll make sure to study the documentation a bit more to learn how the latest fabricjs works. Tnx.

**Comment by jwbats** [comment]
The 'canvas.renderAll.bind(canvas)' seems to be the standard callback parameter for the loadFromJSON() function.

The bind call yields a new renderAll function with the canvas bound to its context.

Why is this necessary? Why not just a regular renderAll() (or requestRenderAll()) call?

I call requestRenderAll() in plenty of other places in my code, without explicitly passing it the canvas itself as context. Why would it need that, anyway? The method is on the fabric canvas already.

**Comment by asturur** [comment]
canvas.renderAll.bind... is not default of anything. It has been used in a couple of examples and people copied in more and more places.

if you save a reference to canvas.renderAll and you call it from a callback, that is unbound. you can just create a function and inside that function call canvas.renderAll and you do not need to bind it at all.

I also think that loadFromJSON renders by itself and does not need that callback

**Comment by asturur** [comment]
You should just pass your custom function to the callback, with your custom code

**Comment by jwbats** [comment]
Tnx, I'm doing it like that and it works well.

But why does the loadFromJson documentation show us this canvas-bound render call?

I do not see the point of it.

**Comment by jwbats** [comment]
You're trying to say it made sense then, but now it's pointless?

**Comment by asturur** [comment]
well is something that people take as a rule and is pointless for that.

I think at some point the loadFromJson has been made render by itself and calling render in the callback is useless. Also calling it in that way is worse because people may miss the point of having a custom callback.

Also fabricjs 2 has for its own needs a Canvas.renderAndResetBound function that is already bound to the instance

**Comment by jwbats** [comment]
Thanks for the clarifications.
