### ISSUE TITLE
Canvas setLeft and setTop

### ISSUE THREAD

**Issue by lorenzopolidori** [fabricjs/fabric.js#1841]
I might have missed something, but is there any particular reason why there is no method to set the position of the canvas programmatically?

Something similar to `setWidth` and `setHeight` like the following:

``` javascript
setLeft: function (value, options) {
    return this.setDimensions({ left: value }, options);
},
setTop: function (value, options) {
    return this.setDimensions({ top: value }, options);
},
```

**Comment by rororoororor** [comment]
These are deprecated in v 2.0 right?

**Comment by rororoororor** [comment]
I even can't find these in the doc.

**Comment by letmeeeeeee** [comment]
> I even can't find these in the doc.

I think you are right. So I used the set method to solve the problem.
