### ISSUE TITLE
Add support for percent-based canvas dimensions

### ISSUE THREAD

**Issue by myselfgaurav** [fabricjs/fabric.js#1858]
see http://liveweave.com/BHULSo

i had issue with using height and width in % to take size of parent window.

you can see first canvas does not covers whole td(in red background) while 2nd covers whole td( in yellow background)

this problem occurs only when i use js code
<code>
(function () {
    var canvas = new fabric.Canvas('canvas');
    var canvas_el = document.getElementById('canvas');
  canvas.backgroundColor ='red';
    canvas.renderAll();
})();
</code>
when i remove js code both canvas works fine why so does fabric js is adding some styles why so ??. how to make it work
##

**Comment by jagi** [comment]
If you want to fill up container with canvas you can use something like this http://liveweave.com/6EOOBA
I think that supporting canvas element size in percentages is not the case. Canvas is for graphics rendering and this is done in pixels. You can of course scale element to example you have canvas 100px by 100px in size and you want to stretch it to fill container of size 200px by 200px. But it would blur canvas out.

**Comment by ShaMan123** [comment]
#1270
