### ISSUE TITLE
[Question] Event listener 'selection:*' for iText Elements

### ISSUE THREAD

**Issue by josesayago** [fabricjs/fabric.js#1865]
Hello, I'm new to FabricJS (coming from KineticJS) and I'm wondering if there are events triggered when text elements are selected and deselected. 

I read [Working with events](https://github.com/kangax/fabric.js/wiki/Working-with-events) where there are `object:selected` and `selection:cleared` being triggered whenever an object is selected and deselected, however they are not triggered for text elements:

![object-events](https://cloud.githubusercontent.com/assets/2735947/5233383/f7b975e0-774f-11e4-877c-251a771cb94b.png)

Adding listeners for deselection on stage nor for iText objects trigger these events. I am trying to add a floating menu when text elements are selected (I solved this issue detecting `mousedown` event whenever an iText object is clicked), however due to `selection:cleared` not being triggered I cannot make them disappear (screenshot below).

![menu](https://cloud.githubusercontent.com/assets/2735947/5233398/e42400f8-7750-11e4-891f-519026d3c381.png)

What is the recommended way of doing this? Should I detect click events on stage through JavaScript to remove appended elements? or is there a better way of doing this using native FabricJS methods.

Thanks in advance for your help.

**Comment by Manoj-Roy** [comment]
Thanks its really helpful ..
