### ISSUE TITLE
[Question] Drawing images from buffer in fabric.js on the server

### ISSUE THREAD

**Issue by lukejagodzinski** [fabricjs/fabric.js#1867]
Hi, I'm trying to draw images on canvas created with _fabric.js_.

``` js
var canvas = fabric.createCanvasForNode(200, 200);
```

I create those images from node buffer

``` js
var Image = Canvas.Image;
var img = new Image;
img.src = fs.readFileSync('image.png');
```

and draw them on canvas

``` js
var ctx = canvas.nodeCanvas.getContext('2d');
ctx.drawImage(img, 0, 0);
```

Later any call to _fabric.js_ canvas clears out my context.

``` js
var oImg = new fabric.Image(/* I can't create image object from node buffer */);
oImg.set({
    left: 100,
    top: 100,
});
canvas.add(oImg);
```

Is there any option to use node buffers to draw images?

EDIT:
I've found here https://github.com/kangax/fabric.js/blob/master/src/node.js#L72 that there is a way for creating `Image` object from buffer but I have to pass `context` object. What context?

EDIT2:

I've found solution:

``` js
var Image = Canvas.Image;
var img = new Image;
img.src = fs.readFileSync('image.png');
var oImg = new fabric.Image(img);
canvas.add(oImg);
```

It would be nice to give such information in the documentation :)

**Comment by albertyou2** [comment]
@jagi have you found out the solution?

**Comment by jagi** [comment]
@albertyou2 I've found solution and it's in the first post **EDIT2**

**Comment by Climax777** [comment]
Is this method still valid?

**Comment by asturur** [comment]
Now that fabricjs use nodecanvas 2 and newer jsdom you can use browser like code to handle images under node.

Can you explain your use case and show what are you trying to do?

**Comment by Climax777** [comment]
> Can you explain your use case and show what are you trying to do?
Much like the OP, I would like to load a background image onto a canvas from a node `Buffer`. I would prefer not te have an additional dependency to nodecanvas but rather just rely on fabricjs. How would EDIT2 from OP look with what you mention?

**Comment by asturur** [comment]
So node-canvas is necessary. Node does not have a canvas, fabricJS would not work at all.
To load an image from a buffer i think you can create a new image like this:

```
var image = new Image(); // get you a JS image
var nodeCanvasImage = fabric.util.getNodeCanvas(image); // give you access to the node canvas substrate
// read docs on how to put a buffer there but i think is nodeCanvasImage.scr = nodebuffer
// then create a fabric.Image from that original image
var fabricImage = new fabricImage(image);
```

**Comment by Climax777** [comment]
> So node-canvas is necessary. Node does not have a canvas, fabricJS would not work at all.
> To load an image from a buffer i think you can create a new image like this:
> 
> ```
> var image = new Image(); // get you a JS image
> var nodeCanvasImage = fabric.util.getNodeCanvas(image); // give you access to the node canvas substrate
> // read docs on how to put a buffer there but i think is nodeCanvasImage.scr = nodebuffer
> // then create a fabric.Image from that original image
> var fabricImage = new fabricImage(image);
> ```

Thanks, does this mean my application needs to import node-canvas too, or can I get all the requirements from fabricjs's own import of node-canvas/jsdom?

To be more specific, you call in line 1:
```
var image = new Image(); // Where does this come from?
```

Should I add node-canvas as a dependency of my own to get `Canvas.Image()` like in OP. Or can I create the Image element from fabricjs?

**Comment by asturur** [comment]
Sorry i was not as explicative as i should be.
You better use standard fabric installation that will provide JSDOM and NODECANVAS.
jsdom will make possible for you to do

var image = fabric.document.createElement('img');

This will make JSDOM create a img-like structure in javascript and will like to it the node-canvas layer.
I think you can still load the buffer with the example i provided before.

The point is that fabric could do some kind of assumption on the html api of the image or canvas element and JSDOM will emulate that, while node-canvas alone will not.

**Comment by Alex-Golovin** [comment]
works for me:

```
const pageImageBase64 = 'data:image/png;base64,' + buffer.toString('base64')

  fabric.Image.fromURL(pageImageBase64, function(img) {
    img.set({ top: 0, left: 0 })
    canvas.add(img)

    // do other things
  })
```
