### ISSUE TITLE
how can i download Kitchensink fabric demo

### ISSUE THREAD

**Issue by urcoder** [fabricjs/fabric.js#1870]
how can i get a copy from your demos especially
Kitchensink fabric demo
http://fabricjs.com/kitchensink/

**Comment by keremdemirer** [comment]
Found a fiddle [here](http://jsfiddle.net/zmWs4/)

**Comment by ilyaskuzu** [comment]
i have created a repo for kitchensink. 
you can check it here: https://github.com/ilyaskuzu/fabricjs_kitchensink

**Comment by asturur** [comment]
also: https://github.com/fabricjs/fabricjs.com
