### ISSUE TITLE
Disabling the multi object selection by mouse down and move

### ISSUE THREAD

**Issue by grunzmeniroj** [fabricjs/fabric.js#1887]
I want to disable the dash lines that appears on mousedown and move on canvas and also the selection that it performs, but i don't want to disable the multi-object selection by holding shift and mouse click on object.......

canvas.selection=false is disabling both...
Is this possible ... if so how can I achieve it.....

**Comment by rudevich** [comment]
@gruzmeniroj @kangax sorry, but is that question answered?
