### ISSUE TITLE
Rendering Large Images

### ISSUE THREAD

**Issue by TimHarker** [fabricjs/fabric.js#1912]
Rendering the attached image to the canvas does not work...

``` js
fabric.Image.fromURL(largeImage, function (oImg) {
    canvas.add(oImg).setActiveObject(oImg);
    canvas.calcOffset();
}, {
    originX: 'center',
    originY: 'center'
});
```

![test](https://cloud.githubusercontent.com/assets/5775607/5565646/614a4620-8ed3-11e4-9d2a-a5e10232242f.png)

**Comment by asturur** [comment]
without knowing wich is the purpouse of a very large image on the canvas, consider the possibility to apply a static resize filter on it while loading. you can still export later the original one depending on the purpose of your application.

this won t solve the bug and is not proposed as a general solution for perfomance gain. but if you are working on a 700x700 canvas and you have a 4000x3000 image creating you problems, consider resize it with .applyFilters() once before addinit on the canvas.
