### ISSUE TITLE
Custom fonts and _initDimensions in Fabric.js for Node

### ISSUE THREAD

**Issue by lukejagodzinski** [fabricjs/fabric.js#1924]
I think that after last update of Fabric.js for Node.js there was a change in function `fabric.Text.prototype._initDimensions`. In effect when working with custom fonts and calculating dimension of font, calculations are made on new canvas without fonts that was added using `ctx.addFont(font)`. So I've made fix for fabric so that any context shares the same fonts list. I think it should be merged into Fabric.js. I can create pull request. Here is the code.

``` js
var sharedFonts = null;

var getContext = Canvas.prototype.getContext;

Canvas.prototype.getContext = function () {
  var ctx = getContext.apply(this, arguments);

  ctx._fonts = sharedFonts;

  return ctx;
};

var addFont = Canvas.Context2d.prototype.addFont;

Canvas.Context2d.prototype.addFont = function () {
  addFont.apply(this, arguments);

  sharedFonts = this._fonts;
};
```
##

**Comment by asturur** [comment]
there is some ongoing work on text class. do not create a different pr now, i will try to take care of this suggestion in the open pr.

**Comment by jagi** [comment]
Ok so I will wait

**Comment by raphaeleidus** [comment]
OMG thank you so much for this snippet. This just saved me.

**Comment by raphaeleidus** [comment]
anyone know if this is fixed in fabric 2?

**Comment by jfizz** [comment]
it is still an issue in fabric 2
