### ISSUE TITLE
Italics does not work in Node.

### ISSUE THREAD

**Issue by sweetsmurph** [fabricjs/fabric.js#1946]
So I created this application using fabric.js (love it btw. It has made my job a lot easier).
(Link to project: http://markmaster.no/designs/stickercolor )

Basically you design your own stickers. However, when the stickers are being rendered for the printer, it goes through fabric on node (I just load the sticker JSON information). Everything here works fine, except italic. For some reason it will not load italic fonts (it has no problem with bold etc.) What could cause this?

This is how I add the fonts in node.
var crimsonFont = new canvas.Font('crimsontextttf', '/var/www/html/markmaster/public/css/fonts/crimsontext-roman-webfont.ttf');
crimsonFont.addFace('/var/www/html/markmaster/public/css/fonts/crimsontext-bold-webfont.ttf', 'bold');
crimsonFont.addFace('/var/www/html/markmaster/public/css/fonts/crimsontext-italic-webfont.ttf', 'normal', 'italic');
crimsonFont.addFace('/var/www/html/markmaster/public/css/fonts/crimsontext-bolditalic-webfont.ttf', 'bold', 'italic');
canvas.contextTop.addFont(crimsonFont);
##

**Comment by maxim-torba** [comment]
I’m having this issue in fabric@3.1.0, is there any updates on this?

**Comment by asturur** [comment]
Italic do works in node.
Do you have availability of both the normal and italic fonts and are you loading the correctly?

**Comment by maxim-torba** [comment]
Yes, and everything fine in browser and if i generating svg image. 
But if i saving it like this `canvas.createPNGStream();` - italic losing. 
This happens even on Times New Roman.
How i register fonts: 
`fabric.nodeCanvas.registerFont(fontPath, {family: font.name});
  fabric.fontPaths[``${font.name}``] = font.url;`

SVG export:
<img width="494" alt="Screen Shot 2019-06-21 at 1 17 17 PM" src="https://user-images.githubusercontent.com/16847194/59916100-edc09480-9426-11e9-9e40-bb4f7e1771c1.png">

PNG export:
<img width="491" alt="Screen Shot 2019-06-21 at 1 17 24 PM" src="https://user-images.githubusercontent.com/16847194/59916120-fa44ed00-9426-11e9-8536-c5bb6ed838bb.png">

**Comment by asturur** [comment]
you have to register the italic too.
Either include the weight in the registration or assign a specific font-family name to the italic version.

**Comment by maxim-torba** [comment]
okay, thanks.
Wont it work if i do something like this:
`fabric.nodeCanvas.registerFont(fontPath, {family: font.name, weight: 'regular', style: 'normal'});
        fabric.nodeCanvas.registerFont(fontPath, {family: font.name, weight: 'bold', style: 'normal'});
        fabric.nodeCanvas.registerFont(fontPath, {family: font.name, weight: 'regular', style: 'italic'});
        fabric.nodeCanvas.registerFont(fontPath, {family: font.name, weight: 'bold', style: 'italic'});`
for the same font? 
What I mean, is it work like in browser? (which automatically apply fonts style)

**Comment by asturur** [comment]
it should work provided you ha 4 different files and privided you do before creating the canvas

**Comment by asturur** [comment]
( unsure why the latter limotation)
