### ISSUE TITLE
IE: SCRIPT5022: SecurityError

### ISSUE THREAD

**Issue by LIDJungle** [fabricjs/fabric.js#1957]
SCRIPT5022: SecurityError 
fabric.js, line 18466 character 11

This happens when I have saved a presentation with images. Looks to be a CORS error, but I'm on the same server.

Here is the JSON for the offending presentation. I am on shineemc.com, but the error is thrown when trying to load the "awesome_tiger" SVG. This code all works fine in Firefox or Chrome.

Does anyone know a workaround for this issue?

JSON:
`{"objects":[{"type":"image","originX":"left","originY":"top","left":107.46325411445987,"top":22.34196846601907,"width":900,"height":900,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":0.03649580141518866,"scaleY":0.03611752386062922,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","src":"http://shineemc.com/shine/stock/awesome_tiger.svg","filters":[{"type":"Pixelate","blocksize":1}],"crossOrigin":""},{"type":"image","originX":"left","originY":"top","left":3.667444098649749,"top":23.26017963861261,"width":900,"height":900,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":0.03684055774117561,"scaleY":0.03396535896085542,"angle":0,"flipX":true,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","src":"http://shineemc.com/shine/stock/awesome_tiger.svg","filters":[{"type":"Pixelate","blocksize":1}],"crossOrigin":""},{"type":"i-text","originX":"left","originY":"top","left":29.757250393282494,"top":48.622734977019064,"width":271.24658203125,"height":63.7,"fill":"#ffff00","stroke":"#ff8000","strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":0.31032712544298274,"scaleY":0.39577553933369664,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","text":"Chinese Food","fontSize":49,"fontWeight":"normal","fontFamily":"amaranthregular","fontStyle":"","lineHeight":1.3,"textDecoration":"","textAlign":"left","path":null,"textBackgroundColor":"","useNative":true,"styles":{}},{"type":"i-text","originX":"left","originY":"top","left":10.5621952727132,"top":-3.2599591590493056,"width":361.78173828125,"height":63.7,"fill":"#ffffff","stroke":"#ff8000","strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":0.3387039547159154,"scaleY":0.4314281344568717,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","text":"Roaring Tigers","fontSize":49,"fontWeight":"normal","fontFamily":"paloaltoheavy","fontStyle":"","lineHeight":1.3,"textDecoration":"","textAlign":"left","path":null,"textBackgroundColor":"","useNative":true,"styles":{}},{"type":"i-text","originX":"left","originY":"top","left":45.1776410691081,"top":26.690915614716108,"width":173.701171875,"height":63.7,"fill":"#ff0000","stroke":"#000000","strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":0.3070655868305623,"scaleY":0.3763976686824566,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","text":"Drive Thru","fontSize":49,"fontWeight":"normal","fontFamily":"boogaloo","fontStyle":"","lineHeight":1.3,"textDecoration":"","textAlign":"left","path":null,"textBackgroundColor":"","useNative":true,"styles":{}}],"background":"#d4d4d4"}`

Save: 
       `$.ajax({
        type: 'POST',
        url: 'data/fabric/save.php',
        data: {
            task: 'save',
            img: canvas.toDataURL('png'),
            json: JSON.stringify(canvas.toJSON(['transition'])),
            name: name,
            coid: companyId,
            id: currPresId,
            presId: 0
        },
        success: function(json) {
            console.log("success callback fired.");
            if (!json.success) {
                alert('Error!'); return;
            } else {
                scope.dialog('savePresentation', "Presentation saved!", 600, 'auto');
                currPresId = '';
                scope.listPresentations();
                scope.getApprovalList();
                $('#presName').text(name);
                zoomIt(oldZoom);
                setTimeout(function () {
                    scope.closeDialog('savePresentation');
                    scope.$apply();
                }, 2000);
            }
        }
    });`
Load:
    `$.ajax({
        type: 'GET',
        url: 'data/fabric/loadPresentation.php',
        data: {
            id: id,
            t: t
        },
        success: function(data) {
            var j = JSON.parse(data.json);
            currPresName = data.name;
            $('#presName').text(currPresName);
            currPresId = data.id;
            origPresId = data.presId;
            canvas.loadFromJSON(j);
            canvas.transition = j.transition;
            $('#bgcolor').val(canvas.backgroundColor);  
        }
    });`
##

**Comment by kangax** [comment]
@dstorey @jacobrossi @jonathansampson folks, any idea what this is about?

**Comment by LIDJungle** [comment]
Just to update since I've been looking into this today:

The error above happens in IE 10. In IE 11, I get SCRIPT5022: IndexSizeError, still at fabric.js, line 18466 character 11.

I have gone through and set (verified) my headers to allow cross scripting.

SCRIPT5022: SecurityError  - IE 10 only. The official docs say it's a CORS error. I have origin control set up in the headers, and I'm not on a different domain.

SCRIPT5022: IndexSizeError - IE 11. 

It seems to only happen with SVG files. Using PNG images works as expected.

http://wecanbeaoriginal.com/blog/wp-content/uploads/2011/05/Butterfly.zip

Tested with this "butterfly.svg" and when I try to save:

SCRIPT5022: SecurityError 
fabric.js, line 10074 character 5

json:
`{"objects":[{"type":"image","originX":"left","originY":"top","left":0,"top":0,"width":504,"height":504,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":0.14653465346534652,"scaleY":0.14653465346534652,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","src":"http://shineemc.com/shine/user/28/Butterfly.svg","filters":[],"crossOrigin":"","alignX":"none","alignY":"none","meetOrSlice":"meet"}],"background":"#8000ff"}`

**Comment by asturur** [comment]
i had same issue when the data to load was in upper level directory than my javascript.
example:

www.mydomain.com/data/images/
www.mydomain.com/website/app/js/fabric.js
Accessing images with ../../../data/images/something.svg
Was throwing out CORS errors


What do you have at line 18466 character 11?

**Comment by LIDJungle** [comment]
The line with the arrow in front of it:

>/**
>     * Applies filter to canvas element
>     * @param {Object} canvasEl Canvas element to apply filter to
>     */
>    applyTo: function(canvasEl) {
>      var context = canvasEl.getContext('2d'),
> -->          imageData = context.getImageData(0, 0, canvasEl.width, canvasEl.height),
>          data = imageData.data,
>          iLen = imageData.height,
>          jLen = imageData.width,
>          index, i, j, r, g, b, a;

The other error, when trying to save an SVG is:
SCRIPT5022: SecurityError 
fabric.js, line 10074 character 5

>__toDataURL: function(format, quality, cropping) {
>    this.renderAll(true);
>    var canvasEl = this.upperCanvasEl || this.lowerCanvasEl,
>        croppedCanvasEl = this.__getCroppedCanvas(canvasEl, cropping);
>    // to avoid common confusion https://github.com/kangax/fabric.js/issues/806
>    if (format === 'jpg') {
>      format = 'jpeg';
>    }
> -->    var data = (fabric.StaticCanvas.supports('toDataURLWithQuality'))
>              ? (croppedCanvasEl || canvasEl).toDataURL('image/' + format, quality)
>              : (croppedCanvasEl || canvasEl).toDataURL('image/' + format);

**Comment by jonathansampson** [comment]
@LIDJungle Could you please set up a small demo that shows the issue? I'd like to investigate further and open an issue internally for the Internet Explorer team if necessary.

**Comment by LIDJungle** [comment]
The problem with setting up a demo is that I don't know how to expose a CORS error on JSFiddle.

Maybe this is the next best thing:
http://shineemc.com/shine/index.php

I have a demo account set up:
uname: jshipp@holidaysigns.com
pass: j

From there, click on "Playlists" in the top nav. The top presentation should be named "Tiger1". You can edit that. Click on "Add Image", and in the file browser choose the folder "Stock" and you should see the "Awesome_tiger.svg". You should get the error when trying to add that to the canvas.

**Comment by taveras** [comment]
I have verified this issue in IE. All other browsers work normally, even IE9! IE10 throws a 'Security Error' when loading these images. The images in my scenario are served from a different origin, but with proper CORS permissions set. Doing some research, I found this: 
#908 also references this issue, but was closed as IE10 claims support for CORS, but it is known that full-support for CORS is not present in IE10. CORS for canvas images is not present.

http://stackoverflow.com/questions/18112047/canvas-todataurl-working-in-all-browsers-except-ie10

**Comment by StephanBijzitter** [comment]
Our customers have been reporting that our entire application is stuck at loading on 0%.

After some research, we found that we could reproduce this on IE11 and Edge (did not try IE10).

The specific error, in Edge would be `SCRIPT5022 IndexSizeError`, which according to the stacktrace is a result of the following call: https://github.com/kangax/fabric.js/blob/9422fd39bebb7e2f07fcc44e29eec71f61b6eff5/src/shapes/image.class.js#L480

IE11 gives a different error: `"Bad argument"`, but also leads to the same stacktrace.

Still doing more research, because we simply have to solve this.

**Comment by asturur** [comment]
what version of fabric are you using?

**Comment by asturur** [comment]
take care that ie11 does not handle very good image coordinates with decimals.

**Comment by StephanBijzitter** [comment]
We are using a modified version of fabric 1.6.2

We have mask for images (that clip them into a shape), but also "complex" masks, that also add an SVG or PNG overlay on the image. We found the following steps lead to reproduction:

* Start with a clear canvas - just to be sure
* Add two photos to the front of the card - slightly modified from fabric
* Add one complex mask to either of the photos - modified from fabric
* Save the state of the canvas - just turns it into json and saves on the server
* Reload the page - it will load the json and crash while adding it to the canvas

So, we're making progress...
