### ISSUE TITLE
Overlay image resize

### ISSUE THREAD

**Issue by maevelevie** [fabricjs/fabric.js#204]
First of all - thanks for putting all this work into Fabric.js. I didn't know it existed until a few weeks ago, and it makes working with canvases a LOT better and easier.

The only thing I missed was the option to size the overlay image according to the canvas side. I'm trying to make a canvas editor that resizes automatically when the window is resized, and I tried quite a lot of options to resize the overlay image client-side before I realised I could simply change the function.

I only added a quick fix to suit my needs, changing this line twice:
   (this.contextTop || this.contextContainer).drawImage(this.overlayImage, 0, 0, this.width, this.height);
...but perhaps it would be an idea to include this as an option in a future version?

-Kevin

**Comment by deepanjandas** [comment]
#jaydenseric - It would be great if you can throw some light as to how did you implement the overlayImageWidth and overlayImageHeight.

Thanks in advance.
Deepanjan

**Comment by zaus** [comment]
@deepanjandas I think you meant to tag @jaydenseric
