### ISSUE TITLE
Issue with text flipping

### ISSUE THREAD

**Issue by anhle82** [fabricjs/fabric.js#2067]
Hi Kangax,

I found a bug with text flipping. After text was flipped using setFlipX(), json encode and generate image via server side, the text position is moved to the left. You can recreate this same issue at your website http://printio.ru. Seem like issue is related to this function _getLeftOffset() from text object class.

Attached is image before and after i flipped the top hello world text

![flipxbug](https://cloud.githubusercontent.com/assets/1724645/6907236/1d750fe2-d6fa-11e4-99c1-9a560e7d9ff2.jpg)
##

**Comment by kangax** [comment]
I think this is related to Node.js flipping behavior

**Comment by asturur** [comment]
added a test and looks like on current version text flipping is ok.
