### ISSUE TITLE
How to add a point to polygon dynamically

### ISSUE THREAD

**Issue by johnbayne** [fabricjs/fabric.js#2197]
I'm using fabricJS to create polygons with a size of 1px \* 1px. As the user clicks around the canvas, new points are added to the existing polygon, expanding the width & height.

Because fabric counts the center as the origin for polygons, in order to prevent the polygon jumping around, I have to manually set the left & top offsets of the shape by running:

``` javascript
shape.left = (initial_left_offset - shape.width/2)
shape.top = (initial_top_offset - shape.width/2)
```

after adding each point. This works fine.

The problem is with the bounding/controls box. The middle of the box is set at the origin (first point) of the polygon, and as much as I try to offset it with "+ shape.width/2", the blue controls box won't move. It expands in width & height correctly as I add new points, but the middle of the box is always set to origin. Failed attempts so far:
- calling shape.setCoords()
- Overriding .setCoords & manually returning tr, tl, br, bl etc values with new coordinates (box still doesn't move)
- Manually setting shape.oCoords & then running shape._setCornerCoords(). Still won't budge

If anyone has ideas on how I can ensure the bounding box is set correctly after changing the height & width of the corresponding shape, I'd be appreciative. Despite references to "controls" in the above, I don't actually need to use the control box - I just need to be able to pick up mouse:over events (with perPixelTargetFind) across the entire image instead of the bits within the incorrectly-offset bounding box. :-)
##

**Comment by asturur** [comment]
Would you share a jsfiddle with your current code? It would be easier for me to help with some comments in the code and some tries other than trying to explain something in which my english level will probably be the biggest enemy.

There is something weird in polygons, so there is some issue in this and is not your fault.

**Comment by johnbayne** [comment]
Many thanks for the quick response, @asturur - jsfiddle.net is down (went down halfway through my fiddle)...I still need to extract a bunch of backbone/rails models/views. Will do within the next few hours, assuming fiddle gets back up.

**Comment by johnbayne** [comment]
@asturur Apologies for the delay. A quick-n-dirty example of the problem is shown here: https://jsfiddle.net/sloop_john_b/rgppry56/11/

If you click 3 times at different points on the canvas to create a minimal polyon, you'll notice the blue controls box seems to be the correct width/height, but it's center is set to the origin of the polygon, which leaves much of the polygon outside its bounds. Hoping to find a way to get that blue box (or at least, the bounding box) to encapsulate the whole shape. ...I can get around it by removing the existing polygon & creating a new one each time a point is added, but I'm hoping not to have to do that. :-)

**Comment by asturur** [comment]
https://jsfiddle.net/rgppry56/15/

I had to convert in js, i cannot use coffescript.

This is a example of how you could do.
If you also move the polygon, you see it does not work good.

There is a problem with current implementation (my fault) about the offsetting of points.
I think that maybe is better to add canvas translate and stop offsetting the points.

**Comment by johnbayne** [comment]
Thanks @asturur - unfortunately I will need movement as well. At present, I'm destroying the shape & recreating upon addition of any new elements. I suspect that may be the best option.

Admittedly I'm new to fabric, but I fear canvas translation may get confusing considering there will be multiple shapes(?) upon the canvas.

I'll stick with destroy/recreate for now - thanks for the help.

**Comment by lirmont** [comment]
You can prevent jumping by putting the polygon beneath a group: https://jsfiddle.net/rgppry56/17/

**Comment by johnbayne** [comment]
Thanks @lirmont - it certainly works as intended re: jumping, but the bounding box still won't encapsulate the shape correctly.

**Comment by orian** [comment]
Can we reopen this bug? The fabric.Polyline and fabric.Polygon still doesn't work properly when adding points dynamically.

**Comment by butch2k** [comment]
While the fix at: https://jsfiddle.net/rgppry56/15/ works perfectly on fabric 1.5, fabric 1.6.0 broke it again as underlined by this fiddle https://jsfiddle.net/butch2k/rgppry56/30/

**Comment by asturur** [comment]
to add point dynamically now that the points are not changed anymore, should be very easy.

Add a point to the array and everytime remove the old polygon and create a new one.
https://jsfiddle.net/rgppry56/31/
