### ISSUE TITLE
Add Undo and Redo  suppoert

### ISSUE THREAD

**Issue by rizwanullah** [fabricjs/fabric.js#23]
I want to use this library but main feature of my application is undo & redo,Can you please guide me  how  could I handle it as you people did in http://printio.ru/ringer_man_tees/new

Regards,
Rizwan Ullah
jeerizwan@gmail.com

**Comment by piyush-avantsoft** [comment]
1.) Anything new about undo/redo feature?
2.) is there anyway to fire custom events on canvas of fabricjs?

**Comment by chrisrickard** [comment]
I am allowing the user to remove the last added path (in my painting application), this works fine for me:

    `var lastItemIndex = (fabricCanvas.getObjects().length - 1);
    var item = fabricCanvas.item(lastItemIndex);

    if(item.get('type') === 'path') {
      fabricCanvas.remove(item);
      fabricCanvas.renderAll();
    }`

But you could just as easily remove that IF statement and allow them to remove anything.

**Comment by jadhavanant85** [comment]
@chrisrickard great work for me for undo

**Comment by lukluk** [comment]
cool

2015-06-10 15:14 GMT+07:00 Anant <notifications@github.com>:

> @chrisrickard <https://github.com/chrisrickard> great work for me for undo
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kangax/fabric.js/issues/23#issuecomment-110645903>.
>



-- 
Lukluk Luhuring S. S.Kom, MT
Software Engineer / Seminar Speaker

**Comment by stormbreakers** [comment]
do we have state present in when an object is added or moved

**Comment by Elvinas** [comment]
Yes, you can look up here: http://fabricjs.com/events/ There's event inspector and you can observe these events.

**Comment by stormbreakers** [comment]
has any one done undo feature on a group object

**Comment by dshep4** [comment]
+1

**Comment by dineshsinghchauhan** [comment]
@luklukls  your link overlayme.com/page/app/xindex.php not working can you please share the updated link of app

**Comment by paulcredmond** [comment]
Any update on this? It would be great to have this as a separate module.

**Comment by piyush-dholariya** [comment]
No fabric.js framework is now deprecated, so no longer is in more use. hence seems so one updating any features,

**Comment by asturur** [comment]
"deprecated" by who?

**Comment by asturur** [comment]
@paulcredmond  undo redo feature can be built with fromObject/ toObject.
Is not as straight forward as it seems, but is not something that with the actual team we can support.

**Comment by AlexanderIstomin** [comment]
i wrote undo/redo functions little lite ago. Here is fiddle:
https://jsfiddle.net/AlexanderIstomin/8y92ceuf/
sorry for messy code - just copied pieces from my project

**Comment by krishnaisdinesh** [comment]
@AlexanderIstomin One click in both direction is false.

**Comment by abhi06991** [comment]
I have implemented Undo Redo using Canvas states. Take a look. Could be useful to someone
https://github.com/abhi06991/Undo-Redo-Fabricjs

**Comment by hazeeb** [comment]
Any update on this ?

**Comment by asturur** [comment]
Undo redo is a specific application feature and not a canvas one. It won t be part of fabric.js

**Comment by paulcredmond** [comment]
I made an implementation of this as well if it's useful for anyone: https://github.com/paulcredmond/fabric-undoredo

**Comment by vxrai** [comment]
To track the state, I'm using JSON.stringify(canvas) and canvas.loadFromJSON() and have an event registered on the object:modified to capture the state. 
I just wanted to know if pushing the entire json of the canvas for every state update going to be expensive and put the load on the browser?
@asturur - your input will be valuable.

**Comment by asturur** [comment]
well the bigger the design the more expensive, untill is not slow is still ok.

Updating part of the json is complicated and can give you mutability problem.

An harder alternative is saving just the differences but is a path full of errors to solve. The problems comes when you handle multi selections in which what is changed is harder to find.

**Comment by vxrai** [comment]
Hey, Andrea (@asturur ) for now I have decided to stick to saving the canvas json as of now. In time if I find that its expensive or is causing issues, in that case, I will restrict to saving only the last 10 iterations on the canvas.

**Comment by asturur** [comment]
i mean if you have 600 objects on the canvas, and you do toJson and stringfy, will take some ms. If is ok, keep this approach.

If you have 20 objects and not crazy groups with hundreds of objects, it will be ok

**Comment by vxrai** [comment]
Hi @asturur , that's much clear now. 
Also, just incase you missed it, can you please look into this issue as well - https://github.com/fabricjs/fabricjs.com/issues/215
