### ISSUE TITLE
loadSVGFromURL() breaks fabric in IE9 for SVGs that contain <text />

### ISSUE THREAD

**Issue by mbrzuzy** [fabricjs/fabric.js#2315]
There is a bug in IE9 and how it handles <text /> nodes when the XML is loaded from a file.

The problem is that textContent is not set properly on textContent so when Text.fromElement tries to grab element.textContent it causes fabric to break in IE9.

See example here: http://mbrzuzy.com/fabric-bug/

Solution would be to run the loaded XML through DOMParser every time (similar to what LoadSVGFromString() does) or grab the text content from element.firstChild.data.

Here is my fix: https://github.com/mbrzuzy/fabric.js/commit/1ecebe38ee6ba569f3488e578be4296408bd51a3
##

**Comment by mbrzuzy** [comment]
The fix I link in the post is not a complete solution to the problem. As outlined by @kangax firstChild will not grab all <tspan> content. The current working solution does however fix the issue of fabric breaking.

I did make an additional commit to fix two errors I made when I was porting over my fix. https://github.com/mbrzuzy/fabric.js/commit/5ddcce56878e3cac272050b73611f4ed02aa9c30

Perhaps for IE9 the <text> node content should be re-parsed by DOMParser?

**Comment by asturur** [comment]
domparser is used whenever available.
Where did you see that we are not doing that?

**Comment by mbrzuzy** [comment]
During the onComplete used in loadSVGFromUrl()'s ajax request. xml.documentElement does exist in IE9, but the problem is that the browser parses the file incorrectly making textContent not accessible.

loadSVGFromString() parses the XML appropriately every time.

**Comment by asturur** [comment]
so you would say:

i get response,
if i do not have xml.documentElement, take the responseText, and parse.
if i have xml.documentElement, but i'm IE9, check if there is domParser, take responseText and parse it with DomParser.

Or simply

When i'm on the onComplete function,
check if there is DomParser, parse the responseText.
if there is no DomParser check if i have already responseXML and do usual controls that you are already doing.

**Comment by mbrzuzy** [comment]
I would say your first suggestion is the way to go. That way you are not re-parsing a document unless absolutely necessary.
