### ISSUE TITLE
Add RegularPolygon object type

### ISSUE THREAD

**Issue by nickvans** [fabricjs/fabric.js#2437]
Sorry, this is my first time using GitHub, and I'm not sure if this is the proper forum to get this to you. 

It seems that just having a triangle primitive type is insufficient. What if you want a square, pentagon, hexagon etc? I have written a small method that returns a path for a regular polygon with the specified number of sides which I would like to submit for inclusion in fabricjs. I don't think I'm competent enough to make the change in fabric source directly, but please consider creating a RegularPolygon object type.

The function I wrote below takes arguments of x, y, radius, numVertexes and returns an SVG path string for a regular polygon centered at x,y, with vertex points at radius from the center, and with numVertexes corners. 

``` javascript
function polarToCartesian(centerX, centerY, radius, angleInDegrees) {
  // This function converts polar coordinates to cartesian coordinates

  var angleInRadians = (angleInDegrees-90) * Math.PI / 180.0;

  return {
    x: centerX + (radius * Math.cos(angleInRadians)),
    y: centerY + (radius * Math.sin(angleInRadians))
  };
}

function getRegularPolygonPath(x,y, radius, numVertexes){
  // This function returns a path for a regular polygon centered at x,y with a radius specified with numVertexes sides

  var interiorAngle = 360/numVertexes;

  // rotationAdjustment rotates the path by 1/2 the interior angle so that the polygon always has a flat side on the bottom
  // This isn't strictly necessary, but it's how we tend to think of and expect polygons to be drawn
  var rotationAdjustment = 0;
  if (numVertexes % 2 == 0){
    rotationAdjustment = interiorAngle/2;
  }

  var d = [];
  for (var i=0; i<numVertexes; i++){
    // var coord = coordList[i];
    var coord = polarToCartesian(x, y, radius, i*interiorAngle + rotationAdjustment);

    if (i==0){
      d.push('M ');

      // If an odd number of vertexes, add an additional point at the top of the polygon-- this will shift the calculated center
      // point of the shape so that the centerpoint of the polygon is at x,y (otherwise the center is mis-located)
      if (numVertexes %2 == 1){
        d.push(0);
        d.push(radius);
      }

      d.push('M');

    } else {
      d.push(" L ");
    }

    d.push(coord.x);
    d.push(coord.y);
  }

  d.join(" ");

  d+= " Z";

  return d;

}

```

The current code is used like this:

``` javascript
    var pathStr = getRegularPolygonPath(50,25, 10, 8);

    var polygon = new fabric.Path(pathStr,
    {
      stroke: 'black',
      strokeWidth: 1,
      fill: 'blue',
      originX: 'center',
      originY: 'center',
    });

    // draws an octagon in this case
    canvas.add(polygon);
```

Note: I drew a separate circle object at the x,y location to show the origin point
![octagon](https://cloud.githubusercontent.com/assets/9273051/9412517/f4fcfb26-47e0-11e5-9eed-386409412546.png)

Similarly we can draw other polygons as well

numVertexes = 5
![image](https://cloud.githubusercontent.com/assets/9273051/9412572/449166d6-47e1-11e5-974a-e71cb681e945.png)

numVertexes = 6
![image](https://cloud.githubusercontent.com/assets/9273051/9412583/5d7b8ed8-47e1-11e5-8405-6bbfe64de6c9.png)

numVertexes = 14
![image](https://cloud.githubusercontent.com/assets/9273051/9412609/781f691c-47e1-11e5-9ce8-fd206d8b262d.png)

I think it would be cleaner if we could just create a new RegularPolygon object and have it internally use the path, but I don't know how to do this.

``` javascript
    var polygon = new fabric.RegularPolygon(
    {
      left: 50,
      top: 25,
      radius: 10,
      vertexCount: 8,
      stroke: 'black',
      strokeWidth: 1,
      fill: 'blue',
      originX: 'center',
      originY: 'center',
    });
```

Something would probably need to be done to handle the left, top coordinate transform, but I don't know how that works internally in fabric.

Thanks for your consideration!

**Comment by kangax** [comment]
This is an interesting idea, thanks for proposing it! Which benefits would this have vs. existing fabric.Polygon, fabric.Polyline? Easier way of specifying number of vertices/sides without messing with SVG path? Perhaps it should be a subclass of fabric.Polygon then?

**Comment by nickvans** [comment]
Yeah, the real benefit is not needing to work out all the point locations yourself. I have no objection to it being a subclass of Polygon. 

Thanks for your consideration!

**Comment by asturur** [comment]
passed ages.
I think that as soon as fabric 2.0 is out, we can check this thing and insert it with as less code as possible. Would be an handy tool for someone.

Being a subclass of polygon i do not see problems in supporting the standard features.

**Comment by Rameshv** [comment]
With a little bit of a change, we can use this in `new fabric.Polygon`

```
const getPolygon = (size,radius,numVertexes) => {
        var interiorAngle = 360/numVertexes;
        var rotationAdjustment = 0;
        if (numVertexes % 2 == 0){
          rotationAdjustment = interiorAngle/2;
        }
      
        var d = [];
        for (var i=0; i<numVertexes; i++){
            var coord = polarToCartesian(size, size, radius, i*interiorAngle + rotationAdjustment);
            d.push(coord)
        }
        return d
    }

    const polarToCartesian = (centerX, centerY, radius, angleInDegrees) => {
        // This function converts polar coordinates to cartesian coordinates
        var angleInRadians = (angleInDegrees-90) * Math.PI / 180.0;
        return {
          x: centerX + (radius * Math.cos(angleInRadians)),
          y: centerY + (radius * Math.sin(angleInRadians))
        };
      }
```

And use it like this

 ```
var octagon = new fabric.Polygon(getPolygon(100,50,6), 
            {
                left: 10,
                top: 10,
                strokeLineJoin: 'bevil',
                id:uuidv4(),
                fill:'rgba(0,0,0,0)',
            });
```

```
var hexagon = new fabric.Polygon(getPolygon(100,50,8), 
            {
                left: 10,
                top: 10,
                strokeLineJoin: 'bevil',
                id:uuidv4(),
                fill:'rgba(0,0,0,0)',
            });
```

**Comment by asturur** [comment]
so we would like to compress polygon/polylines/path in the same class, since are way similar.
We could add simply an utility to create the point set for a regular polygon.
