### ISSUE TITLE
font problem in nodejs render

### ISSUE THREAD

**Issue by RWizard** [fabricjs/fabric.js#2514]
In v1.6rc1+ node problem with font params (family, size). In Fabric 1.5 + node work fine.
Problem only in node (in browser fine).
Example custom font add in 1.5 (work fine): 

```
font = new canvas.Font('FreeMono', __dirname + '/../../app/assets/fonts/FreeMono.ttf');
font.addFace(__dirname + '/../../app/assets/fonts/FreeMono.ttf', 'normal');

canvas.contextTop.addFont(font);
```

In 1.6 + node font always in one family in one size. Font params in JSON ignored.

**Comment by RWizard** [comment]
In browser (fabric 1.6rc1)
![2015-10-16 0 07 14](https://cloud.githubusercontent.com/assets/190453/10527653/4b5a49ee-739a-11e5-8b3b-6d5475ddafcb.JPG)
After node.js (0.12.4) rendering (fabric 1.6rc1).
![2015-10-16 0 08 13](https://cloud.githubusercontent.com/assets/190453/10527658/55b65734-739a-11e5-913d-29a3665b19d5.JPG)

Would you like resolve the problem?

**Comment by RWizard** [comment]
Additional information: NodeJs render on OSX worked fine, problem on Linux (Ubuntu 14).

**Comment by mahnunchik** [comment]
+1

**Comment by keanass** [comment]
+1

**Comment by thedarkside** [comment]
Yes i ran into the same bug. It's in the master branch.
The measurements (lineheight for example) are rendered correctly but the font itself isn't rendered. 

System: Ubuntu 14.04
Node: v0.12.12
-> canvas@1.2.11
fabric 1.6.0-rc1 (current master branch)

Any solutions so far?

**Comment by teewuane** [comment]
+1

**Comment by asturur** [comment]
this is issue is related to legacy code and should be closed
