### ISSUE TITLE
SVG text on path is not working

### ISSUE THREAD

**Issue by k7moorthi** [fabricjs/fabric.js#2544]
When i try to load SVG which has a text on path component, the canvas shows straight line text instead of text on a particular path.

SVG sample:

```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <path id="myTextPath" d="M75,20 a1,1 0 0,0 100,0 " />
    </defs>

    <text x="10" y="100" style="stroke: #000000;">
        <textPath xlink:href="#myTextPath" >
            Text along a curved path...
        </textPath>
    </text>
</svg>
```

**Comment by rajeevchoudhary22** [comment]
Hi,
Fabric is fabulous product thanks for giving support to us for create such a great t-shirt designer tool.
All SVG is working fine and i can add any SVG on canvas but have an issue with wordcloud svg. when i try to add wordcloud svg by loadSVGFromString then its disturb svg's styles. I have attached a screenshot and also check your demo.

Its only with <text> tag in svg element. Can you please advise ?

SVG code find in .txt file.

![screenshot-demo veesys com 2016-01-11 19-03-37](https://cloud.githubusercontent.com/assets/16375551/12234927/3ab48b40-b896-11e5-9526-7af898bfdf5e.png)
 
[test.txt](https://github.com/kangax/fabric.js/files/85792/test.txt)

Thanks
Rajeev

**Comment by megalithic** [comment]
Just resurrecting this. Will this ever be supported? @asturur / @kangax

**Comment by josefanostylus** [comment]
Please add this feature, its very much needed.

**Comment by alexzaganelli** [comment]
It would be very nice feature!!! Please, add this feature

**Comment by meglio** [comment]
So, the implementation would be to allow for `textPath` property on a `Text` object that links to a `Path` object?

**Comment by asturur** [comment]
yes. another canva library has it, would be interesting to see if their code is pluggable and reusable

**Comment by meglio** [comment]
Which one?

Can I use two libraries with the same canvas DOM element?

**Comment by juzhiyuan** [comment]
Any updates here?

**Comment by asturur** [comment]
no one is working on it that i know of

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/pull/6543 this PR track progress of this
