### ISSUE TITLE
gradient render problem for path-group objects in node js

### ISSUE THREAD

**Issue by Godweed** [fabricjs/fabric.js#2546]
Hello, for itext I can both correctly render gradient in client and server side but for svg objects I can able to render in client and but not in node.js 

I am loading a svg object and apply a gradient to object it correctly renders gradient in client side. Then I am using canvas.toDatalessJSON() method and render canvas in node js but the gradient do not applied to svg objects. It works for i-text object

**Comment by asturur** [comment]
We do not have a SVG object. Could you be more specific about applying the gradient to SVG object?

Did you try to ise full JSON  instead of dataless?

**Comment by Godweed** [comment]
I mean path-group object as mentioned in the subject , I am loading a path group object to canvas and give gradient effect. It is a svg file. After loading svg file to canvas in client side gradient is rendered correctly. I prefer datalessJSON because of performance issues and load object and render canvas in server side.

**Comment by asturur** [comment]
where are you appling the gradient? fill property of pathgroup is not rendered. which version are you using?

**Comment by Godweed** [comment]
I am using 1.6.0-rc.1

 if (obj instanceof fabric.PathGroup){
            obj.getObjects().forEach(function(o){
                odx = o.width  /2;
                ody = o.height /2;
            
                o.setGradient('fill',{
                    x1: gradient.start.x - odx,
                    y1: gradient.start.y - ody,
                    x2: gradient.end.x   - odx,
                    y2: gradient.end.y   - ody,
                    colorStops : colors
                });
            });	return;
        }
    
        if (obj instanceof fabric.IText){
          obj.setGradient('fill',{
              x1: gradient.start.x - odx,
              y1: gradient.start.y - ody,
              x2: gradient.end.x   - odx,
              y2: gradient.end.y   - ody,
              colorStops : colors
          }); 
        }

**Comment by asturur** [comment]
missing snippet, old fabric and node-canvas. Closing
