### ISSUE TITLE
Problem with touch:longpress in scrollable page

### ISSUE THREAD

**Issue by cerve** [fabricjs/fabric.js#2621]
Hi, I have got a problem with the touch:longpress event in touchable device.
It seems that fabric.js does not fire the event correctly if the canvas is placed for example at the bottom of page and you must use scroll down to display it.

I built a simple example here http://jsfiddle.net/cerve/jmsoruqo/ using fabric.js with Custom Build

In this example, I've created two equal canvas initialised in the same way with fabric. In the middle we have a single <div> with an height of 2000px. In order to see the second div it is necessary to scroll the result page.

Using a touchable device (or simulating it) the first canvas fire the event longpress but the second one doesn't fire nothing.

Could you help me?

Thank you in advance

**Comment by khmyznikov** [comment]
Same issue. On PC too. Reproduced on large canvas too. Half part under scroll, and long press doesn't work on it.

**Comment by mrs1ava** [comment]
It is a consequence, not a cause. If this is commented out, the long event will occur, even if after it was drag.
For myself, modified in root.tap (1):
`conf.delay = conf.delay || 1000;` 

conf.onPointerMove (2)
change from
`var y = (touch.pageY - bbox.y1);`
to:
`var y = (touch.pageY - bbox.y1 - parseInt($(window).scrollTop()));`

p.s. If there is a scroll through Axis, then keep this in mind!

> Problem with eventjs. If you comment this line, long press start to work across all canvas, even on under scroll part.
> 
> ```
> for (var key in conf.tracker) {
>         var point = conf.tracker[key];
> 	if (point.end === true) return;
>         // -- comment below
> 	// if (conf.cancel) return;
> 	fingers ++;
> }
> ```

**Comment by jeffreydwalter** [comment]
@cerve are you still on github? I'd like to know if you'd be interested in giving up your cerve github organization name? Thanks in advance!

**Comment by SatwinderKaur** [comment]
@cerve  I have the same issue, did you find a solution for it?

**Comment by GerwinFleurop** [comment]
Hey @asturur Do you know what the status of this issue is?

the 'LongPress' event doesn't seem to fire when the browser is scrolled down the page.
FabricJS version 4.5.1

**Comment by asturur** [comment]
do you know if our eventjs support the longpress event? i m out of contact with our touch events situation

**Comment by GerwinFleurop** [comment]
@asturur It supports longpress - but the longpress event handler doesn't take the windows scroll position into account

**Comment by asturur** [comment]
ok. can you open a clean new issue adding a really minimal setup to test it?

**Comment by GerwinFleurop** [comment]
Sure - do you happen to have a URL of FabricJS with gestures? The URL the person uses above is 4.0.0 - rather than 4.5.1

**Comment by GerwinFleurop** [comment]
@asturur see - http://jsfiddle.net/d71exfr9/ if you longpress before scrolling it works - if you then drag the element down & longpress again it doesn't work

**Comment by GerwinFleurop** [comment]
@asturur new issue can be found here -> #7159
