### ISSUE TITLE
Add crossOrigin to images loaded by fabric.Image.fromURL to prevent canvas tainting [$35 awarded]

### ISSUE THREAD

**Issue by kylemacfarlane** [fabricjs/fabric.js#263]
All of the big browsers except IE (even IE10, unless it's in the RTM which I haven't tried) now support adding cross domain images to a canvas without tainting it.

To support this feature `fabric.Image.fromURL` needs to set the `crossOrigin` property on images it loads. For example:

```
fabric.Image.fromURL = function(url, callback, imgOptions, crossOrigin) {
  var img = fabric.document.createElement('img');
  if (crossOrigin != null && url.indexOf('data:') != 0) img.crossOrigin = crossOrigin;

  /** @ignore */
  img.onload = function() {
    if (callback) {
      callback(new fabric.Image(img, imgOptions));
    }
    img = img.onload = null;
  };
  img.src = url;
};
```

It should not be set for data URIs because it will break them, but it should (as far as I know) still be set for local files (i.e. `file://`) because they are still technically cross domain under CORS.

As for the actual value of the `crossOrigin` then it has two possible values: `anonymous` or `use-credentials`. [Their usage determines whether cookies or other authentication information is passed along.](https://developer.mozilla.org/en-US/docs/HTML/CORS_settings_attributes)
##

**Comment by robgoddes** [comment]
Hi, wondering if you can help Kangax?

I have some simple code to save the canvas to png that works on Firefox but not Chrome. 

I understand I need to add `img.crossOrigin = 'anonymous'` but really unsure where to place it in my code.

Are you able to help?

// code to add image to canvas from local
```
fabric.Image.fromURL('images/bt-logo-white.png', function(xImg) {
     xImg.scale(0.5).set({ left: 200, top: 200 });
          canvas.add(xImg);
});
```

// code to save canvas to png
```
$("#b-savepng").click(function(){
     $("#c").get(0).toBlob(function(blob){
          saveAs(blob, "robImage.png");
     });
});
```

**Comment by robgoddes** [comment]
Hi, wondering if you can help @kangax?   [fabricjs]

I have some simple code to save the canvas to png that works on Firefox but not Chrome.

I understand I need to add `img.crossOrigin = 'anonymous'` but really unsure where to place it in my code.

Are you able to help?

// code to add image to canvas from local

```
fabric.Image.fromURL('images/bt-logo-white.png', function(xImg) {
     xImg.scale(0.5).set({ left: 200, top: 200 });
          canvas.add(xImg);
});
```

// code to save canvas to png

```
$("#b-savepng").click(function(){
     $("#c").get(0).toBlob(function(blob){
          saveAs(blob, "robImage.png");
     });
});
```
