### ISSUE TITLE
Pinch to Zoom all Canvas Objects

### ISSUE THREAD

**Issue by Kampii** [fabricjs/fabric.js#2658]
What is the syntax for that? Looks like pinching gesture scales an object, but how would I zoom in/out all of the canvas objects?

**Comment by kangax** [comment]
You'll need to hook up gestures to our zooming functions. Nothing like this built-in afair, but I'll mark it as possible feature.

**Comment by Anruin** [comment]
Hi, if it will help, that's what I'm using in my project, as an example. Works for me.

```
'touch:gesture': function(event) {
  // Handle zoom only if 2 fingers are touching the screen
  if (event.e.touches && event.e.touches.length == 2) {
    // Get event point
    var point = new fabric.Point(event.self.x, event.self.y);
    // Remember canvas scale at gesture start
    if (event.self.state == "start") {
      zoomStartScale = self.canvas.getZoom();
    }
    // Calculate delta from start scale
    var delta = zoomStartScale * event.self.scale;
    // Zoom to pinch point
    self.canvas.zoomToPoint(point, delta);
  }
}
```

**Comment by Sphinxxxx** [comment]
*Note: I only use the "free drawing" feature of the library, so this probably won't do as a general fix.*

To allow normal pinch-to-zoom while drawing, I simply added this as the first line of `_onMouseMove()`:

    if((e.type === 'touchmove') && (e.touches.length > 1)) { return; }

**Comment by jtara** [comment]
Unfortunately, Sphinxxx's solution makes marks in drawing mode. It's of course impossible to make two touches at EXACTLY the same time!

I haven't tried Anruin's solution yet. Problem is, I need to scale both the canvas and multiple positioned overlays. But I think perhaps it will work for me if I substitute a CSS transform of the container (of canvas and overlays) for calling` zoomToPoint()`.

**Comment by jtara** [comment]
Some changes to my solution, it is still far from perfect. The 400mSec delay is annoying, and still it sometimes leaves a small mark in drawing mode.

``` javascript
*jslint browser: true, devel: true, vars: true, unparam: true, white: true, indent: 2 */
/*global fabric */

(function fabricZoomMonkeypatchSelfEx(window, document, undefined) {
  'use strict';

  fabric.util.object.extend(fabric.Canvas.prototype, /** @lends fabric.Canvas.prototype */ {

    _svTouchStartDeferTimerID: undefined,

    _svOnMouseDownOriginal: fabric.Canvas.prototype._onMouseDown,

    _onMouseDown: function (e) {
      if (this.allowTouchScrolling) {
        // This is dubious, because it will be almost impossible to have touchstart with multi-touch
        if (e.touches && (e.touches.length > 1)) {return;}
        clearTimeout(this._svTouchStartDeferTimerID);
        this._svTouchStartDeferTimerID = undefined;
        if(e.type === 'touchstart') {
          var _this = this;
          this._svTouchStartDeferTimerID = setTimeout(function() {
            _this._svTouchStartDeferTimerID = undefined;
            _this._svOnMouseDownOriginal(e);
          }, 400);
        }
      } else {
        this._svOnMouseDownOriginal(e);
      }
    },

    _onMouseMove: function (e) {
      if (this.allowTouchScrolling) {
        if((e.type === 'touchmove') && e.touches && (e.touches.length > 1)) {return;}
      }
      e.preventDefault && e.preventDefault();
      this.__onMouseMove(e);
    }

  });

}(window, document));
```

**Comment by marsonmao** [comment]
@Anruin 

1. I'd like to know what is `self.canvas` in the codes you share? Is it `event.self.canvas`? Thanks.
2. Also that I can't get `touch:gesture` fired on my canvas, but my objects on the canvas can be scaled by gesture. Not sure if you've ever had the same issue?

**Comment by ShaMan123** [comment]
`viewportTransform`
see http://fabricjs.com/fabric-intro-part-5#pan_zoom
