### ISSUE TITLE
Properties get lost if i use loadFromJSON

### ISSUE THREAD

**Issue by Kienz** [fabricjs/fabric.js#272]
Properties like `borderColor, cornerColor, padding, cornerSize`get lost if objects loaded with `loadFromJSON()`.

Jsfiddle example:
http://jsfiddle.net/r2ZE7/86/

**Comment by LunaZheng** [comment]
Please help me.
The following serialized data can be loaded with loadFromJSON()
{"objects":[{"type":"image","originX":"center","originY":"center","left":72.5,"top":91.5,"width":658,"height":982,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":0.22,"scaleY":0.22,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"crossOrigin":"","cropX":0,"cropY":0,"src":"http://zhengrongrong.top/my-blog/dist/static/img/face-20.png","filters":[]}]}

but the following serialized data cannot be loaded with loadFromJSON()
{"objects":[{"type":"image","originX":"center","originY":"center","left":96.5,"top":186.5,"width":658,"height":982,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":0.46,"scaleY":0.46,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"crossOrigin":"","cropX":0,"cropY":0,"src":"http://zhengrongrong.top/my-blog/dist/static/img/face-20.png","filters":[{"type":"Saturation","saturation":"0.913448"}]}]}

How do I load filtered data?

**Comment by asturur** [comment]
What version of fabric are you using?

**Comment by asturur** [comment]
The difference is on filters. Webgl is complaining about a creating a texture with that image. Needs a check.

Looks like an image/url problem since this identical JSON can be loaded

```

{"objects":[{"type":"image","originX":"center","originY":"center","left":96.5,"top":186.5,"width":658,"height":982,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":0.46,"scaleY":0.46,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"crossOrigin":"","cropX":0,"cropY":0,"src":"http://www.fabricjs.com/assets/pug.jpg", "filters":[{"type":"Saturation","saturation":"0.913448"}]}]}

```

**Comment by LunaZheng** [comment]
@asturur Thanks very much!
So I can't load JSON with filters directly, the filters must be removed before loading, then add the filter to the object. Is that so?

**Comment by asturur** [comment]
no i guess the image has some problem, maybe cors issues?
