### ISSUE TITLE
Shadow on nodejs canvas is not same as normal canvas.

### ISSUE THREAD

**Issue by keanass** [fabricjs/fabric.js#2782]
shadow is not applying when use it in nodejs, that because of node-canvas not suporting that, is there any aproach to solve this problem asap, we can work on what given.
Regards.

**Comment by mobidev111** [comment]
Does an up-to-date version of node-canvas support this? https://github.com/kangax/fabric.js/issues/2767 talks about upgrading node-canvas

**Comment by keanass** [comment]
the shadow is showing but in inversed angle !!

**Comment by asturur** [comment]
so it should be nice to refer to node-canvas team so they can check if it is a bug or not.

**Comment by keanass** [comment]
they are aplying now with canvas 1.3.2 but when i scale an image with shadow and use `canvas.toDataUrl()` the shadow is setting very far from the object. any idea people any reaction on that ?!

**Comment by asturur** [comment]
this works in node afaict
