### ISSUE TITLE
util.createClass to support (native) getters and setters

### ISSUE THREAD

**Issue by StephanBijzitter** [fabricjs/fabric.js#2786]
Our customers are of a special kind: they always manage to break the canvas.

A week ago, a customer managed to set the scale of a text object to 0, which caused massive rendering issues (division by zero) on our backend and caused it to crash. Yesterday, another customer managed to nullify a value that should have been a String. These are only two examples.

Therefore, I want to implement input sanitation on the frontend and backend by using getters and setters for values like these. They would not be traditional getters and setters `setScaleX(val)` but would use the property descriptor `scaleX = val`, as we would otherwise need to refactor a large amount of the codebase. 

As the frontend and backend share the same Fabric implementation, it makes sense for me to do this either in our implementation, or in Fabric itself, which I prefer. I want to add support to the `createClass` function in Fabric itself to be able to do this. @kangax Do you think this would be accepted as pull request provided the code is clean, performant and won't introduce breaking changes?

The current flow would still be supported and would be left completely untouched:

``` javascript
fabric.MyImageClass = fabric.util.createClass(fabric.Image, {
    type: 'MyImageClass',
    originX: 'center',
    offsetBackX: 0,
    imageId: null
});
```

But then it would also support:

``` javascript
fabric.MyImageClass = fabric.util.createClass(fabric.Image, {
    get type() {
        return 'MyImageClass'
    },

    get originX() {
        return this._originX;
    },

    set originX(val) {
        if (/left|center|foobar/.test(val)) {
            this._originX = val;
        }
    },

    get offsetBackX() {
        return this._offsetBackX;
    },

    set offsetBackX(val) {
        //cast to 32bit integer
        this._offsetBackX = val | 0;
    },

    get imageId() {
        return this._imageId;
    },

    set imageId(val) {
        if (typeof val === 'string') {
            this._imageId = val;
        }
    },

    initialize: function() {
        this.originX = 'center';
        this.offsetBackX = 0;
        this.imageId = null; //invalid, won't be set
    }
});
```

**Comment by kangax** [comment]
Couple questions:

1) is there a reason you can't sanitize these values before passing them to accessors? I assume they're coming from some sort of input fields in a document?

2) how would we make it backwards-compatible? If we add corresponding _prop's then we need to add validation too? The reason we're not using accessors right now is due to browser support. We can consider deprecating certain browsers in the future in which case this will be an option.

**Comment by StephanBijzitter** [comment]
1) We could, but they're not necessarily from actual user input. That is, most of the issues arrive from customers with strange mobile-like devices that somehow glitch when working with the canvas causing some calculations to mess up.

I can imagine we're not the only ones with this issue, so to solve it in the library itself could possibly save others a lot of time, while it costs us the same amount of time.

2) Fabric itself can continue to use its current way to define properties, without any validation, as older browsers indeed have issues with these. The change would be implemented in a way that allows dependants of Fabric to use the getters and setters, provided the dependants are okay with requiring more recent browsers.

Skimming through Fabric's code, the [addMethods](https://github.com/kangax/fabric.js/blob/master/src/util/lang_class.js#L15) function would probably be the place where an additional check for a property is made using [getOwnPropertyDescriptor](http://caniuse.com/#search=getOwnPropertyDescriptor), if available.

As soon as all most-used browsers support this, we could indeed opt for Fabric itself to start using this too, with very basic sanitising. For example, a variable that needs to be a String would not check whatever the content of the String is, as long as it's a String. This would most-likely result in breaking changes, indeed.
