### ISSUE TITLE
Not able to apply custom fonts on nodejs

### ISSUE THREAD

**Issue by keanass** [fabricjs/fabric.js#2798]
Not able to add fonts like tutorial, i tested multiple ways with no results, this is my code.

```
   var myFont = new nodeCanvas.Font(val.fontFamily, fontfile);
   myFont.addFace(fontfile, 'bold');
   createPNGStream or createJPEGStream
   canvas.contextTop.addFont(myFont);
```

**Comment by jhundley9109** [comment]
Ah, I think I mentioned this might be an issue in #2758. Try to add your font to the contextContainer. For instance canvas.contextContainer.addFont(myFont);

**Comment by jhundley9109** [comment]
Also, looking at your example a little bit more, it looks like you might have two separate canvas references?

This should probably be like this:
<pre lang="javascript"><code>
   var myFont = new nodeCanvas.Font(val.fontFamily, fontfile);
   myFont.addFace(fontfile, 'bold');
   // createPNGStream or createJPEGStream
   nodeCanvas.contextContainer.addFont(myFont);
</pre></code>

**Comment by keanass** [comment]
Tried that but not working, and i know about the separate instances, i the global Canvas module. For both fabric and app, i think there is an issue in the fabric font api, because i tested the api in github version after i build and test the font example listed there, and found somthing wrong with Canvas.addfont(), any solution for this issue. Thanks

**Comment by jhundley9109** [comment]
Oh I see. This could actually be an issue with createPNGStream possibly. I'm not sure without looking into it more. I do know custom fonts work for me when using toDataURL(). I know this isn't going to the bug, but it is a work around for now.
<pre lang="javascript"><code>
canvas.toDataURL();
var imageData = data2.replace(/^data:image\/\w+;base64,/, "");
var buf = new Buffer(imageData, 'base64');
</code></pre>

**Comment by keanass** [comment]
i m using `canvas.toDataURLWithMultiplier('png', 1) ` without any success

**Comment by adamcrown** [comment]
Anybody have any update on this. I'm running into really weird problem. The only font I can get to work on a Node canvas of the seven I tried is [Exo 2](https://fonts.google.com/specimen/Exo+2). And even then it's only working for text that is added programatically. I can't get fonts to work on the JSON I'm loading at all. Applying a custom font just seems to switch it to a generic sans font and shrink the size.

Here is an example. The text on the left is loaded from JSON and the ones on the right I'm just adding in code for testing.
![node-fabric-font-issue](https://cloud.githubusercontent.com/assets/277306/21689560/b3d43e72-d3ab-11e6-9d58-c537eba04fb1.png)

**Comment by adamcrown** [comment]
FYI, to anybody else who comes after me I made progress by using the current master git branch with is unreleased work on version 2. There certainly could be other bugs, but so far I haven't had any trouble and font rendering is much improved.

`git://github.com/Automattic/node-canvas.git#188c4ca7f2ea510991e1da390a22f06f69405af2`

**Comment by asturur** [comment]
this issue is related to legacy code now, i ll close it
