### ISSUE TITLE
Clicking on transparent pixel select element beneath

### ISSUE THREAD

**Issue by brunobg** [fabricjs/fabric.js#28]
Clicking on a pixel selects the element using the bounding box in the demo. I'd like to test if it's a transparent pixel for that element, and if so select the element below it, recursively. I couldn't find a way in the docs to do this, but I'd be glad to help to implement if given a few pointers. 

It seems that all that it would take is to add a test in Element::containsPoint() such as:

``` javascript
      // we iterate through each object. If target found, return it.
      var iLines = target._getImageLines(target.oCoords),
          xpoints = target._findCrossPoints(x, y, iLines);

      // check if pixel is transparent
      var color = target.getPixelColor(x, y);

      // if xcount is odd then we clicked inside the object
      // For the specific case of square images xcount === 1 in all true cases
      if (color.alpha > 0 && ((xpoints && xpoints % 2 === 1) || target._findTargetCorner(e, this._offset))) {
        return true;
      }
```

But I couldn't find a 'getPixelColor' method or similar....

**Comment by Swerv3** [comment]
Does this work for layered pngs with transparent backgrounds? I have looked through the docs on the website and can't see any implementations of this which is leading me to the conclusion it doesn't?

**Comment by asturur** [comment]
well it should. if you have many transparent images on top of each other and perPixelTargeFind activated, the target search start from the topmost on z axes  and stop at the first non trasparent pixel it found

**Comment by Swerv3** [comment]
@asturur thank you! I didn't see the perPixelTargetFind property in my search previously.
