### ISSUE TITLE
Hook up `npm version` for easier (and more frequent) publishing

### ISSUE THREAD

**Issue by JSteunou** [fabricjs/fabric.js#2813]
Hi,

this is more a request than a usage question so I write down here, let me know if it would be better in google group.

fabric.js is real jewel when it comes Canvas in JavaScript, and I could not thank you enough for that. Last year we were excited to see that the process of a release candidate for the 1.6.0 was started. It has been more than 6 months now.

I have the feeling you all want to reach the stars and set goals hard to reach before a possible RC2 or final release. Would it be better to plan littler steps and having regular RC we all can test, play with and make a final 1.6.0 release sooner than never?

It's a common mistake others did before you. JavaScript es4 and PHP6 for example. Please do not fall into that trap.

What can we do to help you make or plan this release?

**Comment by asturur** [comment]
I was planning to make a nightly build system and place a link somewhere.

**Comment by kangax** [comment]
I agree that we need faster releases; I just simply didn't have time to make a proper release. @asturur would you be able to?

**Comment by asturur** [comment]
Give me list of steps you have.
Update npm, update bower,update tweeter, update docs...

**Comment by kangax** [comment]
0) Don't forget to pull new changes
1) `npm run all`
2) make sure there are no errors
3) bump version, `npm run all` & commit
4) Tag new version
   > git tag v1.x.x
   > git push --tags
5) `npm publish`
6) Update build files on fabricjs.com (commit, push)
7) Submit pull request to cdnjs
8) Update cdnjs link on fabricjs.com
9) Ask @jsfiddle on twitter to update
10) Prepare list of changes
11) Write about new version + changes on Google Group
12) Tweet link to Google Group

**Comment by JSteunou** [comment]
steps 1 to 5 can be done with [npm version](https://docs.npmjs.com/cli/version) and npm hooks.

for example `$ npm version minor` will increment to 1.7.0 the version in package.json, create a commit and a tag. You can personalize the tag and message via `.npmrc` or cli arguments.

* script `preversion` is triggered before version: you can do `npm run all && git commit`. Exit with non 0 interrupt `npm version`
* `postversion`  is triggered after version, so after package version update, commit & tag. You can do `git push --follow-tags && npm publish`

If you have to do things before publish you can use `prepublish` but be aware this one is triggered by `npm install` too which lead to [hack like this](https://www.npmjs.com/package/in-publish) `"prepublish": "in-publish && npm run build || not-in-publish"`

You can do tasks after 5 with `postpublish`.

**Comment by kangax** [comment]
@JSteunou never knew about `npm version`, that's really awesome, thanks! if you can make a PR that would very helpful since I'm a bit constrained on time now.

**Comment by JSteunou** [comment]
I which I could, hard to find time since a while. @asturur if you're on it I could help you with some code review. The recipe is above, the most valuable missing ingredient is time.

**Comment by asturur** [comment]
i'm happy to learn. But first i need a npm account i think.

**Comment by JSteunou** [comment]
For testing purpose I use https://github.com/rlidwka/sinopia and set `"publishConfig": {"registry": "http://localhost:4873/"}` in the package.json of my projects

This will allow you to test your script at home without publishing for real ;)
