### ISSUE TITLE
New feature for moving an object - see scrollkit.com [$30]

### ISSUE THREAD

**Issue by Kienz** [fabricjs/fabric.js#298]
Don't showing original object while moving but display object dimensions for the moving object.
<img src="https://s3-eu-west-1.amazonaws.com/kienzle.geschaeft/projects/sketch/scrollkit_move_object.png">

What do you think about that additional behavior for fabric?
I think for large path-groups it make sense.
##

**Comment by asturur** [comment]
So 2.5 years have passed.
Object caching is finally in.
This feature could be still a nice addon if we can implement with very few lines of code.

That said we could have on canvas a rect, stored somewhere, as ghost object.

for every object `render` method would flow as usual.

while `_render` would check:

```javascript
// if there is a transform on the canvas...
if (this.canvas && this.canvas._currentTransform && this.useGhost) {
  this.canvas.ghost.width = ...properwidth;
  this.canvas.ghost.height = ...properheight;
  this.canvas.ghos._render(ctx);
  return;
}
```

this should make the trick.

who is still reading, wants to give some comments?

**Comment by samael205** [comment]
Can you create a fictitious object while you move, without really adding it to the canvas? Or do I really not understand this functionality?

**Comment by asturur** [comment]
yes you  can.
In the `_render` function of an object the canvas is transformed to handle that particular object.
If at that point you call a `rect._render` you will just get another drawn.
the stroke of this rect has to be set up manually. or some other trick is needed in the `render` fnuction to setup the ghost object colors.

**Comment by Aubron** [comment]
@asturur - thoughts on this? To me this seems like one of those 'implement in your editor', things, or at the very least default off, but I'm interested in your thoughts.

**Comment by Aubron** [comment]
If not could see it being implemented like html5's drag events.

When a drag starts you can run some code to generate a preview or cache for the drag.

https://kryogenix.org/code/browser/custom-drag-image.html

Not actually important to me, just trying to clean up some old issues where we can.
