### ISSUE TITLE
text rendering isn't working

### ISSUE THREAD

**Issue by kilaulena** [fabricjs/fabric.js#3]
Hey,

we just spend a couple of hours trying to render text in a canvas, using cufon for the fonts. We have the assumption that the _render method in text.class.js is somehow not complete, as there is nothing happening that would render the text. Can you give us any hint how we can get it working? 

The result we want is that we can specify font family and font color of the text, and make the text element resizable etc, like a normal canvas element. The rest of the library is awesome so far, so we'd rather not switch now.

Any hints very much appreciated!

**Comment by saran110313** [comment]
fabric.util.loadImage( ' ../sample.png' , function(img){
});
Uncaught TypeError: object.render is not a function
fabric.StaticCanvas.fabric.util.createClass._onObjectAdded @ fabric.js:6378
fabric.Collection.add @ fabric.js:198
this image object move and not add the client side in image function.
how to solve this function...
