### ISSUE TITLE
Disable dragging globally

### ISSUE THREAD

**Issue by cleercode** [fabricjs/fabric.js#30]
Is there a way to toggle whether selection/dragging is enabled?

**Comment by pioneersingh321** [comment]
fcanvas = new fabric.Canvas(canvasId); 
var oElements= fcanvas.getObjects();

              $.each(oElements, function(index, element) {
                  element.lockMovementX = true;
                  element.lockMovementY = true;
                  element.lockScalingX= true;
                  element.lockScalingY=true;
                  element.lockRotation=true;
                  element.hasControls = element.hasBorders = false;
              });

**Comment by DedaDev** [comment]
thx bud, that works, also the vanilla JS equivalent:

```js
    const allObjects = fabricRef.current.getObjects();
    allObjects.forEach((object) => {
      object.lockMovementX = true;
      object.lockMovementY = true;
      object.lockScalingX = true;
      object.lockScalingY = true;
      object.lockRotation = true;
      object.hasControls = object.hasBorders = false;
    });
```
