### ISSUE TITLE
Group object ignore own lockMovementX/Y = false properties

### ISSUE THREAD

**Issue by geekduck** [fabricjs/fabric.js#3074]
## Version

1.6.2
## Test Case

https://jsfiddle.net/geekduck/0u62cwy5/2/
## Steps to reproduce
1. Create two objects (lockMovementX/Y = true) .
2. Create group object(lockMovementX/Y = false) with 1. objects.
## Expected Behavior

When group object has own lockMovementX/Y=false properties,  should moving.
## Actual Behavior

Group object is locked.

**Comment by geekduck** [comment]
Here.
https://github.com/kangax/fabric.js/blob/master/src/shapes/group.class.js#L499
```
if (typeof this[prop] !== 'undefined') {
```

**Comment by neopheus** [comment]
like this : https://jsfiddle.net/0u62cwy5/3/ ?

**Comment by asturur** [comment]
incline to remove both those lockProperties and delegated properties.
if you want the group to do not move, set the group props.
For activeGroup ( multiselection ) i will find another way.

**Comment by asturur** [comment]
will take longer than expecting.
I m removing the lock properties and delegated properties from Group. This is a breaking change and so i ll do for 2.0. ( already did )
I will introduce a ActiveSelection class that will do this quirks for the Group.

Group is a container and will do the container.
ActiveSelection/ActiveGroup is a more evolved container and will get some automatism for setting  props and locking.

**Comment by fredguth** [comment]
@asturur  Could you further elaborate on this?  i didn't understand.

I had a set of items with lockMovementX/Y=true.
before grouping, I set items lockMovementX/Y= false
I create a group from items, I expected group to be unlocked, but it was locked.

I then further set group.lockMovementX/Y = false
Still, my group is locked.

Didn't understand why.

**Comment by asturur** [comment]
can you elaborate a fiddle to show it? are you talking of  version 1 or 2?

**Comment by fredguth** [comment]
Never mind... I thought I was in the latest version, but wasn't. Sorry.
