### ISSUE TITLE
Corner Control Images

### ISSUE THREAD

**Issue by mzander** [fabricjs/fabric.js#313]
Hi,

I needed to show images adove the controls at the top-left, top-right, bottom-right and bottom-left corners. The images should indicate that the element it rotatable.

Anyway, I forked your repository, modified the classes and comitted it to my repo.
For some reason I wasn't able to create a jsfiddle - so I'd like to inform you in this way.

If you want, you can see my changes in the Fork; https://github.com/mzander/fabric.js

![screenshot of the result](http://s14.directupload.net/images/121113/4iizft9a.jpg)

Code example:

```
canvas.useCornerImages = true;
canvas.cornerImagePadding = 10;
canvas.cornerImageTopLeft = '/img/icons/rotate_tl.png';
canvas.cornerImageTopRight = '/img/icons/rotate_tr.png';
canvas.cornerImageBottomRight = '/img/icons/rotate_br.png';
canvas.cornerImageBottomLeft = '/img/icons/rotate_bl.png';
```

**Comment by paragmehtahelios** [comment]
Hi mzander,

I want to implement same functionality for one my project for which I have tried out one solution but that isnt perfect. The fork link specified by you is not working currently, can you please share the changes that you have made in the core file?

**Comment by jiahuamld** [comment]
嗨mzander，

我想为我的项目实现相同的功能，我尝试过一个解决方案，但这并不完美。您指定的fork链接当前不工作，请您分享您在核心文件中所做的更改？
