### ISSUE TITLE
IText/Textbox - two blinking cursors

### ISSUE THREAD

**Issue by darkknightpl** [fabricjs/fabric.js#3232]
## Description

Windows 7, after updating from IE10 to IE11 (IE11 version: 11.0.9600.18426, update version: 11.0.34).

There are two blinking cursors when typing text in IText/Textbox (second one is behind text):

![b_cursors](https://cloud.githubusercontent.com/assets/16231411/18251837/d2808afe-738b-11e6-9083-95d2ab0f0639.png)
## Version

1.6.3
## Test Case

http://jsfiddle.net/darkknightpl/Da7SP/176/

**Comment by asturur** [comment]
I cannot help on this. I cannot find a way to make the blinking cursor transparent on IE.
the hiddenTextarea is 0x0 pixel, transparent, low Zindex, but still ie and iphone show the cursor.
If you are able to style a textbox to make it disappear the cursor i will bring the fix in.

**Comment by FeaRCODE** [comment]
@asturur using this in my CSS fixes the issue for me:
```
textarea:focus {
  text-indent: -9999em;
}
```
http://jsfiddle.net/Da7SP/177/

**Comment by asturur** [comment]
why just on focus? i'm inclined to pull it in.

**Comment by FeaRCODE** [comment]
I think its because the cursor is only shown when the textarea is in focus (assuming why its showing). Changing the text-indent forces it off the page. Probably not the cleanest solution, but it works.

**Comment by darkknightpl** [comment]
The problem is still occurring after hitting enter:
![b_cursors2](https://cloud.githubusercontent.com/assets/16231411/18273134/141fad90-743c-11e6-9f86-6e2731ce78d3.png)

**Comment by FeaRCODE** [comment]
@darkknightpl Good catch. @asturur I have modified the `top` / `left` attributes to `[0, 0]` and it seems to work even when pressing enter.

```
textarea:focus {
  top:0 !important;
  left:0 !important;
}
```

http://jsfiddle.net/zqeu83kL/

**Comment by asturur** [comment]
no we cannot move textarea position at all. it has to be where it is or iphones will get crazy.

http://jsfiddle.net/Da7SP/178/

what happens with lineHeight, does it get better?

**Comment by darkknightpl** [comment]
@asturur Unfortunately, IE still is so generous and overzealous that it adds additional cursor after hitting enter ;)

**Comment by asturur** [comment]
i will search an IE box and make a test later. i want to get rid of it also.

**Comment by salmanjaved** [comment]
@asturur - Any update regarding this issue.. As it look much weird in the app that we built... everything is working fine except it..

**Comment by mole440** [comment]
I'm not sure about IE, but I had success in removing the duplicate cursor on iOS with the following CSS

`body > textarea {
`  font-size: 0;
`}

**Comment by Wj0622** [comment]
What's the difference between IText and Textbox?

**Comment by sherpa-nimesh** [comment]
@asturur any updates on this. As i am still having the same issue.

**Comment by asturur** [comment]
I do not know a way to hide that blinking cursor in IE11.
Moving the textbox away to hide it would kill chinese/japanese input at least and MacOS longpress feature.

If there is a way to make it disappear, happy to apply it.
Some weird CSS trick i do not know.

**Comment by asturur** [comment]
Oh if your issue is on IOS, weirder then.

**Comment by ShaMan123** [comment]
IText cursor blinking has been addressed.
If this is still relevant try upgrading to latest and testing.
And report back.
