### ISSUE TITLE
Uncaught TypeError: Object #<Object> has no method '_initStatic'

### ISSUE THREAD

**Issue by erichiggins** [fabricjs/fabric.js#328]
I can't even seem to get started with Fabric.
Version 0.9.15.
I am not and will not be using Node for this project.

Markup:

```
<canvas id=canvas></canvas>
```

JS:

```
var fab = fabric.StaticCanvas('canvas');
```

Which then throws the error:

```
Uncaught TypeError: Object #<Object> has no method '_initStatic' 
```

**Comment by saran110313** [comment]
fabric.util.loadImage( '    ../sample.png' , function(img){ 
});
Uncaught TypeError: object.render is not a function
fabric.StaticCanvas.fabric.util.createClass._onObjectAdded	@	fabric.js:6378
fabric.Collection.add	                                                      @	fabric.js:198
