### ISSUE TITLE
Editing text in Chrome on Android is broken

### ISSUE THREAD

**Issue by jeroengijsman** [fabricjs/fabric.js#3368]
Try editing one of the examples on:
http://fabricjs.com/test/misc/itext.html
- when typing text in one of the examples, parts of the already existing text is sometimes added.
- the back/delete button doesn't work, if you hit it a few times and then tap the text again the text partialy gets updates.
- Sometimes the cursor is way off, (i think this is because of all the extra added text)
- i managed to crash the Chrome browser by just typing a couple of words and ignoring all the previous bugs

Tested on Android 6.x and 7.x on a Nexus 5, Nexus 5X and Nexus 6P

**Comment by asturur** [comment]
are you using the autocomplete text on keyboard?

**Comment by jeroengijsman** [comment]
@asturur no this is without autocomplete. Actually it already happens by just typing one letter

**Comment by ivelfan** [comment]
Same issues on Android 4.4 on Samsung Galaxy Tab E.

**Comment by jeroengijsman** [comment]
@asturur any news on this? Any suggestions? A'd really like to tackle this problem

**Comment by asturur** [comment]
delete key does not work, and cursor jump ( that can be a retina problem )
any tool to debug javascript on mobile devices?

**Comment by jeroengijsman** [comment]
@asturur i did some more testing with phones hooked up to my laptop and used the `chrome://inspect` to see if anything weird happens but so no errors or thinks that might be the problem.

Did you already tested this yourself? i think it's easier to talk about this if you have seen the behaviour on android

**Comment by asturur** [comment]
yes i tried on android. i think i have to make up a test page that prints on html some event properties to figure out what is going on.

**Comment by jeroengijsman** [comment]
@asturur did you create a branch for this? Maybe i can help with testing and figuring out whats wrong 👍

**Comment by austindunn** [comment]
Experiencing this on Nexus 6

**Comment by Brewal** [comment]
Same on Nexus 5 android 6.0.1

**Comment by krisrang** [comment]
Experiencing on Nexus 4 with Android 5.1.1. From what I gathered the bogus text gets added when onCompositionUpdate triggers on the itext so removing that listener on android works around that issue and makes it halfway usable but the delete and other issues remain.

**Comment by asturur** [comment]
this will probably be fixed in a future release, where i decided to rewrite the text component for easier mod/ input capabilities.
Keep in mind that canvas element on mobile browsers has so many limitation and is not in supported list at all.
That does not mean i m not really trying to fix it.

**Comment by arminbusatlic** [comment]
Hello, even though it does have many limitations, this limitation with iText on Android is quite big, maybe the biggest and most restrictive. iText is pretty much unusable on Android devices which is a big deal. 

Thank you for your support. Keep us updated on when you think this issue could be resolved.

**Comment by Sysaninster** [comment]
I have similar problems with the back/delete button in android 4.2.2 (Lenovo B8000-H), but I don't have any problems in android 6.0.1 (Samsung Galaxy A7 (2016)).

**Comment by MattiLehtinen** [comment]
Experiencing this with nexus 5X (android 7.1.2)

**Comment by asturur** [comment]
Hey someone of you have a way to test the new fabricjs 2.0 beta with the android devices? is available on NPM and for download. is not on website yet.

**Comment by davidrossiter** [comment]
I just came here looking for a solution or to draw some attention to this issue, but you guys have it covered! I am experiencing the same, it's the only drawback I've had with FabricJS.

https://streamable.com/4jr4m

It happens with auto correct on or off, same result.

Delete doesn't work well at all, after 10+ clicks it may delete 1 character.

It duplicates many characters and random ones when you type anything.

It eventually crashes,

Experiencing it on Android 6 and 7 on these devices:
Sony Z5 Compact 
Samsung Galaxy S7 Edge

**Comment by davidrossiter** [comment]
Just gave it a test and this is fixed in 2.0 beta 😀

**Comment by asturur** [comment]
thanks for confirming it

**Comment by sschendel** [comment]
Is this issue confirmed fixed? Should issue be closed?

**Comment by asturur** [comment]
i think it works. Just can respond weirdly with strange setups.

**Comment by amitmgit** [comment]
Hi Andrea,
I have tested small piece of code to write text using iText feature of fabricjs but seems to me it's not working with android chrome browser but same thing working with firefox browser app in mobile and in desktop everything is fine. Not getting where is the issue for android chrome browser.

I was trying with this sample code in website :


canvas = new fabric.Canvas('c');
var textbox = new fabric.IText('New\nText Here', {
	  left: 50,
	  top: 50,
	  fontFamily: 'Helvetica',
	  fill: '#333',
	  lineHeight: 1.1,
	  styles: {
		0: {
		  0: { textDecoration: 'underline', fontSize: 80 },
		  1: { textBackgroundColor: 'red' }
		},
		1: {
		  0: { textBackgroundColor: 'rgba(0,255,0,0.5)' },
		  4: { fontSize: 20 }
		}
	  }
	});
	canvas.add(textbox).setActiveObject(textbox);
I'm using this reference - https://jsfiddle.net/4nzygs8a/

Please respond me. Thanks in advance

Regards
Amit

**Comment by asturur** [comment]
is unclear what is not working. What is not working?

**Comment by amitmgit** [comment]
Not able to type anything inside the box even existing text not able to delete.

**Comment by amitmgit** [comment]
Just open this jsfiddle into you android mobile and try to type something on itext its not working.
