### ISSUE TITLE
Feature for scaling object by corners (tl, tr, bl, br) - non-uniscaling width and height

### ISSUE THREAD

**Issue by Kienz** [fabricjs/fabric.js#338]
Hey kangax,

your first implementation of dynamic origin looks quite good.

Maybe you can implement non-uniscaling the object by the corner 'tl', 'tr', 'bl' and ''br'.

Here you can see a example of google drawing:
<img src="http://kienzle.geschaeft.s3.amazonaws.com/projects/sketch/non-uniscaling_object_corners.png" />

**Comment by taqimustafa** [comment]
> "uniScaleTransform" (default: false, activated with shift key or programmatically).

Is this is supported in latest version of fabricjs ?

It only works when i press shift button. I want that to work as default, without pressing Shift.

**Comment by asturur** [comment]
Hi Taqi, yes it works.
it is a canvas property, not on per object basis

`canvas.uniScaleTransform = true;`
