### ISSUE TITLE
Import svg support in nodejs

### ISSUE THREAD

**Issue by afdev82** [fabricjs/fabric.js#3466]
I'm trying to use an svg as a pattern in nodejs, but it doesn't work.
I followed the instructions on [this page](http://fabricjs.com/fabric-intro-part-4#node)
I searched in node-canvas and for me it's not clear yet if this feature is supported or not.
If I change the fill to 'black', it works.

## Version of fabricjs
1.7.0

## Version of nodejs
6.9.1

## Version of node-canvas
1.6.2

## Test Case

```js
/** test.js */

var fs = require('fs'),
    fabric = require("fabric").fabric,
    output = fs.createWriteStream(__dirname + '/preview.png');

var canvas = new fabric.createCanvasForNode(500, 500);

fabric.Image.fromURL('p.svg', function(img) {
  var patternSourceCanvas = new fabric.StaticCanvas();
  patternSourceCanvas.add(img);
  var pattern = new fabric.Pattern({
    source: function() {
      patternSourceCanvas.setDimensions({
        width: img.getWidth(),
        height: img.getHeight()
      });

      return patternSourceCanvas.getElement();
    },
    repeat: 'repeat'
  });

  canvas.add(new fabric.Rect({
    left: 50,
    top: 50,
    height: 400,
    width: 400,
    fill: pattern
  }));

  canvas.renderAll();

  var stream = canvas.createPNGStream();
  stream.on('data', function(chunk) {
    output.write(chunk);
  });
});
```

## Steps to reproduce
Just run in the console `node test.js`

## Expected Behavior
A `preview.png` of a rect with the pattern applied.

## Actual Behavior
An empty png.

[pattern.zip](https://github.com/kangax/fabric.js/files/622240/pattern.zip)

**Comment by afdev82** [comment]
[pattern.zip](https://github.com/kangax/fabric.js/files/622246/pattern.zip)

**Comment by temuri416** [comment]
I think the problem here is that SVG is loaded asynchronously and you write to output before SVG is rendered.

I am currently experiencing a similar problem - I'm loading SVG definition from string:

```js
var addSVGElements = function(objects, canvas) {
    var svgContainer = {};
    for (idx in objects) {
        svgEl = objects[idx];
        elIdx = fabric.Object.__uid;
        svgContainer[elIdx] = svgEl;
        fabric.loadSVGFromString(svgEl['svg'], function(objects, options) {
            var obj = fabric.util.groupSVGElements(objects, options);
            if (obj.svgUid in svgContainer) {
                options = svgContainer[obj.svgUid];
                obj.set(options);
            }
            canvas.add(obj);
        });
    }
};

...

req.on('end', function() {

    var json = 'definition here'; // Comes from request
    
    var fabricJSONdefinition = JSON.parse(json);

    var svgElements = [];
    var svgIdx = [];

    if ('objects' in fabricJSONdefinition) {
        // ...

        for (i in fabricJSONdefinition['objects']) {
            obj = fabricJSONdefinition['objects'][i];

            // Collect SVG objects.
            if (obj.type == 'path-group') {
                svgElements.push(obj);
                svgIdx.push(i);
            }
        }

        // ...
    }

    // ...

    canvas.loadFromJSON(json, function() {

        /**
         * Once Canvas is rendered, position SVG elements.
         */
        if (svgElements.length) {
            addSVGElements(svgElements, canvas);
        }

        canvas.renderAll();
        res.end(canvas.toSVG());
    });
});

```

In my case callback of `fabric.loadSVGFromString` is executed after `res.end(canvas.toSVG());`, thus none of SVGs are rendered.

So, at this point I haven't figured out how to "wait" until SVG rendering is complete.

@kangax Your assistance will be greatly appreciated!

Thanks!

**Comment by afdev82** [comment]
I'm new to nodejs, so I don't know if I made mistakes in my test case.  
What I really want is to use an svg as a pattern, in the browser is rendered correctly, but it fails in nodejs and I don't know why. I searched the node-canvas repository and I found a lot of issue regarding import SVG in canvas (https://github.com/Automattic/node-canvas/issues/494, https://github.com/Automattic/node-canvas/pull/811).
It seems that also others have the same problem (https://github.com/vega/vega/issues/600#issuecomment-230184545).
I really don't know how fabricjs handles it, if the import of svg as an image (to create a pattern) is supported in nodejs or not.

**Comment by afdev82** [comment]
I prepared a simpler example, without the pattern.
Just simply load the image in the canvas. With a JPG it works, it doesn't work with the svg provided.

```js

var fs = require('fs'),
    fabric = require('fabric').fabric,
    output = fs.createWriteStream(__dirname + '/preview.png');

var canvas = fabric.createCanvasForNode(800, 800);
canvas.backgroundColor = '#FFF';

fabric.Image.fromURL('p.svg', function(img) {
  canvas.add(img);

  canvas.renderAll();

  var stream = canvas.createPNGStream();
  stream.on('data', function(chunk) {
    output.write(chunk);
  });
});
```

Importing the svg with `loadSVGFromURL` works, but it's not what I need, because I have a running code in the browser that loads the svg as an image to create a pattern.  
I wish to reuse this code in nodejs to generate the same drawing, in order to save it into a file.

**Comment by asturur** [comment]
if nodeCanvas does not support rendering of svg in theyr Image() counterpart there is little we can do. Is probably related to the backend they use.
Did you try to use phantomJs under node or similars?
Did you open an issue on node-canvas tracker?

**Comment by afdev82** [comment]
I didn't open any issue on the node-canvas because there are already issue for the svg rendering, but I was not sure if it was supported in fabricjs, this is why I asked here.
I didn't find any doc in fabric that says that `fabric.Image.fromURL` doesn't work with SVG in nodejs, maybe I was doing something wrong, I wanted only to know if it's supposed to work.
I tried already phantomJS, but I have to use a big (very big canvas) in order to generate printable svg of the canvas with patterns. The patterns are resized when I import them, so in order to have good quality I need the canvas in real size (in my case the maximum size would be 3m x 3m) and then export as svg (at this size the png is not a viable solution).
With phantomJS then I hit the limit of the canvas size in the browser.

**Comment by asturur** [comment]
We need to update the docs with this finding about nodejscanvas. I m not a nodejs expert too and this is why i lack in fixing/finding bugs there.

I do not know on which version of chrome phantom is based, but on modern chrome you can render up to 16kx16k pngs with little delay. Firefox can go higher
When the PNG is imported as image, it takes the dimensions of  its viewbox and will not get more details on scaling used as a pattern.

Can you explain better your problem?

You have a svg that u need to use as a pattern on some objects
Then you have to export everything at printable size.

Am i missing something?

**Comment by afdev82** [comment]
Basically it's what you said:

> You have a svg that u need to use as a pattern on some objects
Then you have to export everything at printable size.

The following explains what I tried so far.
Just say that I have a Rect on the canvas that could be filled with patterns.
I use svg images as a source for the pattern, because I could also scale its size (this is why I use svgs to get the best quality).
The size of the Rect could be maximum 3m x 3m and I need to export it as a printable image from the canvas.
I have to do this server side, because I want to be able to save the printable image without user interaction and allow to download the file once it is ready.
As far as I know there are two options: phantomJS and nodejs.
I tried with phantomJS to export as a PNG, both with a big canvas and using the multiplier while exporting a smaller canvas and it didn't work, in Firefox I got the NS_ERROR_FAILURE, I think because of the canvas too big (it could be 35433px x 35433px). Even if I could export such a big PNG, my pc would crash handling this image.
Then I tried exporting the SVG of a smaller canvas and set in the options the viewbox of that SVG.
It worked, but the patterns were low quality, I think because they are imported first as raster images at small size when used as patterns. Then I understood that probably I have to use a real size canvas somehow and this would be possible only with nodejs.
Finally I used a nodejs script, imported my js logic to draw the canvas and I discover that error using the SVGs as patterns, with PNG images it worked.

Anyway for my needs, I would prefer the nodejs solution, because I could run the js directly without having to "render" a page and mantain an URL just to draw a canvas in a "virtual" browser. But I didn't get the solution yet with both methods.

**Comment by asturur** [comment]
i guess nodeCanvas will crash also. 35kx35k, so 3 meters at 300dpi more or less is around 4gigs of ram just for pixels data. am i wrong?

i guess fabric can be tweaked to handle without need to render, creation of a svg as big as you want with an svg pattern, but not image. the  from svg to png you have to find another solution. not a javascript one.

other approach is tiling. make fabric output small canvases of 3kx3k that then tiled togheter gives you the big big png.
how you put them togheter i have no idea.

**Comment by asturur** [comment]
or maybe give back a pdf. is easy to create a php script that bundle images in a big pdf of 3mx3m. take care that so much data will make a reader crash probably.

**Comment by afdev82** [comment]
Thank you for your feedback.

What do you mean with "svg pattern"?
> i guess fabric can be tweaked to handle without need to render, creation of a svg as big as you want with an svg pattern, but not image. the from svg to png you have to find another solution. not a javascript one.

As far as I know it's not possible to have svg patterns, I tried that, but never got to work, that's why I import the svg as an image. When I export the svg the pattern is exported in base64/png format anyway.
Exporting the canvas as a big svg in nodejs works, the only missing piece is how to import the svg for the pattern.
All the other solutions will lead to problems, as you already said.

**Comment by asturur** [comment]
This is the svg output for a pattern:

![image](https://cloud.githubusercontent.com/assets/1194048/20922811/c63709ba-bba9-11e6-86c2-1b74983a4e65.png)

i guess you can replace that image tag with the full content of your svg and get a pattern done.
That means you will export an svg and not a png, but at least you have a representation of your design that then you can rasterize with something else.

Is not easy to handle very big canvases you have to look for a crafted solution.

**Comment by afdev82** [comment]
Yes, I meant it's not possible in fabricjs.
It's not an issue to have the PNG in the exported SVG, in this way I include everything in the file itself, it's more portable.
The only issue that I have at the moment is how to import the SVG in nodejs, then it should be fine.
But if you confirm that this is not an issue of fabricjs, but of node-canvas instead (as I thought), you can close this issue and I have to wait the fix for node-canvas or find another way to generate the image.
Thank you for your support.

**Comment by afdev82** [comment]
> i guess you can replace that image tag with the full content of your svg and get a pattern done.
That means you will export an svg and not a png, but at least you have a representation of your design that then you can rasterize with something else.
Now I got what you meant.
Yes, with hand made work it could work to have the svg in the pattern tag, I think.
I will think about it, maybe manually modify the exported svg could be the solution.

**Comment by asturur** [comment]
this is an old issue, node canvas 1.6 did not support svg loading and nor we do support svg patterns.
I m closing for now, since has long inactivity anyway.

**Comment by afdev82** [comment]
As far as I understand, this should be possible now in v2.0.0 of node-canvas, out since 18 hours :smile: https://github.com/Automattic/node-canvas/pull/811#issuecomment-330188996

**Comment by asturur** [comment]
yes but we need to modify a couple of things before being able to use node-canvas 2. Also we need to drop support for node4 and so bump fabric to 3

**Comment by afdev82** [comment]
yes, I expected that it was not so easy... ;)
