### ISSUE TITLE
drawingMode - line shifts moves down slightly after drawing

### ISSUE THREAD

**Issue by kangax** [fabricjs/fabric.js#347]
Hi, 

In drawingMode, after drawing a line, sometimes the line moves down a bit.  Maybe related to the smoothing?  

My app is a very simple test app, so I don't think I'm doing anything to cause this behavior.  It doesn't happen in the kitchensink app.  Has anybody else had this problem? 

Thanks,
Patrick

http://jsfiddle.net/SXKyy/4/

**Comment by azerum** [comment]
I still had this issue with fabric 5.2.4. I had `border` style on my `<canvas>`, once I removed the style, the bug disappeared. I've solved this problem by wrapping `<canvas>` into `<div>` and applying `border` style to the `<div>` itself
