### ISSUE TITLE
animate patterns/gradients [Feature request]

### ISSUE THREAD

**Issue by ncou** [fabricjs/fabric.js#3514]
Hi,

Do you think an animate fonction for the background could be added as a feature in the future roadmap ?

somethink like : 

canvas.background.animate(style = "scroll-left-to-right", speed = 1.0, duration = -1, loop = true, pattern="repeat")

Or perhaps a function "plugin-like" ?

_Detail :_
With style could be : scroll-left-to-right / right-to-left / top-to-bottom / bottom-to-top
And pattern = repeat to duplicate the background to made the scroll resume the picture on the oposite part of the canvas during the scroll (if a picture is scrolled at 50% to the left, the other 50% is show on the right part of the canvas, if pattern is not set, you need to wait that 100% of the background is scrolled on the left, to see it appear again on the right side of the canvas).

There is an animate() function but it does not work for the background object and not allow a continious scroll (in theory you could scroll the "left" propertie but for a continuous scroll you need a duplicate background to appear after the first background who is being scrolled).

Thank you for your insight.

**Comment by asturur** [comment]
animate function animates properties, so it should work anyway. if you can open a fiddle with trying to animate a background we can see why is not working.

**Comment by ncou** [comment]
Hi,

Here is a quick fiddle with a test to animate the offsetX of an object.
http://jsfiddle.net/QT3pa/160/

But there is an error, it seems the "animate" function is not found on the pattern objects.

**Comment by asturur** [comment]
yea animation is just for object.
Animation support sort of dot notation ( animatr x
.y of an object ) but i do not think it can animate object.fill.offsetx.  but we should make it possible so that grandients, patterns can be animated

**Comment by ncou** [comment]
good news if this could become a future "feature".
