### ISSUE TITLE
Inconsistency with nodejs (spacing to the right of text)

### ISSUE THREAD

**Issue by mirzabusatlic** [fabricjs/fabric.js#3516]
Hello,

I'm getting an inconsistency with Text between the client-side and server-side (nodejs). There is extra space appearing to the right when the Text is generated on the server-side. 

### Client-side:

![image](https://cloud.githubusercontent.com/assets/2063091/21058027/18be87e6-be0a-11e6-8b22-bb2c9b646c49.png)

Printing the text.width & text.height produces: 313x56.5

### Server-side:

![image](https://cloud.githubusercontent.com/assets/2063091/21058028/1c066626-be0a-11e6-8377-78d39a37720b.png)

Printing the text.width & text.height produces: 380x56.5

I used a red background to illustrate the difference, but the extra spacing on the right side still occurs whether there's a background or not. It doesn't matter what font I use.

### Code
The code for the client-side is obvious (you won't see the extra spacing on the right in any case). Here's the code on the server-side. Run it using `node run.js`. Replace the path to the font file. You can use the font I used: [files.zip](https://github.com/kangax/fabric.js/files/642802/files.zip)

#### run.js
```javascript
var fs = require('fs'),
		fabric = require('fabric').fabric;

var canvas = fabric.createCanvasForNode(1000, 1000);

var font = new canvas.Font('IndieFlower', '/path/to/font/IndieFlower.ttf');
canvas.contextContainer.addFont(font);

var text = new fabric.Text('regular', {
	text: 'Your Text Here',
	fontFamily: 'IndieFlower',
	fontSize: 50,
	fill: '#ffffff',
	backgroundColor: '#ff0000'
});

canvas.add(text);

// Trim
canvas.setWidth(text.width);
canvas.setHeight(text.height);

console.log(text.width, text.height);

var out = fs.createWriteStream(__dirname + '/server.png');
var stream = canvas.createPNGStream();
stream.on('data', function (chunk)
{
	out.write(chunk);
});
```

Any help would be greatly appreciated.

## Version
1.6.5

**Comment by friday** [comment]
Have you tried installing libpango, node-canvas 1.6.1 or later and fabric 1.7.x?

**Comment by mirzabusatlic** [comment]
@friday I actually had to make sure libpango was not installed on my system (Ubuntu 16.04) when running 'npm install' because loading in fonts would not work, as per this issue (you created): https://github.com/kangax/fabric.js/issues/3272

**Comment by friday** [comment]
Yeah, that fixes the font-loading issues. Fabric uses node-canvas which up until recently misimplemented libpango, which is why you had to do that. However they fixed that issue now and if you use node-canvas 1.6.1 or later custom font loading works. That version uses libpango for font rendering instead of libcairo, so if there is an issue with how the font is rendered now it could potentially have been fixed in node-canvas 1.6.1.

**Comment by friday** [comment]
Ignore my previous comment. It hasn't been fixed. It will be fixed in node-canvas 2.0 ̰0

**Comment by mirzabusatlic** [comment]
@friday: Thanks for the info. I think I may go with the approach you said you used, by generating it on the client-side and uploading it to the server. There's too many inconsistencies otherwise & it's too difficult to get it right

**Comment by friday** [comment]
It will still be inconsistent between browsers and OSes, as fonts normally are.
