### ISSUE TITLE
IOS 2 keys hold on keyboard -> missed focus from hiddenTextArea

### ISSUE THREAD

**Issue by Rad1calDreamer** [fabricjs/fabric.js#3522]
## Version
1.7.0

## Test Case
http://jsfiddle.net/Rad1calDreamer/77ea4bae/1/

## Steps to reproduce
1) focus on itext
2) on keyboard press 2 buttons (keys must hide)
3) try to type
## Expected Behavior
text typing
## Actual Behavior
cursor in itext ticking but text not updatung

**Comment by asturur** [comment]
what do you mean by press 2 buttons?
2 buttons togheter? one after the other?
What `keys must hide` means?
I have no iphone, let me understand better.

**Comment by Rad1calDreamer** [comment]
sorry for delay answer.
make short video 
https://youtu.be/STy0AgXHvxM

**Comment by Rad1calDreamer** [comment]
when i hold 2 keys on textarea - i can move cursor, but if textarea is hidden, i cant continue typing. Press "backspace" and "enter" will "unblock".

In debbuging i found what if i hold to keys on textarea dont fire onInput event, but fired keyDown.
I add this trigger in

`onKeyDown: function(e) {
         if (!this.isEditing) {
            return;
         }
         if (e.keyCode in this._keysMap) {
            this[this._keysMap[e.keyCode]](e);
         } else if (e.keyCode in this._ctrlKeysMapDown && (e.ctrlKey || e.metaKey)) {
            this[this._ctrlKeysMapDown[e.keyCode]](e);
         } else {
            this.onInput(e);
            return;
         }
         e.stopImmediatePropagation();
         e.preventDefault();
         this.canvas && this.canvas.renderAll();
      }`

and fix it. But i dont know where i create new bug)

**Comment by asturur** [comment]
So i need to inspect the event. Would you be so kind to post an expanded console.log(e) of that event? I m curios what ios pass down.
Anyway routing the event to onInput could be a very valid idea. thanks.
