### ISSUE TITLE
selection background color for selection of multiple objects (group)

### ISSUE THREAD

**Issue by ncou** [fabricjs/fabric.js#3792]
Hi,

I have set the "selectionBackgroundColor" parameter for all the objects.
If i select a group of object, the selectionBackgroundColor is not applyed. Is that normal ?

Example with a single object :
![image](https://cloud.githubusercontent.com/assets/16743322/24180794/4e8164d6-0eb7-11e7-9b2c-ae61d4e87504.png)

Example with a group selection :
![image](https://cloud.githubusercontent.com/assets/16743322/24180816/6eac0766-0eb7-11e7-9fb0-d04d9ba31dce.png)

Shouldn't the background for the groupped selection be white ? like for the object selection ?

Thanks for your insights.

**Comment by asturur** [comment]
do not know what to say.
For activeGroup that selection is not done. I will check why and try to figure out if is a code limit or because it would look bad.

**Comment by ncou** [comment]
Hi,

There is a condition in the "drawSelectionBackground()" function to exit if it's a group.
I tried to remove this condition, but the backgroundselection for the group is now draw on the top left corner of the canvas.

It seems to me, there is no backgroundcolorslection for the group because some code is missing (and not because it would seems bad).
For drawing the borders, there is 2 fonctions, one for a single object and another one for drawing the borders for a group of objects.
For the moment, there is only one function to drawSelectionBackground, so it's for that i think there is some code missing.

**Comment by divyanshjain217** [comment]
is there any way to set background color for group (except the way to add rectangle of same size as of group), I have tried setting background color property, but it doesn't helped.

**Comment by asturur** [comment]
So group is mainly a container, it does not render anything, can i ask you what is your use case for a bg color on a group?

**Comment by divyanshjain217** [comment]
actually I am making an application, for which I have made subclass by extending fabric.Rect class with some custom properties and I consider them as 'files' as per my use case and when I group those files I wish to assign different colors to different groups to distinguish them on canvas depending on file type inside those groups.

**Comment by divyanshjain217** [comment]
> So group is mainly a container, it does not render anything, can i ask you what is your use case for a bg color on a group?

but I have seen 'background' color property in official documentation of Group section that's why I have asked here. Btw Thanks for help.

**Comment by daneto82** [comment]
I would like to know if there is any update on this. Thanks.

**Comment by asturur** [comment]
@daneto82 can you help showing a use case for this?

**Comment by talaviram** [comment]
> can you help showing a use case for this?

I have a strange use case but it might be reasonable.
I have a basic black and white canvas usage. in dark mode, I simply invert (with filter) the canvas.
But the selection is what I'm after. so while I can handle per object selection the multiple object selection isn't customizable.

<img width="301" alt="image" src="https://github.com/user-attachments/assets/6197c253-c030-4c22-98d6-eeeb9fdb299f">

<img width="112" alt="image" src="https://github.com/user-attachments/assets/182b36a1-1b82-4e60-9f64-05cd57ce97f5">

(Or I've missed something in the API :) )
