### ISSUE TITLE
Text position differs when apply text styles

### ISSUE THREAD

**Issue by antucg** [fabricjs/fabric.js#3816]
Hi guys I have a piece of text that is rendered using I-Text. I set font size to 72 and this is the output:

![08ee8cd0-15fd-11e7-8bc4-e78e753f7330 1](https://cloud.githubusercontent.com/assets/2089578/24549894/692e6cf8-1613-11e7-9eed-d09d369c9604.jpg)

I put the green line to be sure that is in the correct position.
Now when I put styles to each of the characters, this is font size again to 72, this is the output:

![08ee8cd0-15fd-11e7-8bc4-e78e753f7330 2](https://cloud.githubusercontent.com/assets/2089578/24549917/859ee250-1613-11e7-8711-2f798e261262.jpg)

I use node canvas to create the images, could it be that the libraries that render the text are the problem? It's not exactly the same node canvas and html canvas, right?

The I-Text json object looks like this:

{
          "width": 340.5599060058594,
          "height": 81.36,
          "left": 448.4860269339981,
          "top": 259.9,
          "r": 0,
          "opacity": 1,
          "effects": [],
          "flipX": false,
          "flipY": false,
          "value": "Text here ...",
          "type": "text",
          "fontSize": 72,
          "fontFamily": "Alegreya",
          "fontWeight": "normal",
          "fontStyle": "normal",
          "fontColor": "rgb(0, 0, 0)",
          "backgroundColor": "rgb(255, 0, 0)",
          "styles": {
            "0": {
              "0": {
                "fontSize": 72
              },
              "1": {
                "fontSize": 72
              },
              "2": {
                "fontSize": 72
              },
              "3": {
                "fontSize": 72
              },
              "4": {
                "fontSize": 72
              },
              "5": {
                "fontSize": 72
              },
              "6": {
                "fontSize": 72
              },
              "7": {
                "fontSize": 72
              },
              "8": {
                "fontSize": 72
              },
              "9": {
                "fontSize": 72
              },
              "10": {
                "fontSize": 72
              },
              "11": {
                "fontSize": 72
              },
              "12": {
                "fontSize": 72
              }
            }
          }
        }

Some keys might not be the default ones, but that is ok, I handle this in the backend.
Thanks.

**Comment by asturur** [comment]
if the the screens come one from web and one from node, with text, this kind of errors are possible.
You should try the new text to see if it behaves better, but i did not finish it yet.

**Comment by antucg** [comment]
Thanks for the answer. What is the new text?

**Comment by ncou** [comment]
I think asturur is speaking about the new itext lib. you can find the file in the "newtext" branch in the dist folder : 

https://github.com/kangax/fabric.js/tree/newtext

**Comment by asturur** [comment]
@antucg are you able to provide a simple node script that i can run with node script.js that produce that image? so i can test with new code.

**Comment by antucg** [comment]
I can't now, but tomorrow I will try to provide a jsfiddle with the code.

**Comment by asturur** [comment]
i need just the node.js code. you can post it here.

**Comment by antucg** [comment]
`var canvas = fabric.createCanvasForNode(width, height);
const font = new big.canvas.Font(fontFamily, `${__dirname}/../../fonts/${fontFamily}-Regular.ttf`);
font.addFace(`${__dirname}/../../fonts/${fontFamily}-Bold.ttf`, 'bold');
font.addFace(`${__dirname}/../../fonts/${fontFamily}-Italic.ttf`, 'normal', 'italic');
font.addFace(`${__dirname}/../../fonts/${fontFamily}-BoldItalic.ttf`, 'bold', 'italic');

var canvasLayers = [];
var text = funtion(element, array) {
    const options = {
      top: element.top,
      left: element.left,
      opacity: element.opacity,
      fill: element.fontColor,
      fontFamily: element.fontFamily,
      fontWeight: element.fontWeight,
      fontStyle: element.fontStyle,
      fontSize: element.fontSize,
      angle: element.r,
      lockUniScaling: true,
      flipX: element.flipX,
      flipY: element.flipY,
      styles: element.styles || {},
    };
    const text = new fabric.IText(element.value, options);
    text.index = element.index;
    array.push(text);
  }

text(data, canvasLayers);
canvas.add(...canvasLayers);
canvas.createJPEG({quality: 100})
        .on('error', (err) => {
          console.log(err);
        })
        .pipe(here we send to client);
`

This is more or less the code we use. I am using async to process all layers of an image, but this should work ok.

Thanks!!

**Comment by asturur** [comment]
@antucg could you please try on your code the latest npm package 2.0.0-beta1? i would like to know if it fix a bit node. Take care that it uses a different version of node-canvas, so maybe try with a fresh install.

**Comment by asturur** [comment]
i confirm that text is bad positioned with nodejs. i ll try to figure out why.

**Comment by asturur** [comment]
![image](https://cloud.githubusercontent.com/assets/1194048/25573623/712323f8-2e47-11e7-87b9-44bef0edbdbb.png)

to me the positioning is very bad.

**Comment by albertyou2** [comment]
Hey @asturur 
Have you sovled this problem yet? I '  also meet this problem . 
I use web fabric.js to create a JSON objects for canvas, then the JSON objects will be sent to my node server and will load in this way : canvas.loadFromJSON .

i found that the text positions are much different from web generated.The text gap is bigger than web generated.
The font size is also different too,  bigger than web .

######
this is the JSON objs created by web:
var json ={
  "objects": [
   
    {
      "scaleX": 2.92,
      "scaleY": 2.92,
      "fontFamily": "Source Han Sans CN Bold Bold",
      "top": 628.33,
      "left": 38.33,
      "width": 150,
      "fontSize": 50,
      "styles": {},
      "text": "啊啊啊",
      "type": "i-text",
      "fill": "#1548C9",
      "height": 56.5
    },
    {
      "scaleX": 2.5,
      "scaleY": 2.5,
      "fontFamily": "Source Han Sans CN Bold Bold",
      "top": 513.33,
      "left": 86.67,
      "width": 150,
      "fontSize": 50,
      "styles": {},
      "text": "好好好",
      "type": "i-text",
      "fill": "#EB0808",
      "height": 56.5
    }
  ]
}

###### this is my node js test code 
var fs = require('fs'),
    fabric = require('fabric').fabric,
    out = fs.createWriteStream('test.png');
var canvas = fabric.createCanvasForNode(800, 800);

canvas.loadFromJSON(json, function() {
    canvas.renderAll();
    canvas.createPNGStream().pipe(out);
});

OS: macos 10.12.6 / ubuntu 16.04
node : v 8.5.0
fabric: 2.0.0-beta.7
canvas:1.6.7

Thank you very much

**Comment by asturur** [comment]
this issue should be solved after canvas2 migration
