### ISSUE TITLE
Add support to repeat background image

### ISSUE THREAD

**Issue by plkumar** [fabricjs/fabric.js#382]
is it possible to repeat the background image, instead of Stretch? i want apply a pattern as background, without Stretching it.

**Comment by umangvyas** [comment]
​Hi @kangax

Setting the pattern as the background color of the canvas, stretches the pattern image while fetching DataURL with multiplier > 1.

**Comment by asturur** [comment]
Can you replicate in a fiddle?

**Comment by umangvyas** [comment]
@asturur, I have also added the issue @ https://github.com/fabricjs/fabric.js/issues/5884

DataURL with multiplier doesn't work as expected while using patterns.
