### ISSUE TITLE
Animating strokeDashArray? strokeDashOffset?

### ISSUE THREAD

**Issue by derpoho** [fabricjs/fabric.js#3835]
Hey,

thanks for the great work. I want to animate the strokeDashArray, or better the strokeDashOffset of a path. is this possible? 
When using SVG you can do this easily with the dashOffset, like in this example: https://css-tricks.com/almanac/properties/s/stroke-dasharray/

Is there a way to do this with fabric?

Greets Marcus

**Comment by asturur** [comment]
is not supported but couod be.
then you would start a normal animation.

there is currently no dashOffset support.

**Comment by lorkel** [comment]
Has anything like this been implemented?

**Comment by asturur** [comment]
i wrote no, and i wrote an explanation on how to implement it.

Then i made a full text search in the codebase and i found that is there
`strokeDashOffset`
And is in the docs too
http://fabricjs.com/docs/fabric.Object.html#strokeDashOffset

The animation utility should be able to animate it normally.

**Comment by lorkel** [comment]
@asturur Where did you write the explanation on how to implement it?

**Comment by asturur** [comment]
in the message that i trashed before posting that.

just use that property on the object and use the animation utility to fire an animation.

**Comment by lorkel** [comment]
Great thank you. [Here's a fiddle](https://jsfiddle.net/lorkel/Lmu8sk4x/16/) of an example for anyone else who ends up here.
