### ISSUE TITLE
LoadFromJSON with custom class results in blank Canvas

### ISSUE THREAD

**Issue by gjijon** [fabricjs/fabric.js#3851]
## Version
1.7.7 and 1.7.9

## Test Case
https://jsfiddle.net/knc1Leuz/18/

## Steps to reproduce
1. Just define  one class and try to load from JSON. In fiddle I use the json from example.

## Expected Behavior
If I use this class to draw in canvas, the result is a rect with a label in it.

## Actual Behavior
After **stringify** and reuse the String, the result is a canvas with no elements and no errors in console (not even the classic "klass" exception)

**Comment by gjijon** [comment]
If you change the "labeledrect" from JSON to"rect" everything is "ok"

**Comment by gjijon** [comment]
And if you change the object definition to the way that is explained [here](http://fabricjs.com/fabric-intro-part-3#subclassing) nothing of this will work. I mean, the code not even pass to calling object constructor.

**Comment by asturur** [comment]
https://jsfiddle.net/knc1Leuz/19/

you need to see how another fromObject function is made and copy it.

**Comment by gjijon** [comment]
Thanks, I think that many people will be thankful with this.

**Comment by mdumrauf** [comment]
This should be part of the docs!

**Comment by ShaMan123** [comment]
#8203 will handle this
