### ISSUE TITLE
Text selection causes page to scroll/jump to top in Chrome

### ISSUE THREAD

**Issue by mlev** [fabricjs/fabric.js#3890]
## Version
1.7.11

## Test Case
Kitchen Sink Demo

## Steps to reproduce
1. Scroll the page down a little
2. Start editing the right hand text box and position cursor at start of "foo"
3. Select the word "bar" using the mouse

## Expected Behavior
"bar" becomes new selection.

## Actual Behavior
"bar" becomes new selection AND page scrolls to top.

## Notes
- Scrolling __doesn't__ occur if the new selection starts/ends/includes the current cursor position
- Only seems to affect Chrome - tested in Stable 57.0.2987.133 and Canary 60.0.3080.5. Safari and Firefox working ok.
- I tried enabling Scroll Anchoring in Chrome but it didn't make any difference (chrome://flags/#enable-scroll-anchoring)

**Comment by asturur** [comment]
agree. strange! i look into it asap

**Comment by asturur** [comment]
is a problem of 1.x branch only, new master branch 2.0beta is ok

**Comment by mlev** [comment]
I'm still seeing this with 2.0.0-beta.1. This fiddle was a simple as I could make it https://jsfiddle.net/mlev/3ox8fL81/4/

**Comment by asturur** [comment]
it does not happen 100% on branch 2.0. this gives me idea it can be fixed. no idea how.

**Comment by asturur** [comment]
i already spent a couple of hours on it without success. what is making the page scroll is the `focus` command on the hidden textboard that is necessary to keep the keypress capture working.
