### ISSUE TITLE
Disable "perPixelTargetFind" on some objects

### ISSUE THREAD

**Issue by MatBdry** [fabricjs/fabric.js#4020]
## Version
1.7.13

## Test Case
https://jsfiddle.net/y12yLvgv/4/

I have a problem when I try to set `perPixelTargetFind` on a specific object on the canvas.

First, I set it to true for the all canvas, but I want it to be false on the textBox. On the fiddle, we can see that, even if I set it to false on the textBox, the textbox is not selectable (it keep the attribute of the canvas). Is there any solution for this issue ?

I tried to override `fabric.Object.prototype.perPixelTargetFind = true;` but that creates issue on try to select a group.

Thanks a lot !

**Comment by asturur** [comment]
Well being the double option a simple logic OR, there is not other chance:

if you want to select just some object: activate per object
if you want all canvas but not some objects: set Object.prototype. perPixelTargetFind = true and turn it off for the specific objects.
If groups create a problem, set fabric.Group.prototype.perPixelTargetFind = false.

There are no other ways.

What kind of problem did you find with groups?

**Comment by mbaudry** [comment]
Ok, it missed the options `fabric.Group.prototype.perPixelTargetFind = false`, to specify the behavior when we select multiple objects.

**see the fiddle:**

https://jsfiddle.net/y12yLvgv/5/

![issue_perpixeltargetfind](https://user-images.githubusercontent.com/15127641/27425610-3d9873ec-5739-11e7-9da1-f2408785c5b9.gif)

**Comment by asturur** [comment]
understood the point of the bug.
I have no idea which is the right behaviour.

Effectively you are missing the target because is transparent. So the selection is broken, but for some reason the text is given also as a valid target after your mouse move....

i wrong

**Comment by mbaudry** [comment]
May be this condition in `_checkTarget` function is to strict: `(this.perPixelTargetFind || obj.perPixelTargetFind)`

If the canvas has perPixelTargetFind equal to true, but the object not, we should take into account the value for the object, and not for the canvas. But it depends of the case...

**Comment by Macavity** [comment]
I concur, if perPixelTargetFind is false for an object and true for the canvas then i would expect i can select the object by clicking on transparent areas.

**Comment by Macavity** [comment]
At least it is currently possible to solve the problem the other way around: https://jsfiddle.net/y12yLvgv/8/
