### ISSUE TITLE
Bug on scrollable list after drawing on iOS 9

### ISSUE THREAD

**Issue by MatBdry** [fabricjs/fabric.js#4078]
## Version

1.7.13

## Test Case

https://jsfiddle.net/y12yLvgv/13/
iOS 9.0

When I have a scrollable list on my web page, the scroll is disable after a drawing on the canvas. I made research, and it seems it appears since the 1.7.4 version of fabric. It appears only on iOS 9.

![bug_fabric](https://user-images.githubusercontent.com/15127641/27958162-0dec759a-6322-11e7-9515-606e17267f63.gif)

**Comment by mvzen** [comment]
I'm getting the same thing.

Any updates on this?

**Comment by JSteunou** [comment]
Any hint on this issue @asturur or support of iOS 9 is dropped?

**Comment by asturur** [comment]
is not ios 9, is touch event management.

i bought a touch device for this purpose, i did not have any time to dig on it. would be helpfull if soneone can find the root cause before me

**Comment by JSteunou** [comment]
iOS 10 & 11 do not have this issue, so I dont know if it worth dig on it thoroughly

**Comment by TristanPct** [comment]
Reproduced on iOS 9.3.5 (on iPad) with fabric.js v2.2.1 in my Cordova app
