### ISSUE TITLE
toDataURL 'png' Cropping not working in Node.js

### ISSUE THREAD

**Issue by homerlex** [fabricjs/fabric.js#4079]
Fabric version: 1.17.2
Node Version: 6.9.1

I have a function like:
```
function convertToPng(canvasJson) {
	var canvas = fabric.createCanvasForNode(600, 600);
	canvas.loadFromJSON(canvasJson);
	return canvas.toDataURL('png', { width: 10, height: 10});
}
```

The PNG that is returned is 600x600.

A similar function run on fabric in a browser does crop the png properly.  Am I doing something wrong here?  Is this a known issue?

FYI I've done the same type of cropping with the toSVG function (on Node.js) and that is working properly.

**Comment by asturur** [comment]
is the snippet what you are actually using?

loadFromJson is async, should not you be using a callback?

can you share a single js file with a minimal JSON that i can test on my computer?

**Comment by homerlex** [comment]
Ignore the loadFromJson.  Even without it I can repro.  The following results in a ping that is 600x600 as well:
{code}
	var canvas = fabric.createCanvasForNode(600, 600);	
	return canvas.toDataURL('png', { width: 10, height: 10});
{code}

**Comment by asturur** [comment]
i ll try to test it to day. i have been busy

**Comment by asturur** [comment]
i do believe now everything works
