### ISSUE TITLE
Surface Pen stops working after native dialog is opened

### ISSUE THREAD

**Issue by koglerch13** [fabricjs/fabric.js#4090]
## Version
1.7.16

## Test Case
http://jsfiddle.net/h4p0c8zL/
Google Chrome (59)
Microsoft Surface w/ active pen

## Steps to reproduce
- Use a Surface with the active pen
- Use Google Chrome (59)
- Free drawing works
- Open the file dialog or alert
- Drawing with the pen is no longer possible

## Expected Behavior
Drawing with an active pen works, even after dialogs open

## Actual Behavior
Using the pen does not work, after a native dialog is used

**Comment by koglerch13** [comment]
Update:
I looked a bit more into this topic and found [a filed bug for chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=738357) that seems to cause this issue.
I updated my Fiddle with a (hack-ish) fix: http://jsfiddle.net/h4p0c8zL/3/

Hopefully this will be fixed in future chrome releases. Still, a fix in fabric would probably be nice.

**Comment by asturur** [comment]
i got a surface finally today. BUt i will not be able to use it for 10
days. I can start investigating the touch related stories

2017-07-12 17:32 GMT+02:00 Christian Kogler <notifications@github.com>:
