### ISSUE TITLE
[Feature] Integrate Pointer Event API for unifying mouse, touch and pen inputs

### ISSUE THREAD

**Issue by Faibk** [fabricjs/fabric.js#4134]
The [Pointer Event API](https://caniuse.com/#feat=pointer) enables the unified implementation of user input handling and eliminates the need for separate touch and mouse implementations. Therefore it might be worth the slightly higher initial effort compared to the work on touch events in #3869. It will definitely make the input more robust on browsers supporting it, while falling back to the usual implementation on older browser versions. 

My motivation for suggesting this is that we had some problems over at the [OpenseadragonFabricjsOverlay Repository](https://github.com/altert/OpenseadragonFabricjsOverlay/issues/11) where OSD supports pointer events and fabric does not. When OSD detects pointer support it stops sending mouse events and fabric receives no more events, what basicly breaks the overlay.

As a code sample I can provide my [Pull Request](https://github.com/altert/OpenseadragonFabricjsOverlay/pull/21) at the OSDFabricjsOverlay repository , where I made a first try to include pointer events with fabricjs (look at the file fabric/fabric.adapted.js). It is not much change and I will need your help determining if it breaks something else, but I think pointer events would be a big step into the future.

**Comment by asturur** [comment]
I took a touch device just for this.
Do you have some knowledge to share?
what about MSPointer? are those needed or better to fallback to mouse events for them?
Should i try to update event.js to support pointer events or bring the support in fabric?

I'm really undecided ( and in this filed unexperienced ) on what to do.

**Comment by asturur** [comment]
Anyway thanks for the start, i m trying to get 2.0 to a releasable state, so if i will not update anything here is because i m busy with the other things, i m interested in supporting this.

**Comment by Faibk** [comment]
I don't have much knowledge either, but from my experience the Mozilla Developer Network has some very good documentation of the APIs, so I would feel comfortable to look into this myself over the next few weekends. I am interested in these eventing topics and have already forked fabric. I will try and mess around a bit to get the knowledge needed.

About MSPointer, these are needed for IE10 and are the prefixed version of the official events, as usual for experimental browser support. Since IE11 the pointer event API is supported without prefix. I guess it is still better to use them than fall back to mouse events, since looking forward we should focus more on the pointer event implementation.

Does fabric.js already use event.js? 
Event.js does support pointer events and fallbacks, so I guess it makes a lot of sense to include this in fabric to also enable the multitouch gestures. The integration steps would be to replace all events in fabric with the generic event interface from event.js (e.g. mousedown => down). Event.js will then take over the detection of events from various input sources like touch or mouse and leave fabric to handle them.

**Comment by asturur** [comment]
fabricjs has optional binding to event.js
I m not touching since long, i have also no idea what happened to event.js those years.
Is still developed?
