### ISSUE TITLE
IText Keyboard Shortcuts are based on MacOS standards

### ISSUE THREAD

**Issue by jyguyomarch** [fabricjs/fabric.js#4143]
Hi,

Currently the [IText keyboard shortcuts](http://fabricjs.com/docs/fabric.IText.html) are based on the MacOS standards and this can be frustrating for Windows users.

The example I have currently is the "_Go to previous word_": currently it is being mapped to `Alt-Left` which is totally fine for Mac users. But Windows users would expect `Ctrl-Left`, and if they use `Alt-Left` most browsers will interpret that as "_Back: got to previous location in history_".

Is there already a solution in Fabric.js for this issue? If not, the only thing I can think of so far is detecting the user's OS at runtime and mapping the shortcuts accordingly.

Thx a lot
Currently using Fabric.js 1.7.7

For reference: [Table of keyboard shortcuts- Editing](https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts#Text_editing)

**Comment by asturur** [comment]
IT depends what ctrl+left does on MAC.

I m fine in adding alternatives as long as i do not break other functionalities

**Comment by jyguyomarch** [comment]
@asturur Ctrl+Left/Right will [cycle through your "desktops"](https://apple.stackexchange.com/questions/18043/how-can-i-make-ctrlright-left-arrow-stop-changing-desktops-in-lion) on Mac.
