### ISSUE TITLE
npm install with gestures

### ISSUE THREAD

**Issue by justin-hackin** [fabricjs/fabric.js#4155]
Is there any way to npm install fabric with gesture support ?  Asked here https://stackoverflow.com/questions/45428993/include-fabricjs-in-npm-dependencies-with-custom-build-for-gestures-module

**Comment by marsonmao** [comment]
As the linked question has been answered, you have to fork the fabric.js repo, then clone to your machine, then install and do `npm run build_with_gestures`, then push the built `dist/` folder to your forked repo. Now install this forked repo instead of the officially published repo.
