### ISSUE TITLE
SVG doesn't render in correct position

### ISSUE THREAD

**Issue by otterslide** [fabricjs/fabric.js#4158]
## Version
1.7.14

## Test Case
https://jsfiddle.net/otterotter/77bf32py/10/

## Steps to reproduce
Click on rectangle.
The rectangle should in the middle of the thin blue outline/object outline, but it is to the left.
Opening same SVG in InkScape and BoxySvg renders a rectangle in the middle of the canvas.

## Expected Behavior
Rectangle in middle of canvas.

## Actual Behavior
Too far to the left.. perhaps ViewBox is not taken into account properly.

SVG file at:
https://dropfile.to/aDvmYxa

Same canvas and shape if made into a box, 250x250 renders correctly.. 
Something to do with aspect ratio causes the issue? Any workaround appreciated.

**Comment by asturur** [comment]
this is the SVG
![image](https://user-images.githubusercontent.com/1194048/28891623-70245ca6-77cb-11e7-989c-ac01583e2756.png)

![image](https://user-images.githubusercontent.com/1194048/28891894-51111808-77cc-11e7-9af1-75e5fe26afad.png)


to me they looks ok.

**Comment by asturur** [comment]
this is how your fiddle loads the SVG without additional code
https://jsfiddle.net/77bf32py/15/
![image](https://user-images.githubusercontent.com/1194048/28891880-43b80da6-77cc-11e7-9399-57be39a74d19.png)

This is how the svg looks like in the browser

**Comment by otterslide** [comment]
and Inkscape:
![image](https://user-images.githubusercontent.com/11649943/28892054-9c8c2a70-779a-11e7-8924-83980cdef083.png)

It's just the left-right padding that is not consistent with actual one observed when saving the SVG, this is the issue.

**Comment by asturur** [comment]
I think is more a problem of a too wide pathGroup.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/28892895-c5687874-77cf-11e7-8587-318f3b405c1d.png)

It look in order for the specs i know. i see that browsers render it differently

**Comment by otterslide** [comment]
I rendered it with Apache Batik and it renders same as Inkscape.. In the middle.
I'm only changing height and it fixes it though in Fabric, although it doesn't make sense why it would.
It seems like height=125 feels too short for Fabric and it's squishes it?.. This is what seems like anyway..as the height is so short that it squishes the width.

**Comment by otterslide** [comment]
The shorter the height is, the more pronounced the effect:
   height="115"
![image](https://user-images.githubusercontent.com/11649943/28893132-53742b36-779e-11e7-82ec-f05544900ecf.png)

**Comment by otterslide** [comment]
And height="115" in Inkscape still renders it in the middle.

**Comment by asturur** [comment]
this is weird, it should just get out of bounds, not adapt.

**Comment by otterslide** [comment]
I think it has something to do with the X coordinate start calculation.. 
Basically, it fits, so it can't go out, but it's starting at the wrong X..  I don't know how height affects X coordinate though.

**Comment by otterslide** [comment]
Or it could have something to do with the fact that ViewBox has negative values.

**Comment by otterslide** [comment]
Nope,
viewBox="0 0 262.0053232 137.0053232"
same issue.

**Comment by otterslide** [comment]
it fits in middle like this, and quite perfectly.. although it goes out of bounds, as it should..

   width="250"
   height="110"
   viewBox="0 0 250 110"

increasing viewBox height should bring it in bounds:

   width="250"
   height="110"
   viewBox="0 0 250 130"
but changing the viewbox to a bigger height causes the issue to happen.
Seems something to do with viewBox versus width/height.

**Comment by asturur** [comment]
So what height are you changing here?
The viewbox define a scaling.

In the case of that SVG
width 250
height 200
viewbox -5 -6 1000 200

rect x = 4 , y = 4, width = 100, height = 100

means:

take a space that is 250x200.
Divide it in 1000x400 small areas ( sort of rectangular virtual pixels )
the first pixel in the top left is -5,-6,  so that means that the bottom right is 995,194 as position.

The rect extends from 4,4 to 100,100 of those virtual pixels.

What extend is the dimensionless line that define the rect. Then the stroke of 10 pixels is half left and half right of that line.

**Comment by otterslide** [comment]
viewBox = <min-x> <min-y> <width> <height>
I think ViewBox defines which pixels to take a "picture" of, and then width/height resize that picture to that width/height.

changing
viewBox="0 0 250 110"
https://jsfiddle.net/otterotter/77bf32py/18/

to
viewBox="0 0 250 130"
https://jsfiddle.net/otterotter/77bf32py/19/

should just add more height/white space at the bottom, but it affects the side.

I think Inkscape/other parsers seem to center if it is scaled down, while in Fabric is remains to the left.. maybe this is the issue.

You can ViewBox directly in the fiddle, the SVG is in the html part.

**Comment by otterslide** [comment]
Here is another that I just used for test:
https://jsfiddle.net/otterotter/77bf32py/20/
I scaled the height to 200 from 250, and in Inkscape it centered it, in fabric it didn't.  Seems to be just a centering missing when it scales down.

**Comment by otterslide** [comment]
Similar issue on the height scaling:
https://jsfiddle.net/otterotter/77bf32py/21/
stays at top but Inkscape/Browser moves it down to center , with equal top/bottom margins.

**Comment by asturur** [comment]
there are specs that defines it, no centering involved.

https://www.w3.org/TR/SVG/coords.html#ViewBoxAttribute

i need to check with calculator to understand how it should be displayed properly.

there may be some bug for sure.

**Comment by otterslide** [comment]
I think it should be like this: if ViewBox is greater than Width/Height, when ViewBox is scaled down, if scaled width is < canvas width center on X axis by adding to OriginX ((canvas width-scaledwidth)/2)
scaled height is < canvas height center on Y axis by adding to OriginY ((canvas height-scaledheight)/2)

I'm not sure if there is really is an OriginX though, or how you add the rendered SVG to the canvas Object.. but seems like an easy fix if you have those settings.

**Comment by otterslide** [comment]
"Just like viewBox, preserveAspectRatio has a lot of information in a single attribute. The default behavior can be explicitly set with preserveAspectRatio="xMidYMid meet". The first part, xMidYMid **tells the browser to center the scaled viewBox region within the available viewport region, in both the x and y direction**s. You can replace Mid with Min or Max to align the graphic flush against one side or the other. Watch the camelCase capitalization, though: SVG is XML, and is therefore case sensitive. The x is lowercase but the Y is capital."
https://css-tricks.com/scale-svg/
It says this is default behavior.

**Comment by otterslide** [comment]
Those specs you referred to don't say it clearly, but if you look at the happy faces with xMid and YMid they're in the middle, for preserveAspectRatio.

**Comment by asturur** [comment]
other than that refer to w3.org for specs. css tricks is not a reference.

**Comment by otterslide** [comment]
Csstricks just explained it better, it can easily be matched up with the W3 specs once you know what to look for.
From the w3.org page you mentioned, it does say it's the default.

xMidYMid **(the default)** - Force uniform scaling.
Align the midpoint X value of the element's ‘viewBox’ with the midpoint X value of the viewport.
Align the midpoint Y value of the element's ‘viewBox’ with the midpoint Y value of the viewport.

**Comment by asturur** [comment]
w3.org specify the default as you say.
Now i'm trying to figure out why we take that as none as default since it has been developed reading that website.

There is no support to preserveAspectRatio attribute for the SVG element, there is just for the images in svgs.

Yes so this is a bit of a pain as a bug.
For meet is ok to support it, for slice is difficult.
1) fabric cannot slice paths
2) fabric should consider in advance how big is the content and is not able to do so.

**Comment by otterslide** [comment]
I think default/xMidYMid meet  is going to be the most common scenario.. especially since nobody even noticed this yet.  I haven't seen any SVGs with slice set.
Thanks for looking into this.

**Comment by otterslide** [comment]
I don't think the current default is 'none' .. If I set none it stretches the SVG to the entire object, which is correct, no aspect ratio is preserved.
It seems to be the equivalent of 'xMinYMin meet' that is currently the default.

**Comment by asturur** [comment]
this has been fixed with 2.3.1, now the meet/slice is supported.
