### ISSUE TITLE
Inner Shadow

### ISSUE THREAD

**Issue by Aubron** [fabricjs/fabric.js#4239]
We've been using fabric.js for ScoreShots for over a year now, and it's been the backbone that's made our product possible. We're interested in if, as part of 2.0 or beyond, inner shadows will become a possibility, that is to say shadows that cover the fill of an object, which are clipped by the outer edge and/or stroke. Some places do this by setting a negative blur value, others have an 'inset' flag. This feature is present on most graphic design applications in some shape or form.

While I assume there is some way we can drop down to a canvas context and make this happen today, currently we're doing unfortunate hacks to try and replicate this kind of look and feel in our more advanced templates used by sports teams throughout the US. In particular, we're using a clipTo method that reduces performance pretty significantly, and could see a native solution providing a much better experience. Thanks!

**Comment by asturur** [comment]
Well there are not inset shadow in canvas, so native solution is out.

As soon as i m finished pulling this 2.0 releas around i would like to work on a better solution for clipping, that works better with cache. This would involve a clippingMask. Theorically panting a circle, without shadow, then painting a circular stroke with shadow and a clippingMask will give you an inner shadow. If this is supported by the cache system should make everything faster.

I cannot guarantee that it would be something like `shadow.inner = true` because i do not want to add too many features here and there, but i believe it would be possible in some way

**Comment by asturur** [comment]
Also remember, if you plan to update to 2.0, start asap because your problems during upgrading can be valuable insight in improving the API while is still in beta.

**Comment by asturur** [comment]
Do you think i can have an account to see what you have built?

**Comment by Aubron** [comment]
Yeah of course. I'd be happy to. You should get a registration email here in a bit. It's not awesome right now, it's the result of a year of learning and growing, but we have a react driven, fabric.js 2.0 based rewrite around the corner, and I'll ping you when that's a thing as well.

**Comment by asturur** [comment]
I saw it!
Is a nice idea!
Awesome or not it depends with what you compare to and the size of organization that backes it. I would not really be worried about it.

It looks like you disable retina support, i noticed since i have a mac and immediately looked blurry to me. Any reason? bugs with retina found?

**Comment by Aubron** [comment]
Yeah we've had some spooky retina bugs in the past (we actually still have one in which *sometimes* the canvas will produce images 2-3 times larger than desired when we render a png). It didn't help that we didn't have the budget to pick up a retina mac here in the office for a long time, and browserstacks doesn't let us emulate a retina mac easily.

Like I said, it's been the accumulation of a lot of hotfixes and bandaids, and we were real dumb when we started this project. Thanks for the praise!

**Comment by jimmywarting** [comment]
dose inset shadow works or not?
maybe some option about using `inverted`?

**Comment by jimmywarting** [comment]
i tried achieving this using the same technic described in https://stackoverflow.com/questions/37378088/inset-shadow-on-html5-canvas-image/37380488#37380488

```js
fabric.util.createClass(fabric.Rect, {
  initialize() {
    this.callSuper('initialize', options)
    this.set({globalCompositeOperation: 'xor'})
    this.setShadow("-2px -2px 7px #FFF")
    this.set({globalCompositeOperation: 'destination-atop'})
```

but it kind of backfire, it draws a inner shadow on a rectangle like i wanted it to do, but now the other objects won't be drawn normally, it kind of disappear

**Comment by jimmywarting** [comment]
can we re-open this issue?

**Comment by asturur** [comment]
We can keep it open if someone wants to provide a solution but we can't support inner shadow right now. To many rendering passes are needed on the canvas to make it work

**Comment by asturur** [comment]
also depending on the order in which you draw stroke or fill you need to change the logic. Is very complicated.

**Comment by jimmywarting** [comment]
Hmm, okey. can you maybe provide me with a workaround? I was thinking maybe if I could draw it in a separate canvas or draw it directly onto the top context somehow - more or less like [konva's sceneFunc](https://konvajs.org/docs/shapes/Custom.html). but i don't know if there is any equal functionality in fabricjs

It should be drawn last of all other object. And it dosen't have to be transparent. White rectangle with rounded corners and inner shadow is all i need. i can change shape like width/hight and border-radius

(i'm not using stroke, i'm using fill)

**Comment by juzhiyuan** [comment]
BTW, if fabric.js supports multiple fills, mutiple borders? I went through all issues and StackOverflow tickets, no more information found 😂😂

**Comment by asturur** [comment]
No it doesn't , that is why no information found.
Is something i always thought about but i would like to fix other things first.
Multiple fills would allow more complex design, especially with gradients

**Comment by juzhiyuan** [comment]
All right 🙈

**Comment by juzhiyuan** [comment]
> No it doesn't , that is why no information found.
> Is something i always thought about but i would like to fix other things first.
> Multiple fills would allow more complex design, especially with gradients

hi @asturur, could you provide some ideas about how to implement the multiple Fill and Border? Google told me I should add another shape to the current one.

**Comment by asturur** [comment]
well to add multiple fills, you should have an array of fills and repeate the fill code for each value of the array

**Comment by juzhiyuan** [comment]
Got it, let me have a try!

**Comment by natancabral** [comment]
https://github.com/natancabral/fabric-js-inner-shadow

**Comment by asturur** [comment]
@natancabral nice! Why don't you create a tutorial/demo for the website?

**Comment by natancabral** [comment]
> @natancabral nice! Why don't you create a tutorial/demo for the website?
Nice idea.
