### ISSUE TITLE
Clicking on source links from documentation results in an "Unresponsive Script" error

### ISSUE THREAD

**Issue by Pointy** [fabricjs/fabric.js#4253]
## Version
1.7.6

## Steps to reproduce

Pick some random class from the main documentation page. Find a "Source" reference with a clickable link, like some reference to `fabric.js` itself. Click that.

## Expected Behavior

I'd like to see the promised source.

## Actual Behavior

The browser freezes up until an "Unresponsive Script" alert is shown. The script in question appears to be a source code "prettifier". Allowing the script to continue does not work; it seems to be actually stuck.

**Comment by asturur** [comment]
for me it works.

**Comment by Pointy** [comment]
Using Linux Firefox 54.0 (64-bit)

**Comment by asturur** [comment]
the code formatter we have is probably slow.
Do you know any better?

**Comment by Pointy** [comment]
Well it's a little sluggish in Chrome, but in Firefox it behaves as if it's completely stuck in an infinite loop somewhere. I can click on the "Continue Script" button in the warning popup as many times as I like and it never completes.

**Comment by asturur** [comment]
what are the machine specs? so you have any extension active? ( like firebug or similar )

**Comment by Pointy** [comment]
I'm on a moderately good laptop running Linux 4.4.0.87. Firebug no longer works in modern versions of Firefox so no Firebug; and I've run into the problem running in a no-extensions browser profile so I don't think it's an extension.

**Comment by asturur** [comment]
i can open it with no probs from my macbook chrome or firefox.
 can you post a link that reproduces the problem 100%?

**Comment by Pointy** [comment]
Every single link from any documentation page to the source triggers the behavior. So, if I go to the main documentation page and select `fabric.Canvas`, and then from there click on the link to "line 8506", the page hangs.

As an additional note: it's clear from the browser console (not Firebug; the native console) that the browser is reporting various content security policy issues for URLs from twitter, carbonads, and gratipay. That could be what's messing things up.

**Comment by asturur** [comment]
i just belive the file is big and format it is a pain. probably a better source formatter is needed. no idea what to pick up.

**Comment by asturur** [comment]
This is a link if someone else want to try.
There is no problem in js itself.

If you want to provide machine specs and linux distro, i can try to figure out why it stops for so long. Otherways for me it looks like working.

Any plugin installed in firefox can interfere with loading times.

**Comment by tiesont** [comment]
I get the same behavior from http://fabricjs.com/docs/fabric.js.html#line18069:

![fabric-script-error](https://user-images.githubusercontent.com/420293/29892192-b541e034-8d9b-11e7-82d8-4a76a492376a.png)

This is on a Dell Latitude E6540 with a Core i7 CPU and 16GB of RAM, running Windows 10.

There are more than a few good highlighters out there, if that's what you think the issue is. I've used [Prism.js](http://prismjs.com/) and [Highlight.js](https://highlightjs.org/). You may also want to consider using something to pre-encode the source you're displaying, if it's that bad, or if JSDoc can be configured this way, default to displaying code in simple pre elements, and then use a setTimeout to highlight the code after a moment; not exactly sexy, but viewable > sexy, in my opinion.

**Comment by Pointy** [comment]
I get the behavior when running Firefox with no plugins at all. . It's not just slow: *it hangs in an infinite loop*. I can click the "Continue" option on the browser's slow script popup over and over again and it never finishes. I can't debug the problem because `prettify.js` is minified.

On the same machine, the page loads fairly quickly in Chrome. It's just a laptop but it's got plenty of memory and there's nothing else going on.

**Comment by asturur** [comment]
i would like to understand why i cannot replicate.
@tiesont do you have any link of jsdocs that explain how to pre render the source file?

**Comment by tiesont** [comment]
@asturur I don't know anything about JSDocs, but I can look.

**Comment by asturur** [comment]
i m sorry from your answer looked like you knew it was possible.

**Comment by asturur** [comment]
i ll mark this as help wanted, if someone wants to find a nicer solution.

Nicer solution could be:

Jsdocs pointing to the smaller original files rather the big one.
A better  source formatter, that loads fast or loads later or load progressively.
