### ISSUE TITLE
[Feature request] Filter function for the ActiveSelection Object

### ISSUE THREAD

**Issue by ncou** [fabricjs/fabric.js#4262]
Hi,

I didn't really think thoroughly, but a 'filter' function for the "ActiveSelection" coul be usefull.

I will try to explain a bit with my poor english, and i hope other people could add there ideas.

The main objective is to have a way to add a custom function who could work as a "Array.map()" to filter the objects in the ActiveSelection array.

I suppose by default this function could be a check on the "selectable === true" parameter for each objects (because normaly you should could select an "unselectable" object with an activeSelection object).

But this filter could be overridden by each developper, for example to add a custom function to prevent a user to select a locked object (example : if lockMovementX === true && lockMovementY === true you could use this filter in the activeSelection object when the user select objects).

This could open a way for the users to customise the selection allowed by the activeSelection (to prevent selection of lower z-index object, or a type of objects...etc).

@asturur : What do you think ?

**Comment by asturur** [comment]
So in the selection docs, no idea if i already wrote it, there is a `onSelect` method that works exactly like that.
You can define a function that return TRUE and make the selection voided or return FALSE and the selection works as normal.

For example  
```javascript
object.onSelect = function() {
  if (this.locked) return true;
  if (this.canvas.getObjects().indexOf(this) < 2) return true;
  // something else...
}
```

**Comment by ncou** [comment]
Perfect, i will try it soon.
Thank you.

**Comment by asturur** [comment]
http://fabricjs.com/v2-breaking-changes-2

give a check there

**Comment by ncou** [comment]
It seems the function only work when you select one object.
If you try to do a multiple selection the "onselect" event is not fired.

=> The green object is customized to not be selectable. It work when you click on the object.
1)
But if you select 2 objects, it seems to me it doesn't fire the onSelect envent.
https://jsfiddle.net/wta4pdpz/7/

2)
Also when you try to create a selection programmaticly it doesn't fire the event onSelect => is that normal ? (try to click on the button)

**Comment by ncou** [comment]
updated the demo, to ckeck the objects in the activeSelection, but without success.
https://jsfiddle.net/wta4pdpz/8/

Is that possible to deselect an object during an active selection ?

**Comment by ncou** [comment]
@asturur : hi, sorry to bother you do you think there is a workaround for this ? like changing on the fly the activeObject ? thanks

**Comment by ncou** [comment]
good news :)

**Comment by leesc81** [comment]
When I select the A object, I want to select the B object and keep the drag state on the newly selected B object. 
Can I select a B object while the mouse is hold down and let the B object drag when the cursor is moved? Dragging will stop when setSelection is done ...

This is an important feature to make my project successful ...

sorry my english...

Thank you

**Comment by asturur** [comment]
this has nothing to do with the library itself. is probably possible with the event system.
