### ISSUE TITLE
[fabric on nodejs] shadow doesn't render out and textbox scaling changes not only the size but relative position

### ISSUE THREAD

**Issue by rokenchou** [fabricjs/fabric.js#4265]
## Version
fabricjs 2.0.0-beta.6
nodejs 6.11.0
node-canvas 1.6.6

## Steps to reproduce
```
var jsonStr = '{"objects":[{"type":"circle","originX":"center","originY":"center","left":361.5,"top":234.5,"width":48,"height":48,"fill":null,"stroke":"#d6477f","strokeWidth":2,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":{"color":"rgb(93, 255, 79)","blur":13,"offsetX":0,"offsetY":0,"affectStroke":false},"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"evenodd","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"radius":24,"startAngle":0,"endAngle":6.283185307179586},{"type":"textbox","originX":"center","originY":"center","left":290.4,"top":335.5,"width":111,"height":67.8,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":2.82,"scaleY":2.82,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"主标题123","fontSize":30,"fontWeight":"normal","fontFamily":"Pingfang SC","fontStyle":"normal","lineHeight":1,"underline":false,"overline":false,"linethrough":false,"textAlign":"left","textBackgroundColor":"","charSpacing":350,"minWidth":20,"styles":{"0":{"0":{"fontFamily":"Wawati SC","fill":"#00a352","fontStyle":"italic"},"1":{"fontFamily":"Wawati SC","underline":true,"fontWeight":"bold"},"2":{"fontFamily":"Wawati SC","underline":true,"fontWeight":"bold","linethrough":true}}}}]}';

 var canvas = fabric.createCanvasForNode(1000, 800);

canvas.loadFromJSON(jsonStr, function() {
    canvas.renderAll();
});
```
## Expected Behavior
scaling of the textbox shouldn't change the position of the textbox, and the shadow should render out

I've created a jsfiddle (see below), see the browser side rendering use fabricjs with the same fabric json, there will be shadow of light green color near the circle and the textbox is under the circle
http://jsfiddle.net/ct9u56fr/4/
![image](https://user-images.githubusercontent.com/5461253/29915505-a2318660-8e6e-11e7-8386-c9313aa28147.png)

## Actual Behavior
the shadow isn't showing up and the textbox move to the upper side of circle because of scaleing(scaleX and scaleY of  textbox is 2.82)
![qq 20170831170621](https://user-images.githubusercontent.com/5461253/29915565-c63486b6-8e6e-11e7-9da1-9d59518d9873.png)

**Comment by rokenchou** [comment]
node canvas downgrade to v1.6.4, font position is right, shadow still isn't rendering out

**Comment by asturur** [comment]
what happens on 1.6.5?
in 1.6.6  they introduced a change about baseline

**Comment by rokenchou** [comment]
@asturur on node canvas 1.6.5 the font-style "italic" is ignored. BTW, can you find out the cause of the  shadow problem? or shed some light on me to work round this

**Comment by asturur** [comment]
is the baseline correct on 1.6.5?

**Comment by rokenchou** [comment]
baseline seems ok

**Comment by asturur** [comment]
i m trying to setup a node test suite so i can check all differences that i bet are many. i ll need some time.

**Comment by rokenchou** [comment]
@asturur I figure it out, in _renderStroke function of fabric.js, when affectStroke  is set to false, the circle which is stroke only will have no shadow, I think this behavior in node side is right,  while in the browser side, the code snippet below is not running into (don't know why), so the shadow renders out.
```
if (this.shadow && !this.shadow.affectStroke) {
    this._removeShadow(ctx);
}
```

**Comment by asturur** [comment]
that is a difference betweeb caching of and on. Node has caching off by default. so you are right.

text baselibe is something to watch on.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/54077594-f26b9d80-42ba-11e9-9ce5-b45d900f25f7.png)

this is what we get with node canvas 2.
i m closing the issue since with migration looks solved.
