### ISSUE TITLE
square is seen in left top corner after loadSVGFromURL

### ISSUE THREAD

**Issue by darxx** [fabricjs/fabric.js#4326]
## Version
1.6.7

## Test Case
https://jsfiddle.net/darxx/7qqvcvtd/2/

**Comment by asturur** [comment]
The bug is same with last version, but is also true that that SVG is full of clipPath.
Unless you can show that top left corner square is not for a unsupported clipPath i would say this issue is duplicate of #1454

**Comment by darxx** [comment]
Don`t see possible solution for My case. Can You make example how to fix it?

**Comment by asturur** [comment]
clipPath support is not ready yet, and is not an easy fix

**Comment by darxx** [comment]
And no work around? We can`t ship our product looking like this. We need some kinda solution that`s works.

**Comment by asturur** [comment]
remove that square from the svg.
go back at the root of the problem.

why are you getting a clippath in the svg? what application is creatong the svg,

**Comment by darxx** [comment]
SVG is provided by magic draw. https://www.nomagic.com/products/magicdraw Nasa and other big company's are using it. 

In some svg we have a lot of squares :) So to remove one it`s not a solution. Can we get contacts of team lead of this project? Or have developer for video chat? Because we have lot of bugs coming on every version update that You make. We stuck on 1.6.7. That`s we ask for possible solution .

**Comment by asturur** [comment]
Full SvG support on canvas is not so easy.

And i believe rewriting custom shapes for 2.0 needs some work. not that much, but still needs it.

Currently i am the team and the team lead myself since i m pretty much alone.

**Comment by darxx** [comment]
Can we show You how we are using Fabricjs library and what problems do we have?

**Comment by darxx** [comment]
You are doing great job. And we hope until all issues is fixed in 2.0 we will use 1.6.7 and all possible work around. 

Loading this SVG not to canvas. Instead load to image tag and use canvas on top of that. Just to draw shapes.

If You can contact us and spend some times. darius.laurincikas@nomagic.com we will be Very happy.

**Comment by asturur** [comment]
I m fine at starting a conversation by email, just start to write me  if you manage to load the SVG in some way that looks good and also please explain what your application is aiming at doing.

Proper clippath support is the next big thing ( in my opinion ) but i have no idea how long it will take to write, and will be just for 2.0 that means no pathGroups support.

**Comment by asturur** [comment]
@darxx never got email about this. did you solve loading svg correctly?

**Comment by darxx** [comment]
I wrote You a email.
