### ISSUE TITLE
Line-specific charSpacing via styles for iText missing?

### ISSUE THREAD

**Issue by romanolicker** [fabricjs/fabric.js#4331]
Hello everyone,

we want to set **different char spacing per line (or character)** - this seems to be missing.

From the documentation and the fiddle http://fabricjs.com/kitchensink it seems that the property
"charSpacing" is only supported for the whole object.

Adding it to the styles hash doesnt do anything.
The docu says that these are the supported styles:
["stroke","strokeWidth","fill","fontFamily","fontSize","fontWeight","fontStyle","underline","overline","linethrough","textBackgroundColor"]
http://fabricjs.com/docs/fabric.Text.html#_styleProperties

Why is charSpacing missing? Could or will this be added?

In general: Is it possible to set a style for a whole line? It seems only character specific styles are supported. Why is that?

**Comment by asturur** [comment]
So is that for implementation semplicity.
Text is already a big mess.
I'm not going to support per char ( per line ) charspacing, but i have to support the dx attribute.
This will make possible to set chars of a specific line displaced between them

I agree that a method to set the line of a line could be useful. It will anyway set it per every char of that line.

**Comment by romanolicker** [comment]
The "per line" command would be for simplicity - but that would be just something convenient. 

The char spacing is actually a feature that we need. With fabric we can build, edit and arrange text almost like in "Word" - and that's beautiful.

Why would you argue against adding this? As this is possible in "Word" and any other high level text editor, it surprised us a bit.
With dx, you mean this: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dx ,right?
Would that behave similar? For when is this scheduled?

Thanks a lot for the quick response!
Romano

**Comment by asturur** [comment]
So i m currently stuck in 2.0 documentation and deciding changes to existing code.

As soon as this is done, i want to develop tspan and clippath parsing. That means that dx and dy are needed.

dy is already implemented and needs to be merged, dx will be implemented similarly.

Dx allow you to move a char on the right or on the left and will act OVER charspacing

If you need to position chars individually you will use dx.

It may look the same to you and just a nomenclature problem, the fact is that text-spacing is bad supported on svgs while dx is wildly used.

**Comment by ncou** [comment]
@asturur : do you think the futur "dx" feature could solve this strange behaviors ?
https://github.com/kangax/fabric.js/issues/4285

thanks.

**Comment by romanolicker** [comment]
@asturur Can you give us any estimation when this will be included / when it is scheduled?

**Comment by asturur** [comment]
not yet, last 10 days i worked very little on fabricjs. I m trying to solve last standing issue and i m not doing anything else do not get distracted from it or i will never do it.

**Comment by Prati1310** [comment]
@asturur Thank you so much for everything here. 
I wanted to know if the DX has been implemented? 
Is there a possible patch that I can look in to? 

Regards.
