### ISSUE TITLE
Blur for part of the image 

### ISSUE THREAD

**Issue by sumit3sep** [fabricjs/fabric.js#4342]
I have to blur part of the image on click event and wants to implement functionality in such a manner during mouse move the part of the image make a blur.
How should I proceed? Please help me out of this

## Version
2.0 beta

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by asturur** [comment]
There is nothing like that.
easy way woupd be blir the full image and the use the blurred one as patter fill for a pencil brush.

**Comment by sumit3sep** [comment]
Could you share jsfiddle for the same.

**Comment by asturur** [comment]
i do not have it. i should make it on pirpose and i have really no time

**Comment by sumit3sep** [comment]
:( I m stuck on this in my annotation tool and this tool is completely based on fabric js. Without this functionality, annotation tool will not be complete.
I would be great to you if you help me out to complete this tool.

**Comment by asturur** [comment]
so start creating a fiddle with 2 images identical, one blirred and one not

**Comment by sumit3sep** [comment]
Please check - http://jsfiddle.net/Da7SP/599/.  I have added 2 images one as a background in canvas other is in imag tag

**Comment by mzuberbhatuk** [comment]
Hello Sumit and Asturur,

If you have found any solution to this, please let me  know.

Thank You
Zuber
