### ISSUE TITLE
On iOS WKWebview, when drawing on top edge of canvas, drawings deleted.

### ISSUE THREAD

**Issue by DeepanshiGupta3** [fabricjs/fabric.js#4374]
## Version
2.0 beta

We are using free drawing on canvas embedded in WKWebview in iOS app. The canvas container is added to take full space of WKWebview and screen.

Issue: The canvas is displaced by around 10 pixels in its y position. Due to which when drawing on the top edge of canvas, the free drawings are delete (due to multi touch) and there is space of some 10 pixels on lower edge due to which we cannot draw towards the bottom edge of WKWebview.

Even the size of lowecanvas is double the screen size but the size of upper canvas is same as that of screen size. This issue appears only on WKWebview in iOS app. But works fine on browser (Safari or Chrome).

## Test Case
[testing.zip](https://github.com/kangax/fabric.js/files/1357478/testing.zip)

## Steps to reproduce
Please find attached the source code of app under test case section. 
1. Install and run the app on iPhone device.
2. App works in landscape left mode.
3. Try to free draw towards the top edge of screen, touching the top edge. Drawings would be deleted.
4. Try to draw towards the bottom edge of screen. Canvas is displaced by 10 pixels upwards due to which we cannot draw towards the bottom edge of screen. Even though canvas container covers full screen.

## Expected Behavior
We should be able to draw towards the upper edge of screen in free drawing mode without drawings get deleted. And we should be able to draw towards the bottom edge of screen touching the bottom edge without gap of some pixels towards the bottom edge.

## Actual Behavior
While drawing towards the top edge of screen in free drawing mode, drawings are deleted and when drawing towards the bottom edge of screen we cannot draw full towards bottom, touching the edge of screen. There is some space due to canvas displacement.

**Comment by asturur** [comment]
I have no ability to test on iphones.

**Comment by DeepanshiGupta3** [comment]
You can test it on Android phone or iPhone simulator as well.
This issue is occurring on only mobile web views, iPhone and Android and not in browsers.
