### ISSUE TITLE
Deserializing Custom Groups Issue

### ISSUE THREAD

**Issue by SmboBeast** [fabricjs/fabric.js#4376]
Hi guys,

Been using Fabric for a while, and love it.  Thanks for all the time and effort that was put into it.  

I'm having trouble with deserializing custom groups, and after searching the entire web, I can't really find any documentation or examples that really touch on this topic in regards to custom groups.

Below is my code.  I'm basically trying to create a group that includes a line and a triangle, to make an arrow.  The fromObject piece is what's causing me problems I believe.  I just can't get it to deserialize and receive the error: 

TypeError: "Cannot read property 'fromObject' of undefined".  My code is below.  What am I missing?

```javascript
fabric.Arrow = fabric.util.createClass(fabric.Group, {
    type: 'arrow',

    initialize: function (objects, options) {
        options || (options = {});
        console.log('Arrow', objects);

        this.callSuper('initialize', objects, options);
    },

    toObject: function () {
        return fabric.util.object.extend(this.callSuper('toObject'), {
            type: this.get('type'),
        });
    },

    _render: function (ctx) {
        this.callSuper('_render', ctx);
    },
});

fabric.Arrow.fromObject = function (object, callback) {
    var _enlivenedObjects;
    fabric.util.enlivenObjects(object.objects, function (enlivenedObjects) {
        delete object.objects;
        _enlivenedObjects = enlivenedObjects;
    });
    
    return new fabric.Arrow(_enlivenedObjects);
};
```

**Comment by willKo** [comment]
Hi SmboBeast, 
in case only the whole arrow should be selectable, not the parts of the arrow, I think it might be easier to extend fabric.Object or fabric.Rect instead of fabric.Group. 

When extending Object or Rect you can override the _render Method (and draw your Arrow): 
e.g.  https://stackoverflow.com/questions/26565436/fabricjs-render-method-of-my-fabric-object-subclass-is-never-called

**Comment by SmboBeast** [comment]
Hi @willKo 

Thanks for the reply.  Actually, I do need it to be selectable as an entire unit.  I've seen plenty of examples for manually drawing my own by overriding the render method, but in my use case, I don't think this will work.

I think I have no other option than extending fabric.Group.  Please let me know if I'm incorrect.  Any help is appreciated.

Thank you again.

**Comment by willKo** [comment]
Hi, 
ok. I don't know your usecase, but if your arrow behaves like e.g. a Rectangle Circle or a Triangle 
(E.g. is selectable as only one entire Element as well as scalable and movable as one Element), I see no need to make a group of fabric.Elements but that is just my opinion and i do not know the entire usecase.
Regards .

**Comment by asturur** [comment]
On what version of fabric are you working on? 1.7 or 2.0?

**Comment by SmboBeast** [comment]
@asturur 

I am on 1.7 for now.  Will need to upgrade at some point, but for the next few weeks (or months), I will need to be on 1.7.

Would you think moving things over like @willKo is mentioning is best?  I actually am drawing my arrows with the mousedown, mousemove, and mouseup events.

Thanks.  I will follow whatever advice is given at this point.

**Comment by asturur** [comment]
i have no idea what is the moving thing, the issue is about not being able to deserialize and i m trying to figure out what is wrong

**Comment by SmboBeast** [comment]
@asturur 

Thanks.  To clarify, @willKo was telling me that instead of trying to extend a Group object, I should just extend an Object because it would be easier with the framework.

Basically, currently, I create a line and a triangle and try and create a custom Group object with them.  I believe @willKo was just telling me to not do this, and instead use the render method to draw out the arrow as a workaround for this problem.

**Comment by asturur** [comment]
but would be still nice to figure out what you do that is not working now.

**Comment by SmboBeast** [comment]
Yes! Absolutely.  

In my honest opinion, I would much rather be able to deserialize things this way.  

Would it help to give you the serlialized string that I'm trying to deserialize?

**Comment by asturur** [comment]
https://jsfiddle.net/gh316vm2/

Can you paste a serialized canvas with a couple of arrows in a string inside the fiddle so we can actually try it?

**Comment by Beardless** [comment]
Have same problem here with fromObject and loadFromJSON :/

**Comment by sherburne** [comment]
I just ran into this issue as well. I have a subclass of fabric.Text, and when loading serialized subclassed objects into the canvas I'm getting the same error: "Cannot read property 'fromObject' of undefined". It is thrown from fabric.util.enlivenObjects (called from canvas.loadFromJSON). It appears that my subclass (created with fabric.util.createClass) isn't known to fabric.util.getKlass, leading to the exception. I'd assumed that createClass would register my custom types. Any suggestions are appreciated.

**Comment by asturur** [comment]
@SmboBeast never got the serialized string.
Did you solve at the end?

**Comment by asturur** [comment]
@sherburne createClass does not register anything.
We really need a `create your subclass` page on the website.

**Comment by SmboBeast** [comment]
Guys,

For some reason I wasn't being notified of these replies.  That explains the MIA.  Somehow I wasn't subscribed to the thread no longer.  Apologies there.

@asturur - here you go: https://jsfiddle.net/gh316vm2/2/

Thank you!

**Comment by asturur** [comment]
https://jsfiddle.net/gh316vm2/5/

i think is deserializing correctly. What is the exact problem? in the fiddle works

**Comment by fahadnabbasi** [comment]
@asturur actually it is deserializing but not adding the group on canvas, there are three elements in the JSON
1) Image
2) Line
3) Arrow (which is the custom group but it is not being added on canvas)

**Comment by fahadnabbasi** [comment]
@SmboBeast the problem was in this line

`callback(new fabric.Arrow(_enlivenedObjects), object);`

you need to write it as following

`callback(new fabric.Arrow(_enlivenedObjects, object));`

**Comment by TeslaFreak** [comment]
Could someone take a look at mine as well? https://jsfiddle.net/0vxg23u8/1/ Im having the same error, but its not even making it into my fromObject function. I have no idea whats wrong

**Comment by asturur** [comment]
@TeslaFreak change the type from `visualcounter` to `visualCounter` and do it also in the saved JSON string.

This is for certain something that should be clearly stated somewhere more clear than is now.

**Comment by TeslaFreak** [comment]
@asturur oh man thank you! I had found a thread that had mentioned the second capital letter and I had added it to the object declaration, but forgot about it in the json strong. changing both fixed my problem.

**Comment by TeslaFreak** [comment]
One more problem I noticed with loading groups, I get an error "o.setCoords is not a function" from calcBounds. this fiddle replicates the problem https://jsfiddle.net/o8yacfwz/

**Comment by asturur** [comment]
our doc page on this is a bit better now.
It specify how to create the type and the fromObject function.
