### ISSUE TITLE
Add shrinkToObject parameter to getBoundingRect

### ISSUE THREAD

**Issue by malerba118** [fabricjs/fabric.js#4384]
If a circle is rotated at a 45 degree angle, the bounding rect returned from getBoundingRect does not touch the circle at any point.

![boundingrect](https://user-images.githubusercontent.com/5760059/31579437-10a4ae56-b0fc-11e7-8948-3fed4ce4de1a.gif)

I have a use case where I would like to do some object snapping, but when objects are rotated they don't snap as i hope they would because the bounding rect doesn't shrink to fit the object. It would be nice to have an option like getBoundingRect(shrinkToObject), which if set to true would start with the bounding rect and shrink it until lies flush against the contained object.

**Comment by asturur** [comment]
I thought i answered this, i probably forgot.
Fabric has no concept outside the bounding box of the shape inside.

For circle is very easy to implement, for polygons too. for paths a little bit less.
For some things is harder and heavy calculation dependant.
