### ISSUE TITLE
Add support for rotating around origin point (via flag) [$40 awarded]

### ISSUE THREAD

**Issue by Kienz** [fabricjs/fabric.js#439]
The origin while rotating is not 'center'/'center'. Only originX is set to 'center'.
http://jsfiddle.net/r2ZE7/172/

Is it possible to change rotate origin also to 'center'/'center' if angle is set by obj.setAngle(45)?
##

**Comment by prateekj-nfer** [comment]
@chetbox Rotate works fine. I am able to rotate objects on the center point but for me x,y shifts a bit when angle increases.

**Comment by prasanna-gmail** [comment]
yes
The triangle is not rotating from center rather some shift in xy is noticed.

any solution please
