### ISSUE TITLE
Not Drawing Selection Border(Bounding Box)

### ISSUE THREAD

**Issue by durga598** [fabricjs/fabric.js#4400]
[jsFiddle](https://jsfiddle.net/durga598/ndqov7m1/)
If `perPixelFind = true` , That bounding box is not drawing.

>Problem is in `isTargetTransparent` function

**Comment by asturur** [comment]
I think it has been fixed with this commit:

https://github.com/kangax/fabric.js/commit/0bb8a131a6e386a1a73ce4b7f579b8cfb14f83f1
