### ISSUE TITLE
Text absent in Exported SVG in IE11

### ISSUE THREAD

**Issue by phoenixrip** [fabricjs/fabric.js#4431]
fabric.js >= **1.7.17**
IN IE11+

## Test Case
[https://codepen.io/robbiewhite/pen/gXpRzj](https://codepen.io/robbiewhite/pen/gXpRzj)
or
http://fabricjs.com/test/svg_export/text.html

## Steps to reproduce
[https://codepen.io/robbiewhite/pen/gXpRzj](https://codepen.io/robbiewhite/pen/gXpRzj)
or
use `http://fabricjs.com/test/svg_export/text.html` in IE11:

<img width="851" alt="screen shot 2017-10-31 at 11 47 45" src="https://user-images.githubusercontent.com/17065959/32223156-2d56b09a-be34-11e7-86a5-22dcee83e12e.png">

## Expected Behavior
Text is visible in SVG image exported and viewed in IE 11

## Actual Behavior
No text at all is visible when exporting canvas to an SVG and then viewing that SVG in IE11

I can't find anybody mentioning this as an issue so I thought it must be something I was doing, but I can see that the text export doesn't work even on the fabric site itself, so I was just wondering if someone could tell me if this is a known unfixable limitation or if it's something that I can fix somehow :)

Thanks in advance for any help at all!

## Further Investigation
The problem is only present from 1.7.17 onwards;

The only difference in the text tag in the exported SVG between the v1.7.16 & v1.7.17 appears to be the inclusion of `xml:space='preserve'` and `white-space: pre;` at the end of it's style tag.

Turns out that it is the `white-space: pre;` which is causing the problem.

**Comment by asturur** [comment]
this is a problem, since one of those is required by safari.
I ll investigate deeper.

**Comment by asturur** [comment]
it seems to happen on 1.7 only.

**Comment by mozgor** [comment]
I still have it in my custom build based on 2.0.0-rc.3 (custom build for gestures)

**Comment by phoenixrip** [comment]
Here's something curious I discovered in trying to find a way around this bug....

Originally I was dealing with it by just regexing out 'white-space: pre;' on IE11... then I noticed that
just doing the following regex replace on the exported SVG fixes the problem and make the text display perfectly in IE as well as other browsers with no need to remove the whitespace: pre

` .replace(/\n\t/g, '') `

I have no idea why removing the newline tabs fixes this issue. I also don't know why removing white-space pre was fixing the issue, but for some reason both of them do. Obviously the '\n\t' removal is preferable because then you have one SVG that just works in all browsers with no further modification.

I can't find any record of why whitespace within inline SVG code itself would stop text from displaying in IE, nor can I can I work out why that problem was ever fixed by removing part of a style tag within that inline SVG, but at least now I have an SVG export method that renders beautifully from IE11+ with no further effort required:


```
 const finalSvgExport = this.fabriccanvas.toSVG({
      suppressPreamble: true
    })

 .replace(/\n\t/g, '')
```

Please let me know if this helps and fixes your issue, as this is something that could definitely be fixed at source if it is a common problem.

**Comment by ShaMan123** [comment]
IE11 support is discontinued
