### ISSUE TITLE
Text not shown when Unicode controls for bidi text at begin of text

### ISSUE THREAD

**Issue by palize** [fabricjs/fabric.js#4440]
![image](https://user-images.githubusercontent.com/2226899/32417170-a735f0f8-c26a-11e7-8989-c9b181cafc95.png)

i test with version 2.0,
in older version (1.7.6) was ok.

**Comment by asturur** [comment]
There is not other than LTR support in yet.
I'm not expert of RTL, i have no clue how it works.
If you have some knowledge to share on how it should behave i can try to fix it, otherwise not.

**Comment by ShahramCodeDeveloper** [comment]
please see this description link:[ https://www.w3.org/International/tutorials/svg-tiny-bidi/]( https://www.w3.org/International/tutorials/svg-tiny-bidi/)

**Comment by YaakovHatam** [comment]
Duplicate of #2374
