### ISSUE TITLE
Possible feature: insertCharsByRowIndex

### ISSUE THREAD

**Issue by redlive** [fabricjs/fabric.js#4451]
Based on the demand https://stackoverflow.com/questions/47230573/how-to-change-text-in-multiple-lines-places-of-a-textbox-in-fabricjs I would like to suggest to create such a function as a possible feature.

Basically, the function will get text and row index as are attributes,  will replace the text between start and end selection and then apply styles.

```
{
    rowId: 0,
    offset: 0,
    length: 6
},
{
    rowId: 1,
    offset: 0,
    length: 4
}
```

**Comment by asturur** [comment]
If you are referring to this
https://stackoverflow.com/questions/47230573/how-to-change-text-in-multiple-lines-places-of-a-textbox-in-fabricjs

I guess there is a missing functionality that has been made with only user input in mind.
There is a function that can detect changes in text and update style accordingly, but works just when working on hiddenTextarea.
Should be updated maybe.

**Comment by redlive** [comment]
The main point here is to be able to insert a text based on Row Id similar to **insertCharStyleObject** function which accepts rowId, char index and style.

Nowadays, the only way to change selected text is to use **insertChars** function, however, it's logic relies on selectionStart and selectionEnd and works perfectly with physically selected text using a mouse for example. That means client controls a selection. 

But what if selection should be controlled by data and the data only knows rowId and offset with text length?
Do you see my point?

**Comment by asturur** [comment]
I see your point.

Fabric as of now is missing completely any kind of method to handle text.
The only one is to replace .text with a new text and set back the style to what you want.

the method that exist now are more the older methods to manipulate user input other than specific method to modify text and you should rely too much on them.

Especially insertCharStyleObject is really for just following up user specific inputs.

Also a textbox will probably wrap once you swap some text with another, so row/column could make not work.

As of now is something to build more than fix.

**Comment by redlive** [comment]
In the stack link above we kind of solved the problem and it looks working except one thing...
Anytime, I remove a text (I call it variable text; those colored lines), fabric removes the style (makes sense) which holds the reference to that variable.
So, the question is there any way to preserve the styles of removed chars? I know it sounds weird, but let's say it won't delete it at all but will store the location of that removed char...

Instead of
```
0: {
    field : "FIELD_1"
    textBackgroundColor: "#F00"
}
```

Do not remove a 1, but just remove the style
```
0: {
    field : "FIELD_1"
    textBackgroundColor: "#F00"
},
1: {
    field : "FIELD_1"
}
```

**Comment by asturur** [comment]
you should probably use getSelectionStyle and save a copy of the style by yourself.
We need to add more method to work on text, i'm just not sure of which they are.
