### ISSUE TITLE
toDataUrl discrepancies between 1.6.4 and 1.6.5+ when using clipTo

### ISSUE THREAD

**Issue by snout-o** [fabricjs/fabric.js#4457]
## Version
1.6.4 +

## Test Case

1. Using Fabric 1.6.4 - http://labs.leesibbald.com/fabric.js/toDataUrl/112017/index.html
2. Same code using Fabric 1.6.5 - http://labs.leesibbald.com/fabric.js/toDataUrl/112017/index2.html

(p.s. apologies for not using jsFiddle - due to loading an external image I encountered a number of CORS issues that I could not resolve.)

## Steps to reproduce
At each of the URLs above, allow the main image to load in to the canvas, observe how the SVG square shape is used with clipTo to create a clipped canvas, then click the "save crop" link. This link will output a new image in a new window/tab using toDataUrl and x,y,w,h values.

## Expected Behavior
Both should produce an image that is exactly the same as the cropped window area

## Actual Behavior
Correct crop image only appears to work for 1.6.4 (and below, perhaps). Any version above this returns unexpected results: in this example, just a black square, but I have seen half black and half image being returned in other tests.

**Comment by asturur** [comment]
i need to check what we changed between 1.6.4 and 1.6.5 before figuring out how to solve it.

**Comment by asturur** [comment]
like one year passed and i will not have time to do this for sure.
clipTo is unsupported and so is 1.x, i need to close this issue.
