### ISSUE TITLE
Add z-index methods to objects in groups

### ISSUE THREAD

**Issue by tomw42** [fabricjs/fabric.js#447]
Currently z-index methods, like bringToFront() or bringForward() do not work on groups, although the documentation states that these methods are borrowed from fabric.object.
For reference see the following example: http://jsfiddle.net/6n8LD/11/

**Comment by princ09** [comment]
Any Solution to this issue? I have Svg image and I am trying to add IText on it , together i am creating Group , but i am not able to select IText, On click only SVG image get selected. I want to move IText above SVG so that i can edit it.

**Comment by asturur** [comment]
@princ09 groups have zIndex methods too.

**Comment by princ09** [comment]
> @princ09 groups have zIndex methods too.

I didn't find any, bdw i am asking for zindex of items of group, not zindex of group with respect to canvas objects.

**Comment by asturur** [comment]
the zindex is the position in the _objects array in the group and it can be managed using moveToFront, moveToBack, forward and backward.

**Comment by princ09** [comment]
> the zindex is the position in the _objects array in the group and it can be managed using moveToFront, moveToBack, forward and backward.

http://jsfiddle.net/6n8LD/11/
can you please make it work in this fiddle , How can i make IText editable here?

**Comment by asturur** [comment]
Text in a group is not editable, but nothing has to do with zIndex.
You need to ungroup the text, edit it, and group back
