### ISSUE TITLE
Fuzzy text cursor on retina screen

### ISSUE THREAD

**Issue by AvaelKross** [fabricjs/fabric.js#4479]
## Version
2.0, but i guess it's valid for all versions

## Test Case
http://fabricjs.com/loadfonts

## Steps to reproduce
try text editing on retina screen with downsampling to lower resolution (osx sierra, safari 10.1.2). I guess most of macbook users have downsampling enabled.

## Expected Behavior
text cursor should be crisp

## Actual Behavior
on retina screen, cursor is just fuzzy. I think it's not really important, but if it's easy to fix - it would be nice. All other control elements seem to be adjusted for retina resolution, but not the cursor in a textbox.

**Comment by asturur** [comment]
The upper canvas is not yet retina enabled and also the cursor is not pixel positioned. This is a known issue, will be improved after 2.0 release
