### ISSUE TITLE
Object.toDataURL include intersecting objects

### ISSUE THREAD

**Issue by Tsourdox** [fabricjs/fabric.js#4484]
Hey! I'm trying to snapshot parts of my canvas covered by a group.
The object.toDataURL works like a charm for everything within that group but some things are rendered directly onto the canvas.

Would it be possible to add an option to the toDataURL function like so:

```
myObject.toDataURL({
   format: 'jpeg',
   quality: 0.9,
   inlcudeInteresectingObjects: true,
}) 
```

Or is there another simple way to do this? Thx 🙏

**Comment by asturur** [comment]
well not there is not.
cropping would be enough if it wasn't that the group can be rotated too and cropping would not fit.

What we can do is adding an option to canvas.toDataUrl in order to cut an arbitrary part of the canvas
Not today not tomorrow, as soon as 2.0 is released.
