### ISSUE TITLE
Chrome update makes fabric default to touch

### ISSUE THREAD

**Issue by nickyout** [fabricjs/fabric.js#450]
After a reload of Chrome today, items on the canvas suddenly became unselectable. 

The cause was (likely) that the latest Chrome update (it says 25.0.1364.97 m) causes isTouchSupported to become true - and thus fabric would pick touchstart and touchmove instead of mousedown and mousemove. After manually setting it to false, everything seemed to work again. 

I'm not sure if this is a bug, but it sure doesn't seem like desired behavior to me.

**Comment by Manoj-Roy** [comment]
How to support canvas in mobile devices by using this fabric.js library.

**Comment by asturur** [comment]
build fabricjs with gesture module, it should work with gestures. with chrome emulator i m not able to make multitouch events go

**Comment by Manoj-Roy** [comment]
please give a demo site for help. Because  it does not working.

**Comment by handersen** [comment]
Have you tried http://fabricjs.com/touch-events/ ?

**Comment by Manoj-Roy** [comment]
I have also trying this but it does not working in google chrome mobile device emulator you can check it.

**Comment by asturur** [comment]
as i wrote before, i m not able to make chrome emulator work with event.js.

refer to chrome help center.

**Comment by Manoj-Roy** [comment]
Without checking in chrome emulator should it run in mobile devices  ?

**Comment by asturur** [comment]
yes it does

**Comment by Manoj-Roy** [comment]
Thanks! mr. asturur
