### ISSUE TITLE
Should activeObjects always be a "ActiveSelection" even on single selection

### ISSUE THREAD

**Issue by JSteunou** [fabricjs/fabric.js#4505]
in v2 the active object can be a single object or a multiple selection wrapped into an `ActiveSelection`

I'm wondering if it would be better to always wrap the selection into an `ActiveSelection` even for a single object. It could save a lot of code logic, condition, check and reset to go from one to multiple wrapped into one.

As an example this is two version of an hypothetic `addActiveObjects`

With actual V2

```js
fabric.Canvas.prototype.addActiveObjects = function(objects) {
    objects = Array.isArray(objects) ? objects : [objects];
    const selection = this.getActiveObject();

    if (selection && selection === 'activeSelection') {
        objects.forEach(o => selection.addWithUpdate(o));
        return;
    }

    if (selection) objects.push(selection);

    // this should be abstract inside #setActiveObject
    if (objects.length) {
        const newSelection = new fabric.ActiveSelection(objects, {canvas: this});
        this.setActiveObject(newSelection);
    } else {
        this.setActiveObject(objects[0]);
    }
};
```

and considering active is always `ActiveSelection`

```js
fabric.Canvas.prototype.addActiveObjects = function(objects) {
    objects = Array.isArray(objects) ? objects : [objects];
    const selection = this.getActiveObject();

    if (selection) {
        objects.forEach(o => selection.addWithUpdate(o));
    } else {
        // this should be abstract inside #setActiveObject
        const newSelection = new fabric.ActiveSelection(objects, {canvas: this});
        this.setActiveObject(newSelection);
    }
};
```

**Comment by asturur** [comment]
You would then add an extra layer for the .get function to know the fill, stroke of your active selection.
Is a possibility but i think is another breaking change

**Comment by JSteunou** [comment]
Unfortunately yes it is breaking.

Maybe all possible feature could go under a *2.x* milestone when not breaking, and *3.0* when breaking?

**Comment by asturur** [comment]
i'll try to follow semver more strictly.
`2.x.y` where `y` are just fixes, and `x` are addition to the api.

That means that we will ramp up with version fast, like 2.1, 2.2

We never followed it good till now
