### ISSUE TITLE
GlobalComposite with Shadow render different Chrome vs Safari

### ISSUE THREAD

**Issue by blobinabottle** [fabricjs/fabric.js#4520]
## Version
2.0 (and all previous)

## Test Case
http://jsfiddle.net/Drw7W/1/

## Steps to reproduce
If I use a blend mode to an object and apply a shadow, there is difference between Chrome & Safari
Test first in Chrome then in Safari

## Expected Behavior
Chrome is the correct render.

## Actual Behaviour
Safari
![screen shot 2017-11-30 at 12 19 24](https://user-images.githubusercontent.com/8090162/33428342-ba9ce84c-d5c8-11e7-9b57-9a757f8c3a83.png)
Chrome
![screen shot 2017-11-30 at 12 19 17](https://user-images.githubusercontent.com/8090162/33428345-bc33f6be-d5c8-11e7-8f8d-2f316924d3ae.png)

**Comment by asturur** [comment]
How do you know chrome is correct?
firefox and safari render same

**Comment by asturur** [comment]
also chrome, without caching, and so painting the rect directly on main canvas behaves like the other browsers.
http://jsfiddle.net/Drw7W/2/

i think i have to replicate in plainjs and ask on the chromium bug tracker what is the expected effect

**Comment by blobinabottle** [comment]
Ah good catch. For me chrome was correct (with caching on) because it render the same as html css

**Comment by asturur** [comment]
ok this is an info.
