### ISSUE TITLE
Fabricjs 2.0 Text decoration

### ISSUE THREAD

**Issue by DangerD256** [fabricjs/fabric.js#4555]
2.0

## Test Case
https://jsfiddle.net/bLn363j1/1/

Can't set underline/overline/line-through...
Worked well in 1.x

**Comment by DangerD256** [comment]
line-through: true/false - doesn't work

**Comment by samael205** [comment]
Please read the FabricJS Docs

http://fabricjs.com/docs/fabric.IText.html

You must use canvas.getActiveObject().set("linethrough", true);

**Comment by darron1217** [comment]
Doc says its type is `String` but actually it accepts `boolean`
Doc should be fixed 

https://github.com/fabricjs/fabric.js/blob/efa490fff020b287561a31d8d388850b5762152c/src/shapes/text.class.js#L93-L114

**Comment by pidugusundeep** [comment]
`linethrough:True` works just fine for me

**Comment by asturur** [comment]
Just in case someone can still hit this issue, i updated the official doc with a note.

http://fabricjs.com/fabric-text
