### ISSUE TITLE
[Question] Is touch:gesture only fired on objects?

### ISSUE THREAD

**Issue by marsonmao** [fabricjs/fabric.js#4556]
## Version
1.7.20

I built it using `build_with_gestures`, however I do not receive `touch:gesture` event when I use 2-finger touch on my canvas. 

I read the code comment and found

> Method that defines actions when an Event.js gesture is detected on an object

does it mean that only objects receive `touch:gesture` event? If so, how do I implement a 2-finger zooming for the canvas?

**Comment by asturur** [comment]
I haven't been in touch gestures since long.
Never worked much on that part of the library, mainly because mobile/tabled performance were not so good.
I recently took a touch device in order to be able to improve it and i will see what i can do.
As of now probably the event is not fired on canvas.

**Comment by marsonmao** [comment]
Hi Andrea, thanks for the reply, hope you could get some good news in the future!
