### ISSUE TITLE
Drawing brush isn't being added to canvas when drawing outside of the browser's tab

### ISSUE THREAD

**Issue by akoznodii** [fabricjs/fabric.js#4562]
## Version
1.7.16+

## Environment 
Android 5.0.0; Chrome 62.0.3202.84

## Test Case
https://codepen.io/akoznodii/pen/OzVqqy
or
http://fabricjs.com/freedrawing

## Steps to reproduce
Open https://codepen.io/akoznodii/pen/OzVqqy 
or
http://fabricjs.com/freedrawing
on any device with touchscreen functionality.

Touch a canvas area to start drawing, draw a brush outside of the browser's tab content (move touch cursor to browser's top bar area), end drawing a brush. Start drawing a next brush. Previous drawing brush disappears.

## Expected Behavior
Previous drawing brush should be added to canvas. 

## Actual Behavior
Previous brush is not being added to canvas.

**Comment by asturur** [comment]
this happens because we probably we do not get a mouseup event.
maybe something we can fix with proper touch events?
