### ISSUE TITLE
In fabric group, when edit in Itext, canvas is hide

### ISSUE THREAD

**Issue by ducvu91** [fabricjs/fabric.js#4565]
Hi, Thanks for library canvas, it awesome !!!
I have research your library but i stuck in this case. I get a example with fabric group object. it runs smooth with version 1.5. But when i use lastest version, i click in iText, all canvas hide, when out, it show again.
My Case : http://jsfiddle.net/Da7SP/776/
Another case in mobile, when i use browser on mobile, i double click to edit Itext, it auto zoom in to edit area, and then. I don't know how to zoom out or exit edit mode. it bug or i research not enought :(
I test on http://fabricjs.com/test/misc/itext.html

**Comment by asturur** [comment]
http://jsfiddle.net/Da7SP/777/

there are edge cases in which you have to manually declare an object as dirty, it looks like this is one of those.
looks what i did at line 35.

I'll try to figure out if this should be fixed and if it has a cost in performances.

**Comment by ducvu91** [comment]
thanks, it fixed
