### ISSUE TITLE
"fill: 'none'" not working as expected

### ISSUE THREAD

**Issue by vago** [fabricjs/fabric.js#457]
Fabric version: 1.0.12
Browser: Firefox 19 / IE 9

I understand, fill setting 'none' is to get a transparent fill. It was working ok in a previous Fabric version, '0.9.21'.

To get a quick glance, try following jsfiddle in both, Chrome as well as Firefox. It works OK in chrome, but not in Firefox.

http://jsfiddle.net/varungovil/SDyJF/1/

It can be seen in the Kitchen Sink demo as well. Pls follow following steps in Firefox:
1. Goto http://fabricjs.com/kitchensink/
2. Select 'Execute' tab
3. Remove code related to adding circle
4. Replace "fill" setting of rectangle with "none"
5. Add "stroke: 'black'"
6. Click Execute.
**Result**: A black filled rectangle shows up. Shouldn't this have been transparent with black borders?
7. In "Canvas background" box, enter a color, say 'blue' and click execute
**Result**: the entire canvas box including the rectangle turns blue (except rectangle's borders).. They way it should be.
8. Clear "Canvas background" box and click execute'
**Result**: the canvas become transparent/ white. However, the rectangle has a blue fill with black borders. Shouldn't this be transparent?

**Comment by alejobrainz** [comment]
Hello.  I saw this thread and wanted to ask a question.  When I set the fill to transparent, shadows seem to disappear from the stroke.  Is there a way to keep a stroked shape with shadows?

    var arc = new fabric.Circle({
        left: 50,
        top: 50,
        radius: 25,
        startAngle: 0,
        endAngle: 2*Math.PI,
        stroke: '#0000FF',
        strokeWidth: 10,
        fill:'transparent'
    });

    arc.setShadow({
        color: '#000000',
        blur: 10
    });

**Comment by asturur** [comment]
shadow.affectStroke property. set it to true.

**Comment by alejobrainz** [comment]
Thanks!

Enviado desde mi iPad
