### ISSUE TITLE
Zoom feature and toDataURL exporting (without zoom) / Feature request

### ISSUE THREAD

**Issue by DangerD256** [fabricjs/fabric.js#4602]
I need both zooming feature and exporting, currently when i make zooming it affects toDataURL exporting:
http://jsfiddle.net/neya4q0h/2/
Basically i can reset zoom and XY offsets when i make exporting and get them back after, but user will see image bouncing...

Any way to achieve this? Or can i request feature to update toDataURL so it will check getZoom values or make some toDataURLwithZoom

**Comment by asturur** [comment]
i think there is something already built in. please check the options accepted by toDataUrl

**Comment by DangerD256** [comment]
There're only added cropping functionality, not sure that it will help...

**Comment by asturur** [comment]
there is no functionality indeed.
For SVG we have a ignoreViewport and we should have for dataUrl too.
please cnsider that if you want to export for now, you can just change the viewportTransform before dataUrl, and put it back after, and the user will not see any jump.

use `canvas.viewportTransform = [1, 0, 0, 1, 0, 0]` without using .setViewportTransform

**Comment by ncou** [comment]
Why not use the multiplier*zoomValue option in the toDataURL ?

**Comment by asturur** [comment]
multiplier will affect also canvas size. ignoring viewport means exporting with zoom at 1 and no padding.

is not hard to do, i have just to fix other things before that i gave priority.

since SVG export has this function it may make sense to add it to png/jpeg export

**Comment by DangerD256** [comment]
Having issues with that, after deleting object i need to update page thumbnail.
```
canvas[current].remove(activeObject);
viewport = canvas[current].viewportTransform;
canvas[current].viewportTransform = [1, 0, 0, 1, 0, 0];
url = canvas[index].toDataURL({format: 'jpeg',quality: 0.3, multiplier:0.2});
canvas[current].viewportTransform = viewport;
```
It causes rendering with resetted viewport ([1, 0, 0, 1, 0, 0])...
Any way to disable automatic rerendering on object deleting? (i don't like that)
Or any other suggestion?

**Comment by DangerD256** [comment]
Still needed...

**Comment by asturur** [comment]
I know is needed, is marked as possible_feature it will get done.
To disable automatic renders on add remove, you can work with canvas.renderOnAddRemove = false;
that should be default in my opinion, but i did not want to shake devs so much.

**Comment by DangerD256** [comment]
After calling `.toDataURL({format: 'jpeg',quality: 0.3, multiplier: 0.2});` it still rerenders. If making some action like move stretch it's not bouncing as that actions has rerender event, only bounces when deleting object or if i just run this code:
```
	  viewport = canvas[id].viewportTransform;
	  canvas[id].viewportTransform = [1, 0, 0, 1, 0, 0];
	  url = canvas[id].toDataURL({format: 'jpeg',quality: 0.3, multiplier: 0.2});
         // bounce here
	  canvas[id].viewportTransform = viewport;
```
where i can comment out renderAll action from toDataUrl?

**Comment by DangerD256** [comment]
Solved by adding renderAll() again.

**Comment by asturur** [comment]
can you show a fiddle with the bouncing to look at?

**Comment by Ramyakutralam** [comment]
hi, i m facing a similar issue. we are building an image editor tool using fabric js. It has zoom feature and export as well. But after zoom the exported svg and todataurl is having zoomed image. We want the original image to be retained the same. how can we achieve. is there any property? i tried with setting viewport but  didnt turn out.

**Comment by asturur** [comment]
If you set the viewport and then export, it should work. isn't it?

**Comment by Ramyakutralam** [comment]
It works but the canvas is not resizing to its actual size. Canvas remains in zoomed size itself.  That shows weird behaviour in UI. I will post the screenshot soon.

**Comment by asturur** [comment]
i will close this issue.
Since we have `toCanvasElement` things are change and are simpler.

You can do

```js
var originalTransform = canvas.viewportTransfrom;
canvas.viewportTransfrom = fabric.IMatrix.slice(0);
canvas.toDataURL(...options);
canvas.viewportTransfrom = originalTransform;
```

**Comment by d-ilievski** [comment]
@asturur 
Your last reply have some errors, here's what worked for me

`
var originalTransform = canvas.viewportTransform;
canvas.viewportTransfrom = fabric.iMatrix.slice(0);
canvas.toDataURL(...options);
canvas.viewportTransfrom = originalTransform;
`

**Comment by asturur** [comment]
I cannot see any difference between our code snippet

**Comment by devsnowy** [comment]
> 
> 
> I cannot see any difference between our code snippet
iMatrix instead of IMatrix
