### ISSUE TITLE
Stylus not working in chrome

### ISSUE THREAD

**Issue by Exlord** [fabricjs/fabric.js#4610]
## Version
1.7.6 to 2.x

## Test Case
Try any demo on the site itself, freedrawing for instance http://fabricjs.com/freedrawing

## Steps to reproduce
You need a stylus like device for testing, I am using this https://www.amazon.co.uk/Genius-EasyPen-Stylus-Graphic-Interface/dp/B005DPPXPY

It works fine on firefox but not on chrome

Windows 10 
Chrome Version 63.0.3239.108

## Expected Behavior
To Work.

## Actual Behavior
Not working ... Nothing happening ...

I am currently debugging to see what and where is going wrong, will update if I found anything.

Updates
-
Testing on version 1.7.20
https://github.com/kangax/fabric.js/blob/v1.7.20/dist/fabric.js#L10838
```
    _onMouseMoveInDrawingMode: function(e) {
      if (this._isCurrentlyDrawing) {
        var pointer = this.getPointer(e);
        console.log(pointer);
        this.freeDrawingBrush.onMouseMove(pointer);
      }
      this.setCursor(this.freeDrawingCursor);
      this._handleEvent(e, 'move');
    },
```

`pointer` is `{x: NaN, y: NaN}`

https://github.com/kangax/fabric.js/blob/v1.7.20/dist/fabric.js#L2228
```
  function getPointer(event) {
    event || (event = fabric.window.event);

    var element = event.target ||
                  (typeof event.srcElement !== unknown ? event.srcElement : null),

        scroll = fabric.util.getScrollLeftTop(element);

    return {
      x: pointerX(event) + scroll.left,
      y: pointerY(event) + scroll.top
    };
  }
```
`pointerX(event)` and `pointerY(event)` are `undefined`

Finally here is the problem :
```
  if (fabric.isTouchSupported) {
    pointerX = function(event) {
      return _getPointer(event, 'pageX', 'clientX');
    };
    pointerY = function(event) {
      return _getPointer(event, 'pageY', 'clientY');
    };
  }
```
The stylus is firing touch events!!! but the `fabric.isTouchSupported` is false.

Why not just do this :
```
  var pointerX = function(event) {

    if(event.touches || event.changedTouches)
      return _getPointer(event, 'pageX', 'clientX');
    
        return (typeof event.clientX !== unknown ? event.clientX : 0);
      },

      pointerY = function(event) {
        if(event.touches || event.changedTouches)
          return _getPointer(event, 'pageY', 'clientY');

        return (typeof event.clientY !== unknown ? event.clientY : 0);
      };
```

now its working! but since this is a private function, I can't override it from outside and have to do it inside the fabric.js itself

**Comment by asturur** [comment]
the point was avoiding inspecting the event and decide everytime.
We want blocking event managment as fast as possible.

This issue fall in the generic pointer event discussion we have open and i can't work on it immediately.

**Comment by Exlord** [comment]
Can you at least make this function to be available publicly so I can override them from outside, until you have a fix for this, right now I have modified the fabricjs itself, but that makes it unupdateable which is a problem , since there is bug in the 1.7.20 version and I should fix it manually! or update and they apply the fixes for this part manually!

**Comment by minzojian** [comment]
why not just re-define fabric.util.getPointer after loaded fabric.js
fabric.util.getPointer = YOUR_OWN_getPointer;

**Comment by asturur** [comment]
that is an opportunity for the shor term.
But we would like to get pointer event support.

I would like to make a fool proof pen drawing example with fabricjs

**Comment by asturur** [comment]
i think this has been resolved with pointer events support
