### ISSUE TITLE
"makeXHR is not a function" in node

### ISSUE THREAD

**Issue by peerbolte** [fabricjs/fabric.js#4634]
## Version
2.0.0-rc.4
node v8.4.0

## Test Case
```javascript
const fabric = require('fabric').fabric;
const Canvas = require('canvas');

const canvas = new fabric.Canvas(null, { width: 500, height: 500});
fabric.loadSVGFromURL('https://s.cdpn.io/3/kiwi.svg');
```

## Steps to reproduce
run the snippet in nodejs.

## Expected Behavior
the svg should be loaded

## Actual Behavior
the following error is thrown:
```
node_modules/fabric/dist/fabric.js:2622
        xhr = makeXHR(),
              ^

TypeError: makeXHR is not a function
```

**Comment by 0ro** [comment]
I have same problem. Obviously this problem is connected with the fact that XMLHttpRequest isn't supporting in node.js. How to use this API?

**Comment by asturur** [comment]
i think this has been fixed?
