### ISSUE TITLE
InsertChars before adding to canvas throw error

### ISSUE THREAD

**Issue by redlive** [fabricjs/fabric.js#4635]
## Version
1.7.22

## Test Case
https://jsfiddle.net/redlive/doLtq27s/

## Steps to reproduce
Open console log in chrome, run code and see an error
## Expected Behavior
No js error
## Actual Behavior
JS error.
Text doesn't insert.

**Comment by redlive** [comment]
Not a bug. The object needs to be added before manipulation with chars.

**Comment by asturur** [comment]
looks like that is the problem, but it should not be like that. i will try to verify why is like this.

**Comment by redlive** [comment]
Sounds good. Tnx

**Comment by durga598** [comment]
If you set text as active object then it works. Here is [fiddle](https://jsfiddle.net/doLtq27s/4/)

**Comment by asturur** [comment]
probably fixed with #5614, cannot really test it, the pr looks good.
If is confirm fixed i ll release this as 1.7.23
