### ISSUE TITLE
Suggestion on Cropping attributes

### ISSUE THREAD

**Issue by semiadam** [fabricjs/fabric.js#4709]
I think introducing cropping capability in V2 is great and will open up a lot of opportunities. I have personally dealt with cropping before and have some suggestions that the community may find helpful.

Here's the background:
In many web2print applications, the image used for interaction on the canvas, is a scaled down mockup of actual high-res image. This is done to help with performance and load time. When the system want to generates the final high res output, it will update the JSON and replace the URL of mockup images with highres images, and generates the output.

Now, if the crop information is calculated in pixel, the systems needs to update all that, according to the ratio of mockup and original, which is a lot of work prone to different sort of bugs, including misdetection of image dimensions for certain image format/version.

A different approach to cropping would eliminate this problem all together, and simplifies things in several other ways. In this method, instead of using pixel for crop attributes, we use percentages.

Say your original image is 1000x2000, and you want the area from (250,200) to (1000,800).
Crop attributes will be as follow:
{
cropLeft: 0.25    // 25% from left = 250px
cropTop: 0.5     // 50% from top = 1000px
cropWidth: 0.75   //  75% of total width = 750px (=1000 - 250)
cropHeight: 0.3     // 30% of total height = 600px (= 800 - 200)
}

From here, you can assume you have a new image resource, so you can place and scale it on the canvas exactly as a regular image.

With this, you can easily swap the original image with a mockup or thumbnail without having to change anything else. Also, validating attributes and creating crop interface will be much easier because you always deal with values between 0 and 1 and your tool will be agnostic to loaded image.

Thoughts?

**Comment by jilster** [comment]
I don't know how hard it is to implement it, but i myself like the crop based on percentage. But not instead of pixels, but as a second flavour.

**Comment by asturur** [comment]
```
Now, if the crop information is calculated in pixel, the systems needs to update all that, according to the ratio of mockup and original, which is a lot of work prone to different sort of bugs, including misdetection of image dimensions for certain image format/version.
```

So since the drawImage works in pixels, this means that i need to make the logic in the library itself.
Other than that, the problem is mirrored on the other side.

How do you crop away 3 pixel of a picture? what is the percentage that is gonna give you exactly 3 pixel over..   47?

**Comment by semiadam** [comment]
I agree both percentage and pixel crops would be helpful depending on the scenario. 

Regarding @asturur point, if the percentage logic is implemented inside the library, it would be once and for all, and more optimized than 3rd party implementations.

Btw, are you considering introducing a built-it crop tool at some time?

**Comment by asturur** [comment]
No, less tool the better.
My (personal) opinion is that built tools take lot of effort and code to customize.
At the end people to make their own product has to rewrite half of the logic, workaround existent one, and is no worth.
FabricJS should aim to make you in condition to do canvas things with a class based approach and a serializing ability. If it starts to offer built-in tools it becomes a crappy editor with no interface.
