### ISSUE TITLE
Transparency issue on IE with BlendColor filter

### ISSUE THREAD

**Issue by neirda** [fabricjs/fabric.js#4715]
## Version
2.0

## Test Case
https://jsfiddle.net/w2kdcs21/7/

## Steps to reproduce
Open the jsfiddle in IE or Edge
It uses the filter BlendColor to make the image blue.

## Expected Behavior
The transparent area of the PNG should remain transparent.

## Actual Behavior
The transparent area of the PNG is not fully transparent anymore and a part of the red square is now pink.

PS: It's my first report and I wanted to thank you for this great tool !

**Comment by asturur** [comment]
I have to check it. I have not my windows VM right now.

**Comment by ncou** [comment]
why don't you use a multiplay or overlay mode ?

**Comment by neirda** [comment]
I don't know what you mean by "multiplay"
There is the same issue with the overlay mode, it's just more or less visible according the color.

**Comment by ncou** [comment]
i wanted to say "multiply" and not "multiplay", it's another blend mode, but here is what i get with the mode "tint" for the color = green applyed on the logo img :

![image](https://user-images.githubusercontent.com/16743322/36227796-848d311c-11d2-11e8-96b9-f098d48b81cf.png)

it looks like the green is added on the alpha channel, so we get yellow color if the alpha part are over the red rect behind. The alpha value seems ignored when the two objects intersect.

**Comment by asturur** [comment]
I think there is a parameter to choose between opacity or not.
Please give a look at filter properties or docs, and let me know if is not
stated anywhere

2018-02-14 22:06 GMT+01:00 ncou <notifications@github.com>:

**Comment by asturur** [comment]
The opacity of source image should be taken in consideration. Probably a bug

2018-02-15 0:39 GMT+01:00 Andrea Bogazzi <andreabogazzi79@gmail.com>:
