### ISSUE TITLE
2.0.1 bringtofront, sendtoback has no effect

### ISSUE THREAD

**Issue by boomsya** [fabricjs/fabric.js#4716]
try to learn Fabrik.js
in demo http://fabricjs.com/kitchensink

1. add image like "google" and text
2. move text over image
3. select image object
3. click tab "Object" to manual control of selected object
4. clicking buttons "send to back", "bring to front" has no visible effects :( - image still over text

**Comment by boomsya** [comment]
hmm. this behaviour just when checkbox "Preserve stacking" is unchecked

but when checked it is all OK

**Comment by asturur** [comment]
So preserveStacking set to false is an odd default that i found in fabric and never changed.
Is odd.

send to back will work as long as you deselect the object and the normal stack is take care of.
I agree that with send back/front, preserveStacking = false is a big mess.

**Comment by Aubron** [comment]
Agreement on the preserveStacking false default, always seemed like an editor feature that didn't really belong on by default, if at all.

**Comment by sashapavlov** [comment]
Any update on this?

I guess methods like bringToFront should print a warning at least when preserveStacking is set to false as they have no effect at all.

**Comment by asturur** [comment]
It would be nice to have a dev only set of warnings for those things.
We could wrap them in some special markers and remove them when a build is done in the prod environment.

If you want to start a PR, look for how we mark the SVG_EXPORT code and how we remove it in build.js, we can do the same for those warnings.

**Comment by ShaMan123** [comment]
These methods sure do have effect.
If you are calling these methods on a selected object with `preserveObjectStacking` set to `false` you will not see a visual change until after you deselect, as @asturur mentioned.
I see no reason for this issue to remain open.
