### ISSUE TITLE
Background Image low res when applying through a pattern

### ISSUE THREAD

**Issue by redlive** [fabricjs/fabric.js#4721]
## Version
2.0

## Test Case
http://jsfiddle.net/redlive/cLd08o80/

## Steps to reproduce
Click on [+] button to zoom and compare top with the bottom... The top is an Image Tag, a bottom is a Pattern.
## Expected Behavior
An image should be way better
## Actual Behavior
Image is blurred

**Comment by redlive** [comment]
![screen shot 2018-02-14 at 8 41 06 am](https://user-images.githubusercontent.com/5912122/36216174-e24f26b8-1162-11e8-8867-7a7d438f5eae.png)

**Comment by redlive** [comment]
![screen shot 2018-02-14 at 3 18 44 pm](https://user-images.githubusercontent.com/5912122/36233344-68514a0c-119a-11e8-94ff-0f97e71d4a10.png)

**Comment by asturur** [comment]
@redlive sorry for not answering here.
What is the point of using a canvas as pattern if you already hav an image element you can use as a pattern? The blurriness come from that.

**Comment by redlive** [comment]
@asturur Basically, what I need is to create a "container" with an image (as a pattern or any other way) where the image could be rotated, scaled and moved inside of its container. If the image is bigger than a container, I need to hide whatever is beyond of container borders.

**Comment by asturur** [comment]
@redlive i imagine you moved on from this problem, i m sorry i do not have time to help with implementation ideas, i have not time enough for real bugs.
