### ISSUE TITLE
Scale image source of Texture Pattern Brush

### ISSUE THREAD

**Issue by kephin** [fabricjs/fabric.js#4736]
## Version
2.0.1

## Test Case
http://jsfiddle.net/kephin/23hLLrkj/21/

## Expected Behavior
I'm trying to use texture pattern brush to mimic the eraser function, so I need to scale the source image of the texturePatternBrush to fit with the original canvas

## Actual Behavior
Cannot scale the image when using texturePatternBrush.

**Comment by cabaret** [comment]
@kephin Did you ever solve this?
