### ISSUE TITLE
Feature request: make text selection more understandable

### ISSUE THREAD

**Issue by blobinabottle** [fabricjs/fabric.js#4744]
## Version
ALL

## Test Case
https://cl.ly/2o0L1X2u123z
When you select a text range and enter new text, it doesn't use the same style as selected text.
It's confusing for all our users, I suggest we take the first selected character style as reference.
As in majority of text editor. 
Here an example in TextEdit on os X:
https://cl.ly/1o1Q2W0P1L1x

I don't see what's the benefits of the actual solution? 

Thanks for your feedback :-)
(I know I'm submitting a lot of text related issues these days and I know you're not a big fan of this fabric area :-D Sorry for that)

**Comment by asturur** [comment]
So it could make sense, it effectively does.
The problem is that fabric does not have the concept of `current style` at all.
When inserting text, it wipes the old text, and then insert the new.

We can build this, reasonable, feature if between deletion and inserting the new text there is a clear straight codepath where we can do this.

This would be handled on the onInputMethod, maybe with a method calling `getSelectionStyles()` that should already exist and picking up the first result.
At this point everyone can easy imitate that when doing insertChars on a selection, but there won't be automatic, since is on the dev hands.

**Comment by blobinabottle** [comment]
I see how to get the right style, but I don't see how to override the method where we catch when a user is typing...

**Comment by asturur** [comment]
i do not think is overridable easily. you have to copy the method and insert your functionality in the middle. but i think is a good candidate for a feature. Not this week from me. If you manage to do it, feel free to open a PR.

**Comment by blobinabottle** [comment]
Working on something, but can't get it correct with undo/redo... Do you think we shoud keep an array of all corresponding styles of all the changes made during "editing mode"?

**Comment by asturur** [comment]
... no.
90% of the time undo/redo problem are mutability problem.
So when firing your undo/redo function ensure the style is a new object and not a reference of what is currently live.

**Comment by blobinabottle** [comment]
But my problem is how to undo/redo keeping the styles correct. Right now it will just paste the "undo-ed" text using the style of where the cursor is, so probably not the same style as the text was initially. 
Like here: https://cl.ly/3b1k2W0l0f1Z
Did you already try to solve it? I feel it's too big for my skills :D

**Comment by asturur** [comment]
ohh..
no undo redo works good when you wipe everything and restore a copy of your canvas state.
Really can't pretend to handle it manually, is prone to error.

then undo redo inside the textbox, the one generated by the textarea, create a big mess.

**Comment by blobinabottle** [comment]
I ended up something like that 
https://jsfiddle.net/blobinabottle/yab4fk2z/75/
Check only the input method (the rest is just other temp fixes). So now when you select a text it will keep this style as reference for new text. 

But in my opinion it's not good for Fabric Master branch, because as soon as you undo you clearly mess everything with different styles.  I'm not sure how different from the standard fabric function...
