### ISSUE TITLE
TextParagraph - possible feature

### ISSUE THREAD

**Issue by redlive** [fabricjs/fabric.js#4800]
Hi, 
I would like to suggest a new text element or extend the behavior of existing Textbox element.
Based on my company's needs, I had to override Textbox and add an ability to preserve a height of an element and hide text outside of it frame boundaries.

Temporary name is **_Paragraph_**
You can play with it here: http://jsfiddle.net/redlive/4vbbx0ut/

Thank you.

**Comment by perky** [comment]
This is great, was just looking for this functionality.
