### ISSUE TITLE
Does fabric.js support canvas inside iframe?

### ISSUE THREAD

**Issue by JimmyNi** [fabricjs/fabric.js#4805]
I got an iframe inside a html and a canvas inside the iframe. When I add fabric.Text to the canvas from html, the text did appear on the canvas but cannot drag around or do any interaction. Please help here:)
```
var iframeDocument = document.getElementById('myIframe').contentWindow.document;
var canvas = iframeDocument.getElementById('myCanvas');
var fabricCanvas = new fabric.Canvas(canvas);

var text = new fabric.Text('Hello from parent', {
   left: 100,
   top: 100
});

fabricCanvas.add(text);
```

**Comment by asturur** [comment]
please provide a fiddle

**Comment by satendra02** [comment]
@asturur I am getting the same problem. Here is the fiddle

http://jsfiddle.net/satendra02nov/v9oar6q3/12/ 

I am using fabricjs in chrome extension, which is loaded inside iframe srcdoc

**Comment by zyxnowell** [comment]
I am also having this is just like what's @satendra02 got in his fiddle. Is there any solution to this one?

**Comment by asturur** [comment]
i would assume it works.

**Comment by igorgripas** [comment]
Drag and drop does not work if canvas is located inside iframe while fabric js script is outside it.
@satendra02  link reproduces this situation

**Comment by asturur** [comment]
This because fabric attach events to the document, but in this case, the wrong one.
The idea of having the canvas in an iframe and the library somewhere else is new to me.
Could probably be fixed.

**Comment by iongion** [comment]
Hi, @asturur but the fiddle is failing, **cannot interact** with the objects, you **cannot select**.

> The ideea here is to be able to pass a **custom window / document object for fabricjs** to use as base instead of the global one.

* This situation is caused when dealing with iframes that are not loaded using src, who's html content is written at run-time using DOM functions. In this case fabric thinks it lives in the parent window/document, but it does not, so binding to parent window's events is causing bugs.
* Iframes used like this are an often solution to CSS collision problems when people are migrating legacy apps, it is a very clean solution for a global reset / clean state **document**.

Can we pass something in the options of the fabric.Canvas constructor to be able to tell it to use *this* document/window element instead of the one provided by the global scope.

**Comment by asturur** [comment]
i think fabric uses its own reference to document that is fabric.document and fabric.window, what happen if you change those? we could start referencing here all the code parts that need window/document for interaction and events and count how many those are and what fixes can we do.

**Comment by iongion** [comment]
@asturur , I try right now and come back with answers asap!

**Comment by asturur** [comment]
The problem stays if you want to have more than one iframe...
But if we send it as an option to a canvas, we need to change much code to
have a canvas look for its own document / window reference.
Still something we can investigate if someone has the time for making a
draft.

Il giorno lun 24 feb 2020 alle ore 13:19 ionut stoica <
notifications@github.com> ha scritto:

**Comment by rafasashi** [comment]
To keep a different instance of fabric from one iframe to another it would probably be best to inject fabric.js in each iframe and make the parent controller target a different iframe to apply changes.
```

						
						// get iframe window
						
						var w = window.frames[0].window;
						
						// get iframe fabric
						
						var fabric = w.fabric;
						
						// get canvas
						
						var canvas = new fabric.Canvas('c');
						
						// resize canvas
						
						w.addEventListener('resize', function(){
							
							canvas.setWidth( this.innerWidth );
							canvas.setHeight( this.window.innerHeight );

						}, false);
						
						canvas.setWidth( w.window.innerWidth );
						canvas.setHeight( w.window.innerHeight );
						
						// load vectors
						
						var rect = new fabric.Rect({
							
							left: 150,
							top: 200,
							originX: 'left',
							originY: 'top',
							width: 150,
							height: 120,
							angle: -10,
							fill: 'rgba(255,0,0,0.5)',
							transparentCorners: false
						});

						canvas.add(rect).setActiveObject(rect);

```

**Comment by ShaMan123** [comment]
This is really interesting
`setEnv` can be used with v6.0.0-beta5

> The problem stays if you want to have more than one iframe...
But if we send it as an option to a canvas, we need to change much code to
have a canvas look for its own document / window reference.

I really like this idea

**Comment by ShaMan123** [comment]
https://stackoverflow.com/questions/16010204/get-reference-of-window-object-from-a-dom-element

el.ownerDocument.defaultView is the solution

PRing
