### ISSUE TITLE
fabric.Object#selection on object level

### ISSUE THREAD

**Issue by Kienz** [fabricjs/fabric.js#482]
There is the property fabric.Canvas#selection to enable/disable selection mode. I think to define, that a specified object can not selected with selection-mode would be great.
I knew there is the property fabric.Object#selectable, but if you set this to true, the object can also not selected with "normal" selection (click on object).

What do you think?
##

**Comment by ShaMan123** [comment]
`onSelect` `onDeselect` should handle this and this isuues is probably dead for ages
