### ISSUE TITLE
Detect that canvas element is outside of canvas boundary

### ISSUE THREAD

**Issue by dhavalsisodiya** [fabricjs/fabric.js#4823]
Is there a way to identify that any object element is outside of canvas boundary or not?  Let's say user added different objects in canvas and after that if they hit the "Submit" button, we can warn the user that element is outside of boundary. 

I am able to found that there is a way to prevent user to place the object outside of canvas boundary, but not able to found that there is a way to identify that object is outside of boundary.

It is useful in case where canvas element is changed in server side, like there is a card template in which we have parameters like {first_name}, {last_name} which is replaced on server side with user's actual first_name & last_name. During the replacement, it might happen that object went outside of boundary. So if there a way to identify that element is outside of canvas then we can write logic to place it inside of canvas.

**Comment by scriptspry** [comment]
[fabric.Object.intersectsWithRect](http://fabricjs.com/docs/fabric.Object.html#intersectsWithRect) and [fabric.Canvas.vptCoords](http://fabricjs.com/docs/fabric.Canvas.html#vptCoords) should be sufficient to do this. There is a ready function fabric.Object.isOnScreen but it is not what you want as even if the object is partially outside and partially inside this method returns true.

**Comment by asturur** [comment]
Should be very easy to create a function that is called isFullyOnScreen or isPartiallyOfScreen or whatever else name, derived from what we already have. 
I ll mark as possible feaure and as good for beginners.

**Comment by randomstep** [comment]
Could be `isOnScreen(fully: true)` with a boolean for whether to test if it is fully or partially onscreen.

**Comment by JonathanDn** [comment]
@scriptspry  @asturur  
This method does not state which structure the pointTL and pointBR should be inserted to the function. 
in this method: 
fabric.Object.intersectsWithRect

**Comment by asturur** [comment]
hi @JonathanDn , intersect with rect should take 2 points with x and y properties or 2 fabric.Point instances. i would be ok addressing the doc. can you open an issue that we can label as doc related stating what example of usage would you like to see in the docs, or maybe open a pr to address it as soon as you understand how to use it.

**Comment by JonathanDn** [comment]
I am honestly trying to achieve something quite simple And would be happy if you could provide a working example.

Best would be if it will be on version 1.4.13.
Can also be for 2.0.0 or 2.4.3 if that is needed.

I am just trying to check when a certain Fabric Object is outside the visible part of the canvas... lets say 1214x700 pixels.

I tried intersectsWithRect with these sizes --> it did not work.
I tried isOnScreen --> it did not work.

Which methods should I use, could you show a working fiddle?

**Comment by asturur** [comment]
there is a method that is called isOnScreen that tells you whenever an object has at least a part of the bounding rectangle inside the visible part of the canvas.

now if you change the viewport you have to both update the canvas visible space and the object position, but that happens automatically if you are executing renderAll.

isOnScreen will get false when all the corners of the objects are out of view.

I think there is also one for knowing when is fully onscreen or only partially on screen, but i do not rember now exactly.

**Comment by JonathanDn** [comment]
@asturur  isOnScreen gets true all the time now does not matter if the object is visible or not.

**Comment by asturur** [comment]
it shouldn't. There are unit test that would fail if that would be the case.
anyway, there is also `isPartiallyOnScreen()` that will make exactly what you are looking for.

If you think they fail, please open a fiddle with the bug visible and we can fix it.

**Comment by JonathanDn** [comment]
@asturur 
I changed the canvas.setTransform to canvas.setViewportTransform
and it helped detect when even one object is outside the canvas with
isOnScreen.

The problem I now encounter is that when I have 100 objects.
Every one of them returns true (initially when they area ll visible)

And once even one of them is outside the viewport --> They all return false...

Any clue on this one?

**Comment by asturur** [comment]
reproduce the problem in a jsfiddle.Or is not possible to help.

**Comment by alihassan8193** [comment]
canvas.on('object:scaling' , function (e) 
{
//write code here for what to do if object is out of canvas
}

**Comment by mtrabelsi** [comment]
@uforiadev  remove your comment its not helpful and not answering the question, its just a plain spam
