### ISSUE TITLE
_calcBounds() offset positions of grouped objects

### ISSUE THREAD

**Issue by blobinabottle** [fabricjs/fabric.js#4835]
## Version
2.2

## Test Case
https://jsfiddle.net/66jb8o87/27/
I try to update texts already grouped and update the groups bounds. To do that I call _calcBounds() after I change texts values. But all the objects get their position offset. 
To let you understand quickly in red are the text boxes with correct position.

## Steps to reproduce
Comment group._calcBounds(true); at line 47 and you'll see texts keep their correct position but of course the bounds of the group are incorrect.
Also you should test it with only 1 object in the group. It doesn't work either.

## Expected Behavior
Ideally the positions shouldn't change. Or did I miss something?

## Actual Behavior
Top position offset in a weird way.
Another issue to me is with only 1 text item in the group: it's even worst as the bounds is not even correct AND the position is offset.

**Comment by blobinabottle** [comment]
https://jsfiddle.net/66jb8o87/41/ I tested with simple rects, it's also a bit weird.

**Comment by asturur** [comment]
There is not an easy way to update a group that is already done.
Either ungroup and regroup, or do the math inside.

I think is simpler to ungroup and regroup, since calculation at the end are similar, and if you need to keep box rotation and other properties of the group, add some additional calculation.

I tried to explain transformations in this tutorial, not sure if it helps:
http://fabricjs.com/using-transformations

**Comment by blobinabottle** [comment]
This example is really interesting. Makes me understand much better the matrix/transformations.
But it seems there is a problem somewhere. If you bind the minion and then play with rotation or scale, you see them moving not in sync with the master. 
Here is a video to describe the problem:
https://cl.ly/411t1Q2n2r33

I know it's just an example but I'm getting similar results by playing with matrix in "real time" (~while moving/scaling/rotating).

**Comment by blobinabottle** [comment]
What I'm trying to achieve is the behavior of groups like in typical native apps (sketch, keynote, etc). Meaning we can modify objects into a group and keep the group properties intact (rotation, scale, etc).
Video to describe it: https://cl.ly/0s2W0O3r1K0C

Do you think it's possible with groups in fabric or we should try recreate it from scratch by using transformations as in your example? It's almost like in the video, just need to calculate boundaries in a coherent way...

**Comment by asturur** [comment]
Yes you can make groups mantain properties exactly using the code of the example.
That jelly effect i see too, i also commented somewhere that i have no idea why it happen.
It could be the requestAnimationFrame or some kind of rounding? the problem is that when you stop moving everything is perfect.
And the faster you move, the worse the effect.

**Comment by asturur** [comment]
oh well your movie is different. it actually break something. Maybe that position is the key to understand what is going on?

**Comment by blobinabottle** [comment]
I got the issue if I scale one minion. If just changing their position everything seems good

**Comment by blobinabottle** [comment]
Ok make sense, it’s just because we set the option after the positionbyorigin if we reverse it that’s ok: https://jsfiddle.net/blobinabottle/u4tk4xq1/20/

**Comment by asturur** [comment]
You are getting good :D

2018-04-17 22:35 GMT+02:00 Blob <notifications@github.com>:

**Comment by blobinabottle** [comment]
;D

**Comment by blobinabottle** [comment]
https://jsfiddle.net/blobinabottle/hgvq5byo/117/ I'm trying to play with the matrix to adapt the group boundaries (just move your cursor over the jsfiddle). But I don't know if it's the good idea/path. Do you think it's possible to achieve something stable?

**Comment by asturur** [comment]
Sure, i think i did it, just that for the particular example of transtormation wasn't really necessary. I m very busy, when i have 10 minutes i ll try to remember.
