### ISSUE TITLE
pencilBrush with rgba color problem since version 2.0.3

### ISSUE THREAD

**Issue by mmfouda** [fabricjs/fabric.js#4857]
## Version
2.0.3 and above

## Test Case
https://jsfiddle.net/vvy24yd7/1/

## Steps to reproduce
Revise the modifications done in ver. 2.0.3 on the pencilBrush.

## Expected Behavior
The drawing should have real-time opacity.

## Actual Behavior
The drawing have a solid color with some circles inside.

**Comment by asturur** [comment]
Yes, this is a problem of not having acceptance tests :(
i ll see if i can fix without reverting.

**Comment by asturur** [comment]
@mmfouda i started a fix and try to make it in a release this weekend.

**Comment by AndrewJDR** [comment]
I've also noticed a performance issue caused by this same pencilbrush commit, details here - #4948
