### ISSUE TITLE
Remove white background of image + Image cropping

### ISSUE THREAD

**Issue by vxrai** [fabricjs/fabric.js#4860]
Hi
Wanted to check if anyone worked on -

1. The removal of white background from the image dropped on canvas. Is there any function in fabric js that can help with that. 

We drop a jpg image with a white background on the canvas and we want the user to remove or add white background on the image on button click. 

2. Enhanced crop feature where the user can manually select the section of the image to be cropped on the canvas

@kangax @asturur please guide us incase you have worked on something similar before

**Comment by asturur** [comment]
please check the remove color filter demo, it will remove all the white, even the one that is not in the background, but that is the only thing that is avaliable

Cropping interface is up to the dev. It will not be embedded in fabric
