### ISSUE TITLE
can pencilBrush be with fill property like Path.fill?

### ISSUE THREAD

**Issue by mmfouda** [fabricjs/fabric.js#4861]
I am not sure if this is the right place to ask this question but I wanted to draw a freedrawing with color and width set but I want also it to be filled in real-time while drawing. However, there is not fill property for the brush. Also, the path is not yet created to fill it. Only after I finish drawing, I can fill the path through the created event, but this is not what I need.

I put some code here for better understanding:
https://jsfiddle.net/xmz2xkk3/5/

If you know of any library who implemented it or help me build a customized solution, it will be much appreciated.

**Comment by asturur** [comment]
I understand the question.
We recently moved the pencilBrush to a different drawing logic that kills this opportunity.
And also creates problems with the transparency in general.

I wonder if we did right.

**Comment by asturur** [comment]
Can you illustrate your use case? what is this feature for if i may ask.

**Comment by mmfouda** [comment]
I want to allow the users to draw a filled shape using freedrawing. I want them to see the filled part while drawing.

**Comment by mmfouda** [comment]
I had suggestion to draw it as a polygon but I don't know how.
