### ISSUE TITLE
Fabric js on Google Chrome

### ISSUE THREAD

**Issue by jmd60** [fabricjs/fabric.js#4867]
Hi,
I use fabric js on Chrome 65 and touch event doesn't work. 
The version of fabric.js is 1.7.9, I tested fabric.js 2.2.2 and the result is the same. 

I tested the example : http://fabricjs.com/touch-events and I have this message in the console 
fabric_with_gestures.js:11314 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

Is there any implementations i need to do? Thank you for your time and efforts.

Jean-Michel

**Comment by asturur** [comment]
i think this is a bug.
I think that we switched all the events as passive and this is bad.

**Comment by rightdroid** [comment]
I have the same bug. Is there a workaround for that? This seems to be a deal-breaker when using fabric in kiosk solutions.

**Comment by asturur** [comment]
should be easy fixable

**Comment by slahser1992** [comment]
hello, fixed it already? @asturur

**Comment by asturur** [comment]
no! did not have time

**Comment by slahser1992** [comment]
I will be try today. should be easy.

**Comment by asturur** [comment]
Pushing up one update that let me drag in chrome mobile simulator with fabric 2.2.3
Can you try it now on fabricjs.com?

**Comment by asturur** [comment]
(refresh a couple of time to be sure to get the new build)
