### ISSUE TITLE
Add deprecation warning to obj.getWidth() & obj.getHeight()

### ISSUE THREAD

**Issue by josefanostylus** [fabricjs/fabric.js#4872]
Since version 2.* , the object's functions getWidth() and getHeight() have been removed. However, this is never mentioned in the docs, and there is no deprecation warnings being displayed in the console. In my case, no error was displayed in the console. (I am using fabric 2.2.2 with webpack)

I think this could cause a lot of headaches for people who are trying to update their codebase from version 1.* to 2.* 

## Version
2.2.2

## Steps to reproduce
Import fabric version 2.2.2 (or 2.*) and use obj.getWidth() or obj.getHeight()

## Expected Behavior
An error object thrown or deprecation warning

## Actual Behavior
No errors or warnings displayed

**Comment by durga598** [comment]
getter and setter is optional, and doesn't include in the build, if you want that you can use [custom build](http://fabricjs.com/build/) and include _Named accessors_

**Comment by asturur** [comment]
I need to check if i stated this in some doc, but:

getWidth and getHeight were confusing, were the only methods returning the scaled width and height, they looked like normal getters but were actually doing calculations.

In 1.x version there is clearly written that they are gonna be renamed in the jsdoc over the function.

they got renamed in getScaledWidth and getScaledHeight

**Comment by josefanostylus** [comment]
Hi, thanks for replying. I think the problem in my case was with webpack that. For some reason when I used obj.getWidth(); it didn't throw an error and just failed silently.

**Comment by asturur** [comment]
if you built fabric with the namedSetters, getWidth will return the width now. the width property.
