### ISSUE TITLE
Vertical positioning of text is wrong when using Node JS and canvas.toDataURL with multiplier and when using canvas 2.x

### ISSUE THREAD

**Issue by synio-wesley** [fabricjs/fabric.js#4887]
Rendered text isn't positioned correctly vertically when exporting using canvas.toDataURL() with multiplier and using Node JS with canvas 2.x.

Using canvas 2.x + jsdom 11.x solved all my other text related issues (fallback font for missing glyphs, correct rendering) but it appears another issue has been introduced regarding incorrect vertical positioning for the text when a multiplier is used in canvas.toDataURL() and I can't seem to debug it myself.

## Version
fabric: 2.2.3
canvas: 2.0.0-alpha.12
jsdom: 11.7.0

## Test Case
```
var fs = require('fs'),
    fabric = require('fabric').fabric;

var canvas = new fabric.StaticCanvas(null, {width: 200, height: 200, imageSmoothingEnabled: false});

var rect = new fabric.Rect({
    left: 0,
    top: 0,
    width: 200,
    height: 200,
    fill: 'blue'
});
canvas.add(rect);

var text = new fabric.Text("Test", {
    left: 50,
    top: 100,
    fill: 'white'
});
canvas.add(text);

fs.writeFileSync('./test1.png', canvas.toDataURL({
    format: 'png',
    multiplier: 1
}).replace(/^data:image\/png;base64,/, ""), 'base64');

fs.writeFileSync('./test2.png', canvas.toDataURL({
    format: 'png',
    multiplier: 4
}).replace(/^data:image\/png;base64,/, ""), 'base64');
```

## Steps to reproduce
1. Install required dependencies if necessary (Cairo, Pango, etc.)
2. npm install fabric --save
3. npm install canvas@next
4. npm install jsdom@11.7.0
5. save above test case as test.js
6. node test.js

## Expected Behavior
Both test1.png and test2.png should show the text in the same vertical position.

## Actual Behavior
Viewing test1.png and test2.png will show that when using multiplier in toDataURL the vertical positioning of the text is completely wrong.

![test1](https://user-images.githubusercontent.com/30413/38281535-418bc17c-37ab-11e8-83f2-8c8c596762e7.png)

![test2](https://user-images.githubusercontent.com/30413/38281534-416e4ade-37ab-11e8-93cd-80fca393e87d.png)

**Comment by kidzzz** [comment]
Hello, 

We seem to have the same problem. Attached are the design and the final PNG. You can see the texts are being pushed down by some pixels, but the images are fine. 

![canvasdesign](https://user-images.githubusercontent.com/8389960/45232056-c16ec980-b293-11e8-9a4f-d2582af1f6a0.png)

![canvas](https://user-images.githubusercontent.com/8389960/45232082-d8adb700-b293-11e8-8f6f-21458389ce89.png)



Our environment:

Node 8.11.6
Fabric: 2.3.6
Node-canvas: 1.6.11

@asturur: any thoughts? Thanks!
