### ISSUE TITLE
Image not displaying when loading from JSON

### ISSUE THREAD

**Issue by newtriks** [fabricjs/fabric.js#4888]
## Version
2.2.3

## Test Case
https://jsfiddle.net/gqcgwd7j/

## Steps to reproduce
Click the load button to load the JSON containing an image onto the canvas 

## Expected Behavior
An image should display on the canvas

## Actual Behavior
No image displays on the canvas. If you look at the canvas log, however, the canvas shows it has one item. I have also tried `canvas.renderAll.bind(canvas)` and `canvas.requestRenderAll`.

**Comment by GreatAuk** [comment]
The problem still exists

**Comment by duydodevgithub** [comment]
There's something wrong with the JSON file. I use a different JSON and it works 
var json = '{"objects":[{"type":"rect","left":50,"top":50,"width":20,"height":20,"fill":"green","overlayFill":null,"stroke":null,"strokeWidth":1,"strokeDashArray":null,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"selectable":true,"hasControls":true,"hasBorders":true,"hasRotatingPoint":false,"transparentCorners":true,"perPixelTargetFind":false,"rx":0,"ry":0},{"type":"circle","left":100,"top":100,"width":100,"height":100,"fill":"red","overlayFill":null,"stroke":null,"strokeWidth":1,"strokeDashArray":null,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"selectable":true,"hasControls":true,"hasBorders":true,"hasRotatingPoint":false,"transparentCorners":true,"perPixelTargetFind":false,"radius":50}],"background":"rgba(0, 0, 0, 0)"}';

**Comment by newtriks** [comment]
@duydodevgithub this issue is specific to defining an image via URL in the JSON. You don't have a `url` key value hence your JSON works... ¯\_(ツ)_/¯

**Comment by asturur** [comment]
in your JSON the `src` property is missing, and os nothing can be loaded.

https://jsfiddle.net/gqcgwd7j/64/

with src it works.

Your JSON is not correct, how did you generate it?

**Comment by newtriks** [comment]
@asturur the JSON was generated using `canvas.toJSON :confused:

**Comment by asturur** [comment]
how did you get URL there instead of src?
