### ISSUE TITLE
Node JS opacity render issue

### ISSUE THREAD

**Issue by Clemweb** [fabricjs/fabric.js#4889]
Hello,

I've an issue with NodeJs render : on my browser the canvas is fine, I can change the opacity on elements like rectangle, text etc...

The saved JSON file is correct, mean the value of opacity in the file is correct (I can have many different value on different element)

Bug when I render the canvas width Node curiously all the canvas opacity is changed. When I set opacity on 1 the render is ok.

When my canvas contains only 1 text all work fine, but with one more (the 2 texts has different opacity value) the render is wrong.

Is there a bug ?

![2516-1](https://user-images.githubusercontent.com/24622426/38378588-85e9e4b2-38fe-11e8-95e9-593df45d2819.png)
![wrong](https://user-images.githubusercontent.com/24622426/38378591-88908b80-38fe-11e8-8644-6848cbe5acc5.png)

## Version
1.7.20

## Steps to reproduce
Insert a text or i-text, change the opacity

## Expected Behavior
Node js render must apply specific opacity on each element

## Actual Behavior
Nodejs render change the canvas opacity

Thanks

**Comment by asturur** [comment]
please provide the node script

**Comment by Clemweb** [comment]
Hi Asturur

I do this 

`req.body.canvas = fabric.createCanvasForNode(finalCanvasWidth, finalCanvasHeight);


	var p=new Promise(function(resolve, reject){

		req.body.canvas.loadFromJSON(req.body.jsonStr, function(){
			try{
				console.log('> Loaded OK');
				
				var imgsToLoad=[], txtsToLoad=[];
				// Create main support
				console.log('> Search support ...');
					
				req.body.canvas.forEachObject(function(obj){
					if(typeof obj.ctzParams!='undefined'){
						if(obj.ctzParams.id=='ctzMainSupport'){
							console.log('> Find!');
							req.body.support=fabric.util.object.clone(obj);
							// Get support color add overhand
							req.body.canvas.backgroundColor=req.body.support.paths[0].fill;
							return false;
						}
					}
				});

				// Cal new optimal scale
				if(req.body.wantedCanvasWidth>=req.body.wantedCanvasHeight){
					newMaxSize=req.body.wantedCanvasWidth;
					scale=req.body.wantedCanvasWidth/req.body.realWidth;
				}else{
					newMaxSize=req.body.wantedCanvasHeight;
					scale=req.body.wantedCanvasHeight/req.body.realHeight;
				}

				
				req.allpromises = [];
				req.body.canvas.forEachObject(function(obj){
					// Disable main clip
					obj.clipTo=null;

					var shadow={};

					if(obj.isType('image')){

						console.log('> Load old url image : '+obj.src+' - width : '+obj.getWidth()+' - scale : '+obj.getScaleX()+' - original width : '+obj.getWidth()*obj.getScaleX());
						var newUrl=obj.src.replace(/(size=).*?(&)/,'$1' + newMaxSize + '$2').replace(/(mode=).*?(&)/,'id_customer='+req.body.id_customer+'&token=dd0js1oc!&');
						console.log('> Load new url image : '+newUrl);

						var finalImgWidth=obj.getWidth();
						var finalImgHeight=obj.getHeight();

						req.allpromises.push(new Promise(function(subresolve, reject) {
							fabric.util.loadImage(newUrl, function(img) {
								obj.setElement(img, function(){
									obj.setScaleX(1).setScaleY(1).set({
										width:finalImgWidth,
										height:finalImgHeight
									});

									if(typeof obj.ctzParams!=='undefined' && obj.ctzParams.shadowEnabled){
										shadow={
											color: obj.ctzParams.shadowColor,
											blur: (finalImgWidth*obj.ctzParams.shadowBlur/100),
											offsetX: (finalImgWidth*obj.ctzParams.shadowOffset.x/100)/req.body.scale,
											offsetY: (finalImgWidth*obj.ctzParams.shadowOffset.y/100)/req.body.scale
										};
									}
									obj.set({
										shadow: shadow
									});

									req.body.canvas.renderAll();
									console.log('> Image loaded !');
								});

								subresolve();
							});
						}));


					}else if(obj.isType('i-text') || obj.isType('text')){
						if(req.body.texttoimg==1){
							console.log('> Initial txt width '+req.body.canvasWidth+' * '+obj.ctzParams.percent.width+' / 100');
							obj.setVisible(false);

							var txtID='ctzTxt'+obj.ctzParams.id;
							console.log('> Replace text "'+txtID+'" object by image');

							req.allpromises.push(new Promise(function(subresolve, reject) {
								fabric.util.loadImage(req.body.mainDir+'txt-'+txtID+'.png', function(img) {
									req.oImg = new fabric.Image(img);
									var widthTextBrut=(req.body.canvasWidth*obj.ctzParams.percent.width/100);
									var widthPadding=widthTextBrut*obj.ctzParams.percent.padding/100;
									var zIndex=req.body.canvas.getObjects().indexOf(obj);
									
									console.log('> Loaded txt image to width : '+widthTextBrut+' - padding: '+widthPadding);
								  req.oImg.scaleToWidth(widthTextBrut+(widthPadding*2)).set({
								  	padding: 0,
								  	originX: 'center',
										originY: 'center',
										angle: obj.ctzParams.angle,
										centeredScaling:true,
								    left: obj.left,
								    top: obj.top,
								    opacity: 1, // Set 1 but becareful : it's ok because text is from image taken from canvas, so the opacity is in this image.
								    shadow: {} // Set off but becareful : it's ok because text is from image taken from canvas, so the shadow is in this image.
								  });
								  req.body.canvas.insertAt(req.oImg, zIndex);
								  req.oImg.setCoords();
								  console.log('> Font image '+txtID+' loaded at width: '+req.oImg.getWidth()+' and left: '+req.oImg.getLeft()+' and top: '+req.oImg.getTop());

								  subresolve();
								});
							}));

						}else{
							console.log('> Load font "'+obj.fontFamily+'" - "'+obj.ctzParams.fontFile+'" - '+req.body.dir+ '/_custengine/fonts/'+obj.ctzParams.fontFile);
							font = new canvas.Font(obj.fontFamily, req.body.dir+ '/_custengine/fonts/'+obj.ctzParams.fontFile);
							req.body.canvas.contextTop.addFont(font);
						}
					}else{
						if(typeof obj.ctzParams!=='undefined' && obj.ctzParams.shadowEnabled){
							shadow={
								color: obj.ctzParams.shadowColor,
								blur: (obj.width*obj.ctzParams.shadowBlur/100),
								offsetX: (obj.width*obj.ctzParams.shadowOffset.x/100),
								offsetY: (obj.width*obj.ctzParams.shadowOffset.y/100)
							};
						}else{
							shadow={};
						}
						obj.set({
							shadow: shadow
						});
					}
				});
			
				return Promise.all(req.allpromises).then(function(){
					// quand toutes les promesse images sont résolues (succès comme rejet), on résout la promesse principale
					req.body.canvas.renderAll();
					resolve(true);
				}).catch(function(error){
					console.log(error);
				});`

**Comment by asturur** [comment]
I see a lot of code that is app related more than canvas rendering.

Can you create a index.js that i run with node index.js and that reproduce the big without having to rely on other stuff?

**Comment by Clemweb** [comment]
Too hard to extract only part of code...

but I do some test and it's strange : it's like the opacity on each element on the canvas are combinated or substract.

Is there other property to change opacity ?

**Comment by asturur** [comment]
if is too hard to extract maybe the bug is not so bad. I can t really use my time to debug lot of code i have first to understand.


Coming with a small, clear, reproducible case is the first common sense rule to ask for a fix.
