### ISSUE TITLE
setSrc in the third param doesnt apply width and height

### ISSUE THREAD

**Issue by salomonsanz** [fabricjs/fabric.js#4890]
## Version
2.2.3

## Test Case
http://jsfiddle.net/Da7SP/1434/

## Steps to reproduce
in the setSrc method, in the third param specify a width and height values

## Expected Behavior
The loaded image using "setSrc" should have the specified width and height

## Actual Behavior
It is forced to have the original element width and height and the size only can be changed using the scaleX and scaleY params, forzing to use again a fix function in the setSrc callback (used up to this point and that I was hoping this new version would fix). The behaviour that setSrc used to have in the v1.* was perfect.

```
fabric.Image.prototype.fixFabricV2Scale = function() 
{
       let img = this.getElement();
       var real_width = this.width * this.scaleX;
       var real_height = this.height * this.scaleY;

       this.set({
               width: img.naturalWidth,
               height: img.naturalHeight,
               scaleX: real_width / img.naturalWidth,
               scaleY: real_height / img.naturalHeight
       });            
}
```

**Comment by asturur** [comment]
Well to be honest i did not think this as a part of the api.
But i see your point.

I thought that setSrc would have been called just to change the image element and that it was the right thing to set original width and height.

This is a use case i did not think about.
You can set width and height with just passing options down to setWidthAndHeight, but this will not change the v2 behaviour that is about cropping an image and not scaling it down.

If you want to open a PR for it please do it, or i'll do as soon as i can.

**Comment by scriptspry** [comment]
It's probably my mistake not tagging @asturur in the comment i made few days ago.

https://github.com/kangax/fabric.js/pull/4877#discussion_r178462787

I think that's what's causing this issue. [Working fiddle](http://jsfiddle.net/Da7SP/1432/).
