### ISSUE TITLE
SVG Radial Gradient not rendering properly when i try to load SVG as string. 

### ISSUE THREAD

**Issue by Sillergeoduck** [fabricjs/fabric.js#4898]
## Version
2.2.3

## Test Case
http://jsfiddle.net/Da7SP/1466/

## Steps to reproduce
create a SVG with Radial gradient , as shown below SVG:

`<svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 150" ver="4" width="500" height="500">
  <defs>
    <radialGradient id="fill_id0" spreadMethod="pad" gradientUnits="objectBoundingBox">
      <stop stop-color="#ff7e00" offset="0%"/>
      <stop stop-color="#ff7e00" offset="14%"/>
      <stop stop-color="#fd8813" offset="37%"/>
      <stop stop-color="#3c2900" offset="47%"/>
      <stop stop-color="#3c2900" offset="50%"/>
      <stop stop-color="#ffffff" offset="53%"/>
      <stop stop-color="#fffaf7" offset="55%"/>
      <stop stop-color="#ff7e00" offset="71%"/>
      <stop stop-color="#ff7e00" offset="100%"/>
    </radialGradient>
  </defs>
  <rect id="background" fill="url(#fill_id0)" x="0" y="0" width="300" height="150"/>
</svg>`

## Expected Behavior
http://jsfiddle.net/Da7SP/1471/ --- Loading SVG as data URL , works perfectly fine ....

http://jsfiddle.net/Da7SP/1468/ -- Trying to load SVG as string , does not render the radial gradient

if you look in the above 1st fiddle , i am trying to render the svg as data URL , when i do that it is rendering perfectly fine as expected. But when i try the same to render as string in the 2nd filddle , it fails to render the radial gradients. could you please help me fix it. 

## Actual Behavior
please check the above fiddle, i have just created a simple radial gradient as background and trying to render SVG as string. But the radial gradient is not rendering properly. Here i am trying to load SVG as string as shown above in the fiddle

**Comment by asturur** [comment]
http://jsfiddle.net/Da7SP/1471/ --- Loading SVG as data URL , works perfectly fine ....

http://jsfiddle.net/Da7SP/1468/ -- Trying to load SVG as string , does not render the radial gradient

for me both fiddle works, with a bit of difference.
Can you explain what is that is not loading at all for you?

**Comment by Sillergeoduck** [comment]
http://jsfiddle.net/Da7SP/1471/ --- Loading SVG as data URL , works perfectly fine ....

http://jsfiddle.net/Da7SP/1468/ -- I want this fiddle to load just like the way the first fiddle is loading ... this one is loosing its radial gradient , if you see the first one the circle radial looks different from this one.... not sure why though .. the first one i am loading as data url works the way it has to ... but the second one is not... could you please help me fix that...

**Comment by asturur** [comment]
Ok so is not loosing it, is just not respecting the stretch.

**Comment by Sillergeoduck** [comment]
Yes , my apologies for wrong choice of words ... yes as u said its not respecting the stretch....

**Comment by ajvincent** [comment]
The "load SVG as data URL" example is broken.  Could you try to fix it?

I think I've run into this bug as well, so if you can, I can make an attempt to figure out what's going on here.

**Comment by asturur** [comment]
can you point me at the example?

**Comment by ajvincent** [comment]
http://jsfiddle.net/Da7SP/1471/ as per the top of this ticket...

**Comment by asturur** [comment]
i'm sorry i thought you were referring to some kind of website example

**Comment by asturur** [comment]
http://jsfiddle.net/uf4as569/ <--- this is the correct dataurl, the other is malformed.
Also the stretch bug stays

**Comment by asturur** [comment]
Seems fixed to me.
