### ISSUE TITLE
imageSmoothingEnabled=false ignored when caching turned on

### ISSUE THREAD

**Issue by CookieJon** [fabricjs/fabric.js#4911]
When objectCaching is true, images are smoothed even if the main canvas specifies no smoothing.

## Version
2.2.3

## Test Case
https://jsfiddle.net/CookieJon/xpvt214o/130294/

## Steps to reproduce
- Specify canvas `imageSmoothingEnabled=false`
- Specify `objectCaching=true`

## Expected Behavior
Images should not be smoothed

## Actual Behavior
Images are smoothed

**Comment by CookieJon** [comment]
Indeed. The problem seems to be that objects' cache canvases are unaffected by the main canvas's 'imageSmootingEnabled' option.  

I tried subclassing 'fabric.Image', overriding '_render()' and setting 'ctx.imageSmoothingEnabled=false', but it doesn't always work for me (I have to resize the image up for it to kick in) and I don't understand the caching mechanism enough to know why that's the case.  

Seems to me 'imageSmoothing' option should flow to cached objects without hacking, so I raised this issue. :-)

**Comment by asturur** [comment]
So image caching is default off because it often loose sense, also the code is not really good at caching images right now. Needs some reworking.

What is your reason behind caching images?

**Comment by CookieJon** [comment]
> What is your reason behind caching images?

I can live without it.

**Comment by asturur** [comment]
i mean as of now it does not offer any improvement in speed at all.

**Comment by asturur** [comment]
@CookieJon a change landed in recent beta that fix this issue.
Is now possible to specify this setting on the images, and it works independently of caching.
