### ISSUE TITLE
SprayBrush bug after adding a video

### ISSUE THREAD

**Issue by 1394230111** [fabricjs/fabric.js#4913]
## Version
2.2.3

## Test Case
http://jsfiddle.net/Da7SP/1553/

## Steps to reproduce
1.add a video
2.zoom in or out
3.draw something

## Actual Behavior
The upper canvas does not fit the lower canvas. It seems that the upper canvas have a bigger/smaller zoom level
![default](https://user-images.githubusercontent.com/5087845/38789023-feed4ad4-4169-11e8-8fb3-6f406ab5745c.gif)

**Comment by asturur** [comment]
well continuosly refreshing the canvas while brushing was never an idea.
But i see your point, we need to check if a fix is possible.

**Comment by 1394230111** [comment]
Thank you!
But maybe there is a new issue.
When I need to set canvas width/height, The same thing happened!  And the param 'cssOnly' make it unwork.
Test Case:
[http://jsfiddle.net/Da7SP/1644/](http://jsfiddle.net/Da7SP/1644/)
I hope you can help.

**Comment by asturur** [comment]
i took resize in consideration, i evidently did something bad

**Comment by 1394230111** [comment]
There has been no feedback for a long time. Do you have any plans to revise it?

**Comment by asturur** [comment]
yeah but you know plans often differ from outcomes.
Is also an hard setup to test.

**Comment by ShaMan123** [comment]
seems fixed by the test case http://jsfiddle.net/Da7SP/1553/
