### ISSUE TITLE
Feature request: Image with rounded borders

### ISSUE THREAD

**Issue by DangerD256** [fabricjs/fabric.js#4914]
I need to make image with rounded borders. Yes, i can use clipTo, but i also need to use stroke and stroke is cut if i use clipTo.

Also i can't export it to JSON, when i load it, i'm getting error with clipTo function is not found, any suggestions with that?

**Comment by asturur** [comment]
use a rect with rounded corners and a pattern? may it work?

**Comment by asturur** [comment]
clipPath api may be the thing for you but is not coming out soon. That would cut the image with a path of choice and could use it for border paint too.

**Comment by DangerD256** [comment]
OKay, regarding saving canvas (toJSON), it serializes it as `clipTo":"function () { [native code] }"`
How can i save to json with clipping?

**Comment by asturur** [comment]
well it should not. It should serialize with correct syntax

**Comment by asturur** [comment]
please make a fiddle, if there is a bug we will address

**Comment by DangerD256** [comment]
https://jsfiddle.net/krxwdz8t/2/

seems like i need to rewrite code, with circle it exports corrent, with rounded borders not...

**Comment by DangerD256** [comment]
Yeap, this way works:
https://jsfiddle.net/va2bbf7f/

**Comment by DangerD256** [comment]
Can some stroke be added to clip?

**Comment by asturur** [comment]
Clipping with clipPath does not support borders.
But paths can have borders and can be filled with an image pattern.

**Comment by Richienb** [comment]
Simpler implementation:

```js
const roundedCorners = (image, cornerRadius) => new fabric.Rect({
    width: image.width / image.scaleX,
    height: image.height / image.scaleY,
    rx: cornerRadius / image.scaleX,
    ry: cornerRadius / image.scaleY,
    left: -image.width / 2,
    top: -image.height / 2
})

image.set("clipPath", roundedCorners(image, 20))
```
