### ISSUE TITLE
Fabric Touch build does not fire object:modified when resizing with a gesture

### ISSUE THREAD

**Issue by stewartmatheson** [fabricjs/fabric.js#4915]
## Version
fabric-with-gestures 2.2.2

## Test Case
https://jsfiddle.net/mmv80jc3/3/

## Steps to reproduce
1. Use a build of fabric with fabric-touch enabled
2. Create any object on the canvas.
3. Use a touch enabled device to resize the object to a different size

## Expected Behavior
Once the resize is finished I would expect the object:modified event to be fired

## Actual Behavior
object:modified does not fire.

**Comment by arlen-yu** [comment]
FYI the event fires on my iPhone 6s, safari browser

**Comment by leinue** [comment]
same problems

**Comment by lingsang2** [comment]
up

**Comment by jake-griffin** [comment]
I am experiencing the same problem, on an iPhone X in Safari. However, I am only seeing it when you use a two finger gesture (scale or rotate) and 1 or both of your fingers leave the canvas before releasing.

**Comment by jake-griffin** [comment]
On the fiddle that stewartmatheson posted, though, I see it with any two-finger gesture (whether I leave the canvas or not). I am using a custom fabric build with Touch based on fabric 3.2.0 and I only experience it when at least one finger leaves the canvas before releasing the gesture.

**Comment by asturur** [comment]
the idea is to move to hammer.js integration and rewrite those events to be on par with mouse gestures.
