### ISSUE TITLE
Getting low resolution output for small canvas

### ISSUE THREAD

**Issue by nitin-bc** [fabricjs/fabric.js#4921]
Hi Support,

I am using fabric 1.7.9 to work on my project. If I create small dimension canvas and set the image with high resolution then the canvas.todataURLwithMultiplier() is giving blurred output. Would you please confirm if there is something I can do to fix this issue?

Looking forward to hearing from you soon.

![layer_e404412](https://user-images.githubusercontent.com/24458978/39119048-88b8a396-4708-11e8-8cab-93299d6bb9d6.jpg)
![pd_res_8cecc7e](https://user-images.githubusercontent.com/24458978/39119063-93a5e7c8-4708-11e8-8c12-f4616850954d.jpg)

**Comment by nitin-bc** [comment]
Hi,
Can someone update me on my issue please?

**Comment by asturur** [comment]
I m sorry you have to use at least 1.7.22 or 2.2.3, older version are not supported at all.
Can you make a fiddle of this low resolution output?

When you open an issue there is clearly written we need a fiddle to look into things.

**Comment by asturur** [comment]
You are not doing anything wrong, that is how canvas resize images, with a simple algorithm that produces bad results.
If you want to obtain something better you need to use fabric resizeFilter, but then you can't use the multiplier, you have to write some custom export code.

What are you doing with your application? are you specifically resizing images or are you trying to do something more general and this is a particular case of your app?

**Comment by nitin-bc** [comment]
Hi,
Thank you for your quick response. Actually, we are generating the high-resolution images by calculating the multiplier based on the resolution of the background image. We are getting a good result if we keep the canvas size bigger. But if we keep the smaller canvas then the output is not getting properly as it should be.

Hopefully, you are getting me.

**Comment by asturur** [comment]
does your app just generate different size images?

**Comment by asturur** [comment]
the dataurl is proper, is the canvas that is generating bad images.

Give a look at resize filters for better resizing
