### ISSUE TITLE
TextBox - fontFamily with custom font not shows up on initial render

### ISSUE THREAD

**Issue by redlive** [fabricjs/fabric.js#4922]
## Version
2.2.3

## Test Case
https://jsfiddle.net/redlive/g0ars1gb/

## Steps to reproduce
Load fiddler

## Expected Behavior
Initial render will have text set to Arial Italic custom font.
## Actual Behavior
Some default font renders.

**Comment by asturur** [comment]
The font you want to use, Arial Italic is not ready when you add the textbox to the canvas.
So it show a fallback, that in case looks like a timesnewroman to me, maybe in your machine it picks up an Arial.
There is nothing wrong here, you should preload the fonts before adding the textbox to the canvas.

**Comment by dannmalik** [comment]
> The font you want to use, Arial Italic is not ready when you add the textbox to the canvas.
> So it show a fallback, that in case looks like a timesnewroman to me, maybe in your machine it picks up an Arial.
> There is nothing wrong here, you should preload the fonts before adding the textbox to the canvas.

Is there a way to keep a backup font family if some characters are unavailable in the font family? Say '.' isn't available in the font family. For the unavailable character, Chrome falls back to Time New Roman and Safari to Helvetic on Mac OS.

**Comment by asturur** [comment]
that is up to the OS nothing we can influence with JS.
Unless you can do it with some clever font family name.
Like `mySpecialFontName Arial`. Maybe some css spec i do not know.

**Comment by vijaygurjar** [comment]
is any solution found for above issue. Just want to hide unsupported characters

**Comment by Xmmsir** [comment]
请问怎么解决
