### ISSUE TITLE
Ghost overlay image

### ISSUE THREAD

**Issue by Sashkan** [fabricjs/fabric.js#4925]
## Version
2.2.1

## Test Case
inconsistent bug

## Steps to reproduce
I have an empty canvas, 

I have 2 buttons : first one sets both an overlayImage and a backgroundImage second one replaces my backgroundImage by another, and remove my overlayImage.

Code is pretty straightforward : 

```js

firstButton = () => {


    fabric.Image.fromURL(
      url,
      (img) => {
        this.canvas.setBackgroundImage(
          img,
          () => {
            this.canvas.renderAll.bind(this.canvas)
          }
        )
      },
      {
        crossOrigin: 'anonymous',
        objectCaching: false,
      }
    )


      fabric.Image.fromURL(
        url,
        (img) => {
              img.scaleToWidth(this.canvas.getWidth())
              img.set({
                originX: 'left',
                originY: 'top',
              })
              this.canvas.setOverlayImage(
                img,
                this.canvas.renderAll()
              )
            },
            {
              crossOrigin: 'anonymous',
              objectCaching: false,
            }
          )
}


secondButton = () => {

    fabric.Image.fromURL(
      urlImg1,
      (img) => {
        this.canvas.setBackgroundImage(
          img,
          () => {
            this.canvas.renderAll.bind(this.canvas)
          }
        )
      },
      {
        crossOrigin: 'anonymous',
        objectCaching: false,
      }
    )
    this.canvas.setOverlayImage(0)
}


```
## Expected Behavior

When clicking the second button, I should see the correct background image, and no overlay Image.

Background image on first button click (overlayImage is the shirt sleeves): 
![image](https://user-images.githubusercontent.com/6276267/39234766-790acd26-4874-11e8-9df8-3cc6eafe445f.png)

Background image on second button click : 

![image](https://user-images.githubusercontent.com/6276267/39234789-8fc080f6-4874-11e8-89ff-7cce6c1b38f3.png)

## Actual Behavior

Every once in a while, when I click on my second button, the backgroundImage is correctly replaced, but the overlay image stays in place, until I click in my canvas.

![image](https://user-images.githubusercontent.com/6276267/39234932-e21b55f6-4874-11e8-8164-5529580740e6.png)

Any way to prevent this behaviour ?

**Comment by asturur** [comment]
Please make a JSFIDDLE with the 2 buttons on top of a canvas.
