### ISSUE TITLE
LoadfromJSON breaks when fabric.image has a resizeFilter

### ISSUE THREAD

**Issue by offerpopje** [fabricjs/fabric.js#4929]
## Version
2.2.2 & 2.2.3

## Test Case
https://jsfiddle.net/offerpopje/twgpzu52/2/

## Steps to reproduce

Load an exported JSON object using loadFromJSON, with a fabric.image object that contains a resizeFilter.

## Expected Behavior

Fabric.image object should load.

## Actual Behavior

LoadfromJSON breaks on cannot read property 'fromObject' of undefined, only for fabric.image objects that have a resizeFilter.

**Comment by asturur** [comment]
looks a legit bug

**Comment by asturur** [comment]
Can i ask you to reproduce the bug? the code looks good to me, you have a type = 'hermite' but i m worried you got there with your on code?

**Comment by asturur** [comment]
THe current fiddle show a broken JSON data. Please try to reproduce how do you get to that data.

**Comment by offerpopje** [comment]
It is generated by running the following code: 
`image.resizeFilter = new fabric.Image.filters.Resize({type: 'hermite'});
image.applyResizeFilters();`

Just like it was mentioned on this page: http://fabricjs.com/v2-breaking-changes

Then after that the canvas is exported through 
`var json = JSON.stringify(canvas);`

If you need a fiddle that reproduces this object let me know.

**Comment by asturur** [comment]
so you are just initializing it wrong.

image.resizeFilter = new fabric.Image.filters.Resize({resizeType: 'hermite'}); image.applyResizeFilters();

Also hermite is the default one, no need to initialize it
