### ISSUE TITLE
Fabric js incompatibility with css grid layout

### ISSUE THREAD

**Issue by MGTHEBOSS** [fabricjs/fabric.js#4932]
Hi,

We would like to thank the contributors for developing and maintaining an amazing library such as fabric.js. With every passing day, fabric.js keeps getting more awesome. We are using fabric js in an app that uses css grids. We are also using the setHeight and setWidth methods to set the height and width of the canvas to its initial values before adding an image as we noticed that if we don't fabric.js resizes the canvas to 300x150. The problem that we are encountering is, when an image is loaded, the div element of preview class that wraps the canvas increases in size and disturbs the grid layout. 

Version information: chrome 66.0.3359.117, jquery 3.3.1, fabric js 2.2.3.

unit-1524827977610.html:
```
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title>unit-1524827977610</title>
    <style>
        .item-1 {
            grid-area: item-1;
        }

        .item-2 {
            grid-area: item-2;
        }

        .preview {
            grid-area: preview;
            position: relative;
        }

        .item-3 {
            grid-area: item-3;
        }


        .grid-container {
            display: grid;
            grid-template-areas: 'item-1 item-1 preview preview preview preview' 'item-2 item-2 preview preview preview preview' 'item-3 item-3 item-3 item-3 item-3 item-3';
            grid-gap: 50px;
            height: 100vh;
            padding: 10px;
        }

        .grid-container>div {
            border: 1px solid #000000;
            text-align: center;
            display: flex;
            align-items: center;
            justify-content: center;
            cursor: pointer;
        }

        canvas {
            border: 1px solid black;
            position: absolute;
            height: 100%;
            width: 100%;


        }
    </style>
</head>

<body>
    <div class="grid-container">
        <div class="item-1">item 1</div>
        <input type="file" id="choose-file" style="display: none;">
        <div class="item-2">item 2</div>
        <div class="preview">PREVIEW</div>
        <div class="preview"><canvas id="canvas"></canvas></div>
        <div class="item-3">item 3</div>

    </div>
    <script src="jquery-3.3.1.js"></script>
    <script src="fabric.js"></script>
    <script src="unit-1524827977610.js"></script>
</body>

</html>
```
unit-1524827977610.js
```
$(document).ready(function() {
    var canvasheight = $("#canvas").height();
    var canvaswidth = $("#canvas").width();
    console.log(canvasheight, canvaswidth);
    $(".item-1").click(function() {
        $("#choose-file").click();

    });

    $("#choose-file").change(function(e) {
        var reader = new FileReader();
        reader.onload = function(event) {

            var imgObj = new Image();
            imgObj.src = event.target.result;
            imgObj.onload = function() {


                var image = new fabric.Image(imgObj);
                image.set({
                    left: 0,
                    top: 0,
                    angle: 0,
                    padding: 10,
                    cornersize: 10
                });
                var canvas = new fabric.Canvas("canvas");
                canvas.setHeight(canvasheight);
                canvas.setWidth(canvaswidth);
                canvas.add(image);




            }

        }
        reader.readAsDataURL(e.target.files[0]);
    });



});
```
Screenshot: The page has been loaded:
![1-e](https://user-images.githubusercontent.com/3612991/39361700-3fe765b2-4a41-11e8-93f1-3e2318842cac.png)

Screenshot: An image has been selected:
![2-e](https://user-images.githubusercontent.com/3612991/39361754-792da43a-4a41-11e8-95df-649cbc8744cf.png)

We appreciate the cooperation of the community members.

**Comment by asturur** [comment]
Hi, it would be necessary for you to reproduce the problem in jsfiddle so that we can look at.
Include a minimal gridlayout and the code that generate the problem, removing all the unnecessary parts.

**Comment by MGTHEBOSS** [comment]
@asturur https://jsfiddle.net/mgtheboss/k9fxsLt4/3/

**Comment by asturur** [comment]
https://jsfiddle.net/k9fxsLt4/4/

300 and 150 are the standard canvas size if not differently specified.
Fabricjs won't be at best in a responsive design because of pixel scaling, but with this code sample you should be able to make it work, it is setting the width/height of the canvas to the space you reserved, then is putting back 100% on the size to fill up the space.

I do not know how you can do this differently.
