### ISSUE TITLE
How to  draw webcam view to canvas on IOS 11?

### ISSUE THREAD

**Issue by zxcv13579** [fabricjs/fabric.js#4935]
Hi,
 I can  draw webcam view to canvas on computer, but use ios 11 cell phone, it will doesn't work,
only webcam can work, they doen't draw webcam view to canvas, i don't know how should I do, Let this code will can work. I very need this features.

html:
  `<canvas id="canvas" width="500" height="500"></canvas>`
  `<video autoplay playsinline></video>`

js
  var video = document.querySelector('video');

	var canvas = new fabric.Canvas('canvas',{
		selection: false
	});

	navigator.mediaDevices.getUserMedia({ video: true, audio: false})
		.then(function(localMediaStream ){
			console.log(localMediaStream);
			window.stream = localMediaStream
			video.srcObject =  localMediaStream;
			run();
		})

	function run(){
		var webcam = new fabric.Image(video, {
			left: 0,
			top: 0,
			width: 500,
			height: 500
		});

		canvas.add(webcam);
		webcam.getElement().play();

		render();
		function render(){
			canvas.renderAll();
			fabric.util.requestAnimFrame(render);
		}
	}

Please help me solve the problem. Thank!

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
