### ISSUE TITLE
When clipped canvas exported as JPG gives black background

### ISSUE THREAD

**Issue by monis01** [fabricjs/fabric.js#4937]
Hi
I am facing an issue with the clipped region that is giving black background when is exported as jpg image. I have a canvas onto which I add shapes like(circle,square,rectangle,octagon etc.) and clipped the canvas according to the base shapes. Now when I try preview the drawn image by doing :
```
imagBased64 = canvas.toDataURL({multiplier:1});                    
$('#preview_img').attr('href', imagBased64);
```
and same thing happens when I send data to backend and then fetch then generated image. This what my canvas is like  
![screenshot from 2018-04-28 14-53-07](https://user-images.githubusercontent.com/7036532/39394844-6d857848-4af4-11e8-8297-12373e3ba001.png)
and this what I get on preview (and getting image back from the server)
![screenshot from 2018-04-28 14-53-10](https://user-images.githubusercontent.com/7036532/39394852-8dae03c4-4af4-11e8-82ed-8f5b0fd7867f.png)

**I have tried** :
```
var shape = canvas.item(0);
canvas.clipTo = function(ctx){
            shape.set({
                       fill:' '
            })
           shape.render(ctx);
}
```
and also [#2443](https://github.com/fabricjs/fabric.js/issues/2443) by making changes as [directed here](https://github.com/fabricjs/fabric.js/pull/1875/files), but no luck.
Have I missed something or I am not aware of.
Thanks for time and help.

PS: I am using fabric "1.6.2" .

**Comment by asturur** [comment]
Canvas pixels are transparent black, all zeroes.
IF you do not color them with white, in jpeg you get non transparent black, black black.

Seta background color to white for your canvas, what you see on your canvas in the browsers is a transparent canvas trough which the white webpage is visible.

**Comment by monis01** [comment]
Yes I did that 
```
canvasCopy.setBackgroundColor('#FFFFFF')
canvasCopy.renderAll();
```
![screenshot from 2018-04-28 16-14-59](https://user-images.githubusercontent.com/7036532/39395711-8ab6009e-4aff-11e8-95fa-572645f7c9ca.png)
 
but when checked inside 
```
canvasCopy.renderAll();
```
``canvasToDrawOn`` variable
![screenshot from 2018-04-28 15-10-06](https://user-images.githubusercontent.com/7036532/39395730-e4141e8c-4aff-11e8-8c3b-77bd2ca04387.png)
is this `fillStyle` dominating ?

Thanks

**Comment by asturur** [comment]
no i think your clipTo is clipping the background color too.

try to use the `before:render` event and  do 

```
this.contextContainer.fillStyle = 'white'
this.contextContainer.fillRect(0, 0, canvas.width, canvas.height)
```

**Comment by monis01** [comment]
Thanks I believe that is what happening, fixed now.   :+1: 
So by clipping the region on canvas it changes that area to transparent and when I have exported it to 'png' format I was able to get white background.
Is there anything I can read more deep on such issue.
Thanks

**Comment by asturur** [comment]
So the canvas IS transparent and the clipping region prevent it to be painted white with background white.

You should give a check to fabricJS code there is no much documentation on how the render loop works.

**Comment by monis01** [comment]
Appreciated :+1: 
Thanks
