### ISSUE TITLE
The enableRetinaScaling value is true, the width of the canvas over 1000px, rotating or moving is too laggy

### ISSUE THREAD

**Issue by bosmo** [fabricjs/fabric.js#4939]
The enableRetinaScaling value is true, the width of the canvas over 1000px, rotating or moving is too laggy

**Comment by bosmo** [comment]
@asturur 
I use Apple Computer MacOS operating system. Thank you.

**Comment by bosmo** [comment]
If enableRetinaScaling is configured as false, it will not be carton, but the content will be fuzzy.
@asturur

**Comment by asturur** [comment]
what cpu?

**Comment by bosmo** [comment]
Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz

**Comment by bosmo** [comment]
The larger the width is, the more time it takes to move or zoom.

**Comment by asturur** [comment]
of course the more the pixels the more work to do. Are u using setZoom to zoom?

There is nothing to fix or inprove for now, you are maybe writing unoptimal code, but since there is no jsfiddle, there is little to do.

**Comment by bosmo** [comment]
All right, thank you.
