### ISSUE TITLE
fabric.text doesn't display

### ISSUE THREAD

**Issue by Ajirogg** [fabricjs/fabric.js#4940]
Hello,
I have to use fabric.Text to display some informations in a group but when I load the web page (on Chrome, Firefox or Internet Explorer) this text isn't display if its length is smaller than 7 caracters.
And when I try my code in jsfiddle it works

ind.text = new fabric.Text(ind.nom + ' ' + ind.prenom +'\nN: ' + ind.dateNaissance, {left : ind.rect.left + 5, top : basFormetxt(ind) + 5, hasControls : false, fontSize: 15});

Thanks for your help

**Comment by asturur** [comment]
This issue will be closed if a failing fiddle  won't be provided.

**Comment by Ajirogg** [comment]
This is the fiddle but it doesn't show what append in a browser
https://jsfiddle.net/jq7s5f4k/1/

**Comment by asturur** [comment]
the fiddle looks like is working good
