### ISSUE TITLE
Blurred image used as a fill pattern

### ISSUE THREAD

**Issue by redlive** [fabricjs/fabric.js#4941]
## Version
2.2.3

## Test Case
http://jsfiddle.net/redlive/y03skqcc/

## Steps to reproduce
Run fiddle code and observe the differences.

## Expected Behavior
A pattern used as a background needs to have a better quality.

## Actual Behavior
A pattern used as a background is blurry.

**Comment by asturur** [comment]
i ll try to understand what is the problem, i m a bit behind with the whole issues

**Comment by redlive** [comment]
@asturur Any idea when you'll have time to look into it?

**Comment by asturur** [comment]
http://jsfiddle.net/y03skqcc/7/

This is a simplifed version of the fiddle.
In this case the image itself is acting as a pattern, i m trying to understand why your canvas is  blurried, but i think that picture is not the best example.

I would say is again the rect stroke maybe?

Do you have a picture like the one with the air baloon so we can test it?

**Comment by redlive** [comment]
I've updated the image in the fiddle above.

**Comment by asturur** [comment]
well is ti blurred? to me looks a 1:1 match, am i wrong?

**Comment by asturur** [comment]
i still.think is just the border of the rect, lets redo it from static canvas and check

**Comment by asturur** [comment]
@redlive Do you have the static canvas version of the fiddle somewhere? i cannot find it

**Comment by redlive** [comment]
@asturur thank you for taking this seriously 👍 
I've made a new one based on static canvas.
http://jsfiddle.net/redlive/xda3rzku/

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/40778059-20974d40-64d0-11e8-99c5-43343bb47496.png)

this is the default fiddle

![image](https://user-images.githubusercontent.com/1194048/40778089-3bd48636-64d0-11e8-9eca-aee76527ae73.png)

this is the fiddle removing the strokeWidth from the rect, i see that at point it becomes sharp.

Having a default strokeWIdth of 1 will give you blurriness on images

**Comment by asturur** [comment]
solution is either a stroke multiple of 2 or blurriness

**Comment by aramir** [comment]
So - just for me to understand - you **can't** have an element with a simple border with a width of "1" (which is one of the most common cases) without having the element's image blurred?

Is that like that by design and will never be fixed or am I not reading the comments above correctly?

**Comment by asturur** [comment]
well you can have a stroke of 1 and postion the rect at 0.5 left and top, but it will eventually go on other coordinates amd ve blurred. the pattern itself is not blurred, but a stroke of 1 means 0.5 pixel of offset that blur everything. why a stroke of 1 should be more common of a stroke of 2 is just a matter of settings.

Also you can try stroke 2 and paintFirst stroke, so that the stroke is under the fill and you see just half of it, and will look like 1

**Comment by klaivs** [comment]
I was facing similar issue, but the strokeWidth fix did not fix the issue - the image was still blurred!
Probably because I needed to scale the image to a certain size before adding to StaticCanvas and making as a Pattern. 

The fix in my case was not to scale the image but apply scaling transformation on a pattern object instead. 
`pattern.patternTransform = [obj.scaleX, 0, 0, obj.scaleY, 0, 0];`

**Comment by hoomanaskari** [comment]
in my case I ended up using `pattern.patternTransform = [obj.scaleX, 0, 0, obj.scaleY, 0, 0]` to prevent scaling the image itself, the image quality got better, but edges were blurry, so on top of that I also added 4 pixels to width and height of the image and reduced 2 pixels from left and top of the image, I lose 2 pixels around the image but the edges are now sharp.

**Comment by youdream2** [comment]
I also encountered the same problem. I tried the above methods but failed to solve it. Is there any other way to solve it? Paid solution, I am willing to pay 500 yuan

**Comment by youdream2** [comment]
> I also encountered the same problem. I tried the above methods but failed to solve it. Is there any other way to solve it? Paid solution, I am willing to pay 500 yuan

I also encountered the same problem. I tried the above methods but failed to solve it. Is there any other way to solve it? Paid solution, I am willing to pay 500 yuan

> in my case I ended up using `pattern.patternTransform = [obj.scaleX, 0, 0, obj.scaleY, 0, 0]` to prevent scaling the image itself, the image quality got better, but edges were blurry, so on top of that I also added 4 pixels to width and height of the image and reduced 2 pixels from left and top of the image, I lose 2 pixels around the image but the edges are now sharp.

I also encountered the same problem. I tried the above methods but failed to solve it. Is there any other way to solve it? Paid solution, I am willing to pay 500 yuan

**Comment by youdream2** [comment]
> ![image](https://user-images.githubusercontent.com/1194048/40778059-20974d40-64d0-11e8-99c5-43343bb47496.png)
> 
> this is the default fiddle
> 
> ![image](https://user-images.githubusercontent.com/1194048/40778089-3bd48636-64d0-11e8-9eca-aee76527ae73.png)
> 
> this is the fiddle removing the strokeWidth from the rect, i see that at point it becomes sharp.
> 
> Having a default strokeWIdth of 1 will give you blurriness on images
I also encountered the same problem. I tried the above methods but failed to solve it. Is there any other way to solve it? Paid solution, I am willing to pay 500 yuan
