### ISSUE TITLE
How do deal with "repeat-x" to don't remain a blank zone?

### ISSUE THREAD

**Issue by violin84** [fabricjs/fabric.js#4942]
## Version
2.2.3

I want to repeat the image in x direction then I use "repeat-x", but if the image's height is less then the rect, it remain a blank zone which cover the canvas. The code as follow:

var canvas = new fabric.Canvas('c', {
        backgroundColor: 'rgb(200,200,200)'
    });

    var shape = new fabric.Rect({
        width: 800,
        height: 450
    });

    fabric.util.loadImage('assets/potato.jpg', function(img) {

        shape.set('fill', new fabric.Pattern({
            source: img,
            repeat: 'repeat-x'
        }));
        canvas.add(shape);
    });

I don't want the blank zone, I just want to show the canvas backgroundColor. How to make it?
![fabric](https://user-images.githubusercontent.com/26641545/39511515-490aae32-4e20-11e8-9126-906004a181e9.png)

**Comment by asturur** [comment]
This requires a different pattern api that we do not have right now. You should use custom patterns with a canvas but those are hardly serializable.
