### ISSUE TITLE
fabric group让text字体变形

### ISSUE THREAD

**Issue by walidream** [fabricjs/fabric.js#4943]
## Version
2.2.3

## Test Case
https://jsfiddle.net/waliblog/hbxzdmpc/

## Steps to reproduce
1.拖拽group Y轴时,text文本的自己会变形。有什么方能能不让字体变形。

**Comment by asturur** [comment]
I m sorry i speak only english and italian, and we prefer keep this place in english.
Can you translate?

**Comment by slahser1992** [comment]
@asturur  he said when he drag the Y-axis to change the height of the red rectangle, the fontsize is changed too.

**Comment by asturur** [comment]
oh i understand now looking at the fiddle.
This requires custom code to solve, nothing hard, but fits more in stackoverflow.com, where you will probably get an answer before i get there.

Can we move that discussion there?

**Comment by walidream** [comment]
@slahser1992 谢谢

**Comment by walidream** [comment]
@asturur 非常感谢您的回答，很高兴能和你一起讨论这个 问题。

**Comment by durga598** [comment]
Don't group text and rect object. Make text dependable to rect. Check this [fiddle](https://jsfiddle.net/hbxzdmpc/1/)

**Comment by asturur** [comment]
There is also a setOnGroup callback that can be used to restore text scaling, i ll try to make an example

**Comment by laoruiwen** [comment]
兄弟 同道中人啊T_T

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/71313965-009d3b80-2441-11ea-91e8-5847809db89b.png)

How can i help not speaking chinese? This is what google translate offers me

**Comment by Lin-Min** [comment]
How can Rect and Text be combined into a group so that the text content does not deform when the group shape is changed? Using version 6.5.1, my code is as follows：
`
      const textbox = new fabric.Textbox('GZWC-B-23F-B-006', {
        width:22,
        fontSize: 4,
        lineHeight:1,
        originX: 'center',
        originY: 'center',
        splitByGrapheme: true, // 启用自动换行
      })

      const rect = new fabric.Rect({
        width: 22,
        height: 30,
        opacity:.8,
        originX: 'center',
        originY: 'center',
        fill:SPACE_TYPE_COLOR[type],
      })
      
      const group = new fabric.Group([rect, textbox])

      canvas.add(group);
      canvas.requestRenderAll();
`

**Comment by laoruiwen** [comment]
您好!您的邮件我已收到,感谢您的来信,我会尽快予以您回复,谢谢!~~

**Comment by Lin-Min** [comment]
> 还有一个 setOnGroup 回调可用于恢复文本缩放，我将尝试举一个例子

Is it convenient to provide an example?

**Comment by asturur** [comment]
@Lin-Min 3 posts with the same question in less than one hour is not the way to use an open source repo

**Comment by Lin-Min** [comment]
> @Lin-Min不到一小时内就出现 3 篇关于相同问题的帖子，这不是使用开源存储库的方式

I'm sorry. I didn't know where to send it

**Comment by Lin-Min** [comment]
> @Lin-Min不到一小时内就出现 3 篇关于相同问题的帖子，这不是使用开源仓库的方式

I can delete other posts if I can
