### ISSUE TITLE
Add a method to detect overlapping between segments, differently from intersection

### ISSUE THREAD

**Issue by pstuermlinger** [fabricjs/fabric.js#4944]
Hello,
if you place 2 objects next to each other without a visible gap, the intersection test always returns true even though it shouldn't.
See this fiddle: https://jsfiddle.net/knuj5b23/5/

Is this is a bug or do I miss something here?

Tested with version 2.2.3.

**Comment by haggins** [comment]
Posted a workaround for rects at SO: https://stackoverflow.com/a/50199339/1295856

**Comment by asturur** [comment]
The answer you got on stackoverflow from me and Dourga are indeed correct.
The intersection is happening for valid reasons.

There could be an option maybe to avoid coincidence as intersection, but that would have extra side effects

**Comment by ShaMan123** [comment]
As mentioned in the SO ticket you can check the intersection's points (see #8121) and decide what to do from there
