### ISSUE TITLE
Shadow on circle disappear when include in group

### ISSUE THREAD

**Issue by Ajirogg** [fabricjs/fabric.js#4947]
Hello,

I have to add a shadow to a circle which is a part of a target.
But when i make a group with the two circles the shadow disappear.

And this is the failing fiddle this time :
http://jsfiddle.net/9WWqG/1602/

I actually work with the version: "2.2.3"

**Comment by durga598** [comment]
This was working with version "1.5.0" [jsfiddle](http://jsfiddle.net/9WWqG/1603/)

**Comment by Ajirogg** [comment]
I know but I have to work with the latest version and on this version that didn't work

**Comment by asturur** [comment]
Please have a look at docs

http://fabricjs.com/docs/fabric.Shadow.html#affectStroke
