### ISSUE TITLE
fix for stateful mixin method isEqual which fails hard on array value compared with null.

### ISSUE THREAD

**Issue by keyurpatel** [fabricjs/fabric.js#4950]
## Version
2.2.3

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Steps to reproduce
_Description_
stateful mixin method `isEqual` throw an exception when it tries to compare an array value with null.

Generally when we use stroke
1. add an object
2. apply stroke from line stroke to dashed stroke.

here when the state has changed for an object it verifies using `isEqual` mixin method and returns a boolean value. But while checking it fails where original array value is [4,1] and the current value is null and not an array.

## Expected Behavior
it should return false

## Actual Behavior
currently, throw an exception in the console.

**Error stack reference**
<img width="543" alt="screen shot 2018-05-04 at 3 58 00 pm" src="https://user-images.githubusercontent.com/2897751/39649501-ff3612fc-4fb3-11e8-8acd-91ab0f8f6dff.png">

**Comment by asturur** [comment]
this has been fixed right?
