### ISSUE TITLE
fabric.Image.filters.Brightness 2.x branch not working.!

### ISSUE THREAD

**Issue by androidsystest001** [fabricjs/fabric.js#4952]
## Version
2.2.3

## Test Case
http://jsfiddle.net/Da7SP/1634/

## Steps to reproduce
// Add brightness filter
oImg.filters.push(new fabric.Image.filters.Brightness({
     brightness: 100
  }));
// Apply
oImg.applyFilters();

## Expected Behavior
Working like 1.x branch
https://jsfiddle.net/b50d9kt2/4/

## Actual Behavior
oImg display "white screen"

P/s: brightness filter on homePage: http://fabricjs.com/image-filters not working too :(
I'm testing on Lubuntu 17.10, Firefox Quantum 59.0.2 (64-bit) / Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by asturur** [comment]
http://fabricjs.com/fabric-filters

please read this documentation for moving from v1 to v2 with filters
