### ISSUE TITLE
findTarget sometimes fails on paths with objectCaching enabled

### ISSUE THREAD

**Issue by AndrewJDR** [fabricjs/fabric.js#4953]
## Version
2.2.3

## Test Case
http://jsfiddle.net/stq8yjLb/8/

## Steps to reproduce
Move the mouse over the black line in the canvas. Do this repeatedly.

## Expected Behavior
Every time your cursor is on top of the line (path), the hand cursor should show up and the console.log statement should be printed.

## Actual Behavior
The hand cursor and console.log() either:
a) never shows up
b) shows up one time, then never again after that.

Please see video if more info is needed:  https://youtu.be/zfWPGTwnGKg

## Other Notes
Works as expected with object caching disabled -- seems like a bug in object caching?

**Comment by AndrewJDR** [comment]
Ah, I've identified that it is very picky about different scaleX/scaleY values. I have explained it more in this fiddle:
http://jsfiddle.net/stq8yjLb/11/

I'll also paste the notes below:
```
// The scaleX / scaleY value of 1.19 is seemingly not handled well by the object caching.
// If we change them to something like, 0.6, everything is fine:
nonWorkingCanvas = nonWorkingCanvas.replace('scaleX":1.19', 'scaleX":0.6'); // This works now!
nonWorkingCanvas = nonWorkingCanvas.replace('scaleY":1.19', 'scaleY":0.6'); // This works now!
// (Comment out the above lines and it won't work anymore...)

// I also experimented with other scaleX/scaleY values here, such as 1.0, but that also did not work.
//nonWorkingCanvas = nonWorkingCanvas.replace('scaleX":1.19', 'scaleX":1.0'); // Still doesn't work!
//nonWorkingCanvas = nonWorkingCanvas.replace('scaleY":1.19', 'scaleY":1.0'); // Still doesn't work!
```

So it seems like there's an object caching bug related to scaling values?

**Comment by AndrewJDR** [comment]
(Tried different noScaleCache values, didn't seem to make a difference)

**Comment by AndrewJDR** [comment]
Seeing if I can fix this now. I just tried setting statefullCache differently on the object, made no difference.
I'll start looking at the scale matrix transformation now (_calcDimensionsTransformMatrix) to see if something is going wrong in there.

**Comment by asturur** [comment]
256x256 is the minimum size after which chrome trigger the hw acceleration for 2d canvases, using smaller canvases often produce slower speeds when you have many objects.

I would not be surprised if there is some transparency check that is not working in this case, but to be honest the transparency check should be improved to just check the canvas itself, while as of now is repainting the cache somewhere else.

Matrix code and dimension code for objects should be good.

**Comment by asturur** [comment]
For me it works good most of the time, can you give me a fiddle that works 100% wrong?
Also consider i m on a retina screen, so i get double your pixels and cache size, you should put in the canvas the option `enableRetinaScaling: false`

**Comment by AndrewJDR** [comment]
> For me it works good most of the time, can you give me a fiddle that works 100% wrong?
Also consider i m on a retina screen, so i get double your pixels and cache size, you should put in the canvas the option enableRetinaScaling: false

Can you link me the url to the exact fiddle you're testing with? I've posted many fiddles, several of which intentionally are supposed to work, so I don't want there to be a confusion with that.

**Comment by AndrewJDR** [comment]
@asturur Okay I have an interesting update:
For this fiddle: http://jsfiddle.net/stq8yjLb/16/
Chrome 64.0.3282.140 hw accelerated canvas enabled - doesn't work (100% of the time)
Chrome 64.0.3282.140 hw accelerated canvas disabled - works fine all the time
Chrome Canary 68.0.3409.2 - Works fine all the time (hw enabled or not)
Firefox 57.0 - Works fine all the time
I don't have webkit here to test with. What's your result in Safari?

*shrug* So I guess I hit another browser bug in chrome? I'm super frustrated at this point with browsers :P

**Comment by asturur** [comment]
chrome 64 was broken and hasn't be fixed.
Some canvases were loosing the transform in painting and this has been addressed in chrome 65, so chrome 64 is the only one broken.

**Comment by asturur** [comment]
chrome 64 was badly broken and all canvas app that use transformations have been broken till a fix has been released ( chrome 65 )

**Comment by AndrewJDR** [comment]
@asturur Good to know. Bad luck for me and browser bugs these last couple of days :) Thanks.

Also, I will think about this optimization you mentioned:
> but to be honest the transparency check should be improved to just check the canvas itself, while as of now is repainting the cache somewhere else.

**Comment by asturur** [comment]
yes is easier to know with the object props zoomX and zoomY what is the current level of zoom of the object, consider the relative position of the mouse over the object, and sample the pixel of the cache canvas, skipping a painting operation. This require some forking in the isTargetTransparent code, but should be the default code since everything is most of the time cached.

**Comment by AndrewJDR** [comment]
@asturur I can submit a PR later today, but anything seem totally wrong to you about this modified isTargetTransparent? (the new code is basically just the if part of the if/else). It works so far in my testing. I don't exactly understand the purpose of the boolean argument to isCacheDirty(), and I'm not sure if there's anything else I should be doing to check for cache dirtiness etc.
```
isTargetTransparent: function(target, x, y) {
    var ctx = this.contextCache, originalColor = target.selectionBackgroundColor, v = this.viewportTransform;
    var isTransparent;
    if (target.shouldCache && target._cacheCanvas && !target.isCacheDirty())
    {
        var center = target.getCenterPoint(), curRelTargetX = x - center.x, curRelTargetY = y - center.y;
        curRelTargetX = (target._cacheCanvas.width/2) + (curRelTargetX / target.zoomX);
        curRelTargetY = (target._cacheCanvas.height/2) + (curRelTargetY / target.zoomY);
        isTransparent = fabric.util.isTransparent(target._cacheContext, curRelTargetX, curRelTargetY, this.targetFindTolerance);
    }
    else
    {
        target.selectionBackgroundColor = "";
        this.clearContext(ctx);
        ctx.save();
        ctx.transform(v[0], v[1], v[2], v[3], v[4], v[5]);
        target.render(ctx);
        ctx.restore();
        target === this._activeObject && target._renderControls(ctx, {
            hasBorders: false,
            transparentCorners: false
        }, {
            hasBorders: false
        });
        target.selectionBackgroundColor = originalColor;
        isTransparent = fabric.util.isTransparent(ctx, x, y, this.targetFindTolerance);
    }
    return isTransparent;
},
```

**Comment by asturur** [comment]
i have no idea what you changed. opening a PR stating what are you changing and why, is good to start a more detailed discussion. Not every code gets merged for various reason, but trying, unless it takes costs you too much, is very welcome.
