### ISSUE TITLE
Text Warp Feature 

### ISSUE THREAD

**Issue by Sillergeoduck** [fabricjs/fabric.js#4956]
## Version
2.2.3

## Test Case
http://jsfiddle.net/Da7SP/1636/
## Steps to reproduce
I am not sure if this is the right place to ask , but i am posting it please excuse me for the indirect approach.... I have implemented Text warp feature using vanilla Javascript and i was hoping if you this feature can be added in fabric JS, 
I am attaching the fiddle in which i have created a path and updating the path so that way the text warp is applied. but i was hoping if some one help me to implement the same using Fabricjs, it would be of a great help and once again my sincere apologies for posting this here.. not sure if this is as issue again.

**Comment by asturur** [comment]
So this is not a text warp feature, is more a path warp feature.
Your code does not need to be made in fabricJS, what you need is more to embed it in your application.

If you take a standard fabric.Path, you can do this:

const input = fabric.Path.toObject()
.... use code warp to warp  input.d ...
.... get output.d .....
input.d = output.d
fabric.Path.fromObject(input, (newPath) => {
... remove old path from canvas
... add new newPath 
});

**Comment by Sillergeoduck** [comment]
Thanks Andrea Bogazzi for the response and i appreciate a lot. so what i was trying to achieve was to render a svg that had patheffect , which actually changes the text style as shown in the below image. 
But when i tried since fabric does not account for the path effect , the text looses its path and renders as normal text as show in the fiddle - http://jsfiddle.net/Da7SP/1637/
<img width="831" alt="screen shot 2018-05-08 at 10 51 05 pm" src="https://user-images.githubusercontent.com/6580027/39772253-6095a84e-5312-11e8-9f16-762750869b62.png">
Any thoughts or suggestions you have about this.

Also i had another question , lets say i have a svg that is either a circle or a football shape or any random shapes SVG, is there a way that i can mask SVG into the canvas , so that shape renders the canvas template and what ever that overflows out of it gets blurred.

**Comment by asturur** [comment]
so let's talk about one thing at time.
there is missing support for path effects.

Can you find them on w3c and link the spec here?

**Comment by Sillergeoduck** [comment]
please find the below w3c link for the SVG <path> - https://www.w3schools.com/.

**Comment by asturur** [comment]
w3schools is not a valid source of informations for me, also the link bring to the homepage and not to the specific functionality, please search here 

https://www.w3.org/TR/SVG12/

w3 org contains the specs of html, svg and other things. I use it as reference.

**Comment by asturur** [comment]
I used 20 minutes, it looks like path-effect is a inkscape proprietary attribute and so out of scope for us.
You can anyway implement it in the way i suggested.
For the clipPath discussion, there is ongoing work (going slow) and will be soon possible, provided the SVG uses the standard clipPath.
https://github.com/fabricjs/api-discussion/issues/1

**Comment by Sillergeoduck** [comment]
Awesome.... thanks a lot Andrea Bogazzi.... you guys are doing amazing job and this framework has come very handy and helpful for me. A big Kudos to you and your team....

**Comment by bitttttten** [comment]
@Sillergeoduck Do you have a unminified version of your text path code? I can integrate it into fabricjs.

I see in the code you have some classes for Point2d and Rects and so on. I see that in your demo, that `Rise` isn't working although I fixed this too.

Happy to collab if you like!

**Comment by bitttttten** [comment]
> So this is not a text warp feature, is more a path warp feature. Your code does not need to be made in fabricJS, what you need is more to embed it in your application.
> 
> If you take a standard fabric.Path, you can do this:
> 
> const input = fabric.Path.toObject() .... use code warp to warp input.d ... .... get output.d ..... input.d = output.d fabric.Path.fromObject(input, (newPath) => { ... remove old path from canvas ... add new newPath });

@asturur If I understand, fabricjs does not have a way to go from text, to path, which is what @Sillergeoduck 's code needs. So if you write some text, and want to do some kind of path warp on it, there is a missing step where you need to convert your text into a path.. right? I guess you are saying that this is out of scope for fabricjs.

**Comment by asturur** [comment]
Fabric does not have a way to go from Text to Path but with opentype.js is very simple to do so.

**Comment by asturur** [comment]
You need to load the fonts for fabric anyway to render properly, but in general yes, if you want to create a text object like a path, you load the font, you convert a text string with opentype, then you can paint it as a path in fabricJS.
Is not editable at that point, is just a path
