### ISSUE TITLE
Generic font families no longer supported

### ISSUE THREAD

**Issue by FelixHenninger** [fabricjs/fabric.js#4957]
Thanks a lot for putting together this library, it's super-useful! I've noticed a recent change in behavior, something that used to work but doesn't any more, namely assigning generic `fontFamilies` to text objects. I looked into the library, but haven't been able to figure out why this is the case. Any help would be much appreciated!

## Version
2.2.3

## Test Case
https://jsfiddle.net/apnqhosf/4/

Please use the drop-down menu on the right to switch between different fonts. You'll notice that some work (Times and Arial, provided they are available on your machine) while others (sans-serif and monospace) don't.

## Steps to reproduce
* Change a text object's `fontFamily` property to a known font, e.g. `Times New Roman` or `Arial`
* Change the value to a generic font, such as `sans-serif` or `monospace`

## Expected Behavior
The display is updated for both types of fonts.

## Actual Behavior
The font family is only changed when a specific font is selected (by name, as opposed to a generic value).

**Comment by asturur** [comment]
I have no idea what is the fallback font for monospace, to me courier works fine.
Can it be because fonts families are now quoted in the code?

with 1.7.x it indeed works

**Comment by asturur** [comment]
yeah that is the bug! no quotes for those

**Comment by FelixHenninger** [comment]
Hej @asturur, 

I'm sorry I missed your response! Just wanted to say a big thanks for fixing this, and for your incredible work on maintaining the `fabric.js` library. Can I get you a glass or cup of your preferred beverage somehow, or do you have a patreon link? ;-)

All the best, and thanks again! -Felix
