### ISSUE TITLE
Font kerning in IE & Edge on canvas

### ISSUE THREAD

**Issue by kmarcisz** [fabricjs/fabric.js#4960]
## Version
2.2.4

## Test Case
https://jsfiddle.net/8u6xznp1/

## Steps to reproduce
Add text element with text such as *WAVA* or any other that would show kerning. Run the code in IE, Edge and Chrome.
## Expected Behavior
Fonts rendered look the same.
## Actual Behavior
Letters in IE and Edge are spaced too far apart.
Chrome:
![chrome](https://user-images.githubusercontent.com/664346/39777624-a9f764d0-52c9-11e8-8f55-b9a6b2cb0e8d.png)
IE 11:
![ie11](https://user-images.githubusercontent.com/664346/39777629-af2f633a-52c9-11e8-9c25-10dbeb89965a.png)
Edge 15:
![edge](https://user-images.githubusercontent.com/664346/39777644-b6681fac-52c9-11e8-9586-27d0c0b7aab0.png)

**Comment by asturur** [comment]
i hate microsoft and all their browsers.

**Comment by GrayTechnical** [comment]
I am seeing the same issue myself with Edge - although I wouldn't consider this an end of the world issue for us (Edge is < 5% of our traffic).  
My text in the example is standard SVG <text> tags, styled with web/woff fonts via css.  Fabric DOES get the font face correct - just not the kerning.
 
![fabric rendering errors in edge](https://user-images.githubusercontent.com/30353294/39839045-f723bfa8-53a8-11e8-9441-ff4da5bc2cdf.png)

**Comment by asturur** [comment]
i would have sweared that this was working before. But i  did a fiddle on jsfiddle and it is not working at all with plainJS:

https://jsfiddle.net/qxfy1em8/1/

Now i remember i had to go around issues of font measurement in ie11/edge.
Someone with windows 7 can try this fiddle and take a screenshot on ie11 or ie10?

**Comment by asturur** [comment]
https://jsfiddle.net/qxfy1em8/2/

they are not kerning with normal P too.

**Comment by asturur** [comment]
@GrayTechnical may be non fixable as far as i understand, ie11 is simply not kerning ( even if i thought we were doing it at some point ) If you want to recover your bounty feel free to do so.

**Comment by asturur** [comment]
@kmarcisz  the fonts kerns differnetly from chrome and edge also if you render them in P or SPAN element is not just a canvas problem

**Comment by GrayTechnical** [comment]
@asturur IE/Edge will kern just fine - it just doesn't honor the fonts kerning tables by DEFAULT.   I ran into this with our app some time ago. Adding:
`font-feature-settings: "kern" 1;`
... is required to tell IE to use the font's kerning tables.   

If you add that CSS property to your fiddle above - you'll see that the <p> text kerns properly...   This also applies to SVG text - I hope this can lead you down the right road for canvas text.   
https://drafts.csswg.org/css-fonts-3/#propdef-font-feature-settings

**Comment by GrayTechnical** [comment]
note that the Working Group recommended `font-kerning: normal;` does NOT seem to work.  Since when has IE/Edge ever strictly adhered to the recommended standard.  LOL.   

I stumbled across this some time ago trying to get my svg text to look correct in IE / Edge.  It was the only thing that worked.

**Comment by asturur** [comment]
https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/34427839-canvas-2d-font-kerning-support

It does not work for canvas, at least it looks not to me.

If someone wants to upvote the feature request, is there.
