### ISSUE TITLE
Dynamic Polygon Bounding Box

### ISSUE THREAD

**Issue by IanBurgan** [fabricjs/fabric.js#4961]
## Version
2.2.4

## Test Case
https://jsfiddle.net/rhvLvqxL/1/

## Steps to reproduce
Add a point to a polygon that isn't in the bounding box.
## Expected Behavior
The bounding box can be forced to update in some way.
## Actual Behavior
The bounding box does not update.
However, getBoundingRect() seems to be accurate if it is relevant.

**Comment by asturur** [comment]
Would be nice to add the new methods to update the shapes, probably something i ll do soon, since other major reworks is stopped because it requires more time than i have.

I move this to API-DISCUSSION, please let's move the discussion there.

**Comment by ShaMan123** [comment]
If relevant let's try and fix it within the scope of #7478

**Comment by asturur** [comment]
this is more relevant to the work you did for the path, and that i have to complete yet.

**Comment by ShaMan123** [comment]
Is there some to-do/feature list.
I want to close issues. 
Many things are related.

**Comment by asturur** [comment]
If you want to close issues, there are small bugs open, labeled as fix-next
