### ISSUE TITLE
SVG import does not honor PreserveAspectRatio attribute of nested SVGs

### ISSUE THREAD

**Issue by GrayTechnical** [fabricjs/fabric.js#4962]
## Version
2.2.4

## Test Case
Simple test case using the W3 example SVG for PreserveAspectRatio:
https://jsfiddle.net/tonygray/ht6v7so0/

## Steps to reproduce
- load SVG with nested SVG's aligned using PreserveAspectRatio attribute via fabric.loadSVGFromString()

## Expected Behavior
- canvas output mirrors the appearance of the SVG, with child SVG's aligned as specified at https://www.w3.org/TR/2003/REC-SVG11-20030114/coords.html#PreserveAspectRatioAttribute

## Actual Behavior
- all child SVG's appear to be anchored at top/left.

We have a graphic designer app that allows you to design graphics for your motocross motorcycle.  I am looking to use fabricJS to enable taking a "screenshot" of the design - so that after it's been made we should have a pretty realistic copy of what the customer saw when designing.

I have a sample of how this looks on our live app at:
https://www.decalmx.com/pages/ds3/index.php?groupID=1&presetID=296
if you scroll down to the bottom - just above the footer there is a camera button to take a screenshot.  

Using this example, this alignment issue greatly affects:
- Race Numbers and any Text Elements - to give the numbers pinstripe and background colors - the same text is simply stacked on top of each other several times with differing stroke colors and widths.  
- "Logo" (child SVG) placement - all are basically aligned top/left instead of honoring the PreserveAspectRatio.
![fabric preserveaspectratio misalignment](https://user-images.githubusercontent.com/30353294/39873574-53cbd12e-5439-11e8-85bf-e56bf014a89d.png)

This is the best library I can find for doing this so far - none of the others that I've tried get the text / fonts correct.   My company is willing to entertain funding some development to get this working correctly - as this is a huge tool I need to get in the hands of our customer service / sales reps.

**Comment by asturur** [comment]
I tried a basic implementation of the aspectRatio, i agree is hard to do by spec.
Can you share the motorbike SVG? would make everything simpler.

So i really would like to fix those things, you can post a bounty over it, it can speed up but i can't assure it.

**Comment by GrayTechnical** [comment]
Attached is a zip file with a copy of the test bike svg (has to put in zip since the upload widget here does not allow svg raw).   Note that this is the same svg as generated from the url mentioned in the original post, found inside the "#designStudioSVG" container.

[testbike.zip](https://github.com/fabricjs/fabric.js/files/1992783/testbike.zip)

The SVG text in the attached svg does not reflect the proper font face (fish out of water without the support CSS and font files) - but the stacked text layers still align as intended, as do the logos on the rear fender.

As far as the spec goes - in our case 99% of the time we are using either "xMidYMid meet" or "none".  I read in your other posts about the difficulties of slice - we don't use that anywhere.   We primarily stretch to fit the container ("none") or center in the container, maintaining aspect ("xMidYMid meet").

**Comment by asturur** [comment]
I appreciate you putting a bounty before even checking if the fix would happen automagically fast.

**Comment by GrayTechnical** [comment]
@asturur - we run in "get er done" mode basically 24/7.   :-)

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/40300205-db67c9c8-5ce8-11e8-856a-65d5e9761075.png)

ok this looks like it start working.

But in the svg you gave me i cannot see text pieces. Are text pieces there?

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/40300647-2362a35a-5cea-11e8-8e9c-fbaee8182a6f.png)

my fault i wrote bugged code and the text disappeared.
I m looking in text positioning now!

Hope we can fix this.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/40301645-ff17dd46-5cec-11e8-9180-ac68e6105334.png)

something is off but getting better, i wish i had more text + stroke svg example to understand.

**Comment by asturur** [comment]
Anyway svg has so many features and possibilities that is not suggested for production when svg comes from uncontrolled sources.

So please do not expect to pick any svg from the internet and be able to import it.
If your customer can draw svg and is ok with avoiding some features, then ok.

**Comment by asturur** [comment]
Here PR is linked to the issue now.

**Comment by GrayTechnical** [comment]
@asturur I guess I'm not sure I'm pulling the correct code - /dist/fabric.js in the "try-preserve" branch should have your changes in it, correct(?)  When I try to compare that source to the changes noted in the pull request - I don't believe they are there...  My apologies for not possibly fully understanding the github alternate branches...

**Comment by asturur** [comment]
no it has not, you have to clone the branch and build it. 

or use this commit here: https://github.com/fabricjs/fabric.js/pull/4984/commits/5a2609866014484e83b7c2713e9cba8d1a56068c  where i accidentally pushed up the built library.

dist gets updated on releases only

**Comment by GrayTechnical** [comment]
We are VERY close!
- It appears the logos are now perfectly aligned.
- The text elements now "stack" correctly - only issue is that the text elements appear to be shifted down instead of centered in their bounding box vertically.   They are centered side to side - but not top to bottom.  If I'm following your code correctly - looks like you're using a static multiplier in there to figure the top of  the text?
![tempsnip](https://user-images.githubusercontent.com/30353294/40320410-3b162cd6-5cf1-11e8-9de4-bbc8dd6bb2c2.png)


https://www.decalmx.com/pages/ds3/index.php?groupID=1&presetID=650 to view live (scroll to bottom, click the camera button in lower left above page footer to generate fabric canvas/png).

**Comment by GrayTechnical** [comment]
Indeed - if I alter the 0.18 constant in the text.set asignment to 0.07 - I get perfect alignment on my test case.   I'm assuming that this is bumping up the top to account for the stroke width(?).   I will test across several different bikes and fonts.   This might be enough just adjusting that constant to get us by...

**Comment by asturur** [comment]
i cannot change a constant just like this. I made that constant and it can be wrong, but i think i need to build some svg and test out.

**Comment by GrayTechnical** [comment]
I have not run thru EVERY test case - but I've run thru several dozen - for our crazy use - 0.07 IS the magic number.   ;-)  I've pushed that update to our public test if you want to see it in action...
https://www.decalmx.com/pages/ds3/index.php?groupID=1&presetID=650

**Comment by GrayTechnical** [comment]
So far after changing the constant - I am close enough for our production on all image sets I've tried.   Only issue I still see btw is https://github.com/fabricjs/fabric.js/issues/4960 - but I'm not losing any sleep over it considering that accounts for less than 5% of our traffic.

**Comment by asturur** [comment]
i want to understand the constant, merge it and release 2.3.1  Then check
back ie11. Testing under.ms browser is a pain

**Comment by GrayTechnical** [comment]
I went thru my font management - and adjusted the stroke widths way up then way down - where we are at now with the 0.07 constant seems to work in all situations.   Good Work @asturur !

**Comment by asturur** [comment]
i ll check this costant deeper. maybe is right. but i have to test
with.something that is simple enough

**Comment by GrayTechnical** [comment]
While further testing - the alignment is still OK - but I noticed on A and 4 (with their very pointed inner stroke) is blowing out the top of the letter.   I've checked pretty much all letters and numbers - seems the 4 and the A are the only issues.   Please see attached.

![capture](https://user-images.githubusercontent.com/30353294/40334350-d5303326-5d22-11e8-8e1f-6203756539ea.PNG)

**Comment by asturur** [comment]
Let me check the standard for corners in SVG, that thing should not happen.
Is easily solvable with a fabricJS setting, but it should be automatic from
SVG

2018-05-22 1:16 GMT+02:00 Tony Gray <notifications@github.com>:

**Comment by GrayTechnical** [comment]
Sounds good @asturur - if you can point me to the fabricJS setting - that would be awesome.   Note that this does not happen in the source SVG - only in the fabricJS representation of it...

Thank you again for all of your help by the way.  I am very confident we can get this last glitch figured out - so  I can move forward with the rest of my image capture workflow.  👍

**Comment by asturur** [comment]
i have been doing this:
![image](https://user-images.githubusercontent.com/1194048/40416967-f2aa4a56-5e7e-11e8-98f9-8ced968cefce.png)

to figure out better positioning, i ll try to understand how to place it correctly.
Not having real ascending descending support in canvas, it can be complicated.
I can adjust it on arial but may fail for other fonts, since fabricJS uses something else to position font.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Wikimedia logo" viewBox="0 0 1000 1000" width="1000" height="1000">
<defs>
  <g id="lines" >
    <line x1="-200" y1="0" x2="1100" y2="0" />
    <line x1="-200" y1="100" x2="1100" y2="100" />
    <line x1="-200" y1="200" x2="1100" y2="200" />
    <line x1="-200" y1="300" x2="1100" y2="300" />
    <line x1="-200" y1="400" x2="1100" y2="400" />
    <line x1="-200" y1="500" x2="1100" y2="500" />
    <line x1="-200" y1="600" x2="1100" y2="600" />
    <line x1="-200" y1="700" x2="1100" y2="700" />
    <line x1="-200" y1="800" x2="1100" y2="800" />
    <line x1="-200" y1="900" x2="1100" y2="900" />
    <line x1="-200" y1="1000" x2="1100" y2="1000" />
    <line y1="-200" x1="0" y2="1100" x2="0" />
    <line y1="-200" x1="100" y2="1100" x2="100" />
    <line y1="-200" x1="200" y2="1100" x2="200" />
    <line y1="-200" x1="300" y2="1100" x2="300" />
    <line y1="-200" x1="400" y2="1100" x2="400" />
    <line y1="-200" x1="500" y2="1100" x2="500" />
    <line y1="-200" x1="600" y2="1100" x2="600" />
    <line y1="-200" x1="700" y2="1100" x2="700" />
    <line y1="-200" x1="800" y2="1100" x2="800" />
    <line y1="-200" x1="900" y2="1100" x2="900" />
    <line y1="-200" x1="1000" y2="1100" x2="1000" />
  </g>
  <g id="small-lines" stroke="red" stroke-width="0.1" >
    <use xlink:href="#lines" transform="translate(2,2)" />
    <use xlink:href="#lines" transform="translate(4,4)" />
    <use xlink:href="#lines" transform="translate(6,6)" />
    <use xlink:href="#lines" transform="translate(8,8)" />
  </g>
</defs>

<use xlink:href="#small-lines" />
<use xlink:href="#small-lines" transform="translate(10,10)" />
<use xlink:href="#small-lines" transform="translate(20,20)" />
<use xlink:href="#small-lines" transform="translate(30,30)" />
<use xlink:href="#small-lines" transform="translate(40,40)" />
<use xlink:href="#small-lines" transform="translate(50,50)" />
<use xlink:href="#small-lines" transform="translate(60,60)" />
<use xlink:href="#small-lines" transform="translate(70,70)" />
<use xlink:href="#small-lines" transform="translate(80,80)" />
<use xlink:href="#small-lines" transform="translate(90,90)" />

<use xlink:href="#lines" transform="translate(10,10)" stroke-width="0.25" stroke="lightgreen" />
<use xlink:href="#lines" transform="translate(20,20)" stroke-width="0.25" stroke="lightgreen" />
<use xlink:href="#lines" transform="translate(30,30)" stroke-width="0.25" stroke="lightgreen" />
<use xlink:href="#lines" transform="translate(40,40)" stroke-width="0.25" stroke="lightgreen" />
<use xlink:href="#lines" transform="translate(60,60)" stroke-width="0.25" stroke="lightgreen" />
<use xlink:href="#lines" transform="translate(70,70)" stroke-width="0.25" stroke="lightgreen" />
<use xlink:href="#lines" transform="translate(80,80)" stroke-width="0.25" stroke="lightgreen" />
<use xlink:href="#lines" transform="translate(90,90)" stroke-width="0.25" stroke="lightgreen" />

<use xlink:href="#lines" transform="translate(75,75)" stroke-width="0.5" stroke="gray" />
<use xlink:href="#lines" transform="translate(25,25)" stroke-width="0.5" stroke="gray" />
<use xlink:href="#lines" transform="translate(50,50)" stroke-width="0.5" stroke="gray" />
<use xlink:href="#lines" stroke-width="1" stroke="black" />
<text x="25" y="125" stroke-width="0" font-size="40" >I AM A DEFAULT TEXT</text>
<text x="25" y="225" stroke-width="3" stroke="rgba(0,255,0,0.5)" font-size="40"  paint-order="stroke" >123 no angles</text>
<text x="25" y="325" stroke-width="10" stroke="rgba(255,0,0,0.5)" font-size="40" paint-order="stroke" >123 no angles</text>
</svg>
```

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/40417220-8d5294a0-5e7f-11e8-972f-c61f7ede127b.png)

this is current fabric output and is bad placed ( forget the pixellation since the svg is BIG and i did not tweak the cache size )

**Comment by asturur** [comment]
oh the spike problem is indeed in svg too, so you have to tweak your svg to make it disappear, and if then fabric does not import it correctly there is a problem to fix. the parameter in the text to use is 

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-linejoin

probably you want it round.

**Comment by asturur** [comment]
or the miter limit is not working, unsure but totally a separate issue we can tackle separtely

**Comment by GrayTechnical** [comment]
@asturur - while I understand the spike problem COULD be an issue in the source SVG given the correct parameters and situation (I've spent months learning how to interact with the fonts to get the SVG display correct - including editing the line join parameters) - the spike problem is NOT in the examples given.   

I am working on a fiddle to hopefully more simply demonstrate / replicate the situation I am experiencing here where the SVG and the fabricJS do not match...   ;-)

**Comment by GrayTechnical** [comment]
https://jsfiddle.net/tonygray/pj5apwm6/23/ - here is a revision of the same fiddle with all layers commented out except for the blue layer.   Here it becomes very clear that the browser / raw svg font strokes are interpreted differently than how fabric / browser canvas is interpreting.   

In discussions with my Graphics Dept Head - we recalled that specifying proper start/stop and stroke direction within the font files affected this.  So it appears that that possibly fabric and/or browser canvas is not interpreting the font file's strokes in a uniform way as they do fonts in SVG(?)    That may be a reach - my SVG / Font experience is pretty good - how the browser interprets canvas I am very new at...

**Comment by asturur** [comment]
maybe the miter limit is not imported or we have a wrong default value.
The way in which the blue svg stroke is not a unicorn, is exactly a miter limit.

the more the angle is acute the more the spike would tend to infinity, unless you cut it out.

Now i have to research how to cut that spike with the correct value.

![image](https://user-images.githubusercontent.com/1194048/40473488-9b4ede16-5f3c-11e8-9732-25a8f69147d8.png)
fabric

![image](https://user-images.githubusercontent.com/1194048/40473518-a7c848b2-5f3c-11e8-9921-04f2e14570bc.png)
svg by mdn (i assume correct)

I should handle this in the svg import, but one fabric logic has always been to mirror svg defaults where possible ( reason behind stroke of 1 by default )

This would be a breaking change, but i also think no one likes spikes, and no one will ever complain if they disappear?

**Comment by GrayTechnical** [comment]
strokeMiterLimit = 4 did the trick!   :-) 💯 🥇 

I made the change to my modified 2.3.0 (will be reflected in my fiddles if you clear cache and rerun).   GREAT WORK @asturur !

I'm going to leave this ticket open - not sure if more appropriate to leave open until you patch investigate more and patch or ?

Thank you again sir!

**Comment by asturur** [comment]
i ll add the fixes and merge i hope tomorrow, i ll check also that 0.7 constant and if it fixes all the positions  i ll just take it, i just need a way to verify with the grid.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/40641654-b1d065a6-631a-11e8-939a-4659ba8ecbcb.png)
<img width="1440" alt="screen shot 2018-05-29 at 8 30 21 am" src="https://user-images.githubusercontent.com/1194048/40641659-b7499e3a-631a-11e8-9470-75cadc92953e.png">

**Comment by asturur** [comment]
0.07 looks perfect
i m gonna merge and close this issue

**Comment by asturur** [comment]
Hey does you app / company have a twitter account? i would like to tweet about this nice fix.
Also can i post an svg of those?

**Comment by GrayTechnical** [comment]
@asturur https://twitter.com/DeCalWorks
Thanks again!
