### ISSUE TITLE
Vulnerabilities from npm security audit

### ISSUE THREAD

**Issue by smariel** [fabricjs/fabric.js#4968]
I use the last version of Fabric 1.x.x (currently 1.7.23) with npm.
With npm 5.10.0 I tried the new "audit" feature and find out that Fabric dependancies had 7 vulnerabilities.

[fabric vulnerabilities.txt](https://github.com/fabricjs/fabric.js/files/1997600/fabric.vulnerabilities.txt)

**Comment by asturur** [comment]
those are deps of deos, nothing i can really fix. Maybe when we switch to latest json we can fix it. Browser side nothing is affected
