### ISSUE TITLE
Changing the position of objects in groups

### ISSUE THREAD

**Issue by Harmageddon** [fabricjs/fabric.js#4969]
I found several old, closed issues wrt image positioning inside groups (e.g. #1765, #869), but the problem that images don't seem to respect the group's origin seems to persist for me in the latest Fabric version.

## Version
2.2.4

## Test Case
https://jsfiddle.net/tyzphn1k/2/

## Steps to reproduce
1. Add an image to a group.
2. Try to specify the position of the image relative to the group's top left corner. 

## Expected Behavior
Setting the image position to (0,0) should place the image's top left corner at the top left corner of the group.

## Actual Behavior
The image gets placed at the center of the group.

**Comment by asturur** [comment]
Groups are placed in this way, is not a bug.

**Comment by Harmageddon** [comment]
Sorry, I got confused with my own test case / with what I was trying to show. See the updated test case here: https://jsfiddle.net/tyzphn1k/2/
When the image is added the first time, the position works (i.e., it gets placed at (0,0) calculated from the top left of the group). Later, I try to change the position of the image to (20,20), which should still be calculated from the top left, but gets calculated from the center instead. It seems to me that elements positioned inside a group are internally positioned with respective to the center point, i.e. when I add a rectangle at (0,0) with `addWithUpdate`, its left and top will be (-groupWidth/2) respectively (-groupHeight/2).

So the core point of my problem is not specific for images, but rather for repositioning elements in groups. I'm sorry for the confused first version of my report, will update the title to reflect the real cause.

**Comment by Harmageddon** [comment]
Thank you for your reply! I'm afraid this is no option for my use case. For example, say I'm adding an image to a group and want to set its position inside the group once loaded (which is after the group has been created, because the creation of the group is not possible inside the onload handler if there is more than one image. So I'd have to ungroup all elements, change the position and regroup them again?
As a workaround, I'm going to use a function realigning objects by subtracting the `x` and `y` values of the `group.getCenterPoint()` from the `left` and `top` values of the objects, but I remain with the opinion that this behaviour is a bug.

Nevertheless, I'd like to thank your for this library, that is really useful!

**Comment by asturur** [comment]
well is not a bug in the sense is made like this is not an error. Is bugging you but this does not make it a bug.

What addWithUpdate does is exactly ungrouping everything and regrouping everything, each time you call it.

shouldn't hard reading the transformation tutorial write a function that position the object exactly where you want.
