### ISSUE TITLE
Object Clone - are they linked to original Objects

### ISSUE THREAD

**Issue by byeshkumar** [fabricjs/fabric.js#497]
In the sample the if cloned object's property changes, even the original object's properties changes

 var Aobj = canLayer.getActiveObject(); //canLayer.item(0);
 var vobj = fabric.util.object.clone(Aobj); //Aobj.clone();
 vobj.set('fill', '#fff'); // This changes the color of both the objects

http://jsfiddle.net/YpUgc/7/ 

YESH

**Comment by deepdoon** [comment]
Hi Kangax/Kienz, 

                First of all a fabricjs is very nice library thanks a lot for your efforts. I am stuck in a problem, Can i delink the cloned object so that if i change anything in cloned it won't affect original? Actually i am changing values in objects placed on canvas by cloning and adding them on temp canvas(actual changes takes place in temp canvas, original canvas just have 0 as a text/value) after changing values on clone when i render the original the value are reflected there. It is only happening in case i clone a group. Working fine for individual items. Please help. 

Thanks

**Comment by asturur** [comment]
Can you make a fiddle please?

**Comment by abhi06991** [comment]
I have list of image filters' check boxes through which users can apply different filters for an image. When a user clicks on a particular image in the canvas, I check whether there are any filters applied to that image and update the checkboxes accordingly. Here the problem is when an image is cloned, the image filters applied or removed is shared between the images,so I am not able to correctly update the checkboxes. Anything that can be done to resolve this problem?

**Comment by ehdwns980416** [comment]
@Kienz It works in the latest version(1.7.20). 😭
[JSFiddle](http://jsfiddle.net/JunKim/YpUgc/40/)
Like This:
![image](https://user-images.githubusercontent.com/26425092/37139686-1d7cbde0-22f2-11e8-8875-1b5dc593dea0.png)

**Comment by asturur** [comment]
thanks for the fiddle so we can look at it.

**Comment by asturur** [comment]
your fiddle works good on 1.7.20

**Comment by ehdwns980416** [comment]
Really? It has bug when I run it.
![image](https://user-images.githubusercontent.com/26425092/37501675-c1def24c-2912-11e8-899c-5fdf4bc4c7e5.png)

**Comment by asturur** [comment]
ok maybe describing the bug with words would be helpful.
Also please unlock the adblocker on both jsfiddle and fabricjs.com, looks unfair.

**Comment by ehdwns980416** [comment]
I am using chrome browser. And I was also expecting that problem.
So I tried incognito mode, but it was the same. 😭

**Comment by asturur** [comment]
There is no adblocker in incognito mode.
Can i understand what is the problem? if you are not able to explain, i m not willing to help.

**Comment by vgerte** [comment]
I have fix your jsfiddle. It should work.
 http://jsfiddle.net/gerte/1pcwfgfa/1/
You have chosen white color, it not bug.
