### ISSUE TITLE
Random rendering with 180° rotated setViewportTransform

### ISSUE THREAD

**Issue by belartodmarinus** [fabricjs/fabric.js#4971]
## Version
2.2.4

## Test Case
https://jsfiddle.net/87m5gqqd/

## Steps to reproduce
1. Start fiddle
2. Drag textbox around (especially in the corners)

## Expected Behavior
Text should always be (partly) visible

## Actual Behavior
Text sometimes hides completely, when dragged to another point it reappears.

**Comment by asturur** [comment]
Custom viewport is not supported yet. There is an open request for feature.
Not being supported we can't track bugs
