### ISSUE TITLE
altSelectionKey not working

### ISSUE THREAD

**Issue by scriptspry** [fabricjs/fabric.js#4972]
## Version
2.2.4

## Test Case
http://jsfiddle.net/45m05xyz/1/

## Steps to reproduce
1. Select the blue rectangle
2. Click on the overlapped region of red and blue rectangles with alt key held down

## Expected Behavior

Expect the selection to toggle from blue rectangle to red rectangle.

## Actual Behavior

Selection is unchanged.

---

I noticed that the comment for altSelectionKey says "feature is disabled, feature disabled", but I couldn't find in issues or docs as to why the feature was disabled, and how to get it to work.

**Comment by asturur** [comment]
http://jsfiddle.net/45m05xyz/2/

AltSelectionKey  works only with preserveObjectStacking set to true.
This decision came inspecting what it makes sense from a general point of view, i updated the jsdoc of the property because this was not clear before.

**Comment by scriptspry** [comment]
Is the updated fiddle working for you?

It's still not working here with preserveObjectStacking set to true. I've tried with 3 different keyboards just to be sure it's not working in some of them.

**Comment by asturur** [comment]
let me check again

**Comment by scriptspry** [comment]
Any update on this @asturur ?

**Comment by asturur** [comment]
So the fiddle works fo me. What the key is doing in the fiddle is fo example, once RED is selected, it lets you keep RED selected when you click on on the interesection between BLUE and RED even if RED is behind BLUE.

it does not do more than this.
