### ISSUE TITLE
Nested SVG transform issues.

### ISSUE THREAD

**Issue by sputty01** [fabricjs/fabric.js#4973]
## Version
2.2.4

## Test Case
https://jsfiddle.net/makvexqq/6/

## Steps to reproduce

1. Import an SVG on to the canvas which contains a scale transform nested within a matrix transform.
2. Export the canvas to JSON.
3. Import the JSON back on to canvas.

OR 

1. Import an SVG on to the canvas which contains a scale transform nested within a matrix transform.
2. Export as an SVG.

## Expected Behavior
The canvas should be the same both before and after the JSON export/import.

## Actual Behavior
The elements within the object represents the SVG move slightly.

**Comment by asturur** [comment]
check the docs on fabricjs.com/docs for NUM_FRACTION_DIGITS
