### ISSUE TITLE
Is it possible to set originX and originY to the beginning of a path

### ISSUE THREAD

**Issue by EkaterinaShteyn** [fabricjs/fabric.js#4974]
Hi,

We've been using fabric for our project and we love it! We've been trying to implement curved arrows for a while and we've run into some issues with paths I'm not sure how to resolve.

I've looked in detail at the [demo](http://fabricjs.com/quadratic-curve), but can't figure out how to  make the head, tail and curve point align on the actual path. 

If I make the originX=left and originY=top, then it's almost like fabric draws the curved arrow, calculates the topmost and leftmost point of the bounding box and sets that to be the origin. Calculating positions of the head, tail and curve anchor points becomes really difficult.

If I make the originX=center and originY=center, then calculating positions of the head, tail and curve anchor points is also really difficult. For example, when the curve point is to the left of head and tail, you can no longer reason about the absolute position of head and tail based from the bounding box
![image](https://user-images.githubusercontent.com/3108190/40147948-a5138810-5939-11e8-8ef8-afbefb2c3a91.png)

In addition, it seems that setting strokeWidth makes the path grow down and to the left which changes the bounding box and makes the positioning of tail, head and curve points even more difficult to predict. 
![image](https://user-images.githubusercontent.com/3108190/40148132-80c5a2ee-593a-11e8-914d-4709640add05.png)
![image](https://user-images.githubusercontent.com/3108190/40146336-267ab9ac-5933-11e8-9922-96fab15e2128.png)

My two questions are:

1. Is it possible to set originX, originY to path[0][1] and path[0][2]?

2. Is it possible to make strokeWidth grow from center? 

Please let me know if there is a way to modify the [demo](http://fabricjs.com/quadratic-curve) to make the anchor points to sit on top of the path.

Thank you!
Katya

**Comment by asturur** [comment]
This looks like a solution proposed for a problem, without completely stating the problem.
Are you just trying to guess where exactly is, for example, the point of the triangle and you would like to know where to put top and left in order for the triangle to be exactly on one point?

**Comment by EkaterinaShteyn** [comment]
Hi Andrea, can you make any suggestions how to solve the problem?

Is there is a way to modify the demo to make the anchor points to sit on top of the path? 

Thank you, I really appreciate your help! :)

**Comment by asturur** [comment]
I need to write an example, i tend to prioritize bugs features and docs
rather than direct help request.

I l try to do tomorrow, depending on my workload ( that is not fabric
related )

2018-05-21 20:15 GMT+02:00 EkaterinaShteyn <notifications@github.com>:

**Comment by EkaterinaShteyn** [comment]
Hi Andrea, thank you so much for getting back to me! DId you get a chance to look into how to do this? I really appreciate your effort and time!

I keep trying to figure it out and the math just doesn't seem to work. It would be amazing if you could help :)
