### ISSUE TITLE
How to add border for Group Object

### ISSUE THREAD

**Issue by muxi2015** [fabricjs/fabric.js#4978]
## Version
2.2.4

**Comment by asturur** [comment]
Group is just a container and it does not support stroke or fill.
You have to insert in the group a rect as big as the group.

**Comment by muxi2015** [comment]
Thank you @asturur

**Comment by muxi2015** [comment]
Do you plan to add this feature?

**Comment by asturur** [comment]
i do not think so.
Group is a container.
In We should find  way to make things easier for who wants to add objects
in the group and simulate a border.
I m not sure drawing a border in groups is a good idea

Something should be discussed. What a group does and should do.

I'm pretty much full right now and this is lower priority


2018-05-18 16:03 GMT+02:00 kk <notifications@github.com>:

**Comment by muxi2015** [comment]
@asturur  Thank you for your work

**Comment by milahu** [comment]
```js
// fabricjs group - always show border
fabric.Group.prototype.initialize = (function (initialize) {
    return function () {
        initialize.apply(this, arguments)
        // prepend rect to group objects
        this._objects = [
        new fabric.Rect({
            // position from group center
            left: -0.5*this.width,
            top: -0.5*this.height,
            width: this.width,
            height: this.height,

            stroke: '#00f',
            strokeWidth: 2,
            fill: false,
        })]
        .concat(this._objects)

        // TODO repaint border on group resize event

        // TODO remove border on group destroy
    };
})(fabric.Group.prototype.initialize);
```

**Comment by ShaMan123** [comment]
For debug purposes you can do many things including

```
ctx.save()
group.transform(ctx)
ctx.strokeRect(-group.width/2, -group.height/2, group.width, group.height)
ctx.restore()
```

Or hack into fabric
```
group._renderControls(canvas.getContext())
```


For real usage you could add a rect to your group and resize it using the LayoutManager

**Comment by themallisetty** [comment]
may i know where should we add `group._renderControls(canvas.getContext())`

**Comment by ShaMan123** [comment]
That will not work because renderAll redraws everthing.
Override the camvas drawControls method or something or add a after:render event
