### ISSUE TITLE
Pasted text does not get the applied style

### ISSUE THREAD

**Issue by semiadam** [fabricjs/fabric.js#4981]
By design, my app does not allow rich text. Meaning that, all text styles are applied to the entire text element by applying .set() on the itext object. However, if user copy/paste some text within the itext, the applied style will not be applied to the pasted text, so I ended up having a textbox with different text styles in it (see snapshot and fiddle). 

## Version
2.3.0

## Test Case
http://jsfiddle.net/Da7SP/1647/

## Steps to reproduce
Edit text box. Select a few letters. Hit CTRL+C and CTRL+V to duplicate those letter. Click on button to change the 

## Expected Behavior
The entire  content of textbox must get the applied style.

## Actual Behavior
Pasted letter do not get the applied style.
![image](https://user-images.githubusercontent.com/5418638/40273918-cb445f7c-5b7e-11e8-8310-110b3b4cbee9.png)

**Comment by semireg** [comment]
This worked for me:

`
    document.addEventListener('keydown', this.keyHandler.keydown, false);
`

then...

`
  keydown = (e: any) => {
    fabric.copiedTextStyle = null;
  }
`

**Comment by melchiar** [comment]
I just encountered the same issue with my app since I'm trying to keep the styling uniform within each textbox as well. I ended up just overriding `insertNewStyleBlock` function like so to prevent the creation of style blocks.

`fabric.Textbox.prototype.insertNewStyleBlock = function() {}`

@asturur, would you be okay if I did a PR to add a config option for modifying this behavior as you suggested?

**Comment by asturur** [comment]
i thought we did something like that.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/54864506-942dc880-4d58-11e9-8f7f-c7d20e059ce2.png)

i think we can get away with a boolean disableStyleCopying property on the Text Class so that that object has an empty object or whatever it has to have to do not carry over any style?

**Comment by sponno** [comment]
Adding this line fixes the issue
`fabric.disableStyleCopyPaste = true`
