### ISSUE TITLE
how to move object in group

### ISSUE THREAD

**Issue by muxi2015** [fabricjs/fabric.js#4982]
## Version
2.3.0

**Comment by asturur** [comment]
please for those kind of question ise stackoverflow.com

**Comment by muxi2015** [comment]
hey gay, i write a demo, Can I add it to the official example?
[LINK](https://jsfiddle.net/muxi2015/bv7vz5bk/)
@asturur

**Comment by asturur** [comment]
what is the demo about and how it show a common uses case to users?

We are happy to add demos to the demo page, provided they are not duplicated and represent a common use case

**Comment by muxi2015** [comment]
@asturur Selecting border will select its internal element，simulation “group” behavior
sorry, My English is bad，You can open the sample operation
