### ISSUE TITLE
pattern unit Load From JSON and export get crossOrigin Error

### ISSUE THREAD

**Issue by evolutionjay** [fabricjs/fabric.js#4983]
## Version
2.3.0

## Test Case
https://jsfiddle.net/evolutionjay/b9fgknd2/

## Steps to reproduce
1. Load image url with crossOrigin 
2. using pattern to  fill a Rect klass with this image 
3. export to json for save
4. load a json form saved json to cavnas and export .
got error

**Comment by asturur** [comment]
https://jsfiddle.net/b9fgknd2/1/

You need to set a crossOrigin for the pattern too!
I know this is a repetition but we can't assume that is anonymous automatically.
