### ISSUE TITLE
Inconsistent behavior in enabling edit mode on textbox when setActiveObject() is used

### ISSUE THREAD

**Issue by semiadam** [fabricjs/fabric.js#4985]
When a textbox is selected by a user click, another click will take it to editable mode.
However, if a textbox is selected programatically using setActiveObject(), the next click will not take it to editable mode. It requires two clicks to go to edit mode. This is an inconsistent behavior from user perspective and can cause confusion.

See Fiddle:
http://jsfiddle.net/Da7SP/1649/

Expected behavior:
No matter if the textbox is selected by user click or through code, a single click must take it to editable mode.

**Comment by asturur** [comment]
http://jsfiddle.net/Da7SP/1657/

i agree this think must be fixed.
