### ISSUE TITLE
Calling setZoom() or setWidth() when a textbox is in editable mode results in malfunction

### ISSUE THREAD

**Issue by semiadam** [fabricjs/fabric.js#4986]
If setZoom(), setWidth(), or setHeight() is called on a canvas while a textbox is in editable mode, typing cannot continue after the action, although the blinking cursor is displayed in the right position.

See this Fiddle:
http://jsfiddle.net/Da7SP/1651

Expected behavior:
User must be able to continue typing if the blinking cursor is present and/or textbox is in editable mode (i.e. resize controls are hidden).

**Comment by asturur** [comment]
Fiddle does not seem describing the issue

**Comment by samael205** [comment]
![textproblem](https://user-images.githubusercontent.com/649740/40603057-144975da-625b-11e8-820f-727102a2e4c4.gif)
We can not write anything after having zoomed. Keyboard events do not work, unless you change the selection with the mouse
In addition the selection of the object is maintained even if the object has been moficado as seen in the gif

**Comment by durga598** [comment]
As text area is not in focus so you can't able to input from keyboard. You need to set focus on textarea after calling zoom or set width function.
Here is [fiddle](http://jsfiddle.net/Da7SP/1659/)

**Comment by asturur** [comment]
We have the new issue you opened for this.
We'll keep the discussion there. I do think it needs a fix in some way.
