### ISSUE TITLE
feather edge in image

### ISSUE THREAD

**Issue by liajoy** [fabricjs/fabric.js#4987]
## Version
2.3.3

## Test Case
https://jsfiddle.net/hcfk8oha/

## Steps to reproduce
how to make feather edge in image?
i dont see any filter to do this.
clipTo seems cant make effect like the test case.

**Comment by asturur** [comment]
As of now there is nothing built in for this kind of things.
A mask api and clip api are in the works

**Comment by liajoy** [comment]
Use a color-to-transparent gradient to be a mask can do this.

**Comment by laibinweb** [comment]
> Use a color-to-transparent gradient to be a mask can do this.

Can you give me an demo?
