### ISSUE TITLE
How to render text Wiki

### ISSUE THREAD

**Issue by Lucas-Espindola** [fabricjs/fabric.js#4988]
The how to render text page in the Wiki simply has a \ in it, and the previous revision is just some gibberish.

**Comment by asturur** [comment]
?

**Comment by Lucas-Espindola** [comment]
![image](https://user-images.githubusercontent.com/14125780/40396791-4a245daa-5e05-11e8-9269-7c76e95e7d10.png)

**Comment by asturur** [comment]
I think we should just remove this page.
I m sorry i did not understand that `how to render text wiki` was not a question.

**Comment by Lucas-Espindola** [comment]
NP, i wrote it in kinda of a silly way tbh
