### ISSUE TITLE
the range of filling is exceed of the rect

### ISSUE THREAD

**Issue by slahser1992** [fabricjs/fabric.js#4991]
## Version
2.3.0

## Test Case
http://jsfiddle.net/Da7SP/1655/

## Steps to  #reproduce
Move the dot in the lower right corner and update size of the red rect.

## Expected Behavior
the range of filling is same of the size of rect.
## Actual Behavior

Can not change the size of the rect as expected, especially when the rect is small, the range of filling will far exceed the range of the rect.

**Comment by asturur** [comment]
This looks like more something that should be handled in stackoverflow, i cannot see here a specific fabricJS problem, rather a specific app functionality you are trying to implement.

**Comment by asturur** [comment]
Please add  a question on stackoveflow and reply with the link.
Be sure to open the question with a working snippet ( not a fiddle ) in order to people being able to help you faster.
