### ISSUE TITLE
Need help for IText object to add bullets (like Order list and Unorder list)

### ISSUE THREAD

**Issue by solanki-ankit** [fabricjs/fabric.js#4992]
Any idea or suggestion?

**Comment by asturur** [comment]
you can handle it in many ways, making bullets part of your text is the first one.

**Comment by solanki-ankit** [comment]
Do you have any tutorial or demo of that?

**Comment by asturur** [comment]
no i mean just add the bullets code point in the text, like with string manipulation

**Comment by solanki-ankit** [comment]
- fdgfdg
fgfd

1. fgfdg
1. 

- fgfdgf


fdfdgfdg

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
