### ISSUE TITLE
Can't add looped image objects to a group?

### ISSUE THREAD

**Issue by StrangerPings** [fabricjs/fabric.js#4993]
I am trying to add looped objects to a group and does not work.  Please see.

https://jsfiddle.net/seversides/mo2q44wa/1/

Yet when something like circles are added it works just fine, as per

https://stackoverflow.com/questions/46076682/unable-to-ungroup-with-fabric-js

But using 

fabric.Image.fromURL

does not seem to work?

**Comment by asturur** [comment]
Please is unclear what are you asking, nor the fiddle is clear
