### ISSUE TITLE
Bounding box is the wrong size for zoomed multi-selections

### ISSUE THREAD

**Issue by melchiar** [fabricjs/fabric.js#4995]
## Version
2.3.0

## Test Case
https://jsfiddle.net/melchiar/gjde7jvs/

## Steps to reproduce
Create a multi-selection of textframes programmatically. If the canvas is zoomed, the bounding box/controls appear in the wrong location/size.

## Expected Behavior
The bounding box of a multi-selection should display at the correct size/location when the canvas is zoomed

## Actual Behavior
When creating a multi-selection of textframes programmatically and then changing your zoom level, the bounding box and controls display in the wrong correct size/location.

![image](https://user-images.githubusercontent.com/9057412/40455052-15a178a6-5ea0-11e8-8a89-244b2252b0dd.png)

**Comment by brentcappello** [comment]
I would say this probably falls as a Stackoverflow question. 

Here is a solution I created that should work for you.
https://jsfiddle.net/Lwg1nxa0/1/

Hope that helps!

**Comment by melchiar** [comment]
That was it! Thanks Brent, I thought for sure I'd found a bug.
