### ISSUE TITLE
Disable all events (Making eyeDropper). 

### ISSUE THREAD

**Issue by DangerD256** [fabricjs/fabric.js#4996]
Need to change selected object color by using eyedropper, color i can get using this way:
```
canvas.on('mouse:up', function (e) {
    var c = document.getElementById("c");
    var ctx = c.getContext("2d");
    var imgData = ctx.getImageData(canvas.getPointer().x, canvas.getPointer().y, 1, 1);
    alert("rgb " + imgData.data[0] + " " + imgData.data[1] + " " + imgData.data[2]);
});
```
But clicking somewhere will deselect current object. Any way to "freeze" whole fabricjs?

**Comment by asturur** [comment]
well i have 2 answers here, one os fabricjs related, the other not.

Fabricjs side you can take the activeObject and set 'onDeselect = () => true'

that will make it undeselectable, then remove the onDeselect function when you are done.

The other is just overlay a transparent div in the canvas container div and take position of the click adding a plain js event handler there. is a perfect valid solution i think.

**Comment by DangerD256** [comment]
Sorry for disturbing, but what i'm doing wrong:
https://jsfiddle.net/ngbdhkkq/54/

**Comment by asturur** [comment]
https://jsfiddle.net/asturur/ngbdhkkq/56/

in this way works, but weirdly if i center the image on screen is not working anymore

**Comment by asturur** [comment]
https://jsfiddle.net/asturur/ngbdhkkq/57/

i m sorry it works, is just that the retina screen is not taken in account, you have to consider who has a retina screen has to multiply the resulting coordinates by fabric.devicePixelRatio

**Comment by DangerD256** [comment]
Can you please help me with that, it partially works, but as i have zooming in using Ctrl+mouse wheel and moving canvas area it works with some offset.
Added zoom and viewportTransform compensation, but i still have some offset
`var data = ctx.getImageData(
Math.round((pointer.x+canvas.viewportTransform[4])* fabric.devicePixelRatio*canvas.getZoom()), 
Math.round((pointer.y + canvas.viewportTransform[5])* fabric.devicePixelRatio*canvas.getZoom()), 1, 1).data;`

https://jsfiddle.net/2gbrcty4/51/

**Comment by DangerD256** [comment]
Any suggestions?

**Comment by DangerD256** [comment]
A bit stuck with eyeDropper, the main problem that i'm using fabricjs ZOOM capabilities and area moving. With 100% zoom this code works fine:

    ctx.getImageData(x,y,1,1)

But with zooming i had to multiply xy values with current zoom value `x*canvas.getZoom()` and also i had to multiply it by `fabric.devicePixelRatio` as i had "retina" (4k) screen. This all works fine unless i move working area `canvas.viewportTransform[5] += 100;` so i tried to compensate it, but it fails...
Whole code:

    (pointer.x+canvas.viewportTransform[4])* fabric.devicePixelRatio*canvas.getZoom()

Whole example here:
https://jsfiddle.net/2gbrcty4/72/

Note: moving canvas - mouse wheel or touchpad, zoomingIn/out ctrl + mouse wheel

**Comment by DangerD256** [comment]
If you will reset area offset eyeDropper will work fine:

    canvas.viewportTransform[4] = 0;
    canvas.viewportTransform[5] = 0;

Any suggestions?

**Comment by mean2me** [comment]
Hi @DangerD256 ,
I see you are using getPointer(evt). It should already consider the zoom/pan transformations but actually I verified that you are getting wrong data when you pan the canvas and I'd like to have an answer from someone in the core development team of fabric after about 4 years... it would be appreciated :)
