### ISSUE TITLE
Hex code provides wrong CMYK detail in photoshop

### ISSUE THREAD

**Issue by nitin-bc** [fabricjs/fabric.js#4997]
Hi,

I have been generating the output for text object using hex code as per default flow of the Fabric JS library. Whenever I open this output image or generated PDF file in Photoshop or Illustrator then CMYK information is being displayed wrong while comparing through online convertor. We are using latest Fabric JS library in our system.

![designer-colour-ouput-black](https://user-images.githubusercontent.com/24458978/40536698-9f1f6274-602a-11e8-9e1f-4f1ffed95315.png)
![designer-colour-ouput-grey](https://user-images.githubusercontent.com/24458978/40536700-9f702f06-602a-11e8-94ef-a0d3e3200c56.png)

In above attachments, the colors has been used are black and Grey but CMYK information doesn't seem proper.

Would you please provide some suggestion on this?

Thank You.

**Comment by asturur** [comment]
I have no idea with what process the cmyk color are generated or why are they wrong.

Can you replicate this problem in a way is observable?

**Comment by nitin-bc** [comment]
Hi Asturur,

Thank you for your response. Please refer the link @ https://edgetest.idcardsolutions.co.uk/productdesigner/index/card/id/28564/templateid/125 and click on the "[Download Proof](https://drive.google.com/file/d/1catjNAXUmWdR4ifpSU0bkU-KlsICNgeE/view)" button, a PDF would be downloaded to your desktop. If you will open this PDF in Photoshop and check the color for "[The Edge System](https://drive.google.com/file/d/1eWTzw4_HUOrZQABjPZzgsAFEF5tdVUGe/view
[design.pdf](https://github.com/fabricjs/fabric.js/files/2041267/design.pdf)
)" then compare the CMYK information. It will display wrong. The color is #000000 but Photoshop displays wrong CYMK information.

Hope you are getting the concern.

**Comment by nitin-bc** [comment]
[Download Proof](url)

**Comment by asturur** [comment]
are you outputting rgb or cmyk from fabric and who is doing the conversion?

**Comment by nitin-bc** [comment]
I am just generating an image with todataurl output and converting it to PDF. Our customer is checking the PDF in photoshop that displays the CMYK information wrong.
Thank you

**Comment by nitin-bc** [comment]
Hi, Would you please update me on my last query if possible?

Thank you

**Comment by asturur** [comment]
Well toDataUrl is encoding images without fabricJS code.
FabricJS has not knowledge at all of cmyk, not even support for color codes conversions, so i m really sure the problem is somewhere in the conversion process.

All the canvas in browser works are RGB.
