### ISSUE TITLE
Bug with removing all objects from the canvas

### ISSUE THREAD

**Issue by mxlnk** [fabricjs/fabric.js#4998]
## Version
2.3.0

## Test Case
http://jsfiddle.net/mxlnk/Da7SP/1656/

## Steps to reproduce
see the fiddle

## Expected Behavior
As suggested in https://github.com/fabricjs/fabric.js/issues/3356 I'd also expect all objects to be removed

## Actual Behavior
Object that was last added to the canvas is not removed.

## Workaround
```
const objects = lodash.clone(this.canvas.getObjects());
this.canvas.remove(...objects);
```

**Comment by asturur** [comment]
this has been discussed already somewhere in the issues.
getObjects returns the current array, and then with remove you mutate it.

Use `canvas.remove(...canvas.getObjects().concat())` you should be ok
