### ISSUE TITLE
clipTo  对 Path2D 的支持有问题(ClipTo is support for Path2D is problematic)

### ISSUE THREAD

**Issue by mnonmcn** [fabricjs/fabric.js#5001]
很抱歉，我不会英语，clipTo 对于 Path2D 不能得到良好的支持
I'm sorry, I can't speak English, this is Machine Translation, and clipTo can't get good support for Path2D.

    clipTo:(ctx)=>{
        var path = new Path2D('M108 152 L174 30 L42 30 Z');
        //ctx.stroke(path);
        ctx.fill(path);
    }

**Comment by asturur** [comment]
Could you use english please? I cannot read chinese.

**Comment by mnonmcn** [comment]
很抱歉，我不会英语，我对问题进行了修改，使用机器翻译的，有可能表达不准确，见谅
I am sorry, I can not speak English, I have modified the problem, using Machine Translation, it is possible to express inaccuracy, forgive me.

**Comment by mnonmcn** [comment]
你好，我的问题解决了，我重写了 fabric.util.clipContext 方法使其对返回 Path2D 路径的支持，希望我的方法能对项目有帮助。


Hello, my problem has been solved, and I rewrote the fabric.util.clipContext method to support the return of the Path2D path, and I hope my method can help the project.



`fabric.util.clipContext = function(receiver, ctx) {
                ctx.save();
                ctx.beginPath();
                var path = receiver.clipTo(ctx);
                if(path){
                    ctx.clip(path);
                }else{
                    ctx.clip();
                }
} `

**Comment by asturur** [comment]
ClipTo is deprecated, and later will be removed.
Please check here:
https://github.com/fabricjs/api-discussion/issues/1
