### ISSUE TITLE
Applying multiple filter to image resizes it

### ISSUE THREAD

**Issue by hamed743** [fabricjs/fabric.js#5011]
## Version
2.3.1

## Test Case
http://fabricjs.com/image-filters

Browser Chrome 66

when applying multiple filters on image with webgl  enabled, image gets resized.
is this a bug or not?
![filter](https://user-images.githubusercontent.com/9843558/40717235-d782c67a-6420-11e8-855b-b02537115c39.png)

**Comment by asturur** [comment]
Would be interesting to know on what computer/OS/videocard are you

**Comment by hamed743** [comment]
window 8.1 
cpu AMD Athlon ||
gpu NVIDIA GeForce 7100 GS

**Comment by asturur** [comment]
When you use the webgl filter, in the console you should find an information like:

maxTexturesize: number

what is reporting? 
![image](https://user-images.githubusercontent.com/1194048/40719053-72e4c7ee-6412-11e8-8877-3491d4e6be56.png)

**Comment by hamed743** [comment]
its 4096

**Comment by asturur** [comment]
Is very strange, it can be a driver issue since Nvidia did not produce drivers for that card on windows 8 anymore. Is very unlikely we can fix it from JS.

**Comment by hamed743** [comment]
thank you @asturur

**Comment by RusEu** [comment]
It also happens to me when I apply multiple filters:

    let filters = [
      new fabric.Image.filters.Brightness({ brightness: this.brightness }),
      new fabric.Image.filters.Contrast({ contrast: this.contrast }),
      new fabric.Image.filters.Saturation({ saturation: this.saturation })
    ];
    const image = this._fabricEl.getActiveObject();
    const newImage = image.applyFilters(filters);

    this._fabricEl.renderAll();

Any help please ?

**Comment by asturur** [comment]
i think is hardware dependant. what is your configuration?

**Comment by hamed743** [comment]
@RusEu , I checked with a more powerful computer and it was ok.

**Comment by asturur** [comment]
can we know what the other computer had?

**Comment by hamed743** [comment]
i dont know. but its maxTexturesize was 8192

**Comment by hamed743** [comment]
i think if the image is complex filter cant work on it

**Comment by asturur** [comment]
more a driver issue maybe.

**Comment by asturur** [comment]
myax texture size is 16384, but fabric generates a canvas of  2048 pixels, so is not a problem of texture. If the image has a side bigger than 2048 you have to increasize the filtering size as per docs. If the image zoom, or you can see just a quarter of it, there is a different problem

**Comment by RusEu** [comment]
@asturur Hello, my image is 4000x4000, and I think what happens is what you are describing, that when applying the filter the image is resized to 2048x2048.

What is the solution for this kind of problem?

You are talking about increasing filtering size. But how can I achive this?

I searched it everywhere in the fabricjs documentation, but i didn't found nothing.
The texture size that is printed in the console, when I apply the filters is 16384.

**Comment by asturur** [comment]
http://fabricjs.com/fabric-filters

please read this completely to have an understanding of what you are working on, and what does it do.
