### ISSUE TITLE
Issue While rotating SVG in chrome on windows 7

### ISSUE THREAD

**Issue by muthughilli** [fabricjs/fabric.js#5012]
I have created a canvas element and completed the rotate functionality using fabric js. Everything is working fine. But I see a set of dotted lines pointing to the center of the canvas only in the Chrome browser of windows 7 and that too in some devices and not in all windows 7 and chrome combinations.  https://i.stack.imgur.com/JdnH8.png

I have tried a simple page to replicate the same issue. https://i.stack.imgur.com/zUrBQ.png
 Please find the fiddle link below.

Does anyone faced this issue.?  It would be great if i find a solution.

## Version
1.7.22

## Test Case
https://jsfiddle.net/muthu999/4frbstqa/

**Comment by asturur** [comment]
it has been fixed in 2.x, you should search back the commit and backport it.

**Comment by muthughilli** [comment]
It's working fine after using 2.x. Thank you!
