### ISSUE TITLE
[Question]  How to Export clipTo area only

### ISSUE THREAD

**Issue by folkevil** [fabricjs/fabric.js#5014]
Hi,
I'm trying to export clipTo area only, but when i use toDataUrl, it export only about 1/4 clipping area and wrong coords

**Test case**

https://jsfiddle.net/tradade/7m3yzr4k/

-------------------------

This is my init code:

```


canvas = new fabric.Canvas('canvas', {
            fill: '#D4A076'
});
var setActiveProp = function(name, value) {
    var object = canvas.getActiveObject();
    if (!object) return;
    object.set(name, value).setCoords();
    canvas.renderAll();
}
var getActiveProp = function(name) {
    var object = canvas.getActiveObject();
    if (!object) return '';

    return object[name] || '';
}

var exportImg = function (x = null, y = null, w = null, h = null) {
    
    $.fancybox.close();
    var imgDataUrl = canvas.toDataURL({
        left: x,
        top: y,
        originX: 'center',
        originY: 'center',
        width: w,
        height: h,
        format: 'png'
    });

    //fabric.log('Normal SVG output: ', canvasContainer[side].toSVG());
    $.fancybox.open('<div class="message"><img  src="' + imgDataUrl + '"/></div>');

};
var $sideContainer = $('#canvas');
var cWidth = 900,
  	  cHeight = 600,
      x = 375,
      y = 225,
      w = 400,
      h = 300;
canvas.backgroundColor = '#222222';
canvas.clipTo = function (ctx) {
  ctx.rect(x, y, w, h);
  ctx.save();
};
canvas.renderAll();
exportImg(x,y,w,h);
```
And this is how canvas displayed

![Display](https://i.imgur.com/3rPcCV7.png)

My expected result
![Expected result](https://i.imgur.com/cEhbodw.png)

And this is final result
![Final result](https://i.imgur.com/fFg7ro1.png)

Result image display only 1/4 of source image, with extract dimensions but wrong coords, 3/4 are transparent. I tried to change coords but no luck. Any solution ?

**Comment by wesleyguirra** [comment]
@asturur can you be more specific? I mean there's no params about getting just a part of canvas.

**Comment by asturur** [comment]
you can specify top, left, width, height. in toDataURL options.

**Comment by asturur** [comment]
http://fabricjs.com/docs/fabric.Canvas.html#toDataURL

**Comment by Khushalikg** [comment]
@asturur your given link is not working anymore, can you give us some new link showing use of clip path and toDataURL. I am currently working on a functionality where I want to show part of canvas instead of whole canvas for working window. But at the same time I want to be able to see whole canvas and goto another part of it when I want to by specifying coordinates. I thought clip path would work for this case, but when I apply clip path to canvas it removes the rest of image when exporting using toDataURL.

**Comment by pchunky** [comment]
I'm on Fabric.js 6.7.0. I think what @asturur meant was to specify the `top`, `left`, `width`, and `height` (hence a definition of a rectangle) to `canvas.toDataURL` so that the exported image is cropped into said rectangle.

```ts
const clipRect = canvas.clipPath.getBoundingRect();

const url = canvas.toDataURL({
  top: clipRect.top,
  left: clipRect.left,
  width: clipRect.width,
  height: clipRect.height,
  format: "png",
  multiplier: 1,
});
```
