### ISSUE TITLE
Reset image in group shadow-offset to zero make image disappear

### ISSUE THREAD

**Issue by liajoy** [fabricjs/fabric.js#5016]
## Version
2.3.0

## Test Case
https://jsfiddle.net/fkr8473u/

## Steps to reproduce
1.  Set image shadow
2. Make image in group
3. Set image shadow-offset to be zero

## Expected Behavior
Image shadow offset to be zero.

## Actual Behavior
Image disappeared.

## Final
Fire group.addWithUpdate can avoid this situation. But Why?

**Comment by asturur** [comment]
this is a bug
