### ISSUE TITLE
_onMouseDown not removing from touch device

### ISSUE THREAD

**Issue by durga598** [fabricjs/fabric.js#5027]
## Version
2.3.0

## Test Case
https://jsfiddle.net/durga598/L6u6ftzp/7/

## Steps to reproduce
Touch and drag to draw circle, while drawing circle try to use another finger(touch), it will stop drawing.
## Expected Behavior
For touch device it need to remove the eventlistener `_onMouseDown` from uppercanvas(line #10933), but its not removing. It need to listen the old mousemove/mouseup, old event listener are not calling, it creates new.

**Comment by asturur** [comment]
@durga598 is not completely clear what is the problem in your opinion. Can you be more specific?

**Comment by durga598** [comment]
For one finger its drawing properly. If you put another finger while drawing, it stops drawing.

**Comment by asturur** [comment]
i meant the code problem

**Comment by durga598** [comment]
`_onMouseDown` in this function there is a removelistner, its not removing event listener.
