### ISSUE TITLE
Fabric not rendering additional objects while resizing/scaling object

### ISSUE THREAD

**Issue by Zahlii** [fabricjs/fabric.js#5028]
Hi,

I have the following problem using the old Fabric 1.17:
Whatever I add to a canvas in a on('obejct:scaling') - it is not displayed until the scaling of the object is finished, i.e. mouse gets lifted, see this fiddle for an example.

Try scaling the black box and pay attention to ehwn the red lines appear.

https://jsfiddle.net/wtk02t4t/13/

**Comment by asturur** [comment]
weird, definitely a bug.
Does 2.3.2 behave same?

**Comment by asturur** [comment]
oh 1.7.22 fixes it.
Please update.
