### ISSUE TITLE
Blinking cursor does not disappear when hiddenTextarea goes out of focus

### ISSUE THREAD

**Issue by semiadam** [fabricjs/fabric.js#5029]
If a fabric textbox is in editing mode, and users take an action that takes away the focus from the corresponding hiddenTextarea, the blinking cursor on the canvas does not disappear. Therefore, while the blinking cursor signals them to continue typing, in reality they cannot type, which leads into confusion.

Here's a fiddle:
http://jsfiddle.net/Da7SP/1699/

There are manual workarounds that can fix this with additional coding at application level, but IMHO the text object itself should be aware of its own state and automatically hide the blinking cursor when the hiddentextarea gets blurred.

**Comment by asturur** [comment]
Agree is a bit werid.
I ll try to use an onBlur event handler to understand if is fixable in some way.
onBlur should trigge an exitEditing for the object, i m worried of side effects i m not thinking of now, like MACOS text bubble or other things like chinese / japanese composition dropdown

**Comment by samael205** [comment]
One suggestion, is it not possible to invoke programmed exit editing? Something like object.exitEditing ()?

**Comment by asturur** [comment]
yes that would do, but since the textarea is deleted and destroyed as many time as you enter edit, you have to bind the event many times.

if fabric handles that we have to be sure we do not break other functionalitied
