### ISSUE TITLE
Shadow offset make path disappear

### ISSUE THREAD

**Issue by liajoy** [fabricjs/fabric.js#5031]
## Version
2.3.1

## Test Case
https://jsfiddle.net/msxr0wku/

## Steps to reproduce
1. let a image and a path in the group.
2. clone image and set shadow offset
3. click to trigger render
4. path disappear
## 
The version 2.3.0 not fix #5016 will make the path whole disappear.
I update to 2.3.2 will make the path partial disappear when i custom a path class like this:
`    const Path = fabric.util.createClass(fabric.Path, {
        _setPositionDimensions: function(options) {
            const calcDim = this._parseDimensions();

            this.width = calcDim.width;
            this.height = calcDim.height;
            if(typeof options.left === 'undefined') {
                this.left = calcDim.left;
            }
            if(typeof options.top === 'undefined') {
                this.top = calcDim.top;
            }
            this.pathOffset = this.pathOffset || {
                x: this.width / 2, 
                y: this.height / 2 
            };
        }
    });
`
The pathOffset was modified from this.width /2 + calcDim.let

**Comment by asturur** [comment]
https://jsfiddle.net/msxr0wku/1/

Unsure if this is bette, i m waiting for fabic 2.3.2 to be published

**Comment by asturur** [comment]
Yes the fix for 2.3.2 conver this case too, and this is definitely how you should handle it. If you are adding an object to a group, you should declare it as dirty.
