### ISSUE TITLE
centeredScaling is not working with slider control.

### ISSUE THREAD

**Issue by appledev44** [fabricjs/fabric.js#5032]
centeredScaling Not working with slider control.
It working when we scale object manually by using object's corner.
I want scale object using slider control in my project.
Can  you please help me or any suggestion or solution for this issue?

Here I made fiddle for it.
https://jsfiddle.net/AppleDev/gpj20mzh/

**Comment by asturur** [comment]
For custom help, please open questions on stackoverflow.
This is not an issue regarding fabricJS.

**Comment by appledev44** [comment]
I applied centeredScaling=true  property to object but still it not scaling from center.
But When I manually scaled then its working..
How can you say, this issue is not regarding to fabricJS.
Instead of manually scale I just use slider for that.

**Comment by asturur** [comment]
This is a custom app help, and bette fits stackoverflow.
Can you open a question there and post the link here?

**Comment by appledev44** [comment]
https://stackoverflow.com/questions/50791024/centeredscaling-is-not-working-with-slider-control

**Comment by asturur** [comment]
https://stackoverflow.com/a/50793634/2655678
