### ISSUE TITLE
moving small objects on canvas is difficult

### ISSUE THREAD

**Issue by uoojin1** [fabricjs/fabric.js#5033]
## Version
2.3.0 (wasn't a problem with fabric 1)

## Test Case
https://jsfiddle.net/asogtqmu/1/

## Steps to reproduce
1) create a small object on canvas (size should be similar to the default control point's size)
2) make sure the object is deselected (click canvas)
3) try to move the object by click/drag

## Expected Behavior
Object should be moved along with the mouse

## Actual Behavior
object gets scaled instead

![2018-06-08 2 19 21](https://user-images.githubusercontent.com/26753936/41175142-1fc5a898-6b2a-11e8-9aae-94654545dfe7.png)

**Comment by asturur** [comment]
yes fabric at some point started give precedence to controls if the object is already selected.
I think this is right.

There is no many solution to this problem if not using  a minScaleLimit and giving some padding to controls.

**Comment by melchiar** [comment]
I encountered the same issue. As asturur mentioned, you can use padding to mitigate the problem. 

Doing something like this, you can apply padding to the object if needed after each object:modified event https://jsfiddle.net/melchiar/ezsqjku3/
