### ISSUE TITLE
Fabric version 2.2.4 + google chrome version 67 + Microsoft surface studio pen tool 

### ISSUE THREAD

**Issue by rottesindhuri** [fabricjs/fabric.js#5034]
I recently upgraded the fabric version to 2.2.4 but that doesn't seem to help with my issue.
I cannot draw on fabric js using pen tool that has google chrome version @67.
Basically pen tool is not patching the points.. to get the points I'm using get pointer events function of fabric js. Fabric path, rect, object are what I'm using. 
I appreciate for solving this.
Thank you.

**Comment by asturur** [comment]
Do you notice this problem since you moved to chrome 67 from an older version or is all chrome vs firefox other browsers?

**Comment by rottesindhuri** [comment]
Thank you so much for responding first of all. It is with previous versions
too. We don't use Firefox. If you need anything else please let me know.

**Comment by asturur** [comment]
You need to leave open a jsfiddle that can trigger the problem
I got a surface ( i lost the pencil but maybe i can find it again ) just to test those things and to develop multitouch / pointers better.

**Comment by rottesindhuri** [comment]
I'm trying open a js fiddle.. that is a complicated task..
i can share some of our original code is that ok?
and i have one more bug too after upgraded the fabric. ill attach the
picture.

Please help me if you can.

**Comment by asturur** [comment]
You have to understand that if the fiddle is not simple, maybe the bug is in the fiddle.

**Comment by rottesindhuri** [comment]
ok I'm creating one.

**Comment by rottesindhuri** [comment]
I created one js fiddle. Fiddle has 1.7.20 version line seems to be working
fine. My fabric version is 2.2.4. Line wiggles when you move and bounding
box is also not right. I'm sorry if I'm borne vague.

**Comment by rottesindhuri** [comment]
I created a fiddle and its not fabric js :(.. thank you very much
