### ISSUE TITLE
Blurred SVG groups when loading on regular screen

### ISSUE THREAD

**Issue by kfir124** [fabricjs/fabric.js#5036]
## Version
2.3.2

## Test Case
![screen shot 2018-06-11 at 4 35 54 pm](https://user-images.githubusercontent.com/4980504/41234847-0a5564b2-6d96-11e8-9475-6259ba99c296.png)
![screen shot 2018-06-11 at 4 35 36 pm](https://user-images.githubusercontent.com/4980504/41234852-0d1299c2-6d96-11e8-8a42-69fad60cefe2.png)

## Steps to reproduce
- Open browser window on Retina laptop and look at a fabric canvas drawing
- Open the same browser on a normal screen and render the same image

As you can see in the images one is really blurred (the non retina).

BUT! if you drag the browser window from the retina screen to your other regular screen the image won't be blurred at all, in fact it will look as sharp as in the retina. even after I redraw the image it is still sharp, the only way to make it blurred again is to refresh the sharp image on a regular screen and now it will draw it blurred.

disposing / redrawing stuff in the canvas will still be sharp if the SVG was loaded while the browser window was on a retina laptop screen while loading the svgs. and it will still be blurred if you drag the blurred image from the big screen to the retina screen.

Only a full page refresh will cause the SVG elements on the canvas to look sharp/blurred (and then it depends on which screen the browser window was on)

Happens on Chrome 67, Firefox newest, safari, etc...

## Expected Behavior
SVG shouldn't be blurred when resized.

## Actual Behavior
SVG is blurred when opened on non retina screen, and it will stay blurred no matter what.

## Note

**I can freely resize the svg to fit the window size and it looks great if the svg originally loaded on a retina screen. if it loaded while on non retina screen it looks bad on both retina and the original regular screen**

Seems like it doesn't matter on which screen I am, it only matters on which screen I originally loaded the browser tab

**Comment by kfir124** [comment]
I thought maybe it was hard to notice the difference so now I took the canvas from the big screen to the small retina screen.

First image I didn't refresh:

<img width="837" alt="screen shot 2018-06-11 at 5 52 18 pm" src="https://user-images.githubusercontent.com/4980504/41239110-588d223c-6da0-11e8-9d59-91dc5e2c143a.png">

Second image I refreshed:

<img width="838" alt="screen shot 2018-06-11 at 5 52 26 pm" src="https://user-images.githubusercontent.com/4980504/41239194-7fa8a972-6da0-11e8-94ab-610b3e5878be.png">

**Comment by kfir124** [comment]
If someone wonder in the future I hacked it to work good on all screens by doing:
`fabric.devicePixelRatio = 2;`
before I set the canvas

**Comment by asturur** [comment]
you probably have a positioning problem on the svg object that put it half pixel.

Can you load this svg on a jsfiddle?

**Comment by kfir124** [comment]
It is very possible indeed that some elements are getting placed at half pixels I'll look into it thanks.

I can't load it on fiddle because it is being generated by a pretty complicated code.
