### ISSUE TITLE
Unexpected extra gap between uppercased letter and container border on text rendering.

### ISSUE THREAD

**Issue by redlive** [fabricjs/fabric.js#5037]
## Version
2.3.0

## Test Case
https://jsfiddle.net/redlive/ksc0rf8x/

## Steps to reproduce
Run script

## Expected Behavior
The `Agent` text should touch the top border.

## Actual Behavior
The `Agent` text has a gap between top border and letter `A`

**_InDesign Rendering:_**
<img width="578" alt="screen shot 2018-06-11 at 11 01 54 am" src="https://user-images.githubusercontent.com/5912122/41250802-d1c42e72-6d6c-11e8-9551-3ceb664c4246.png">

**_FabricJS rendering:_**
![image](https://user-images.githubusercontent.com/5912122/41250822-e4f70578-6d6c-11e8-8bae-dbde253af6ea.png)

**Comment by asturur** [comment]
Text is positioned by baseline in a box that is as tall as the fontSize plus some multiplied.
It will never match with other text tools.

FabricJS keeps some space to fit the oveline decoration

**Comment by asturur** [comment]
You can try to export to SVG and import in fabric if you have to keep some deisgn similarities between indesign and fabricJS

**Comment by redlive** [comment]
What `overline decoration` means? could it be configurable? I'm as a user can decide myself what `overline decoration` size to apply... Don't you think it will be better for users as I?
These days I need to find a solution and write some overrides (which I have no idea even where to start) to match the design...
