### ISSUE TITLE
getActiveObject does not return path

### ISSUE THREAD

**Issue by sops21** [fabricjs/fabric.js#5038]
## Version
2.3.0

## Test Case
(2.3.0) (Broken)
https://jsfiddle.net/aLkkxghz/70/

1.5 (Working)
https://jsfiddle.net/aLkkxghz/72/

## Steps to reproduce
Click to add SVG to the canvas. Use the color picker to change the color of the SVG

## Expected Behavior
Whole SVG object changes color. It appears that getActiveObject return an object without a path

## Actual Behavior
Throws error in console. 
Cannot read property 'forEach' of undefined

**Comment by durga598** [comment]
As of v2 [path group removed](http://fabricjs.com/changes-introduction) . Here is your updated [fiddle](https://jsfiddle.net/durga598/aLkkxghz/80/)

**Comment by sops21** [comment]
Thanks. That worked!
