### ISSUE TITLE
Fabric Textbox - Vertical alignment, Diagonal alignment(Left , Right) , Clockwise and anticlockwise rotate 

### ISSUE THREAD

**Issue by BhuvaneshwaranR** [fabricjs/fabric.js#5040]
Hi @kangax ,
        I have modified the _wrapLine, _generateStyleMap, _renderChar function. but can't able to to do it. Please suggest me how to achieve the below output. 
 Is it possible by using fabric?
How to restrict a width of textbox object?
![veritical text](https://user-images.githubusercontent.com/10132578/41332913-4d754114-6efd-11e8-927e-3c00bdaaad30.png)
![rightdiagonal](https://user-images.githubusercontent.com/10132578/41332890-3b93f9c2-6efd-11e8-8704-1dc6f589fa75.png)
![left diagonal text](https://user-images.githubusercontent.com/10132578/41332892-3c0569fe-6efd-11e8-8374-baba6d3d57d5.png)
![clockwise rotate text](https://user-images.githubusercontent.com/10132578/41332893-3d723646-6efd-11e8-8cba-899449a48606.png)
![anti clockwise rotate text](https://user-images.githubusercontent.com/10132578/41332894-3e3a41c2-6efd-11e8-8f3b-3c234e77388b.png)

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
