### ISSUE TITLE
Fail to render text with Zero Width Joiner character

### ISSUE THREAD

**Issue by zengfenfei** [fabricjs/fabric.js#5041]
## Version
2.3.0

## Steps to reproduce

With following code, the first line will disappear:
```javascript
var canvas = new fabric.Canvas('canvas');
        var text = new fabric.Textbox(`നിങ്ങള്‍ ഏത് ടീമിനെ
 പിന്തുണക്കുന്നു?`, {
            top: 10,
            left: 10,
            width: 480,
            fontSize: 32,
            color: '#161616',
            textAlign: 'center'
        });

        setTimeout(function(){
            text.width = 470;
            canvas.renderAll();
        }, 100)
```

## Expected Behavior
All text can be rendered correctly.

## Actual Behavior
The first line is not rendered.

## More info
I did some investigation and discovered:
 * The problem occurs only when `textAlign` is not `left`.
 * When `textAlign` is not left, fabric will try to calculate the width of every line, but when the line contains `ZWJ` char, the computed width is `NaN`. 
 * A quick working fix is: give a default value `0` to `previousWidth` in the method `_measureChar` of `text.class.js`.

**Comment by asturur** [comment]
In what browser this happen?

How many zwj chars unicode has?

**Comment by zengfenfei** [comment]
In chrome.
`ZWJ` is specific char of which the unicode code point is `U+200D`, it's not a type of chars. Refer to https://en.wikipedia.org/wiki/Zero-width_joiner

**Comment by asturur** [comment]
i meant, are there any other adimensional characters in the unicode?

**Comment by zengfenfei** [comment]
I'm not sure. I only ran into problems with a few sample texts of those languages.

**Comment by asturur** [comment]
So i ll patch exceptions on zwj. But take care that zwj is not meant to be measured alone by fabric 2+

If this is happening, the text is not good splitted in good way, that will lead to wrong char representation and cursor position.

please override the standard grapheme splitter with one that support arabic too

**Comment by asturur** [comment]
zwj and zwnj

**Comment by asturur** [comment]
can you replicate it? i can't
