### ISSUE TITLE
fontsize less then 12 did not work

### ISSUE THREAD

**Issue by flappymonkey** [fabricjs/fabric.js#5042]
when I set fontsize less then 12px, it still draw 12px text;

http://jsfiddle.net/tbqrn/480/

and the result should be like this,  http://jsfiddle.net/tbqrn/481/

**Comment by asturur** [comment]
please add a fiddle or  this issue will be closed

**Comment by flappymonkey** [comment]
@asturur  you can see this demo , http://jsfiddle.net/tbqrn/477/

**Comment by flappymonkey** [comment]
@asturur do you have solution？

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/41457435-ea7ab700-7083-11e8-937a-a94da9235dfe.png)

to me looks good.
On what platform is it failing?

**Comment by flappymonkey** [comment]
@asturur  firefox is ok, but chrome has problem.
this is chrome
<img width="350" alt="chrome" src="https://user-images.githubusercontent.com/397388/41459399-11cba700-70bc-11e8-8126-0ccfc431ff2f.png">
this is firefox
<img width="354" alt="default" src="https://user-images.githubusercontent.com/397388/41459409-19ff54e4-70bc-11e8-8e9c-4dcaf1a8c5fc.png">

**Comment by asturur** [comment]
i was using chrome.
What version on what operating system and hardware?

**Comment by flappymonkey** [comment]
@asturur
I was using MacBook Pro (Retina, 15-inch, Mid 2015)，system version is 10.13.4 (17E202)
and my chrome version is 67.0.3396.87

**Comment by asturur** [comment]
i have similar specs and works for me.

**Comment by Lucas-Espindola** [comment]
working fine on Windows 10, Chrome 67
![image](https://user-images.githubusercontent.com/14125780/41609077-58e6951c-73c0-11e8-9def-326f0a784a81.png)

**Comment by flappymonkey** [comment]
@Lucas-Espindola  I think what you look ok is this demo "http://jsfiddle.net/tbqrn/481/", this demo is ok for me too，because this demo used pure canvas api.
what has problem is this demo "http://jsfiddle.net/tbqrn/480/" which used fabric.js

**Comment by flappymonkey** [comment]
@asturur  do you looked this demo "http://jsfiddle.net/tbqrn/480/" ?

**Comment by Lucas-Espindola** [comment]
@flappymonkey Hey man, just tested the [](http://jsfiddle.net/tbqrn/480/) and it worked fine.

![image](https://user-images.githubusercontent.com/14125780/41933471-532e50c0-795a-11e8-8018-fec026217e39.png)

**Comment by flappymonkey** [comment]
this problem did not solved!

**Comment by asturur** [comment]
If we cannot even replicate it, we have nothing we can do

**Comment by flappymonkey** [comment]
@asturur

**Comment by asturur** [comment]
can you give full detail of your OS and browser used? also can you make a reproducible case that will actually show the problem on more computers.

Please also try different browsers on your machine.

**Comment by OPY-bbt** [comment]
+1;  this link http://jsfiddle.net/tbqrn/480/ can replicate it.
macOS 10.14.5
chrome 75.0.3770.142
but cannot replicate it in safari.

**Comment by OPY-bbt** [comment]
@asturur I switch system language to English can resolve it. You can replicate it by changing system language to Chinese Simplified. Amazing~

**Comment by asturur** [comment]
I cannot replicate, even if i set chinese simplified.
What i see is this:
![image](https://user-images.githubusercontent.com/1194048/61998370-4aab0c80-b0af-11e9-80b2-839b0d8d19fd.png)

**Comment by OPY-bbt** [comment]
Sry, you may need to restart your computer.
