### ISSUE TITLE
Selection and cursor leaves trace when zooming

### ISSUE THREAD

**Issue by Tsourdox** [fabricjs/fabric.js#5043]
`Using fabric v2.3.x`

## Test Case
http://jsfiddle.net/n2yLv0h9/8/

## Steps to reproduce
Create a textbox, select the text or click to enable editing with flashing cursor. Then zoom(fast) the canvas.

## Expected Behavior
Selection/cursor is re-drawn within the textbox.

## Actual Behavior
Selection/cursor leaves a trace outside of the textbox.

## Image
![skarmavbild 2018-06-14 kl 10 58 13](https://user-images.githubusercontent.com/17639389/41402733-5fc2bdda-6fc3-11e8-80ca-e76c5c5bfc1c.jpg)

**Comment by samael205** [comment]
**Hint ** This only happens when you select a character that is attached to the selection box.

**Comment by samael205** [comment]
It only occurs in those selections that involve an edge. As you see in the image "then" is attached to the bounding-box of the object
![fabricerror](https://user-images.githubusercontent.com/649740/41414258-dab81eaa-6fe5-11e8-8f0a-e6639b8644fd.png)

**Comment by Tsourdox** [comment]
@samael205 Not true, scroll faster and it will happen for selected words in the middle as well (or even if the cursor is in the middle)

**Comment by samael205** [comment]
![scrollfast](https://user-images.githubusercontent.com/649740/41430432-472f43d6-7010-11e8-838f-b68d39ce4cba.jpg)

Scrolling fast at my home

**Comment by asturur** [comment]
Yes this is a problem, i noticed it too.

So the Itext does not clear all the upper canvas to save on speed. It clears the part where it is.
If you scroll before the cleaning happens this is what you see.

I think at least setZoom ( and setViewportTansform ) should take care of cleaning before reRendering

**Comment by Tsourdox** [comment]
Wow, that was fast! thx 🙏🏅

**Comment by eldstrom** [comment]
@asturur  Still having this issue. Was this fix removed? I tried to override setViewportTansform and apply it again on the static canvas since it was only there on the normal canvas but i still have this problem.

**Comment by asturur** [comment]
no that i know of

**Comment by eldstrom** [comment]
We had set renderOnAddRemove to false so the fix was never hit. Changed that and it now looks as it should so the fix still works.
I did try to do the clearContextTop and requestRenderAll in my own code but it had no effect there, not sure why but i will try this now and see if it causes any issues for us.

**Comment by asturur** [comment]
i would expect renderOnAddRemove to not interfere with the fix. Why it does? can you help me understand?

**Comment by eldstrom** [comment]
The only code that was added in setViewportTransform in canvas.class.js that does something is this code:

`if (this.renderOnAddRemove && this._activeObject && this._activeObject.isEditing) {
        this._activeObject.clearContextTop();
}`

As i understand it, it is `clearContextTop `method that clears the marked text + cursor trail before each re-render. The if statement here requires `renderOnAddRemove` to be true.

In static_canvas.class.js on line 698 you have this line:
`this.renderOnAddRemove && this.requestRenderAll();`
Now, my js is a bit bad but to me that looks like also there, `renderOnAddRemove` is required to tun `requestRenderAll`.

**Comment by asturur** [comment]
that is weird! can you open a separate bug ticket so i can track it? Is also important that you make a jsfiddle that makes the problem actually happen so that it can be used to see if the fix is effective.
