### ISSUE TITLE
Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by solanki-ankit** [fabricjs/fabric.js#5046]
```
fabric.min.js?_=1529039733850:1 Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at i.__toDataURL (http://teacherworkshop.in/js/fabric.min.js?_=1529039733850:1:118674)
    at i.__toDataURLWithMultiplier (http://teacherworkshop.in/js/fabric.min.js?_=1529039733850:1:118409)
    at i.toDataURL (http://teacherworkshop.in/js/fabric.min.js?_=1529039733850:1:117946)
```

I am getting above error.

I have created powerpoint like functionality with one website. which we can use in any other project like a third-party tool.

now I am getting above error with I use my site in another project as third party tool. if I am not used my site as the third party then it woks fine.

`var dataURL = canvas.toDataURL();`

in above code, I getting this error.

I have loaded canvas I just need to that canvas convert to dataURL but getting above error.

**Comment by joturako** [comment]
When you load image from the web with `fabric.Image.fromURL` the 3rd args must have the following value:
```
{
...
   crossOrigin: "Anonymous",
...
}
```
Note the uppercase characters.

**Comment by solanki-ankit** [comment]
I am not loading an image from URL. When the page renders I am creating one canvas drow what I want then I save this canvas as an image so before saving canvas image save API I need DataURL of the canvas. And getting this error.

**Comment by joturako** [comment]
Ah, I see you said you're using your tool (at site A) from inside another site (B). That may have the cross origin problem. I suspect you can't call toDataURL from your current site B, when the canvas is in your site A. I haven't meet this case yet, so it's just my guess. Please investigate.

**Comment by asturur** [comment]
if is not reproducible in a fiddle is not a problem we can take care of.

**Comment by jinchengyang** [comment]
i set useCORS to ture can solve this issue.

`html2Canvas(document.querySelector('#pdfDom'), {
    useCORS: true
  }).then( (canvas)=> {
let pageData = canvas.toDataURL('image/jpeg', 1.0);
console.log(canvas);
}`

**Comment by Uhelliton** [comment]
> Quando você carrega uma imagem da Web com `fabric.Image.fromURL`o terceiro argumento, deve ter o seguinte valor:
> 
> ```
> {
> ...
>    crossOrigin: "Anonymous",
> ...
> }
> ```
> 
> Observe os caracteres maiúsculos.

Nice.....

**Comment by AbingPj** [comment]
> > Quando você carrega uma imagem da Web com `fabric.Image.fromURL`o terceiro argumento, deve ter o seguinte valor:
> > ```
> > {
> > ...
> >    crossOrigin: "Anonymous",
> > ...
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Observe os caracteres maiúsculos.
> 
> Nice.....

How did you apply it? 
I try this but it doesn't  work
`  var getRandomInt = fabric.util.getRandomInt;
    // var coord = this.getRandomLeftTop();
    fabric.Image.fromURL(
      "https://www.osfhealthcare.org/blog/wp-content/uploads/2019/08/apples-OG-765x310.jpg",
      function (image) {
        image
          .set({
            left: 0,
            top: 0,
            angle: getRandomInt(-10, 10),
          })
          .scale(0.75)
          .setCoords();

        self.canvas.add(image);
      }
      ,{crossOrigin: "Anonymous"}
    );`

**Comment by joturako** [comment]
@AbingPj this apply to very old version dated back in 2018.

I tried your image here and it appear to work without a problem: http://jsfiddle.net/xvhmwuek/ (in this jsfiddle fabricjs version at the time of comment is 4.4.0)

Next time don't resurrect old issue please.

**Comment by AbingPj** [comment]
> @AbingPj this apply to very old version dated back in 2018.
> 
> I tried your image here and it appear to work without a problem: http://jsfiddle.net/xvhmwuek/ (in this jsfiddle fabricjs version at the time of comment is 4.4.0)
> 
> Next time don't resurrect old issue please.

Okay,. Sorry @joturako

**Comment by NhatLam310399** [comment]
> @AbingPj this apply to very old version dated back in 2018.
> 
> I tried your image here and it appear to work without a problem: http://jsfiddle.net/xvhmwuek/ (in this jsfiddle fabricjs version at the time of comment is 4.4.0)
> 
> Next time don't resurrect old issue please.

Hi bro, I just try use my url at your link. It return url like i want. But apply my code then get error same **solanki-ankit** .

**Comment by zhijiejia** [comment]
```js
fabric.Image.fromURL(currentHit.data, function (img) {   
      canvas.setBackgroundImage(img, canvas.renderAll.bind(canvas), {
        width: canvas.width, 
        height: canvas.height,
      });
    }, {crossOrigin: 'anonymous'}
);

**Comment by talbertherndon** [comment]
### My Problem:
When using Fabric.js to load images from **Google Cloud Storage** onto a canvas, you may encounter a "SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement'" due to tainted canvases. Additionally, you might face a CORS error with a message like "no 'access-control-allow-origin' header."

### Solution:

1. **In Your Fabric.js Code:**
   ```javascript
   fabric.Image.fromURL(
       {your image url from Google Cloud Storage},
       function (img) {
           // Adjust scaling as needed
           img.scaleToWidth(fc.current.width);
           img.scaleToHeight(fc.current.height);
           canvas.setBackgroundImage(
               img,
               canvas.renderAll.bind(fc.current),
               {
                   originX: "left",
                   originY: "top",
               }
           );
       }.bind(this),
       {
           crossOrigin: 'anonymous'
       }
   );
   ```
   Ensure that you include `crossOrigin: 'anonymous'` in the options when loading the image with `fabric.Image.fromURL`.

2. **Configure CORS in Google Cloud Storage:**
   - Create a `cors.json` file with the following content:
     ```json
     [
         {
             "origin": ["*"],
             "method": ["GET", "HEAD"],
             "responseHeader": ["Content-Type"]
         }
     ]
     ```
   - Upload the `cors.json` file to your Google Cloud Storage bucket:
     ```bash
     gsutil cors set cors.json gs://{your-bucket-name}
     ```
   - If needed, re-upload your files to the bucket for the changes to take effect.

By setting `crossOrigin: 'anonymous'` in Fabric.js and configuring the CORS policy in Google Cloud Storage, you allow the canvas to load images cross-origin without security errors. The provided CORS policy allows any origin (`"*"`) to make `GET` and `HEAD` requests with the necessary headers.

This solution should resolve the "tainted canvases" issue and address the CORS-related errors during canvas operations like `toDataURL`.
