### ISSUE TITLE
text stroke not updating after changing color

### ISSUE THREAD

**Issue by Sunilthecoder007** [fabricjs/fabric.js#5047]
when i apply stroke width on selected object with a input then its work but when i change stroke color it does not change after setting new color but it will updated later if i do any other change on object like change stroke width or drag it to resize then last added stroke color applied but not after applying it.

I am applying stroke on text like this:

**object.stroke = color;
canvas.renderAll();**

i am on version 2.2.4

**Comment by asturur** [comment]
please read about the caching here:

http://fabricjs.com/fabric-object-caching

**Comment by cbcwebs** [comment]
ok so is there any workoround for my situation or i need to turn off objectCaching  to use that live stroke update feature
