### ISSUE TITLE
BoundingRect not wrap text when change font weight or font style

### ISSUE THREAD

**Issue by mediumhust** [fabricjs/fabric.js#5050]
## Version
2.3.3

## Test Case
https://jsfiddle.net/o6v7yhmq/
Use google font Roboto

## Steps to reproduce
Zoom text to render canvas again ( when font Roboto loaded )
## Expected Behavior
BoundingRect wrap text when change font weight or font style
## Actual Behavior
https://image.prntscr.com/image/woK7n4Y0Ql6PA3wuqyXRAg.png

**Comment by asturur** [comment]
http://fabricjs.com/docs/fabric.util.html#.clearFabricFontCache
