### ISSUE TITLE
Export Circle  with endAngle greater than 2 * Math.PI to SVG not correct

### ISSUE THREAD

**Issue by mediumhust** [fabricjs/fabric.js#5053]
## Version
2.3.3

## Test Case
https://jsfiddle.net/c3gop1z9

## Steps to reproduce
Add fabric.Circle with endAngle greater than 2 * Math.PI
## Expected Behavior
http://prntscr.com/jx3v16
## Actual Behavior
http://prntscr.com/jx3v6q
http://prntscr.com/jx3vix
Canvas export to SVG is not the same with canvas and lost a quotes mark

**Comment by asturur** [comment]
i think that extra quote has been solved by some commit.

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/commit/efa490fff020b287561a31d8d388850b5762152c
