### ISSUE TITLE
SVG image not correctly render on canvas.

### ISSUE THREAD

**Issue by maskingg** [fabricjs/fabric.js#5055]
## Version
2.3.3

## Steps to reproduce
I have made an svg image using some text and image and get the svg data using toSVG() method.When I have load that svg image using loadSVGFromURL method and render on the canvas but image is not correctly render on the canvas .When I opened that image on browser its working fine.
## Expected Behavior
svg image should be correctly render on canvas like actual image
## Actual Behavior
svg image should be correctly render on canvas like actual image

**Comment by asturur** [comment]
Not all SVG can imported back, especially the one with text. This is a know issue already open in the tracker
