### ISSUE TITLE
Android IText keyboard not staying up

### ISSUE THREAD

**Issue by somethingsgottagive** [fabricjs/fabric.js#5056]
Has anyone encountered problems using the itext for androids? It works fine on pc browsers and ios but on android the keyboard comes up for a brief second then disappears making it impossible to write.  
I've tested it in several devices and it's the same problem.

**Comment by asturur** [comment]
can you make a small fiddle that opened in android triggers the problem? or host a simple html somewhere if the fiddle is too complicated for a phone

**Comment by somethingsgottagive** [comment]
@asturur it's a little complicated for a fiddle but basically what im doing is drawing a rectangle with the mouse/touch and then inserting text on it adjusting its size like below:
`    drawText() {
      const txt = 'Text here';
      const coords = this.getTopLeftRectangleCoords();
      const widthToFont = 155 / 37;

      const fontFamily = 'Helvetica';

         this.fontSize = this.getTextRectangleWidth() / widthToFont;
        
       if (this.fontSize < 70 / widthToFont) {
        this.fontSize = 70 / widthToFont;
      }
      this.fText = new fabric.IText(txt,
        { fontFamily, left: coords.x, top: coords.y, fontSize: this.fontSize },
      );
      this.fText.setColor(this.canvas.freeDrawingBrush.color);
      this.fText.setFontFamily(fontFamily);
      this.fText.bypassHistory = true;
      this.fText.bypassRemoveEvent = true;
      this.canvas.add(this.fText);
      this.canvas.setActiveObject(this.fText);
      this.fText.enterEditing();
      this.fText.hiddenTextarea.focus();
      this.fText.hiddenTextarea.setAttribute('wrap', 'off');
      var style = this.fText._calcTextareaPosition();
      this.fText.hiddenTextarea.style.cssText = 'position: absolute; top: ' + style.top +
       '; left: ' + style.left + '; z-index: -999; opacity: 0; width: 1px; height: 1px; font-size: 16px;!important' +
       ' line-height: 1px; paddingｰtop: ' + style.fontSize + ';';

      this.fText.selectAll();
      this.fText.on('editing:exited', () => {
        const finalText = fabric.IText.fromObject(this.fText.toObject());
        this.canvas.remove(this.fText);
        finalText.bypassHistory = false;
        finalText.bypassRemoveEvent = false;
        if (finalText.getText() !== 'Text here' && finalText.getText() !== '') {
          this.canvas.add(finalText);
          finalText.initBehavior();
          store.commit('changeInteractionMode', 'DRAG');
        }
      });
    }`

**Comment by brunolm** [comment]
On Android it doesn't happen to me.

On iPhone it does, my workaround is:

```
function fixKeyboard() {
  const a = canvas.getActiveObject();

  setTimeout(() => {
    a.hiddenTextarea.focus();
  }, 100);
}

textbox.on('editing:entered', fixKeyboard)
```

**Comment by asturur** [comment]
i m  sorry for not answering before.
Is unclear what your fiddle is doing, if you cannot reproduce in a small fiddle without too much custom code, i can't really help.
Please if you did not solve already, organize a reproducible case to post here and i ll reopen/investigate the issue.
