### ISSUE TITLE
allowed to draw lines within the specified range

### ISSUE THREAD

**Issue by zhishaofei3** [fabricjs/fabric.js#5058]
## Version
2.3.3

## Test Case
https://jsfiddle.net/zhishaofei3/bmk6jvgh/9/

## Steps to reproduce
canvas = new fabric.Canvas('c')
canvas.isDrawingMode = true

## Expected Behavior
in free drawing mode, Only allowed to draw lines within the specified range, such as canvas width height inside
## Actual Behavior
Do not lift the mouse, you can draw outside the canvas

**Comment by asturur** [comment]
is it works like that, mouse move is kept working and is not removed, is actually attached to the window.
What is the issue here?

**Comment by zhishaofei3** [comment]
I using 'group' to calculate all object width height and scale all object
I don't want user drawing line to outside the canvas 
this will affect my calculation of the full width height

```
<canvas width="1000" height="750" id="c">

var img = new Image()
img.src = 'http://test-ic-static.vipkid.com.cn/course/material/DEMO1-U1-LC1-L2/5827cbca05bdb0dcdf20b8d6b261ec34.jpg'
img.crossOrigin = 'anonymous'
img.addEventListener('load', () => {
  this.fabricImg = new fabric.Image(img, {width: img.width, height: img.height, crossOrigin: 'anonymous'})
  this.fabricImg.crossOrigin = 'anonymous'
  let scale = this.coumputeWH(img.width, img.height)
  this.fabricImg.scaleX = scale // this.fabricImg.width == 1000
  this.fabricImg.scaleY = scale // this.fabricImg.height == 750
})

var group = new fabric.Group(this.myCanvas.getObjects())
group.width // 1000
group.height // 750
```
but when user drawing line outside the canvas area

var group = new fabric.Group(this.myCanvas.getObjects())
group.width // > 1000
group.height // > 750
I can't calculate width and height correctly

https://github.com/zhishaofei3/WritingCorrection/blob/master/src/App.vue
line:216 setZoom method

**Comment by asturur** [comment]
This is something you have to fix in your application. Can't really help. Add an event for mouseout on the upperCanvasElement and stop drawing.

Not a library issue anyway.
