### ISSUE TITLE
loadSVGFromURL is not working In firefox

### ISSUE THREAD

**Issue by ravipatel2293** [fabricjs/fabric.js#5059]
Hi,

I am using a **loadSVGFromURL()** method to get the objects from the SVG url.
Below is my code:
 fabric.loadSVGFromURL("some svg url", (objects, options) => {
      console.log(objects);
 });
But here i'm not getting objects only in Firefox. I'm getting _**objects is null**_ .
Can anybody give any idea why it is giving objects null in firefox.

Thanks in advance.

**Comment by asturur** [comment]
Please make a fiddle that loads that SVG and breaks in firefox
