### ISSUE TITLE
Not allowed to scaling objects programatically selected

### ISSUE THREAD

**Issue by samael205** [fabricjs/fabric.js#5060]
## Version
2.3.3

## Test Case
https://jsfiddle.net/samael205/bx7xrysn/26/

## Steps to reproduce

When I create a selection with javascript, I have no way to modify the scaling with the handles.

Also in my development environment, I have a procedure that does the following:

I create a programmed selection and I store it in a variable, to later create that same selection again, I perform some operations with different objects, selecting and deselecting those objects, and when I finish active the selection that I had previously created, but when I go to move, the canvas returns the top and left negative coordinates.

the code of the procedure:
```
function actualizarPropiedadesWorker(){
        var selection = new fabric.ActiveSelection(canvas.getActiveObjects(), {canvas: canvas});
        canvas.forEachObject(function(obj){
            
            if(obj.type == "rect" ){
                canvas.setActiveObject(obj);
                // do something
                canvas.discardActiveObject().renderAll(); //Deselecciono el objet
            }
        });
        canvas.setActiveObject(selection);

    }
```

left -142
top -111.5
and the object type is activeSelection

## Expected Behavior

I am allowed to modify the scaling on objects selected programatically

## Actual Behavior

I am not allowed to moidfy the scaling on objects selected programatically

**Comment by asturur** [comment]
```
var selection = new fabric.ActiveSelection(canvas.getActiveObjects(), {canvas: canvas});
```

i do not think you can do that. you are creating a selection from objects already selected.
This is help for custom code, please open a stackoverflow question and post the link here, happy to help, also there you find more eyes than here.

**Comment by samael205** [comment]
@asturur https://stackoverflow.com/questions/50983846/not-allowed-to-scaling-objects-programatically-selected
