### ISSUE TITLE
Groups clip contents

### ISSUE THREAD

**Issue by wjk** [fabricjs/fabric.js#5061]
## Version
1.7.20

## Test Case
<https://jsfiddle.net/0o2dbm7j/11/>

## Steps to reproduce
Load the fiddle; the problem should be self-evident.

## Expected Behavior
The line should not be clipped visually in its bottom-right corner, and the bounding box should encompass the entire line as it appears visually.

## Actual Behavior
The group that contains the line should expand (either automatically or via manual manipulation; however, please note I haven't found a successful way to do it manually yet) to display the entire line.

Note that this bug only reproduces if the line is placed within a group, and the line width is then adjusted after the group has been displayed. Setting `dirty = true`, etc, seems to have no effect.

Thanks for taking a look at this!

**Comment by wjk** [comment]
Here's a version of the fiddle using Fabric 2.3.3: <https://jsfiddle.net/0o2dbm7j/21/>

**Comment by HeChengjun** [comment]
Maybe it can help you
http://fabricjs.com/docs/fabric.js.html#line18451  
https://jsfiddle.net/0o2dbm7j/33/

**Comment by asturur** [comment]
Yes @HeChengjun is right, if you modify an object after grouping, you need to call at least that 2 functions in order to update it.
