### ISSUE TITLE
Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by santosmken** [fabricjs/fabric.js#5062]
Hello, I just want to know if how can I fix the `Tainted Canvas` when doing the `toDataURL()` method. It's working when Google chrome `CORS` plugin is ON and `fabric.util.loadImage` or `fabric.Image.loadFromURL` crossOrigin was set. But when the app is already in the Live (Azure: 'https'), exporting the canvas doesn't work specially if crossOrigin is in the code. Here is the fiddle with an image coming from our blob storage: https://jsfiddle.net/santosmken/v3n8fo2q/14/

**Comment by scriptspry** [comment]
Wrong params. This works https://jsfiddle.net/v3n8fo2q/16/

**Comment by santosmken** [comment]
@scriptspry not working for me

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/41891645-9a9681c0-7915-11e8-91f5-39082f631fc1.png)

i do not see any crossOrigin header on the response, you have to se the origins header on the server too.

**Comment by santosmken** [comment]
@asturur I've set proxy server to fix the crossOrigin, but now I still have the error `Tainted Canvas`. First I set image as a background of the canvas. After that I tried to `console.log` the `this.canvas.toDataURL()` but it return the `Tainted Canvas` error. Any possible solution that you can suggest?

**Comment by gongph** [comment]
+1

**Comment by railway17** [comment]
> [@asturur](https://github.com/asturur) I've set proxy server to fix the crossOrigin, but now I still have the error `Tainted Canvas`. First I set image as a background of the canvas. After that I tried to `console.log` the `this.canvas.toDataURL()` but it return the `Tainted Canvas` error. Any possible solution that you can suggest?

Hey, @santosmken 
Did you get a solution for this?

**Comment by gongph** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
