### ISSUE TITLE
viewportTransform affects Object.toDataURL

### ISSUE THREAD

**Issue by Aubron** [fabricjs/fabric.js#5063]
## Version
2.3.3

## Test Case
https://codepen.io/anon/pen/eKKaVr

## Steps to reproduce

1. Create an image object.
2. Scale the viewport
3. image.toDataURL()

## Expected Behavior
a dataURL that represents the current state of the image

## Actual Behavior
a dataURL that zooms (and inherently crops) the image based on the viewport transform of the canvas.

Somewhat (but not completely) related to #4602

**Comment by asturur** [comment]
oh i see were the problem comes from.
toDataUrl for the object has this weird bejaviour of representing the object with the angle and everything else.
But getting the viewport involved is indeed wrong.
This is an easy fix.

**Comment by Aubron** [comment]
All this sounds good. In my tests passing `true` to getBoundingRect does fix the problem. I have some other issues with photos with filters (I'm using this to extract filtered versions of images for video processing), but I'll wait til your changes are in, since the 'object export' use case is what we're going for, and then test moving the system and seeing if the issues persist.

(Currently we're doing)
```
if (image.filters && image.filters.length > 0 && image._filteredEl) {
          // put a version of the image to s3 that represents it with filters.
          results.push((
            new Promise((complete, reject) => {
              fetch(image._filteredEl.toDataURL('png'))
```

**Comment by asturur** [comment]
that toDataURL from _filteredEl is a plain javascript toDataUrl and is not the fabricJS one. So for that if there is a problem, is probably not a fabricJS one.

**Comment by Aubron** [comment]
Sorry, I misspoke, we've been using that one because of some weird inconsistencies we saw with fabric's toDataURL and filtered images.

We were using it expecting it to be an object export utility though. Hearing that it's meant to include the object's properties on the canvas may actually explain all of those away.

**Comment by asturur** [comment]
When i arrived, 4 years ago, it was already like that. I have no idea what was the original idea behind that method. I do think that now, a way to export it with neutral properties and another to export it as you see it, is fine and do not require any big effort

**Comment by asturur** [comment]
Opened a small PR, i was wondering how this should work when you target an object that is inside a group. what the withoutTransform should do?
