### ISSUE TITLE
Copy & paste custom object - can't Paste

### ISSUE THREAD

**Issue by novacek78** [fabricjs/fabric.js#5064]
## Version
2.3.3

## Test Case
http://jsfiddle.net --- does not support Fabric 2.3.3 

## Steps to reproduce
1. create custom Class exactly like here: http://fabricjs.com/cross
2. add new object of that Class to the Canvas
3. try to Copy & Paste that object like here: http://fabricjs.com/copypaste
4. Copy works fine, Paste throws an error in Console: "**this._render is not a function**" pointing into FabricJS library - to this line:

```
drawObject: function(ctx) {
      this._renderBackground(ctx);
      this._setStrokeStyles(ctx, this);
      this._setFillStyles(ctx, this);
      this._render(ctx); // <--- crashes here
},
```

## Expected Behavior
Creates a clone object after "Pasting" copied object.

## Actual Behavior
Throws an error into Console: **this._render is not a function**

**Comment by novacek78** [comment]
Thank you!
Would be great to mention it in the demos/tutorials.

**Comment by asturur** [comment]
That tutorial is missng at least a `type: 'cross'` to work correctly with clone/restore
