### ISSUE TITLE
Custom fonts in Fabric on Node example not working

### ISSUE THREAD

**Issue by adtm** [fabricjs/fabric.js#5065]
## Version
2.3.0

### Custom fonts in Fabric on Node
http://fabricjs.com/fabric-intro-part-4#node 

## Steps to reproduce
Just install fabric.js and run the example

## Expected Behavior
I should be able to load custom fonts in my `node` application.

## Actual Behavior
I get the error: `fabric.nodeCanvas.Font is not a constructor`;

**Comment by adtm** [comment]
Update: after clearing everything and reinstalling the script now just hangs.
I suspect at this place: 
```
var font = new fabric.nodeCanvas.Font(
	"Ubuntu",
	__dirname + "/fonts/Ubuntu-Regular.ttf"
);
```

**Comment by alejandroLoz** [comment]
same here TypeError: fabric.nodeCanvas.Font is not a constructor
this is what I get when I do a console.log(fabric.nodeCanvas)

{ [Function: Canvas]
  version: '1.6.12',
  cairoVersion: '1.10.2',
  Context2d: { [Function: CanvasRenderingContext2D] parseFont: [Function] },
  PNGStream: [Function: PNGStream],
  PDFStream: [Function: PDFStream],
  JPEGStream: [Function: JPEGStream],
  Image: { [Function: Image] MODE_IMAGE: 1, MODE_MIME: 2 },
  ImageData: [Function: ImageData] }

Font won't seem to be there... any idea why?

**Comment by asturur** [comment]
cleaned for canvas2
