### ISSUE TITLE
fabric object has no CacheContext 

### ISSUE THREAD

**Issue by rottesindhuri** [fabricjs/fabric.js#5067]
var fabricArrowFactory = function(annotationWrapper, options, viewport) {
      // reset minCacheSideLimit in fabric to take advantage of GPU and better performance
      // we set this to 0 in ruler/arrow because of rendering issue
      fabric.minCacheSideLimit = 0;

      var cacheProperties = fabric.Object.prototype.cacheProperties.concat();
      cacheProperties.push('x1','x2','y1','y2');

      /**
       * Arrow class
       * @class fabric.Arrow
       * @extends fabric.Object
       * Based off the fabric.Object class
       * @see {@link fabric.Object#initialize} for constructor definition
       */
      fabric.Arrow = fabric.util.createClass(fabric.Object, /** @lends fabric.Arrow.prototype */ {
       cacheProperties: cacheProperties,

        /**
         * Constructor
         * @param {Object} [options] Options object
         * @return {fabric.Arrow} thisArg
         */
        initialize: function(options) {
          options = options || {};
          this.callSuper('initialize', options);

          // this should get called when creating an annotation with data from the web service
          // that needs to be converted from ws to viewport coords first
          if(typeof options.points == 'undefined') {
            this.setViewportCoords(options);
          }     
          else {
            // sets x/y, height/width, left/top values
            this.initObjectProperties(options);
          }

          // setting type on this object instead of inheriting from rect class because it's more explicit for later
          this.type = options.type; 
          this.annotationWrapper = annotationWrapper;
          var visibility = (options.visible === true || options.visible === null || typeof options.visible === 'undefined') ? true : false;

          this.set({
            'originX': 'left',
            'originY': 'top',
            'transparentCorners': false,
            'includeDefaultValues': false,
            'borderColor': viewerConstants.colorConstants.red,
            'cornerColor': viewerConstants.colorConstants.red,
            'selectable': false, //we don't want annotations to be selectable unless selection tool is selected
            'strokeWidth': viewerConstants.ANNOTATION_CONSTANTS.DEFAULT_PROPERTIES.DEFAULT_ANNOTATION_WIDTH,
            'stroke': options.stroke,
            'angle': options.originalAngle || options.angle || 0,
            'visible': visibility,
            'hasControls': false,
            'lockMovementX': true,
            'lockMovementY': true            
          });
        },

        /**
         * @private
         * @param {CanvasRenderingContext2D} ctx Context to render on
         */
        _render: function(ctx, noTransform) {
          if(angular.isUndefined(ctx)){
            return;
          }

          var objProperties = this._calcArrowPtsAndDimensions();
          ctx.save();

          // For some reason, this object's transform is not set properly
          // It seems like it's set at half the scale. It should always be 1.
          // Reseting will set it back to [1,0,0,1,0,0]
          ctx.resetTransform();

          var startPt = this._relativePointFromAbsolute({ 'x': objProperties.adjustedX1, 'y': objProperties.adjustedY1 });
          var endPt = this._relativePointFromAbsolute({ 'x': objProperties.adjustedX2, 'y': objProperties.adjustedY2 });
          var secondPt = this._relativePointFromAbsolute({ 'x': objProperties.headSecondPtX, 'y': objProperties.headSecondPtY });      
          var thirdPt = this._relativePointFromAbsolute({ 'x': objProperties.headThirdPtX, 'y': objProperties.headThirdPtY });
                    
          // draw line
          ctx.lineWidth = this.strokeWidth;
          ctx.moveTo(startPt.x, startPt.y);
          ctx.lineTo(endPt.x, endPt.y);
          // draw arrow head - we keep stroke around arrow head
          // or else there are minor imperfections that are visible
          ctx.lineTo(secondPt.x, secondPt.y);
          ctx.lineTo(thirdPt.x, thirdPt.y);  
          ctx.lineTo(endPt.x, endPt.y);   

          // ctx.miterLimit=5;
          ctx.lineJoin = 'bevel';     
          ctx.strokeStyle = this.stroke || ctx.fillStyle;
          this.stroke && this._renderStroke(ctx);

          var origFill = this.fill;
          ctx.fillStyle = this.stroke || ctx.fillStyle;
          this.fill = ctx.fillStyle;
          this._renderFill(ctx);
          
          // restore ctx and this.fill to orig values
          this.fill = origFill;
          ctx.restore();          
        },
 
onMouseMove: function(mousePointer) {
          if (!isNaN(mousePointer.x) && !isNaN(mousePointer.y)) {
            this.set({
              x2: mousePointer.x,
              y2: mousePointer.y
            });

            // sets width/height, left/top
            this.initObjectProperties();
            if(this._cacheContext){
              var cacheCanvasWidth = this._getCacheCanvasDimensions().width;
              var cacheCanvasHeight = this._getCacheCanvasDimensions().height;
              this._cacheContext.clearRect(0,0,cacheCanvasWidth,cacheCanvasHeight);
              this._render(this._cacheContext);
            }
            
          }
        },

**Comment by asturur** [comment]
Hello, this issue will be close since a failing fiddle with a small reproducible case is missing.
This is more a quesiton fit for stackoverflow.com, if you opened a question there too, please post the link here.
