### ISSUE TITLE
iOS Safari Stretches HEVC videos with Rotation

### ISSUE THREAD

**Issue by Aubron** [fabricjs/fabric.js#5069]
## Version
2.3.3

## Test Case
https://codepen.io/anon/pen/VdGbLd?editors=1010

## Steps to reproduce
use iOS (currently using 11.latest)
try and put a recorded video onto a fabric canvas when it has orientation based rotation

## Expected Behavior
Video renders with the proper dimensions and pixels.

## Actual Behavior
Video renders with the proper dimensions, but with the pixels stretched inappropriately across it.

I assume that internally the phone is rotating the video element, and inherently reporting the correct width and height, but not one of our calls. May not be fixable, but it's a pain in the ass for my use case.

**Comment by asturur** [comment]
i cannot see anything in the codepen.

**Comment by Aubron** [comment]
Are you viewing in iOS? It's a HEVC mov file, so only very recent safari and/or iOS can see it

https://caniuse.com/#feat=hevc

**Comment by asturur** [comment]
ok with safari i can reproduce.
I think this should happen with any video that has orientation right?

Is this orientation available as an attribute? what happens if you do not set width and height at all?

How can we compare with chrome/firefox with a normal file?

**Comment by Aubron** [comment]
So to answer some of these questions:

https://codepen.io/AubronWood/pen/WygKrj

Not setting element height and width directly doesn't seem to change anything. It still creates an object with the correct dimensions, but with the pixels mapped incorrectly.

As far as how to get orientation, it seems to only be embedded into the file as metadata, which would require something like a FileReader to extract, if I'm not mistaken. Add to that that the browser support is spotty and in flux, and this starts to look like a real headache to fix reliably.

**Comment by Aubron** [comment]
Both good points.

I'll follow up on this and see if i can reproduce with vanilla canvas.

**Comment by asturur** [comment]
oh i m sure you can, i was just wondering if is just something they did not
think of yet, and shipped this orientation support without checking.

2018-06-26 18:06 GMT+02:00 Aubron Wood <notifications@github.com>:

**Comment by asturur** [comment]
Did you manage to replicate in plain js?

**Comment by Aubron** [comment]
I haven't yet, but I'm hopping back on this this week.
