### ISSUE TITLE
Image quality issue

### ISSUE THREAD

**Issue by monis01** [fabricjs/fabric.js#5073]
Hi 
I am using fabric v '1.6.2', the exported image quality is not good.  I have working area for user where user can add text/images/background etc. and have options for sizes between 1-12 inches, so based on user selection say ` 4" X 4"` rectangle  we provide possible area to play with with canvas (not exact `4" x 4"`) and user do all the activities and when submitting the canvas I scale the canvas to the desired result of `4" x 4" ; @72dpi` and at server end using iMagick to get image@300dpi and converting to cmyk colors for printing. The output comes out to be of low quality with blurriness.

(1) Image at workable area
![screenshot from 2018-06-27 13-17-24](https://user-images.githubusercontent.com/7036532/41960228-dd11edbc-7a0c-11e8-9836-a0144ffb7654.png)

(2) Output image @300 dpi
![file_1530084442](https://user-images.githubusercontent.com/7036532/41960309-1306b0ba-7a0d-11e8-82bd-afcaea14b67b.jpg)

(3)output Image @72dpi
![file_1530084520](https://user-images.githubusercontent.com/7036532/41960360-2c4bb66a-7a0d-11e8-9fec-9b33121c2cc5.jpg)

(4) actual image
![121](https://user-images.githubusercontent.com/7036532/41960417-515399d2-7a0d-11e8-8b32-0771e7d19156.jpg)

I have seen few answers saying regarding usage of `toDataURL({multiplier: ratio to be scaled})` I tried this but it hides the entire image and only show a small section e.g.

(5) CROPPED_CORNER_IMAGE
![file_1530086789](https://user-images.githubusercontent.com/7036532/41961525-54158c7c-7a10-11e8-909c-b09c19d677d2.jpg)
(5.1)
![file_1530087168](https://user-images.githubusercontent.com/7036532/41961533-5898ce3a-7a10-11e8-8d6f-fd376e0f98b3.jpg)
(Ignore differences of colour it's because of cmyk)
I am also clipping the area around my shape and if apply `toDataURL({multiplier: 1})` it works good **but**  if I make changes to `toDataURL({multiplier: with ratio})` (having clipping code) it gives (5)CROPPED_CORNER_IMAGE

Any suggestion for 
(1) clipping is required along with the quality of Image

Thanks

[EDIT]
The code that I am using for scaling before sending data to server :
```
function scaleToDimension(w_value,h_value){
//@ w_value is in inches
//@ h_value is in inches
var newWidth = w_value*72;
var newHeight = h_value*72;
  if (canvasCopy.width != newWidth) {
        var scaleMultiplier = newWidth / (canvasCopy.width);
        var  scaleMultiplierH = newHeight / (canvasCopy.height);
        var objects = canvasCopy.getObjects();
              for (var i in objects) {
                    objects[i].scaleX = objects[i].scaleX * scaleMultiplier;
                    objects[i].scaleY = objects[i].scaleY * scaleMultiplierH;
                    objects[i].left = objects[i].left * scaleMultiplier;
                    objects[i].top = objects[i].top * scaleMultiplierH;
                     objects[i].setCoords();
          }
          var obj = canvasCopy.backgroundImage;
                 if(obj){
                     obj.scaleX = obj.scaleX * scaleMultiplier;
                     obj.scaleY = obj.scaleY * scaleMultiplierH;
                 }
                 canvasCopy.discardActiveObject();
                 canvasCopy.setWidth(canvasCopy.getWidth() * scaleMultiplier);
                 canvasCopy.setHeight(canvasCopy.getHeight() * (scaleMultiplierH || scaleMultiplier));
                 canvasCopy.renderAll();
                 canvasCopy.calcOffset();
}  
scaleToDimension(4,4)  ;
var canvasData =  canvasCopy.toDataURL({multiplier:1}) //@ 1 is because of shape clipping        
```
I was in believe if we provide bigger workable canvas area and then export it then it might improve but I tried that too and no success. 
Any help or suggestion is appreciated 
Thanks again.

**Comment by monis01** [comment]
Thanks @asturur for quick reply 
I can't move to higher version of fabric because most of the work is already done and we are at such stage that's would require to test all the cases again.
For changing canvas if we have limit of 19 inch highest that means 5700 px at max??
I have tried same image for producing bigger size image (1) and (2)
(1) 9x9 @72dpi
![9x9 72](https://user-images.githubusercontent.com/7036532/41964973-044ba934-7a19-11e8-8cbc-c4cd0f4264c2.jpg)

(2) 9x9 @300dpi
![9x9 300](https://user-images.githubusercontent.com/7036532/41964990-100c5cdc-7a19-11e8-8138-eb4bb9f3155f.jpg)
Thanks

**Comment by asturur** [comment]
DPI stands for dot per inch.
So takes the inches, multiply for the number of DPI and that is pixel dimensions.
Changing DPI is just a matter of changing a number in the image that will tell the printer how big is this image.
Nothing else should change, not file size, image data, no image pixel dimenions. If those things change, you are doing it wrong.

Pardon me being direct.

Said so, 1.7.X with cache disabled should be basically a 1.6.x version.

Working with a normal canvas, as big as the user working area, and upscaling with the dataURL is still the best option for me, you should not run a scaling code on your own.

Why to you is not working is unclear to me right now.
Can't you reproduce the dataurl issue in a fiddle?

**Comment by monis01** [comment]
First of all Thanks a lott, that repo `changedpi` really worked (not printed yet) , better quality in comparison from iMagick.
 '_Nothing else should change, not file size, image data, no image pixel dimenions._' I can't say if iMagick is processing something
'_upscaling with the dataURL is still the best option for me_' yes, seen your answers and others for the suggestion of multiplier value in `dataURL`.
As I said at this stage we can't update, because we don't know what may break, but your library has really helped, thanks again.
Btw I am guessing the repo you have shared for DPI would be separate one or any chance to include code in fabric in later versions? and yes for CMYK colours options?
Thanks @asturur  for the help

**Comment by asturur** [comment]
i do not know if png supports cymk at all.

The change dpi is a separate library that i wrote while at work and has been released for free under work domain, it does not fit in fabricjs as a concept, so it won t be included.
