### ISSUE TITLE
Load SVG using Fabric JS "loadSVGFromURL" method all the inner path element not align properly rendered.

### ISSUE THREAD

**Issue by gpisrtandel** [fabricjs/fabric.js#5074]
## Version
2.3.2

## Test Case
https://jsfiddle.net/rtandel/pyLwe1rx/10

## Steps to reproduce
1. Create SVG graphics
2. try to load using "loadSVGFromURL" method

## Expected Behavior
All the path exist in SVG that need to render at proper position.

## Actual Behavior
SVG all path node misplaced.

My SVG File code mention below:

<svg version="1.1" id="guide" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="167.4px" height="167.4px" viewBox="0 0 167.4 167.4" enable-background="new 0 0 167.4 167.4" xml:space="preserve">
	 
<path fill="#FFFFFF" d="M167.4,167.4H0V0h167.4V167.4z M83.699,167.275c46.084,0,83.576-37.491,83.576-83.576
	c0-46.084-37.492-83.574-83.576-83.574S0.125,37.615,0.125,83.699C0.125,129.784,37.615,167.275,83.699,167.275L83.699,167.275z"/>
	
<path fill="#FFFFFF" stroke="#5B5B5B" stroke-width="0.5" d="M167.4,167.4H0V0h167.4V167.4z M83.699,167.275
	c46.084,0,83.576-37.491,83.576-83.576c0-46.084-37.492-83.574-83.576-83.574S0.125,37.615,0.125,83.699
	C0.125,129.784,37.615,167.275,83.699,167.275L83.699,167.275z"/>
	
<path fill="none" stroke="#000000" stroke-width="0.5" d="M83.699,167.275c-46.084,0-83.574-37.491-83.574-83.576
	c0-46.084,37.49-83.574,83.574-83.574s83.576,37.49,83.576,83.574C167.275,129.784,129.783,167.275,83.699,167.275L83.699,167.275z"/>
	
<circle fill="none" stroke="#E92071" stroke-width="0.5" cx="83.699" cy="83.699" r="72"/>

<path fill="none" stroke="#00AAD4" stroke-width="0.5" d="M83.699,142.199c-32.256,0-58.5-26.244-58.5-58.5
	c0-32.256,26.244-58.5,58.5-58.5c32.256,0,58.501,26.244,58.501,58.5C142.2,115.955,115.955,142.199,83.699,142.199L83.699,142.199z"/>
</svg>

**Comment by asturur** [comment]
Please open a JSfiddle where the problem occur and link the svg file so that the bug is easily reproductible.

**Comment by gpisrtandel** [comment]
Hi Andrea Bogazzi , i have update JSfiddle link in ticket detail and my SVG code mention below.
`
<svg version="1.1" id="guide" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="167.4px" height="167.4px" viewBox="0 0 167.4 167.4" enable-background="new 0 0 167.4 167.4" xml:space="preserve">
	 
<path fill="#FFFFFF" d="M167.4,167.4H0V0h167.4V167.4z M83.699,167.275c46.084,0,83.576-37.491,83.576-83.576
	c0-46.084-37.492-83.574-83.576-83.574S0.125,37.615,0.125,83.699C0.125,129.784,37.615,167.275,83.699,167.275L83.699,167.275z"/>
	
<path fill="#FFFFFF" stroke="#5B5B5B" stroke-width="0.5" d="M167.4,167.4H0V0h167.4V167.4z M83.699,167.275
	c46.084,0,83.576-37.491,83.576-83.576c0-46.084-37.492-83.574-83.576-83.574S0.125,37.615,0.125,83.699
	C0.125,129.784,37.615,167.275,83.699,167.275L83.699,167.275z"/>
	
<path fill="none" stroke="#000000" stroke-width="0.5" d="M83.699,167.275c-46.084,0-83.574-37.491-83.574-83.576
	c0-46.084,37.49-83.574,83.574-83.574s83.576,37.49,83.576,83.574C167.275,129.784,129.783,167.275,83.699,167.275L83.699,167.275z"/>
	
<circle fill="none" stroke="#E92071" stroke-width="0.5" cx="83.699" cy="83.699" r="72"/>

<path fill="none" stroke="#00AAD4" stroke-width="0.5" d="M83.699,142.199c-32.256,0-58.5-26.244-58.5-58.5
	c0-32.256,26.244-58.5,58.5-58.5c32.256,0,58.501,26.244,58.501,58.5C142.2,115.955,115.955,142.199,83.699,142.199L83.699,142.199z"/>
</svg>
`

**Comment by gpisrtandel** [comment]
Hi Andrea Bogazzi , i have update JSfiddle link in ticket detail and my SVG code mention below.

<svg version="1.1" id="guide" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="167.4px" height="167.4px" viewBox="0 0 167.4 167.4" enable-background="new 0 0 167.4 167.4" xml:space="preserve">
	 
<path fill="#FFFFFF" d="M167.4,167.4H0V0h167.4V167.4z M83.699,167.275c46.084,0,83.576-37.491,83.576-83.576
	c0-46.084-37.492-83.574-83.576-83.574S0.125,37.615,0.125,83.699C0.125,129.784,37.615,167.275,83.699,167.275L83.699,167.275z"/>
	
<path fill="#FFFFFF" stroke="#5B5B5B" stroke-width="0.5" d="M167.4,167.4H0V0h167.4V167.4z M83.699,167.275
	c46.084,0,83.576-37.491,83.576-83.576c0-46.084-37.492-83.574-83.576-83.574S0.125,37.615,0.125,83.699
	C0.125,129.784,37.615,167.275,83.699,167.275L83.699,167.275z"/>
	
<path fill="none" stroke="#000000" stroke-width="0.5" d="M83.699,167.275c-46.084,0-83.574-37.491-83.574-83.576
	c0-46.084,37.49-83.574,83.574-83.574s83.576,37.49,83.576,83.574C167.275,129.784,129.783,167.275,83.699,167.275L83.699,167.275z"/>
	
<circle fill="none" stroke="#E92071" stroke-width="0.5" cx="83.699" cy="83.699" r="72"/>

<path fill="none" stroke="#00AAD4" stroke-width="0.5" d="M83.699,142.199c-32.256,0-58.5-26.244-58.5-58.5
	c0-32.256,26.244-58.5,58.5-58.5c32.256,0,58.501,26.244,58.501,58.5C142.2,115.955,115.955,142.199,83.699,142.199L83.699,142.199z"/>
</svg>

**Comment by gpisrtandel** [comment]
Hi Andrea Bogazzi , I have done JSfiddle test case in ticket detail and SVG code mention in same.

**Comment by asturur** [comment]
Non of the jsfiddle posted, from version /10 to /15 open nothing that is actually wrong, are incomplete or the svg files are no more reacheable.

I'll close the issue, comment below if you have some reproductible test case
