### ISSUE TITLE
can't trigger select after set object attribute when dragging

### ISSUE THREAD

**Issue by liajoy** [fabricjs/fabric.js#5081]
## Version
2.3.0

## Test Case
https://jsfiddle.net/zxqc1u7k/47/

## Steps to reproduce
1. mousedown on canvas
2. mousemove on canvas to set circle size
3. mouseup
4. can't select circle 
###
If ` canvas.setActiveObject(circle) `, then select can be triggered, but click still not fire select. Like this:
https://jsfiddle.net/zxqc1u7k/50/

**Comment by durga598** [comment]
You need to use `setCoods()` after drawing complete. Here is updated [jsfiddle](https://jsfiddle.net/zxqc1u7k/52/)

**Comment by liajoy** [comment]
@durga598 Thank you. It worked. Why should I use `setCoods` and when should I use `setCoods`?

**Comment by durga598** [comment]
Check the doc [setCoords](http://fabricjs.com/docs/fabric.Object.html#setCoords)
