### ISSUE TITLE
Custom Fonts Rendering in 2.3.3 not working well

### ISSUE THREAD

**Issue by radykal** [fabricjs/fabric.js#5084]
## Version
2.3.3

## Test Case
http://jsfiddle.net/phkfLv6s/3/

The custom font rendering is not working well in fabricjs 2.+. I switched my app to fabricjs 2.+ and now I get notifications from my customers that some custom fonts are not rendered well. In most cases the text is outside of bounding box or the alignment is wrong. It was working with fabricjs 1.6.7. Is this a known issue?

**Comment by asturur** [comment]
http://jsfiddle.net/phkfLv6s/17/

Be sure to use font and create text objects AFTER the font is loaded. Just rendering is not enough

**Comment by radykal** [comment]
Also in your fiddle you can see the issue:
https://drive.google.com/file/d/1sx8lyR4qLNE9rP2WY4KvmlR1J2rxSMpo/view?usp=drivesdk

**Comment by asturur** [comment]
oh but that is the font.
The final d is as wide as the circle on the base and the upper leg is not calculated.

The font is measured as acciratelyas possible with font metrics

**Comment by radykal** [comment]
Ok thank you. I am just wondering, because in 1.6.7 it was working well.
