### ISSUE TITLE
Itext text looks blurry 

### ISSUE THREAD

**Issue by shaangidwani** [fabricjs/fabric.js#5086]
## Version
2.3.3

## Test Case
https://jsfiddle.net/shaangidwani/91y5jb83/5/

## Steps to reproduce
1. Add itext with object caching false or true

## Expected Behavior
Text must be very clear like mspaint or winword.

## Actual Behavior
Text looks blurry

**Comment by asturur** [comment]
Is blurry because is set on half pixels.
Please try to add text on half pixels on winword or mspaint and you will get a simila bluriness

**Comment by shaangidwani** [comment]
but whats the solution. if i set device pixel one still looks blurry. Please help if you can.

**Comment by shaangidwani** [comment]
![image](https://user-images.githubusercontent.com/26000152/42379163-8ca9491e-8147-11e8-81d2-cabb3b324d50.png)


I have attached ms-paint screenshots where font-size is 11 but its looks very clear

**Comment by asturur** [comment]
@shaangidwani i do not have the font face calibri to replicate the same, can you paste and example with Arial and also give the position of it?

**Comment by shaangidwani** [comment]
@asturur sure. I have set the "Arial" font and try to draw a text in microsoft paint. its gives crystal clear fonts. attached screenshot for the same.
Also attached fonts "Times of new roman"

Not sure about position how to get it from ms-paint. Kindly suggest on this.

![image](https://user-images.githubusercontent.com/26000152/42445669-71fee0dc-8391-11e8-9343-657834c50e35.png)
![image](https://user-images.githubusercontent.com/26000152/42445756-bee87908-8391-11e8-81dc-62507e57499a.png)

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/42446306-0e16156a-8376-11e8-8bba-0ea0e8fa463f.png)
![image](https://user-images.githubusercontent.com/1194048/42446336-2a233ba2-8376-11e8-838f-42171f9fc85a.png)

**Comment by asturur** [comment]
Your 11px text is definitely using many pixels compared to canvas one. Aren't you using some sort of high dpi screen?

**Comment by shaangidwani** [comment]
Attached comparision of all the verson. wpaint , fabricjs , ms-paint.

![image](https://user-images.githubusercontent.com/26000152/42448113-c3958ccc-8399-11e8-813d-f176e816b9d6.png)

**Comment by shaangidwani** [comment]
Please let me know if any thing further required. Pls pls pls help me to fix this.

**Comment by asturur** [comment]
on what windows are you? if win 10 can you check you are not using dpi scaling of 125% in display settings?

If you look at your screenshot the 14px font is bigger than then 15px on canvas, something is off.

**Comment by shaangidwani** [comment]
I am on windows 10 . I have attached my display setting. dip scaling 100%. I have check on diffrent machines. i.e. windows 10, windows 7 canvas fonts looks blurry with fabricjs itext and textbox.

![image](https://user-images.githubusercontent.com/26000152/42746103-def66996-88f3-11e8-9391-6c1659c41962.png)

**Comment by asturur** [comment]
your non canvas font is still way bigger than the canvas one, that is why
is more clear.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/42769020-567dfd26-8921-11e8-956c-5c0f2dafe8d8.png)

Those are the apps compared with arial 12px there is basically no difference.
Your native apps are using more pixels than needed and you are seeing a better text, but the fabricJS is as clear as a 12px arial text on canvas can be

**Comment by shaangidwani** [comment]
Is there any solution for display text what native apps are doing for display better text ? Means how to set more pixcel in Itext or Textbox in fabricJS. i really appreciate your help.

**Comment by asturur** [comment]
increase fonts size. Increase the scale.

**Comment by david-mark** [comment]
"increase fonts size. Increase the scale."

Is that really the final resolution for this discussion? :)
