### ISSUE TITLE
Interface 'Group' incorrectly extends interface 'Object'.

### ISSUE THREAD

**Issue by ItsTehStory** [fabricjs/fabric.js#5089]
## Version
2.3.3

## Test Case
I would not know what to include in the fiddle

## Steps to reproduce
`npm install fabric`
## Expected Behavior
Installs fabric
## Actual Behavior
Installs fabric, but I get an implementation problem:
```
my/path/to/node_modules/@types/fabric/fabric-impl.d.ts
(1624,18): Interface 'Group' incorrectly extends interface 'Object'.
  Types of property 'get' are incompatible.
    Type '(prop: string) => any' is not assignable to type '<K extends keyof this>(property: K) => this[K]'.
      Types of parameters 'prop' and 'property' are incompatible.
        Type 'K' is not assignable to type 'string'.
          Type 'keyof this' is not assignable to type 'string'.
            Type 'string | number | symbol' is not assignable to type 'string'.
              Type 'number' is not assignable to type 'string'.
```

So yeah... Any idea on what's going on?

**Comment by asturur** [comment]
i think this is related to typescript?

There is no type definition file for fabricJS, if there is one is obviously wrong.

I do thing that Group extends Object and is correct.

**Comment by ItsTehStory** [comment]
You litterally have said it in the past....
> is based on fabricjs 1.5
> 
> May lead to errors with new versions.

Alright I got to either use fabricjs 1.5 or find updated types.
Thanks!

**Comment by asturur** [comment]
I understand my answer may be read wrong, but as of now, there is no file that you can trust or use with success.

There is an open effort to make one, but apart from initial contribution is not progressing. Please do contribute to it if you know how to.

you find it in the open PRs

**Comment by ItsTehStory** [comment]
No I totally understood your answer! That was my bad for not looking at other threads!
Sadly I'm not good enough to contribute on that... Started using typescript about 2 weeks ago...
I ended up including the libraries without the types actually like you mentioned (I think) in the same thread I'm referring to. As if everything was of type any!
