### ISSUE TITLE
object.toJSON() has wrong position if object is part of a selection

### ISSUE THREAD

**Issue by nisserne** [fabricjs/fabric.js#5092]
I am changing my project from saving all canvas objects in a single JSON to instead saving each object in separate JSONs.

I was using canvas.toJSON() and canvas.loadFromJSON(). 
Now I use object.toJSON() and fabric.util.enlivenObjects().
It basically works, although I am missing real documentation that enlivenObjects() actually takes JSON:-).
[fabric.util documentation](http://fabricjs.com/docs/fabric.util.html#.enlivenObjects)
[deserialize-a-json-object-in-fabric-js example
](https://stackoverflow.com/questions/19361971/deserialize-a-json-object-in-fabric-js
)
 
My problem is that if selecting 2+ objects, object.toJSON() is "polluted" with relative coordinates from the selection. This is not the case when using canvas.toJSON().
I realize objects in the canvas get relative coordinates when part of a selection, but suggest that JSON extracts are not affected by this in neither canvas.toJSON() or object.toJSON().

[See fiddle example here](https://jsfiddle.net/a76qw9nt/21/)

Kindest regards and thanks for your respond.

PS. I tried to work around by extracting object-JSONs from the canvas.toJSON() output by looping through objects using JSON.parse()/stringify(). But it seems that JSON.parse() fails when parsed the canvas.toJSON() output(?).

**Comment by asturur** [comment]
I unerstand the issue, i wonder if we can move the canvas toObject code in the ActiveSelection class so that is solved.

For the other question, JSON.parse is used to parse STRINGS into objects, while toJSON return object type.
a JSON object is just a subset of plain javascript object.

**Comment by nisserne** [comment]
Thanks for your fast comments!

I am not all sure I understand your plans, but I hope that what you are thinking of will make the output from object.toJSON() similar to the output from canvas.toJSON().

Again, not sure about your second explanation. Are you writing that canvas.toJSON() does not return a JSON-string but an "object type"?
My failing idea of a work around was to:
1. get the "valid" canvas.toJSON() output, 
2. convert it to a JS-object using JSON.parse(), and then
3. loop the 'objects' member, converting each to JSON using JSON.stringify().
Definitely just a work around, converting things 3 times.
