### ISSUE TITLE
npm install fabric --save always gives me the version 1.7.22 from 2015 instead of the newest version 2.x.x. 

### ISSUE THREAD

**Issue by kabrice** [fabricjs/fabric.js#5094]
`npm install fabric --save` always gives me the old version `1.7.22` from 2015  instead of the newest version 2.x.x. 
Is it normal ?

**Comment by asturur** [comment]
... no... i ll try.

**Comment by ItsTehStory** [comment]
Was the problem found? Because I've been using fabric's npm version for about as much time as this was posted and I got the right version... (2.3.3)

**Comment by asturur** [comment]
i m sorry i can't reproduce.
