### ISSUE TITLE
Nested shapes overlapping each other (Triangle)

### ISSUE THREAD

**Issue by monis01** [fabricjs/fabric.js#5096]
Hi
I need to create the nested triangles (2 level nesting) with triangle shapes getting reduced in dimensions when going from outside to inside.
Tried on various canvas sizes the triangle overlaps badly with each other. My other shapes e.g. (circle and rectangle working fine)
my code for triangle 
```
var triangleConfig1 = {
strokeWidth= 2;
strokeLineJoin= 'bevil';
stroke= 'blue';
lockScalingX= true;
lockScalingY= true;
lockMovementX= true;
lockMovementY= true;
id="shape";
originX = "center";
originY = "center";
height:canvas.height,
width : canvas.width,
nameOfShape:'triangle'
}

var triangleConfig2 = {
lockScalingX= true;
lockScalingY= true;
lockMovementX= true;
lockMovementY= true;
originX = "center";
originY = "center";
height:canvas.height -(0.250*72), //@ some calculations required
width : canvas.width -(0.250*72), //@ some calculations
...//@ other properties
}

var mainTriangle1 = new fabric.Triangle(triangleConfig1);
var mainTriangle2 = new fabric.Triangle(triangleConfig1);

canvas.add(mainTriangle1,mainTriangle2);

//@ getting result (1)
//@ few other sizes
```
Though they have different properties (circle and triangle), but I believed with similar fashion of providing difference for triangle would produce similar result, but I am wrong.
I tried with polygon as well 
```
//@ example for creating triangle
canvas = new fabric.Canvas('canvas');
var p1 = {left:50,top:50}; var p2 = {left:40,top:60}; var p3 = {left:60,top:60};
var shape = new fabric.Polygon([{x:p1.left, y:p1.top},{x:p2.left, y:p2.top},{x:p3.left, y:p3.top}]);
canvas.add(shape);
//@ see test case (a)
```
but no success, anything I am missing out any direction would be helpful.
P.S. Sorry If I would missing out something very basic, some suggestion or direction would be very helpful.
## Version
1.6.2

## Test Case
a. https://jsfiddle.net/monis/pb43cfmt/

## Expected Behaviour
`//@ something more better like this`
a. https://jsfiddle.net/monis/fts70u51/
Equal size nested triangles

## Actual Behavior
1.  result
![screenshot from 2018-07-10 18-11-12](https://user-images.githubusercontent.com/7036532/42511663-223886d6-8470-11e8-9285-603eb5baeb8f.png)

`//@ other results `
2. 
![screenshot from 2018-07-10 18-12-37](https://user-images.githubusercontent.com/7036532/42511718-4a549e0c-8470-11e8-8c55-429663eefbe3.png)

![screenshot from 2018-07-10 18-12-48](https://user-images.githubusercontent.com/7036532/42511734-52febf24-8470-11e8-831a-c49447dff8f4.png)

![screenshot from 2018-07-10 18-12-58](https://user-images.githubusercontent.com/7036532/42511741-593cbc74-8470-11e8-9cb9-6f03b9097b71.png)

`//@ Other shape example`
![screenshot from 2018-07-10 18-17-44](https://user-images.githubusercontent.com/7036532/42511827-9569c8d6-8470-11e8-9a36-e7be912dda67.png)

![screenshot from 2018-07-10 18-18-02](https://user-images.githubusercontent.com/7036532/42511842-9ced07ee-8470-11e8-9a06-fb372a9fd40a.png)

**Comment by monis01** [comment]
Hi
any update on this ?

**Comment by asturur** [comment]
what is wrong using scale to obtain this effect?

like you know that you want a 5 px difference,
you take scaleFactor = ( height - 5 ) / height
And then you use the old height but with scaleX an scaleY set to scaleFactor and strokeWidth = original / scaleFactor.

If it does not work, setting the width to originalWith * scaleFactor should work too, keeping the center in the same position.

**Comment by monis01** [comment]
Oh great, 
how can I missed that, let me try @asturur
