### ISSUE TITLE
Draw free drawing path from x and y points

### ISSUE THREAD

**Issue by ppriyank40** [fabricjs/fabric.js#5100]
Hello,
I want to use freedrawing function for drawing a path using x and y coordinates i have. So, please can you help with an example. I am currently doing this using the line functionality but with that its not fully smooth. Its broken between two points.

**Comment by asturur** [comment]
you can try:

```
var pathData = canvas.freeDrawingBrush.prototype.convertPointsToSVGPath.call(canvas.freeDrawingBrush, yourPoints);
```

**Comment by ppriyank40** [comment]
I am getting Cannot read property 'convertPointsToSVGPath' of undefined when i implemented above code.
