### ISSUE TITLE
How to create exact Circle Boundary

### ISSUE THREAD

**Issue by positiveneutron** [fabricjs/fabric.js#5103]
I just implemented drag and drop object function to the circle object by `isContainedWithinObject ` function. Is there any function to create exact circle boundary?

So far I tried the circle object has rectangle boundary, as shown the image below:
[The rectangle boundary on circle object](https://ibb.co/dGzBe8)

How to create exact circle boundary on the circle object? Something like this:
[The circle boundary](https://ibb.co/dHkTRo
)

**Comment by asturur** [comment]
There is not feature like that as of now.
FabricJS has a list of intesection functions that work on the bounding box, you should rewrite them for the circle class to take in account that the circle is a circle or an ellipse when scaled.
