### ISSUE TITLE
Loading large base64 image data-url string will cause RangeError

### ISSUE THREAD

**Issue by TyrealGray** [fabricjs/fabric.js#5106]
Using fabric version 2.3.3 in NodeJS, if `fabric.Image.fromURL` API is loading a very large base64 image data-url string like the attach file below, it will cause RangeError.

The problem is the jsdom version 9.x.x all check the base64 string by a Regex `test` method. And if the string is too large, the `test` method will run out of the stack memory in the loop.

[base64PNGImage.txt](https://github.com/fabricjs/fabric.js/files/2200762/base64PNGImage.txt)

**Comment by asturur** [comment]
how newer jsdom did solve this problem?

**Comment by TyrealGray** [comment]
I didn't test newer jsdom, but in jsdom 11.11.0, the Regex part is gone. They use a 'data-url' npm library to do the job.

**Comment by asturur** [comment]
what if it crash anyway?

**Comment by TyrealGray** [comment]
Found one solution for my project. I could create an image file using this base64 string to directory and load this file back instead of loading base64 url string directly.

**Comment by asturur** [comment]
i think this is more an issue for the jsdom tracker

**Comment by TyrealGray** [comment]
> i think this is more an issue for the jsdom tracker

But they won't do fix for old version right? Or will they do it for version 9?

**Comment by asturur** [comment]
no they will not, but you told me you did not test with latest. Does latest work?
