### ISSUE TITLE
Cannot read property 'imageSmoothingEnabled' of null

### ISSUE THREAD

**Issue by vinothmoorthkumar** [fabricjs/fabric.js#5108]
When i m running this code i m facing this error. Please check it.

 var fabric = require('fabric').fabric;
 var canvas = new fabric.StaticCanvas(null, {width:1920,height:1080, imageSmoothingEnabled: false});

**Comment by asturur** [comment]
are you sure nodeCanvas is correctly installed?

**Comment by vinothmoorthkumar** [comment]
I m using canvas 2-alpha.. Because in canvas 1.6 arabic is not working. But i m facing error in fabric.. Is there any solution?

**Comment by asturur** [comment]
not for now, jsdom is not interfacing with canvas 2 correctly yet, and jsdom 9 will not do it anyway.
I'm not sure if node-canvas 2 will solve all your problems, did you try it natively on node yet?

**Comment by vinothmoorthkumar** [comment]
Yes i tried . Arabic is not working on node-canvas 1.6 but it is working with 2-alpha. But fabricjs is not supporting 1.6.. Please fix it

**Comment by vproce** [comment]
Deploy the service and encounter the same problem
