### ISSUE TITLE
Page broken on website: http://fabricjs.com/image-filters

### ISSUE THREAD

**Issue by antoine-nedelec** [fabricjs/fabric.js#5110]
## Version
2.3.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by durga598** [comment]
#5080

**Comment by p-glynn** [comment]
@antoine-nedelec it's a workaround but the filters take effect when you select an image, apply filters, and then re-size the image ¯\\_(ツ)_/¯

**Comment by asturur** [comment]
duplicate of #5080
