### ISSUE TITLE
freedraw doesn't work with stylus

### ISSUE THREAD

**Issue by k1nger** [fabricjs/fabric.js#5111]
## Version
2.3.0

## Test Case
http://fabricjs.com/freedrawing works with fingers on mobile devices, mouse with normal browsers, but does not work with a stylus. Tested with a Samsung Note 8 stylus

## Steps to reproduce
Open the free drawing demo link above. And try drawing with a stylus. I don't know how to replicate it without a device to do this with.

## Expected Behavior
Work same as finger or mouse.

## Actual Behavior
Seems to identify the original touch but nothing after.

I suspect the problem and solution to this would be changing the event that gets passed for listening for the touch event. I haven't dug into the code but I'm thinking it is using touchstart? If so possibly replacing it with pointerdown may work across all different device types. 

https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/pointerType

**Comment by k1nger** [comment]
Just searched a bit more thoroughly, this is probably a dupilicate of #4134

**Comment by asturur** [comment]
yes duplicated of missing pointer-event.
