### ISSUE TITLE
Start moving object is too sensitive. It should be separated clearly from the click event

### ISSUE THREAD

**Issue by darron1217** [fabricjs/fabric.js#5112]
## Version
2.3.3

## Test Case
http://jsfiddle.net/Da7SP/1998/

## Steps to reproduce
1. Click on object and check moving event fired
(It's too sensitive)

## Expected Behavior
Clicking event fired, not the moving event
Start moving object when user press mouse still for more than 300~500ms

## Actual Behavior
Moving event fired immediately when user click the object for selecting. (User just accidently moved 1px due to mouse tick).

## Additional Resource
http://jsfiddle.net/arcm111/Makgq/
This is what I found for checking pressing duration

**Comment by darron1217** [comment]
I solved this problem by using the code below

```javascript
fabric.Canvas = fabric.util.createClass(fabric.Canvas, {
  /**
   * @private
   * Handle event firing for target and subtargets
   * @param {Event} e event from mouse
   * @param {String} eventType event to fire (up, down or move)
   * @param {fabric.Object} targetObj receiving event
   * @param {Number} [button] button used in the event 1 = left, 2 = middle, 3 = right
   * @param {Boolean} isClick for left button only, indicates that the mouse up happened without move.
   */
  _handleEvent: function(e, eventType, button, isClick) {
    if(eventType == 'down') {
      var target = this._target;
      if(target) {
        target._lastMouseDown = new Date().getTime();
      }
    }
    return this.callSuper('_handleEvent', e, eventType, button, isClick);
  },
  /**
   * Translates object by "setting" its left/top
   * @private
   * @param {Number} x pointer's x coordinate
   * @param {Number} y pointer's y coordinate
   * @return {Boolean} true if the translation occurred
   */
  _translateObject: function (x, y) {
    var transform = this._currentTransform,
        target = transform.target,
        duration = new Date().getTime() - target._lastMouseDown;

    if(duration >= 100) {
      return this.callSuper('_translateObject', x, y);
    }
    console.log('Move started too soon', duration);
  },
});
```

**Comment by asturur** [comment]
If you generate a mouse move, you will get a moving event, time is not important.
Every other approach to generate expected behaviours will just fail all the people that have different expectations than yours.

In custom applications you can use that code you showed to modify the application behaviour to better fit your needs.
