### ISSUE TITLE
[bug] Group centeredRotation: false is not working

### ISSUE THREAD

**Issue by StarStep** [fabricjs/fabric.js#5113]
I was trying to rotate a group arround a custom origin,
But the rendering is not working. Do you have any fix for this?
Thanks

var group = new fabric.Group([circle1, circle2, circle3], {
  left: 250,  top: 200,
  centeredRotation: false,
  originX: 0.5,  originY: 0.5,
  rotate: 20
});

## Version
2.3.0

## Test Case
http://jsfiddle.net/StarStep/anwjhs2o/243/

![image](https://user-images.githubusercontent.com/8550701/43004765-0fc48248-8c31-11e8-99b3-06baac39ffc3.png)

**Comment by durga598** [comment]
Here is updated [fiddle](http://jsfiddle.net/durga598/anwjhs2o/252/), u had provided wrong origin values.

**Comment by StarStep** [comment]
@durga598 the values I provided, I still think are correct :]
I'm trying to rotate the entire group **around a different origin** from center or top-left corner.
When i specified "originX: 0.5, originY: 0.5" i wanted to show that it wont rotate correctly even than.
You can try with other values too... for example try to rotate it around the right-middle point
Here another example: http://jsfiddle.net/StarStep/anwjhs2o/253/
Hope that this time the issue is more clear.

**Comment by durga598** [comment]
For more about origin values [check](http://fabricjs.com/test/misc/origin.html).

**Comment by asturur** [comment]
I understand the bug, while numeric origins works for positioning, they are currently not working for rotation.

Scaling and skewing have always a forced origin OR the center, while rotation has the origin OR the object origin point.
Needs a fix and an updated to docs and demo.

**Comment by asturur** [comment]
Ok i chased the wrong bug.
I read the issue fast, then i was 8 hour on a plane with no internet and i tried to fix the rotation that indeed work great. Here the problem is group creation.

**Comment by StarStep** [comment]
Thanks for the help! I would like to do something but I'm not that good yet 😋
