### ISSUE TITLE
Support for word-breaking on Textbox

### ISSUE THREAD

**Issue by darron1217** [fabricjs/fabric.js#5114]
## Version
2.3.3

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Expected Behavior
Textbox's `maxWidth` didn't work in my case. Because I usally have long words.
I need word breaking on special characters too. ex) `-`,`/`,`_`

Is there a way to break a line on special characters too?
Or just word breaking is enough.

**Comment by asturur** [comment]
no there is not. We have an old issue that talks about this but there are no plans to integrate it in main library #2376

**Comment by Matergi** [comment]
https://github.com/fabricjs/fabric.js/pull/8470#issuecomment-1925518522
