### ISSUE TITLE
SVG not loading properly and causing 'cloneNode undefined' error

### ISSUE THREAD

**Issue by onassar** [fabricjs/fabric.js#5115]
## Version
2.3.0

## Steps to reproduce
Attempt to load this SVG into a canvas using fabric:
https://pastebin.com/BESyXJDc

## Expected Behavior
A cow vector to show up properly (like this: https://i.imgur.com/MEkLuTH.png)

## Actual Behavior
An error in console which looks like this: https://i.imgur.com/hvKh7sr.png
Specifically, this method:
https://i.imgur.com/YDW6f0u.png

**Comment by asturur** [comment]
with latest 2.3.3 the svg is loaded correctly

![image](https://user-images.githubusercontent.com/1194048/43069089-7fa03f48-8e6c-11e8-8f07-1837aa9cd509.png)

**Comment by onassar** [comment]
Ahh it is. Okay. I'm using an older version, and upgrading would be difficult. Do you have any idea on what version changes to SVG would have been introduced that may have fixed issues?

**Comment by asturur** [comment]
2.3.0 > 2.3.3 should be plain and simple.
Some gradient parsing logic has been fixed, on what version are you?

**Comment by onassar** [comment]
You'll laugh: `1.6.0-rc1`
It looks like the upgrade to recent release will be pretty tough..

**Comment by asturur** [comment]
Well ... probably yes, but there are more docs than before.

So basically you need to rework filter usage a bit ( values may be different ), Text is different a bit, and caching in general. No more PathGroups also.

Depending how much time you can spend on it, you should definitely start a beta fork of your app to try it out. Tackle one problem at time

**Comment by onassar** [comment]
Yeh I just forked and will inch away at it; we've got a lot of custom work in there, but considering the noto emojis work in there, and eventually we'll need to upgrade, the time may be approaching. Thanks for your guidance and work :)
