### ISSUE TITLE
Identity ColorMatrix when used with other filters breaks filter behaviour

### ISSUE THREAD

**Issue by brandondong** [fabricjs/fabric.js#5118]
## Version
2.3.3

## Test Case
https://jsfiddle.net/ojt42731/14/

## Steps to reproduce
Press the Apply Filter button.

## Expected Behavior
Sepia filter applied to image.

## Actual Behavior
Image disappears.

I believe the isNeutralState optimizations may be causing this issue. If I change the values of the matrix slightly, the test case works as expected. In my real application use case, I was generating a colour matrix dynamically based on parameter values. It just so happened to land on the identity matrix causing this issue.

**Comment by asturur** [comment]
I see this is getting me headache, i guess i should remove the filters before getting them in the filter chain rather than in the middle of filtering, i have not time to setup a proper debug test with webgl, but looks like that removing the first filter causes the problem.
