### ISSUE TITLE
Basic fonts not working

### ISSUE THREAD

**Issue by alexgeofilter** [fabricjs/fabric.js#5119]
## Version
2.3.0

## Test Case
http://jsfiddle.net/Da7SP/2027/

## Steps to reproduce
Insert itext/textbox and select a font that is not Times New Roman or Arial for ex. Comic Sans. 

## Expected Behavior

Comic sans should be the text font of the text box on click. 

## Actual Behavior

In the fiddle, I start the textbox as Arial then on click change the font to comic sans. The font changes to the default times new roman instead. If you set Comic Sans as the default fault it will behave the same way.

**Comment by alexgeofilter** [comment]
This could be an issue specific to Ubuntu. It didn't work in my rails application as well as in the jsfiddle. If I open it on my phone I can see different font.

**Comment by asturur** [comment]
Do you have Comic Sans on ubuntu?
Also the font is called `Comic Sans MS` normally.
And needs to be loaded, not just assigned.

Please have a look at the custom font loading demo and check the correct name of the font family
http://fabricjs.com/loadfonts
