### ISSUE TITLE
`canvas.toJSON()` does not export specific properties related to object movement 

### ISSUE THREAD

**Issue by ickata** [fabricjs/fabric.js#5122]
## Version
2.3.3

## Test Case
http://jsfiddle.net/ickata/hu7t2rzf/

## Steps to reproduce
Run the test case and try to move the image. You're able to, and you should not.

## Expected Behavior
`canvas.toJSON()` should export specific properties related to object movement, such as:

 - `hoverCursor`
 - `hasControls`
 - `lockMovementX`
 - `lockMovementY`
 - `selectable`

Respectively `canvas.loadFromJSON()` must respect them.

## Actual Behavior
`canvas.toJSON()` does not export these properties.

**Comment by samael205** [comment]
Hi, you need to explicit serialize these propietes

Here the fiddle updated: http://jsfiddle.net/samael205/xo93hwkL/
