### ISSUE TITLE
After scaling add attribute(text) dynamically then group position changed.

### ISSUE THREAD

**Issue by rahulyadav-walkingtree** [fabricjs/fabric.js#5125]
## Version
2.2.3

## Steps to reproduce

- Add more than one image/attribute(text) in the canvas.

- Select all group and scale it.

- Select one group and add the attribute(text) dynamically.

- Check the selection position it is in the same place and height and width as expected based on scaling.

- Check the group position it is getting disturbed but height and width as expected based on scaling.

## Expected Behavior
After scaling the image/attributes select the group and add attributes(text) in the group dynamically than selection and group position must be the same.
 
## Actual Behavior
Group Top and Left position in a weird way.
When we select groups and scales it than groups are scaled but when we select and add a few more attributes(text) in the group dynamically than group position got changed but selection position remains the same.

Select the groups
![1](https://user-images.githubusercontent.com/12165030/43336558-f358135e-91ee-11e8-9311-cffe0beeef52.PNG)

Perform scaling for a selected group
![2](https://user-images.githubusercontent.com/12165030/43336570-fbbcc80a-91ee-11e8-9291-1938134e3442.PNG)

Select any group
![3](https://user-images.githubusercontent.com/12165030/43336580-019f71e6-91ef-11e8-909d-b1b6fa69959b.PNG)

Add few attributes(text) in group
![4](https://user-images.githubusercontent.com/12165030/43336583-06b23bf0-91ef-11e8-8adf-ad53d8785c5b.PNG)

**Comment by asturur** [comment]
I'm sorry this is custom application question, and not a library bug.
Please open a stack oveflow question for those things.
