### ISSUE TITLE
safari 11 bug with text shadow

### ISSUE THREAD

**Issue by AlexSergey** [fabricjs/fabric.js#5128]
## Version
2.3.3

## Test Case
http://jsfiddle.net/e9xtbomc/7/

## Steps to reproduce
I made text with shadow and added Pattern or Gradient. In latest Safari version on Mac (Safari 11.11.1) the shadow disappeared  

## Expected Behavior
http://jsfiddle.net/e9xtbomc/7/

## Actual Behavior
http://joxi.ru/ZrJpp03h9YV5y2

**Comment by durga598** [comment]
Check [this](http://jsfiddle.net/durga598/e9xtbomc/8/). changed `color: 'rgb(0,0,0)',`, you had used color: 'rgba(0,0,0)', without alpha value.
