### ISSUE TITLE
Use alpha:false contextAttribute for lower canvas

### ISSUE THREAD

**Issue by aggrosoft** [fabricjs/fabric.js#5132]
I was playing around with custom fonts on i-text and noticed that the text rendering is not optimal because of the missing sub-pixel rendering. But recently browsers started implementing the alpha:false contextAttribute, if this is active you will be able to use subpixel rendering on canvas. The only drawback I found so far is that the default background color is always black.

See my jsfiddle to get an idea of what I have been doing:
https://jsfiddle.net/4qL7jwba/24

My idea would be to make this a parameter of the canvas class, it would improve performance in quite a lot of use cases and might help against blurry elements for some scale values.

What do you think?

**Comment by aggrosoft** [comment]
Sorry, wrong link:

https://jsfiddle.net/4qL7jwba/24

See this stackoverflow topic, maybe this is not the case anymore - but still the flag can give performance improvements:

https://stackoverflow.com/questions/40066166/canvas-text-rendering-blurry/40074278

This for improving canvas performance (not subpixel related, but performance related):

https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas

Documentation for the alpha property which states:

> alpha: Boolean that indicates if the canvas contains an alpha channel. If set to false, the browser now knows that the backdrop is always opaque, which can speed up drawing of transparent content and images.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext

**Comment by asturur** [comment]
If  you do not deactivate object caching the text rendering happens on an offscreen canvas where the alpha is still true.

I do see just a worse situation if i remove alpha.

with caching
![image](https://user-images.githubusercontent.com/1194048/43457610-b030dd64-94c7-11e8-8e54-46b09b5d0141.png)

without caching:
![image](https://user-images.githubusercontent.com/1194048/43457651-d118b9ca-94c7-11e8-997b-449700b24f6d.png)

**Comment by asturur** [comment]
Normally if it improves speed, it can't improve quality.
This is a general rule that is hard to defeat.

I do think that subpixel rendering needs alpha, do you have any other source with some discussion about it?

**Comment by asturur** [comment]
i do think this answer is beautiful and explain everything:
https://stackoverflow.com/questions/40066166/canvas-text-rendering-blurry/40074278

**Comment by aggrosoft** [comment]
Yeah, and also that topic explains why there is no subpixel rendering with a canvas:

> Why no true type for canvas
> 
> When using sub pixels you need to have full control of each, including the alpha value. For the display drivers alpha applies to all the sub pixels of a pixel, you can not have blue at alpha 0.2 and red on the same pixel at alpha 0.7. But if you know what the sub pixel values are under each sub pixel you can do the alpha calculations instead of letting the hardware do it. That gives you algha control at a sub pixel level.
> 
> Unfortunately (no... fortunate for 99.99% of cases) the canvas allows transparency, but you have no way of knowing what the sub pixels under the canvas are doing, they can be any colour, and hence you can not do the alpha calculations needed to use sub pixels effectively.

So the alpha = false flag **should** help with doing subpixel rendering. Can you tell me which browser you used to take the screenshots above?

**Comment by asturur** [comment]
my screenshot was chrome on macbook, moved on the non retina screen.

Take care that the subpixel rendering is a manual code execution, you are not getting it for free from the canvas. You have to write your own subpixel hinting logic.

**Comment by asturur** [comment]
@aggrosoft  i think i will close this issue.
If there is more you think we should talk about i will reopen it.
