### ISSUE TITLE
toSVG() doesn't show the same result than canvas or toDataURL()

### ISSUE THREAD

**Issue by rikkarv** [fabricjs/fabric.js#5134]
## Version
2.3.3

## Test Case
https://jsfiddle.net/0Ldgz5x7/3/
or
https://jsfiddle.net/0Ldgz5x7/2/

## Steps to reproduce
Click the "test output" button on the bottom of browser

## Expected Behavior
The svg container should have the same content/result that the fabric and png containers have

## Actual Behavior
The svg container image is slightly scaled and has a space in the top

![issues](https://user-images.githubusercontent.com/40458494/43471462-f5b12d56-94e2-11e8-80f0-04b4d31fe90e.png)

**Comment by asturur** [comment]
may be related to the preserve-aspect-ratio attribute, something to look at.

**Comment by rikkarv** [comment]
@asturur , In first place let me congratulate you on the excellent job and your contribute to the support of fabric project!
In concern to this issue, i'm looking to the svg output and i see that the the image is wrapped in a group tag (<g>) which has a transform attribute with the following value: "translate(189, 155) scale(0.08 0.08)". If i change this value to "translate(189, 155) **scale(0.085 0.085)**" i can get the image to a more accurate positioning
![issues2](https://user-images.githubusercontent.com/40458494/43517503-dc1154cc-9580-11e8-914c-2271b4b69344.png)

**Comment by rikkarv** [comment]
If i use another image with other dimensions (1200 x 900) i get the expected output [https://jsfiddle.net/0Ldgz5x7/10/](url)

**Comment by rikkarv** [comment]
In the first example, by doing canvas.item[0] i get scaleX and scaleY with "0.0847226" value. 

However, in line 19368 of fabric_2_3_3.js (toSVG function) this.getSvgTransform() returns "... scale(0.08 0.08)".

Maybe because of "fabric.Object.NUM_FRACTION_DIGITS = 2;" in line 13968?

**Comment by asturur** [comment]
oh sure bumping the NUM_FRACTION_DIGITS to an higher number is the first
thing when you are missing accuracy. Did not think of it.

2018-08-01 14:44 GMT+02:00 Ricardo Carvalho <notifications@github.com>:
