### ISSUE TITLE
toDataURL: clipTo is ignoring the multiplier

### ISSUE THREAD

**Issue by c-gross** [fabricjs/fabric.js#5135]
## Version
2.3.3

## Test Case
http://jsfiddle.net/0k2rjLfv/50/

## Steps to reproduce
1. click render result (multiplier = 1) => result image looks like the canvas preview
2. change multiplier to 2 and click render result => The dog image gets scaled, the clipTo mask is not scaling
3. change multiplier to 0.5 and click render result => The dog image gets scaled, the clipTo mask is not scaling

## Expected Behavior
The clipTo mask should scale too

## Actual Behavior
The clipTo mask is ignoring the multiplier param of toDataURL

I know that clipTo is deprecated  since 2.0 but there is no replacement so far available.

**Comment by rikkarv** [comment]
I'm going to suggest a workaround:
- drop clipTo (as you said it is deprecated);
- use setOverlayImage;

You have to invert your svg (i.ve followed the answer of Nicole Moore in:
[https://graphicdesign.stackexchange.com/questions/46069/how-to-create-an-inverse-path](url) 
to get the svgString in the following fiddle:

[http://jsfiddle.net/L05gwzav/4/](url)

It's not perfect but it should be a good start to achieve your goals.

**Comment by c-gross** [comment]
I'm already using setOverlayImage for something else. And it will not work if I need to create a transparent PNG which is the plan in the next 1-2 months.

**Comment by rikkarv** [comment]
Check:

[https://github.com/fabricjs/fabric.js/wiki/How-fabric-canvas-layering-works](url)

The order of various physical and functional "layers" of canvas:

after:render callback     // canvas.on('after:render', function(){ ... })
         ^
canvas overlay image      // canvas.overlayImage
         ^
**canvas clipped area       // canvas.clipTo**
         ^
canvas object selection   // (only visually represented)
         ^
canvas objects' controls  // (only visually represented; rendered implicitly by drawCorners, drawBorders)
         ^
canvas objects            // canvas.getObjects()
         ^
canvas background image   // canvas.backgroundImage
         ^
canvas background color   // canvas.backgroundColor
         ^
div container             // document.getElementById('wrapper')

I think that you are drawing the mask in a specific layer (ctx) that apparently does not scale.
For example: if you try canvas.setZoom(2) and canvas.setDimensions({width: 800, height: 800}) you get the canvas and the image in double size but the clip area remains in the initial size.

**Comment by c-gross** [comment]
Hm, I'll check the layer thing. But thats how it was working in 1.5.0 and I'm not sure how to get the basic layer where everything is added to.

**Comment by rikkarv** [comment]
[http://jsfiddle.net/L05gwzav/12/](url)

You have here a very simple example of the issue.

And

[http://jsfiddle.net/L05gwzav/14/](url)

Where you get the scaled mask by:
- making the mask variable global (it is declared outside the loadSVGFromURL);
- in the renderBtn listener you scale the mask object and overwrite the canvas.clipTo with the new mask scaled.

After the canvas.toDataURL(), you can reset the scale [http://jsfiddle.net/L05gwzav/17/](url)

**Comment by c-gross** [comment]
Hm yes that might work. 

Funny thing, I was using a similar logic when I added a shadow fix long time ago. Because the shadow is set as pixels it doesn't look the same when you scale the result image. I also just apply the scale/multiplier when I render the image and reset it after. Didn't think about, that I can do the same with the mask. That workaround will work until we have the new clipping methode.
