### ISSUE TITLE
Very strange panning bug, when top = "0" and height = 959

### ISSUE THREAD

**Issue by g1ts** [fabricjs/fabric.js#5136]
## Version
2.3.3

## Test Case
https://jsfiddle.net/fucs97L1/31/

## Steps to reproduce
CTRL + DRAG

## Expected Behavior
panning

## Actual Behavior
during the dragging (panning) image disappears
it's happening only if top = "0" and height = 959

**Comment by g1ts** [comment]
no, does it happen only if top is string and height is odd number
i receive data from server (top="0") and i did spend a lot of time to understand why image has disappears when i changes viewportTransform
this is a very unexpected behavior for me

**Comment by asturur** [comment]
the jsdocs for top, left, width, height clearly want numbers. You can't give strings.
