### ISSUE TITLE
Image opacity after setOverlayImage

### ISSUE THREAD

**Issue by hungln213** [fabricjs/fabric.js#5145]
Hello Team

I have get an issue for add another image to OverlayImage.

Step 1: add image to canvas and setOverlayImage this.
Step 2: add another image to canvas but this image have opacity and i want to original image.

<img width="616" alt="screen shot 2018-08-06 at 3 58 31 pm" src="https://user-images.githubusercontent.com/5548687/43708013-9fec7f5a-9993-11e8-9188-c670337de503.png">

![google-maps-icon](https://user-images.githubusercontent.com/5548687/43708082-c8493b82-9993-11e8-9ab0-670f750d0dff.png)

Please support me. Thank you so much

**Comment by ncou** [comment]
i think you should open a stackoverflow topic with your problem, it's not a fabric.js bug, it looks like you are seeking help for a custom app.

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
