### ISSUE TITLE
Problem with exporting to SVG for objects with image fill.

### ISSUE THREAD

**Issue by yuriyant** [fabricjs/fabric.js#5146]
## Version
2.3.4

## Test Case
https://jsfiddle.net/yuriyant/t6v73r8h/41/

Json: https://vsesorta.ru.test.dvaslona.com/tmp/page.json

## Steps to reproduce

Create an object with a fill image and a negative value of the offsetX/offsetY property
![0beb433dd9](https://user-images.githubusercontent.com/1130955/43729574-64abeb92-99b1-11e8-96db-7a44e3ffee82.png)
 

## Expected Behavior

![1111111](https://user-images.githubusercontent.com/1130955/43729981-ad3e8f26-99b2-11e8-92a2-a6847432039a.png)

## Actual Behavior
Part of the image moved to another part
![abbb43b5ac](https://user-images.githubusercontent.com/1130955/43729800-0fb4d7f6-99b2-11e8-8166-7d3d7847872b.png)

I will be grateful for any advice on fixing the problem.

**Comment by asturur** [comment]
Hi, sorry for the delay.
The problem is that the SVG does not support the no-repeat attribute.
We have to somehow build a special SVG logic that will imitate it.

I ll check what i can do
