### ISSUE TITLE
i want to use floodfill algorithm to my project.(  https://github.com/karlew/canvas-flood-fill ) if i am intigrating with fabric js it was not working,can you please help me

### ISSUE THREAD

**Issue by RajasekharKadasani** [fabricjs/fabric.js#5147]
## Version
2.3.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

**Comment by RajasekharKadasani** [comment]
hi i am implimenting and intigrating flood fill algorithm to fabric js ,it was not wprking,

means i am trying to re draw pixel as shown in demo

https://github.com/karlew/canvas-flood-fill

**Comment by RajasekharKadasani** [comment]
I have an algorithm for Floodfilling a canvas. Im trying to incorporate this with fabricJS. So here is the dilemna.... I create a fabric.Canvas(). Which creates a wrapper canvas and also an upper-canvas canvas. I click on the canvas to apply my Floodfill(). This works fine and applies my color. But as soon as i go to drag my canvas objects around, or add additional objects to the canvas, the color disappears and looks like it resets of sort.

**Comment by yoniP68** [comment]
hey, im trying the same thing now, did you find a goos solution? 
@RajasekharKadasani
