### ISSUE TITLE
Active selection + textbox is bugging

### ISSUE THREAD

**Issue by blobinabottle** [fabricjs/fabric.js#5152]
## Version
2.3.0

## Test Case
KitchenSink

## Steps to reproduce
Edit a text, next click and drag to make an active selection but release the mouse on top of text that you were editing. It will put that textbox back in editing mode. And it's mixing editing mode with selection mode... 
Check the video here: https://cl.ly/0U2D1g2u3m0s

## Expected Behavior
Keep all textbox in selection mode

## Actual Behavior
Textbox are switched in editing mode with no reason

**Comment by asturur** [comment]
uh ok this needs a fix definetely.

**Comment by asturur** [comment]
@blobinabottle  check the PR, looks good to me testing manually.
Need to add a test for it

**Comment by blobinabottle** [comment]
@asturur  seems to be fixed! Can't reproduce it! Thanks!

**Comment by blobinabottle** [comment]
Sorry still and issue, but now if you shift + double click you enter editing text but you can sill interact with other objects (while keeping the text in editing mode). 
https://cl.ly/0009312X3i08

**Comment by asturur** [comment]
ok i ll first fnd a way to test interactions with tests and then i will eventually fix it.
