### ISSUE TITLE
Shadow bug when using paintFirst: 'stroke'

### ISSUE THREAD

**Issue by melchiar** [fabricjs/fabric.js#5154]
## Version
2.3.4

## Test Case
https://jsfiddle.net/melchiar/3m8apcgd/

## Steps to reproduce
Add an image with a drop shadow and stroke. When you set 'paintFirst' to 'stroke', the drop shadow disappears.

**Comment by asturur** [comment]
To add shadow to stroked images, you need to enable object caching.
Shadow is a per paint operation, stroke and fill are 2 different operations and cast 2 shadows.
Probably the shadow is there, but covered by stroke that is not casting a shadow.
If you try to set affectStroke true to shadow ( you can see it in docs fabricjs.com/docs ) you will get a shadow from a fill ( maybe that is a bug )

Shadow on stroke is a recurring problem that is solved by caching, but images in fabricjs are not cached yet ( 2.4.0 will bring this change )

**Comment by melchiar** [comment]
Thanks @asturur. You're right, enabling objectCaching fixes it. I don't think the stroke was merely covering the shadow since the issue occurs even when the stroke width is a negligible amount, or when the shadow has a huge offset that should extend beyond the bounds of the stroke. 

Keep up the great work!
