### ISSUE TITLE
Href parsing in SVG use directive

### ISSUE THREAD

**Issue by DylanPaulusSEL** [fabricjs/fabric.js#5155]
(https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href)
xlink:href is being deprecated for href

## Version
2.3.0

## Test Case
http://jsfiddle.net/uybeqc5r/

## Steps to reproduce

Use `loadSVGFromUrl`/`loadSVGFromString` with an SVG `<use />` tag that contains `href` instead of `xlink:href`. (`<use href="#myId" />`)

## Expected Behavior

Should parse the SVG into the fabric canvas.

## Actual Behavior

Throws a null reference error on `xlink = el.getAttribute('xlink:href').substr(1)` when using `href`.
![image](https://user-images.githubusercontent.com/30325527/43851028-7453376a-9aee-11e8-8069-033365140c6a.png)

--------

Willing to make a PR for this if everything seems fine. Thinking of adding checks for either `xlink:href` and `href`. (eg. `xlink = (el.getAttribute('xlink:href') || el.getAttribute('href')).substr(1)`

**Comment by asturur** [comment]
it make sense to support href on top of xlink:href to do not immediately being completely incompatible with svg 2.

But we still focus on svg 1.1 ( with 1.2 addons where possible ) compatibility, so is not deprecated for us.

Most of svg2 features are really out of reach for us.

**Comment by asturur** [comment]
merged
