### ISSUE TITLE
ClipPath examples broken

### ISSUE THREAD

**Issue by timpulver** [fabricjs/fabric.js#5159]
## Version
2.3.4

## Test Case
http://fabricjs.com/test/svg_import/clippaths.html
http://fabricjs.com/clippath-part1

In the ClipPath tutorial as well as the ClipPath test you can see that ClipPath is broken in 2.3.4.

Both in recent versions of Firefox and Chrome. Didn’t test any other browsers.

**Comment by asturur** [comment]
Yes i m sorry, clipPath is 2.4.0 only that i temporarly put on the website. I try to push a 2.3.5 this weekend, merge everything in the 2.4.0 branch and push out clipPath as it is, marking the feature as `can change - beta` or it will not move easily from where it is.
