### ISSUE TITLE
preserveObjectStacking: true - causes error in creating group from ActiveSelection

### ISSUE THREAD

**Issue by nateevans** [fabricjs/fabric.js#5160]
## Version
2.3.4

## Test Case
https://jsfiddle.net/nateevans/jayc67sk/ (click the "Add & Group" button)

## Steps to reproduce
1. Create canvas with `preserveObjectStacking: true`
1. Add some objects to the canvas
1. Create a new ActiveSelection with those objects
1. Set that selection to active with canvas.setActiveObject
1. Call canvas.getActiveObject().toGroup() to create a group

## Expected Behavior
A new group should be created with the selected objects and it should be actively selected.

## Actual Behavior
`Uncaught RangeError: Maximum call stack size exceeded` occurs

It seems the uncaught error is result of recursive calls to `_set` here:
https://github.com/fabricjs/fabric.js/blob/068c815340a65dd7577cfb61a03f5492f947c42b/src/shapes/active_selection.class.js#L105

Possible fix may lay in this area??
https://github.com/fabricjs/fabric.js/blob/c541a273ff40e6267418dc76c80b492295f3eed4/src/canvas.class.js#L359

The code in the fiddle works as expected with `preserveObjectStacking: false`, and the error does not occur when you do not pass the canvas object to the new ActiveSelection. But when you do not pass the canvas, the group is not created properly.

I may be using the API incorrectly, not sure. But seems if the code works with `preserveObjectStacking: false`, it is probably not intended to error when `preserveObjectStacking: true`

**Comment by asturur** [comment]
i ll look into it, looks a bug.

OFF TOPIC:
I have seen your reference to printsites.com, i feel like mentioning this library i released, since i did not find anything similar in the web:
https://www.npmjs.com/package/changedpi

it allows you to change the DPI of image generated by canvas, quickly in the browsers.
Generally ( but i may be wrong ) who needs to change dpi always fallback on some server side approach to use available tools, while this is quick and effective.

**Comment by asturur** [comment]
```
var rect = new fabric.Rect({
    width: 40,
    height: 40,
    originX: 'left',
    originY: 'top'
  });
  
  canvas.add(rect);
  
  var circle = new fabric.Ellipse({
    width: 40,
    height: 40,
    originX: 'left',
    originY: 'top',
    rx: 40,
    ry: 40
  });
  
  canvas.add(circle);

  var objs = canvas.getObjects();
  
  var selection = new fabric.ActiveSelection(objs, {canvas: canvas});
  
  canvas.setActiveObject(selection);
   canvas.getActiveObject().toGroup();
```

this is the minimal amount of code to reproduce the bug in kitchensink.

**Comment by asturur** [comment]
i do not see any difference with preserveObjectStacking false

**Comment by asturur** [comment]
Ok the usual JS mutability problem that took 2 hours of my life.
getObjects return a reference to the canvas.object and the canvas.remove in toGroup is causing the error.

this needs to change once for all.

**Comment by nateevans** [comment]
Thanks for the reference to https://www.npmjs.com/package/changedpi @asturur  looks interesting!

I don't work with that company anymore, but might still have a use for it. 👍
