### ISSUE TITLE
Selection of programatically moved objects

### ISSUE THREAD

**Issue by AntonyGarand** [fabricjs/fabric.js#5161]
## Version
2.3.4

## Test Case
https://jsbin.com/guresorazi/1/edit?js,output

## Steps to reproduce
1. Move red circle to the right, about until the black circle is where the red circle previously was
2. Try to select the black circle: It fails
3. Select the area around the black circle: It fails
4. Select the area from the original black circle position until the red circle: It should work
After step 4, the black circle is now selectable once again.

## Expected Behavior
When setting the `top` of `left` attribute, the element should be selectable at its new position.

## Actual Behavior
When setting the `top` of `left` attribute, the element is not selectable at its new position.
We can still somewhat interact with it at its old position.

It seems like selecting the original element position + any other element fixes this issue, as the modified element is selectable once again after.

**Comment by asturur** [comment]
if you change left and top of an object programmatically, you have to call .setCoords() on the object before being able to interact it again.
.setCoords will update the cached coordinates that make targeting easy.
