### ISSUE TITLE
Inconsistent image rendering between v1 and v2

### ISSUE THREAD

**Issue by flyfj** [fabricjs/fabric.js#5163]
## Version
2.3.4

## Steps to reproduce

The issue happens when simply adding image object to canvas. The image element is smaller than the original size, in my case, is a responsive element with 'img-fluid' from bootstrap v4.

```
<html>

<head>
  <title>Fabric JS Lab</title>
  <link rel=" stylesheet " href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css
    " integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO " crossorigin="anonymous ">
 <!-- switch between 1.7.22 and 2.3.4 to see the difference -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.7.22/fabric.min.js"></script>
  <script>
    let canvas = null;
    function init() {
      let box_tl, box_br;
      let img_elem = document.getElementById('test-img');
      canvas = new fabric.Canvas("my-canvas");
      canvas.selection = false;
      canvas.setHeight(img_elem.height);
      canvas.setWidth(img_elem.width);
      // image
      var imgInstance = new fabric.Image(img_elem, {
        left: 0,
        top: 0,
        angle: 0,
        opacity: 1
      });
      imgInstance.set("selectable", false);
      canvas.add(imgInstance);
      });
  </script>
</head>

<body class="container-fluid">
  <div style="height: 500px;">
    <div class="row">
      <div class="col-3 text-center">
        <img id="test-img" src="http://animals.sandiegozoo.org/sites/default/files/2016-08/category-thumbnail-mammals_0.jpg"
          alt="" class="img-fluid" onload="init();">
        <canvas id="my-canvas" class="mx-auto" style="border-style: solid;">
        </canvas>
      </div>
    </div>
  </div>

</body>

</html>
```

## Expected Behavior

Both v1 and v2 should correctly render the resized image.

## Actual Behavior

v2 is rendering the original size.

![v1](https://user-images.githubusercontent.com/2397970/43993192-c00465f6-9d57-11e8-99ce-c1308cea6955.png)
![v2](https://user-images.githubusercontent.com/2397970/43993191-b83fe228-9d57-11e8-83ab-ddd9d66c9968.png)

**Comment by asturur** [comment]
this is the reason why we moved to  a major version. Incompatibility.

If you remove the class it should load fine

Is it loading cropped or just bigger?

**Comment by flyfj** [comment]
cropped. which class are you referring to?

**Comment by asturur** [comment]
the css class

**Comment by flyfj** [comment]
isn't that forcing the canvas to be the same size of the original image?

**Comment by asturur** [comment]
the image will load as big as it is. Unless you provide a scale factor.

This was always the intended behaviour.

What does concern you?

**Comment by flyfj** [comment]
What if the image is put inside a responsive container, e.g. bootstrap col with img-fluid, a user would expect the image to be scaled automatically based on the container. This is easily done in the v1, but in v2, it is not scaled but rather show part of the image.

**Comment by asturur** [comment]
it has been fixed. it will show the whole image. Big, and you have to scale it down to the size you want.

We will fail dev expectation, always. as long as we provide docs it is still ok.

**Comment by flyfj** [comment]
ok, so the scale factor needs to be calculated by ourselves. No problem. Thanks for the clarification. Awesome library!
