### ISSUE TITLE
Two finger gestures broken after 2.3.0

### ISSUE THREAD

**Issue by pawel-pawlowski** [fabricjs/fabric.js#5167]
## Version
2.3.0

## Steps to reproduce
1. Add image to canvas with gestures support enabled
2. Zoom or rotate with two fingers
## Expected Behavior
Image is scaled and/or rotated.
## Actual Behavior
Image is zoomed only at the end of the gesture. Rotation is not applied. The following error appears in the console:
![bug](https://user-images.githubusercontent.com/17722532/44088289-e5b0ed98-9fc2-11e8-99a7-c031c8f2cccc.png)

**Comment by sameermanuja** [comment]
_fire now expects the event name and an options object. _scaleObjectBy and _rotateObjectByAngle are still using the old form.

Defining an options object:
var options = {
              e: e,
              target: t.target,
              transform: t
          };
and calling _fire with options fixes this.

**Comment by asturur** [comment]
you may have found the problem.
I refactored some events and completely forgot about the 2 fingers gestures.

The truth is that they are half unsupported.
