### ISSUE TITLE
Free Drawing Mode: Circle and Spray move after completing line

### ISSUE THREAD

**Issue by JonLaliberte** [fabricjs/fabric.js#5169]
## Version
2.3.5 (I assume the demos use the most recent release)

## Test Case
http://fabricjs.com/kitchensink
http://fabricjs.com/freedrawing

## Steps to reproduce
Use the Circle or Spray modes. Draw something.

## Expected Behavior
The line should be drawn using the given mode, and the line should be drawn where you drew it.

## Actual Behavior
The line moves up and to the left after you release the mouse.
I've tested in Safari and Chrome, both show the same issue.

**Comment by asturur** [comment]
definitely a bug

**Comment by durga598** [comment]
@asturur, removing origin properties while creating group, it works.

**Comment by asturur** [comment]
weird. I recently modified group logic to work with numeric origins. I wonder if i broke something.

**Comment by asturur** [comment]
We need acceptance tests.
