### ISSUE TITLE
Image with opacity looks strange

### ISSUE THREAD

**Issue by MonFig** [fabricjs/fabric.js#5172]
This how an image with opacity 0.4 looks like in fabric.js:

![image](https://user-images.githubusercontent.com/16597492/44262321-3595ee80-a24d-11e8-8cd4-71852b64aee8.png)

and this is how an image with opacity 0.4 rendered by canvas API looks like:

![image](https://user-images.githubusercontent.com/16597492/44262438-a806ce80-a24d-11e8-9956-305e735f5780.png)

The color of the image with fabric.js looks deeper.

**Comment by asturur** [comment]
weird. can you share a fiddle with both source codes?

**Comment by MonFig** [comment]
@asturur Found the Reason. `clipTo` causes it. It was caused by:

```
image.set({
    clipTo: rounderCornerRect.bind(image)
});

function rounderCornerRect(ctx) {
    const rect = new fabric.Rect({
        left: 0,
        top: 0,
        rx: this.radius / this.scaleX,
        ry: this.radius / this.scaleY,
        width: this.width,
        height: this.height,
        fill: 'transparent'
    });
    rect._render(ctx, false);
}
```

But I think it's also an issue.

**Comment by asturur** [comment]
clipTo is deprecated, i ll let it as it is.
Please try the new clipPath functionality, should work for you.
