### ISSUE TITLE
Object: clipTo serialization and name mangling

### ISSUE THREAD

**Issue by AntonyGarand** [fabricjs/fabric.js#5173]
Fiddle: http://jsbin.com/dawuyunuti/1/edit?js

This is a very specific behavior bug which is used when merging code uglification with name mangling and the clipTo serialization.

Basically, the `clipTo` property on Object is a function which can be used for clipping.
When serializing this object, the JSON property for `clipTo` will be `this.clipTo.toString()`.
When unserializing this object, the following code is executed:

```javascript
_initClipping: function (options) {
	if (!options.clipTo || typeof options.clipTo !== 'string') {
		return;
	}

	var functionBody = fabric.util.getFunctionBody(options.clipTo);
	if (typeof functionBody !== 'undefined') {
		this.clipTo = new Function('ctx', functionBody);
	}
},
```
It extracts the function body, then creates a new function using `new Function`.

The issue is with the hardcoded `ctx` in `new Function('ctx', functionBody);`
The clipTo function can have another argument name, and hardcoding `ctx` here will cause the next call to clipTo to have a nullpointer.

The fix would be to extract both the argument name and the function body to create the new clipTo function, instead of hardcoding `ctx`.

---

In my case, while my variable was named `ctx` in development, it was uglified in production and therefore caused the issue.
As I couldn't disable name manglification, I'm currently using a workaround with `var ctx = arguments[0];` in my function.

# References
 - Original commit adding this feature: https://github.com/fabricjs/fabric.js/commit/2407dbba49bd662ad2dba92bc463dcddb544cf40
 - clipTo unserialize: https://github.com/fabricjs/fabric.js/blob/master/src/mixins/shared_methods.mixin.js#L51

**Comment by asturur** [comment]
this is one of the reasons why clipTo is deprecated. Maybe we should add in the docs that ctx = arguments[0] is the way to go.

**Comment by asturur** [comment]
improved jsdocs with this notes.
