### ISSUE TITLE
Filters WebGL on Chrome 68 windows 10

### ISSUE THREAD

**Issue by blobinabottle** [fabricjs/fabric.js#5175]
## Version
2.3.5

## Test Case
KitchenSink filter demo

## Steps to reproduce
Apply a filter with webGL "on"

## Expected Behavior
Show filter applied

## Actual Behavior
Image become transparent (whatever the filter you apply)
<img width="505" alt="image" src="https://user-images.githubusercontent.com/8090162/44301223-82dc9380-a313-11e8-9204-d0075bb8c691.png">

If you turn off WebGL it's working (but slow ;-)).

It seems Chrome 69 fixes that issue.

**Comment by blobinabottle** [comment]
Nothing shown in the console.
I know it's working fine everywhere else. But I guess it's a bug in chrome, I tested several filters case in 69 and that's working. 69 will be out in 4th September.

**Comment by asturur** [comment]
let me try the VM here, just to rule out a driver issue

**Comment by asturur** [comment]
If you resize the image it stays blank?

**Comment by blobinabottle** [comment]
Stays blank.
You can also use browserstack.com (that's what I use to quickly test something like that ;-))

**Comment by asturur** [comment]
Tested on my virtual box VM windows 10, chrome 68, hw acceleration enabled, working fine.
I think is a driver issue with chrome, on what hardware are you running it?
An intel integrated not recent intel core?

**Comment by blobinabottle** [comment]
On browserStack I'm not sure. 
But my user reporting the issue is using the following https://cl.ly/1d1F2p1L0h2Y
He told me intel integrated (no gpu)

**Comment by asturur** [comment]
only chrome knows.
Internal webgl changes probably ... but empty textures on intel integrated
in chrome only, is something i already seen many times and does not occur
with alternative copy methods.

Il giorno sab 18 ago 2018 alle ore 22:19 Blob <notifications@github.com> ha
scritto:

**Comment by asturur** [comment]
@blobinabottle i should either close this or move to a bug. Did you do more reasearch on what was happening?
