### ISSUE TITLE
object with perPixelTargetFind in nested group 

### ISSUE THREAD

**Issue by liajoy** [fabricjs/fabric.js#5179]
## Version
2.3.5

## Test Case
https://jsfiddle.net/f5zwk3by/10/

## Steps to reproduce
1. create a red circle in group
2. create a blue circle in nested group
3. listen canvas mousemove event

## Expected Behavior
Blue circle should trigger mousemove event.

## Actual Behavior
Blue circle can handle click event correctly But can't trigger mousemove event.

**Comment by asturur** [comment]
i think we wanted to avoid handling all the calculations on the mouse move.

Fabricjs has to first verify if a target is there and eventually fire the event. Doing on mousemove can be expensive for the gpu.

I ll give a look if we can handle it differently.

Do not have much time now for this. So do not expect a quick fix

**Comment by asturur** [comment]
hey i think this has been fixed, please check as soon as i release 2.4.2
