### ISSUE TITLE
Bounding rectangle is not updated after setLeft/setRight

### ISSUE THREAD

**Issue by raichu** [fabricjs/fabric.js#518]
When moving the object from javascript using setLeft/setRight (followed by a canvas.renderAll()), the object itself moves but the bounding rectangle stays still.
I wasn't able to find any function to force updating bounding rectangle after a move either, so I believe this is a bug. It happens with a single selected object as well as a group of objects.

![bug](https://f.cloud.github.com/assets/3126046/316452/8ed0acec-981c-11e2-8118-74357e432d71.png)

**Comment by EylonSu** [comment]
old issue, but I'm experiencing the same bug in ver 2.6.0.
after moving objects within a multiple selected with set('left', x), the bounding box doesn't update to the new position

**Comment by asturur** [comment]
No it doesn't.
You have to call setCoords since you are setting left, you should do it.

**Comment by EylonSu** [comment]
Of course, forgot to mention that thus is happening even after calling setCoords() on every object in the selection
