### ISSUE TITLE
Unexpected behaviour on set('text', ...)

### ISSUE THREAD

**Issue by AshwinTayson** [fabricjs/fabric.js#5182]
## Version
2.3.5

## Test Case
https://jsfiddle.net/4s6o7v5k/10/

## Steps to reproduce
1. Click on to uppercase button
2. Double Click inside the textbox to enable editing and add a few letters to it
3. Click on to lowercase button
4. Click on textbox to enable editing and add a few letters to it

## Expected Behavior
The textbox should contain all small letters

## Actual Behavior
The textbox reverts back to the previous uppercase state. Vice-versa is also true.

## Observation
If the object is deselected between step 2 and step 3 then expected behaviour is achieved. So what function should be called after every time set text method is called?

**Comment by asturur** [comment]
when a user is editing the text, the hidden textarea is in charge and will overwrite the text with its content.


if you want to modify text during editing outside the user input you have to exit and re enter editing from the buttons, before changing the text. You should also take note of where the user cursor is, and reposition it.

Alternatively you can try to modify the hidden textarea content during editing.

**Comment by asturur** [comment]
you find it under fabricObject.hiddenTextarea ( when the iText is editing and fabricObject is your iText/Textbox instance)
