### ISSUE TITLE
How to test fabric.js with Cypress?

### ISSUE THREAD

**Issue by nitingupta220** [fabricjs/fabric.js#5183]
I'm using fabric.js on my website. I want to test my website so I need to test fabric.js as well.
I'm using Cypress.io. How do I test Fabric.js with Cypress? @kangax @Kienz @asturur

**Comment by asturur** [comment]
i do not know cypress at all. Testing fabricjs interactions is hard, since you may need to target specific points of the canvas element if you are talking about interactions.

How does a cypress test looks like?

**Comment by nitingupta220** [comment]
Okay, but how do you test fabric.js?
Are you using any tool or doing it manually?

**Comment by asturur** [comment]
Is still unclear what you want to test. Can you make an example?

**Comment by nitingupta220** [comment]
Basically I'm using Fabric.js on my website to draw some graphs. And I want to test these graphs like they have rendered properly or not. And also I have built some tools with the fabric.js as well like I made an Geozebra graph by using it.
Now I want to test it whether it rendered properly or not. 

Let me know if this is good or you want any more info.

**Comment by asturur** [comment]
so in our package.json, follow what the test:visual script does and do something similar.
