### ISSUE TITLE
Ensure fabric.Image exists

### ISSUE THREAD

**Issue by BradleyHill** [fabricjs/fabric.js#5185]
Pretty simple (but pretty specific).

Angular @angular-devkit/build-angular version 0.6.8 and higher fail to build in aot mode on fabric.js.
```
ERROR in ./node_modules/fabric/dist/fabric.js
Module build failed: Error: Debug Failure. False expression.
    at forEachIdentifierInEntityName (./node_modules/typescript/lib/typescript.js:24115:26)
```

Digger into the bowels of the build, it seems that it does not like that `fabric.Image.filters` is created when no guarantee `fabric.Image` exists. Adding the following line:
`fabric.Image = fabric.Image || { };`
before
`fabric.Image.filters = fabric.Image.filters || { };`
remedies this. Shouldn't affect any existing functionality (and seems like best practice).

**Comment by asturur** [comment]
i think the build just know that Image file is included before the Filters files.

Feel free to open a pr to fix it.

This is a typescript thing looks like, not a KS problem right?

**Comment by BradleyHill** [comment]
Tis a typescript thing and only in `production` mode i.e. strict. Working on PR. Trying to be a contributor and not just taker. Hopefully soon.

**Comment by asturur** [comment]
I merged and closed too fast.
We need to modify not dist/fabric.js BUT just the file of the filters itself ( i think is base_filter in filters folder ).

fabric.js gets built once in a while later.

**Comment by BradleyHill** [comment]
Made changes.
Was following the build. Haven't used Travis CI yet. Looks nice.

**Comment by asturur** [comment]
looks good. i merged it. Is a non harmful change for sure.
