### ISSUE TITLE
IText Copy works first time, then holds first value forever

### ISSUE THREAD

**Issue by gotjoshua** [fabricjs/fabric.js#5189]
https://codepen.io/gotjoshua/pen/XPWLry?editors=0010

I am drawing a color wheel and fabric is setting the value of the IText element to the hex code perfectly. It also _appears_ to be selecting the text.

First Copy&Paste works...
Every subsequent copy paste is stuck with the first clicked value.

Also not fixed by:
fabric.Object.prototype.objectCaching = false

Is this a bug or is there something i can do differently in the setting/selecting process?

Also is there an easy way to copy it to the clipboard automatically?

**Comment by asturur** [comment]
i do not understand the second enterEditing call.

It may be that since is on a mousedown, the mouseup is like removing the focus from the textbox?

Did you try to execute the same code but on the mouseup event, and eventually wrap the enterEditing / selectAll in a setTimeout?

**Comment by gotjoshua** [comment]
i removed the second enter editing and did as you suggest: mouseup + setTimeout...

IText (or maybe it is Chrome in this case) seems quite convinced that the selected value is the first clicked value)

Any other ideas to try?

**Comment by asturur** [comment]
oh yes, please exitEditing before setting the new text. that could be the problem. Otherwise, i do not know.

**Comment by gotjoshua** [comment]
bingo! thanks a lot!
somehow makes sense, but still weird behavior to visually see that the text changes and the new text is selected - but the old one gets copied... i'd still consider this a bug 
Thanks for the easy workaround...

**Comment by asturur** [comment]
can t really support a situation in which both the textarea for the input and the javascript dev code fight for control.
If you want to edit, enterEditing and exitEditing when you are done. I believe a bunch of weird situations would pop out with too much freedom
