### ISSUE TITLE
Documentation: object:added event missing

### ISSUE THREAD

**Issue by awehring** [fabricjs/fabric.js#5191]
## Version
2.3.6

In the documentation for the canvas is the `object:added` event not mentioned, but it is still working.

It should have been corrected here, but still is not: #4668 

I think it should be added in the Event Inspector too: http://fabricjs.com/events

## Test Case
http://jsfiddle.net/awehring/g6rd3mc1/

## Steps to reproduce
Run the fiddle.
Click button "Add Rect"

## Expected Behavior
Alert "object:added" appears, new rectangle appears after OK.

## Actual Behavior
Works, only documentation is missing the `object:added` event for the canvas object.

**Comment by asturur** [comment]
In the staticCanvas doc you can see that object:added and object:removed are available.
