### ISSUE TITLE
SVG letter-spacing is calculated wrongly

### ISSUE THREAD

**Issue by teohhanhui** [fabricjs/fabric.js#5192]
## Version
`master` @ 2a476e4 (did `npm run build` to build `dist`)

## Test Case
https://fabricjs-issue-svg-letter-spacing.netlify.com/

## Steps to reproduce
1. Load SVG which uses `letter-spacing` and `transform`

## Expected Behavior
`letter-spacing` is not affected by `transform`

## Actual Behavior
`letter-spacing` is affected by `transform`

Looks like a similar bug happened in Chrome before: https://stackoverflow.com/questions/36132450/chrome-v49-letter-spacing-in-svg-with-transform-matrix/36764459

**Comment by teohhanhui** [comment]
`letter-spacing` support was introduced in #3718

**Comment by asturur** [comment]
can you link the SVG?
fabric letterspacing is affected by transform. and it will be.

**Comment by teohhanhui** [comment]
You mean `charSpacing`, right? Then we cannot use it for SVG / CSS `letter-spacing`. At least not directly like it is now.

**Comment by teohhanhui** [comment]
Links to sample SVGs:

https://fabricjs-issue-svg-letter-spacing.netlify.com/svg/SN131.svg
https://fabricjs-issue-svg-letter-spacing.netlify.com/svg/SN404P-left.svg

**Comment by asturur** [comment]
So regarding:
`letter-spacing is not affected by transform`
I do not understand where this come from.

Letter spacing is affected by transform, indeed i put a scale 0.2 on the SVG and the letter-spacing is reduced to mantain proportions.

![image](https://user-images.githubusercontent.com/1194048/44555383-2d4e1f80-a735-11e8-9e20-f0ee47658a18.png)

There are 2 bugs here:
1) fabric interprets the number as .em, while being without unit should be 5px.
2) at the moment of parsing the fontSize is considered 16px, that throws out calculations.

If we could know that at this point fontSize is 220px, this would parse correctly

**Comment by teohhanhui** [comment]
Sorry about my misunderstanding of the problem. And thanks for investigating! :)

**Comment by teohhanhui** [comment]
Anyway, I've just realized that in the sample SVGs I've provided, the `letter-spacing` CSS property actually has an invalid value (it cannot be unit-less), while the `letter-spacing` SVG attribute (which could be unit-less) is poorly supported: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/letter-spacing#Usage_Note

Seems like Adobe Illustrator generates invalid values on SVG export.

**Comment by asturur** [comment]
well now works better!

**Comment by teohhanhui** [comment]
Indeed. But there's still another rendering issue in the second sample SVG. I'm not quite sure what's going on. It's around the multiple `<tspan>` with `x` and `y` attributes.

**Comment by asturur** [comment]
tspans are unsopperted yet
