### ISSUE TITLE
canvas.loadFromJSON() does not work with JSON that have filter types "Tint"

### ISSUE THREAD

**Issue by duydodevgithub** [fabricjs/fabric.js#5193]
Hello, 
My node version is v8.11.4 and fabric 2.3.6, canvas@1.6.11
I need help for an issue with loadFromJSON method 

var jsonString = '{"objects":[{"type":"image","originX":"left","originY":"top","left":228.81,"top":201.39,"width":500,"height":500,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1.26,"scaleY":0.6,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","original_left":228.8125,"original_top":201.38509656161,"original_scaleX":1.25875,"original_scaleY":0.60242973576949,"original_zoom":1,"original_init":0,"objectType":"","objectShape":"","lockUniScaling":false,"src":"https://nbpublic.s3.amazonaws.com/product_cliparts/most-popular/HfhlAohkgE55035309b9946_thumb.png?v=0.9847660759261536","filters":[{"type":"Tint","color":"#ffffff","opacity":1}],"crossOrigin":"anonymous","alignX":"none","alignY":"none","meetOrSlice":"meet","imageType":"Stock","cloudinarySrc":"","filterType":"Tint","hexcodes":["#040708"],"removedBackground":false}],"background":"","zoom":1}';

The code break at function:
canvas.loadFromJSON(jsonString, function(
       console.log("Display from here");
) {})

-----When I remove "type": "Tint" in "filters":[{"type":"Tint","color":"#ffffff","opacity":1}]  then it works perfect

Please help !
Thank you.

**Comment by asturur** [comment]
Yes Tint filter has been removed.
There are some guideline to fix the JSON:

http://fabricjs.com/fabric-filters

**Comment by duydodevgithub** [comment]
@asturur Do you know the latest version that work with tint filter?  Thank you :)

**Comment by asturur** [comment]
1.7.22

But you should just pre process the Tint filter and replace Tint with BlendColor, and move on.
