### ISSUE TITLE
Scaling SVG-created object doesn't match changes to bounding box height/width

### ISSUE THREAD

**Issue by RavenHursT** [fabricjs/fabric.js#5195]
So, I've been trying to make it so that I could load an SVG icon and programmatically resize it.  But I keep running into this issue.  It _seems_ like a bug.  Logically, if I have an svg that, once parsed, and grouped into a Fabric object, has a height and width of X and Y, respectively.  But I _want_ it drawn on the canvas w/ `w` and `h`, then the scaling ration _should_ be `w/X` and `h/Y`, right?

But instead, I get _some_ scaling, but ultimately, it doesn't match the bounding box `w` & `h`.

I have an example here: http://jsfiddle.net/ax5b7vmt/32/

![image](https://user-images.githubusercontent.com/496983/44549769-1802d200-a6f0-11e8-8fed-e3370223ac69.png)

Now.. maybe I'm just doing something wrong?  I dunno. Really just looking for some help here....

**Comment by asturur** [comment]
http://jsfiddle.net/ax5b7vmt/34/

You should not try to set width/height for a group.
Just set scaleX and scaleY for it.

**Comment by RavenHursT** [comment]
Thank you!
