### ISSUE TITLE
Text shadow effect is not being display while objectCaching is disable and under line is applied on text

### ISSUE THREAD

**Issue by shaktippatel** [fabricjs/fabric.js#5196]
## Version
2.3.6

## Test Case
https://jsfiddle.net/shaktipatel/ruLydzsn/

## Steps to reproduce
objectCaching is disable for object
fabric.Object.prototype.objectCaching = false;

## Expected Behavior
Shadow effect should display on text and underline both.

## Actual Behavior
Shadow effect is not being display in text while apply underline on same text

**Comment by asturur** [comment]
we could shadow it eventually. Unsure if is good.

I rember the underline has been moved before text because we did not want the descendant to be under the underline.

**Comment by asturur** [comment]
duplicate of #5364
