### ISSUE TITLE
Multiple canvas elements one above the other - no interaction possible after switching to each other

### ISSUE THREAD

**Issue by JezzeBlue** [fabricjs/fabric.js#520]
Example: http://jsfiddle.net/fpHaE/

Try the following: push the button Drop Text. Move the text. Push the button View 2 and then Drop text. Try to move this text. It is not possible. If you switch back to View 1 you can move this text normally.

I have the following situation: two canvas elements, one is "display: block" the other is "display: none". I add a text to the first canvas and can interact with it (move, resize...). Now I switch to the other canvas element. First one is "display: none" and second "display: block" now. I add a text to the second canvas. Now the problem: I cannot interact with the added text (no selection possible). If I switch back to the first canvas, I can interact normally with the text on this canvas. I tried different things but as long as the canvas elements are on the same position after they are turned to visible there is no interaction possible.

As long as the elements are not at the same position (e.g. visibilty: visible and visibility: hidden) but one is above of other all is working fine.

What also helps: if you resize the browser window the canvas element is getting back its interaction. But then the other is not working anymore. Really strange behavior.

**Comment by Khadreal** [comment]
Is there a solution to this am having the same issue, anybody with a solution

Thanks

**Comment by asturur** [comment]
you should add some context to help understanding what are you doing.

**Comment by Khadreal** [comment]
Thanks @asturur 
I have two canvasses using jquery to  show/hide 

`<div id='preview_t'>
<div id="preview_front" style="background-color: rgb(255, 255, 255);">
<img id="tshirtFacing" src="tdesignAPI/images/product/crew_front.png">
<div class="front_print"><canvas id="tcanvas" width=200 height="400" class="hover" style="-webkit-user-select: none;"></canvas>
</div>
			</div>
div id="preview_back" style="background-color: rgb(255, 255, 255);">
				<img src="tdesignAPI/images/product/crew_back.png">
				<div class="back_print">
					<canvas id="tbcanvas" width=200 height="400" class="hover" style="-webkit-user-select: none;"></canvas>
				</div>
			</div>
		</div>`
The first canvas is selectable but the other canvas is not selectable.

Thanks

**Comment by asturur** [comment]
make a jsfiddle pleaee

**Comment by Khadreal** [comment]
Thanks @asturur .
here is a link https://jsfiddle.net/nvo5ynuj/1/
But while I was trying to set up on fiddle I solve the issue.

Thanks

**Comment by asturur** [comment]
90% of the time reducing the code to the minimal amount to reproduce the
issue, surface the issue.

**Comment by abhisb** [comment]
I'm also having the same issue. In my case, I want to show two fabric canvases where one over the other. The issue what I'm facing is events are not getting propagated to the sibling fabric canvas element instead events are fired only for the top most fabric canvas element in the DOM.

I have customized the plunkr of @Khadreal .  Here is the link [https://jsfiddle.net/nvo5ynuj/1/](https://jsfiddle.net/nvo5ynuj/1/)

In the above example, I'm unable to select the fabric object of second fabric canvas after adding it.

**Comment by asturur** [comment]
to be honest i do not remember if fabricjs stop event propagation, nor i do remember how siblings css positioned should behave.

can you replicate a click on 2 sibling canvases, without using fabric but using a simple event listener?

**Comment by VinAr22** [comment]
> I'm also having the same issue. In my case, I want to show two fabric canvases where one over the other. The issue what I'm facing is events are not getting propagated to the sibling fabric canvas element instead events are fired only for the top most fabric canvas element in the DOM.
> 
> I have customized the plunkr of @Khadreal . Here is the link https://jsfiddle.net/nvo5ynuj/4/
> 
> In the above example, I'm unable to select the fabric object of second fabric canvas after adding it.

Hi! Did you solve your problem? If that could you share code snippet please?
