### ISSUE TITLE
Applying filters to image cuts the image when using specific image

### ISSUE THREAD

**Issue by ickata** [fabricjs/fabric.js#5200]
## Version
2.3.3+

## Test Case
https://codepen.io/anon/pen/rZerWW

## Steps to reproduce
Use this image:
https://images.pexels.com/photos/414171/pexels-photo-414171.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260

Apply any filter to it, the final result is the image being cut on the right side.

## Expected Behavior
Filter is properly applied and image is not cut.

**Comment by maxim-torba** [comment]
It's not about specific image, it's about big image with big texture size that bigger than default in fabric (2048).
Try this (before add image to canvas):
`
let imageTextureSize = img.width > img.height ? img.width : img.height;

if (imageTextureSize > fabric.textureSize) {
        fabric.textureSize = imageTextureSize;
}
`

**Comment by ickata** [comment]
@maxim-torba : that solved it. Thanks a lot!

**Comment by asturur** [comment]
be carefull you can change it once. after filtering another change will not have effect.

As an app developer you should pick a limit and make the pictures fit the limit.

**Comment by superdevkit** [comment]
i have a similar issue but i can solve it .thanks maximum torba
