### ISSUE TITLE
canvas.setWidth(NUMBER) distorts the objects

### ISSUE THREAD

**Issue by lonelydatum** [fabricjs/fabric.js#5201]
After changing the canvas width 
canvas.setWidth(NUMBER)
the objects get distorted. I created a demo 
https://codesandbox.io/s/0py34838jp
change the input field to change the canvas size.

Thank you!

**Comment by asturur** [comment]
Code looks right, but i can't rule out strange interactions between sanbox react and style and fabric.js

Can you replicate in a small fiddle without react?

Also please remind inputs give back STRINGS while setWidth by docs wants a number.

**Comment by asturur** [comment]
i think the problem is in the double update that react causes to the canvas. the bug is probably visible only on screens with pixelRatio different than 1.

You can t resize a canvas with setWidth and then change is width property later with the component rerender.

**Comment by lonelydatum** [comment]
Yep adding this fixes the issue. Both on retina and non retina

componentDidUpdate(){
    this.canvasFabric.setWidth(this.state.width);
  }

**Comment by lonelydatum** [comment]
updated sandbox for anyone who is having the same issue.
https://codesandbox.io/s/0py34838jp
