### ISSUE TITLE
Cursor events not detected on overlapping objects with selectable:false

### ISSUE THREAD

**Issue by AshwinTayson** [fabricjs/fabric.js#5203]
## Version
2.3.5

## Test Case
http://jsfiddle.net/Da7SP/2732/

## Steps to reproduce
Case 1: Hover over the red rectangle overlapped by the blue
Case 2: Click the red rectangle overlapped by the blue
Case 3: Mouse down and drag the red rectangle overlapped by the blue, then mouse up

## Expected Behavior
Case 1: Mouse cursor should have a 'pointer' cursor
Case 2: Red rectangle should be selected
Case 3. Red rectangle should be dragged

## Actual Behavior
Case 1: It takes default cursor. Something like css pointer-events: none is needed for objects with selectable: false
Case 2: Red rectangle is selected (Pass)
Case 3: It creates a selection box and then the red rectangle is selected. If any other object is nearby the whole group is selected.

I'm not sure if this is a bug or a feature request. Is it possible to detect the object underneath while hovering, when objectPreserveStacking is true? How should this be handled? Is there a CSS property like pointer-events: none?

**Comment by asturur** [comment]
i m confused.
The red should not be selectable at all under a unselectable blue.
I need to verify why/how.
But this cannot be fixed before we get interaction tests, or will likely break again.

The property you are looking for is maybe:
http://fabricjs.com/docs/fabric.Object.html#evented

**Comment by AshwinTayson** [comment]
I'm sorry I forgot to close this issue. After scouring through the doc I found **evented** as you pointed out. Thanks for the response.

**Comment by asturur** [comment]
still i see a bug, do not close

**Comment by asturur** [comment]
not really. that would be an object without  mouse events.

Unselectable has always been that does not get selected as side effect of mouse down, but it will consume the click
