### ISSUE TITLE
option "canvas.renderOnAddRemove" doesn't apply when "canvas.loadFromJSON"

### ISSUE THREAD

**Issue by salomonsanz** [fabricjs/fabric.js#5204]
## Version
2.3.6

## Test Case
http://jsfiddle.net/5KKQ2/5582/

## Steps to reproduce
- Create a canvas.
- Set: canvas.RenderOnAddRemove = false
- Use the canvas.loadFromJSON method

## Expected Behavior
It shouldn't render the canvas

## Actual Behavior
Inmediately the canvas is rendered.

**Comment by asturur** [comment]
yes, loadfromJson has an embedded renderAll that i could not remove because it would have break eventually all the app that upgraded.

I do not know if is cancellable at all.
