### ISSUE TITLE
oCoords value changed after setCoords but the position has not changed

### ISSUE THREAD

**Issue by muxi2015** [fabricjs/fabric.js#5206]
## Version
2.3.6

## Steps to reproduce
calll setCoords() method after chang object property 
## Actual Behavior
![New-Project.png](http://imgup.nl/images/2018/08/31/New-Project.png)

**Comment by asturur** [comment]
can you make a jsfiddle?

**Comment by muxi2015** [comment]
@asturur The strange thing is that it can only be appear on the company's computer.

**Comment by muxi2015** [comment]
[![code](http://imgup.nl/images/2018/09/02/QQ20180902-203745.png)](http://imgup.nl/image/Uxx)

[![consolg.log](http://imgup.nl/images/2018/09/02/QQ20180902-203558.png)](http://imgup.nl/image/Uxy)

**Comment by muxi2015** [comment]
[ggg](https://gfycat.com/MatureNiceIsabellineshrike)

**Comment by asturur** [comment]
Sorry for not getting back, is some kind of application problem that i do not have the time to dig deeper into, but:

Position will not change visually if you do not call renderAll, setCoords will just change the interactivity points for the mouse when you change top/left/width/height manually.
