### ISSUE TITLE
lottie animation in fabricjs canvas

### ISSUE THREAD

**Issue by sbala69gmail** [fabricjs/fabric.js#5207]
Hi,
   Is it possible to load lottie animation in fabricjs canvas.

**Comment by asturur** [comment]
what is a lottie animation?

**Comment by sbala69gmail** [comment]
`https://github.com/airbnb/lottie-android`  it loads After Effect Json to canvas

**Comment by asturur** [comment]
well as of now no.
Can be done? maybe yes.
depends what is in that json files and someone has to make a kind of adapter.

**Comment by sbala69gmail** [comment]
Thank you @kristianAndersen

**Comment by alexsprings** [comment]
If of any help, I've created this Lottie class with the support of exporting toObject/JSON
`import { fabric } from 'fabric'
import lottie from 'lottie-web'

const Lottie = fabric.util.createClass(fabric.Image, {
  type: 'lottie',
  lockRotation: true,
  lockSkewingX: true,
  lockSkewingY: true,
  srcFromAttribute: false,

  initialize: function (path, options) {
    if (!options.width) options.width = 480
    if (!options.height) options.height = 480

    this.path = path
    this.tmpCanvasEl = fabric.util.createCanvasElement()
    this.tmpCanvasEl.width = options.width
    this.tmpCanvasEl.height = options.height

    this.lottieItem = lottie.loadAnimation({
      renderer: 'canvas',
      loop: true,
      autoplay: true,
      path,
      rendererSettings: {
        context: this.tmpCanvasEl.getContext('2d'),
        preserveAspectRatio: 'xMidYMid meet',
      },
    })

    // this.lottieItem.addEventListener('DOMLoaded', () => {
    //   console.log('DOMLoaded')
    // })

    this.lottieItem.addEventListener('enterFrame', (e) => {
      this.canvas?.requestRenderAll()
    })

    this.callSuper('initialize', this.tmpCanvasEl, options)
  },

  play: function () {
    this.lottieItem.play()
  },
  stop: function () {
    this.lottieItem.stop()
  },
  getSrc: function () {
    return this.path
  },
})

Lottie.fromObject = function (_object, callback) {
  const object = fabric.util.object.clone(_object)
  fabric.Image.prototype._initFilters.call(object, object.filters, function (filters) {
    object.filters = filters || []
    fabric.Image.prototype._initFilters.call(object, [object.resizeFilter], function (resizeFilters) {
      object.resizeFilter = resizeFilters[0]
      fabric.util.enlivenObjects([object.clipPath], function (enlivedProps) {
        object.clipPath = enlivedProps[0]
        const fabricLottie = new fabric.Lottie(object.src, object)
        callback(fabricLottie, false)
      })
    })
  })
}

Lottie.async = true

export default Lottie`

To create Lottie element just pass JSON:
`const fabricImage = new fabric.Lottie('https://assets5.lottiefiles.com/private_files/lf30_rttpmsbc.json', {
          scaleX: 0.5,
        })
        canvas.add(fabricImage)
`

**Comment by HammerMax** [comment]
👆 works for me，thanks

**Comment by asturur** [comment]
i do not know how common and adopted is this lottie format.
If you think is important, please feel free to opena repository with this subclass code, or we can have another repository in this organization where we store all this dev contributed specific sub classes

**Comment by graphics-et-al** [comment]
It's getting more common- I'm using it.
My code is:
`// animation class
fabric.AeAnimation = fabric.util.createClass(fabric.Image, {
    type: 'aeAnimation',
    initialize: function (AECanvas, anim_object, options, uuid) {
        // console.log('AeAnimation initialize')
        // console.log(uuid)
        this._uuid = (typeof uuid !== 'undefined') ?  uuid : uuidv4();
        this._AECanvas = AECanvas;
        this._anim_object = anim_object;
        options = options || {};
        this.callSuper('initialize', AECanvas, options);
    },

    drawCacheOnCanvas: function (ctx) {
        ctx.drawImage(this._AECanvas, -this.width / 2, -this.height / 2);
    },


    // override the fabric-extensions image editing stuff, it messes with the  rendering
    registerEditingEvents: function () {
        return;
    },

    toObject: function () {
        return fabric.util.object.extend(this.callSuper('toObject'));
    },

    _createCacheCanvas: function () {
        // console.log('override!!!')
        this._cacheProperties = {};
        this._cacheCanvas = this._AECanvas;
        // console.log(this._cacheCanvas)
        this._cacheContext = this._cacheCanvas.getContext('2d');
        // debugger
        // this._updateCacheCanvas();
        // if canvas gets created, is empty, so dirty.
        this.dirty = true;
    },
    render: function (ctx) {
        // do not render if width/height are zeros or object is not visible
        if (this.isNotVisible()) {
            return;
        }
        if (this.canvas && this.canvas.skipOffscreen && !this.group && !this.isOnScreen()) {
            return;
        }
        ctx.save();
        this._setupCompositeOperation(ctx);
        this.drawSelectionBackground(ctx);
        this.transform(ctx);
        this._setOpacity(ctx);
        this._setShadow(ctx, this);
        if (this.transformMatrix) {
            ctx.transform.apply(ctx, this.transformMatrix);
        }
        this.clipTo && fabric.util.clipContext(this, ctx);
        if (this.shouldCache()) {
            if (!this._cacheCanvas) {

                this._createCacheCanvas();
            }
            this.drawCacheOnCanvas(ctx);
        } else {
            this._removeCacheCanvas();
            this.dirty = false;
            this.drawObject(ctx);
            if (this.objectCaching && this.statefullCache) {
                this.saveState({propertySet: 'cacheProperties'});
            }
        }
        this.clipTo && ctx.restore();
        ctx.restore();
    }
});

// used to recreate an animation when canvases are restored
fabric.AeAnimation.fromObject = (obj, callback) => {
    let animationData = JSON.parse(obj.animation_data);
    //const animationDataParsed = JSON.parse(animationData)
    //console.log('fabric.AeAnimation.fromObject parsing:')
    //console.log(obj)
    const animationWidth = animationData.w
    const animationHeight = animationData.h
    // temporary canvas
    let temp_canvas = document.createElement('canvas')
    temp_canvas.width = animationWidth;
    temp_canvas.height = animationHeight;

// canvas.getContext('2d').setTransform(0.5,0,0,0.5,30,30)
    //const svgContainer = document.getElementById('svgContainer')
    let animItem = bodymovin.loadAnimation({
        renderer: 'canvas',
        loop: obj.loop,
        autoplay: obj.autoplay,
        animationData: animationData,
        rendererSettings: {
            context: temp_canvas.getContext('2d'), // the canvas context
            preserveAspectRatio: 'xMidYMid meet',
            // clearCanvas: false,
        }
    });
    animItem.addEventListener('DOMLoaded', () => {
        window.tempEl = animItem
        callback && callback(new fabric.AeAnimation(temp_canvas, animItem, obj, ));
    })

    //return fabric.Object._fromObject('AeAnimation', object, callback);
};

fabric.AeAnimation.async = true;`

Usage (loading from Lottie data from an axios/ajax call or something):
`let animationData = data; // this data is from the we
        //const animationDataParsed = JSON.parse(animationData)
        const animationWidth = animationData.w
        const animationHeight = animationData.h

        console.log('available_colourways are:' + animationData.colourways)

        // temporary canvas
        let temp_canvas = document.createElement('canvas')
        temp_canvas.width = animationWidth;
        temp_canvas.height = animationHeight
        let animItem = bodymovin.loadAnimation({
            renderer: 'canvas',
            loop: true,
            autoplay: true,
            animationData: animationData,
            rendererSettings: {
                context: temp_canvas.getContext('2d'), // the canvas context
                preserveAspectRatio: 'xMidYMid meet',
            }
        });
        animItem.addEventListener('DOMLoaded', () => {
            window.tempEl = animItem
            // animItem.goToAndPlay(1, true)
            // console.log('total frames', animItem.getDuration(false))
            // console.log('DOMLoaded')
            let fabricAnimation = new fabric.AeAnimation(temp_canvas, animItem, {
                // scaleX: 0.25,
                // scaleY: 0.25,
                needsItsOwnCache: () => {
                    return true
                },
                objectCaching: false,
            }, uuidv4());

            canvas.add(fabricAnimation)
            fabricAnimation.loop = true;
            fabricAnimation.scaleToWidth(200)
            fabricAnimation.left = left / canvas.getZoom() + (fabricAnimation.getScaledWidth() / 2);
            fabricAnimation.top = top / canvas.getZoom() + (fabricAnimation.getScaledHeight() / 2);
            fabricAnimation.set({originX: 'center', originY: 'center'});
            fabricAnimation.setCoords();
            fabricAnimation.set('clipart_id', image_id);
            fabricAnimation.set('objectCaching', false)
            `

Apologies if it's missing bits/context, but it should be enough to give someone ideas :)

**Comment by ShaMan123** [comment]
cool repro
