### ISSUE TITLE
There is a layer of backgroud color above the svg in microsoft Edge

### ISSUE THREAD

**Issue by chenwei979** [fabricjs/fabric.js#5208]
## Version
2.3.6

## Test Case
https://codepen.io/chenwei979/pen/zJZgoG

## Steps to reproduce
click 'upload-svg' button under edge,
select the attached [svg file](https://drive.google.com/open?id=1i7rJF2A7k3u4IYgrudJ6ih5_L2GWBcKz),
the svg will be inserted to the canvas,
but there is a layer of backgroud color above the svg.

If you clear the canvas and upload again, It is working properly.

## Expected Behavior
There is no backgroud color above the svg in microsoft Edge.
It is work fine in chrome.

## Actual Behavior
There is a layer of backgroud color above the svg in microsoft Edge

**Comment by asturur** [comment]
i do not have edge.
Can you specify what edge version and add a a screenshot of the 2 different situations?
thanks.

**Comment by chenwei979** [comment]
@asturur ，My edge version is 41.16299.611.0 

Screenshot of the 2 different situations:
![image](https://user-images.githubusercontent.com/19570496/45073640-c8220300-b112-11e8-943a-08dcd38d1f62.png)
