### ISSUE TITLE
Clippath fabric 2.4

### ISSUE THREAD

**Issue by vxrai** [fabricjs/fabric.js#5209]
Hi 

As mentioned here in this tutorial - http://fabricjs.com/clippath-part1
clipPath property has been introduced for all objects in fabric 2.4
How can I upgrade to fabric 2.4??
When will it be added in the http://fabricjs.com/build/ , custom build page?

**Comment by vxrai** [comment]
@asturur

**Comment by vxrai** [comment]
is there a release date for v 2.4?

**Comment by asturur** [comment]
Clippath is merged in the main codeline, the 2.3.6, the next  version will be 2.4.0, released as soon as possible, with the feature as it is, with as much as tests as possible.
toSVG is still not working and fromSVG is working partially.

https://github.com/fabricjs/fabric.js/pull/5199

This PR contains 2 additional features and tests

**Comment by vxrai** [comment]
Hey @asturur . I'm using the latest version  2.3.6 right now and tried implementing the exact same code from the tutorial page - http://fabricjs.com/clippath-part4 , but it's not working at all. Is there some issue? It doesn't crop but returns the rectangles as it is.

**Comment by vxrai** [comment]
These examples - http://fabricjs.com/clippath-part4  should work fine the current release or do we need to wait for v 2.4 for these to work?

**Comment by vxrai** [comment]
My bad, i was using an older copy of v2.3.6,  just took the latest release and the examples seem to work fine. Thanks, genius!

**Comment by vxrai** [comment]
But for some reason, I'm getting this error after updating to the latest version of 2.3.6
TypeError: e.shouldCache is not a function
    at n._drawClipPath

**Comment by vxrai** [comment]
http://fabricjs.com/build/
