### ISSUE TITLE
Polygon crop + Clippath

### ISSUE THREAD

**Issue by vxrai** [fabricjs/fabric.js#5212]
I'm really excited about the much awaited clip-path feature and couldn't stop but create the polygon crop tool using fabric clip-path.
Its almost ready but unfortunately, there is some issue related to the positioning while setting the polygon as the clip path. 

Here is the code - https://codepen.io/vxrai/pen/RYVXjZ

@asturur i know you can fix this in less than 5 mins :)

**Comment by vxrai** [comment]
@asturur  - so i spent some time debugging and managed to make it work. Actually the issue that i'm facing is that if i try and align the image to the center of the canvas using -
cropimg.centerH().centerV().setCoords();
The code breaks and the crop doesn't work well. So how can we take care of positioning of items, as well as scale while we crop? What are your suggestions/solutions?

**Comment by vxrai** [comment]
@asturur  apologies for the inconvenience caused. 
I have commented the code now. Please have a look at it. 
The main problem is that the crop fails when we center align the image or scale the image that needs to be cropped. 
Let me know in case something is unclear.

**Comment by asturur** [comment]
Is unclear what kind of user interaction are you looking for and what the tool should do.
If the tool should just crop images, why should it be a clipPath absolute?

**Comment by vxrai** [comment]
Without "absolutePositioned: true" the crop doesn't happen.  The result show an empty selection

**Comment by vxrai** [comment]
So basically we want the user to select the crop path on mouse click. When the user clicks different points on the image, we generate a polygon and after that use the polygon as clip path to crop the image. What do you think?

**Comment by vxrai** [comment]
@asturur  is it clear now or you need more information?

**Comment by vxrai** [comment]
Hi @asturur  i figured that i wasn't placing this  line - cropimg.centerH().centerV().setCoords();
after adding the image which was causing the issue. 
Its fixed now. Thanks for your time!
