### ISSUE TITLE
base64 image + filters + mobile = black image

### ISSUE THREAD

**Issue by atlanteh** [fabricjs/fabric.js#5213]
## Version
2.3.6

## Test Case
https://codepen.io/atlanteh/pen/WgOyjq

## Steps to reproduce
Create a canvas with Image. Feed the image with base64 image data.
Apply a filter to the image (GrayScale, Sepia, Vintage, Technicolor, Kodachrome, etc.)

## Expected Behavior
Image is applied filters, both on web and on mobile

## Actual Behavior
Works fine on web but on mobile I'm getting black image

**Comment by asturur** [comment]
what mobile?

**Comment by atlanteh** [comment]
I checked it on a onePlus one with Chrome

**Comment by atlanteh** [comment]
Just checked with a Xiomi mi A1 and on this phone I see quarter of the image

**Comment by atlanteh** [comment]
Oh man, this sucks. I also see that even on desktop chrome, if I use [this image](https://purepng.com/public/uploads/large/purepng.com-mastercard-logologobrand-logoiconslogos-251519938372dnf77.png) then it only renders a quarter of it. If I want to have my users apply some filters on the photos before they upload them, how would I do it?

**Comment by atlanteh** [comment]
Ok, so finally I found a solution [here](https://stackoverflow.com/questions/46067427/applying-webgl-filter-on-hd-images-cuts-the-image-fabric-v2-beta-6).
The solution is to set fabric.textureSize=5000
