### ISSUE TITLE
How to limit the size of the font and the width and height of the text when the canvas is zoomed

### ISSUE THREAD

**Issue by xiayuan920** [fabricjs/fabric.js#5215]
When I zoomed the canvas, I found that the size of font and the width and height of the text were also scaled.Is there any way to disable this behavior? In the other words,I want the font and text box size to remain the same when the canvas is zoomed.
Looking forward to your reply,thank you!

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.
