### ISSUE TITLE
left top position is mismatching in rotation

### ISSUE THREAD

**Issue by sbala69gmail** [fabricjs/fabric.js#5217]
In cropping, while rotating an object with multiple paths left and top position is not placed correctly in that object  

```
var targetTop = (OriginalTarget.top * actObj.scaleX);
 var targetLeft = (OriginalTarget.left * actObj.scaleY);
 
 var convertToAngle = function(matrix) {
 var values = matrix.split('(')[1],
 values = values.split(')')[0],
 values = values.split(',');
 var sin = values[1];
 return Math.asin(sin) * (180/Math.PI);
 };
 
 var matrixVal;
 var cAngle;
 var targetRotate;
 if(fillElement.transformMatrix){  // Here transformMatrix - matrix(0.75, -0.566, 0.4567, 1.1243, 0, 0)
 matrixVal = "matrix("+fillElement.transformMatrix.toString()+")";
 cAngle = convertToAngle(matrixVal);
 targetRotate = cAngle + targetAngle;
 }else{
 cAngle = 0;
 targetRotate = 0;
 }
```

how should i get left and top position after rotation

- my object angle is like below image 

![mockup1](https://user-images.githubusercontent.com/2879062/45250553-0d347800-b353-11e8-937c-05c4af1cf19f.png)

-  when i click reposition(crop) my image left and top position is not fixed correctly

![mockup](https://user-images.githubusercontent.com/2879062/45250541-c050a180-b352-11e8-93a3-6d93581a170d.png)

**Comment by asturur** [comment]
Is completely unlcear to me what are you doing.
Are you trying to have an HTML setup as the canvas?

Does not look like a fabric.js library issue.
