### ISSUE TITLE
Select an object behind transparent object

### ISSUE THREAD

**Issue by lonelydatum** [fabricjs/fabric.js#5219]
Hi 

I have a large triangle that is on top of a small rect. How can I select the rect without first moving the triangle out of the way. 
I made a demo here:
https://codesandbox.io/s/w6wr7pmrx5

![image](https://user-images.githubusercontent.com/858774/45224640-6a172c00-b288-11e8-9b1f-5061c6f12b84.png)

Thank you.
Gar

**Comment by melchiar** [comment]
This is really more of a stackoverflow question than a bug. You need to enable `perPixelTargetFind: true` on your triangle.

http://fabricjs.com/docs/fabric.Object.html#perPixelTargetFind

**Comment by lonelydatum** [comment]
Thanks @melchiar Will keep those to SO in the future.
