### ISSUE TITLE
rect.set({ left: 125 }) the hover area is not updated

### ISSUE THREAD

**Issue by lonelydatum** [fabricjs/fabric.js#5220]
How can I use the "object.set({})"  and then have hover area update. For example when I move a rect to the left, visually the rect has moved but the hover area is still based on the previous left position. Do I need to do an additional render? I figured canvas.renderAll(); would be enough

Here is a demo 
https://codesandbox.io/s/rlo3ojwvp4

Click the button and then hover the cursor over the existing  spot. 

![image](https://user-images.githubusercontent.com/858774/45225555-d2670d00-b28a-11e8-8f90-33c9f3a50599.png)

**Comment by AlexSergey** [comment]
You need call setCoords

rect.set({ left: 125 }).setCoords();

**Comment by lonelydatum** [comment]
Thank you sooo much!! that worked!

Wonder why that is even needed. It would be nice if that was a default.

**Comment by AlexSergey** [comment]
setCoords - That way is very useful for some issues

**Comment by asturur** [comment]
is not automatic because it takes some calculatuons to get those.

Eventually when setting top, left, scaleX and angle of an object you do not want to calculate it 4 times.

**Comment by lonelydatum** [comment]
Thanks good to know. Thanks @asturur
