### ISSUE TITLE
Add correct clipping for objects in SVG

### ISSUE THREAD

**Issue by radykal** [fabricjs/fabric.js#5222]
## Version
2.3.5

## Test Case
https://jsfiddle.net/radykal/L32d795r/

I am trying to include the clipping of objects when exporting with toSVG. I am only using a rectangular clipping for elements, so I can create a clipPath with rect, which is also working. But my math skills seems to be to weak to calculate the  correct position and size for rect :) .
Just move the text element outside the blue box and click "Show SVG".

Does anyone knows how to calculate the correct position and size for rect:
`$svg.find('defs').append('<clipPath id="myclip"><rect x="' + (-text.width / 2) + '" y="' + (-text.height / 2) + '" width="' + text.width + '" height="' + text.height + '"></rect></clipPath>');`

Thanks

**Comment by asturur** [comment]
We are working on clipPath toSVG support that acutally is stopping the release of 2.4.0

For other custom implementation please open a clear question of stackoverflow, with a working stackoverflow snippet ( the embedded one ) and i will try to help you there.

Post the question link here
