### ISSUE TITLE
Mouse icons on customized controls don't change after padding and cornerSize, before moving object.

### ISSUE THREAD

**Issue by jorgeecardona** [fabricjs/fabric.js#5228]
## Version
2.3.6

## Test Case
In the official demo page for controls customization: http://fabricjs.com/controls-customization

## Steps to reproduce
1) Notice the locations where the mouse icon changes when hovering on the controls.
2) Change padding to its maximum.
3) Without clicking notice that the mouse icon doesn't change when hovering on the controls.
4) Move the object.
5) Notice that now the icons react properly when hovering on the controls.

## Expected Behavior
In step 3 we should expect for the correct mouse icons when hovering on the controls.

## Actual Behavior
See the steps to reproduce.

**Comment by jorgeecardona** [comment]
In my own test just adding `object.setCoords();`  after the padding and cornerSize are set solves the problem.

**Comment by asturur** [comment]
i updated the demo and i will update it on the next website update.
Thanks
