### ISSUE TITLE
Use SVG for background/overlay

### ISSUE THREAD

**Issue by kingschnulli** [fabricjs/fabric.js#5230]
It seems like the documentation currently states that canvas.setBackgroundImage and canvas.setOverlayImage have to use a fabric.Image instance. This is not true, you can just set any fabric.Object for this - I just used a group object currently. Maybe the docs can be improved for this part.

**Comment by asturur** [comment]
Yes this is true, a part of breakin 2.0 changes was to change on backgroundObject and overlayObject, backgroundFill and overlayFill ( since backgroundColor can be a fill or a pattern too ).
But then it looked like it was too much of an hassle.

I ll check what docs can be udpdated.

**Comment by asturur** [comment]
http://fabricjs.com/fabric-intro-part-4#customization

docs updated.
