### ISSUE TITLE
Transfer control of fabric.StaticCanvas to offscreen?

### ISSUE THREAD

**Issue by vinch** [fabricjs/fabric.js#5231]
Since Chrome 69 which was released very recently, it's possible to render graphics off the main thread with `OffscreenCanvas`. This results in speed improvements as canvas rendering doesn't mess with the main thread.

The full article is here: https://developers.google.com/web/updates/2018/08/offscreen-canvas

Until now, what I did when I needed to render stuff that should not be directly visible on screen is to do it with a `fabric.StaticCanvas` that I hid with CSS styles. It works OK but you can really feel that everything becomes laggy when something is currently rendering in the canvas.

In the article above, they give an example of `OffscreenCanvas` working with a third-party library (three.js in that case) so I gave it a try with Fabric.js (v2.3.4).

Here is what I did:

```
const canvasEl = document.querySelector('canvas');
const canvas = ('OffscreenCanvas' in window) ? canvasEl.transferControlToOffscreen() : canvasEl;

const fabricCanvas = new fabric.StaticCanvas(canvas, {
  width,
  height,
});
```

Unfortunately, it directly results in the following error:

`this.lowerCanvasEl.setAttribute is not a function`

This is because we try to add attributes to the canvas element (lines 6724 and 6725 here http://fabricjs.com/docs/fabric.js.html) but this is obviously not possible with `OffscreenCanvas` as there is no DOM as soon as you transfer control to offscreen (that's the whole point of it).

So, my question(s): Is there something we can do about it? Some kind of quick fix (even if it's a little dirty at first) that would make it possible, at least with fabric.StaticCanvas? If yes, could you point me in the right direction so perhaps we can submit a PR or something?

Thanks a lot.

**Comment by asturur** [comment]
Filtering for sure.
ObjectCaching for sure.

Unsure what 'non main thread means'

But is something we have to look into.

Want to open a topic in the api-discussion repo in the organization?

**Comment by asturur** [comment]
Also i do not think that rendering everything on a offscreen and then copying in the onscreen part would actually speed up. But we can try.

I m really busy those weeks.
I have a long queue of fabricjs email to handle and i will be not as responsive as usual.

**Comment by melvynhills** [comment]
> Unsure what 'non main thread means'

He means `OffsreenCanvas` can be run in a web worker, so it doesn’t block the main thread that is responsible for the DOM and normal JS execution.

**Comment by asturur** [comment]
Ok i thought i was an hidden thread like the one from network request or js parsing and optimization.

Depending how easy is to pass in the worker thread all the rest, we will see.

I do think needs some planning. I do not think just pulling it in will give benefits.

Also becomes async....

**Comment by vinch** [comment]
@asturur No stress, it's not an emergency. I just wanted to know your opinion on this and if you had an idea of something that could be easily feasible but you're right, let's do our research and do it properly.

**Comment by johannb75** [comment]
Any update on this ?

**Comment by asturur** [comment]
no one looked into this, is unclear if it would give any real advantage over the added complexity of loosing syncronousness
Do you have any specific idea in mind?

**Comment by codebycarlos** [comment]
Could this perhaps come in handy in situations where you need to create lots of canvases on the fly for the purpose of exporting their data to, say, PNG images? In such situations you make use of the FabricJS programmatically to draw but you don't care about actually rendering on the DOM. I'm not familiar with OffscreenCanvas but it's possible this unique use case could benefit.

**Comment by asturur** [comment]
this could work.
But does not need to be backed by us entirely.
We need to verify that fabricJS can actually render in a worker.

**Comment by rockerBOO** [comment]
I have a [project to test this scenario](https://github.com/rockerBOO/fabric-offscreen-canvas). Initially testing has these requirements to be met. 

* Detecting if in browser or node or worker
* Remove window/document references (not in workers)
* Send all events that could cause rendering to the worker. (mouse, touch, pointer, keyboard events)
 
offscreen canvas has limited browser support, which limits some motivation. Decoupling the canvas rendering off the main thread helps improve input latency and blocking with larger designs. 

I think initially something that decouples input handling and the rendering. This would then allow inputs to be sent to the worker to do the same behavior. The 2 canvas behavior currently works well with this as the upper could be on the main thread and the lower on the offscreen canvas, or both on offscreen canvas. 

I would be willing to talk further about what may be possible to allow. [three.js offscreencanvas](https://threejs.org/manual/#en/offscreencanvas) is a good overview of using their renderer with offscreencanvas.

**Comment by asturur** [comment]
The issue is that with large design at that point you would have lagging response time.
You would speed up the render only in 2 ways:
1- detect the area changed and refresh only that ( i have code for that but i don't have a worthy algorithm that works for many many objects )
2 - render the canvas in tiles in offscreen and stitch them in main thread

all cool stuff.

Consider tho transferring the pixel from the  extra thread to the main thread is in theory the slower part.

**Comment by asturur** [comment]
the renderer to refresh a single object will be committed sooner than later
