### ISSUE TITLE
Stickman Bug

### ISSUE THREAD

**Issue by njofce** [fabricjs/fabric.js#5232]
## Version
2.3.5

## Test Case
http://fabricjs.com/stickman

## Steps to reproduce
Without moving anything, when hovering over lines and circles, the drag cursor appears. After moving a circle, the new line coordinates does not get set properly (If you hover along the new line, no cursor appears, only on the previous coordinates. So the new line is not detected while the original coords are kept.

## Expected Behavior

The new line coordinates should be set properly and when hovering over the entire line, the drag cursor should appear.

## Actual Behavior

The drag cursor appears only over the original line coordinates, no matter how the line is moved.

**Comment by asturur** [comment]
I think the point of the demo is having just the circle interactive and the lines as drawings and nothing else.

I set the line as not evented, and i will push up with next update of fabricjs.com.

Thanks

**Comment by njofce** [comment]
@asturur 
I understand the point of the demo, but I noticed the bug when creating a circle with other lines added as properties and trying to update the coordinates of these lines as the circle was moving. 
Check the following fiddle(the stickman code, with the lines marked as selectable)
http://jsfiddle.net/h0sf3x5h/44/

If you move the circle then you can select the connected lines only by hovering over the previous line coordinates.

**Comment by asturur** [comment]
i think you should not be able to select the lines at all

**Comment by asturur** [comment]
If you want to select the lines, yes you have to call setCoords
