### ISSUE TITLE
v2 migration - migrate custom image class for animated sprites

### ISSUE THREAD

**Issue by mobidev111** [fabricjs/fabric.js#5237]
## Version
2.3.6

## Test Case

The custom image class "sprite" is used in the fabric.js demo "animated sprite":
http://fabricjs.com/js/sprite.class.js
http://fabricjs.com/animated-sprite

## Steps to reproduce

after migrating to fabric.js v2 the animations don't work in our code - which is uses the custom image class "sprite".

(I can create a working fiddle with the current demo code if it speeds you up)

## Expected Behavior
the sprites animate correctly

## Actual Behavior
* currently the demo "animated sprite" even fails with an angularJS 1.2.6 `Error: [$injector:modulerr]`
* after that the sprites don't animate

## Questions
- how and where to place scaling factor calculation for scaleX/scaleY as described in the v2 breaking changes doc?
- make animation work

**Comment by asturur** [comment]
the animation now work, we can probably refactor it to use the cropX, cropY feature and make it simpler.
