### ISSUE TITLE
feather edge

### ISSUE THREAD

**Issue by komagic** [fabricjs/fabric.js#5238]
Can you provide a sample with the feather edge, like https://codepen.io/kangax/pen/lpAnD  in fabric.js?
Thank you~

**Comment by asturur** [comment]
Hello, thanks for posting.

If you need help or information about fabricJS please try our docs
[http://fabricjs.com/docs](http://fabricjs.com/docs) Or try on StackOverflow forum.

If  you think you found a bug in the code or a strange behavour of some feature then create a basic jsfiddle that demonstrate the problem and explain it.

If you want to propose a feature please explain the use case for this feature, how it should work and why it would be usefull and if some other library / application already make use of that.

Issue different from those will be closed automatically.

You can link back the question here once you properly opened it

**Comment by komagic** [comment]
thanks,  I post it here because I don't know  how to do something when I use drawbrush？For example， I want to create feather edge for pencilbrush，but first of all，I need to get the real-time mouse's position, and then I need to draw a Rectangle or a circle which center is the mouse's position?
 I need the mouse's position and a method to draw a feather effect for pencil brush in fabric.js ^ ^, but  I cannot find a solution by fabric.js, maybe fabric could provide one?
