### ISSUE TITLE
toSVG() fails to export imported svg which contains 'polygon' nodes.

### ISSUE THREAD

**Issue by BobRazowsky** [fabricjs/fabric.js#5239]
I noticed that the SVG output from toSVG method misses a few parts of my imported svgs.
After inspection, the non rendered part where the ones defined as 'polygon' in the svg.
Converting the polygons to paths in Inkscape fix the problem.

`<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="775.6800000000001" height="242.4" viewBox="0 0 768 240" xml:space="preserve">
<desc>Created with Fabric.js 2.0.0-beta1</desc>
<defs>
</defs>
<rect x="0" y="0" width="775.6800000000001" height="242.4" fill="#FFFFFF"/>
<g id="db6349ef-5218-4f2d-856d-89b8d1ac91c5" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" transform="translate(262.37248677248675 -1.6275132275132336) scale(0.86 0.86)">
	<polygon id="polygon3732" points="NaN,NaN NaN,NaN NaN,NaN NaN,NaN " style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" transform="  matrix(1 0 0 1 0 0) "/>
	<polygon id="polygon3734" points="NaN,NaN NaN,NaN NaN,NaN NaN,NaN " style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" transform="  matrix(1 0 0 1 0 0) "/>
	<polygon id="polygon3736" points="NaN,NaN NaN,NaN NaN,NaN NaN,NaN " style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" transform="  matrix(1 0 0 1 0 0) "/>
	<path id="path3738" d="M 74 132.5 c -2 -3.7 7.2 -8.3 8.7 -5.2 c 1.5 3.1 35.5 31.8 35.5 38 c 0 6.2 0.1 63.9 0.1 63.9 H 79.6 v -44.8 c 0 0 -25.7 -35.7 -25.7 -46.7 s 1.2 -53.6 1.5 -63.1 c 0.2 -8.6 14.8 -8.3 14.8 -0.2 c 0 6.6 0.4 53.6 0.7 57.6 c 0.3 4 16.3 25 16.3 25 l 2.2 -1.5 C 89.3 155.4 76 136.2 74 132.5" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" transform=" matrix(1 0 0 1 0 0) " stroke-linecap="round"/>
	<path id="path3740" d="M 209.2 132.5 c 2 -3.7 -7.2 -8.3 -8.7 -5.2 c -1.5 3.1 -35.5 31.8 -35.5 38 c 0 6.2 -0.1 63.9 -0.1 63.9 h 38.7 v -44.8 c 0 0 25.7 -35.7 25.7 -46.7 s -1.2 -53.6 -1.5 -63.1 c -0.2 -8.6 -14.8 -8.3 -14.8 -0.2 c 0 6.6 -0.4 53.6 -0.7 57.6 c -0.3 4 -16.3 25 -16.3 25 l -2.2 -1.5 C 193.9 155.4 207.2 136.2 209.2 132.5" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" transform=" matrix(1 0 0 1 0 0) " stroke-linecap="round"/>
</g>
</svg>`

**Comment by asturur** [comment]
can i see the original svg?

**Comment by BobRazowsky** [comment]
`<?xml version="1.0" encoding="utf-8"?>

<svg version="1.1" id="Calque_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 283.5 283.5" style="enable-background:new 0 0 283.5 283.5;" xml:space="preserve">
<g>
	<polygon points="139.9,53.5 102.2,84.3 143.2,115.6 179.2,82.6 	"/>
	<polygon points="101,88.8 101,123.1 140.2,157.4 140.2,118.2 	"/>
	<polygon points="180.9,86.5 144.9,118.9 144.9,157.3 182.5,124.9 	"/>
	<path d="M74,132.5c-2-3.7,7.2-8.3,8.7-5.2c1.5,3.1,35.5,31.8,35.5,38c0,6.2,0.1,63.9,0.1,63.9H79.6v-44.8c0,0-25.7-35.7-25.7-46.7
		s1.2-53.6,1.5-63.1c0.2-8.6,14.8-8.3,14.8-0.2c0,6.6,0.4,53.6,0.7,57.6c0.3,4,16.3,25,16.3,25l2.2-1.5
		C89.3,155.4,76,136.2,74,132.5"/>
	<path d="M209.2,132.5c2-3.7-7.2-8.3-8.7-5.2c-1.5,3.1-35.5,31.8-35.5,38c0,6.2-0.1,63.9-0.1,63.9h38.7v-44.8
		c0,0,25.7-35.7,25.7-46.7s-1.2-53.6-1.5-63.1c-0.2-8.6-14.8-8.3-14.8-0.2c0,6.6-0.4,53.6-0.7,57.6c-0.3,4-16.3,25-16.3,25l-2.2-1.5
		C193.9,155.4,207.2,136.2,209.2,132.5"/>
</g>
</svg>
`

**Comment by asturur** [comment]
this svg is imported and exported fine.
I m closing the issue if more details arise i ll reopen
