### ISSUE TITLE
Paths not drawn correctly

### ISSUE THREAD

**Issue by dcotoz** [fabricjs/fabric.js#5240]
Hi

First of all, this is a great library, I love it.

I am having a weird issue with paths, when I'm done drawing I save to a JSON file and then on later uses I import what I drew from the JSON file, everything works fine except with paths, specifically with big strokewidths, they seem to be half rendered at the edges, take a look:

While drawing:

![untitled](https://user-images.githubusercontent.com/9681009/45655190-7e3b0480-baa4-11e8-849f-557d8996cec5.png)

After reloading:

![untitled2](https://user-images.githubusercontent.com/9681009/45655224-ad517600-baa4-11e8-8f3b-e9e9ba25d077.png)

Here is how I load the path:

`var obj = new fabric.Path(object.path);
obj.set({
					stroke:object.stroke,
					strokeWidth: object.strokeWidth,
					selectable:false,
					fill: "",
					id:object.id,
					hasRotatingPoint:false,
					perPixelTargetFind:false,
					borderColor: 'darkred',
					cornerColor: 'darkred',
					originX: 'center',
					originY: 'center',
					cornerSize: 6,
					transparentCorners: false
			});`

**Comment by asturur** [comment]
please add a jsfiddle that demonstrate the problem
