### ISSUE TITLE
stopPropagation of events

### ISSUE THREAD

**Issue by durga598** [fabricjs/fabric.js#5241]
## Version
2.3.5

## Test Case
http://jsfiddle.net/Da7SP/3024/

## Steps to reproduce
Add more than one event listener with same event. Then stop propagation of events.
## Expected Behavior
It should stop propagation of events.
## Actual Behavior
Though there is no handler for that now, still it should stop the propagation.(feature)

**Comment by durga598** [comment]
So we need to use a property to break the loop, which won't call the next event?

**Comment by asturur** [comment]
i think you should not try to organize your logic on breaking events. You can try to add a property to options and see if it goes to the next event, but that is not a public api feature, could be break in the future by other changes.
