### ISSUE TITLE
iText requires *double* tap to move caret while editing text

### ISSUE THREAD

**Issue by josephrocca** [fabricjs/fabric.js#5242]
## Version
2.3.6

## Test Case
http://jsbin.com/jahecemuku/2/edit?html,output

## Steps to reproduce
Open the jsbin with Chrome android, click on the text to select the text object. Then click again to place the caret. Now click around a few times - try to move the caret to a different position.

## Expected Behavior
The caret should move with a single tap at a new position.

## Actual Behavior
It only moves if you double-tap (fast). Sometimes it does move with only one tap, but this seems to only occur the first few times you try moving it.

**Comment by asturur** [comment]
I'm sorry i did not have time to look at this at all.
Working on chrome android is uncomfortable and i have no debug experience.
