### ISSUE TITLE
Feature: new event suggested "before added"

### ISSUE THREAD

**Issue by salomonsanz** [fabricjs/fabric.js#5244]
## Version
2.3.5

## Test Case
It will be very helpful to add the "before:object:added", 

There are many cases, that it is necessary to "inject" properties into a object before the object it's added to the canvas. Why not directly when loading the object? Well, for example, if you create a API layer, for example to add a mandatory filter each time that the object is added to the canvas.

Ok you can apply the filter after using "object:added" but in this case it is about performance, using "before:object:added" you can avoid render 2 times the item, and /or in the case that the image is dynamic (provided by the server) you can avoid load 2 times the image src.

**Comment by salomonsanz** [comment]
Well, it's not for security only. In the case of my company we use fabric in several reusable components, and it would be very useful to decouple this logic between this components. 

For me this event would help to have a cleaner code, for example, i could extend the canvas class, and add this logic in the canvas instead of create a method/helper out of the canvas that it's harder to re-use between components. In this way, all the logic stays in the canvas.

I know i could use the object:added event but this is worst in performance, because forces me to render twice, or even worst, also forces me to setSrc because the image is dynamic and the filter is applied in the server...

I hope i explained myself well, my English is not very fluent :man_facepalming:

**Comment by asturur** [comment]
My question was more about code writing.
To add an object you have to write canvas.add() or a loadFromJson that will add code without you to have chance to intervene.

What are situations in fabric you can find that will make you add objects without using add?

When using add you can simply add some come before on your logic, like addWithFilter.

Can you please make an example with code of what you would obtain that you can't now?

i have nothing against this event but i would like to evaluate before adding things.

You can also open a simple pr for discussion
