### ISSUE TITLE
Operate a scale operation on a multiple selection causes the inner text of a TextBox to be disformed

### ISSUE THREAD

**Issue by florianduros** [fabricjs/fabric.js#5245]
As a first step, thank you for your amazing work on fabric.js ! 

## Version
2.3.5

## Test Case
http://jsfiddle.net/Da7SP/3033/

## Steps to reproduce

1. Select the first textbox and scale the figure to the right 
2. Select the second textbox and scale the figure to the right 
3. Select the two textboxs and scale the figure to the left

## Expected Behavior

The textboxs are back to their initial form and the inner text isn't disformed

## Actual Behavior

- The inner text is disformed.
- Scale on a multiple selection causes the inner text to be disformed.

**Comment by asturur** [comment]
hi @florianduros this behaviour is normal, and we can't change it.

There is a method for each instance, called
```javascript
setOnGroup(key, value) { }
```

this method will be triggered in objects when something is set on their container group.
In this case is scaleX, and you can revert the change probably and increase the width.

**Comment by florianduros** [comment]
Hi @asturur 

Okay, I'll work on it ! Thx for your reply.
