### ISSUE TITLE
ScaleToHeight/Width not working correct with rectangular images after rotating angle 90 degree.

### ISSUE THREAD

**Issue by tusharsamyama** [fabricjs/fabric.js#5246]
## Version
2.3.5

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by tusharsamyama** [comment]
when we rotate the rectangular image nearly 90 degree, scaleToWidth get applied to image's height and vice versa

**Comment by melchiar** [comment]
pretty sure that's by design. Think about it this way... if rotating an image object changed which side was considering the top, how would you handle images with an angle of 45 degrees?

**Comment by tusharsamyama** [comment]
Hi Steve, thank you for reply.
Is there anything which i can use to scaleToDiagonal kind of thing? so we dont need to worry about angle.

**Comment by asturur** [comment]
You can use getBoundingBox of object and a couple of utils fabricjs has that are like calcScaleToFit ( i should look the exact name )

Then you can scale the object of the scaling that gets calculate between your actual bounding box and the rectangle where you want to fit the image
