### ISSUE TITLE
Fabric objects hiding when zooming or dragging the canvas while working with Openseadragon.

### ISSUE THREAD

**Issue by Fatehkhann** [fabricjs/fabric.js#5247]
## Version
2.3.5

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Steps to reproduce
https://plnkr.co/edit/kBqOHVvzvvAgZL9hwgqY?p=preview

**Comment by liajoy** [comment]
seems the problem was due to below code in `resizeCanvas` function
`resizeCanvas: function() {
  // ...
  this._fabricCanvas.setWidth(this._containerWidth);
  this._fabricCanvas.setHeight(this._containerHeight);
}`

Have no idea why set canvas size twice (resize function was called before reseizeCanvas)
see: https://plnkr.co/edit/q7KrucdLS7UTbnL1caXR?p=preview

**Comment by Fatehkhann** [comment]
Thank you so much! It has solved my problem.

**Comment by Kampii** [comment]
@liajoy It does solve the "object hiding" issue, but now there is a new "objects floating" issue. Please see [this video](https://youtu.be/URsxSb9PBpA) where I am comparing the 2.3.6 version with 1.7.1. In the video you can see that in the latest version the circle is sort of floating in drag gestures, but on version 1.7.1. the objects stick with the image. For that reason we never upgraded to 1.7.1. What do you think causes this delay and can it be improved?

**Comment by liajoy** [comment]
@Kampii 
canvas.renderAll should be called immediately after canvas.absolutePan

**Comment by asturur** [comment]
in browser usage i suggest calling requestRenderAll instead of renderAll.

This will sync up with next frame

**Comment by Kampii** [comment]
Oh wow, it works absolutely fabulous now, thank you!!

**Comment by Mamikon95** [comment]
Hello everyone, I have version 3.6.3, I use it together with openseadragon, when dragging or zooming, objects are hidden and then appear after drag or zoom. how to fix?
