### ISSUE TITLE
How to create rounded rectangle? I want to implement an online prototyping tool to generate keyboard layout files.

### ISSUE THREAD

**Issue by qssq** [fabricjs/fabric.js#5249]
I try to create a circle object and set the rounded corners to 0, but it is not the same as expected.

**Comment by qssq** [comment]
The required functions include shape shadow and shadow fillet size.

**Comment by asturur** [comment]
Please have a read at the docs.

We also cannot offer specific support here.

Look at fabricjs.com examples too.
