### ISSUE TITLE
Not able to Clip single object withing group

### ISSUE THREAD

**Issue by vijaygurjar** [fabricjs/fabric.js#5250]
I have one group object which contains 2 elements like shape and text. I want to clip only text box when i have increase its font size then it is going to out of then group. I want to clip this text box. Without group clip working fine but not able to achieve when textbox within group

## Version
2.3.5

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by asturur** [comment]
Even if you could clip it with the current master branch that supports different clipping, the size of the group would grow anyway.

If this is ok, please try the latest branch for example and check examples on how to use clipPath.

If you want the text bounding box to not grow, you have to manually modify the text class to cut away text, is not something that is supported
