### ISSUE TITLE
clipPath in node.js error

### ISSUE THREAD

**Issue by AlexSergey** [fabricjs/fabric.js#5260]
## Version
2.4.0

## Test Case
I try to load SVG with clipPath in node.js. But I have problem in "fabric.parseSVGDocument"
In line of code:
clipPaths[el.id] = fabric.util.toArray(el.getElementsByTagName('*'))
el.id - undefined
I try to replace it to el.getAttribute('id'), and this work fine

**Comment by asturur** [comment]
xldom has a problem with getElementsByTagName i thing. let me verify

Weird that getElementsByTagName works, reading here:
https://github.com/fabricjs/fabric.js/blob/master/src/parser.js#L676

this should be a quick fix.

**Comment by asturur** [comment]
this should be fixed right? would be nice to have a small test that catch regressions.
