### ISSUE TITLE
clipPath toSVG bug

### ISSUE THREAD

**Issue by AlexSergey** [fabricjs/fabric.js#5264]
## Version
2.4.0

## Test Case
I load svg with clip path. In canvas it looks good but after I call toSVG it is disapear.
http://jsfiddle.net/he53rzy6/3/

**Comment by asturur** [comment]
toSVG compatibility is still low. Need to figure out correct transform and positioning.

**Comment by asturur** [comment]
I spent a bit of time over it, i think i need an overhaul of the toSVG export for single object. Transforming and positioning the clipPath is not easy. Is also unclear if the clipPath support a transform attribute on its own

**Comment by asturur** [comment]
The code in the PR now correctly support a wider range of clipPath output in SVG.
All SVG code is basically rewritten, an hefty task.

Absolute clipPath seems to work, is unclear for me if inverted could ever work somehow.

**Comment by AlexSergey** [comment]
This is awesome! Good job! I think, inverted clip path won't be able to work in svg

**Comment by AlexSergey** [comment]
Unfortunately, this is still not working :( I tested it on the same SVG as in the top example and when we call toSVG - it is disappear. 

This SVG has broken too
http://rgho.st/8JgJCXkXV

**Comment by asturur** [comment]
for me the first jsfiddle example, the top opening one work correctly, it loads and exports ok.

**Comment by asturur** [comment]
dino.svg is broken for different reasons, some clipPath is not recognized during import

**Comment by AlexSergey** [comment]
I think, this is our mistake. I need more time for investigation
