### ISSUE TITLE
Keep Active Group Resize in Back when Other Objects are Behind It

### ISSUE THREAD

**Issue by lgrapplications** [fabricjs/fabric.js#5265]
Thank you for allowing Feature Requests.  I am new to fabric js and so far very impressed with the library.

**Feature**: Add "keepRectangleInBackUntilGrouped" attribute  type boolean to rect class.
Behavior: When set to true, allow selection and resizing to remain behind all other objects until it becomes a member of a group.  When set to false retain current behavior.

**Solves Problem**: When creating a sidebar for example where several objects would be put inside a rectangle with the intention of creating a sidebar group, it becomes difficult to set the rectangle's height and width to make a nice looking sidebar because every time you try to resize the rectangle it comes to the front and covers up the objects you want put inside of it.

I hope the screen shots that follow combined with the description above are enough to get the point.

**Screen Shots of Current Process**:
There are 9 screenshots shown in order of the current process.  If this feature is added it would reduce the number steps dramatically.

![fabric_js_rfc_image_1](https://user-images.githubusercontent.com/30484863/45935309-3fabbb00-bf78-11e8-973e-b0efb4e35802.png)

![fabric_js_rfc_image_2](https://user-images.githubusercontent.com/30484863/45935310-45090580-bf78-11e8-8c19-a5b9b5cf6cce.png)

![fabric_js_rfc_image_3](https://user-images.githubusercontent.com/30484863/45935312-4afee680-bf78-11e8-8898-c7f3cfb2a5b2.png)

![fabric_js_rfc_image_4](https://user-images.githubusercontent.com/30484863/45935316-505c3100-bf78-11e8-8a55-420bfa54e73a.png)

![fabric_js_rfc_image_5](https://user-images.githubusercontent.com/30484863/45935319-54884e80-bf78-11e8-97ea-2366c7d59d4d.png)
![fabric_js_rfc_image_6](https://user-images.githubusercontent.com/30484863/45935324-581bd580-bf78-11e8-9f7f-5338e93cb523.png)

![fabric_js_rfc_image_7](https://user-images.githubusercontent.com/30484863/45935328-5e11b680-bf78-11e8-9f75-61bee55ed0f1.png)

![fabric_js_rfc_image_8](https://user-images.githubusercontent.com/30484863/45935330-62d66a80-bf78-11e8-99df-171f8a0d6561.png)

![fabric_js_rfc_image_9](https://user-images.githubusercontent.com/30484863/45935333-679b1e80-bf78-11e8-98f3-aa38765f0301.png)

Thank you very much for reading my request.

**Comment by melchiar** [comment]
If I'm understanding your problem correctly, you can set `preserveObjectStacking: true` on your canvas to prevent the selection of objects from changing the stacking order.

**Comment by asturur** [comment]
I also think this would keep them in the stack order when you multiselect them.

**Comment by asturur** [comment]
Please verify and in case close the issue.

**Comment by lgrapplications** [comment]
Thank you melchiar and asturur so much that worked perfectly!
