### ISSUE TITLE
fabric 2.4.0 - issue using clipPath absolutePositioned with toSVG()

### ISSUE THREAD

**Issue by rikkarv** [fabricjs/fabric.js#5267]
## Version
2.4.0

## Test Case
https://jsfiddle.net/bepj8vLz/1/

## Information about environment
browser (chrome)

## Steps to reproduce
Best to use image with 400x300 size (with bigger images the clipPath doesn't show at all)

## Expected Behavior
Expected that 'toSvg' outputs same result than canvas, which means getting clipPath centered

## Actual Behavior
clipPath goes to a different place (partially outside svg)

##
Hi @asturur great job with clipPath, it will be a major upgrade after getting the inevitable bugs solved.
I believe i found one when using 'absolutePositioned' and the toSVG() method

**Comment by rikkarv** [comment]
https://jsfiddle.net/bepj8vLz/2/

New version of previous fiddle, now with options to change clip path object.
However, now i'm struggling to understand the effect of changing the properties and the relations between this properties

**Comment by rikkarv** [comment]
Returning to title issue, is it possible that svg output ignores "absolutePositioned = true" and sets the clipPath position relative to clipped object instead of canvas?

![test](https://user-images.githubusercontent.com/40458494/46078286-9ccb8a80-c18b-11e8-896e-f2913d0f4825.png)
Path position relative to clipped object instead of canvas?

**Comment by asturur** [comment]
i could not inspect issue yet. For sure i did not write enough code to make
all clipPath situation exportable. So absolute won t work yet.

**Comment by rikkarv** [comment]
Thank you @asturur should i close the issue?

**Comment by rikkarv** [comment]
![test1](https://user-images.githubusercontent.com/40458494/46086833-e5da0980-c1a0-11e8-8c29-7c90a38b982a.png)
![test2](https://user-images.githubusercontent.com/40458494/46086851-ec688100-c1a0-11e8-8dad-5bcc5386a768.png)

**Comment by rikkarv** [comment]
It seems to me that it's going to be difficult because the fix should be done in clipPathObject.toSvg(), and it has different methods toSvg() for each kind of clipPathObject (paths, rectangles, circles, ...).
Related to getSvgTransform and getSvgTransformMatrix

**Comment by rikkarv** [comment]
Is it stupid, or prone to other errors, to change getSvgTransform() to:

       var angle = this.angle,
        skewX = (this.skewX % 360),
        skewY = (this.skewY % 360),
        center = this.getCenterPoint(),

       NUM_FRACTION_DIGITS = fabric.Object.NUM_FRACTION_DIGITS,

        translatePart = 'translate(' +
          toFixed(center.x, NUM_FRACTION_DIGITS) +
          ' ' +
          toFixed(center.y, NUM_FRACTION_DIGITS) +
          ')',

        anglePart = angle !== 0
          ? (' rotate(' + toFixed(angle, NUM_FRACTION_DIGITS) + ')')
          : '',

        scalePart = (this.scaleX === 1 && this.scaleY === 1)
          ? '' :
          (' scale(' +
            toFixed(this.scaleX, NUM_FRACTION_DIGITS) +
            ' ' +
            toFixed(this.scaleY, NUM_FRACTION_DIGITS) +
            ')'),

        skewXPart = skewX !== 0 ? ' skewX(' + toFixed(skewX, NUM_FRACTION_DIGITS) + ')' : '',

        skewYPart = skewY !== 0 ? ' skewY(' + toFixed(skewY, NUM_FRACTION_DIGITS) + ')' : '',

        flipXPart = this.flipX ? ' matrix(-1 0 0 1 0 0) ' : '',

        flipYPart = this.flipY ? ' matrix(1 0 0 -1 0 0)' : '';

      if (this.absolutePositioned) {
        centerX = toFixed(center.x, NUM_FRACTION_DIGITS) - this.canvas.getCenter()['left'];
        centerY = toFixed(center.y, NUM_FRACTION_DIGITS) - this.canvas.getCenter()['top'];
        translatePart = 'translate(' + centerX + ' ' + centerY + ')';
      }

      return [
        translatePart, anglePart, scalePart, flipXPart, flipYPart, skewXPart, skewYPart
      ].join('');

**Comment by rikkarv** [comment]
Forget the last comment, it doesn't work if you move the clipped object (image). 

But to me it seems the right place to solve the issue

**Comment by rikkarv** [comment]
https://stackoverflow.com/questions/16164565/clip-path-and-translate-in-g-tag-svg/16166249#16166249

_"your clip-path is subjected to the same transformations as the g element where you use it. it seems that you have designed the clip path for the target position. if you do so, you have to offset the transformation on the g element with its inverse so the concatenation of both transformation becomes the identity transform"_

So changed:

    getSvgTransform: function() {
        ...
        if (this.absolutePositioned) {
            translatePart = 'translate()';
        }
        return ...
    }

and also changed:

    _createBaseSVGMarkup: function() {
        ...
        if (clipPath) {
            ...
            if (clipPath.absolutePositioned) {
                var clippingObjectCenterPoint = this.getCenterPoint();
                var clippedObjectCenterPoint = clipPath.getCenterPoint();
                var tempString = this.clipPath.toSVG();
                var fix = 'translate(' + (clippedObjectCenterPoint.x - clippingObjectCenterPoint.x) + ' ' + (clippedObjectCenterPoint.y - clippingObjectCenterPoint.y) + ')';
                var finalString = tempString.replace('translate()', fix);
                markup.push('<clipPath id="' + clipPath.clipPathId + '" >\n\t' + finalString + '</clipPath>\n');
            } else {
                markup.push('<clipPath id="' + clipPath.clipPathId + '" >\n\t' + this.clipPath.toSVG() + '</clipPath>\n');
            }
        }
        return markup;
    }

**FULL METHODS WITH CHANGES:**

    getSvgTransform: function() {
      var angle = this.angle,
        skewX = (this.skewX % 360),
        skewY = (this.skewY % 360),
        center = this.getCenterPoint(),
       NUM_FRACTION_DIGITS = fabric.Object.NUM_FRACTION_DIGITS,
        translatePart = 'translate(' +
          toFixed(center.x, NUM_FRACTION_DIGITS) +
          ' ' +
          toFixed(center.y, NUM_FRACTION_DIGITS) +
          ')',
        anglePart = angle !== 0
          ? (' rotate(' + toFixed(angle, NUM_FRACTION_DIGITS) + ')')
          : '',
        scalePart = (this.scaleX === 1 && this.scaleY === 1)
          ? '' :
          (' scale(' +
            toFixed(this.scaleX, NUM_FRACTION_DIGITS) +
            ' ' +
            toFixed(this.scaleY, NUM_FRACTION_DIGITS) +
            ')'),
        skewXPart = skewX !== 0 ? ' skewX(' + toFixed(skewX, NUM_FRACTION_DIGITS) + ')' : '',
        skewYPart = skewY !== 0 ? ' skewY(' + toFixed(skewY, NUM_FRACTION_DIGITS) + ')' : '',
        flipXPart = this.flipX ? ' matrix(-1 0 0 1 0 0) ' : '',
        flipYPart = this.flipY ? ' matrix(1 0 0 -1 0 0)' : '';
      if (this.absolutePositioned) {
        translatePart = 'translate()';
      }
      return [
        translatePart, anglePart, scalePart, flipXPart, flipYPart, skewXPart, skewYPart
      ].join('');
    },


     _createBaseSVGMarkup: function() {
         var markup = [], clipPath = this.clipPath;
         if (this.fill && this.fill.toLive) {
             markup.push(this.fill.toSVG(this, false));
         }
         if (this.stroke && this.stroke.toLive) {
             markup.push(this.stroke.toSVG(this, false));
         }
         if (this.shadow) {
            markup.push(this.shadow.toSVG(this));
         }
         if (clipPath) {
             clipPath.clipPathId = 'CLIPPATH_' + fabric.Object.__uid++;
             if (clipPath.absolutePositioned) {
                 var clippingObjectCenterPoint = this.getCenterPoint();
                 var clippedObjectCenterPoint = clipPath.getCenterPoint();
                 var tempString = this.clipPath.toSVG();
                 var fix = 'translate(' + (clippedObjectCenterPoint.x - clippingObjectCenterPoint.x) + ' ' + (clippedObjectCenterPoint.y - clippingObjectCenterPoint.y) + ')';
                 var finalString = tempString.replace('translate()', fix);
                 markup.push(
                       '<clipPath id="' + clipPath.clipPathId + '" >\n\t',
                       finalString,
                       '</clipPath>\n'
                  );
              } else {
                  markup.push(
                      '<clipPath id="' + clipPath.clipPathId + '" >\n\t',
                      this.clipPath.toSVG(),
                      '</clipPath>\n'
                  );
              }
          }
          return markup;
    }

**Comment by asturur** [comment]
i m trying to rewrite svg export in a way that make sense for clipPaths

**Comment by rikkarv** [comment]
Solved the scaling issue with:

      if (clipPath) {
        clipPath.clipPathId = 'CLIPPATH_' + fabric.Object.__uid++;
        if (clipPath.absolutePositioned) {
          var ClippedObjectmatrix = this.matrixCache;
          var clippingObjectCenterPoint = clipPath.getCenterPoint();
          var fix = 'translate(' + (clippingObjectCenterPoint.x - ClippedObjectmatrix.value[4]) * (1 / ClippedObjectmatrix.value[0]) + ' ' + (clippingObjectCenterPoint.y - ClippedObjectmatrix.value[5]) * (1 / ClippedObjectmatrix.value[3]) + ') scale(' + (1 / ClippedObjectmatrix.value[0]) + ' ' + (1 / ClippedObjectmatrix.value[3]) + ') ';
          var fixed = (this.clipPath.toSVG()).replace('translate()', fix);
          markup.push(
            '<clipPath id="' + clipPath.clipPathId + '" >\n\t',
            fixed,
            '</clipPath>\n'
          );
        } else {
          markup.push(
            '<clipPath id="' + clipPath.clipPathId + '" >\n\t',
            this.clipPath.toSVG(),
            '</clipPath>\n'
          );
        }
      }

**Comment by asturur** [comment]
> > i m trying to rewrite svg export in a way that make sense for clipPaths
> 
> Thank you, if you need help feel free to ask.

Well an help could be give a look at the open PR, i may have broke it again yesterday trying to add more things, the point would be check that SVG export without clipPath still works after the refactor.

The code needed for the clipPath export is not added yet, what i did is wrapping each object in a container so the clipPath is transformed as the object.

**Comment by rikkarv** [comment]
> > > i m trying to rewrite svg export in a way that make sense for clipPaths
> > 
> > 
> > Thank you, if you need help feel free to ask.
> 
> Well an help could be give a look at the open PR, i may have broke it again yesterday trying to add more things, the point would be check that SVG export without clipPath still works after the refactor.
> 
> The code needed for the clipPath export is not added yet, what i did is wrapping each object in a container so the clipPath is transformed as the object.

Sorry, i don't know how to make the kind of tests that you are used to make. 

However i have copied the code in https://raw.githubusercontent.com/fabricjs/fabric.js/tweak-toSVG/dist/fabric.js and i have used it in my work without any issues.

Also i made [fiddle](https://jsfiddle.net/2h6Lycfr/2/) to test a few objects and once again it seems to me that without issues. However it is very slow because i couldn't link to pull request and i have paste it to fiddle.

**Comment by asturur** [comment]
Your changes to the absolute positioned clipPath in svg works because clipPath is now sort of broken in the toSVG ( i figured out yesterday ). Once is fixed probably they won't work anymore :(

**Comment by rikkarv** [comment]
Thank you @asturur i will stay on hold to see your fix and better understand what is going on. I will also be available if you need

**Comment by asturur** [comment]
My new svg export seems to work like the old one, producing slightly smaller svgs, and should make easier to work with clipPaths.
I m having trouble validating my changes.

**Comment by rikkarv** [comment]
What do you mean by "having trouble validating my changes"?

No dia 04/10/2018, às 19:32, Andrea Bogazzi <notifications@github.com<mailto:notifications@github.com>> escreveu:


My new svg export seems to work like the old one, producing slightly smaller svgs, and should make easier to work with clipPaths.
I m having trouble validating my changes.

**Comment by asturur** [comment]
That i changed so many things, i probably broke other. We do not have svg export tests, and i need time to write them.

Visually everything seems fine
