### ISSUE TITLE
Just a note that video and animation do not appear to work anymore on your site...

### ISSUE THREAD

**Issue by deenfoxx** [fabricjs/fabric.js#5268]
http://fabricjs.com/video-element
http://fabricjs.com/animated-sprite

I tried on Chrome, Firefox, IE, and Safari, on both Windows 10, Mac Powerbook Pro, and Andorid phone. Just thought you might like to know.

**Comment by asturur** [comment]
i ll check thanks!

**Comment by asturur** [comment]
fixed
