### ISSUE TITLE
How to modify the height of the object correctly by code?

### ISSUE THREAD

**Issue by qssq** [fabricjs/fabric.js#5269]
I called``` object.height=value```, which led to higher selection, but the solid area did not increase.

Have a usage question?

**Comment by melchiar** [comment]
@qssq, questions like this are covered in the tutorials page where you'll find a whole section on object manipulation http://fabricjs.com/fabric-intro-part-1#objects. For questions not covered there, stackoverflow is a great place to get help (github is for bug reporting & feature requests). Good luck!

**Comment by qssq** [comment]
thank you
