### ISSUE TITLE
fabric 2.4.0 - toDataURL with clipPath makes objects invisible

### ISSUE THREAD

**Issue by maxim-torba** [fabricjs/fabric.js#5271]
## Version
2.4.0

## Test Case
https://jsfiddle.net/maxim_torba/3Lrob45u/24/

## Information about environment
chrome, firefox - Ubuntu, Windows - working
chrome, firefox - macOs - not working

## Steps to reproduce
If clipPath applied to whole canvas - calling toDataURL makes objects invisible, 
if clipPath using for specific object everything is fine.

**Comment by rikkarv** [comment]
I've tried your fiddle and pasted the console output to browser address bar. What i get is the expected output.
Same result using online decoder:
![image](https://user-images.githubusercontent.com/40458494/46018325-852fcb80-c0d1-11e8-897f-17010ad474f3.png)

**Comment by maxim-torba** [comment]
This is what i have: 
<img width="1232" alt="screen shot 2018-09-25 at 4 53 10 pm" src="https://user-images.githubusercontent.com/16847194/46018946-b1ecde80-c0e3-11e8-9fc5-107b90c29f28.png">
just transparent png image

**Comment by rikkarv** [comment]
@maxim-torba when using the online converter you have to remove 'data:image/png;base64,'.

If using browser address bar you include full string with the 'data:,,,' part.

Or you can try your fiddle with the following changes:
https://jsfiddle.net/3Lrob45u/25/

**Comment by rikkarv** [comment]
![image](https://user-images.githubusercontent.com/40458494/46019651-7f87b500-c0d4-11e8-93f1-6f88c55d73eb.png)

**Comment by maxim-torba** [comment]
@rikkarv yes, i've tried to open it from address bar too (like i said it generating just transparent image), this is what i see in updated fiddle:
 <img width="613" alt="screen shot 2018-09-25 at 5 04 05 pm" src="https://user-images.githubusercontent.com/16847194/46019920-cf22ac80-c0e5-11e8-96b0-3ea65d43d65a.png">

I've just try it on Ubuntu and Windows and everything is fine, but on macBook it's not working

**Comment by rikkarv** [comment]
Oh! I'm on windows and perhaps that is why i'm not having problems.
Sorry, i can't debug on macBook.

**Comment by maxim-torba** [comment]
Do you have any ideas how it can be related?

**Comment by rikkarv** [comment]
I have no idea

**Comment by yannickguillemot** [comment]
Same issue here. Noticed on mac.

**Comment by maxim-torba** [comment]
@yannickguillemot It was fixed in 2.4.1
