### ISSUE TITLE
Download Version 2.4.0 link broken on homepage

### ISSUE THREAD

**Issue by melchiar** [fabricjs/fabric.js#5274]
The download link for version 2.4.0 on the fabricjs.com homepage is currently broken.

https://cdnjs.cloudflare.com/ajax/libs/fabric.js/2.4.0/fabric.min.js

**Comment by asturur** [comment]
this should be fixed now.

**Comment by melchiar** [comment]
Thanks @asturur, although the link for the new 2.4.1 build now has the same problem

https://cdnjs.cloudflare.com/ajax/libs/fabric.js/2.4.1/fabric.min.js

**Comment by asturur** [comment]
i m sure i did it yesterday.
