### ISSUE TITLE
fabric.loadSVGFromURL fails to load my SVG

### ISSUE THREAD

**Issue by Rexdelapits** [fabricjs/fabric.js#5277]
Some of my SVG files will not load when using the fabric.loadSVGFromURL() method. 
Here is an example file :

[Dino.zip](https://github.com/fabricjs/fabric.js/files/2430875/Dino.zip)

This is the console output I get:

> TypeError: Cannot create property 'canvas' on string 'url(#SVGID_4_)'
    at i._drawClipPath (fabric.min.js:1)
    at i.drawObject (fabric.min.js:1)
    at i.renderCache (fabric.min.js:1)
    at i._drawClipPath (fabric.min.js:1)
    at i.drawObject (fabric.min.js:1)
    at i.renderCache (fabric.min.js:1)
    at i.render (fabric.min.js:1)
    at i._renderObjects (fabric.min.js:1)
    at i.renderCanvas (fabric.min.js:1)
    at i.renderAll (fabric.min.js:1)

The function works fine with other SVGs eg:

[Unicorn.zip](https://github.com/fabricjs/fabric.js/files/2430877/Unicorn.zip)

So, I'm assuming this is a problem with the SVG parser? Is there any way to make the parser take this SVG or is there a method to re-format the SVGs so they will work?

All the SVGs were created in Adobe Illustrator.

**Comment by asturur** [comment]
use node attribute under clipPath.
I ll verify if is svg spec and then fix it in case

**Comment by Rexdelapits** [comment]
Thanks for looking into it. shame it's not an easy fix, got a load of files failing on the same thing.

**Comment by asturur** [comment]
i would love to fix it, but i do not have enough time to sit down and do it.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/69020866-484e2480-09b6-11ea-98c0-8ba6b087c136.png)

i think that this has been side-fixed parsing nested clipPath.
