### ISSUE TITLE
SVG backgroundImage does not re-render on canvas zoom

### ISSUE THREAD

**Issue by x3r10n** [fabricjs/fabric.js#5280]
## Version
2.4.0

## Information about environment
All browser

## Steps to reproduce
Set an svg as the canvas background image, then use canvas.zoomToPoint to zoom in.

## Expected Behavior
SVG re-render to zoom factor and look sharp. was working with version 2.2.
http://jsfiddle.net/at60ojdc/

## Actual Behavior
SVG does not re-render so it get zoom but look super pixelated.
http://jsfiddle.net/t34La5yk/

**Comment by asturur** [comment]
Ok found.
Images are now cached, that means that if we do not put a reference to the canvas they are on, the zoom won't affect their resolution.
I'll put a fix for it and improve docs.
