### ISSUE TITLE
Custom Font is not getting loaded - Nodejs - LoadFromJSON

### ISSUE THREAD

**Issue by adhip49** [fabricjs/fabric.js#5286]
`var num = Math.random();
var fs = require('fs'),
    fabric = require('fabric').fabric,
    out = fs.createWriteStream(__dirname + '/'+num+'.png');

const canvas = new fabric.StaticCanvas(null, { width: 333, height: 500 });

var rochester = new fabric.nodeCanvas.Font('Rochester', __dirname + '/Rochester-Regular.ttf');
var frente = new fabric.nodeCanvas.Font('FrenteH1-Regular', __dirname + '/FrenteH1-Regular.otf');
var comingsoon = new fabric.nodeCanvas.Font('ComingSoon', __dirname + '/ComingSoon.ttf');

console.log(frente);
canvas.contextContainer.addFont(rochester);
canvas.contextContainer.addFont(frente);
canvas.contextContainer.addFont(comingsoon);

var jsonStr ='{"version":"2.2.2","objects":[{"type":"i-text","version":"2.2.2","originX":"center","originY":"center","left":163.5,"top":466,"width":231.37,"height":28.25,"fill":"#000000","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":0.64,"scaleY":0.64,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"from 7pm onwards...","fontSize":25,"fontWeight":"normal","fontFamily":"ComingSoon","fontStyle":"normal","lineHeight":1.16,"underline":false,"overline":false,"linethrough":false,"textAlign":"center","textBackgroundColor":"","charSpacing":0,"styles":{"0":{"0":{"stroke":null,"strokeWidth":1,"fill":"#000000","fontFamily":"ComingSoon","fontSize":25,"fontWeight":"normal","fontStyle":"normal","underline":false,"overline":false,"linethrough":false,"deltaY":0,"textBackgroundColor":""},"1":{"stroke":null,"strokeWidth":1,"fill":"#000000","fontFamily":"ComingSoon","fontSize":25,"fontWeight":"normal","fontStyle":"normal","underline":false,"overline":false,"linethrough":false,"deltaY":0,"textBackgroundColor":""},"2":{"stroke":null,"strokeWidth":1,"fill":"#000000","fontFamily":"ComingSoon","fontSize":25,"fontWeight":"normal","fontStyle":"normal","underline":false,"overline":false,"linethrough":false,"deltaY":0,"textBackgroundColor":""},"3":{"stroke":null,"strokeWidth":1,"fill":"#000000","fontFamily":"ComingSoon","fontSize":25,"fontWeight":"normal","fontStyle":"normal","underline":false,"overline":false,"linethrough":false,"deltaY":0,"textBackgroundColor":""},"4":{"stroke":null,"strokeWidth":1,"fill":"#000000","fontFamily":"ComingSoon","fontSize":25,"fontWeight":"normal","fontStyle":"normal","underline":false,"overline":false,"linethrough":false,"deltaY":0,"textBackgroundColor":""},"5":{"stroke":null,"strokeWidth":1,"fill":"#000000","fontFamily":"ComingSoon","fontSize":25,"fontWeight":"normal","fontStyle":"normal","underline":false,"overline":false,"linethrough":false,"deltaY":0,"textBackgroundColor":""},"6":{"stroke":null,"strokeWidth":1,"fill":"#000000","fontFamily":"ComingSoon","fontSize":25,"fontWeight":"normal","fontStyle":"normal","underline":false,"overline":false,"linethrough":false,"deltaY":0,"textBackgroundColor":""},"7":{"stroke":null,"strokeWidth":1,"fill":"#000000","fontFamily":"ComingSoon","fontSize":25,"fontWeight":"normal","fontStyle":"normal","underline":false,"overline":false,"linethrough":false,"deltaY":0,"textBackgroundColor":""},"8":{"stroke":null,"strokeWidth":1,"fill":"#000000","fontFamily":"ComingSoon","fontSize":25,"fontWeight":"normal","fontStyle":"normal","underline":false,"overline":false,"linethrough":false,"deltaY":0,"textBackgroundColor":""},"9":{"stroke":null,"strokeWidth":1,"fill":"#000000","fontFamily":"ComingSoon","fontSize":25,"fontWeight":"normal","fontStyle":"normal","underline":false,"overline":false,"linethrough":false,"deltaY":0,"textBackgroundColor":""},"10":{"stroke":null,"strokeWidth":1,"fill":"#000000","fontFamily":"ComingSoon","fontSize":25,"fontWeight":"normal","fontStyle":"normal","underline":false,"overline":false,"linethrough":false,"deltaY":0,"textBackgroundColor":""},"11":{"stroke":null,"strokeWidth":1,"fill":"#000000","fontFamily":"ComingSoon","fontSize":25,"fontWeight":"normal","fontStyle":"normal","underline":false,"overline":false,"linethrough":false,"deltaY":0,"textBackgroundColor":""},"12":{"stroke":null,"strokeWidth":1,"fill":"#000000","fontFamily":"ComingSoon","fontSize":25,"fontWeight":"normal","fontStyle":"normal","underline":false,"overline":false,"linethrough":false,"deltaY":0,"textBackgroundColor":""},"13":{"stroke":null,"strokeWidth":1,"fill":"#000000","fontFamily":"ComingSoon","fontSize":25,"fontWeight":"normal","fontStyle":"normal","underline":false,"overline":false,"linethrough":false,"deltaY":0,"textBackgroundColor":""},"14":{"stroke":null,"strokeWidth":1,"fill":"#000000","fontFamily":"ComingSoon","fontSize":25,"fontWeight":"normal","fontStyle":"normal","underline":false,"overline":false,"linethrough":false,"deltaY":0,"textBackgroundColor":""},"15":{"stroke":null,"strokeWidth":1,"fill":"#000000","fontFamily":"ComingSoon","fontSize":25,"fontWeight":"normal","fontStyle":"normal","underline":false,"overline":false,"linethrough":false,"deltaY":0,"textBackgroundColor":""},"16":{"stroke":null,"strokeWidth":1,"fill":"#000000","fontFamily":"ComingSoon","fontSize":25,"fontWeight":"normal","fontStyle":"normal","underline":false,"overline":false,"linethrough":false,"deltaY":0,"textBackgroundColor":""},"17":{"stroke":null,"strokeWidth":1,"fill":"#000000","fontFamily":"ComingSoon","fontSize":25,"fontWeight":"normal","fontStyle":"normal","underline":false,"overline":false,"linethrough":false,"deltaY":0,"textBackgroundColor":""},"18":{"stroke":null,"strokeWidth":1,"fill":"#000000","fontFamily":"ComingSoon","fontSize":25,"fontWeight":"normal","fontStyle":"normal","underline":false,"overline":false,"linethrough":false,"deltaY":0,"textBackgroundColor":""}}}},{"type":"i-text","version":"2.2.2","originX":"center","originY":"center","left":164.5,"top":415,"width":203.98,"height":28.25,"fill":"#000000","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1.03,"scaleY":1.03,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"on friday Oct 12th","fontSize":25,"fontWeight":"normal","fontFamily":"ComingSoon","fontStyle":"normal","lineHeight":0.9,"underline":false,"overline":false,"linethrough":false,"textAlign":"center","textBackgroundColor":"","charSpacing":0,"styles":{}},{"type":"i-text","version":"2.2.2","originX":"center","originY":"center","left":174.5,"top":100,"width":206.59,"height":28.25,"fill":"#000000","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1.26,"scaleY":1.26,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"BREW SOME FUN","fontSize":25,"fontWeight":"normal","fontFamily":"ComingSoon","fontStyle":"normal","lineHeight":1.16,"underline":false,"overline":false,"linethrough":false,"textAlign":"center","textBackgroundColor":"","charSpacing":0,"styles":{}},{"type":"i-text","version":"2.2.2","originX":"center","originY":"center","left":166.5,"top":45,"width":41.41,"height":28.25,"fill":"#FF0606","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1.47,"scaleY":1.47,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"lets","fontSize":25,"fontWeight":"normal","fontFamily":"ComingSoon","fontStyle":"normal","lineHeight":1.16,"underline":false,"overline":false,"linethrough":false,"textAlign":"center","textBackgroundColor":"","charSpacing":0,"styles":{}}],"backgroundImage":{"type":"image","version":"2.2.2","originX":"left","originY":"top","left":0,"top":0,"width":1080,"height":1920,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":0.31,"scaleY":0.31,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"crossOrigin":"","cropX":0,"cropY":0,"src":"https://s3-ap-south-1.amazonaws.com/expresapp/snapstudio_templates_qa/W3x39ZvQCa3VqiKhAx5K1534832748.jpg","filters":[]}}';

canvas.loadFromJSON(jsonStr, function() {
  canvas.renderAll(); 
  var stream=canvas.createPNGStream();
  stream.on('data', function(chunk) {
    out.write(chunk);
  });
});`

What it originally looks like on the web : 
![screen shot 2018-10-01 at 4 40 01 pm](https://user-images.githubusercontent.com/9017855/46285344-beb47b00-c598-11e8-807d-bdbd2af119f2.GIF)

What it is looking like when i convert it from json in canvas node 

![0 3134102345214991](https://user-images.githubusercontent.com/9017855/46285351-c70cb600-c598-11e8-90c1-4546c28d9bd8.png)

@asturur 

Any idea why this is happening ? 
node - v 10.6.0
npm - 6.1.0

**Comment by espindolaa** [comment]
Do you have the fonts loaded on the web page? I recommend you use import them and use it in some paragraph just to test if they are properly loaded.

**Comment by so-as** [comment]
@adhip49 hi, I have the same problem with you. Did you solve the problem ? waiting for you reply. thank you!

**Comment by asturur** [comment]
This issue and the relevant json should be updated with fabric 3 and the new node canvas.
There is a clear api to load the fonts now:
http://fabricjs.com/fabric-intro-part-4#node
where it says:
`Custom fonts in Fabric on Node`
