### ISSUE TITLE
fabric.Image.fromURL doesn't accept data URI

### ISSUE THREAD

**Issue by raichu** [fabricjs/fabric.js#529]
I was trying to get let a user upload an image to display on the canvas, and I bumped into this problem:
When I tried `fabric.Image.fromURL("data:image/png;base64,iVBORw0KGgo...")` but it doesn't work (a bug?). I was wondering whether a separate function like fromDataURL exists, but nope, according to the docs.

Is there any way of loading data-URI images into a fabric image object?

**Comment by sid2407** [comment]
i am also facing same problem , How you fixed it?

Thanks

**Comment by nickolaso** [comment]
Hey @raichu how bout that solution that made you close this?

**Comment by asturur** [comment]
it should work normally. What problem are you experiencing?

**Comment by nickolaso** [comment]
I ended up getting it.  Was using the wrong var.  Thanks for checking in bud.
