### ISSUE TITLE
Line coordinates change when loading object with loadFromJSON

### ISSUE THREAD

**Issue by christian-vorhemus** [fabricjs/fabric.js#5291]
## Version
2.4.0

## Test Case
https://jsfiddle.net/pmuopyfn/3/

I'm facing the same issue that nikksan has already described here #3289

When you add a line to the canvas and set x1, y1, x2, y2, it works as expected. When you serialize this line in a file and reload it, the x1, y1, x2, y2 coodinates change! You can see this in the console output of the JSFiddle.

My question is: Why is that happening? And if this is intended and not a bug, what's the logic behind it?

**Comment by kostasx** [comment]
Same case fo the latest version. 
@christian-vorhemus Did you manage to solve this issue or find a workaround?

**Comment by malipetek** [comment]
There is a function called `calcLinePoints` changing those values when its being exported to JSON. But I am not sure why it is doing it.

**Comment by asturur** [comment]
i m sorry for never answering this. Is not a bug nor a feature.
Is like this, the line looks the same and behave the same, with different numbers.

I plan to overhaul the line at some point, avoiding rectangular bounding boxes for diagonal lines and integrating it in polylines.
