### ISSUE TITLE
Include something like SVG viewbox in object/object JSON serialization

### ISSUE THREAD

**Issue by jtara** [fabricjs/fabric.js#5293]
## Problem

When serialized to JSON, there is no "viewbox" included. It is impossible to determine the original pixel dimensions of the canvas. So, it is impossible to correctly scale or place the image on a canvas of different pixel dimensions, if desired to replicate the original relationship to canvas.

Note that viewbox IS included in serialized SVGs. This leaves the SDK non-orthogonal in this respect.

##  Solution

Include equivalent of the SVG viewbox in some manner in object/serialized JSON.

## Current proposed (application) workaround

Serialized SVGs DO include a viewbox specification, e.g.

``` svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="369" height="369" viewBox="0 0 369 369" xml:space="preserve">
```

(This particular example is from, e.g. iPhone 5S, where we happen to use full width of device, which is 768px hardware pixels, or 369 CSS pixels.)

So, for now, I plan to either switch to loading from the SVG instead of the serialized JSON, or else extract the viewbox from the saved SVG, and then use that to scale the sketch when loaded from from JSON.

We did save canvas dimensions in database separately, but - unfortunately :( - we saved native hardware pixels rather than CSS pixels, and did not record the device or device characteristics. So, there is no way to know the original CSS pixel units of the canvas.

(We have a good number - 10's of 1,000s - of already-saved sketches on server, and so need to maintain backward compatibility. If the proposed real solution is implemented, we can do a data migration to update the existing serialized JSON sketch representations.

## Context

We have a native-hybrid mobile app that uses fabric.js. A student creates sketches according to a set of spatial orientation assignments using a touchscreen device (iOS/Android/Chromebook), and is graded on correctness using some image processing.

Supported devices (basically all iOS/Android devices with a fairly recent OS) have widely-varying screen sizes and resolutions. We create a square aspect canvas that will fit the device with room for assignment instructions above. Thus, the pixel dimensions of the canvas will vary widely, depending on the device the student used.

We desire to permit students to load synchronize their work across multiple devices. e.g. perhaps they have worked some assignments on an iPad in a lab at school, and then will continue and work some assignments (or modify previous ones) on an Android phone at home. They should be able to see their previous work with correct scaling.

We save a serialized JSON representation (and, as well, SVG) to a server, and download to other devices. To now, we have not implemented specific user login or synchronization of sketches across user devices. Now we are implementing that.

Currently, when the app loads a previous sketch, it loads the serialized JSON representation. This works as expected, so long as done on a device with same screen pixel dimensions (and also provided our app has not changed the size of the canvas from one version to the next!)

For further context, see: https://egrove.education

(I include this also, for the author's interest in seeing one way that fabric.js is being used.)

**Comment by asturur** [comment]
I cannot see the problem in scaling the canvas.

If you have the latest saved pixel size, and you have the current pixel size ( of the current device ) you can always apply a scale to fit.

What would not work?

**Comment by aggrosoft** [comment]
Yeah I had exactly the same issue and just stored this information by myself. This is an issue if you are working with saved configurations between different devices (e.g. responsive fabric canvas)

**Comment by asturur** [comment]
i do not see the issue yet.
Unless you want to replicate the same exact canvas with also white space around it,
The total objects gives you the size of the design and you can see how big it is and zoom the canvas accordingly.

I do not think a rendering library should take care of app sizes, is out of scope.

This is more a feature for an editor-sdk

**Comment by aggrosoft** [comment]
@asturur would +1 this - @jtara just implement this in user space, there is no reason to have this in the core

**Comment by asturur** [comment]
also please be aware that svg export is not meant for import back. Text won t work for example. No patterns.

**Comment by jtara** [comment]
I can probably use SVG export/import for my use case: I have ONLY paths. No text. No patterns.

The "size of the design" is not of any use in our use case. The drawing has to be placed on the canvas at same offset and zoom as original, albeit potentially on a different sized (but same aspect ratio) canvas. This is because students draw on a grid of 12 x 12, and some simple image processing grades the drawings against correct results. The results have to match both shape and dimension. (The grid is not included in drawing objects FWIW - it is an SVG placed behind the canvas.)

>Unless you want to replicate the same exact canvas with also white space around it,

Yes, exactly. As explained above.

The designers of SVG apparently thought there was a use case for this, and thus the viewbox, which is, in fact properly supported by fabric.js on SVG export.

----
OK, so I've not convinced you that this is a valuable bit of information to record and (certainly optionally) act upon.

But, as my use case is not unique, I'd appreciate any guidance on the "right"/"suggested"/"best" way to implement this myself, and might be good to add to documentation.

I've done some experiments, and I can get the viewbox out of the SVGs that I already have, compute a zoom ratio, and use setZoom() and I get (almost) correct results. It will also be necessary to go through and alter *strokeWidth*s in the objects. (Easy, keep in mind I only use paths). Otherwise, a sketch started on one device and student continues on another would have different stroke widths.

Obviously, I can continue to extract viewbox from SVG, but that is silly. I can add two columns to an associated rational database table, but that' equally silly. I'd like the viewbox values (really, all I care about is width/height, min-x, min-y will always be 0, but might as well include) in the serialized objects.

I'm thinking of subclassing to create a custom object. Perhaps named "viewbox", but that might not be smart in case I can eventually, convince developers that this is a good idea. So, I will prefix with some custom prefix. (Is there a suggested convention? So, before rendering, my code can look at the viewbox values and apply *.setZoom()*.

An alternative would be to normalize to some arbitrary dimensions (e.g. 640x640, 1024x1024, etc.), calculate zoom even for new drawing, and assume the arbitrary dimensions when deserializing. 

But in any case, I feel more comfortable with the viewbox dimensions being recorded in the object serialization.

**Comment by asturur** [comment]
What we could do is allow `additionalProperties` to work in the canvas export.
In this case you cold export the aspect ratio of your device viewport and use it next load to fit the design in the next device, you could export the viewport too.

If you would export width/height and import with the normal loadFromJSON you would have the canvas resized automatically and i think this is an unwanted behaviour.

Exporting an official width and height means take the burden of fixing all the weird use cases that will come out of it, and in one person only, this is not possible.
