### ISSUE TITLE
Pinch gesture inconsistent behaviour 

### ISSUE THREAD

**Issue by alexgeofilter** [fabricjs/fabric.js#5294]
## Version
2.4.0

## Test Case
http://fabricjs.com/touch-events
^^ Base case is shown here with the effect of pinch gesture initialization resizing the element according to the distance between the two touch locations. Will update with a custom fiddle if needed to show the effect on a bigger canvas.

## Information about environment
Nodejs or browser?

Browser

Which browsers?

Mobile browsers

## Steps to reproduce

Include gesture support and setup a canvas of size 360x780 or higher.

## Expected Behavior

The element should resize depending on the motion of the pinch gesture only.

## Actual Behavior

Based on the size of the canvas, pinch gesture will resize the element immediately depending on the distance between the two touch positions. If one finger is used to select an element, and the other finger repeatedly taps another part of the canvas, the element will continue to get smaller/bigger with each new touch of the canvas. The effect is not proportional with the size of the canvas. The bigger the canvas is, the more the element will downsize on two touch gesture. On a 1080x2360 canvas, 1-2 pinch gesture intializations will results in the selected element being significantly reduced in size that you cannot select it anymore.

**Comment by Scanerrr** [comment]
Did You manage to resolve it?

**Comment by lpsBetty** [comment]
i tried to create a jsfiddle, but you can't really test the behaviour on mobile in that environment: https://jsfiddle.net/0871dh4c/2/

I uploaded a video to show my problem when trying to make a image smaller or bigger:
![ezgif-4-f28dddd2f96c](https://user-images.githubusercontent.com/244475/69427043-f1867900-0d2e-11ea-9ffe-60bfb7e2af21.gif)

**Comment by asturur** [comment]
Our current pinch to zoom integration is horrible.
The idea would be to switch to hammer.js and have generic handlers.

I'll check if the current pinch implemnetation is improvable, but i won't be able to do it before tuesday.

**Comment by asturur** [comment]
hi @lpsBetty i noticed now your video and that special top right corner with the `X` on the image.
I wanted to inform you that we are about to publish an api that will allow for control customization in that direction.

**Comment by juxhinNM** [comment]
@asturur how comes that [this demo](http://fabricjs.com/touch-events) is ok on mobile?
By the way, I have the same behaviour as @lpsBetty
