### ISSUE TITLE
Wrong bounding object when translate viewport in FabricJS, user can't select object when click on object

### ISSUE THREAD

**Issue by thobn24h** [fabricjs/fabric.js#5295]
## Version
2.4.0

## Test Case
https://jsfiddle.net/thobn24h/qokx1n7w/2/

## Information about environment
Safari on Mac OS X

## Steps to reproduce
1. I have a text display at postion : left: 10, top: 10.<br />
2. Using viewportTransform to move viewPort to new position : translate by X axis 100 & by Y axis 100 <br />
3. The text object is moving to new position <br />

## Expected Behavior
User can selected text Object ( 'hello world' ) by click on the text ( at new position )<br />

## Actual Behavior
At first time, user can't click on text Object. & object bounder still at old position ( left: 10, top: 10 )
![wrong_cursor_position](https://user-images.githubusercontent.com/8949278/46569172-47f1f600-c97b-11e8-8fde-6f9e3764a6ae.png)

**Comment by mariusturcu1** [comment]
You need to call `text.setCoords` after you change the viewport.
https://jsfiddle.net/qokx1n7w/3/
