### ISSUE TITLE
Text rendering web vs node canvas

### ISSUE THREAD

**Issue by antucg** [fabricjs/fabric.js#5296]
Hi I don't think this is a bug, but I want to confirm it. Some fonts aren't rendered the same on the web and node canvas.
For example this is a screenshot of the canvas in my website:

![screenshot 2018-10-05 at 13 07 43](https://user-images.githubusercontent.com/2089578/46652759-f5dbeb00-cb9b-11e8-85c8-f0d4e938d502.png)

In the image black coloured text touches the two vertical lines. Green and purple text are two different text objects. Purple is also touching vertical lines. They are all textbox objects.
When I generate the same image with node canvas this is the result:

![d33311c0-c892-11e8-ae1c-972848442e62 3](https://user-images.githubusercontent.com/2089578/46652852-2f145b00-cb9c-11e8-9682-073b0fc08e38.jpg)

As you can see black and purple texts are not touching the lines anymore. Lines are rendered correctly.
The web version of the image is generated in latest version of Chrome in OSX. Second one is generated by node canvas, running inside docker with a linux image.

My guess is that pango (or whatever library is rendering the text) doesn't behave as the browser. If this is the case, is there anything I can do to prevent this problem?

Thanks.

**Comment by asturur** [comment]
This is a common problem with node-canvas. The ideal would be understand where the difference in measurement come from and apply correction at node-canvas level for the canvas api

**Comment by antucg** [comment]
Should I post this problem in the node canvas project repository?

Thanks for the answer.

**Comment by asturur** [comment]
You should, they are well aware of differencies. Also maybe that the new nodecanvas will bring some improvements in that sense.
