### ISSUE TITLE
setting direction of gradientTransparency?

### ISSUE THREAD

**Issue by kbhailstock** [fabricjs/fabric.js#5298]
Am I blind? I cannot figure out if there is an option to set the direction of  gradientTransparency in the docs or anywhere else - http://fabricjs.com/docs/fabric.Image.filters.GradientTransparency.html

Version
1.5.0+

###Test Case
http://web-emerse.com/test/gradTranspB.html

###Steps to reproduce
//after initializing steps and setting object etc as seen in working code above
```
var filter = new fabric.Image.filters.GradientTransparency({
  threshold: 20,
  });
  img4.filters.push(filter);
  img4.applyFilters(canvas.renderAll.bind(canvas));
  canvas.renderAll();
```
###Expected Behavior
ability to set to go other directions like left to right or right to left?

###Actual Behavior 
automatically goes bottom to top - tried setting direction similarly to how other options work in fabric to no avail

Thanks!

**Comment by asturur** [comment]
Gradient transparency is no more available and i see that old doc is there for some wrong reason.
You can have an easier outcome with the blendimage filter probably, but a tutorial on how obtain the same effect is missing

**Comment by kbhailstock** [comment]
Thanks, Andrea will explore this.

**Comment by hamzawain7** [comment]
Hi, I created the gradient transparency filter using the blendImage filter. Here is the JSFiddle for it:

https://jsfiddle.net/hamzawain7/9v7e5j1n/
