### ISSUE TITLE
Selecting selectable objects behind unselectable objects

### ISSUE THREAD

**Issue by ImDom** [fabricjs/fabric.js#53]
If an object is unselectable, would it be possible to somehow select the first selectable object behind that object? Any functions I've missed in the documentation that already does this?

I made another issue a while ago (https://github.com/kangax/fabric.js/issues/22) that would probably work very well together with  this _(selecting selectable object behind unselectable objects)_.

Thanks!

**Comment by vleandersson** [comment]
Relates to https://github.com/fabricjs/fabric.js/issues/3833 and is answered properly there.

@ImDom
