### ISSUE TITLE
minX and minY no longer returned when creating fabric.Path

### ISSUE THREAD

**Issue by ConnorTCM** [fabricjs/fabric.js#5300]
## Version
2.4.1

## Test Case
(Showing previous behaviour)
http://jsfiddle.net/mrb7gqL8/1/
(Showing new behaviour)
http://jsfiddle.net/xvf4g7d5/

## Steps to reproduce
Create a new fabric.Path.

## Expected Behavior
Previously, minX and minY were properties returned when creating a fabric.Path.

## Actual Behavior
In 2.4.1 these values are not returned. There appears to me no mention of this removal in the migration docs. Whilst minX and minY are equivalent to left and top, it appears as though the values cannot simply be swapped out. For example, the following function (the need for this function is explained here https://stackoverflow.com/questions/51406351/fabricjs-when-moving-a-path-the-path-object-doesnt-update) now does not work.

```
transformedPoint = (target) => {
  const points = [];
  const path = target.path;
  points.push(new fabric.Point(path[0][1], path[0][2]));
  points.push(new fabric.Point(path[1][3], path[1][4]));
  points.push(new fabric.Point(path[1][1], path[1][2]));
  const matrix = target.calcTransformMatrix();
  return points
  .map(p => new fabric.Point(
    p.x - target.minX - (target.width / 2) - (target.strokeWidth / 2),
    p.y - target.minY - (target.height / 2) - (target.strokeWidth / 2)),
  )
  .map(p => fabric.util.transformPoint(p, matrix));
}
```

**Comment by asturur** [comment]
i think minX and minY where probably removed because no more necessary to the path functioning.

MinX and minY are equal top and left at time of path initialization, if originX and originY are 'letf' and 'top'  you can add path.minX = path.left in those conditions at initialization.

Also what you can do is calculate them on your own.
Taken each point of the path, minX is  smaller X of all the points and minY the the smallest Y

**Comment by ConnorTCM** [comment]
I've attempted to calculate the minX and minY on my own. The following code works if drawing a path from the top left to the bottom right, but if drawing in any other direction the path repositions itself (must be due to the origin which is 'left' and 'top').

```
transformedPoint = (target) => {
    const points = [];
    const path = target.path;
    points.push(new fabric.Point(path[0][1], path[0][2]));
    points.push(new fabric.Point(path[1][3], path[1][4]));
    points.push(new fabric.Point(path[1][1], path[1][2]));
    const matrix = target.calcTransformMatrix();
    const xArray = [path[0][1], path[1][3], path[1][1]];
    const yArray = [path[0][2], path[1][4], path[1][2]];
    const minX = Math.min(...xArray);
    const minY = Math.min(...yArray);
    return points
      .map(p => new fabric.Point(
        p.x - minX - (target.width / 2) - (target.strokeWidth / 2),
        p.y - minY - (target.height / 2) - (target.strokeWidth / 2)),
      )
      .map(p => fabric.util.transformPoint(p, matrix));
  }
```

Comparing what minX and minY used to return in Fabric 1.7.19 to the minX and minY I've calculated myself, my calculations always return the same value no matter what direction the path is drawn, whereas the old minX and minY return differently depending on the direction.

**Comment by ConnorTCM** [comment]
I have looked at the 1.7.19 source code to see how it is calculated but I don't see how I can make use of `_parseDimensions()` in the code above as it is a private method.
