### ISSUE TITLE
CloneAsImage clips shadows

### ISSUE THREAD

**Issue by Tsunami2069** [fabricjs/fabric.js#5302]
## Version
2.4.1

## Test Case
http://jsfiddle.net/g4ds1fbm/

## Information about environment
Nodejs or browser? Browser
Which browsers? Chrome (version 69)

## Steps to reproduce
Add a iText to the canvas with a shadow with a sort of large offset. Then clone the Text using the CloneAsImage function.

## Expected Behavior
I expect the shadow to be fully replicated in the clone version.

## Actual Behavior
The shadow is not taken into consideration when sizing the clone and ends up with part of the shadow cut.

**Comment by Tsunami2069** [comment]
I have, for now, found a temporary solution to my problem.

Basically, I remove the shadow b4 the clone is made and, after the clone has been created, I re-apply the same shadow.

However, IMO, this is still an issue that. although not super important, should still be checked out.

**Comment by asturur** [comment]
probably clone as image should have an option to have or not have shadow.

**Comment by Tsunami2069** [comment]
Sounds good... 

But if we choose to have shadow, it should clone the shadow properly, IMO.
