### ISSUE TITLE
Creating dynamically objects with mouse drag after canvas scale causes object wrong position

### ISSUE THREAD

**Issue by virto111** [fabricjs/fabric.js#5303]
## Version
2.3.6

## Test Case
http://jsfiddle.net/virto/pxvsbt3o/30/

## Information about environment
Browser Chrome

## Steps to reproduce
First zoom the canvas after clicking once on "zoomIn" button.
After canvas scaling try to create triangle by mouseDown -> mouseDrag
from the center of the scaled canvas.
The figure is drawn with considerable offset.
If you start creating the object from the top left corner of the canvas the offset is minimal.
But if you start farther from the top left corner the offset incrementally increases.
In our project all objects behave the same way as the example triangle: (line, rectangle, polygon, etc.)
Higher scale index is causing bigger offset.
## Expected Behavior
Before scaling the canvas try to create a triangle. It is drawn from the initial position
on mouse down. That is expected also when the canvas is scaled - the figures should be drawn
from the mouse down and gradually expand their size on mouse move.
## Actual Behavior
The objects are drawn with offset from the mouse down point. The greater the scale, the 
offset is bigger.

Thank you in advance for your contribution!

**Comment by asturur** [comment]
the mouse events give you 2 sets of coordinates, one with zoom and one without. You do not need to calculate them again.

**Comment by virto111** [comment]
@liajoy , @asturur, thank you both. I also managed to calculate correct drawing 
```
    const mousemovePointer = {
      x: e.pointer.x / this.zoom,
      y: e.pointer.y / this.zoom
    };
```
But that is not a "clean" way of doing it.
Thank you again for the quick response.
