### ISSUE TITLE
SVGs don't load in IE 11

### ISSUE THREAD

**Issue by melchiar** [fabricjs/fabric.js#5304]
## Version
2.4.1

## Information about environment
IE 11 (sigh) - No other browsers seem to be affected

## Steps to reproduce
Go to http://fabricjs.com/kitchensink
Try adding an SVG from the "Simple" tab 

_...nothing happens_

## Explanation
Internet Explorer seems to be returning null on `fabric.loadSVGFromURL()`.

**Comment by awehring** [comment]
Can confirm for "Simple" Tab.

At "Load SVG" Tab it works; with IE 11.0.9600.19155, Windows 7, 64 bit (and it worked a few month ago too).
Click "Load SVG" Tab - "Load as Group" or "Load without grouping" - a blue rectangle appears.

**Comment by asturur** [comment]
i probably broke the ie11 created http request. i must be missing a try catch
