### ISSUE TITLE
The background size of the mobile terminal has been magnified 2 times, and it is normal at the PC end. How to control it? Thank you

### ISSUE THREAD

**Issue by mengfei2611** [fabricjs/fabric.js#5305]
## Version
2.4.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Nodejs or browser?
Which browsers?

## Actual Behavior
The background size of the mobile terminal has been magnified 2 times, and it is normal at the PC end. How to control it? Thank you

**Comment by mengfei2611** [comment]
[
![tim 20181013134642](https://user-images.githubusercontent.com/22373868/46901981-bdb40f80-ceef-11e8-8b1a-f09d0045b55d.png)
](url)

**Comment by asturur** [comment]
This is because fabricJS support automatic retina scaling.

you can disable it reading the supported options in the fabricJS docs for static Canvas

fabricjs.com/docs
