### ISSUE TITLE
如何穿透组，直接选中组内的内容进行控制调整的方法，How to penetrate the group and directly select the method of controlling and adjusting the contents of the group,

### ISSUE THREAD

**Issue by mnonmcn** [fabricjs/fabric.js#5306]
抱歉，这个项目中文帮助很少，而我又有英文障碍，我找遍了文档都没有找到如何穿透组，直接选中组内的内容进行控制调整的方法，请告知，多谢了
--------------------
Sorry, this project has very little help in Chinese, and I have English obstacle, I have searched the documents to find how to penetrate the group, directly select the content in the group for control adjustment, please let me know, thank you.

**Comment by asturur** [comment]
Hi, @mnonmcn i m sorry but i speak only english and italian.
Can you try to explain better what are you trying to achieve?

**Comment by mnonmcn** [comment]
I have a canvas, there is a layer group, I want to click on the selected layer in the editorial group for editing, not the group.
What should I do？

**Comment by hookszhang** [comment]
@mnonmcn 我觉得你应该尝试把画布内的对象在合适的位置列出，用户可以在列表中选择要编辑的对象。编组以后就是一个整体了，不能知道用户要编辑的是组内的那个对象。

I think you should try to list the objects in the canvas in the right place, and the user can select the object to edit in the list. Marshalling becomes a whole, and you can't know that the user is editing the object within the group.

**Comment by mnonmcn** [comment]
@hookszhang 我现在就是这样做的，可是感觉不够人性化。希望能完善此功能。
 That's what I'm doing now, but it's not humane enough. Hope to improve this function.
