### ISSUE TITLE
When some fonts are bold, the drawing is repeated

### ISSUE THREAD

**Issue by mnonmcn** [fabricjs/fabric.js#5314]
When some fonts are bold, the drawing is repeated
---------------------------
在某些字体使用加粗的情况下，描边是重复的
![image](https://user-images.githubusercontent.com/39721003/47005591-a6cb2280-d166-11e8-9b17-201c81e16231.png)

![image](https://user-images.githubusercontent.com/39721003/47005539-9024cb80-d166-11e8-8e24-7d5890022b11.png)

**Comment by asturur** [comment]
Hi, please follow the issue template proposals. We are not getting anywhere with screenshots.

This is probably a font file problem and not code related
