### ISSUE TITLE
Drawing Path is Following Mouse Cursor even isDrawingMode is set to False

### ISSUE THREAD

**Issue by Fatehkhann** [fabricjs/fabric.js#5315]
## Version
2.4.0

## Test Case
https://plnkr.co/edit/eEiGyeMbY34mqCyOPozg?p=preview

## Information about the environment
I am running this on Chrome.

## Steps to reproduce
1. Start drawing a line by clicking and holding mouse left button.
2. Release the left Mouse (touch gesture) click to stop sketching
3. Long press the left mouse button to activate the drag mode and after a while release it.
4. Left click and hold the mouse to drag the canvas.
5. Release the left click to stop the image drag.
Here is the video: https://youtu.be/i9gIoA5aiEI
## Expected Behavior
Fabric is adding a sketch from the long press point and the current mouse location. It also adds a point at the end.
## Actual Behavior
After the drag, Fabric is drawing wherever the cursor moves.

**Comment by asturur** [comment]
Hi @Fatehkhann can you reproduce your issue in a fiddle with a fabricjs version from the repo? in the plunker you opened the are like 4 libs. Is this reproducible with fabricJS only? We should not need an image from openseadragon to  make it happen.

**Comment by Fatehkhann** [comment]
I am looking for this behavior on a draggable and zoomable canvas and OSD Viewer is exactly that kind of element. Just a canvas without any overlay could not be dragged and I can't get expected results.

**Comment by asturur** [comment]
I understand. If you think there is a problem in fabricjs, you need to reproduce it in fabricjs. 

You need to pick up plain fabricjs, that does not have embedded zoom and pan.

You probably need to stop the panning behaviour when you are drawing, or some error is stopping fabricjs from deactivating drawing.

**Comment by asturur** [comment]
Also reproducing canvas zoom and pan in fabricjs is easy, is like 20 lines of code. If you are using OSD just for that, is probably an overkill

**Comment by Fatehkhann** [comment]
Well, I'll provide a plain fabricjs plunker in a while.

**Comment by Fatehkhann** [comment]
I have solved this issue by simulating the mouse up event of fabricjs on canvas. Like this: `canvas._onMouseUp(eventProps)`

**Comment by asturur** [comment]
that means that some other lib is swallowing the event and not let it reach fabricJS.
That is why i asked you a fabricJS only fiddle.
I think we can close then. You should probably fix the other library letting the event bubble up
