### ISSUE TITLE
Unselectable objects can be selected with Shift+click

### ISSUE THREAD

**Issue by alidadasb** [fabricjs/fabric.js#5317]
## Version
2.4.0

## Test Case
https://jsfiddle.net/alidadasb/vgats6w4/

## Information about the environment
Nodejs or browser? **Browser**
Which browsers?  **Chrome**

## Steps to reproduce
 // 1- click on blue circle
 // 2- hold shift
 // 3- click on red circle while holding the shift
 // 4- click on the center of rect (somewhere on the green rect)
 // 5- release the shift
 // 6- you can move the none selectable rect.

## Expected Behavior
Unselectable won't be selected

## Actual Behavior
Unselectable will be selected in multiselection with shift

Apparently back in old days, this issue has been resolved [2460](https://github.com/fabricjs/fabric.js/issues/2460), however, since activeSelection implementation it has been broken again.  The `_shouldGroup` checks the activeSelection object for the selectable flag, not the actual target.

**Comment by alidadasb** [comment]
Also, the `onSelect` and `onDeselect` on objects do not work in multi-select. Unless I'm mistaken, the expectation is to be able to override these methods to intercept the selection.

**Comment by asturur** [comment]
i do not think i fixed and verified also the onSelect and onDeselect
