### ISSUE TITLE
NUM_FRACTION_DIGITS stops working after scaling image

### ISSUE THREAD

**Issue by washamdev** [fabricjs/fabric.js#5320]
## Version
2.4.1

## Test Case
https://jsfiddle.net/johndubya/mwx2hz54/26/

Also see this screen recording, if needed: https://johnmotominer.tinytake.com/sf/MzAxMjYwMV85MDI4NDMx

## Information about environment
Tested in both Chrome 69 (64-bit) and Firefox 59.0.3 (64-bit).

## Steps to reproduce

1. Set `fabric.Object.NUM_FRACTION_DIGITS = 0;`
2. Insert image into canvas.
3. Move image around on canvas and note that `top` and `left` have no decimals.
4. Scale image until scale % is shown as fractional number (e.g. 104.571).
5. Note that `top` and/or `left` now show decimals.

## Expected Behavior
`top` and `left` should not have decimals. Not entirely sure, but I would expect `scaleX` and `scaleY` to not have decimals either.

## Actual Behavior
`top`, `left`, `scaleX`, and `scaleY` have decimals if image is scaled.

**Comment by asturur** [comment]
'NUM_FRACTION_DIGITS ' is just for SVG export and toObject export. Not for real time interactions

**Comment by asturur** [comment]
our `toFixed` is a not fast function that is not suitable for realTime.
I do not remember why is like this and why we cannot have something better.

Apart from that, as a feature is weak. i understand restricting to whole or decimals, but as an extension i could ask to restrict to integer multiple of 5 or 10. ( imagine grids )

I m not sure if it should be implemented in the core lib or not.

We can address documentation, no problem. You can do it too with a PR.

**Comment by awehring** [comment]
I support the idea to restrict dimensions and positions to some integer multiples for a "snap to grid" functionality. Like `canvas.snapAngle`.

I implemented a basic "snap to grid" in my app and it was surprising difficult. Especially to snap the control points  from a rotated or skewed object.

**Comment by asturur** [comment]
i know everyone wants ready and standardized features.

But are never flexible enough and also they do not mix together well, that is why i trying to add less and less but improve what we have.

Unless someone con come up with a very small code change that enable the feature.
