### ISSUE TITLE
Cannot read property 'imageSmoothingEnabled' of null

### ISSUE THREAD

**Issue by vproce** [fabricjs/fabric.js#5326]
Hello,
Currently using fabricjs deployment service, I know that the version of node-canvas after 2.x comes with prebuilt module, I am concerned that this version can not be used in fabricjs v2.4.2, so I manually introduce canvas in the project package.json- Prebuilt 1.6.11, the deployment service is all fine. But when you call the service interface, you get an error:

TypeError: Cannot read property 'imageSmoothingEnabled' of null

nodejs: -v8.9.4
fabricjs : -v2.4.2
canvas-prebuilt:  -v1.16.11
system：Linux

Fabricjs has always been very good in the browser environment, I also use it in many of my projects, but now it is the first time to be deployed as a service, I am not sure how to solve this problem?

**Comment by vproce** [comment]
[#3577](https://github.com/fabricjs/fabric.js/issues/3577)
[#5171](https://github.com/fabricjs/fabric.js/issues/5171)
[#5108](https://github.com/fabricjs/fabric.js/issues/5108)

**Comment by asturur** [comment]
I need to remove any reference to canvas in the evaluation stage

**Comment by asturur** [comment]
Be also aware that each prebuilt version may not run on every architecture. So if is built for node 8.x and 10.x and then you switch to node 11 or to a version for which the module version has been changed, you will need to build on yourself

**Comment by asturur** [comment]
i think you should just be aware that the node-canvas installation requirements are respected:
![image](https://user-images.githubusercontent.com/1194048/47266324-16f5f180-d535-11e8-8b48-854cecea9a2b.png)

**Comment by asturur** [comment]
https://travis-ci.org/fabricjs/fabric.js/jobs/444376253

In this link you can see a fresh container from travis where i install fabric, then remove node-canvas and then install canvas-prebuilt and test run ok.

I skip the apt-get step and i do not install any library

**Comment by asturur** [comment]
i have no idea if at least cairo is a requirement ( the lib and not the dev package ).
Something on travis trusty builds is preinstalled, but should be the same you  find in other linux distros.

**Comment by ludbek** [comment]
@vproce try `yarn install --ignore-optional`

This will make yarn not install optional dependencies in `fabric.js` (canvas, jsdom, xmldom).
Make sure to install `jsdom and xmldom` afterwards.
