### ISSUE TITLE
Styles in Texbox are misaligned

### ISSUE THREAD

**Issue by gabrielmanara** [fabricjs/fabric.js#5329]
## Version
2.4.2-b

## Information about environment
I'm trying to apply a style to a specific word using fabric on node. But for some reason the style it's misaligned. I tried to render on browser and everything looks good, this is only happening on node.
I tried in another's versions and this problem is happening too.

## Expected Behavior
![hrhvqow0noulg5s4ee17s48td0zfoyij](https://user-images.githubusercontent.com/5527758/47310295-0618af00-d60d-11e8-8ac5-db4144319aef.png)
![zg8tdji1c5f49xl035vbkwuukmkasyq1](https://user-images.githubusercontent.com/5527758/47310318-1892e880-d60d-11e8-93e6-e26f76685736.png)

## Actual Behavior
![hrhvqow0noulg5s4ee17s48td0zfoyij](https://user-images.githubusercontent.com/5527758/47310164-b508bb00-d60c-11e8-8967-0543de14b772.png)
![zg8tdji1c5f49xl035vbkwuukmkasyq1](https://user-images.githubusercontent.com/5527758/47310179-b934d880-d60c-11e8-862a-41f8f48968ef.png)

**Comment by asturur** [comment]
can you share the code?

**Comment by gabrielmanara** [comment]
```const fs = require('fs');
const { fabric } = require('fabric')
const out = fs.createWriteStream(__dirname + '/helloworld.png');

var canvas = new fabric.StaticCanvas(null, {
  width: 1080,
  height: 1350,
  backgroundColor: "#FFF"
});


const font = new fabric.nodeCanvas.Font("Ubuntu", './fonts/Ubuntu.ttf');
const font2 = new fabric.nodeCanvas.Font("Bold", './fonts/Ubuntu-B.ttf');

canvas.contextContainer.addFont(font);
canvas.contextContainer.addFont(font2);

var text = new fabric.Textbox('Lorem ipsum dolor sit amet consectetur, adipisicing elit', {
  left: 150,
  width: 800,
  height: 800,
  top: 50,
  fontSize: 60,
  fontFamily: 'Ubuntu',
  styles: {
    0: {
      52: {
        fontFamily: 'Bold',
        underline: true
      },
      53: {
        fontFamily: 'Bold',
        underline: true
      },
      54: {
        fontFamily: 'Bold',
        underline: true
      },
      55: {
        fontFamily: 'Bold',
        underline: true
      },
    }
  }
});
canvas.add(text);

var stream = canvas.createPNGStream();
stream.on('data', function (chunk) {
  out.write(chunk);
});
canvas.renderAll();
```
# Actual Behavior
![helloworld](https://user-images.githubusercontent.com/5527758/47359322-da480880-d6a2-11e8-80ea-3399eb42941e.png)
