### ISSUE TITLE
No border drawn for a 1x1 rectangle

### ISSUE THREAD

**Issue by jpkoskela** [fabricjs/fabric.js#5331]
## Version
2.4.2

## Test Case
http://jsfiddle.net/jpkoskela/zLh2d6y7/

## Information about environment
All browsers.

## Steps to reproduce
Add a 1x1 rectangle with 0.1 stroke width to canvas. Zoom in.

## Expected Behavior
Border should be rendered for the 1x1 rectangle.

## Actual Behavior
Rendering of border is optimized away.

## Source of Problem
rect.class.js
````
 _render: function(ctx) {

      // optimize 1x1 case (used in spray brush)
      if (this.width === 1 && this.height === 1) {
        ctx.fillRect(-0.5, -0.5, 1, 1);
        return;
      }
```

**Comment by asturur** [comment]
you are right. This optimization was for the spray brush. i think since we have caching we should remove it.
Do you want to do it with a PR?
