### ISSUE TITLE
Weird interaction between image and resize filters

### ISSUE THREAD

**Issue by melchiar** [fabricjs/fabric.js#5332]
## Version
2.4.1

## Test Case
https://jsfiddle.net/melchiar/hwrs1bzd/

## Information about environment
Browser
tested on Chrome & Firefox

## Steps to reproduce
1. Apply both an image filter and resizeFilter to an image.
2. Shrink the image using the corner controls
3. Serialize, then load the canvas by clicking the 'To JSON', then 'Load JSON' buttons

## Expected Behavior
The image should resize as expected while keeping the image filter. The stringified canvas should also load exactly as it appeared before being serialized.

## Actual Behavior
Shrinking the image beyond a certain point causes the image filter to disappear. When the canvas is serialized and then loaded while in this state, the loaded canvas makes the image filter work again, but the image becomes cropped. If you resize the image again, the cropping disappears, but so does the image filter.

**Comment by asturur** [comment]
Thanks for the bug report. i ll look at it.

**Comment by melchiar** [comment]
Thanks @asturur. Just a note that the cropping issue doesn't seem to be present on HiDPI displays so I expect it's related to retina scaling. The image filter issue is present on all devices I've tested.

**Comment by asturur** [comment]
https://jsfiddle.net/hwrs1bzd/43/

While the Load from JSON looks like a bug, the filter interaction was fixed recently. Can you check if you can make the filter disappear on the fiddle based on 2.4.1?

**Comment by asturur** [comment]
the fiddle is 2.3.4 based while 2.3.5 changelog:
![image](https://user-images.githubusercontent.com/1194048/47603488-b828f000-d9ec-11e8-9d56-1d38052cd38e.png)

**Comment by melchiar** [comment]
Thanks @asturur, you're right the disappearing filter issue is fixed in later releases (I used an older fiddle as a starting point so I must have missed updating to the latest release). The fiddle was only intended to isolate the load from JSON issue which I came across in my project running 2.4.1.

**Comment by asturur** [comment]
Load from JSON is now solved too.

**Comment by melchiar** [comment]
Yeah, I saw the PR, thanks for the quick fix. I've been putting off using resizefilters in my project so I'm hoping this week I'll be able to make use of this excellent feature (some images definitely suffer without it)
