### ISSUE TITLE
controlVisibility information is not stored in JSON

### ISSUE THREAD

**Issue by semiadam** [fabricjs/fabric.js#5333]
## Test Case
http://jsfiddle.net/Da7SP/3122/

When I use setControlVisibility() to hide some of the controls, the corresponding data will not go to the JSON, so the next time I load the JSON, all the controls appear again. IS this a bug? Or such information is not supposed to be in JSON by design?

**Comment by melchiar** [comment]
See this tutorial on adding additional properties to the outputed JSON. 

https://github.com/fabricjs/fabric.js/wiki/adding-additional-object-properties-to-serialized-json

**Comment by semiadam** [comment]
Thanks for your reply. Does this mean I need to extend standard fabric objects and create my own classes that support these attributes? Or it means that I can manipulate the standard object at initiation time overwrite stateProperties and toObject?

**Comment by melchiar** [comment]
That doc should actually be improved now that I look at it. The `toJSON` method accepts an array of additional properties you'd like to include in the serialized string. 

(eg. `canvas.toJSON(["_controlsVisibility"]`)

http://jsfiddle.net/melchiar/725wbrpk/

**Comment by asturur** [comment]
i ll see if a clear example is available.
If you have the same set of controls for each type of objects ( all paths same controls, all text same controls... ) i suggest that exporting  the controlVisibility is not the right choice.
If you have a per object different control logic, that may be the case.

overriding the getControlVisibility function is easier.

controls are likely part of the project and not part of the saved data

**Comment by semiadam** [comment]
Thanks, @asturur. Overriding the `getControlVisibility `function sounds to be the right option for me because as you said, the controls are set at the project level. With the override, I can make sure all controls are always right under any circumstances, even for older saved data. Would you mind showing an example of how that function can be overridden so it sets different controls for each object type?

**Comment by asturur** [comment]
you can override one per type.
So if for Image you do not want to see the stretching controls, you can do:

```
fabric.Image.prototype.getControlVisibility = function() {
    return {
      mtr: true,
      ml: false,
      mr: false,
      mb: false,
      mt: false,
      tl: true,
      tr: true,
      bl: true,
      br: true,
    };
}
```

if your object have special state, like for example you do want to show some controls when the object has the property `enableDeform = true`. After setting the property you will call image.setControlVisibility(image.getControlVisibility())

```
fabric.Image.prototype.getControlVisibility = function() {
    return {
      mtr: true,
      ml: this.enableDeform,
      mr: this.enableDeform,
      mb: this.enableDeform,
      mt: this.enableDeform,
      tl: true,
      tr: true,
      bl: true,
      br: true,
    };
}
```
