### ISSUE TITLE
Object not rendered on canvas when clipPath applied and objectCaching is false

### ISSUE THREAD

**Issue by shaktippatel** [fabricjs/fabric.js#5336]
Object not rendered on canvas when clipPath applied and **objectCaching** is **false**. check **Obj2** not rendered 

It will working fine if **objectCaching** is **true**

## Version
2.4.2

## Test Case
https://jsfiddle.net/shaktipatel/8r37dLw1/

**Comment by melchiar** [comment]
see http://fabricjs.com/clippath-part1

> "ClipPath REQUIRES object caching."
