### ISSUE TITLE
Install fail! Error: Run "sh -c node-gyp rebuild" error, exit code 1

### ISSUE THREAD

**Issue by vproce** [fabricjs/fabric.js#5339]
../src/CanvasPattern.cc: In static member function 'static repeat_type_t Pattern::get_repeat_type_for_cairo_pattern(cairo_pattern_t*)':
../src/CanvasPattern.cc:90:69: error: 'cairo_pattern_get_user_data' was not declared in this scope
void *ud = cairo_pattern_get_user_data(pattern, pattern_repeat_key);
^
make: *** [Release/obj.target/canvas/src/CanvasPattern.o] Error 1
make: Leaving directory `/usr/local/lib/node_modules/canvas/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack at emitTwo (events.js:126:13)
gyp ERR! stack at ChildProcess.emit (events.js:214:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp-bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/canvas
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

sudo yum install pkgconfig cairo cairo-devel libjpeg-devel pango pango-devel  giflib-devel -y

npm i canvas@1.6.12  jsdom@9.12.0  fabric@2.4.2-b

Execute npm install canvas error

Not sure if something is missing and not installed?

**Comment by conor-kelleher** [comment]
@vproce Did you ever find a solution to this problem? What made you close the issue?
