### ISSUE TITLE
Keyboard handle incorrectly with suggestion mode

### ISSUE THREAD

**Issue by dhduc** [fabricjs/fabric.js#5342]
Hi there,
I'm using an image editor that use the fabric 1.6.7 for canvas handler, and haven't upgraded to 2.4 version yet. 
Currently, I'm facing a problem in texting mode on the keyboard with suggestion mode, when I inserting a word, then delete the ending character by backspace, the other characters automates inserted to the text box.

I figured out the `compositionupdate` event was fired when I delete the ending characters with data of other characters then insert them to the text box. But I don't know how to fix that.
Any suggestion for me? Thanks.

## Version
Fabric 1.6.7

## Test Case
TUI Image Editor
http://nhnent.github.io/tui.image-editor/latest/tutorial-example01-includeUi.html

## Information about environment
Safari on iOS 11.4
Chrome 69 on Android 6.0

**Comment by asturur** [comment]
Text has improved in 2.0 and 2.0+ is the only one using the composition update event. If you want to use it, you need to update.
