### ISSUE TITLE
requestRenderAll seems not working properly

### ISSUE THREAD

**Issue by solomax** [fabricjs/fabric.js#5343]
I have created video player with ability to play/pause/seek
everything seems to work as expected except for "pause" and "seek while on pause"

Attached Fiddle illustrates this behavior for "seek on pause"

user can seek clicking progress bar, but the picture is not being updated while mouse is over video player
Picture is only being updated if mouse pointer is removed from "video area"

The issue is not reproducible while video is being played, due to requestAnimFrame do its job

Maybe there is better way to update video area than canvas.requestRenderAll()?

original issue against our project is here: https://issues.apache.org/jira/browse/OPENMEETINGS-1945

## Version
2.4.1, 2.4.2

## Test Case
https://jsfiddle.net/solomax666/yhsgcvL8/

## Information about environment
Tested under Ubuntu 16/18, Chrome/FF latest

## Steps to reproduce

1. Open Fiddle
2. click on progress bar to change video position

## Expected Behavior
Both progress and video frame should be updated

## Actual Behavior
Progress is updated with new position, new video frame is not being displayed

**Comment by asturur** [comment]
So to me the video frame changes, not always.
Are you sure the seek is working properly?
Can we reduce the test case a bit to focus on what you think the problem is? in this way is hard to understand

**Comment by asturur** [comment]
Oh i think i can understand but i m not sure. Are you sure the seek is istantenous and not some kind of async process that requires a callback to understand when is done?
RequestRenderAll render at next frame, ( 1/60 of sec ) but maybe the video is still seeking and so does not have a valid picture to display, and that could be why you see it white.

**Comment by asturur** [comment]
i moved the discussion in your JIRA board, definitely an application issue and not a fabricjs one.
