### ISSUE TITLE
Incorrect pointer behaviour after dragging something into canvas from outside of it.

### ISSUE THREAD

**Issue by NazarKryvyy** [fabricjs/fabric.js#5354]
### **Version**
Version: 2.3.3

### **Test Case**
http://fabricjs.com/freedrawing

### **Information about environment**
Chrome Version 69.0.3497.100

### **Steps to reproduce**
freedrawing mode, select for example mode Pencil(it can be reproduce with any mode), then move pointer outside of canvas, press and hold mouse button, then move pointer inside canvas and  
then let it go, as if you try to drag something into canvas, then try to draw something.

### **Expected Behavior**
after actions i mentioned in Steps to reproduce, it should to draw a line after I have pressed, hold and move a mouse inside a canvas, after I release a button the line should  have been saved on canvas.

### **Actual Behavior**
after actions i mentioned in Steps to reproduce, I press and hold  mouse button inside of canvas, the line start to be drawn then I move a mouse, the line doesn't continue to be drawn, after  I release mouse button  the line continue to be drawing as if the mouse button was pressed and hold, then I click mouse button for second time and the line disapears

Can anybody help to handle this situation?

**Comment by NazarKryvyy** [comment]
![8jcpuqunnr](https://user-images.githubusercontent.com/18085684/47777401-583c8d00-dcfd-11e8-9311-4ec3edbe1557.gif)

**Comment by asturur** [comment]
i cannot replicate. can you replicate 100%? can you see some errors in the console?

**Comment by asturur** [comment]
Virtual machine or real hardware? there is a difference on how standard mouse is installed in VM, as a touch device. That means that to replicate we should try on a touch device.

**Comment by NazarKryvyy** [comment]
I was testing everything on real hardware. Firefox - no problem on windows, ubuntu and ios, safari also working good, there are problems with chrome on ubuntu, and windows, but after updating chrome on windows  to version 70, problem was gone. On ubuntu chrome version still 69, maybe with future updates the problem will disappear. Still there is problem with Opera, they use the same engine with chrome, maybe  opera devs will fix it with future updates.

**Comment by asturur** [comment]
well is still weird that behaves differently.
i m sure is something to do with touch detection. What kind of pointing device do you have on ubuntu hardware?
