### ISSUE TITLE
activeSelection coords not updating while changing the object position.

### ISSUE THREAD

**Issue by AnurajRicky** [fabricjs/fabric.js#5357]
`key('left', function (e) {  
                let activeObject = canvasFabric.getActiveObjects();  
                if(activeObject.length !== 0){
                    e.preventDefault();
                    activeObject.forEach(function (object) {
                        object.left -= 5; 
                        object.setCoords(); 
                        canvasFabric.renderAll();
                    });
                  }               
            });`

_Originally posted by @AnurajRicky in https://github.com/fabricjs/fabric.js/issues/858#issuecomment-432926143_

**Comment by AnurajRicky** [comment]
I found a solution

let activeObject = canvasFabric.getActiveObjects();                
                if (canvasFabric.getActiveObject().type === 'activeSelection') {
                    let groped =  canvasFabric.getActiveObject().toGroup();
                    groped.left -= 5;
                    canvasFabric.renderAll();
                    canvasFabric.getActiveObject().toActiveSelection();
                    canvasFabric.requestRenderAll();
                } else {
                    activeObject.forEach((object) => {
                            object.left -= 5;
                            canvasFabric.renderAll();
                    })           
                }

**Comment by asturur** [comment]
```
let activeObject = canvasFabric.getActiveObject();
activeObject.left -= 5;
activeObject.setCoords();
canvasFabric.renderAll();
```

Does not work always in any condition?
