### ISSUE TITLE
FabricJS canvas objects group is being hidden when adding its clone to another canvas

### ISSUE THREAD

**Issue by kabrice** [fabricjs/fabric.js#5366]
I try to export a group of objects from a canvas to svg. To do so, I clone the group in another canvas (which will have the same height/width of the group).It works very well. But the problem is the group becomes hidden in the original canvas, I don't know why.

here is the jsfiddles: http://jsfiddle.net/edgarkamdem/8hrsabu4/2/

If you select both the text and the red rectangle at once, and then click on the button "Generate the SVG", and then click on the canvas again, the group will disappear. And I don't know why.

Please how to fix it ?

**Comment by asturur** [comment]
You are not cloning the object, you are using jquery to reference its own properties on another plain javascript object.

Use the clone method, read about it in the docs.
