### ISSUE TITLE
Add support for cmdKey on Mac for selectionKey

### ISSUE THREAD

**Issue by njofce** [fabricjs/fabric.js#5367]
**Is your feature request related to a problem? Please describe.**
The current implementation allows only shiftKey, altKey or ctrlKey for selection of multiple objects.

**Describe the solution you'd like**
It would be useful for Mac apps to add support for cmdKey(command key) as well

Thanks

**Comment by njofce** [comment]
According to Mozilla docs, the cmdKey refers to KeyboardEvent.metaKey. Is there a way to include that as an option, as right now only alt,shift and ctrl are supported?

![image](https://user-images.githubusercontent.com/20361763/47969052-7f36ee00-e072-11e8-9351-4de602187914.png)

**Comment by asturur** [comment]
i think you have just to use the string 'metaKey' on the key property you want to use.

**Comment by njofce** [comment]
Thanks, I had a typo.
