### ISSUE TITLE
Cannot drag small objects

### ISSUE THREAD

**Issue by nickasd** [fabricjs/fabric.js#5369]
## Version
2.4.0

## Test Case
http://fabricjs.com/many-objects

## Information about environment
Safari 12.0

## Steps to reproduce
Select one of the dots in the right canvas and drag it around.

## Expected Behavior
The selected dot should be dragged.

## Actual Behavior
The selected dot is resized. The problem is that apparently for very small objects resizing has a higher priority over dragging.

**Comment by asturur** [comment]
so controls have priority over dragging, and that may make sense because otherwise the inner part of the control, the one inside the bounding box, would never work.

I wonder if we can consider this a bug or a fact, and how we could ever solve the problem.

What would you consider a correct default behaviour, that is not reinventing the wheel, but that you can see also in other applications?

**Comment by asturur** [comment]
if controls does not react before dragging, when clicking the part of controls that is inside the object area you would drag rather than use the control. that was my first sentence.

**Comment by nickasd** [comment]
Hmm ... I tried dragging many of the dots in the example by clicking inside the object area but all got resized instead of being dragged.

**Comment by asturur** [comment]
yes ok there is a bug.
I m sure the wanted behaviour was that from unselected you can only drag to avoid accindental resizing.
When selected resizing is easier than dragging.
When selected for small small object dragging is impossible but that is a problem we are going to keep and that devs should solve with padding maybe.

whitout interaction tests this area is always fragile. I m not sure what framework that run in browsers and node (potentially, not necessary ) can solve this

**Comment by asturur** [comment]
this bug is on 2.4.0 or 2.4.3?

**Comment by nickasd** [comment]
It's 2.4.3. Thanks!

**Comment by asturur** [comment]
ok so i opened a PR tests are broken at least, showing that some test was there.
I need to find time to write tests, and i ll merge it
