### ISSUE TITLE
SVG not being properly rendered

### ISSUE THREAD

**Issue by onassar** [fabricjs/fabric.js#5370]
## Version
Kitchen Sink Version

## Information about environment
Chrome Browser

## Steps to reproduce
Go to fabric's [Kitchen Sink demo page](http://fabricjs.com/kitchensink)
Paste in the following SVG code: https://pastebin.com/B6sRU0Bf

## Expected Behavior
An SVG that resembles this:
https://i.imgur.com/WNbjSQh.png

## Actual Behavior
An SVG that looks like this:
https://i.imgur.com/78lX8O8.jpg

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/48168305-02fd0e80-e2ef-11e8-9458-c989abc65b2a.png)

this is the first time i try some code and it just works :P

**Comment by onassar** [comment]
Here's a screencast of the issue. It's happening for me right now:
https://www.useloom.com/share/2ea67317c0c1497eba4e23634cbccc98

**Comment by asturur** [comment]
i m sorry oliver i poorly explained myself. I fixed it. Is just the first time that i wrote all the code top bottom and i got staright to the solution without passing for a syntax error at least.

You need to wait for 2.4.4 or build from master.

**Comment by onassar** [comment]
Oh okay! Do you have a different version of Kitchen Sink Demo than the one that is live right now?

**Comment by asturur** [comment]
The local one when i develop.
