### ISSUE TITLE
Upgrade to node-canvas 2.0 to optimize deps install and increase tests speed

### ISSUE THREAD

**Issue by iongion** [fabricjs/fabric.js#5371]
The new [node-canvas](https://github.com/Automattic/node-canvas/releases) from the **2.x** series should have binary builds which will seriously decrease the install time of dependencies

**Is your feature request related to a problem? Please describe.**
It takes very long time for automated tests to perform due to dependencies needing installation and compilation

**Describe the solution you'd like**
Specify **node-canvas 2.x** as dependency instead of **1.x**

**Comment by asturur** [comment]
https://github.com/fabricjs/api-discussion/issues/8

bumping to node canvas 2 requires bumping jsdom 9 to 13 and so dump node 4 and 6.
While this may not be an issue it requires to bump fabricjs to 3.0 and i m trying to discuss it there.

**Comment by iongion** [comment]
👍

**Comment by asturur** [comment]
If you have time or will to update that branch and see if you can make it start that would help
