### ISSUE TITLE
Redraw object of type 'activeSelection' when changing inner objects properties

### ISSUE THREAD

**Issue by iongion** [fabricjs/fabric.js#5372]
**Is your feature request related to a problem? Please describe.**
The selection object does not properly adjust its size if inner objects are changed, even if setCoords and renderAll are called.

**Describe the solution you'd like**
The selection object should adapt its size and position in such a way to respect inner objects bounding boxes.

**Describe alternatives you've considered**
I solve it with this kind of code, although it triggers unwanted events from the chain that I need to avoid like `selection:cleared` and `selection:created`, they have side effects in a React app using fabric.
```
  selectObjects(objects) {
    canvas.discardActiveObject();
    const newSelection = new fabric.ActiveSelection(objects, {
      canvas,
    });
    canvas.setActiveObject(newSelection);
    canvas.requestRenderAll();
  }
```

**Additional context**
Here is the fiddle https://jsfiddle.net/S9sLu/3822/
_Select both objects and click the **Align to top** button at the top of the canvas_

It is like this:
![image](https://user-images.githubusercontent.com/867609/48068354-e4095a00-e1d2-11e8-8e61-8647c07ed115.png)

It should be like this:
![image](https://user-images.githubusercontent.com/867609/48068378-f5eafd00-e1d2-11e8-9c49-f5697ad0a5fc.png)

**Comment by asturur** [comment]
I have some code that does this, i have to ask if i can release it as open source.
Or i can suggest something else.
Anyway standard fabric methods could help doing this.
Did you try calling `addWithUpdate()` without nothing else?

**Comment by asturur** [comment]
addWithUpdate seems to solve at least partially,
more problems will come when you want to keep current rotation of active selection or object inside it are rotated and you want to align them in one direction that is not the one of the default originX/originY.

https://jsfiddle.net/S9sLu/3822/

I close the issue for now, since is handled in some way, the conversation is kept open of course.
