### ISSUE TITLE
Ignoring cursorColor in IText

### ISSUE THREAD

**Issue by sintanial** [fabricjs/fabric.js#5373]
As you can see https://github.com/fabricjs/fabric.js/blob/e76df2a04579430a0d8a4407754e0980cc201f88/src/shapes/itext.class.js#L121 this property not used anywhere in code ! :)

**Comment by asturur** [comment]
oh that may be.
Where do we pick up the color to draw the cursor then?

**Comment by asturur** [comment]
So the cursor color is the fill color of the text at that position.
I wonder if we should delete the property or what else

**Comment by awehring** [comment]
I consider the cursorColor quite usefull is some situations. E.g. when you do not have much contrast between the text color and the backgroundColor. The Cursor is narrow and a different Color helps to see it.

The logic of @sintanial makes sense to me (more then the one in te docs: "_Color of default cursor (when not overwritten by character style)_".

**Comment by asturur** [comment]
i m sure i lost that functionality in the 2.0 rewrite.
I just have no idea when one should take precedence over the other.

**Comment by willhalling** [comment]
Hi @sintanial, I have the same use case as you did. I also always need the same `cursorColor` (green in my case). 

I am having difficulties extending the iText class to achieve this. Would you be kind enough to share your solution?

**Comment by asturur** [comment]
this should be probably fixed indeed

**Comment by willhalling** [comment]
thanks @asturur

**Comment by asturur** [comment]
@lcswillems 

the fix should happen here:
https://github.com/fabricjs/fabric.js/blob/master/src/shapes/itext.class.js#L384

cursorColor default value could go to empty string.
That simple line could become a function that would check if the  cursorColor is defined and in case return it, or return that getValuePropertyAt ....

Should be a simple thing to fix and would solve your problem.
