### ISSUE TITLE
Borders enter transparent state immediately on select

### ISSUE THREAD

**Issue by nicktouchette** [fabricjs/fabric.js#5378]
## Version
2.4.1+

## Test Case
http://jsfiddle.net/d8bmvp4s/1/

## Information about environment
Newest version of Chrome w/ Windows 7

## Steps to reproduce
The fiddle automatically sets the object as active in which case the border is completely black.. When clicking off and setting the box as active again with the cursor, the border either highlights back to black or remains in a transparent state.  It's completely random, and if you click off and back onto it several times, it will alternate between states.  This behavior now occurs in all fabricjs examples.

## Expected Behavior
The border should be black when selected, and grey when being altered.
![defaultstate](https://user-images.githubusercontent.com/8799909/48213075-00300700-e34b-11e8-8a24-11ffbcc8e074.jpg)

## Actual Behavior
The border states seem to alternate between the black and grey version on select.  One moment it will select with a black border, and another moment it will be grey.
![reproduction](https://user-images.githubusercontent.com/8799909/48216067-bdbdf880-e351-11e8-9636-985edd4ef098.gif)

**Comment by asturur** [comment]
hard to reproduce. i wonder if if a side effect of a slight move. But anyway does not fire a move event, just tested.

**Comment by nicktouchette** [comment]
> hard to reproduce. i wonder if if a side effect of a slight move. But anyway does not fire a move event, just tested.

I don't know why, but i'm getting it quite consistently.  The sample canvas on the fabricjs.com front page actually always highlights as the transparent border, until you scroll down to the lady bug animation, in which case you'll see the border cycle from transparent to it's correct color.

![frontpage](https://user-images.githubusercontent.com/8799909/48216391-99aee700-e352-11e8-8572-b45408bd797d.gif)

**Comment by asturur** [comment]
i managed to replicate like twice on 50 times tried, but that does not means is not a bug.

**Comment by nicktouchette** [comment]
@asturur It looks like the bug is introduced in version 2.4.1

Everything up to 2.4.0 is working fine.

**Comment by asturur** [comment]
probably that 'avoid extra renders' thing i did. Guys is so hard to have a comprensive testing strategy

**Comment by nicktouchette** [comment]
> probably that 'avoid extra renders' thing i did. Guys is so hard to have a comprensive testing strategy

I would assume that's why the borders fix themselves when an animation plays.

**Comment by asturur** [comment]
a little bit more than 2 years later, a fix.
