### ISSUE TITLE
SVG group does not work 'clipPath = null'

### ISSUE THREAD

**Issue by leesc81** [fabricjs/fabric.js#5381]
## Version
2.4.3

## Test Case
https://jsfiddle.net/SooChangLee/w96n4c7h/

## Information about environment
Safari 12.0.1(Mac)

The image works to release clipping with clipPath = null;
but, SVG does not work with clipPath = null;

**Comment by asturur** [comment]
So when setting the clipPath to different object, you need to also set the object as dirty, or it won't work.
I will add the clipPath to the list of cacheProperties so that you can just use `set('clipPath', object/null)`

Assumed this won't create problems.

**Comment by leesc81** [comment]
Okay.
clpiPAth = null works, when apply object.dirty = true
Thank you very much.

**Comment by asturur** [comment]
i see now clipPath is both in stateProperties and cacheProperties.
