### ISSUE TITLE
Custom fonts in Fabric on Node

### ISSUE THREAD

**Issue by vproce** [fabricjs/fabric.js#5385]
Environment and dependency installation：
CentOS 7
yum install -y pixman cairo-devel libjpeg-turbo-devel libpng-devel pango-devel
cairo-devel @1.14.2
pango-devel @1.36.8

canvas@1.6.12
fabric@2.4.3
jsdom@9.12.0

reference to historical issues:
#5065 
#1924
#3272
#570

browser rendering effect：
<img width="253" alt="20181112171154" src="https://user-images.githubusercontent.com/28007664/48338542-e0794580-e6a0-11e8-82b5-cb5c302ba540.png">

does not install pango on the server side to call createPNGStream generated effect:
<img width="324" alt="20181112161612" src="https://user-images.githubusercontent.com/28007664/48338570-f2f37f00-e6a0-11e8-9f60-9e91b4eb1e6c.png">

server-side installation pango calls createPNGStream generated effect:
<img width="286" alt="20181112171207" src="https://user-images.githubusercontent.com/28007664/48338829-a2c8ec80-e6a1-11e8-9693-95f514aecf78.png">

It is not clear whether this issue has been resolved recently? Still need to wait for the upgrade of canvas2.x to solve?

**Comment by asturur** [comment]
can you share an index.js runnable in node so that we can reproduce?

thanks

**Comment by vproce** [comment]
`var fs = require('fs'),
    path = require('path'),
    fabric = require('fabric').fabric,
    canvas = new fabric.StaticCanvas(null, { width: 750, height: 300 });

const fontsPath = path.join(__dirname, 'fonts');
font = new fabric.nodeCanvas.Font('Arimo', `${fontsPath}/Arimo-Regular.ttf`);
font.addFace(`${fontsPath}/Arimo-Bold.ttf`, 'bold');
font.addFace(`${fontsPath}/Arimo-Italic.ttf`, 'normal', 'italic');
font.addFace(`${fontsPath}/Arimo-BoldItalic.ttf`, 'bold', 'italic');
canvas.contextContainer.addFont(font);

var text1 = new fabric.Textbox('SHOES & BAGS', {
    left: 395,
    top: 96,
    fill: '#fff',
    fontSize: 26,
    fontFamily: 'Arimo',
    width: 215,
    height: 29,
    lineHeight: 1 / 1.16,
    textAlign: 'center'
});
canvas.add(text1);

var text2 = new fabric.Textbox('UP TO↵70% OFF', {
    left: 377,
    top: 140,
    fill: '#fff',
    fontSize: 52,
    fontFamily: 'Arimo',
    width: 251,
    height: 109,
    lineHeight: 1 / 1.16,
    textAlign: 'center'
});
canvas.add(text2);

var out = fs.createWriteStream(__dirname + '/customfont.png');
var stream = canvas.createPNGStream();
stream.on('data', function(chunk) {
    out.write(chunk);
});`

**Comment by vproce** [comment]
I tried to package the font in the docker image to deploy the service and the text was rendered normal. However, italic and bold font rendering has no effect. I think this should be a problem with my code.
<img width="255" alt="20181112224102" src="https://user-images.githubusercontent.com/28007664/48354297-4f1fc880-e6cc-11e8-8623-04a7598a2e2b.png">

**Comment by vproce** [comment]
Today, I tried to install 105 font packages into the system directory, and the front end and server rendering effects are the same. However, the three fonts of Roboto, Raleway, and Oswald light do not render properly on the server side. The wrong font is as follows:
Roboto Light Italic,
Roboto Condensed Italic,
Roboto Condensed,
Roboto Thin Italic,
Roboto Medium Italic,
Roboto Medium,
Roboto Bold Condensed Italic,
Roboto Bold Condensed,
Roboto Black Italic,
Roboto Black,
Roboto thin,

Raleway Thin,
Raleway SemiBold,
Raleway Medium Italic,
Raleway Medium,
Raleway Light,
Raleway ExtraLight,
Raleway ExtraBold,
Raleway Black,
Oswald light,

**Comment by vproce** [comment]
All fonts are rendered correctly

**Comment by so-as** [comment]
@vproce hi, how do you make it?
