### ISSUE TITLE
Text stroke issue (I see construction lines instead the full stroke)

### ISSUE THREAD

**Issue by stileinverso** [fabricjs/fabric.js#5389]
## Version
2.3.3

Hello!
I added a border to a text with these instructions:

    obj.set ({
        'stroke': '#ffcc00',
        'strokeWidth': stroke_w / obj.scaleX,
        'paintFirst': 'stroke',
        'strokeLineJoin': 'round',
        'strokeLineCap': 'round',
    });

Unfortunately the border of some characters of some fonts (as in the example of the attached image in which I used the font Seagram - https://www.dafont.com/seagram-tfb.font) in certain sizes has a strange effect: the edge seems to be formed by its construction lines instead of being full (I hope I explained myself well).
The animation shows how it is not an error that always occours but only with some characters in particular sizes.

Is it something that can be fixed?

Gianpiero

![ezgif-3-d5fb6c8f0841](https://user-images.githubusercontent.com/6285444/48405107-f5ea8000-e731-11e8-93e4-ddcb227defb4.gif)
![fabricjs-stroke-bug](https://user-images.githubusercontent.com/6285444/48405131-06025f80-e732-11e8-9cb1-8ae4589437d1.png)

**Comment by asturur** [comment]
Check if the problem happen on the browser with hardware acceleration disabled and if it happen in firefox too.
On what kind of computer are developing?
(OS / Videocard / browser)

**Comment by stileinverso** [comment]
Thanks for the reply, asturur.
I'm using Chrome (70.0.3538.102) on Windows 10 x64 (videocard: NVIDIA Quadro 2000).

I tested the same thing on Firefox and the problem does not occur (leaving the default settings).
On Chrome I disabled hardware acceleration as you told me and the problem no longer occurs!
Is there a solution by not disabling this hardware acceleration option for Chrome?

Thank you!

**Comment by asturur** [comment]
no.
The solution is making the problem occur with little javascript without fabricJS and open a chrome bug. That they will eventually fix some day.

**Comment by asturur** [comment]
i ll start a fiddle, let's if we can do it.
would be cool if you can log in console and post here a couple of values that make this happen, regarding font size, stroke width and scaling factor of stroke width.

maybe dump all the values of 'setStrokeStyle' function that contains stroke width, stroke color, linejoin, linecap and so on.

**Comment by stileinverso** [comment]
Hello and thank you for the quick answers!
This Chrome bug is a bad news :-(

However, in all the cases listed below you may notice that the text scale increases as the stroke width decreases proportionally.
In fact, in my project the border must appear visually constant regardless of the scale of the text (note that scaleX always has the same value as scaleY).
The starting thickness of the stroke is 6, so to get the strokeWidth you have to do:

    strokeWidth = 6 / scaleX;

**Constant values for all cases:**

    fontFamily: Seagram
    fontSize: 10
    fill: #414042
    stroke: #ffcc00
    strokeLineJoin: round
    strokeLineCap: round

**NO ERROR:**

    scaleX: 19.513774921520042
    scaleY: 19.513774921520042
    strokeWidth: 0.3074751053617577

**ERROR on letters W (uppercase):**

    scaleX: 19.584965394811967
    scaleY: 19.584965394811967
    strokeWidth: 0.30635744710528784

**ERROR on letters M and W (uppercase):**

    scaleX: 20.34522622756635
    scaleY: 20.34522622756635
    strokeWidth: 0.29490947571133036

**ERROR on letters M, P and W (uppercase):**

    scaleX: 22.44498890227322
    scaleY: 22.44498890227322
    strokeWidth: 0.26732024801279014

**NO ERROR again:**

    scaleX: 25.775637018283525
    scaleY: 25.775637018283525
    strokeWidth: 0.23277795213146424

**Comment by stileinverso** [comment]
@asturur 
Yes, of course. You can create a fiddle ;-)

**Comment by asturur** [comment]
can you modify your code a bit just to make a test:

use the 'scaling' event to do not change the stroke width but instead grow in fontsize and reset scale to 1 each time.

Just to see if it makes a difference

**Comment by stileinverso** [comment]
Here a little video when I zoom the canvas
![ezgif-1-12498ffe2e09](https://user-images.githubusercontent.com/6285444/48662211-1f334500-ea7f-11e8-8e51-2ff101493beb.gif)

**Comment by stileinverso** [comment]
Hi!
I did this other test:

1. I created an SVG image using Illustrator using the same font (converting the text to path)
2. I added a text in my project until the "stroke problem" appears (the text is the top object in the attached image)
3. I added to my project the SVG image (SVG is the object at the bottom of the attached image)
4. I have scaled the image as large as the text

The SVG image does not create problems, it seems a problem due to the iText object (on Chrome).

![fabricjs-stroke-problem-01](https://user-images.githubusercontent.com/6285444/48698164-a818c080-ebe6-11e8-8966-32100d19af8c.png)

**Comment by asturur** [comment]
You can see that whoever created that font did a strange job with the stroke.
Look how the corners are done.

I bet the P has normal `construction lines` as we named them.

 I hope i can try to replicate in plain JS code and submit.
Also i wonder if chrome 69 was ok. Do you still have a copy somewhere?

**Comment by stileinverso** [comment]
Thank you for your replies.
Honestly, it's really strange that if you scale the text, the stroke appears and disappears ("construction lines on/off") :-/
I think it can be an approximation error of the coordinates of some characters.
But the even stranger thing is that the text, converted into a SVG image with text transformed into path, instead works perfectly!
I hope you can create a fiddle of this case ASAP.
I don't know if is a fabricjs (on Chrome) or a Chrome bug.

**Comment by stileinverso** [comment]
Can it be useful?
[https://codepen.io/stileinverso/pen/jQaOLd](https://codepen.io/stileinverso/pen/jQaOLd)

**Comment by stileinverso** [comment]
Are there any news about this Chrome bug?
Has the bug report been sent to Google?

**Comment by asturur** [comment]
no, had hard time replicating it.
