### ISSUE TITLE
strokeDashArray inconsistent rendering when starting with 0

### ISSUE THREAD

**Issue by blobinabottle** [fabricjs/fabric.js#5391]
## Version
2.4.0

## Test Case
https://codepen.io/blobinabottle/pen/yQgMbw?editors=0010

## Information about environment
All environnements

## Steps to reproduce
Use an strokeDashArray starting with 0 (it helps to create offset). 

## Expected Behavior
In Canvas it doesn't render a "starting point":
![image](https://user-images.githubusercontent.com/8090162/48411855-24bd2200-e743-11e8-90c1-2270277bca75.png)

## Actual Behavior 
In Fabric it's rendering a first dot (in circle, rect, line, etc). 
![image](https://user-images.githubusercontent.com/8090162/48411872-34d50180-e743-11e8-83a7-06490a4f66a7.png)

**Comment by asturur** [comment]
i m happy to help if i can, but consider that:

- plain canvas and fabric should not be compared for consistency.
- you are comparing an examples with fixed numbers to one with a formula and circles of different radius
- on one side you have a strokedash with 3 numbers and in another 4 numbers (that is a huge diff )


my first gut feeling is that that dot is not a starting point but an ending point for a piece of the circle that was not covered by the third number of your stroke dash.

**Comment by blobinabottle** [comment]
Ok maybe my title is wrong we should not compare to canvas :-) Still we have an issue in fabric in my opinion. Here is a very simple example with lines:
https://codepen.io/vinch/pen/BGWOww
![image](https://user-images.githubusercontent.com/8090162/48491037-f57fe100-e826-11e8-952c-9fab080bef5d.png)
The round linecap is creating a dot when it shouldn't.

**Comment by blobinabottle** [comment]
The fabric rendering seems to be consistent with SVG rendering!

What could be interesting then is to add `lineDashOffset` support in Fabric? We have the same in SVG `stroke-dashoffset` 

Do you know if there is a reason it's not implemented yet? Shoud I try to push a PR for that?

**Comment by asturur** [comment]
i did not even know that was a feature.
Never found it before.

Thanks for the pr.
