### ISSUE TITLE
Line disappearing when first point is panned out of canvas

### ISSUE THREAD

**Issue by gmorubio** [fabricjs/fabric.js#5396]
Hello,
I have been working on some drawing stuff and i found something that i do not know how to solve.

When I draw a line on the canvas, and i use the pan or zoom to get close to the line, if the first point of the line gets out of sight, the whole line disappears, but this does not happen if the point that goes out is the end point. I'm really struggling with it and I cannot find a solution. Can you guys help me out? I'm using fabric version 2.4.3

Thank you so much.

**Comment by asturur** [comment]
may be a bad implementation of the `isOnScreen` method.
Can you please reproduce in a small fiddle so that we can work on it as a bug?

Keep the fiddle small, copy just the line drawing code and your pan and zoom code for the interaction

**Comment by gmorubio** [comment]
Thanks! actually I fixed it by calling setCoords on the object that was being modified with a custom mouse event! Thank you so much this was giving me such a headache.
