### ISSUE TITLE
Fabric.js takes up more memory than canvas

### ISSUE THREAD

**Issue by f987002856** [fabricjs/fabric.js#5400]
In android app webview, draw the same page using canvas and fabric.js respectively。Canvas takes up 50M of memory，but fabric.js takes up 200M of memory.Is this situation normal?Is my way of using fabric.js wrong?

**Comment by asturur** [comment]
fabric.js uses at least 3 canvas, of which 1 is retina enhanced. So maybe is normal.

Use StaticCanvas and enableRetinaScaling set to false and check the differences

**Comment by f987002856** [comment]
Thank you for your answer. According to what you said, change to StaticCanvas and set enableRetinaScaling to false. The memory used is 100M less than before. But it is still much higher than canvas.

**Comment by asturur** [comment]
because there is a cacheCanvas for targeting that is still created. Maybe we can make in a way that is created only if needed.
