### ISSUE TITLE
Lagging issue when dragging images on android phones

### ISSUE THREAD

**Issue by yz3358** [fabricjs/fabric.js#5404]
## Version
2.2.0

## Information about environment
Browser on android phones

## Details
Rendering a canvas with multiple image layers. When dragging the reactive image component, lagging occurred on most android phone (even the latest model of Huawei nova3).  However, on most iPhones, the fps performance is almost ideal. 

I searched for the problem online. Some said the issue will not occur when "enableRetinaScaling" is set to false. I tried and yes the lagging problem is gone on any os. Yet texts on canvas becomes very blur. Is there a way to solve the lagging issue on android phones without hurting the display?

**Comment by leesc81** [comment]
I also have a lag when scaling with finger on Android phone.
I hope this issue is resolved...
