### ISSUE TITLE
FreeDraw adds only dots on mobile + React

### ISSUE THREAD

**Issue by zuuuiko** [fabricjs/fabric.js#5405]
## Version
2.4.3

## Information about environment
We have this bug on mobiles after updating React to version 16.5.2.
Updating Fabric from 1.7.22 to 2.4.3 does not resolve problem.

## Steps to reproduce
Enable mobile mode on Chrome and try to draw.

## Expected Behavior
I expect to draw properly with mobile mode on Chrome (and mobiles)

## Actual Behavior
It only adds dots on Chrome with mobile mode (also Chrome Android, Firefox Android, iOS Safari)

**Comment by asturur** [comment]
fixed with #5406 ( hopefully)
