### ISSUE TITLE
Resize object not working properly

### ISSUE THREAD

**Issue by Sunilthecoder007** [fabricjs/fabric.js#5407]
Hi i am unable to resize object i am using two inputs from where i get new width and height and the use that input value as new height and with for Active Object and object container is resizing but content is not
**Below is my code for resizing** 

   ```
  o = activeCanvas.getActiveObject();
     w = $('#objSetterWidth').val();
     h = $('#objSetterHeight').val();
     o.width  =  w / o.scaleX
     o.height =  h / o.scaleY
     o.setCoords();
     canvas.renderAll();
```

**Comment by asturur** [comment]
Hey please this fit in stackoverflow rather than here.
Please open a question there with a proper interactive snippet that reproduce your use case, and someone will help.
Post the link in this thread after opening the question.
