### ISSUE TITLE
Interactive promotion, which is conducive to productization

### ISSUE THREAD

**Issue by hookszhang** [fabricjs/fabric.js#5409]
Now I am developing a design tool, which has many interactive operations, such as 3D deformation, filter, cropping and so on. Fabricjs provides the basics to get things done, but interaction development is a headache for me.

- How can a user edit only the objects he is selecting without affecting other objects in the canvas?
- Sets a clipping area for a deformed object that cannot exceed the edge of the object?
- Reedit the edited object (save the original object)
- etc.

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Provide some plugins, wikis, demos, and even editing mode features in Fabricjs. I'm not sure which one is better, but I'm sure these interactive enhancements will help developers quickly build their Fabricjs based products

**Additional context**
After discussing which method is better, I think I can provide some PR

**Comment by asturur** [comment]
@hookszhang is unclear to me if you want to provide demos for the community or if you need specific demos about some features.

**Comment by hookszhang** [comment]
@asturur Both. I am looking for some community demos, and I am trying to implement them myself. I will be glad to share them with the community after implementation.

**Comment by jalevin** [comment]
I would also like to contribute to the documentation on the fabricjs website. What is the best way to make that happen?

**Comment by asturur** [comment]
I m trying to make a new clear website, with interactive examples. It will take time since i m doing it slowly with a friend. A very good way to contribut is taking the source code and fill up the jsdocs over functions with examples. ( check setBackgroundImage as an example of how it is done ). Fill up missing jsdocs too and correcting wrong ones
