### ISSUE TITLE
Add support for namespaced events

### ISSUE THREAD

**Issue by WeftDigital** [fabricjs/fabric.js#5413]
jQuery's event system supports namespaced events, as described in this article: https://css-tricks.com/namespaced-events-jquery/. 

This feature is extremely useful when you are trying to remove a single event handler but don't have a reference to that handler function, perhaps because it is anonymous.

**Comment by asturur** [comment]
well this is something that is completely solvable from the outside, keeping references of  handlers. isn't it?
