### ISSUE TITLE
canvas.clipPath creates invalid SVG file

### ISSUE THREAD

**Issue by jessemtcarlton** [fabricjs/fabric.js#5414]
## Version
2.4.4

## Test Case
https://jsfiddle.net/jester1983/Da7SP/3171/

## Information about environment
chrome

## Steps to reproduce
create canvas, apply clipPath to canvas, toSVG the canvas

## Expected Behavior
clipPath path element has one transform attribute

## Actual Behavior
2 transform attributes, strict svg parsers fail

```
<clipPath id="CLIPPATH_1" >
	<path transform="matrix(2 0 0 1 201 150.5) translate(-150, -150)" d="M 100 100 v 100 h 100 V 100 H 100 z" stroke-linecap="round" transform=" translate(-150, -150)" />
</clipPath>
```

circle (and presumably other objects) are correct:
```
<clipPath id="CLIPPATH_3" >
	<circle transform="matrix(1 0 0 1 150.5 100.5)" cx="0" cy="0" r="100" />
</clipPath>
```

**Comment by asturur** [comment]
thanks for the report, i ll fix this.

**Comment by asturur** [comment]
luckily enough that extra transform was a left over from a rewrite to enable clipPath in svg. easy fix with a deletion
