### ISSUE TITLE
Thai text appears garbled on the server

### ISSUE THREAD

**Issue by vproce** [fabricjs/fabric.js#5416]
The server has installed a language pack
locale -a

thai
th_TH
th_TH.tis620
th_TH.utf8

Rendering effect in the browser environment：
<img width="330" alt="20181130143819" src="https://user-images.githubusercontent.com/28007664/49272751-a0da9800-f4ad-11e8-9d6e-bf5c662eb3c4.png">

Server rendering effect：
<img width="466" alt="20181130144006" src="https://user-images.githubusercontent.com/28007664/49272829-e0a17f80-f4ad-11e8-9668-e11bb67bbd3f.png">

**Comment by asturur** [comment]
please add the code that renders this image. Are you loading the font in the canvas?

**Comment by vproce** [comment]
dockerFile Configuration：
RUN sudo yum install -y pixman cairo-devel libjpeg-turbo-devel libpng-devel pango-devel freetype-devel fontconfig-devel
ADD fonts.tgz /usr/share
RUN cd /usr/share/fonts/ && sudo fc-cache -fv

**Comment by vproce** [comment]
The fonts used will be packaged into the system directory.

**Comment by vproce** [comment]
OK. I'll submit a runnable example later. thank you

**Comment by vproce** [comment]
Output text content on the server to ensure that this is not a coding problem
It is now possible to determine that the problem is the underlying rendering of the node canvas
