### ISSUE TITLE
Create objects, select and grouped, ii will visible false

### ISSUE THREAD

**Issue by prabhathAmila** [fabricjs/fabric.js#5419]
Hi,
I create canvas and add 2 text.
but i select all element and add to group it is visible false.
[please refer image](https://groups.google.com/forum/#!topic/fabricjs/iDC38y27Ghc)
```
canvas.getActiveObject().toGroup();
 canvas.dirty = true;
 canvas.renderAll();
```

**Comment by asturur** [comment]
Can you provide a working failing snippet with a specific fabricjs version?
