### ISSUE TITLE
TextBox font size has been limited in 12px

### ISSUE THREAD

**Issue by wethk** [fabricjs/fabric.js#5420]
`var t = new fabric.Textbox('This', {
  left: 20,
  top: 50,
  fill: '#880E4F',
  fontSize: 12,
  strokeWidth: 2,
  stroke: "#D81B60",
});

t.set('fontSize',8);`

text in TextBox can not be set font size below 12

**Comment by rikkarv** [comment]
Did you called the method renderAll() after 't.set('fontSize', 8);'?

**Comment by asturur** [comment]
this has been observed also somewhere else, there is no way to replicate this bug for me.
Unless you can provide a fiddle that is 100% broken, i have to close this issue.
Please try to make a reproducible use case and i ll reopen it.
