### ISSUE TITLE
can't resize in mobile

### ISSUE THREAD

**Issue by sebolio** [fabricjs/fabric.js#5421]
## Version
2.4.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Nodejs or browser?
Which browsers?

## Steps to reproduce
open fabricjs.com on Chrome for iOS

## Expected Behavior
Touching the resizing squares around the picture should resize it, or pinching with 2 fingers too

## Actual Behavior
touching the borders makes them disappear and does nothing else; pinching with 2 fingers does absolutely nothing

**Comment by asturur** [comment]
pinch to zoom is not a default behavior.
I have no ability to debug IOS + CHROME for now, i ll ask in some days if someone can borrow me an iphone.

I agree that touching the corners, for how smally they are, should work

**Comment by sameermanuja** [comment]
If this started with Chrome 70, this is same as issue #5362 in all likelihood.

**Comment by asturur** [comment]
fixed with #5406
