### ISSUE TITLE
Update DOC tint filter

### ISSUE THREAD

**Issue by YaakovHatam** [fabricjs/fabric.js#5423]
I am not familiar with DOCs contributing so i post it here for someone else to do it

Tint filter:
http://fabricjs.com/docs/fabric.Image.filters.Tint.html

now moved and the code example and documentation are not correct.

it moved to a new class `BlendColors` and the right code example to use Tint:
```javascript
var filter = new fabric.Image.filters.BlendColor({
  color: 'red',
  mode: 'tint',
  alpha: 0.5
});
```
Maybe this page should redirect to http://fabricjs.com/docs/fabric.Image.filters.fabric.Image.filter.BlendColor.html

and mention at that page that `mode` parameter can set to `tint`

**Comment by asturur** [comment]
hey thank you for the notice!
The problem is that the script that generates the files does not know how to delete the old files of classes that do not exist anymore.
Those pages are auto generated and i should just delete it.

**Comment by kob-e** [comment]
@asturur thank you very much for your amazing work.
