### ISSUE TITLE
Blend Filter Not apply when call canvas function `loadFromJson`

### ISSUE THREAD

**Issue by contact2mayurkukadiya** [fabricjs/fabric.js#5425]
when I apply `blend` filter on the image and convert canvas into JSON then again I load canvas from that JSON, at that time, my filter not applied.
I am using a fabric version 1.7.22
My filter code is like below :

 canvas.getActiveObject().filters.push(new fabric.Image.filters.BlendColor({
                        color: '#ff0000',
                        mode: 'add',
                        alpha: 0.8
                    }))

canvas.getActiveObject().applyFilters(canvas.renderAll.bind(canvas));
_________________________________________________________________________________
all other filter are work perfect after canvas load from json but only blend filter not work.
Is there any property missing in my filter?
please help Me.

**Comment by asturur** [comment]
Do you think you can provide a fiddle for it?

**Comment by contact2mayurkukadiya** [comment]
[https://jsfiddle.net/Mark_1998/1pc95xef/](url)

**Comment by shkaper** [comment]
@asturur do you accept PRs for v1? If yes, I'll make one for this issue.

**Comment by contact2mayurkukadiya** [comment]
I have one solution for this problem and I applied it.
Solution : 
[https://stackoverflow.com/questions/53700229/blend-filter-not-apply-when-call-canvas-function-loadfromjson/53711334?noredirect=1#comment94288034_53711334](url)
