### ISSUE TITLE
How to get canvas object coordinates relative to window same as mouse position

### ISSUE THREAD

**Issue by smaqeelkazmi** [fabricjs/fabric.js#5430]
I'm trying to control an outside HTML element using canvas Object. I'm just getting help from this one tutorial:
http://fabricjs.com/interaction-with-objects-outside-canvas

but it doesn't looks to work for me at a point when moving the canvas Object

Here is my code:

```

var addIframe = function() {

    var ranStr = 'PQRSTUVWXYZabcdefghijklmno01234';
    var src = 'https://www.youtube.com/watch?v=ZGUEjZckijA';
    $('body').append('<iframe src="https://www.youtube.com/embed/ZGUEjZckijA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"  id="'+ ranStr +'" allowfullscreen></iframe>');

    var iframe = $("#" + ranStr);

    iframe.css({
        'position': 'absolute',
        'z-index' : '0'
    });

    var canvas = window._canvas;
    fabric.Object.prototype.transparentCorners = false;
    fabric.Object.prototype.originX = fabric.Object.prototype.originY = 'center';

    fabric.Canvas.prototype.getAbsoluteCoords = function(object) {
        return {
            left: object.left + this._offset.left,
            top: object.top + this._offset.top,
            width: object.scaleX * object.width,
            height: object.scaleY * object.height
        };
    };



    function positionBtn(obj) {
        var absCoords = canvas.getAbsoluteCoords(obj);

        var iframeWidth = parseFloat(iframe.css('width').replace('px', '')),
            iframeHeight = parseFloat(iframe.css('height').replace('px', ''));

        iframe.css({
            'left': (absCoords.left - iframeWidth / 2) + 'px',
            'top' : (absCoords.top - iframeHeight / 2) + 'px',
            'width': (absCoords.width - 20) + 'px',
            'height' : (absCoords.height - 20) + 'px'
        });
    }

    fabric.Image.fromURL('https://opengameart.org/sites/default/files/Transparency500.png', function(img) {

        canvas.add(img.set({ left: 250, top: 250 }).scale(0.25));

        img.on('moving', function() { positionBtn(img) });
        img.on('scaling', function() { positionBtn(img) });
        positionBtn(img);
    });
}
```

When I starts moving canvas Object the `IFRAME` that is attached to this Object should be on same position the position of canvas Object, but `IFRAME` moves faster then the canvas Object.

There is a problem in getting the actual coordinates of Canvas Object to overlay the IFRAME on the same exact position according to window on Canvas as the Object attached to it is:

Can anybody please help me to solve this issue.

**Comment by inseetu** [comment]
Hello !

I'm trying to use your code but it doesn't work, nothing appears...

https://jsfiddle.net/inseetuvalerian/anhLrbz4/15/

Can you please tell me what goes wrong ?
I really need to overlay an iframe on a canvas object !

Thanks in adavnce for your help !

**Comment by asturur** [comment]
the canvas top and left css placement is something related to normal HTML + CSS and is outside the scope of this repository.

The object position, in pixels can be fount in Object.oCoords, on tl, tr, bl, br properties that represent top left, top right, bottom left  corners...

Those are in current pixels.

**Comment by animeshlm** [comment]
fabric.Canvas.prototype.getAbsoluteCoords = = function(object) {
      return {
        left: object.left + this._offset.left,
        top: object.top + this._offset.top
      };
    }
gives ERROR-  says "Property 'getAbsoluteCoords' does not exist on type 'Canvas' 
I am trying in angular  "fabric": "5.3.0",
https://stackblitz.com/edit/blank-8r5uz5?file=app%2Fartboard%2Fartboard.component.ts
