### ISSUE TITLE
Object Stacking issue after creating a group from the objects on canvas

### ISSUE THREAD

**Issue by vxrai** [fabricjs/fabric.js#5433]
We have few objects layered on the canvas one on top of the other, using the bringForward & canvas.sendBackwards functions. When we try to create a group of these items, the layering order is lost and the items are stacked based on the order they were added on the canvas and not based on the layers we created by bringing items forward and sending backward. How can we maintain the sorting of the layers while we create a group of such items?
@asturur

**Comment by vxrai** [comment]
Hey, @asturur  thanks for your prompt reply! hope you are doing great man!

In order to center align all the items present on the canvas, while maintaining the space between them, 

//We first create a group of all the items present on the canvas

 var myGroup = new fabric.Group();

         var i = canvas.getObjects().length;

                while (i--) { 
                  if(canvas.item(i).isOnScreen()){
                
                  myGroup.addWithUpdate(canvas.item(i)).setCoords();
              
                 }
                } 
                
//After the group is created we clear the canvas off of all the individual items
        canvas.clear();

// and add the group on the canvas
        canvas.add(myGroup);

//center align group on canvas

        myGroup.viewportCenter().setCoords();


//After the group is center aligned, the below code is used to take all items out of the group so that //we can manipulate the items individually

        var edit_items = myGroup._objects;
        myGroup._restoreObjectsState();
        canvas.remove(myGroup);
        for(var i = 0; i < edit_items.length; i++) {
          canvas.add(edit_items[i]);
        }

        canvas.renderAll();

**Comment by asturur** [comment]
If you are doing this on fabric v2, and you loop with i--, you are at least reversing the order of the group.

If you are on fabric v2:
this code:

```
var myGroup = new fabric.Group();
     var i = canvas.getObjects().length;

            while (i--) { 
              if(canvas.item(i).isOnScreen()){
            
              myGroup.addWithUpdate(canvas.item(i)).setCoords();
          
             }
            } 

```

should be fairly equivalent to, without the reversing:

```
var myGroup = new fabric.Group(canvas.getObjects());
```

and this code

```
    var edit_items = myGroup._objects;
    myGroup._restoreObjectsState();
    canvas.remove(myGroup);
    for(var i = 0; i < edit_items.length; i++) {
      canvas.add(edit_items[i]);
    }

    canvas.renderAll();
```

should be equivalent to:

```
myGroup.toActiveSelection();
canvas.discardActiveObject();
canvas.renderAll();
```
(at least the code is more descriptive and you type less)

So i think your code could invert the order of objects, but not ruin it completely in a different way.

Can you replicate it?
What you describe seems easily reproducible in jsfiddle
