### ISSUE TITLE
toDataUrl on Node does not export hex opacity

### ISSUE THREAD

**Issue by toshetoo** [fabricjs/fabric.js#5434]
## Version
2.4.0

## Test Case
http://jsfiddle.net/Da7SP/3204/

## Information about environment
Nodejs or browser? NodeJS

## Steps to reproduce
1. Create canvas
2. Add shape with fill color in hex with opacity
3. Call toDataUrl
## Expected Behavior
Image is exported correctly

## Actual Behavior
The opacity is not included in the color

I've encountered this issue where I have to generate a PDF from the canvas on a NodeJs server. Whenever I have elements with fill color in HEX mode with opacity included, if I call `toDataUrl`, the base64 is not correct and the images are exported without opacity.

The same thing works in the browser and the images are exported correctly. 

Any info about it?

**Comment by asturur** [comment]
Following this article here: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value would seems on spec, since the renderingContext.fillStyle sends to that article.

Is a node-canvas issue anyway not a fabricJS one, i can help somehow

**Comment by asturur** [comment]
First step would be replicate in a plain node.js file, without fabric and after is replicated open an issue here: https://github.com/Automattic/node-canvas

**Comment by awehring** [comment]
The 8 digit hex color notation is a CSS Color Level 4 Working Draft feature:

"_[CSS Color Level 4] adds [...] four- (#RGBA) and eight-digit (#RRGGBBAA) hexadecimal notations [...]_"

Not every browser supports it up to now. Especially Internet Explorer, Edge and some mobile browsers not. Not sure with Node.js.

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value

**Comment by asturur** [comment]
node.js has nothing to do. It depends if node-canvas people are ok with implementing it being a draft and so subject to changes.

**Comment by asturur** [comment]
This feature is implemented in node-canvas 2.0+, while fabric still uses the 1.6 branch.

**Comment by asturur** [comment]
If they can merge this and release 1.6.14 it get fixed
https://github.com/Automattic/node-canvas/pull/1344

**Comment by asturur** [comment]
Pr on node-canvas not accepted. Won't work unless we update to node-canvas 2.
