### ISSUE TITLE
Canvas toSVG ,the svg will break

### ISSUE THREAD

**Issue by xmqywx** [fabricjs/fabric.js#5436]
## Version
2.4.5 bad
2.4.3 and 2.4.4 show well
## Test Case
http://fabricjs.com/kitchensink

## Information about environment
brower
Which browsers?
chrome 70.0.3538.110
## Steps to reproduce
http://fabricjs.com/docs/fabric.Canvas.html#toSVG
canvas toSVG image
## Expected Behavior

![image](https://user-images.githubusercontent.com/3355712/50175135-fc72a580-0336-11e9-889e-e19f1a298eaa.png)
![image](https://user-images.githubusercontent.com/3355712/50175220-2fb53480-0337-11e9-95f6-9dac5c5445a1.png)

**Comment by asturur** [comment]
omg that is terrible. How did it pass the tests?

**Comment by Rexdelapits** [comment]
Yeah, I had similar problems with the move to 2.4.5. Which is a shame because I really need the fix that stops a second transform being added to my clip paths (which did seem to be working great btw - thanks)

**Comment by asturur** [comment]
Because specific transform is added in `COMMON_PARTS` already.
But eventually something went wrong. That was a clipPath bug and i checked just clipPath when i modified it. I have a full test page that is all broken, that i did not look at.
Human error
