### ISSUE TITLE
Image of amazon s3 not load in farbc js canvas in safari, and chrome of macbook

### ISSUE THREAD

**Issue by contact2mayurkukadiya** [fabricjs/fabric.js#5437]
I am using fabric js version 1.7.22. 
my images from cross-origin are loaded in fabric js when I open a page in chrome in windows.
but the same page I open in safari in MacBook, it throws an error of cross-origin like below : 

        `cross-origin image load denied by Cross-Origin Resource Sharing policy`

My cross-origin image is from amazon s3 bucket.
I have also setup Cors configuration in a bucket, like Below :

 `<CORSRule>`
    `<AllowedOrigin>https://example.com</AllowedOrigin>`
    `<AllowedMethod>GET</AllowedMethod>`
    `<AllowedMethod>PUT</AllowedMethod>`
    `<AllowedMethod>POST</AllowedMethod>`
    `<AllowedMethod>DELETE</AllowedMethod>`
    `<AllowedHeader>*</AllowedHeader>`
    `<ExposeHeader>x-amz-server-side-encryption</ExposeHeader>`
    `<ExposeHeader>x-amz-request-id</ExposeHeader>`
    `<ExposeHeader>x-amz-id-2</ExposeHeader>`
` </CORSRule>`
 `<CORSRule>`
    `<AllowedOrigin>*</AllowedOrigin>`
    `<AllowedMethod>GET</AllowedMethod>`
    `<AllowedMethod>PUT</AllowedMethod>`
    `<AllowedMethod>POST</AllowedMethod>`
    `<AllowedMethod>DELETE</AllowedMethod>`
    `<AllowedHeader>*</AllowedHeader>`
    `<ExposeHeader>x-amz-server-side-encryption</ExposeHeader>`
    `<ExposeHeader>x-amz-request-id</ExposeHeader>`
   ` <ExposeHeader>x-amz-id-2</ExposeHeader>`
` </CORSRule>`

I don't know where I make a mistake?

My image loading code for fabric js is like below : 

fabric.Image.fromURL(image_details, (image) => {
            if (image._element == null) {
                alert('failed to load image');
                return;
            }
            image.crossOrigin = "Anonymous";
            image.set({
                left: 10,
                top: 10,
                angle: 0,
                padding: 0,
                cornersize: 10,
                hasRotatingPoint: true
            });
         canvas.add(image)
        }, { crossOrigin: 'Anonymous' '});

Please help me, how to fix this error in safari.

**Comment by asturur** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes

Try follow the right casing for the attribute.
is `anonymous` and not `Anonymous`
