### ISSUE TITLE
[HELP] How could I add attributes like onclick to objects

### ISSUE THREAD

**Issue by nameszian** [fabricjs/fabric.js#5439]
How could I add `attributes` like `onclick` for example to a `rect object` and that when I do `toSVG` (and an `innerHTML` of the result of `toSVG`) the element `<rect>` (inside `<svg>` element) in the HTML has the `onclick` to call some function?

This would be a kind of pseudocode:
```
    const canvas = new fabric.Canvas('canvas_id');
    const rect = new fabric.Rect({
      left: 100,
      top: 100,
      width: 100,
      height: 50,
      fill: 'red',
      onclick: 'alert(1)', <----- [HERE]
    });
    canvas.add(rect);
    rect.center();
    document.querySelector('#output').innerHTML = canvas.toSVG();
```
and then inside the element with `id` `output`, by clicking on the red rectangle (`<rect>` element from `<svg>`), a popup with a `1` would appear.

❓Any ideas?

**Comment by asturur** [comment]
This is not a library feature.
You should start a real stackoverflow snippet up to the point where rehydrate the svg string in the dom, and then ask suggestions on how you can add the onclick handler.

I would probably store my on click handlers in an objects with keys, and then add those keys as ID on  my fabric objects, and then at hydration time bind the handlers.

This if you are not already using the ID for other purposes.
