### ISSUE TITLE
Group is not clickable after set()

### ISSUE THREAD

**Issue by solomax** [fabricjs/fabric.js#5441]
## Version
2.4.1, 2.4.5

## Test Case
https://jsfiddle.net/solomax666/2wgzjLf3/

## Information about environment
Tested using Chrome and FF latest (Ubuntu 16)

## Steps to reproduce

1. Open Fiddle https://jsfiddle.net/solomax666/2wgzjLf3/
2. try to click 'Play' group

## Expected Behavior
Cursor should be changed while mouseover 'Play' group

## Actual Behavior
Cursor is not being changed while mouseover 'Play' group, group is not draggable
Weird enough it is being changed while mouseover it's original position ( approx coordinates [x, y] == [50, 0]
This is only reproducible on first render

Please let me know if you need any additional details

**Comment by asturur** [comment]
if you modify position by code you have to also call `.setCoords()`

**Comment by solomax** [comment]
Thanks a lot!
call to `setCoords` helps :)
