### ISSUE TITLE
How to send image request with cross-origin using setBackgroundImage function of fabric  js (In Safari)

### ISSUE THREAD

**Issue by contact2mayurkukadiya** [fabricjs/fabric.js#5444]
Currently, I am working in one project in which I want to set an image as background 
I am using fabric js version 1.7.22
I am trying to fetch an image from amazon s3 bucket which is already CORs configured.
When I try to set an image  in canvas background at the first time, it is throwing an error like:

        Cross-origin image load denied by Cross-Origin Resource Sharing policy.

But when I try to set the same image again in canvas, it is set successfully because it is load from cache.

So actual problem is that when at first-time request sent by fabric js `setbackgroundImage` function, Origin is not passed in the request. which may cause failed to load an image as background.

Please guide me that how to set cross-origin in a request when setting background Image.

This is working in chrome and firefox but Not is Safari on Mac

**Comment by asturur** [comment]
http://fabricjs.com/docs/fabric.StaticCanvas.html#setBackgroundImage

In the docs there is also an example for crossOrigin
