### ISSUE TITLE
Artwork not centered properly please help

### ISSUE THREAD

**Issue by prabhathAmila** [fabricjs/fabric.js#5445]
Hi

I create editor using fabricjs. the lib. is wonderful
but I have some problem loading json. when I open editor and create artwork in my 1980x768 monitor then save as it json.
after save json, I open my editor 1024x768 monitor. and load json using 'loadFromJSON" function, the artwork is not centerd properly.
please help

[https://groups.google.com/forum/#!topic/fabricjs/mbszpnkg7gM](https://groups.google.com/forum/#!topic/fabricjs/mbszpnkg7gM)

**Comment by finom** [comment]
Try to include origin properties to returned JSON object `toJSON(['originX', 'originY])`.

See http://fabricjs.com/docs/fabric.Canvas.html#toJSON

**Comment by asturur** [comment]
This is ok for stackoverflow.com,

Could you please a question there, with a properly working snippet and link the question here?
