### ISSUE TITLE
discardActiveObject doesn't erase controls rendered with _renderControls

### ISSUE THREAD

**Issue by finom** [fabricjs/fabric.js#5446]
## Version
2.4.6, 2.0.0-rc.4

## Test Case
http://jsfiddle.net/Da7SP/3332/

## Information about environment
Chrome 71

## Steps to reproduce

- Render custom controls for an object with `_renderControls`
- Select the object with either `setActiveObject` or manual selection
- Call `discardActiveObject`

(see last lines of the test case)

## Expected Behavior

Rendered controls should disappear.

## Actual Behavior

They disappear only if `discardActiveObject` is called right after `setActiveObject` but they don't disappear if a little delay is used before `discardActiveObject` call. If canvas is clicked manually outside of the object area, the controls disappear as expected.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/51087242-e6e37680-1750-11e9-8e49-7577ff625709.png)

Unless specified with options, canvas.add(objects) is rendering the canvas on the next video frame ( if thread is free ).

if calling everything right there:

canvas.add
render is scheduled
set active object
discard active object
render happens.

if called with timeout:

canvas.add
render is scheduled
set active object
render happens
discard active object
(no other render happens)
