### ISSUE TITLE
Image is Blurry When I use Group with a Circle

### ISSUE THREAD

**Issue by WisestCoder** [fabricjs/fabric.js#5447]
## Version
2.4.0

## Information about environment
browsers：Chrome(latest version)

## Steps to reproduce
When I follow this codes，the result is expected:
```javascript
const canvas = new fabric.Canvas('haha');
fabric.Image.fromURL('https://img.alicdn.com/tfs/TB1vezqnFzqK1RjSZFvXXcB7VXa-3729-1970.png', function(oImg) {
  oImg.scale(0.5).set('flipX', true);
  canvas.add(oImg);
});
```

But when I follow this codes，the result is not expected，the image will blurry:
```javascript
// diffrence between above code：I add a Group to combine Image and Circle
const canvas = new fabric.Canvas('haha');
const circle = new fabric.Circle({
  radius: 100,
  fill: '#eef'
});
fabric.Image.fromURL('https://img.alicdn.com/tfs/TB1vezqnFzqK1RjSZFvXXcB7VXa-3729-1970.png', function(oImg) {
  oImg.scale(0.5).set('flipX', true);
  group = new fabric.Group([ circle, oImg ]);
  canvas.add(group);
});
```

## Expected Behavior
![image](https://user-images.githubusercontent.com/21785332/50463995-8a026500-09c9-11e9-8a66-7b0b7a1df295.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/21785332/50464011-9edef880-09c9-11e9-929f-ebc6653fbc02.png)

Why the image is blurry，and how to fix it?

**Comment by asturur** [comment]
could you please make a working jsfiddle from your use case?

**Comment by WisestCoder** [comment]
This is first [demo](http://jsfiddle.net/uo07r6fb/3/)
I use only fabric.Image，And this is the expected result.

This is second [demo](http://jsfiddle.net/1ym6j2cx/)
I use fabric.Group to combine fabric.Image and fabric.Circle, you can find the image of canvas is blurry.

**Comment by malipetek** [comment]
Your image `width * height` is `7357532` which exceeds `fabric.perfLimitSizeTotal` ( 2097152 ). 
You can try this: `fabric.perfLimitSizeTotal = 8357532;`

You can see how limiting is happening in [_limitCacheSize](http://fabricjs.com/docs/fabric.Object.html#_limitCacheSize) function.

http://jsfiddle.net/malipetek/s3tL6qgo/

**Comment by WisestCoder** [comment]
Great,  I solved  problem by set a large size of `fabric.perfLimitSizeTotal`.
Thanks a lot.

**Comment by asturur** [comment]
Sorry did not had time to help much.
If you have few objects (less than 20 ) i suggest you to disable caching for maximum clarity when big objects are used. Big cache perform slower than no cache when the big objects are just images.

On the other hand i m working on an exporter to get clear images with caching when using toDataUrl.
But for live canvas usage if you want to have smooth performances most of the time, you need to apply some limit.
