### ISSUE TITLE
Very first demo on Intro Part 1 fails with empty canvas. 

### ISSUE THREAD

**Issue by ogrotten** [fabricjs/fabric.js#5450]
I'm just trying to get my sea-legs with fabric, so I directly copy/pasted the first code to tweak with it. The code in the section http://fabricjs.com/fabric-intro-part-1#why_fabric is apparently supposed to put a teeny red square. It leaves the canvas empty.

## Version
2.4.0

## Test Case
http://jsfiddle.net/ybc7spod/

## Information about environment
Chrome, FFox, JSFiddle

**Comment by asturur** [comment]
Hi, and welcome.
Looks like that having the script tag in the head section is not a good idea.
If you move it later in the body, after the canvas is available, it will work.

**Comment by ogrotten** [comment]
Now that I'm back to my project after the holidays, I wanted to ask: are there outlined setup instructions that I missed?

**Comment by asturur** [comment]
no.
Is a side effect of I initialization.
When the script runs that canvas does not exists yet, so fabricjs creates on and paints that.
The canvas on screen remains empty.

We could outline it in those tutorial, and we could also warn with a message in the console when that happen.
