### ISSUE TITLE
your pan&zoom tutorial is some mistaken.

### ISSUE THREAD

**Issue by simuy** [fabricjs/fabric.js#5459]
## Version
2.4.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Nodejs or browser? browser
Which browsers? chrome

## Steps to reproduce
There is some mistake at http://fabricjs.com/fabric-intro-part-5#pan_zoom.
After alt+drag, the mouseover on shapes don't show mouse cursor's crosshair shape, because the shape's position is also panning, so it shows mouse cursor's crosshair shpes at the wrong positon.

## Expected Behavior
I think the tutorial codes need to be corrected.

## Actual Behavior
Above descripted.

**Comment by asturur** [comment]
i admit i did not care for shapes since selection was disabled on purpose to avoid to complicate the code.
I can fix it.

**Comment by simuy** [comment]
Thank you for answer but, I don't understand the solution you said.
Could you suggest a code about that?
And I'd also like to know differences between the way of pan using canvas.viewportTransform and the ways of pan using canvas.relativePan or canvas.absolutePan.

**Comment by asturur** [comment]
i ll fix the code asap and add some description there so it stays as documentation

**Comment by asturur** [comment]
this has been fixed. the demo now takes in account selectio.
