### ISSUE TITLE
V2 migration - Line elements from 1.x SVG pathgroup do not show at correct position

### ISSUE THREAD

**Issue by sameermanuja** [fabricjs/fabric.js#5467]
I have an SVG with line elements. When saved in 1.7.6 as JSON, and opened in 2.x (with fabric.PathGroup.fromObject in place), the line elements do not show at the correct position. Other elements like circles, ellipses show up just fine. Any thoughts what could be wrong?

Example SVG:
`<?xml version="1.0" ?>
<svg viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg">
<g>
<circle fill="#957c12" stroke="none" cx="32" cy="32" r="30"/>
<line fill="none" stroke="#001c63" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" x1="34" x2="33" y1="6" y2="2"/>
</g>
</svg>`

**Comment by asturur** [comment]
how much are those displaced?
can you attach a screenshot of the SVG and the current fabric import and of what you get?

**Comment by sameermanuja** [comment]
Attaching screenshot of SVG and what I get in 2.3.
![screenshot](https://user-images.githubusercontent.com/42500656/50852221-f9525e80-13a4-11e9-8a75-9b8091d5f9b7.jpg)

**Comment by sameermanuja** [comment]
In fabric.PathGroup.fromObject (converting a 1.x path-group to group), _removeTransformMatrix is called on the enlivened objects. In _removeTransformMatrix, for fabric.Line objects, the center is computed using a dedicated _findCenterFromElement implementation (x1 + x2) / 2, (y1 + y2) / 2. It is restored using setPositionByOrigin. This changes the left/top for Line objects which is causing the displacement. Not sure why Line computes its center that way, and what changing it may break.

**Comment by sameermanuja** [comment]
Any pointers @asturur ?
