### ISSUE TITLE
unit test fail at iphone

### ISSUE THREAD

**Issue by hatano0x06** [fabricjs/fabric.js#5469]
## Version
2.4.6

## Test Case
I access to http://fabricjs.com/test/unit/ from iphone
and iphone test is not 100%
![img_0003](https://user-images.githubusercontent.com/7422251/50890288-3ff39780-143d-11e9-9ec9-315563ce4019.jpg)

## Information about environment
browser
safari and chrome from iphone

**Comment by asturur** [comment]
since i do not have an iphone, can you paste failures here?

**Comment by hatano0x06** [comment]
I think there is a bug in unittest page.
when unit test finish, scroll is prevent and stick to the top.
So I just capture only two test

![unnamed](https://user-images.githubusercontent.com/7422251/50892752-91525580-1442-11e9-8303-796851c2217f.jpg)
![unnamed 1](https://user-images.githubusercontent.com/7422251/50892760-94e5dc80-1442-11e9-886e-566ccdb75309.jpg)

**Comment by asturur** [comment]
if failures are just like that, are small rounding error, nothing to worry about. Could be fault of cpu architecture or different float implementation / math libs in the arm vs x86 area.

**Comment by hatano0x06** [comment]
ok! thank for answer it.
