### ISSUE TITLE
using object.toDataURL() in zoomed canvas returns controls position misplaced

### ISSUE THREAD

**Issue by rikkarv** [fabricjs/fabric.js#5472]
## Version
2.4.6
## Test Case
http://jsfiddle.net/rg9mhvuj/

## Information about environment
Browser: Chrome

## Steps to reproduce
Set zoom input to 2 and click "rectangle.toDataURL" button

## Expected Behavior
On mouse over rectangle and clicking in it should set rectangle as active object

## Actual Behavior
The controls of the rectangle are located as the canvas wasn't zoomed.
![screenshot](https://user-images.githubusercontent.com/40458494/50967843-3fa4dc00-14d1-11e9-931f-fa420293e8fc.png)

## Comments
This situation can be solved by calling "object.setCoords()" after "object.toDataURL()".
However i leave to you the decision if it is a bug or if it should be used .setCoords() (maybe add this example to https://github.com/fabricjs/fabric.js/wiki/When-to-call-setCoords)

**Comment by asturur** [comment]
ok this is a bug. have you any idea if it happened before 2.5.0?

**Comment by rikkarv** [comment]
>           ok this is a bug. have you any idea if it happened before 2.5.0?

I've tried with previous versions and it happened.
I' ve tested now with 2.6 and it's fixed. Thank you very much @asturur

**Comment by asturur** [comment]
depending on what are you doing with the toDataUrl, take care there is a toCanvasElement also now! maybe is usefull if you are redisplaying that dataUrl sonewhere else
