### ISSUE TITLE
Target always null when clicking selected newly created shape

### ISSUE THREAD

**Issue by newtriks** [fabricjs/fabric.js#5475]
## Version
2.4.0

## Test Case
http://jsfiddle.net/74s9erua/1/

## Information about environment
Nodejs or browser? browser
Which browsers? chrome (latest) on OS X

## Steps to reproduce
See fiddle

## Expected Behavior
On clicking selected shape, shape should remain selected and target should not be null

## Actual Behavior
On clicking selected shape, shape does not remain selected and target is null

**Comment by newtriks** [comment]
@contact2mayurkukadiya thanks, but that's not what I am reporting. 

The bug is that if you create a shape then set it as an active object, when the user clicks on it it becomes (a) de-selected [unexpected behaviour] and (b) mouse down on the selected object returns `null` for the target [unexpected behaviour]. 

If you comment out my *hack* lines you'll see that removing and adding the object to the canvas again, then setting as active object actually shows the expected behaviour.

**Comment by asturur** [comment]
Hi @newtriks, the object is unselectable because the object changed size after being added to canvas.
If you change object size by code, be sure to call `currentShape.setCoords();` in the mouseUp event.
