### ISSUE TITLE
Support Relative Image URL src

### ISSUE THREAD

**Issue by nateevans** [fabricjs/fabric.js#5476]
**Affected Version**
Fabric 2.5.0

**Is your feature request related to a problem? Please describe.**
We save canvas JSON in a portable database. So when we save Images to Fabric canvas, we need relative Image src url. The browser and Fabric seem to work correctly with relative url like `/api/path/to/my/image`, but the Fabric api does not handle this as expected.

If we call `setSrc()` with a relative url like `/api/path/to/my/image`, update canvas etc, then call `getSrc()` the result will have the current browser schema and hostname prepended to the src string. Like: `http://127.0.0.1/api/path/to/my/image`.

This seems counter-intuitive behavior and maybe not intended to happen by Fabric.js team.

**Describe the solution you'd like**
I've narrowed down the cause to calling `return element.src` in `fabric.Image.prototype.getSrc`. It seems that the behavior of `HTMLImageElement` causes it to prepend hostname when accessing the property in this way. 

I've found that calling `element.getAttribute('src')` is capable of returning the un-altered relative url and doesn't seem to interfere with current behavior.

```
getSrc: function(filtered) {
  var element = filtered ? this._element : this._originalElement;
  if (element) {
    if (element.toDataURL) {
      return element.toDataURL();
    }
    return element.getAttribute('src');
  }
  else {
    return this.src || '';
  }
}
```

**Additional context**
I can submit a PR for this, but it is not clear to me how testing this should be handled within your testing framework.

**Comment by melchiar** [comment]
A simple override to `fabric.Image.prototype.toObject` can accomplish this. Native support might not be a bad idea though. 

See https://stackoverflow.com/a/51903965/7693185

**Comment by nateevans** [comment]
Yep, I already overrode this in my app, but would prefer not to maintain it for the foreseeable future. Thanks though

**Comment by asturur** [comment]
I would add a step 0 before.
Verify that this is a spec, finding any reference of it somewhere (mdn, w3c )
Verify that browser do this all the same
And verify that jsdom + nodecanvas2 do that too

**Comment by nateevans** [comment]
Correct @asturur it is `getAttribute()`, my bad. I will update the original comment.

**Comment by nateevans** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement is what is being used and seems to be essentially the same across all browsers for this use. 

It extends from `Element` which has `getAttribute()` and that seems to be widely supported https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute

**Comment by nateevans** [comment]
Seems JSDOM implements WHATWG spec? `HTMLImageElement` inheritance looks the same up to `Element` and has same method `getAttribute()`:

https://dom.spec.whatwg.org/#interface-element

**Comment by asturur** [comment]
i m fine with this feature, a test added for it will tell us if node works or not.

**Comment by nateevans** [comment]
OK @asturur, how does this look? https://github.com/fabricjs/fabric.js/pull/5484

**Comment by RoeyMaor** [comment]
This can be closed now

**Comment by asturur** [comment]
yes
