### ISSUE TITLE
mouse move events bind on objects inside the group

### ISSUE THREAD

**Issue by simmons8616** [fabricjs/fabric.js#5480]
I want to achieve this effect. such as:
![image](https://user-images.githubusercontent.com/33823489/51086475-4c039000-1782-11e9-8d82-e17f36443202.png)
As the picture shows:
table is a group, I want to bind mousemove event to the line,  which is not fired.

**Comment by asturur** [comment]
Hi @simmons8616 , there are requirements when opening an issue.
Did you read them before setting up the issue as it is?
