### ISSUE TITLE
Generate Box Image using Canvas

### ISSUE THREAD

**Issue by rajesh0608** [fabricjs/fabric.js#5486]
Hi Folks,

I am looking for to create "Box image" in open and closed mode using Canvas.

This image rotate in different angle like front, back, left, right etc.

Image can be further customise like to add color, text or image.

reference- https://packlane.com/customize/mailer-box?quantity=250

**Comment by asturur** [comment]
This is an high level question that does not fit this issue tracker.
I suggest you to try on stackoverflow.com and also to look at three.js

https://threejs.org/

**Comment by rajesh0608** [comment]
Thanking you.

I already asked on stackoverflow.com
