### ISSUE TITLE
Update custom fabric build page

### ISSUE THREAD

**Issue by Elviron** [fabricjs/fabric.js#5488]
Need to update the website to have the latest fabricjs for the custom build page.
Maybe also add a selection for which version you want?

**Comment by asturur** [comment]
i can t keep all the version on the website. Nor i do want to support the 1.7.22 that much. I ll update the website as soon as i can

**Comment by jtara** [comment]
Note that the website currently custom-builds 3.0.0, but current release is 3.1.0.

As well, the web page says 2.4.3, yet the version built is 3.0.0.

**Comment by asturur** [comment]
Yeah i m a bit behind with everything.
