### ISSUE TITLE
ClipPath manipulation

### ISSUE THREAD

**Issue by AlexSergey** [fabricjs/fabric.js#5489]
## Version
2.6.0

http://jsfiddle.net/08tyake6/

## Steps to reproduce
I tried to select clip path and manipulate that. I setted canvas.setActiveObject(rect.clipPath); but that throw a error. How can I make it right way?

**Comment by AlexSergey** [comment]
I found workaround

**Comment by asturur** [comment]
this could be a tutorial/demo item

**Comment by AlexSergey** [comment]
I've just created transparently rectangle and bind all modifications for original clip path
