### ISSUE TITLE
Cursor position of Textbox.splitByGrapheme

### ISSUE THREAD

**Issue by TsuchiyaMasahiro** [fabricjs/fabric.js#5490]
## Version
2.6.0

## Test Case
https://jsfiddle.net/uemon/aq25mwh7/

## Information about environment
Nodejs or browser? browser
Which browsers? chrome

## Steps to reproduce
I tested "Textbox.splitByGrapheme" released by ver. 2.6.0.
When I double clicked the textbox to edit the text, the cursor position did not move backward from near the center of the text.
I know this problem exists previously, but can I fix it in ver. 2.6.0 ?

## Expected Behavior
The cursor position move according to the mouse position.

## Actual Behavior
The cursor position does not move backward from the near the center of the text.

Thank you in advance.

**Comment by asturur** [comment]
i see, i ll try to fix asap. Strange that i did not catch it.

**Comment by Rootcaller** [comment]
Sorry about the duplication.

As I tried the sample , I found a bug.

When I hightlight words and delete some letters, textbox freezes and disappeared.
Words inside the textbox disappeared either.

**Comment by feixiang001** [comment]
I also found this problem.

**Comment by asturur** [comment]
I have a branch to fix it, trying to push it in the weekend.

**Comment by asturur** [comment]
closed with #5544
