### ISSUE TITLE
Textbox freezes and disappears

### ISSUE THREAD

**Issue by Rootcaller** [fabricjs/fabric.js#5491]
As I tried the sample in this issue , I found a bug.

> Cursor position of Textbox.splitByGrapheme https://github.com/fabricjs/fabric.js/issues/5490

When I hightlight words and delete some letters, textbox freezes and disappeared.
Words inside the textbox disappeared either.

Sometimes, it actually deletes a few words, but mostly textbox goes somewhere.

**Comment by asturur** [comment]
let's stay in #5490 .

duplicate of #5490
