### ISSUE TITLE
How can I obtain the original coordinates from the activeObjects[] elements of a multiple selection?

### ISSUE THREAD

**Issue by Hershef** [fabricjs/fabric.js#5492]
In my selection:created handler I call the getActiveObjects() method to obtain the array of the selected objects and then, with a for-loop, I print in a form the left and top properties of each array elements. However, if it is a multiple selection, these values are different from the one I set when I created the objects. 

https://stackoverflow.com/questions/54232485/how-can-i-obtain-the-original-coordinates-from-the-activeobjects-elements-of-a

**Comment by asturur** [comment]
thanks for following the template for the issues.
I answered it there:
https://stackoverflow.com/questions/54232485/how-can-i-obtain-the-original-coordinates-from-the-activeobjects-elements-of-a/54233183#54233183

i'll close the issue, conversation is open. Let me know if it solves, if it doesn't try to specify better what is not working.

**Comment by Hershef** [comment]
Unfortunately, it doesn't work. The printed coordinates are still different from what I aspect.
My goal is to to read exactly what I set when I created the object. So, if I created an object as
`var circle = new fabric.Circle({left: 10, top: 20});`, when I select that object I expect that `activateObj.left==10 and activateObj.top==20`
