### ISSUE TITLE
Textbox - reset styles to default after press Enter

### ISSUE THREAD

**Issue by AlexSergey** [fabricjs/fabric.js#5493]
## Version
2.6.0

http://jsfiddle.net/d1c8yezn/4/

I enter the edit mode, set carriage after a coma in the first line "et," where letters are red and press enter, then text styles are reset to default: the new line will be a green color, but it's expected to be red.

**Comment by asturur** [comment]
do you remember if it ever worked in the way you say in 2.0?

**Comment by asturur** [comment]
If you swap in the fiddle the 2.6.0 with 2.0.0 https://cdnjs.cloudflare.com/ajax/libs/fabric.js/2.0.0/fabric.min.js still behave the same.
So is not a regression, is probably either a feature or a discussion point if that should be a feature.

More or less if google doc / word behave in that way we want to try to behave in that way too.

**Comment by AlexSergey** [comment]
I changed version for your link. This is the same. The bug happened.

**Comment by asturur** [comment]
Yes i m just saying is like that since long. is not a new problem

**Comment by asturur** [comment]
This has been solved recently with:
https://github.com/fabricjs/fabric.js/pull/6268

**Comment by asturur** [comment]
i hope cleverBrush is doing well!
