### ISSUE TITLE
Move object (image, text) to the right or left and show it flow in on the other side

### ISSUE THREAD

**Issue by iwhp** [fabricjs/fabric.js#5495]
I am trying to figure out if the following is available in fabric.js, or if it could be implemented with it.

I have a object (text or image) on the canvas. I start to move it to the right. When the object starts to leave the visible area of the canvas on the right side, the part which is not visible, should now become visible on the left side.

If this is not a feature of fabric.js today, could it be implemented by using the library?
I would assume, that it should be possible with the following general steps:
- fabric.js sends an event, that the object is leaving the canvas (or it sends an event that an object is moving around and its position)
- the even receiver makes a copy of the object and show is on the other side with the corresponding position.

Would that be possible?
Are there any other solutions?

Thankx a lot - Harry

**Comment by asturur** [comment]
it depends. You could use patterns with offset.
It mostly depend what is the larger scope of this effect you want to  obtain.

You could also make a trick, you could wrap the ender method of each object in a function that render twice, one normal and one with an offset of -canvas.width

**Comment by asturur** [comment]
Let's move it to stackoverflow, because for sure this is neither a new feature nor a bug.
It fall in the category custom help.

**Comment by iwhp** [comment]
moved to https://stackoverflow.com/questions/54297111/move-object-image-text-to-the-right-or-left-and-show-it-flow-it-in-on-the-oth

**Comment by asturur** [comment]
Hi, i know lot of time passed, and no one helped on SO as i can see.
If you did not solve already, i ll try to circle back as soon as i m a bit more free.

**Comment by iwhp** [comment]
Hi asturur... I have a first version running and it looks promising.  I am still not sure about the way I do it, but I could not figure out another way.

The current solution figures out if an object is leaving the left or right side of the canvas.
If it does, a copy is made for the object and placed on the other side.
Every move of these matching objects is then applied to the other.
There is also some clean out code, if objects are in a certain state.

What you think?
Many thankx for coming back!

**Comment by asturur** [comment]
You do not have an example to show?
sorry but i m alone and you guys are too many.
