### ISSUE TITLE
objectCaching can cause stroke clipping

### ISSUE THREAD

**Issue by melchiar** [fabricjs/fabric.js#5497]
## Version
2.6.0

## Test Case
https://jsfiddle.net/melchiar/xqjdmorp/

## Information about environment
Browser - Chrome

## Steps to reproduce
Add a thick stroke to a path with sharp corners and objectCaching enabled. The cache canvas isn't quite big enough to include the stroke at the path's sharpest point, leaving part of the stroke clipped. This can only be fixed by disabling objectCaching.

## Expected Behavior
![image](https://user-images.githubusercontent.com/9057412/51422789-d7599880-1b69-11e9-8166-87d6b8426d3b.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/9057412/51422783-b85b0680-1b69-11e9-8b92-c306031b1384.png)

**Comment by asturur** [comment]
yes, this is a duplicate of a very old issue:
#580

If there was a library, or a alghortim to calculate corners between points of a path, i would be happy to solve it. I do not know how to search for it.

Please take #580 as a reference for this issue.

**Comment by melchiar** [comment]
Thanks asturur. I wondered if this had been reported already but couldn't find any existing issues for it.

**Comment by asturur** [comment]
wasn t reported exactly like that. Anyway if i would commit to study that problem we could unlock also text on a path and correct bounding boxes. Is just lot to study amd experiment and write the code in a way that make sense

**Comment by asturur** [comment]
i found the docs i need, now i need time.
