### ISSUE TITLE
[feature request] Rotation option for toDataURL() 

### ISSUE THREAD

**Issue by semiadam** [fabricjs/fabric.js#5498]
It would be very helpful if toDataURL() can return rotated output at 90 degree multiples. Something like: `toDataURL({rotation: 180})` .There are several use cases that the high resolution output will be used at a different orientation. I understand toDataURL() output can be fed to an external JS function for rotation, but that operation is very CPU intensive because the function has to create a new js canvas, load image, do the transforms, and output again. If it happens several times per second on a large image, it causes 100% CPU usage.

Since fabric.js already has the image in a canvas, it makes sense to do the transform right there before output. That eliminates several steps compared to the external scenario.  Thoughts?

**Comment by asturur** [comment]
Hi @semiadam, sorry for the long time getting back to you.
You can actually already do this rotating the object and using toDataUrl, and then rotate back.

If you need to rotate a single object, you can set its angle then use Object.toDataURL, while if you need to rotate the whole canvas with more objects, you also need to swap width and height.

toDataUrl already has too many option and won't be able to support more.

Also recently we added toCanvasElement together with toDataURL. This allows you to picture a canvas in a single image, and then rotate the single image.
