### ISSUE TITLE
Canvas.toJSON blows up when there is a clipPath defined on the canvas

### ISSUE THREAD

**Issue by matrei** [fabricjs/fabric.js#5499]
## Version
2.6.0

## Test Case
https://jsfiddle.net/mattiasr/zLuq0kt2/11/

## Information about environment
Nodejs or browser? browser
Which browsers? chromium

## Steps to reproduce
Open the developer console to see console output

## Expected Behavior
See JSON representation of canvas

## Actual Behavior
Error thrown, different error if there are objects added to the canvas or if it is empty.

**Comment by asturur** [comment]
duplicate of #5549
