### ISSUE TITLE
Resize Textbox at a high zoom level not possible.

### ISSUE THREAD

**Issue by belartodmarinus** [fabricjs/fabric.js#5500]
## Version
2.4.6

## Test Case
https://jsfiddle.net/aofpqh62/

## Information about environment
Google Chrome

## Steps to reproduce
- Run fiddle
- Horizontally resize Textbox wider
- Resize the Textbox to the initial width

## Expected Behavior
Be able to resize the Textbox to the initial width

## Actual Behavior
The Textbox can't be resized to a certain width (which seems to be random)

**Comment by asturur** [comment]
There is an option in fabricJS to set the minimum width of a textbox, since if you go to little, then is hard to click inside.

http://fabricjs.com/docs/global.html#minWidth

unsure why jsdocs reports it under global.
