### ISSUE TITLE
Improper documentation for fabric.Image constructor/initializer

### ISSUE THREAD

**Issue by joeflateau** [fabricjs/fabric.js#5501]
## Version
2.4.0

## Test Case
http://fabricjs.com/docs/fabric.Image.html#initialize
http://fabricjs.com/video-element

## Information about environment
Documentation

## Actual Behavior
The documents say the first argument to the initializer should be `HTMLImageElement`, but according to the demos, it's valid to pass an `HTMLVideoElement`. So the proper type for the first argument to `new fabric.Image` should probably actually be `CanvasImageSource`? Or maybe just `HTMLImageElement | HTMLVideoElement`?

**Comment by asturur** [comment]
it should be a drawable. Image/Canvas/Video. I ll update the doc

**Comment by asturur** [comment]
fixed.
