### ISSUE TITLE
Lose `__corner` property when you resize the object outside the canvas area

### ISSUE THREAD

**Issue by mariusturcu1** [fabricjs/fabric.js#5504]
## Version
2.4.0

## Test Case
http://jsfiddle.net/nLaxumbj/

## Information about environment
Nodejs or browser?
Which browsers?
All major browsers
## Steps to reproduce
1.Open the console.
2. Select the rectangle and resize it from 'mr' corner until the rectangle pass the canvas area.
3. When you come with the cursor back into the canvas area the `__corner` property is lost.
I think the problem comes from `_onMouseEnter` callback. This function calls `findTarget` and from here 
it goes to `_findTargetCorner` where no __corner is found.
I guess the fix is to check the `_currentTransform` property and if is different from null we just trigger the `mouse:over` event
## Expected Behavior
The __corner property must remain the same
## Actual Behavior
No `__corner` property when you resize the rectangle outside the canvas

**Comment by aggrosoft** [comment]
I can confirm this behaviour, this is due to the fact that mouseenter fires when you re enter the canvas. Maybe implement a mouseout handler that will take care of this?

**Comment by asturur** [comment]
Well tricky to fix to be honest.
Also weird that mousemove continue to fire, probably we attach one to window in this case?

We should fix this, absolutely.

**Comment by asturur** [comment]
Thanks for taking the time of confirming it @aggrosoft
