### ISSUE TITLE
Canvas background image quality when zooming

### ISSUE THREAD

**Issue by santosmken** [fabricjs/fabric.js#5508]
I have a project where a floor plan can be display but one of my issue is the canvas background image become pixelated when I reach a certain zoom level. How can I maintain the quality of the image? One solution that I think is to limit the zooming in of the user but different plans have their own dimensions (some are small some are very large/wide). It'd great if your solution will fix my problem. Thank you in advance.

**Comment by asturur** [comment]
hi @santosmken, sorry for taking long to get back to you.
With this description is not possible to help.
You have to provide a working example so that we can look at the used code.
I'll close the issue, i ll reopen it as soon as the details are provided.
