### ISSUE TITLE
Nodejs fabric - toDataURL with clipPath object makes all other objects transparent

### ISSUE THREAD

**Issue by corey-taffe** [fabricjs/fabric.js#5510]
## Version
Tried on both 2.4.3 and 2.60

## Test Case
https://jsfiddle.net/fr0x/wq8nL1uy/

## Information about environment
Works as expected in browser.
Fails to generate proper output image in Nodejs

## Steps to reproduce
Get the json for a canvas with multiple objects (with at least one having a clipPath...see the jsfiddle).  
Load that json into a nodejs script and export out an image (canvas.loadFromJSON, canvas.toDataURL).  Something similar to what is in here in the node section: http://fabricjs.com/fabric-intro-part-4

## Expected Behavior
An image is generated that matches the json that was generated in the fiddle example

![expected](https://user-images.githubusercontent.com/18216524/51991161-28259700-2470-11e9-8859-2eaae876c221.png)

## Actual Behavior
The only object that is drawn is whatever the last object with a clipPath was

![nodejs_image](https://user-images.githubusercontent.com/18216524/51991041-daa92a00-246f-11e9-9cd0-3af1df61a78c.png)

Maybe related to:
https://github.com/fabricjs/fabric.js/issues/5271

**Comment by 0ro** [comment]
**ClipPath REQUIRES object caching**. So it is written in the [tutorial](http://fabricjs.com/clippath-part1).
For nodejs environment objectCaching is false https://github.com/fabricjs/fabric.js/blob/master/dist/fabric.js#L12409
You can correct this behavior by adding:
```javascript
fabric.Image.prototype.objectCaching = true;
```

**Comment by asturur** [comment]
This has been sort of fixed in latest master.
I changed the major version to 3 and object caching will not disable chaching if it is required for a functionality.
