### ISSUE TITLE
Blurry image inside group when group.top is fractional

### ISSUE THREAD

**Issue by jfizz** [fabricjs/fabric.js#5513]
## Version
2.6.0

## Test Case
http://jsfiddle.net/hdup70zt/1/

## Information about environment
Nodejs or browser? Browser
Which browsers? Latest chrome

## Steps to reproduce
Open up the fiddle and toggle the group's top value between 1.5621975452 and 1. The image becomes slightly blurry when the top value is fractional. Property values can easily become fractional by moving/scaling objects, so I feel like this behavior is a bug.

**Comment by asturur** [comment]
this is not exactly a bug, is a side effect of caching.
And we cannot do much about it.
If you feel like is too bad, you can disable caching.

fabric.Object.prototype.objectCaching = false.

**Comment by jfizz** [comment]
While turning off objectCaching fixes the issue, it also disables clip paths - but that is a separate issue.

**Comment by asturur** [comment]
yes, caching is necessary for clipping.
Sadly we do not have a type of caching that is calculated on subpixels.
