### ISSUE TITLE
fail to render in iphone safari sometimes

### ISSUE THREAD

**Issue by hatano0x06** [fabricjs/fabric.js#5514]
## Version
2.4.6

## Test Case
I'am making comic create application.
and I use fabric for viewing comic.
I use staticCanvas but I create comic few times , fabric going to be fail
this is video I debuging
![error-report](https://user-images.githubusercontent.com/7422251/52231939-87ffc000-28fe-11e9-81e1-65a41db0ee71.gif)

this is capture of error log
**console.log**
![devtools - 163 43 105 137_ 2019_02_05 4_05_00](https://user-images.githubusercontent.com/7422251/52231643-d2cd0800-28fd-11e9-89f2-75a0d7762929.png)

**detail**
![devtools - 163 43 105 137_ 2019_02_05 4_05_23](https://user-images.githubusercontent.com/7422251/52231641-d2cd0800-28fd-11e9-86d7-a41d1d3b0f9e.png)
![devtools - 163 43 105 137_ 2019_02_05 4_04_50](https://user-images.githubusercontent.com/7422251/52231642-d2cd0800-28fd-11e9-9f1b-92858f18312e.png)

## Information about environment
browser
iphone safari
using staticCanvas

## Steps to reproduce
1. access here by iphone safari
https://163.43.105.137/#

2. push 「マンガを生成」button few times ( about three ~ four times)

## Expected Behavior
the picture under the button is render full
![success](https://user-images.githubusercontent.com/7422251/52231425-402c6900-28fd-11e9-8bdf-c4905d079bb9.jpg)

## Actual Behavior
the picture under the button is not render full
![fail](https://user-images.githubusercontent.com/7422251/52231416-37d42e00-28fd-11e9-8033-a0f27b197ecb.jpg)

**Comment by hatano0x06** [comment]
I think it happen when use clippath many time

**Comment by leesc81** [comment]
I also get the same error when calling clippath frequently ...
