### ISSUE TITLE
Wrong Emoji position in chrome when font is too large

### ISSUE THREAD

**Issue by melchiar** [fabricjs/fabric.js#5515]
## Version
2.6.0

## Test Case
https://jsfiddle.net/melchiar/tye4h9gn/

## Information about environment
Browser - Chrome 71.0.3578.98 (Windows 10)
(not reproducible in Firefox)

## Steps to reproduce
Add a `textbox` containing an emoji. When the emoji is made too big, the emoji's position becomes offset up and to the right of the bounding box. This can be reproduced by either by setting a very large font size (around 350), zooming the canvas beyond a certain point, or running `toDataURL` with a multiplier. (The above fiddle demonstrates exporting the canvas with a multiplier)

## Expected Behavior
![image](https://user-images.githubusercontent.com/9057412/52302773-0b430500-2943-11e9-8eee-feefccaf727f.png)
## Actual Behavior
![image](https://user-images.githubusercontent.com/9057412/52302790-185ff400-2943-11e9-874a-236789397104.png)

**Comment by asturur** [comment]
this is an old bug that changed recently.
Before this offset, every emoji too big would just not render in any browser.
Now it renders correctly on firefox/safari but not on chrome.
We should open a bug ticket on their issue tracker and let them handle it.

**Comment by asturur** [comment]
Looks like is fixed in chrome now.
