### ISSUE TITLE
Wrong element size after re-loading the JSON data

### ISSUE THREAD

**Issue by AndreiPog** [fabricjs/fabric.js#5519]
## Version
2.6.0

## Test Case
http://jsfiddle.net/psfgoyhv/3/

## Information about environment
IE, Firefox, Chrome.

## The problem description

Hello, 

At first, let me say "Thank You" for the awesome library "Fabric.js". 

I have found the issue with the wrong element size (scale) after reloading the canvas's JSON. The demo is here:

http://jsfiddle.net/psfgoyhv/3/

I just load SVG (https://menu16.com/Temp/Badge_070.svg) into the canvas by the "loadSVGFromURL" method and then re-load the JSON data (by the "toJSON" and "loadFromJSON" methods). 

In a result, the size of the element is not the same. What I am missing?

Tried many different SVG files, sometimes canvas works without the mentioned problem. The problem is in the SVG?

Thank you.
Andrei.

**Comment by asturur** [comment]
http://jsfiddle.net/fdvo5e0u/

Please bump the value as in line 9.

Fabric for comfort purposes saves up to the second decimal in the data.
If you need more precision, bump it up.
find the number that fits your needs.

**Comment by AndreiPog** [comment]
Andrea Bogazzi,

 

Thank you very much!

 

You saved my life :-)

 

Sincerely,

Andrei.
