### ISSUE TITLE
Video with audio track is not being played in Safari

### ISSUE THREAD

**Issue by solomax** [fabricjs/fabric.js#5521]
## Version
2.4.6

## Test Case
http://fabricjs.com/video-element

## Information about environment
Browser: Safari MacOS 10.13 High Sierra

## Steps to reproduce
Open video example

## Expected Behavior
Video being played as expected

## Actual Behavior
Video is not being played, NotAllowedError in browser console

As I understand it related to: 
https://sites.google.com/a/chromium.org/dev/audio-video/autoplay
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play#Example

Unfortunately I was unable to bypass this restriction since "real" `<video>` element is always hidden, and I see no way to display it with play button :(
Maybe you can give an example how this can be achieved?

**Comment by asturur** [comment]
to me works in safari.
Maybe it was because at some point the video did not have disabled audio?

the real video element is fabricImage._originalElement, is a reference to the real video.

Sorry for the delay anyway. You probably solved in the mean time.

**Comment by solomax** [comment]
Hello @asturur,

Thanks for the answer
I have solved it by wrapping `play()` with dialog popup, and resuming play after click

It's a bit annoying but seems to be the only way to bypass Safari limitations

**Comment by asturur** [comment]
what is exactly the limitation? in my safari it just play. ( mojave )

**Comment by solomax** [comment]
I'm getting `NotAllowedError` due to Safari blocks `play()` of video with sound
I guess it can be fixes as described here: https://support.apple.com/guide/safari/websites-ibrwe2159f50/mac
Or using "interaction with user"

I don't have Mac, but according to our users `Stop Media with Sound` rule is in effect since "High Sierra"

**Comment by asturur** [comment]
well the demo has been updated some time ago, and it does not play audio now. It plays just video. So either is a safari bug to be fixed by them, or you got this bug when the website was still palying audio.
