### ISSUE TITLE
Drawing mode with .captureStream() from fabric canvas

### ISSUE THREAD

**Issue by paulconlin** [fabricjs/fabric.js#5522]
I'm looking to use canvas.captureStream() off of a fabric canvas while in drawing mode. Currently I only see the drawn shapes on mouse up, but would like to see them as the mouse moves. Attached is a gif showing the issue. 

![flipgridresponse 21](https://user-images.githubusercontent.com/10995964/52592574-60cc5580-2e0c-11e9-9773-0b8b2b7257dc.gif)

Is there any way to get it to show the entire drawing process?

Any help would be much appreciated!

**Comment by asturur** [comment]
You should capture a canvas that is the merge of the 2.
Create a new canvas, and copy over it both of them with draw image.

**Comment by asturur** [comment]
Can you share your actual implementation?

**Comment by paulconlin** [comment]
Ahh, yes that was exactly what I needed. I was just copying from the main canvas, but now am merging it with the upper-canvas as well.

![flipgridresponse 22](https://user-images.githubusercontent.com/10995964/52595157-cae7f900-2e12-11e9-9834-dfd21782882f.gif)

**Comment by charmi2011** [comment]
I am facing the same issue. Can you please elaborate the solution. I tried cloning the canvas but can't find the absolute solution.

**Comment by jakajacky** [comment]
> I am facing the same issue. Can you please elaborate the solution. I tried cloning the canvas but can't find the absolute solution.

did you find a way ?

**Comment by sdawka** [comment]
> I am facing the same issue. Can you please elaborate the solution. I tried cloning the canvas but can't find the absolute solution.

AFAIK there's an upper-canvas automatically generated by fabric, they mean that.

**Comment by ilyasaktass** [comment]
I have the same problem. How did you solve it?
