### ISSUE TITLE
mouse:up options give random values on iOS

### ISSUE THREAD

**Issue by Kampii** [fabricjs/fabric.js#5528]
## Version
2.6.0

## Test Case
https://plnkr.co/edit/BFtPYA?p=preview

## Information about environment
On iOS Chrome Browser  64.0.3282.112

## Steps to reproduce
Single finger tap on canvas or two finger tap on canvas. Please see [this video of the test](https://youtu.be/qT-yrwR2Tmg)

## Expected Behavior
Expecting single finger tap to return 0 on mouse up, and two finger tap to return 1 on mouse up either after tap with no drag/ pan or after tap with drag/ pan.

## Actual Behavior
Single finger tap does not return anything at all and two finger tap randomly returns 0 and 1.

**Comment by Kampii** [comment]
Does anyone else get this issue or it is only on my device?

**Comment by Kampii** [comment]
@kangax Any chance you could take a look at this and see if you can replicate the issue that I recorded in the video?

**Comment by asturur** [comment]
If you are referring to this:

```
    overlay.fabricCanvas().on('mouse:up', (options) => {
      showSnackBar("Mouse Up" + options.e.touches.length)
    })
```

options.e is the native event and gets forwarded to the event handler as it is.

It may be that sometimes the tap event is not fired at all, let me check what is the logic if a touch device is detected.

**Comment by Kampii** [comment]
I would think that if tap event is not fired then we would not get the toast, and when it is detected why would it randomly return different values for the same two finger tap?

**Comment by Fatehkhann** [comment]
@asturur  Looks like multi gestures are not being handled, can you please suggest any other options that could help?

**Comment by asturur** [comment]
Multi gestures aren't handled. We are using a side library to do so, did you build your fabricJS with gesture support?

**Comment by Fatehkhann** [comment]
Yeah, we have gesture support in our fabricjs
