### ISSUE TITLE
AngularJS

### ISSUE THREAD

**Issue by raichu** [fabricjs/fabric.js#553]
Is it possible to use fabric.js with AngularJS?
I gave it a try, but apparently none of the functions I gave to `canvas.on.()` got run.

Is AngularJS eating up all events?
I wonder if there's a way of getting fabric.js work with AngularJS.

**Comment by shurui91** [comment]
1. I am kinda surprised Angular does not have any directives related to canvas available./
2. Is writing a directive by myself for Fabric.js sounds like a possible solution for this issue?

**Comment by asturur** [comment]
I wish i could help you but i really do not know angular. I mean you do not need a directive for canvas for use fabricjs. once the element is ready on the dom just initialize the library.

**Comment by shurui91** [comment]
I know we can use Fabric.js in Angular but I am just trying to see if there is a more elegant way to do so. Plugging some non-angular code into an Angular project might not be something can be easily maintained by someone else. But still, thanks for your feedback!

**Comment by asturur** [comment]
check the kitchensink deno, is built with angular.

**Comment by shurui91** [comment]
Can you provide a link for that? Thanks. @asturur

**Comment by keetstream** [comment]
> I wanted to call it on canvas events also, but I encountered another problem even before that. my fabric.Canvas is inited on window.onload event, but angularjs is inited beforehand - thus when trying to use canvas inside a controller I get `canvas undefined` errors. Any idea how to avoid that?
> Thanks



> I wanted to call it on canvas events also, but I encountered another problem even before that. my fabric.Canvas is inited on window.onload event, but angularjs is inited beforehand - thus when trying to use canvas inside a controller I get `canvas undefined` errors. Any idea how to avoid that?
> Thanks

Still facing this issue of not being able to access class's properties inside canvas.on event listener

**Comment by asturur** [comment]
@keetstream the i m not sure if your issue relates to the original question, if it does, is probably a matter of mastering angularJS initialization

**Comment by keetstream** [comment]
hi asturur, I believe so, I got it working though, weirdly enough
