### ISSUE TITLE
Support Fabric in XML documents.

### ISSUE THREAD

**Issue by ajvincent** [fabricjs/fabric.js#5530]
Fabric.js assumes that it runs inside a HTML document.  Which is usually not a bad assumption, but it does mean if I try to load Fabric in a XML document, it just breaks all over the place.  In particular, when referring to properties of element.style, it throws exceptions because element is an instance of [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element), not [HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement).  The latter has the style property; the former does not.

Fortunately the fix is simple:  in HEADER.js, I use `fabric.document = document.implementation.createHTMLDocument("");` to make this work (in the case where document isn't a HTMLDocument).  I will provide a pull request momentarily.

I can provide a testcase upon request, written in SVG and using the `<foreignObject>` element.  (I know, I know, why use FabricJS and Canvas if I have SVG?  Well, I have my reasons - specifically, being able to capture a video stream in the browser from the canvas.)  In general, though, I think the pull request I will generate will work with any XML document.

**Comment by ajvincent** [comment]
[editor.zip](https://github.com/fabricjs/fabric.js/files/2882671/editor.zip)
This has the SVG file and a FabricController.js, and assumes the existence of libraries/fabric/fabric.js .

**Comment by asturur** [comment]
i ll try the editor.zip, understand the use case and probably merge.

**Comment by cnsdato** [comment]
This breaks IE10 and IE9: both do not support HTMLDocument.
Now I have to go back to 2.6.0

**Comment by asturur** [comment]
ie9 is no more supported since 2.0
Ie10 there is a PR to restore functionality, if you would be able to test it, i can merge it.

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/pull/5678
