### ISSUE TITLE
Turn Canvas JSON into PNG within PHP

### ISSUE THREAD

**Issue by JakeOcean** [fabricjs/fabric.js#5536]
I need to render my images in PHP.

I am using AJAX to post my canvas JSON to the server, where I save it into the database for processing later.

How can I take the canvas JSON and turn it into a PNG or JPG?  

I absolutly cannot do this client side, and all guides seem to think you want to download the image from within Javascript using the browser

**Comment by malipetek** [comment]
You have to use __nodeJS__ to make it work. Or you can use something like `puppeteer` to simulate a browser client on server. I am not familiar with PHP solutions which can control a browser on demand. So if you decide to use nodeJS path: 
- You can write something like `convert.js` with fabricjs and node-canvas. I would suggest using `canvas-prebuilt`. 
- `convert.js` would get json from [process stdin](https://nodejs.org/docs/latest-v8.x/api/process.html#process_process_stdin) and use `toDataURL` to export image and return it with [process stdout](https://nodejs.org/docs/latest-v8.x/api/process.html#process_process_stdout)
- From PHP you can do something like this: ``` exec('node convert.js "'.$json_from_client.'"', $output); ```

You can ask for details on [Gitter Room](https://gitter.im/kangax/fabric.js) .

**Comment by aggrosoft** [comment]
ImageMagick will give you a good base for parsing all of the information in the JSON file to get a good output. We are doing this for previews in some of our projects and this works fine. If you want a 1:1 image without putting effort in it there is no way around using nodejs

**Comment by asturur** [comment]
Alos nodejs will not make everything identical. Text has still some problems.
I wish i had time to update to mode-canvas 2.

**Comment by asturur** [comment]
@malipetek solution look doable, unless you have problem installing nodejs on your machines ( like not your machines or not full control )

**Comment by asturur** [comment]
i close it, we can continue talking, but not being here an action item needs to be clsoed.
