### ISSUE TITLE
Having issues with object selection when have image on canvas

### ISSUE THREAD

**Issue by vicky-solulab** [fabricjs/fabric.js#5537]
I am using ReactJS with Typescript and FabricJS to develop a image templating tool.

The issue is when I place image on the canvas, the selection on the canvas doesn't work with a single click, which works fine when there is no image on the canvas. Posting links below of 2 videos for working and not-working scenarios

https://www.dropbox.com/s/jipmwhankq5i7nk/not_working.mov?dl=0
https://www.dropbox.com/s/d3zngdak90r0zwz/working.mov?dl=0

It's just that the selections (blue border) is not visible, rest all the things work fine. In the videos, the options on the left would change based on selection, which shows the selections are working.

**Comment by asturur** [comment]
create a snippet with your setup please.

**Comment by vicky-solulab** [comment]
I got this working with few changes to my redux.
