### ISSUE TITLE
How to load a image into a rectangle and have it moving around?

### ISSUE THREAD

**Issue by vicky-solulab** [fabricjs/fabric.js#5538]
I have a requirement of having the ability to load an image inside a rectangle and it should be moving around. This is very similar to having an image on the canvas and having the ability to move, resize, rotate etc. The same should be available inside a rectangle, or whatever option available. Only concern is the image should be movable, resizable.

**Comment by asturur** [comment]
i think you may have a look at absolute clippath in the website, tutorial area.

**Comment by vicky-solulab** [comment]
Thanks alot for the perfect guiding.

I was able to create to a fiddle and reach to a 90% feasible stage as per my requirement.

The issue I'm facing now is, the image in clipPath is overlapping the objects outside the container. Is there a possibility to disable or remove the overlapping.

I tried the sendToBack function, but that messes up the canvas layering order

Here is my fiddle: 
https://jsfiddle.net/ru3cgh21/12/

**Comment by asturur** [comment]
What does it mean disable overlapping?

Please check in the http://fabricjs.com/docs if you are looking for `preserveObjectStacking`

**Comment by asturur** [comment]
http://fabricjs.com/docs/fabric.Canvas.html#preserveObjectStacking

**Comment by asturur** [comment]
Anyway this is help. Not bug/issue/feature.
So for now i m closing the issue, since i have nothing to fix and work on.
Conversation is open.
