### ISSUE TITLE
fabric without cairo

### ISSUE THREAD

**Issue by flieks** [fabricjs/fabric.js#5539]
Hi, 

Is there a version of fabric that doesn't depend on cairo ?
I want to install it with zeit now but cairo is causing errors.

Greetings

**Comment by asturur** [comment]
the node version need cairo. What is your application for? browser or server?

**Comment by flieks** [comment]
@asturur for browser in reactJS. 
Where can i find the browser version? 
`npm install fabric` installs the node version right ?

**Comment by asturur** [comment]
The version is one only.
Please check how we manage this kind of problem in webpack looking at:
https://github.com/fabricjs/fabricjs-webpack

and so something similiar or your installer/bundler.

Also if you problem is an install problem only, install the cairo dependency on your machines.

**Comment by fuzzzerd** [comment]
Installing other software really isn't a good solution for down stream users.

**Comment by asturur** [comment]
i do not know zeit. If zeit does not let you mock dependencies when bundling or does not respect npm 'optionalDeps' the problem is in zeit.

Npm can install fabric even when cairo is missing.

**Comment by fuzzzerd** [comment]
Yes, npm can install fabric even if cairo is missing; however, it throws a lot of warnings and errors. I'm not suggesting support for ziet. Just saying that it would be nice if npm worked without it.

**Comment by asturur** [comment]
it should throw just warnings and error inside node-canvas but the command should return a 0.

**Comment by fuzzzerd** [comment]
The npm install command does seem to intsall, the warnings and errors just muddy up the logs and make it hard to see if adding or removing other packages worked. On the scale of things, its short of a show stopper but its more than a minor annoyance.

**Comment by asturur** [comment]
I understand, but that is how they built NPM.
When fabric can use node-canvas 2, the cairo will be needed just for architectures for which a prebuilt extension does not exist.
On linux/windows/macos you should be fine.

**Comment by flieks** [comment]
Thanks for the help, eventually it worked on zeit. Didn't have to add any special webpack configuration, 
Using CRA with react-scripts, typescript, @now/static-build
