### ISSUE TITLE
Error generating SVG file when adding endAngle or startAngle attribute

### ISSUE THREAD

**Issue by francoly** [fabricjs/fabric.js#5540]
## Version
2.4.6

## Test Case
error svg
## Information about environment
Nodejs or browser?
is browser
Which browsers?
chrome 71

## Steps to reproduce
new fabric.Circle  and  add property endAngle or startAngle.
When I execute the toSVG()，The SVG file is error。
I found  the tag '<path d="M xxx"style="xxx">' in SVG  is missing a space between 'd' and 'style''
I'd appreciate it if you fixed it,thank

Chinese:
你好，我在使用fabricJS生成一个扇形时，使用了endAngle 和 startAngle属性，在生成svg文件时，生成出来的svg文件报错，我查看了下svg文件，发现是因为path 标签中的style属性之前缺少空格，非常感谢您的修复。

## Actual Behavior
http://svg-prod.oss-cn-shenzhen.aliyuncs.com/5ac8b5d9d39e3f396729aa08/work_canvas_M_f3e9d8e8-beff-4287-9356-e1206271f97c_5e87e7582a305e957827cab4ed4ca371.svg

**Comment by asturur** [comment]
fixing in #5544
