### ISSUE TITLE
LoadFromJSON not load png;base64 image

### ISSUE THREAD

**Issue by W3b3r** [fabricjs/fabric.js#5541]
Hi guys,
i'm trying to load my canvas from json data but image set in data:image/png;base64 does't be loaded in canvas.
 It only load the box inside created canvas neither the text.

Here is a fiddle.
http://jsfiddle.net/xkpen7tu/2/

FabricJS version: "1.7.6"
Thanks in advance for help.

**Comment by asturur** [comment]
i have no idea if your JSON has a clipTo function somewhere but the error is clear:
![image](https://user-images.githubusercontent.com/1194048/53682308-cbc6c900-3cf4-11e9-81e7-1630cc183fd3.png)

a `lumise` is not defined. Something in your JSON is wrong.

**Comment by W3b3r** [comment]
Updated with no function in clipTo.
https://jsfiddle.net/W3b3r/msf6tk13/12/
The png;base64 doesn't show

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/53683138-bd30df80-3cfd-11e9-8e96-61e5925d196b.png)

do we have an image of what we should see on screen?

**Comment by W3b3r** [comment]
Miss this image: https://prnt.sc/ms9h1z

**Comment by asturur** [comment]
http://fabricjs.com/v2-breaking-changes

please the answer is here where is written `fabric.Image.fromObject IMPORTANT!`
This JSON is probably created with an older fabricJS version prior to 2.0, and loaded with 2.6.0 ?

if i apply the logic described in the doc for the fromObect method it works.

**Comment by MuhammedRafi** [comment]
@W3b3r did you got any solution?
