### ISSUE TITLE
Support images with EXIF rotation

### ISSUE THREAD

**Issue by brunolm** [fabricjs/fabric.js#5542]
**Is your feature request related to a problem? Please describe.**
I'm loading images from camera/album in a mobile device and some of the images have EXIF rotation, so I see them upside down etc.

**Describe the solution you'd like**
I'd like an option on `fabric.Image.fromURL` to handle EXIF header

**Describe alternatives you've considered**
An alternative is handling it before I load in the canvas, but I think it would be faster if Fabric could do it directly. The performance is not ideal in the current scenario.

**Additional context**
None.

**Comment by asturur** [comment]
Sorry this can't be a fabric feature.
Fabric is already overloaded with support of things with limited scope and is difficult to keep everything with coherence moving forward.

**Comment by kiramclean** [comment]
I'm experiencing this, too. We have some images that have an EXIF orientation other than 1 that do not display properly when they are loaded as a fabric image.

**Comment by asturur** [comment]
i think is a browser bug anyway.

If the image gives values for width and height but then gets drawn rotated that is a bug at least. it makes impossible to use the api correctly. Can we reproduce it in a jsfiddle?
