### ISSUE TITLE
svg with image inside is not showing in safari and illustrator

### ISSUE THREAD

**Issue by MiqayelSimonyan** [fabricjs/fabric.js#5548]
after setBackgroundColor as base64 image
when i try to use canvas.toSVG()
it is working on chrome but
it is not working on safari or adobe illustrator

this is a example
https://jsfiddle.net/Mikayel_Simonyan/q480rche/12/

**Comment by asturur** [comment]
I ll reopen the issue when there is a description and a failing fiddle.
Please read the template.

**Comment by MiqayelSimonyan** [comment]
i have added description and link for jsfiddle

**Comment by MiqayelSimonyan** [comment]
in safari instead of background image from svg showing black place
in adobe illustrator layers from svg is missing.
