### ISSUE TITLE
[IOS clipPath] When adding an object's clippath to canvas and drag it several times, get "Total canvas memory use exceed the maximum limit" error. However, if do not add the object's clippath to the canvas, work normally.

### ISSUE THREAD

**Issue by leesc81** [fabricjs/fabric.js#5551]
## Version
2.4.6~2.7.0

## Test Case
**Getting memory error**
http://etc.soochang.pe.kr/iphone_test_clippath_added.html
**Working fine**
http://etc.soochang.pe.kr/iphone_test.html

## Information about environment
Nodejs or browser?
browser

Which browsers?
iOS(12.1.4) safari, chrome, firefox(iPhone 6, iPhone X) - error
Android chrome(Galaxy note fe, Galaxy s6). - fine

The object's clippath works whether it is added to the canvas or not. However, if the object's clippath is added to the canvas on the iPhone, dragging a few times will cause a memory error.

## Actual Behavior
When adding an object's clippath to canvas and drag it several times, get "Total canvas memory use exceed the maximum limit" error. However, if do not add the object's clippath to the canvas, work normally.

![2019-03-04 12 21 02](https://user-images.githubusercontent.com/16448526/53708713-13299280-3e78-11e9-919b-d0e0049e44b9.png)

![img_518cec1a9bef-1](https://user-images.githubusercontent.com/16448526/53708761-4b30d580-3e78-11e9-88f2-baab250df93c.jpeg)

**Comment by anthify** [comment]
I believe this maybe connected to this [issue](https://github.com/fabricjs/fabric.js/issues/5549).

Try adding this to your code before instantiating your canvas. (warning: using some es6 features).
```javascript
fabric.Canvas.prototype._toObjectMethod = function _toObjectMethod(
  methodName,
  propertiesToInclude
) {
  const { clipPath } = this;
  const data = {
    version: fabric.version,
    objects: this._toObjects(methodName, propertiesToInclude)
  };

  if (clipPath) {
    data.clipPath = clipPath;
  }

  fabric.util.object.extend(
    data,
    this.__serializeBgOverlay(methodName, propertiesToInclude)
  );

  fabric.util.populateWithProperties(this, data, propertiesToInclude);

  return data;
};
```

**Comment by leesc81** [comment]
I have applied your code but still have a memory error on the iPhone.

I have not been able to release the app for iPhone because this issue is not resolved.
There is no problem with Android or PC browsers.

Could you fix a memory error when using clippath on the iPhone?

@asturur Please take a look at this issue

**Comment by leesc81** [comment]
@asturur @kangax Please check this issue...

**Comment by asturur** [comment]
have lot of emails, getting rid of the one liners first to make some breathing space for me.

Meanwhile can you try to disable retina on your canvas? Just to try.

when creating the canvas pass 'enableRetinaScaling: false' in the options object.

**Comment by leesc81** [comment]
@asturur Thank you for your effort.

Changing enableRetinaScaling to false still causes the same problem.
(Total canvas memory use exceed the maximum limit 224MB)

There is a problem with using a small image. Take a look at the example url.

Also, turning off enableRetinaScaling is not a viable option because it significantly degrades the image quality.

The problem occurs when clippath is added to the canvas.

I hope it has been resolved.

**Comment by yunho2141** [comment]
@asturur @kangax Have you fix this issue?

it happen to me.

**Comment by wiktor-wrzaszcz** [comment]
Same issue reporting, after years. :)

I'm creating a cone out of a circle and rectangle within. Rectangle is the clippath and is 4 times smaller, resulting in a cone-alike shape.

Error occurs on iPad only (i tested only iPad so far, but i assume similar issue on iPhone might occur), and only when playing around bigger zooms.  - it hits limits 480mb with same error

Retina scalling does not help, unfortunately.

Any ideas? :)

**Comment by asturur** [comment]
My personal idea/suggestion is to use a clipPath when is necessary.
ClipPath requires caching the object in an extra layer and that cost processing time and memory to keep the result around.
Zooming makes things worse because it creates larger caches that by default i think are limited to 8Mega pixels. ( still big enough to count on 480mb )
Some simple suggestion is to draw a cone with a path rather than a composition of 2 objects and also disable caching entirely if you are using simple objects.

Ipads can have retina scaling up to 3x that makes your base canvas grow in size quite fast.
