### ISSUE TITLE
Shadow scaling independently from parent object

### ISSUE THREAD

**Issue by serkyen** [fabricjs/fabric.js#5552]
It would be great to be able to manipulate the scale of a shadow independently from its parent object. Maybe using width and height, or using scaleX and scaleY. 

```
obj.setShadow({
        color: 'red',
        blur: 20,
        offsetX: -5,
        offsetY: 5,
        scaleX: 0,
        scaleY: obj.width/2
});
```
Fabric.js is a 2D environment but In my project, I am using a lot of 3D elements, and being able to adjust the scale of shadows would really help with this. 

![image](https://user-images.githubusercontent.com/16330002/53772262-7fb49800-3f31-11e9-8b5c-e27cc986bdf6.png)
 
@kangax

**Comment by asturur** [comment]
You can't scale a shadow, since a shadow is a side effect of a drawing operation and cannot be scaled independently from the object itself ( until we start to draw our own shadows ).

The only thing you can do with the current api is to make blur bigger.

**Comment by asturur** [comment]
Feel free to continue posting, not being any action item i close the issue. This does not mean i won't get notified of the posts.
