### ISSUE TITLE
Programmatically select text in Textbox

### ISSUE THREAD

**Issue by paulconlin** [fabricjs/fabric.js#5555]
Just interested to know if there's a way to programmatically select the text within a Textbox. Not just setting it as the active object, but actually highlighting and selecting the text. 

Interaction would be I would click an "Add textbox" button, and then the text would be selected so the user could immediately start typing instead of having to double click on the textbox to select the text.

![selecttext](https://user-images.githubusercontent.com/10995964/53816916-15e4c000-3f2a-11e9-986b-abcb26e6c5d9.gif)

**Comment by aggrosoft** [comment]
IText has an enterEditing function, just call this after adding the object to stage. See the mixin on how the default mouse behaviour works:

https://github.com/fabricjs/fabric.js/blob/master/src/mixins/itext_click_behavior.mixin.js#L155

**Comment by asturur** [comment]
i think you can actually do .EnterEditing() and then .selectAll()

there are more methods like .setSelectionStar() and .setSelctionEnd()

**Comment by paulconlin** [comment]
As always, you guys are amazing. Thanks so much 👍 

You need a patreon or something so I can send beer.

**Comment by asturur** [comment]
i guess this was in the docs :)

**Comment by paulconlin** [comment]
🤦‍♂️
