### ISSUE TITLE
 The text is blurred on windows when zooming, there is no such problem on the mac.

### ISSUE THREAD

**Issue by tong3d** [fabricjs/fabric.js#5559]
no such problem on the mac：
![image](https://user-images.githubusercontent.com/39045329/53862298-def1d580-4021-11e9-9129-c3f86f31bf89.png)

on windows：
![image](https://user-images.githubusercontent.com/39045329/53862191-828eb600-4021-11e9-8bc7-80f3dd3f241f.png)

**Comment by asturur** [comment]
Please add a fiddle denonstrating the problem.
