### ISSUE TITLE
clipPath clips canvas instead of group if group has objectCaching set to false

### ISSUE THREAD

**Issue by niels-van-den-broeck** [fabricjs/fabric.js#5561]
## Version
2.7.0

## Test Case
http://jsfiddle.net/jzt5s0py/6/

## Information about environment
Nodejs or browser? Browser
Which browsers? All

## Steps to reproduce
- Create 2 fabric Images fromURL
- Add them in a fabric.Group
- set group objectCaching to false
- Add a clipPath to this Group

## Expected Behavior
it clips the group to the clipPath

## Actual Behavior
it clips the canvas to the clipPath

**Comment by aggrosoft** [comment]
looks like your jsfiddle link is not correct

**Comment by niels-van-den-broeck** [comment]
> looks like your jsfiddle link is not correct

Fixed and Adjusted description of the issue.

**Comment by asturur** [comment]
CliPath does require caching.
If is off, things do not work as expected. ( same problem we had with clipTo, they just did not work at all)

In the next version 3.0, there will be just 2 changes. Node 4,6 will be drepecated and objectCaching will change meaning. If disabled caching will be disabled only if possible. If clipPath or other things  needs it, it will be used.

It will be part of the rendering and no more a feature.
