### ISSUE TITLE
Problem resize canvas and object

### ISSUE THREAD

**Issue by W3b3r** [fabricjs/fabric.js#5563]
Hi guys,

I'm trying to resize canvas and all object in it.
After load the Json and set the main width and height of the canvas i just try to resize canvas.
After resize the canvas and the object some of the object don't respect the top value(or not is calculated right i my function).
I'm runnung on fabricjs 1.7.7
Here is  a Fiddle: http://jsfiddle.net/W3b3r/3stbg75d/
(in this fiddle there is some timeout to show at first the result of load json and after the result of resize)
In this case i got some element that don't have the same position after resize.

I also try only the command centerH() without scaling but the result is the same i got some of picture out of viewport.

Thanks in advance.
Best.

**Comment by asturur** [comment]
Maybe the best thing to do is to group all objects in a single group.
Scale as much as you need the group to fit in your new canvas.
Then ungroup everything again.
In that way, everything is scaled proportionally ( or just moved together )

Also please upgrade to latest 2.x, so many fixes happened, 1.7 is no worth anymore.
