### ISSUE TITLE
(textBox)The cursor position of the second line is incorrect after the text is wrapped

### ISSUE THREAD

**Issue by Wildlifes** [fabricjs/fabric.js#5572]
## Version
2.7.0

## Information about environment
 browser
chrome

## Steps to reproduce
```
new fabric.Textbox('some text', {
       width:100,
        height:30,
        splitByGrapheme: true
 })
```

## Expected Behavior
After a line break, the second line cursor goes to the end of the text

## Actual Behavior
The second line cursor cannot reach the end of the text after a line break
![image](https://user-images.githubusercontent.com/26505011/54247481-1c9bb480-4574-11e9-9190-7a12d3e25661.png)

**Comment by Wildlifes** [comment]
use   splitByGrapheme

**Comment by Wildlifes** [comment]
Hope to support Chinese line-changing, but set the properties, English Line-Changing also has problems.

**Comment by asturur** [comment]
i ll look at it. Does chinese line have problems? can you describe them? Splitbygrapheme may lead to subpar result with languages that uses spaces, since words will break everywhere.

**Comment by Wildlifes** [comment]
The cursor position in the second line will be in front of the penultimate first letter. This is a problem in both English and Chinese.

**Comment by asturur** [comment]
how does it works with more lines and more words?

**Comment by Wildlifes** [comment]
I can't move the cursor to the end of the second line.

**Comment by Wildlifes** [comment]
I think it's the use of Splitbygrapheme that caused the original Line-Changing function cursor position bug.

I don't use Splitbygrapheme. It's okay to change lines in English. The cursor can also be moved to the last line.

**Comment by Wildlifes** [comment]
I don't use Splitbygrapheme. English line wrapping is fine. The cursor can also be moved to the end of the last line.

**Comment by Wildlifes** [comment]
I think it's the use of Splitbygrapheme that caused the original Line-Changing function cursor position bug.

**Comment by Wildlifes** [comment]
Dude, think about my problem.

**Comment by Wildlifes** [comment]
#5490 this issue  is same
