### ISSUE TITLE
Can i set 2 images to overlay?

### ISSUE THREAD

**Issue by ternaryCat** [fabricjs/fabric.js#5574]
Hi!
Can i set 2 images to overlay?
I have 1 static image and 1 which i move.
I tried to combine that as group and set group as overlay, but it doesn't work.

**Comment by asturur** [comment]
a group can be an overlay.
What do you mean by 'does not work'?

Please add a jsfiddle with your failing test case.

**Comment by ternaryCat** [comment]
i removed code(
I wrote something like this

**Comment by ternaryCat** [comment]
i removed code(
I wrote something like this
var group = new fabric.Group()
var imgInstance1 = new fabric.Image(image1, {});
var imgInstance2 = new fabric.Image(image2, {});
group.add(imgInstance1)
group.add(imgInstance2)
canvas = new fabric.Canvas('render')
canvas.setOverlayImage(group)

**Comment by asturur** [comment]
need to add a working fiddle as per issue requirements.

**Comment by ternaryCat** [comment]
Can you show how to do this?

**Comment by asturur** [comment]
http://jsfiddle.net/fabricjs/Da7SP/

^^^ make from this your working code that show the problem

**Comment by ternaryCat** [comment]
done
http://jsfiddle.net/fabricjs/Da7SP/

![1234](https://user-images.githubusercontent.com/24289268/54290894-f0188480-45d5-11e9-8f12-dd3e3f65bfad.PNG)

**Comment by ternaryCat** [comment]
done 
http://jsfiddle.net/Ternarycat/1cg5m4fh/1/

I need the logo and background to  change, and the center was static, while the center always overlaps the background, and the logo overlaps the center
![Снимок](https://user-images.githubusercontent.com/24289268/54293795-d0378f80-45da-11e9-9e17-76d9e9d1efb3.PNG)

**Comment by asturur** [comment]
i came back to the issue, but i cannot really understand what is not working.
Can you setup the desired effect somehow so that is visible/understandable?
