### ISSUE TITLE
Adding styles to Itext Object

### ISSUE THREAD

**Issue by enekobermejo** [fabricjs/fabric.js#5575]
Im working in a project that i need to apply different styles to each word of IText object. I'm trying to achieve this using **styles** propierty of IText object, but it seems that it applies style in a character level, not in a word level.

For example in the code below it applies different styles to different characters. My question is if there is a possibility of appliying styles to all the word.

```
var iTextSample = new fabric.IText('hello\nworld', {
  left: 50,
  top: 50,
  fontFamily: 'Helvetica',
  fill: '#333',
  lineHeight: 1.1,
  styles: {
    0: {
      0: { textDecoration: 'underline', fontSize: 80 },
      1: { textBackgroundColor: 'red' }
    },
    1: {
      0: { textBackgroundColor: 'rgba(0,255,0,0.5)' },
      4: { fontSize: 20 }
    }
  }
});
```
 I tried to achieve this with the code below, but it would not work.
```
styles: {
    0: {
       textDecoration: 'underline', fontSize: 80 
    },
    1: {
      0: { textBackgroundColor: 'rgba(0,255,0,0.5)' },
      4: { fontSize: 20 }
    }
  }
```

**Comment by asturur** [comment]
No sadly there is no such functionality.
Style management in fabricJS is still hard.

I would suggest trying to use setSelectionStyles method, and selecting the pieces of text you need using setSelectionStart and setSelectionEnd.

**Comment by enekobermejo** [comment]
Okay thanks. I will try some workaround!!
