### ISSUE TITLE
Pinch to zoom performance on mobile is very slow.

### ISSUE THREAD

**Issue by leesc81** [fabricjs/fabric.js#5576]
## Version
2.0 ~ 2.7.0

Scaling with the corner control is very smooth because the applyResizeFilters function is called when the finger released.

However, when scaling an image with a multi-finger, the applyResizeFilters function is applied on every frame, so lag is heavier.

If not use the resize filter, it will be a little smoother when scaling with multi-fingers, but still laged rather than scaling with corner controls.

I hope this problem is resolved to provide high quality image to mobile users with resize filters.

Thank you...

**Comment by asturur** [comment]
we have an open issue for handling this. Please have a look in issue list and comment on that one.

Thanks
