### ISSUE TITLE
blank text component - bugs

### ISSUE THREAD

**Issue by zuliandri2** [fabricjs/fabric.js#5579]
Hi,
I am try to reload data from json, but it shows blank, only show rectangle,
This is only first reload, second reload become normal
In my project, I group Rect and TextBox.
either release component
here, I tried to reload
![image](https://user-images.githubusercontent.com/10961433/54502127-9f998200-495b-11e9-89d6-9c879ca3b23d.png)
this is second reload
![image](https://user-images.githubusercontent.com/10961433/54502374-d8862680-495c-11e9-8ee3-58794027ef9c.png)

and, here release component
![image](https://user-images.githubusercontent.com/10961433/54502162-c952a900-495b-11e9-87a5-bbe51f935509.png)
this is second reload
![image](https://user-images.githubusercontent.com/10961433/54502356-c5735680-495c-11e9-8181-ee96b9e539e5.png)

**Comment by asturur** [comment]
Without a failing fiddle that demonstrate the problem we cannot do anything.
