### ISSUE TITLE
Applying the "Redify" filter (from Tutorials) throws error

### ISSUE THREAD

**Issue by ickata** [fabricjs/fabric.js#5580]
Hi,

Applying the "Redify" filter [from the Tutorials page](http://fabricjs.com/fabric-intro-part-2#image_filters) results in:

```
Uncaught Error: Fragment shader compile error for Redify: ERROR: 0:6: 'assign' : cannot convert from 'const int' to 'highp float'
ERROR: 0:7: 'assign' : cannot convert from 'const int' to 'highp float'

    at klass.createProgram (VM50 lib.m.js:20844)
    at klass.retrieveShader (VM50 lib.m.js:21003)
    at klass.applyToWebGL (VM50 lib.m.js:21022)
    at klass.applyTo (VM50 lib.m.js:20987)
    at VM50 lib.m.js:20458
    at Array.forEach (<anonymous>)
    at WebglFilterBackend.applyFilters (VM50 lib.m.js:20458)
    at klass.applyFilters (VM50 lib.m.js:19895)
```

Using fabric v2.4.6

All other built-in filters (Sepia, etc.) are applied as expected. 

Any idea what am I doing wrong?

**Comment by antoox** [comment]
Hello ickata,

I just came across the same issue. 
The following section contains the issue:

      'vec4 color = texture2D(uTexture, vTexCoord);\n' +
      'color.g = 0;\n' +
      'color.b = 0;\n' +

`g` & `b` are `float`, not `int`, meaning they should be assigned to `0.0`.

Here is the right `fragmentSource`: 

    fragmentSource:
        "precision highp float;\n" +
        "varying vec2 vTexCoord;\n" +
        "uniform sampler2D uTexture;\n" +
        "void main() {\n" +
        "vec4 color = texture2D(uTexture, vTexCoord);\n" +
        "color.g = 0.0;\n" +
        "color.b = 0.0;\n" +
        "gl_FragColor = color;\n" +
        "}",

**Comment by TrumanGu** [comment]
![image](https://user-images.githubusercontent.com/32283973/72216211-2fe32c00-3559-11ea-917e-6e3c60613cf2.png)

**Comment by asturur** [comment]
someone could open a quick PR to fix it in the demo

**Comment by jminardi** [comment]
This issue should not be closed as the documentation still contains the failing code.

**Comment by jminardi** [comment]
I've created a PR: https://github.com/fabricjs/fabricjs.com/pull/267

**Comment by asturur** [comment]
merged.
