### ISSUE TITLE
ClipPath with text when we call toSVG is broken

### ISSUE THREAD

**Issue by AlexSergey** [fabricjs/fabric.js#5581]
## Version
2.7.0

## Test Case
I call toSVG method in your "clipping with text example" (http://fabricjs.com/clippath-part2). It is produce to error: "this._toSVG is not a function"
https://jsfiddle.net/zjg8f5L9/

## Steps to reproduce
Just open my fiddle and check the console
https://jsfiddle.net/zjg8f5L9/

**Comment by asturur** [comment]
we can fix it, but i think TEXT can't be used as a clipPath in SVGs.
We should use the globalCompositeOperation of SVG, that would be fine, but i remember is not really well supported.
It works only on ie11 and the bigger browsers wants to support the version of svg2, but that is not ready yet ( at least 1 year this was the situation )

**Comment by asturur** [comment]
it sort of works. So text can be a clipPath i just forgot about it.
The position is not exact as it should be, but since i m busy, i m just fixing the error and moving on.
