### ISSUE TITLE
About new documentation instead of replace old documentation and demos

### ISSUE THREAD

**Issue by contact2mayurkukadiya** [fabricjs/fabric.js#5594]
every developer needs a better documentation, if possible, please add new documentation of new version of fabricJS  instead of replace old all documentation.

It's too hard to find old code and documentation of old version and demos. and one other thing is that if developer's project is too large, there is too hard to convert fabricJS version from old to new. so please if possible, please do not remove old version documentation and demos.

**Comment by asturur** [comment]
Well how do other libraries do? where is documentation of jsdom 9 or immutable.js 2 or react 0.12?

You have to pickup the website from git and rebuild it to see.

**Comment by contact2mayurkukadiya** [comment]
> You have to pickup the website from git and rebuild it to see. 

How can I rebuild project ? will you please mention in detail.

Should we represent documentation like saperate version like font awesome size like : https://fontawesome.com/v4.7.0/

above url contain version , can we do like this.

**Comment by melchiar** [comment]
Keep in mind that unlike FontAwesome which operates on a paid subscription model if you want all the features, FabricJS is competely free to use and built/maintained by unpaid hobbyists. That being said I've always found Fabric's documentation more than more than adequate all things considered. 

Is there room for improvement? Sure. If you'd like to contribute you'll find a list of ways you can help out here: [Love Fabric? Help us by...](https://github.com/kangax/fabric.js/wiki/Love-Fabric%3F-Help-us-by...)

**Comment by asturur** [comment]
There is lot of soace for improvement, especially in docs.

To rebuild the website, clone fabricjs.com repository, move back to the commit with a specific version, then run the website locally  to run demos and read old jsdocs.
