### ISSUE TITLE
onSelect called when the object is not selected.

### ISSUE THREAD

**Issue by rpFilipe** [fabricjs/fabric.js#5596]
## Version
2.6.0

## Test Case
http://jsfiddle.net/rpfilipe/rjx23sek/4/

## Information about environment
Chrome, FIrefox

## Steps to reproduce
Perform a selection by dragging the mouse that doesn't intersect the object.

## Expected Behavior
onSelect() should not be called.

## Actual Behavior
onSelect() is caled

## Where's the problem
The onSelect() is called in the __collectObjects() method.

On the [docs](http://fabricjs.com/docs/fabric.Object.html#onSelect) is stated that "This callback function is called every time _discardActiveObject or _setActiveObject try to to select this object".

Full Call Stack
__collectObjects() : fabric.js:12024
_groupSelectedObjects(): fabric.js:12015
_maybeGroupObjects(): fabric.js:12074
__onMouseUp(): fabric.js:11290
_onMouseUp(); fabric.js:11187

**Comment by asturur** [comment]
i think the doc needs to be updated.
That function is called everytime something (that is not under direct dev control) tries to select the object and you want to intervene before this happens.

**Comment by asturur** [comment]
oh well i see your point. is called too much there. a bug.

**Comment by rpFilipe** [comment]
Okay, I understand now. Maybe we should move the calling of the onSelect after we determine whether the object is in the area of the selection?

**Comment by rpFilipe** [comment]
Created a PR that fixes this problem. #5632
