### ISSUE TITLE
Bad dimensions when getting them from input value

### ISSUE THREAD

**Issue by kordix** [fabricjs/fabric.js#5598]
## Version
2.7.0

## Test Case
https://codepen.io/kordix/pen/bZXBQz

## Information about environment
Chrome version 73.0.3683.8

## Steps to reproduce
1.Make an fabric object e.g Rect or Image
2.Set width and height properties
3.Make another fabric object which takes width and height from inputs but with the same values like in first example.
4.See the difference

## Expected Behavior
Objects should act identical, but it makes huge difference when it gets values from input instead writing it directly in function

## Actual Behavior
It makes much bigger object when it took width and height from inputs. Look on example on codepen. 
What is also strange the objects get out of select boundary

**Comment by asturur** [comment]
are you passing numbers? inputs returns strings.

**Comment by kordix** [comment]
Daamn... thanks used parseInt now it works
