### ISSUE TITLE
freedraw not draw shorter than circle or zero number

### ISSUE THREAD

**Issue by ShahramCodeDeveloper** [fabricjs/fabric.js#5599]
hello
When drawing a number 0 or a small circle do not draw
please see issue: [https://i.ibb.co/yFD8CNL/photo-2019-03-29-01-34-42.jpg](https://i.ibb.co/yFD8CNL/photo-2019-03-29-01-34-42.jpg)

jsfiddle:  https://jsfiddle.net/ShahramCodeDeveloper/xz053pmk/4/

this work on paper.js: [https://i.ibb.co/7v9ncXw/0.jpg](https://i.ibb.co/7v9ncXw/0.jpg)

where is problem?

**Comment by asturur** [comment]
Please add a working fiddle not screenshots.

**Comment by ShahramCodeDeveloper** [comment]
> 
> 
> Please add a working fiddle not screenshots.

Thank you for answering asturur

jsiddle: https://jsfiddle.net/ShahramCodeDeveloper/xz053pmk/4/
