### ISSUE TITLE
The selectable property on Textboxes are inconsistently ignored in Fabric.js

### ISSUE THREAD

**Issue by peterkmurphy** [fabricjs/fabric.js#5600]
## Version
2.7.0

## Test Case
https://jsfiddle.net/peterkmurphy/85pymLns/

## Information about environment

npm 6.4.0 on Linux Mint 18.3 (Compatible with Ubuntu 16.04)
Firefox Quantum 64.0 (64-bit)
Repeated in Google Chrome 71.0.3578.98 (Official Build) (64-bit)

## Steps to reproduce

1. Click on "A" and edit it to something else (like "D").
2. Click on "B" and edit it to something else (like "E").
3. Move the mouse across all three text boxes with the left button down, as if you are trying to select all three textboxes.
4. Click on the "D" so the text cursor is next to it.
4. Repeat action 3 again.

## Expected Behavior

No text boxes should be selected at all in steps 3 or 5. They cannot be expanded, dragged or rotated.

## Actual Behavior

1. In step 3, a selection box appears around "D". However, it is not possible to drag or rotate it.
2. In step 5, "D" and "E" are now selectable. You can even expand them by size, and rotate them.

**Comment by asturur** [comment]
defintely a bug, and  a quick fix too i think.

**Comment by asturur** [comment]
jsut for you info, the fiddle is overly complicated. i think that a single textbox and enter/exit editing mode is all you needed to reproduce

**Comment by peterkmurphy** [comment]
Thanks for looking at it. I wasn't certain how to reproduce using a simpler fiddle, but I will try to simplify anytime another issue arises.
