### ISSUE TITLE
Fabric 2x NodeJs How To Load Fonts - canvas.Font is not a constructor

### ISSUE THREAD

**Issue by glenelkins1984** [fabricjs/fabric.js#5601]
According to the fabric documents and everything else I read online the following code should work to load fonts via node for fabric:

```
// create the canvas
                var canvas = new fabric.Canvas(null,{
                    width:docWidth,
                    height:docHeight,
                    backgroundColor:'white'
                });

                var font = new canvas.Font('JosefinSans-SemiBold','/usr/share/fonts/JosefinSans-SemiBold.ttf');
                canvas.contextContainer.addFont(font);
```

The problem is this doesn't work on fabric 2.3.3 I just get the following error:

**canvas.Font is not a constructor**

Can someone help out as what to do here?

**Comment by ludbek** [comment]
Could you point me to the documentation you are referring to?

**Comment by AnnaHotsa** [comment]
Hi there! 

I had faced the same issue a couple weeks ago and I found another way of loading fonts into canvas.  
There is new canvas method `registerFont()` which works well. You can see the implementation details here-> [registerFont()](https://github.com/Automattic/node-canvas#registerfont)

Hope it was helpfull! ;)

**Comment by ludbek** [comment]
Yeah `registerFont` works. From your example code above I was under the impression that there is another way of doing it in `fabricjs`.
