### ISSUE TITLE
stretch image to given width/height non-proportional

### ISSUE THREAD

**Issue by kordix** [fabricjs/fabric.js#5602]
**Is your feature request related to a problem? Please describe.**
I know there was a breaking change in 2 version with height and width property for an image. Now we can use only scaleX and scaleY to stretch images (not scale them proportionally)

**Describe the solution you'd like**
It would be very nice to have something like width and height like in previous version, which works exactly like scaleX and scaleY but to given width **without proportions**. **It's not scaleToWidth and scaleToHeight.**

**Describe alternatives you've considered**
I can calculate the proportions and use scaleX and scaleY but it's quite irritating can't we have propierties which worked just like in previous version? We could call them e.g. scaleToWidthNP, scaleToHeightNP (non-proportional)

**Additional context**
I hope you understand, I can add codepen if you want

**Comment by asturur** [comment]
i understand.
But i do not find it irritating and there is no space for this kind of extra customization/effects.
I do not think the advantage is that much, you can write those methods and add them as functions to your projects.

scaleX and scaleY are the exact properties to use, and write a method that let you take a width in input and set the new scale is a matter of a division.
