### ISSUE TITLE
Setting rx and ry after creating rectangle no longer works

### ISSUE THREAD

**Issue by hags033** [fabricjs/fabric.js#5609]
## Version
2.7.0

## Test Case
https://jsfiddle.net/anshyan/5zsc2oos/11/

## Information about environment
Nodejs

## Steps to reproduce
If you set the rx and ry in the new Rect args it works. But if you do fabricObj.set('rx', newValue) there is no update.
## Expected Behavior
I would expect the rectangle to round the corners when fabricObj.set is used. 
## Actual Behavior
Nothing is updated. If you log the object, the rx and ry are correctly set in the fabric object, but it doesn't render those changes.

**Comment by asturur** [comment]
you based the fiddle on fabric 1.7.3
Current version is 2.7.0, and last from 1.x is 1.7.22

**Comment by ChenArno** [comment]
When I set 3 above, set works, if I set 0,1,2 it doesn't work
`
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <style type="text/css">
    #img {
      width: 200px;
      height: 200px;
    }

    canvas {
      border: 1px solid red;
    }
  </style>
</head>

<body>
  <script src="https://cdn.bootcss.com/fabric.js/3.4.0/fabric.js"></script>
  <canvas id="c" width="300" height="250"></canvas>
  <div id="big">big</div>
  <div id="small">small</div>
  <div id="value"></div>
  <script>
    const canvas = new fabric.Canvas('c')
    let size = 0

    const rect = new fabric.Rect({
      left: 10,
      top: 10,
      width: 100,
      height: 100,
      rx: size
    })

    rect.on('scaling', function () {
      this.set({
        width: this.width * this.scaleX,
        height: this.height * this.scaleY,
        scaleX: 1,
        scaleY: 1
      })
    })

    canvas.add(rect).renderAll()

    document.getElementById('big').onclick = () => {
      console.log(rect)
      rect.set('rx', size++)
      canvas.renderAll();
      update()
    }
    document.getElementById('small').onclick = () => {
      rect.set('rx', size--)
      canvas.renderAll();
      update()
    }
    function update() {
      document.getElementById('value').innerText = size
    }
    update()
  </script>
</body>
</html>`
