### ISSUE TITLE
How to clone object with all custom attrbute after canvas load from json in fabric js version 1.7.22

### ISSUE THREAD

**Issue by contact2mayurkukadiya** [fabricjs/fabric.js#5612]
I want to make group and ungroup existing object in to  canvas (not make clone of selected object and add into group, just add that existing object into group), but when, i group and ungroup object, my custom attributes are removed.

I am using fabric js version 1.7.22.

**Comment by aggrosoft** [comment]
Please provide a jsfiddle to show the behaviour

**Comment by contact2mayurkukadiya** [comment]
Here is the fiddle : https://jsfiddle.net/Mark_1998/e069hm3x/10/
Steps are written in fiddle.

**Comment by asturur** [comment]
sorry for the delay.

`var object = fabric.util.object.clone(element);` you should not clone objects like this.
You should use the async clone method provided by the object instances.

`Object.clone(callback, [...extraProperties])`
