### ISSUE TITLE
Lists of valid unquoted font names in fontFamily is not working

### ISSUE THREAD

**Issue by sflanker** [fabricjs/fabric.js#5613]
This used to work. It has gotten broken before, and fixed before:
https://github.com/fabricjs/fabric.js/issues/3261

It appears to have been broken again here: 
https://github.com/fabricjs/fabric.js/pull/4840

Given that fabric calls the property "FontFamily" and it takes only a string I think it is logical for the behavior to mirror that of web standards, which is to treat FontFamily as a list of identifiers or quoted strings. That means that if you want to use a font that contains a space or special character, or starts with a number, you need to quote it. I think automatically quoting the entire FontFamily string is misguided since it deviates from typical expectations based on the behavior of CSS, and it breaks applications that worked in earlier versions. Some alternatives that might solve the issue PR 4840 was addressing might be to check the string for commas before quoting it, or to support passing a list (i.e. `[ "Helvetica Nue", "Arial", "sans-serif" ]`) and only use the automatic quoting on the strings within this list (the default behavior when a string is specified should be to use the string as is).

## Version
2.7.0

## Test Case
Technically this works because the latest version of fabric.js supported by jsfiddle is 1.7.7
http://jsfiddle.net/sh8dg97x/

## Information about environment
Browser, Google Chrome 73

## Steps to reproduce
Create a Textbox with a fontFamily including multiple fonts separated by commas.

```javascript
 var txt = new fabric.Textbox("Foo Bar", {
        left: 100,
        top: 100,
        fill:  "#000000",
        width: 100,
        height: 100,
        fontSize: 14,
        fontFamily: "Arial, sans-serif"
    });

canvas.add(txt);
```

## Expected Behavior
The font of the text box should be the first available font in the list.

## Actual Behavior
The font of the Textbox is the default: Times New Roman

## Workaround
Explicitly quote each of the *non-generic* font names in the list. Annoyingly if you quote generic font names like `sans-serif` or `cursive` this won't work. This places an onerous burden on the consumer of Fabric.js to parse a font list, determine which names are generic, and quote the ones that aren't. Alternately it is possible to prefix any given valid font list with a random string that is guaranteed not to match a font: (i.e. `"'0770F049-5B7B-49C8-B714-14499F1DA12F', " + originalFontList).

```javascript
 var txt = new fabric.Textbox("Foo Bar", {
        left: 100,
        top: 100,
        fill:  "#000000",
        width: 100,
        height: 100,
        fontSize: 14,
        fontFamily: "'Arial', sans-serif"
    });

canvas.add(txt);
```

**Comment by sflanker** [comment]
broken example (v2.6.0)

```html
<html>
<head>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/2.6.0/fabric.js"></script>
</head>
<body>
<canvas id="c" width="300" height="300"></canvas>
<script>
var canvas  = new fabric.Canvas('c');

var txt = new fabric.Textbox("Foo bar",
  {
    left: 100,
    top: 100,
    fill:  "#000000",
    width: 100,
    height: 100,
    fontSize: 14,
    fontFamily: "Arial, sans-serif"
  }
);

canvas.add(txt);
</script>
</body>
</html>
```

**Comment by asturur** [comment]
Is `fontFamily: "Arial, sans-serif"` valid or should be:
`fontFamily: '"Arial", sans-serif'`.

I understand that font family should be quoted, or am i wrong?

**Comment by asturur** [comment]
No i m wrong. they have to be quoted if contains space or  numbers.
We will stop quoting if contains a coma. I think is the simplest thing we can do.

**Comment by asturur** [comment]
To be honest we  should quote if there is no quoting and there is some space or  start with numbers.

**Comment by sflanker** [comment]
Thank you @asturur for the speedy fix! Much appreciated.
