### ISSUE TITLE
removing background image

### ISSUE THREAD

**Issue by danrcoull** [fabricjs/fabric.js#5615]
seems impossible to remove the background image from a canvas once its set
with cors on every element, toDataUrl still throws a security exception

**Comment by aggrosoft** [comment]
Please provide a jsfiddle which shows the behaviour

**Comment by asturur** [comment]
@danrcoull i m going to close this since is unclear what are you asking.
Feel free to clarify i ll reopen the issue.
Add a jsfiddle to support your question/bug report.
