### ISSUE TITLE
Changing an Image b4 loadFromDatalessJson

### ISSUE THREAD

**Issue by Tsunami2069** [fabricjs/fabric.js#5618]
Hello.

First of all, my apologies, I do not know yet if this is really an issue or not.
Please allow me to explain my situation.

I'm developing a solution that is kinda of album maker. You can add your images, position them, etc. then we save it as a datalessjson to the server and then using another backoffice software to use that datalessjson, send it to a nodeJS Fabric to recreate it and generate the printable version.

Since we're talking about photographs take can have quite high quality and size and file weight, I've been using a system where I create compressed smaller versions of the images so that they're smaller and therefor lighter on the user's browser. Then, when you click the "generate the printable versions" sort of button, I replace the link from the compressed version of the image with the actual real high quality version of that image.

Now, this was working beautifuly before I upgraded to fabric v2+ (I had to upgrade for other reasons like for example needing the new clipping system, etc). Even though the images who, on the compressed side, were only for example, 800x600 pixels and then replaced with the, for example, 5000x4000 real sized version, the loadFromDatalessJson would still keep the full image in it's place.

After upgrading to the v2+, the new behaviour is that the loadFromDatalessJson with the real sizes images show a image that is as if it was zoomed in.
This is kinda hard to explain, so i'm going to attach a couple of screenshots of the wanted effect and what is happening.
The first will demonstrate how it is supposed to come out and the 2nd shows how it IS actually coming out and, as you can see, because i'm replacing the smaller version with the actual bigger version, only a portion of the image is showing (you can even see, for example, the kickboxers glove on the top right image).

Is this expected as a result of something that changed with v2+?
Am I possibly forgetting something?

Could you please, help me out as I am struggling to find a solution to this issue.

Thank you very much.

![Snip1](https://user-images.githubusercontent.com/14236716/55582059-6a8c7e00-5716-11e9-960d-a505c980c2aa.jpg)
![Snip2](https://user-images.githubusercontent.com/14236716/55582063-6ceed800-5716-11e9-9c23-8b3a71e77a4d.png)

**Comment by asturur** [comment]
```
http://fabricjs.com/v2-breaking-changes
```

There there is an example that explain how to change fabric.Image fromObject in order to mantain compatibility from 1 to 2.

**Comment by Tsunami2069** [comment]
@asturur 

Thank you very much for the reply.
The function I found on that link fixed the problem... HOWEVER, it only did for the normal images.

I have some images that could be cropped. And the images that ARE cropped, they get "squeezed".
It's like he's ignoring the cropX and cropY.

I'm attaching new screenshots to demonstrate what is intended and what is the result.
The first screenshot shows what is intended.
The image on the left is normal, no cropping whatsoever.
The image on the right is cropped, both from the left and the right, using cropX and changes to the width.

The 2nd screenshot is what I'm getting.
The image on the left is OK, as intended.
However, the image on the right is not cropped and comes out kinda squeezed in that place.

I've thought I need to adjust the math used on the function but, like I said, it seems that having a cropX and/or cropY doesn't do anything.

Could you help me with this?
Thank you very much in advance.

![Snip1](https://user-images.githubusercontent.com/14236716/56236500-a95cf500-6081-11e9-8422-cc1a0187ef8a.jpg)
![Snip2](https://user-images.githubusercontent.com/14236716/56236501-a95cf500-6081-11e9-9136-1338f1f2b29b.png)

**Comment by Tsunami2069** [comment]
@asturur 

An update to this question.
After fiddling with the function a bit more and trying out some things, I realized that not only I wasn't adjusting the object's width based on the new image's width (hence why it was being squeezed), I was also not adjusting the cropX and cropY using the same ratio.

That's why it seemed like the cropX and cropY weren't working, they were too small given the fact that the new image is considerably bigger.

So apparently, all is well. You can keep this issue closed.
Thank you once more for your time.
