### ISSUE TITLE
Rendering broken when using setViewportTransform to flip y-axis 

### ISSUE THREAD

**Issue by niiyeboah** [fabricjs/fabric.js#5619]
## Description
In our project, we are converting complex image objects that use a different coordinate system ([0,0] = bottom left) into fabric.js objects. We tried to use `setViewportTransform` with a negative value on the scale y in order to achieve this.

I am aware of [this](https://github.com/fabricjs/fabric.js/issues/4971) similar issue where the resolution was that there is an open feature request for custom viewport transformations but I could not find the feature request and could not find any updates on this problem.

## Version
2.7.0

## Test Case
http://jsfiddle.net/niiyeboah/ry4Lqn3f/

## Steps to reproduce
1. Start fiddle
2. Drag path object around

## Expected Behavior
The path object should always be visible

## Actual Behavior
The path sometimes disappears when dragged to certain points

**Comment by asturur** [comment]
flipped viewport transform, as long as rotated viewport is not supported or viewport with different scaling of X,Y.
Shoulbn't be hard to support it tho.
It could be just a matter of fixing controls and getZoom functionality
