### ISSUE TITLE
the problem of fabric.Path component 

### ISSUE THREAD

**Issue by itubiaoge** [fabricjs/fabric.js#5621]
## Version
2.7.0

hi, I came again ^_^, recently I am developing the pen tool with fabric , then I found that the path component is a bit problem, the d value is the same in svg and the strokeWidth is different, the path will remain centered, but in fabric, the same path value Different strokewidths behave strangely. See the example for details. Is this a bug or is there any other solution?

## Test Case
in fabric
https://jsfiddle.net/jrLqdnyh/

in svg, I think this is correct
https://jsfiddle.net/p03j9Lun/

**Comment by asturur** [comment]
there is no 1:1 similarity between SVG and canvas or FabricJS.
Try to use  originX and originY set to `center` this could help.

**Comment by itubiaoge** [comment]
very good, thank you
