### ISSUE TITLE
PencilBrush does not trigger when moving less than 10 pixels in touch devices

### ISSUE THREAD

**Issue by yanxlg** [fabricjs/fabric.js#5625]
## Version
2.7.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
browser：Chrome@latest

## Expected Behavior
when we move less than 10 pixels in touch devices,fabricjs does not dispatch mouseMove or touchMove event,it is a problem of touch events,but when changed to pointerEvents,it will does well.so fabricjs must support pointerEvents to make it accurately！

**Comment by asturur** [comment]
you are welcome to open a pr, write tests, check compatibility with browsers and mantain compatibility with ie10+

**Comment by arcatdmz** [comment]
@yanxlg Given that my PR #5589 was merged, using the master branch, you could pass `enablePointerEvents: true` to utilize `PointerEvent` rather than `TouchEvent`.
