### ISSUE TITLE
Fabric 2.7.0 still points to jsdom ^9.12.0

### ISSUE THREAD

**Issue by ludbek** [fabricjs/fabric.js#5628]
## Version
2.7.0

## Information about environment
Nodejs

## Steps to reproduce
npm install fabric

## Expected Behavior
Should have installed `jsdom` 13.1.0.

## Actual Behavior
Install `jsdom` ^9.12.0 instead.

**Comment by asturur** [comment]
jsdom 13 or higher is for the fabricjs 3 release.
2.7.0 still uses 9.12

**Comment by ludbek** [comment]
fabricjs 3 is on the horizon? sweet

Just curious why the package.json file in master branch following values
```javascript
...
"version": "2.7.0",
...
  "optionalDependencies": {
    "canvas": "^2.3.0",
    "jsdom": "13.1.0"
  },
...

```

**Comment by asturur** [comment]
because i did not bump version yet.
Main change of fabric 3 is node 4 and 6 deprecation and update to jsdom 13 or 14 and node-canvas 2
