### ISSUE TITLE
checkboxes using fabric.js not working

### ISSUE THREAD

**Issue by CIE81** [fabricjs/fabric.js#5630]
Hi,

We've implemented checkboxes using fabric.js and everything worked fine until I've uplifted fabrichs to the current version, and  the checkbox click started to behave weird.

Looking at fabric code, I've noticed a change in onMouseUp that might have cause the behavior we've experience.

In fabric.js line 13731

      if (!isClick) {
        this._maybeGroupObjects(e);
        shouldRender || (shouldRender = this._shouldRender(target));
      }

Why is the following line going to execute only if isClick is false ?

 shouldRender || (shouldRender = this._shouldRender(target)); 

Thank you,
Ioan

**Comment by asturur** [comment]
Because we want to render as less as possible. If you have an onClickEvent in your subclass you can actually render from there.

**Comment by CIE81** [comment]
We are drawing the check on the onMouseUp event. What method do you suggest to invoke, fabric render ?

**Comment by asturur** [comment]
something like `checkbox.on('mouseup', function() { this.canvas.requestRenderAll() });`
Shouldn't it work?

**Comment by CIE81** [comment]
Ok, I will give it a try. 

Thank you,
Ioan
