### ISSUE TITLE
Weird selectarea behavior when requestAnimFrame after canvas resize

### ISSUE THREAD

**Issue by luhof** [fabricjs/fabric.js#5631]
## Version
2.7.0

## Test Case
https://jsfiddle.net/luhof/2hfr80t3/9/

## Information about environment
Chrome browser, angular7 application

## Steps to reproduce

1 - Create a new fabric object in a canvas
2 - Use the fabric.util.requestAnimFrame with a renderAll() or requestRenderAll() inside
3 - Resize the canvas using setWidth/setHeight or even setDimensions()
(steps 2 and 3 order doesn't matter)

The requestanimframe is needed for videos, and since my canvas has to be responsive, I need to resize it often.

## Expected Behavior

Simple loop that let my videos object run inside fabricjs 

## Actual Behavior

The selector has a weird behavior where if you click->drag->stop moving (but click button still pressed), the select box will be more opaque, looks like there are two select boxes overlapping ?

## More

I hope I given enough informations and that my jsfiddle is clear enough ! Please tell me if anything is needed.

**Comment by durga598** [comment]
Just call `requestRenderAll` method inside loop to render, you no need to use `fabric.util.requestAnimFrame`.

**Comment by asturur** [comment]
i need to try the fiddle. there could be a strange case where we end up rendering twice the top canvas without clearing?

**Comment by durga598** [comment]
@asturur, [hasLostContext](https://github.com/fabricjs/fabric.js/blob/765f11537b5002ffe5b556f47ccccbfb8428d022/src/canvas.class.js#L392) always set to true in [here](https://github.com/fabricjs/fabric.js/blob/765f11537b5002ffe5b556f47ccccbfb8428d022/src/static_canvas.class.js#L632). May be this gives the problem.
