### ISSUE TITLE
isTargetTransparent(target, x, y)

### ISSUE THREAD

**Issue by damelco** [fabricjs/fabric.js#5635]
I am attempting to autocrop the canvas of bordering transparent pixels ... it would seem I might use this function to test pixels ... but I am either not understanding its use or something? can I use it for that, or is it a [sub]function of corner marker routine only?

TypeError: t.shouldCache is not a function --- fabric.min.js:1:93352

anyone see a reason for this appearing in the console when this function is accessed?

thanks in advance.

-DJ

**Comment by asturur** [comment]
How are you using the function? target should be a fabric.Object derivate.

**Comment by damelco** [comment]
ah ... I see now ... I had pushed the object's 'data' into the function, thinking that was necessary to prevent the script timeout I was observing.

if I use 'just' the object (not its data), it does work (it times out the browser in a loop, but it does work) ... apparently isTargetTransparent too 'fat' to use in a loop iteration. 

it was probably conceived to check a single pixel only, not used to iterate through an entire image?

Thank you though for your time! ... I'll simply need to settle for my slow but functional routine.

-DJ

**Comment by asturur** [comment]
yes the function is used for one pixel per event.

You can build a function that acts on the cacheCanvas and cycle over that one to know if a pixel is transparent. It will be slow anyway, but you can make it as effective as possible.

**Comment by damelco** [comment]
I had built a function using native html5/canvas methods to check the border rows/columns progressively for a non-transparent pixel ... then crop to that/those new borders
that routine could take a couple seconds on large images ...
I though perhaps fabricjs might do such a process quicker, and that function seemed worthy?!

thanks again for your time and input.

-DJ

**Comment by asturur** [comment]
you can write a webgl filter to do so.

**Comment by damelco** [comment]
though that 'sounds' interesting ... I probably don't have the skill-set to figure that out. it has taken me a year to understand fabricjs to this point!   ;^)

is there any sites that you are aware of that may have some information regarding creating/implementing webgl filters?

thank you 

-DJ

**Comment by asturur** [comment]
you should check one of the fabricjs filter here. I would start from a filter that assumes all row/columns are transparent and then flag away the one that are not.
i have no idea how you can then export that from the webgl space, but i believe it can be done somehow.
