### ISSUE TITLE
Image got blurred when using clipPath

### ISSUE THREAD

**Issue by TsuchiyaMasahiro** [fabricjs/fabric.js#5639]
## Version
2.7.0

## Test Case
https://jsbin.com/kenibew/edit?html,js,output

## Information about environment
browser
Chrome and mobile Safari

## Steps to reproduce
When I use "clipPath", the clipped image becomes blurred.
It is particulary noticeable in iPhone Safari.
![Image of result](https://stg.bookrator.com/img/test/compare.png)

The top image is generated simply by fabric.Image,
and the bottom image is generated by fabric.Image with clipPath.
(see [https://jsbin.com/kenibew/edit?html,js,output](https://jsbin.com/kenibew/edit?html,js,output) )

I thought it was related to ”enableRetinaScaling”, but there was no relationship.

Can I solve this problem ?

Thank you in advance.

## Expected Behavior
There is no difference whether I use clipPath or not.

**Comment by leesc81** [comment]
I have the same problem...

clipPath = null; will restore image quality again.
Applying clipPath lowers the image quality.
I hope this issue is resolved.

**Comment by leesc81** [comment]
Is this a problem related with ctx.imageSmoothingEnabled?

**Comment by TsuchiyaMasahiro** [comment]
Maybe, I can solve the problem !
I only added ''objectCaching: false" to the fabric.Image.

There is no difference between original image and clipped image.

See below in iPhone.
https://jsbin.com/jeqohew/edit?html,js,output

**Comment by TsuchiyaMasahiro** [comment]
If I set 'objectCaching: false', there is another ploblem.

If there is already an object in the canvas,
I can add an object which has a 'clipPath' parameter to the canvas if the object does not have 'objectCaching: false'.

see [https://jsfiddle.net/uemon/2aswLyon/2/](https://jsfiddle.net/uemon/2aswLyon/2/)

But, If the object has 'clipPath' parameter and 'objectCaching: false' parameter, the existed object was disappeared.

see [https://jsfiddle.net/uemon/gm68wfte/1/](https://jsfiddle.net/uemon/gm68wfte/1/).

That is, if I set 'clipPath' and 'objectCaching: false' to an object, I can not add the  object to the canvas if there are other objects in the canvas. 

I want to use 'objectCaching: false' to keep image quality,
what should I do ?

Please give me some advice.

Thank you in advaice.

**Comment by TsuchiyaMasahiro** [comment]
I see https://github.com/fabricjs/fabric.js/issues/5510

**Comment by TsuchiyaMasahiro** [comment]
Sorry, I have closed this issue without asking.

**Comment by leesc81** [comment]
@TsuchiyaMasahiro  Did you find a solution?
What was the cause?
I can not solve the problem by applying objectCaching to clippath ...
Could you update the successful fiddle?

**Comment by leesc81** [comment]
https://jsfiddle.net/SooChangLee/xtfm8pos/

Hi.
Image quality is important because I will use the final result for printing.

If apply clippath to an image, the image looks a bit blurry.
(Image selection, dragging works fine)

If objectCaching is set to false for images, the image quality is fine.
But, when one image is selected, the other image disappears.

I reproduced the both cases in jsfiddle.

I tried to specify several properties of the target image, but I failed to get clear picture quality and accurate control.

Is it impossible to use objectCaching = false with clipPath?
Or am I misused?

Please help me.

**Comment by TsuchiyaMasahiro** [comment]
@leesc81
In [#5510](https://github.com/fabricjs/fabric.js/issues/5510), Oro said that "ClipPath REQUIRES object caching",
and asturur said that "I changed the major version to 3 and object caching will not disable caching".

So, the best way is to wait the major version 3 of fabricjs.
I am anxious for the Ver.3, too.

In my case, I created a hidden canvas which has "display:hidden" in css in addition to a normal canvas, and if an object has a "clipPath" property, I change the object into a picture clipped by the clipping object in the hidden canvas before I use "toDataURL" or add another object.
In this method, I manage to avoid the degradation of the image quality.

But as said before, I think the best way is wait the Ver.3.

**Comment by leesc81** [comment]
@TsuchiyaMasahiro 
Thank you for your response.
I am sad that I can not use ClipPath and ObjectCaching = false together ...
Image quality is important for printing ...

@asturur 
When you plan to release version3? Does it take a lot of time?

**Comment by asturur** [comment]
So version 3 could be released but i did not manage to fix the clipPath scaling issue.
I m looking at the fiddle now to see if i understand the problem. i think i do.

So if you fully read here:
http://fabricjs.com/fabric-object-caching

is explained that the cache of the objects has some size limit for performances.

Now there are 2 solutions here:
- enlarge the limits as i did in the fiddle
- if you need to clip with rects, try using the embedded cropping functionalities

https://jsfiddle.net/uxho784t/1/

using crop gives you 0 blur ( with rects! ) but does give you any embedded interactivity, you have to build it yourself.

**Comment by leesc81** [comment]
Thank you for pointing out the problem.
I use rect, polygon, and path as clip paths.
I have found that the problem is improved when the perfLimitSizeTotal value is increased.
I lacked an understanding of the properties relative with objectCaching.
This time seems to be a valuable time.
Thank you for providing us good library and for your support.
Thank you

**Comment by asturur** [comment]
we don't have one yet.
We have some slight improvement in an open PR but is not complete

**Comment by jiang-bx** [comment]
> Sorry for the delay, full days for me.
> 
> So version 3 could be released but i did not manage to fix the clipPath scaling issue. I m looking at the fiddle now to see if i understand the problem. i think i do.
> 
> So if you fully read here: http://fabricjs.com/fabric-object-caching
> 
> is explained that the cache of the objects has some size limit for performances.
> 
> Now there are 2 solutions here:
> 
> * enlarge the limits as i did in the fiddle
> * if you need to clip with rects, try using the embedded cropping functionalities
> 
> https://jsfiddle.net/uxho784t/1/
> 
> using crop gives you 0 blur ( with rects! ) but does give you any embedded interactivity, you have to build it yourself.

@asturur Thank you for your solution, which solved a difficult problem for me

**Comment by nimil-official** [comment]
@asturur Hi Again,
I dont know what I am doing wrong, I am unable to restore the quality. I tried disabling cache, enlarge the limits as you did in the fidle, still the same result. Able to restore it once clipPath is set to null
Thanks in advance. I am using fabric 4.6.0
![testwithClipping
![testWithoutClipping](https://user-images.githubusercontent.com/77372692/157602405-91c3c12b-4df8-4f87-8d49-a81f92f8d5b7.PNG)
](https://user-images.githubusercontent.com/77372692/157602370-fd4480c9-9b33-4896-b777-527869bce37c.PNG)

**Comment by viktor-silakov** [comment]
I have the same problem in v5.2.4 the cache is off via:             
`fabric.Object.prototype.objectCaching = false;`
Before clipping via rectangle:
<img width="867" alt="image" src="https://user-images.githubusercontent.com/23633060/201074761-a121eacf-635e-4441-9330-78a1c22d552c.png">
After:
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/23633060/201074884-da6c342a-8531-4011-bb26-ca09054350ae.png">

**Comment by m20io** [comment]
The newer version decides with [`fabric.Object.shouldCache`](http://fabricjs.com/docs/fabric.Object.html#shouldCache), which relies on [`fabric.Object.needsItsOwnCache`](http://fabricjs.com/docs/fabric.Object.html#needsItsOwnCache) method.

I'm using fabric with node-canvas, so I want to avoid caching. You can overwrite this method:

```javascript
fabric.Object.prototype.needsItsOwnCache = () => false
```

I just wanted to let you know that this worked for me. It may help.

**Comment by asturur** [comment]
The issue with that is that your clipPath will erase all the canvas then. clipPath requires caching because it requires drawing isolation.

**Comment by m20io** [comment]
I'm pretty sure I'm missing something, but it seems to work for me. Here is a fiddle https://jsfiddle.net/z2ao8srj/4/ with this.

**Comment by asturur** [comment]
> The newer version decides with [`fabric.Object.shouldCache`](http://fabricjs.com/docs/fabric.Object.html#shouldCache), which relies on [`fabric.Object.needsItsOwnCache`](http://fabricjs.com/docs/fabric.Object.html#needsItsOwnCache) method.
> 
> I'm using fabric with node-canvas, so I want to avoid caching. You can overwrite this method:
> 
> ```js
> fabric.Object.prototype.needsItsOwnCache = () => false
> ```
> 
> I just wanted to let you know that this worked for me. It may help.

Well then I may be missing something.
a clipPath that doesn't cache should delete whatever was painted before on the canvas, and is not a feature.

**Comment by asturur** [comment]
Oh it is because you are using absolutePositioned.
If you don't the bug i described happens.

**Comment by milansimek** [comment]
> > The newer version decides with [`fabric.Object.shouldCache`](http://fabricjs.com/docs/fabric.Object.html#shouldCache), which relies on [`fabric.Object.needsItsOwnCache`](http://fabricjs.com/docs/fabric.Object.html#needsItsOwnCache) method.
> > I'm using fabric with node-canvas, so I want to avoid caching. You can overwrite this method:
> > ```js
> > fabric.Object.prototype.needsItsOwnCache = () => false
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I just wanted to let you know that this worked for me. It may help.
> 
> Well then I may be missing something. a clipPath that doesn't cache should delete whatever was painted before on the canvas, and is not a feature.

@asturur For me that solution also didn't work (using absolute position). 

The fix I mentioned here does work fine though: https://github.com/fabricjs/fabric.js/issues/5639#issuecomment-1819073793

**Comment by ab-etemadi** [comment]
> Found a solution which works well in my case:
> 
> fabric.StaticCanvas.prototype.enableRetinaScaling = true;
> 
> const originalRetina = fabric.StaticCanvas.prototype.getRetinaScaling();
> 
> fabric.StaticCanvas.prototype.getRetinaScaling = function() {
>      return originalRetina * 4;
> }
> This will increase the cached (and non-cached) canvas size by a factor of 4, which fixes the blurring issue.

Thanks! This approach works for me and fixes the image blur. However, it prevents me from moving objects on the canvas, so I can't use it. Do you have any suggestions?

**Comment by asturur** [comment]
Clippath blurriness has been fix in fabric 6.x

**Comment by mshndev** [comment]
> Clippath blurriness has been fix in fabric 6.x

Hello, it seems that I still have this issue with fabric 6.7.0. When I zoom the canvas the clipped path has blurred edges:
<img width="570" alt="Image" src="https://github.com/user-attachments/assets/f1d86a94-a107-46b1-9296-c0649d86af95" />

[https://jsfiddle.net/b7981f46/2/](https://jsfiddle.net/b7981f46/2/)

```typescript


const width  = 300;
const height = 200;
const overlayMargin = 200;

const frame = new fabric.Rect({
  left: 0,
  top: 0,
  width,
  height,
  fill: '#f00',
  selectable: false,
  objectCaching: false,
});

const overlayBg = new fabric.Rect({
  width:  width  + overlayMargin * 2,
  height: height + overlayMargin * 2,
  fill: '#000',
  opacity: 0.5,
  selectable: false,
  objectCaching: false,
});

// “hole” in the middle
const mask = new fabric.Rect({
  left: 0, top: 0, width, height,
  absolutePositioned: true,
  objectCaching: false,
});

const overlay = new fabric.Group([overlayBg], {
  left: -overlayMargin,
  top: -overlayMargin,
  selectable: false,
  objectCaching: false,
});

overlay.clipPath = mask;
overlay.clipPath.inverted = true;

const crispRect = new fabric.Rect({
  left: -10,
  top: -10,
  width: 50,
  height: 50,
  rx: 10,
  ry: 10,
  fill: '#00f',
  objectCaching: false,
});

canvasAPI.add(frame);
canvasAPI.add(crispRect);
canvasAPI.add(overlay);
```

I tried with `globalCompositeOperation: "destination-out"` for the mask with `overlay.needsItsOwnCache = () => true` for the group, but the result is the same. Setting `overlay.needsItsOwnCache = () => false` throws an `Error: Cannot read properties of undefined (reading 'forEach')` somewhere in `canvasAPI.renderAll`. 

Is there a  way to keep clipPath edges sharp when the canvas is zoomed?

**Comment by asturur** [comment]
What happen if you don't use the group?

**Comment by mshndev** [comment]
> What happen if you don't use the group?

Exactly the same blurred edge.

And I just faced with another issue: if I add an object with shadow and offsetY > 0 to this masked group, it trows an `Error: Cannot read properties of undefined (reading 'forEach')`. Shadow with offsetY: 0 renders fine (no crash, still blurry edge)

**Comment by asturur** [comment]
ok that is an actual bug, can you open a bug issue with the shadow and a reproduction ? that needs to be fixed

**Comment by asturur** [comment]
this can stay open for the blurriness
