### ISSUE TITLE
canvas background problem  when loadFromJSON image object canvas background 

### ISSUE THREAD

**Issue by ShahramCodeDeveloper** [fabricjs/fabric.js#5640]
## Version
2.7.0

## Test Case
jsfiddle: http://jsfiddle.net/ShahramCodeDeveloper/bcm3q42p/9/
codpen: https://codepen.io/ShahramCodeDeveloper/pen/YMexzB
## Information about environment
Nodejs or browser?
browser

Which browsers?
all browser

## Steps to reproduce
Set a background for canvas and then call a image type with the loadFromJSON() function

## Expected Behavior
The background disappears
http://uupload.ir/files/mtlw_0.png
## Actual Behavior
Behind the background should stay and the image should be displayed
http://uupload.ir/files/wbu0_1.png

**Comment by asturur** [comment]
i cannot see the code in the fiddle, i see just the result tab. can you post a working link?

**Comment by ShahramCodeDeveloper** [comment]
hello
thanks for reply me.

jsfiddle new link: http://jsfiddle.net/ShahramCodeDeveloper/bcm3q42p/9/

codepen link: https://codepen.io/ShahramCodeDeveloper/pen/YMexzB

**Comment by durga598** [comment]
[loadfromjson](http://fabricjs.com/docs/fabric.Canvas.html#loadFromJSON) will clear the canvas, and populate the data from specified json. You need to use [fabric.util.enlivenObjects](http://fabricjs.com/docs/fabric.util.html#.enlivenObjects) to load fabricjs objects from json.
Here is [jsfiddle](http://jsfiddle.net/durga598/av2gscbe/).

**Comment by ShahramCodeDeveloper** [comment]
> 
> 
> [loadfromjson](http://fabricjs.com/docs/fabric.Canvas.html#loadFromJSON) will clear the canvas, and populate the data from specified json. You need to use [fabric.util.enlivenObjects](http://fabricjs.com/docs/fabric.util.html#.enlivenObjects) to load fabricjs objects from json.
> Here is [jsfiddle](http://jsfiddle.net/durga598/av2gscbe/).

Thanks for the answer, my problem has been resolved

**Comment by asturur** [comment]
thanks @durga598
