### ISSUE TITLE
Remove padding between required image and bounding box

### ISSUE THREAD

**Issue by vxrai** [fabricjs/fabric.js#5643]
![GEBpQ](https://user-images.githubusercontent.com/7886890/56376638-098c9c00-6226-11e9-83d1-003d22244bac.png)

I want to remove the space between the product and the bounding box using fabricjs

Here is the stack-overflow link for the context - https://stackoverflow.com/questions/12175991/crop-image-white-space-automatically-using-jquery

**Comment by vxrai** [comment]
@kangax is it possible to remove the padding - the white space between the bounding box and the actual image that we require?

**Comment by asturur** [comment]
You can detect the extra white as suggested in that answer.
Instead of generating a new image you can use fabricJS cropX, cropY, width and height property to show just the portion of the image you are interested in.

**Comment by asturur** [comment]
Issue is closed since there are no action items for me, we can keep talking.
