### ISSUE TITLE
Scaling of text does not work as expected.

### ISSUE THREAD

**Issue by ludbek** [fabricjs/fabric.js#5646]
Scaling of text does not work at `node`.

## Version
2.7.0

## Information about environment
Nodejs = 8.10
canvas = 2.4.1
jsdom = 13.1.0

## Expected Behavior
The expected behavior is the enlarged version of the image below.

![expected](https://user-images.githubusercontent.com/8296449/56543072-b747d400-65b3-11e9-8abe-e768228fca7f.png)

## Actual Behavior
![actual](https://user-images.githubusercontent.com/8296449/56542999-7c45a080-65b3-11e9-8318-6e23bc3f1224.png)

Update
---------
The white background of the text seems to scale right. Its just the text thats having the problem.

**Comment by asturur** [comment]
hi @ludbek we need an index.js file that can run under node easily.
Can you provide it?

i would suggest meanwhile to pull down the latest master code, and try. That has latest node-canva integration and could work better.

**Comment by ludbek** [comment]
I tried the `setZoom` method and it seems to work. The problem is I can't zoom by the factor of  3 and beyond. If I do so the bottom image just disappears. No clue.

![scale3](https://user-images.githubusercontent.com/8296449/56876493-11043e80-6a8b-11e9-8997-8a071da3c094.jpg)
