### ISSUE TITLE
Svg Parsing problem

### ISSUE THREAD

**Issue by lone1yyy** [fabricjs/fabric.js#5647]
**Version**
2.7.0

**Expected Behavior**

Hi guys, i'm having a issue with the svg parsing in my project. i was tring to add a svg on fabric.js like this https://codepen.io/anon/pen/oOPgXz

i was expecting a svg image with correct coordinate of rect in svg, the border is just for  emphasizing the coordinate

![理想](https://user-images.githubusercontent.com/43112039/56550430-350dde80-65b8-11e9-9d3a-0c4d9f3da4f5.png)

**Actual Behavior**

however, the actual image i get below seemingly does not parse the real size of svg and the coordinate of interior rect, it's just a full rect

![实际](https://user-images.githubusercontent.com/43112039/56550448-42c36400-65b8-11e9-8dfa-214cfca3b6b4.png)

i'm new to fabric.js and i'm not sure that if this is a bug or improvement, any reason for this ?

Thank you for your help.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/56847577-0146f780-68dd-11e9-9c93-6698958be507.png)

if you remove your scaling code, what you get is this picture.
the svg is 80x80, has a rect big 40 positioned at 20.
And that is exactly what i see.

Why did you expect something else?

**Comment by asturur** [comment]
(i'll close the issue, since the handling is started, please feel free to continue posting i'll get notified )

**Comment by lone1yyy** [comment]
> ![image](https://user-images.githubusercontent.com/1194048/56847577-0146f780-68dd-11e9-9c93-6698958be507.png)
> 
> if you remove your scaling code, what you get is this picture.
> the svg is 80x80, has a rect big 40 positioned at 20.
> And that is exactly what i see.
> 
> Why did you expect something else?

Thanks for your reply, I may not have described it clearly.  You can see the difference clearly from two pictrues below, i have to add another element in svg to make the rect stay at right positon. here is the example https://codepen.io/anon/pen/QPYZaV
![理想](https://user-images.githubusercontent.com/43112039/56847908-a204d980-6914-11e9-9dd1-6786ff754247.png)
![现实](https://user-images.githubusercontent.com/43112039/56847909-a204d980-6914-11e9-8129-8cc1849c3469.png)

**Comment by asturur** [comment]
oh no that does not work like that.
Groups are always built with the parsed object bounding boxes.
The SVG exact position is not respected if the object is just one, becuase the single object gets positioned on the canvas at the correct 20,20 but there is no group that is gonna keep that in the center. If you want an effect like that you can in your callback function you can create a rect that has just width/height as big as the width/height you find in the options argument, set strokeWidth as 0. That rect will represent the area of the SVG. make it transparent too.

then you can group `newObjects = [rect].concat(objects)`
