### ISSUE TITLE
Dynamic patterns are scaled by a factor of 2 and blurry on unscaled object

### ISSUE THREAD

**Issue by sflanker** [fabricjs/fabric.js#5648]
## Version
2.7.0

## Test Case
https://jsfiddle.net/3w7t9mdr/1/

## Information about environment
Chrome 73.0.3683.103

## Steps to reproduce
1. Create a repeating pattern of lines using a call to canvas.getElement
1. Apply the pattern as the fill of a polygon

## Expected Behavior
The lines rendered as a pattern should be the width specified when they were drawn on the source canvas and the should be sharp.

## Actual Behavior
The lines rendered as a pattern are twice as wide as expected and blurry.

**Comment by sflanker** [comment]
Here is a blown up bitmap of what gets rendered. I am expecting the red lines filling the polygon to be the same width as the red line on the left.

<img width="360" alt="Screen Shot 2019-04-23 at 12 17 36 PM" src="https://user-images.githubusercontent.com/940246/56620079-5922ed00-65c3-11e9-8506-a118679f9f46.png">

**Comment by asturur** [comment]
Hi @sflanker, sorry for the delay, full days for me.

https://jsfiddle.net/us6nkady/

`new StaticCanvas(null, { enableRetinaScaling: false });`

I'm not sure is clearly state in the docs, probably not clearly enough.
Is better to create dinamic patterns with retina scaling disabled in the canvas, or who has devices with higher dpi scaling will find the exact same issue.

Are you on a macbook or on a hidpi device?

**Comment by asturur** [comment]
Said so the current pattern api is not really the best for me, i would rather be able to define a pattern as standard fabricjs objects or group of objects, but i m far from rewriting it.
