### ISSUE TITLE
Replacing an image using setSrc and keeping the image dimensions same

### ISSUE THREAD

**Issue by rathorer** [fabricjs/fabric.js#5650]
Here is my scenario:
1. On Canvas I load say 100 images, of 200 x W size.  At initial load I am scaling both width and height to 100.
2. On "mouse:wheel" event, I am zooming the canvas using zoomToPoint method.
3. If zoom exceeds certain level say 5, I try to load higher resolution images by doing setSrc of only onScreen images.
4. If zoom increases further say 8, try to load even higher resolution images using same setSrc and so on.

And when I replace the images with higher resolution image, I want keep its dimensions same (width height, top, left etc.) The problem I am facing is, while doing setSrc, for multiple images on zooming, there is flickering happening on canvas. And this flickering doesn't go no matter whatever property I set in setSrc callback.

Created a JsFiddle, but as of now it has only 2 sizes (in my actual code i have 5-6 sizes of images) of the images. So flickering issue appears after doing multiple zoom-in and zoom-out (using mouse-wheel, and at the point where the image get replaced, which is zoom 5).

[Js fiddle](https://jsfiddle.net/rahulr/Lp1n6g3f/)

In the same lines I also wanted to understand, in fabric.Image object, which property does have the height/width, or scaledHeight/scaledWidth or zoomedHeight/zoomedWidth of initial image which is scaled and zoomed (which was rendered on canvas i.e. 200 X W with scaleToHeight of 100). And if I do zoomToPoint, what properties of  the fabric.Image object gets change, I couldn't find any.

**Comment by asturur** [comment]
I tried to fix the fiddle, i could not find a quick way.
Anyway in each imageObject, if you did not use any cropX,cropY:
width/height are the size of image element and then there is the scale factor.
In theory when the element change, and so change width and height, you should multiply your current scale factor by oldWidth/newWidth for example. This would keep the image the same size.

**Comment by surajwaghmare** [comment]
Hi @asturur ,
I'm also facing same issue in my application and I tried your above suggestions at my end but scaleX and scaleY value changes when I zoom-in or zoom-out on the image and due to this the flicker issue occurred. 
@rathorer : from your fiddle I observed following things.
![canvaspoc1](https://user-images.githubusercontent.com/5966352/56911078-b3dbad80-6ac9-11e9-9e35-9aa991f9f81b.JPG)

in above screenshot the white-space occurred due to scaleX and scaleY value changes. please see below screenshot for more details.
![canvaspoc3](https://user-images.githubusercontent.com/5966352/56911211-087f2880-6aca-11e9-9cda-6973938aae8c.JPG)

**Comment by rathorer** [comment]
@asturur, Thanks for the response. 
I have tried the scale-factor for width, height, but it doesn't help:

````
 function changeSrc(newSrc, imageObject, currentZoom) {
         var url = newSrc;
         var scaleX = imageObject.scaleX;
          var scaleY = imageObject.scaleY;
          var left = imageObject.left;
          var top = imageObject.top;
        imageObject.setSrc(url, function (image) {
             image.left = left;
             image.top = top;
             image.scaleToHeight(SCALE_FACTOR * currentZoom);
             image.scaleToWidth(SCALE_FACTOR * currentZoom);
             image.setCoords(true);
            canvas.requestRenderAll();
        }, { width: imageObject.width, height: imageObject.height });
    }
````
Where SCALE_FACTOR is constant, and has the value with which initial images are scaled. currentZoom is simply the same number we pass to zoomToPoint method.
Actually, I couldn't find any property of image object which changes with zoomToPoint function.

**Comment by rathorer** [comment]
I even tried to set width and height of new object like this:
`width = imageObject.width * imageObject.scaleX * currentZoom;`
`height = imageObject.height * imageObject.scaleY * currentZoom;`

**Comment by asturur** [comment]
when you zoom, nothing about the image change.
The image width/height/scaleX/scaleY/left/top are stable.

oldImage.width * oldImage.scaleX = newImage.width * newImage.scaleX

top and left should not change either.
If something does not work as you want it means that the new image does not have the same aspect ratio of the old image you are trying to swap.

I'm closing the issue, but please feel free to ask, if i have time i can answer
