### ISSUE TITLE
affectStroke fails if cache enabled;

### ISSUE THREAD

**Issue by tonycaso** [fabricjs/fabric.js#5659]
## Version
2.4.1

## Test Case
http://jsfiddle.net/tonycaso/7kx6a2op/17/

## Information about environment
chrome

## Steps to reproduce
affectStroke fails if cache enabled;
## Actual Behavior
affectStroke fails if cache enabled;

**Comment by asturur** [comment]
Affect stroke is not supposed to be used with colored fills.
Best shadow effect is when cache is on, when cache is off use affectStroke only if fill is transparent.

Otherwise you get 2 shadow for 2 drawing operations.
