### ISSUE TITLE
obj.selectable = false; and 'mouse:down' event.target is undefined

### ISSUE THREAD

**Issue by sn3p** [fabricjs/fabric.js#566]
On my canvas I have an object with `selectable = false`.
But I still want to retrieve the object when it's clicked. Is there any way to do this?

As you can see in this [jsfiddle](http://jsfiddle.net/sn3p/sBGH6/) the canvas mouse:down event.target is undefined.

**Possible related issues/threads:**
https://github.com/kangax/fabric.js/issues/482
https://groups.google.com/forum/?fromgroups=#!topic/fabricjs/o04ufPJ_8p8
https://groups.google.com/forum/?fromgroups=#!topic/fabricjs/XJgj8fKwtYc

**Comment by sopheaksem1993** [comment]
@kangax 
Did you enable the unselectable object to fire events again?

**Comment by SergiiMarkin** [comment]
@kangax 
To support event fire with unselectable object, do I have to downgrade to version 1.2.0?
If you have a good solution for the latest version, please help me.

**Comment by asturur** [comment]
unselectable objects do fire events, they can't be selected.
To do not fire events, you can set an object as `evented: false`.
Isn't exactly clear what both of you are looking for

**Comment by SergiiMarkin** [comment]
@asturur , Thanks for your quick response.

I would like to achieve following things

1. Set object (image object) to 'selectable: false'.
2. Support Unselectable object of event fire to catch 'mouse:up' or 'mouse:down' event

Here is code snippet.

```
- Define Image object

      fabric.Image.fromURL(imageUri, (img) => {           
                const fbImg = img.set({
                  ...
                  selectable: false
                });
                fbImg.setControlVisible('mtr', false);
                canvas.add(fbImg);
                canvas.sendToBack(fbImg);
      });

- Listen mouse:up event on canvas, and print undefined when catching 'mouse:up' event by clicking on unselectable image.

     canvas.on('mouse:up', (e) => {
           console.log('event target', e.target) // log undefined when triggering 'mouse:up' event by clicking on unselectable image on canvas.
      })
```

Thanks in advance
