### ISSUE TITLE
Cannot select object below an selectable=false object with a single click, but group select works.

### ISSUE THREAD

**Issue by thotar** [fabricjs/fabric.js#5660]
Between version 2.4.0 and 2.4.1 - Selecting an object below an un-selectable object behavior changed.

This change changed the behavior:
https://github.com/fabricjs/fabric.js/pull/5259#issuecomment-487224741

The jsfiddles are the same except the fabric version is different.

## Version
2.4.1

## Test Case
https://jsfiddle.net/v8kafdL5/ - v 2.4.1
https://jsfiddle.net/qgkt2fLw/ - v 2.4.0

## Information about environment
Which browsers?
At least Chrome

## Steps to reproduce
Click on the Triangle below the circle.

## Expected Behavior
Triangle is selected.

## Actual Behavior
Not selected.

**Comment by johnsoncheg** [comment]
maybe u can try `this.canvas.bringToFront()` first.

**Comment by jessemtcarlton** [comment]
I think selectable disables selection but absorbs the events.  You need to set evented:false on the circle if you want it to be a static overlay and be able to select items below it.

**Comment by asturur** [comment]
the change was half intentional, i have no idea why this issue was still open.
Yes selectable means that you cannot select it, not that is transparent to selection process.
Interact with the events, but refuses to be selected.
