### ISSUE TITLE
How to make the size of the Rect's handles scale when zoomed? 

### ISSUE THREAD

**Issue by yxchng** [fabricjs/fabric.js#5662]
http://jsfiddle.net/hdramos/ux16013L/

As can see from the fiddle, when zoomed, the size of the Rect's handles do not scale but remain fixed when zoomed. How to make it scale proportionally with the zoom such that it becomes larger when zoomed in and smaller when zoomed out?

**Comment by asturur** [comment]
controls/handles are sort of UI elements and fabricjs does not resize it.
I do not think we want to handle it either.
What is your use case?

If you want to do that, you can still change fabric.Object.prototype.cornerSize value every time you zoom in/out.
