### ISSUE TITLE
[Fonts] How does Fabric.js calculate font size / line height / bounding box?

### ISSUE THREAD

**Issue by washamdev** [fabricjs/fabric.js#5663]
I am trying to take the underlying canvas data that Fabric.js generates and use a library on the server to copy how an image looks in Fabric. This works very well in all cases but fonts. I have noticed that no matter how I try to calculate line height on the server side, I cannot get it to match Fabric's line height. It seems it may have something to do with spacing around the text. See this:

![fjs-font-padding](https://user-images.githubusercontent.com/4692325/57005893-3e431080-6ba1-11e9-9d2c-70aefc7652eb.jpg)

There are 6px above the font ascent and 2px below the descent, then 38px for the font (which is correct, as the font size is set to 38px). On the server, I have the `top` and `left` coords of the bounding box, the font size, and the line height from Fabric. How do I reliably calculate the same 6px above the text and 2px below to then reliably calculate the same line height as Fabric? Or do you think this is even possible?

Thanks for any insight you can provide!

**Comment by asturur** [comment]
if you look in the closed issue there is an explanation somewhere. i ll try to find it.

Was a long discussion with some manual drawing at some point.


what server library are you using?

**Comment by washamdev** [comment]
@asturur I did some searching last night but didn't find anything then, so I must have missed it.

Attempting to use SkiaSharp. I basically take the `top` and `left`, the font size, and the line height from Fabric.js, and use them to write out the font, but I consistently run into spacing issues. I tried getting font metrics from SkiaSharp and adjusting spacing according to the ascent, descent, etc., but still couldn't get the text to render like in Fabric.js. So it would definitely be helpful if I can view that issue where it's described how text is rendered. Thanks!

**Comment by asturur** [comment]
with nodejs don't you get enough results, using fabrix on the server side?

**Comment by washamdev** [comment]
We currently don't use NodeJS, although I guess that could be an option. You're saying we could load up Fabric.js in NodeJS on the server, pass in the canvas JSON of the image created in Fabric on client-side, then output the raw image bytes to generate the image?

**Comment by asturur** [comment]
yes but wait for release of 3.0, makes everything easier on node. ( likely this days )

**Comment by washamdev** [comment]
Sounds good, thank you! I will stand by...
