### ISSUE TITLE
After canvas setZoom, the stuff once added could be selected will never be selected unless you scale to the original zoom

### ISSUE THREAD

**Issue by johnsoncheg** [fabricjs/fabric.js#5664]
## Version
2.4.0

## Test Case
https://codepen.io/johnsoncheg/pen/dLExRJ?editors=1010

## Information about environment
Nodejs or browser?
browser
Which browsers?
chrome 73.0.3683.103

## Steps to reproduce
First click button "add stuff", then click button "-", then I try to hover cursor to the stuff,
it cannot be selected
## Expected Behavior
the stuff added can be selected despite the scaling( setZoom )
## Actual Behavior
the stuff cannot be selected

**Comment by asturur** [comment]
please looks the documentation for setCoords. You should call it after modifying viewport or positions

**Comment by johnsoncheg** [comment]
@asturur I call setCoords after setZoom operation in my test case, and it doesn't work

**Comment by johnsoncheg** [comment]
@asturur please check my test case carefully and let me know if I misuse the setCoords

**Comment by asturur** [comment]
If you add objects on the canvas those are selectable
I have no idea what are you adding there to the imageGroup.
Objects inside a group are not selectable

**Comment by johnsoncheg** [comment]
@asturur The reason why I add object(group consistent of line & triangle) to imageGroup is that I need to do some moving to the big img, If I add object to canvas, when I move the image, the object I added cannot transform the position as long as I move the image, so I choose a simple way to wrap objects & image into imgGroup just for the convienience of moving together 😭

**Comment by asturur** [comment]
you just can select them individually. i do not see any bug here. what would it be?

**Comment by johnsoncheg** [comment]
@asturur After I called setZoom on the canvas, the object(group [line, triangle]) I added cannot be selected again, that's the problem I want to solve. I think it's very weird, I want to select the object again not the image. I've tried many ways to achieve the effect just as many answers said to setCoords for objects after `setZoom`. Sadly, it seems not work

**Comment by asturur** [comment]
but that line triangle is added to another group i see from the code. or am i wrong?

**Comment by johnsoncheg** [comment]
@asteriskman7 yeah u r right. I just want to select the group (line & triangle) after calling setZoom on canvas. the group of [line & triangle] is added to the imgGroup and the setZoom operation affect all of them. it's weird that sometimes u can select the line group after calling setZoom sometimes u can't - -

**Comment by asteriskman7** [comment]
@johnsoncheg I don't think you intended to @ me here.

**Comment by johnsoncheg** [comment]
@asteriskman7  sorry bro. it was a mistake and I feel embarrassed

**Comment by johnsoncheg** [comment]
@asturur I finally settled it. just iterate the group (not image) and call `setCoords(true)`, and thanks bro
