### ISSUE TITLE
Browser zoom causes blurryness, even when not zooming in past 100%

### ISSUE THREAD

**Issue by teuneboon** [fabricjs/fabric.js#5665]
## Version
2.4.0

## Test Case
I know you like jsfiddle here, but this is reproducible on the official site: http://fabricjs.com/

## Information about environment
Nodejs or browser? Browser
Which browsers? Chrome, Firefox, probably more?

## Steps to reproduce
1. Zoom out to 50%
2. Refresh
3. Zoom back in to 100%

## Expected Behavior
Canvas is not blurry, or have the option to listen to the zoom event and rerender or something like that.

## Actual Behavior
Canvas is blurry

**Comment by asturur** [comment]
in canvas the retinaScaling is mixed with window devicePixelRatio where also windows zoom is stored.

So if you detect a zoom from the user, you should reinitialize the canvas so that fabric can read the correct pixels.

something like:

```
fabric.devicePixelRatio = window.devicePixelRatio;
yourCanvas.initiRetinaScaling(); // i do not remember the exact method
// or alternatively
// yourCanvas.setDimensions(yourCanvas);
// will reset width/height and apply retina scaling again
yourCanvas.renderAll();
```
