### ISSUE TITLE
How to edit a textbox within a group in fabricjs

### ISSUE THREAD

**Issue by kriztupher1** [fabricjs/fabric.js#5667]
My fabric application requires a feature that allows the user edit textboxes within groups. I almost have it working. As it stands, this is how my application works:

Click on a group
Checks to see if you are clicking on a textbox. If yes...
Ungroups the group
Sets the focus on the textbox so that the user can make edits.
On "editing:exited," re-groups the objects
Here is a fiddle with my code: https://jsfiddle.net/1dr8jn26/4/

Do the following to replicate my issue:

Add 2 input boxes using the button at the top
Group the input boxes using the button at the top
Click once on one of the input boxes in the group you created
Click on the canvas outside of the group
Click back on the same input box
Click on the canvas outside of the group again
Repeat 5 & 6
You will notice that the group creates duplicates of itself off to the side of the page. What I have discovered on my own:

"object.on('editing:exited... is what keeps getting run over and over.
The "duplication counter" resets if you click on one input box vs another.
When the duplicates appear, if you click on some of them, they disappear.
I am still relatively new to programming, so i'm sure this is something obvious to the experienced coders here. Any help would be appreciated!

```
canvas.on('mouse:down', function(options) {
if (options.target) {
    var thisTarget = options.target; 
    var mousePos = canvas.getPointer(options.e);
    if (thisTarget.isType('group')) {
       var groupPos = {
            x: thisTarget.left,
            y: thisTarget.top
        }
var currentGroup = [];
var groupItems = []
groupItems = thisTarget._objects;
thisTarget.forEachObject(function(object,i) {
currentGroup[i] = object;
currentGroup.push(object);
})
        thisTarget.forEachObject(function(object,i) {
         if(object.type == "textbox"){            
 console.log("Start for statement that finds the x and y for each 
object")            
var matrix = thisTarget.calcTransformMatrix()
var newPoint = fabric.util.transformPoint({y: object.top, x: 
object.left}, matrix)
            var objectPos = {
                xStart: newPoint.x,
                xEnd: newPoint.x + object.width,
                yStart: newPoint.y,
                yEnd: newPoint.y + object.height
            }
            if (mousePos.x >= objectPos.xStart && mousePos.x <= 
(objectPos.xEnd)) {
                if (mousePos.y >= objectPos.yStart && mousePos.y <= 
objectPos.yEnd) {
function ungroup (group) {
groupItems = group._objects;
group._restoreObjectsState();
canvas.remove(group);
for (var i = 0; i < groupItems.length; i++) {
    canvas.add(groupItems[i]);
}
canvas.renderAll();
};
ungroup(thisTarget)
canvas.setActiveObject(object);
object.enterEditing();
object.selectAll();
object.on('editing:exited', function (options) {
var items = [];
groupItems.forEach(function (obj) {
    items.push(obj);
    canvas.remove(obj);
});
console.log(JSON.stringify(groupItems))
var grp = new fabric.Group(items, {});
canvas.add(grp);   
                  });
                }
            }
        }
        });   
      }    
   }
}); 
```
-Chris

**Comment by kriztupher1** [comment]
Hey guys, I am completely stumped on this. Can anyone assist?

**Comment by asturur** [comment]
hi @kriztupher1 i suggest you to restructure your fiddle as follow:

- attach the mousedDown handler to the group that have textbox only only, so you can remove the code for determining if the group you clicked is of interest. ( determine it in the group button function )

- enable group.subTargetCheck so that fabric will tell you on what sub item of the group you clicked and you do not need to calculate it by yourself ( will be in options.targets, that is an array )

- use group.toActiveSelection() and then canvas.discardActiveObject() to reduce the code that ungroup the group.

at this point the fiddle should be shorter to read and easier to help.

I presume there is a reference problem somewhere where some objects gets referenced both on the canvas and the group array and that  ruins the position.

**Comment by iyobo** [comment]
I feel like this needs to be addressed more. subTargetCheck does not work
http://jsfiddle.net/iyobo/bhpsfavr/4/
