### ISSUE TITLE
The cursor cannot move to the second char in the second line when the second line is generated using \n

### ISSUE THREAD

**Issue by youyou098888** [fabricjs/fabric.js#5669]
Hi,

I have found an issue that the cursor cannot move to the second char in the second line when the second line is generated using enter press instead of wrapping automatically.

**Comment by asturur** [comment]
please add a jsfiddle

**Comment by youyou098888** [comment]
Hi, I cannot reach jsfiddle in China but I can provide my code here:
The cursor cannot move to 'cannot', and when using command+A, it can not select the whole sentences.

let text = new fabric.Textbox("The first line\nIcannotmove", {
      left: 10,
      top: 10,
      width: 200,
      height: 200,
      angle: 0,
      fontSize: 16,
      fontFamily: 'FZDaBiaoSongS',
      textAlign: 'left',
      breakWords: true,
      objectCaching: false,
    });

**Comment by youyou098888** [comment]
Hi, I am sorry that I cannot reach jsfiddle in China but I can provide my code here:
The cursor cannot move to 'cannot', and when using command+A, it can not select the whole sentences.

let text = new fabric.Textbox("Thefirstline\nIcannotmove", {
left: 10,
top: 10,
width: 200,
height: 200,
angle: 0,
fontSize: 16,
fontFamily: 'FZDaBiaoSongS',
textAlign: 'left',
breakWords: true,
objectCaching: false,
});

**Comment by asturur** [comment]
any javascript template sharing is good. jsbin?

**Comment by asturur** [comment]
what is 'breakWords: true'?

**Comment by youyou098888** [comment]
It turns out to be my own method with 'breakWords: true' that caused the problem.
Sorry to border you. Appreciating your quick reply and I will close this issue.

**Comment by asturur** [comment]
@youyou098888 are you trying to use fabric with chinese and you need to break lines without the use of spaces?

If this is your problem now we are trying to officially support this kind of breaking method using the property `splitByGrapheme`  please pull down the latest master and run `npm run build` to get the lastest version ( unpublished ) and try it.

**Comment by asturur** [comment]
Just to say that NON English languages and non European one are hard for me to parse. Anyway i understand that today equal support for everyone is more important than perfect bug-free text. So i'm happy to understand what are the biggest necessity of asian languages and what is missing, and try to help.

**Comment by youyou098888** [comment]
Yes, I used to break lines without using space in chinese, now I have built the latest version from master that uses <cmd-splitByGrapheme> and it works fine.
Glad to hear that fabric will be getting stronger for asian languages, that is very nice of you.

**Comment by youyou098888** [comment]
Yes, I used to break lines without using space in chinese, now I have built the latest version from master that uses 'splitByGrapheme' and it works fine.
Glad to hear that fabric will be getting stronger for asian languages, that is very nice of you.
