### ISSUE TITLE
How to add custom attributes to Object

### ISSUE THREAD

**Issue by Wildlifes** [fabricjs/fabric.js#5670]
## Version
2.7.0

## Information about environment
 browser
chrome

## Steps to reproduce
```
    itext.clone(function (a) {
      a.includeDefaultValues = false;
      console.log(a.toJSON())

      canvas.add(a)

    }, { aaa: 111 })
```

## Expected Behavior
IText has an attribute ‘aaa’

## Actual Behavior
![image](https://user-images.githubusercontent.com/26505011/57207876-dc503400-7002-11e9-8dc7-33039385584f.png)

**Comment by asturur** [comment]
```
    itext.clone(function (a) {
      a.includeDefaultValues = false;
      console.log(a.toJSON())

      canvas.add(a)

    }, ['aaa'])
```

will copy aaa attribute if present when cloning.

**Comment by Wildlifes** [comment]
Thank you. I misunderstood the document.
