### ISSUE TITLE
Demo error blur filter

### ISSUE THREAD

**Issue by maxiplay** [fabricjs/fabric.js#5671]
Hello,

Thx for this great project. It's the best js library that I ever seen.

There is a little error in here http://fabricjs.com/image-filters

`
  $('blur').onclick = function() {
    applyFilter(11, this.checked && new f.Blur({
      value: parseFloat($('blur-value').value)
    }));
  };
`

The "value" attribute does not work. But the "blur" instead work successfully.

`
  $('blur').onclick = function() {
    applyFilter(11, this.checked && new f.Blur({
      blur: parseFloat($('blur-value').value)
    }));
  };
`
Fabric version:"2.4.4

**Comment by asturur** [comment]
To me blur filter works correctly, what is wroung for you?

**Comment by maxiplay** [comment]
The demo specify the "value" attribute but the good attribute is "blur"

**Comment by asturur** [comment]
but i can blur the pictures on fabricjs.com, can't you?

**Comment by asturur** [comment]
oh great, i understood it now.
When toggling the checkbox it does not work. It works only sliding.
Some extra explanation would have been useful.

Can you open a PR to fix it?
