### ISSUE TITLE
Bundled "fabric.js" doesn't  work on IE10

### ISSUE THREAD

**Issue by junghwan-park** [fabricjs/fabric.js#5677]
## Version
2.7.0

## Test Case
```
Test case not needed.
```

## Information about environment
Web Browser / IE10

## Steps to reproduce

1. Execute IE10 browser in Windows OS.
2. Load web page that loads bundled [fabric.js](https://cdnjs.cloudflare.com/ajax/libs/fabric.js/2.7.0/fabric.js).
3. Check debugger window console tab.

## Expected Behavior

There should be no errors. Script parsed successfully, and ready to use fabric.

## Actual Behavior

Browser hasn't `HTMLDocument` constructor but bundled file header contains `HTMLDocument`. I can't use `fabric` in IE10 at all.

**Comment by asturur** [comment]
ie10 should be supported, i'll check the issue.
The problem is that i do not have a  ie10 computer anymore. I need to setup a vm.

**Comment by junghwan-park** [comment]
@asturur
As far as I know, `HTMLDocument` constructor not exists in IE9, IE10. But, It has non HTML5 specification constructor `Document`. But modern browsers has `Document` too.

I think [HEADER.js#L13](https://github.com/fabricjs/fabric.js/blob/765f11537b5002ffe5b556f47ccccbfb8428d022/HEADER.js#L13)'s condition statement should be check `document` is instance of `Document` constructor when `HTMLDocument` constructor is `undefined`.
