### ISSUE TITLE
Events on object get fired when triggered outside clipped area

### ISSUE THREAD

**Issue by jvanaert** [fabricjs/fabric.js#5679]
## Version
2.7.0

## Test Case
https://jsfiddle.net/jvanaert/k0xt96nb/9/

## Information about environment
all browsers

## Steps to reproduce
open fiddle
place mouse just outside blue circle.
click and drag
blue circle is dragged

## Expected Behavior
Blue object cannot be dragged when action originated outside clipped area.

## Actual Behavior
Events on objects do not respect clipTo area

**Comment by asturur** [comment]
clipping area is just for drawing, the bounding box is responsible for the events. You can enable pixel transparency for events if you want.

Is described in the doc
http://fabricjs.com/docs/fabric.Canvas.html#perPixelTargetFind

**Comment by jvanaert** [comment]
ok, thank you for the clarification !
