### ISSUE TITLE
SplitbyGrapheme: text selection got messed up on multiple lines

### ISSUE THREAD

**Issue by blobinabottle** [fabricjs/fabric.js#5680]
## Version
2.7

## Test Case
https://codepen.io/anon/pen/vwLJXV

## Information about environment
Vanilly fabric

## Steps to reproduce
Double click to select the whole text

## Expected Behavior
Select the whole text

## Actual Behavior
Missing the last char.
And the more you add new text lines by sizing down the block the more you miss characters in the selection

![image](https://user-images.githubusercontent.com/8090162/57453754-79130b80-7267-11e9-82c7-7ae4f0ddf365.png)
![image](https://user-images.githubusercontent.com/8090162/57453763-7e705600-7267-11e9-9db7-f19f460139ad.png)

**Comment by asturur** [comment]
hi recently fixed this, please use latest master or wait till i republish 3.0.0.
(and please verify i m saying the truth)

Closing the issue and reopening if you verify i'm wrong.

**Comment by IftekherSunny** [comment]
<img width="514" alt="Screenshot 2021-05-30 at 12 59 06 PM" src="https://user-images.githubusercontent.com/8013399/120095319-21de7d00-c147-11eb-92a4-9c8d9d383b01.png">
I'm still facing same problem :(

**Comment by asturur** [comment]
Hi @IftekherSunny i m not sure what issue are you describing.
