### ISSUE TITLE
Lock canvas in the frame

### ISSUE THREAD

**Issue by lcontassto** [fabricjs/fabric.js#5681]
Hi,
I use a Fabric JS canvas in my project and I would like it to not go beyond the frame when I move it.

Someone can help me ?

thanks !
Lucas

**Comment by melchiar** [comment]
Do you mean restricting your objects to the boundaries of the canvas?

See here:
https://stackoverflow.com/questions/22910496/move-object-within-canvas-boundary-limit

**Comment by asturur** [comment]
Being a question i'll keep the issue closed, feel free to continue posting.
