### ISSUE TITLE
How to get object at mouse position on mouse up?

### ISSUE THREAD

**Issue by yxchng** [fabricjs/fabric.js#5683]
How to get object at mouse position on mouse up?

I tried `canvas.findTarget(opt)` and it is giving `undefined`. It works for `mouse:down` and `mouse:move` but not `mouse:up`.

I hope to be able to check if the added rect is empty (area == 0) on mouse up and remove it after it is drawn.

**Comment by asturur** [comment]
did you check opt.target? if is available is the target. Otherwise fabric found no targets.

**Comment by yxchng** [comment]
@asturur Is it supposed to find a target on `mouse:up` or is it not? If it is, then there is a bug here and I will file a new issue.

**Comment by asturur** [comment]
yes it is supposed. if it doesn't, make a fiddle that shows it and link it here. we reopen this issue.
