### ISSUE TITLE
Textarea

### ISSUE THREAD

**Issue by Roinoss** [fabricjs/fabric.js#5685]
Request for class similar to Textbox and working like html text area:
https://www.w3schools.com/tags/tag_textarea.asp
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_textarea

With additional options like:
maxlength: as html textarea

minFont: number | default = 1
maxFont: number | default = fontSize
resize: false | true
resize - change font size to match free space in Textarea. Resized font size must be between minFont and maxFont.

scroolbar: 'show' | 'hide' | 'auto-hide'
'auto-hide' - Hide scrollbar if not active.

overflow: 'scroolable' | 'cut'
cut - Don't allow to write characters, if there is no space for more visible characters, if there is overflow due to changing font size, hide overflow and signalize it by changing bottom part of active edit frame to red.

**Comment by asturur** [comment]
We do not plan to extend text functionality more than what we have now.
Some of the feature you are planning/asking are also a bit strange for a canvas based application.

```
maxlength: as html textarea

minFont: number | default = 1
maxFont: number | default = fontSize
resize: false | true
resize - change font size to match free space in Textarea. Resized font size must be between minFont and maxFont.
```

i think those are currently implementable with events.
Fabric does not let users change fontSize so you can implement min/max font size in the code you write to actually change fontSize.
