### ISSUE TITLE
Web Site Tutorials Have Broken Links

### ISSUE THREAD

**Issue by scottie-uk** [fabricjs/fabric.js#5691]
I am wanting to get started with Fabric.JS and see that the first third of your tutorials (on your website) have broken links.  Is this something that will soon be fixed?

**Comment by arivarton** [comment]
Also most of the demos are getting a 404 from github pages.

**Comment by asturur** [comment]
can you point me to some of them?

**Comment by scottie-uk** [comment]
It seems the broken links have been fixed. Quick work well done.

I would say that having updated tutorials a is more important than new features. Its how people will learn and then be convinced to utilize your frameworks. A lot of open source projects struggle on this point as they put new features above the usability of the code base by not updating documentation and tutorials.

Thanks for your responsiveness.

**Comment by asturur** [comment]
i perfectly understand that.
I have really little time to do it.
I was also thinking to so make the documentation less example based and more like a book, where how fabricJS works gets explained.

**Comment by asturur** [comment]
Oh by the way i think i fixed links in my local, and just i did not push because i had this half done 3.0 update.
