### ISSUE TITLE
setCoords() doesn't work

### ISSUE THREAD

**Issue by jiao1187875445** [fabricjs/fabric.js#5692]
I want to update the width of an object of type ActiveSelection, but setCoords() doesn't work.

**Comment by jiao1187875445** [comment]
> doAlignLeft:function(){
            var that_=this;
            if(that_.canvas.getActiveObjects().length<2){
                return false;
            }
            var newLeft;
            that_.canvas.getActiveObjects().forEach(function (t,i) {
                newLeft=i==0?t.left:newLeft>t.left?t.left:newLeft
            })
            that_.canvas.getActiveObjects().forEach(function (t,i) {
                t.set({left:newLeft})
                t.setCoords();
            })
            that_.canvas.getActiveObject().setCoords();
            that_.canvas.renderAll();
        },

>

**Comment by jiao1187875445** [comment]
![Uploading 8449GV)UVR`@HXRGUO$XKE6.png…]()

**Comment by jiao1187875445** [comment]
![Uploading IANOVM62FXJM}_C7S5N{4JT.png…]()

**Comment by SirPm** [comment]
Hi, did this later work for you, because I keep calling setCoords() after I programmatically change the width of an element with the set() method, but the coordinates don't seem to change, and the left and top still remain the same

**Comment by asturur** [comment]
setCoords change the aCoords and oCoords sub objects that are responsible for interactions with other objects/ mouse interaction and proper rendering.

**Comment by SirPm** [comment]
Okay, but the aCoords and oCoords sub objects of the object whose width I changed still reflects the old coordinates and not where it currently is in the canvas

**Comment by SirPm** [comment]
I finally understand what the setCoords does now, thanks
