### ISSUE TITLE
The top and left values of the same object are different in different activity types

### ISSUE THREAD

**Issue by jiao1187875445** [fabricjs/fabric.js#5694]
I want to know how the top and left of the object in an activeSelection type object are calculated. Why is the value I get when I select an object different from the value I get in an activity group of type activeSelection?

**Comment by asturur** [comment]
http://fabricjs.com/using-transformations

inner objects top and left gets changed in order to be rendered.
In order to know the top and left of that object on the canvas try to read the using-transformations tutorial and see if it helps
