### ISSUE TITLE
Extract the functionality to manipulate image in pure JS

### ISSUE THREAD

**Issue by kordix** [fabricjs/fabric.js#5698]
Is it possible to achieve the effect of manipulating the image (selecting, moving and resizing) in pure JS? 

Or maybe another way -to use FabricJS functionality but treat element not like Fabric.js object but object in pure JS canvas and then use pureJS functions. 

I would like to use fabricJS functionality and also some other in pure JS on canvas elements created in fabric, like perspective on this codepen: https://codepen.io/kaliedarik/pen/MwPVOR

**Comment by asturur** [comment]
you should help me to understand what is a pure JS canvas.

What is the part of the fabric.js code that is not pure javascript?
Is because of the class abstraction or because of the size of the library?

**Comment by asturur** [comment]
i have checked the codepen, the library you are using there is much similar to fabricJS. has abstractions and classes.
You can definitely have perspective transform with fabricJS and a bit of coding, but you have to first figure out if you want to modify scrawl for interaction of fabricJS for perspective.

There are no guidelines i can give you to help you understand what will be easier for you.

Is probably possible to make a fabricImage from a scrawl canvas.
