### ISSUE TITLE
Node.js / fabric fails to render custom fonts using toDataURL

### ISSUE THREAD

**Issue by sn3p** [fabricjs/fabric.js#570]
In my fabric app I'm using custom fonts (loaded via Google Fonts).
My canvas is rendered to PNG via Node.js, so I need to load these fonts on the server as well. This can be done with the NodeCanvas Font class ([example](https://github.com/LearnBoost/node-canvas/blob/dce07d50238e157a893653013e513658d476cc46/examples/font.js)).

So far so good, fonts are properly loaded and rendered when using `createPNGStream`.
But the PNG needs to be printed, so I need `toDataURLWithMultiplier` to get a high quality image. This is where it goes wrong. For some reason toDataURL and toDataURLWithMultiplier doesn't render the custom fonts.
Client side rendering of custom fonts using toDataURL works fine.

Does anyone know what could be the problem?

Below a test to illustrate the problem:

``` javascript
var fs = require('fs'),
    fabric = require('fabric').fabric,
    canvas = fabric.createCanvasForNode(400, 400);

// Load font
var font = new canvas.Font('Arvo', 'Arvo.ttf');
canvas.contextContainer.addFont(font);

// Add text
var text = new fabric.Text('Lorem Ipsum', {
    fontFamily: 'Arvo'
});
canvas.add(text);
text.center();

// RENDERS FONT CORRECTLY
var out = fs.createWriteStream('font1.png');
var stream = canvas.createPNGStream();
stream.on('data', function(chunk){
    out.write(chunk);
});

// FAILS TO RENDER FONT
var dataUrl = canvas.toDataURL();
var data = dataUrl.replace(/^data:image\/png;base64,/, '');
fs.writeFile('font2.png', data, 'base64');
```

**Comment by engrsandeep** [comment]
Hi @sn3p 

Can you help me how you have used google fonts in fabric.js on node.js. 
I am trying to create replica of user created design on node.js to generate high resolution image. Can you help?

Thank you so much in advance

**Comment by sn3p** [comment]
@engrsandeep, I wrote [this tutorial](http://fabricjs.com/fabric-intro-part-4/#custom-fonts) on custom fonts in fabric.js with node.js.
Also [this post](http://stackoverflow.com/a/16173795/949258) might come in handy when dealing with high resolution exports.

Hope it helps!

**Comment by engrsandeep** [comment]
Thank you.

**Comment by keanass** [comment]
Not able to add fonts like you did, i tested all ways with no results.
```
   var myFont = new nodeCanvas.Font(val.fontFamily, fontfile);
   myFont.addFace(fontfile, 'bold');
   createPNGStream or createJPEGStream
   canvas.contextTop.addFont(myFont);
```
