### ISSUE TITLE
Animate Calculation Issue in 3.0.0

### ISSUE THREAD

**Issue by orthatg** [fabricjs/fabric.js#5700]
## Version
3.0.0
Not present in previous 2.x versions.

## Test Case
http://jsfiddle.net/OrthATG/x5nkqbgf/

## Information about environment
Tested in Chrome 74 and Safari; macOS 10.12

## Steps to reproduce
In the fiddle, press Toggle Properties to animate some properties. Opacity is toggled from 1 to 0. Left is changed from 0 to 8.

## Expected Behavior
On animation complete we should see `rect.opacity = 0` and `rect.left = 8`

## Actual Behavior
On animation complete we _actually_ see `rect.opacity = 1.1102230246251565e-16` and `rect.left = 7.999999999999999`

It seems animating values between 0 and 8 causes the issue (possibly due to floating point calculation errors).

**Comment by asturur** [comment]
in 3.0 we did not change anything about animations.
Recently there has been some PR to set the final animation values to the exact values.
I'll look at the fiddle

**Comment by asturur** [comment]
This is an old bug, i do not think is 2.7 or 3, we never had this functionality.

I agree that the onComplete callback could set the values as the final value planned.
I m just not sure doing this will not break anything.
