### ISSUE TITLE
Must define canvas inside method to work

### ISSUE THREAD

**Issue by kordix** [fabricjs/fabric.js#5701]
## Version
3.0.0

## Test Case
https://codepen.io/kordix/pen/joGaBv

## Information about environment
browser chrome 74.0.3729.157

## Steps to reproduce
As shown on codepen, sometimes fabric.js does not show anything on canvas unless you define the canvas inside function/method. getObjects() method shows that something indeed is rendered on canvas, but still it doesn't show anything.

Problem often occurs with more complicated code, here I am using vue.js framework but I met the same issue in pure js when my code became more robust, hard to tell when exactly canvas worked only when defined inside function.

## Expected Behavior
It should render things exactly the same when canvas object is called globally

## Actual Behavior
It doesn't render when I define variable with canvas globally, I've commented it on pen

**Comment by asturur** [comment]
I have no idea how VUE works.
i think is clearing the div content and recreating the dom structure that is there.
If you move the canvas element outside the app div, everything works ok.
I think vue is swapping the canvas element and the fabric.Canvas is initialized over the old one.
