### ISSUE TITLE
Fill and stroke colors from computedStyle are ignored in toSVG() but render in canvas

### ISSUE THREAD

**Issue by alexhuot1** [fabricjs/fabric.js#5702]
## Version
2.7.0

## Test Case
I did 2 squares, the red one uses the css variable value and has the issues. The blue one has an hardcoded value and is work properly.

You can click on each square to make it copy to svg.
https://jsfiddle.net/h9sx6v01/1/

## Information about environment
Chrome browser

## Steps to reproduce
We are using css variable in our application to have consistant design and use some of those variables in our canvas drawings. We get our css variable value from the ```getComputedStyle``` fonction.
The colors inside the canvas are displayed properly, but not when we export it to SVG
## Expected Behavior
I would expect that the colors displayed in the SVG would be the same as the ones displayed in the canvas.
## Actual Behavior
Once exported with toSVG(), the drawing are all black.

**Comment by asturur** [comment]
if you remove the space between `red` and the colons `:` it works.
Is crazy i know.
I wonder who is at fault here.

**Comment by alexhuot1** [comment]
Yes it does work. It's really weird.

Thanks for the quick answer.
