### ISSUE TITLE
The fabric is referenced in the project, but the Wechat widget does not support document, because the widget does not run in the browser.

### ISSUE THREAD

**Issue by mengfei2611** [fabricjs/fabric.js#5703]
The fabric is referenced in the project, but the Wechat widget does not support document, because the widget does not run in the browser.

**Comment by jiao1187875445** [comment]
bu zhi dao ni zai shuo shen me

**Comment by mengfei2611** [comment]
微信小程序中不支持window对象和document对象,该如何使用fabric.js.

**Comment by jiao1187875445** [comment]
应该不支持小程序

**Comment by somychfudewe** [comment]
In wechat miniprogram use 
_(taro, remaxjs)_
1. npm i fabric --production
2. build npm
3. `import fabric from 'fabric'`
4. console error
```js
thirdScriptError 
 sdk uncaught third Error 
 module "miniprogram_npm/jsdom/path" is not defined 
 Error: module "miniprogram_npm/jsdom/path" is not defined
    at require (WAService.js:1:1432978)
    at WAService.js:1:1432729
```

**Comment by somychfudewe** [comment]
In wechat miniprogram use 

1. npm i fabric --production
2. build npm
3. `import fabric from 'fabric'`
4. console error (_(Same error on taro, remaxjs)_)
```js
thirdScriptError 
 sdk uncaught third Error 
 module "miniprogram_npm/jsdom/path" is not defined 
 Error: module "miniprogram_npm/jsdom/path" is not defined
    at require (WAService.js:1:1432978)
    at WAService.js:1:1432729
```
https://github.com/jsdom/jsdom/issues/2483

**Comment by asturur** [comment]
Are you running in node or browser?
