### ISSUE TITLE
Regression of free drawing pixel shifting bug

### ISSUE THREAD

**Issue by newtriks** [fabricjs/fabric.js#5705]
## Version
2.4.0

## Test Case
http://jsfiddle.net/mw1oybvk/

also evident on http://fabricjs.com/freedrawing

## Information about environment
Nodejs or browser? Browser
Which browsers? Chrome

## Steps to reproduce

Draw

## Expected Behavior

On mouse up, drawn line remains at the exact same coordinates on canvas

## Actual Behavior

On mouse up, drawn line shifts coordinates up and left on canvas. Regression of this issue: https://github.com/fabricjs/fabric.js/issues/4646

**Comment by asturur** [comment]
i think is the position fix done a couple of days ago.
I can fix this quickly and add a test in some way for free drawing.

**Comment by asturur** [comment]
Thanks for reporting the bug

**Comment by newtriks** [comment]
@asturur nw and thanks!

**Comment by coonmoo** [comment]
Any chance how we can add some custom code in our app to fix this behaviour? Need to publish a prototype next week and can't seem to figure it out on my own
Thanks a lot for the awesome work!

**Comment by asturur** [comment]
i think is easy to fix, just i did not have time.

**Comment by coonmoo** [comment]
Thanks a lot for the fast processing of the issue. I just pulled the source and made a build. Checked the dist file to verify it has the proper changes.
But after using the freedraw feature I still experience the same reported issue. Is there anything else we need to set/do?

**Comment by coonmoo** [comment]
@asturur when I draw a line the line is 15px under the crosshair's center (line is not originating from the center of the crosshair). Adding this code to the object:added event prevent's the line from jumping after drawing, but the drawing itself is still offset.

 event.target.set({
          top: event.target.top + 15
        });

**Comment by asturur** [comment]
i do not see the issue, can you build a fiddle on fabric 3.1 that show the problem?

**Comment by coonmoo** [comment]
I found it out today since I could not reproduce on fiddle. I had the canvas "top:-15px;" offsetted in the css...
Thanks for the fix!

**Comment by ToshipSo** [comment]
I'm facing the same issue on version 3.1.0!

**Comment by asturur** [comment]
that is because you are giving a string to something that expect a number

**Comment by leeharr** [comment]
I was seeing this today on Fabric.js version 4.2.0

The easy fix was to remove the margin: xxxx from the css for the canvas.

Not sure if it is a bug (that css on the canvas disrupts reading the position of the free drawing cursor) but if that is a problem you are having, try removing the css from the canvas, wrapping the canvas in a div, and styling the div instead.

**Comment by asturur** [comment]
can you reproduce it on current 4.2.0?

**Comment by leeharr** [comment]
Here is a complete example that shows the shifting behavior with fabric 4.2.0:

```
<!DOCTYPE html>
<html>
  <head>
    <title>Canvas Free Draw Bug</title>
    <script type='text/javascript' src='/static/js/fabric-4.2.0.js'></script>
    <style type='text/css'>
        #sheet {
            border:1px solid black;
            margin: 2em;
        }
    </style>
    <script type='text/javascript'>
        window.onload=function(){
            var canvas = new fabric.Canvas('sheet');
            canvas.isDrawingMode = true;
            canvas.freeDrawingBrush.width = 5;
            canvas.freeDrawingBrush.color = "#ff0000";
        }
    </script>
  </head>
  <body>
    <canvas id="sheet" width="400" height="400"></canvas>
  </body>
</html>
```

**Comment by asturur** [comment]
would you be able to have it in a jsfiddle and open an issue for it?

**Comment by leeharr** [comment]
Sorry. I took a quick look at jsfiddle. Not sure how to make it load the latest fabric version.

Note that even having only the border styling causes a small shift.

**Comment by asturur** [comment]
if you open a new issue, in the template there is linked a jsfiddle template with the latest version loaded.
http://jsfiddle.net/fabricjs/Da7SP/

**Comment by leeharr** [comment]
Ah. I see!

Well. In the jsfiddle, the problem does not appear. I have no idea why.

However, in the isolated example above, the problem does appear.

**Comment by libovness** [comment]
I am experiencing this in `4.6.0`. There is no margin on the canvas as there was with @leeharr's comment. Rather it seems the brush is drawing around the cursor evenly but then shifting to the top / left of the object that's created. If I shift the `top` and `left` of the object to `canvas.freeDrawingBrush.width / 2` it fixes the issues but that's not pretty. Is there something I'm missing in terms of setting something like `originX` or `originY` for the brush / object? 

Fiddle here: https://jsfiddle.net/nf1rqusL/4/

**Comment by libovness** [comment]
added a function to fix the shift in the fiddle which you can toggle, but this is not pretty. there's gotta be something I'm missing.

```
const shiftDrawnObject = (object) => {
	object.top += object.strokeWidth / 2
  object.left += object.strokeWidth / 2
}
```
