### ISSUE TITLE
Fabric JS + Gif image animation not working

### ISSUE THREAD

**Issue by cpvishal** [fabricjs/fabric.js#5706]
Hello,

I am using FabricJS, i've tired to gif image animation object on canvas.
Is there any way or plugin to render gif image animation with object in canvas ?

I have use below code for render gif image.
```
var canvas  = new fabric.Canvas('canvas');
fabric.Image.fromURL('./assets/images/e8nZC.gif', function(myImg) {

    var img1 = myImg.set({ left: 0, top: 0 ,width:400,height:400});

    canvas.add(img1);

    fabric.util.requestAnimFrame(function render() {
        canvas.renderAll();
        fabric.util.requestAnimFrame(render);
    });
});
```

**Comment by asturur** [comment]
all we know on this topic is here #560 
Is probably browser dependant and not a canvas specific
