### ISSUE TITLE
Object not clickable during animation

### ISSUE THREAD

**Issue by karloper** [fabricjs/fabric.js#5709]
## Version
2.4.0

## Test Case
https://jsfiddle.net/euL7to2w/

## Expected 

Circle should always be clickable.

#Actual
At the end of the animation the circle is not clickable.

**Comment by asturur** [comment]
onChange allows you to run code on each animation step, where you have to make the circle clickable.

https://jsfiddle.net/3gkvmnjo/

**Comment by karloper** [comment]
Thank you a lot!
 

Gesendet: Mittwoch, 22. Mai 2019 um 13:17 Uhr
Von: "Andrea Bogazzi" <notifications@github.com>
An: "fabricjs/fabric.js" <fabric.js@noreply.github.com>
Cc: KarloPeranovic <kropro@gmx.at>, Author <author@noreply.github.com>
Betreff: Re: [fabricjs/fabric.js] Object not clickable during animation (#5709)


onChange allows you to run code on each animation step, where you have to make the circle clickable.

https://jsfiddle.net/3gkvmnjo/
