### ISSUE TITLE
Creating stroke around the image with transparent background

### ISSUE THREAD

**Issue by ornitorenk** [fabricjs/fabric.js#5713]
SO link: https://stackoverflow.com/questions/56264312/stroke-for-custom-image-in-fabric-js

I'm trying to create stroke "around" my image that has transparent background but all I get is a static "square" stroke.

Here is an example of what I'm doing (I get "square" stroke not stroke around the actual image)
```

<canvas id="c" width="800" height="800"></canvas>
<script>
var canvas = new fabric.Canvas('c');
var srcImg = "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png";

var canvas = new fabric.Canvas('c');

fabric.Image.fromURL(srcImg, function(oImg) {
oImg.set({
stroke:'red',
strokeWidth:10
});
  canvas.add(oImg);
  canvas.renderAll();
 oImg.center();
});
canvas.renderAll();
</script>

```

Also JSFiddle: https://jsfiddle.net/e14f9mj5/1/

Any thoughts? Thank you

**Comment by asturur** [comment]
if you change that question and add a basic interactive fiddle so that i can modify, i ll try to see if my idea works.
Is not a fabric feature tho.

**Comment by asturur** [comment]
You can copy active fabric snippets from other fabricjs questions

**Comment by ornitorenk** [comment]
> if you change that question and add a basic interactive fiddle so that i can modify, i ll try to see if my idea works.
> Is not a fabric feature tho.

Sure thing, here it is: https://jsfiddle.net/e14f9mj5/1/
Thanks

**Comment by asturur** [comment]
Wanted to get back to this, it can't really be done with every image.
with filled shape like the hearth, with no holes, we can draw them scaled a bit, monocolor, then draw the image on top of that.
But this would fails for text, image with holes.

I tried also to make a demo with various non blurred shadow, but the final effect does not look good and depends too much on the image shape.

**Comment by ornitorenk** [comment]
Thank you @asturur 
Could you share your example for your monocolor example?

All the best

**Comment by ornitorenk** [comment]
Could you kindly add stroke functionality for images in the future? (like in Photoshop?)
It would be a great addition to FabricJS

**Comment by asturur** [comment]
i have been thinking around this a bit, and i think the only clean solution is a filter

**Comment by ornitorenk** [comment]
@asturur Could you please elaborate/share an example code regarding the filter solution?

**Comment by asturur** [comment]
depends on the approach. the only way you can understand the shape of an image on a canvas is using the alpha layer. So you have to write a code that moves around transparent pixels and create a path, smooth the path and paint it, or erode the transparency image and fill the difference with a color. neither of those are standard fabric things

**Comment by khajaordant** [comment]
I am trying to do this same but nothing official available yet may be. 

Would like to implment  "find around transparent pixels"  feature.   But need help to check if anything available similar.

**Comment by asturur** [comment]
not that i know of

**Comment by matheuscamarques** [comment]
i need this function in png images

**Comment by hamzawain7** [comment]
@asturur can you implement this or elaborate on how to "find around transparent pixels". Anything available in fabricjs to get started on this myself?
