### ISSUE TITLE
Merge/Join a canvas with a video

### ISSUE THREAD

**Issue by kenseii** [fabricjs/fabric.js#5715]
Is it possible to merge a canvas with a video to export a webm file?
I saw whammy.js but i am wondering if it is possible through fabricjs.

Thanks

**Comment by asturur** [comment]
there are a couple of canvas api that let you record a video
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/captureStream

**Comment by kenseii** [comment]
> there are a couple of canvas api that let you record a video
> https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/captureStream

Does it require the user to play the whole content of the video before merging the data?

**Comment by asturur** [comment]
Sorry for not getting back to you sooner.
Yes i think it requires you rendering the video somehow.
I'm not sure if, provided the computer is fast enough, you can fast forward

**Comment by kenseii** [comment]
So far i can capture the canvas i think but it is not showing the video in the back of the canvas, so the merged video doesnt show any content.

**Comment by kenseii** [comment]
I solved it. Thank you very much for the guidance.
I was missing the part that the fabric canvas is not a normal canvas.
https://github.com/kenseii/video-annotator
