### ISSUE TITLE
In Safari (7.0), the Object element cannot be clicked, selected, or dragged. But the IText and path elements can,

### ISSUE THREAD

**Issue by jiao1187875445** [fabricjs/fabric.js#5716]
In Safari (7.0), the Object element cannot be clicked, selected, or dragged. But the IText and path elements can,

**Comment by jiao1187875445** [comment]
error: Unable to get image date from canvas because the canvas has been tainted by cross-origin data

**Comment by jiao1187875445** [comment]
I added the {crossOrigin:'anonymous'} attribute when I drew the image, and it was all right in the Windows system, but the error was reported in Mac's safari

**Comment by asturur** [comment]
Is the image coming from a video source? crossOrigin images works in safari 7, videos do not.

Is safari at least latest of the 7? 7.1.8?

**Comment by jiao1187875445** [comment]
> Is the image coming from a video source? crossOrigin images works in safari 7, videos do not.
> 
> Is safari at least latest of the 7? 7.1.8?

The picture is in SVG format. It is hosted on the image server. My Safari version is 7.0.6

**Comment by asturur** [comment]
can you make a fiddle from it? if is hosted on your server is weird. External content in the image?

**Comment by jiao1187875445** [comment]
I'm sorry, but my English is very poor. Maybe the description is not clear enough. And I don't quite understand what fiddle is. So I tried to describe my problem in as much detail as possible.

I'm making a drawing tool now. Users are free to add pictures to the canvas. The images uploaded by users will be stored in the OSS (Object Storage Service) of Aliyun.
Every time the user saves the painting task data, it is the data I get through canvas. toJSON ().  The SRC of the image in the data points to the path where the image is stored on OSS. It involves cross-domain issues. After setting the {crossOrigin:'anonymous'} attribute, the problem of canvas contamination has been solved in the browser of windows system. But in Safari (7.0.6), there has error message about canvas contamination.

**Comment by asturur** [comment]
If it works in any other browser, is a problem of safari 7.
If you can create a fiddle that demonstrate the problem, i can test in safari 12 but not below.

**Comment by awehring** [comment]
@jiao1187875445:
fiddle is an online HTML / CSS / JavaScript editor. It is perfect to test code-snippets.

There is a template for fabric.js:
http://jsfiddle.net/fabricjs/Da7SP/

There is a collection of fabric.js examples too:
http://jsfiddle.net/user/fabricjs/fiddles/
