### ISSUE TITLE
Consistently failing to render both text & image layers to Canvas on iOS 12 (Safari / Chrome latest versions)

### ISSUE THREAD

**Issue by malkhuzayyim** [fabricjs/fabric.js#5720]
## Fabric Version
3.0.0

Building a product customizer with fabric, everything going very smoothly, its absolutely great.
Screenshot: https://drive.google.com/file/d/11QrqXxRf7GY2XxKBS9S0WZCV9FYSTFnT/view?usp=sharing

However, weird behavior came up only when using an iPhone with iOS version 12 or above, the canvas was not rendering anything, i had some limitation in testing (i don't own an iphone 8 or above, it was friends testing remotely) but here is what I know so far:
- Everything works fine on my iphone (iphone 7, capped at iOS 11), both chrome & safari work fine
- Everything works fine on windows laptop, and mac laptops
- Everything works fine on android phones

## The issue comes here:
- On iphones running iOS 12 or above (Tried it on a single iphone 8, and 3 different iphone x's or above, all of them running the same iOS12), it doesn't render anything to canvas, even using different browsers (Safari / Chrome)
- I know my CSS isn't messing up the canvas positioning, because i tried color coding my elements used to do absolute positioning to visually see the canvas and nothing is misplaced
- I know no errors are being logged to the console, i set up Sentry on it, and injected a sentry exception on the events of adding text, no errors are showing up along with it with my custom sentry message

Is anyone else experiencing this for iOS 12 / Safari 12 on FabricJS Version 3?

Its hard for my to provide the jsfiddle, as this is running using vue CLI project, and its a lot of code to reproduce. If you're interested to see the issue running live, just message me i'll send you the link to my staging site, m.alkhuzayyim@gmail.com

## Expected behaviour
On adding user input text/image to canvas, the layer shows up

## Actual behaviour
Layers show up in the UI for layer controls (so fabric is consuming my add function), but no layers visually show up on the canvas (that is when running on iOS12 safari/chrome, everything works great on all other environments i tried)

**Comment by asturur** [comment]
can you log in the console the fabricCanvas.lowerCanvasEl.width and height? How big is your canvas after retina enhancing?

**Comment by malkhuzayyim** [comment]
I did not have access to the phone myself to plug it in start logging things as I usually do.

But I color-coded the lowerCanvas, the upperCanvas, and my custom container for them, and did some offsetting to see where they overlap and where they dont, all of them seem to be in-position according to each other (i got screenshots from a friend). I use a custom width/height of 1600/2400.

**Comment by malkhuzayyim** [comment]
This is some snippets:

Canvas Initialization:
`
    const canvas = new fabric.Canvas("canvas", {
      width: "1600",
      height: "2400"
    });
`
My HTML:
`
        <v-flex sm6 xs12>
          <div class="insideWrapper">
            <div class="canvasWrapper">
              <canvas id="canvas"></canvas>
            </div>
          </div>
        </v-flex>
`
My CSS:
`
.insideWrapper {
  width: 100%;
  padding-bottom: 100%;
  position: relative;
  background-image: url("../assets/mens-tshirt-black.png");
  background-size: contain;
}
.canvasWrapper {
  border: 1px grey solid;
  width: 40%;
  height: 60%;
  position: absolute;
  top: 23%;
  left: 31%;
}
#canvas {
  width: 100% !important;
  height: 100% !important;
  position: absolute;
}
.canvas-container {
  width: 100% !important;
  height: 100% !important;
  position: absolute !important;
}
.upper-canvas {
  width: 100% !important;
  height: 100% !important;
  position: absolute !important;
}
`

**Comment by malkhuzayyim** [comment]
i just disabled retina scaling and everything worked perfectly.
```
    const canvas = new fabric.Canvas("canvas", {
      width: "1600",
      height: "2400",
      enableRetinaScaling: false
    });
```
Fabric is absolutely amazing, the more I dive into the documentation the more I realize how powerful it is, keep up the good work. If  whoever is the lead maintainer opened up a patreon I'd be the first to sign up.

**Comment by asturur** [comment]
Hi did not have time to test the link ypu provided me, had a very unpleasent weekend up to yesterday.

Just by curiosity, how big was the canvas at the end? some phones have a retina factor of 3, that would have sent the lower canvas to 4800 by 7200, effectively too much for a phone.

**Comment by malkhuzayyim** [comment]
don't worry about it, i actually still didn't get to check the canvas value on those iphones i mentioned, i just took a shot in the dark and disabled retina scaling, had that friend test it again, and everything was working as intended

your previously reply tipped me off, found the default for retinaScaling set to true in the docs, so i tried turning it off and it just worked

sorry i couldn't be more useful here c:

**Comment by bcodes11** [comment]
> i just disabled retina scaling and everything worked perfectly.
> 
> ```
>     const canvas = new fabric.Canvas("canvas", {
>       width: "1600",
>       height: "2400",
>       enableRetinaScaling: false
>     });
> ```
> 
> Fabric is absolutely amazing, the more I dive into the documentation the more I realize how powerful it is, keep up the good work. If the lead developer on it opened up a patreon I'd be the first to sign up.

Thank you @malkhuzayyim , it worked for me
