### ISSUE TITLE
gesture not working in chrome

### ISSUE THREAD

**Issue by yesm1994** [fabricjs/fabric.js#5721]
## Version
3.0
## Information about environment
chrome browser 74

## Steps to reproduce
open http://fabricjs.com/touch-events in chrome 74 
## Expected Behavior
gesture should work and logged.
## Actual Behavior
not working and no logged

This is really critical in touchable device.
Hope you guys can fix it quickly.

**Comment by yesm1994** [comment]
I tried latest firefox, it works well.
I think some updates in chrome destroyed event.js

**Comment by asturur** [comment]
should be visible in chrome changelog then. what is the visible effect?

**Comment by yesm1994** [comment]
@asturur Cannot drag, zoom, rotate.  All touch interaction just give no response.
I just tried chrome 67, All touch events are ok.

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/pull/5785

use this PR to follow updates on this issue
