### ISSUE TITLE
IText insertChars method is not removing previous styles properly.

### ISSUE THREAD

**Issue by durga598** [fabricjs/fabric.js#5722]
## Version
3.0.0

## Test Case
https://jsfiddle.net/durga598/6kyzt4jn/

## Information about environment
All browsers

## Steps to reproduce
Use `insertChars` method to add some text without any style programmatically.
## Expected Behavior
It should remove previous style.
## Actual Behavior
It is not removing completely. Issue may be in this method [insertCharStyleObject](https://github.com/fabricjs/fabric.js/blob/47666580f4e7566ee75a151587935b0315e6f732/src/mixins/itext_behavior.mixin.js#L783)

**Comment by asturur** [comment]
I do not agree.
You are inserting `Cool` from position 1 to 5, and this will inherit the style that is there, unless you provide one.

What makes you think that the style should not preserved? When you type the style is preserved.

**Comment by durga598** [comment]
If I pass empty object instead of null then its throwing error. [fiddle](https://jsfiddle.net/durga598/6kyzt4jn/2/)

**Comment by asturur** [comment]
the doc requires an array of styles.
i think that is ok to use insertChars to insert text and use setSelectionStyle to set o remove the style.

why insertChars should do both?

**Comment by durga598** [comment]
I wanted to replace text from selection with new style. How to achieve it?
