### ISSUE TITLE
Сustom color overlay for the image behaves incorrectly

### ISSUE THREAD

**Issue by brutalsignature** [fabricjs/fabric.js#5723]
## Version
3.0.0

## Test Case
https://jsfiddle.net/3e1rcdmy/13/
## Information about environment
Nodejs or browser?
Which browsers?

## Steps to reproduce
Custom color overlay for the image
## Expected Behavior
Normal overlay behavior
## Actual Behavior
Transparent image with overlay. You can see the shadow in the image

**Comment by asturur** [comment]
Hi Maxim, you example is not clear.
It looks like you do not want the overaly to have a shadow over the image, this can be done in 2 ways:
1) enabled caching for the image
2) disable shadow on the context before drawing the overlay.

Those are not the kind of issues we solve here, this is more a stackoverflow question use case.

https://jsfiddle.net/opyagcs0/ 

Here there is a solution, but please next time follow guideline.

**Comment by brutalsignature** [comment]
Thanks Andrea! Unfortunately I could not figure it out and thought it was a mistake.
