### ISSUE TITLE
fabric.js 3.0 Brush Drawing is Offsetting After Mouse Up

### ISSUE THREAD

**Issue by mrgreen8** [fabricjs/fabric.js#5725]
## Version
3.0.0

## Test Case
http://fabricjs.com/freedrawing
https://jsfiddle.net/mrgreen8/dLrkgqbx/
(your website and my jsfiddle are both doing it)

## Information about environment
Google Chrome

## Steps to reproduce
Draw in the canvas area using the Pencil mode.  After mouse up, the object is offset from the freehand drawing.

## Expected Behavior
After drawing in the canvas area using the Pencil mode, after mouse up, the object should be where the freehand drawing was.

## Actual Behavior
After drawing in the canvas area using the Pencil mode, after mouse up, the object is offsetting from where the freehand drawing was.

**Comment by asturur** [comment]
there is a pr open to fix it and an issue that duplicates this.

**Comment by mrgreen8** [comment]
Ok. So what is the PR or issue I can reference?

**Comment by rob-64** [comment]
I am also experiencing same issue; curious which PR it is.

Thanks

**Comment by asturur** [comment]
in the pr list i think is the top one. The fix is the first commit.

**Comment by leeharr** [comment]
For those landing here from google, #5705 seems to be the one.
