### ISSUE TITLE
Free drawing a single point rotates / moves the point.

### ISSUE THREAD

**Issue by cabaret** [fabricjs/fabric.js#5726]
## Version
2.7.0 / 3.0.0

## Test Case
2.7.0: https://codepen.io/anon/pen/qGMVeP
3.0.0: https://codepen.io/anon/pen/MdqGoJ

## Information about environment
Browser

Which browsers?
Chrome, Safari

## Steps to reproduce
Click once on the canvas. A single square point is drawn. 

## Expected Behavior
I expect the point to stay in the same position and not rotate, as seen in this pen with version 1.7.19: https://codepen.io/anon/pen/byxMWG

## Actual Behavior
In version 2.7.0 (which we are using in our application), the path rotates 45 degrees. 
In version 3.0.0, the path rotates 45 degrees and moves.

**Comment by asturur** [comment]
The moving is fixed with the PR: #5718

**Comment by asturur** [comment]
Rotation is probably given by how i displace coincident points to avoid an hardware acceleration bug that would draw transparent. Since i have an open PR for freeDrawing i can try to address it there

**Comment by asturur** [comment]
i think i could have fixed this in 3.1.0
I will add a visual test to be sure.

**Comment by asturur** [comment]
i confirm is fixed with 3.1.0
