### ISSUE TITLE
after applyFilters and renderAll, the image render in error size in windows QQ browser

### ISSUE THREAD

**Issue by OPY-bbt** [fabricjs/fabric.js#5728]
## Version
3.0.0

## Test Case
https://codepen.io/opy-bbt/pen/xNydOy
## Information about environment
Nodejs or browser?
browser
Which browsers?
QQ browser in windows
## Expected Behavior
render in corrent size (you can comment the line: 121, 122)
## Actual Behavior
error size

**Comment by asturur** [comment]
The fiddle is not clear, can you explain better what is wrong?
