### ISSUE TITLE
How to get all properties available in fabric.js so that I can feed them into toJson and have a state snapshot that is exactly the same as before?

### ISSUE THREAD

**Issue by yxchng** [fabricjs/fabric.js#5732]
Specifically, I hope to be able to have say `canvas.getAllProperties()` function and do `state = canvas.toJSON(canvas.getAllProperties())` so that I can reload the exact same state back in the future. Otherwise, me being unfamiliar with the internals of fabric.js may miss out some properties and have subtle bugs in the state loaded in the future.

Even if there is no such function, where can I find the list of all properties that I need to feed into `ToJson` to get back the exact same state?

I tried getting `stateProperties` of object and inspect them and it gives

`["top", "left", "width", "height", "scaleX", "scaleY", "flipX", "flipY", "originX", "originY", "transformMatrix", "stroke", "strokeWidth", "strokeDashArray", "strokeLineCap", "strokeDashOffset", "strokeLineJoin", "strokeMiterLimit", "angle", "opacity", "fill", "globalCompositeOperation", "shadow", "clipTo", "visible", "backgroundColor", "skewX", "skewY", "fillRule", "paintFirst", "clipPath", "strokeUniform", "rx", "ry"]`

which does not include `cornerSize`, `viewportTransform`, `noScaleCache`, `objectCaching`, etc and probably many others.

And I have trouble finding the list in the documentation too.

Right now, I am missing the property of which objects are active and load back a canvas with those object being active. And I foresee more properties missing. That's why I am asking this question.

**Comment by asturur** [comment]
corner specific properties and viewportTransform and caching properties are not exported.
We consider those settings of your particular app more than specific content of the canvas.

You can still export them using the additional properties array, and no there is no a full list somewhere.

conerSize, cornerColor, cornerStrokeColor, hasControls, hasBorders, cornerStrokeDashArray, borderDashArray, objectCaching, noScaleCache are some additional object properties.

For the canvas you may have: viewportTransform and width, height.

Active objects are not exported anywhere and there is no property to do so.

You can add an id to objects and manually save what id were active at the moment of export.
