### ISSUE TITLE
NUM_FRACTION_DIGITS doesn't work for SVG export

### ISSUE THREAD

**Issue by Clemweb** [fabricjs/fabric.js#5734]
## Version
3.3.0

## Test Case
https://www.prima-cms.com/2629.svg

## Information about environment
Nodejs or browser?
Which browsers?

## Steps to reproduce
Export a canvas to SVG

## Expected Behavior
Rounded number

## Actual Behavior
Decimal number

I run Fabric like this 👍 
`custengine.canvas = new fabric.Canvas($(custengine.container).children('canvas').attr('id'), {enableRetinaScaling: true});
    custengine.canvas.preserveObjectStacking = true;
    custengine.canvas.selection = false;
    fabric.Object.NUM_FRACTION_DIGITS = 0;`

But the SVG export contain big float number (see sample)

And the problem is with background image pattern, floatting number create half pixel shift in Imagick render.

Example: see this file https://www.prima-cms.com/imagick.png that is a conversion of the SVG to png and you can see 1 pixel in background patterns.

How works NUM_FRACTION_DIGITS ? Is there anyway solution to export SVG without floating numbers ?

Thanks

**Comment by asturur** [comment]
exporting svg without decimals may result in wrong svg.

Num fraction digit is not used everywhere in svg export, but should. Please start with some examples of where it does not work

**Comment by rikkarv** [comment]
Maybe related to https://github.com/fabricjs/fabric.js/issues/5134?

**Comment by asturur** [comment]
sort of.
The problem here is that the parameter is applied inconsostently in svg export, and so precision is always max.sometimes. That is ok for accuracy but sometimes a problme if you just want a shorter svg.

Not a big deal, instead is parked here since a bit...
