### ISSUE TITLE
How can I change the size without maintaining the aspect ratio, like editing the size of shapes in "Microsoft office"?

### ISSUE THREAD

**Issue by ysnrszk** [fabricjs/fabric.js#5737]
<pre><code>
<canvas id="c" width="500" height="500" style="border:1px solid #ccc"></canvas>
<script>
var canvas =  new fabric.Canvas('c');
var rect = new fabric.Rect({
	left: 100,
	top: 100,
	fill: '#D81B60',
	width: 50,
	height: 50,
	hasControls: true
});
rect.setControlsVisibility({"mb":false, "mt":false, "ml":false, "mr":false});
canvas.add(rect);
</script>
</code></pre>

**Comment by asturur** [comment]
Please check the docs for uniScaleKey and uniscaleTransform.
