### ISSUE TITLE
toSVG() losing path opacity

### ISSUE THREAD

**Issue by mediumhust** [fabricjs/fabric.js#5739]
## Version
3.1.0

## Test Case
https://jsfiddle.net/tinyhustlee/v8dyb2wj/3/

## Information about environment
Which browsers?

## Steps to reproduce
Load SVG from URL, set object opacity 0.3. Then use the function toSVG() to export canvas to svg ( click the button To SVG in jsfiddle ).
## Expected Behavior
Exported SVG has the same opacity with canvas
## Actual Behavior
Exported SVG losing opacity

**Comment by asturur** [comment]
yes is a bug!
