### ISSUE TITLE
freehand eraser with real time erasing

### ISSUE THREAD

**Issue by TomVanHaver** [fabricjs/fabric.js#5742]
**Is your feature request related to a problem? Please describe.**
We would like to implement a classic eraser functionality that can erase "real time".

**Describe the solution you'd like**
When freehand drawing in erase mode (= globalComposteOperation set to "destination-out" on the path) over an existing drawing, the erasing should be applied "real time", so onMouseMove, not onMouseUp.

**Describe alternatives you've considered**
- set "globalCompositeOperation" to "destination-out" on the brush
- apply the erase path intermediate (onMouseMove)
- apply the erasing on the "main" canvas, and not on the topcanvas (**most plausible idea ?**)

**Additional context**
image a: onMouseOver while erasing.
![image a](https://user-images.githubusercontent.com/7240053/58961862-4bf44300-87aa-11e9-96f6-40e0cd56e856.png)

image b: erased after onMouseUp.
![image b](https://user-images.githubusercontent.com/7240053/58961865-4bf44300-87aa-11e9-8ce7-9dd1ae3accf8.png)

**Comment by alexwenbj** [comment]
@TomVanHaver Hi,Tom,I am looking for a eraser for the free drawing scence,would you please share your eraser code for us?Thank you.
