### ISSUE TITLE
Unpkg CDN friendly NPM publish

### ISSUE THREAD

**Issue by iongion** [fabricjs/fabric.js#5744]
For those that use/prefer CDN instead of large vendors bundle:

**Is your feature request related to a problem? Please describe.**
Using `dynamic-cdn-webpack-plugin` and `module-to-cdn` to isolate vendors bundle

**Describe the solution you'd like**
https://unpkg.com/fabric@3.1.0/ matches the npm package

But there is no production build included, can it be added ?

**Describe alternatives you've considered**
Unfortunately there are no alternatives

**Additional context**
No

**Comment by asturur** [comment]
Hi iongion, i m unfamiliar with solution different from webpack + npm or a simple cdn.
Can you elaborate better what unpkg does and what are we trying to solve?

**Comment by iongion** [comment]
So, the unpkg creates CDN automatically for any published npm package.
The CDN can be used in development and production.
Currently, the npm package of fabricjs does not publish the dist file, could it ?
Without this, the unpkg CDN cannot serve optimized builds as it just exposes the npm package.

**Comment by asturur** [comment]
but there is also the other cdn, cloudflare. Isn't that good?

I have plans to change the package content anyway, i want to add the src folders to allow custom build from npm, i can include back the dist file too. Just that for csn purposes you already have a working cdn that gets triggered by the git tag operation here

**Comment by iongion** [comment]
The unpkg works very well with the two modules listed above, they just work. I am not demanding this, just an idea, but if you include back the dist file, that will simply solve it and handle this case.

**Comment by asturur** [comment]
@iongion just published fabricJS 3.2.0 with the minified and full separated source files inside the npm package.
