### ISSUE TITLE
Extend class By Typescript Cause error when i Load From JSON

### ISSUE THREAD

**Issue by meron1122** [fabricjs/fabric.js#5745]
I extend Fabric Js Default type:

```typescript
//...
export class Button extends fabric.Rect {


  public text: string;
  public textColor: string;
  public font = '30px Arial';
  public action: ActionEnum;
  public type = 'button';


  constructor(options: IButttonOptions) {
    super(options);
    if (options.font) {
      this.font = options.font;
    }
    this.text = options.text;
    this.textColor = options.textColor;
    this.action = options.action;
  }


  toDatalessObject(propertiesToInclude?: string[]): any {
    propertiesToInclude = (propertiesToInclude || []).concat(
      ['text', 'textColor', 'font', 'action']
    );

    return super.toDatalessObject(propertiesToInclude);
  }


  _render(ctx: CanvasRenderingContext2D) {
    super._render(ctx);
    console.log('test');
    ctx.font = this.font;
    ctx.fillStyle = this.textColor;
    ctx.textAlign = 'center';
    ctx.fillText(this.text, 0, 10);
  }
```

And i want serialize/desearialize canvas like this:
```typescript
var json = canvas.toDatalessJSON();
canvas.clear();
canvas.loadFromJSON(json); // cause error 
```
But when i want load canvas with object defined above, i have exception "klass is undefined"

I Dont know how resolve this issue.Somebody can help?

**Comment by asturur** [comment]
fabric has to know that button exists.
Try `fabric.Button = Button`

Also you have to redefine the fromObject method, check how the Rect class does it

**Comment by Clemzd** [comment]
Did you ever find a solution for this? @meron1122 Im also looking to do the same as its easier with Typescript

I did not find a working example in typescript

**Comment by asturur** [comment]
@Clemzd did you try my comment?

**Comment by niketaOptimumnbrew** [comment]
> fabric has to know that button exists. Try `fabric.Button = Button`
> 
> Also you have to redefine the fromObject method, check how the Rect class does it

Hello @asturur 
I have tried this line of code but in v6 not working.
Can you please help me ?

Thanks.
