### ISSUE TITLE
Make newly select object viewable on object.deselected

### ISSUE THREAD

**Issue by carterw485** [fabricjs/fabric.js#5749]
This is a small request for version 2.0.0-beta0. The request only involves switching the order of 2 lines.

**Is your feature request related to a problem? Please describe.**
There is no way to know what the newly selected object is when 'deselected' is fired on an object.

**Describe the solution you'd like**
Swap the order of lines 10603 and 10604

Within`__onMouseDown: function (e)`

    if (target !== this.getActiveGroup() && target !== activeObject) {
      this.deactivateAll();
      if (target.selectable) {
        activeObject && activeObject.fire('deselected', { e: e });
        this.setActiveObject(target, e);
      }
    }

should become

    if (target !== this.getActiveGroup() && target !== activeObject) {
      this.deactivateAll();
      if (target.selectable) {
        this.setActiveObject(target, e);
        activeObject && activeObject.fire('deselected', { e: e });
      }
    }

This allows you to call canvas.getActiveObject() from within the deselected event and know what the newly selected object is.

**Comment by asturur** [comment]
v2 beta 0 is gone now. Events are better handled in 3.1 or even latest versions of 2.x  What.stops you from upgrading?

**Comment by carterw485** [comment]
One thing preventing updating is the change in hoverCursor behavior when an object is not selectable. The beta0 version maintains whatever canvas.hoverCursor is set to. The new version uses object.hoverCursor even when object.selectable === false.

https://github.com/fabricjs/fabric.js/issues/5712

There were a few other things, but I don't recall the specifics at the moment.

**Comment by asturur** [comment]
You should make your own patch.
If you think that line is good, go for it.

Would be better you stay on the top and you patch the hoverCursor behaviour if that really is creating you problems

you can still setup events on mouse over/out to change object.hoverCursor  to canvas.hoverCursor when is not selectable.
