### ISSUE TITLE
How to load base64 img in Fabric.js

### ISSUE THREAD

**Issue by gongph** [fabricjs/fabric.js#5750]
@kangax  @davidjrice  @maxim  @seanhussey  @miracle2k How to load base64 image in Fabric.js.

```js
const reader = new FileReader()
reader.readAsDataURL(file)
reader.onload = function (e) {
  const imgEl = self.$fabric.util.createImage()
  imgEl.src = this.result
  const img = self.$fabric.util.loadImage(imgEl, function (oImg) {
     console.log(1, oImg)
     // -> 1, undefined
  })
}
```

**Comment by sbtn** [comment]
loadImage() only requires the URL as the first parameter. If you change this param from imgEl to imgEl.src then it should work.

**Comment by asturur** [comment]
or just `const img = new fabric.Image(imgEl);`
