### ISSUE TITLE
Load an external svg element to report an error

### ISSUE THREAD

**Issue by gongph** [fabricjs/fabric.js#5751]
@kangax  big god, Here is the code for my vue project:

```js
// Img parse to svg element
import { createSvg } from 'img-svgize'

const imgEl = self.$fabric.util.createImage()
imgEl.src = this.result
imgEl.onload = function () {
  const svgEl = createSvg(imgEl.src, {
    width: this.width,
    height: this.height
  })
  self.$fabric.Image.fromElement(svgEl, function (oImg) {
    console.log(12, oImg)
  })
}
```
Then, chrome browser console log：

```bash
Uncaught TypeError: element.getAttribute is not a function
    at Object.parseAttributes (fabric.js?7a94:4239)
```
Open `fabric.js` sources for 4239 line:

```js
if (typeof svgUid === 'undefined') {
  // code coming here
  svgUid = element.getAttribute('svgUid');
}
```
`svgUid` attribute is how to defined ?

**Comment by awehring** [comment]
What does your `createSvg` function do?
Fabric offers the `fabric.loadSVGFromString()`  and `fabric.loadSVGFromURL()` methods. Both methods are async, the result is delivered in a callback.

Here is a code example: http://fabricjs.com/svg-caching

**Comment by asturur** [comment]
Not an issue of the library, closing, you can continue posting here.

**Comment by gongph** [comment]
Thank you @asturur
