### ISSUE TITLE
Text component of Fabric

### ISSUE THREAD

**Issue by davids123** [fabricjs/fabric.js#5752]
Can you extend functionality of the Text component of Fabric
![drag-drop](https://user-images.githubusercontent.com/16587371/59422536-2db3c600-8dee-11e9-8d4e-c9201f400273.gif)
?

**Comment by asturur** [comment]
This is out of scope for now, and will be for long.
A new api for controls is coming and filters are being move to objects, at that point you can build yourselft.

There is no easy cooperation between 2d transform and faked 3d ones, at least not that i know of.
