### ISSUE TITLE
Object as reserved keyword

### ISSUE THREAD

**Issue by dfa1234** [fabricjs/fabric.js#5756]
Thank for this fantastic project.

Just to say, 'Object' should be reserved, not a name of one of the class in Fabric.
Now webstorm want to import 'Object' everytimes.
That's a bug regarding my IDE but it's seems weird/wrong to me to name a class after `Object`... My example here is very trivial but I suspect others problem with this problem.

Step to reproduce, in typescript
Typing
`var test:Object`
I get automatically
`import {Object} from 'fabric/fabric-impl';`

**Comment by asturur** [comment]
i understand.
Is this a TS issue?

**Comment by dfa1234** [comment]
No I think it's related to the IDE (Webstorm)

Here another exemple more annoying. Webstorm keep asking for implementing `Object` import automatically.

![Screen Shot 5779-10-27 at 3 52 54 PM](https://user-images.githubusercontent.com/8502517/60396861-4c84bd00-9b4f-11e9-910e-9f94b745b29c.png)
