### ISSUE TITLE
svg repeat failed in Firefox for certains svg

### ISSUE THREAD

**Issue by maxiplay** [fabricjs/fabric.js#5758]
## Version
2.4.0

## Test Case
http://jsfiddle.net/maxiplay/kLxyfzjd/2/

## Information about environment
Firefox 67, windows 10, 64bits

## Steps to reproduce
Open the fiddle, toggle the background button. The button works on Chrome, not on Firefox

## Expected Behavior
Change the background, not become black

## Actual Behavior
Background become black

**Comment by asturur** [comment]
This is a long standing firefox defect.
If a svg has width and height 100% but does not have a container, it has undefined width and heigth and does not get rendered properly.

add numeric width and height to the svg to solve it

**Comment by maxiplay** [comment]
Exact ! Thx
