### ISSUE TITLE
Re-rending fabric objects to PDF or via C# to an image server side?

### ISSUE THREAD

**Issue by brightertools** [fabricjs/fabric.js#5759]
This is a question:

I have used fabric to draw various objects on top of an image (which is also an object)
The paths etc are saved to a database using my own methods of serialization, basically just saving each object individually.

I would like to create a report where I can redraw the same shapes etc ideally to a PDF, has anyone converted shapes and freehand drawings to other mediums like PDF? or even to image (server side)

Any ideas on the best way to do this? if this has been etc? Not looking for a whole solution if there isnt one, but some pointers or things to consider..

Am using C#,  .net core, vue.js

Thanks,

Mark

**Comment by asturur** [comment]
If you can run node.js you can render with fabric on the server side, otherwise yes paths are easily convertible in pdf but can be a pain. i would suggest you to look at fabricjs under node.
node-canvas has also direct pdf support output if i m not wrong.
