### ISSUE TITLE
ReactJs Package - react-fabricjs is not working

### ISSUE THREAD

**Issue by krishnadeveloper** [fabricjs/fabric.js#5761]
Hi,

I have used fabricjs package from [react-fabricjs](https://www.npmjs.com/package/react-fabricjs) but that could not work when I checked the console then there was an Uncaught TypeError: Cannot read property 'bool' of undefined

I have many other ways to fix buy installing the below packages

"@types/fabric": "^2.6.15",
"@types/prop-types": "^15.7.1",
"@types/react": "^16.8.20"

But still nothing is working. 
Please suggest any other was to use fabricjs with reactjs and react-native.
I am waiting for your reply to start my project.

**Comment by asturur** [comment]
just install fabric and react.
You do not need any special package.
