### ISSUE TITLE
prevent zoom outside background

### ISSUE THREAD

**Issue by hno2** [fabricjs/fabric.js#5762]
Hey there,

I try to restrict zoom to not go outside a loaded background image like in [your example](http://fabricjs.com/fabric-intro-part-5). But even after[ reading the Documentation on transformation](http://fabricjs.com/using-transformations) I don't know how to get it working. 
Check out my [StackOverflow Question](https://stackoverflow.com/questions/56629718/prevent-zoom-outside-background-fabric-js) with a working snippet for any details. 
Sorry to bother you.

**Comment by asturur** [comment]
i answered you there, thanks for following the suggested format.
