### ISSUE TITLE
IText rotation

### ISSUE THREAD

**Issue by charmjeh** [fabricjs/fabric.js#5763]
![image](https://user-images.githubusercontent.com/43127789/59747937-fd1fd080-92b4-11e9-99f1-bbfee9b55181.png)

Hi

I would like to use itext.set to make each letter of the canvas appear vertically.
What can I do?

i use javascript and canvas settings are all done

thank you for your time

**Comment by asturur** [comment]
We do not support per char rotation yet, probably somethingt that can go along tspan support. So for now you can just override the code and make it work.

**Comment by charmjeh** [comment]
thank you for your reply
