### ISSUE TITLE
charBox is undefined in renderChars.

### ISSUE THREAD

**Issue by TeslaFreak** [fabricjs/fabric.js#5768]
## Version
2.4.0

## Test Case
http://jsfiddle.net/zrjqh4xo/8/

## Information about environment
setting ._textLines from ._splitTextIntoLines() with TextBox _dimensionAffectingProps set to IText's _dimensionAffectingProps causes charBox to be undefined.

## Steps to reproduce
extend new fabric class from Textbox and override the dimensionAffectingProps array to be equal to that of the Text object:

fabric.ClueTextbox = fabric.util.createClass(fabric.Textbox, {
            type: 'cluetextbox',
             /**
             * Properties which when set cause object to change dimensions
             * @type Object
             * @private
             */
            _dimensionAffectingProps: fabric.Text.prototype._dimensionAffectingProps,
        });

Then override the onScaling of this item upon creation to call splitTextIntoLines for textwrapping purposes:

var newItem = new fabric.ClueTextbox("Lorem ipsum")
                newItem.set({
                    fontSize: 40,
                    width: this.canvas.width - 40,
                    lineHeight: 1,
                    charSpacing: 10,
                    editable: false,
                    lockUniScaling: false,
                    lockScalingFlip: true,
                });
                newItem.setControlsVisibility({
                    mt: false, // middle top disable
                    mb: false, // midle bottom
                    ml: false, // middle left
                    mr: false, // middle right
                });
                newItem.on('scaling',  () => {
                    var newfontsize = (newItem.fontSize * newItem.scaleX);
                    newItem.set({
                        width: newItem.width * newItem.scaleX,
                        height: newItem.height * newItem.scaleY,
                        scaleX: 1,
                        scaleY: 1,
                    });
                    var newLinesObject = newItem._splitTextIntoLines(newItem.text);
                    newItem.textLines = newLinesObject.lines;
                    newItem._unwrappedTextLines = newLinesObject._unwrappedLines;
                    newItem._text = newLinesObject.graphemeText;
                    newItem._textLines = newLinesObject.graphemeLines;
                });

The inclusion of the line  newItem._textLines = newLinesObject.graphemeLines; causes renderChars to break here on next render:
for (var i = 0, len = line.length - 1; i <= len; i++) {
        timeToRender = i === len || this.charSpacing;
        charsToRender += line[i];
        charBox = this.__charBounds[lineIndex][i];
        if (boxWidth === 0) {
          left += charBox.kernedWidth - charBox.width;   <---
          boxWidth += charBox.width;
        }

because charBox is undefined after the call to __charBounds.
## Expected Behavior
indexes should not go out of bounds of charBounds.
## Actual Behavior
__charBox is returning undefined. causes crash, have to reload to resolve issue.

This was working a few updates ago and i dont know what got added to break it but I cant wrap text in textboxs anymore with this method. there should be some kind of check to make sure charBox exists before calling properties on it.

**Comment by asturur** [comment]
can you make a fiddle for it please?

**Comment by TeslaFreak** [comment]
@asturur updated my previous comment with a fiddle. error will occur when you attempt to scale the object to the point that the text wrap changes.

**Comment by asturur** [comment]
http://jsfiddle.net/gx9jdwq8/

What about using initDimensions that is not a private method and seems to do the job?

**Comment by TeslaFreak** [comment]
Hadnt considered setting the height after the call to text wrap. seems to work. In the event someone had to override initDimensions for their own implementation in the future, it would still be a good idea to have a check for charbox though

**Comment by asturur** [comment]
Well i can add a check for charbox, but is more important to me to understand how we get there with mismatching indexes

**Comment by TeslaFreak** [comment]
I would agree with that. I just mean I think it would be good to still look into this bug, even though I admit its very low priority
