### ISSUE TITLE
How to test Fabricjs in Protractor?

### ISSUE THREAD

**Issue by Neuroforge** [fabricjs/fabric.js#5770]
Hello,

I am creating an Angularjs web application that uses the powerful Fabricjs canvas.  As part of the end to end testing, we use Protractor to simulate a user and check the application state to ensure that the app is working correctly.

When it comes to the Fabricjs canvas, i want to be able to test that an image has shown up correctly upon clicking a button in my web app. 

What is the best way to handle this and query the canvas for objects and ensure they are loaded?
How is this best achieved with Protractor?

https://github.com/angular/protractor/issues/4950

Regards,

**Comment by asturur** [comment]
throwing my 2 cents there.
