### ISSUE TITLE
Freedrawing with stylus broken in Chrome 75/ Windows 10

### ISSUE THREAD

**Issue by pinstripe-potatohead** [fabricjs/fabric.js#5773]
## Version
3.2.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Nodejs or browser? browser
Which browsers? Chrome 75/Chrome Canary, on Windows 10. Freedrawing works on Chrome on Mac

## Steps to reproduce

Freedrawing with a Wacom tablet(One, Intuos), with 'pen' mode selected doesn't draw lines on the canvas on Chrome/Win 10. 

## Expected Behavior
'pen' mode should draw lines, just like 'mouse' mode (pointerType = mouse) would 

I believe the issue happens because Chrome on Windows 10, detects pen mode styluses as touch devices, and emits pointerevents and touchevents at the same time(Only pointerevents are fired on Chrome Mac, and Firefox). These touch events cause the getPointer util to return null coordinates, which causes freedrawing to not work

**Comment by asturur** [comment]
would be great to attach console logs if the events generated from the epncil

**Comment by asturur** [comment]
Please follow #5785

**Comment by pinstripe-potatohead** [comment]
It's working with v3.3.2.
