### ISSUE TITLE
setFill is not a function

### ISSUE THREAD

**Issue by UnHumbleBen** [fabricjs/fabric.js#5775]
In the tutorials, http://fabricjs.com/fabric-intro-part-3
The setFill() function is used, but this function does not exist. I think it is supposed to be setColor().

**Comment by Clemweb** [comment]
It's a mistake in doc, the right syntax is object.set('fill', ....

setColor works too, it's just an alias

**Comment by durga598** [comment]
Check this [PR](https://github.com/fabricjs/fabric.js/pull/4065).

**Comment by asturur** [comment]
i will update the doc
