### ISSUE TITLE
Compression with Yui Compressor broken

### ISSUE THREAD

**Issue by pimpin** [fabricjs/fabric.js#5778]
## Version
at least from 3.0.0 and until 3.2.0

similar to #2934 

Compression broken by usage of reserverd "char" variable name  in `getHeightOfChar` here : https://github.com/fabricjs/fabric.js/blob/v3.0.0/dist/fabric.js#L25206

You can test it here : https://fr.piliapp.com/minify/yui-compressor/

**Comment by pimpin** [comment]
My bad, actually `getHeightOfChar` is still here in v 3.2.0. (but Github does not display it https://github.com/fabricjs/fabric.js/blob/master/dist/fabric.js ).

**Comment by asturur** [comment]
Please, open a pr over the latest master, swapping the word char in all the places you think is needed.
Update JSDOCS, but do not update the dist files.
Then i can rebuild and release again.
