### ISSUE TITLE
Ipad: canvas memory use exceeds the maximum limit

### ISSUE THREAD

**Issue by bassemBMI** [fabricjs/fabric.js#5780]
# Context:

While implementing FabricJS, we have encountered a canvas memory limit error.
While FabricJS alone is not the reason for the memory consumption(we have other components that use canvas too)
we have noticed that an older version of Fabric (1.3.0) merge all drawing in once canvas thus keeping canvas memory
consumption manageable

To illustrate our scenario please consider the following screenshots of safari devtoos -> canvas tab:

Latest version:
![image](https://user-images.githubusercontent.com/657496/60213543-ba6c7400-9831-11e9-86d8-00d633823cdb.png)

1.3.0 version:
![image](https://user-images.githubusercontent.com/657496/60213667-fe5f7900-9831-11e9-8f34-2697959e7e4b.png)

We can see that in the latest version, every action lives in a separate canvas while in the old version everything is merged in the main canvas

# Question:

Is there a way in the latest version of FabricJS to force all drawing and actions to apply only in the main canvas without creating secondary canvases

Please note that we have tried to deactivate the object cache without success:
```
fabric.Object.prototype.objectCaching = false;
```

http://fabricjs.com/fabric-object-caching

Thanks.

**Comment by bassemBMI** [comment]
Finally, I was able to force objectCaching = false; and it worked.
Thanks.

**Comment by Evelynddu** [comment]
I have the same question now. I have tried this solution but it doesn't work:
```
fabric.Object.prototype.objectCaching = false;
```
I'm wondering how to force objectCaching = false

**Comment by asturur** [comment]
that should work, except when you use features that require caching. Like clipPaths for example
