### ISSUE TITLE
a path has shadow in group,the group clippath with circle, canvas root path not show

### ISSUE THREAD

**Issue by wishinlife** [fabricjs/fabric.js#5783]
## Version
3.1.0

## Steps to reproduce
my canvas have multi path、svg object  ant text object ,path object and svg object has set shadow, on this time, a group have path and other object, if the group inner path set shadow and clippath(circle), the canvas text object and path object will not show, if the group inner path not set shadow, all show correct。

let pipePath= new fabric.Path(pipePath, {
            fill: null,
            selectable: false,
            hoverCursor: 'default',
            stroke: pipeColor,
            strokeWidth: 8,
            strokeLineJoin: 'round'
})
pipePath.setShadow({ color: 'rgba(0, 0, 0, 0.65)', offsetX: 3, offsetY: 3, blur: 5 })
canvas.add(pipePath)
let circle = new fabric.Circle({
          radius: 140,
          fill: '#fff',
          scaleX: 0.6,
          selectable: false,
          hoverCursor: 'default'
})
let innerBack = new fabric.Path(waterPath.innerBack, {
          fill: null,
          selectable: false,
          hoverCursor: 'default',
          stroke: CONST.pipeColor,
          strokeWidth: 8,
          strokeLineJoin: 'round'
})
let group = new fabric.Group([circle, innerBack], {
          clipPath: new fabric.Circle({ left: 0, top: 0, originX: 'center', originY: 'center', radius: 140, scaleX: 0.6 }),
          selectable: false,
          hoverCursor: 'default',
          left: 360,
          top: 180
})
// innerBack.setShadow({ color: 'rgba(0, 0, 0, 0.65)', offsetX: 3, offsetY: 3, blur: 5 })
**// if innerBack set shadow, pipePath will not show, if innerBack not set shadow, all show correct**
canvas.add(group)

**Comment by asturur** [comment]
Please create a fiddle that demonstrate the problem and that is easily usable.
I'll reopen the issue to discuss the problem/bug.
