### ISSUE TITLE
Canvas.getActiveObject(); is not working in Angular 7

### ISSUE THREAD

**Issue by lovep34** [fabricjs/fabric.js#5784]
Hello,

I am using Fabric in Angular 7, Some features are working correctly, But I want to use "Mask" from "BlendImage", so here is my code.

I have already installed Fabric & Fabric types package, but the "Canvas.getActiveObject();" is showing error.

```
Property 'getActiveObject' does not exist on type 'typeof Canvas'.ts(2339)
```
Here is my code :
```javascript
let object = Canvas.getActiveObject();
var filter = new fabric.Image.filters.BlendColor({
 color: '#000',
 mode: 'multiply'
});

var filter = new fabric.Image.filters.BlendImage({
 image: fabricImageObject,
 mode: 'mask',
 alpha: 0.5
});
object.filters.push(filter);
object.applyFilters();
canvas.renderAll();
```

**Comment by asturur** [comment]
i think you should verify on the type package, is not a package from this repository i cannot support it.
