### ISSUE TITLE
how can I get sawtooth with complete graphics?

### ISSUE THREAD

**Issue by yaoleia** [fabricjs/fabric.js#5787]
Full-quality color blocks are required, with sloping edges not gradient.
like:
![image](https://user-images.githubusercontent.com/22293549/60484426-2df80080-9ccc-11e9-9c0f-f0a5ebf1ccdc.png)
![image](https://user-images.githubusercontent.com/22293549/60484447-4831de80-9ccc-11e9-832f-8560e780e1fc.png)

just like http://members.chello.at/easyfilter/canvas.html

I want no gradient:
![image](https://user-images.githubusercontent.com/22293549/60484587-c1c9cc80-9ccc-11e9-9d44-11b24ce71495.png)

**Comment by asturur** [comment]
We cannot do this, while everything is possible, this would be extremely hard for everything related to fill, polygons and complex curves.
You can subclass lines and circle and ellipses  and implement yourself.

**Comment by yaoleia** [comment]
Thank you. It's really difficult. It's not what most people want.

**Comment by asturur** [comment]
you can ovverride circle render method or line, but you have to tale in account rotation and scaling
