### ISSUE TITLE
Color.toHex not respecting alpha in HexA color when converting.

### ISSUE THREAD

**Issue by rlightner** [fabricjs/fabric.js#5789]
## Version
2.4.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
browser?
Which browsers?
Chrome

## Steps to reproduce
var c = new fabric.Color("#ffffff00");
let hex = c.toHex();
hex == 'ffffff';

## Expected Behavior
hex should equal '000000'

**Comment by durga598** [comment]
In `#ffffff00`, after `#`6 letters represent color, and last two are alpha value.
So for 00 alpha value is zero. [stackoverflow](https://stackoverflow.com/questions/15852122/hex-transparency-in-colors).
If you want hex color with alpha value use `c.toHexa()`
[jsfiddle](https://jsfiddle.net/durga598/g2kycptq/)

**Comment by asturur** [comment]
thanks @durga598
