### ISSUE TITLE
setActiveObject() method seems not working new 3.1.0 version of Fabric.js

### ISSUE THREAD

**Issue by virto111** [fabricjs/fabric.js#5790]
## Version
3.0.0 and subsequent versions

## Test Case
https://jsfiddle.net/virto/skf10Lmh/4/ - working with 1.7.2
https://jsfiddle.net/virto/1obm952t/2/ - not working with 3.1.0

## Information about environment
setActiveObject() is not working properly in the new version of fabric - 3.0.0 and subsequent new versions.
Browsers: Chrome, Firefox
There are js fiddles provided.

## Steps to reproduce
Just click on the buttons to trigger setActiveObject method
## Expected Behavior
For not working example - figures should be set to active (selected)
## Actual Behavior
For not working example - figures are not selected

**Comment by awehring** [comment]
It is working, but there is a mall difference in behavior.

You can check that it is set active with `console.log(canvas.getActiveObject());`
In version 3 just add `canvas.requestRenderAll();` to see the handles.

**Comment by virto111** [comment]
So, is that method `requestRenderAll()` replacement for `renderAll()` method?

**Comment by awehring** [comment]
`renderAll()` still exists. 
`requestRenderAll()` was introduced with version 2.0.0 and is more efficient, as it renders async.

Details are here: http://fabricjs.com/v2-breaking-changes#requestRenderAll

I would suggest to read the many changes of release 2.0.0: http://fabricjs.com/changes-introduction

**Comment by asturur** [comment]
simply we removed some automatic renders from methods called by devs and not called by events. That saves on extra renders
