### ISSUE TITLE
I rotate the canvas with css3，but the pointer is defferent.

### ISSUE THREAD

**Issue by tczj199076** [fabricjs/fabric.js#5791]
HI,I have a requirement, I use css3 to transform the canvas with rotate(X deg),but the pointer is defferent,what should I do? thanks

**Comment by asturur** [comment]
the pointer is different because fabricJs assumes the canvas is not rotated.
There is no way to fix this from outside, there should be a fix in the library.
Is there a way that span from ie10 to chrome/firefox/safari to get the current css transform of the canvas?
Expressed as a 6 digit matrix possibly.

**Comment by mr47** [comment]
@tczj199076 fabricjs can't deal with css transforms because it's don't know transform matrix, you should not try to do this. maybe rotate objects that on canvas or use some kind of mask for making a rotation effect.

**Comment by asturur** [comment]
We would need a simple way to read the css transform matrix, but it has to be cross browser compatible.

**Comment by mr47** [comment]
@asturur Can you please link a good place for that functionality land. I will try to make PR for this.

Basic idea use [https://developer.mozilla.org/ru/docs/Web/API/CSSStyleDeclaration/getPropertyValue](getPropertyValue("transform")) and try to parse matrix

Should work but need some tests

**Comment by asturur** [comment]
we already have all the code to parse the matrix, we use it for svg. Just need to pull out the transform from the transform property and the difference of css dimensions compared to real dimensions
