### ISSUE TITLE
Is there any protential problem when pass a canvas to fabric.Image?

### ISSUE THREAD

**Issue by codertx** [fabricjs/fabric.js#5792]
Hi, I found if I pass a canvas element to `fabric.Image` constructor or `setElement` method on `fabric.Image`, it seem to work(which the doc says it only accept image element). 

Furthermore, I'm planning to add `HTMLCanvasElement` type to `fabric.Image` constructor and `setElement` method's parameter on its [TypeScript definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/fabric/fabric-impl.d.ts).

I'm not sure if there will be any problem with this. Could you give me some advice?

Thanks.

**Comment by asturur** [comment]
The code assume that if there is a canvas, a dataurl will be created for cloning the image and serializing it. That may be a show stopper for someone.
