### ISSUE TITLE
Cloning is broken in version 3.2.0

### ISSUE THREAD

**Issue by mbejda** [fabricjs/fabric.js#5793]
## Version
3.2.0

## Test Case
http://jsfiddle.net/rmpxya3L/2/

## Information about environment
Which browsers?
Chrome
Version 75.0.3770.100 (Official Build) (64-bit)

## Steps to reproduce
1. Select both text and object and click clone
2. While having an active selection, click on the cloned object.

## Expected Behavior
I expect the cloned object to be visible. 

## Actual Behavior
The cloned object disappears. 

<img width="409" alt="Screen Shot 2019-07-07 at 5 01 49 PM" src="https://user-images.githubusercontent.com/5429780/60770244-3c358a80-a0d9-11e9-84a7-6a7e65f8727f.png">

**Comment by durga598** [comment]
Check this [copypaste demo](http://fabricjs.com/copypaste)

**Comment by mbejda** [comment]
@durga598 That demo uses **version 3.0.0.** I'm reporting a bug in **version 3.2.0**. The bug is simple to reproduce and I outlined the steps to reproduce it.

**Comment by durga598** [comment]
@mbejda Here is updated [fiddle](http://jsfiddle.net/durga598/yswj09gh/) from the demo, and it works as expected. Updated your clone method.

**Comment by mbejda** [comment]
```
/**
 * fabric.js template for bug reports
 *
 * Please update the name of the jsfiddle (see Fiddle Options).
 * This templates uses latest dev verison of fabric.js (https://rawgithub.com/kangax/fabric.js/master/dist/fabric.js).
 */

// initialize fabric canvas and assign to global windows object for debug
var canvas = window._canvas = new fabric.Canvas('c');

// ADD YOUR CODE HERE
var text = new fabric.Textbox('Hello i m a bug', {
  width: 150,
  fontSize: 20
})

var rect = new fabric.Rect({
  left: 10,
  top: 20,
  width: 60,
  height: 60,
  fill: 'rgba(255,0,0,0.5)',
});

canvas.add(rect, text);

//canvas.renderAll();
window.clone = function() {

  canvas.getActiveObject().clone(function(object) {

    object.set({
      left: ((object.left) + 20),
      top: ((object.top) + 20),
      width: object.get('width'),
      height: object.get('height')
    });
    if (object.type === 'activeSelection') {
      // active selection needs a reference to the canvas.
      object.canvas = canvas;
      object.forEachObject(function(obj) {
        canvas.add(obj);
      });
      // this should solve the unselectability
      object.setCoords();
    } else {
      canvas.add(object);
    }

    canvas.setActiveObject(object); //// <!--- THIS IS IMPERATIVE 
    canvas.requestRenderAll();
  });
}
```

@durga598  I'm confused. If you remove the line ` canvas.setActiveObject(object);` the clone object can't be selected anymore. The cloning functionality effectively breaks the object. Is this by design?

**Comment by durga598** [comment]
@mbejda You need to destroy that activeselection, Here is updated [fiddle](http://jsfiddle.net/durga598/yswj09gh/1/).
@asturur on calling `canvas.discardActiveObject();` it doesn't fire `onDeselect` method if active object is `ActiveSelection` object.

**Comment by mbejda** [comment]
@durga598 Thank you for your guidance. This makes sense now. I'm closing this ticket.

**Comment by asturur** [comment]
@durga598 i think it calls onDeselect on the single objects? i did not check yet.
