### ISSUE TITLE
Blend Image has only one mode "Multiply" how to use other mode?

### ISSUE THREAD

**Issue by iamappmaker** [fabricjs/fabric.js#5796]
There are many modes Normal, Dissolve, Darken, Multiply, Lighten, Add, Difference, Hue. only multiply is available. If we have other modes then it will helps to create various image filter effects.

Why only multiply?

**Comment by asturur** [comment]
Because i miss the code for the others.
If you have the formula, please share.
I did not research that much.

**Comment by iamappmaker** [comment]
Sure. I will try to write the code. If i completed i will share it.
