### ISSUE TITLE
Wrong boundaries for fabric.Triangle with stroke (on the corners)

### ISSUE THREAD

**Issue by insolite** [fabricjs/fabric.js#580]
Object of type 'triangle' with thick stroke does not fit in his boundaries. It causes corners cropping when rasterizing.
Here is an example:
http://jsfiddle.net/dHhmQ/
##

**Comment by webmak** [comment]
Not shue have you solution but for my work I have write
fabric.util.object.extend(fabric.Triangle.prototype, {
    _render: function(ctx) {
        var widthBy2 = (this.width)/ 2,
            heightBy2 = (this.height)/2;

        ctx.beginPath();
        ctx.moveTo(-widthBy2 + this.strokeWidth/4*1.2, heightBy2);
        ctx.lineTo(0, -heightBy2 + this.strokeWidth/2*1.2);
        ctx.lineTo(widthBy2 - this.strokeWidth/4*1.2, heightBy2);
        ctx.closePath();

        this._renderFill(ctx);
        this._renderStroke(ctx);
    },
});
I've no time to look why Koef 1.2 need to use it seems to be in some funciton but for me it work fine, but It can do not work if chenge some parameter witch have impact to 1.2

**Comment by webmak** [comment]
I have make some changes for width is good, but recive vertical shift
fabric.util.object.extend(fabric.Triangle.prototype, {
    _render: function(ctx) {
        var tg = this.height/(this.width / 2)
        var angle = Math.atan(tg);
        var deltaWdth = (this.strokeWidth/2)/Math.tan(angle/2);
        var widthBy2 = this.width / 2 - deltaWdth,
            heightBy2 = (widthBy2 * tg) / 2;
        ctx.beginPath();
        ctx.moveTo(-widthBy2, heightBy2);
        ctx.lineTo(0, -heightBy2);
        ctx.lineTo(widthBy2, heightBy2);
        ctx.closePath();
        this._renderFill(ctx);
        this._renderStroke(ctx);
    },
    _calculateCurrentDimensions: function(shouldTransform)  {
      var vpt = this.getViewportTransform(),
          strokeWidth = this.strokeWidth,
          w = this.width,
          h = this.height;

      w = w * this.scaleX + 2 * this.padding;
      h = h * this.scaleY + 2 * this.padding;
      
      return { x: w, y: h };
    },
});
can you say witch funciton is responsible for checking position for drow element in main

**Comment by webmak** [comment]
http://jsfiddle.net/gda3b1ua/

**Comment by asturur** [comment]
i think we need a general solution outside triangle. same problem applies to polygon and polylines and of course paths.

**Comment by webmak** [comment]
here my solution for triangle:
fabric.util.object.extend(fabric.Triangle.prototype, {
    _render: function(ctx) {
        var tg = this.height/(this.width / 2)
        var angle = Math.atan(tg);
        var deltaWdth = (this.strokeWidth/2)/Math.tan(angle/2);
        var widthBy2 = this.width / 2 - deltaWdth,
            heightBy2 = (widthBy2 * tg) / 2;
        var shift = 1.2 * this.strokeWidth * Math.tan(angle/4) *this.height/this.width * Math.cos((Math.PI - 2 * angle)/2);
        ctx.beginPath();
        ctx.moveTo(-widthBy2, heightBy2 + shift);
        ctx.lineTo(0, -heightBy2 + shift);
        ctx.lineTo(widthBy2, heightBy2 + shift);
        ctx.closePath();
        this._renderFill(ctx);
        this._renderStroke(ctx);
    },
    _calculateCurrentDimensions: function(shouldTransform)  {
      var vpt = this.getViewportTransform(),
          w = this.width,
          h = this.height;

      w = w * this.scaleX + 2 * this.padding;
      h = h * this.scaleY + 2 * this.padding;
      if (shouldTransform) {
        return fabric.util.transformPoint(new fabric.Point(w, h), vpt, true);
      }
      return { x: w, y: h };
    },
});
Tested with different width and height combinations
Tomorrow I'll work with star - it is an polygon, and maybe find some solution.
You have some mistake with line stroke for the same width and height figure became large then they seted size. I have correct it for rectangle and circle if you'll need can give the code

**Comment by delian7** [comment]
@webmak: have you found an solution for polygons? I've been struggling with this issue. @asturur is there a fix in the works to this issue.

**Comment by webmak** [comment]
@delian7: Hello. For my work was not needed polygons so I've not worked with them

**Comment by ncou** [comment]
Solved in the latest version of fabric.js (v1.7.16)
http://jsfiddle.net/dHhmQ/8/

The corner of the triangle is no more cropped.

BEFORE :
![image](https://user-images.githubusercontent.com/16743322/27992922-99603200-649f-11e7-827b-7ea2eeac4447.png)

NOW :
![image](https://user-images.githubusercontent.com/16743322/27992929-a3d68522-649f-11e7-9a60-e9d9ddc403b4.png)

**Comment by asturur** [comment]
I wish it would that easy. that effect is because we added a bit more canvas space around the object to avoid resizing at each pixel.

The main point of this issue, that is open since 4 years is that we do not have a way to calculate the correct bounding box of a shape stroke included.

While this is a simple trignometry problem for triangles, when we go to polygons and paths it becomes hard. is a pure math problem.

The more the angle is acute, the farthest the stroke is gonna cross each other.
a 0.1 degree angle cross sooooo far away

**Comment by asturur** [comment]
Look the same triangle copy pasted in inkscape ( a vector design tool ) grows big with stroke to 4mm

![image](https://user-images.githubusercontent.com/1194048/27993037-88e49de2-64a1-11e7-973b-145ca555f01a.png)

the red long triangle and the triangle with black thin stroke are the same triangle, but the bigger stroke, the acute angle and the miter limit capped to 100 ( more is not allowed there ) creates that.

**Comment by asturur** [comment]
and is not just the extension. you have to calculate how the tip, made of 3 point is oriented respect to the bounding box. Is a fun mess to solve. I wonder how much it will slow down everything.

**Comment by ncou** [comment]
Yes i understand, I haven't checked the comment in #3944 ticket closed above.
Getting the right BBox seems like a real headache.

**Comment by panthar1** [comment]
I have ran into this same problem. Thinking about this conceptually, seem like all you really need to know for something like a polygon, is the smallest-x, the largest-x, smallest-y, and largest-y points on the object. Then add the strokeWidth to it, and calculate/transform the bounding box based on that? Maybe if I have some time I will look into this, seems solvable if you do it in two steps like that.

**Comment by ncou** [comment]
do you think using a bbox function like the one present in Raphael.js could do a better job ?
https://github.com/DmitryBaranovskiy/raphael/blob/master/dev/raphael.core.js#L3720

**Comment by panthar1** [comment]
My main concern is that it has enough canvas space required to render the polygon without cutting it off. If we can fix the bounding box as well, that would be great too. @ncou Never seen or used Raphael.js, but the function looks close to what I had in mind.  In particular that pathDimensions() function.

**Comment by asturur** [comment]
some resources

https://math.stackexchange.com/questions/527005/find-value-of-t-at-a-point-on-a-cubic-bezier-curve

[Bezier_curves.pdf](https://github.com/fabricjs/fabric.js/files/2775532/Bezier_curves.pdf)

**Comment by melchiar** [comment]
Not sure if this will be of help, but there's a lengthy discussion on the paper.js github tackling this issue (specifically as it applies to stroke outlining) https://github.com/paperjs/paper.js/issues/371

Working demo here: http://bl.ocks.org/sapics/raw/d10f455b8ec1e54a46cf04ed2b386334/

**Comment by asturur** [comment]
Yes there there is all we need and more.
To be honest i do not want to get into stroke->path with fill.
I just want to calculate the bbox of it.

i may start to think that that is a necessary conversion.

If there is an alghoritm behind a paywall i can buy it.

**Comment by rsKliPPy** [comment]
Can we just overestimate the size for the cache canvas? I don't know know the rendering process of Chrome, but it does overestimate the size of SVG objects in DevTools when you hover over them. Here's a path with `strokeMiterLimit = 8`.
![](https://i.imgur.com/spMJLTs.png)

I encountered the same issue with stroke corners being cut off, so to combat this I increased the width and height of every object by `(this.strokeMiterLimit - 1) * this.strokeWidth`, only if `this.strokeLineJoin === 'miter' && this.strokeMiterLimit >= 1`. I don't like this hack, but it worked well so far.

**Comment by asturur** [comment]
just a note here that when this gets fixed, grants a major bumb in the library version.
once this is fixed, width/height will change and old saved jsons with sharp angles will reload in different positions.

**Comment by melchiar** [comment]
That's a good point, although I suppose one solution would be to provide some example code for translating object positions when loading json from previous fabric versions (similar to the code in the http://fabricjs.com/v2-breaking-changes for dealing with  the height/width behavior changes in the image class)

**Comment by tkachukcha** [comment]
The issue with polygon is still there
<img width="253" alt="image" src="https://user-images.githubusercontent.com/20718976/205625142-5e9ca3d9-dece-4202-8cd8-d858888e30bc.png">

**Comment by ShaMan123** [comment]
not on v6/master
