### ISSUE TITLE
Free Drawing does not work in Firefox > 66 with the stylus of a Microsoft surface.

### ISSUE THREAD

**Issue by bricejar** [fabricjs/fabric.js#5801]
## Version
2.4.0

## Test Case
http://fabricjs.com/freedrawing

## Information about environment
Nodejs or browser? Browser
Which browsers? Firefox > 66

## Steps to reproduce

Try freedrawing on http://fabricjs.com/freedrawing with a Stylus and a Microsoft Surface with the last version of Firefox (68)

## Expected Behavior

To be able to draw.

## Actual Behavior

Nothing happens when using the stylus. It works in Chrome and Firefox 65.

**Comment by asturur** [comment]
i have a branch that fixes it, please follow here:
https://github.com/fabricjs/fabric.js/pull/5785
