### ISSUE TITLE
Weird issue with canvas toDataURL method, the base64 result is 2x the expected size

### ISSUE THREAD

**Issue by malkhuzayyim** [fabricjs/fabric.js#5802]
I created a stackoverflow question about this, wanted to link it here for exposure as well: https://stackoverflow.com/questions/57022091/canvas-todataurl-image-result-png-base64-size-is-larger-than-expected-twice-a

Issue brief:

I've got FabricJS running, a user can add text/images on a product, manipulate them, then purchase the product. My plan is as the user finishes the design, I would export the canvas as png base64, and send it to the server in JSON (it'll be somewhat large, but i can take that hit, i have to, to preserve printing quality).

The canvas size i'm working with is - width: 1600 & height: 2400

I am expecting base64 images to be 137% of the original size of their PNG counterparts, but what I am getting is about 280% the original size.

The test I did was:

- add anything to the canvas
- export and console.log the base64 image
- used multiple tools online to decode base64 to png, and then encode back to base64, and these are my results:

Test 1 - Adding a full size image & exporting it:

1. Initial base64 image size on canvas export: 12.6mb

2. After converting to PNG: 4851 kb

3. After encoding the same PNG back to base64: 6576 kb (this is the size i am expecting on initial export)

4. After decoding the resulting halfsize base64 back to PNG again: 4851 kb (the exact same result as the large base64)

Test 2 - Done with a simple text element, pretty much the same result ratios.

Main online tools I've used for encoding/decoding are:

- https://onlinepngtools.com/convert-base64-to-png
- https://www.base64encode.org/

The method I am using to export the canvas (its built in vueJS, irrelevant info but just for context):
```
    exportCanvas() {
      const exportedArt = this.canvas.toDataURL({
        format: "png"
      });
      this.exportedArt = exportedArt;
      const exportedArtThumbnail = this.canvas.toDataURL({
        format: "png",
        multiplier: 0.2
      });
      console.log("Exported Art:", exportedArt);
      console.log("Exported Thumbnail:", exportedArtThumbnail);
    }
```

I tried checking the pixelRatio thing, my device has a pixel ratio of 1, so thats not the issue. I also know the whole "retinaScaling" thing isn't an issue here.

What am I missing?

**Comment by asturur** [comment]
if you display the dataurl in an image tag, and then do right click -> save image as, how much big is the image compare to base 64?

**Comment by malkhuzayyim** [comment]
If i display it in an img tag, then "save as", i get the 4851kb size, which matches size after converting to PNG using that online tool. The original exported base64 is still 12.6mb though.

**Comment by malkhuzayyim** [comment]
the exported base64 at 12.6mb is almost exactly 2x the base64 size I am expecting, which should be 6576 kb, so i think there is something i am missing here causing it to double the base64 size in the original export which i should be able to eliminate. Any thoughts?

**Comment by malkhuzayyim** [comment]
Okay wait, I just copied the same base64 string and pasted it in a string size checker, and i am getting the expected size from the original export (not double the size). The original 12.6mb was my reading from the chrome console.log, and that reading is just wrong it seems.

There is nothing wrong with my base64 export. Sorry for the confusion.

Altho since we already started this discussion, any idea what might be causing this mis-read from the chrome console on string sizes?

**Comment by malkhuzayyim** [comment]
Just leaving it open a little longer incase u want to add any opinion on this. Gonna close the issue soon.

**Comment by asturur** [comment]
we can continue the discussion with the closed issue. Since there are no bug to fix or investigation to do in the library, is fine as closed.

**Comment by malkhuzayyim** [comment]
cool, thanks
