### ISSUE TITLE
straightenObject doesn't work?

### ISSUE THREAD

**Issue by zavodnyrichard** [fabricjs/fabric.js#5805]
I don't know if I didn't understood the **straightenObject**, **straighten** functions properly, but I guess it is supposed to lock the rotation when it's close to the 90 deg. multiples (0, 90, 180, 270), but this doesn't work that way. So my question (and yes I'm aware this is issue tracker, but I haven't got answer on Google Groups), how can I achieve this functionality, as it is done on your printio.ru, that you lock the rotation on 45 deg. multiples? 

Here is the functionality, I'm trying to implement:
https://youtu.be/S5keukSG1ag

**Comment by asturur** [comment]
i have no idea on what version of fabric is printio.ru, but lately we introduced a snap to angle feature for rotation.

http://fabricjs.com/docs/fabric.Canvas.html#snapAngle

**Comment by zavodnyrichard** [comment]
How to apply this snapAngle functionality? I'm kinda lost.

**Comment by asturur** [comment]
just set it to a number, like 45

**Comment by zavodnyrichard** [comment]
Well yes, it snaps now. But still it is not what I expected. It snaps only every 45°, but I'm not able to rotate it to anything between, like 35°, 56°, 93°, etc., because it only snaps on every 45°. I need it to snap every 45°, but also be able to choose whatever other value.

What does the **snapThreshold** actually do?

**Comment by asturur** [comment]
what is written over it? is it missing a description?

**Comment by zavodnyrichard** [comment]
> Indicates the distance from the snapAngle the rotation will lock to the snapAngle. When `null`, the snapThreshold will default to the snapAngle. 

Not really sure what this does tho.

**Comment by asturur** [comment]
so if snap treshold is for example 5, and snapAngle 45, i think this will happen:

from -5 to 5 it will snap to 0, from 5 to 40 will be free rotation, and from 40 to 50 will snap to 45.

So maybe you want a small treshold, like 1 or 2 just to get a light sensation of snapping.

**Comment by zavodnyrichard** [comment]
Oh, thank you man. I got it working like I wanted. Thanks man! :)
