### ISSUE TITLE
I can't get object Id in latest version. It works in version 2.x.x 

### ISSUE THREAD

**Issue by iamappmaker** [fabricjs/fabric.js#5806]
this.canvas.getActiveObject().id returns undefined

 for (var i=0;i<this.canvas.getObjects().length;i++){ 
    var myid = this.canvas.getActiveObject().id;
    if(myid==99) {this.canvas.getActiveObject().remove();}
console.log(myid);
  }

It consoles all object id as undefined.

Is that bug or i am doing it wrong

**Comment by asturur** [comment]
There are no ID if you do not set them.
Please open a fiddle as requested in the issue tracker.
I'll reopen the issue as soon as a reproducible case is available.
