### ISSUE TITLE
Custom JSON to DataURL

### ISSUE THREAD

**Issue by homescript1** [fabricjs/fabric.js#5807]
Hello!

I'm facing an issue, using fabric JS version : 2.4.6

I have a canvas with some dimensions and I'm making some edit on it, when I have finished to work on it, I have stored some customs values (width and height), this one i use them to change the canvas width and height, at the end I get a JSON, now i want change this JSON  into dataurl or imageurl like that I can allow download from my browser. How can i achieve that?

**Comment by asturur** [comment]
please post this question on stackoverflow, following guidelines, post the link here in the issue, you'll get answers.
