### ISSUE TITLE
Text Shadow overlapping Previous character

### ISSUE THREAD

**Issue by sagarvibrant** [fabricjs/fabric.js#5808]
![shadowtest](https://user-images.githubusercontent.com/36664189/61451395-de296280-a976-11e9-9e46-c576ddca1da5.jpeg)

Text Shadow overlapping Previous character of my textBox.
I facing this issue after i change charSpacing of textbox.
thank you

**Comment by asturur** [comment]
i would expect this to happen with a version before 1.7 or with object caching disabled.

Can you reproduce with a fiddle as requested by the issue template?
