### ISSUE TITLE
Paths in path created not cleared properly when removing all objects.

### ISSUE THREAD

**Issue by niels-van-den-broeck** [fabricjs/fabric.js#5814]
## Version
Upgrading from 3.2.0 to ^3.3.0

## Test Case
https://codesandbox.io/s/vigilant-ptolemy-n2ztg

## Information about environment
browser

Which browsers?
All

## Steps to reproduce
Open sandbox and alternate between v3.2.0 and 3.3.0.
Draw a couple of paths

## Expected Behavior
No black paths remain. All paths are red.

## Actual Behavior
In 3.3.0 the last black path remains, but is not listed in the canvas objects

**Comment by niels-van-den-broeck** [comment]
Possibly having issues with an object which remains on the upper-canvas?

**Comment by asturur** [comment]
definitely something broke.

**Comment by niels-van-den-broeck** [comment]
> Possibly having issues with an object which remains on the upper-canvas?

Scrap this. Doesn't seem to be the case. I am oblivious as to what may have happened.

**Comment by niels-van-den-broeck** [comment]
Have been searching a bit yesterday. Totally oblivious as to what is happening

**Comment by niels-van-den-broeck** [comment]
@asturur Wondering if there were any updates on this?

**Comment by niels-van-den-broeck** [comment]
Changing renderAll to requestRenderAll in the brush resolves the issue. Still searching why this might be the case
