### ISSUE TITLE
control not visible outside context 2d rectangle. 

### ISSUE THREAD

**Issue by RoopkamalOrem** [fabricjs/fabric.js#5817]
Hello Team Fabric,

I m trying to create customizable product options to my store, for that I was trying the fabric js to implement and test it. 
Please check this link ( http://appmantechnologies.com/roop/Canvas/ ).
I have used below code to create a rectangle so that user can have a bounded area to manage the images in it:
var ctx = canvas.getContext("2d");
    ctx.beginPath();
    ctx.rect(100,100,200,200);
    ctx.closePath();
    ctx.stroke();
    ctx.clip();

this displays a rectangle and working as well but when I scale the image insaide the rectangle to be outside it then the controls are hided. It seems the controls are working outside the rectangle but they are visible. 
Please check this video link for more info. ( https://www.loom.com/share/c092058dc4cf4ebba310a0f5c7595ada )

I found one github link that says I have to use "controlsAboveOverlay" ( https://github.com/fabricjs/fabric.js/issues/2468 ), but I don't know where to add this?

Please let me know solution for this issue ASAP. 

Regards,
Roop

**Comment by sagarvibrant** [comment]
Can you reproduce with a fiddle ?

**Comment by asturur** [comment]
controlsAboveOverlay is a Canvas property. ClipTo is deprecated. How are you exactly clipping?

**Comment by RoopkamalOrem** [comment]
I have  created a fiddle. ( https://jsfiddle.net/Roopkamal/7qLbkm8t/25/ )Please check the dog image which is clipped in bounded box and it is absolutely correct. 
But I want the image which is uploaded dynamically by user to be also be also in this same rectangle.
Means I want this bounded box to be the only customization area how much images will be uploaded they all must be in that same box.

please check and let me know how we can implement this.

**Comment by RoopkamalOrem** [comment]
is there anybody to help me out of this?

**Comment by sagarvibrant** [comment]
How to Generate fabric canvas like shutterstock tool ? 
https://www.shutterstock.com/editor/image/

**Comment by asturur** [comment]
instead of clipping you can use different solutions.
You can either add an overlay that will darken/lighten the external area or you can paint it with a globalCompositeOperation that will make things opaque.

instead of create a rect create an overaly that has a rectangular shape hole.
