### ISSUE TITLE
FabricJS group region does not drag instantly after making it group

### ISSUE THREAD

**Issue by albert-hoffman** [fabricjs/fabric.js#5820]
## Version
3.1.0

## Information about environment
browser
All browsers

## Steps to reproduce
In FabricJS I have multiple individual texts that I made group on mouse:down event, after that it is not dragging while mouse:down. it requires me to click outside then drag again.

```
         canvas.on('mouse:down', event => {                   
                    const sel = new fabric.ActiveSelection(child, {
                        canvas: this.canvas[index]
                    });
                    sel.setControlsVisibility({
                        mtr: false,
                        mb: false,
                        ml: false,
                        mr: false,
                        mt: false
                    });
                    sel.setOptions({
                        cornerStyle: 'circle',
                        transparentCorners: false
                    });

                    canvas.setActiveObject(sel);

                    sel.setCoords();

                    canvas.renderAll();
       });
```

## Expected Behavior
It should allow both at the same time. I should able to drag while I am doing mouse:down.

## Actual Behavior
It does not allow both at the same time. I should able to drag while I am doing mouse:down.

**Comment by albert-hoffman** [comment]
Finally found a good solution for it: just call this function

`canvas._setupCurrentTransform(event.e, sel);`

**Comment by asturur** [comment]
hi @albert-hoffman, another solution, less hacky, would be to use the event `mouse:down:before` this will allow to create the group before all the other logic runs, at that point you do not need the custom call to `canvas._setupCurrentTransform` that is a private method and likely to have changes in non major version.

**Comment by asturur** [comment]
let me know if it works.

**Comment by albert-hoffman** [comment]
@asturur thanks for your reply, I also applied the same solution some days back and it works. see here too. https://stackoverflow.com/questions/57266217/fabricjs-mousedown-and-drag-are-creating-conflicts-with-each-other
