### ISSUE TITLE
Moving behind the scenes makes element unreachable

### ISSUE THREAD

**Issue by theBork** [fabricjs/fabric.js#5826]
## Version
1.7.16

When I move object in canvas behind the scenes, there is no way to catch it after. Is Fabric JS have any tricks to fix it? Maybe with limit of object moving or something else?

**Comment by asturur** [comment]
hi @theBork , fabric 1.7 is long way out of support and help for me, is also a bit unclear what are you asking. I will close the issue, and reopen when more information come.
