### ISSUE TITLE
No border using ClipPath 

### ISSUE THREAD

**Issue by jaspreet9319** [fabricjs/fabric.js#5827]
I am using fabric js clipPath part 3 from your provided tutorial (http://fabricjs.com/clippath-part3) , I have used 2nd option from this clipPath which is apperence of controls outside the clipPath. 
 
clipPath is working fine but there is no such option to add border to the rectangle which I have used as clippath. I have tried adding border to the rectangle directly but that also doesn't seems to be working for me. However the background color is wokring when I add background color to canvas. Please help me how to add border using clipPath function.

please check below fiddle link and let me know how to add border in this clipPath rectangle:-
https://jsfiddle.net/jaspreet123/hgo716qa/12/

**Comment by asturur** [comment]
to be as much similar to a clipTo command and to SVG clipPath, clipPaths are without border by definition.

```
  //myCanvas.setBackgroundColor("#00CCEE");
	myCanvas.set({
		backgroundColor:"#00CCEE",
		fill: "",
		strokeWidth: 5,
		stroke: "red",
		hasBorders: true,
		borderColor:"#3ff4ff"
	});
```

Those properties about border set on the canvas have no effect.

**Comment by zavodnyrichard** [comment]
Is there any feasible way to workaround this?

**Comment by asturur** [comment]
clippath are without border by definition. We could do masks from clippath code, but i have very few tine lately

**Comment by khajaordant** [comment]
Did anyone got this ready or working with any workaround ?

**Comment by zavodnyrichard** [comment]
> 
> 
> Did anyone got this ready or working with any workaround ?

Yes. I simply did created an rectangle of the size of the ClipPath and styled it as I wanted (striped border for ex.).
