### ISSUE TITLE
NS_ERROR_FAILURE in firefox retina display for canvas size over 5590px

### ISSUE THREAD

**Issue by rahulserver** [fabricjs/fabric.js#5828]
## Version
3.3.0

## Test Case
http://jsfiddle.net/z2kgqub9/

## Information about environment
Firefox 68.0.1 on MAC or retina mode enabled( heres how to do on non MAC systems http://kirinyan.net/retina-display-emulation-with-firefox/ )

## Steps to reproduce
Create a canvas with either width and height over 5590px
## Expected Behavior
Should work normally like non retina display browsers. 
## Actual Behavior
Gives the NS_ERROR_FAILURE with full trace as:

```
NS_ERROR_FAILURE: fabric.js:6697
    _initRetinaScaling https://rawgithub.com/kangax/fabric.js/master/dist/fabric.js:6697
    _initInteractive https://rawgithub.com/kangax/fabric.js/master/dist/fabric.js:9482
    initialize https://rawgithub.com/kangax/fabric.js/master/dist/fabric.js:9205
    klass https://rawgithub.com/kangax/fabric.js/master/dist/fabric.js:2118
    onload http://fiddle.jshell.net/_display/:38

```

On chrome for MAC, it works fine.

**Comment by asturur** [comment]
You are probably creating a too big canvas. How much over 5590 pixels are you?
If you add a scaling of 2x Fabric will create a canvas bigger than 11180px width and height, that starts to be really big and slow.

You can disable retina scaling in fabric for example, or create a smaller canvas.

For me on firefox mac it works with the 6000 pixels example.
