### ISSUE TITLE
How can I cancel animation?

### ISSUE THREAD

**Issue by silverlovesl** [fabricjs/fabric.js#5829]

**Comment by silverlovesl** [comment]
The fabric.util.animate doesn't return any thing after calling. So how can I cancel requestAnimationFrame?

**Comment by asturur** [comment]
good question, i have to check.

**Comment by kumayato** [comment]
I these two days have also met this question

**Comment by asturur** [comment]
I'm not completely updated on the thing, i just quickly checked.
On the animate options you can pass an abort callback.
When abort function returns a truthy value the animation will stop.

The point is that as today that function does not seems to take any argument, so it has to depend on external values.

**Comment by asturur** [comment]
Needs to be improved at least.

**Comment by RaidPRDev** [comment]
using Fabric 5.2.1

I also needed a way to cancel the animation myself, so for anyone looking for a way.
Save the return on the animation() call.  The return is an Array with a cancel function. 
Then use it to call the cancel the animation.

Simple example below.  Hope this helps someone.

`
// create your shape, etc...
let theShape = new fabric.Circle(someOptions);

// animate it...
// from what I gather, the animate function returns an Array with its first item as a function
let theShapeAnim = theShape.animate({ radius: 100 }, {
     duration: 500,
     easing: fabric.util.ease.easeOutCubic
});

// somewhere down in your code....
// cancel animation, the following just double checks and ensures the shapeAnim is a function
if (theShapeAnim.length > 0 && typeof theShapeAnim[0] === "function") theShapeAnim[0]();
`
