### ISSUE TITLE
the toJSON of Canvas can not save the all stylesheet of object(rect、circle etc) 

### ISSUE THREAD

**Issue by GDUT-Rex** [fabricjs/fabric.js#5830]
I have set the stylesheet of rect,but when i  make it to JSON and after read it from JSON with loadJSON,the rect has lost stylesheet.So i have to reset the stylesheet about the rect.
```javascript
    var Rect = new fabric.Rect({
      fill: 'red',
      width: 100,
      height: 100,
      left: 100,
      top: 100,
      // the lost properties
      lockRotation: true,
      borderColor = '#0077FF'
      cornerColor = 'white'
      cornerStrokeColor = '#CCCCCC'
      cornerSize = 6
      padding = 1
      hasRotatingPoint = false
     transparentCorners = false
    })
```

**Comment by asturur** [comment]
There is no stylesheet for objects.
There are some properties that do not get saved by default.
You can either save them using to object with `propertiesToInclude`

http://fabricjs.com/docs/fabric.Object.html#toObject

Or you can set up the properties that are common to all objects ( if they are ) on the object prototype.

```
fabric.Object.prototype.cornerColor ='white';
```
