### ISSUE TITLE
scale object in fabricjs

### ISSUE THREAD

**Issue by laibinweb** [fabricjs/fabric.js#5831]
I'm implementing a function that restricts the scaling of elements beyond boundaries. The current version of fabric.js I use is 2.7.0. Listening for scaling events finds that the element attributes obtained by the getBoundingRect () method are not updated in real time, but the 1.7.3 version is updated in real time. I don't know if there are parameters that can be set to allow the element to be updated in real time. Scale and size. Thank you.

**Comment by asturur** [comment]
Hi @laibinweb `getBoundingRect` has 2 parameters:
http://fabricjs.com/docs/fabric.Object.html#getBoundingRect

The first let you choose if you are working with the coordinates ignoring canvas zoom, the other to  calculate position on the fly.

Depending on what you are actually doing, i suggest you to either call Object.setCoords during the scaling event, or set the second argument as true.
