### ISSUE TITLE
gesture module

### ISSUE THREAD

**Issue by ynnyh** [fabricjs/fabric.js#5832]
I use `npm install fabric --save`, But I found that it does`t include gesture module,What should I do?Thank you very much!

**Comment by asturur** [comment]
I'll add it in with the 3.4.0 release so you can have a custom build out hof npm
Gesture module is not that much supported right now, i ll try to switch to something better as soon as i have time to understand it properly.

**Comment by ynnyh** [comment]
Thank you for your response,hope this version will come soon...
