### ISSUE TITLE
How to Generate fabric canvas like shutterstock tool ?

### ISSUE THREAD

**Issue by sagarvibrant** [fabricjs/fabric.js#5833]
How to Generate fabric canvas like shutterstock tool ?

https://www.shutterstock.com/editor/image/cake-macaron-macaroon-on-turquoise-background-418367578?exit=%2F&ref=lohp

I want to use object controls outside from Drawing area and Generate that drawing area as Image.

**Comment by bhaskardas9475** [comment]
I have the same question. I want to define an art-board kind of thing as work area, where size can be anything like shutterstock editor.

**Comment by sagarvibrant** [comment]
Any Update on this ?

**Comment by asturur** [comment]
There is a custom overlay there, but all the rest is real plain fabric usage with viewport. ( zoom and pan ).

**Comment by itsmemanoj** [comment]
> How to Generate fabric canvas like shutterstock tool ?
> 
> https://www.shutterstock.com/editor/image/cake-macaron-macaroon-on-turquoise-background-418367578?exit=%2F&ref=lohp
> 
> I want to use object controls outside from Drawing area and Generate that drawing area as Image.

Did you find anything bro?

**Comment by roadwild** [comment]
> > How to Generate fabric canvas like shutterstock tool ?
> > https://www.shutterstock.com/editor/image/cake-macaron-macaroon-on-turquoise-background-418367578?exit=%2F&ref=lohp
> > I want to use object controls outside from Drawing area and Generate that drawing area as Image.
> 
> Did you find anything bro?

I have the same problem, do you have a solution bro?
