### ISSUE TITLE
Emit click events by coords x, y 

### ISSUE THREAD

**Issue by VinAr22** [fabricjs/fabric.js#5834]
Hi! I started to develop the project using three.js and fabric.js, where i can move and transform texture on the 3d model. I finded coords on model and sync it with coords on canvas fabric js. But i don`t know how to simulate click event and get full manage this clicked objects. I finded the stackoverflow topics that demonstrate my problem. Much thanks!

1) https://stackoverflow.com/questions/53609015/programmatically-select-object-in-a-fabricjs-canvas-from-coords

2) https://stackoverflow.com/questions/52840486/raycast-mouse-clicks-from-threejs-model-to-the-fabricjs-canvas-used-for-the-text

3) https://stackoverflow.com/questions/52877822/emit-click-events-from-one-canvas-to-another

Codepen: 

https://codepen.io/ricardcreagia/pen/EdEGod

**Comment by asturur** [comment]
https://stackoverflow.com/questions/52877822/emit-click-events-from-one-canvas-to-another/57452275#57452275

**Comment by VinAr22** [comment]
Unfortunately, this solution dont work. Can you provide an example code?

**Comment by VinAr22** [comment]
Please, look at this example 
https://codepen.io/vinar22/pen/aejmdp
