### ISSUE TITLE
fabric.js how to use fromObject api

### ISSUE THREAD

**Issue by laibinweb** [fabricjs/fabric.js#5835]
I want to implement importing data from one template into another without affecting data from the other.Using deserialization API loadFromJson will empty the canvas data first, so I want to use toObect method to export the data, and then use toFromObject to import, but the object cannot display correctly after the import, may I ask if there is any solution?Or is there another implementation?thank you

demo: https://jsfiddle.net/laibin/gpvef0k5/2/

**Comment by asturur** [comment]
i think you can use enlivenObjects:
https://jsfiddle.net/8nutyeq6/1/
