### ISSUE TITLE
Export Circle with endAngle greater than 2 * Math.PI to SVG not correct

### ISSUE THREAD

**Issue by mediumhust** [fabricjs/fabric.js#5837]
## Version
3.3.2

## Test Case
https://jsfiddle.net/tinyhustlee/c3gop1z9/44/

## Information about environment
Browser: Chrome, Firefox

## Expected Behavior
http://prntscr.com/oqv0ay
## Actual Behavior
http://prntscr.com/oqv0cf

Related issue [5053](https://github.com/fabricjs/fabric.js/issues/5053)
but they haven't a same reason.

**Comment by asturur** [comment]
why we think is not correct?
Angle get transformed for the reminder of a division by 2*Math.pi

I also wonder if the export should be a slice cacke rather than this.
