### ISSUE TITLE
Emit click events from one canvas to another

### ISSUE THREAD

**Issue by VinAr22** [fabricjs/fabric.js#5839]
First, thanks for the support. I already wrote here 3 days ago. You advice me to use element.dispatchEvent in this topic:

https://stackoverflow.com/questions/52877822/emit-click-events-from-one-canvas-to-another/57452275#57452275

Click event works, but not correctly
Please, look at this code:

https://codepen.io/vinar22/pen/aejmdp

Thank you!

**Comment by asturur** [comment]
please reuse the old issue

**Comment by VinAr22** [comment]
I wrote you there 

https://github.com/fabricjs/fabric.js/issues/5834#issue-478802582
