### ISSUE TITLE
Can not Find Actual Position x y of objects on canvas

### ISSUE THREAD

**Issue by JonathanDn** [fabricjs/fabric.js#5840]
How can I easily get the pixel positions of a certain object on the canvas?
For example in a 1000px by 500px canvas. If I have certain points that are outside the canvas from the top and some are inside. How can I access the x and y relative to the visual canvas(1000x500px) ?

**Comment by asturur** [comment]
@JonathanDn is unclear what are you trying to solve, please follow the procedure for asking help, following the stackoverflow suggestion.
