### ISSUE TITLE
It is possible to move locked objects when multiple objects are selected 

### ISSUE THREAD

**Issue by orian** [fabricjs/fabric.js#5843]
## Version
3.3.0

## Test Case
https://jsfiddle.net/n98p52ov/

## Information about environment
In all supported browsers.

## Steps to reproduce
1. Add more than one object with all locks (lockMovementX, ...)
2. Select multiple objects.
3. Try to move them.

## Expected Behavior
None of objects move.

## Actual Behavior
Objects moved.

**Comment by asturur** [comment]
Yes this is not a bug, i think it has been discussed also somewhere.

If you want to support something like this, use the selection events so that when a user select multiple objects you can inspect them and eventually lock the active selection movement.

**Comment by davNazaryan** [comment]
Have the same issue.
I didn't find any way to handle it.
I think at least it must be configurable.

> If you want to support something like this, use the selection events so that when a user select multiple objects you can inspect them and eventually lock the active selection movement.
@asturur Can you please send a link with an example? I googled a lot but my little knowledge of fabric make this process really hard.

**Comment by asturur** [comment]
i ll try to make an example today.

**Comment by asturur** [comment]
https://jsfiddle.net/Lun395qv/

Sorry for the delay, this is an example

**Comment by anujparekh18** [comment]
I just had a look into the fiddle. The thing is, if I select both objects with mouse, it forms a group and then when I try to move the group, it doesn't move. This is fine. But when you group both objects by using shift + click, we are able to move the group.
@asturur can you let me know how to solve this??

**Comment by asturur** [comment]
add the same code to `selection:updated`

**Comment by anujparekh18** [comment]
Yep, working like a charm. Thanks @asturur :-)

**Comment by rolitter** [comment]
> 是的，像魅力一样工作。谢谢
This method does not work in version 5.2.1
Because the params have been change
https://codepen.io/rolitter/pen/wvYpJER
