### ISSUE TITLE
Minified version 3.3.2 reports version 3.2.0

### ISSUE THREAD

**Issue by awehring** [fabricjs/fabric.js#5844]
## Version
3.3.2

Minfied version 3.3.2 at cloudflare reports version 3.2.0

## Information about environment
Browser (any)

## Steps to reproduce
Load: `https://cdnjs.cloudflare.com/ajax/libs/fabric.js/3.3.2/fabric.min.js `
Enter at the browser console: `fabric.version`

Or look at the first line of the file.

Non-minified version ist ok (`https://cdnjs.cloudflare.com/ajax/libs/fabric.js/3.3.2/fabric.js`)

## Expected Behavior
reports "3.3.2"

## Actual Behavior
reports "3.2.0"

**Comment by asturur** [comment]
it happende because i had to republish the same file for npm issues i created. Next version will be 3.4.0 and will be aligned again

**Comment by awehring** [comment]
ok, thanks for the information !
