### ISSUE TITLE
Laggy zoom behavior using touch events

### ISSUE THREAD

**Issue by rovervannispen** [fabricjs/fabric.js#5846]
## Version
2.4.0

## Test Case
Can't provide a jsfiddle since that is not working on mobile. [I've added a video instead](https://streamable.com/lf5gu)

## Information about environment
Mobile browsers like Chrome and Safari

## Steps to reproduce

_Note: I'm using fabricjs with touch events_

1. Create a new canvas (in my case with the dimensions 1800x1200)
2. Pick photo and add image data to canvas
3. Drag the image to change position (works great)
3. Pinch photo to zoom (strange behavior)

## Expected Behavior
Zooming from the center and smooth animation for growing and shrinking 

## Actual Behavior
When the image is pinched it is also changing position. When the image gets bigger or smaller there is a strange cropping effect that will go away once you release the image. The image gets scaled from the top left corner instead  of the center

**Comment by asturur** [comment]
pinch to zoom us not an embedded feature.
The gesture.module connects it to a scale action on the selected object. I think we should.remove.it and make it more customizable just generating an 'onpinch' event.
