### ISSUE TITLE
Inconsistent behavior for .set function and some keys that needs numbers.

### ISSUE THREAD

**Issue by Roinoss** [fabricjs/fabric.js#5847]
## Version
2.4.0

## Test Case
http://jsfiddle.net/v5f2wzyg/2/

## Information about environment
Firefox, JS/JQuery

## Expected Behavior
Allow to pass strings that can be interpreted as number in canvasItem.set('key', 'number') in all
cases.

## Actual Behavior
Inconsistent, for some keys (tested for 'left' and 'top') .set function need to have passed number and for some keys are acceptable strings (parseable) or numbers (tested for angle).

For left and top (canvasItem.set('left', '20')) changed by string, canvasItem just disappear.

**Comment by asturur** [comment]
Well the docs asks for numbers. And you have to pass numbers
If there are division ( like angle divided by Math.PI * 2 ) it can be implicitly converted as number, but this is a side effect and should not be considered as a feature.
You have to pass numbers.
