### ISSUE TITLE
lockScalingY=false/lockScalingX=false not working when fabric.Textbox doesn't packaged

### ISSUE THREAD

**Issue by mikab** [fabricjs/fabric.js#5850]
## Version
3.2.0

## Test Case
https://jsfiddle.net/mikabpeng/e9s3tdqo

## Information about environment
Chrome  74.0.3729.169

## Steps to reproduce
Use a custom build fabric.js exclude fabric.Textbox class
Create a fabric.Rect and set lockScalingY= false, lockScalingX= false
Click the rect to make the rect selected
drag the middle or center control point to zoom the rect

## Expected Behavior
The rect zoomed as dragging

## Actual Behavior
The rect didn't zoom as dragging. A javascript exception thrown in the background:fabric.3.2.0_without_textbox.js:9685 Uncaught TypeError: Right-hand side of 'instanceof' is not an object
![exception](https://user-images.githubusercontent.com/7811209/63328444-c1f85700-c362-11e9-9002-1f876df34ee0.PNG)

**Comment by asturur** [comment]
right.... this should be fixed.
Need to check that the class has been imported/added to the build.
