### ISSUE TITLE
setClipTo is not a function

### ISSUE THREAD

**Issue by mehrdadmraad** [fabricjs/fabric.js#5851]
Hi,

setClipTo is not available in newer versions of fabric.js (currently I'm using version 3.4.0), but when switching back to older versions (checked with version 1.7.11) there is no such error!

![image](https://user-images.githubusercontent.com/3070795/63425146-2845ae00-c425-11e9-866d-fdaab27c1a29.png)

Would you please let me know how to replace setClipTo with a newer alternative?

Thankx

**Comment by asturur** [comment]
set('clipTo', ..... )


but clipTo is deprecated and will be removed in fabric 4. Please try if clipPath(s) fit your use case

**Comment by mehrdadmraad** [comment]
Thanks a lot,

clipTo works fine now, I'll try to use clipPath as well.

Regards
