### ISSUE TITLE
Image SVG Export 

### ISSUE THREAD

**Issue by Obiwarn** [fabricjs/fabric.js#5854]
UPDATE: Ok. Took me ages to find the related issue (https://github.com/fabricjs/fabric.js/issues/4011).
However, why not increase fabric.Object.NUM_FRACTION_DIGITS during SVG exports in advance? 

When you add a image (e.g. 5000 x 2000 pixels) to canvas and scale to a fixed width (e.g. 400 x 250 px) then the image is scaled a little too small on SVG export. This effect gets more with larger images.

This is in my fabric.js canvas with a large image. The black rect dimensions are equal to the scaled image dimensions.
![image](https://user-images.githubusercontent.com/9539797/63596090-b7d09580-c5ba-11e9-9508-ead7bffc2cd6.png)

This is the SVG export. See the shrinked image.
![image](https://user-images.githubusercontent.com/9539797/63596109-c454ee00-c5ba-11e9-9ecf-ebff9b9c918c.png)

**Comment by asturur** [comment]
Hi @Obiwarn, 
The current issue is that the 'NUM_FRACTION_DIGIT' value is used for 2 kinds of exports.

when serializing and restore, 2 digits are often enough to do not bloat the file size too much.
When dealing with setups that need higher precision this value is better changed.

changing it by default means blowing the json representation for everyone.

I agree this should be stated clearly somewhere, like in a page dedicated to all those details ( together with setCoords and the named getters )

If there was a programmatic way to figure out a problematic setup we could also hace a dev build that warns you in the console.

**Comment by Obiwarn** [comment]
Maybe precision could auto-increase with image size?

**Comment by asturur** [comment]
is mostly a small scale that will create problems. if a scale factor is 0.125, rounding to 0.13 will create a difference
