### ISSUE TITLE
Text selection box issue for some languages.

### ISSUE THREAD

**Issue by bhaskardas9475** [fabricjs/fabric.js#5856]
## Version
3.0.0

## Test Case
https://jsfiddle.net/bhaskar321/zp6st8h4/1/

## Information about environment
Nodejs or browser?
Browser
Which browsers?
Chrome Version 74.0.3729.169 (Official Build) (64-bit)

## Steps to reproduce
1. Add text in canvas.
2. I am adding one indian language text (ಕಾರ್ಮಿಕರ)

## Expected Behavior
Selection box should match the actual width of the whole text.
## Actual Behavior
Selection box width is smaller than the text

**Comment by asturur** [comment]
hi @bhaskardas9475,
You need to override `fabric.util.graphemeSplit` with some function that is able to handle diatrical marks and unicode points for indian language.

**Comment by bhaskardas9475** [comment]
Hello @asturur ,
Thanks for the suggestion. That would be really helpful if you elaborate little more. May be a small example of code.

**Comment by asturur** [comment]
check grapheme splitter https://www.npmjs.com/package/grapheme-splitter
```js
fabric.util.graphemeSplit = function(stringOfText) {
  // import a library that does this job, like grapheme splitter
  return graphemeSplitter(stringOfText)
}
```

**Comment by bhaskardas9475** [comment]
Works Perfectly..
--Thanks @asturur
