### ISSUE TITLE
"allowTouchScrolling" does not work in Ver.3.4.0

### ISSUE THREAD

**Issue by TsuchiyaMasahiro** [fabricjs/fabric.js#5857]
## Version
3.4.0

## Test Case
***Please see in a smartphone.****
Ver. 3.4.0 <--I can't scroll the canvas.
https://jsbin.com/titivi/8/edit?output

Ver 3.3.2  <-- I can scroll the canvs.
https://jsbin.com/titivi/11/edit?output

## Information about environment
Nodejs or browser? -> browser
Which browsers? -> Chrome in android.

## Steps to reproduce
In fabric Ver 3.4.0, maybe the property "allowTouchScrolling" does not work in a smartphone.
In fabric Ver 3.3.2, If a canvas's width is bigger than a div which contains the canvas,
I can scroll the canvas, but in fabric Ver 3.4.0, I can not scroll the canvas.
Maybe, the property 'allowTouchScrolling' does not work in Ver 3.4.0.
Please see the jsbin above in mobile phone.
 
## Expected Behavior
I can scroll the canvas.

## Actual Behavior
I can not scroll the canvas.

**Comment by asturur** [comment]
how are you trying to scroll? with what gesture?

**Comment by TsuchiyaMasahiro** [comment]
I tried to scroll a canvas by one finger.

**Comment by asturur** [comment]
Did you enabled pointer events in your setup?

**Comment by asturur** [comment]
Also in 3.4.0 changelog there is nothing about events. Just gradients stuff.

**Comment by TsuchiyaMasahiro** [comment]
Sorry, I was mistaken.
In 3.2.0, I can scroll the canvas by sliding the screen by one finger when the canvas is bigger than a screen.
Please see a following demo with a smart phone.
[https://jsbin.com/zuzucos/edit?html,css,js,output](https://jsbin.com/zuzucos/edit?html,css,js,output)

Bur in 3.3.2, I can's scroll the canvas even if the canvas is bigger than a screen.
Demo 
[https://jsbin.com/yakikof/edit?html,css,js,output](https://jsbin.com/yakikof/edit?html,css,js,output)

**Comment by asturur** [comment]
this could make sense,  i ll check asap

**Comment by asturur** [comment]
the code seems fine to me.
In the mouse move event ( that is the same used for touch move ) the code did not change.

Can you inspect the canvas element and check what value you have for the touch-action attribute in your html? you should have 'manipulation'. if not the error is there, if yes i m clueless.

Other than that the interaction in 3.2.0 seems pretty broken to me. You can scroll but dragging the rect makes the canvas scroll, seems bad. I wonder which is a decent interaction.

**Comment by hiutalemedia** [comment]
e.preventDefault() at _onTouchStart breaks your scrolling if you havent enabled the pointer events. Remove it and scrolling will work again.

**Comment by asturur** [comment]
that is a good info, thanks.

**Comment by asturur** [comment]
@TsuchiyaMasahiro i know lot of time passed, but  can you verify if my linked commit solves the issue? i cannot test on my phone right now.

**Comment by TsuchiyaMasahiro** [comment]
@asturur I tested it on Android smartphone and iPhone.  It worked fine.
Thank you always !
