### ISSUE TITLE
intersectsWithRect() does not allow to check intersection for rotated Rect

### ISSUE THREAD

**Issue by Roinoss** [fabricjs/fabric.js#5859]
Item:
http://fabricjs.com/docs/fabric.Object.html#intersectsWithRect

Problem:
Function doesn't allow to check it object intersects with rotated rectangle.
As rotation is a fabric feature, it should allow.

Possible solution:
```
intersectsWithRect(pointTL, pointBR, angle <option or = 0>, absoluteopt, calculateopt)
if(angle) {
  check intersection for rotated rect
} else {
 current solution
}
```
Possible way around in current state of fabric:
```
count data {left, top, angle, height, width} from pointTL, pointB and angle
var rect = new fabric.rect(data);
use intersectWithObject(rect);
```
Personal context:
Working at sticky, chess-like collision detection script with rotation and resize.

**Comment by asturur** [comment]
The method intersect with rect, should allow you to check if any object, rotated or not, intersect with the axis oriented rectangular area defined by pointTL and pointBR.

What intersection are you trying to find?

**Comment by Roinoss** [comment]
I tried to find rotated rectangular area defined by pointTL and pointBR. In the end i used way around described in 1st post, so topic is to close.
