### ISSUE TITLE
Disable canvas selection without disabling event handling

### ISSUE THREAD

**Issue by sugogron** [fabricjs/fabric.js#586]
Hello,

Is there a way to disable canvas selection without disabling event handling ?

I found a work around by applying these properties to every objects:
hasControls: false
hasBorders: false
lockMovementX: true
lockMovementY: true

And theses properties to canvas:
selection = false
hoverCursor = 'default'

I need to do this because my canvas can be in a "edit mode" (with selection) and in a viewer mode (without selection and with event handling to make something happen when clicking on objects).

Thx for help and gratz for your lib, it's great :)

**Comment by diogoico** [comment]
Doesn't work on 1.6> :|

**Comment by asturur** [comment]
i will check it. can you make a demo? did it work on 1.5.0?

**Comment by diogoico** [comment]
Hello asturur, that is strange hehe, I was testing the problem I mentioned local, like this: "file:///C:/Users/user/Desktop/myFabricjs/index.html" because I'm building it to run local inside a android WebView and noticed that funny behaviour, but testing it online using jsfiddle.net, both 1.5.0 and 1.6.1 worked fine.

**Comment by hichem147** [comment]
@diogoico Hello Diego, how do you get back all the objects in the edit mode ?

**Comment by bosz** [comment]
Thanks @Kienz , your approach of 
`o.selectable = false;` works fine. 

Thanks again

**Comment by andrea11** [comment]
Hi,
sorry but I tried several times and unfortunately it does not work. I add the handler on canvas (es6 notation):
`this.canvas.on('object:selected', (object): void => {
console.log(object);
});`
this.canvas is an instance of fabric canvas.

Every time I set selectable = false on a group, fabric does not fire object:selected

Some ideas?

**Comment by andrea11** [comment]
I have a question pretty simple, but: 
Is object:selected event fired when selactable = false ?
Thanks

**Comment by boomsya** [comment]
```
fabric.Image.fromURL('2.jpg', function (image) {
		image.set({left: 0, top: 400, angle: 0}).scaleToWidth(600);
		canvas.add(image);
	});
```

image still selecting :(  (v 2.0.1)
