### ISSUE TITLE
Draw rectangle by dragging with mouse like ms paint

### ISSUE THREAD

**Issue by cancerberoSgx** [fabricjs/fabric.js#5861]
What I need is to support an interaction where users are able to draw rectangles by drag&drop with the mouse in the canvas, like in mspaint and other image bitmap editors. Currently one create rectangles programmatically with fabric, with a fixed size, and then users are able to resize/move/rotate them, but what I need is users to create the rectangle using dragging with the mouse to give its initial bounds. fabric selection tool actually behaves like this. 

So I looked for this feature exhaustively in the library and I think it's not supported. I'm implementing it manually and I cant's get it perfect. Now I'm will try to implementing manually but using fabric shapes, but before I would like to know if this is supported by fabric ? Do you know if there is some third-party project based on fabric with something like this ? 

Thanks and sorry to ask this as an issue here. but I really couldn't find any related to this. Also if this exists I will make sure it gains some visibility in the docs, otherwise, I will PR with this feature if it doesn't. Thanks

**Comment by asturur** [comment]
i think stackoverflow has examples at least for circles and ellipses that i answered to.
Rectangle is an straight extensions from it.

if you do not find them, please open a new question, but i m sure there are.

**Comment by cancerberoSgx** [comment]
Thanks I'm trying with this answer: https://stackoverflow.com/questions/9417603/fabric-js-free-draw-a-rectangle

Nevertheless would be awesome to have official support for rectangle and ellipse free drawing . My use case is an bitmap processing tool where users **select** a region of interest inside the image (bitmap). Examples are background removal or feature detection tools in which the the expected tool is users being able to define the region of interest by drawing a rectangle. IMO this use case is even more common then the ones that can be solved with "shape-dropping" which is the only interactive way the library supports to define shapes. I wonder if there are any plans to support, at least a rectangle free drawing tool or if for any reason this is not viable. I would be glad to PR once I test and feel confortable with an implementation. thanks

**Comment by cancerberoSgx** [comment]
This is my final implementation. I tested with all combinations I could think of.

https://cancerberosgx.github.io/demos/misc/fabricRectangleFreeDrawing.html?d=9

 * two modes: one that will create and update a rectangle onmousedown and another that won't and only create the rectangle onmouseup
 * doesn't depend on any other  library other than fabric.js
 * Doesn't use offsets or event.clientX , etc. It just uses fabric event.pointer API to compute the coordinated. 
 * carefully manages event listeners

TODO:
I probably will also add throttle support for mousemove 

Do you think something like this could be contributed to this project. Is it viable to start discussing this if I create a PR - or I should not waste time ? 

Thanks

**Comment by asturur** [comment]
i think it would be cool to have this as a brush probably, the problem with features is that they do not stack well all together.

A brush could leave in the library and not being imported by default.

**Comment by brendler** [comment]
The implementation above is buggy. When you resize an existing rectangle you end up creating yet another rectangle while you resize the first one.

**Comment by Shitanshukumar607** [comment]
hey @cancerberoSgx! can i have the code of the free drawing rectangle that you created the one you mentioned in the last comment?
