### ISSUE TITLE
How to place object in center of any objects in FabricJS?

### ISSUE THREAD

**Issue by albert-hoffman** [fabricjs/fabric.js#5865]
I am using FabricJS 3.1.0. I have added multiple rect objects in canvas. Now I am adding images on top of rect. How to add those images in center of those rects?

**Note: I don't want to set in center of canvas. I want to set in center of those rects.**

**Comment by denniskawurek** [comment]
You may want to group your objects.

See [http://fabricjs.com/fabric-intro-part-3](http://fabricjs.com/fabric-intro-part-3)

**Comment by albert-hoffman** [comment]
I tried but it doesn't work.

**Comment by ankitgehlot123** [comment]
Hi albert, can you createa  fiddle for it so i can see what exactly you are trying to do

**Comment by asturur** [comment]
There is an easy way and a less easy way:

1) use originX and originY set to 'center' ( both of the properties )
Then assign to the rect and the image the same top and left value.
In this way the top and left value represent the center of the object, and assigning the same top and left postion their center in the same point.

2) use getCenterPoint and setPositionByOrigin.
take the center point of the rect with
```
var centerPoint = rect.getCenterPoint();
```
set the image with the center on that point
```
image.setPositionByOrigin(centerPoint, 'center', 'center');
```

**Comment by albert-hoffman** [comment]
@asturur : thanks, dear. you are doing well to make fabricJS better. hope you will add crop feature also in the coming version.

**Comment by asturur** [comment]
crop is there, missing an interface that i won't add.
I ll probably add a new control interface that is customizable and where you can create your functionalities

**Comment by matifanger** [comment]
> There is an easy way and a less easy way:
> 
> 1. use originX and originY set to 'center' ( both of the properties )
>    Then assign to the rect and the image the same top and left value.
>    In this way the top and left value represent the center of the object, and assigning the same top and left postion their center in the same point.
> 2. use getCenterPoint and setPositionByOrigin.
>    take the center point of the rect with
> 
> ```
> var centerPoint = rect.getCenterPoint();
> ```
> 
> set the image with the center on that point
> 
> ```
> image.setPositionByOrigin(centerPoint, 'center', 'center');
> ```

this works, but if the rect has an angle, when you image.setPositionByOrigin, the image doesn't center. How do you solve this?

![chrome_sC0qeN4ghK](https://github.com/fabricjs/fabric.js/assets/39188240/6c53fd42-ae85-4eef-a3bc-8d64694d8850)
