### ISSUE TITLE
Display image object every time at left corner

### ISSUE THREAD

**Issue by adungureanu** [fabricjs/fabric.js#5868]
Hello, I have an SVG image that I need to display when the object is selected on a canvas in the left top corner of a rectangle, line or free form displayed.
 Right now I take the top - left corner to calculate the distances, but if the rectangle is at -90 degree it will display at bottom left corner because is flipped and if I zoom in it will mess all my calculation because I don't know where to get the scale value, I don't want to depend on too many variables. 

Is there a way to get the coords of left top corner and position there whenever I move, scale, or rotate?

**Comment by asturur** [comment]
See if this helps
http://fabricjs.com/using-transformations
