### ISSUE TITLE
How Can I Clip fabric.Rect to Top Left and Bottom Right Corners With Radius ?

### ISSUE THREAD

**Issue by sagarvibrant** [fabricjs/fabric.js#5869]
How Can I Clip fabric.Rect to Top Left and Bottom Right Corners With Radius ?
I have Trubble to generate 2 corners with radius Rectangle cliping. 

![2_corner](https://user-images.githubusercontent.com/36664189/64588629-9cd69180-d3c0-11e9-947e-3a2f52777bea.png)

Thank you.

**Comment by asturur** [comment]
we do not support per corner radius.
We have radius either in all corners or none.
You have to make a path with that shape instead.

**Comment by sagarvibrant** [comment]
Any update on this ?

**Comment by asturur** [comment]
@sagarvibrant there won't be an update from us
You can extend Rect to behave like this if you want, is not hard and being your exclusive need, it should comfortably fit in your codebase.

The rect drawing code does draw 4 rounded corner, create a class that can do that only on the corners you want.

**Comment by sagarvibrant** [comment]
Thanks for replay. I'll try this

**Comment by asturur** [comment]
this is the rect code:

```diff
    _render: function(ctx) {

      // 1x1 case (used in spray brush) optimization was removed because
      // with caching and higher zoom level this makes more damage than help

      var rx = this.rx ? Math.min(this.rx, this.width / 2) : 0,
          ry = this.ry ? Math.min(this.ry, this.height / 2) : 0,
          w = this.width,
          h = this.height,
          x = -this.width / 2,
          y = -this.height / 2,
          isRounded = rx !== 0 || ry !== 0,
          /* "magic number" for bezier approximations of arcs (http://itc.ktu.lt/itc354/Riskus354.pdf) */
          k = 1 - 0.5522847498;
      ctx.beginPath();

+    // top left corner
-       ctx.moveTo(x + rx, y);
+      ctx.moveTo(x + this.topLeftRounderd ? rx : 0, y);
+     // moving to top right
-       ctx.lineTo(x + w - rx, y);
+      ctx.lineTo(x + w - this.topRightRounderd ? rx : 0, y);
      isRounded && this.topRightRounderd + ctx.bezierCurveTo(x + w - k * rx, y, x + w, y + k * ry, x + w, y + ry);

+     // bottom right corner
-      ctx.lineTo(x + w, y + h - ry);
+     ctx.lineTo(x + w, y + h - this.bottomRightRounded ? ry : 0);
      isRounded && ctx.bezierCurveTo(x + w, y + h - k * ry, x + w - k * rx, y + h, x + w - rx, y + h);

      ctx.lineTo(x + rx, y + h);
      isRounded && ctx.bezierCurveTo(x + k * rx, y + h, x, y + h - k * ry, x, y + h - ry);

      ctx.lineTo(x, y + ry);
      isRounded && ctx.bezierCurveTo(x, y + k * ry, x + k * rx, y, x + rx, y);

      ctx.closePath();

      this._renderPaintInOrder(ctx);
    },

```

Something on this kind of work, in its own class where only the _render, type and toObject are changed, should do the trick for you.

**Comment by sagarvibrant** [comment]
thank @asturur

**Comment by kanojiyarohit** [comment]
Hello, Thanks @sandro for great solution, I have modified it a bit to match my usage, it is adding fine but if I change the value of topLeft outside, it is not re-rendering or not updated shape in canvas, and how should i export and import with same values i have selected?
Modified code:
```
export const RoundedRect: any = fabric.util.createClass(fabric.Rect, {
  type: "roundedRect",
  topLeft: 10,
  topRight: 10,
  bottomLeft: 10,
  bottomRight: 10,

  _render: function (ctx: CanvasRenderingContext2D) {
    var w = this.width,
      h = this.height,
      x = -this.width / 2,
      y = -this.height / 2,
      /* "magic number" for bezier approximations of arcs (http://itc.ktu.lt/itc354/Riskus354.pdf) */
      k = 1 - 0.5522847498;
    ctx.beginPath();

    // top left
    ctx.moveTo(x + this.topLeft, y);

    // line to top right
    ctx.lineTo(x + w - this.topRight, y);
    ctx.bezierCurveTo(
      x + w - k * this.topRight,
      y,
      x + w,
      y + k * this.topRight,
      x + w,
      y + this.topRight
    );

    // line to bottom right
    ctx.lineTo(x + w, y + h - this.bottomRight);
    ctx.bezierCurveTo(
      x + w,
      y + h - k * this.bottomRight,
      x + w - k * this.bottomRight,
      y + h,
      x + w - this.bottomRight,
      y + h
    );

    // line to bottom left
    ctx.lineTo(x + this.bottomLeft, y + h);
    ctx.bezierCurveTo(
      x + k * this.bottomLeft,
      y + h,
      x,
      y + h - k * this.bottomLeft,
      x,
      y + h - this.bottomLeft
    );

    // line to top left
    ctx.lineTo(x, y + this.topLeft);
    ctx.bezierCurveTo(x, y + k * this.topLeft, x + k * this.topLeft, y, x + this.topLeft, y);

    ctx.closePath();

    this._renderPaintInOrder(ctx);
  },
});
```

**Comment by sandro** [comment]
Hi @kanojiyarohit , I'm glad you found the code useful.

For import and export, you'll need to add `toObject` and `fromObject` methods. Follow the [pattern](https://github.com/fabricjs/fabric.js/blob/master/src/shapes/rect.class.ts#L108) that `Rect` uses.

I'm not sure why your changes are not rendering, did you call `requestRenderAll()` after changing the properties? You can stick a `debugger` in the `_render` function to debug why your changes aren't updating.

**Comment by kanojiyarohit** [comment]
@sandro, Ok will add code for toObject and fromObject methods. Thanks.

I have changed the code to be class and added to constructor, now it is fine. :+1: 

```
export class RoundedRect extends fabric.Rect {
  topLeft = 10;
  topRight = 10;
  bottomLeft = 10;
  bottomRight = 10;

  constructor(options: FabricObject) {
    super(options);
    this.topLeft = options.topLeft ? options.topLeft : 0;
    this.topRight = options.topRight ? options.topRight : 0;
    this.bottomLeft = options.bottomLeft ? options.bottomLeft : 0;
    this.bottomRight = options.bottomRight ? options.bottomRight : 0;
  }

  setTopLeft = (radious: number) => {
    this.topLeft = radious;
  };
  setTopRight = (radious: number) => {
    this.topRight = radious;
  };
  setBottomLeft = (radious: number) => {
    this.bottomLeft = radious;
  };
  setBottomRight = (radious: number) => {
    this.bottomRight = radious;
  };

  _render = (ctx: CanvasRenderingContext2D) => {
    if (this.width && this.height) {
      let w = this.width,
        h = this.height,
        x = -this.width / 2,
        y = -this.height / 2,
        /* "magic number" for bezier approximations of arcs (http://itc.ktu.lt/itc354/Riskus354.pdf) */
        k = 1 - 0.5522847498;
      ctx.beginPath();

      // top left
      ctx.moveTo(x + this.topLeft, y);

      // line to top right
      if (w) {
        ctx.lineTo(x + w - this.topRight, y);
        ctx.bezierCurveTo(
          x + w - k * this.topRight,
          y,
          x + w,
          y + k * this.topRight,
          x + w,
          y + this.topRight
        );
      }

      // line to bottom right
      if (w && h) {
        ctx.lineTo(x + w, y + h - this.bottomRight);
        ctx.bezierCurveTo(
          x + w,
          y + h - k * this.bottomRight,
          x + w - k * this.bottomRight,
          y + h,
          x + w - this.bottomRight,
          y + h
        );
      }

      // line to bottom left
      if (h) {
        ctx.lineTo(x + this.bottomLeft, y + h);
        ctx.bezierCurveTo(
          x + k * this.bottomLeft,
          y + h,
          x,
          y + h - k * this.bottomLeft,
          x,
          y + h - this.bottomLeft
        );
      }

      // line to top left
      ctx.lineTo(x, y + this.topLeft);
      ctx.bezierCurveTo(x, y + k * this.topLeft, x + k * this.topLeft, y, x + this.topLeft, y);

      ctx.closePath();

      this._renderPaintInOrder(ctx);
    }
  };
}
```

**Comment by Hasi6** [comment]
> I just created a rounded rect class to fit my needs. It allows you to specify the rounding of each corner. It works like `rx`,`ry` except for each corner.
> 
> ```js
> // RoundedRect allows rounding each corner of a rect individually.
> const RoundedRect = new fabric.util.createClass(fabric.Rect, {
>   type: "roundedRect",
>   topLeft: [20, 20],
>   topRight: [20, 20],
>   bottomLeft: [20, 20],
>   bottomRight: [20, 20],
> 
>   _render: function(ctx) {
>     var w = this.width,
>       h = this.height,
>       x = -this.width / 2,
>       y = -this.height / 2,
>       /* "magic number" for bezier approximations of arcs (http://itc.ktu.lt/itc354/Riskus354.pdf) */
>       k = 1 - 0.5522847498;
>     ctx.beginPath();
> 
>     // top left
>     ctx.moveTo(x + this.topLeft[0], y);
> 
>     // line to top right
>     ctx.lineTo(x + w - this.topRight[0], y);
>     ctx.bezierCurveTo(x + w - k * this.topRight[0], y, x + w, y + k * this.topRight[1], x + w, y + this.topRight[1]);
> 
>     // line to bottom right
>     ctx.lineTo(x + w, y + h - this.bottomRight[1]);
>     ctx.bezierCurveTo(x + w, y + h - k * this.bottomRight[1], x + w - k * this.bottomRight[0], y + h, x + w - this.bottomRight[0], y + h);
> 
>     // line to bottom left
>     ctx.lineTo(x + this.bottomLeft[0], y + h);
>     ctx.bezierCurveTo(x + k * this.bottomLeft[0], y + h, x, y + h - k * this.bottomLeft[1], x, y + h - this.bottomLeft[1]);
> 
>     // line to top left
>     ctx.lineTo(x, y + this.topLeft[1]);
>     ctx.bezierCurveTo(x, y + k * this.topLeft[1], x + k * this.topLeft[0], y, x + this.topLeft[0], y);
> 
>     ctx.closePath();
> 
>     this._renderPaintInOrder(ctx);
>   }
> })
> ```

@sandro Thanks man, I was looking for this for more than 3 days. You just saved me

**Comment by sandro** [comment]
@Hasi6 you're very welcome! Glad it helped.

**Comment by wuxingping** [comment]
when object has stroke prop.stroke has been cliped,the part of rect has been cliped also.i dont want rect has changed,just stroke has been cliped.how can i  do?
