### ISSUE TITLE
Clone an object who contains objects (Group)

### ISSUE THREAD

**Issue by bodeva** [fabricjs/fabric.js#5870]
Hi,

I have a concern to clone an object (group) since the passage in version 3.4.0. For other objects it works perfectly. On the other hand for a group (Not a selection of several objects but really a group of object), this one is duplicated but is not visible immediately. On the other hand by reloading the canvas this one appears

here video :
http://bodeva.com/fabric-group.mp4

My code :
this.cloneHandler = function () {
            
			var objectToClone = this.canvas.getActiveObject();
            
			if (!Utils.Tools.isNull(objectToClone)) {           
                
                var clone;
                
                clone = fabric.util.object.clone(objectToClone);
                
                clone.set({
                    left: objectToClone.left + 10, 
                    top: objectToClone.top + 10, 
                    uid: Utils.Tools.guid(), 
					dirty: true,
                    extra: {
                        scalable: true,
                        locked: false,
                        rotatable: true,
                        selectable: true,
                        editable: true,
                        duplicable: true,
                        deletable: true,
                        typage: '',
                        ws:''
                    } 
                });
                
                if(objectToClone.type === 'bodevatext' || objectToClone.type === 'bodevasimpletext'){                              
                    clone.initBehavior();
                }
                             
                this.canvas.add(clone);
                this.canvas.setActiveObject(clone);
                this.layers.ul.trigger(Bodevapp.events.ADD_ITEM_EVENT, {object: clone, app: this, layers: this.layers});
                //this.canvas.renderAll();
                this.canvas.requestRenderAll();
            } else {
                //console.log("cloneHandler : None active");
            }
               
        };

Thanks you in advance

**Comment by Chienle** [comment]
Same issue!

**Comment by asturur** [comment]
Any chance to get an interactive fiddle?

**Comment by Chienle** [comment]
You can try to add canvas.discardActiveObject(); before clone an object.

**Comment by bodeva** [comment]
canvas.discardActiveObject(); no effect, I've the same bug

**Comment by bodeva** [comment]
No fiddle it's complex api integrated to our app.
Here the json loaded into canvas

{"pages":[{"name":"AFFICHE VIERGE ORANGE 1","value":{"objects":[{"type":"bodevatext","originX":"left","originY":"top","left":1682.91,"top":1079.02,"width":1351.25,"height":124.3,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"NOM DU PRODUIT","fontSize":"110","fontWeight":"normal","fontFamily":"Helvetica Neue LT Std Heavy","fontStyle":"","lineHeight":1.16,"textDecoration":"","textAlign":"left","textBackgroundColor":"","charSpacing":0,"minWidth":20,"undefined":"110","styles":[],"extra":{"scalable":true,"locked":false,"rotatable":true,"selectable":true,"editable":true,"duplicable":true,"deletable":true,"typage":"","ws":""},"uid":"a50fc643-ab2e-f8f6-74bb-83cb2dca4f12","objectCaching":false,"dirty":false},{"type":"bodevatext","originX":"left","originY":"top","left":1690.8,"top":1213.21,"width":1343.34,"height":90.4,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"Descriptif du produit","fontSize":"80","fontWeight":"normal","fontFamily":"Helvetica Neue LT Std Roman","fontStyle":"","lineHeight":1.16,"textDecoration":"","textAlign":"left","textBackgroundColor":"","charSpacing":0,"minWidth":20,"undefined":"80","styles":[],"extra":{"scalable":true,"locked":false,"rotatable":true,"selectable":true,"editable":true,"duplicable":true,"deletable":true,"typage":"","ws":""},"uid":"09ea0615-57e6-57bd-31b0-d3b2987d0bf9","objectCaching":false,"dirty":false},{"type":"bodevatext","originX":"left","originY":"top","left":41,"top":41,"width":0,"height":93.79,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"","fontSize":83,"fontWeight":"normal","fontFamily":"BaronDidot","fontStyle":"","lineHeight":1.16,"textDecoration":"","textAlign":"left","textBackgroundColor":"","charSpacing":0,"minWidth":20,"styles":[],"extra":{"scalable":true,"locked":false,"rotatable":true,"selectable":true,"editable":true,"duplicable":true,"deletable":true,"typage":"","ws":""},"uid":"a8f73699-001f-6d0b-efd3-b544520c7b3c","objectCaching":false,"dirty":false},{"type":"bodevatext","originX":"left","originY":"top","left":41,"top":41,"width":0,"height":93.79,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"","fontSize":83,"fontWeight":"normal","fontFamily":"BaronDidot","fontStyle":"","lineHeight":1.16,"textDecoration":"","textAlign":"left","textBackgroundColor":"","charSpacing":0,"minWidth":20,"styles":[],"extra":{"scalable":true,"locked":false,"rotatable":true,"selectable":true,"editable":true,"duplicable":true,"deletable":true,"typage":"","ws":""},"uid":"185755bb-fbad-ba4d-1eba-ca5550e32e6c","objectCaching":false,"dirty":false},{"type":"bodevatext","originX":"left","originY":"top","left":41,"top":41,"width":0,"height":93.79,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"","fontSize":83,"fontWeight":"normal","fontFamily":"BaronDidot","fontStyle":"","lineHeight":1.16,"textDecoration":"","textAlign":"left","textBackgroundColor":"","charSpacing":0,"minWidth":20,"styles":[],"extra":{"scalable":true,"locked":false,"rotatable":true,"selectable":true,"editable":true,"duplicable":true,"deletable":true,"typage":"","ws":""},"uid":"8dc144f8-2e4e-0411-006f-a2fe0691e7d6","objectCaching":false,"dirty":false},{"type":"bodevaimage","originX":"left","originY":"top","left":298.12,"top":992.76,"width":945,"height":1535,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"crossOrigin":"","alignX":"none","alignY":"none","meetOrSlice":"meet","src":"https:\/\/giphar.webtoprint-by-pnr.com\/origin\/TESTPRODUIT.png","filters":[],"resizeFilters":[],"extra":{"scalable":true,"locked":false,"rotatable":true,"selectable":true,"editable":true,"duplicable":true,"deletable":true,"typage":"","ws":"","label":"Produit"},"uid":"0caa67a7-20a7-a1b2-9d0c-5ca8ddaa85f6"},{"type":"bodevaprice","originX":"left","originY":"top","left":489.59,"top":3137.56,"width":118,"height":90.4,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":9.05,"scaleY":9.05,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"objects":[{"type":"bodevasimpletext","originX":"left","originY":"top","left":-59,"top":-45.2,"width":80,"height":90.4,"fill":"#ed7102","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"00","fontSize":80,"fontWeight":"bold","fontFamily":"Helvetica Neue LT Std Heavy","fontStyle":"","lineHeight":1.16,"textDecoration":"","textAlign":"right","textBackgroundColor":"","charSpacing":0,"styles":[],"extra":{"ws":"ws-price-unit"},"uid":"f822f23f-d1cd-f1ac-8301-50b41bd1d466","objectCaching":false,"dirty":false},{"type":"bodevasimpletext","originX":"left","originY":"top","left":31,"top":-0.2,"width":28,"height":31.64,"fill":"#ed7102","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"00","fontSize":28,"fontWeight":"bold","fontFamily":"Helvetica Neue LT Std Heavy","fontStyle":"","lineHeight":1.16,"textDecoration":"","textAlign":"left","textBackgroundColor":"","charSpacing":0,"styles":[],"extra":{"ws":"ws-price-cents"},"uid":"b5cf41b5-cdf8-2c62-09b7-973e6b1f662e","objectCaching":false,"dirty":false},{"type":"bodevasimpletext","originX":"left","originY":"top","left":31,"top":-30.2,"width":14,"height":31.64,"fill":"#ed7102","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"\u20ac","fontSize":28,"fontWeight":"bold","fontFamily":"Helvetica Neue LT Std Heavy","fontStyle":"","lineHeight":1.16,"textDecoration":"","textAlign":"left","textBackgroundColor":"","charSpacing":0,"styles":[],"extra":{"ws":"ws-price-devise"},"uid":"503a3b09-8aff-9eb8-2a7a-ced53b628258","objectCaching":false,"dirty":false},{"type":"bodevasimpletext","originX":"left","originY":"top","left":28.5,"top":29.8,"width":30.5,"height":6.78,"fill":"#ed7102","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"Soit 0\u20ac\/Litre","fontSize":6,"fontWeight":"normal","fontFamily":"Helvetica Neue LT Std Heavy","fontStyle":"","lineHeight":1.16,"textDecoration":"","textAlign":"right","textBackgroundColor":"","charSpacing":0,"styles":[],"extra":{"ws":"ws-price-sentence"},"uid":"44e75aa6-f6de-9ce2-168a-13b3f2d9d538","objectCaching":false,"dirty":false},{"type":"bodevasimpletext","originX":"left","originY":"top","left":18,"top":-21.2,"width":12.5,"height":56.5,"fill":"#ed7102","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":",","fontSize":50,"fontWeight":"normal","fontFamily":"Helvetica Neue LT Std Heavy","fontStyle":"","lineHeight":1.16,"textDecoration":"","textAlign":"right","textBackgroundColor":"","charSpacing":0,"styles":[],"extra":{"ws":"ws-price-comma"},"uid":"b654f9a4-6b37-33c6-c6ab-e27a5aac7f29","objectCaching":false,"dirty":false},{"type":"line","originX":"center","originY":"center","left":0,"top":-6.88,"width":118,"height":56.64,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":0,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"x1":-59,"x2":59,"y1":-28.32,"y2":28.32}],"color":"#ed7102","colorSentence":"#ed7102","strokeColorBarre":"#FF0000","strokeEnabled":false,"sentenceEnabled":true,"fontFamilyDigits":"Helvetica Neue LT Std Heavy","fontFamilySentence":"Helvetica Neue LT Std Heavy","fontFamilyDevise":"Helvetica Neue LT Std Heavy","unite":"00","cents":"00","devise":"\u20ac","sentence":"Soit 0\u20ac\/Litre","output":"l","quantify":"l","quantity":1,"minprice":0,"maxprice":0,"extra":{"scalable":true,"locked":false,"rotatable":true,"selectable":true,"editable":true,"duplicable":true,"deletable":true,"typage":"","ws":""},"uid":"c6de3377-9e27-166d-1e1e-e5d4009c7fc0","objectCaching":false,"dirty":false},{"type":"bodevatext","originX":"left","originY":"top","left":1562.97,"top":2776.16,"width":1506.71,"height":145.77,"fill":"#ffffff","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"VOTRE REMISE ","fontSize":"129","fontWeight":"normal","fontFamily":"Helvetica Neue LT Std Heavy","fontStyle":"","lineHeight":1.16,"textDecoration":"","textAlign":"center","textBackgroundColor":"","charSpacing":0,"minWidth":20,"undefined":"129","styles":[],"extra":{"scalable":true,"locked":false,"rotatable":true,"selectable":true,"editable":true,"duplicable":true,"deletable":true,"typage":"","ws":""},"uid":"e425b9ce-eac3-cf33-5691-56380d32e736","objectCaching":false,"dirty":false},{"type":"bodevatext","originX":"left","originY":"top","left":33.11,"top":4573.25,"width":1584.12,"height":67.8,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"Prix valable du XX au XX 2019","fontSize":"60","fontWeight":"normal","fontFamily":"Helvetica Neue LT Std Roman","fontStyle":"","lineHeight":1.16,"textDecoration":"","textAlign":"left","textBackgroundColor":"","charSpacing":0,"minWidth":20,"undefined":"60","styles":[],"extra":{"scalable":true,"locked":false,"rotatable":true,"selectable":true,"editable":true,"duplicable":true,"deletable":true,"typage":"","ws":""},"uid":"ca15f8b1-dfaa-ca5b-9e5c-ccb51d9b91c3","objectCaching":false,"dirty":false},{"type":"bodevaimage","originX":"left","originY":"top","left":2425.05,"top":3771.44,"width":512,"height":273,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1.51,"scaleY":3.2,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"crossOrigin":"","alignX":"none","alignY":"none","meetOrSlice":"meet","src":"https:\/\/giphar.webtoprint-by-pnr.com\/apps\/giphar.webtoprint-by-pnr.com\/users\/userfiles\/1\/images\/r2llrt04gxs19qno6oe3.png","filters":[],"resizeFilters":[],"extra":{"scalable":false,"locked":false,"rotatable":false,"selectable":false,"editable":false,"duplicable":false,"deletable":false,"typage":"","ws":"","label":"Mes images"},"uid":"e490b5df-9e25-53ea-26c3-02f391fa4f21"}],"background":"rgba(255,255,255,1)","backgroundImage":{"type":"image","originX":"left","originY":"top","left":0,"top":0,"width":3307.0866,"height":4677.1654,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeLineJoin":"miter","strokeMiterLimit":10,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"crossOrigin":"","alignX":"none","alignY":"none","meetOrSlice":"meet","src":"https:\/\/giphar.webtoprint-by-pnr.com\/apps\/giphar.webtoprint-by-pnr.com\/medias\/upload\/products\/58\/0.71-59.jpg","filters":[],"resizeFilters":[]}}}],"width":210,"height":297,"charte":"58","format":"11","orientation":"0","user":"1","dpi":300,"name":"2019-09-12 08:50:13"}

**Comment by asturur** [comment]
quoting
```
No fiddle it's complex api integrated to our app.
```

If you can't reproduce in a fiddle, the problem is elsewhere.

By the way, this is exactly how you do not clone objects:
```
clone = fabric.util.object.clone(objectToClone);
```

to clone an object you have to use

```js
objectToClone.clone((cloned) => { ... do something with the clone })
```
http://fabricjs.com/docs/fabric.Object.html#clone

**Comment by Oleksii14** [comment]
The correct behaviour of cloning a group can be achieved using this approach:

```js
/**
 * @param {fabric.Group} oldGroup
 * @returns {fabric.Group}
*/
const cloneGroup = (oldGroup) =>
 new fabric.Group(oldGroup._objects.map(item => fabric.util.object.clone(item)))
```

Just create a new group and clone objects separately during the new group initialisation.

**Comment by ShaMan123** [comment]
@Oleksii14 that is redundant, `group.clone()` is enough

**Comment by Oleksii14** [comment]
I can reproduce the issue attached in the ticket description. When cloning a group itself, I am having a "disappearing" issue.

**Comment by ShaMan123** [comment]
If you can reproduce any related bug in v6 please open a new report
