### ISSUE TITLE
Drawing mode with .captureStream() from fabric canvas

### ISSUE THREAD

**Issue by jakajacky** [fabricjs/fabric.js#5873]
I'm looking to use document.getElementById("canvas").captureStream() off of a fabric canvas while in drawing mode. Currently I only see the drawn shapes on mouse up, but would like to see them as the mouse moves. Attached is a gif showing the issue.
![52592574-60cc5580-2e0c-11e9-9773-0b8b2b7257dc](https://user-images.githubusercontent.com/16397721/64672824-2492cd80-d49f-11e9-832b-e2953d253c20.gif)

Is there any way to get it to show the entire drawing process?

Any help would be much appreciated!

**Comment by asturur** [comment]
i think the problem is the upperCanvas that is handling the drawing process.
Did you try to capture that? fabricCanvas.upperCanvasEl.

**Comment by Exlord** [comment]
Did you managed to get this to work? @jakajacky ? 
@asturur doesn't the upperCanvas gets cleared on every new drawing?

**Comment by asturur** [comment]
Yes the upper canvas gets cleared on every drawing if you use the pencil brush.

**Comment by AndrzejSala** [comment]
@asturur 
We have the same issue while streaming the lower canvas.
It would be nice if the pencil brush could work as eraser mixin, so both lower and upper canvas are edited at the same time on mouse move.

**Comment by brainly-konrado** [comment]
Hi, I face the same issue.

This problem does not exist when drawing shapes so I assume that the issue might be solved quite easily (and make the drawing methods work consistently), especially if sb experienced with `fabric.js` would make the fix. 

After some investigation this is what I've come to:
- streaming the top canvas does not help as it is kind of "working canvas" and it seems to be configured (or drawn) in some other way so when we stream it we get sth like a negative of the image
- it seems that the changes (a path added to the canvas) are applied only `onMouseUp` (https://github.com/fabricjs/fabric.js/blob/master/src/brushes/pencil_brush.class.ts#L122 in the `_finalizeAndAddPath();` method) but  the `onMouseMove` method already "has" all the required information (the list of points in the path) for drawing the path so why not do it in there?

@asturur, maybe you could reopen this issue as it seems to bother people? Maybe sb could advise something?
