### ISSUE TITLE
createPngstream not working in Electron

### ISSUE THREAD

**Issue by kristianAndersen** [fabricjs/fabric.js#5874]
Hi i am using fabric to generate static banners it works fine using  just nodejs.

Now my colleague would like to do the same, so i want to build an electron app for him to use. But now when i try run the code in electron get this Error

_Uncaught TypeError: canvas.createPNGStream is not a function_

i can use createPNGStream in electron if i use canvas without fabric? What can i do to fix this?

```
const fs = require('fs')
const fabric = require('fabric').fabric;

let canvas  = new fabric.Canvas(null, { width: 500, height: 500 });

fabric.Image.fromURL(__dirname+'/lime-cat.jpg', function(img) {
  img.set({left: 0, top: 0});
  canvas.add(img);
});
canvas.renderAll();

let tagline = new fabric.Textbox(tagres, {
fontSize: 50,
width:iWidth,
fixedWidth: iWidth,
fill: '#ffffff',
textAlign:'center',
fontFamily:'font90557',
left: canvas.width/2, top: canvas.height/2, originX: 'center', originY: 'top',
lineHeight:0.8,
shadow: 'rgba(0,0,0,1) 4px 4px 4px'      
});  

canvas.add(tagline);
canvas.renderAll();

const out = fs.createWriteStream(__dirname + '/test.png')
const stream = canvas.createPNGStream()
stream.pipe(out)
out.on('finish', () =>  console.log('The PNG file was created.'))
```

**Comment by asturur** [comment]
I'm not completely familiar with electron, but you should be able to run both node code and browser code right?

If you run in the node code you need to add the canvas package for node and jsdom.
I have no idea how you do that.
Can you verify is currently installed?
