### ISSUE TITLE
IText word selection on doube tap in iOS does not work

### ISSUE THREAD

**Issue by JamalAPI** [fabricjs/fabric.js#5875]
## Version
fabricjs 3.4.0

Cordova Hybrid App. Tested on iPhone iOS 12.4.1

## Steps to reproduce

**Add a textbox or IText object to canvas, enter edit mode, type some words. Double tap does not highlight the word which was double tapped.**

## Expected Behavior
**In iOS apps, if you double tap a word in a text box, the word is highlighted. This is how it should behave.**

## Actual Behavior
**Word is not highlighted on word double tap. I have to swipe finger over text to highlight individual letters.**

**Am I missing something or is fabricjs overriding normal iOS behavior? 
Is there a solution.**

Thanks!

**Update**: The issue is the same even on Safari mobile or Chrome mobile browser on Android phone. Try to select a word in one of the text boxes at http://fabricjs.com/kitchensink. It does not work.

**Comment by JamalAPI** [comment]
In the meantime, I implemented a hack that takes care of the issue on iOS. Have not tested on desktop browsers. If anyone interested, the changes are below. I did not the touch the isTripleClick section (which also does not work). _Sorry if formatting does not look right; the github editor Insert Code does not work as it should!_ 

**// handle double click**
var DELAY = 700,
  clicks = 0,
  timer = null;

function IsDoubleClicked() {
  clicks++;  //count clicks

  if (clicks === 1) {
    timer = setTimeout(function () {
      clicks = 0;  // reset counter
    }, DELAY);
    return false;

  } else {   // double click
    clearTimeout(timer);  //prevent single-click action
    clicks = 0;  // reset counter
    return true;
  }
}    

**// update onMouseDown event**

onMouseDown: function (options) {
    if (!this.canvas) {
      return;
    }
    this.__newClickTime = +new Date();
    var newPointer = options.pointer;
    if (this.isTripleClick(newPointer)) {
      this.fire('tripleclick', options);
      this._stopEvent(options.e);
    } **else {   // new code: Jamal 20190914
      if (this.isDoubleClick()) {
        this.fire('mousedblclick', options);
        this._stopEvent(options.e);
      }**
    }
    this.__lastLastClickTime = this.__lastClickTime;
    this.__lastClickTime = this.__newClickTime;
    this.__lastPointer = newPointer;
    this.__lastIsEditing = this.isEditing;
    this.__lastSelected = this.selected;
  },

  isTripleClick: function (newPointer) {
    return this.__newClickTime - this.__lastClickTime < 500 &&
      this.__lastClickTime - this.__lastLastClickTime < 500 &&
      this.__lastPointer.x === newPointer.x &&
      this.__lastPointer.y === newPointer.y;
  },

  **// new code: Jamal 20190914
  isDoubleClick: function () {
      return IsDoubleClicked();
  },**

// rest of fabricjs code...

**Comment by JamalAPI** [comment]
I wonder if the above changes can be tested and merged info fabricjs.

**Comment by asturur** [comment]
i would love to support touch events with hammer.js as an options. tap and double tap are not native events and an external library implementation would be cleaner for us to mantain

**Comment by JamalAPI** [comment]
I am hoping hammer.js will be incorporated in fabicejs 4.0.

**Comment by JamalAPI** [comment]
Any updates on this issue in 4.0?

**Comment by asturur** [comment]
not now. the roadmap for now is text on a path, filters on objects and masks

**Comment by dfvgbh86** [comment]
@asturur How soon can this be added? Our application works with text box and we really need this functionality. 
Or could you tell me how to solve this problem of not being able to double tap selection with overwrite/call fabric functions(the hack from the issue didn't work)
