### ISSUE TITLE
Blurred SVG Pattern on Text Fill

### ISSUE THREAD

**Issue by lovenick** [fabricjs/fabric.js#5876]
## Version
3.4.0

## Test Case
https://codepen.io/nicklove/pen/LYPrbNR

## Information about environment
Chrome, FireFox, Safari (IE / Edge not tested)

## Steps to reproduce
- Load an svg image
- Create a pattern with svg image
- Apply pattern to Text 

## Expected Behavior
The SVG text fill should be sharp, not blurry.

## Actual Behavior
The pattern, when applied to text, is blurred.

This appears to be related to the "strokeWidth" on the SVG pattern. From the demo CodePen, you can see the pattern is applied to a Rect with a strokeWidth of 0 and renders correctly. 

From what I can tell, there doesn't appear to be a way to set the strokeWidth on the text's pattern fill.

**Comment by asturur** [comment]
hi @lovenick 
i simplified the codepen to use the SVG directly

```js
const canvas = new fabric.Canvas(document.getElementById('canvas'));
canvas.setWidth(500);
canvas.setHeight(500);

const pattern = new fabric.Pattern({
  source: document.getElementById('svg'),
});

const rectWithStroke = new fabric.Rect({
  width: 70,
  height: 70,
  fill: pattern,
  left: 0,
  top: 0,
});

const rectNoStroke = new fabric.Rect({
  width: 70,
  height: 70,
  fill: pattern,
  left: 0,
  top: 70,
  strokeWidth: 0,
});

const text = new fabric.Text('Fabric\nTest', {
  fontFamily: 'Sans-Serif',
  fontWeight: 'bold',
  left: 90,
  top: 200,
  fontSize: 64,
  lineHeight: 0.7,
});

text.set('fill', pattern);

canvas.add(rectWithStroke);
canvas.add(rectNoStroke);
canvas.add(text);
canvas.renderAll();
```

but the blurriness stay anyway.
It may be that patterns are NOT scalable as SVGs when painted, and once created they stay with that amount of pixels.

Need to check the plain canvas api here.

**Comment by asturur** [comment]
i may have misunderstood your problem, to me looks all blurry

![image](https://user-images.githubusercontent.com/1194048/65144408-9d51d680-da17-11e9-8762-cf9cdcd176b2.png)

care to explain what you think is good and bad in your codepen?

**Comment by lovenick** [comment]
Hi @asturur,

Thanks for cleaning up the example. My original plan was to dynamically resize / adjust the SVG during rendering via the static canvas, but you're right, it's not needed for this issue.

I'm not sure how you zoomed in your screenshot, but it does look all blurry. 

The image below highlights the difference - it's definitely subtle.

![Screen Shot 2019-09-18 at 8 46 56 AM](https://user-images.githubusercontent.com/1697076/65164643-26561700-d9f2-11e9-97db-8db4baf8d69e.png)

I haven't dug into the source code to see how patterns are created and applied to text. But I'm happy to have a look if it helps provide more context.
