### ISSUE TITLE
arabic text rtl direction problem

### ISSUE THREAD

**Issue by ShahramCodeDeveloper** [fabricjs/fabric.js#5877]
## Version
3.4.0

## Test Case
http://jsfiddle.net/ShahramCodeDeveloper/xq6rj92m/3/

## Information about environment
Nodejs or browser?
browser
Which browsers?
firefox and chrome
## Steps to reproduce
Difficult to display Arabic and English text:
[http://www.upsara.com/images/p060305_01.jpg](url)

## Expected Behavior
I putted the correct state into the jsfiddle div

**Comment by JamalAPI** [comment]
I don't see a problem no matter what the combination is.

**Comment by ShahramCodeDeveloper** [comment]
The words are reversed when the Arabic and English words are typed together

**Comment by JamalAPI** [comment]
It's probably a keyboard behavior issue on your system. I tried it on Chrome and there is no issue that I can see.
May be you wish to post a video showing the issue.

**Comment by ShahramCodeDeveloper** [comment]
The problem is reverse the order of words, which is the rtl direction of arabic words (bi-directional (Bidi) )

The following link explains this in full: [](https://www.iamcal.com/understanding-bidirectional-text/)

**Comment by JamalAPI** [comment]
You are not using fabricjs!! 

See: [https://jsfiddle.net/rsq28a6d/ ](url)

This shows your code and at bottom it uses the fabric.Text.

**Comment by ShahramCodeDeveloper** [comment]
Yes, but how to solve this problem?

**Comment by JamalAPI** [comment]
This is not a fabricjs issue.

It looks like your fiddle is from https://stackoverflow.com/questions/8961636/html5-canvas-filltext-with-right-to-left-string

There is a possible solution there at bottom.

**Comment by asturur** [comment]
i would like to have stronger support for arabic text, but not understanding it is a big issue to me in trying to write code to handle it.

**Comment by ThakurKarthik** [comment]
@asturur how is the support for RTL languages now ? Did u had time to look into this?

**Comment by asturur** [comment]
i did not. I got someone to explain me rtl a bit, with unicode symbols, but my free time is few and it require a lot of it. Is my intention to support it if i find a way to inplement it

**Comment by YaakovHatam** [comment]
@ShahramCodeDeveloper @ThakurKarthik  please look at the issue #2374 i am developing a RTL version please test it
