### ISSUE TITLE
Can I give Multicolor to svg paths ?

### ISSUE THREAD

**Issue by sagarvibrant** [fabricjs/fabric.js#5879]
![multicolorSVG](https://user-images.githubusercontent.com/36664189/64903286-7a4fbb80-d6d3-11e9-9bba-351ef64f59b0.png)

I have 3 colors, can i change those separately .

**Comment by asturur** [comment]
Can youbload that with code in a fiddle?

**Comment by sagarvibrant** [comment]
https://jsfiddle.net/hebk2ztc/1/ 

I have 3 colors in svg , can i change those separately .

**Comment by awehring** [comment]
Yes, you can.

Inspect the `loadedObjects` in your browser. It has an array `paths`, which represents the 3 arcs. To set the first arc to blue: `loadedObjects.paths[0].set({fill: "blue"});`

I updated your fiddle, to show the full code:
https://jsfiddle.net/4vcmoqxw/

**Comment by sagarvibrant** [comment]
Thanks @awehring , It's Working .

**Comment by asturur** [comment]
thanks @awehring

**Comment by awehring** [comment]
I updated the solution to fabric.js version 3.5 (the former ran with version 1.7).

https://jsfiddle.net/awehring/k7azLb84/9/

The only difference is one line:
`loadedObjects.getObjects()[0].set({fill: "blue"});`

instead of:
`loadedObjects.paths[0].set({fill: "blue"});`
