### ISSUE TITLE
Fabric js gets slow with hundrards of objects

### ISSUE THREAD

**Issue by TimYi** [fabricjs/fabric.js#5885]
I'm writing a canvas base spreadsheet, I use fabric.js as my canvas library, just to simplify the canvas call.

When the screen is scrolling, I need to calculate which pard of the spreadsheet should be rendered, clear the canvas, and render all the visible part. So StaticCanvas.renderAll method is frequently called when the screen is scrolling.

StaticCanvas.renderAll method took more than 100ms to finish, causing the scrolling not smooth.

This is the link to [my project](https://github.com/TimYi/fabric-spreadsheet).

Does fabric.js have some efficient static rendering settings, or should I consider swapping other libraries?

[This project](https://github.com/myliang/x-spreadsheet) write canvas calls by hand, and it scrolls very smoothly. Here's it's [demo link](https://myliang.github.io/x-spreadsheet/).

**Comment by asturur** [comment]
Can't really read all the project to try to help.
Can you put in a fiddle a similar number of objects on a equally sized canvas and we can see where the problem is.

Fabric already renders the object that are visibile on screen and not much else, but scrolling often requires lot of changes.

**Comment by TimYi** [comment]
![image](https://user-images.githubusercontent.com/7494892/65291519-50404280-db86-11e9-8ed7-364e4c0a12ee.png)
I will write a fiddle demo later. This is the call tree of chrome performance view. Hope this may help you discover something.

**Comment by TimYi** [comment]
I added `fabric.CanvasObject.prototype.objectCaching = false`, then execution time cut in half.

Then I fill all the cells with text, like this

![image](https://user-images.githubusercontent.com/7494892/65306634-7088f500-dbb8-11e9-9aab-46b1cf0aebc0.png)

The execution time of renderAll method rose to 400ms.

I wrote the code to directly manipulate the canvas. After replacing the fabric.js, the execution time was reduced to 10ms. [This is the canvas code link](https://github.com/TimYi/fabric-spreadsheet/blob/canvas/src/canvas/index.ts)

I think I should write the canvas code directly to achieve the effect I need, it's not very hard.
Fabric.js is great, there are good api and animation effects, but I need the ultimate performance, so I should probably implement the rendering library myself.

Thank you.

@asturur

**Comment by asturur** [comment]
do not know, is your application installable and runnable locally?
Exact canvas code for your need may be faster, but not 40 times faster. there must be something going wrong somewhere.

Removing the cache for the text is an issue, i can tell you.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/65477093-78c98480-de85-11e9-8186-68461ce2b926.png)

definitely you are doing something too much

**Comment by asturur** [comment]
i see you are adding a cell to the canvas every time you want to draw it.
That is really bad.
You have to add a cell to the canvas and then simply scroll the viewport.
I ll try to make an example in a fiddle just to see if is an implementation problem or a library problem.

https://jsfiddle.net/8gzo9wmj/1/

This fiddle for how much simple, contains 6400 editable cells.
The cells are added once and keep there, the canvas code render them when needed.
Cells are editable ( is really just a matrix of textboxes, there are not spreadsheet functionalities ).
Performance is fast.

![image](https://user-images.githubusercontent.com/1194048/65478193-28ecbc80-de89-11e9-96c3-a30510f27eb4.png)

RenderAll takes around 25ms, that while not in the 60fps budget, is still ok.

Of course 6400 objects are too many and you would need some optimization because you cannot scale up to 200.000 or 400.000, would be simply too much.

**Comment by TimYi** [comment]
I changed this code `for(var j = 0; j < 80; j++)` to `for(var j = 0; j < 800; j++)`, then the code runs very stuck.

The reason I need to redraw the entire canvas every time is because the actual use of excel tables can be very large. If I paint all the elements, the rendering efficiency will always become a bottleneck. 

So every time I calculate the area I need to render in memory, there is only one screen of content, and then render it, so that as long as the calculation is fast enough, rendering a screen of content is fast enough, the table performance is fast enough.

In this scenario, fabric.js does not seem to have a good enough response.

**Comment by asturur** [comment]
Yes i m sure that custom code wrote for a specific task is faster than the generic setup fabricjs offers out of the box.

64.000 objects for fabricjs are defintely too much today.
