### ISSUE TITLE
Building doesn't work

### ISSUE THREAD

**Issue by maniac0s** [fabricjs/fabric.js#5887]
I cloned the git and tried to build then this happened:

    server:/var/www/fabric.js$ node build.js
    Built distribution to dist/fabric.js
    Minification failed using uglifyjs with uglifyjs  --compress --mangle --output fabric.min.js fabric.js
    Minifier error output:
    Error: Command failed: uglifyjs  --compress --mangle --output fabric.min.js fabric.js
    /bin/sh: 1: uglifyjs: not found

I tried installing uglifyjs but that didnt help

    npm install uglifyjs --save
    npm WARN deprecated uglifyjs@2.4.11: uglifyjs is deprecated - use uglify-js instead.
    + uglifyjs@2.4.11
    updated 1 package and audited 1 package in 1.632s
    found 0 vulnerabilities

**Comment by maniac0s** [comment]
you need

    npm install uglifyjs -g

(Documentation does not mention this)

**Comment by asturur** [comment]
you can also do `npm run build` it should work without installing uglify globally.

**Comment by Dok11** [comment]
![image](https://user-images.githubusercontent.com/2697890/126070443-491ad47e-439f-49f7-8852-110a9f1abc8b.png)

not working eve with globaly installed uglifyjs
```
npm 6.14.10
node 14.15.3
```

**Comment by asturur** [comment]
we use `    "uglify-js": "3.3.x"` can you do `npm ls uglifyjs` and `npm ls uglify-js` and see what is the output? you should have 3.x.something

**Comment by Dok11** [comment]
on my desktop pc the build script works fine, but on laptop I see this error

npm ls on laptop show this
```
\fabric>npm ls uglifyjs
fabric@4.5.0 \fabric
`-- (empty)

\fabric>npm ls uglify-js
fabric@4.5.0 \fabric
`-- uglify-js@3.3.28
```

**Comment by Dok11** [comment]
`npm install -g uglify-js` fixed this =)
