### ISSUE TITLE
Can't get the tutorial examples running

### ISSUE THREAD

**Issue by maniac0s** [fabricjs/fabric.js#5888]
I try to set up a projeyt with fabricjs but nothing appears. I get a white screen and I don't understand what I am missing in the tutorial. I tried to reproduce the first example in the tutorial:

    <html>
        <head>
            <meta charset="UTF-8">
            <script type="text/javascript" src="http://localhost/fabric.js/dist/fabric.js"></script>
            <script language="javascript">
                var canvas = new fabric.Canvas('c');

                // create a rectangle with angle=45
                var rect = new fabric.Rect({
                  left: 100,
                  top: 100,
                  fill: 'red',
                  width: 20,
                  height: 20,
                  angle: 45
                });

                canvas.add(rect);
            </script>
        </head>
        <body>
            <canvas id="c"></canvas>
        </body>
    </html>

Blank page, nothing is drawn and console shows no errors either.

**Comment by umangvyas** [comment]
@maniac0s, It seems you have added script tag before the body tag. In your example, It will load the script first and then the canvas element.

So keep the script code below the body element. You also need to add 'canvas.renderAll()' after canvas.add(rect);

Hope this helps

**Comment by maniac0s** [comment]
Yes that helped, thanks. I don't understand why tho anyhow could the example HTML be included in the tutorials?

**Comment by asturur** [comment]
can you link to one of the non working example?

**Comment by maniac0s** [comment]
Starts with the first examples http://fabricjs.com/fabric-intro-part-1 I didn't find where it is mentioned how the html code has to be for the examples since they are javascript only.
