### ISSUE TITLE
Producing black image personalize images

### ISSUE THREAD

**Issue by santoshsupport3** [fabricjs/fabric.js#5889]
Hi There
We have integrated fabric js for creating personalize images with adding graphics and text.
On few mobile devices for example 

Android 7.0; Moto G (5)
Android 9; SM-A530F
Android 9; SM-A530F

On browser Chrome verison 77.0.3865

When saving png image from canvas it is giving black image.
Please find attach black image for example.

Could you please assist how can we fix this?
Thanks
![1569231538](https://user-images.githubusercontent.com/40258575/65509911-873a8f00-decb-11e9-8002-7e307e429340.png)

**Comment by umangvyas** [comment]
Can you please share fiddle for the same?

**Comment by asturur** [comment]
Yes would be nice to have a fiddle, as requested by the guidelines when you open an issue.
Eventually, depending how big your image is, this can be an out of memory problem.
How much is device pixel ratio of those devices?

**Comment by powerthinking** [comment]
I'm having this exact same issue, and just found this with a Google search.  It only appears to be happening on certain IOS devices and it's not consistent.  The first time an image is uploaded it might work, the second and third times it appears black and then it works again.  
![Screenshot_20191118-144557_Messages](https://user-images.githubusercontent.com/16319465/69087794-dfe26000-0a14-11ea-90ea-aa71b5a03021.jpg)
