### ISSUE TITLE
Shadow not working for JPG images

### ISSUE THREAD

**Issue by fahadnabbasi** [fabricjs/fabric.js#5891]
## Version
2.7.0

## Test Case
https://jsfiddle.net/fahadnabbasi/c603qvno/8/

## Information about environment
Browser - Windows 10
Chrome latest - Version 77.0.3865.90 (Official Build) (64-bit)

## Steps to reproduce
Open the fiddle and notice the shadow applied to both PNG and JPG images
Click on JPG image and shadow will disappear (or sometimes won't even show up at all)

## Expected Behavior
Shadow on JPG image should be retained

## Actual Behavior
Shadow disappears only on Chrome, it appears fine on Opera and FireFox browsers

**Comment by asturur** [comment]
i think is a new chrome bug, or a particular problem of hardware acceleration in your computer with chrome and windows.

Try to disable hardware acceleration in chrome for a test and the fiddle should work.

**Comment by fahadnabbasi** [comment]
@asturur thanks for getting back to me
I disabled the hardware acceleration in chrome but still having the same issue.
Tried it on Mac as well with the latest browser and it is doing the same 

One thing I noticed is it is not JPG vs PNG issue but has something to do with transparent pixels. If you upload a PNG with no transparent pixels, shadow doesn't work in this case as well

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/65614356-c514e180-dfb7-11e9-89ea-a233cb6bdd5e.png)

is this working?

**Comment by asturur** [comment]
yes just uploaded to 77 and now is broken.

**Comment by asturur** [comment]
i bet there is an issue already on chromium bug tracker, if not you should open it

**Comment by asturur** [comment]
needs to be reproduced in plain JS and then in case submitted to chromium.
After getting chrome 77 i can see the problem too

**Comment by fahadnabbasi** [comment]
@asteriskman7 ok so how can I reproduce this in plain JS? html5 canvas? because when we load for the very first time, it shows the shadow but when we select the image or move it, shadow disappears

**Comment by asteriskman7** [comment]
@fahadnabbasi I think you intended to mention @asturur

**Comment by asturur** [comment]
my guess would be make a fiddle where the image is load and has shadow. add
a set timeout where you clear the canvas, you draw again the image.

see if the bug happen.

**Comment by fahadnabbasi** [comment]
@asteriskman7 sorry about that, yes I meant @asturur 
@asturur thanks, will try n create a fiddle about that

**Comment by asturur** [comment]
Did you manage to create a fiddle?

**Comment by fahadnabbasi** [comment]
@asturur nope, not yet, I managed to find a work around for the bug. 
You add any filter to the image then the shadow shows up, so I apply tint with 0.1 value and then set it to 0 again and it works fine

**Comment by MohamedElamry** [comment]
I have the same issue but in my case you can see the shadow and once start to interact with the canvas the shadow disappears. I also have a Blur filter on all the images if the value is 0 shadows are not rendered but if any other value even 0.0001 shadows work fine.

Could it be actually a fabricjs bug not a browser bug? 
Note that there was a similar issue many years ago https://github.com/fabricjs/fabric.js/issues/1372 and I could replicate the issue using JS code see http://jsfiddle.net/Kienz/BJda8/

**Comment by JamalAPI** [comment]
The issue can be solved easily by applying a filter via drop-shadow() function: 

`ctx.filter = 'drop-shadow(9px 9px 20px black)';`

See my CodePen: https://codepen.io/jamalassaf/pen/rNNyxOx

**Comment by asturur** [comment]
https://jsfiddle.net/82amsxvb/

update the fiddle for semplicty

**Comment by asturur** [comment]
@MohamedElamry it was not happening with chrome 76, it started with 77, that is why is not a fabricJS bug.

**Comment by DangerD256** [comment]
Any way to make temp fix for that? Like JamalAPI proposed?

**Comment by asturur** [comment]
For me firefox still works.
I can't update something in fabricJS since this is a bug and something to accomodate.
Someone should open an issue to the affected browsers.

**Comment by DangerD256** [comment]
All existing browsers are affected... =(

**Comment by asturur** [comment]
not on my machine. for me just chrome. Also if you disable hw accelerarion, it just works everywhere.

**Comment by DefeninMaxime** [comment]
Is something planned to fix the problem?

**Comment by fidaktk** [comment]
I have the same issue. for temp fix.
Apply transparent stroke to the object solves the issue.
`canvas.getActiveObject().set('stroke','rgba(0,0,0,0)');
canvas.renderAll();`

**Comment by idealstudija** [comment]
Has anyone found a solution to this problem?

**Comment by asturur** [comment]
i did not investigate for a bug, i m still convinced is a chrome only problem from hardware acceleration.
I could not manage to replicate in plain Js tho.
That would help.

**Comment by xiaowangsmile** [comment]
> I have the same issue. for temp fix.
> Apply transparent stroke to the object solves the issue.
> `canvas.getActiveObject().set('stroke','rgba(0,0,0,0)'); canvas.renderAll();`
it is not work

**Comment by hamzawain7** [comment]
Still not working on chrome mac.
http://jsfiddle.net/hamzawain7/ksf0r12u/

Try moving the image if you initially see the shadow

**Comment by xiaowangsmile** [comment]
Still not working on chrome81.

**Comment by hamzawain7** [comment]
Reported to chromium devs:
https://bugs.chromium.org/p/chromium/issues/detail?id=1063336

**Comment by asturur** [comment]
great thank you!

**Comment by tonycaso** [comment]
if you use an image filter the shadow will be visible

**Comment by xiaowangsmile** [comment]
Still not working on chrome83

> Reported to chromium devs:
> https://bugs.chromium.org/p/chromium/issues/detail?id=1063336

**Comment by asturur** [comment]
they say chrome 84 was the good one.
