### ISSUE TITLE
toObject() method not working

### ISSUE THREAD

**Issue by udbhavjatia** [fabricjs/fabric.js#5892]
## Version
3.4.0

## Test Case
https://jsfiddle.net/ezmo2rtk/2/

## Information about environment
Angular Project (CLI 7.2.0) on Google Chrome

## Steps to reproduce
1. Instantiate a fabric canvas
2. Add a rectangle or any other object to it
3. Select the rectangle to make it an 'active object'
4. Get the 'active object' using the canvas.getActiveObject() method
5. Convert the fabric instance of the 'active object' to a normal JS object using the toObject() method

## Expected Behavior
The 'clone' variable should contain a JS object representation of my fabric rectangle instance.

## Actual Behavior
Get this error logged to my console (1st line)-

<b>ERROR TypeError: selectedObject.toObject is not a function</b>

Weird part was that it was working just fine till yesterday evening. Not sure what broke.

**Comment by udbhavjatia** [comment]
<b>Update</b>
Tried to use the clone method on a fabricjs instance and its giving the same error.

**Comment by udbhavjatia** [comment]
Okay figured out the problem...

I had this function in my code: 
`static extendObjectJson(obj, id, objectType) {
    obj.toObject = (function(toObject) {
      return function() {
        return fabric.util.object.extend(toObject.call(this), {
          _oId: id,
          _key: `${objectType}_placeholder_${id}`,
          objectType
        });
      };
    })(obj.toObject);
  }`

which I tried to refactor into an arrow function which is when toObject() stopped working. I didn't realize I had to .bind(this) somewhere. Hope this helps someone one day =)

**Comment by asturur** [comment]
but what was the point of that function in first place?
Seems like you want to avoid referencing stuff for mutation problem.
Is that the case?
Do you wanted to extend the output only?
