### ISSUE TITLE
set text can not triggering ‘change’ event

### ISSUE THREAD

**Issue by jrs320** [fabricjs/fabric.js#5893]

**Comment by jrs320** [comment]
```
textBox.on('changed', () =>  {
   console.log('changed') // not output
   canvas.requestRenderAll()
})
textBox.set('text', 'new text')
```

**Comment by asturur** [comment]
it does do not trigger it, events are generally there to have reactions to user input.
If you set the text property as a dev, run also the code you want on the change event to happen.

What is your particular use case? care to explain?

**Comment by jrs320** [comment]
It's not good smoother experience when editing text on 'Itext' widget directly, so i want to popup a input when click Itext, and set new text into 'Itext' when finish input，at this time i want to know Itext's text is changed for doing something

**Comment by asturur** [comment]
but since you have your input text, you can attach an event there, and you are in control. Is not fabric domain.

**Comment by jrs320** [comment]
yes, may be i think too much, you are right, i deal it like your thinking later
