### ISSUE TITLE
IText fails to show soft keyboard on touch to in embedded webview on Android 10 fabricjs 3.4.0

### ISSUE THREAD

**Issue by sschendel** [fabricjs/fabric.js#5895]
## Version
3.4.0

## Test Case
Load simple fabric canvas with single IText. Touch to edit content. No keyboard displayed.

This started failing with fabricjs version 3.4.0. Version 3.3.2 does not fail in this manner.

## Information about environment
Failing device:
Pixel 2 running Android 10 - chrome 77.0.3865.92

Confirmed no issue with:
Samsung Galaxy S7 SM-G930F running Android 8.0 - chrome 77.0.3865.73

NOTEWORTHY: Running failing device while inspecting embedded webview with Chrome dev tools - no issue - keyboard is shown as expected.

Problem not reproducible in fabricjs versions beore 3.4.0.

## Steps to reproduce

Simple Android app that reproduces bug...

MainActivity.kt
```
package com.example.myapplication

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import kotlinx.android.synthetic.main.activity_main.*

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val webSettings = webView.settings
        webSettings.javaScriptEnabled = true
        webView.loadUrl("file:///android_asset/test.html")
    }
}
```

activity_main.xml
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
<WebView
    android:id="@+id/webView"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />
</androidx.constraintlayout.widget.ConstraintLayout>
```

test.html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport"
          content="initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-touch-fullscreen" content="yes"/>
    <meta name="msapplication-tap-highlight" content="no"/>
    <title>Android: LLP Whiteboard</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/3.4.0/fabric.min.js"></script>
</head>

<body>
<div id="canvasContainer">
    <canvas id="canvas" width="300" height="300"></canvas>
</div>
<script>
    window.addEventListener("load", function(){
        var canvas = new fabric.Canvas("canvas");
        var text = new fabric.IText('testing', {
            left: 50,
            top: 50,
            selectable: false
        });
        canvas.add(text);
        text.enterEditing();
    });
</script>
</body>
</html>
```

## Expected / Actual Behavior

Capture (left: v3.3.2 success!, right: v3.4.0 FAIL):
![fabric_no_keyboard](https://user-images.githubusercontent.com/1459873/65724138-61e98480-e075-11e9-8b52-0dbb770e35f9.gif)

**Comment by asturur** [comment]
the diffs between those 2 tags in git should be easily to obtain.
Do you want to paste them here?

**Comment by sschendel** [comment]
https://github.com/fabricjs/fabric.js/compare/6fd3bc4..e4db8ec

**Comment by asturur** [comment]
i see exactly 0 changes that can be related.
Can it be a chrome bug? The version is not exactly the same.
Is highly improbable that i can fix it from the JS side.

**Comment by sschendel** [comment]
Yeah. I reviewed the deltas as well and did not see an obvious cause. 

That said - the bug only presents itself with 3.4.0, not earlier versions of fabric on same device (Pixel 2, Android 10, chrome 77.0.3865.92).

**Comment by asturur** [comment]
another thing that changed is that there is an accidental e.preventDefault in the touchStart event.
Can you try to enable pointer events in the fabricCanvas and see if something changes?

**Comment by sschendel** [comment]
Sure. Can you clarify what precisely you mean by "enable pointer events in the fabricCanvas"?

**Comment by asturur** [comment]
fabricCanvas.enablePointerEvents = true

**Comment by asturur** [comment]
With this we subscribe to pointer events, that should occur BEFORE touch start and trigger something different. Alternatively you can take  your local copy of fabric, remove the `e.preventDefault()` in touchStart and see if that helps.

**Comment by asturur** [comment]
I have difficulties remembering.
I added a `_onTouchStart` with a `e.prevendDefautl()` because i think this avoid the weird logic of ignoring the generated mousedown event.
This could be the problem that stops the keyboard from popping out.

**Comment by sschendel** [comment]
Setting `canvas.enablePointerEvents = true` did not solve this issue. FYI.

**Comment by sschendel** [comment]
Removing the `e.preventDefault()` as suggested seems to fix the issue.

**Comment by asturur** [comment]
ok so that e.preventDefault has to go away.
Now i have to remind why is there, and i m struggling.

**Comment by asturur** [comment]
probably to avoid the touchStart to generate a mousedown :(

**Comment by asturur** [comment]
i hope is not a chrome bug only. Do you think we can find a spec somewhere?

**Comment by sschendel** [comment]
This spec suggests that cancelling the `touchstart` should have the effect we see with the bug.

https://w3c.github.io/touch-events/#dfn-touchstart

> it should prevent any default actions caused by any touch events associated with the same active touch point, including mouse events or scrolling

**Comment by asturur** [comment]
i disagree 100%.
fabricjs touchstart does calls a function that sets focus on a textarea,

so, super reduced:

```
onTouchStart(e) => {
  e.preventDefault(); //e.target is the upperCanvasElement and the div container
  // ... code to search for what is under your finger
  // ... code that finds a textbox
  textbox.enterEditing();
  // ... some more code will displace a textbox under the your finger with absolute positioning
  textarea.focus();
}
```

 that specific focus(); should have no relation with the previous touch start prevented.

my humble opinion is that this is a chrome bug and that we should try to replicate in plain JS and open an issue.

You have a workaround meantime, that is not 100% perfect. I would suggest eventually use the workaround ad enable pointer events.

The touchstart is going to fire a mousedown too without the preventDefault()

**Comment by asturur** [comment]
another test would be wrapping the textarea.focus in a setTimeout, keeping the event default prevented.

**Comment by sschendel** [comment]
Ok. Thanks for the clarification. My reference to `touchstart` spec and expectations of behavior was coming from a naive understanding.

**Comment by asturur** [comment]
no worries, i have been following the same trail, and just later rememberde fabricjs text is not in the DOM

**Comment by zuhairnaqi** [comment]
Hi @asturur - Adding focus code for textarea working well inside onTouchStart function. but this changes I've made in your library, how can I do this through my project code?.
Updated library code for touchstart
```
_onTouchStart: function(e) {
      e.preventDefault();
      if (this.mainTouchId === null) {
        this.mainTouchId = this.getPointerId(e);
      }
      if (this._iTextInstances) { // --------------->.  added this if block to work
        this._iTextInstances.forEach(function(obj) {
          if (obj.isEditing) {
            obj.hiddenTextarea.focus();
          }
        });
      }
      this.__onMouseDown(e);
      this._resetTransformEventData();
      var canvasElement = this.upperCanvasEl,
          eventTypePrefix = this._getEventPrefix();
      addListener(fabric.document, 'touchend', this._onTouchEnd, addEventOptions);
      addListener(fabric.document, 'touchmove', this._onMouseMove, addEventOptions);
      // Unbind mousedown to prevent double triggers from touch devices
      removeListener(canvasElement, eventTypePrefix + 'down', this._onMouseDown);
    },
```
