### ISSUE TITLE
Blurry images when zoom in on android devices

### ISSUE THREAD

**Issue by vlinde** [fabricjs/fabric.js#5897]
## Version
3.4.0

## Test Case
https://jsfiddle.net/iad_vlinde/bethy6rk/8/

## Information about environment
The issue appears on an ionic app and also on google chrome from android.

## Expected Behavior
The image content must be sharp.

## Actual Behavior
When I open a big image and I zoom in, the image becomes blurry and the text is not understandable.

**Comment by asturur** [comment]
The fiddle renders nothing.
Can you please paste here the big image?

**Comment by vlinde** [comment]
This is the image from fiddle: http://vlinde.show/new_test.jpg

**Comment by asturur** [comment]
is unclear if that image is prduced with fabric, or you want to render it in fabric.

The image you provide is blurry for me id i open it in my phone.

**Comment by vlinde** [comment]
I want to render the image in fabric.
I think the issue is from google chrome engine, like you said, the image is blurry if you open it in browser.

**Comment by asturur** [comment]
If it looks ok on desktop there is little we can do. We can just open an issue on the chromium android issue tracker. Does it looks on desktop?

**Comment by vlinde** [comment]
The issue appears only on google chrome from android.

**Comment by asturur** [comment]
i ll flag it as browser bug.
You should open an issue on their own issue tracker.
