### ISSUE TITLE
Can fabrics operate without DOM in vue?

### ISSUE THREAD

**Issue by mengfei2611** [fabricjs/fabric.js#5899]
In vue, you can't use windows objects and document objects. How do you replace them?

**Comment by mohamediburan** [comment]
@mengfei2611  In vue, it is possible access window and document objects. Refer this [link](https://stackoverflow.com/questions/54166847/how-to-access-the-window-object-in-vue-js).

**Comment by asturur** [comment]
Please if the link is not enough, ise stackoverflow.
