### ISSUE TITLE
How to Generate Curved Text ? 

### ISSUE THREAD

**Issue by sagarvibrant** [fabricjs/fabric.js#5900]
I am using fabric js (version 3.4.0), How can i Generate or Make text Curved ?

**Comment by av01d** [comment]
You can't, at least not "out of the box".
This might help though: https://jsfiddle.net/av01d/4p0syzw3/

**Comment by asturur** [comment]
duplicate of #2544

**Comment by rifatwahid** [comment]
@av01d thanks for sharing the codes. I tried these codes but SVG export not working with it. Do we have any luck with SVG export?

**Comment by av01d** [comment]
> @av01d thanks for sharing the codes. I tried these codes but SVG export not working with it. Do we have any luck with SVG export?

Nope, I have no need for SVG export, so I haven't made any progress on it.

**Comment by rifatwahid** [comment]
> > @av01d thanks for sharing the codes. I tried these codes but SVG export not working with it. Do we have any luck with SVG export?
> 
> Nope, I have no need for SVG export, so I haven't made any progress on it.

:(

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/pull/6543 working on it

**Comment by devsb-tech** [comment]
> You can't, at least not "out of the box".
> This might help though: https://jsfiddle.net/av01d/4p0syzw3/

@av01d  thank for sharing https://jsfiddle.net/av01d/4p0syzw3/ but i have used faced some upper part is cropping issue can you please help here thanks!
here is SS
https://prnt.sc/10ozxzt
