### ISSUE TITLE
Objects in group are blurry when downloaded as PNG with multiplier

### ISSUE THREAD

**Issue by CoachM** [fabricjs/fabric.js#5901]
## Version
3.4.0

## Test Case
https://jsfiddle.net/karolymolnar/pm18eh0z/80/

## Information about environment
Chrome

## Steps to reproduce
1. On an empty canvas add text or other objects to canvas
2. Export via toDataURL({format: 'png', multiplier: 20})
3. On an empty canvas add text or other objects to group and then add to canvas
4. Export via toDataURL({format: 'png', multiplier: 20})
5. On an empty canvas add text or other objects to canvas and other object to group and then add to canvas
6. Export via toDataURL({format: 'png', multiplier: 20})

## Expected Behavior
The bitmap of the objects should be identical

## Actual Behavior
The blurriness of edges of the objects are different:

Object alone on canvas is blurry
![c1](https://user-images.githubusercontent.com/6551869/65833590-3c0ceb80-e2d2-11e9-8989-63e63e952036.png)

compared to object in group
![c2](https://user-images.githubusercontent.com/6551869/65833599-4f1fbb80-e2d2-11e9-86fb-4f93c54b03b3.png)

However when there's an object on canvas and another in group the group is blurry
![c3](https://user-images.githubusercontent.com/6551869/65833602-56df6000-e2d2-11e9-8af1-224b7384e058.png)

**Comment by asturur** [comment]
Hi @CoachM, sorry for the delay.
I think you have a problem of blurriness because of caching.
In order to preserve performances caching has a limited number of pixels.

Please read here:

disabling caching should give you great sharpness.
http://fabricjs.com/fabric-object-caching

**Comment by CoachM** [comment]
I experimented with objectCaching before, however I made the mistake of turning it off on the object level and not on the group level. Now I just set objectCaching to false for the groups and it works fine.

Thanks for the pointer
