### ISSUE TITLE
allowTouchScrolling doesn't work

### ISSUE THREAD

**Issue by 0ro** [fabricjs/fabric.js#5903]
## Version
3.4.0

## Test Case
https://codepen.io/den-bogdanov/pen/eYOwbPj

## Information about the environment
mobile browser chrome, safari

## Steps to reproduce
Open test case and try to scroll with help device emulation in devtools or from a mobile device

## Expected Behavior
Must be scrolling

## Actual Behavior
No touch scrolling

**Comment by Rumthorp** [comment]
Is anyone able to merge this?

**Comment by asturur** [comment]
I got stuck in understanding if there is something fundamentally wrong in my last touch events pr.

**Comment by Lyqxyz** [comment]
How to solve this problem @asturur

**Comment by 0ro** [comment]
@asturur is there any problems with my pr? I think you've just forgotten to add a condition with allowTouchScrolling because we have this same line in _onMouseMove event [here](https://github.com/fabricjs/fabric.js/blob/50962efe6bbd77174cda2e9bd169c19d301edb7a/src/mixins/canvas_events.mixin.js#L381)

**Comment by Lyqxyz** [comment]
"we have this same line in _onMouseMove event here?" What does this sentence mean @0ro

**Comment by asturur** [comment]
@oro your pr is probably good and i did not forget about it.
I'm currently busy getting in the PR about upperCanvas retina scaling and the sub targets mouse in/out event, and that is taking all my free time.

**Comment by 0ro** [comment]
> "we have this same line in _onMouseMove event here?" What does this sentence mean @0ro

I meant we have the same behavior _onMouseMove method and in onTouchStart we don't. I added this behavior in my pr.

**Comment by asturur** [comment]
I will look into this as soon as i m having back my touch device.
The point of preventing default there was to avoid mousedown and mouseup to fire because of touchstart and touchend.

not firing preventDefault would mean add back the removal of mousedown listener when touchstart fires. Stuff i was happy to have removed.

Seems silly to me that is possible to stop the mouse events fire but just at the cost of preventing everything.

**Comment by flexeo** [comment]
Same problem here, scrolling doesn't work on mobile devices with allowTouchScrolling = true.

**Comment by asturur** [comment]
We have a PR tracking this

**Comment by linewei** [comment]
Same problem.

**Comment by CarlosSamp** [comment]
Same Problem here

**Comment by CarlosSamp** [comment]
could fix it adding this to the Script
`window.addEventListener("load", function(){
			jQuery('#canvasshow').css('pointer-events', 'none');
			jQuery('.upper-canvas').css('pointer-events', 'none');
			jQuery('#canvasshow').css('touch-action', 'manipulation');
	});`

**Comment by suman** [comment]
Same problem in version 3.6.2, does anybody has any solution for this ?

**Comment by 0ro** [comment]
> Same problem in version 3.6.2, does anybody has any solution for this ?

you can see my solution in pull request above https://github.com/fabricjs/fabric.js/pull/5904

**Comment by A-ZC-Lau** [comment]
@0ro does that mean I need to go into the code and update it myself? I'm using the 3.6.3 npm package.

**Comment by lynmije** [comment]
> > Same problem in version 3.6.2, does anybody has any solution for this ?
> 
> you can see my solution in pull request above #5904

I tried your solution but its still not working.

**Comment by de-don** [comment]
The same problem

**Comment by Abdelwahab07** [comment]
Same Problem here, Is there any fix ??

**Comment by yangjiang3973** [comment]
Is there any hack solution while waiting for this issue being solved? thanks!

**Comment by alexshmalex** [comment]
Found the cause of this bug. First line (e.preventDefault();) in the _onTouchStart function prevent the event propagation. FabricJS version 4.1.0

**Comment by javinladish** [comment]
Has anyone found a fix to allow mobile scrolling to work? I've tried a bunch of workarounds but couldn't get any to work.

**Comment by alexshmalex** [comment]
> Has anyone found a fix to allow mobile scrolling to work? I've tried a bunch of workarounds but couldn't get any to work.

Try this code in your project. It works with fabric 4.1.0

            (function() {
                var addListener = fabric.util.addListener,
                    removeListener = fabric.util.removeListener,
                    addEventOptions = { passive: false };

                fabric.util.object.extend(fabric.Canvas.prototype, /** @lends fabric.Canvas.prototype */ {
                    _onTouchStart: function(e) {
                        //e.preventDefault();
                        if (this.mainTouchId === null) {
                            this.mainTouchId = this.getPointerId(e);
                        }
                        this.__onMouseDown(e);
                        this._resetTransformEventData();
                        var canvasElement = this.upperCanvasEl,
                        eventTypePrefix = this._getEventPrefix();
                        addListener(fabric.document, 'touchend', this._onTouchEnd, addEventOptions);
                        addListener(fabric.document, 'touchmove', this._onMouseMove, addEventOptions);
                        // Unbind mousedown to prevent double triggers from touch devices
                        removeListener(canvasElement, eventTypePrefix + 'down', this._onMouseDown);
                    }
                });
            })();

Also set touch-action for canvases:

`$('canvas').css('touch-action', 'manipulation');`

**Comment by wnbittle** [comment]
Thanks @alexshmalex for your solution, very helpful.  My solution was similar - I wanted to allow object selection/move _and drawing_ - I think for a general solution there could be more considerations.

```javascript
(function(){
  var defaultOnTouchStartHandler = fabric.Canvas.prototype._onTouchStart;
  fabric.util.object.extend(fabric.Canvas.prototype, { 
    _onTouchStart: function(e) { 
      var target = this.findTarget(e); 
      // if allowTouchScrolling is enabled, no object was at the
      // the touch position and we're not in drawing mode, then 
      // let the event skip the fabricjs canvas and do default
      // behavior
      if (this.allowTouchScrolling && !target && !this.isDrawingMode) { 
        // returning here should allow the event to propagate and be handled
        // normally by the browser
        return; 
      } 

      // otherwise call the default behavior
      defaultOnTouchStartHandler.call(this, e); 
    } 
  });
})();
```

**Comment by javinladish** [comment]
@alexshmalex I wasn't able to get your code above to work. My create canvas function looks like:
```
function createCanvas(w, h) {
          canvasContainerEl = document.getElementById("canvas-container");
          canvas = new fabric.Canvas("meme-canvas",{
	      allowTouchScrolling: true   
          });
          canvas.selection = false;
          canvas.setBackgroundColor("white", canvas.renderAll.bind(canvas));
```

And then I put your code into a <script> at the bottom of the <body>. It had no effect so I probably did something incorrect. I'm not too well versed in Javascript.

**Comment by Hoody123** [comment]
> Thanks @alexshmalex for your solution, very helpful. My solution was similar - I wanted to allow object selection/move _and drawing_ - I think for a general solution there could be more considerations.
> 
> ```js
> (function(){
>   var defaultOnTouchStartHandler = fabric.Canvas.prototype._onTouchStart;
>   fabric.util.object.extend(fabric.Canvas.prototype, { 
>     _onTouchStart: function(e) { 
>       var target = this.findTarget(e); 
>       // if allowTouchScrolling is enabled, no object was at the
>       // the touch position and we're not in drawing mode, then 
>       // let the event skip the fabricjs canvas and do default
>       // behavior
>       if (this.allowTouchScrolling && !target && !this.isDrawingMode) { 
>         // returning here should allow the event to propagate and be handled
>         // normally by the browser
>         return; 
>       } 
> 
>       // otherwise call the default behavior
>       defaultOnTouchStartHandler.call(this, e); 
>     } 
>   });
> })();
> ```

It works well, thank you

**Comment by javinladish** [comment]
> > Has anyone found a fix to allow mobile scrolling to work? I've tried a bunch of workarounds but couldn't get any to work.
> 
> Try this code in your project. It works with fabric 4.1.0
> 
> ```
>         (function() {
>             var addListener = fabric.util.addListener,
>                 removeListener = fabric.util.removeListener,
>                 addEventOptions = { passive: false };
> 
>             fabric.util.object.extend(fabric.Canvas.prototype, /** @lends fabric.Canvas.prototype */ {
>                 _onTouchStart: function(e) {
>                     //e.preventDefault();
>                     if (this.mainTouchId === null) {
>                         this.mainTouchId = this.getPointerId(e);
>                     }
>                     this.__onMouseDown(e);
>                     this._resetTransformEventData();
>                     var canvasElement = this.upperCanvasEl,
>                     eventTypePrefix = this._getEventPrefix();
>                     addListener(fabric.document, 'touchend', this._onTouchEnd, addEventOptions);
>                     addListener(fabric.document, 'touchmove', this._onMouseMove, addEventOptions);
>                     // Unbind mousedown to prevent double triggers from touch devices
>                     removeListener(canvasElement, eventTypePrefix + 'down', this._onMouseDown);
>                 }
>             });
>         })();
> ```
> 
> Also set touch-action for canvases:
> 
> `$('canvas').css('touch-action', 'manipulation');`

I got this code to work, but if I select and try to move an object the canvas is still scrolling.

How can I stop the scrolling behavior if an object is selected?

**Comment by alexshmalex** [comment]
> How can I stop the scrolling behavior if an object is selected?

Try this:

        var tmf = function(e) {
            e.preventDefault();
        };
        canvas.on('mouse:down', function(e) {
            if (canvas.getActiveObject()) {
                $('*').bind('touchmove', tmf);
            }
        });
        canvas.on('mouse:up', function(e) {
            $('*').unbind('touchmove', tmf);
        });

**Comment by javinladish** [comment]
> > How can I stop the scrolling behavior if an object is selected?
> 
> Try this:
> 
> ```
>     var tmf = function(e) {
>         e.preventDefault();
>     };
>     canvas.on('mouse:down', function(e) {
>         if (canvas.getActiveObject()) {
>             $('*').bind('touchmove', tmf);
>         }
>     });
>     canvas.on('mouse:up', function(e) {
>         $('*').unbind('touchmove', tmf);
>     });
> ```

Uncaught TypeError: Cannot read property 'on' of undefined

**Comment by NandeeshG** [comment]
> Thanks @alexshmalex for your solution, very helpful. My solution was similar - I wanted to allow object selection/move _and drawing_ - I think for a general solution there could be more considerations.
> 
> ```js
> (function(){
>   var defaultOnTouchStartHandler = fabric.Canvas.prototype._onTouchStart;
>   fabric.util.object.extend(fabric.Canvas.prototype, { 
>     _onTouchStart: function(e) { 
>       var target = this.findTarget(e); 
>       // if allowTouchScrolling is enabled, no object was at the
>       // the touch position and we're not in drawing mode, then 
>       // let the event skip the fabricjs canvas and do default
>       // behavior
>       if (this.allowTouchScrolling && !target && !this.isDrawingMode) { 
>         // returning here should allow the event to propagate and be handled
>         // normally by the browser
>         return; 
>       } 
> 
>       // otherwise call the default behavior
>       defaultOnTouchStartHandler.call(this, e); 
>     } 
>   });
> })();
> ```

Hi, where exactly should I add this code? Sorry if this is a bad question, I am new to fabric.js library. 
Thanks

**Comment by wnbittle** [comment]
@NandeeshG This should be run after you've loaded the fabric.js script but before you interact with the library.

**Comment by cby016** [comment]
Any update on this? It's pretty important to have this functionality on mobile and it's been over a year with no fix.

**Comment by cby016** [comment]
> How can I stop the scrolling behavior if an object is selected?

@javinladish 

Try this code (basically @alexshmalex's code with a minor change):

```
(function() {
    var addListener = fabric.util.addListener,
        removeListener = fabric.util.removeListener,
        addEventOptions = { passive: false };

    fabric.util.object.extend(fabric.Canvas.prototype, /** @lends fabric.Canvas.prototype */ {
        _onTouchStart: function(e) {

          this.getActiveObject() && e.preventDefault && e.preventDefault();

          if (this.mainTouchId === null) {
            this.mainTouchId = this.getPointerId(e);
          }
          this.__onMouseDown(e);
          this._resetTransformEventData();
          var canvasElement = this.upperCanvasEl,
              eventTypePrefix = this._getEventPrefix();
          addListener(fabric.document, 'touchend', this._onTouchEnd, addEventOptions);
          addListener(fabric.document, 'touchmove', this._onMouseMove, addEventOptions);
          // Unbind mousedown to prevent double triggers from touch devices
          removeListener(canvasElement, eventTypePrefix + 'down', this._onMouseDown);
        }
    });
})();
```

**Comment by 1248499257** [comment]
Same Problem here

**Comment by moghwan** [comment]
@alexey-altteam's code and @wnbittle's edit work like a charm in fabricjs 4.2.0, thank you!
https://github.com/fabricjs/fabric.js/issues/5903#issuecomment-699011321

**Comment by zmiju** [comment]
> (function() {
>             var addListener = fabric.util.addListener,
>                 removeListener = fabric.util.removeListener,
>                 addEventOptions = { passive: false };
> 
>             fabric.util.object.extend(fabric.Canvas.prototype, /** @lends fabric.Canvas.prototype */ {
>                 _onTouchStart: function(e) {
>                     //e.preventDefault();
>                     if (this.mainTouchId === null) {
>                         this.mainTouchId = this.getPointerId(e);
>                     }
>                     this.__onMouseDown(e);
>                     this._resetTransformEventData();
>                     var canvasElement = this.upperCanvasEl,
>                     eventTypePrefix = this._getEventPrefix();
>                     addListener(fabric.document, 'touchend', this._onTouchEnd, addEventOptions);
>                     addListener(fabric.document, 'touchmove', this._onMouseMove, addEventOptions);
>                     // Unbind mousedown to prevent double triggers from touch devices
>                     removeListener(canvasElement, eventTypePrefix + 'down', this._onMouseDown);
>                 }
>             });
>         })();

Hi,

do you know how to make it work in Typescript?

**Comment by rasel-xs** [comment]
@asturur 
I'm facing same issue and trying to fix many way but doesn't work.  can anyone help please

**Comment by maxcmoi89** [comment]
> Thanks @AlexShmalex for your solution, very helpful. My solution was similar - I wanted to allow object selection/move _and drawing_ - I think for a general solution there could be more considerations.
> 
> ```js
> (function(){
>   var defaultOnTouchStartHandler = fabric.Canvas.prototype._onTouchStart;
>   fabric.util.object.extend(fabric.Canvas.prototype, { 
>     _onTouchStart: function(e) { 
>       var target = this.findTarget(e); 
>       // if allowTouchScrolling is enabled, no object was at the
>       // the touch position and we're not in drawing mode, then 
>       // let the event skip the fabricjs canvas and do default
>       // behavior
>       if (this.allowTouchScrolling && !target && !this.isDrawingMode) { 
>         // returning here should allow the event to propagate and be handled
>         // normally by the browser
>         return; 
>       } 
> 
>       // otherwise call the default behavior
>       defaultOnTouchStartHandler.call(this, e); 
>     } 
>   });
> })();
> ```

This fix is needed for fabric 5.3 too

**Comment by alexisbar** [comment]
Does anybody has a working solution to use in fabric v6 ? `fabric.util.object` does not exists anymore as stated here https://github.com/fabricjs/fabric.js/issues/8299

**Comment by jayzambrano** [comment]
I am too looking for a solution for V6. Is **allowTouchScrolling** not working at all? or is there a specific set of parameters that need to be added/avoided for it to work properly?  @0ro your solution works perfectly for v 5.3, do you know how it can be recreated for v6?

**Comment by jayzambrano** [comment]
This solution works for my scenario in version V6, @alexisbar  not sure if it will work for everybody but you can try:

  (function(){
    var defaultOnTouchStartHandler = Canvas.prototype._onTouchStart;
    Object.assign(Canvas.prototype, { 
      _onTouchStart: function(e) { 
        var target = this.findTarget(e); 
        // if allowTouchScrolling is enabled, no object was at the
        // the touch position and we're not in drawing mode, then 
        // let the event skip the fabricjs canvas and do default
        // behavior
        if (this.allowTouchScrolling && !target && !this.isDrawingMode) { 
          // returning here should allow the event to propagate and be handled
          // normally by the browser
          return; 
        } 
  
        // otherwise call the default behavior
        defaultOnTouchStartHandler.call(this, e); 
      } 
    });
  })();

**Comment by jayzambrano** [comment]
This solution works for my scenario in V6, @alexisbar not sure if it will work for everybody, but you can try this:

`(function () {
    var defaultOnTouchStartHandler = Canvas.prototype._onTouchStart;
    Object.assign(Canvas.prototype, {
      _onTouchStart: function (e) {
        var target = this.findTarget(e);
        if (this.allowTouchScrolling && !target && !this.isDrawingMode) {
          return;
        }
        defaultOnTouchStartHandler.call(this, e);
      }
    });
  })();`

**Comment by asturur** [comment]
For everyone having issue with allowTouchScrolling check this
https://github.com/fabricjs/fabric.js/pull/10078
