### ISSUE TITLE
How to convert fabrics js into pdf

### ISSUE THREAD

**Issue by onlinecheckwriter** [fabricjs/fabric.js#5906]
Hello,
How can we convert fabricsjs json into pdf and save it in backend server?

**Comment by oxiao** [comment]
may you take a look at [node-canvas](https://github.com/Automattic/node-canvas) ?

**Comment by asturur** [comment]
So node-canvas will allow you to have a pdf renderer from the canvas itself, so all the low level instructions of fabricJS should become a PDF.
I'm not sure how would you handle fonts.

**Comment by asturur** [comment]
I'll close the issue since there is nothing to solve from me, but if you want to talk about it, feel free to write.

**Comment by dungmv** [comment]
Why fabricjs rely on the jsdom? can fabricjs rely on NodeCanvas and remove jsdom? I think that is better

**Comment by asturur** [comment]
Well fabric run in browser and additionally in node.
Fabric does some dom manipulation and without JSDOM that would not be possible.
Jsdom also provide a clean interface for the canvas.

If the point is to initialize a backend as PDF in node from node-canvas, that should be somehow organized trough JSDOM to pass the correct options.

**Comment by dungmv** [comment]
@asturur  I found the solution to export pdf,
```js
const fs = require('fs');
const fabric = require('fabric').fabric;
const { createCanvas } = require('canvas')
const utils = require('jsdom/lib/jsdom/living/generated/utils');

const mPDFcanvas = createCanvas(600, 800, 'pdf') // see "PDF Support" section

const el = fabric.document.createElement('canvas');
el[utils.implSymbol]._canvas = mPDFcanvas;
const fabricCanvas = new fabric.StaticCanvas(el, { width: 1024, height: 1024 });
fabricCanvas.setZoom(10);

fabric.Image.fromURL('http://thenewcode.com/assets/images/thumbnails/homer-simpson.svg', function (data) {
    var img = data.set({ left: 0, top: 0, width: 500, height: 500 });
    fabricCanvas.add(img);
    fabricCanvas.renderAll();
    var stream = fabric.util.getNodeCanvas(fabricCanvas.lowerCanvasEl).createPDFStream();
    // var stream = fabricCanvas.createPNGStream();
    stream.pipe(fs.createWriteStream('output.pdf'));
});
```
but the result is image ember inside pdf,

**Comment by asturur** [comment]
looks nice. i think we should document somewhere. Does it work good also with custom fonts?

**Comment by dungmv** [comment]
I am not test yet, I will test with custom fonts later

**Comment by hjchanna** [comment]
Does anyone have luck with the solution?

**Comment by morenogiudici** [comment]
> @asturur I found the solution to export pdf, but the result is a image inside the pdf.
> 
> ```js
> const fs = require('fs');
> const fabric = require('fabric').fabric;
> const { createCanvas } = require('canvas')
> const utils = require('jsdom/lib/jsdom/living/generated/utils');
> 
> const mPDFcanvas = createCanvas(600, 800, 'pdf') // see "PDF Support" section
> 
> const el = fabric.document.createElement('canvas');
> el[utils.implSymbol]._canvas = mPDFcanvas;
> const fabricCanvas = new fabric.StaticCanvas(el, { width: 1024, height: 1024 });
> fabricCanvas.setZoom(10);
> 
> fabric.Image.fromURL('http://thenewcode.com/assets/images/thumbnails/homer-simpson.svg', function (data) {
>     var img = data.set({ left: 0, top: 0, width: 500, height: 500 });
>     fabricCanvas.add(img);
>     fabricCanvas.renderAll();
>     var stream = fabric.util.getNodeCanvas(fabricCanvas.lowerCanvasEl).createPDFStream();
>     // var stream = fabricCanvas.createPNGStream();
>     stream.pipe(fs.createWriteStream('output.pdf'));
> });
> ```

This work, if you importsvg instead of insert the svg as image the pdf elements remains vector.

**Comment by asturur** [comment]
If you load it as an image YES. if you load as loadSVGfromURL or loadSVGfromString probably it won't be.

**Comment by asturur** [comment]
this is how i load it
```js
const fs = require('fs');
const fabric = require('fabric').fabric;
const { createCanvas } = require('canvas')
const utils = require('jsdom/lib/jsdom/living/generated/utils');
const svg = fs.readFileSync(__dirname + '/file.svg', 'utf8');
const mPDFcanvas = createCanvas(800, 800, 'pdf') // see "PDF Support" section
const el = fabric.document.createElement('canvas');
el[utils.implSymbol]._canvas = mPDFcanvas;
const fabricCanvas = new fabric.StaticCanvas(el, { width: 800, height: 800 });

fabric.loadSVGFromString(svg, function (objects, options) {
    var svg = fabric.util.groupSVGElements(objects, options);
    fabricCanvas.add(svg);
    fabricCanvas.renderAll();
    var stream = fabric.util.getNodeCanvas(fabricCanvas.lowerCanvasEl).createPDFStream();
    // var stream = fabricCanvas.createPNGStream();
    stream.pipe(fs.createWriteStream('output.pdf'));
});
```

this is the PDF i get

[output.pdf](https://github.com/fabricjs/fabric.js/files/4672022/output.pdf)

**Comment by onlinecheckwriter** [comment]
Hello,
We can do it in different way.
We can use puppeteer to convert canva page to pdf.

If you are laravel developer you can use : https://github.com/spatie/browsershot

**Comment by asturur** [comment]
But that will give you a raster PDF, that is what @morenogiudici was complaining about

**Comment by andrewzolotukhin** [comment]
@onlinecheckwriter, If you're going to print this PDF then it's not a case. Ideally it would be great to have a CMYK colors support. I'm thinkg about developing it.

**Comment by morenogiudici** [comment]
@asturur I was saying the same thing, but after having tested the libraries over the weekend and checked the results of "node-canvas" and pdfKit (with svgtopdfkit) I prefer to export to svg and use an illustrator script to convert to pdf, because it gives a better result and more stable.

@andrewzolotukhin If you print with professional Rip software the conversion in cymk during rasterization it is much more accurate, so I think it is enough to limit the RGB color space  to the color space of the cymk during user choices.

**Comment by asturur** [comment]
I agree that limiting the color space and let professional do the work is way better. Conversion is print machine dependent and you do not want to mess it up.

@morenogiudici how does svg to pdf from illustrator handle custom fonts linked with external refs?

**Comment by morenogiudici** [comment]
@asturur I'm limiting the choice of fonts to some selected googlefonts and I do not plan to give the possibility to upload custom fonts, so I simply pre-installed the fonts on the system that do the conversion with illustrator. Unfortunately, I don't think it's a solution suitable for everyone.

**Comment by asturur** [comment]
can you run illustrator in a linux container? or are you bound to some desktop like server?

**Comment by morenogiudici** [comment]
In my case I use the pdf to print at the factory. On the server I save the data in JSON and when clients confirm the order and I have to print I create the files locally.

I think that the illustrator license does not allow it to be used for server automation, maybe inkskape it's more appropriate both legally and at the automation level

**Comment by asturur** [comment]
inkscape can be run in a container and from command line, i use it for converting pdf and eps to fabricjs importable stuff ( most of the time )

**Comment by andrewzolotukhin** [comment]
Sometime printing companies needs to specify CMYK values directly in
template (not on RIP stage). That's why I said that it would be great (for
me) to have CMYK color space directly in Fabric.
But main issue here is that CMYK in SVG is not very broad used, for example
Inkscape can't convert SVGs with objects having CMYK colors to PDFs with
CMYK colored objects.
I mean that it isn't enough just to generate a SVG with CMYK colors, the
main challenge is to correctly convert it to PDF with CMYK colors.

**Comment by morenogiudici** [comment]
The svg specifications support icc profiles, but there are incompatibilities with browsers.

PDFKit supports cymk colors but svgtopdfkit dosen't (it is easy to extend the parseColor function of svgtopdfkit)

Scribus seems to generate pdfs that are more compatible with typographic standards than inkscape

I haven't tested the libraries enough to evaluate the full support of the svg created by fabricjs, but maybe it's a starting point

**Comment by asturur** [comment]
once you solve the conversion problem accurately, any rgb color svg can become a cymk svg, outside fabricjs. There is no reason for this to happen in fabric.

Also i wonder when printing standars will start to consider svg as valid format.

**Comment by andrewzolotukhin** [comment]
@morenogiudici, yes, SVG specs support ICC profiles, but a little of
editors respect colors set using ICC profile while converting to PDF. For
example Inkscape just ignore it and replaces with RGB fallback. Scribus is
better, I managed to run it in Docker container to convert ICC SVG to CMYK
PDF, but it's very slow. I didn't know about the SVG-to-PDFKit, that might
simplify the process. But how it deals with things like filters. shadows,
etc?

**Comment by jhondge** [comment]
> looks nice. i think we should document somewhere. Does it work good also with custom fonts?

@asturur node-canvas does support custom font right? [registerFont()](https://github.com/Automattic/node-canvas/#registerfont-for-bundled-fonts)

**Comment by Saberjsd** [comment]
I try this successfully.
But the pdf with dpi 72 or dpi 300 uncontrollable.
How can I control the dpi for 300 by settings?

**Comment by asturur** [comment]
pdf does not have DPI.
PDF has 72 points per inch and you can use decimals to achieve an higher precision.
You can embed images of any size and display them o an arbitrary area.

The DPI concept does not apply to PDF.

**Comment by Saberjsd** [comment]
> pdf does not have DPI.
> PDF has 72 points per inch and you can use decimals to achieve an higher precision.
> You can embed images of any size and display them o an arbitrary area.
> 
> The DPI concept does not apply to PDF.

Thanks for help me.
I open the PDF with Photoshop, click the “Image” menu and choose “Image Size”, look at “pixels/inch” value.
PDF convert to bitmap page may have DPI,because the PDF have really size with inch and have pixels size.

**Comment by Saberjsd** [comment]
### `drwaImage` with scale or crop render very blur.
[Here is result PDF](https://github.com/Saberjsd/assets/raw/main/comments/canvas/output_1622709280832.pdf)
#### This is preview with 200%:

![preview with 200%](https://raw.githubusercontent.com/Saberjsd/assets/main/comments/canvas/preview_with_200.png)

### I wite a demo for show my problem for export PDF.

```js
const exportPdf = async () => {
  const { createCanvas, loadImage } = require('canvas');
  const fs = require('fs');
  const path = require('path')
  let canvasWidth = 200;
  let canvasHeight = 200;
  const canvas = createCanvas(canvasWidth, canvasHeight, 'pdf');
  const ctx = canvas.getContext('2d');
  // image is a 800 x 800 px png 
  const imgUrl = "http://capcium.com/wp-content/themes/capcium/dist/images/-placeholders/img-example-square.png" 
  let img = await loadImage(imgUrl);
  const padding = 100;

  ctx.scale(0.1, 0.1)
  // draw origin image
  ctx.drawImage(img, padding, padding);
  // draw image with scale
  ctx.drawImage(img, img.width + padding * 2, padding, img.width - 1, img.height - 1);
  // draw image with crop
  ctx.drawImage(img, 0, 0, img.width - 1, img.height - 1, padding, img.height + padding * 2, img.width, img.height);
  
  const outPath = path.join(__dirname, `./output_${+new Date()}.pdf`)
  canvas.createPDFStream().pipe(fs.createWriteStream(outPath));
  console.log('end')
}

exportPdf()
```

**Comment by asturur** [comment]
ok there is an issue here.
I m not sure what the createPdfStream does with the drawImage operation.

The best you can do is to be sure the PDF before converting has the best quality possible image inside.
Then everything else is a photoshop export issue i have no idea about.
When you open the PDF with a simple viewer, is the image detailed enough?

**Comment by Saberjsd** [comment]
> ok there is an issue here.
> I m not sure what the createPdfStream does with the drawImage operation.
> 
> The best you can do is to be sure the PDF before converting has the best quality possible image inside.
> Then everything else is a photoshop export issue i have no idea about.
> When you open the PDF with a simple viewer, is the image detailed enough?

It's not very clear when you zoom in.
Because draw image with scale or crop, `node-canvas` will create a temporary canvas to draw on and then draw onto the PDF canvas.
Only when drawing the original image, is the complete image.
[Here is result PDF](https://github.com/Saberjsd/assets/raw/main/comments/canvas/output_1622709280832.pdf)

**Comment by Saberjsd** [comment]
Hi, @asturur 
How can I export pdf by `puppeteer`, not a image in pdf,  all fabric objects are vector in pdf.
Who can help me, please

**Comment by okeoke85** [comment]
is there a way to transform fabric canvas to standart html canvas like a screenshot canvas? After that pdf export woluld be much easier i guess.

**Comment by asturur** [comment]
hi @saberjsd that is not a simple task.
You may need someone to take the work for you.
I don't have freely available code to solve the issue.

**Comment by mordak-95** [comment]
Finally, what is the best solution?
Use inkscape or pdfkit?
I had worked with aspose pdf before
And is there no standard for Fabric's Jason translation?

**Comment by asturur** [comment]
i got the best result with this library and some work
https://pdfkit.org/

**Comment by asturur** [comment]
The trick is to understand how pdf render works in that library and product a renderPdf function in fabricJS that will go over the standard renderAll process but instead of canvas commands, emits compatible pdf commands through that library.
I will open a request for release what i created a work let's see if they accept it

**Comment by mordak-95** [comment]
Thank you very much if you can give me a sample code to read.

**Comment by saberjsd** [comment]
Hello! Is there any new progress?

**Comment by hassanphp** [comment]
Hi, Everyone interesting topic for me, I am also working on same project now days. What is final thoughts? I would highly appreciate if someone can share his final thoughts or experience?

**Comment by Andrekarma** [comment]
Hi, has anyone found a viable way to make a pdf from a fabric canvas that is not a generated image inside the pdf?

Our solution at the moment is to create an SVG from the canvas and using inkscape to obtain the final pdf.
But we are having nightmares with the fonts

**Comment by ShaMan123** [comment]
I think node-canvas is the viable way forward
You can tryout fonts using the register fonts method
checkout #9185

**Comment by alagiyanirav** [comment]
@Andrekarma : We have tried the node-canvas but some properties of text and image is not working in node-cannas. But you can check and confirm that is it working for your needs.

**Comment by ShaMan123** [comment]
@alagiyanirav which didn't work?

**Comment by alagiyanirav** [comment]
@ShaMan123 : I think font style bold and italic wasn't the same as fabric and text-decoration :overline not working with text-background. Also, some custom features like curve text are not working.

**Comment by ShaMan123** [comment]
I wonder, when did you try it?
Curved text works great in my demo in #9185 
And I am guessing the rest might need a retest
Node canvas came a long way the last few years

**Comment by alagiyanirav** [comment]
> I wonder, when did you try it? Curved text works great in my demo in #9185 And I am guessing the rest might need a retest Node canvas came a long way the last few years

I was using the old version of fabric. Version : 1.7.22

**Comment by ShaMan123** [comment]
Ancient stuff
Fabric and node canvas leaped forward since then

**Comment by Andrekarma** [comment]
In our case fonts are already registered with fabric.nodeCanvas.registerFont, which is good

@ShaMan123 i tried your example, in the pdf the texts are not selectable, why is that?
We are on fabric 4.3, do you think it could be possible to integrate your solution?

**Comment by ShaMan123** [comment]
Regarding selecting text, in the PR there is a comment about it. A node canvas option to render text as path or as glyph. Hopefully that will solve it.
I guess you could use v4 with latest node canvas to get PDF exporting.
I am bias. V6 is so much better. And makes development of features much shorter.

**Comment by Andrekarma** [comment]
@ShaMan123 i'm trying to make it work with fabric 4.6
The main problem i'm facing is on the ctx.drawImage function that gives this error "TypeError: Image or Canvas expected"

Seems to me that "new Canvas(0, 0, 'pdf').getContext('2d')" has a mismatch with the canvas fabric is expecting 
Do you have any suggestion?

**Comment by ShaMan123** [comment]
Seems you need to pass the canvas, not the context

**Comment by Andrekarma** [comment]
In which point?

**Comment by ShaMan123** [comment]
In the point it throws at

**Comment by Andrekarma** [comment]
It is not working on fabric 4.3

**Comment by madmacc** [comment]
> ```js
> createPDFStream
> ```
@asturur  Is there a way to get this to work in the browser rather than on the server?

**Comment by madmacc** [comment]
> this is how i load it
> 
> ```js
> const fs = require('fs');
> const fabric = require('fabric').fabric;
> const { createCanvas } = require('canvas')
> const utils = require('jsdom/lib/jsdom/living/generated/utils');
> const svg = fs.readFileSync(__dirname + '/file.svg', 'utf8');
> const mPDFcanvas = createCanvas(800, 800, 'pdf') // see "PDF Support" section
> const el = fabric.document.createElement('canvas');
> el[utils.implSymbol]._canvas = mPDFcanvas;
> const fabricCanvas = new fabric.StaticCanvas(el, { width: 800, height: 800 });
> 
> fabric.loadSVGFromString(svg, function (objects, options) {
>     var svg = fabric.util.groupSVGElements(objects, options);
>     fabricCanvas.add(svg);
>     fabricCanvas.renderAll();
>     var stream = fabric.util.getNodeCanvas(fabricCanvas.lowerCanvasEl).createPDFStream();
>     // var stream = fabricCanvas.createPNGStream();
>     stream.pipe(fs.createWriteStream('output.pdf'));
> });
> ```
> 
> this is the PDF i get
> 
> [output.pdf](https://github.com/fabricjs/fabric.js/files/4672022/output.pdf)

@asturur Is there a way to get this to work in the browser rather than on the server?

**Comment by ShaMan123** [comment]
You will get many more error
Node canvas can't work on the browser

**Comment by madmacc** [comment]
If anyone else wants to export as svg via the browser I did it this way.

   ```
  this.canvas.renderAll();

     if (download) {
      const svgString = this.canvas.toSVG();
      console.log('svgString', svgString); // This is your SVG as a string
      this.saveSVG(svgString, 'exportedCanvas.svg');
    }

async saveSVG(svgString: string, filename: string) {
    const blob = new Blob([svgString], {type: 'image/svg+xml'});
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }

```

**Comment by asturur** [comment]
There isn't a full proof reliable way to create very good PDFs on the browser from fabricJS.
I implemented a couple of time the functionality, and i have one i did recently for few objects that you can find here:
https://github.com/asturur/nfc-retro-label-printer/blob/main/src/extensions/fabricToPdfKit.ts

Is a conversion between canvas objects and PDFKIT.
Works for me for what i have to do, may work for you or not.

If there was a real good library between PDFKIT and JSPDF i would happily do an export layer, but non of them match fabric very well.
Consider that code has the scope of making pdf with certain content, is not a generic translation layer, but you can build upon it or use it to understand

**Comment by more-strive** [comment]
I recently developed a function to generate PDF from json data using fabric.js. Anyone who needs it is welcome to consult and use it.  
[yft-design](https://yft.design/zh/editor). 
[Github](https://github.com/dromara/yft-design)

<img width="1683" height="874" alt="Image" src="https://github.com/user-attachments/assets/693ac379-eeaf-4fa8-a172-3094c8d62844" />

[yft-design-1761188492042.pdf](https://github.com/user-attachments/files/23076729/yft-design-1761188492042.pdf)

[yft-design-1761188346997.pdf](https://github.com/user-attachments/files/23076743/yft-design-1761188346997.pdf)

**Comment by mauricekindermann** [comment]
> I recently developed a function to generate PDF from json data using fabric.js. Anyone who needs it is welcome to consult and use it. [yft-design](https://yft.design/zh/editor). [Github](https://github.com/dromara/yft-design)

Very cool thanks for sharing! But how do you convert the JSON data to PDF? I checked your code but it calls a backend API I can't access. It works in your demo but I can see it's not 100% stable yet, but very close, and text appears to be vectorized. 

Are you skipping the. SVG / `canvas.toSVG()` entirely?

**Comment by more-strive** [comment]
> > I recently developed a function to generate PDF from json data using fabric.js. Anyone who needs it is welcome to consult and use it. [yft-design](https://yft.design/zh/editor). [Github](https://github.com/dromara/yft-design)
> 
> Very cool thanks for sharing! But how do you convert the JSON data to PDF? I checked your code but it calls a backend API I can't access. It works in your demo but I can see it's not 100% stable yet, but very close, and text appears to be vectorized.
> 
> Are you skipping the. SVG / `canvas.toSVG()` entirely?

yes, it is implemented through the underlying API of PDF

**Comment by mauricekindermann** [comment]
> yes, it is implemented through the underlying API of PDF

@more-strive Nice! I JUST got it working using `canvas.toSVG()` → Chromium headless → PDF. Google Fonts render correctly with a delay for font loading, and I believe that means the fonts are embedded in the PDF itself for portability. Thanks for the inspiration!

I'm not sure what it's done with the fonts y position.- and the shadow font I can't select it but it appears to be a vector when I zoom in. Interesting. And no issues with masked images too.

1. Screenshot from my editor: 
<img width="895" height="416" alt="Image" src="https://github.com/user-attachments/assets/209e583b-faad-409d-a022-0307ca1b7aaa" />

2. Rasterized via jsPDF (0.5 / 4x) - 231 kb
[raster-test.pdf](https://github.com/user-attachments/files/23691830/raster-test.pdf)

3. Vector via Chrmoium - 488 kb
[vector-test.pdf](https://github.com/user-attachments/files/23691832/vector-test.pdf)

4. SVG (text on path removed due to SVG errors) - 9 kb
![Image](https://github.com/user-attachments/assets/7b9c6066-cdbf-4bb8-b7e0-38b9b1469081)

UPDATE: After playing around with this I realized my custom FabricJS Text objects don't work perfectly with toSVG(), which makes sense since I'm saving custom properties and would need to handle the maths to support their positions (tricky).

I believe the Vector PDF file size must be so big due to rasterizing images and having to embed fonts, whereas the SVG is tiny but doesn't support fonts or rasterized images. 

So I did some real-world printing, and for normal day-to-day use there is no visual difference between the PDF vector and the jsPDF (plus it's half the size). If you needed commerical print-quality - you'd have to use vanilla FabricJS objects or ensure your custom objects map perfectly toSVG().

**Comment by asturur** [comment]
For canvas to pdf i wrote some custom code as well, that is hosted here, not sure about @more-strive approach, i used pdflib i think on the browser, is not complete it just does what i needed but i think i can be fairly extended to cover all the classes

https://github.com/ZaparooProject/zaparoo-designer/blob/main/src/extensions/fabricToPdfKit.ts

That is also free to consume, i was thinking of making it an official extension but there is a lot of work to finish.

**Comment by more-strive** [comment]
The currently developed feature does not support shadow yet. The serialized data through Fabric.js can basically support commercial printing, and of course, CMYK is also supported. However, the function of exporting PDF is not open source

**Comment by asturur** [comment]
> The currently developed feature does not support shadow yet. The serialized data through Fabric.js can basically support commercial printing, and of course, CMYK is also supported. However, the function of exporting PDF is not open source

So when you said that everyone was free to consult it, what did you mean?

**Comment by mauricekindermann** [comment]
@more-strive Your editor is so cool, I'd love to see how you handle PDFs and Text Transform/Intensity, but as a build it seems none of it is inspectable. 

@asturur I can't imagine a better solution than **FabricJS → toSvg() → a server-side Chromium Printer**. It's flawless in my testing. There's no additional work other than installing browsershot/snappdf server side. 

In my case I ran into issues because I extended Textbox (added vertical alignment, fill, stroke, and ry/rx), and so toSVG() doesn';t support them so I'd need to fix that. 

Do you want me to setup a demo/test so you can play with it?

**Comment by asturur** [comment]
I don't need to, but your example could make an excellent doc/suggestion for anyone interested, it could be a page on fabricjs.com in the docs part. i can't run a node server there but you can link to a codesandbox that does. But even just describing the process would be so helpful for many people.

Regarding the better solution or not, outside people running commercial business and so having servers, many projects are still interested in a browser only solution. Like the one i developed is a free for everyone label printer, i don't want to go through the hassle of having a node server at all.
