### ISSUE TITLE
Blur filter makes dark border / glow on clipped images

### ISSUE THREAD

**Issue by ultradeq** [fabricjs/fabric.js#5910]
## Version
2.4.0

## Test Case
https://codepen.io/ultradeq/pen/RwbXZKm?editors=0010

## Information about environment
All browsers

## Steps to reproduce
When I use blur filter on fabric.Image object with transparent PNG it looks ok. But when I use clipPath on fabric.Image object, then make transparent PNG with toDataURL() or cloneAsImage() and then blur it, it makes strange dark glow. Any idea how to get rid of it?

**Comment by asturur** [comment]
can you post here the image that does not make the black border? we need better blur code, that is for sure.

**Comment by danilogr** [comment]
Does fabric.js implement its own blur code? If so, it sounds like the blur code is hard-coding edges without alpha

**Comment by asturur** [comment]
Sorry for being late.
Yes fabricJS has some webgl blur code that you can find here
https://github.com/fabricjs/fabric.js/blob/master/src/filters/blur_filter.class.js
And some canvas2d blur filter that i made and that probably is wrong.
(it uses drawImage with opacity to simulate blur, is fast but has problems with transparency )

**Comment by asturur** [comment]
I would love help to make it better.

**Comment by LucThi-ss** [comment]
I found a workaround way for this issue,  instead of keeping the background completely transparent, fill it with a color. 

I override the `toCanvasElement` method (http://fabricjs.com/docs/fabric.js.html#line15767) and fill the canvas with `ffffff01`. 

It solves the problem for me.

**Comment by The-Luc** [comment]
I found a workaround way for this issue. Overriding the `toCanvasElement` method (http://fabricjs.com/docs/fabric.js.html#line15767) and fill the canvas will `ffffff01` instead of keep it completely transparent.

It solves the problem for me.

**Comment by asturur** [comment]
oh that would be a nice workardound for the filter too
