### ISSUE TITLE
Rendered SVG is Blurry When Zoom In SVG 

### ISSUE THREAD

**Issue by sagarvibrant** [fabricjs/fabric.js#5915]
![AddSVG](https://user-images.githubusercontent.com/36664189/66450894-cfcf7c00-ea77-11e9-910e-17af325fd654.png)
 - This Image of SVG which i was render SVG on canvas.

![BlurrySVG](https://user-images.githubusercontent.com/36664189/66450950-0d340980-ea78-11e9-9152-67d73237132e.png)
 - This Image of Blurry SVG when I Zoom in that SVG
I'm Using this Code for render SVG : 

 fabric.loadSVGFromString(**mySVGCode**, function (objects, options) {
        var obj = fabric.util.groupSVGElements(objects, options);
        obj.set({
          left: 100,
          top: 100,
        });
        yow.canvas.add(obj);
        yow.canvas.setActiveObject(obj).renderAll();
        yow.save();
      });

thank you : )

**Comment by dan-lee** [comment]
Do you use `canvas.setZoom(value)`?

**Comment by dan-lee** [comment]
For the record, setting `objectCaching` to `false` solved the issue for me.

```js
fabric.Object.prototype.objectCaching = false
```

**Comment by asturur** [comment]
So caching as you can read here:
http://fabricjs.com/fabric-object-caching
Will definitely makes things blurry.
There are configuration options.
In 3.0+ caching can be turned off and will be turned on if some options requires it ( like clipPath ).

To be honest, most of the time there is no reason to cache rects,circles,simple paths.

Caching is usefull on TEXT and complex groups.

**Comment by dan-lee** [comment]
> To be honest, most of the time there is no reason to cache rects,circles,simple paths.
Maybe it's time to change the default value for those in the next major version? :)

**Comment by asturur** [comment]
it could be.
I m working on a beta with new controls api, and i will change easy things there.

Definitely rects, circle, ellipse and lines are better non cached by default.

The point is giving the developer a choice.
A rect with a border and a dash array, and a fill that is a gradient, may be worth a caching

**Comment by icandothat2** [comment]
I'm working with a complex SVG. Without caching it's too slow to zoom in/out and move around on canvas. With caching it's too blurry.  I'd like to redraw and cache on zoom to clear it up. So far I'm unsuccessful, I have yet to figure it out.

**Comment by melchiar** [comment]
Assuming you're loading the svg as an image, you can adjust the width, height, cropX, and cropY properties during zooming to exclude parts of the svg from the cache that are outside of the viewport

**Comment by icandothat2** [comment]
Thanks for the super quick response. I'm using loadSVGFromURL(), the
documentation says it  " parses [the SVG] into a set of fabric objects."
does that count as an image?

**Comment by melchiar** [comment]
To load an svg as an image use `fabric.Image.fromURL`. Be aware though you'll lose the ability to individually manipulate objects within the svg.

**Comment by icandothat2** [comment]
hmm. will that prevent me from re-saving it as a vector image? I'm opening
vector images, allowing user to add elements and then re-saving as a
vector.

**Comment by melchiar** [comment]
You can still export as an svg, but it will be an svg with an embedded svg image (still vector though)

**Comment by icandothat2** [comment]
still vector is key. I'll give it a shot, thank you.

**Comment by icandothat2** [comment]
melchiar, I've been messing with caching and some other options
I thought tonight about your comment:  "you can adjust the width, height, cropX, and cropY properties during zooming to exclude parts of the svg from the cache that are outside of the viewport" would I do this to reduce the amount of data in the cache? would that improve the image quality?

**Comment by asturur** [comment]
Hi @icandothat2  there is this doc about caching:
http://fabricjs.com/fabric-object-caching
It should explain whch are the parameters for youu to make a bigger cache area.

**Comment by icandothat2** [comment]
Thank you I’ve read it to no avail.
  If I create image from svg and turn on cache, the panning is great but
the zoom is slow and blurry.  If I create image from url the zoom is good
and clean but the panning is terrible and the cache doesn’t seem to matter.

It was previously suggested that I try cropping to reduce the drawn area
but  the truth is, if I’m doing creat from url, the higher the zoom the
faster it pans, so I think fabrics is already doing that.

I’m dealing with SVGs that could have thousands of vectors, maybe tens of
thousands?

**Comment by melchiar** [comment]
@icandothat2 can you post a fiddle showing the issue?

**Comment by icandothat2** [comment]
Yes, I can. I believe I now understand the problem.
1. My SVG has over 40,000 vectors.
2. If using imageFromURL the zoom works well but panning is terrible.
3. if using loadSVGFromURLthe pan works well but zoom is terrible.

Here's why I believe this is the case:
when using imageFromURL, fabric rasterizes a pretty high resolution image
and as one zooms in, it automatically clips the non-rendered portions of
the image, so zooming gets better as you zoom.  However, the massive image
size means panning is abysmal.
when using loadSVGFromURL, fabric creates a "just big enough" raster of the
image on canvas, thus panning is snappy! However with each zoom a new "just
big enough" image has to be re-rendered from the svg which takes a lot of
time when the SVG has 40,000 vectors, thus zooming is basically a
non-starter it's horrible.

My goal today is hybridize each problem behaviour to see what works best.
For the bad panning on imageFromURL I'm going to, on pan, swap the image
for a cheap copy and then replace it on stop. The other choice is to try to
just just prevent the SUPER HIGH res image from being rendered.
For the bad zoom I'm going to basically do the same, swap the "SVGfromURL"
file with a imageFromURL file, until the zoom has stopped (by "zoom" I mean
zooming with scroll wheel.

I recognize I can just not scroll with mouse wheel, but I want to so, you
know, I'm going to. haha.

I'll post my results.

**Comment by icandothat2** [comment]
Ok I got this working yesterday, here's how.

I do loadSVGFromURL to rasterize my original, gigantic, SVG.
Once the SVG is loaded I use fabric.image.fromURL(<element>.toDataURL()) to
convert the element on the canvas to a placeholder  image that I store as a
variable.
This is quick and is done in the background. When the user tries to zoom
(using the scroll wheel), I swap the rastered SVG for the cheap placeholder
and I let them zoom that.
I start a timer in the background, on a loop and when it's been more than
400 milliseconds since last scroll wheel, I swap the low grade copy for the
re-rastered SVG.

It's working really well, I could not be more pleased.

**Comment by enriqueerrando** [comment]
Hi,

I'm having the exact same scenario, but with a difference: in my case the user can add unlimmited complex SVGs (not as heavy as the one mentioned by @icandothat2) to the scene. That means that I cannot keep a variable of every generated cheap placeholder because would eat too many resources.

Is there a better aproach?

Thanks!

**Comment by enriqueerrando** [comment]
That would be great @icandothat2  ;) How do I contact you? I'm not used to use github and cannot find a place to message u privately.

**Comment by icandothat2** [comment]
I am also uncertain of the mechanics of that task. How about this use my
username, remove the “2”, at gmail.  Try that, remind me of the problem and
I’ll let you know what I did.

**Comment by enriqueerrando** [comment]
Ok, I've just sent u the email ;)

Thanks for helping me out!

**Comment by enriqueerrando** [comment]
Hi!!
I've found a fix to this issue at stackoverflow (look for the 'EXAMPLE 2 LARGER CACHE' at [https://stackoverflow.com/questions/47513180/fabricjs-lines-in-group-become-blurry/#answer-47570950](url))!!

It works for me 100%!!

`fabric.perfLimitSizeTotal = 225000000;
fabric.maxCacheSideLimit = 11000;`

Does this solution has any cons?

Thanks in advance!

**Comment by icandothat2** [comment]
Yeah it doesn’t work. I don’t remember why. Maybe only doesn’t work with
some file types?

**Comment by enriqueerrando** [comment]
Hi @icandothat2,

The thing is that simple fix I posted it does finally work! I've been searching for this several years now...

Do u know if has any cons?

Thanks!

**Comment by icandothat2** [comment]
I’m sorry, I knew this existed but it wouldn’t work for my needs.  I have
to think back. As I recall there were Some trade offs. I’d like to see your
work. If you’re interested we should do a zoom call or something. I’ll show
you what I did.
