### ISSUE TITLE
how to drawing ellipse

### ISSUE THREAD

**Issue by jrs320** [fabricjs/fabric.js#5916]
how to drawing ellipse? help! thank you very much.

**Comment by jrs320** [comment]
I got it , it's just to set skewX and skewY value can change circle to ellipse.

**Comment by asturur** [comment]
Hi @jrs320 we do have the Ellipse shape.
Did you try it?

**Comment by asturur** [comment]
var ellipse = new fabric.Ellipse({ rx, ry })

**Comment by jrs320** [comment]
Ok, i try it, thx
