### ISSUE TITLE
Blurry rendering of rectangles (non-integer translate values)

### ISSUE THREAD

**Issue by marcohamersma** [fabricjs/fabric.js#5918]
## Version
3.3.2

## Test Case
http://jsfiddle.net/tuphj75z/3/

## Information about environment
Firefox & Chrome. Mac. Regular DPI display (no retina)

## Steps to reproduce
Go to the test case, observe the different displays between the fabric canvas and the regular canvas. 

## Expected Behavior
The fabric-rendered canvas should be as sharp as the regular canvas.

## Actual Behavior
The objects are rendered on subpixels (even though each object's position is set to rounded numbers) causing them to display blurry. Perhaps because the `translateX` and `translateY` values for each rendered object have non-integer as values.

![image](https://user-images.githubusercontent.com/577144/66590718-4c05b480-eb89-11e9-8900-92f1ba41b206.png)

---

Is this an actual bug, or are there some settings I need to change to make this work as expected?

**Comment by asturur** [comment]
A common missing information in fabric is that the stroke of the rect is default as 1 ( like SVG ) and takes space when is transparent.
So effectively your rects are wide 3.

if i set strokeWidth to 0 to each of those rects, this is my result:

![image](https://user-images.githubusercontent.com/1194048/66678909-3a95d880-ec6d-11e9-950d-bee5a0b91efc.png)

**Comment by asturur** [comment]
I think this issue here deserve a place in this page, it happens quite often.
http://fabricjs.com/fabric-gotchas

**Comment by marcohamersma** [comment]
Ah got it, great! Thanks for the quick reply 👍
