### ISSUE TITLE
canvas.containsPoint result is not right when change object width and height

### ISSUE THREAD

**Issue by jrs320** [fabricjs/fabric.js#5919]
first create a rect

      let rect = fabric.Rect({
        width: 1, 
        height: 1
      })

      canvas.add(rect)

changed rect's width and height when drag rect moving 

      let width = coord.x - coordS.x
      let height = coord.y - coordS.y

      rect.set({
        width,
        height
      })

then click rect to judging current point if in rect, the result is false

      let isInRect = canvas.containsPoint(opt.e, rect, opt.pointer)
      // isInRect = false

is it wrong for me to use this way ?  thx

**Comment by jrs320** [comment]
I got it, it should invoke setCoords method again, thx

**Comment by huanghaiyang** [comment]
+ 1 how to use setCoords

**Comment by huanghaiyang** [comment]
object.set({
  width,
  height,
})
object.setCoords(); // call it after object.set()
