### ISSUE TITLE
Unable to find target object  while dropping canvas object on another object in same canvas during move or mouseup

### ISSUE THREAD

**Issue by Pratik2409** [fabricjs/fabric.js#5921]
## Version
2.4.0

## Test Case
https://jsfiddle.net/Pratik2409/jyc1mwae/12/

## Information about environment
Fabric js 3.4.0

## Steps to reproduce
1. Move any object from canvas and put on some another object in the same canvas.

## Expected Behavior
1. The target key should give another object details rather than moved object details. 

## Actual Behavior
1. The target key gives moved object details.

**Comment by asturur** [comment]
During a transformation, the target is steady.
You can add a `object.on('moving', callback)` event that will look for any other object at that mouse position that is not the same as the one being moved, and get the information you want in this way.

**Comment by enuke-shahroz** [comment]
> During a transformation, the target is steady.
> You can add a `object.on('moving', callback)` event that will look for any other object at that mouse position that is not the same as the one being moved, and get the information you want in this way.

This also pointing to moved object.
