### ISSUE TITLE
FlipX in 3.4.0 Not Respecting ViewBox

### ISSUE THREAD

**Issue by mwcbrent** [fabricjs/fabric.js#5923]
Up-front apologies if this is covered in the docs somewhere, I scoured and couldn't find it.  I may be searching for the wrong terms.  

I'm noticing a difference in how flipX is handled on SVG elements that I have on the canvas.  

## Version
3.4.0

## Test Case
https://jsfiddle.net/mwcbrent/q10srhuc/5/

## Information about environment
Chrome Browser (latest)

## Steps to reproduce
Here is how this was rendered in 1.7.2 - https://jsfiddle.net/mwcbrent/8k469qwy/2/

## Expected Behavior
When using FlipX, I had expected the SVG shape to be transformed based on the full SVG view box.  In my example, the left position of the central white circle should shift relative to the viewBox's size.

## Actual Behavior
When using FlipX on an element the SVG shape is flipped without consideration of its position in its view box.

**Comment by mwcbrent** [comment]
I've found that if I group the elements and then flip them it happens to work for my situation:

Solution - https://jsfiddle.net/mwcbrent/spyo3fza/3/

**Comment by asturur** [comment]
So the basic notion is that there is no SVG objects as a whole.
We import various pieces and then we make a group.

If you flip the single pieces they flip i think over their origin ( it may be over the center i do not remember ).

This is not explained in the docs, if i could find the right place i could add a example of flipping objects vs flipping groups of objects.

**Comment by mwcbrent** [comment]
That makes sense for the library to work like that.  It seemed like the breaking changes doc for V2 touches on this.  It seemed like this was rooted in the PathGroup changes from this doc:

http://fabricjs.com/v2-breaking-changes <http://fabricjs.com/v2-breaking-changes>

Is that related?
