### ISSUE TITLE
Object#strokeUniform should take Canvas#getZoom() into account.

### ISSUE THREAD

**Issue by deping** [fabricjs/fabric.js#5925]
## Version
2.4.0

## Expected Behavior
Object#strokeUniform should take Canvas#getZoom() into account.
That is when I zoom the scene by mouse wheel, the stroke width should be fixed if Object#strokeUniform is true. Currently it only take Object#scaleX/scaleY into account.

**Comment by awehring** [comment]
I don't think so.

Zoom currently works as I would expect it: Getting closer to the objects, so that they appear larger. The proportions of the objects - icluding the proportion of the border - shall stay the same.

**Comment by asturur** [comment]
Yes @awehring  zoom is a vieport feature.
Is like asking that when you look closer at the screen, the border to stay constant.

The feature you are asking for would be like a sort of outline of the object, aimed at representing a selection state or an hover effect or something else.

Not a stroke

**Comment by melchiar** [comment]
If that's something you really want, you could just perform a `strokeWidth` / `zoom` calculation on your objects whenever the zoom is changed.

**Comment by deping** [comment]
thanks for your feedback.
I just change fabric.Object.prototype._renderStroke to suite my need.

**Comment by dbbert** [comment]
> If that's something you really want, you could just perform a `strokeWidth` / `zoom` calculation on your objects whenever the zoom is changed.

Is this still the recommended way of achieving this effect (stroke width stays 1 pixel thick, irrespective of zoom level of the viewport) in Fabric 4.2.0? Or is there another way?

**Comment by asturur** [comment]
There isn't a way because it hasn't been marked ever as a feature. We should understand what the feature is and implement it. Would you be able to describe it a bit more in detail?

**Comment by dbbert** [comment]
Sure! I have a fabric canvas that I can zoom and pan, by following [these instructions](http://fabricjs.com/fabric-intro-part-5).

Now I want to place a shape on this canvas (for example a rectangle or circle), and I want the border of this shape to seemingly stay the same width, independent of the zoom level of the canvas. Here is a [short video](https://imgur.com/36P9gSf) of what it should look like. Note that the border of the rectangle doesn't become thicker as we zoom in.

Ideally, this would be something that I can enable as a property on the canvas, for example: `autoScaleStrokeWidth: false`.

Not sure how hard this would be to add as a feature, or if there is a simple workaround?

**Comment by asturur** [comment]
it would never be a canvas feature, at best a per object setting, and not related to stroke.
Stroke already has the uniform property related to scale, if you add more options there is an high chance that you have incompatibility between the combination of options.
This could be an outline or something like that.

**Comment by dbbert** [comment]
Yes, that would work as well! Let me know if there's anything I can do to support the development of this feature.

**Comment by asturur** [comment]
You can start to hack a PR.
The idea is that you start to add a property to the object main class, called outline.
You look a the function renderPaintInOrder

```
    /**
     * @private
     * @param {CanvasRenderingContext2D} ctx Context to render on
     */
    _renderPaintInOrder: function(ctx) {
      if (this.paintFirst === 'stroke') {
        this._renderStroke(ctx);
        this._renderFill(ctx);
      }
      else {
        this._renderFill(ctx);
        this._renderStroke(ctx);
      }
    },
```

and you can add at the end of the function a `this._renderOutline(ctx)`

Then you think of writing thing `_renderOutline; function(ctx) { }` function.

To get some inspiration it can be just a copy of what we do for the rect render function.

**Comment by dbbert** [comment]
In the end I solved my issue with the suggestion of @melchiar: every time the zoom is changed, I update the strokeWidth of all my objects. This way I can also easily update the size of other things to make them look scale-invariant, like the cornerSize of the control handles.

```
function onZoomChange(canvas) {
  let w = 1; // desired width in pixels
  let strokeWidth = w / canvas.getZoom();
  for (let object of canvas.getObjects()) {
    object.set('strokeWidth', strokeWidth);
    // can also update other things here
  }
}
```

In any case, thanks for your help @asturur. Your hints will certainly be useful to others who bump on this thread.

**Comment by melchiar** [comment]
Glad it helped!

**Comment by OmkarPh** [comment]
> In the end I solved my issue with the suggestion of @melchiar: every time the zoom is changed, I update the strokeWidth of all my objects. This way I can also easily update the size of other things to make them look scale-invariant, like the cornerSize of the control handles.
> 
> ```
> function onZoomChange(canvas) {
>   let w = 1; // desired width in pixels
>   let strokeWidth = w / canvas.getZoom();
>   for (let object of canvas.getObjects()) {
>     object.set('strokeWidth', strokeWidth);
>     // can also update other things here
>   }
> }
> ```
> 
> In any case, thanks for your help @asturur. Your hints will certainly be useful to others who bump on this thread.

hi @dbbert 
which event did you listen for this onZoomChange

**Comment by dbbert** [comment]
I implemented a zoom change on mousewheel scroll, by listening to the `"mouse:wheel"` fabric event.

**Comment by OmkarPh** [comment]
> I implemented a zoom change on mousewheel scroll, by listening to the `"mouse:wheel"` fabric event.

thanks, this works partially for me

Since i've used `canvas.zoomToPoint` at several places, mousewheel doesn't fire. there, so I had to listen to `after:render`

**Comment by KaidongChen** [comment]
> 
But stroke will be fuzzy when zoom is too large

**Comment by KaidongChen** [comment]
> 

@dbbert But stroke will be fuzzy when zoom is too large.
