### ISSUE TITLE
A function that will always return the center cordinates of your current view, even if you zoomed it

### ISSUE THREAD

**Issue by Xatnagh** [fabricjs/fabric.js#5926]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by asturur** [comment]
@Xatnagh issue templates are for a reason.

You can obtain the center coordinates of your current view using transformPoint and invertTransform.

```
var myCenterCoordinates = fabric.util.transformPoint({
  x: canvas.width / 2,
  y: canvas.height / 2,
}, fabric.util.invertTransform(canvas.viewportTransform));
```

please read:
http://fabricjs.com/using-transformations

**Comment by Xatnagh** [comment]
I copy and pasted your code into my script and the return is half of canvas width and height everytime, no matter how much I zoomed or panned

**Comment by asturur** [comment]
Seems weird to me.
That function should do exactly that.

**Comment by Xatnagh** [comment]
It will always return the center of the entire canvas, not the current view port, but thanks to your answer I found the solution: 
function CenterCoord(){
   return{
      x:fabric.util.invertTransform(canvas.viewportTransform)[4]+(canvas.width/zoom)/2,
      y:fabric.util.invertTransform(canvas.viewportTransform)[5]+(canvas.height/zoom)/2
   }

}

**Comment by asturur** [comment]
i would think your function is like mine. i have to test and see with my eyes
