### ISSUE TITLE
How can I use fabricjs in a react project?

### ISSUE THREAD

**Issue by maniac0s** [fabricjs/fabric.js#5927]
I already tried a few tutorials and things but none really gives what I need...

https://www.npmjs.com/package/react-fabricjs is 3 years old and hasn't gotten any maintaining since then
https://github.com/tbolis/react-sketch is somewhat newer however not exactly what I need.

The main issue is, that it seems everything with react and fabricjs is either outdated or not well maintained.

I also don't want to depend on x packages where I don't know how long they get maintained or when some update of react or fabric breaks the whole thing.

How can you develop something for production under these circumstances?

What should I use?

**Comment by horizon0514** [comment]
I am developing a REACT binding for fabricjs
https://github.com/react-fabricjs/react-fabricjs
Get involved if you like.

**Comment by ShaMan123** [comment]
We are thinking of exposing bindings, hooks and such
Could you elaborate on your repo?
What is the goal?
We want low level stuff like `useCanvas`, `useEventListener` and maybe other stuff
