### ISSUE TITLE
How to draw a sector

### ISSUE THREAD

**Issue by jrs320** [fabricjs/fabric.js#5929]
I want to draw a sector of angle 30, and i try drawing a Circle with endAngle of 30, but it seem show the circle of radian  30, not of angle 30, is there any way to do this, think you very much

**Comment by awehring** [comment]
I don't know a direct solution in fabric.js, but a workaround:

Draw the sector / arc with SVG and import it  with `fabric.loadSVGFromURL()` or create the SVG-string (dynamically with Javascript if necessary) and convert it with `fabric.loadSVGFromString()`.

**Comment by awehring** [comment]
You can convert degree to radian with: `fabric.util.degreesToRadians()`.

But - as far as I know - fabric.js draws allways a segment, not a sector of a circle with `startAngle` and `endAngle:`.
https://jsfiddle.net/awehring/e4c58ybw/1/

For a sector you can combine the segment with a triangle between the endpoints of the arc and the center of the circle (see grouping in fabric.js). This requires some calculations, if you need it dynamically.

Or you draw the sector with SVG and import it to a fabric.js object: `fabric.loadSVGFromURL()`

If you need it dynamically you can create the SVG string  (lookup: SVG path, arc) and covert it: `fabric.loadSVGFromString()`
This might help to understand the SVG string: https://www.raincloud.co.uk/svg/svgSector_C.html

**Comment by jrs320** [comment]
@awehring  thank you
