### ISSUE TITLE
Sides of rectangle stroke are truncated when size is elongated

### ISSUE THREAD

**Issue by jsbakker** [fabricjs/fabric.js#5932]
## Version
3.2.0, master

## Test Case
https://jsfiddle.net/staeryatz/9bj6rhg4/8/

## Information about environment
- IE 11.805.17763.0
- Edge 44.17763.771.0
- Chrome 77.0.3865.90 (Windows)
- Safari 13.0.2 (15608.2.30.1.1) (Mac)

## Steps to reproduce
Use provided jsfiddle to click-drag to create several elongated rectangles. This does not occur with all rectangles, but is guaranteed to reproduce after several tries. Rectangles with larger widths and relatively smaller heights increase reproduction rate.

**Note**: the method used for creating rectangles is to create it on click down and then set width and height as the size is determined by the user. <= See update below.

## Expected Behavior
Rectangle stroke is visible around the entire border.

## Actual Behavior
Rectangle stroke is not visible on right and left borders, and the right and left sides are also truncated for the top and bottom borders.

![fabric_rect_no_sides](https://user-images.githubusercontent.com/15329951/67525559-d4935300-f667-11e9-9a00-b51fb297b9d6.PNG)

**Update**:  Even if I change the endRectangle() function to create a completely new rectangle with the same dimensions, add it to the canvas and remove the currentRect, I still get the stroke rendering issue. Therefore it does not seem to be related to changing the width and height of an existing rectangle.

**Update 2**: The same is true when creating a very tall but skinny rectangle, in that the top and bottom borders are truncated. If you then create a rectangle large enough, all four edges of the stroke will vanish.

**Comment by asturur** [comment]
https://jsfiddle.net/ru1jLsdk/

@jsbakker, the problem is that you are using negative width and height.

Please look at the updated fiddle. I added Math.abs in order to get positive width/height.

You have to adjust for top and left in order to respect mouse movement.

**Comment by jsbakker** [comment]
@asturur  Thanks for the quick response. Knowing this now, I can definitely update the state and event management to adjust top and left. However I still feel that this is a bug because using negative width and height values appear to work the majority of the time - and it is only when the rectangle reaches certain proportions that the stroke rendering starts to fail.

If negative widths and heights are truly not supported, they should not work at all, instead of most of the time. Especially when the rectangle fill still works when the stroke fails.

**Comment by asturur** [comment]
Well i can update the docs with a clarification.
a width and an height are dimensions, and negative dimensions are sort of a stretch.
Something is thinking of moving `-5 pixels` to say you move 5 pixels in the opposite direction wher your positive values are, but being `-5 pixels wide` is a bit strange to me,

I would not expect a negative dimension to make sense.
