### ISSUE TITLE
How to mask Image,text and background color

### ISSUE THREAD

**Issue by prabhathAmila** [fabricjs/fabric.js#5934]
Hi
I create custom umbrella design app using fabricjs
So I upload umbrella SVG without grouping.

the problem is,

I want to add image and text into the umbrella top  Svg separately. so the user can edit umbrella part mask 
Also, user the user can change background-color

please [download source files](https://drive.google.com/file/d/15zVPKtdsYVSIYb-uICGVBvI3aRtGH2NB/view?usp=sharing)

**Comment by asturur** [comment]
Hi @prabhathAmila i cannot provide support to custom application.
If you have a problem or a question you have to reproduce it in a simple fiddle.

**Comment by prabhathAmila** [comment]
Hi Asturur,
I create a [fiddle sample](https://jsfiddle.net/prabhath/1oahrtd5/45/)
I want to add images, text, and colors to an umbrella top view separately. also, all part of this umbrella will be masked. please help
