### ISSUE TITLE
Lock object can move Error

### ISSUE THREAD

**Issue by prabhathAmila** [fabricjs/fabric.js#5940]
Hi
I create fiddle [for this](https://jsfiddle.net/prabhath/1oahrtd5/59/)

I load ungrouped svg and it is selectable but not drag or drop, scale ect

but I select all, It can drag or scale. 
I want it to create select all but can not drag or scale
please help

**Comment by durga598** [comment]
It works for v1.7.6, [fiddle](http://jsfiddle.net/mfL3z8yj/), but after v2.0.0 dosen't [fiddle](http://jsfiddle.net/q8hu67st/1/). May be cause of ActiveSelection.

**Comment by asturur** [comment]
you have an event called `selection:created`
On that event you get the activeSelection passed as an argument, you can lock movement of it during the event.
