### ISSUE TITLE
Fabric JS Arrow Line width/ Stroke Width Issue on resize

### ISSUE THREAD

**Issue by kamleshpra995** [fabricjs/fabric.js#5941]
We draw an arrow with a stroke width of 5. When we are resizing the arrow it's increasing the stroke width of the arrow. See attached Screenshot both arrow are created with a stroke width of 5 but when I increased the size of the second arrow it's with is increased.

In the object stroke width still shows 5.

I am using fabric 2.4.1.

It's happening in the latest version also. JS Fiddle - https://jsfiddle.net/6e17oxc3/

I want to keep my stroke width unchanged.

Please suggest a way how can I do this?

**Comment by awehring** [comment]
When you change the size of a fabric object with the mouse, its `scaleX` and `scaleY` properties are changed. You must recalculate your points in an `object:scaling` eventhandler.

**Comment by asturur** [comment]
Please also try to use the `strokeUniform` property.
If not available in 2.4.1 updates to the higher you need. There are no big changes from 2.4.1 to 3.4.0

http://fabricjs.com/docs/fabric.Object.html#strokeUniform
