### ISSUE TITLE
canvas.setDimensions messes up path._render

### ISSUE THREAD

**Issue by SebastienEske** [fabricjs/fabric.js#5943]
## Version
3.4.0

## Test Case
http://jsfiddle.net/gjn9yx13/13/

## Information about environment
Nodejs or browser? both
Which browsers? at least firefox

## Steps to reproduce
In the fiddle, try to draw a line, it should be erased automatically
But if you uncomment one of the two mentioned lines (9 and/or 10) the latest path is not rendered properly.

## Expected Behavior
All paths are hidden

## Actual Behavior
The latest path is not hidden

**Comment by asturur** [comment]
@SebastienEske  can you try with 3.5.0 version?
for some reason is not available anymore on cloudflare but is out and it was fixing some weird effect with pencil brush

**Comment by SebastienEske** [comment]
@asturur It works! Thanks a ton for that!
