### ISSUE TITLE
Locked elements can move after select all

### ISSUE THREAD

**Issue by prabhathAmila** [fabricjs/fabric.js#5944]
Hi
I upload SVG to the canvas without grouping.
And locked mouseMove, Scaling, rotation. and only can select objects.
But if I select all, it can move, scale and rotate. 
how can I stop that?
[jsfiddle source here](https://jsfiddle.net/prabhath/1oahrtd5/68/)
Thank you

**Comment by durga598** [comment]
Duplicate of https://github.com/fabricjs/fabric.js/issues/5940
