### ISSUE TITLE
this.clipPath becomes string and crashes application

### ISSUE THREAD

**Issue by lancelab** [fabricjs/fabric.js#5945]
Dear community.

This apparently is a bug. The value becomes a string "none" which is not what expected. Can you please look at it? Thank you.

apparently in version:
var fabric = fabric || { version: '3.4.0' };

on line 13908
drawClipPath: function(ctx) {
      var path = this.clipPath;
      ....
![apparent-bug-in-fabric](https://user-images.githubusercontent.com/368709/68077358-5aae4880-fd90-11e9-8cea-b1e77cb2a715.png)
![bug-on-string-value-none](https://user-images.githubusercontent.com/368709/68077359-5eda6600-fd90-11e9-9327-a38e7e532570.png)
![fabric-version](https://user-images.githubusercontent.com/368709/68077360-613cc000-fd90-11e9-8a1f-ad06618294be.png)

http://landkey.net/z/bs/3r-party-bugs/fabric-bugs/

**Comment by asturur** [comment]
Hi, can you reproduce the bug in a fiddle?

**Comment by lancelab** [comment]
Andrea, thank you very much for reply.

I don't have time resources to strip all the plugins and recode the app. 
for fiddle. The easiest way to me is reverse engineer and recode an 
original fabricjs app, but this is doing things in blind way.

**Comment by asturur** [comment]
I have no idea how you end up with `none` there.
clipPath has to be an object or a falsy value.
If is `none` fabricJS is going to error and that is fine, we should not have code to protect ourself from that.

**Comment by asturur** [comment]
Are you importing some SVGs? what the app is doing? are you setting/removing the clipPath with some button/ui code?

**Comment by lancelab** [comment]
Dear Andrea.

Thank you for your care. Sorry for my delay in response.
Yes, I port data from SVG. Without details, the code is exactly this:

     //===============================================
     // //\\ inserts canvases into prebuilt containers
     //===============================================
     function insertCanvas( svg, wRack )
     {
         var chartOptions    = wRack.cconf.cdataOptions;
         var canvasRoot      = wRack.canroot;
         var fabric          = window.fabric;
         var canvasDom       = document.createElement( 'canvas' );
         canvasRoot.innerHTML= "";
         canvasRoot.appendChild( canvasDom );

         var fabCanvas = new fabric.Canvas( canvasDom );
         wRack.fabCanvas = fabCanvas;

         fabric.loadSVGFromString(
             svg,
             function( objects, options ) {
                 objects.forEach( ob => fabCanvas.add( ob ) );
                 //if( wRack.cardId === 0 )
                 //    ccc( //'fabCanvas=', fabCanvas,
                 var width = chartOptions.chart.width || 400; //todo
                 var height = chartOptions.chart.height || 300;
                 fabCanvas
                     .setDimensions({
                         width: width,
                         height: height,
                     })
                     .renderAll()
                     ;
         });
     }
     //===============================================
     // \\// inserts canvases into prebuilt containers
     //===============================================

The module is this:

/var/www/html/bwork/fabricjs/prj/version/src/vendor/macrogrid/plugin-components/load-charts-for-canvas-editor.js

//*******************************************************************
//          Lite-weight PDF creator wrapper based on pdfmake.
//          Part of b$l = Beaver $cript Library.
//          Copyright (c) 2018 - 2019 Konstantin Kirillov.
//          Licenses: MIT, GPL, GPL2.
//*******************************************************************

import Highcharts from 'highcharts'


( function() {
     var ns          = window.b$l        = window.b$l        || {};
     var $$          = ns.$$;
     var methods     = ns.methods        = ns.methods        || {};
     var fmeth       = ns.fmeth;
     var ccc         = console.log; ccc && ( ccc = console.log );
     methods.options_2_SVGChart_2_canvasEditor = 
options_2_SVGChart_2_canvasEditor;
     return;








     function options_2_SVGChart_2_canvasEditor( wRack )
     {
         var chartOptions = wRack.cconf.cdataOptions;
         var { width, height } = fmeth.getCardContentSize( wRack );
         if( width ) {
             chartOptions.chart.width = width;
             chartOptions.chart.height = height;
             //c cc( 'loading ... id=' + wRack.cardId + ' width='+width + 
' height=' + height );
         }
         //-----------------------------------------------
         // //\\ finalizes configuration
         //-----------------------------------------------
         var inProgress = false;
         chartOptions.chart.events =
         {
             ///todo ... perhaps render is the better event to catch the 
chart ...
             load: function( event ) {
                     //ccc( Date.now() + ' chart loaded: event=', event, 
' this=', this );
                     if( inProgress ) {
                         inProgress = false;
                         return;
                     }
                     inProgress = true;
                     var svg = this.getSVG();
                     insertCanvas( svg, wRack );
                     hiddenAuxiliaryChartContainer.remove();
             }
         };
         //-----------------------------------------------
         // \\// finalizes configuration
         //-----------------------------------------------


         //-----------------------------------------------
         // //\\ calls Highcharts and catches error if any
         //-----------------------------------------------
         var hiddenAuxiliaryChartContainer = $$.div().to(document.body)
             .css('position', 'absolute' )
             .css('left', '-10000px' )
             ();
         try{
             Highcharts.chart( hiddenAuxiliaryChartContainer, 
chartOptions );

         } catch (chartErr ) {
             ccc( chartErr );
             ////emulates normal program flow, but outputs error warnings
             //.instead of outputting chart to pdf, does output error 
image
             insertCanvas(
                 "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA" +
                 
"AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO" +
                 "9TXL0Y4OHwAAAABJRU5ErkJggg==",
                 wRack
             );
         }
         //-----------------------------------------------
         // \\// calls Highcharts and catches error if any
         //-----------------------------------------------
     }





     //===============================================
     // //\\ inserts canvases into prebuilt containers
     //===============================================
     function insertCanvas( svg, wRack )
     {
         var chartOptions    = wRack.cconf.cdataOptions;
         var canvasRoot      = wRack.canroot;
         var fabric          = window.fabric;
         var canvasDom       = document.createElement( 'canvas' );
         canvasRoot.innerHTML= "";
         canvasRoot.appendChild( canvasDom );

         var fabCanvas = new fabric.Canvas( canvasDom );
         wRack.fabCanvas = fabCanvas;

         fabric.loadSVGFromString(
             svg,
             function( objects, options ) {
                 objects.forEach( ob => fabCanvas.add( ob ) );
                 //if( wRack.cardId === 0 )
                 //    ccc( //'fabCanvas=', fabCanvas,
                 var width = chartOptions.chart.width || 400; //todo
                 var height = chartOptions.chart.height || 300;
                 fabCanvas
                     .setDimensions({
                         width: width,
                         height: height,
                     })
                     .renderAll()
                     ;
         });
     }
     //===============================================
     // \\// inserts canvases into prebuilt containers
     //===============================================

}) ();


On 2019-11-05 05:00, Andrea Bogazzi wrote:
> Are you importing some SVGs? what the app is doing? are you
> setting/removing the clipPath with some button/ui code?

//*******************************************************************
//          Lite-weight PDF creator wrapper based on pdfmake.
//          Part of b$l = Beaver $cript Library.
//          Copyright (c) 2018 - 2019 Konstantin Kirillov.
//          Licenses: MIT, GPL, GPL2.
//*******************************************************************

import Highcharts from 'highcharts'


( function() {
    var ns          = window.b$l        = window.b$l        || {};
    var $$          = ns.$$;
    var methods     = ns.methods        = ns.methods        || {};
    var fmeth       = ns.fmeth;
    var ccc         = console.log; ccc && ( ccc = console.log );
    methods.options_2_SVGChart_2_canvasEditor = options_2_SVGChart_2_canvasEditor;
    return;








    function options_2_SVGChart_2_canvasEditor( wRack )
    {
        var chartOptions = wRack.cconf.cdataOptions;
        var { width, height } = fmeth.getCardContentSize( wRack );
        if( width ) {
            chartOptions.chart.width = width;
            chartOptions.chart.height = height;
            //c cc( 'loading ... id=' + wRack.cardId + ' width='+width + ' height=' + height );
        }
        //-----------------------------------------------
        // //\\ finalizes configuration
        //-----------------------------------------------
        var inProgress = false;
        chartOptions.chart.events =
        {
            ///todo ... perhaps render is the better event to catch the chart ...
            load: function( event ) {
                    //ccc( Date.now() + ' chart loaded: event=', event, ' this=', this );
                    if( inProgress ) {
                        inProgress = false;
                        return;
                    }
                    inProgress = true;
                    var svg = this.getSVG();
                    insertCanvas( svg, wRack );
                    hiddenAuxiliaryChartContainer.remove();
            }
        };
        //-----------------------------------------------
        // \\// finalizes configuration
        //-----------------------------------------------


        //-----------------------------------------------
        // //\\ calls Highcharts and catches error if any
        //-----------------------------------------------
        var hiddenAuxiliaryChartContainer = $$.div().to(document.body)
            .css('position', 'absolute' )
            .css('left', '-10000px' )
            ();
        try{
            Highcharts.chart( hiddenAuxiliaryChartContainer, chartOptions );

        } catch (chartErr ) {
            ccc( chartErr );
            ////emulates normal program flow, but outputs error warnings
            //.instead of outputting chart to pdf, does output error image
            insertCanvas(
                "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA" +
                "AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO" +
                "9TXL0Y4OHwAAAABJRU5ErkJggg==",
                wRack
            );
        }
        //-----------------------------------------------
        // \\// calls Highcharts and catches error if any
        //-----------------------------------------------
    }





    //===============================================
    // //\\ inserts canvases into prebuilt containers
    //===============================================
    function insertCanvas( svg, wRack )
    {
        var chartOptions    = wRack.cconf.cdataOptions;
        var canvasRoot      = wRack.canroot;
        var fabric          = window.fabric;
        var canvasDom       = document.createElement( 'canvas' );
        canvasRoot.innerHTML= "";
        canvasRoot.appendChild( canvasDom );

        var fabCanvas = new fabric.Canvas( canvasDom );
        wRack.fabCanvas = fabCanvas;

        fabric.loadSVGFromString(
            svg, 
            function( objects, options ) {
                objects.forEach( ob => fabCanvas.add( ob ) );
                //if( wRack.cardId === 0 )
                //    ccc( //'fabCanvas=', fabCanvas, 
                var width = chartOptions.chart.width || 400; //todo
                var height = chartOptions.chart.height || 300;
                fabCanvas
                    .setDimensions({
                        width: width,
                        height: height,
                    })
                    .renderAll()
                    ;
        });
    }
    //===============================================
    // \\// inserts canvases into prebuilt containers
    //===============================================

}) ();

**Comment by asturur** [comment]
i think this could be fixed with upcoming 3.5 release.
