### ISSUE TITLE
SVG difference between old 1.6.0 and 3.2.0

### ISSUE THREAD

**Issue by c-gross** [fabricjs/fabric.js#5948]
Hi,

as I mentioned already last year, Amazon is using Fabric.js for personalized photo products. I wrote a fully automated import and PDF generator for the warehouse. The Amazon SVG is alot bigger than the content area and has alot of whitespace and does not cut content outside of the viewport. Without some modifications it can't be used. Thats why a automated modification is important.

Last week we had a few PDFs that were not generated and I found out, that Amazon is starting to release a new Fabric.js version which comes with a different result SVG file.

Here an old Amazon SVG via API:
```
<?xml version='1.0' encoding='UTF-8' standalone='no'?><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="3200" height="3200" viewBox="0 0 3200 3200" xml:space="preserve">
<desc>Created with Fabric.js 1.6.0-rc.1</desc>
<defs></defs>
<g transform="translate(1558.5 1715.27) scale(9.22 9.22)">
<image xlink:href="random_hash.jpeg" x="-37.27272727272727" y="-37.27272727272727" style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" width="74.54545454545455" height="74.54545454545455" preserveAspectRatio="none"></image>
</g>
</svg>
```

Here my proccessed SVG:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="1208" height="712" viewBox="960 1344 1208 712" xml:space="preserve">
<desc>Created with Fabric.js 1.6.0-rc.1</desc>
<defs/>
<g transform="translate(1558.5 1715.27) scale(9.22 9.22)">
<image xlink:href="data:image/jpg;base64...." x="-37.27272727272727" y="-37.27272727272727" style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" width="74.54545454545455" height="74.54545454545455" preserveAspectRatio="none"/>
</g>
</svg>
```
I base64 encode the embedded image and replace the image link with the base64 code.
And I caclulate the correct viewBox and image width and height based on the real viewport and the design configuration for the PDF. 

Now they start switching to Fabric.js 3.2.0 and the SVG for the same product is completely different.
```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="3200" height="3200" viewBox="0 0 400 400" xml:space="preserve">
<desc>Created with Fabric.js 3.2.0</desc>
<defs>
</defs>
<g clip-path="url(#CLIPPATH_10)"  >
<g transform="matrix(0.07 0 0 0.07 193.56 224.44)"  >
<clipPath id="CLIPPATH_10" >
	<rect transform="matrix(1 0 0 1 196 213)" x="-75.5" y="-44.5" rx="0" ry="0" width="151" height="89" />
</clipPath>
	<image style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;"  xlink:href="random_hash.jpg" x="-402" y="-800" width="804" height="1600"></image>
</g>
</g>
</svg>
```
The viewBox has now a different size for some reason it's not the full size anymore. I started today with this issues and so far I was not able to find a way to cacluated working viewBox values. Looks like the matrix and/or clippath and/or new image position (x/y) has some kind of effect to it too. But it's complicated to test in which way I have to change the values.

Can you give me an hint which values I have to take care about to get similar results as with the old version?

Other minor issue is, that the clippath is not defined inside defs. TCPDF is not able to render these SVGs because it can't find the clippath definition. I can move it to the correct XML node and it's fine but maybe this should be fixed in new versions.

**Comment by asturur** [comment]
hi @c-gross 
The clippath can be outside the defs, it has the added benefits of getting the parent transformation out of the box, and that is very helpful. Maybe it can be swapped with some `<use>` tag, but i m not 100% sure.

If you move the clipPath in another node, away from where is now, the output will change.

Can you make a visual example with a non super simple SVG and try to identify which part of the output you want to wrap with the viewbox? Also please attach a virual image output of what you are looking for.

**Comment by c-gross** [comment]
The clippath should be still the smallest issue. I could also delete it. There is no fancy clipping mask on Amazon or we don't use them if they are about to add them now. It's a simple rect I hope.

When I change the SVG, like I did before, to set the viewBox to the visible part (the area which the user were able to change -> thats what we want to print), I might be able to ignore the clippath anyway. But changing the viewBox has not even close the same result as with the old version. Even when I delete the <clippath> and <g clip-path> I don't find a way to zoom to the content which was not a problem with the old SVGs.

I don't think that I'll be able to get a test picture. When I visit one of our products on Amazon and check the fabric version in the dev console, it's always 1.6.0.

Like here on the screenshot.
![amazon_fabric](https://user-images.githubusercontent.com/10271639/68191784-91fb4000-ffb0-11e9-8184-561a20d581b1.png)

The canvas is way bigger then the real user content area. In the old version, it was easy to modify the viewBox and set the correct image size.

**Comment by c-gross** [comment]
I'm "playing" around with the SVG right now.

Changing the svg width and height is ok. Changing the viewBox has very strange results. 
But if I change the matrix from
`<g transform="matrix(0.16 0 0 0.16 201.97 211.62)"  >`
to
`<g transform="matrix(0.69 0 0 0.69 201.97 211.62)"  >`
I'm getting close to the result I want. So the matrix is blocking the viewBox to scale and looks like I have to do it via the matrix transformation. But it's still not the 100% correct viewport as it should be.

I was not using any calculations, just using texteditor on the SVG and playing with the numbers... At the end I have to find the formulars to calculate it when I know what has to be changed in which way.

**Comment by asturur** [comment]
fabric has internal svg viewbox handling. I do not think you have to change it manually.

Unless it is broken and so then need a bugfix, i think you should do:

```
     * var svg = canvas.toSVG({
     *   viewBox: {
     *     x: posX,
     *     y: posY,
     *     width: width,
     *     height: height
     *   }
     * });
```

**Comment by c-gross** [comment]
I do not open the SVG with fabric since there was not much to do to get it working for the PDF until now. I just open the SVG with PHP by loading it as XML document, modify the nodes and save it.

If I don't find a good way to keep it like this it's maybe a good idea to use node.js with fabric if I can get the correct result. I already have a node.js fabric service for the amazon order import running to render product images with a personalized text for a specific design. Maybe I could extend that node app.

**Comment by asturur** [comment]
i'm not sure what you mean by opening  the SVG with fabric.
I'm saying that fabric can generate the correct SVG for you, without you need to modify the viewbox.

**Comment by c-gross** [comment]
Amazon is creating the SVG. I can't change what Amazon is sending me. They are sending me right now a mix of fabric 1.6.0 and fabric 3.2.0 SVGs and I have to handle them somehow.

**Comment by asturur** [comment]
Well i can help with fabricJS not with your specific app/work/partner setup.

You are modify by hand what fabricJS is doing probably with an option.
I would test if the viewbox option can solve your problem and then in case find the way to update it to the amazon side.


All the app setup and data flow are black box for me.

**Comment by c-gross** [comment]
Yes ofc you can't know the flow. Thats why I was first asking about the differences in the SVG and the matrix + viewBox to modify the SVG in the correct way. I don't think that Amazon will care if we want them to save the SVG in a different way. We are not that big ;)

As I said, in the old version I was able to zoom to the user content by just changing the viewBox. Since there is the translate matrix the viewBox is not able to zoom in anymore. Any change in the viewBox values will only move the image around. Thats why I try to get the same result by changing the matrix but that does not fit 100% so far. Still searching how to adjust the position since it's a couple pixels off. 

But I guess you can't help here. It's even for me very difficult to get SVGs since every shipped order will delete the SVG (zip) on Amazon and I always have to start with a new order.

**Comment by asturur** [comment]
You can reverse engineer the problem somehow.
Do you understand 100% how the viewbox works?

I would rather reparse the SVG with fabric, get the objects, check how big the object is and calculate the vieport from that.

Do you have at least a problematic SVG to share?

**Comment by c-gross** [comment]
The viewbox should be: posX posY width height
As far as I used it until now.

Yes I'll try to open it with fabric in my node.js app. Maybe I can open it, get the viewport inside the clippath and save just this area as jpg or whatever.

I have a amazon download like I get it from the Amazon API.
I removed all customer related data and modified the images.
[amazon_dl.zip](https://github.com/fabricjs/fabric.js/files/3810239/amazon_dl.zip)

There are basic infos in the Json about the dimension and position I was using in the old version SVG. This example should have in the result image abit whitespace left and right but none top or and bottom.

**Comment by c-gross** [comment]
Open the SVG in fabric might work. I did a quick dummy test and it's not 100% perfect I think but I need more orders to validate. 

Tested with hardcoded values:
```
var dataURL = canvas.toDataURL({
        format: 'jpg',
        multiplier: 1,
        width: 2328,
        height: 2320,
        top: 416,
        left: 488,
    });
```

But I think I can't use `toDataURL` in node. My existing renderer service in node is using `createJPEGStream`. But it doesn't look like that I can save a viewport with this method. Do you know the best way to save just a specific viewport of an canvas in node?

**Comment by c-gross** [comment]
I deployed last friday a solution to send the SVG to my node.js app with fabric. Loading the SVG and render the correct viewport as JPG. It shoudl work but for some reason there are no new orders on Amazon with the new fabric version. So I can't 100% confirm but I expect that it works. Tested with the old fabric SVGs and that works fine.

Too bad that amazon does not allow merchants to test when they release a change for a part of the customers. also the amazon support was horrible. They explained me how to download the SVG via the amazon backend while I download via API already...

**Comment by asturur** [comment]
i m sorry i wasn't able to help, glad you found your way out somehow.

**Comment by c-gross** [comment]
Funny that you write that this week. Amazon stopped the Fabric.js update before ymas and I was never able to fully test my solution.

This week Amazon started again to switch to Fabric.js 3.2.0
Some SVGs are working and some don't work with my soluation.

We have at least 1 product/design so far that does not work. The funny thing, there is some magic crop size, if I go below that size the final image is always white. Amazon SVGs are always 3200x3200. I calculate the correct X and Y position and size of the image. 

Means the size of the canvas is the final image size I want like 1200x800. And then I mode the content of the SVG with set('left', value) and set('right', value) that it fits in the canvas viewport.

In this example the magic number of the canvas viewport is around 1400x1400. The content is in the upper left corner with alot of white space bottom and right. If I set 1300x1300 everything is white.

Not sure that g transform or clippath are the reason for that.

`<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="3200" height="3200" viewBox="0 0 400 400" xml:space="preserve">
<desc>Created with Fabric.js 3.2.0</desc>
<defs>
</defs>
<g clip-path="url(#CLIPPATH_5)"  >
<g transform="matrix(0.06 0 0 0.06 194.32 214.64)"  >
<clipPath id="CLIPPATH_5" >
	<rect transform="matrix(1 0 0 1 196 213)" x="-75.5" y="-44.5" rx="0" ry="0" width="151" height="89" />
</clipPath>
	<image style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;"  xlink:href="4008bdb2-250a-4dd2-a85e-41c0a5360df8.jpg" x="-600" y="-800" width="1200" height="1600"></image>
</g>
</g>
</svg>`

**Comment by asturur** [comment]
but can t you use puppeteer to render the svg and get the image bounding box? Did i ask that already? sure is not fast...

**Comment by c-gross** [comment]
Just googled puppeteer, wow 280MB sounds abit overkill to just render a part of an SVG as JPG. The bounding box of the image inside the SVG might not be the viewport I need. I'll read abit about puppeteer if it could be an ugly fallback solution.

Maybe the SVG get white rendered when the content (the image inside) is outside of the canvas viewport? Since the SVG is much bigger than the image inside. Is this maybe some optimization feature that can be disabled?

I tried to use renderOnAddRemove false, set the position of the SVG to make sure the content is inside the canvas viewport and then render but doesn't change anything.

Is there a way to set a viewport when using createJPEGStream?

**Comment by c-gross** [comment]
I haven't found any way with fabric.js.

I tested now svg-to-img, which is also using puppeteer as dependency. It's working. Don't really like to have such a heavy lib, even with vulnerability warnings but it's a solution for now and my node app is not public accessible.

**Comment by asturur** [comment]
i stil did not see one of those svgs 😂

**Comment by c-gross** [comment]
I attacked an SVG 3 messages ago. Or is that not enough?

Anyway puppeteer doesnt work on live server. Not sure if I can get the hosting service to install the huge list of dependencies.

**Comment by asturur** [comment]
oh i did not see that, i expected it in the markup. now i see it.

**Comment by c-gross** [comment]
Btw, I'm running fabric 2.3.4
```
{
  "dependencies": {
    "body-parser": "^1.19.0",
    "canvas": "^1.6.13",
    "express": "^4.16.3",
    "fabric": "^2.3.4",
    "google-font-installer": "^1.1.0",
  }
}
```

But I also tested new fabric version like 2.7.0 and 3.6.0 and new canvas 2.6.1.
```
{
  "dependencies": {
    "body-parser": "^1.19.0",
    "canvas": "2.6.1",
    "express": "^4.16.3",
    "fabric": "3.6.0",
    "google-font-installer": "^1.1.0"
  }
}
```

But it's always the same result. If the canvas is too small, it's always white.

Attached is a zip with all relevant files from Amazon, just all personal data got removed. I base64 encode the linked JPG and put it inside the SVG. I also added an extra saved version of the SVG with the base64 encoded JPG in the zip which is send to the node.js app.

The correct settings for this would be:
Canvas width: 1208
Canvas height: 712
SVG offset x: 960
SVG offset y: 1344

```
module.exports = class SvgConverter {

    /**
     * Constructor
     *
     * @param config
     */
    constructor(config) {
        this.canvas;
        this.config = config;
    };


    /**
     * Convert and Save SVG to JPG
     *
     * @returns {Promise<void>}
     */
    async convertAndSave() {
        await this.initCanvas();
        await this.renderSvg();
        await this.adjustContent();
        await this.saveImage();

        return;
    };


    /**
     * Init canvas
     *
     * @returns {Promise<void>}
     */
    async initCanvas() {
        this.canvas = new fabric.StaticCanvas(null, {
            width: this.config.viewBox.width,
            height: this.config.viewBox.height,
            objectCaching: false,
            backgroundColor: '#FFFFFF'
        });
        console.log(fabric.version);
    };


    /**
     * Render SVG on canvas
     *
     * @returns {Promise<unknown>}
     */
    renderSvg() {
        return new Promise((resolve, reject) => {
            var that = this;

            try {
                fabric.loadSVGFromString(this.config.svg.body,function(objects, options) {
                    let group = fabric.util.groupSVGElements(objects, options);
                    that.canvas.add(group);

                    resolve(true);
                });
            } catch(e) {
                console.log('[ERROR] Not able to render SVG.');
                console.log(e);
                reject(false);
            }
        });
    }


    /**
     * Adjust content position
     *
     * @returns {Promise<unknown>}
     */
    adjustContent() {
        return new Promise((resolve, reject) => {
            let objects = this.canvas.getObjects();

            for(let i = 0; i < objects.length; i++) {
                objects[i].set('left', objects[i].get('left') - this.config.viewBox.x);
                objects[i].set('top', objects[i].get('top') - this.config.viewBox.y);
            }
            this.canvas.renderAll();

            resolve(true);
        });
    };


    /**
     * Save image
     *
     * @returns {Promise<any>}
     */
    async saveImage() {
        let filePath = this.config.basepath + this.config.filename;

        // Create output stream
        let out = fs.createWriteStream(filePath);

        // Create image stream
        let stream = this.canvas.createJPEGStream({
            quality: config.JPEG_QUALITY,
            chromaSubsampling: config.CHROMA_SUBSAMPLING
        });

        // Save Image
        stream.pipe(out);
        return await this.streamWritePromise(out, filePath);
    }


    /**
     * Write image stream
     *
     * @param stream
     * @param imagePath
     * @returns {Promise<any>}
     */
    streamWritePromise(stream, imagePath) {
        return new Promise((resolve, reject) => {
            stream.on('finish', () => {
                console.log(`[INFO] Converted SVG image saved (${imagePath})`);
                resolve(true);
            });
            stream.on('error', (error) => {
                console.log(`[ERROR] Unable to save converted SVG image (${imagePath})`);
                stream.end();
                reject(false);
            });
        });
    }
};
```
[mws_import_modded.zip](https://github.com/fabricjs/fabric.js/files/4076961/mws_import_modded.zip)
