### ISSUE TITLE
loadFromJSON not returning any objects.

### ISSUE THREAD

**Issue by rbulph** [fabricjs/fabric.js#5949]
I've started having problems with fabricjs.loadFromJSON..serialized.objects contains the objects I'm expecting it to. But after _enlivenObjects has been run, "this" doesn't contain any objects. So loadFromJSON doesn't get me my objects back. This used to work OK, but has suddenly stopped and I can't figure out why. Can anyone help?

Thanks

Here's the code:

"loadFromJSON: function (json, callback, reviver) {
    if (!json) {
      return;
    }

    // serialize if it wasn't already
    var serialized = (typeof json === 'string')
      ? JSON.parse(json)
      : fabric.util.object.clone(json);

    this.clear();

    var _this = this;
    this._enlivenObjects(serialized.objects, function () {
      _this._setBgOverlay(serialized, function () {
        // remove parts i cannot set as options
        delete serialized.objects;
        delete serialized.backgroundImage;
        delete serialized.overlayImage;
        delete serialized.background;
        delete serialized.overlay;
        // this._initOptions does too many things to just
        // call it. Normally loading an Object from JSON
        // create the Object instance. Here the Canvas is
        // already an instance and we are just loading things over it
        _this._setOptions(serialized);
        callback && callback();
      });
    }, reviver);
    return this;
  },
"

**Comment by asturur** [comment]
Hi @rbulph is unclear to me if you are using the official LoadFromJson from fabric.
You need to post your JSON object and the version of fabric you are using.

**Comment by rbulph** [comment]
OK, I'm using var fabric = fabric || { version: '2.0.0-beta1' };. I'm self-hosting it because I had some problems after a new version was released once. My objects are:

{
    "objects": [
        {
            "type": "Arrow",
            "originX": "left",
            "originY": "top",
            "left": 196.5,
            "top": 138.5,
            "width": 160,
            "height": 215,
            "fill": "#444",
            "stroke": "#444",
            "strokeWidth": 1,
            "strokeDashArray": [
                10,
                5
            ],
            "strokeLineCap": "butt",
            "strokeLineJoin": "miter",
            "strokeMiterLimit": 10,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "clipTo": null,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "globalCompositeOperation": "source-over",
            "transformMatrix": null,
            "skewX": 0,
            "skewY": 0,
            "x1": 80,
            "x2": -80,
            "y1": 107.5,
            "y2": -107.5,
            "lockMovementX": true,
            "lockMovementY": true,
            "lockScalingX": true,
            "lockScalingY": true,
            "lockRotation": true,
            "hasControls": true,
            "hasBorders": false,
            "id": "Arrow2",
            "offset": 0,
            "cornerColor": "rgba(255,0,0,1)",
            "sourceid": "Entity 2",
            "targetid": "Entity 1"
        },
        {
            "type": "group",
            "originX": "left",
            "originY": "top",
            "left": 40,
            "top": 100,
            "width": 157,
            "height": 77,
            "fill": "rgb(0,0,0)",
            "stroke": null,
            "strokeWidth": 0,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeLineJoin": "miter",
            "strokeMiterLimit": 10,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "clipTo": null,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "globalCompositeOperation": "source-over",
            "transformMatrix": null,
            "skewX": 0,
            "skewY": 0,
            "centeredRotation": false,
            "hasControls": false,
            "id": "Entity 1",
            "hasRotatingPoint": false,
            "objects": [
                {
                    "type": "rect",
                    "originX": "center",
                    "originY": "center",
                    "left": 0,
                    "top": 0,
                    "width": 156,
                    "height": 76,
                    "fill": "#fbfbfb",
                    "stroke": "#444444",
                    "strokeWidth": 1,
                    "strokeDashArray": null,
                    "strokeLineCap": "butt",
                    "strokeLineJoin": "miter",
                    "strokeMiterLimit": 10,
                    "scaleX": 1,
                    "scaleY": 1,
                    "angle": 0,
                    "flipX": false,
                    "flipY": false,
                    "opacity": 1,
                    "shadow": null,
                    "visible": true,
                    "clipTo": null,
                    "backgroundColor": "",
                    "fillRule": "nonzero",
                    "globalCompositeOperation": "source-over",
                    "transformMatrix": null,
                    "skewX": 0,
                    "skewY": 0,
                    "rx": 0,
                    "ry": 0,
                    "centeredRotation": false,
                    "hasControls": false,
                    "hasRotatingPoint": false
                },
                {
                    "type": "text",
                    "originX": "center",
                    "originY": "center",
                    "left": 0,
                    "top": -10,
                    "width": 69.85,
                    "height": 22.6,
                    "fill": "#444444",
                    "stroke": null,
                    "strokeWidth": 1,
                    "strokeDashArray": null,
                    "strokeLineCap": "butt",
                    "strokeLineJoin": "miter",
                    "strokeMiterLimit": 10,
                    "scaleX": 1,
                    "scaleY": 1,
                    "angle": 0,
                    "flipX": false,
                    "flipY": false,
                    "opacity": 1,
                    "shadow": null,
                    "visible": true,
                    "clipTo": null,
                    "backgroundColor": "",
                    "fillRule": "nonzero",
                    "globalCompositeOperation": "source-over",
                    "transformMatrix": null,
                    "skewX": 0,
                    "skewY": 0,
                    "text": "Entity 1",
                    "fontSize": 20,
                    "fontWeight": "700",
                    "fontFamily": "Lato",
                    "fontStyle": "normal",
                    "lineHeight": 1.16,
                    "underline": false,
                    "overline": false,
                    "linethrough": false,
                    "textAlign": "left",
                    "textBackgroundColor": "",
                    "charSpacing": 0,
                    "centeredRotation": false,
                    "hasControls": false,
                    "hasRotatingPoint": false,
                    "styles": null
                },
                {
                    "type": "text",
                    "originX": "center",
                    "originY": "center",
                    "left": 0,
                    "top": 12,
                    "width": 131.9,
                    "height": 22.6,
                    "fill": "#444444",
                    "stroke": null,
                    "strokeWidth": 1,
                    "strokeDashArray": null,
                    "strokeLineCap": "butt",
                    "strokeLineJoin": "miter",
                    "strokeMiterLimit": 10,
                    "scaleX": 1,
                    "scaleY": 1,
                    "angle": 0,
                    "flipX": false,
                    "flipY": false,
                    "opacity": 1,
                    "shadow": null,
                    "visible": true,
                    "clipTo": null,
                    "backgroundColor": "",
                    "fillRule": "nonzero",
                    "globalCompositeOperation": "source-over",
                    "transformMatrix": null,
                    "skewX": 0,
                    "skewY": 0,
                    "text": "England/Wales",
                    "fontSize": 20,
                    "fontWeight": "normal",
                    "fontFamily": "Lato",
                    "fontStyle": "normal",
                    "lineHeight": 1.16,
                    "underline": false,
                    "overline": false,
                    "linethrough": false,
                    "textAlign": "left",
                    "textBackgroundColor": "",
                    "charSpacing": 0,
                    "centeredRotation": false,
                    "hasControls": false,
                    "hasRotatingPoint": false,
                    "styles": null
                }
            ]
        },
        {
            "type": "group",
            "originX": "left",
            "originY": "top",
            "left": 356,
            "top": 315,
            "width": 157,
            "height": 77,
            "fill": "rgb(0,0,0)",
            "stroke": null,
            "strokeWidth": 0,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeLineJoin": "miter",
            "strokeMiterLimit": 10,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "clipTo": null,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "globalCompositeOperation": "source-over",
            "transformMatrix": null,
            "skewX": 0,
            "skewY": 0,
            "centeredRotation": false,
            "hasControls": false,
            "id": "Entity 2",
            "hasRotatingPoint": false,
            "objects": [
                {
                    "type": "rect",
                    "originX": "center",
                    "originY": "center",
                    "left": 0,
                    "top": 0,
                    "width": 156,
                    "height": 76,
                    "fill": "#fbfbfb",
                    "stroke": "#444444",
                    "strokeWidth": 1,
                    "strokeDashArray": null,
                    "strokeLineCap": "butt",
                    "strokeLineJoin": "miter",
                    "strokeMiterLimit": 10,
                    "scaleX": 1,
                    "scaleY": 1,
                    "angle": 0,
                    "flipX": false,
                    "flipY": false,
                    "opacity": 1,
                    "shadow": null,
                    "visible": true,
                    "clipTo": null,
                    "backgroundColor": "",
                    "fillRule": "nonzero",
                    "globalCompositeOperation": "source-over",
                    "transformMatrix": null,
                    "skewX": 0,
                    "skewY": 0,
                    "rx": 0,
                    "ry": 0,
                    "centeredRotation": false,
                    "hasControls": false,
                    "hasRotatingPoint": false
                },
                {
                    "type": "text",
                    "originX": "center",
                    "originY": "center",
                    "left": 0,
                    "top": -10,
                    "width": 66.92,
                    "height": 22.6,
                    "fill": "#444444",
                    "stroke": null,
                    "strokeWidth": 1,
                    "strokeDashArray": null,
                    "strokeLineCap": "butt",
                    "strokeLineJoin": "miter",
                    "strokeMiterLimit": 10,
                    "scaleX": 1,
                    "scaleY": 1,
                    "angle": 0,
                    "flipX": false,
                    "flipY": false,
                    "opacity": 1,
                    "shadow": null,
                    "visible": true,
                    "clipTo": null,
                    "backgroundColor": "",
                    "fillRule": "nonzero",
                    "globalCompositeOperation": "source-over",
                    "transformMatrix": null,
                    "skewX": 0,
                    "skewY": 0,
                    "text": "Entit45",
                    "fontSize": 20,
                    "fontWeight": "700",
                    "fontFamily": "Lato",
                    "fontStyle": "normal",
                    "lineHeight": 1.16,
                    "underline": false,
                    "overline": false,
                    "linethrough": false,
                    "textAlign": "left",
                    "textBackgroundColor": "",
                    "charSpacing": 0,
                    "centeredRotation": false,
                    "hasControls": false,
                    "hasRotatingPoint": false,
                    "styles": null
                },
                {
                    "type": "text",
                    "originX": "center",
                    "originY": "center",
                    "left": 0,
                    "top": 12,
                    "width": 80.34,
                    "height": 22.6,
                    "fill": "#444444",
                    "stroke": null,
                    "strokeWidth": 1,
                    "strokeDashArray": null,
                    "strokeLineCap": "butt",
                    "strokeLineJoin": "miter",
                    "strokeMiterLimit": 10,
                    "scaleX": 1,
                    "scaleY": 1,
                    "angle": 0,
                    "flipX": false,
                    "flipY": false,
                    "opacity": 1,
                    "shadow": null,
                    "visible": true,
                    "clipTo": null,
                    "backgroundColor": "",
                    "fillRule": "nonzero",
                    "globalCompositeOperation": "source-over",
                    "transformMatrix": null,
                    "skewX": 0,
                    "skewY": 0,
                    "text": "Bermuda",
                    "fontSize": 20,
                    "fontWeight": "normal",
                    "fontFamily": "Lato",
                    "fontStyle": "normal",
                    "lineHeight": 1.16,
                    "underline": false,
                    "overline": false,
                    "linethrough": false,
                    "textAlign": "left",
                    "textBackgroundColor": "",
                    "charSpacing": 0,
                    "centeredRotation": false,
                    "hasControls": false,
                    "hasRotatingPoint": false,
                    "styles": null
                }
            ]
        },
        {
            "type": "triangle",
            "originX": "left",
            "originY": "top",
            "left": 190.88,
            "top": 143.87,
            "width": 14,
            "height": 9,
            "fill": "#444",
            "stroke": "#444444",
            "strokeWidth": 1,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeLineJoin": "miter",
            "strokeMiterLimit": 10,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 323.34,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "clipTo": null,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "globalCompositeOperation": "source-over",
            "transformMatrix": null,
            "skewX": 0,
            "skewY": 0,
            "hasBorders": true,
            "id": "triangle2",
            "lockScalingX": true,
            "lockScalingY": true,
            "lockRotation": true,
            "hasControls": false
        },
        {
            "type": "text",
            "originX": "left",
            "originY": "top",
            "left": 279.37,
            "top": 212,
            "width": 51.12,
            "height": 22.6,
            "fill": "rgb(0,0,0)",
            "stroke": null,
            "strokeWidth": 1,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeLineJoin": "miter",
            "strokeMiterLimit": 10,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 413.34,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": true,
            "clipTo": null,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "globalCompositeOperation": "source-over",
            "transformMatrix": null,
            "skewX": 0,
            "skewY": 0,
            "text": "Bonds",
            "fontSize": 20,
            "fontWeight": "normal",
            "fontFamily": "Times New Roman",
            "fontStyle": "normal",
            "lineHeight": 1.16,
            "underline": false,
            "overline": false,
            "linethrough": false,
            "textAlign": "left",
            "textBackgroundColor": "",
            "charSpacing": 0,
            "centeredRotation": true,
            "hasControls": true,
            "id": "text2",
            "hasRotatingPoint": true,
            "styles": null
        }
    ],
    "centeredRotation": false,
    "counter": 3
}

**Comment by rbulph** [comment]
Could the problem be that reviver is not defined in the call to loadFromJSON? Here's the code I have in my project, although, as I say, it worked before:

  " canvas.loadFromJSON(contents, canvas.renderAll.bind(canvas));"

**Comment by rbulph** [comment]
OK I've added this function

"function fnreviver(o,obj,error){
	canvas.add(obj);
}" 

and passed it here

" canvas.loadFromJSON(contents, canvas.renderAll.bind(canvas), fnreviver);"

It does get called with each object, but still the objects don't show up.

**Comment by asturur** [comment]
I see there is an Arrow type in.
I'm not sure what may have happened, but you have definitely a custom code setup, you should try to make a fiddle with this code and a serialize button.
Just with the JSON string and no Arrow class is not debuggable.

Also you are on one of the first beta of fabric 2, there may have been bugs that have been fixed.
Any reason not to be at least on the latest of version 2 or on the latest?

**Comment by rbulph** [comment]
Thanks, I'll try to set up a fiddle.

I found that my code stopped working one day, a couple of years ago, when I was simply referencing the latest version of fabric.js. So I just started self-hosting the version that had worked for me.

**Comment by asturur** [comment]
If your project is in production and using fabricJS, the hassle of opening an issue and starting the discussion timely when something break is important for you and the project.
Since the 2.0 beta ( it was beta because 2.0 was the first version with intentional breaking changes and moving parts ) many improvement has been added, and not being able to migrate is a big loss.

**Comment by rbulph** [comment]
I did open a discussion actually, although we didn't take it very far. [here](https://groups.google.com/forum/#!searchin/fabricjs/robulph%7Csort:date/fabricjs/OBsodSMqUk4/n2MdYlO6AQAJ).

So, since hosting my own version has stopped working, perhaps I'd better go back to referring to the current version and try to get it to work. But I can't even figure out how to do that. The people who initially set up the website for me referred to the rawgit version, and Andrea Bogazzi says that that is very wrong. He says to refer to the link on the main page, but I can't see that. I could have a reference:

<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.7.17/fabric.min.js"></script>

But that refers to a particular version so I don't think that that is right either. 

What on earth am I supposed to do?

**Comment by rbulph** [comment]
OK, it's working with a link to a cdn version now. Except that my Arrow objects don't get deserialized. Nothing shows up. Below is the definition of the Arrow. It inherits from Fabric.Line and has an arrowhead and associated text. Any ideas what I have to do so that this works?

fabric.Arrow = fabric.util.createClass(fabric.Line, {
  type: 'Arrow',
  initialize: function(points, options) {
    options || (options = { });
    this.callSuper('initialize',points, options);
	this.strokeWidth=1;
	this.fill= '#444';
	this.stroke= '#444';
	this.id= 'Arrow' + canvas.linecounter;
	this.name= 'arrow';
	this.selectable= true;		//if turn this off hovercursor doesn't work. So arrow is selectable. But setting hasBorders to false stops blue rectangle appearing around it so there's no problem.
	this.lockMovementX= true;
	this.lockMovementY= true;
	this.lockScalingX= true;
	this.lockScalingY= true;
	this.lockRotation= true;
	this.hasControls= true;
	this.lockRotation= true;
	this.hasBorders= false;
	this.cornerColor= 'rgba(255,0,0,1)';
	this.cornerSize=9;
	var vx1,vy1,vx2,vy2;
	
	/** [Create triangle attached to the end of the line pointing to the target entity] */
	this.triangle = new fabric.Triangle({
		originX: 'left',
		originY: 'top',
		hasBorders: true,
		id: 'triangle' + canvas.linecounter,
		lockScalingX: true,
		lockScalingY: true,
		lockRotation: true,
		hasControls: false,
		pointType: 'arrow_start',
		fill:  '#444',
		stroke: "#444444",
		strokeWidth: 1,
		selectable: false,
	});
	
	this.text= new fabric.Text("", {
		id: 'text' + canvas.linecounter,
		fontSize:20,
		selectable: false,
	});
	
/* 	 this.Instrument= new {
			name: 'Instrument Name',
			issuedate: Date(),
			redemptiondate: Date(),
		}; */
	
  },
  toObject: function() {
    return fabric.util.object.extend(this.callSuper('toObject'), {
    });
  },
  
  length: function(){
  return Math.sqrt(Math.pow(this.y2-this.y1,2) + Math.pow(this.x2-this.x1,2));},
 
});

**Comment by asturur** [comment]
So the google group is pretty much unmantained, i can't even get behind it because this issue tracker is enough for me.

You arrow class shold work, to deserialize add this after the class declaration, outside the class declaration:

```
fabric.Arrow.fromObject = function(object, callback) {
    return fabric.Object._fromObject('Arrow', object, callback);
  };
```

Start with this and see where do you arrive.

**Comment by rbulph** [comment]
I actually already have this

fabric.Arrow.fromObject = function(options) {
	return new fabric.Arrow(options);
}

It gets called but for some reason the arrow doesn't get added. I'm still trying to figure out why.

I tried substituting your code but it never got called.

**Comment by asturur** [comment]
my code is substantially different. there is a callback argument. 

Please pretty paste all the class in a jsfiddle with linked latest fabric and i ll help you migrating.

**Comment by rbulph** [comment]
OK, here's my attempt at a jsfiddle. I don't know why the canvas doesn't appear bigger. [https://jsfiddle.net/Arbubu/c7mesgf0/35/](url)

**Comment by asturur** [comment]
https://jsfiddle.net/mg7L5jrw/

this fiddle load stuff, with the standard method, i m not sure the rendering is ok.  I cannot find/understand the rendering method of your arrow class.

**Comment by rbulph** [comment]
It's not about the rendering. My fnreviver gets called for all of the objects except the Arrow. It's something to do with my fromObject function. The text object, for instance, via a very long call stack, calls EnlivenPatterns, which calls EnlivenObjects again and finallly calls my fnreviver where I add the object in. My fromObject does none of that.

**Comment by asturur** [comment]
https://jsfiddle.net/hjka61ov/

![image](https://user-images.githubusercontent.com/1194048/70846966-2fbf1600-1e5f-11ea-9f3e-30b385fd3f48.png)

in my fiddle, the arrow gets added, without the reviver, and i added a reviver with a simple console.log, and you can see in the screenshot the Arrow gets called.
That means that in my fiddle there is at least a working solution to your first reported problem.

I'm not sure if other problems will uncover after that.

**Comment by asturur** [comment]
you should NOT need to add the arrow to the canvas manually.

**Comment by rbulph** [comment]
OK, thanks. Should the results that you show appear in the normal browser console? I'm running Chrome and I don't see anything.

**Comment by asturur** [comment]
Did you solve something with this issue?

**Comment by rbulph** [comment]
No, not yet. Been too busy on other things.

**Comment by asturur** [comment]
lets keep the discussion on the proper thread

**Comment by rbulph** [comment]
> lets keep the discussion on the proper thread

Yes, hopefully stale bot won't close it again.

So I'm continuing to try to figure this out. Your fromObject code still doesn't get me the arrow back - just the triangle and text. I'm wondering if I should create a new fabric.Arrow from within the fromObject function. Hopefully I will get there in the end.

**Comment by rbulph** [comment]
Can I post on this now?
