### ISSUE TITLE
Object.toCanvasElement doesn't work well for objects in a selection

### ISSUE THREAD

**Issue by av01d** [fabricjs/fabric.js#5952]
I'm using `Object.toCanvasElement` to generate thumbnails of all objects on canvas.
This works beautifully, except for objects that are part of the active selection.

## Version
3.4.0

## Test Case
http://misc.avoid.org/fabricjs-bug/
(jsfiddle.net is down at this moment)

## Information about environment
Nodejs or browser? browser
Which browsers? all

## Steps to reproduce
see fiddle

## Expected Behavior
Object.toCanvasElement should render all objects on canvas correctly, even if they're part of a selection.

## Actual Behavior
Objects part of a selection aren't rendered correctly.

**Comment by asturur** [comment]
hi @av01d , i look into this asap.
I would expect it to work for both single objects and full selection and objects inside selection.
I would like to know the code you are using because `toCanvasElement` has so many options.

**Comment by av01d** [comment]
view-source:http://misc.avoid.org/fabricjs-bug/

```
function showThumbs() {
	var div = document.getElementById('thumbs');
	div.innerHTML = '';
	
	var objs = fabricCanvas.getObjects();
	for (var i = 0; i < objs.length; i++) {
		var obj = objs[i], mw = 100, mh = 75, ow = obj.width, oh = obj.height, canvas;
		var canvas = obj.toCanvasElement({multiplier:Math.min(mw/ow, mh/oh),withoutTransform:true});
		var thumb = document.createElement('div');
		thumb.className = 'thumb';
		thumb.appendChild(canvas);
		thumbs.appendChild(thumb);
	}
}

fabricCanvas.on({
	'selection:created': showThumbs,
	'selection:updated': showThumbs,
	'selection:cleared': showThumbs,
	'object:added': showThumbs,
	'object:modified': showThumbs
});
```

**Comment by asturur** [comment]
ok so you are using without transform, and you are applying a custom multiplier.
What happens if you run it with default options? do you get bit correct thumbs, or still wrong?

**Comment by av01d** [comment]
Still wrong.

**Comment by asturur** [comment]
This should be fixed asap and i do not think it should be hard.

**Comment by av01d** [comment]
Cool! You'll be rewarded ;-)

**Comment by asturur** [comment]
The Pr fixes the most obvious wrong behaviour.
I wonder what should be the interaction of `withoutTransform` and the group scaling.
