### ISSUE TITLE
mouse:move when click the right mouse button, There will be problems with the line

### ISSUE THREAD

**Issue by yaoleia** [fabricjs/fabric.js#5954]
## Version
2.4.0

## Test Case
http://fabricjs.com/freedrawing

## Information about environment
Nodejs v10.11.0
electron v4.2.12

## Steps to reproduce
When drawing a line, click the right mouse button, and then release the left mouse button. There will be problems with the line

![image](https://user-images.githubusercontent.com/22293549/68290056-4042da80-00c2-11ea-8128-ee43c3c61156.png)

**Comment by av01d** [comment]
Can you describe *what* problems there are? Your description is very vague. The better you describe your exact problem, the better people can help you.
I don't think your issue has anything to do with Fabric. When you click the right mouse button, a context menu will show.... it's a context menu from your browser, not from Fabric.

**Comment by yaoleia** [comment]
Thank you.

When I continue to draw the line, it will become a little bit.


![image](https://user-images.githubusercontent.com/22293549/68554965-3d4f3d80-0466-11ea-9387-b53cd9b80068.png)

**Comment by av01d** [comment]
Okay, I thanks for the explanation, I managed to reproduce this (had to find a two-button mouse first, as I am normally using a magic mouse, where it is impossible to click left and right buttons at the same time).
As I see it, this is not a bug. When drawing, you should simply not right-click your mouse, while the left button is down.
But it's up to the developers here to either agree/disagree with me... I can't make that call.

**Comment by yaoleia** [comment]
thank you ,I really don't know how to fix it, haha

**Comment by asturur** [comment]
other than that there are some canvas properties you can use to prevent the context menu from firing.
