### ISSUE TITLE
SVG rendering bug (Google Noto Emojis)

### ISSUE THREAD

**Issue by av01d** [fabricjs/fabric.js#5955]
## Version
3.4.0

## Test Case
http://misc.avoid.org/fabricjs-bug/bug2.html

## Information about environment
Nodejs or browser? Browser
Which browsers? All

## Steps to reproduce
See test case

## Expected Behavior
All SVG's from the Google Noto collection should render correctly.

## Actual Behavior
Quite some SVG's from this collection don't render in fabricJS, they cause a Javascript error:
`TypeError: can't assign to property "canvas" on "url(#c)": not an object`

**Comment by av01d** [comment]
I found a solution or workaround, I am not sure... 
In the `drawClipPath` function of `fabric.Object`, I change line 13917.
from: ```path.renderCache({ forClipping: true });```
to: ```try { path.renderCache({ forClipping: true }); } catch(e) {}```
This causes the JS error to disappear and the SVG to be rendered correctly.
I'm quite sure this is not the _real_ fix for this issue, I'm hoping it _does_ help to know where to look for real fix.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/68813148-3b0efe00-0675-11ea-9ac8-58ca8a14335d.png)

i do not think the solution i found is perfect, but at least it does not crash fabricjs anymore.
We still need  a new SVG parser imho, and that would be a fun project to work on for me, but for now we have to get this one liner to move on.

**Comment by asturur** [comment]
the change set is ridiculos
https://github.com/fabricjs/fabric.js/pull/5960
