### ISSUE TITLE
fabricjs image update

### ISSUE THREAD

**Issue by qqsea** [fabricjs/fabric.js#5958]
Currently we have the following requirement:
The image data will be sent  row by row in milliseconds, so every time client got the raw data (within matrix), will call inner method to generate data.
`      generate image from rawdata
 
        generateImage = (originalData, WwWl, config) => {    
        let c = document.createElement('canvas');
        c.setAttribute("id", "_temp_canvas");
        c.width = config.column;
        c.height = config.row;
        let tempContext = c.getContext("2d");
        let imageData = tempContext.getImageData(0, 0, c.width, c.height);
        this.generateData(originalData, config.imageNumber, config.column, WwWl, imageData.data);
        tempContext.putImageData(imageData, 0, 0);
        return c.toDataURL();
    }`

and then pass url to fabric.Image.fromURL(url, function(_**img**_){});

every time client got the latest raw data, it will follow above procedure to render the image. The problem is the latency of each rendering too big. For example, after rendering the previous 5 row raw data, client should rendering the 6th raw data, but not, the UI will be hanging there and suddenly the 10th row maybe even the 20th row raw data will be rendering.
I know the image.fromURL function is time consumed, so could I directly edit the _**img**_  after getting the raw data?
Could some one give me some suggestion on how to deal this case? 

Thank you very much!

**Comment by awehring** [comment]
Image.fromURL() is an asynchronous function. The callback is called, when the data are processed. I think you have to organize the timing, when the data come in too fast.

You could collect all the data and start the image generation after all arrived.
Promises or async/await might be usefull, or some kind of queuing (with jQuery or other libraries if you do not want to do it yourself).

**Comment by qqsea** [comment]
Thanks @awehring . Our requirement is as the data come, it should be rendered ASAP.  So controlling the timing is not good idea. Now we plan to use the native html canvas to render the image, and when the data come, we immediately redraw the data.

By the way, is it possible to use the filter mechanism of fabricjs to meet our requirement? In another way, 'applyfilter' is also asynchronous function? 

Thanks very much!

**Comment by awehring** [comment]
I don't know. I have never used the filters.

**Comment by asturur** [comment]
do you know how big is the image beforehand?

If no, i cannot help.

If YES:

create a fabric.Image with a canvas, empty, with the size of the image.
Initialize fabric.Image with that empty canvas, transparent.

When the line of data number X arrives do the following:

```
myFabricImage._originalElement.getContext('2d').putImageData(dataJustArrived, 0, X - 1, imageWidth, 1);
```


This should give you an idea.
This operation should be fast.
