### ISSUE TITLE
Feature request: small change in object.toCanvasElement

### ISSUE THREAD

**Issue by av01d** [fabricjs/fabric.js#5959]
**Is your feature request related to a problem? Please describe.**
When calling `object.toCanvasElement`, the object's properties are reset back to their original state via `this.set(origParams).setCoords();` (line 14423, in function `toCanvasElement`).
This means that overwritten `_set` functions in custom fabric objects (in my case: an object that extends fabric.Image) are called. I run some custom code inside the `_set` function of my custom object. That code runs too often when using `object.toCanvasElement`.
Would you consider changing line 14423:

from:
```
this.set(origParams).setCoords();
```
to:
```
for (var p in origParams) {
   this[p] = origParams[p];
}
this.setCoords();
```

I don't call `set` anymore, and that solves my issue... as far as I can tell, there aren't any side effects.

**Comment by asturur** [comment]
Can i ask you what are you doing in your setter? If you are worried firing it too often may not be the right place for it

**Comment by av01d** [comment]
You are right I guess, in the meantime I have restructured my custom object, it no longer uses a custom `_set` method... issue resolved. Let's close this!

**Comment by asturur** [comment]
i would like to know, if possible, what the custom object does. When objects do many things other than rendering there is always some idea or dev need that can be implemented with the help of fabric supporting some extra hooks, but if those things do not surface, we miss the opportunity to evaluate them.

One example is the emoji and multibyte text. The splitting can be only custom and is implemented with a semi empty function that the developer has to provide. But no need to override.

**Comment by av01d** [comment]
This is what I had before:
```
   _set: function(key, value) {
      switch(key) {
         case 'scaleX':
            if (value != 1) {
               this.width *= value;
               this.scaleX = 1;
               if (this.width < 1) { this.width = 1; }
               this._calcCenter();
            }
            break;

         case 'scaleY':
            if (value != 1) {
               this.height *= value;
               this.scaleY = 1;
               if (this.height < 1) { this.height = 1; }
               this._calcCenter();
            }
            break;

         case 'width':
         case 'height':
            this.callSuper('_set', key, value);
            this._calcCenter();
            break;

         default:
            this.callSuper('_set', key, value);
            break;
      }
   }
```
This is part of an extended Image object, that allows users to zoom into the image within the viewport of the object. The center of the viewport is calculated in the `_calcCenter` function. I thought (incorrectly) that I could disable scaling and set the object's width/height instead.
This seriously harms skewing though, and I have now completely let go of this idea.
Scaling in my object is now working as it is with fabric's own Image object. Works flawless now, and I don't need to override the `_set` method anymore.

**Comment by asturur** [comment]
So basically a cropping window for the image.

I think i would have used the `on('scaling', () => {})` event, or maybe the control api would have helped.

**Comment by av01d** [comment]
I *am* using the `on('scaling')` event now :-)
