### ISSUE TITLE
Free Drawing Brush is generating shadow on created object

### ISSUE THREAD

**Issue by VitorRibeiroCustodio** [fabricjs/fabric.js#5961]
So im working on a project that uses FabricJS. I have to use the isDrawingMode to paint my canvas. One of the functionalities that i've developed, allow to zoom the canvas. So the issue started when i apply the zoom on a scale that allow me to see the pixels on the canvas. So to improve the user experience on my project, i decided to use the Free Drawing Brush option and create a Rect brush to fit perfectly when i have the zoom at max. So i create a class Rect Brush that add Rects to the canvas, like this: 

`      const rect = new fabric.Rect({
        width: 1,
        height: 1,
        left: point.x,
        top: point.y,
        fill: this.drawingColor,
        strokeWidth: 0,
      });
      this.canvas.add(rect);
`
the issue is, when i add the rect on the canvas, it generate a shadow on the object and that is not the behavior that i expect.  

When i was developing this on my mac with Mojave, its was working perfectly, but when i updated to OS Catalina , started to set this shadow without my will. I've tested on other computers and then work just fine. Its just on my computer that i'm finding this issue.

Basically this the object that is been add to the canvas. A rect with shadow and i couldnt remove this shadow at any cost. 

![Captura de Tela 2019-11-13 às 17 45 11](https://user-images.githubusercontent.com/22327574/68813288-253d1100-0654-11ea-80d4-bde68261b999.png)

So just to summarize i want to be able to paint the canvas With Rects to be pixel perfect. I create a class that Extends fabric.BasicBrush and i use that same process as they documentation does, but i choose to use Rect instead of circles. But my Rect are being created with shadow. I've updated my OS to Catalina and since then doenst work anymore, i've tried in other devices and they still working. I'm saying the OS differences because it was the only difference that i found on the test environment.

Can someone help me with  that ?

**Comment by asturur** [comment]
You could start posting a fiddle that let you use this brush in an example.
Retina scaling could be influencing here, also is unclear how this brush work, and that could be important.

**Comment by Manish-Manker** [comment]
how can I use different brushes in Fabric v 5.4.0
