### ISSUE TITLE
can't set an itext start point off the canvas.

### ISSUE THREAD

**Issue by charmjeh** [fabricjs/fabric.js#5965]
hello, 

i am using fabricjs itext and i have an issue

```javascript
  let textOption = {
    fontFamily: "Meiryo", // Simon_191028 Change from "Meiryo"
    fontSize: 32,
    strokeWidth: 0.5,
    fill: "#FFFFFF",
    stroke: "#FFFFFF"
  }
  data.fb = new fabric.Canvas(canvasConfig.textCanvas);

  data.fbText = new fabric.IText("", textOption);
  data.fbTextSecondLine = new fabric.IText("", textOption);

  data.fb.add(data.fbText);
  data.fb.add(data.fbTextSecondLine);

/* ... */

  data.fbText.set({
    /* ... */
    text: 'this is first line',
    top: data.fb.getHeight(),
    left: data.fb.getWidth() / 2,
    originX: 'center',
    originY: 'top'
  })
  data.fbTextSecondLine.set({
    /* ... */
    text: 'this is second line',
    top: data.fb.getHeight() + line_diff, /* <-- I can't see this text */
    left: data.fb.getWidth() / 2,
    originX: 'center',
    originY: 'top'
  });

    data.fbText.animate('top', -(data.fbText.fontSize + line_diff ), 
      onChange: data.fb.renderAll.bind(data.fb),
      duration: 5000);

    data.fbTextSecondLine.animate('top', -data.fbTextSecondLine.fontSize,       
      onChange: data.fb.renderAll.bind(data.fb),
      duration: 5000);


```

I want to set different styles for two text lines,
I used two itext layers on one canvas.

What I want is to create an animation where the two texts move up at the same spacing.

But if i set top value as out of canvas size, , it doesn't show at all.

What should I do?

what i want is that `itext.set({top: 128(canvas size) + 30(difference)})` and then `itext.animate('top', -30(difference), animateoption)`

**Comment by asturur** [comment]
Is it possible to have a jsfiddle for this issue?

**Comment by charmjeh** [comment]
[here is my jsfiddle code](https://jsfiddle.net/eunhee_ju/L0zpvh89/18/)

```
let fbText = new fabric.IText("", textOption);
let fbTextSecondLine = new fabric.IText("", textOption);
```

If I change it to `new fabric.IText("second line", textOption);` in columns 23 and 24, I know that both texts work.
but I have to change the text over time as I keep calling the same function, 
So I chose to `fbTextSecondLine({text: 'second line'})`, but it didn't work. 

Is there a good way?

Thank you for your help

**Comment by charmjeh** [comment]
oh i fixed this problem
i realized i can initialize itext multiple time 

[jsfiddle for this code](https://jsfiddle.net/eunhee_ju/L0zpvh89/60/)

:)
