### ISSUE TITLE
How to retain jpg quality?

### ISSUE THREAD

**Issue by idevwebs** [fabricjs/fabric.js#5968]
Hello,

I've been trying to find a way to retain jpg image quality when used in fabric canvas. Have not been successful. Have tried filters, though have either produced errors or did nothing at all. Docs/code examples up to date with latest version?

There must be a way to keep original jpg image. In my case, loading a 4500x3500 px image in a canvas, scaling to fit canvas on load with scaletoheight(). And then using the zoom with mouse to zoom into image. But the image clarity is lost. 

How do we prevent the quality loss?

**Comment by asturur** [comment]
Depending in what version of fabric you are, you may need to disable caching. no quality is lost in fabric.

Please make a fiddle with your image and the example of quality loss.

**Comment by idevwebs** [comment]
Hello. Version 3.4.0
Can you provide any info regarding the caching you're referring to?

http://jsfiddle.net/wonx3qvd/1/

**Comment by niels-van-den-broeck** [comment]
@asturur  I believe this has to do with the fact that the image is in a group. @idevwebs If you try to render the image instead of the group you'll see that the quality is as expected. The problem is that your group also has a clipPath, and for objects with a clipPath I believe that objectCaching is required.

**Comment by asturur** [comment]
Yes in that case you have a limit on the final size has big as the maximum cache.
Maximum cache is configurable anyway.
http://fabricjs.com/fabric-object-caching

Let's keep the discussion going but seems obvious that there are no bugs to fix here.

**Comment by asturur** [comment]
why you set the image as clipPath? what are you trying to do?
