### ISSUE TITLE
Global Function isEmptyStyles caused TypeError "Cannot read property '0' of null" while set IText or Textbox object's styles to NULL

### ISSUE THREAD

**Issue by swen-xiong** [fabricjs/fabric.js#5969]
## Version
3.4.0

## Information about environment
chrome v74.0.3729.131

## Steps to reproduce
when I set my IText or TextBox's styles to NULL.

## Actual Behavior
Text objects were disappeared and in chrome console log 
> TypeError "Cannot read property '0' of null
    at klass.isEmptyStyles (fabric.js:29235)" ...

## Solution
I looked at the source code and found the Global Function `isEmptyStyles` has such line of code `obj = typeof lineIndex === 'undefined' ? this.styles : { line: this.styles[lineIndex] }` which did not make a judgement of `this.styles`  before.

**Comment by asturur** [comment]
Should work on IText and fail on Textbox.
And this is a bug to fix.
