### ISSUE TITLE
chinese strokeLineJoin   effect is not supported

### ISSUE THREAD

**Issue by xiaowangsmile** [fabricjs/fabric.js#5976]
Expected：
![image](https://user-images.githubusercontent.com/28744261/69029415-d0144d00-0a0f-11ea-8034-1ef062186a16.png)
The effect is right when I select the whole text box
actual：
![image](https://user-images.githubusercontent.com/28744261/69029535-37320180-0a10-11ea-8743-602dc3bb31ad.png)

When I select only a single text, the effect is error

**Comment by asturur** [comment]
i do not think stroke line join is supported per character. i will check. Can you reproduce in a fiddle too? 

Is very important for me to access the font and the code.

**Comment by xiaowangsmile** [comment]
Thank you very much for your reply
my fiddle 
 http://jsfiddle.net/aqnruw39/8/
So sorry   My Chinese font cannot be uploaded normally
`@font-face {
  	font-family: ff;   /*chinese font*/
  src: url('http://diy.zheliyin.com/diyWeb/assets/resource/files/MXYZ-C98E481EE1D548C5B0D66AC54C6AC537.ttf')       
}`
I think it could be a network problem

**Comment by asturur** [comment]
Can i ask you why you would set strokelinejoin for a portion of the text only? Just to understand the effect you are trying to achieve.
Why you can't set it for all the text?

**Comment by xiaowangsmile** [comment]
Thank you very much for your reply
![image](https://user-images.githubusercontent.com/28744261/69107324-f4256c00-0aab-11ea-9e96-63eea422abf1.png)
I'm using fabric to Design Coupons，There's a similar effect in my program

**Comment by asturur** [comment]
But why would you set it on 88 only and not on all text?

**Comment by xiaowangsmile** [comment]
Thank you very much for your reply
Sorry，According to Chinese design habits, it is usually designed like this。
I'm trying to find out  other ways to avoid this question. Thank you again for your answer

**Comment by asturur** [comment]
I think this feature can be fixed, i just want to understand why you can't set strokeLineJoin to all the object rather than to a subset of style.

You would still set stroke and strokeWidth to the subset.


```js
var textbox2 = new fabric.Textbox('有效期限', {
  top:100,
  width: 260,
  fontSize: 30,
  fontFamily:'ff',
  strokeLineJoin: 'round',
}); 


obj.setSelectionStyles({strokeWidth:1,stroke:'#009944'});
```

**Comment by xiaowangsmile** [comment]
Thank you for your answer
but，This solution doesn't work now
