### ISSUE TITLE
Can't draw a dot in microsoft edge if I set the line width below 6

### ISSUE THREAD

**Issue by curtisfletcher** [fabricjs/fabric.js#5977]
## Version
3.5.0

## Test Case
http://fabricjs.com/freedrawing

## Information about environment
Microsoft Edge

## Steps to reproduce
Draw a single dot (ie not a line) in free drawing mode at a line width below 6 in Microsoft Edge

## Expected Behavior
Draw a dot

## Actual Behavior
Draws nothing

**Comment by asturur** [comment]
I do not have EDGE to investigate/replicate.
Can you provide a gif or similar?

What version of EDGE? there are plenty.

**Comment by curtisfletcher** [comment]
![fabric js bug](https://user-images.githubusercontent.com/55085861/69062721-15179e00-0a67-11ea-9230-5e12f8dc59c0.gif)
Microsoft Edge 44.18362.449.0
