### ISSUE TITLE
On setting clippath to video object, hides other objects added before.

### ISSUE THREAD

**Issue by satendra02** [fabricjs/fabric.js#5980]
## Version
2.4.1 

## Steps to reproduce
https://jsfiddle.net/satendra02nov/w3t2adr4/79/

On setting clippath to a video object, hides other objects added before.
You can see that the text object is added before the video object and it is not visible

If I do same thing with Image object it works fine. 

> I have commented image code at bottom of jsfiddle

**Comment by asturur** [comment]
jsfiddle decided to die in the moment i was looking at the example.
Anyway, the video is not playing in my jsfiddle, it requires a button to be played more than a simple `.play()` statement. 🤷‍♂

**Comment by satendra02** [comment]
@asturur jsfiddle is working fine at my end. 

So can you point out whats the possible cause for such behaviour?

**Comment by asturur** [comment]
https://jsfiddle.net/62c8o3zq/

Is written in the doc that clipPath REQUIRES object caching set to true, that you are setting as false.

Please if you have to clip an image with a Rect, use the cropX, cropY, width and height to obtain the same effect but without the need of caching.
Also use the latest from fabric 2.x series at least, even if i suggest the latest in general.

**Comment by satendra02** [comment]
@asturur setting `objectCaching` to `true` on video object worked. But now the video is stuck at its first frame on the canvas, I can see that the HTML video element is playing fine but not getting updated on canvas.

**Comment by satendra02** [comment]
@asturur It worked, I overrode the `play` event of video element and there I am setting `dirty` to `true` on video fabric object.

Thanks

**Comment by asturur** [comment]
Yes, i provided a working example in my fiddle link.
I would suggest you again that if you do not need any kind of weird shape clipping, to just use the normal square cropping rather than clipPath.

Change width/height/cropX/cropY of your video in order to crop it with a rectangle. No caching needed, no clipPath needed.
