### ISSUE TITLE
Doubleclick on non-selectable IText fires "text:selection:changed"-Event

### ISSUE THREAD

**Issue by awehring** [fabricjs/fabric.js#5981]
## Description
See Title.

It's a minor issue, but can be confusing in some applications. 

## Version
3.4.0

## Test Case
https://jsfiddle.net/awehring/authmgs1/3/

## Information about environment
Edge, Firefox

## Steps to reproduce
- Add an Itext object to canvas
- Set `selectable: false, editable: false`
- Doubleclick the text

## Expected Behavior
No selection event will be fired

## Actual Behavior
`text:selection:changed` event is fired

**Comment by asturur** [comment]
i think has been fixed in current master
