### ISSUE TITLE
Can fabric.js be used to create an overlay blur mask?

### ISSUE THREAD

**Issue by matixmatix** [fabricjs/fabric.js#5982]
Is it possible to use fabric.js to achieve an effect like this? An object that can be moved freely and blurs the image behind 

![image](https://user-images.githubusercontent.com/273660/69067619-a9601180-0a23-11ea-82e3-0efd7cc11cdd.png)

**Comment by asturur** [comment]
yes and no.
Is a full app more than a simple function.

In 2 words, you organize your canvas with the objects.
Every change on your canvas you export the canvas to a copy element.
you create a fabricImage from that element
you apply a blur filter to that fabricImage
at this point you have a blurred copy of your canvas with all the objects.


Now you have a couple of ways to cut it and position it where you want.

you either you cropX/cropY and width/height on the image to obtain the area of the canvas you are interested in, or you create a Rect and you use the image as a filler for the rect ( a Pattern ).

If this is your first experience with fabricJS all of this may sound complicated, but is not.

Look in the docs for the following things:

```
StaticCanvas.toCanvasElement

fabric.Image.filters.Blur

fabric.Image.cropX, fabric.Image.cropY.

fabric.Pattern
```

**Comment by matixmatix** [comment]
@asturur thanks for your help. I managed to get it working when moving the selection, but not when scaling the selection.

Please check this screen video: https://media.giphy.com/media/VdWsw45mXAoHpRpn2c/giphy.gif

You can see that when scaling the image, the blur just gets scaled. The desired outcome is that the image shouldn't get scaled, but simply cover more area in the background image and be reflected in the blur. Is that possible to achieve? If yes, how?

Fiddle here: https://jsfiddle.net/jurgenwerk/r0sh2o5u/6/

**Comment by asturur** [comment]
can t really open any code right now, but you can use the on('scaling') event to change image size rather than scaling. I ll check later

**Comment by matixmatix** [comment]
@asturur thanks for the tip. I'm interested in how to calculate the image and copied canvas dimensions on scaling so that the masking image will adjust properly (not stretching). Thanks!

**Comment by matixmatix** [comment]
@asturur I managed to solve this issue. JSFiddle here: https://jsfiddle.net/jurgenwerk/top84ye6/1/

**Comment by asturur** [comment]
Do you feel like making a demo with this feature? could be usefull to
someone else.

Making a demo page in fabricjs.com is relatively easy.

**Comment by Rosga** [comment]
Another blur solution that I use in my project:
1. Use additional image (not canvas, simple `<div />` html tag and background-image css property) under the Fabric's canvas and blur it using CSS filter. 
2. Extend rect's `render` method to simply draw fully transparent rectangle. 
As a result, it would make a "hole" in the canvas that shows blurred image under the fabric's canvas.

pros: the solution is highly performant and allows easily using several `blur` items on the screen. it only uses one additional image that is blurred, so no need to create and manipulate with canvas objects

cons:
- it is not straightforward and requires some math logic to locate background image for zoom and crop functionality
- `.toDataURL()` method returns blank rectangle (workaround: override the method, replace `render` for rects with [blur algorithm](http://www.quasimondo.com/BoxBlurForCanvas/FastBlurDemo.html), and after the `dataURL` extracted - replace with original one)
- works only as an image background blur. It doesn't blur canvas

**Comment by Zhouqchao** [comment]
@asturur is it possible to use fabric.js to achieve same blur effect while rendering video in requestAnimFrame function? I want to make a blur mask, which can blur some part of video frame and make it move freely, thanks.

**Comment by iampava** [comment]
Hey! I have the same requirements as @Zhouqchao. I was thinking of using a Rect element and overwriting the `_render` function. 

Do you see any red flags regarding this approach?
