### ISSUE TITLE
group objects can not be edited

### ISSUE THREAD

**Issue by xiaowangsmile** [fabricjs/fabric.js#5984]
when i group objects together, and manipulate them at the same time，Is it possible to edit by double clicking on any one of them，Instead of ungrouping and editing later。
eg：
![image](https://user-images.githubusercontent.com/28744261/69108076-89c1fb00-0aae-11ea-9823-600ae39bb273.png)

**Comment by awehring** [comment]
Might be related to issue #5981

**Comment by asturur** [comment]
this is definitely a bug and needs a fix.

**Comment by asturur** [comment]
I can't actually make it happen, can you make it happen in a fiddle?

**Comment by xiaowangsmile** [comment]
Thank you for your reply
In the current version, I can't edit the text box in the group
My solution：
When I double-click the text or picture in the group, first I will remove it from the group, then Create a new object in the same location,  Put it in the group after editing.
I think my solution is  very complicated and should not be adopted

**Comment by asturur** [comment]
fabricJS does not allow for multi selected editing. Is not a feature now and is not planned for now.

**Comment by xiaowangsmile** [comment]
thank you
