### ISSUE TITLE
Resize handlers are shrink to fit while changing font size

### ISSUE THREAD

**Issue by albert-hoffman** [fabricjs/fabric.js#5987]
## Version
3.5.1

## Information about environment
browser
All browsers

## Steps to reproduce
Add any text using fabricjs,
scale texts using handlers to bigger level may be around A4 size,
Now change the font size to 18 using programming like, font.set('fontSize', 18).
it changes the font size but resizes handler are still bigger they should also shrink to fit with font size. 

## Expected Behavior
they should also shrink to fit with font size. 

Expected thing
![image](https://user-images.githubusercontent.com/53006107/69234465-38e8fa00-0bb5-11ea-84cd-818ee75ed6b8.png)

## Actual Behavior
current issue
![image](https://user-images.githubusercontent.com/53006107/69234447-2969b100-0bb5-11ea-86ad-cd5018b82fea.png)

**Comment by albert-hoffman** [comment]
I have tried `text.width = text.scaleX * text * fontSize`
But it is not working properly.

**Comment by asturur** [comment]
The bounding box of the textbox is not shrink to fit.
You can try `myText.calcTextWidth()` in order to know the max width needed and set that.
