### ISSUE TITLE
toDatalessJSON is rounding the objects scaleX and scaleY

### ISSUE THREAD

**Issue by Tsunami2069** [fabricjs/fabric.js#5990]
## Version
3.1.0

## Test Case
http://jsfiddle.net/k8jfqg6d/

## Information about environment:
Browser - Google Chrome (78.0.3904.97)

## Steps to reproduce
Add an object to a canvas that as a scaleX and/or scaleY with more then 2 decimal digits. Then do a toDatelessJSON and get the scaleX and/or scaleY of the same object.

## Expected Behavior
For the scaleX and scaleY to remain the same.

## Actual Behavior
The scaleX and ScaleY are rounded to a 2 decimal maximum number, resulting in the loss of precision.

## Message
Hello.
As the template as stated, I've been having a bit of an issue with a project that uses toDatalessJSON and loadFromDatalessJSON. Recently, after my code calls these functions, I was noticing that the images would change size in a small factor but still noticeable.
After some digging, I discovered that this was caused by the toDatalessJSON rounding the scaleX and scaleY of the objects.

I've added a small fiddle where you can see that in action. A triangle with a 4.4852543445 scaleX gets rounded to 4.49 after the toDatalessJSON.
You can check it out just by clicking the "Click Me!" button.

Is this expected behaviour?
Is there a way for the toDatalessJSON not to behave like this?

It is quite important for my project for the toDatalessJSON to keep the objects as they were, in terms of position, size, etc.

Thank you for your help.

**Comment by melchiar** [comment]
You can change the number of decimals that values like scale are serialized to with the property `fabric.Object.NUM_FRACTION_DIGITS`.

See [FabricJS Gotchas](http://fabricjs.com/fabric-gotchas) (the section on **Wrong position after reloading a JSON object**).

**Comment by asturur** [comment]
correct! thanks @melchiar

**Comment by Tsunami2069** [comment]
Ahhh much appreciated.

**Comment by outside2** [comment]
问题已解决，非常感谢
