### ISSUE TITLE
toDataURL error

### ISSUE THREAD

**Issue by WanManito** [fabricjs/fabric.js#5992]
## Version
3.5.0
const dataURL = this.canvas.toDataURL({
                    format: 'jpeg', // jpeg或png
                    quality: 0.8 // 图片质量，仅jpeg时可用
                    // 截取指定位置和大小
                    //left: 100,
                    //top: 100,
                    //width: 200,
                    //height: 200
                });
![image](https://user-images.githubusercontent.com/26118508/69301228-836b8480-0c50-11ea-9e15-c9401e7e7f65.png)

**Comment by wildccy** [comment]
Have you solved it

**Comment by WanManito** [comment]
work&nbsp;out&nbsp;，pass&nbsp;let canvas = document.getElementsByTagName('canvas')[0];

This method gets the canvas





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wildccy"<notifications@github.com&gt;; 
发送时间: 2019年11月22日(星期五) 下午2:14
收件人: "fabricjs/fabric.js"<fabric.js@noreply.github.com&gt;; 
抄送: "我亦是行人"<2430937882@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [fabricjs/fabric.js] toDataURL error (#5992)




Have you solved it
