### ISSUE TITLE
Change text style while typing

### ISSUE THREAD

**Issue by ateodor1** [fabricjs/fabric.js#5994]
## Version
3.5.1

## Test Case
Create a text object
start typing
Change the style (the text still has the focus)
continue typing
I expected I was able to continue typing but it freezes

## Information about environment
Chrome

## Steps to reproduce
Access http://fabricjs.com/loadfonts
Click twice on the text, start typing then click on the select to change the font family and try to type new letters, sometimes it takes some time to return and some times it does not work at all. The same happens if I try to change the style to bold, italic, underline...

For example:
text.set("fontWeight", "normal");

I even tried 
text.hiddenTextarea.focus();

but it didn't work

## Expected Behavior
when I change the style I'd like it to not stop working

## Actual Behavior
it freezes and takes some time to return or stop working and I have to double click again to edit.

Thanks.

**Comment by awehring** [comment]
I had the same problem and use the following work around now. 

fabric.js superimposes an IText element for editing with an `textarea` element. It has an attribute `data-fabric-hiddentextarea`. 

I use jQueries "delegated Event" function to assign the event handler to the not yet existing textarea element:

```
$("body").on(
"focusout", "textarea", function (evt) {

var $textareaelement = $(evt.target);		

if ($textareaelement.attr("data-fabric-hiddentextarea") === "") {
	// save the textarea element to a global variable
	$textareainputelement = $textareaelement;      
}
});
```

After changing the style (with a button or something else) I set the focus back to the textarea element

```$textareainputelement.focus();```


Maybe there are better solutions, but it works for me.
