### ISSUE TITLE
fabric.Line uses "fill" for color, not "stroke"

### ISSUE THREAD

**Issue by thevinci** [fabricjs/fabric.js#60]
Check out http://kangax.github.com/fabric.js/test/functional/functional_tests.js in Chrome. Setting color to "stroke" doesn't change the color. I had to use "fill" to actually change the line color.

**Comment by songofhawk** [comment]
fabric.Line still uses "fill" for color now?  If so, why the option parameter of inistializing method, uses "stroke"  property to indicate color ?

**Comment by asturur** [comment]
I do not remember on top of my head, this is a discussion from 2011, early fabric days.
Please check the current version and point out eventual non consistency

**Comment by songofhawk** [comment]
actually i haven't found how to change the color of fabric.Line on latest version, i tried:
`line.stroke = 'rgba(191,191,191,1)';`
`line.fill= 'rgba(191,191,191,1)';`
`line.color= 'rgba(191,191,191,1)';`

None of them works.

**Comment by asturur** [comment]
please use 

set(property, value)

**Comment by songofhawk** [comment]
thanks, it works.

`line.set('stroke','rgba(191,191,191,1)');`

And, it's consistent with the option object.
