### ISSUE TITLE
Interaction between objects

### ISSUE THREAD

**Issue by Federico76** [fabricjs/fabric.js#6002]
if I execute the following code:

```
var oCanvas = new fabric.Canvas('a');
	
var oGreen = 		new fabric.Rect({left: 100, top:   100, fill: 'green', width: 10, height: 10});
var oBlue = 		new fabric.Rect({left: 200, top:   100, fill:  'blue', width: 10, height: 10});

oGreen.on('moving',	function()	{oBlue.set('top', this.get('top'));});
oBlue.on('moving',	function()	{oGreen.set('top', this.get('top'));});
	
oCanvas.add(oGreen);
oCanvas.add(oBlue);
```
and then drag the green rectangle down I realize that I cannot drag the blue rectangle.
why?
am I wrong anything?

**Comment by asturur** [comment]
code seems ok, but you should make a jsfiddle so that it can be tested.

**Comment by Federico76** [comment]
I'm not able to use https://jsfiddle.net/,  but you can try pasting the following code in the html field (in https://jsfiddle.net/)
```
<html>
	<head>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/3.5.0/fabric.min.js"></script> <!-- https://cdnjs.cloudflare.com/ajax/libs/fabric.js/3.5.0/fabric.min.js-->
		
	</head>
	<body>
		<canvas id="Cv01" width="1600" height="600" style="border:1px solid #ccc"></canvas>
		<script>var oCanvas = new fabric.Canvas('Cv01');
		var oStanteVerticale 	= new fabric.Line([0, 0, 100, 0],		{left: 100, top: 100, stroke: 'black', strokeWidth: 2});
	
		var oGreen = 		new fabric.Rect({left: 100, top:   100, fill: 'green', width: 10, height: 10});
		var oBlue = 		new fabric.Rect({left: 200, top:   100, fill:  'blue', width: 10, height: 10});

		oGreen.on('moving',	function()	{
			oBlue.set('top', this.get('top'));
		});
		oBlue.on('moving',	function()	{
			oGreen.set('top', this.get('top'));
		});
			
		oCanvas.add(oStanteVerticale);
		oCanvas.add(oGreen);
		oCanvas.add(oBlue);	
			
		</script>

	</body>
</html>
```

**Comment by asturur** [comment]
Please, try to do it by yourself and save a fiddle. no account required.

**Comment by Federico76** [comment]
can I speak in Italian?
https://github.com/fabricjs/fabric.js/issues/6002

**Comment by Federico76** [comment]
[https://github.com/fabricjs/fabric.js/issues/6002](url)

**Comment by Federico76** [comment]
https://jsfiddle.net/Federico76/zemo4179/

**Comment by Federico76** [comment]
Non so se può essere utile, ma mi sono accorto che se trascino verso il basso uno dei due quadrati (per esempio il blu) l'altro quadrato viene trascinato verso il basso ma il suo punto di '**trascinamento**' rimane in prossimità della sua posizione iniziale (in prossimità del segmento nero disegnato);
è come se il punto di trascinamento non subisse l' azione **oBlue.on('moving',...**.

**Comment by asturur** [comment]
Hi @Federico76 thanks for the fiddle.
As you can read here:
http://fabricjs.com/fabric-gotchas, at the first paragraph, there is exactly your problem explained.

**Comment by asturur** [comment]
I'll close the issue, unless i misunderstood your problem and we need more talks.

**Comment by Federico76** [comment]
I solved the problem by following your instructions.
Thank you very much.
