### ISSUE TITLE
Is there a way to make the text inside the text box vertical layout

### ISSUE THREAD

**Issue by gaowenzhen** [fabricjs/fabric.js#6005]
I changed the text box angle to 90 degrees, the internal text cannot change the angle

`
textboxobj.set({angle: 90, flipX: true})

`
Trying the following properties is also not working

transformMatrix，and  flipX
--------------------------------

I want effect,Make text vertical

     A
     B
     C
     D
     ——

**Comment by asturur** [comment]
duplicate of #511 

vertical text can be added as soon as i understand how vertical text, for example in japanese, is supposed to work
