### ISSUE TITLE
Can ecart / highchart object rendering be supported

### ISSUE THREAD

**Issue by shijunfeng** [fabricjs/fabric.js#6007]
I tried to render the echart / highchart object to the canvas through fabric.js, but I couldn't. The current version does not support?

 	testEchar =()=>{
                 var canvas = new fabric.Canvas('c');
		 var option = {
			 title: {
				 text: 'testechart'
			 },
			 tooltip: {},
			 legend: {
				 data:['Type']
			 },
			 xAxis: {
				 data: ["A","B","C","D","D","F"]
			 },
			 yAxis: {},
			 series: [{
				 name: 'Num',
				 type: 'bar',
				 data: [5, 20, 36, 10, 10, 20]
			 }]
		 };
		var myChart = echarts.init(document.getElementById('mian'));
		myChart.setOption(option);
		 var offcanvas = myChart.getRenderedCanvas({
			pixelRatio: 2,
			backgroundColor: '#fff'
		});
		 canvas.add(offcanvas);//Exception thrown here
	   }

**Comment by asturur** [comment]
if offCanvas is a HTMLCanvasElement, you can do what you are doing, but create a fabric.Image from the canvas.

```js
...
        var offcanvas = myChart.getRenderedCanvas({
		pixelRatio: 2,
		backgroundColor: '#fff'
	});
        var fabricChart = new fabric.Image(offcanvas);
	canvas.add(fabricChart);//Exception thrown here
...
```

**Comment by shijunfeng** [comment]
OK ！I get it。

**Comment by shijunfeng** [comment]
But I don't want a picture

**Comment by asturur** [comment]
and what do you want? because you are generating a picture of it.

**Comment by shijunfeng** [comment]
I want to be exactly the same as that rendered by echart. Can it be implemented?

**Comment by shijunfeng** [comment]
Because I want to add pictures, text, and echart or highchart charts to the canvas.

**Comment by asturur** [comment]
```
var offcanvas = myChart.getRenderedCanvas({
		pixelRatio: 2,
		backgroundColor: '#fff'
	});
```
This is probably giving you a picture of the chart.
You can add that picture of the chart on the canvas together with other things.

**Comment by shijunfeng** [comment]
I know, but I prefer to add the canvas generated by Echart to the canvas through fabric. Because it's a better way to manipulate charts.This is because I know that the picture can definitely be added to the canvas through cloth. Compared with the picture, I want to get a chart generated like echart, not a picture. I hope you understand.

**Comment by asturur** [comment]
I do not understand, because i have no idea of what eCharts is or does.
You have to setup a fiddle that shows it at least.
How can anyone help otherwise?

**Comment by shijunfeng** [comment]
`testEchar =()=>{
             var canvas = new fabric.Canvas('c');
	 var option = {
		 title: {
			 text: 'testechart'
		 },
		 tooltip: {},
		 legend: {
			 data:['Type']
		 },
		 xAxis: {
			 data: ["A","B","C","D","D","F"]
		 },
		 yAxis: {},
		 series: [{
			 name: 'Num',
			 type: 'bar',
			 data: [5, 20, 36, 10, 10, 20]
		 }]
	 };
	var myChart = echarts.init(document.getElementById('mian'));
	myChart.setOption(option);
	canvas.add(myChart);
   }`

**Comment by shijunfeng** [comment]
testEchar =()=>{
             var canvas = new fabric.Canvas('c');
	 var option = {
		 title: {
			 text: 'testechart'
		 },
		 tooltip: {},
		 legend: {
			 data:['Type']
		 },
		 xAxis: {
			 data: ["A","B","C","D","D","F"]
		 },
		 yAxis: {},
		 series: [{
			 name: 'Num',
			 type: 'bar',
			 data: [5, 20, 36, 10, 10, 20]
		 }]
	 };
	var myChart = echarts.init(document.getElementById('mian'));
	myChart.setOption(option);	
	 canvas.add(myChart);//Exception thrown here
   }

**Comment by GDY-2000** [comment]
Have you solved the problem now？

**Comment by pooja0304** [comment]
@shijunfeng I am also looking for the same, have you got the solution to this?

**Comment by ShaMan123** [comment]
If it renders to a canvas add that canvas as a fabric.Image

**Comment by pooja0304** [comment]
Thanks for taking time to help me out.
I have tried adding as an image , but then interactions with the charts
suffers like hover etc. do you have any solution to this?

**Comment by pooja0304** [comment]
Thanks for the tip . It would be great if you can publish it.

Thanks again
Pooja golani
