### ISSUE TITLE
Using toDataURL to get a rotated part of the canvas.

### ISSUE THREAD

**Issue by Sashkan** [fabricjs/fabric.js#6008]
**Is your feature request related to a problem? Please describe.**
My basic setup is a canvas, with a rectangle in it. Every image that is added in the canvas uses this rectangle as its clipPath. Once the image is added, I extract the content of the rectangle and turn it into a PNG, using toDataURL.

The easy part is that all I have to do is 

``` js
const myPNG = canvas.toDataURL({
	top: rect.top,
	left: rect.left,
	width: rect.width,
	height: rect.height.
})

```
So far, so good. Now, the tricky part: let's say my rectangle is transformed, using a simple 90° rotation. Its left, top, width and height are still the same, but obviously, if I use the same toDataUrl() method, the  resulting PNG will be a mess.

**Describe the solution you'd like**
Ideally, just add another 'angle' key to the `option` param

**Describe alternatives you've considered**
I tried rotating the whole canvas to match the rotation of the clipping rectangle before using toDataURL, but then I'm not so sure how I'm supposed to retrieve the new rectangle coordinates.

**Additional context**

**Comment by asturur** [comment]
so you can't extract right now rotated parts of the rect, but in case of multiple of 90 degree rotations you can use the rect bounding box as a clipppin box.

```
rect.getBoundingRect
```

from 

http://fabricjs.com/docs/fabric.Object.html#getBoundingRect

**Comment by Sashkan** [comment]
Thanks :)

For anyone wondering, I managed to achieve this by using this:

Considering `helper` is your cropping rectangle:

```js
   if (helper.angle) {
            rotated = helper.angle
            const degrees = helper.angle
            const rads = fabric.util.degreesToRadians(degrees)
            const canvasCenter = new fabric.Point(canvas.getWidth() / 2, canvas.getHeight() / 2)

            canvas.getObjects().forEach((obj) => {
              const objectOrigin = new fabric.Point(obj.left, obj.top)
              const new_loc = fabric.util.rotatePoint(objectOrigin, canvasCenter, (rads * -1))

              obj.set({
                top: new_loc.y,
                left: new_loc.x,
                angle: obj.angle - degrees,
              })

              canvas.renderAll()
            })
          }

          const printImg = canvas.toDataURL({
            format: 'png',
            left: helper.left,
            top: helper.top,
            width: helper.width,
            height: helper.height,
          })
```
By using this, you rotate the whole canvas, including your clipping rectangle, so that the result of `toDataURL` will be a 'straight' rectangle.
