### ISSUE TITLE
Helper functions for per-pixel collision detection

### ISSUE THREAD

**Issue by raichu** [fabricjs/fabric.js#601]
Per-pixel collision can be done, thanks to the recent commits, but I realized if we had these functions, it could be done even more effectively
- A function that returns the intersecting polygon between two objects. It looks like intersectsWithObject already does this, but it doesn't return the intersect object, it just checks the status.
- A function that returns whether a given point (or x,y pair) is contained within a polygon or intersection object (is used in containsPoint?).
##

**Comment by ShaMan123** [comment]
closed by #8121 
Intersection had some bugs that were fixed
You can obtain the points and check color using `isTransparent`
