### ISSUE TITLE
The Stroke uniform property of the grouped objects do not work

### ISSUE THREAD

**Issue by xiaowangsmile** [fabricjs/fabric.js#6010]
## Version
3.5.0

## Test Case
http://jsfiddle.net/3y21f8ks/

## Information about environment
Nodejs or browser?
Which browsers?
chrome 78

## Steps to reproduce
When I'm not in a group, the Stroke uniform property is OK,
But The Stroke uniform property of the grouped SVG do not work

## Expected Behavior
![image](https://user-images.githubusercontent.com/28744261/69797906-72e87a80-120b-11ea-8abb-1e0af1e16dee.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/28744261/69798554-7af4ea00-120c-11ea-866a-10a40329280a.png)

**Comment by asturur** [comment]
already tracked in #5611
