### ISSUE TITLE
currentHeight and currentWidth in fabric 3.4

### ISSUE THREAD

**Issue by anuj9196** [fabricjs/fabric.js#6012]
I am re-writing a library earlier written in `fabricjs 1.4` to `fabricjs 3.5`.

In `fabricjs 1.4` there were attributes `currentHeight` and `currentWidth`, My library is breaking as these two attributes are missing in new fabric class object.

**Is there any alternative for `currentHeight` and `currentWidth` fabric class object's attributes?**

**Comment by asturur** [comment]
i think those are now getScaledHeight/Width.

I m not sure what they were representing before. Do you remember?

If you are in the process of rewriting and you do special things with controls you may want to wait for 4.0

**Comment by asturur** [comment]
i keep the issue close since there are no action items here.

**Comment by anuj9196** [comment]
May be you can reference this [http://fabricjs.com/report/files/object_geometry_mixin_js/index.html](http://fabricjs.com/report/files/object_geometry_mixin_js/index.html) for more detail.
I got a workaround for my library from the `setCoords` function and it's working as expected as of now.
