### ISSUE TITLE
Gradient Text is not working in v3.4.0

### ISSUE THREAD

**Issue by rafael-cruz-cloudpix** [fabricjs/fabric.js#6014]
## Version
3.4.0

## Test Case
http://jsfiddle.net/Lcqzvx97/

## Information about environment
Nodejs or browser?
- Browser

Which browsers?
- Chrome and Firefox

## Steps to reproduce
- Add a text on canvas.
- Call setGradient on text object.
- Re-render canvas.

## Expected Behavior
- Gradient to be applied in text filling.

## Actual Behavior
- Text is rendered with white fill.

**Comment by asturur** [comment]
confirmed is a bug.
Planning to fix this asap
