### ISSUE TITLE
jsdom.JSDOM is not a constructor

### ISSUE THREAD

**Issue by kirill-chirkov-at-clouty** [fabricjs/fabric.js#6015]
## Version
3.5.1

## Test Case
1. Import fabric somewhere in typescript file:
`import { fabric } from 'fabric';`
2. Compile bundle via webpack
3. Execute code in NodeJS environment

## Information about environment
NodeJS

## Steps to reproduce
Following https://github.com/fabricjs/fabric.js/issues/5914 I was able to update webpack externals by provided example https://github.com/fabricjs/fabricjs-webpack/blob/canvas2-webpack4/webpack.config.js

However this does not help the build and error is the same: https://github.com/fabricjs/fabric.js/issues/5914#issuecomment-539450159
Merely just importing fabric it would crash code in runtime.

**Comment by asturur** [comment]
If you are getting a crash at runtime it means that you are running it under node.
Are you doing some node work with fabricJS? are you making a SSR of some component that requires fabric?

**Comment by kirill-chirkov-at-clouty** [comment]
Yes, I'm in node environment for angular SSR. Hovewer I'm not instantiating fabric on node, here's the usecase:
```typescript
import { fabric } from 'fabric';

...

private instantiateCanvas(imageEditorElement: HTMLCanvasElement): fabric.Canvas {
        if (!isPlatformBrowser(this.platform)) {

            return null;
        }
        const canvas = new fabric.Canvas(imageEditorElement, {
            preserveObjectStacking: true,
            allowTouchScrolling: true,
            backgroundColor: '#fff',
        });
        canvas.renderAll();

        return canvas;
}
```
So I guess that just merely importing fabric on server breaks it.

**Comment by asturur** [comment]
yes it does. Because it will run the node code.
I'm not sure there is a fix, and how this fix should behave.
Maybe we could have a boolean, `notRunNode` to avoid trying to instantiate JSDOM in those cases.

**Comment by kirill-chirkov-at-clouty** [comment]
As for me, a noop instantiating would be a fine too like if we don't have some libraries in current environment - we're doing noop instance. I also wonder why fabric is instantiating eagerly instead of lazy initialization? Is that necessary for static functions or there is some global state?

**Comment by asturur** [comment]
There is no need to instantiate immediately.
When that code was written, ( 2010? ) webpack and ssr rendering maybe were way less common.

We should have a boolean now, and for 4.0 refactor to a default instantiate jsdom on need.

**Comment by asturur** [comment]
if you have time for a PR, add a boolean on header.js
fabric.noJSDOM = false as default.

Then on that part of code, if `noJSDOM` is true, do not enter the if that requires and instantiate jsdom.

Or i'll do at first occasion.

**Comment by kirill-chirkov-at-clouty** [comment]
How this flag should be used in project? Should this be included in webpack config somewhere?

**Comment by asturur** [comment]
mmm i think it won't work now that i better think. Because to set it, you have to import fabricJS.
Scrap my idea.

**Comment by asturur** [comment]
i need to check if a postinstall script is possible and a flag to scrap that line.

**Comment by asturur** [comment]
you can also eventually build a better webpack config that allows you to isntatiate a fake jsdom. Let me see if i can pull out something

**Comment by kirill-chirkov-at-clouty** [comment]
Seems like angular universal (angular for server-side) removed configuration via webpack in last major update and now this cannot be tweaked with `externals` stubs. I wonder whether fabric can run on server (noop run is fine too) without tweaking webpack config? E.g. not importing canvas etc. prematurely.

**Comment by kirill-chirkov-at-clouty** [comment]
Seems like I resolved problem on angular side (https://github.com/angular/universal/issues/1508#issuecomment-586283291) and custom webpack config not required.

**Comment by asturur** [comment]
great to know!
