### ISSUE TITLE
Call discardActiveObject without trigger a clear selection:cleared event

### ISSUE THREAD

**Issue by BenoitClaveau** [fabricjs/fabric.js#6017]
I use fabric.js with redux. I store my selection in my redux store.
Each time my model changing I clear the selection with discardActiveObject to get all Fabric objects in absolute prositions. Otherwise, each Rect of the selection is relative to the selection area.
discardActiveObject trigger a selection:cleared event.

It would be nice to have an option to disable the selection:cleared event.

thx.

**Comment by asturur** [comment]
did you tried using `_discardActiveObject` ? that is the code part without the firing events?
This could be clarified in the docs, that function for now is just marked as _private.

**Comment by BenoitClaveau** [comment]
Thanks asturur, It works. I have the same pb with setActiveObject which fire an selection:created I changed it by _setActiveObject.

**Comment by asturur** [comment]
If you have time, can you open a PR that explain what those 2 methods do, adding the description in the jsdoc?

**Comment by asturur** [comment]
clarified in jsdocs.
