### ISSUE TITLE
可以提供一个类似于辅助线的封装吗，有关限制区域的

### ISSUE THREAD

**Issue by joylord2018** [fabricjs/fabric.js#6020]
我自己尝试写了用于限制对象在画布移动，第一种还可以的，但是只要一旋转对象，就会有问题
let leftViewPort =
          c.viewportTransform[2] * obj.canvas.getZoom() +
          obj.width * obj.scaleX +
          c.viewportTransform[2];

        let topViewPort =
          c.viewportTransform[3] * obj.canvas.getZoom() +
          obj.height * obj.scaleY +
          c.viewportTransform[3];

        if (obj.left < 0) {
          obj.left = 0;
        } else if (obj.left > obj.canvas.width - leftViewPort) {
          obj.left = obj.canvas.width - leftViewPort;
        }

        if (obj.top < 0) {
          obj.top = 0;
        } else if (obj.top > obj.canvas.height - topViewPort) {
          obj.top = obj.canvas.height - topViewPort;
        }

第二种是针对于旋转的，但缩放画布会有问题

 if (
          obj.currentHeight > obj.canvas.height ||
          obj.currentWidth > obj.canvas.width
        ) {
          return;
        }
        obj.setCoords();

        // 上-左
        if (obj.getBoundingRect().top < 0 || obj.getBoundingRect().left < 0) {
          obj.top = Math.max(obj.top, obj.top - obj.getBoundingRect().top);
          obj.left = Math.max(obj.left, obj.left - obj.getBoundingRect().left);
          this.normalAttr.x = obj.left;
          this.normalAttr.y = obj.top;
        }
        // 下-右
        if (
          obj.getBoundingRect().top + obj.getBoundingRect().height >
            obj.canvas.height ||
          obj.getBoundingRect().left + obj.getBoundingRect().width >
            obj.canvas.width
        ) {
          obj.top = Math.min(
            obj.top,
            obj.canvas.height -
              obj.getBoundingRect().height +
              obj.top -
              obj.getBoundingRect().top
          );
          obj.left = Math.min(
            obj.left,
            obj.canvas.width -
              obj.getBoundingRect().width +
              obj.left -
              obj.getBoundingRect().left
          );
          this.normalAttr.x = obj.left;
          this.normalAttr.y = obj.top;
        }

**Comment by asturur** [comment]
Hi @joylord2018 ,  i speak italian and english.
I would ask you to post issue in english, or i can't understand you.
