### ISSUE TITLE
我尝试去绘制一条流动的线条效果，通过动画却无从下手

### ISSUE THREAD

**Issue by joylord2018** [fabricjs/fabric.js#6021]
![image](https://user-images.githubusercontent.com/37334673/70493593-338f2780-1b43-11ea-90e3-b89766b8b165.png)
类似于这种效果，因为没有类似reset循环的方式，我只能通过不断的clone线条小段的对象去流动，不断的生成和remove，也删掉了缓存，但是效果会卡顿，我想请教一下有没有更好的实现方式

**Comment by asturur** [comment]
Hi @joylord2018 , i speak italian and english.
I would ask you to post issue in english, or i can't understand you.
