### ISSUE TITLE
Can you provide a way to restrict objects to move within the canvas

### ISSUE THREAD

**Issue by joylord2018** [fabricjs/fabric.js#6024]
I tried to write my own to limit the movement of objects on the canvas. The first one is OK, but as soon as I rotate the objects, there will be problems

    let leftViewPort = c.viewportTransform[2] * obj.canvas.getZoom() +obj.width * obj.scaleX +
     c.viewportTransform[2];

     let topViewPort = c.viewportTransform[3] * obj.canvas.getZoom() + obj.height * obj.scaleY +
     c.viewportTransform[3];

    if (obj.left < 0) {
      obj.left = 0;
    } else if (obj.left > obj.canvas.width - leftViewPort) {
      obj.left = obj.canvas.width - leftViewPort;
    }

    if (obj.top < 0) {
      obj.top = 0;
    } else if (obj.top > obj.canvas.height - topViewPort) {
      obj.top = obj.canvas.height - topViewPort;
    }

The second is for rotation, but scaling the canvas is problematic

    if (
        obj.currentHeight > obj.canvas.height ||
        obj.currentWidth > obj.canvas.width
    ) {
        return;
    }
    obj.setCoords();
    if (obj.getBoundingRect().top < 0 || obj.getBoundingRect().left < 0) {
      obj.top = Math.max(obj.top, obj.top - obj.getBoundingRect().top);
      obj.left = Math.max(obj.left, obj.left - obj.getBoundingRect().left);
      this.normalAttr.x = obj.left;
      this.normalAttr.y = obj.top;
    }
    if (
      obj.getBoundingRect().top + obj.getBoundingRect().height >
        obj.canvas.height ||
      obj.getBoundingRect().left + obj.getBoundingRect().width >
        obj.canvas.width
    ) {
      obj.top = Math.min(
        obj.top,
        obj.canvas.height -
          obj.getBoundingRect().height +
          obj.top -
          obj.getBoundingRect().top
      );
      obj.left = Math.min(
        obj.left,
        obj.canvas.width -
          obj.getBoundingRect().width +
          obj.left -
          obj.getBoundingRect().left
      );
      this.normalAttr.x = obj.left;
      this.normalAttr.y = obj.top;
    }

**Comment by awehring** [comment]
Have you looked at Stackoverflow? There are a few solutions proposed:

https://stackoverflow.com/questions/22910496/move-object-within-canvas-boundary-limit

The last one from metamagikum looks good to me.

Generally I think Stackoverflow is the better place for questions like this. The issue tracker here is ment for reporting bugs.

**Comment by asturur** [comment]
Yes this is exactly a stackoverflow problem.
I'll close the issue since there are no action items for me.
Conversation can go on.

**Comment by RemmarQX** [comment]
Hi, I tried using the above codes but it works for me only partially, images keeps going out of canvas at the bottom left and upper right part and when dragged too far out, the image disappears. Why does that happen? Sorry, I'm new to this stuff.

**Comment by TimoA200** [comment]
I'm having the same issue as @RemmarQX that the image disappears when dragged too far out.

**Comment by lhotamir** [comment]
@TimoA200 Did you find any solution? I am struggling with the same problem

**Comment by asturur** [comment]
There are a couple of features on the pipeline, one of those is the page object.
As soon as i get there you may find a solution for that but not immediately.
In order to restrict object movements to an area, you need to setup a 'moving' event that check the position of the 4 main corners and avoid escaping a certain area.
You have to use getPositionByOrigin/setPositionByOrigin with the origin of the 4 main corners in order to understand where your corners are.

**Comment by lhotamir** [comment]
I have made progress already, calling the `getBoundingRect(true, true)` did the trick

**Comment by asturur** [comment]
On which fabric are you? didn't we remove the double booleans that were confusing?

**Comment by lhotamir** [comment]
Yeah, I am on version 5 unfortunately and upgrade would be complicated :\ But I got it working in the end.

Thank you for your help :)
