### ISSUE TITLE
Deserialization failed

### ISSUE THREAD

**Issue by joylord2018** [fabricjs/fabric.js#6025]
I create a subclass through createclass, which can be serialized. However, when I deserialize loadfromjson, an error (uncaught typeerror: Klass. Fromobject is not a function) is reported. The deserialization cannot succeed

**Comment by asturur** [comment]
We have many issues ( closed ) about serialization / deserialization of custom classes.

- verify the type property of the class is the same name of the class name.
- verify that `FromObject` is declared as a static method on the class ( look at Rect class )
- the deserialization needs to use the callback provided in the fromObject example.

**Comment by joylord2018** [comment]
thanks, I'll go on to the documents

**Comment by asturur** [comment]
inleave the issue open because i think a clarification in the docs is necessary.

**Comment by asturur** [comment]
added more docs!
