### ISSUE TITLE
Textbox can't  set height

### ISSUE THREAD

**Issue by joylord2018** [fabricjs/fabric.js#6026]
I created a textbox,when I wanted to set its height and lineheight, it didn't work.
I screenshot for this porblem, can you have any time to help me finding the question?
thanks.
![J0IXKQNOQF0XQ 7T $ H{3](https://user-images.githubusercontent.com/37334673/70693027-8dd0e980-1cf7-11ea-95eb-73d28eef90e2.png)

![YAL4~33021~RX 7S@YG(W](https://user-images.githubusercontent.com/37334673/70692972-7691fc00-1cf7-11ea-8913-dbd22d73538a.png)

**Comment by asturur** [comment]
Height is automatic, you can't set it.
You can set the lineHeight, using the set method, or clearing the cache manually.

textbox.set('lineHeight', number);
canvas.requestRenderAll();
