### ISSUE TITLE
Can I create fabric.Image from HEIC images?

### ISSUE THREAD

**Issue by rusucosmin** [fabricjs/fabric.js#6027]
I have an upload button where the user might possibly upload his HEIC photo generated by his iPhone. Can I use that image to display on the canvas? I tried to find some answers, and in the end, I think I will use a HEIC to JPEG converter such as https://github.com/introvertautist/heic2jpg, but I would like to know if there is an out-of-the-box solution from fabric.

**Comment by asturur** [comment]
No, fabric support drawables only, and support will evolve with browsers support.

You should convert the file on your own.
