### ISSUE TITLE
IE: Typing in textbox does not work after programmatically entering edit mode and selecting all text.

### ISSUE THREAD

**Issue by jsbakker** [fabricjs/fabric.js#6028]
## Version
3.2.0, master

## Test Case
https://jsfiddle.net/staeryatz/6kfo49d2/3/

## Information about environment
IE 11.805.17763.0
OR WebBrowser control in a Windows.Forms application

## Steps to reproduce
1. Click anywhere to place text
2. Start tying to change text

## Expected Behavior
Since we have entered editing and selected all text, when you start typing, the existing default text will be replaced as you type. This does work in Chrome, Edge and Safari.

## Actual Behavior
On IE or WebBrowser Windows.Forms control, nothing happens when you type. If you press any of the arrow keys before typing, you are able to add text, but this of course clears the selection and you are not able to delete the default text without manually selecting it first.

**Note**: I understand that IE is probably not a priority for bug fixing, but if anybody knows a workaround for this, please share, as I am stuck with using a WebBrowser control in a Windows application. I've tried many different variations, combinations and order of operations based on this jsfiddle, but none have worked.

**Comment by awehring** [comment]
For a different issue I found a work around. Maybe the information there helps you with your IE problem:
#5994

**Comment by asturur** [comment]
Yes i think setting focus manually on the hidden element should work.
I would try either adding a `textbox.hiddenTextArea.focus()` before the renderAll.

OR

i would put a setTimeout on the mouse down event to call the createText + endText.
The setTimeout would allow the event processing of IE to finish, and the internal focus of fabricJS would probably not be overridden.

Try and let us know.

Thanks @awehring

**Comment by jsbakker** [comment]
Thanks for the quick replies. I've tried `textbox.hiddenTextArea.focus()` in various places before, but it looks like putting it just before the renderAll() appears to work - with a caveat:

Any slight mouse move will cause the selection rendering to not render blue, although the typing does replace the pre-selected text as expected. Running in IE without suppressing errors, I will get this message:

```
Line: 80
Error: Unable to get property 'focus' of undefined or null reference
```
where line 80 points to `textbox.hiddenTextArea.focus()` in the debugger. I used setTimeout to set a delay, but the error message still comes in, just delayed. See https://jsfiddle.net/staeryatz/6kfo49d2/11/

Speaking of timing, I've at one point tried to do the `selectAll` and `focus` calls in a callback for `text:editing:entered` event, as to allow some time for the  `enterEditing` to be processed, but that did not work. See https://jsfiddle.net/staeryatz/6kfo49d2/18/

I've also tried doing the `enterEditing` and `focus` after `text:selection:changed` event, but also it is the same result.

**Comment by awehring** [comment]
I'm sorry, I think I can't help you any more.

Your jsfiddle runs perfectly in Firefox, Chrome and Edge. jsfiddle says, that it does not support Internet Explorer any more.

And - luckily - I dont need to support IE any longer in my project.   :-)
(Win7 goes out of support in January and Edge is prefered in Win10 - and switches over to Chromium soon).

**Comment by jsbakker** [comment]
@awehring no worries. Thanks for the reply, and thanks @asturur.

Given our Windows app uses IE WebBrowser with script errors suppressed, the v11 of the above jsfiddle appears to work as far as the user is concerned. The selection colour is minor.

**Comment by asturur** [comment]
The fabricJS events are sync, so processing on those won't change anything.

https://jsfiddle.net/L8qnkj56/

I have to try this on my windows machine tomorrow.
