### ISSUE TITLE
Unable to select line after resize

### ISSUE THREAD

**Issue by proman24** [fabricjs/fabric.js#6029]
## Version
3.5.1

## Test Case
http://jsfiddle.net/gm2406/5je92aLf/15/

## Steps to reproduce
- Draw a line using the Add line button.
- Try clicking on the line except for the point you started with.

## Expected Behavior
The Line should be selected

## Actual Behavior
The line is getting selected only when we click on the starting point
![issue_line](https://user-images.githubusercontent.com/18314265/70772057-5450ba80-1d99-11ea-8df7-22c3fa11de51.gif)

**Comment by asturur** [comment]
http://fabricjs.com/fabric-gotchas

Check if those helps, your problem has been discussed many items in the issues.
