### ISSUE TITLE
Text is Display Out of the Textbox 

### ISSUE THREAD

**Issue by sagarvibrant** [fabricjs/fabric.js#6030]
Text is Display Out of the Textbox when I'm Changed Fontstyle.

![text_Issue](https://user-images.githubusercontent.com/36664189/70778907-62a6d280-1da9-11ea-8038-bd464d5b9ee3.png)

Thanks.

**Comment by sagarvibrant** [comment]
It Resolved with using  `fabric.charWidthsCache = {};`

**Comment by asturur** [comment]
Just for your help:
- the right solution is to be sure the font is loaded before using it ( using a font loader or similar )
- there is a method to delete the charWidthsCache for that family only, so you do not kill all the caching of all the other fonts.
http://fabricjs.com/docs/fabric.util.html#.clearFabricFontCache

**Comment by sagarvibrant** [comment]
> Just for your help:
> 
> * the right solution is to be sure the font is loaded before using it ( using a font loader or similar )
> * there is a method to delete the charWidthsCache for that family only, so you do not kill all the caching of all the other fonts.
>   http://fabricjs.com/docs/fabric.util.html#.clearFabricFontCache

Thank you @asturur
