### ISSUE TITLE
IndexSizeError: The index is not in the allowed range.

### ISSUE THREAD

**Issue by sintanial** [fabricjs/fabric.js#6031]
## Version
3.5.0

## Information about environment
Os: Mac Os Catalina
Browser: Safari (only in safari)

Try to add video in canvas and receive error on Safari:

```javascript
let img = new fabric.Image(video, {
        objectCaching: true,
    });
    img.set({width: video.videoWidth, height: video.videoHeight});
    this.$canvas.backgroundColor = "#FFFFFF";
    this.$canvas.add(img);
```

It's worked perfect without errors on version 2.4.6 and below. 

But after version 2.6.0 and above error is reproduce with every video :(

**Comment by asturur** [comment]
we need a reproducible jsfiddle that we can open in safari. I have no catalina yet and i m not sure when i ll have it.

**Comment by BenjiRage** [comment]
I've just come across the same issue - receiving "IndexSizeError" whenever I try and add a video to the canvas using v3.6.3.

I've pinned it down to situations when a video element's width and height are not explicitly set. It appears to have been introduced in version 2.6.0 onwards. In 2.5.0 and below a video will load just fine without a width/height being set. Here's a JS Fiddle: 

https://jsfiddle.net/71yc4szr/1/

If you comment out lines 7 and 8 (ie: no width and height set) the video will fail to load with IndexSizeError

**Comment by asturur** [comment]
oh this can be because the video probably has no naturalWidth/ naturalHeight?
This is something we should document somewhere at least
