### ISSUE TITLE
canvas style with "touch-action:none"

### ISSUE THREAD

**Issue by Lyqxyz** [fabricjs/fabric.js#6034]
## Version
3.5.1

canvas style with "touch-action:none"

**Comment by asturur** [comment]
Hi @Lyqxyz, can you be more specific?

**Comment by asturur** [comment]
Hi @Lyqxyz, can you be more specific?

**Comment by Lyqxyz** [comment]
When I set the allowTouchScrolling property to true, without the expected effect, the parent element cannot scroll up and down. When I touch the canvas and canvas style with touchaction: none

**Comment by Lyqxyz** [comment]
> Hi @Lyqxyz, can you be more specific?

When I set the allowTouchScrolling property to true, without the expected effect, the parent element cannot scroll up and down. When I touch the canvas and canvas style with touchaction: none

**Comment by Lyqxyz** [comment]
@asturur

**Comment by asturur** [comment]
duplicate of #5903
