### ISSUE TITLE
How to set the distance between container and the text to be 0？·

### ISSUE THREAD

**Issue by wlxle** [fabricjs/fabric.js#6035]
I want to set thedistance between text border (red) And container border to be 0.

![image](https://user-images.githubusercontent.com/22492878/70864763-4a44dc80-1f90-11ea-85ee-f210a91d0b64.png)

**Comment by asturur** [comment]
we do not have a way to do so.
You can try to lower lineheight, but i m not sure it works.

This because we do not have a way to know where the text starts and finish.
Also the code leave space for possible ascendand and descendant part of the font ( h and g for example ).

**Comment by wlxle** [comment]
Is possible to set the left-side distance to be 0？

**Comment by asturur** [comment]
No, the api does not let you measure the text so stricly.
