### ISSUE TITLE
How can I add  border outside the textbox

### ISSUE THREAD

**Issue by joylord2018** [fabricjs/fabric.js#6038]
not the selection border, I try to use the Rect to pretent a border,but it too Inconvenient,when I change the textbox's height or something, I have to  Calculated altitude and change the rect, i want to  user the textbox to Splicing like table,so I need borders.I see the demo about 'Objects Bounding Rectangles',but it not very suitable.I was trying to use Group,but I need to select every texebox in row and column.

**Comment by asturur** [comment]
You can write a small helper method to stroke a rect around your object.
Example to come
