### ISSUE TITLE
Replace an object in FabricJS for undo/redo?

### ISSUE THREAD

**Issue by maniac0s** [fabricjs/fabric.js#6040]
I already asked this on StO but no answer so far.

I am looking for a way to replace an object in the canvas with object data from a history array. Please see the question on StO why I don't want to use JSON serialization or remove() + add() for that purpose.

https://stackoverflow.com/questions/59358805/replace-an-object-in-fabricjs

**Comment by awehring** [comment]
You got some hints at StackOverflow

**Comment by maniac0s** [comment]
Yeah but they don't help because I can't get insertAt to work. I can't take an object like returned from canvas.item(x) and put it into insertAt, it crashes the app with a type error "obj is undefined".

**Comment by asturur** [comment]
Canvas insertAt works. Probably the canvas.item(x) at that moment is undefined?

**Comment by asturur** [comment]
Anyway insertAt is the way to go, we can continue the discussion on stackOverflow or here, but not being anything to fix i'm closing the issue for now.
