### ISSUE TITLE
Resizing objects does not update their state?

### ISSUE THREAD

**Issue by keko950** [fabricjs/fabric.js#6041]
Hi,
I'm having some issues with scaling/resizing objects in Fabric. 
I have a canvas, where there are multiple rect object, i can drag and move them and its position get updated, so i can save it to my rect database. However, if i want to scale/resize them, this seems not to apply changes to the object, so if i have a 30x30 rect, i scale it to, 90x90 (or whatever), and then i check his properties, the width and height keep being 30. Is this supposed to work in that way? Or im messing up with something?

Thanks

**Comment by asturur** [comment]
It works that way, the rect gets a scaleX and scaleY property of 3, that multiplied by width gets you 90.

**Comment by keko950** [comment]
I figured myself the solution, so finally i made this:

    this.canvas.on({
      'object:modified': callbackModifying
    })
    this.canvas.renderAll();
  }
  onModify(obj): void {
    var newWidth = (Math.round(obj.target.getScaledWidth()))
    var newHeight = (Math.round(obj.target.getScaledHeight())) 

    if (obj.target.width !== newWidth) {
      obj.target.set({ width: newWidth, height: newHeight, scaleX: 1, scaleY: 1, });
    }
  }
