### ISSUE TITLE
find a problem about animate

### ISSUE THREAD

**Issue by joylord2018** [fabricjs/fabric.js#6043]
I read the docs,find the example about the animate,like this 'rect.animate('left', '+=100', { onChange: canvas.renderAll.bind(canvas) });', the second argument '+=100',I try this

         line.animate('angle', '+=1', {
               onChange: c.renderAll.bind(c)
        });
but it didn't work, when i set a specific value, it worked.

**Comment by asturur** [comment]
can you replicate in a small fiddle?
