### ISSUE TITLE
  How to customize borders and controls

### ISSUE THREAD

**Issue by Lyqxyz** [fabricjs/fabric.js#6045]
How to customize borders and controls，like this   http://tieba.baidu.com/photo/p?kw=web%E5%89%8D%E7%AB%AF%E5%BC%80%E5%8F%91&ie=utf-8&flux=1&tid=5906140657&pic_id=ad36bb0a304e251f5716008aaa86c9177e3e53e6&pn=1&fp=2&see_lz=1

**Comment by asturur** [comment]
Look for some custom library, this is not a fabricJS feature right now.
The custom control interface planne for 4.0 will allow something like that.
