### ISSUE TITLE
Got an error when packing with rollup.

### ISSUE THREAD

**Issue by HelloDennis** [fabricjs/fabric.js#6049]
**rollup version:** v1.27.14
**node version:** v10.15.3
**npm version:** 6.13.4
**system:** windows 10
**@types/fabric version:** 3.5.1
**fabric version:** 3.5.1

When packing fabric.js, I got this error:

> **[!] Error: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)**
> node_modules\canvas\build\Release\**canvas.node** (1:2)
> 1: MZ� �� � @ � � �!�L�!This program cannot be run in DOS mode.
> ^
> 2: $ �=�\j��\j��\j��:n��\j��:i��\j��:o�\j�<����\j��4i��\j��4n��\j��\j�u\j��4o��\j��:k��\j��\k�G\j�85c��\j�85j��\j�85���\j�85h��\j�Rich�\j�
> 0� p l P p �. @ .text h3 4 `.rdata �, P . 8 @ @.data
> � @ B
> �%I ���%�H ���%"I ���%�F ���%"G ���%�H ���%�F ���%�G ���%�G ���%�H ���%�F ���%*F ���%�F ���%�H ���%�G ���%"H ���%�F ���%�E ���%G ���%"G ���%G ���
> G ���%jG ���%JG ���%�F ���%�F ���%�F ���%�G ���%G ���%:H ���%rG ���%�E ���%RE ���%�G ���%:G ���%zG ���%�F ���%�G ���%�G ���%RE ���%JG ���%�E ���%F
> ���%�F ���%2E ���%jG ���%�F ���%�E ���%G ���%F ���%�F ���%RG ���%�E ���%"E ���%ZF ���%:E ���%�D ���%�F ���%�D ���%�F ���%�F ���%jG ���%�E ���%�F ��
> �%G ���%�D ���%�E ���%BF ���%�F ���%JE ���%
> 3: F ���%�D ���%�D ���%�E ���%�C ���%*E ���%�D ���%jD ���%�D ���%E ���%�E ���%:D ���%�E ���%�F ���%�C ���%�C ���%*D ���%BE ���%�C ���%�E ���%�C ���%
> rF ���%
> Error: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)

And my rollup config is:

```
var nodeResolve = require('rollup-plugin-node-resolve');
var commonjs = require('rollup-plugin-commonjs');
var uglify = require('rollup-plugin-uglify');
var json = require('rollup-plugin-json');

var common = require('./rollup.js');

var prod = process.env.NODE_ENV === 'production';

module.exports = {
  input: 'src/index.ts',
  output: {
    file: prod ? 'dist/index.aio.min.js' : 'dist/index.aio.js',
    format: 'umd',
    // When export and export default are not used at the same time, set legacy to true.
    // legacy: true,
    name: common.name,
    banner: common.banner,
  },
  plugins: [
    nodeResolve({
      mainFields: ['module', 'main'],
      extensions: ['.ts', '.js']
    }),
    commonjs({
      include: 'node_modules/**',
    }),
    json({
      include: [
        'node_modules/fabric/node_modules/jsdom/package.json',
        'node_modules/domexception/lib/legacy-error-codes.json',
        'node_modules/whatwg-encoding/**',
        'node_modules/canvas/package.json',
        'node_modules/tough-cookie/package.json',
        'node_modules/iconv-lite/encodings/tables/gb18030-ranges.json',
        'node_modules/ajv/lib/refs/json-schema-draft-06.json',
        'node_modules/mime-db/db.json',
        'node_modules/ajv/lib/refs/data.json',
        'node_modules/ajv/lib/refs/json-schema-draft-07.json'
      ]
    }),
    common.getCompiler(),
    (prod && uglify())
  ],
};
```

rollup.js
```
var typescript = require('rollup-plugin-typescript2');

var pkg = require('../package.json');

function getCompiler(opt) {
  opt = opt || {
    tsconfigOverride: { compilerOptions : { module: 'ES2015' } }
  }

  return typescript(opt);
}

exports.name = 'topo';
exports.getCompiler = getCompiler;
```

There is a loader for webpack here: https://github.com/Automattic/node-canvas/issues/867.
However, I don't know how to deal with it in rollup.

Thanks a lot!

**Comment by asturur** [comment]
Where are you planning to run your app? node or browser?

**Comment by HelloDennis** [comment]
> Where are you planning to run your app? node or browser?

browser

**Comment by asturur** [comment]
So you should NOT pack node-canvas in your package, you have to check how rollup allows you to skip packages.

**Comment by asturur** [comment]
There isn't a specific fabric issue here, i m going to close the issue since there are no action items for me.

**Comment by owen-m1** [comment]
@HelloDennis Did you find a solution for this?

**Comment by owen-m1** [comment]
Figured it out, add this to your rollup config:
```js
external: [
        "canvas-prebuilt",
        "canvas",
        "jsdom/lib/jsdom/utils",
        "jsdom/lib/jsdom/living/generated/utils",
        "jsdom",
        "xmldom",
    ],
```
Thanks to @nonnontrivial

**Comment by ZhengRui** [comment]
@owen-m1  with your config, I am able to use rollup to build my react library which depends on fabric, but when I try to import the library in a nextjs app,  it throws errors like `can't resolve net`, `can't resolve fs`, `can't resolve tls`, all related to `jsdom`. Have you encounter jsdom  related issues when you use the bundled code?

**Comment by ZhengRui** [comment]
Update:

thanks to this repo: https://github.com/jayantbh/react-multi-cropper/blob/main/rollup.config.js

my issue can be solved by just put fabric inside external, and put it and its type inside dependencies.
