### ISSUE TITLE
about canvas.getObjects()

### ISSUE THREAD

**Issue by joylord2018** [fabricjs/fabric.js#6052]
If i want to get  some objects,I use the 'canvas.getObjects(type:"")' and  traversing objects, can we have a function just like 'canvas.getObject(id:1) '  'canvas.getObject(name:"") ' ,get objects based on their properties

**Comment by asturur** [comment]
no that would be basically traversing the array with array.filter and a condition.

Not something we should provide since is a generic application need.

canvas.getObjects().filter(obj => obj.name === 'test');

**Comment by joylord2018** [comment]
Except traversing objects，how can i  find an object  exactly based on a property？

**Comment by asturur** [comment]
```
const objectsWithWidth50 = canvas.getObjects().filter(obj => obj.width === 50);
```

it will give you an array with all object with width 50.

or use find to get the first object with width 50.

**Comment by asturur** [comment]
I'm sorry, you asked `without traversing`.
Without traversing you can't.
There is not a map, so you can't access them straight.

**Comment by naonvl** [comment]
hey, igot an issue using `canvas.getObjects()` so far i always use `canvas._objects` but right now i'm trying to upload images from my PC, it is listed on `canvas._objects` but i cant access them like `canvas._objects[1]` or using `canvas._objects.map(x => console.log(x))` it doesn't contains my images, why is that? also after i upload my images, if i'm using `canvas.getObjects()` it's also doesn't contains my images

**Comment by asturur** [comment]
it depends how much after. If it is painted on the canvas, it is on the objects array ( or in a group ).
Loading an image is async, are you waiting for the load to end?
