### ISSUE TITLE
Changing Font Family to not system font "shifts" text object

### ISSUE THREAD

**Issue by Arsennikum** [fabricjs/fabric.js#6053]
## Version
3.5.1, 3.5.0, (checking some random versions from 2.2.2)
*Not reproducing in 1.7.22*

## Test Case
http://jsfiddle.net/arsennikum/Lg9dps5a/7/

## Information about environment
Browser: desktop Firefox, Android Firefox, Android Chrome, iOS Safari

## Steps to reproduce
Load some fonts (for example from google fonts)  
Create text with textAlign and originX center
Create button for change font to loaded font from standard system font
Click button several times

## Expected Behavior
text font change

## Actual Behavior
First time external font didn't display (text field are empty, font face observer didn't help - create issue #6054 for this)
Next time external font display, but **with shift**

**Comment by asturur** [comment]
Is still a font loading issue.
A proper font loader will help.
The first time the text input is white because the font is not ready and the canvas has probably nothing to draw.

I cannot experience any shift, the object stay put on its center since originX is set to 'center'

**Comment by asturur** [comment]
Please update the fiddle with a font loader in #6054 and let's keep just one issue.
