### ISSUE TITLE
External font family (google fonts) not display first time

### ISSUE THREAD

**Issue by Arsennikum** [fabricjs/fabric.js#6054]
## Version
3.5.1, 3.5.0, (checking some random versions from 1.7.20)

## Test Case
http://jsfiddle.net/arsennikum/Lg9dps5a/7/

## Information about environment
Browser: desktop Firefox, Android Firefox, Android Chrome, iOS Safari

## Steps to reproduce
Load some fonts (for example from google fonts)  
Create text with textAlign and originX center
Create button for change font to loaded font from standard system font
Click button several times

## Expected Behavior
text font change

## Actual Behavior
First time external font **did not display** (text field are empty, font face observer didn't help)
Next time external font display, but with shift (created issue for this #6053)

**Comment by asturur** [comment]
This has been discussed many time, please use a font loader before changing font.
If you tried and it did not help, update the fiddle with the font loader.

When is ready i ll reopen the issue.
