### ISSUE TITLE
Textbox problem

### ISSUE THREAD

**Issue by Lyqxyz** [fabricjs/fabric.js#6057]
Textbox "height is adjusted automatically based on the wrapping of lines." written on the official website has no effect. Still stretch

**Comment by asturur** [comment]
Can i ask you what you mean?
Textbox always take as much space as the wrapped textlines height.

**Comment by DivekJohns** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39296126/72142587-068c9980-33bb-11ea-8391-8ca0fedeb025.gif)

this is happening to me for the textbox, text grows weird when I scale the text box object any help
I

config of text box
{
   left: this.lastClickX,
    top: this.lastClickY,
    padding: 5,
    fontSize: 10,
    hasRotatingPoint: false,
    textAlign: 'left',
    minScaleLimit: 0.6,
    width: 100,
    height: 60,
    backgroundColor: '#FFFFA5',
}

**Comment by asturur** [comment]
Textbox is like any other object, but with 2 special controls, left and right that will change the width.
In the moment you use the corner one, you are scaling, stretching it.
So what you see is fine.
You can disable that conrners or try to change their behaviour using the scaling event.

Your best bet is to wait for the 4.0 release ( soon ) where controls are customizable.
