### ISSUE TITLE
Don't change active object z-index

### ISSUE THREAD

**Issue by lcswillems** [fabricjs/fabric.js#6060]
**Is your feature request related to a problem? Please describe.**
When I select an object, it is shown on top even if it was not on top.

[In this Codepen](https://codepen.io/farisk/pen/jGXoba), if I click on the rectangle, it is shown over the circle.

This is problematic because it may make it hard to correctly place the active object as it is hidding objects that were on top and could be used as reference.

**Describe the solution you'd like**
I would like an option to define how the z-index of the active object should be changed.

**Comment by asturur** [comment]
Please have a look at docs when starting with the library. Look for 'preserveObjectStack'

**Comment by lcswillems** [comment]
Thank you for your answer!

The problem with the doc is that it is poorly indexed in Google. So it is very hard to find what I want with Google searches. I have read the doc, but not every single method. I missed this one.

Thank you for your great work with this library, it is awesome!!

**Comment by melchiar** [comment]
I've added a new section on object order to the FAQ which covers the `preserveObjectStack` property since questions about object order are pretty common.

[how-can-i-change-the-order-of-objects-on-the-canvas](/fabricjs/fabric.js/wiki/FAQ#how-can-i-change-the-order-of-objects-on-the-canvas)

**Comment by lcswillems** [comment]
Great!! I think it was needed

**Comment by asturur** [comment]
i wish we had a centeral place for docs.
I basically never check the wiki pages, and i think the documentation is on fabricjs.com ( where also an ad banner is that provide 150$ month to fabricjs ).
Both wikis and the website have outdated pages, and the time to look for them and fix them is few.

**Comment by based64-eth** [comment]
the docs are complete garbage tbh

**Comment by asturur** [comment]
> the docs are complete garbage tbh

While true, your contribution isn't really useful.
Please consider not wasting time of people that receives notification in the emails for those kind of comments
