### ISSUE TITLE
Rect scaling read rect width and height attributes through canvas unchanged

### ISSUE THREAD

**Issue by HDONGDeveloper** [fabricjs/fabric.js#6061]
## Version
3.6.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Nodejs or browser?
Which browsers?

## Actual Behavior
![image](https://user-images.githubusercontent.com/31230864/71649052-79a46900-2d46-11ea-8336-dce555a87388.png)

**Comment by asturur** [comment]
that is how scaling work.
width and height are the base value, and then are multiplied by a scale factor.
