### ISSUE TITLE
loadFromJSON与customiseControls

### ISSUE THREAD

**Issue by qianweijian2017** [fabricjs/fabric.js#6063]
## Version
3.3.2

## Test Case 
 
在使用  loadFromJSON 后
之前设计的控制setControlsVisibility
fabric.Object.prototype.setControlsVisibility 样式会失效 ，自定义了图片与各方向的按钮显示/隐藏。

fabric.Object.prototype.setControlsVisibility({
          ml: false,
          mr: false,
          bl: false,
          tr: false,
          //  mb:false,
          mt: false,
          mtr: false,
          tl: false,
          mb: false,
          br: false
        });

 group.customiseCornerIcons(
        {
          settings: {
            borderColor: "#fff",
            borderWidth: 12,
            cornerSize: 25,
            padding: 20,
            // cornerBackgroundColor: 'red',
            cornerShape: "circle"
            // cornerPadding: 10,
          },
          tl: {
            icon: require("@/assets/utils/fabric/icons/remove.png"),
            settings: {
              cornerBackgroundColor: this.randomColor(),
              // cornerPadding: 10,
              cornerShape: "circle",
              cornerSize: 25
            }
          },
          mb: {
            icon: require("@/assets/utils/fabric/icons/rotate.png"),
            settings: {
              cornerShape: "circle",
              cornerBackgroundColor: this.randomColor(),
              //  cornerPadding: 10,
              cornerSize: 25
              // cornerPadding:[0,20,20,0]
            }
          },

          br: {
            icon: require("@/assets/utils/fabric/icons/resize.png"),
            settings: {
              cornerShape: "circle",
              cornerBackgroundColor: this.randomColor(),
              //  cornerPadding: 10,
              cornerSize: 25
            }
          }
          // bl: {
          //     icon: require('@/assets/utils/fabric/icons/resize.png'),
          //     settings: {
          //         cornerShape: 'circle',
          //         cornerBackgroundColor: this.randomColor(),
          //          cornerPadding: 10,
          //         cornerSize: 25,
          //     },
          // },
        },
        () => {
          // this.stage.renderAll();
        }
      );

**Comment by asturur** [comment]
hi @qianweijian2017  `customiseControls` is not a fabricjs functionality ( yet )
You are probably using some code that we cannot support here.
