### ISSUE TITLE
创建一个对象后，通过toDataURL,生成的图片会变得模糊

### ISSUE THREAD

**Issue by qianweijian2017** [fabricjs/fabric.js#6064]
this.stage.toDataURL({
        format: "jpeg", // jpeg或png
        quality: 1 ,// 图片质量，仅jpeg时可用

        left: this.bgPosition.left / 5,
        top: this.bgPosition.top / 5,
        height: this.bgPosition.height,
        width: this.bgPosition.width
        // multiplier:.2
      });

**Comment by asturur** [comment]
Please add a working snippet reproducting your problem and use english as comunication language.

Thanks.

**Comment by qianweijian2017** [comment]
Hello, in the process of using, I created an instance, and finally converted to base64 format using toDataURL, but I found that the picture became blurred, I don't know how to solve this problem?


> Please add a working snippet reproducting your problem and use english as comunication language.
> 
> Thanks.
Hello, in the process of using, I created an instance, and finally converted to base64 format using toDataURL, but I found that the picture became blurred, I don't know how to solve this problem?

**Comment by qianweijian2017** [comment]
> Please add a working snippet reproducting your problem and use english as comunication language.
> 
> Thanks.
Here's a simple implementation

step1:
 this.stage = new fabric.Canvas("main", {
        backgroundColor: "#060606",
        left: 0,
        top: 0,
        height: height,
        width: this.$refs.main.width
      });

step2:
 var dataURL = this.stage.toDataURL({
        format: "jpeg", // jpeg或png
        quality: 1, // 图片质量，仅jpeg时可用
        left:5 
        top: 5 
        height: 500,
        width: 500
   
      });

**Comment by asturur** [comment]
the first thing to do would be to screenshot this blurriness so that we can understand how much is blurry.
The first red flag for me is the top and left values, that are divided by 5.

If that left and top are a non integer and your canvas has png/jpeg over them, then they could be blurry because of pixel translations.

**Comment by qianweijian2017** [comment]
> the first thing to do would be to screenshot this blurriness so that we can understand how much is blurry.
> The first red flag for me is the top and left values, that are divided by 5.
> 
> If that left and top are a non integer and your canvas has png/jpeg over them, then they could be blurry because of pixel translations.

The left and upper are actually positions, and I think this should not affect the clarity generated.

**Comment by asturur** [comment]
well as i said, is not clear for the read what is the clarity problem without screens and working code and comparision with original.

Having a bitmap picture, and position it with an offset of 0.3 pixels over another grid of pixel will force every pixel to be mixed with the neighbour producing some kind of blurriness.

**Comment by asturur** [comment]
Text and paths are not affected by this, but images yes.
