### ISSUE TITLE
请问我如何才能像canvas中一样moveTo/lineTo/arc,在fabric.js中

### ISSUE THREAD

**Issue by aylizhiyuan** [fabricjs/fabric.js#6066]
我实在是找不到此类型的API,好像只能用path(‘M L z’)这种，难道没有别的办法吗？

**Comment by asturur** [comment]
hi @aylizhiyuan i would apreciate if you could edit in english.
Is very confusing for me to copy paste in google translator and hope to understand what you are looking for.

Also other people could be not willing to do so and post again the same question.

**Comment by aylizhiyuan** [comment]
I hope that I can draw a more complex figure according to the vertex coordinates of the figure, but there seems to be no continuous drawing method such as moveto, lineto and arc in fabric.js. I hope I can give some advice

**Comment by asturur** [comment]
you can create a svg path and import it. Is that enough?

**Comment by aylizhiyuan** [comment]
> you can create a svg path and import it. Is that enough?

thank you  , Oh, I see

**Comment by asturur** [comment]
```
new fabric.Path('M 0,0 L... A, S, C....', options);
```
