### ISSUE TITLE
Invalid getCurrentCharColor return type

### ISSUE THREAD

**Issue by lcswillems** [fabricjs/fabric.js#6067]
It is specified in the documentation that `getCurrentCharColor` returns a string (http://fabricjs.com/docs/fabric.IText.html#getCurrentCharColor) but it doesn't when text object has a fill gradient. In this case, it returns an object (the gradient).

Execute the following Fiddle and look at the console:
http://jsfiddle.net/x64cbmre/

**Comment by asturur** [comment]
It should be fixed specifying that it can be also a fabric.Gradient or fabric.Pattern. I wonder how the textbox would acually work then.

**Comment by asturur** [comment]
fixed
