### ISSUE TITLE
Convolution filter index edge conditions are off by one

### ISSUE THREAD

**Issue by rfinck** [fabricjs/fabric.js#6072]
## Version
3.6.0

## Test Case
Unit tests as well as a fix added here: https://github.com/rfinck/fabric.js/blob/fix-convolution-indexing/test/unit/image_filters.js#L703 
I can make a pull request but there are some workarounds I had to do to get the Node tests to run that may or may not be desirable in the project.

## Information about environment
Nodejs or browser? Both 
Which browsers? Any

## Steps to reproduce
See unit test linked above, which applies the following convolution filter to the following data:
```
var filter = new fabric.Image.filters.Convolute({
  matrix: [
    0, 1, 0,
    1, 2, 1,
    0, 1, 0
  ]
});
var pixelData = new Uint8Array([
  0, 0, 0, 255, 0, 0, 0, 255, 0, 0, 0, 255,
  0, 0, 0, 255, 1, 2, 3, 255, 0, 0, 0, 255,
  0, 0, 0, 255, 0, 0, 0, 255, 0, 0, 0, 255,
]);
```
## Expected Behavior
```
var expected = new Uint8Array([
  0, 0, 0, 255, 1, 2, 3, 255, 0, 0, 0, 255,
  1, 2, 3, 255, 2, 4, 6, 255, 1, 2, 3, 255,
  0, 0, 0, 255, 1, 2, 3, 255, 0, 0, 0, 255,
]);
```
## Actual Behavior
```
var actual = new Uint8Array([
  0, 0, 0, 255, 1, 2, 3, 255, 0, 0, 0, 255,
  1, 2, 3, 255, 2, 4, 6, 255, 0, 0, 0, 255,
  0, 0, 0, 255, 0, 0, 0, 255, 0, 0, 0, 255,
]);
```

**Comment by asturur** [comment]
Can you give more info?
the pixel data is 9 pixels, we need to know how they are organized. i suppose 3 by 3 and not 9 by 1 or 1 by 9.

Can you link to the actual fix?
I also wonder the difference between the webgl version and the js version.
Probably webgl is doing something automatic at the edges ( padding or mirroring ).

**Comment by rfinck** [comment]
@asturur In the example above, the pixels are 3x3.

There were actually two different issues
- the js version had a minor bug affecting only the pixels in the last column on the right. The fix for that is simple: https://github.com/fabricjs/fabric.js/compare/master...rfinck:fix-convolution-indexing?diff=split#diff-23afd339d9275c1e3d5675043230b731R276
- the webgl version did not iterate to the last index of either dimension of the _kernel_ when tested in _Node_, but this problem may not manifest in the browser. I initially wondered if it was an edge effect on the image as you suggest, but I ran the same tests with larger images to try to rule that out -- since they had the same result I reduced to the smallest version for simplicity. The fix for that is here: https://github.com/fabricjs/fabric.js/compare/master...rfinck:fix-convolution-indexing?diff=split#diff-23afd339d9275c1e3d5675043230b731R86

The biggest change in my branch is not these fixes but the attempt to write unit tests for the expected values using both the js and webgl versions.https://github.com/fabricjs/fabric.js/compare/master...rfinck:fix-convolution-indexing?diff=split#diff-bec54426b919d2026d81e3a765251399

**Comment by asturur** [comment]
i would like to see a PR for the fix only with the iteration fix for JS and another to talk about nodejs webgl test, i would like to know how they run under travis before thinking of adopting them.

**Comment by asturur** [comment]
is the `float to int` conversion in the shader fragment necessary?
I'm not a webgl expert and i had difficulties building the filter system, i may have done mistakes.

**Comment by rfinck** [comment]
> i would like to see a PR for the fix only with the iteration fix for JS and another to talk about nodejs webgl test, i would like to know how they run under travis before thinking of adopting them.

Got it, I will split them out.

> is the float to int conversion in the shader fragment necessary?

I believe it makes the shader fragment more consistent across different platforms, since without it I saw inconsistent results between Chrome and Node in your testem setup. I had originally noticed this because I built an erosion filter based on your convolution filter and was able to fix the issues I was having there by making this change.

**Comment by asturur** [comment]
the issue itself is fixed. We are missing webgl testing, but this issue can be closed.
