### ISSUE TITLE
How to add the created fabric.util.createclass JSON to the canvas

### ISSUE THREAD

**Issue by HDONGDeveloper** [fabricjs/fabric.js#6073]
![image](https://user-images.githubusercontent.com/31230864/71802583-0d549d00-3099-11ea-9cd4-76cd3deda005.png)
![image](https://user-images.githubusercontent.com/31230864/71802593-15144180-3099-11ea-913f-051d10cd0fcb.png)

**Comment by asturur** [comment]
@HDONGDeveloper  we need more clear question and issues.
This should not be an help `how to do this` place.
This is more to present wrong behaviour of the library or bugs and verify how to fix them.

I'll close the issue and reopen it when is more clear what is going on.
