### ISSUE TITLE
Object selection handlers don't get moved with the object when replacing it

### ISSUE THREAD

**Issue by maniac0s** [fabricjs/fabric.js#6075]
I try to implement an undo/redo function. For this I use canvas.insertAt() method to replace an object from a history list to an earlier state.

    const undoRedo = (action) => {
        urAction.current = true;
        console.log("Undo Redo action", action);
        console.log("Undo Redo urAction", urAction);
        
        if(action === "undo"){
            histPointer.current--;
        }
        else if (action === "redo") {
            histPointer.current++;
        }
        
        setHistPointerState(histPointer.current);
        canvas.insertAt(historyList[histPointer.current], historyList[histPointer.current].id, true);

        //historyList.pop();
        canvas.renderAll();
    }

That works so far however when the object that gets replaced is selected, the selection with the handles stays at the old spot remaining the old boundaries while the object "jumps" back to an older state. How can I update the selection handlers?

**Comment by asturur** [comment]
http://fabricjs.com/fabric-gotchas

**Comment by maniac0s** [comment]
I don't know how this solves my issue

**Comment by asturur** [comment]
you are using code that updates the object position but you are not updating the handles position. Is described in the first case, the setCoords one.

**Comment by maniac0s** [comment]
Yes I guessed as much and I tried that this way: Get the concerned object via it's id and call setCoords on it.

    const object = canvas.item(historyList[histPointer.current].id);
    object.setCoords();

I also tried it directly:

    canvas.item(historyList[histPointer.current].id).setCoords();

This changes nothing. Am I doing it wrong?

BTW .id is what I add to an object upon addition to the canvas, so that it knows at which a place in the hirachy it belongs.

            const objects = canvas.getObjects();
            e.target.id = objects.length - 1;
