### ISSUE TITLE
Hi, i want help on this shape

### ISSUE THREAD

**Issue by virkse** [fabricjs/fabric.js#6079]
Thanks in advance, i need the same shape like as on https://artpix3d.com/product/heart/
How i can do this?

**Comment by asturur** [comment]
Hi @virske i suggest you to look at docs for the fabric.Path element and clipPath property to cut pictures with that shape.

**Comment by virkse** [comment]
No @asturur , actually this is a full image hiding under a heart type shape. i have update the description.

**Comment by asturur** [comment]
I can't make this kind of support, this is more for stackoverflow where you can find more general help.
There is also written in the description of the issue template, if you need help with something open a stackoverflow question and in case post it here for visibility. But this is exactly what stackoverflow is made for.

Post a working snippet where you show what you have tried so far. ( on stackoverflow )

**Comment by virkse** [comment]
Sure thanks
