### ISSUE TITLE
I want to replace an image that has been rendered on the canvas module with a new image path

### ISSUE THREAD

**Issue by HDONGDeveloper** [fabricjs/fabric.js#6080]

**Comment by asturur** [comment]
Those are application questions.
This is something that has to do with the current application you are developing and not the library itself.

In addition you are not showing a fiddle of what you tried so far.

The fact that i m softer than stackoverflow moderators, does not mean that here you should make questions in a `lazy` way ( pardon me the use of the word lazy ).

If you have a question, open it on stackoverflow and then link it in this issue.
I'll reopen the issue then
