### ISSUE TITLE
transparent background for polygons/rects?

### ISSUE THREAD

**Issue by keko950** [fabricjs/fabric.js#6081]
Hi!
Is it possible to make the background of a rect or a polygon transparent? I want to create a shape over a image, like a convex hull, so i need to see what is behind the convex hull, but i didn't manage to found a way to make the background transparent.

**Comment by awehring** [comment]
Easy.

Set `fill` property to a transparent color, like `"rgba(255,255,255,0)"`

**Comment by asturur** [comment]
whatever works with css strings for plain colors, should work here.
so `Object.set('fill', 'transparent')` should work too.

**Comment by awehring** [comment]
"transparent"does work, and even an empty string:

`Object.set('fill', '')`

**Comment by keko950** [comment]
Nice, thanks for the fast answers!

**Comment by asturur** [comment]
Happy to help, but please this is something you can find on basic docs.
I know that docs aren't perfect on fabricjs.com but i have the feeling you could have found this out easily.

http://fabricjs.com/docs/fabric.Object.html#fill

**Comment by keko950** [comment]
Yeah, dunno why but transparent seems to not work for me, so im using rgba(255,255,255,0), thats why i asked. Thanks and sorry for the inconvenience!

**Comment by minhncud** [comment]
Sorry i want to open this again, i'm not sure that this is my issue but can you help me please?

my rect's fill 'transparent' or 'rgba(255,255,255,0)' or ' ' not work :(
i tried:
crop_rect_area.opacity = 0;
crop_rect_area.set('fill', ' ');
 // crop_rect_area.set('fill', 'transparent');
 // crop_rect_area.set('fill', 'rgba(255,255,255,0)');
 // crop_rect_area.fill = 'rgba(255,255,255,0)';// 'transparent';// ' ';
 canvas.clipPath = crop_rect_area;
 var _i = new Image();
 _i.src = canvas.toDataURL('jpg', 1);
...

![fabricjs_crop](https://user-images.githubusercontent.com/36953180/82458995-98cb4980-9ae1-11ea-90b4-7cb31b3b2fc7.jpg)

---
this is original rectancle.
selectionRect = new fabric.Rect({
            fill: 'rgba(0,0,0,0.3)',
            originX: 'left',
            originY: 'top',
            stroke: 'black',
            opacity: 1,
            width: width,
            height: width / ratio,
            hasRotatingPoint: false,
            transparentCorners: false,
            cornerColor: 'white',
            cornerStrokeColor: 'black',
            borderColor: 'black',
            cornerSize: 6,
            padding: 0,
            cornerStyle: 'circle',
            borderDashArray: [9, 9],
            borderScaleFactor: 1.3,
            id: 'crop_rect_id'
        });
