### ISSUE TITLE
Touch gesture when finger zoom in, It makes the canvas zoom out

### ISSUE THREAD

**Issue by virkse** [fabricjs/fabric.js#6083]
I using the below code to make zoom in/out.
When my two fingers go wide then code makes the canvas zoom out and picture go very very small in size even it disappear. :)

```
canvas.on({
    'touch:gesture': function(e) {
        if (e.e.touches && e.e.touches.length == 2) {
            pausePanning = true;
            var point = new fabric.Point(e.self.x, e.self.y);
            if (e.self.state == "start") {
                zoomStartScale = canvas.getZoom();
            }
            var delta = zoomStartScale * e.self.scale;
            self.canvas.zoomToPoint(point, delta);
            pausePanning = false;
        }
    }
})

```

**Comment by virkse** [comment]
i realize that after this code is not executing and photo jump to smaller 
if (e.self.state == "start") {
   zoomStartScale = canvas.getZoom();
}

anybody can help me?

**Comment by asturur** [comment]
i can't.
I m so disconnected from that gesture code that i m not even willing to fix it.
I made a new integration with hammerJS and as soon as possible i m going to make a tutorial to integrate it.
