### ISSUE TITLE
Event listener always returns "mouseup" or nothing

### ISSUE THREAD

**Issue by maniac0s** [fabricjs/fabric.js#6084]
I want to decide if an object was added, modified or removed. For that purpose I added three event listeners

        canvas.on("object:added", handleEvent);
        canvas.on("object:removed", handleEvent);
        canvas.on('object:modified', handleEvent);

But when I print the event, it always says "mouseup":

    function handleEvent(e) {
            if(!e) {
                return;
            }
            console.log("event caught:", e.e);

On adding an object:

>event caught: undefined

On moving an object:

>event caught: mouseup { target: canvas.upper-canvas, buttons: 0, clientX: 691, clientY: 459, layerX: 429, layerY: 439 }

On scaling an object:

>event caught: mouseup { target: canvas.upper-canvas, buttons: 0, clientX: 458, clientY: 279, layerX: 196, layerY: 259 }

How can I decide what event actually fired?

**Comment by asturur** [comment]
well fabricJS events are not 1:1 bound to mouse events, some events, like object added have no mouse event connected, that is fine.

You can either attach different handlers or wrap the handlers in something that let you know what event handler is.

```js
var genericEventHandler = function(options) { ... my code ...};
var eventHandlerDecorator = function(eventName, handler) { 
  return function(options) {
    options.eventName = eventName;
    return handler(options);
  }
};
addedEventHandler = eventHandlerDecorator('added', genericEventHandler);
```

is up to you.
