### ISSUE TITLE
Inconsistent error on loadSVGfromString

### ISSUE THREAD

**Issue by Sashkan** [fabricjs/fabric.js#6085]
## Version
3.6.0

## Test Case
Sorry, don't have one

## Information about environment
Nodejs or browser?
browser, on Chrome (latest)
Which browsers?

## Steps to reproduce
load an SVG file with axios, get the text, and use this text in the loadSVGfromString method.

## Expected Behavior
Load the SVG properly

## Actual Behavior
Some CORS error results in a `Cannot get property "naturalWidth" of undefined.`

## Use case informations

So, here is the code i'm using to fetch and load my SVG.

      const url = [url of my svg]
      
      axios(url).then(response => fabric.loadSVGFromString(
        replaceDesignVersions(response.data),
        (objects, options) => {
          if (objects && objects.length > 0) {
            objects.forEach((design, index) => {

              this.canvas.add(design)
              design.bringToFront()
              this.canvas.renderAll()
            })
          }
        },
        null,
        { crossOrigin: 'anonymous' },
      ))

And here is the error it raises :
![image](https://user-images.githubusercontent.com/6276267/72140645-79811a80-3391-11ea-946e-3cab022da773.png)

![image](https://user-images.githubusercontent.com/6276267/72140591-62422d00-3391-11ea-8e96-d82d5623108f.png)

Now, the funny thing is, if I clear the cached image in my browser, the error goes away, for a time at least.

I tried to dig a bit inside of fabric code/documentation, and didn't find anything. I made sure to set crossOrigin to `anonymous`.

Is it possible that it has anything to do with image caching ?

**Comment by asturur** [comment]
Looks like that your image has no cors for some weird reason.
Did you try with another browser?
The problem is that you are actually not able to download that URL from s3 due to cors issues.

Nothing specific from fabric.

**Comment by Sashkan** [comment]
I finally found (after 5 weeks) the source of the problem. If anyone ever stumbles upon this problem, make sure than you are not loading these images somewhere else in your page.

basically, I was displaying a list of all added images, with previews. My browser fetched these ones before, resulting in conflicts between the versions of these images. 

The images in the list were loaded first, and therefore cached, and this cached version was probably used by fabric, but since they did not have the same origin, this would eventually raise a CORS issue.

So, to solve this, I created a helper that modify the URL of these images, simply adding a key at the end, so that it would always fetch a non-cached version of it.

**Comment by asturur** [comment]
oh you are right! it happened to me too, and i already removed it from my mind.
What i did was adding the same crossorigin attribute to the img elements in the list that where loading those images.
So i got both with the right attribute.
In that case you can still use the cache, without having to download them twice.

**Comment by Sashkan** [comment]
@asturur you mean, you set the `crossorigin` attribute of your `img` tags to 'anonymous' ?

**Comment by asturur** [comment]
yes
