### ISSUE TITLE
Freedrawing with patternbrush in different shapes.

### ISSUE THREAD

**Issue by anb10991** [fabricjs/fabric.js#6093]
Right now, Fabric.js supports freedrawing with PatternBrush.
I know it supports various modes like vline, spray, diamond and even texture.
The demo [here](http://fabricjs.com/freedrawing) is really helpful.

Now, when we draw using PatternBrush, it creates a path and then applies pattern to its path. Path supports strokeWidth, strokeLineCap, strokeLineJoin parameters.
strokeLineCap can be either 'butt', 'round' and 'square' and strokeLineJoin can be either 'devil', 'miter' and 'round'.
Therefore, the brush shape is just either Circle or Reactangle with radius or width of strokeWidth.

However, what I want to do is to apply some specific brush shape, not just circle or rectangle.
For example, I want a diamond shaped brush with specific pattern.

Can you help me with this?

**Comment by asturur** [comment]
Hi @anb10991 you have to make your own brush.

Is unclear from your description how the brush should behave.
If a simple path with the properties you mentioned is not enough, you have to create a brush that will draw a shape every time it moves, creating a sensation of continuity, but it won't be like a path.

You can create a mix between a spray brush and a pencilbrush?
