### ISSUE TITLE
renderAll() should have a .done() callback

### ISSUE THREAD

**Issue by GreenFootballs** [fabricjs/fabric.js#6095]
In a project I'm working on, it would be really useful to have a function run after all the rendering is complete in a renderAll() operation, either by wrapping it in a Promise or by adding a parameter for a callback function.

I combed through the docs and it seems there's no existing callback for renderAll(), so I'm filing this under feature request. Or maybe someone can suggest an alternative way to handle this?

**Comment by asturur** [comment]
did you check for the 'after:render' event? do doc say nothing about it? if not should be addressed.

**Comment by awehring** [comment]
The `after:render` event is only mentioned briefly at the `Observable.on()` and `Observable.off()` methods:
http://fabricjs.com/docs/fabric.Observable.html#off

At least the search in the documentation does not bring it up elsewhere.

**Comment by GreenFootballs** [comment]
OK, I've been investigating the after:render event but still having problems.

Maybe if I explain exactly what I'm trying to do, someone could suggest an approach.

I have an app that allows a user to apply styles to words in a Textbox, and it works well, except when the font size is increased. My code adds the Textbox to the canvas, then checks its height and if the height exceeds the current canvas height, it resizes the canvas to fit the text. This works well normally, but if the user has increased the font size of a word (or words), the bounding rectangle of the overall Textbox does not reflect the added size until after the rendering is complete.

So I was hoping to be able to call this resizing function after all rendering is done, then re-render the canvas to fit the new Textbox height.

The problem with using the after:render event to do this is that I can't call renderAll() from within that event or it goes into an infinite loop and exhausts the call stack.

So this doesn't seem to be a workable solution, unless there's some way to re-render the canvas from within that event. If this description is clear, can anyone suggest a method to achieve this?

**Comment by asturur** [comment]
So you want to know before rendering the resulting size so you adapt the canvas.

How does the user is changing the text properties?

in that code, all the variation of it, add an event that will let you know the size of new the textbox.

Look in textbox or itext initialize function to understand which one to call.

I do not have to look it now, i ll check later if there are unwanted side effects but i do not think so.

**Comment by GreenFootballs** [comment]
I'm not sure what you mean - can you explain a bit more?

**Comment by GreenFootballs** [comment]
One other question while I'm here - is there a limit on the fontSize property? If I try to set it larger than 256, nothing gets drawn even though the canvas is large enough.

**Comment by asturur** [comment]
After your user has modified the textbox in some way, you can run something like:

```
myText.initDimensions();
```

after that function has done its job, you can check

```
var dim = myText._getTransformedDimensions();
```

dim.x and dim.y will have the final width and height of the textbox.

This function would be called by the render function anyway, but you are calling it before to read the values.

At that point you can resize your canvas.

**Comment by asturur** [comment]
Regarding font size, no there should not be a limit, i have seen rendering big fonts, it depends on your OS and on the browser or font.
For example there was a long standing bug for Emoji, you could not render that much big.

If you think the font size is a bug, open a fiddle that demonstrates it and post it in a separate issue.

**Comment by GreenFootballs** [comment]
Interesting, thanks for the replies. I'll give those methods a try right away.

**Comment by GreenFootballs** [comment]
Excellent! This works perfectly. Thanks again.

**Comment by GreenFootballs** [comment]
Just for the record, all I had to do was replace this code:

`textBox.getBoundingRect()`

with:

`textBox.initDimensions()
let { x: width, y: height } = textBox._getTransformedDimensions()`

The object destructuring expression gives me 'width' and 'height' variables.

**Comment by awehring** [comment]
@asturur:
Shouldn't this issue be left open and labeled as "docs"?
 
I think the `before:render` and `after:render` events sould be added to the documentation for the Canvas object. See my post above (3rd  in this thread).
I was surprised that they exist.

**Comment by asturur** [comment]
yes i think you are right.
I m publishing some changes now ill do it.
