### ISSUE TITLE
Can't fork the base Jsfiddle

### ISSUE THREAD

**Issue by lcswillems** [fabricjs/fabric.js#6096]
I can't fork the Jsfiddle that is given in the bug template, i.e. this fiddle: http://jsfiddle.net/fabricjs/Da7SP/

I tried on Chrome and Safari. Everytime I want to submit a bug, I need to recreate a new Jsfiddle.

## Version
3.6.0

## Information about environment
Nodejs or browser? Browser
Which browsers? Chrome and Safari

**Comment by asturur** [comment]
i m not sure why, but you can still create a new fiddle, make it public, and open a pr with the changes in the file ISSUE_TEMPLATE and add a link to codepen too for example.

that would be an help!
