### ISSUE TITLE
Gradient not correct when x1 = x2 or y1 = y2

### ISSUE THREAD

**Issue by lcswillems** [fabricjs/fabric.js#6097]
### For rect

This code is not working (in Chrome / Safari, [jsfiddle](https://jsfiddle.net/bo6gf014/2/)):

```
const object = new fabric.Rect({
  width: 100,
  height: 100
});
object.setGradient('fill', {
  x1: 0,
  y1: 0,
  x2: 0,
  y2: 0,
  colorStops: {0: 'red', 1: 'black'}
})
```

### For text

Weirdly, the previous code is working for Text, but only in Chrome, **not in Safari** ([jsfiddle](https://jsfiddle.net/bo6gf014/3/)):

```
var canvas = window._canvas = new fabric.Canvas('c');

const object = new fabric.Text('hi');
object.setGradient('fill', {
  x1: 0,
  y1: 0,
  x2: 0,
  y2: 0,
  colorStops: {0: 'red', 1: 'black'}
})
canvas.add(object)
```

**Comment by asturur** [comment]
i do not think a gradient with 0 dimensions should make sense.

Apparently, after checking, it does not.
https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-createlineargradient

The specs say that  in this case the gradient should paint nothing.
