### ISSUE TITLE
Problem with clipPath on a video

### ISSUE THREAD

**Issue by flexeo** [fabricjs/fabric.js#6099]
The video is not played correctly when a clipPath is attached to the object.

The video updates the frames only when you resize the object.

Here is a live example: http://www.myspot.fr/fabricjs/test.html

```
var canvas = new fabric.Canvas('canvas');
var videoEl = document.getElementById('video');

var clipText = new fabric.Text('My Custom Text', { 
	left: 'center',
	top: 'center', 
	fontSize: 40,
});
  
var video = new fabric.Image(videoEl, {
	left: 10,
	top: 10,
	angle: 0,
	originX: 0,
	originY: 0,
	objectCaching: false,
	clipPath: clipText,
	backgroundColor: '#ff0000'
});

canvas.add(video);
video.getElement().play();

fabric.util.requestAnimFrame(function render() {
  canvas.renderAll();
  fabric.util.requestAnimFrame(render);
});
```

**Comment by asturur** [comment]
Videos are not supported out of the box right now.

The video with clipPath get cached, you have to invalidate the cache each frame.

please look here:
http://fabricjs.com/fabric-object-caching
