### ISSUE TITLE
Showing lag in IFP with 2gb ram while using freedrawing.

### ISSUE THREAD

**Issue by dmosyash** [fabricjs/fabric.js#6101]
Hello there,
I have developed an application for an interactive whiteboard. Free drawing is the basic functionality of it. It works perfectly in good config machines. But when I tested it on an android IFP(Interactive Flat Panel) with 2gb ram, it shows a significant performance lag. So I tested the performance in this demo
 http://fabricjs.com/freedrawing . Here also I see the lag, which concludes that basic freedrawing of fabric is not performing well in low config systems. My question is: Can we do some setting change or set some flags to make the freedrawing faster in low-config machines.

**Comment by asturur** [comment]
Which are the specs of those panels? 2gbs is not the limit here, but cpu and pixel number are.
