### ISSUE TITLE
Gestures(zoom, rotate) not working in ionic 4

### ISSUE THREAD

**Issue by maxakash** [fabricjs/fabric.js#6106]
I am using fabric js library inside my Ionic 4 project. I am using fabricjs library with gestures enabled.
But still i am not able to use gestures such as zoom or rotate.
Please help me to implement gestures on Ionic 4

**Comment by asturur** [comment]
If they work outside ionic 4, is not something we can help with.
We are reworking the gesture module anyway to be external to fabricjs.
