### ISSUE TITLE
Object Bounding Box Doesn't Update

### ISSUE THREAD

**Issue by lorkel** [fabricjs/fabric.js#6113]
## Version
3.6.1

## Test Case
https://jsfiddle.net/lorkel/70wnb32h/

## Information about environment
Browser, tested in Chrome and Firefox

## Steps to reproduce
1) Click anywhere in grid
2) Type Command/Control + A to select all, see the correct bounding box/outline for all objects
3) Click on grid to deselect
4) Mousewheel to zoom in or out
5) Command/Control + A to select again, it shows the old bounding area for all objects

## Expected Behavior
Bounding box should be updated to reflect new zoom level.

## Actual Behavior
It remains the initial load bounding box regardless of zoom level. This occurs with both canvas.zoomToPoint() and canvas.viewportTransform() functions, even after re-rendering all and calculating offset.

Initial bounding box (correct):
![Screen Shot 2020-01-22 at 12 58 38 AM](https://user-images.githubusercontent.com/6165552/72879740-5cfab180-3cb2-11ea-890a-adb49ba1e1a6.png)

Zoomed bounding box, still showing original (incorrect):
![Screen Shot 2020-01-22 at 12 58 46 AM](https://user-images.githubusercontent.com/6165552/72879753-66841980-3cb2-11ea-87cf-b871fd10267a.png)

**Comment by asturur** [comment]
hi @lorkel, the issue is in your active selection code.

As you can see here in this not so great demo:

https://jsfiddle.net/b4f2koaL/
