### ISSUE TITLE
Scaling equally when dragging from any corner

### ISSUE THREAD

**Issue by chiragdoctor** [fabricjs/fabric.js#6119]
**Is your feature request related to a problem? Please describe.**
At the moment when we are scaling from edge corners like `tr`, `tl`, `br`, `bl` we perform a `scale` action. And when we drag from middle corners like `mt`, mb, `ml`, `mr` it performs either `scaleX` or `scaleY` action.  

**Describe the solution you'd like**
We want to perform `scale` action when any on the corner is dragged for scaling (like it does for edge corners).  When the user clicks `shiftKey` we want to do `free scaling` or `scaleX` or `scaleY`, which should be customisable option. 

We can override the `action` and `originX` and `originY` property in the `transform` object when `before:transform` or `object:scaling` has been fired. This helps us to achieve the behaviour we want.     

The problem occurs when when we are scaling middle corner and overriding them with `action=scale`. It tries to run the logic to `_scaleObjectEqually`. In this method it tries to compute  the new scaling values for `scaleX` and `scaleY` of the `target` object and set's them. But while this happens it creates a jitter (randomly scale up / down) the object as we get inappropriate scaling values.     

**Describe alternatives you've considered**
The approach we have taken to fix this problem is we are overriding the private method `_scaleObjectEqually` with some custom logic bellow. 

```
const nativeScaleObjectEqually = fabric.Canvas.prototype._scaleObjectEqually;

const scaleObjectEqually = (localMouse, target, transform, _dim) => {
       // Adding this custom logic to detect corners and updating the localMouse position to get 
      // appropriate scaling so that we don't get jitter.  
	if (transform.corner === "mr" || transform.corner === "ml") {
		localMouse.y = _dim.y;
	} else if (transform.corner === "mt"|| transform.corner === "mb") {
		localMouse.x = _dim.x;
	}
	return nativeScaleObjectEqually(localMouse, target, transform, _dim);
};
```

**Additional context**
An example of my description is in the bellow fiddler link 
https://jsfiddle.net/chiragdoctor/dakfcxsn/440/

Please add this feature so that we can stay upto date with the farbic.js library and remove the overriding of the private method.

**Comment by asturur** [comment]
you should look at the new api currently in beta to achieve this, i can try to throw an example

**Comment by chiragdoctor** [comment]
Hi @asturur, I will be great if you could provide us with an example.  Thanks.

**Comment by asturur** [comment]
trying to build some, i m very busy with actual work
