### ISSUE TITLE
fabric.Image().toDataURL returns a blurred image

### ISSUE THREAD

**Issue by danielocdh** [fabricjs/fabric.js#6122]
## Version
3.6.1

## Test Case
https://jsfiddle.net/f8Ldue9o/

## Information about environment
Nodejs or browser?
browser
Which browsers?
Windows 10: Chrome, Firefox, Opera, Edge, IE

## Steps to reproduce
* Create a fabric.Image object with source having odd dimensions
* Use img.toDataURL() to export it

## Expected Behavior
Get the exact same image as the original with the same dimensions

## Actual Behavior
The image is blurred and dimensions on a few images are different

## Details
toDataURL method in Image is using the toCanvasElement method which seems to be the problem. Inside toCanvasElement method there is a call to setPositionByOrigin:
```
this.setPositionByOrigin(new fabric.Point(canvas.width / 2, canvas.height / 2), 'center', 'center');
```
My use case is very limited but I got the correct result by changing that line to this:
```
this.setPositionByOrigin(new fabric.Point(0, 0), 'left', 'top');
```

**Comment by asturur** [comment]
i would not expect it to blur out using center,center.
it should center the image on 49.5  , 49.5 in the canvas, but then drawing back for 49.5 pixels going back to 0.
Unless there is some unexpected rounding around the code that should not happen.

**Comment by asturur** [comment]
there is some weird code i added, and i think i did wrong.
https://github.com/fabricjs/fabric.js/blob/master/src/shapes/object.class.js#L1736
I m adding one pixel if the object has an odd number of pixels, and that is just wrong.
I wonder why i added that, but seems wrong

**Comment by danielocdh** [comment]
> there is some weird code i added, and i think i did wrong.
> https://github.com/fabricjs/fabric.js/blob/master/src/shapes/object.class.js#L1736
> I m adding one pixel if the object has an odd number of pixels, and that is just wrong.
> I wonder why i added that, but seems wrong

missed that, weird indeed

**Comment by asturur** [comment]
I think the point was to avoid canvas with non integer number of pixels, but that should be done with `% 1`

Looking at this now, should be a quick fix.

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/pull/6131

This will address the issue.
