### ISSUE TITLE
Object jumps to the side and can not be selected anymore when changing strokeWidth

### ISSUE THREAD

**Issue by maniac0s** [fabricjs/fabric.js#6123]
When I try to set strokeWidth on an object, the object changes stroke but also jumps to the far right edge half out of the canvas and I can not click it anymore.

    const setStrokeWidth = (e) => {
        console.log(e.target.value);
        context.the_canvas.getActiveObject().set("strokeWidth", e.target.value);
        context.the_canvas.requestRenderAll();
        setStroke(e.target.value);
    }

Screenshot
[https://file.io/fxBrU2]

**Comment by maniac0s** [comment]
Ok, It seems that's because of the type. Input field returns a string but strokeWidth acts up when setting to an integer that's in a string.

Solution: 

    context.the_canvas.getActiveObject().set("strokeWidth", parseInt(e.target.value));

**Comment by asturur** [comment]
in the docs is specified that the requested type is a number.

**Comment by maniac0s** [comment]
Yeah but that doesn't explain why it jumps around and becomes unselective after passing a string. Thought that would be interesting because it's unexpected behaviour.

**Comment by asturur** [comment]
Those values get passed down to a native canvas api that expects number. And the browser will misbehave with strings.
