### ISSUE TITLE
How to display another canvas without zoom in fabricjs

### ISSUE THREAD

**Issue by VinAr22** [fabricjs/fabric.js#6126]
Hi! At first, thank you for your great library! 
In short, I am developing a project in which there are two canvases: a canvas that supports zoom and drawing, a second canvas - a duplicate of the first canvas, which should display a general view without zoom. Unfortunately, I do not understand how to implement this, since the second canvas also displays a picture with a zoom. Please, help 

Here is a small example of what I have:
https://codepen.io/vinar22/pen/XWJLrwv

Also stackoverflow question:
https://stackoverflow.com/questions/59989597/how-to-display-another-canvas-without-zoom-in-fabricjs

Thank you again

**Comment by awehring** [comment]
The issue tracker here is for posting bugs, not for getting help. Stackoverflow is made for this.

As I see, you already got help there.

**Comment by VinAr22** [comment]
Unfortunately, this solution have bad perfomance. Maybe you know much better way? Thank you again

**Comment by asturur** [comment]
i can try to answer there, maybe we can make a demo from it?
