### ISSUE TITLE
Add objects to fabric.js contextTop 

### ISSUE THREAD

**Issue by 20y** [fabricjs/fabric.js#6128]
Trying to draw objects on fabric.js `contextTop` ( to prevent selection / z-index, and make something like rulers / scrollbars at the top of canvas) but after `mouse:wheel` i see strange **stack effect** with my drawn object. But after 'selection' event, `contextTop` clears and all works fine. Can't understand why `mouse:wheel` and `after:render` works so strange

## Version

3.6.1

## Test Case

https://jsfiddle.net/917xp26g/

## Steps to reproduce

mousewheel canvas and see how "line" at the right of canvas 'stacks', when select something on canvas,  "line" becomes normal

**Comment by 20y** [comment]
Found solution, just add `clearContext` method inside `before:render` in my case

**Comment by asturur** [comment]
there is currently NO way to do custom drawing con contextTop.
contextTop is used by fabric in unpredictable way.

For preventing selection and z-index things there is the overlay itself, that can also be unaffected by zoom if you want.

**Comment by 20y** [comment]
@asturur which "overlay" do you mean?

**Comment by asturur** [comment]
canvas.overlayImage = anyFabricObjectOrGrup;
