### ISSUE TITLE
Version 4 changes transformations

### ISSUE THREAD

**Issue by Harmageddon** [fabricjs/fabric.js#6129]
## Version
4.0 beta

## Test Case
https://jsfiddle.net/Harmageddon/7fb2dnys/2/
This test case is based on the [transformations tutorial](http://fabricjs.com/using-transformations).

## Information about environment
Firefox 72.0.2

## Steps to reproduce
1. Click the "Bind minion to boss" button.
2. Move the boss around.
3. Rotate (fast and slowly) the boss.
4. Move it again.

## Expected Behavior
The minion (line) should always be at the same position relative to the boss (red rectangle).

## Actual Behavior
For movement, it seems to stay at the correct position. For rotations, especially fast ones, it sometimes hops some pixels away. When moving again, the update handler is triggered again, and the line is positioned correctly. 
I assume that the transformation matrix is somehow slightly off during rotations. I could track this behavior down to commit c43e1339 where the controls have been changed for v4. This is an edge case, but maybe you still have an idea where it comes from and how to fix it?

**Comment by asturur** [comment]
the same bug is there in the official page based on 3.6 and was there from start.
I remember someone pointed out where it came from, but i forgot.

**Comment by Harmageddon** [comment]
Oh, okay. For the things I used it for, it sometimes did it during rotation, but got back to the correct position afterwards. From v4 I noticed that it only hopped back when applying another transformation like moving the boss object.

**Comment by awehring** [comment]
It seems, that the wobbling of the minon has something to do with the distance from the mousepointer to the center of the rotation.
If you start rotating and move the mouse farther away from the master, the minion wobbles less, and vice versa.

Maybe the position of the  mousepointer is rounded to the nearest pixel, or something like this.

**Comment by asturur** [comment]
i have vague memories of the async render playing a role. more events could be generated between a requestAnimationFrame and another, and somehow we would save references to wrong transforms. just a fuzzy memory

**Comment by awehring** [comment]
I think, this should be left open and marked as bug.

**Comment by asturur** [comment]
i do not think there is any bug here. The demo has always been a bit wobbly. Someone at some point pointed out how to fix it.
