### ISSUE TITLE
FabricJS Inspecting the Canvas from UnitTests or Automated Tools

### ISSUE THREAD

**Issue by Neuroforge** [fabricjs/fabric.js#6132]
We are using FabricJS and items can be rendered to the canvas when actions are taken in the web app.

i.e. Click a button and an object would appear in the fabric canvas.

What are the best methods to check the canvas has been updated correctly using an Automated e2e test?

https://stackoverflow.com/questions/59977532/fabricjs-inspecting-the-canvas-from-unittests-or-automated-tools

After some thinking, i am going to attempt to have a global array that serves as a lookup table for all items added to the canvas. This will only be in Dev mode so it shouldn't affect our production deploy.

This would only work with clickable items that have actions associated with them. i.e. Fabric events. It would not work for inert objects.

Any other thoughts would be greatly appreciated.

**Comment by asturur** [comment]
I think you opened the same question in the other repo, and i answered you there.

The method depends on what are you testing and what kind of testing are you running.

Do you click a button in a browser environment? Do you manually run a click handler in a jest test?

You can inspect what objects has the canvas  before and after the action and verify the difference is what you are looking for.

**Comment by Neuroforge** [comment]
Thank you for your response.

I opened this question in the wrong repo. Apologies.

https://github.com/fabricjs/fabricjs.com/issues/248

I think we should have a hidden 'test' button that can fetch all of the objects from the canvas for inspection. This will allow the testing framework to receive a list of objects and calculate whether or not they are correct.
