### ISSUE TITLE
Don't preserve ratio when resizing via corner handle

### ISSUE THREAD

**Issue by parliament718** [fabricjs/fabric.js#6134]
I noticed when resizing a selected object using one of its corners, Fabric preserves the width/height ratio of the object.

Is there any way to disable this? I would like the corner handles to allow resizing in both directions but without preserving the ratio.

**Comment by asturur** [comment]
please have a look at the docs, everything is described in the jsdocs of the canvas class.

**Comment by asturur** [comment]
http://fabricjs.com/docs/fabric.Canvas.html

**Comment by parliament718** [comment]
Ok I looked at those docs. I don't see what I'm looking for. Can you please note the option name

**Comment by asturur** [comment]
http://fabricjs.com/docs/fabric.Canvas.html#uniScaleKey

`Indicates which key enable unproportional scaling. values: 'altKey', 'shiftKey', 'ctrlKey'.`
Default Value: shiftKey

So keep shift pressed to make it happen.

or to have a permanent setting

http://fabricjs.com/docs/fabric.Canvas.html#uniScaleTransform

I have to admit is not the best doc ever, the never text is slightly better.

**Comment by arthurflor23** [comment]
Hi,
``uniScaleTransform`` is working in 4.0.0-beta.7?
In the previous version was fine, but now I got this problem. (``shiftKey`` is working, anyway)

**Comment by asturur** [comment]
i think it has been renamed, please check the changelog file.

**Comment by arthurflor23** [comment]
I checked and it was renamed to ``uniformScaling``, but it doesn't work either

**Comment by asturur** [comment]
open a fiddle with latest beta and show that it does not work, we'll fix it.

**Comment by kylekirkby** [comment]
Hi all,
Pressing the `shift` key allows me to freely scale an object. Is there an option to flip this behavior so pressing `shift` scales the object uniformly instead?

TIA,
Kyle

**Comment by asturur** [comment]
in fabric 3.6 there is this canvas option:
http://fabricjs.com/docs/fabric.Canvas.html#uniScaleTransform
I'm not sure it works 100% of the time because of some weird boolean logic.
In the fabric 4 beta it changed name to uniformScaling and works normal or inverted.

**Comment by kylekirkby** [comment]
@asturur thank you! Are the beta docs being generated some place? I was starting to think I was going crazy. Atleast I'm not the only one :D

**Comment by kylekirkby** [comment]
FYI - I've just tried with the beta version and I'm still not able to transform freely with the `uniformScaling` option set to `true` or `false`.

**Comment by kylekirkby** [comment]
@asturur thanks for your quick response. I guess we are all with our devices at current in light of the pandemic! Hope all is good with you!

**Comment by asturur** [comment]
Is just that this is the part of the weekend where i work on fabricjs when i can.
Did you build the latest beta before trying it?
Where did you take it from?
It should work i fixed it recently. checking.

**Comment by kylekirkby** [comment]
I'm pulling the beta version using
`yarn add  fabric@4.0.0-beta.8`
Oh.. is there a way I can print the version of FabricJS I'm using to the console?

**Comment by asturur** [comment]
console.log(fabric.version)

**Comment by kylekirkby** [comment]
Thank you!
OK so I'm on 
```
fabric.version
"4.0.0-beta.7"
```
and I've got `uniformScaling` set to `true` but I still have to hold shift to scale freely.

**Comment by kylekirkby** [comment]
I've now got 
```
fabric.version
"4.0.0-beta.8"
```
and still to no avail I'm unable to freely scale.

**Comment by kylekirkby** [comment]
Aha! I've just set `uniformScaling` to `false` and it works! Thank you @asturur !
