### ISSUE TITLE
"Operation is insecure" Error in safari on mac only with cross domain video in background of canvas.

### ISSUE THREAD

**Issue by contact2mayurkukadiya** [fabricjs/fabric.js#6135]
I am using fabric js version 1.7.22. I want to upgrade it with new version of fabricjs in my project but I can't upgrade due to project's complexity.

I am working in fabric js editor in which I need to set video as canvas background. I already done this functionality and all perfect working in all browser except safari browser in mac.

safari is throwing error of **operation is insecure** while convert canvas into image using **canvas.toDataURL()** method.

Video is load perfect in safari also but can't generate image after set that video.And **main point**  is that I don't have any **_control_** over **_cross domain server_**. because it' s third party assets collection server.

I already try to generate this issue in fiddle and here is fiddle.

https://jsfiddle.net/Mark_1998/6ytobvdL/

Please run this Fiddle in windows chrome and safari. you will get difference in console logs.

Is there any missing code or patch in my code that resolve my issue. Please help me.

**Comment by umeshpatadiya** [comment]
getting same issue :(

**Comment by asturur** [comment]
if you do not have control on the cross origin if the external server, and the server allows only certain domains, that is a choice of the server that you can t fix and you should not fix.

**Comment by umeshpatadiya** [comment]
hi @asturur 
I'm using amazone s3 bucket for the same.. 
can you please help me with it?

**Comment by asturur** [comment]
i'm not an expert for s3 bucket configuration, but definetely you can set per file or per folder CORS headers, both full open or open for certain domains
