### ISSUE TITLE
How to lock axis when use fabric js free drawing mode?

### ISSUE THREAD

**Issue by hoc-ht** [fabricjs/fabric.js#6137]
Is it possible to lock the axis for draw a straight line when I use free drawing mode?
I want to develop a feature that user can hold SHIFT key and draw a straight line.
Note: I see there are **lockMovementX** and **lockMovementY** properties but it used for Object only, not for drawing mode on canvas.

**Comment by asturur** [comment]
You need to write a custom brush. You can start from the pencil class. In the mouse move handler you receive the event object and so you can check for modifier keys and change the drawing logic.

**Comment by hoc-ht** [comment]
Thank you for your reply, @asturur .

Finally I found the solution by combine "mouse:down:before", "mouse:move", "mouse:up" event and manually set canvas.isDrawingMode = false.
By this way, I can draw a straight line if I hold SHIFT key. I also can lock axis by hold ALT + SHIFT keys while drawing.

Here is my solution:

1. Listen mouse down event:
```
this.canvas.on('mouse:down:before', this.onMouseDown);
```

2. Save mouse position and draw a line at this point when mouse down
```
onMouseDown = (otp) => {
    if (otp && otp.e && otp.e.shiftKey) {
      this.canvas.isDrawingMode = false;
      const {x, y} = otp.pointer;
      const color = '#E44545';
      this.line = new fabric.Line([x, y, x, y], {
        fill: color,
        stroke: color,
        strokeWidth: 4,
        selectable: false,
        evented: false,
      });
      this.startLineCoords = {x, y};
      this.canvas.on('mouse:move', this.onMouseMove);
      this.canvas.on('mouse:up', this.onMouseUp);
      this.canvas.add(this.line);
    }
  };
```

3. Update this line and redraw while mouse moving
```
onMouseMove = (otp) => {
    if (otp && otp.pointer) {
      let {x, y} = otp.pointer;
      if (otp.e && otp.e.altKey) {
        const d1 = Math.abs(x - this.startLineCoords.x);
        const d2 = Math.abs(y - this.startLineCoords.y);
        if (d1 < d2) {
          x = this.startLineCoords.x;
        } else {
          y = this.startLineCoords.y;
        }
      }
      this.line.set({'x2': x, 'y2': y});
      this.canvas.renderAll();
    }
  };
```
4. Set drawing mode back to true when mouse up
```
  onMouseUp = () => {
    this.line = null;
    this.canvas.isDrawingMode = true;
    this.canvas.off('mouse:up', this.onMouseUp);
    this.canvas.off('mouse:move', this.onMouseMove);
  };
```

Hope to help someone :))

**Comment by asturur** [comment]
i would have used a simple solution that i want to share here.

https://github.com/fabricjs/fabric.js/blob/master/src/brushes/pencil_brush.class.js#L55
This is where the mouse move in drawing mode gets handled.

`options.e` contains the JS event.

if shift is pressed, options.e.shiftKey is true.

i would have forwarded the event in this call here:
https://github.com/fabricjs/fabric.js/blob/master/src/brushes/pencil_brush.class.js#L59

https://github.com/fabricjs/fabric.js/blob/master/src/brushes/pencil_brush.class.js#L132

and i would have ignored either the y or the x coordinate, copying it from the previous point, if options.e.shiftkey was true.

Does it sound reasonable to you?
