### ISSUE TITLE
Unable to hide secondary objects based on property

### ISSUE THREAD

**Issue by emmpii8** [fabricjs/fabric.js#6139]
I've got some code where I'm adding shapes onto the canvas. Each shape has a unique colour code. On select, I can add an image to the canvas, the name property for it being the same as the selected shape. 

The images are being loaded with a property as such:
```
image.set({
        name: obj.fill,
        mediaType: "content"
})
```

Effectively, if I delete a particular shape, all connected images are also deleted from the canvas (that works)

What I'm trying to do is hiding the images when the shape is no longer selected. If I select a different shape, only images attributed to that shape should show.

However, the outcome of my code isn't consistent and keeps hiding/showing incorrectly and it's at this part in the code.

```
function onObjectSelected(e) { // obj select event
  var obj = canvas.getActiveObject();
  if (obj.mediaType !== "content") { // if selected object is not a secondary image attributed to a shape
    var allObjects = canvas.getObjects();
    canvas.forEachObject(function(object) {
      console.log(object.name);
      console.log(object);
      if (object.name !== obj.fill && object.mediaType == "content") { // if image name is not same
       // THIS ONLY RUNS IF CLICKING SHAPE AFTER IMAGE WAS SELECTED 
       object.setVisible(false)
      }
      if (object.name == obj.fill && object.mediaType == "content") { // if image name is same as file
        // THIS CODE IS GETTING RAN AND ABOVE BLOCK GETS SKIPPED
        object.setVisible(true);
        object.selectable = true;
        canvas.bringToFront(object)
      }
      canvas.renderAll();
    });
    } else {
    // ..
   }
}
canvas.on('object:selected', onObjectSelected);
```

Essentially the code doesn't hide/show properly/consistently.

I've found that clicking on a shape1, then clicking on image1 and then again on shape1 hides image2. Same for shape2 etc..

**Comment by emmpii8** [comment]
figured a solution for this would be add each shape to an array, add the connected media as nested arrays and target each object accordingly.

**Comment by asturur** [comment]
Hi @emmpii8 this is less related to fabric and more to general javascript proramming.
It would be best to base those questions on stackoveflow and tag with fabricjs tag too.
Whoever is interested in answering is probably also following the tag.
