### ISSUE TITLE
Dragged objects return to initial render position when updating react state.

### ISSUE THREAD

**Issue by ilbrigz** [fabricjs/fabric.js#6140]
The dragged objects flicker or get stuck to their original position when doing a react state change. Already added React.memo to prevent rerender but the issue persists. The objects won't return to their dragged position til I highlight them. What could be a work around to this problem?

**Comment by ilbrigz** [comment]
Silly me. I haven't added the dependency in the useEffect array.

**Comment by asturur** [comment]
Anyway would have been almost impossible to help with such description. How could we have helped?
