### ISSUE TITLE
Function scaleToDimensions(width, height)

### ISSUE THREAD

**Issue by Roinoss** [fabricjs/fabric.js#6144]
Analogical to fuctions scaleToHeight and scaleToWidth, something like:
```
scaleToDimensions(width, height, absolute) { //or with absoluteX and absoluteY
   var boundingRectFactorY = this.getBoundingRect(absolute).width / this.getScaledWidth();
   var boundingRectFactorX = this.getBoundingRect(absolute).height / this.getScaledHeight();

   this._set('scaleX', height / this.height / boundingRectFactorX);
   this._set('scaleY', width / this.width / boundingRectFactorY);
   return this.setCoords();
}
```

**Comment by asturur** [comment]
Unsure if this is a suggestion or an help request.
Anyhow fabric provide an utility called `calcScaleToFit`
That function ingest to objects with width and height ( plain js objects or fabricObjects ) and return a scale factor to make the origin fit the destination. There is also calcScaleToCover that does the same thing but to cover it.

So you can pass either width and height of an object or the current bounding box if you want to account for rotation and use it for all the combinations possible.

**Comment by Roinoss** [comment]
Is `calcScaleToFit` in fabric docs? Or any info where i can read about it - I and searcher in http://fabricjs.com/docs/ cannot find any info for both calc to fit and to cover? Also no sign of it in fabric code.

**Comment by asturur** [comment]
on what version are you? maybe i do not remember the name correctly.

**Comment by Roinoss** [comment]
I checked current version's code on github in dist folder - 3.6.1 and documentation which is also for 3.6.1 version.

**Comment by asturur** [comment]
The name was different i got confused.

those are fabric.util.findScaleToFit and fabric.util.findScaleToCover

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/commit/d3c4959078c7a2c2f55fed78a585659ef46cd122

just added the JSDOCs to them

**Comment by Roinoss** [comment]
Both them and currently existing functions scales or calculates scales for X and Y both at once, but depending only at one of them.
There isn't independent function to scale only Height or only Width.

I currently use something like this (based on scaleTo functions from fabric, but with removed scaling for second dimension):
```
function _scaleToHeight(object, height, absolute) {
      var boundingRectFactorY = object.getBoundingRect(absolute, true).height / object.getScaledHeight();
      object._set('scaleY', height / object.height / boundingRectFactorY);
      return object.setCoords();
    }

function _scaleToWidth(object, width, absolute) {
      var boundingRectFactorX = object.getBoundingRect(absolute, true).width / object.getScaledWidth();
      object._set('scaleX', width / object.width / boundingRectFactorX);
      return object.setCoords();
    }
```

plus previously poster _scaleToDimensions to set both at once (but still independent) with only one call for setCoords().
```
function _scaleToDimensions(object, height, width, absolute) { 
      var boundingRectFactorY = object.getBoundingRect(absolute, true).width / object.getScaledWidth();
      var boundingRectFactorX = object.getBoundingRect(absolute, true).height / object.getScaledHeight(); );
      object._set('scaleY', height / object.height / boundingRectFactorX);
      object._set('scaleX', width / object.width / boundingRectFactorY);
      return object.setCoords();
    }
```

So I'm still requesting feature like those functions, but maybe renamed as:
scaleOnlyHeight, scaleOnlyWidth (xor scaleHeight, scaleWidth) and scaleToDimension.
