### ISSUE TITLE
Save dataImage of canvas before rendering

### ISSUE THREAD

**Issue by VinAr22** [fabricjs/fabric.js#6145]
Hello! Sorry for dublicate. I am stuck with the problem, where i want to display two canvases. Canvas with zooming and canvas with the general view of the first canvas.  Can you please help me? 
My stackoverflow [question](https://stackoverflow.com/questions/60151384/save-dataimage-of-canvas-before-rendering?noredirect=1#comment106388927_60151384)

**Comment by asturur** [comment]
I hanswered with a comment in the question.
toCanvasElement is the fastest you can get. What is wrong with using toCanvasElement as in the first answer you got?

**Comment by VinAr22** [comment]
Thanks again, Andrea. I will close this topic.

**Comment by asturur** [comment]
@VinAr22  is ok keeping it closed and talking about your performance problems
