### ISSUE TITLE
Selection by borders only

### ISSUE THREAD

**Issue by parliament718** [fabricjs/fabric.js#6146]
Is there any way to **not** treat the entire area of a shape as selectable? 
I would like for my objects to be selectable/draggable only from their borders. 

The reason I need this is because I'm combining 2 canvases. Behind the fabric canvas is a financial chart which can be panned but when there are too many shapes, I end up moving the shapes when I actually wanted to pan. 

Financial chart users often draw many large rectangles over their charts to signify price areas of interest, so at times much of the chart can be covered in them and panning becomes unusable.

This ability also allows for better selection of overlapping shapes. For example, if one shape is completely enclosed by another, you can still select it using the border since the enclosing shape's area is not selectable.

**Comment by asturur** [comment]
Fabric can't select by ~borders~ stroke only.
It select by bounding box, the full square.

The alternative is this:
http://fabricjs.com/docs/fabric.Canvas.html#perPixelTargetFind

And you can enabled it on the canvas or per object.
Be aware that if you do not have caching on, is a bit expensive.

**Comment by parliament718** [comment]
@asturur  This is critical functionality for my use-case. 
How would you suggest implementing it?

Also, I don't understand what perPixelTargetFind really does if I enabled it. How would it even help at the cost of performance?

**Comment by asturur** [comment]
Did you try to enable it? perPixelTargetFind will find the objects only where it is non fully transparent.

**Comment by asturur** [comment]
Also i miss the point on `why are you not even considering it?`. The feature is there, and is called perPixelTargetFind.
Maybe i misunderstood your issue?

**Comment by parliament718** [comment]
I did try to enable it, but it seems to have absolutely no effect, thus my asking what should I be expecting to happen?

The behavior I'm trying to replicate can be seen in TradingView.com, arguably the best financial charting app on the market. 

See the rectangles I've drawn here: https://www.tradingview.com/chart/GBPJPY/lsZ5dsn6-Fabricjs/

Notice how I can select both rectangles by the border, even the one completely enclosed by the larger one. 

Also, if you don't click on the actual  border you can still pan the chart. This allows for the shapes to not interfere with other functionality.

**Comment by parliament718** [comment]
Shoot, actually with that shared link the interactivity seems to be gone. Please open a chart and draw your own rectangles to see.

**Comment by parliament718** [comment]
The goal is to allow the user to interact with the chart more fluidly. A power use will zoom and pan around the chart at a high speed and it's desirable that they don't accidently move the shapes around while trying to do so (since these shapes are often carefully placed at important levels). At the same time it's a bit annoying to force them to switch between "modes" where the shapes are movable vs not. The best middle ground is to allow via border selection only, this way the chance of them accidently moving a shape is significantly reduced and without having to switch modes.

**Comment by asturur** [comment]
Is unclear to me how your application is built. You should really try to reproduce a simple panning html and a fabric canvas overlay and start your discussion on top of that.
`perPixelTargetFind` will allow you to trigger an object selection only where the object is not transparent. So in case your object is a transparent rect with a dark stroke, the dark stroke will trigger an event while the transparent fill will not. The performance cost is not that much unless you have hundreds of rects, with or without object caching.

**Comment by parliament718** [comment]
I've prepared a pen for this: https://codepen.io/parliament718/pen/GRJZQEr

```perPixelTargetEnd``` with a transparent fill does seem to have the behavior I want, with a few problems:

1) I don't actually want a transparent fill
2) The border should have sensitivity threshold of ~5 pixels without having to make an ugly 5px stroke
3) I've recently rebuilt my entire charting from svg to canvas (and webgl where possible) because I was hitting rendering performance bottlenecks. Svg performance was way too poor, now with canvas it is faster but performance continues to be a high priority. In my application, this chart also functions as a renderer for an automated trading system which does indeed plot hundreds of objects when backtesting over multiple year of data.

```perPixelTargetFind``` is a hacky way to partially achieve the behavior I want, with trade-offs. Perhaps a better solution can be built into fabric.js? As I explained in my earlier comment, my naive view is that it doesn't seem too hard to implement inside fabric (if one knows the code). For me it's a bit over my head, as this is my first entry into canvas-based charting and I probably would not have gotten this far without d3fc + fabric. 

 Thank you

**Comment by asturur** [comment]
i ll check the fiddle as soon i can. probably you can leverage the new control api for this, assumed there is a way to make control shapes custom, that as today there isn t. but being beta maybe we can think of it.

The control api is made to solve interaction customization and leave in core fabric only rendering features.

**Comment by parliament718** [comment]
I got a few usable answers on [stackoverflow](https://stackoverflow.com/questions/60143667/fabricjs-selection-only-via-border) for this question. 

It's no longer an issue for me but I'm interested if there's a better way to do it with the new control api. The stackoverflow answers all override internal methods. The accepted answer is the best in my opinion but it still overrides 1 method.

**Comment by asturur** [comment]
that won t work with rotated rects tho.

I think the solution is an extension of the custom controls api in fabric 4, probably post release since is a new feature entirely, ability to define control shape rather than just control size. At that point you would define 4 controls as big as the rect sides.

there is a but, fabric by default does not allow you to use a control of an object that is not selected already. so potentially you would need to first select the rect and then drag it.
