### ISSUE TITLE
Programatically changing Object position doesn't update target areas

### ISSUE THREAD

**Issue by Itzalive** [fabricjs/fabric.js#6148]
If I add an object to a canvas and programatically update the location the target location that is clickable/selectable is still in the original location.

Working example:

    // add red rectangle
    let rect = new fabric.Rect({
      width: 50,
      height: 50,
      left: 50,
      top: 50,
      fill: 'rgb(255,0,0)'
    });
    canvas.add(rect);
    rect.left = 100;

Then try clicking or dragging the rectangle. (This click area is actually to the left of the visible area)

**Comment by RazaGR** [comment]
have tried rect.setCoords()?
https://github.com/fabricjs/fabric.js/wiki/When-to-call-setCoords

**Comment by asturur** [comment]
also
http://fabricjs.com/fabric-gotchas

**Comment by Itzalive** [comment]
Thanks for all the information
