### ISSUE TITLE
about selection

### ISSUE THREAD

**Issue by joylord2018** [fabricjs/fabric.js#6150]
I wat to let elements can be selected but not dragged,i set the selection or hasControls to false, but the elements can't be selected. Can you have any suggests for this question,thanks,

**Comment by joylord2018** [comment]
I write it wrongly,that's selectable not selection.Can you have any suggests for this question,please.

**Comment by RazaGR** [comment]
https://github.com/fabricjs/fabric.js/wiki/Preventing-object-modification

```
lockSkewingY: true,
lockSkewingX: true,
lockMovementY: true,
lockMovementX: true,
```
