### ISSUE TITLE
Polyline no-fill hit detection

### ISSUE THREAD

**Issue by Chagrilled** [fabricjs/fabric.js#6153]
Hi,

I'm trying to draw lines of (up to a few thousand) points like so:

`simplifiedLines.forEach(line => {

     let polyline = new fabric.Polyline(line.points, {
     stroke: line.type == 'primary' ? this.colours.PRIMARY : this.colours.LATERAL,
     fill: null,
     strokeWidth: 4,
     padding: 0
    });        
    this.fabricCanvas.add(polyline);
})`

Which looks like so: 

![git](https://user-images.githubusercontent.com/7968849/74446125-573a5b00-4e6f-11ea-82f0-3b907128c274.PNG)

This is fine, except I'd like to improve hit detection of my lines. By marking fill: null, I assume the polygon still exists just isn't drawn. The red cross is where I clicked to select the line, and the black line is where the polygon WOULD be filled in. As you can see from the selection box, that's quite a distance from the line I wanted, all the way on the right. I tried to reduce padding, but that did nothing.

Is there anything I can do to reduce the selection regions/tighten them up to help with selecting nearby lines? Alternatively, what might I be able to do to improve this in terms of usability?

It may be of worth to note that the canvas element is scaled to 3000x3000, and CSS scaled to 1000x1000, I don't know if that effects how Fabric scales its selection areas.

**Comment by Chagrilled** [comment]
`perPixelTargetFind: true,` was what I needed, after scouring the docs a bit more. Now I just wonder if there's a slight middle ground that allows me a little more leniency than pixel perfect detection.

**Comment by asturur** [comment]
no there is not. That would be a complex geometry problem probably.
perPixelTargetFind has an accuracy parameter somewhere. i remember it can go far from the real pixels.

**Comment by awehring** [comment]
The parameter you are looking for is propably the Canvas property:
`targetFindTolerance` 
Number of pixels around target pixel to tolerate (consider active) during object detection 

http://fabricjs.com/docs/fabric.Canvas.html#targetFindTolerance

**Comment by asturur** [comment]
thanks @awehring 

i was also thinking on a separate note and topic, that diagonal lines should disappear.
Fabric should parse the line structure, get the horizontal line that fit and apply the angle necessary. This works with 2 point lines only of course.

**Comment by asturur** [comment]
and if someone is smart enough the concept can be extended to a bigger number of points, find the smaller rectangle that can get all those points inside.

**Comment by asturur** [comment]
i think we can close this issue i do not see any action item here other than linking to docs.
