### ISSUE TITLE
I'm having a problem with obj.intersectsWithObject(obj2)

### ISSUE THREAD

**Issue by chadhcadlink8com** [fabricjs/fabric.js#6155]
## Version
3.6.0

## Test Case
[canvas.zip](https://github.com/fabricjs/fabric.js/files/4206458/canvas.zip)

## Information about environment
Nodejs or browser? browser
Which browsers? Chrome

## Steps to reproduce
I uploaded a zip file containing html/javascript. I couldn't get it to work in fiddle(not sure if it is due to jquery and/or attempting to use 'window.onload = function () { }' in the javascript.)

Open html file(canvas.html) in Chrome. Using mouse bounding box attempt to multi-select items on the page(hold mouse button down and drag)). I create my own bounding box on the canvas and when 'mouse up' event occurs, it modifies the items touching the bounding box. 

## Expected Behavior
highlight items touched by mouse drag bounding box.

## Actual Behavior
When you attempt to highlight items on the right side, elements on the top left side get highlighted. The problem seems to be with .intersectsWithObject(). file /js/canvas.js (line 232)

**Comment by asturur** [comment]
I understand you had problems reproducing your whole codebase in a fiddle.
But should be very easy to make a fiddle in general, what you are focused on is `highlight items touched by mouse drag bounding box.`

So adding a bunch of elements on a canvas and copy your code to highlight them should be that problematic.

When the fiddle is ready i ll reopen the issue.

**Comment by chadhcadlink8com** [comment]
Hi

I spent a little time with fiddle and I now have it working. Sorry I never used it before and was being lazy :)

https://jsfiddle.net/Hankster/cvgzt7y4/1/

If you go to right side of the canvas and hold the cursor down and attempt to drag highlight some objects. Eventually you will see it highlight objects on the left top left. This is occurring at line 248 (mouse up) intersectsWithObject().

Thanks
