### ISSUE TITLE
Bug, feature request or needed help: Point with same coordinates is in diferent place for objects for their real position. 

### ISSUE THREAD

**Issue by Roinoss** [fabricjs/fabric.js#6156]
As in topic, putting two objects in (0, 0) point with different sizes, didn't sets one real object in same place as second.

In code example it is clear that two rectangles are in different real position with same left and top.
For me there should be one or two things done in fabric.js:
- fix
- add functions/variables to easy calculate it
- add tutorial for way around for it
- add expansion to fabric.js for it
- or i just cannot find function to fix it (have way around baked for my user-case in work)

Code example for Kichensink execute:

```
// clear canvas
canvas.clear();

// remove currently selected object
canvas.remove(canvas.getActiveObject());

// add red rectangle
canvas.add(new fabric.Rect({
  width: 50,
  height: 50,
  left: 0,
  top: 0,
  fill: 'red'
}));


// add blue rectangle
canvas.add(new fabric.Rect({
  width: 50000,
  height: 40,
  left: 0,
  top: 0,
  fill: 'blue'
}));
```

**Comment by asturur** [comment]
hi @Roinoss, is always better to provide a working jsfiddle.

this is an optical effect of resizing images.
Every object has strokeWidth set to 1, even if transparent.
You can set it to 0 and the effect goes away.

The 50000 wide rect is represented on a cached image that is like 2000 pixel wide.
on that scale 50,000 over 2,000 the 1 stroke pixel gets reprenseted as  1/25 of a pixel and what you get is a blue pixel that has opacity of 0.96 probably. To you this pixel looks full blue and creates an offset compared to the red rect that is smaller and has space to represent each pixel entirely.

You can disable obejectCaching ( about which you should learn as much as possible ) or disable the stroke. http://fabricjs.com/fabric-object-caching

try to set the stroke to black before also to see a different representation of the problem.

**Comment by Roinoss** [comment]
Thanks, its looks like i missed strokeWidth options and how it works, but i had it set in code.

Feature request according to jsfiddles:
Create generic naked jsfiddle example and put link to it in few places:
- At the beginning of the each Tutorial  or 1st Tutorial page.
- At the beginning of the README.md in github.
- In 'Feature request' and 'Help with my own project' issue types 
('Bug template' has it and i posted this issue from 'Feature request' so i missed it).

**Comment by Roinoss** [comment]
As i got similar error elsewhere i back here and checked: strokeWidth = 0 don't work for blue rectangle, it caused to blur left ending of the rectangle.

 Also: Should 'stroke strokeWidth strokeDashArray' be duplicated in cacheProperties?

**Comment by asturur** [comment]
strokeWidth isn't in cacheProperties because it is going to change the size of the object anyway and kill the chache. Stroke and strokeDashArray should be in the the array.
What do you mean by duplicated?

Can you clearly show what error are you getting, in a fiddle?

**Comment by Roinoss** [comment]
Here:
in fabric code:

/**
 * List of properties to consider when checking if cache needs refresh
 * Those properties are checked by statefullCache ON ( or lazy mode if we want ) or from single
 * calls to Object.set(key, value). If the key is in this list, the object is marked as dirty
 * and refreshed at the next render
 * @type Array
 */
cacheProperties: (
  'fill **_stroke strokeWidth strokeDashArray_** width height _**stroke strokeWidth strokeDashArray**_' +
  ' strokeLineCap strokeLineJoin strokeMiterLimit fillRule backgroundColor'
).split(' '),

**Comment by asturur** [comment]
oh i see it now, i can update that.
But you can too with a fabricjs.com PR.
