### ISSUE TITLE
cannot set stroke in _render function

### ISSUE THREAD

**Issue by yaoleia** [fabricjs/fabric.js#6157]
fabric@2.7.0

fabric.LabelPoint = fabric.util.createClass(fabric.Circle, {
                    type: 'labelPoint',
                   _render(ctx) {
                          if (this.label === '1') {
                               this.stroke = '#ff8800'
                               this.strokeDashArray = [5, 10]
                          }
                          this.callSuper('_render', ctx)
                     }
            })

when I draw a labelPoint and set label = "1", I check the object, strokeDashArray is [5, 10], but stroke is still null . why it is?

**Comment by asturur** [comment]
when _render is called, _setStrokeStyle has been already called.
You can't change the object property.
If you are writing the _render function, you have to use the CanvasRenderingContext methods on ctx.

`ctx.strokeStyle = '#ff8800'`

this.stroke will be applied in the next rendering, if you invalidate the cache.
