### ISSUE TITLE
Custom object not being restored properly on deserialization.

### ISSUE THREAD

**Issue by rbulph** [fabricjs/fabric.js#6160]
OK, in this [thread](https://github.com/fabricjs/fabric.js/issues/5949) I was having problems with my fabric custom class not being restored properly on deserialization. asturur helpfully produced a fiddle:

[https://jsfiddle.net/mg7L5jrw/](https://jsfiddle.net/mg7L5jrw/)

and he pointed out that the custom class is recreated, and this is correct.

But it doesn't have a lot of its attributes set and so is invisible.  I have copied below a response from the console of what they are.

Why are they not being set?

Thanks.

canvas._objects[0]:

i {x1: undefined, dirty: true, width: NaN, height: NaN, left: NaN, …}
x1: undefined
dirty: true
width: NaN
height: NaN
left: NaN
top: NaN
y1: undefined
x2: undefined
y2: undefined
strokeWidth: 1
fill: "#444"
stroke: "#444"
id: "Arrowundefined"
name: "arrow"
selectable: true
lockMovementX: true
lockMovementY: true
lockScalingX: true
lockScalingY: true
lockRotation: true
hasControls: true
hasBorders: false
cornerColor: "rgba(255,0,0,1)"
cornerSize: 9
triangle: i {originX: "left", originY: "top", hasBorders: true, id: "triangleundefined", lockScalingX: true, …}
text: i {styles: {…}, text: "", __skipDimension: false, id: "textundefined", fontSize: 20, …}
canvas: i {_objects: Array(5), lowerCanvasEl: canvas#canvas.lower-canvas, contextContainer: CanvasRenderingContext2D, renderAndResetBound: ƒ, requestRenderAllBound: ƒ, …}
oCoords: {tl: i, tr: i, br: i, bl: i, ml: i, …}
aCoords: {tl: i, tr: i, br: i, bl: i}
__proto__: i

**Comment by rbulph** [comment]
It seems that this.callSuper is not doing its job.

**Comment by rbulph** [comment]
The code in the fiddle is: 

fabric.Arrow.fromObject = function(object, callback) {
    return fabric.Object._fromObject('Arrow', object, callback);
  };

My code is:

fabric.Arrow.fromObject = function(options) {
	/** from https://github.com/kangax/fabric.js/issues/2668 to permit deserialisation from json. 
	var v= new fabric.Arrow([options.x1, options.x2, options.y1, options.y2], options);

	return v;
};

WIth my code in my website the line part of the arrow doesn't ever get added to the canvas. If I substitute the code for the fiddle, then no objects at all get added.

**Comment by asturur** [comment]
using the callback is mandatory.
you have to end your function with callback(v) rather than return v.

pleas post eventual new findings, questions on the old thread #5949
