### ISSUE TITLE
Fonts are shown incorrectly

### ISSUE THREAD

**Issue by gr8man** [fabricjs/fabric.js#6162]
## Version
3.6.2 - 4.0.0-beta.7

## Test Case
https://jsfiddle.net/gr8man/vyhekdj6/52/

## Information about environment
Nodejs and browser
Which browsers?
Chrome 80.0.3987.116 

## Steps to reproduce
Fonts are shown incorrectly after fonts are loaded.
For object Caching = false; just move the object.
For objectCaching = true you need to change the text.

The problem sometimes does not occur if the browser has cache fonts (ctrl + f5).

**Comment by asturur** [comment]
Hi @gr8man i looked at it,is an issue on how you load the fonts.
The google font loader you are using is loading by default the latin chars only.
If you want more unicode ranges to be available you should follow this guide here:
https://github.com/typekit/webfontloader#google
