### ISSUE TITLE
Why does the NPM package install the 4.0 beta version, and where are the docs for this version?

### ISSUE THREAD

**Issue by d4h0** [fabricjs/fabric.js#6165]
Hi,

The title says all.

I'm wondering why the [NPM package](https://www.npmjs.com/package/fabric) installs the 4.0 beta version, instead of the stable version. And I'm also wondering where I can find the documentation for this version (if it is already stable enough to be used). On the website, I only see [the documentation for version 3.6.2](http://fabricjs.com/docs/).

**Comment by asturur** [comment]
Hi @d4h0 ,
The version 4 is in beta and probably i do not know how to manage npm versions correctly.

The only documentation for 4.0 you can see so far is in the changelog and the example in fabricjs.com in the demos section that talks about control customization.

**Comment by d4h0** [comment]
Hey, @asturur, wait a second, why did you close this issue?

I opened it because I'm pretty sure that an **undocumented beta release with potentially many bugs** should not be the version that is installed by default when someone installs the official NPM package.

Look how many times this package is installed every week: [Arround 60 thousand times](https://www.npmjs.com/package/fabric).

There are probably many people who use this package in production and lose money and time if there are bugs.

You wrote yourself:

> probably i do not know how to manage npm versions correctly.

If I understand you correctly, you pushed the beta version by accident to NPM.

To be completely honest, this all seems very unprofessional to me – especially, that you just closed this issue – and makes me think about if I really should use this library.

Fabric.js looks really amazing, but if you guys don't care about basic stuff like what I outline here, then maybe it's better not to use this tool.

Is there something I don't understand correctly?

I definitely hope so.

I'd really like to use this lib, but if I can trust it, then maybe I shouldn't.

**Comment by avrahamcool** [comment]
It's an open source project, if you think there is something to fix, you can share your knowledge via a PR.

**Comment by d4h0** [comment]
@avrahamcool: I think my comment is more than reasonable after my issue got closed like this.

PRs are not the only way to contribute to a project. Bug reports are also important.

And before someone sends a PR, he or she should understand the situation first fully.

> Don't forget that they don't owe you a thing. It's all out of their good will.

Nobody owns me anything, yes, but certain things are reasonable to expect – and to not needlessly introduce bugs is one of these things.

**Comment by asturur** [comment]
An issue gets closed as soon as is investigated and if there is no clear action item or i know exactly what to do.

Open issues are open because need further reading or clarifications from people who opened them.

Said so, every version has potentially the same quantity of bugs, the quality controls are the same for every single commit.

I can't unpublish published versions and if you know how to tag beta versions on npm as beta, you should definetely share that.

I assume that if you want to use a library you check it a bit before and both on the website and here you find info about a beta stage.

The issue closed does not mean you can't continue asking or you will not receive answers.

**Comment by asturur** [comment]
To clarify the beta version is not published by accident, is published and tagged as beta in the version name.
It looks like there is a beta option in the publish command `npm publish --tag beta` but i have no idea how to identify a beta release from the beta contained in the tag, in a github action file. Definitely we could use this beta tag to lessen the confusion.

**Comment by d4h0** [comment]
> An issue gets closed as soon as is investigated and if there is no clear action item or i know exactly what to do.

> To clarify the beta version is not published by accident, is published and tagged as beta in the version name.

> It looks like there is a beta option in the publish command npm publish --tag beta but i have no idea how to identify a beta release from the beta contained in the tag, in a github action file. Definitely we could use this beta tag to lessen the confusion.

At the very least, I'd add a short disclaimer at the top of the readme that explains the situation. So everybody who is wondering what is going on, finds the answer and people are warned. I'd also add a snippet that shows how to install older versions. 

And then, to handle betas differently is a clear action item, isn't it? That's the reason why I was a bit shocked when the issue was closed without any kind of solution.

I probably could have been much more clear in my initial report/question, to indicate that I think this is a problem.

> Open issues are open because need further reading or clarifications from people who opened them.

> The issue closed does not mean you can't continue asking or you will not receive answers.

Yes, that's correct. The problem is that most other people will not see the issue. So maybe someone else who can help to fix the problem will not see the issue.

> Said so, every version has potentially the same quantity of bugs, the quality controls are the same for every single commit.

Then why release a beta at all?

Besides, I've seen some reports regarding regressions in the beta, and the beta version isn't documented. Maybe both of these issues are not a problem in praxis, but there definitely can be problems easily.

> I can't unpublish published versions and if you know how to tag beta versions on npm as beta, you should definetely share that.

I have no idea how to do this. Maybe you just could publish a second package? Something like fabric-beta.

I did a quick Google search regarding beta tags on NPM, and came up with the following link:

https://gist.github.com/adcreare/00a10f389841dd4c97197608c9b33a7f

This seems to be pretty simple. And to be completely honest, and with the risk of sounding like an a**hole again, it is difficult for me to believe that you weren't able to figure out how to properly publish beta releases.

> I assume that if you want to use a library you check it a bit before and both on the website and here you find info about a beta stage.

Sure, and I did this. But not everyone will – so why not help these people out? And of the people who realize that the beta is installed by default and wonder why, probably most will not ask and some will just not use this library. That is the reason why I opened this issue.

Anyway, I think I have said everything that there is regarding this issue.

Good luck with your project. It wasn't my intention to discourage you or anything, I just thought there are some things that could be improved, and I wanted to notify you.

I spend at least two hours on this issue and this wouldn't make sense for me to do, to just discourage someone to work on his or her open-source project.

**Comment by asturur** [comment]
There are lot of things that can be improved, as always.

The beta is named BETA because the api isn't finalized yet, so function signatures could change, removing or changing shape of arguments.

Is also incorrect that i could not figure out how to do, i did not look at it because i did not think could be a problem. People usually look at version/features and pick up a number to install it, at least locking to a major release is common.

npm install fabric@3.x

**Comment by d4h0** [comment]
> People usually look at version/features and pick up a number to install it, at least locking to a major release is common.

I doubt this is true. Most people just install the latest version with `npm install fabric`. And this is exactly what Fabric's [readme](https://github.com/fabricjs/fabric.js/blob/master/README.md) recommends.

This was the first time in my life that I installed a version of a package that is not the latest version of a package.
