### ISSUE TITLE
I'm having a problem with obj.intersectsWithObject(obj2) attempt 2

### ISSUE THREAD

**Issue by chadhcadlink8com** [fabricjs/fabric.js#6167]
## Version
3.6.0

## Test Case
https://jsfiddle.net/Hankster/cvgzt7y4/1/

## Information about environment
Nodejs or browser? browser
Which browsers? chrome

## Steps to reproduce
If you go to right side of the canvas and hold the cursor down and attempt to drag highlight some objects. Eventually you will see it highlight objects on the left top left. This is occurring at line 248 (mouse up) intersectsWithObject().

## Expected Behavior
highlight items touched by mouse drag bounding box(on mouse up).

## Actual Behavior
When you attempt to highlight items on the right side, elements on the top left side get highlighted. The problem seems to be with .intersectsWithObject(). (js line 248)

**Comment by asturur** [comment]
I m not sure how to better ask people to respect a bit the issue tracker without seeming unpolite.

Please improve the issue that was you attempt 1 rather than opening a new one. edit that.

**Comment by chadhcadlink8com** [comment]
Sorry you think posting a question is disrespectful? 
I modified the first post as you asked. I created a fiddle version of the problem, you didn't re-open it. So I opened a new ticket since I figured you closed the first one and were ignoring my edits to it.
I'm curious as to what disrespectful thing I've done?

**Comment by asturur** [comment]
Maybe respect the issue tracker is not the correct expression.
More keep it in order.

I'm not ignoring the edits, if i was ignoring the edits i could not know that this was a duplicate of the other.

I do not always have a ready answer for every open ticket. Some tickets stays open long, until me or someone else comes and dedicate time to them.

The more the open tickets the more this work is daunting. Not opening duplicate issues is in your best interests.

**Comment by chadhcadlink8com** [comment]
I hear you on work load. Not trying to be difficult. 
I may have to look for another solution to my issue, if I'm unable to resolve this one. It is very odd. Not sure if it is somehow related to the svg data being used.

Just let me know if you will be able to look at it and that you are able to reproduce the problem. If you don't think you have the time just let me know so I can decide my next steps.

Cheers

**Comment by asturur** [comment]
i also already looked at the fiddle already, but is BIG and i had to look at something else smaller first.

**Comment by chadhcadlink8com** [comment]
Hi
I was having another look at this issue and I was wondering if the problem has anything to do with negative values. Just a thought. Or whether it simply has to do with the fact that I'm using very large numbers(refer to the svg paths). 
Screenshots(blue box it the highlighting square while dragging and the next picture shows what is selected on mouse up):
![dragHighlight1](https://user-images.githubusercontent.com/33833903/75583056-e08a8980-5a3a-11ea-8fe7-6103858e1f6d.png)
![dragHighlight2](https://user-images.githubusercontent.com/33833903/75583057-e1232000-5a3a-11ea-88b2-3d736a6526a1.png)

**Comment by asturur** [comment]
There is defintely too much code there.
Is completely unclear why you are using a custom selection logic ( if i understood correctly ) rather than the one provided by fabricjs.
What is the reason behind it? Explaining this could bring to alternative fabricjs-native solutions.

**Comment by chadhcadlink8com** [comment]
Sorry I should have only left in what mattered. I didn't want the libraries default behaviour. This app is only for selecting items on the canvas. I found that the default behaviour didn't always select all the elements. I have the point and click working great. My only problem comes down to how the function intersectsWithObject(line 248)) or isContainedWithinObject work. They both cause the same issues mentioned.

**Comment by chadhcadlink8com** [comment]
- your multi select: canvas.getActiveObjects(); Problem with this option is it doesn't work if your mouse down event starts on an element. That is why I created my own bounding box.

**Comment by asturur** [comment]
why not working on that issue rather than rebuilding the whole feature?

did you try playing with events to see if you could get out with a working solution?

**Comment by chadhcadlink8com** [comment]
are you thinking that maybe mouse down and drag feature could maybe be forced to work even when starting on a element?

**Comment by chadhcadlink8com** [comment]
I just went back to play with it some more and modified: item.evented = false;
Then went back to using canvas.getActiveObjects(); and that might solve my problem!
I'm going to run a few more tests to make sure that fixed it.

If I was to suggest a new feature:
The ability to selected elements that are enclosed in the bounding box. Not just touching it :) That was one thing I was hoping my version of the bounding box would fix.

**Comment by chadhcadlink8com** [comment]
tested and yes I have it working using your function: canvas.getActiveObjects(); setting each items evented = false;

Thanks
