### ISSUE TITLE
Unexpected cursor position after apply custom font in Textbox

### ISSUE THREAD

**Issue by freehost0827** [fabricjs/fabric.js#6168]
The following is my code:
////////////////////////////////////////////////////////////////////////////
var canvas = new fabric.Canvas("tools-creator");
fabric.Object.prototype.objectCaching = false;

var font_family = "bitstream_vera_mono";
var font = new FontFaceObserver(font_family);

var Text = new fabric.Textbox("Sample Text", {
  left: 4,
  top: 50,
  fontSize: 15,
  width: 300,
  textAlign: 'center',
  fontStyle: 'bold',
  fill: 'black',
  splitByGrapheme: true
});

font.load().then(function() {
  fabric.util.clearFabricFontCache(font_family);
  Text.set("fontFamily", font_family);
  canvas.requestRenderAll();
});

canvas.add(Text);
////////////////////////////////////////////////////////////////////////////
Expected the cursor to be after letter "t"
<img width="312" alt="Screen Shot 2020-02-22 at 9 03 42 PM" src="https://user-images.githubusercontent.com/38790925/75093722-e6094f00-55b6-11ea-8e6d-3bfe959b5038.png">

**Comment by freehost0827** [comment]
I found the solution since I try setting "charSpacing" value to 1. Thanks to the documentation.

[...]
font.load().then(function(){
  Text.set("fontFamily", font_family);
  Tex.set("charSpacing", 1);
  canvas.requestRenderAll();
}
[...]

**Comment by niketaOptimumnbrew** [comment]
> I found the solution since I try setting "charSpacing" value to 1. Thanks to the documentation.
> 
> [...] font.load().then(function(){ Text.set("fontFamily", font_family); Tex.set("charSpacing", 1); canvas.requestRenderAll(); } [...]

@ghost Do you have solution when charSpacing is 0 
?

**Comment by huynamboz** [comment]
thank, it soved my problem

> I found the solution since I try setting "charSpacing" value to 1. Thanks to the documentation.
> 
> [...] font.load().then(function(){ Text.set("fontFamily", font_family); Tex.set("charSpacing", 1); canvas.requestRenderAll(); } [...]
