### ISSUE TITLE
My example-webpack + vue, Batch export pdf ，worker Can it be achieved

### ISSUE THREAD

**Issue by gaowenzhen** [fabricjs/fabric.js#6171]
fabric.js ，Not supported, error

Can my thinking change the entrance now, can anyone help me

error,
`
Uncaught ReferenceError: require is not defined

if ("undefined" != typeof exports ? exports.fabric = fabric : "function" == typeof define && define.amd && define([], function() {
    return fabric
}),
"undefined" != typeof document && "undefined" != typeof window)
    document instanceof ("undefined" != typeof HTMLDocument ? HTMLDocument : Document) ? fabric.document = document : fabric.document = document.implementation.createHTMLDocument(""),
    fabric.window = window;
else {
// error --
    var jsdom = require("jsdom")
      , virtualWindow = new jsdom.JSDOM(decodeURIComponent("%3C!DOCTYPE%20html%3E%3Chtml%3E%3Chead%3E%3C%2Fhead%3E%3Cbody%3E%3C%2Fbody%3E%3C%2Fhtml%3E"),{
        features: {
            FetchExternalResources: ["img"]
        },
        resources: "usable"
    }).window;
    fabric.document = virtualWindow.document,
    fabric.jsdomImplForWrapper = require("jsdom/lib/jsdom/living/generated/utils").implForWrapper,
    fabric.nodeCanvas = require("jsdom/lib/jsdom/utils").Canvas,
    fabric.window = virtualWindow,
    DOMParser = fabric.window.DOMParser
}

`

-----------------------------------------------------
my code demo
app.js
`
import Worker from 'worker-loader!./worker.js'
const worker = new Worker()
var canvasdom = document.querySelector('#canvasdom')
var offscreen = canvasdom.transferControlToOffscreen()
worker.postMessage({ canvas: offscreen }, [offscreen])
`

------------------------------------

worker.js
`
self.addEventListener('message', (event) => {
    var fabric = window.fabric || {}
    self.importScripts('./fabric.min.js')
    console.dir(event.data.canvas)
    console.dir(fabric)
    self.postMessage({ foo: 'foo' })
  })
`

**Comment by asturur** [comment]
Is unclear how we can help @gaowenzhen , please try to be more clear and focused on your problem
