### ISSUE TITLE
Edited title: Bug due to duplicated width and height values in upper and lower canvas.

### ISSUE THREAD

**Issue by Roinoss** [fabricjs/fabric.js#6173]
Old tittle: Patterns cannot have constans height and width - pattern real dimensions depends on page zoom instead of

## Version
3.6.0

## Test Case
//My code (snippet in stack):
https://stackoverflow.com/questions/60350747/fabric-js-patterns-how-create-pattern-for-canvas-background-from-rects-without

//Similar issue in:
http://fabricjs.com/dynamic-patterns

## Information about environment
Firefox, Opera

## Steps to reproduce
1. Open page with pattern - look at its dimensions.
2. Change Zoom for page.
3. Refresh page

## Expected Behavior
When i set pattern width to 10 it should be 10 is same scale as canvas, so for object with width 100 i should have pattern repeated always 10 times.

## Actual Behavior
When i set pattern width to 10 for object with width 100 i obtain something like like 9.2 repeated patterns on www zoom = 100% and different amounts when page is loaded with different zoom.

In my example there is small Rect added to compare it size with pattern partially based on that Rect.

Dimensions in pixels are recalculated for patterns depending on zoom on page load. For other fabric elements (to my knowledge) dimensions are independent from zoom.

**Comment by Roinoss** [comment]
As i checked today - it looks like html canvas elements for fabricjs (upper and lower -canvas) have duplicated height and width values (one as key=value and one in style="width: value, height: value"). key=value height and width are definitely wrong as they are not same as size in html inspector and aren't possible to set by canvas.setWidth and canvas.setHeight and are somehow dependable on 'style' width and height as well as current html page zoom (and even at 100% zoom it modify key=value size to wrong).

Example canvas field from http://fabricjs.com/dynamic-patterns:
In page code:
`<canvas id="c" width="500" height="500" style="border:1px solid #ccc"></canvas>`
In generated page:
`<canvas id="c" **_width="625" height="625"_** style="border: 1px solid rgb(204, 204, 204); position: absolute; **_width: 500px; height: 500px;_** left: 0px; top: 0px; touch-action: none; user-select: none;" class="lower-canvas"></canvas>`

It causes few bugs:
- Pattern takes key=value size as canvas size and calculates himself wrong (so when i canvas.setWidth(100) and have pattern 20x20 i haven't got five patterns inside, but 4), it should calculate using style height and width.
- Pattern amount in canvas depends on non-fabric variable - page zoom (and only on initial page zoom - to test zoom page then refresh: http://fabricjs.com/dynamic-patterns) it should be independent from it.  (As key=value depends on page zoom).
- HTMLCanvasElement.toBlob() gets wrong height and width (key=value instead of those from style) so if canvas is converted to image its have unpredictable size.
- Same bug? pattern created from static canvas and rects is blurred. (Small blur to check in example from Test Case - My Code)

Suggestion:  Duplicated width and height from key=value style should be renamed (if some fabric feature really needs them) or removed.

**Comment by asturur** [comment]
https://stackoverflow.com/questions/60350747/fabric-js-patterns-how-create-pattern-for-canvas-background-from-rects-without/60473470#60473470

The output you will have on your canvas with toBlob are always the real pixel dimensions and not the style one.
the .toCanvasElement() method accept a series of options that let you discard retina scaling if i remember correctly.

I will close the issue, since there is no bug.
Please feel free to continue posting here if something is unclear or if you think i misunderstood your point of view.

**Comment by Roinoss** [comment]
Thanks, this and stack answer is all i needed.

Thus i have one feedback:
on-off retina scaling button in dynamic-patterns demo would be nice for future reference, as it isn't very obvious gotcha.

**Comment by asturur** [comment]
definetely better documentation  would help.  we are probably removing some kind of patterns, probably the one that are build with functions.
