### ISSUE TITLE
Chrome 80 objects dissappear/reappear

### ISSUE THREAD

**Issue by TmanTman** [fabricjs/fabric.js#6186]
## Version
3.6.0, and have also tested with 3.5.2

## Test Case
Haven't been able to reproduce, but I've tried to by building an environment where I expected it to fail: https://jsfiddle.net/gruyqnxw/2/
I've attached images of breaking cases on Chrome 80, and images of where it's working on Chrome 79 and Firefox.

## Information about environment
Chrome 80 has this issue.
Chrome 79 does not have this issue.
Firefox 72 does not have this issue.

## Steps to reproduce
Refer to Test Cases and Actual Behavior

## Expected Behavior
All objects should draw to the screen

## Actual Behavior
A subset of the objects that should be on the screen is drawn, and on zoom or pan, the other objects appear/disappear on the canvas.

It's a large number of objects, but nothing Fabric hasn't been able to handle - in one of the cases I've observed this, 4200 annotations across a canvas of 1000 x 1200 px. This has been working fine.

In Chrome 80, not all of the objects appear. When I zoom in on the canvas (using fabric's zoomToPoint) or pan (using fabric's viewportTransform) some objects appear. As I increase zoom, more and more objects appear until all is shown on the screen.

Here it's working in Chrome 79:
![Working in Chrome 79](https://user-images.githubusercontent.com/3293478/75547899-a1f1d080-5a34-11ea-8fff-1503335d0435.png)

Here it's working in Firefox 72:
![Working in Firefox 72](https://user-images.githubusercontent.com/3293478/75547905-a6b68480-5a34-11ea-9212-91ead3dc03d3.png)

Here it's broken in Chrome 80:
![Broken in Chrome 80](https://user-images.githubusercontent.com/3293478/75547907-a74f1b00-5a34-11ea-85db-73aed1b49ffa.png)

Here is a [video](https://aerobotics-angular-styleguide.s3.eu-central-1.amazonaws.com/problem_demo.mp4) of the observed behaviour

**Comment by asturur** [comment]
i do not have a laptop rigth now to verify the fiddle.

Try the following things:
- disable caching completely
- reduce min cache size to a smaller number
- disable hardware acceleration for a test

http://www.fabricjs.com/fabric-object-caching

**Comment by TmanTman** [comment]
@asturur Thanks for your reply. The following worked:

By only doing disabling cache completely: 
`fabric.Object.prototype.objectCaching = false;`

By only switching off hardware acceleration in Chrome (when hardware acceleration was off, it wasn't necessary to disable the cache):
![Screenshot 2020-03-02 at 07 14 09](https://user-images.githubusercontent.com/3293478/75647375-80236400-5c55-11ea-8d32-5ec3c57cf876.png)

None of the following (either separately or together) worked. I did this to attempt to reduce min cache size:
fabric.perfLimitSizeTotal = 1048576; // default 2097152
fabric.minCacheSideLimit = 16; // default 256
fabric.maxCacheSideLimit = 2048; // default 4096

**Comment by asturur** [comment]
I won't give the fault to chrome entirely.
Caching is useful but since canvas are hardware accelerated, having 70x70 4900 cached canvases is probably 4900 textures in the GPU memory. Consinder that if you have a computer without a real gpu, but a simple intel GPU powered laptop, there are limitation or drivers bug likely.

I'm not sure what is the best way for fabric to render a lot of irregular shapes all at once, it won't be fast all the time, that i m sure.

A thing that is still helping is that objects outside view are not rendered, skipped completely
Another thing that could help but are not ready are:
- moving controls outside the main canvas, so that selecting won't trigger a full re-render
- partial re-renderings ( just a project in my head )

If the bug is related to zoom, we could also look at the size of your objects. There could be something that for any reason triggers weird strokes that becomes transparents. Does the bug happen anyway if the shapes instead of stroked are filled? can you try?

**Comment by TmanTman** [comment]
Thanks for the reply.

With a 100% fill and a stroke of 0, the problem persists.

Image and video:
![Screenshot 2020-03-02 at 12 24 03](https://user-images.githubusercontent.com/3293478/75668634-44eb5a00-5c82-11ea-985e-2bada4c0b108.png)
[Video](https://aerobotics-angular-styleguide.s3.eu-central-1.amazonaws.com/filled_annotations.mp4)

From what I understand from the caching article (http://www.fabricjs.com/fabric-object-caching) caching isn't very effective if there are a lot of small objects, but it does help for large objects like large SVGs. Seems like for my specific case the solution is to disable the cache.

For the sake of other users - is there a way to know if we're over-using fabric's cache, and that it's going over Chrome's limit?

**Comment by asturur** [comment]
Well as you see up to chrome 79 over using had a different limit.
I do not know if there is a certain way to know it, maybe is more a general understanding of what the code is doing and which could be the limit of a browser/hardware acceleration.

We could add a list of a situation in which you should not use caching to that doc.

**Comment by TmanTman** [comment]
Thanks @asturur .

My issue is solved then. I can make a PR to the docs to list some situations of when to cache, and when not to.

Perhaps it would be useful for me to also document how to use Memory/Profile developer tools in Chrome to identify when this will be an issue? I'm not sure what functions I should be looking for there, if you can advise I'll include that in the PR? I'm just hesitant that the documentation might get out-of-date as Chrome/other browsers update.

Thanks for the help.

**Comment by asturur** [comment]
@TmanTman please feel free to improve the doc with your experience, we can review it as soon as you want to write something.
