### ISSUE TITLE
Blurry rendering on retina screens for groups with clippath (RETINA)

### ISSUE THREAD

**Issue by niels-van-den-broeck** [fabricjs/fabric.js#6188]
## Version
3.6.2

## Test Case
https://codesandbox.io/s/optimistic-platform-4fkgw
- keep an eye on the image
- press reveal button.

## Information about environment
Nodejs or browser? browser
Which browsers? all major browsers

## Steps to reproduce
render an image
overlay it with another image (group with image that has clippath)
blurry rendering is mainly visible on a retina screen

## Expected Behavior

It renders the same

## Actual Behavior

The image in a group with clipPath renders blurry.

**Comment by asturur** [comment]
Sorry, in the fiddle is not clear what is happening.
Can you be more specific on blurryness?
We know that clipPath can have blurry edges, and that is a tracked bug.
What else are you experimenting?

**Comment by niels-van-den-broeck** [comment]
The entire image rendered over the original one is blurry.

I think this may have something to do with objectCaching since the overlay image is in a group.
In this fiddle this may not be necessary but in our projects use case it is.

I have attached some screenshots from our project to clarify
![Screen Shot 2020-03-02 at 8 52 40 AM](https://user-images.githubusercontent.com/39048448/75656010-55400c80-5c63-11ea-9121-9db33f19c14d.jpg)
![Screen Shot 2020-03-02 at 8 52 49 AM](https://user-images.githubusercontent.com/39048448/75656012-56713980-5c63-11ea-8cf8-36435dbfd952.jpg)

**Comment by niels-van-den-broeck** [comment]
When disabling the objectCaching, rendering is sharp, but any clipPaths with globalCompositeOperation: destination-out, use destination-out on the canvas instead of the group.

**Comment by asturur** [comment]
Ok is just super unclear to me what are you clipping from the example, i can't see it.

Clipping require caching.

Cutting/cropping a rectangular shape of an image does not require clipping tho and can be done without caching. ( look for cropX, cropY, width, height properties on the image object)

Also cache can be bigger and reduce blurriness ( up to the size of the maximum canvas if you have few objects ).

Look for how to do it here:
http://fabricjs.com/fabric-object-caching

**Comment by niels-van-den-broeck** [comment]
I understand. Thanks for taking the time. I tried to simplify the example since the actual implementation is quite big to put in the fiddle. So I tried to add the minimal steps to reproduce

Our usecase is the following.

We have an application which displays schoolbooks.
These schoolbooks consist of 2 layers, a booklayer, and an answerlayer.

Teachers have the ability to reveal/hide parts of the upper layer (answer layer) by dragging a rectangle. A teacher has the ability to reveal a shape, and then hide part of it again. So what we basically have is a list of shapes which can be revealed/hidden. To accomplish this we basically render a group with cutouts of the upper image. Where we use destination-out to hide things inside of the group, and source over to reveal.

**Comment by asturur** [comment]
So to make the cutouts with cover/reveal i think that you can use the clipPath property `inverted`.

http://fabricjs.com/clippath-part4

normal clipPath is a reveal, inverted clipPath is a cutout.
I say this because globalCompositeOperation has been left a bit abandoned since the introduction of caching and the api could change a bit around it in fabricjs.

The best way to have it crisp is to enlarge cache size. You can have the cache size as big as the biggest canvas size of the browsers you support. Ie11 is 5000 pixels ( 5000x5000 ) while chrome/firefox can go up to 14000 i think. ( 14000x14000 ) just cut it around your page sizes basically.

**Comment by niels-van-den-broeck** [comment]
we have tried to do use the inverted property. 
This didn't seem to support our use case though. 

I will try my best to adapt the fiddle to our specific case and I'll give you a heads up when that is done.

After trying to increase the cachesize I can confirm that this still does not resolve the issue.

**Comment by asturur** [comment]
cache should not be blurry if big enough. Can you screenshot this blurryness? can you compare non blurry to blurry?

**Comment by niels-van-den-broeck** [comment]
Screenshots have already been pasted above. Same result is achieved when upping the cache.

The fiddle has been adapted to lean closer to our current implementation.

**Comment by asturur** [comment]
oh i see the blur difference is really subtle, zooming on a detail would have helped maybe.

https://codesandbox.io/s/restless-snowflake-yqo33

i have enlarged the cache and the blurriness is gone ( to my eyes )

**Comment by niels-van-den-broeck** [comment]
You are right, the blur is gone. Thanks a million! 

Upping the cache does cause other issues around text which I did not expect. In the browser all is okay, in my tests I get this diff in the text on a rendered page tho:

![image diff](https://user-images.githubusercontent.com/39048448/75757682-15e0f100-5d33-11ea-9abb-97d1276f54c8.png)

**Comment by asturur** [comment]
are you doing something in particular to your text? Or just plain fabricJS text?
The font seems a custom one.
Also some fonts gets crazy after a certain size with scaling ( like emojis ).

If you can provide the font and the size that image is rendered + fontSize is used, it would be interesting to try to reproduce in plain node example and have a test around it.

**Comment by niels-van-den-broeck** [comment]
Hi asturur, 

Thank you so much for your swift replies
I have tried it without setting a font as well. 

The code used to create the text is the following:

```
  const title = new fabric.Text(name);

  title.set({
      left: x.left + Math.round(x.width) + 40,
      top: x.top,
      fontSize: 50,
      fill: '#00485E',
      // fontFamily: "'Fedra Sans Screen Regular 2', 'Open Sans', sans-serif",
      meta: 'whitepageheader',
      ...disableControls,
    });

  this.fabricCanvas.add(title);
```

**Comment by asturur** [comment]
Can you provide the `Fedra Sans Screen Regular 2` font file?

**Comment by niels-van-den-broeck** [comment]
Unfortunately it's a paid (private) font so I can't just make it publicly available

**Comment by asturur** [comment]
can you replicate with another font?

**Comment by niels-van-den-broeck** [comment]
Without setting a font the same issues occur. So I guess that would be the default font which fabricjs uses for text?

**Comment by iherasymenko** [comment]
@asturur I've just run into a similar issue. Here is a reproducer. https://jsfiddle.net/iherasymenko/2zwpfc1u/1/

**Comment by iherasymenko** [comment]
Oh, sorry. I didn't notice that is a known issue.
