### ISSUE TITLE
Feature to have SVGs perfectly fit (without drawing to canvas)

### ISSUE THREAD

**Issue by onassar** [fabricjs/fabric.js#6189]
**Is your feature request related to a problem? Please describe.**
When I add a specific SVG to the canvas using fabric (https://d1va4dndox6nvz.cloudfront.net/asstyzl8do29.svg) it defines the bounding box to be whatever the SVG has defined.

**Describe the solution you'd like**
Instead, I want the bounding box to perfectly fit around the SVG (still a rectangle, but no extra whitespace)

**Describe alternatives you've considered**
Drawing the SVG to a canvas, iterating over it's pixels, and determining the actual bounding box but searching for non-transparent pixels.

**Additional context**
Here's how it looks when I add an SVG normally:  
https://i.imgur.com/GT9zwTo.png

How I want it to look:  
https://i.imgur.com/JiCcPAz.png

**Comment by asturur** [comment]
This should be definitely possible as today.

http://jsfiddle.net/rdqzow8y/

![image](https://user-images.githubusercontent.com/1194048/75637215-489cc380-5c25-11ea-9a8f-2e596bf0b549.png)

Width/height of the SVG gets passed to the group options ( this happens with the standard code, but no fiddle, no idea what code are you using ). Deleting width/height from the options passed to the parser's callback should be enough to force fabric to calculate the right bounding box starting from parsed objects only.

**Comment by onassar** [comment]
Thanks this helps a lot!
Here's a fork that shows some problems, though:
http://jsfiddle.net/huvs9wqn/

Because the SVG is part of a sprite, it seems to break that flow :(

**Comment by asturur** [comment]
In that case would help the old issue of having a parser that can respect groups, while the standard one is discarding them.
I have the code to recreate groups post parsing, i have to ask if i can release it.

**Comment by onassar** [comment]
The fork is for 3.6.1
Instead, I'll create forks with 4.0.0-beta7 so things can properly be tracked and tested.
