### ISSUE TITLE
canvas.imageSmoothingEnabled is not used on canvas.toDataURL()

### ISSUE THREAD

**Issue by robsch** [fabricjs/fabric.js#6194]
## Version
3.6.2

## Test Case
https://jsfiddle.net/robsch/87pxdLaw/

## Information about environment
Nodejs or browser?
Firefox, Chome, Opera

## Steps to reproduce

- Create an canvas with setting 'imageSmoothingEnabled' to false.
- Create an image object.
- Scale the image (enlarge it).
- Put the image onto the canvas.
- Call toDataURL with format png (you can add an multiplier to better see the result).

## Expected Behavior
The exported image should exactly be what is in canvas.

## Actual Behavior
The exported image is blurry. It looks like as if 'imageSmoothingEnabled' was not taken into account.

## Thoughts

- Is it a bug? Or do I anything do wrong? If it is a bug, what would be a workaround for this version?
- Actually, a related second issue is probably the toSVG() method. To get a exact copy of the canvas `image-rendering='crispy-edges'` should be set in the svg.

**Comment by asturur** [comment]
so crispy-edges is a feature, definitely worth adding.
The other is a bug.

i think we also support per object imageSmoothing, did you try enabling it only on the image?

**Comment by robsch** [comment]
Okay. How should that per object imageSmoothing work? If I search for 'smooth' in all fabrics project files, I can only find things regarding imageSmoothingEnabled.

**Comment by asturur** [comment]
ok let me check... anyway the bug will be fixed, and if you want you can look at the toCanvasElement  implementation and start a pr by yourself.

**Comment by robsch** [comment]
I just have tried the following at [this line](https://github.com/fabricjs/fabric.js/blob/19230c29020671ebe31405f08e7d8cc3b27dfe1c/src/mixins/canvas_dataurl_exporter.mixin.js#L85): 

      // this.renderCanvas(canvasEl.getContext('2d'), this._objects);
      var ctx =  canvasEl.getContext('2d');
      ctx.imageSmoothingEnabled = false;
      this.renderCanvas(ctx, this._objects);

Then the smoothing is gone. Setting this as an option would be quite easy, if the parameter 'cropping', which is an object, gets evaluated for 'imageSmoothingEnabled'. The parameter could be renamed to 'options'. Then it would look like this:

    toCanvasElement: function(multiplier, options) {
        .... 
        var ctx =  canvasEl.getContext('2d');
        ctx.imageSmoothingEnabled = options.hasOwnProperty('imageSmoothingEnabled') 
            ? options.imageSmoothingEnabled 
            : true;
        this.renderCanvas(ctx, this._objects);
        ....
        return canvasEl;
    },

When I use no multiplier, the image looks exactly the same, IMO. However, if I use a multiplier of 2 the image is not exact. What surprises me, since I would expect that each pixel gets mapped to 4 pixels with the same color (1x1 mapped to 2x2 pixels). But that could be caused by the scaling of the image in the canvas?

I'm not sure what I want: exactly the pixels of the canvas or, let's say, the best result.

Sorry, I'm unable to do PRs. Don't know enough of git/github and your policies.

**Comment by robsch** [comment]
Though it would be nice to have a canvas setting, inserting crisp-edges into SVGs seems to be easy:

        let svg = canvas.toSVG({suppressPreamble: true, width: 500, height: 500}, function (svg) {
            if (/<image /.test(svg)) {
                return svg.replace(/<image /, '<image image-rendering="crisp-edges" ');
            }
            return svg;
        });

**Comment by robsch** [comment]
I think it goes beyond that bug, but it would be actually really nice if the disabled smoothing refers to images only. Not to the whole canvas. Since all objects (text, rect, ...) are now also not smoothed, when I apply the modified toCanvasElement function, that I have proposed.

**Comment by asturur** [comment]
rects, texts, paths are not smoothed because they get cached and they get drawn as images.
Let's see what is the best way to fix this, but definitely should be fixed.

**Comment by hmwl** [comment]
enableRetinaScaling: true,//Retina HD
multiplier: 1,//Scaling Ratio

**Comment by hmwl** [comment]
`enableRetinaScaling: true,//Retina HD
multiplier: 1,//Scaling Ratio`

**Comment by hmwl** [comment]
`enableRetinaScaling: true,//Retina HD`
`multiplier: 1,//Scaling Ratio`

**Comment by asturur** [comment]
just one thought:
`imageSmoothingEnabled` affects images only.
It may make sense to know this at fabricJS level and setting off per object type instead of having it global.
This meaning that the setting is global but instead of being switched once, we set it on/off depending on the object we are drawing

**Comment by robsch** [comment]
Man... Hard times in Italy. I feel with you. Also because it is not unlikely that we're getting the same situation here in Austria. Good luck too you!

**Comment by asturur** [comment]
I have a PR fixing the bug and implementing the per object value.
Missing the SVG part yet.
