### ISSUE TITLE
Shape over event issues 

### ISSUE THREAD

**Issue by alexmelo23** [fabricjs/fabric.js#6200]
Hi,
I have some problem with my polygon shape,
I use over event but event firing before I going over shape  

I attaching a gif file 

How I can fix it ?

Thank you

![captured (2)](https://user-images.githubusercontent.com/8425147/75778793-1db78a00-5d61-11ea-8eb2-f07e63eb30d0.gif)

**Comment by asturur** [comment]
http://fabricjs.com/docs/fabric.Object.html#perPixelTargetFind

**Comment by asturur** [comment]
I have no idea what is that picture you posted. Feels disgusting to me. Next time can you post something less biologic/fleshy and more abstract/geometric/plain/non-living? Thanks.
