### ISSUE TITLE
setControlsVisibility not working properly in 4.0.0-beta7

### ISSUE THREAD

**Issue by onassar** [fabricjs/fabric.js#6201]
## Version
`4.0.0-beta7`

## Test Case
http://jsfiddle.net/h30rmxwq/

## Information about environment
Chrome browser

## Steps to reproduce
Launch fiddle; specifically, set the controls visibility on two different objects.

## Expected Behavior
Each object should have their respective control visibility adhere to.

## Actual Behavior
The options passed to `setControlsVisibility` override previous objects drawn to the canvas.
This was not happening in `3.6.0`

**Comment by asturur** [comment]
Yes defintely something to be improved.
We coud need to move back the control visibility per object to do not disrupt functionality.
Are you interested in per Class of objects or per single object?

The idea would be mantain what fabric does today and provide examples on how to do differently.

I do not remember what fabric does today.

**Comment by onassar** [comment]
I'm doing it on a single object.
Today, it works on an individual object. Will it work that way in 4.0.0 as well?

**Comment by asturur** [comment]
yes the idea is mantain current functionality and open for customization. this can be fixed restoring some stuff deleted.

**Comment by onassar** [comment]
Okay. Let me know when you've committed a change and I can test it.
I'm actively working on 4.0.0-beta7, and will happily test whatever changes you make. I'm here to help :-P

**Comment by onassar** [comment]
Was this fixed in a recent commit?

**Comment by asturur** [comment]
i do not think so.

**Comment by onassar** [comment]
Okay thanks!

**Comment by onassar** [comment]
Awesome! I'll test this when a new beta gets pushed up!

**Comment by alcasas** [comment]
I see similar behavior in 5.2.1, do you have a workaround or a fix?

**Comment by sakonexus** [comment]
Still might not be fixed. JSON shows the options are there for `setControlVisibility`, but controls are still showing.
