### ISSUE TITLE
toSVG undesirable trailing space on text-decoration="underline " 

### ISSUE THREAD

**Issue by ilbrigz** [fabricjs/fabric.js#6205]
## Version
3.6.0

## Test Case
http://jsfiddle.net/ilbrigz/eu694kjb/1/

## Information about environment
Browser
## Expected Behavior
toSVG()  to add
`text-decoration="underline" `
prop to svgs
## Actual Behavior.
toSVG() adds
`text-decoration="underline " `
with a trailing space after the underline. Could be problematic when using the svg with other libraries

**Comment by asturur** [comment]
i think is still in specs, but i have no problem fixing it.
Why do you think the space is undesirable?
