### ISSUE TITLE
How animation rotates at center

### ISSUE THREAD

**Issue by shijunfeng** [fabricjs/fabric.js#6206]
obj.animate('angle','+=720', {
            onChange: canvas.renderAll.bind(canvas),
            duration: 500,
            easing: fabric.util.ease.easeInOutCubic
        });

**Comment by awehring** [comment]
See: http://fabricjs.com/docs/fabric.Circle.html#centeredRotation

**Comment by asturur** [comment]
you can also write an animation that uses Object.rotate in the onChange.

Please continue on this discussion with a stackOverflow question.
