### ISSUE TITLE
 text can't enter editing on android

### ISSUE THREAD

**Issue by billywong0703** [fabricjs/fabric.js#6212]
## Version
3.6.0

## Test Case
https://streamable.com/86t4v

## Expected Behavior
Double click can enter to editing mode.

## Actual Behavior
sometimes work, sometimes will be zoom in.

test on android 8.x 9.x

**Comment by asturur** [comment]
double tap can trigger different behaviour on phones, you have to set you viewport meta tags to avoid zooming as much as possible.
There is not a workaround for it.

There are also strange interactions with cursor positioning and keyboard suggestions on android
