### ISSUE TITLE
Textbox can't be edited after adding to another canvas

### ISSUE THREAD

**Issue by shanicerae** [fabricjs/fabric.js#6213]
## Version
3.6.0

## Test Case
http://jsfiddle.net/2m0gvbc1/18/

## Information about environment
Browser (Chrome)

## Steps to reproduce
Edit a textbox in a canvas.
Remove said textbox from canvas, create new canvas, and then add said textbox to new canvas.
-> User can only type on initial click. This is because the `hiddenTextarea` on the Textbox does not get focused upon second click. This seems to be a side-effect of `onClick` not getting bound to the second canvas because `_clickHandlerInitialized` on the Textbox is false.

## Expected Behavior

User should be able to type in a textbox that has been removed from a canvas and added to another canvas. A textbox's `hiddenTextarea` should get focused upon every click and a textbox should have `_clickHandlerInitialized` set to false when removed from the canvas that the click handler was added to.

## Actual Behavior

The `hiddenTextarea` on a Textbox doesn't always focus on click causing users to not be able to type in a textbox that has been added to canvases other than the first one that `initHiddenTextarea` was called in.

**Comment by asturur** [comment]
hi @shanicerae thanks for pointing out the issue in so much detail.
I ll give it a look asap.

**Comment by asturur** [comment]
Sorry for not getting back sooner.

**Comment by ShaMan123** [comment]
ancient and seems fixed
