### ISSUE TITLE
Getting the animated value at specific point of time during the animation

### ISSUE THREAD

**Issue by boraturant** [fabricjs/fabric.js#6217]
I am seeking ways to render object animations frame by frame (to generate FFMpeg video)

I need to get the animated value at a specific point of time during the animation.

rect.animate('left', 500, {
  duration: 3000,
  easing: fabric.util.ease.easeOutBounce
});

For example, I need to get the 'left' value at 1000ms in an 3000ms animation.

Searched the code, looks like a feature request, any comments? Thanks!

**Comment by AdamMadrzejewski** [comment]
The animation function has onChange callback that is executed on each change and returns 3 values:

1. Currently animated property value
2. Value in percentage
3. Time in percentage

```
rect.animate('left', rect.left === 100 ? 400 : 100, {
    duration: 2000,
    onChange: function(current, valuePerc, timePerc) {
      if (parseFloat(timePerc.toFixed(2)) === 0.5) {
          console.log('Half time of the animation.')
      }
      
      canvas.renderAll()
    },
    onComplete: function() {
        console.log('End of the animation.')
    },
    easing: fabric.util.ease.easeOutBounce
})
```

Check this CodeSandbox https://codesandbox.io/s/github-fabric-js-animation-time-callback-t2fq0

**Comment by usama-gh** [comment]
@AdamMadrzejewski 
Sorry for sliding into this thread. Just want your input.
I want to grab each animated frame (DataURL)
I've got the code working but sometime it gives me less frames and sometimes more as it depends on CPU processes. So this is the problem. As i'm merging those photos to create videos using FFMPEG.

Here's my code. Would appreciate your answer.
 ```
function animateText(){
        	
            var topani = 100;
            var opac = 1;
            normalText.animate({left: topani, opacity: opac}, {
                duration: 4000,
                onChange: function(){
                q++;
                  var framed = canvas.toDataURL();
                          console.log(q);
                          console.log(framed);
                },
                easing: fabric.util.ease.easeOutExpo,
                  })
          
        
        }
```

**Comment by AdamMadrzejewski** [comment]
I had a look at the source code. Knowing JavaScript I can tell that you can't expect the callback to be executed exactly at the same rate or with a same time interval difference. I think if you run an infinite loop during the animation then it will trigger the animation callback only a few times? This is because of the event loop, check this video to understand it better: https://www.youtube.com/watch?v=8aGhZQkoFbQ

I am not an expert in the canvas and animations, but I can't think of any reliable way of doing this. Maybe @asturur could know something more about it.

**Comment by asturur** [comment]
if you want to be constant with the 16ms timing, you could play the animation step by step by yourself. There are the animation interpolation in fabric utils, but you can use any from another library.
Apply the properties to the object, render a frame, and move to the next step.

**Comment by asturur** [comment]
I m not opposed to have this available with our current functions, unless the code is too much, i m also unsure if fabric should maintain its own animation branch, it made sense in 2010 i m not sure it make sense anymore.

**Comment by boraturant** [comment]
ok, I ended up using  fabric.js easing functions  ( e.g. fabric.util.ease.easeOutCubic) inside my requestAnimationFrame loop.
				
current = easing(currentTime, startValue, byValue, duration)

closing, thanks!
