### ISSUE TITLE
What is the equiv for filters in 3.6?

### ISSUE THREAD

**Issue by brandnamewater** [fabricjs/fabric.js#6223]
## Version
3.6.0

## Test Case
http://jsfiddle.net/mDfZs/57/ (change to 1.7 with any jquery version)
## Information about environment
The filters work in version 1.7 or less

Tried this a handful of times
http://jsfiddle.net/nu23m45y/
error: fabric.Image.filters.Blend is not a constructor

My goal is to apply a multiply effect a layer above the background image.  For example, this is how the fabricjs example does this: https://printio.ru/full_print_tees/new (I assume).  This is how it works in photoshop so it shouldn't be any different.

What is the way to accomplish this in 3.6?

**Comment by asturur** [comment]
http://fabricjs.com/fabric-filters

Have a look at the conversion suggestion below. You have probably to use BlendColor or BlendImage
