### ISSUE TITLE
Fabric to svg text is moved to left

### ISSUE THREAD

**Issue by sidh01** [fabricjs/fabric.js#6225]
I am using fabric load svg from string and when I do to svg the text position moved towards left .
you can check below link and click to svg button and see console log  
https://codesandbox.io/s/gifted-engelbart-166wg

**Comment by sidh01** [comment]
I have tried with removing tspan as most of the people suggesting but that didn't help.
Also if I am using textbox and then do tosvg the multiline text is generated with tspan

**Comment by asturur** [comment]
Yes, TSPAN are not supported, and when you export an SVG you can't import it back with text.
This is already tracked in another issue

**Comment by fusionbeam** [comment]
@asturur  
can you please specify which issue is tracking this? maybe we can contribute a fix ...

**Comment by asturur** [comment]
#1280

**Comment by asturur** [comment]
There is already some code available, text style implement dy attribute and using dx and dy is possible to position TSPAN correctly. All the rest is XML traversing of tspans.
