### ISSUE TITLE
Strange behaviour when re-adding an SVG to the canvas (undo/redo history)

### ISSUE THREAD

**Issue by maniac0s** [fabricjs/fabric.js#6230]
I have in my project implemented an undo/redo history function. To save memory, I chose not to save the whole canvas as a JSON but each object to the history list individually. It works without problems for everything except "group" (in this case SVG which is a group of paths). I use Fabricjs in a React app but that shouldn't matter since for adding and removing to canvas I use fabricjs methods only.

Here is how I save the history in an array of objects with past, present and future lists. This is ran on object:add. object:modified and object:removed events in a react hook that triggers on canvas changes:

            if(!lockHist.current){
                e.target.event = type;

                setHist(({past, present, future}) => {
                    past = [...past, present];
                    present = copyObj(e.target); //see below
                    future = [];

                    return {
                        past,
                        present,
                        future
                    };
                });
            }

Since objects in Javascript are by reference, I made a function copyObj that returns a copy not a reference of the given object:

    const copyObj = (obj) => {
        let copy = {};
        let key = 0;

        for(key in obj) {
            copy[key] = obj[key];
        }

        return copy;
    }

On undo or redo I take the specific entry from the history list past or future, replace present with it and insert it at the canvas at the object's original position that I saved in a custom prototype {id: object_position}. Example from undo function:

        const lastEvent = hist.present.event;

        setHist(hist => {
            let { past, present, future = [] } = hist;
            past = [...past];
            future = [...future, present];
            present = past.pop();

            if(lastEvent === "add") {
                console.log("removed.");
                canvas.remove(canvas.item(hist.present.id));
            } else {
                present.objectCaching = false;
                canvas.insertAt(present, present.id, true);
            }

            canvas.renderAll();

            return {
                past,
                present,
                future
            };
        });

Now this works for all objects, text, shapes such as rect, circle ect. I can walk endlessly back and forth through the history flawlessly. But when I use it on an imported SVG, strange behaviour happens: First and most obvious is that the object gets pushed to the right and bottom while the selector handle square stays in place.

See the following screenshots.

Feshly added SVG:

![Screenshot_2020-03-25_10-17-36](https://user-images.githubusercontent.com/12167035/77520944-3f98be00-6e82-11ea-8439-cdeec37d9014.png)

After undo (removes object) and redo (adds it again):

![Screenshot_2020-03-25_10-18-15](https://user-images.githubusercontent.com/12167035/77520956-43c4db80-6e82-11ea-8e2a-149693f15585.png)

When I redo once more the object is missaligned even further outside of the selector frame.

This does never happen with other, simpler objects like basic shapes or texts, only appeared on SVG so far I can tell.

I don't know if that's a problem caused by copying the object in my function or if this is a bug so I post it in this section.

**Comment by asturur** [comment]
I think the issue is that you can't copy objects like that.
Is unclear if e.target is a fabric.Object subclass.
If it is, you can't copy it like that, you need to do target.toJSON and store that representation somewhere  in your history
A shallow copy is not enough since fabric objects can have nested properties some level deep ( group of groups, gradients, patterns )
