### ISSUE TITLE
Some images fail to load

### ISSUE THREAD

**Issue by Shohin93** [fabricjs/fabric.js#6231]
After updating to `Fabric 2.7.0` and `Node 10.16.0` in **Amazon Linux AMI**, a couple of images fail to load (but they did load without problem in `Fabric v1.x`). I get the following error:

```
Error: the surface type is not appropriate for the operation
    at /app/node_modules/canvas/lib/pngstream.js:43:19
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Locally on Mac and Ubuntu, those images load successfully 😕. 

I pass **data-url** of an image to `fabric.Image.fromURL()` API, and I suppose the error is coming from there.

I have the following node-canvas dependencies installed (from the docs https://github.com/Automattic/node-canvas/tree/v1.6.13):
`yum install cairo cairo-devel cairomm-devel libjpeg-turbo-devel pango pango-devel pangomm pangomm-devel giflib-devel`

**package.json:**
```
"dependencies": {
    "color-diff": "1.1.0",
    "fabric": "2.7.0"
  },
  "peerDependencies": {
    "canvas": "^2.5.0",
    "jsdom": "^15.1.0"
  }
```

Does anybody have any ideas on what the fix would be ?

**Comment by asturur** [comment]
I'm not sure how canvas 2.5.0 and canvas 1.6. can cooperate.
Did you try bumping up to fabric latest 3.6, the difference with 2.7 are minimal and the node-canvas version is aligned to work with latest jsdom.
