### ISSUE TITLE
Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded.

### ISSUE THREAD

**Issue by manhthepixta** [fabricjs/fabric.js#6232]
I'm using Amazon S3 and cloud front. The image url look like `https://t.pimg.jp/061/089/535/2/61089535.jpg`

My code look like
```
const imgUrl = https://t.pimg.jp/061/089/535/2/61089535.jpg
fabric.util.loadImage(imgUrl, function(imgObj) {
    const oImg = new fabric.Image(imgObj, {
        crossOrigin: 'anonymous',
    });
});
```

The image loaded successfully. But when I apply filter to that image, the error appears.

Already applied the cors config at s3 bucket
```
<CORSConfiguration>
 <CORSRule>
   <AllowedOrigin>*</AllowedOrigin>
   <AllowedMethod>GET</AllowedMethod>
   <AllowedHeader>*</AllowedHeader>
 </CORSRule>
</CORSConfiguration>
```

Do anyone know how to fix?

<img width="1113" alt="Screen Shot 2020-03-25 at 10 06 47" src="https://user-images.githubusercontent.com/49050122/77632901-36424b00-6f81-11ea-9f8f-d5c06b48b7a7.png">

**Comment by asturur** [comment]
You have to setup your CORS headers.
Please make a research around Cross Origin Resource Sharing, is out since some years and is mandatory to know in order to work with canvases, or you can't use images that do not come from your domain.

**Comment by asturur** [comment]
Sorry i first answered to the automatic email, that did not contain the snippet about configuration of headers.
You are loading the image wrong,
http://fabricjs.com/docs/fabric.util.html#.loadImage

crossOrigin options must be set when the image is loaded, not after is loaded inside the callback.
