### ISSUE TITLE
Problem with setDimensions cssOnly

### ISSUE THREAD

**Issue by alexmelo23** [fabricjs/fabric.js#6234]
Hi,

I add cssOnly property and 100% width and height everything works perfect
but If I create a simple Rect I get wrong dimensions
`   canvasEl.add(new fabric.Rect({
            top: 10, left: 0, width: 80, height: 50, fill: 'red'
        }))
`
![Untitled-1](https://user-images.githubusercontent.com/8425147/77672640-cf795d80-6f91-11ea-91f7-83b91128378f.jpg)

Does any Idea fix it?
thanks

**Comment by asturur** [comment]
Hi @alexmelo23 , is completely unclear what are you asking.
Please provide a better explanation and a js fiddle

**Comment by alexmelo23** [comment]
> Hi @alexmelo23 , is completely unclear what are you asking.
> Please provide a better explanation and a js fiddle

https://stackblitz.com/edit/react-y3u9jw

**Comment by asturur** [comment]
because you are stretching the canvas with css. So things are stretched.
