### ISSUE TITLE
fabric-with-gestures - this._setObjectScale/transform.actionHandler is not a function

### ISSUE THREAD

**Issue by lizy0329** [fabricjs/fabric.js#6235]
## Version
3.6.1

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Nodejs or browser? 10
Which browsers? chrome

## Steps to reproduce
```javascript
import { fabric } from 'fabric-with-gestures';

            var canvasEl = document.getElementById('canvas');
            var ctx = canvasEl.getContext('2d');
            var canvas = new fabric.Canvas('canvas');

            var triangle = new fabric.Triangle({
                left: 200,
                top: 150,
                strokeWidth: 1,
                width: 170,
                height: 190,
                stroke: 'black',
                fill: '#ff8a1b',
                selectable: true,
                originX: 'center'
            })

            canvas.add(triangle);

            canvas.on({
                'touch:gesture': function() {
                    var text = document.createTextNode(' Gesture ');
                    info.insertBefore(text, info.firstChild);
                },
                'touch:drag': function() {
                    var text = document.createTextNode(' Dragging ');
                    info.insertBefore(text, info.firstChild);
                }
            });
```

## Expected Behavior
successful to scale ro rotate

## Actual Behavior
mobile chrome console show:

`this._setObjectScale is not a function`
`transform.actionHandler is not a function`

**Comment by GabrieleCicconetti** [comment]
Did you solve this? :(

**Comment by asturur** [comment]
Hi @GabrieleCicconetti  no this was closed by the owner, anyway on latest v4 the pinch gesture does not work and that is a known issue

**Comment by GabrieleCicconetti** [comment]
Hi @asturur thank you for the response. After my last comment i searched a bit more and found this http://fabricjs.com/lib/fabric_with_gestures.js . In this build the gestures works, maybe this can be useful for you (if you don't already know that)

**Comment by lizy0329** [comment]
> Hi @asturur thank you for the response. After my last comment i searched a bit more and found this http://fabricjs.com/lib/fabric_with_gestures.js . In this build the gestures works, maybe this can be useful for you (if you don't already know that)

I change Konva.js + Hamer.js, It suit for me

**Comment by asturur** [comment]
hammer.js definetely is more modern and working better for gestures, also connecting fabricjs to hammer.js is easy enough

**Comment by GabrieleCicconetti** [comment]
Hi again @asturur, i have read something about fabricjs+hammerjs but for my understanding i can only bind a DOM object to hammerjs gestures not a canvas object.

**Comment by lizy0329** [comment]
> Hi again @asturur, i have read something about fabricjs+hammerjs but for my understanding i can only bind a DOM object to hammerjs gestures not a canvas object.

yes, I don't find any document for fabricjs+three-part gesture lib, so I use Konva.js + Hammer.js

By the way, fabricjs is too old

**Comment by asturur** [comment]
`By the way, fabricjs is too old` :)
When being old is a problem?

**Comment by asturur** [comment]
@GabrieleCicconetti i found myself good attaching hammerJS to `fabricCanvas.upperCanvasEl` if you send me an email i can send you some examples.

**Comment by GabrieleCicconetti** [comment]
Thank you very much @asturur i found something like this https://github.com/fabricjs/fabric.js/issues/5083. But i think this is only to zoom the entire canvas. Am i right?

**Comment by asturur** [comment]
@GabrieleCicconetti   the integration with the current gestures library is fixed with the commits of today.
You can find a build here:
http://fabricjs.com/lib/fabric_with_gestures.js

In my opinion hammer.js, on some fork of someone mantaining it, is a better choice than event.js.
i have a full integartion with hammer.js working but i can't pull it out yet.

**Comment by GabrieleCicconetti** [comment]
Thank you so much for your work on this library and the effort you put. Grazie Andrea!!!!

**Comment by GabrieleCicconetti** [comment]
Hi @asturur did you try the multitouch gesture? it doesn't seems to work correctly :((

**Comment by asturur** [comment]
i tried on my android phone, it does scale with 2 fingers.

**Comment by asturur** [comment]
@GabrieleCicconetti in general, a message like this, is wasted time for you.
I got the email, i get here to answer that it works for me, and i wait your next message.
We do not know when i ll replay to the next message, it depends how is my day or my week.

Come, put a link where the thing is obviously not working, explain in what condition it does not work, and you help me helping you.

**Comment by GabrieleCicconetti** [comment]
@asturur my fault, you are right.
this is the link http://gabrielecicconetti.altervista.org/canvas/
this is the code:
`let canvasObj = new fabric.Canvas('c', {
      backgroundColor: '#333',
      width: 300,
      height: 500,
    });
    fabric.Image.fromURL('./assets/images/dash.jpg', (oImg) => {
      canvasObj.add(oImg);
      canvasObj.renderAll()
    });`
For me it does scale and rotate but the image does not stay in the center of my fingers. Thank you and sorry for the previous useless message
