### ISSUE TITLE
How to increase the number of Control Points?

### ISSUE THREAD

**Issue by juzhiyuan** [fabricjs/fabric.js#6237]
**Is your feature request related to a problem? Please describe.**
After going through the docs and stackoverflow, I still cannot find that how to increase the number of Control Points.

**Describe the solution you'd like**
When we double click the fabric object, it could show more control points.

**Describe alternatives you've considered**
None

**Additional context**
Current:
![image](https://user-images.githubusercontent.com/2106987/77837881-ea6dec80-71a0-11ea-85a9-ac2abba84716.png)

Expect:
![image](https://user-images.githubusercontent.com/2106987/77837883-f35ebe00-71a0-11ea-9634-5d4cac686864.png)

**Comment by asturur** [comment]
this will be possible with the new control api.
Won't be a fabric feature tho,
so you have to write it yourself.

Hopefully i can make this exact example in the docs, is not super easy i have to say.

**Comment by juzhiyuan** [comment]
Thanks for your reply!
