### ISSUE TITLE
Additional filters (mask and colourize/duotint) and code reuse.

### ISSUE THREAD

**Issue by aleph1** [fabricjs/fabric.js#624]
I am using Fabric.js for an upcoming project, and have created two custom filters — one for masking an image based upon another image, and another that colourizes an image based on a set of two colours. In the process of creating the masking filter, I also identified some code that could be moved to utils to simplify the creation of filters that require two images an inputs like my mask one does.

Should I submit a pull request for the filters and/or the core code change?

**Comment by vijaygurjar** [comment]
Hi,

I have added mask image by another png image by referring "http://resources.aleph-1.com/mask/"
But mask not properly applied. Please help me to apply png mask over another image. I am just new in HTML5.

Regards,
Vijay

**Comment by DanieleSassoli** [comment]
@vijaygurjar, give a look at #2531 .

**Comment by vijaygurjar** [comment]
Thanks @DanieleSassoli. Its working fine for me.
I have one query:
I want to zoom and pan inner image not selection area is it possible.

**Comment by DanieleSassoli** [comment]
I wouldn't know how to do this with standard fabric image class, I have created my own class to accomplish this( and a lot of other feautres), which  I hope I will be able to commit in the main fabricjs repo in a near future.
