### ISSUE TITLE
Shape 

### ISSUE THREAD

**Issue by hamzawain7** [fabricjs/fabric.js#6240]
## Version
3.6.2

## Test Case
http://jsfiddle.net/hamzawain7/nvc214mk/

## Steps to reproduce
1. Open the jsfiddle
2. The multi path vector is going out of bounds
3.  Scaling the item crops the part outside the bounds

## Expected Behavior
The vector should remain within the bounding box

## Actual Behavior
1. The vector doesn't remain within the bounding box and it crops the part outside the bounds sometimes when scaling

- [Getting out of bounds](https://drive.google.com/file/d/177O2_Ab7Nr4xUp8QntA4H1z7ONFzfINR/view?usp=sharing)
- [Getting cropped](https://drive.google.com/open?id=1WC0D27btgOPbCPRWYWoX2AxpDVD7qksl)

2. Another thing I noticed is the uniformStroke doesn't work for multi path vector. Is that normal?

**Comment by asturur** [comment]
http://jsfiddle.net/o4w72bu8/

Sorry for not answering before. Had been busy.
You are changing the strokewidth after grouping the object, while you have to do it before
