### ISSUE TITLE
clipPath: how to fit the image to the canvas after cropping?

### ISSUE THREAD

**Issue by sashapavlov** [fabricjs/fabric.js#6243]
I implemented image cropping using FabricJS and clipPath property.

[Here is my jsfiddle](https://jsfiddle.net/04nvdeb1/23/)

The question is how do I make the image fit the canvas after cropping? I want the cropped image to fill the canvas area but can't figure out whether it's possible to do using fabric js.

So I want the selected part of the image to fit the canvas size after the user clicks the Crop button:

![I3DJz](https://user-images.githubusercontent.com/6662454/78070981-58830100-73a5-11ea-95ff-4235030759c6.png)

**About the code:** I draw a rectangle on the canvas and the user can resize and move it. After that, the user can click the Crop button and get a cropped image. But the cropped part stays the same size it was on the original image whereas I want it to scale and fit the canvas.

_Note:_ I tried to use methods like scaleToWidth. Additionally, I used absolutePositioned set to true for the selection rectangle. I tried to scale to image with this property set to false, but it didn't help.

Please do not suggest using cropX and cropY properties for cropping instead of clipPath as they don't work properly for rotated images.

**HTML:**

```
<button>Crop</button>
<canvas id="canvas" width="500" height="500"></canvas>
```

**JS:**

```
// crop button
var button = $("button");

// handle click
button.on("click", function(){

  let rect = new fabric.Rect({
    left: selectionRect.left,
    top: selectionRect.top,
    width: selectionRect.getScaledWidth(),
    height: selectionRect.getScaledHeight(),
    absolutePositioned: true
  });

  currentImage.clipPath = rect;

  canvas.remove(selectionRect);

  canvas.renderAll();
});

var canvas = new fabric.Canvas('canvas');

canvas.preserveObjectStacking = true;

var selectionRect;
var currentImage;

fabric.Image.fromURL('https://www.sheffield.ac.uk/polopoly_fs/1.512509!/image/DiamondBasement.jpg', img => {
  img.scaleToHeight(500);

  img.selectable = true;

  canvas.add(img);

  canvas.centerObject(img);

  currentImage = img;

  canvas.backgroundColor = "#333";

  addSelectionRect();

  canvas.setActiveObject(selectionRect);

  canvas.renderAll();
});

function addSelectionRect() {
  selectionRect = new fabric.Rect({
    fill: 'rgba(0,0,0,0.3)',
    originX: 'left',
    originY: 'top',
    stroke: 'black',
    opacity: 1,
    width: currentImage.width,
    height: currentImage.height,
    hasRotatingPoint: false,
    transparentCorners: false,
    cornerColor: 'white',
    cornerStrokeColor: 'black',
    borderColor: 'black',
  });

  selectionRect.scaleToWidth(300);
  canvas.centerObject(selectionRect);
  selectionRect.visible = true;
  canvas.add(selectionRect);
}
```

Original StackOverflow issue: https://stackoverflow.com/questions/60816668/fabric-js-clippath-how-to-fit-the-image-to-the-canvas-after-cropping

**Comment by PoddukinVladimir** [comment]
Yeah, I have the same issue.

**Comment by arlek777** [comment]
Very nice description, our team has faced it recently.

**Comment by asturur** [comment]
I'm trying to answer on stackoverflow, please check comment when you can.

**Comment by shajal-kumer** [comment]
Check out the SO link i given a solution 

https://stackoverflow.com/questions/60816668/fabric-js-clippath-how-to-fit-the-image-to-the-canvas-after-cropping
