### ISSUE TITLE
How to select the object then change color?

### ISSUE THREAD

**Issue by cct823** [fabricjs/fabric.js#6245]
Hello,

I am not sure which is the correct keyword to look for my question.
I checked the demo on the website, and there's a demo called "Kitchensink."
There's a function that changes the object color when selecting it and I have two questions on this:

1. How do I use this function with the HTML and Fabric? I am not sure what is the correct code to do it.
2. Is it possible to select multiple objects ( like all the circle objects) and change the color once?

I am new to HTML/JS/Fabric so I am not sure what is the correct keywords to loop for the answers.
Thanks in advance.

**Comment by asturur** [comment]
This a broad question.
Every object you create on fabric has a series of methods, one of those is `set`. To change the color of an object you can do `myCircle.set('fill', 'red');` for example.

If you are completely new to those i suggest you experiment a bit with it.
Refer to stackoverflow for generic question on usage.
