### ISSUE TITLE
There is a critical miss-leading bug while using scaleToWidth combined with pattern

### ISSUE THREAD

**Issue by JuxhinB** [fabricjs/fabric.js#6246]
I'm trying to make a cropper with fabricjs by getting the crop box with another library. I had the issue that I could position in the center the pattern so after many attempts I understood that the method used to make image scaleToWidth() is not making what it should. Any idea? Or am I totally wrong ?

You can try code below in a CodeSandBox
```
import React from "react";
import { fabric } from "fabric";
import "./styles.css";

const htmlCanvasWrapId = "product-editor-canvas-wrap";
const htmlCanvasId = "product-editor-canvas";

export default function App() {
  const canvasRef = React.useRef(null);
  React.useEffect(() => {
    // set canvas reference and attack events to it
    canvasRef.current = new fabric.Canvas(htmlCanvasId, {
      // @ts-ignore
      width: 600,
      height: 250,
      allowTouchScrolling: true,
      backgroundColor: "#d2d2d2"
    });

    fabric.Image.fromURL(
      "https://cdn.pixabay.com/photo/2015/02/24/15/41/dog-647528__340.jpg",

      img => {
        img.scaleToWidth(50);

        let patternSourceCanvas = new fabric.StaticCanvas();
        patternSourceCanvas.add(img);
        patternSourceCanvas.renderAll();

        let pattern = new fabric.Pattern({
          source: function() {
            patternSourceCanvas.setDimensions({
              width: img.getScaledWidth(),
              height: img.getScaledHeight()
            });
            patternSourceCanvas.renderAll();
            return patternSourceCanvas.getElement();
          },
          repeat: "no-repeat",
          /**
           * The bug is here, after using img.scaleToWidth(50);
           * the pattern instead is always twice of the value set.
           */
          offsetX: (400 - img.getScaledWidth() * 2) / 2,
          offsetY: (200 - img.getScaledHeight() * 2) / 2
        });

        console.log(img.getScaledWidth(), img.getScaledHeight());
        console.log((400 - img.getScaledWidth()) / 2);
        console.log((200 - img.getScaledHeight()) / 2);

        let obj = new fabric.Rect({
          width: 400,
          height: 200,
          backgroundColor: "gray",
          fill: pattern
        });

        canvasRef.current.add(obj);
      }
    );

    canvasRef.current.renderAll();
  }, []);

  return (
    <div className="App">
      <canvas id={htmlCanvasId} />
    </div>
  );
}
```

**Comment by asturur** [comment]
Can you provide a working fiddle?
anyway scaleToWidth will give a scale to the image so that its final width will fit in 50px.
So if the image element is 200px wide will give it a scale of 0.25

**Comment by JuxhinB** [comment]
> Can you provide a working fiddle?
> anyway scaleToWidth will give a scale to the image so that its final width will fit in 50px.
> So if the image element is 200px wide will give it a scale of 0.25

scaleToWidth(50) set the size to 100 instead.
This issue was hard to notice, I measured the size with a chrome extension ruler.
Then made the adjustments: 

```
offsetX: (400 - img.getScaledWidth() * 2) / 2,
offsetY: (200 - img.getScaledHeight() * 2) / 2
```

You can play around here https://codesandbox.io/s/keen-bose-ukgvh, but I might use this sandbox later on again to play for myself :)

**Comment by asturur** [comment]
mmm seems weird to me. Are you on a retina screen? In that case you would get 100 pixels of canvas, but condensed in 50px of screen.

**Comment by JuxhinB** [comment]
> mmm seems weird to me. Are you on a retina screen? In that case you would get 100 pixels of canvas, but condensed in 50px of screen.

Yes I'm working in a MacBook Pro, but I don't think is this the case, I mean the condensation you're talking about is not happening, the behaviour I'm describing is quite the opposite.

**Comment by asturur** [comment]
well i m not sure what are you measuring with that tool, i tried to guess.

The scaleToWidth will set the scale of the object, both x and y so that the width of the object, at zoom level 1 will be what you passed as argument.

**Comment by JuxhinB** [comment]
> well i m not sure what are you measuring with that tool, i tried to guess.
> 
> The scaleToWidth will set the scale of the object, both x and y so that the width of the object, at zoom level 1 will be what you passed as argument.

No I'm just prototyping there. I have a grid of images 3x3 set in a canvas. In another model I get the crop box size and coordinates. I need to manipulate the pattern in order to ma crop the image in place.

**Comment by asturur** [comment]
To get any help is very important to make a working snippet, or working till the part that blocks you, under our ( or my ) eyes.
Otherwise is very hard to understand what are you even thinking to do.

**Comment by JuxhinB** [comment]
I'm working on a non-open-source project and this impedes me to publish the whole code.

I use this method to mount an image on the canvas. In another dialog, I get the crop box size and coordinates. These coordinates I'm trying to adapt and interpolate in order to make the image look cropped as in the crop box.
```
fabric.Image.fromURL(url, (img) => {

    img.scaleToWidth(cellWidth / 2);

    let maskPosition: any = {};
    // Not finished yet
    if (cropBox) {
      maskPosition = {
        offsetX: cropBox.left *(cropBox.width / (img.getScaledWidth() * 2)),
        offsetY: cropBox.top *(cropBox.height / (img.getScaledHeight() * 2)),
      };
    } else {
      maskPosition = {
        offsetX: (cellWidth - img.getScaledWidth() * 2) / 2,
        offsetY: (cellHeight - img.getScaledHeight() * 2) / 2,
      };
    }

    let patternSourceCanvas = new fabric.StaticCanvas("c");
    patternSourceCanvas.add(img);
    patternSourceCanvas.renderAll();

    let pattern = new fabric.Pattern({
      // @ts-ignore
      source: function() {
        patternSourceCanvas.setDimensions({
          width: img.getScaledWidth(),
          height: img.getScaledHeight(),
        });
        patternSourceCanvas.renderAll();
        return patternSourceCanvas.getElement();
      },
      repeat: "no-repeat",
      ...maskPosition,
    });
    let obj = new fabric.Rect({
      // @ts-ignore
      id: imageId,
      customType: "image",
      lockMovementX: true,
      lockMovementY: true,
      lockRotation: true,
      lockScalingX: true,
      lockScalingY: true,
      width: cellWidth,
      height: cellHeight,
      hoverCursor: "pointer",
      fill: pattern,
    });

    imageGridPositioner(obj, cellWidth, cellHeight, left, top);
    obj.customiseCornerIcons(customControlsProps());
    canvas.add(obj);
```

**Comment by JuxhinB** [comment]
> mmm seems weird to me. Are you on a retina screen? In that case you would get 100 pixels of canvas, but condensed in 50px of screen.

I want to know more about this, please.

**Comment by asturur** [comment]
You do not have to publish your whole project, but a working version of the problem that is bothering you. A minimal reproduced case.
That is how issue handling works here. We have to understand if there is a problem with the library and how is reproduced.
If not and you are just looking for generic help with your project/job is better you refer to dedicated resources like stackoverflow.
