### ISSUE TITLE
Files svg  separation colors

### ISSUE THREAD

**Issue by jcarrest** [fabricjs/fabric.js#6248]
My svg files show transparent lines in their boundaries between color and color.
They are created without borders.
It seems to create a separation.
Should I mount one color on top of the other?
It turns out that I have all the svg the same, for their preparation for textile screen printing.

Exemple:
Load on fabric.js this file. Its a design [simple star](https://www.dropbox.com/s/s4665el1zi4bcog/estrella3.svg?dl=0).

Thank you and excuse my ignorance.

**Comment by asturur** [comment]
to me the SVG seems to load fine.
What is your problem acutally? i do not see any separaion.
