### ISSUE TITLE
Serializing objects that have been rotated by multiple selection have wrong positions after de-serializing.

### ISSUE THREAD

**Issue by defcon8** [fabricjs/fabric.js#6249]
## Version
3.6.3

Hi,

I'm building an application that uses Fabric. For the purpose of the application I can not save the entire canvas, I need to save all Fabric Objects seperately to a database table. I serialize them using the FabricJS _object.toJSON()_ method. And reconstruct them using _fabric.util.enlivenObjects()_ and adding them back to the canvas.

This works great. Except I found one particular problem:

When I select 2 objects, using the rectangular mouse selection tool. Then I rotate the selection, then I serialize and deserialize them.. now the position of the objects has been changed (also there is no rotation anymore). In most of the cases the objects have been moved out of the visible viewport or are somewhere in the top left corner.

I found out that after the rotation, the objects (seen in _canvas._objects_) get a negative _top_ and _left_ property. While this also is the case before serializing (and still viewed correctly), after serializing and deserializing they have the wrong position.

I have compared the data objects before and after. I noticed a difference in the _aCoords_ object. Before serializing it holds positive position values. And after serializing / loading they have negative values (they match the values of the _oCoords_ object).

Any suggestions?

FabricJS: v3.6.3

Kind regards.

Bastiaan

**Comment by asturur** [comment]
Objects in groups or active selections receives coordinates relative to selection center. you should serialize the active selection itself, you can t enlive back an object serialized within the active selection, without the active selection itself. Ot if you want to, first deselect it and then serialize it.

**Comment by defcon8** [comment]
Thanks! Deselecting all objects before serialization did the trick!
