### ISSUE TITLE
is there a minimap for fabric.js ?

### ISSUE THREAD

**Issue by QJesus** [fabricjs/fabric.js#6254]
An overview for the entire canvas, and drag to view details.

![image](https://user-images.githubusercontent.com/9971413/78736157-10ed0e00-797f-11ea-8df5-a778986cf31a.png)

is there something like that?

**Comment by awehring** [comment]
@QJesus: Ist unclear what you are requesting.

Please fill out the questionaire in your initial post.

**Comment by awehring** [comment]
No it's not, and as far as I know there are no plans for it. But anyone can contribute to the project.

Or you  implement it in your application. This might contain some usefull hints:

http://fabricjs.com/fabric-intro-part-5#pan_zoom

**Comment by asturur** [comment]
There is not such a thing for now, it does not require any particular fabricJS new functionality to create it.
We can make a tutorial for it. i think is completely doable.

**Comment by CharlesRA** [comment]
@asturur Is there anything new for the tutorial ?

**Comment by asturur** [comment]
I m struggling to keep up with the issues, i did not do it yet.

**Comment by kseanjbz** [comment]
I agree. This would be an awesome addition!

**Comment by asturur** [comment]
@QJesus @CharlesRA i made half of the tutorial, it took way more time than i thought it would need.
http://fabricjs.com/build-minimap

For now the turorial show how to have a minimap that reflect the canvas status, i will update it to also be a control for the main zoom + pan.

If someone has will can create an extra canvas class that this automatically and we can point to it. I do not think this should be a core feature.

**Comment by asturur** [comment]
Panning is also broken.

**Comment by CharlesRA** [comment]
Thank you ! Amazing work

**Comment by bdominguez** [comment]
@asturur any update on a complete example?

**Comment by asturur** [comment]
i didn't move from there! have been on holidays last 2 weeks and i have lot of issues and small bugs to take care of.

**Comment by CharlesRA** [comment]
I think the blue layer (minimapView variable) evented should be set on false btw :)

**Comment by asturur** [comment]
It depends if you want the minimap to be draggable or not.
It can visualize your zoom or use it to move your zoom around.

**Comment by GitHubish** [comment]
Hello @asturur, any news about a more complete example of minimap? I can't do what I would like to do to have an interactive minimap that also allows to move in the canvas and to zoom. Thanks

**Comment by Faizan2225** [comment]
@asturur I have a question Sir. I am totally new in this amazing Library. The functions you made in the tutorial `initMinimap()` and `updateMiniMapVP()`, you have call these function after loading canvas from JSON. You said `canvas.loadFromJson` and at the end you call these functions. Well, in my case, I am not loading canvas from JSON. My canvas is manually added and being edited and modified by User. So, where I can call these two functions, how can I do it?

**Comment by asturur** [comment]
i think in the demo a loadFromJson is like the start of the application.
The point is that you call init and update ONCE when your interactivity start, and then you need to call update everytime you detect an update.

**Comment by Faizan2225** [comment]
@asturur Sir, I tried that already, but it just shows a blue rectangle in `minimap` of much bigger size than `minimap` . It never updtaes even I call it every time when canvas is updated.
Anyways, I am trying to find out a solution.

**Comment by asturur** [comment]
if you have a way to show your full setup, we can see where the issue is.

**Comment by Faizan2225** [comment]
Yes offcourse, I have github repo, but it is private,can I invite you?

**Comment by asturur** [comment]
it depends how extensive is the github repo. if is enormous, no way i can look at it.

**Comment by Faizan2225** [comment]
Yes, that's right, it is extensive. About 2500 JS lines till now. And much
work is left still. Can we talk on twitter, sir?

**Comment by Faizan2225** [comment]
Sir, please check out  this
<https://stackoverflow.com/questions/70030827/restrict-drawing-area-in-fabric-js>
question, have you answer for this?

**Comment by ShaMan123** [comment]
PRs are more than welcome
[../CONTRIBUTING.md](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#pull-requests)
