### ISSUE TITLE
Broken download link on website homepage

### ISSUE THREAD

**Issue by bboyguil** [fabricjs/fabric.js#6257]
## Version
3.6.3

When visiting the homepage of the site, I noticed that the link provided at the bottom of the page is corrupted. I just want to notify them so they can make the correction.

Link not working: [link](https://cdnjs.cloudflare.com/ajax/libs/fabric.js/3.6.3/fabric.min.js)

**Comment by asturur** [comment]
thank you i just tagged the 3.6.3 on the branch, let's see if the link autofixes

**Comment by asturur** [comment]
yes now cloudflare has  the link available.
