### ISSUE TITLE
When adding a video element as an Image, the image is slightly cropped

### ISSUE THREAD

**Issue by iRonJ** [fabricjs/fabric.js#6262]
## Version
3.6.0

## Test Case
http://fabricjs.com/video-element
http://jsfiddle.net/gw16tp29/1/
## Information about environment
Safari on Mac OS

## Steps to reproduce
Load website, allow webcam.
## Expected Behavior
Webcam image should show the full field of view of the camera
## Actual Behavior
Webcam image is cut off around all edges. Setting the height/width of the "webcam" object in the console doesn't resolve the issue, neither does calling "webcam.scaleToHeight(xxx)"

It does seem setting the parameters height/width on the HTML video element itself changes the sizing, but it is not in a predictable way.

**Comment by asturur** [comment]
Can you make a fiddle that works with the webcam?

**Comment by iRonJ** [comment]
I updated the post with the fiddle URL

**Comment by asturur** [comment]
thanks, for some reason the webcam does not trigger at all in my laptop.
Maybe i disabled it.

Il giorno sab 11 apr 2020 alle ore 11:01 Ron Jailall <
notifications@github.com> ha scritto:

**Comment by iRonJ** [comment]
I did determine it was related to the attempt to correct for hi dpi displays, but haven’t dug further. Forcing a 1x dpi fixed my issue
