### ISSUE TITLE
Contrast filter on image not working correctly

### ISSUE THREAD

**Issue by mk10391** [fabricjs/fabric.js#6263]
## Version
Tested with : 3.6.1 & 3.6.3

## Information about environment
Which browsers?
IE 11 and chrome 

## Steps to reproduce
in JavaScript, applying contrast filter on a image shows same result no matter what value i provide to filter. for example 80 or -80 produce same output. This was working correctly in very early versions of fabricjs.
 imgInstance.filters[6] = new fabric.Image.filters.Contrast({
            contrast: -80
        }); 

## Expected Behavior
Contrast value should change image according to its value provided.
## Actual Behavior
Contrast value is not updating the image according to value. it does apply the filter but shows same exact changed image for all values of contrast.

**Comment by asturur** [comment]
The documentation is wrong, i checked the code and contrast take values from -1 to 1  since fabric 2.0.

there is some small guide here:
http://fabricjs.com/fabric-filters

**Comment by mk10391** [comment]
thanks... -1 to 1 works.

**Comment by asturur** [comment]
issue can't be closed because docs needs to be addressed
