### ISSUE TITLE
Scaling border distortion

### ISSUE THREAD

**Issue by matejkramny** [fabricjs/fabric.js#6264]
## Version
3.6.0 / 4 beta

## Test Case
https://jsfiddle.net/4dvwph8q/1/

## Information about environment
Browser, chrome 80

## Steps to reproduce
- open test case
- drag rect to the size of the canvas
- notice the border is distorted until the scaling action is finished (bug 1)
- uncomment potential solution in the code, notice side effect, (bug 2)

## Expected Behavior
Border should be repainted continuously. Inside the test case there's code to resize it when the `scaling` event is triggered. This solution however causes a side effect and glitches.

## Actual Behavior
Border is distorted when scaled. When finished scaling, the border is (seemingly) repainted and sharp again.

bug 1
![Screenshot_20200411_221640](https://user-images.githubusercontent.com/797608/79046224-3a898c00-7c42-11ea-9fc9-adbd54056c6f.png)

bug 2
![Screenshot_20200411_221600](https://user-images.githubusercontent.com/797608/79046223-39f0f580-7c42-11ea-886b-08648989e63a.png)

I want to achieve an effect where dragging the handles does not **scale** the rect but instead _resizes_ it. I understand the library by default scales the object. Is there a better way to do this?

Thanks!

**Comment by asturur** [comment]
http://fabricjs.com/fabric-object-caching

To resize instead of scale, you can look at the fabric 4 latest beta and look at the changeWidth control actions, created for the textbox, and use it on the rect, and create your own changeHeight.

**Comment by matejkramny** [comment]
Thanks @asturur I'll look into that. Appreciate the quick turnaround!

**Comment by matejkramny** [comment]
Cool, I've got it working. It's resizing all corners of rects and circles..

Cheers :beer:

**Comment by asturur** [comment]
that is exactly what 4.0 is about. exposing an interface for let people do things more easily
or at least in a way that does not break with updates. You can also share your functions in a package for others to use.
