### ISSUE TITLE
Bag flipX

### ISSUE THREAD

**Issue by i-prikot** [fabricjs/fabric.js#6269]
## Version
4.0.0-beta.10

## Test Case
https://codepen.io/i-prikot/pen/pojJbMm

## Information about environment
Nodejs or browser?
v10.15.1
Which browsers?
Google Chrome
## Steps to reproduce
FlipX object breaks controls
## Expected Behavior
Flip horizontally
## Actual Behavior
Rotates vertically and breaks controls

**Comment by i-prikot** [comment]
`calcOCoords: function() {
      var rotateMatrix = this._calcRotateMatrix(),
          translateMatrix = this._calcTranslateMatrix(),
          startMatrix = multiplyMatrices(translateMatrix, rotateMatrix),
          vpt = this.getViewportTransform(),
          finalMatrix = multiplyMatrices(vpt, startMatrix),
          dim = this._calculateCurrentDimensions(),
          coords = {};
      this.forEachControl(function(control, key, fabricObject) {
        coords[key] = control.positionHandler(dim, finalMatrix, fabricObject);
      });
}`

function taken from version 9
the variable **dim** takes the value of the function _calculateCurrentDimensions
version 10 **dim** = _getTransformedDimensions, this function skips padding

**Comment by asturur** [comment]
You should compare with the latest unpublished beta. The problem is still there, but that is the code we want to look at.
I may know how the bug was introduced, i just need time to look for a fix.

**Comment by i-prikot** [comment]
> You should compare with the latest unpublished beta. The problem is still there, but that is the code we want to look at.
> I may know how the bug was introduced, i just need time to look for a fix.

Sorry. I don't want to seem intrusive. The code above helped me. You can take the time to view the code. Thank you!
