### ISSUE TITLE
Newlines defined in canvas not saved to JSON.

### ISSUE THREAD

**Issue by kylekirkby** [fabricjs/fabric.js#6270]
Hi all,

I've been racking my brains on this for some time now. I have the need for a textBox that resizes text to fit the box, or at a minium, a fixed width and automatically add newlines. Is there a way this can be achieved with fabric js? 

```
    let textBox = new fabric.Textbox(
      "Some long text to \n test with wrapping onto a \n new line.",
      {
        left: this.state.canvasOptions["originX"],
        top: this.state.canvasOptions["originY"],
        fontSize: 30,
        fontFamily: "Lato",
        textAlign: "center",
        type: "text",
        lockSkewingX: true,
        width: 300,
        height: 200,
        breakWords: true,
        scaleX: 1,
        scaleY: 1,
        lockSkewingY: true,
        clipPath: clipPathObject,
        splitByGrapheme: true,
        fill: "#000",
        layerId: uniqueLayerId,
      }
    );
```

If I create textbox with the above then, upon saving to JSON, the newlines are added back in when loading from JSON. But if the user adds a newline by clicking the textbox and editing the text - the newline characters are not respected. Is there a way that fabric can add these \n characters automatically to the objects `text` property?

Thanks in advance! Best regards,

Kyle

**Comment by asturur** [comment]
You can achieve this with events.
From your description is still unclear what you exactly want to do.
Is possible to use events to shrink font sizes when the box get resized, or to capture how the text has bee wrapped looking at the `textLines` array.

**Comment by kylekirkby** [comment]
Hi @asturur ,

Thank you for your reply. After sleeping on it, I think the base TextBox should suffice. However, when saving the canvas to JSON and reloading the lines are not automatically broken and the width of th 
textbox increases. Any idea as to what is causing this?

Here is a diff of the JSON before and after saving/loading from JSON:
https://www.diffchecker.com/IOCVc0RP

![Peek 2020-04-13 11-14](https://user-images.githubusercontent.com/4564433/79113190-41b2b600-7d78-11ea-959a-8300eb8a06aa.gif)


Best regards,
Kyle

**Comment by asturur** [comment]
It seems you are exporting a fabric.Text object and not a fabric.Textbox from fabric. This is what i see from the JSON file.

**Comment by asturur** [comment]
```js
    let textBox = new fabric.Textbox(
      "Some long text to \n test with wrapping onto a \n new line.",
      {
        left: this.state.canvasOptions["originX"],
        top: this.state.canvasOptions["originY"],
        fontSize: 30,
        fontFamily: "Lato",
        textAlign: "center",
        type: "text",
        lockSkewingX: true,
        width: 300,
        height: 200,
        breakWords: true,
        scaleX: 1,
        scaleY: 1,
        lockSkewingY: true,
        clipPath: clipPathObject,
        splitByGrapheme: true,
        fill: "#000",
        layerId: uniqueLayerId,
      }
    );
```

You can't add `type: 'text'` in the options, or it will break the load/restore. Type is reserved to fabric to know how to restore things.

**Comment by kylekirkby** [comment]
Unbelievable @asturur ! It works! Thank you so much!!!! I can't believe I missed this! You sir are a legend!
