### ISSUE TITLE
How to simulate mouse up event

### ISSUE THREAD

**Issue by VinAr22** [fabricjs/fabric.js#6271]
Hello! I am developing a project where I need to simulate a mouseup event. This should work like this:

I click on the canvas to draw or drag objects, and after timeout I want to handle the mouseup event. How can I achieve this?

My codepen [example](https://codepen.io/vinar22/pen/abvOGvZ)

Stackoverflow [question](https://stackoverflow.com/questions/61185438/how-to-simulate-mouse-up-event-fabric-js)

Thank you very much

**Comment by asturur** [comment]
https://stackoverflow.com/questions/61185438/how-to-simulate-mouse-up-event-fabric-js/61187877#61187877

I tried to answer there
