### ISSUE TITLE
Render a brush stroke on the lower canvas before mouse up

### ISSUE THREAD

**Issue by VinAr22** [fabricjs/fabric.js#6272]
Im trying to render drawing immediately on lower canvas before mouse up event.

I found a few topics describing this, but i dont understand how i can use it in my project.

My stackoverflow question:
https://stackoverflow.com/questions/61191294/render-a-brush-stroke-on-the-lower-canvas-before-mouse-up

Thank you so much

**Comment by asturur** [comment]
https://stackoverflow.com/questions/61191294/render-a-brush-stroke-on-the-lower-canvas-before-mouse-up/61444562#

**Comment by VinAr22** [comment]
Hello! Thanks for the answer! Your solution looks amazing. Tell me, please, is it possible to add freehand drawn content from the top level of one fabric canvas to another low-level fabric canvas? Please, look at this codepen codepen.io/vinar22/pen/vYNmzXp

**Comment by asturur** [comment]
i do not understand what you want to do differently from my answer. What is the part that you need different and why?
