### ISSUE TITLE
Implement stroke to go around the text instead of laying on top of it

### ISSUE THREAD

**Issue by paulconlin** [fabricjs/fabric.js#6273]
**Is your feature request related to a problem? Please describe.**
Working with the stroke on the text feature, it lays on top of the text instead of adding to the outside. 

Stroke width of 1
![image](https://user-images.githubusercontent.com/10995964/79164514-d03e2c00-7da6-11ea-929c-c009bad17013.png)

**Describe the solution you'd like**
Ideally the text itself would remain unchanged and the stroke would just be added around it - 

![image](https://user-images.githubusercontent.com/10995964/79164299-66be1d80-7da6-11ea-8531-150f5959abfd.png)

The current implementation really has kept me from using the stroke since I can't seem to get it to look quite right on a lot of fonts. Totally get this is a low priority item.

**Comment by asturur** [comment]
The stroke will never be around the text for how is handled in canvas.
It is always half outside and half inside the shape/text.
You can use this:
http://fabricjs.com/docs/fabric.Object.html#paintFirst
to obtain the same effect.

**Comment by paulconlin** [comment]
Thank you!
