### ISSUE TITLE
can fabric.js make perspective transformation?

### ISSUE THREAD

**Issue by mevsme** [fabricjs/fabric.js#6274]
<img src="https://i.imgur.com/joZGWXx.gif">

**Comment by asturur** [comment]
i patched it up for a private commercial project, i don t even like it. I will ask if i can release it open source

**Comment by asturur** [comment]
to clarify that is a 3d transform and canvas is 2d only. the transformation happen with triangle approximation and is super slow in 2d, while is somehow a bit faster with webgl. the implementation consist of a filter and controls code

**Comment by mevsme** [comment]
I see, thanks, I've found some matrix3d js library and I have very simple use case, so I guess I won't need fabric for my simple case.

**Comment by CrandellWS** [comment]
this is a sudo 3d transform performed on 2d objects it is doable ...
