### ISSUE TITLE
fabric.js是否可以增加表格控件

### ISSUE THREAD

**Issue by zhangqi11** [fabricjs/fabric.js#6275]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/79560072-282aaa80-80a7-11ea-821e-5e97e5a44198.png)

How much help do you really want if this is the level of effort you can put in creating an issue?

![image](https://user-images.githubusercontent.com/1194048/79560102-3a0c4d80-80a7-11ea-94de-ad31cc25f937.png)

Please translate in english with a translator your problem/request and modify the issue.

**Comment by xiaowangsmile** [comment]
Whether fabric.js can provide methods for drawing tables？
eg：
![image](https://user-images.githubusercontent.com/28744261/80296804-82ff8880-87b0-11ea-8dc1-b79827e25da3.png)

**Comment by juzhiyuan** [comment]
maybe not, in my opinion, fabric.js mainly provides the ability to control Canvas and SVG/Canvas to SVG..

**Comment by xiaowangsmile** [comment]
> maybe not, in my opinion, fabric.js mainly provides the ability to control Canvas and SVG/Canvas to SVG..

^_^

**Comment by asturur** [comment]
If you do not pretend to write in the cells dynamically, you can totally build your own table render easily.
If you want dynamic editing, while fabric is maybe not the right tool for the job, is still possible but harder.
