### ISSUE TITLE
fabric.js group 中 放置 image 会导致图片模糊

### ISSUE THREAD

**Issue by mtshen** [fabricjs/fabric.js#6282]
代码逻辑大约是这样
创建一个group 其中加入一个image, 加入到 fabric.Canvas 中, 图片虚化
```js
const canvas = new fabric.Canvas(main);

const wallImgInstance = new fabric.Image(wallCanvas);

const wallGroup = new window.fabric.Group([wallImgInstance], {
    left, top, width, height, originX, originY,
});

canvas.add(wallGroup);
canvas.requestRenderAll();
```
但如果不加入group则图片不会虚化
```js
const canvas = new fabric.Canvas(main);
const wallImgInstance = new fabric.Image(wallCanvas);
canvas.add(wallImgInstance);
canvas.requestRenderAll();
```

我现在有大量的group来做层级计算, 如何解决其中图片模糊的问题?

**Comment by asturur** [comment]
Any chance you can translate the non english part in english?
For me using the automated translator gives bad result.

**Comment by mtshen** [comment]
Image placement in fabric.js group will cause image blur
Create a group, add an image to fabric.canvas
The picture will blur
If you do not use group
Graphics will not blur

**Comment by mtshen** [comment]
> 代码逻辑大约是这样
> 创建一个group 其中加入一个image, 加入到 fabric.Canvas 中, 图片虚化
> 
> ```js
> const canvas = new fabric.Canvas(main);
> 
> const wallImgInstance = new fabric.Image(wallCanvas);
> 
> const wallGroup = new window.fabric.Group([wallImgInstance], {
>     left, top, width, height, originX, originY,
> });
> 
> canvas.add(wallGroup);
> canvas.requestRenderAll();
> ```
> 
> 但如果不加入group则图片不会虚化
> 
> ```js
> const canvas = new fabric.Canvas(main);
> const wallImgInstance = new fabric.Image(wallCanvas);
> canvas.add(wallImgInstance);
> canvas.requestRenderAll();
> ```
> 
> 我现在有大量的group来做层级计算, 如何解决其中图片模糊的问题?
