### ISSUE TITLE
image placement in fabric.js group will cause image blur

### ISSUE THREAD

**Issue by mtshen** [fabricjs/fabric.js#6283]
image placement in fabric.js group will cause image blur
Create a group, add an image to fabric.canvas
The picture will blur

code:
 ```js
 const canvas = new fabric.Canvas(main);
 
 const wallImgInstance = new fabric.Image(wallCanvas);
 
 const wallGroup = new window.fabric.Group([wallImgInstance], {
     left, top, width, height, originX, originY,
 });
 
 canvas.add(wallGroup);
 canvas.requestRenderAll();
 ```

If you do not use group
Graphics will not blur

code:
 ```js
 const canvas = new fabric.Canvas(main);
 const wallImgInstance = new fabric.Image(wallCanvas);
 canvas.add(wallImgInstance);
 canvas.requestRenderAll();
 ```

**Comment by asturur** [comment]
Hi @mtshen, can you show it with an actual live example on jsfiddle or codepen?

With the group code you add top and left,width,height with the image example no top,left,width,height.
