### ISSUE TITLE
Object getting merged when save  int

### ISSUE THREAD

**Issue by Huyjoon1995** [fabricjs/fabric.js#6288]
![pic1](https://user-images.githubusercontent.com/29111074/79920842-e753ce00-83e5-11ea-9e35-f994bb9c4532.png)

- In the image above, the left side is what i drew on canvas, the right side is what the file system currently saving the image. As its being saved to the file system, the thickness of the line increased and also line that drew parallel or close to each other getting merged into one. Any suggestion on why this happen and is there any particular way to solve it?

**Comment by asturur** [comment]
with just a picture no.
can you make it happen on jsfiddle or codepen?

**Comment by asturur** [comment]
seeing that you are using few pixels, it may be a rounding issue.
http://fabricjs.com/fabric-gotchas <--- did you try this, where this talk about NUM_FRACTION_DIGITS?

**Comment by Huyjoon1995** [comment]
Hi, Unfortunately i cant share the code or replicate it exactly on fiddle
or codepen since this is an internal company work. But the brush that i was
using is a custom square brush when taking in coordinate i have use
parseInt so it cant be floating point issue. The image from canvas is
convert to array buffer using getImageData and was used to write out to the
file. Even with the usage of pencil brush this issue still exists.

**Comment by asturur** [comment]
Well you do not have to replicate exactly, but i can assure you that 90% of the time you try to reproduce in a fiddle the exact problem and you will find the issue.

the right picture clearly do no have alpha, and so it could be an half pixel positioning problem.
You put the coordinates at integers, whatever are those custom square fabric could be repositioning them if they have strokeWidth of 1, of exactly half pixel, creating that issue.

**Comment by Huyjoon1995** [comment]
In the custom square brush when i create the new fabric.rect i dont add the
strokewidth into the rect property add all. It seem like every time when we
annotate something on canvas instead of drawing the actual size of the
rect, the data get written and save into image seem to be the size of the
cursor which usually 3 pixel wider than we want it to be.

**Comment by asturur** [comment]
rect has a default strokeWidth of 1, transparent. You have to set it to 0 if you do not want it. The 1 pixels stroke is gonna offset your placement logic unless you are using originX/originY center/center. In that case you have to place them at half pixels.

Other than that, i repeat, without seeing it in action, is a guessing mission.
