### ISSUE TITLE
How to reduce path points in json data

### ISSUE THREAD

**Issue by yousiedu** [fabricjs/fabric.js#6289]
I want convert the fabric object to json data use `JSON.stringify(canvas)` and save the json object to the server  , because of the json data is so large ( path points in brush )  so I want to compress it , I want to How to do in fabric.js

**Comment by asturur** [comment]
thereisn't much to compress.
Fabric offers a path semplification in the brush that can help reducing the number of points.
Is call `decimate` and takes a number. Each point that is less than `decimate` pixel distant from another will be omitted.

you can try values of 1, 1.5, or 2. You can get higher but the path will be simplified a lot.

http://fabricjs.com/docs/fabric.PencilBrush.html#decimate

**Comment by i-prikot** [comment]
> I want convert the fabric object to json data use `JSON.stringify(canvas)` and save the json object to the server , because of the json data is so large ( path points in brush ) so I want to compress it , I want to How to do in fabric.js

Try using an algorithm LZW to compress. https://gist.github.com/revolunet/843889
