### ISSUE TITLE
Negative charSpacing splitByGrapheme cut text

### ISSUE THREAD

**Issue by munbart** [fabricjs/fabric.js#6291]
## Version
3.6.3

## Test Case
http://jsfiddle.net/ytn7wxfr/8/

## Steps to reproduce
Select text and do resize (scale) from right to left
## Expected Behavior
Text wrap to next line and all text visible
## Actual Behavior
Text on scale become hidden out selected border

**Comment by asturur** [comment]
thanks for the clear bug report.
Definitely seems a bug or anyway something unwanted.
