### ISSUE TITLE
Issue with Node / Node-Canvas + Text + Transformations

### ISSUE THREAD

**Issue by alpfactory-alex** [fabricjs/fabric.js#6292]
## Version
3.6.3

## Test Case
http://jsfiddle.net/6vhxerLt/1/

(Can not post any nodejs sample here)

## Information about environment
NodeJS
On Browser it works as desired

## Steps to reproduce
Run the given code on Node-JS and save a png or pdf or whatever (result is always the same).

## Expected Behavior
The character spacing should be rendered correctly with tranformations on text.

## Actual Behavior
The more you scale the text (or do via fabric canvas.viewportTransform doesn't matter) the more the characters float out of each other. This can also nicely be seen that the text background stays correct but the letters go wild.

On Browser (correct):

<img width="1046" alt="Bildschirmfoto 2020-04-23 um 20 19 57" src="https://user-images.githubusercontent.com/19890104/80134958-cf27ae80-859f-11ea-9f46-3121018e3d1e.png">

Via NodeJS exported as PDF (but same for png or whatever):

<img width="1513" alt="Bildschirmfoto 2020-04-23 um 20 20 35" src="https://user-images.githubusercontent.com/19890104/80135023-e5356f00-859f-11ea-81d9-1fac59dea20e.png">

Checked the known node-canvas limitations but there is nothing like that.

Posting an issue on node-canvas too as its impossible to figure for me if it might be an issue on node-canvas itself with text + transformations.

**Comment by asturur** [comment]
the difference between pdf of png is important. We can look at what happens with png, but with pdf we can t compare. Pdf format and text and fonts embedding aren't 1:1 with canvas and may generate differences. I ll check it as soon as i can.

**Comment by alpfactory-alex** [comment]
@asturur Yes I've thought first its a cairo pdf issue but its definitely not. It also happens when generating a simple PNG so it seems its painted definitely wrongly on node canvas with viewport transformations. I also tried to change the type of text drawing on the node canvas from glyph / path without changes.

**Comment by asturur** [comment]
I'm not saying is a pdf issue, i m saying i will look only at the png output, because i have to narrow down the scope of what i do.

**Comment by asturur** [comment]
i can reproduce indeed.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/80273013-e6b18500-86ce-11ea-9a29-d2055bdc60ce.png)

If i manually compile node-canvas the problem fixes itself, so is not a problem with fabric.
I left a comment in a issue that is duplicated from yours on the node-canvas repo.
