### ISSUE TITLE
Potential memory leak?

### ISSUE THREAD

**Issue by alpfactory-alex** [fabricjs/fabric.js#6293]
Its not a formal bug report (yet) as I need confirmation first. Canvases can be disposed so they release their resources for example on images and temporary canvases and filters etc:

https://github.com/fabricjs/fabric.js/blob/master/src/static_canvas.class.js#L1739

However looking at the mixin it seems this only iterates the flat objects not the nested ones from any groups:

https://github.com/fabricjs/fabric.js/blob/6994b0419b3fd6c64e91e06591136f00a76aca26/src/mixins/collection.mixin.js#L94

Would this mean that i.e. if an image is contained within a group it would leak as it never gets dispose called?

-- Taking on this, I could not find anything that calls dispose either when an object is removed from the collection. Is this not supported?

**Comment by asturur** [comment]
If you find a reproducible way to leak memory, please post it here.
For sure there are some, and in server usage those do matter most.

In theory if you do not keep extra references of the objects, whatever group and nested structure you have, they are not referenced anymore and the GC will harvest them at some point. Sometimes the hidden enemy are small properties of which i forget, like _hoveredTarget for example. There are issues with reproducible memleaks tho, look at those also.

**Comment by alpfactory-alex** [comment]
I am happy helping in fixing those. Just to confirm though are my assumptions correct that

a) canvas.dispose() only disposes on first level so ignores groups and such (as group has no dispose())

b) removing an object from the collection doesn't dispose it either

**Comment by asturur** [comment]
no removing an object from a collection should not dispose. You are free to remove an object from canvas A and put it in canvas B or in other groups.
Disposing should be a manual action from the developer, mainly targeted at node-canvas usage.

I agree group could have a dispose method to take care of objects.

**Comment by alpfactory-alex** [comment]
Yes I understand dispose should be manually. Note we also need dispose a lot on frontend as due using createObjectURL it is the developer's responsibility to clear up.

Currently we're patching certain fabric functions to allow for this. As I can see, however, every fabric.Object might need a dispose as i.e. pattern brushes could contain an image reference as well.
