### ISSUE TITLE
Can't resolve canvas from jsdom utils during packaging

### ISSUE THREAD

**Issue by jasonsturges** [fabricjs/fabric.js#6297]
My Electron application leveraging Fabric.js errors during packaging, unable to resolve canvas from jsdom utils:

```
ERROR in ./node_modules/jsdom/lib/jsdom/utils.js
 Module not found: Error: Can't resolve 'canvas' in '/[project]/node_modules/jsdom/lib/jsdom'
  @ ./node_modules/jsdom/lib/jsdom/utils.js 152:2-27 158:17-34
  @ ./node_modules/jsdom/lib/jsdom/browser/Window.js
  @ ./node_modules/jsdom/lib/api.js
  @ ./node_modules/fabric/dist/fabric.js
  @ ./app/display/FabricApp.ts
  @ ./app/components/Home.tsx
```

Is this a known issue, or any suggestion to debug this dependency of Fabric?

## Version
3.6.3-browser

## Information about environment
[Electron React Boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate)

## Steps to reproduce
1. Clone Boilerplate
2. Add Fabric
3. Package `yarn package-mac`

## Expected Behavior

Electron Application Built

## Actual Behavior

Errors on jsdom

**Comment by asturur** [comment]
Well there are 2 things at stake here.
1) in your app is fabric used in the node portion or the browser portion? ( Electron can do both right?)
2) Why canvas is not installed/available?

**Comment by jasonsturges** [comment]
@asturur Thank you so much - you are correct, I wasn't managing dependencies between the Electron `package.json` and the app's `app/package.json` correrctly.
