### ISSUE TITLE
Crop an area of a Canvas

### ISSUE THREAD

**Issue by mk10391** [fabricjs/fabric.js#6301]
## Version
3.6.3

## Information about environment
Which browsers?
Chrome & IE 11

## Steps to reproduce
- create simple  html canvas.
- using javascript and fabric js, 
 > create a simple  fabric js rectangle on Canvas.
 myCanvas._objects[0] is the Rectangle

 > add any image to canvas using fabric js (image shows up inside the rectangle).   
 myCanvas._objects[1] is my image

Now i have a html button. when i click the button, i want to crop & export that rectangle section into separate image. 

I used the following code 

document.getElementById("myCroppedImg").src =  myCanvas._objects[0].toDataURL({
        format: 'png',
        multiplier: 4        
    });
as a result, i see the rectangle section created a new cropped image, How ever that image i added is not visible inside the rectangle. 

## Expected Behavior

I want to see that image (the image i added on canvas) inside the cropped exported rectangle. 

## Actual Behavior
i was expecting Image visible on the exported rectangle section image.  Any idea how to achieve that ?

**Comment by mk10391** [comment]
seems like i'll have to first take an image from whole canvas and then crop that image using left/top/width/height of the rectangle (and multiplying with multiplier value). I can close this now.

**Comment by asturur** [comment]
there are different ways to do so, one is use Canvas.toDataURL with the cropping option.
