### ISSUE TITLE
setBackgroundColor flashing black

### ISSUE THREAD

**Issue by arminbusatlic** [fabricjs/fabric.js#6304]
Hi there,

I am dynamically setting the background as an image that is being repeated using the following code:

canvas.setBackgroundColor({source: image_path ,repeat: 'repeat',}, canvas.renderAll.bind(canvas));

As this function is being called, I noticed a black background flashing right before the image is displayed. I recently upgraded fabricjs to the newest version which is when this started to occur. This wasn't an issue in the older version I had.

Any advice would be greatly appreciated.

**Comment by asturur** [comment]
any chance you can reproduce it in a codepen or fiddle?

**Comment by asturur** [comment]
That should not happen, but if you can't reproduce in a fiddle, the issue will be closed.
What version of fabricJS are you on?
