### ISSUE TITLE
Lags with a large number of objects

### ISSUE THREAD

**Issue by Mamikon95** [fabricjs/fabric.js#6307]
Hello everyone
With a large number of objects, it terribly lags. json file size can be 20mb where there can be 1000+ polygons, with a lot of points. Zooming and Dragging lags strongly after loadFromJSON(). What can be done?

**Comment by asturur** [comment]
Probably in this case disabling caching helps.
You should reproduce your lag situation in a way we can see what is actually lagging, if is code, cache or what else.

**Comment by Mamikon95** [comment]
> Probably in this case disabling caching helps.
> You should reproduce your lag situation in a way we can see what is actually lagging, if is code, cache or what else.

thanks for answer, and how i can disable caching?

**Comment by asturur** [comment]
http://fabricjs.com/fabric-object-caching
