### ISSUE TITLE
Ability to add border radius to IText using backgroundColor

### ISSUE THREAD

**Issue by paulconlin** [fabricjs/fabric.js#6309]
**Is your feature request related to a problem? Please describe.**
Would like to be able to add a borderRadius to the background of an IText using backgroundColor. Currently I'm able to achieve this - 

![image](https://user-images.githubusercontent.com/10995964/80823080-84aac100-8ba1-11ea-8eea-e99af4c1c31f.png)

**Describe the solution you'd like**
I'd really like to be able to add a borderRadius attribute to give a slight rounding to the edges. 

Was also exploring the idea of being able to have the background only be around the text, and not create a square box.

From something like this - 
![image](https://user-images.githubusercontent.com/10995964/80823147-b15ed880-8ba1-11ea-8dbd-23eb106becba.png)

to something more like -

![image](https://user-images.githubusercontent.com/10995964/80823248-ec610c00-8ba1-11ea-9310-aa19e871f2f5.png)

**Describe alternatives you've considered**
I tried playing around with clipPath, but wasn't able to get it to work quite right. Maybe this is possible already?

**Comment by asturur** [comment]
If you are creating static images or animations, go with your own code, this is too much particular to be handled in the generic textbox.
You should write your own path creator that reading from the text object properties can create that rounded shape. feel the shape with color and group with the text or simply align them together.

If you are looking for interactivity, that is another kind of problem.

**Comment by mspanish** [comment]
This would be so useful, if somebody does have an example of how they did this quickly and easily it would be nice! While creating a custom solution can be done, a 1 line hack to the code that creates the rect box to begin with would be super convenient - for many people this is all they would need, as rounded rects are far more popular for labels these days than non rounded ones.

**Comment by asturur** [comment]
in the text.class.js file you find the single
method responsible for painting the textlinebackground color.
The problem is not adding the rounded corners but handling different cases when the rect change color during the text line and how to handle multiple lines.

There is also the object generic background color  that could be used as a generic rounded background

**Comment by mspanish** [comment]
thanks I will look - I realize this is a hacky solution but for my use case it might be perfect - the simple adding of rounded rects to text, mostly used as labels in lessons for students (no animation either).

**Comment by mspanish** [comment]
I've looked through the object.class.js file and can't see how I would set an rx or ry value - sorry but it's a complicated file and I'm not that familiar with the canvas drawing/rendering methods to be able to piece anything together. Any ideas would be great as at this point I'll have to create a group with some kind of editable text and a rect that responds to the text size and resizes itself.

**Comment by mspanish** [comment]
This feels so hacky I hesitate to post it! But for my purposes this is great, I would never really use textLinesBackground for anything anyway, and this allows you to add the rounded rect there, while preserving the backgroundColor for a regular rect (once you add the padding globally). 

Sizing is not perfect at all - but I can add some settings to my textLinesBackground changer that should take care of that - I'm sure a rect & text group is a way more sophisticated solution that offers far more flexibility, but this works for me for now. Found in the text.class.js file.

```
  _renderTextLinesBackground: function(ctx) {
      if (!this.textBackgroundColor && !this.styleHas('textBackgroundColor')) {
        return;
      }
      
      ctx.fillStyle = this.textBackgroundColor;
      this.rx = 10;
      this.ry = 10;
      let topOffset = this._getTopOffset()
      //console.log('_renderTextLinesBackground...')

      let rx = this.rx ? Math.min(this.rx, this.width / 2) : 0,
        ry = this.ry ? Math.min(this.ry, this.height / 2) : 0,
        w = this.width  * 1.15,
        h = (this.height * 1.9) + (topOffset),
        x = -w / 2,
        y = -h / 2,
        isRounded = rx !== 0 || ry !== 0,
        k = 1 - 0.5522847498;
        
      ctx.beginPath();

      ctx.moveTo(x + rx, y);

      ctx.lineTo(x + w - rx, y);
      isRounded && ctx.bezierCurveTo(x + w - k * rx, y, x + w, y + k * ry, x + w, y + ry);

      ctx.lineTo(x + w, y + h - ry);
      isRounded && ctx.bezierCurveTo(x + w, y + h - k * ry, x + w - k * rx, y + h, x + w - rx, y + h);

      ctx.lineTo(x + rx, y + h);
      isRounded && ctx.bezierCurveTo(x + k * rx, y + h, x, y + h - k * ry, x, y + h - ry);

      ctx.lineTo(x, y + ry);
      isRounded && ctx.bezierCurveTo(x, y + k * ry, x + k * rx, y, x + rx, y);

      ctx.closePath();

      this._renderPaintInOrder(ctx);
      this._removeShadow(ctx);
    },

```

![labels](https://user-images.githubusercontent.com/206150/92319525-be635c80-efc5-11ea-9669-80ba528dfed9.png)

**Comment by asturur** [comment]
what about `_renderBackground: function(ctx) {` in object.class.js?
Seems smaller and less critical than the text line and would allow you to still use background color for text.

Making groups with text and normal rects is still a viable option, requires more code.

**Comment by mspanish** [comment]
Sure I will take a look at adding it there instead.

Is there way to get the size of the selection box from this?

**Comment by asturur** [comment]
At rendering time, the selection is always width by height, originating in the center at 0,0 so your selection box extends from -width/2 to width/2 and from -height/2 to height/2.

Now with textbox you do not stretch the text but you change its width when using the controls, so the radius of the rounded corner will always be ok.
If you are looking into keeping the radius of the rounded corner the same when also scaling from the corners, then you have to step up your calculation a bit, but nothing hard. Probably is just dividing or multiplying your rx/ry by the scale factor.

**Comment by kpomservices** [comment]
Able to add the rounded background color using the below code 
`				//https://stackoverflow.com/questions/1255512/how-to-draw-a-rounded-rectangle-using-html-canvas
				CanvasRenderingContext2D.prototype.roundRect = function (x, y, w, h, r) {
					if (w < 2 * r) r = w / 2;
					if (h < 2 * r) r = h / 2;
					this.beginPath();
					this.moveTo(x+r, y);
					this.arcTo(x+w, y,   x+w, y+h, r);
					this.arcTo(x+w, y+h, x,   y+h, r);
					this.arcTo(x,   y+h, x,   y,   r);
					this.arcTo(x,   y,   x+w, y,   r);
					this.closePath();
					return this;
				}

				fabric.Textbox.prototype._renderBackground = function(ctx) {
					if (!this.backgroundColor) {
						return;
					}
					var dim = this._getNonTransformedDimensions();
					ctx.fillStyle = this.backgroundColor;

					if(!this.bgCornerRadius) {
						ctx.fillRect(
							-dim.x / 2,
							-dim.y / 2,
							dim.x,
							dim.y
						);
					} else {
						ctx.roundRect(-dim.x / 2, -dim.y / 2, dim.x, dim.y, this.bgCornerRadius).fill();
					}
					// if there is background color no other shadows
					// should be casted
					this._removeShadow(ctx);
				}`

**Comment by SakifKhan98** [comment]
@mspanish can you please share a working fiddle with your code? It would really be a great help. I am trying to get the exact thing you created. Tried your code with Textbox object, but not being able to make it work. TIA
