### ISSUE TITLE
Gradient toLive does not take offset into consideration

### ISSUE THREAD

**Issue by codingdudecom** [fabricjs/fabric.js#6312]
**Is your feature request related to a problem? Please describe.**
When using Gradient.toLive() I noticed that the `offsetX` and `offsetY` properties are ignored.

**Describe the solution you'd like**
I think a simple addition like the following will help, I can't tell if there are any downsides to this solution though

```
...
if (this.type === 'linear') {
        gradient = ctx.createLinearGradient(
          coords.x1 + this.offsetX, coords.y1 + this.offsetY, coords.x2 + this.offsetX, coords.y2 + this.offsetY);
      }
      else if (this.type === 'radial') {
        gradient = ctx.createRadialGradient(
          coords.x1 + this.offsetX, coords.y1+ this.offsetY, coords.r1, coords.x2+ this.offsetX, coords.y2+ this.offsetY, coords.r2);
      }
...
```

**Additional context**
And now for some context. I've considered setting the background of the canvas to a gradient. For me the easiest solution was to create a `fabric.Rect` object with the same size as the canvas, but without adding it to the canvas. I set the the gradient color to this rectangle and then use `canvas.backgroundColor = rect.fill.toLive(canvas.contextContainer);` to set the gradient as the background.

This works just fine, but I also have some controls for the `offsetX` and `offsetY` of the gradient. This did not do anything, and that's what lead me to the conclusion that the `toLive` method might be missing something. Hope you agree

**Comment by asturur** [comment]
There is no offsetX or offsetY in the gradient specification. What those are supposed to do? what they do you can t do with the x1, x2 y1 and y2?

**Comment by codingdudecom** [comment]
http://fabricjs.com/docs/fabric.Gradient.html#offsetX

I could use x1, x2, etc but I'm using pixels as the unit and want to keep the x/y in sync with the width/height of the object. 

offsetX and offsetY helps me... well offset the gradient :-)

hope this makes sense

**Comment by asturur** [comment]
I think that offsetX/Y are specific for SVG import use case alignment.
I sincerly do not remember why are still part of the public interface, but i think they should be removed.
