### ISSUE TITLE
Drag selection is broken when selecting part of object

### ISSUE THREAD

**Issue by virror** [fabricjs/fabric.js#6314]
## Version
3.6.3

## Test Case
http://fabricjs.com/manage-selection

## Information about environment
Firefox, Chrome

## Steps to reproduce
Drag and try to select any of the cubes by dragging the selection box only half over it.

## Expected Behavior
Cube should be selected

## Actual Behavior
Cube is selected, but the controls are not showing at all until you try to manipulate it.

**Comment by virror** [comment]
Quick update:
It seems that the selection needs to be bigger then the object in at least one axis to completely select the object. But the strange thing is that the object is always selected, it just does not show it, proof of this is to make a group, select part of it (so no selection shows) and then press ungroup, the object will now be ungroped.

**Comment by awehring** [comment]
Looks like a minor bug.

The object (your "cube") is selected, only the controlling border is not shown. After a `canvas.requestRenderAll()` it appears.
(btw. `canvas.requestRenderAll()` is the newer and more efficient form of `canvas.renderAll()`).

**Comment by virror** [comment]
Yeah, i have noticed the rendering changes : )
Good it can be bypassed, but i guess its still a bug : p

**Comment by asturur** [comment]
true. If i remember correctly the object needs to be partially included in the selection and we are probably doing this using  the idea that the selection box should include at least a corner of the object.
Not firing the render is probably where the bug is.
I can see if i can fix it, this is a bug.

Thanks for the additional debug @awehring

**Comment by asturur** [comment]
(yes requestRenderAll while it does the same job of renderAll it avoids that multiple renderAll would happen in sequence, it uses requestAnimationFrame)

**Comment by virror** [comment]
Its not enough to just include a corner sadly, the selection needs to completely cross the object to work properly.
