### ISSUE TITLE
Extend groups to be able to create "flat" groups

### ISSUE THREAD

**Issue by virror** [fabricjs/fabric.js#6316]
The idea here is to always flatten the groups so you can never have a group in a group. This is desired sometimes both from a user perspective and also for simplicity when trying to save the state of the objects in custom ways.

**Comment by asturur** [comment]
possibly add a method to group, called flatGroup or similar, that without rendering will reorganize internal structure of the objects. 

Example

- group
  - object A
  - object B
  - group
    - object C
    - object D
    - group
      - object F
      - object E

becomes:
- group
  - object A
  - object B
  - object C
  - object D
  - object F
  - object E


this can be achieved apply the nested group transform to objects and then decompose them. 

Features:
- possibly recursive ( does no matter if first implementation is not )
- width/height of group shouldn't change
- possible works on active selections too ( harder )

Bugs to look for:
 - internal clicks should continue to work
 - object stack preserving issue
 - caching invalidation

**Comment by virror** [comment]
This is my solution for now, posting it here in case it might help out.
Im sure it can be made better with use of some internal functions though, but the theory might help some.
https://jsfiddle.net/1p732srw/

**Comment by ShaMan123** [comment]
I am closing this in favor of #7473 
As stated in the mentioned PR the problem of group is that an object is relative to group and not to canvas (which is kind of what you are saying here, but more implied)
Comment if you think this should be reopened.

**Comment by ShaMan123** [comment]
I think this doesn't belong to fabric

**Comment by ShaMan123** [comment]
closing this
#7669 should solve your problems
you're welcome to comment if you disagree and contribute in other paths
