### ISSUE TITLE
User defined brush gives error in more recent versions of fabric.js

### ISSUE THREAD

**Issue by sjscotti** [fabricjs/fabric.js#6318]
## Version
3.6.3

## Test Case
https://jsfiddle.net/sjscotti/xLdob0km/

## Information about environment
Firefox and Chrome

## Steps to reproduce
I am trying to utilize a user-defined brush developed several years ago with the latest version of fabric.js.  For the more recent CDN version (3.6.3), my fiddle (see Test Case) give an error:

 "TypeError: fabric.Image.filters.Tint is not a constructor" 

I looked at a number of earlier CDN's to see where the brush broke and it was working up to and including version 2.0.0-beta.1.  Above this version gives the error.  See this test case for the error:
https://jsfiddle.net/sjscotti/xLdob0km/
while this fiddle using the earlier version of fabric.js works as expected:
https://jsfiddle.net/sjscotti/qvykat7b/

I tried for several hours to debug the behavior, but could not determine how to make the brush work correctly.  Was a bug introduced or a change in behavior introduced in going to version 2+?

## Expected Behavior
It should draw a spray paint path in results window when you use the mouse and left-button to paint in the window

## Actual Behavior
You do not get the cross-hair cursor and nothing is drawn in the results window.

**Comment by asturur** [comment]
http://fabricjs.com/fabric-filters

See the suggestions arount the tint filter for fabric version 2.

**Comment by asturur** [comment]
Other than that the fiddle is massive and after i apply the fix i get a `script error` i can't identify.

**Comment by sjscotti** [comment]
Thanks!  I looked at the link http://fabricjs.com/fabric-filters and as best as I could understand, I needed to replace the line 
`this.brush.filters[0] = new fabric.Image.filters.Tint({ color: color }); `
with the line 
`this.brush.filters[0] = new fabric.Image.filters.BlendColor({ color: color });`
... is that correct?  I tried it, but it didn't seem to work.

If I can get past the filter error, I can look into what may be causing the script error that you mentioned getting.

**Comment by asturur** [comment]
Did you manage to understand the error in the fiddle? the filter swap should work out of the box.

**Comment by sjscotti** [comment]
Hi
Thanks for the help.  Here is what I did to get it to work.  The original code had `tint` used in this routine...

```
    changeColor: function(color) {
      this.color = color;
      this.brush.filters[0] = new fabric.Image.filters.Tint({ color: color });
      this.brush.applyFilters(this.canvas.renderAll.bind(this.canvas));
    },
```
which worked in the old version of fabric.js.  To get it to work I modified the routine to this ...

```
    changeColor: function(color) {
      this.color = color;
      this.brush.filters[0] = new fabric.Image.filters.BlendColor({ color: color, alpha: 1, mode: 'tint' });  
      this.brush.applyFilters();	
    },
```

You can see it work in this fiddle... https://jsfiddle.net/sfzj6t7h/
Thanks for pointing me to the revision of how tint is implemented now in fabric.js!
