### ISSUE TITLE
Is there any complete documentation of the JSON specification?

### ISSUE THREAD

**Issue by devnix** [fabricjs/fabric.js#6320]
**Is your feature request related to a problem? Please describe.**
Hi! I'm considering having the possibility to use the generated JSON by Fabric.js to render the same image on the server side without loading a Node or Fabric instance.

As a whole canvas can be exported to a JSON representation, I guess it should not be extremely hard work (just a tonsh*t of work).

**Describe the solution you'd like**
Is there any complete documentation of the JSON specification used by Fabric.js? This would allow us to develop compatible renders in backend languages like Ruby, PHP, Python, Java, etc.

**Comment by asturur** [comment]
There is not. nothing with that scope in mind has ever been written.
Most of the properties are self explanatory, or are 1:1 with the HTML5 canvas and the one that are not you should ask and we can figure out how they relate to a generic render concept.

Canvas specs are described here: https://www.w3.org/TR/2dcontext/

For other backend languages that have a cairo based graphic library most of the drawing calls will be compatibile, exception made maybe for some of those that rely heavily on multiple layers combined together and filtering or text.

**Comment by devnix** [comment]
Hello again @asturur, it has been a while! :smile: 

>For other backend languages that have a cairo based graphic library most of the drawing calls will be compatibile, **exception made maybe for some of those that rely heavily on multiple layers combined together and filtering or text.**

I was fearing that, but supporting the basic primitives, images and text would be superb!

I will update this issue if I do any progress, I'll try a couple of libraries first. Thank you so much!

**Comment by mspanish** [comment]
The benefit of having some kind of schematic posted for the JSON needed to create an SVG via Fabric would actually be useful for people like me who have datasets of SVG's parsed to JSON. While I can go through your JSON samples and probably figure it out - It would be faster and easier if your samples had something listed!  I've stripped all transforms, but some of my SVGs do have groups - and from this sample I'm not sure how to handle those. My plan is to import some of my SVGs, then export to JSON via Fabric and reverse engineer from there.

Thank you for this library - it has enabled me to build a new editor from scratch in a week, I'm hoping to turn it into a really great homework editor and creator, as right now so many of the virtual lessons kids are doing include static PDFs they are expected to just read and add some basic notes to. Via Fabric they'll be able to do so much more!  Molto grazie per tutto.

**Comment by asturur** [comment]
there isn't a 1:1 connection between SVGs and final Json. Is there any reason why you want to know how they are related?

**Comment by mspanish** [comment]
I have 60,000 SVGs :)  A rather old and non updated version of my app is here [https://kwippe.com](https://kwippe.com)

And they are actually in CBOR, converted from JSON - as they are a fraction of the original size, and load as binary further zipped with zString :)

Of course I have all of the original SVGs but for the purpose of my app - which won't use FabricJS for all of the SVG creation - it's far better to keep these files in JSON, which also allows for variables inside of the files - mainly for colors.

I've noticed some of the big icon libraries also have a JSON dataset - guy like Icons8 have JSON in some of their repos representing hundreds or even thousands of icons.

I realize I'm an unusual use case. But having looked at your JSON export/import yesterday I don't think it will be rocket science to load my stuff into FabricJS. 

Your parser is very impressive - the only piece I'll have to recreate is the path subelements parsing, as I don't do that currently.

**Comment by asturur** [comment]
I still get confused. So you have thousands of json dataset that represent objects, coming from SVGs so probably with properties that match generic fabric objects concepts.

You would like them to load then in fabricjs, probably the missing parts are transformations and groups.

For transformations you can use some fabricjs embedded functionality, for grouping is sligtly
more complicated.

We can talk when you find some difficulties to figure out if something needs to be documented or explained. Happy to help

**Comment by mspanish** [comment]
It will be fine, I strip groups in my own parser, and pre-stripped transformations a well. Basically loading my stuff will mean fetching a file, then parsing from my format to yours, then loading via the fromJSON method.

Fabric.js is awesome. I'm used to writing all my own functions for all SVG manipulation (not to mention my app already stores all changes to JSON, so having a library take care of that for me is an additional bonus!).

Will let you know if I hit any brick walls.

**Comment by asturur** [comment]
if you have 60k svgs, of random kinds, would you open to share them so that i can run the compatibility test on them once, and maybe keep the one that do not pass it? would be beneficial for finding the missing parsing ability on fabricjs.

**Comment by mspanish** [comment]
Sure best to PM me about something like that - mspanish  at outlook email address.
