### ISSUE TITLE
How to zoom the canvas and editable polygon at the same time

### ISSUE THREAD

**Issue by joannluo66** [fabricjs/fabric.js#6322]
it is great to see this demo project for an editable polygon. I used the exact same code in my project. The only difference is that the canvas in my project is zoomed to 0.6 percent. The polygon was created correctly on the canvas. The blue dot handles are aligned with the polygon shape. However, I got an issue as soon as I switch to the Edit mode. The original polygon itself is painted correctly, but all the blue dot handles' coordinates are changed to the coordinates corresponds to where the canvas' zoom setting is 1. I noticed the sample project from this link has the capability to zoom to 1, 0.5 and 0.25 from the Codepen frame. Could somebody point out how this should be done correctly? I guess canvas.setZoom(0.6) may not be the right way to handle this. I was able to reproduce this using the sample project. Please see the screenshot below. I also created this sample project to demonstrate how to reproduce the issue. You will see the blue dot handler issue when you click on the Toggle Edit Polygon button. https://jsfiddle.net/iotdev100/ngcjxwep/4/
![Edit polygon on a zoomed canvas](https://user-images.githubusercontent.com/58533220/81411367-4583ef00-9110-11ea-8d7e-dbcdc80ddd0a.png)
Please let me know what is the correct way to handle this. Thanks!

http://fabricjs.com/custom-controls-polygon

**Comment by joannluo66** [comment]
Hello,

Could somebody offer suggestions on how the zoom to 1, 0.5 and 0.25 from the Codepen frame was done in the Toggle Edit Polygon example page?

Thanks!

**Comment by asturur** [comment]
We can fix the example to work with zoom.

**Comment by CKitisak** [comment]
@joannluo66 would you please share your solution if you already solved the problem?

**Comment by tttclz** [comment]
I have the same problem when pan the canvas by setting viewportTransform.
the control points don't move with original polygon.

**Comment by CKitisak** [comment]
FYI the issue can happen when using `canvas.zoomToPoint()` or Panning or Moving the object.
I have posted a question in SO https://stackoverflow.com/questions/62367880/fabricjs-how-can-i-update-the-custom-control-point-of-a-polygon-after-zoom-or-pa

@asturur please give me some advice what I did wrong. thank you.

**Comment by asturur** [comment]
I just updated the demo to work with the zoom!
