### ISSUE TITLE
Fill Polygon with dots and spacing

### ISSUE THREAD

**Issue by tufail** [fabricjs/fabric.js#6329]
Hi 
I am trying to find a method to fill the polygon with dots and spacing 
just like here is the example 
https://i.stack.imgur.com/8yk2Z.png

I have these points for the polygon shape
```
0: {x: 3512.2134802823884, y: 3651.806371034597}
1: {x: 3418.5113559939764, y: 3965.83511189306} 
2: {x: 4036.4388783283707, y: 3960.7701322017947} 
3: {x: 3942.736754039959, y: 3636.611431960801}
```

and I was trying to fill but this is working for the rectangle 
```
calculateCoord: function(points, space){
    var array = [];
		var width = Math.abs((points[0].x - points[1].x));
		var height = Math.abs((points[0].y - points[1].y)); 
		var i = 0; 
		array.push({x: points[0].x, y: points[0].y});

		while (true){
			width = Math.abs((points[0].x - points[1].x));
			while (width - space >= 0){
				i++;
				array.push({x: array[array.length - 1].x + space, y: array[array.length - 1].y});
				width -= space;
			}
			if ((height - space) <= 0){
				break;
			}
			array.push({x: array[array.length - i - 1].x, y: array[array.length - i - 1].y + space});
			height -= space;
			i = 0;
		}
        return array;
	}
```

I also search and got one algorithm for scanline polygon. But not able to implement because of the bound of the shape . Not able to get the bound like polygon.bounds. is there any way to get this please help.

**Comment by asturur** [comment]
to this question the answer is a pattern.
But you are not explaining what to
do with those points. Are those interactive?

**Comment by tufail** [comment]
> to this question the answer is a pattern.
> But you are not explaining what to
> do with those points. Are those interactive?

Hi @asturur , Actually I am looking to create actual coordinates which will be possible inside polygon based on the spacing value eg ( 20px ) and those points should be the circle shape inside polygon.

Just like https://observablehq.com/@floledermann/scanline-fill-algorithm 

That is why  I wrote the function to get return the possible array of points in  `calculateCoord: function(points, space){`
So I don't want the pattern to fill the polygon but on top of that we want to create new  circle shapes which can be select and can move if polygon is moving as a group.

**Comment by tufail** [comment]
Sorry
I got fixed @asturur  Thank you.
Here is what I wrote the algorithm for Scanline Polygon
```
calculateCoord: function(points, space){
    var array = [];
    var max = fabric.util.array.max;
    var min= fabric.util.array.min;
    var xmin = min(points, 'x');
    var ymin = min(points, 'y');
    var xmax = max(points, 'x');
    var ymax = max(points, 'y'); 
    var spacing_y = space;
    var spacing_x = space;
    var rows = Math.round((ymax - ymin)/spacing_y);
    var cols = Math.round((xmax - xmin)/spacing_x);
    var x = xmin;
    var y = ymax;
   for (var i = 0; i < rows+1; i++){
     for (var j = 0; j < cols+1; j++){
        if (this.pointInPolygon({x,y}, points)) {
           array.push({x,y});
        }
        x = x + spacing_x;
      }
     x = xmin + spacing_x;
     y =  y - spacing_y;
    } 
   return array;
}
```

**Comment by asturur** [comment]
Yeah this works, but won't work after you move the polygon around, or rotate, scale it.

The fix is easy in that case, just in case ask it here in this issue if you have to work on it. ( maybe you do not need it at all )
