### ISSUE TITLE
enableRetinaScaling not working with iPhone 11 Pro and iPhone 11 Max

### ISSUE THREAD

**Issue by wolfi1** [fabricjs/fabric.js#6332]
When enabling enableRetinaScaling iPhone 11 Pro and iPhone 11 Max just showing a blank canvas after calling canvas.loadFromJSON.

**Comment by wolfi1** [comment]
Happened because of exceeding canvas memory.

**Comment by asturur** [comment]
Just by curiosity, how big was your canvas, and how much is this max canvas memory on iphone 11 ?

**Comment by wolfi1** [comment]
The canvas memory of the iPhone 11 Pro/Plus should be 16MB. I didn't dig into fabricJs code but I think, that with enableRetinaScaling enabled (default) both, width and height are multiplied by Window.devicePixelRatio.

**Comment by asturur** [comment]
16mb is nothing. is like at 4 bytes per pixel  a 2kx2k canvas.
