### ISSUE TITLE
Cannot paste into a TextBox if text is selected before paste. 

### ISSUE THREAD

**Issue by sponno** [fabricjs/fabric.js#6333]
## Version
3.6.0

## Test Case
Can be reproduced using this demo page.
http://fabricjs.com/loadfonts

## Information about environment
Browser. Chrome

## Steps to reproduce
Double click on a TextBox or IText field. 
Select a word, then paste any text into over the selected word. 
![image](https://user-images.githubusercontent.com/70642/81748969-e3a3fa80-94fe-11ea-9521-b67e679b159f.png)

Pasting does work correctly when you haven not selected any text within the text box. 

It feels like this is related to issue #6172
https://github.com/fabricjs/fabric.js/pull/6172

Quick video of whats happening. 
![pasteerror](https://user-images.githubusercontent.com/70642/81749640-1b5f7200-9500-11ea-8ec1-96ec7aac7688.gif)

## Expected Behavior
Selected text would be replaced with contents of clipboard. 

## Actual Behavior
Javascript error
`fabric.js:27981 Uncaught TypeError: Cannot convert undefined or null to object`

**Comment by asturur** [comment]
i could have fixed it few days later. Let me try on latest master

**Comment by asturur** [comment]
seems fixed in 4 beta, needs a backport to 3.6.x

**Comment by asturur** [comment]
fixing with  https://github.com/fabricjs/fabric.js/pull/6418 and publishing as 3.6.4
