### ISSUE TITLE
Previous Selected Objects Bounding Box Does Not Update After Resize

### ISSUE THREAD

**Issue by christechno25** [fabricjs/fabric.js#6334]
**Version**
1.14.13

**Test Case**
https://jsfiddle.net/my1ht952/8/

**Information about environment**
Mozilla Firefox 76.0.1

**Steps to reproduce**
1) Select the 2 objects on the canvas.
2) Click on Resize button

**Expected Behavior**
So as soon as objects are added, upon clicking Resize button, selected objects will be resized to fit the canvas as much as possible. The first object should be situated at 0 Y-axis and the 2nd object at the height of the 1st object Y-axis. 1st object should be over 2nd object.

**Actual Behavior**
When the objects get resized, the previous bounding box doesn't update and it uses up space so the newly resized object wouldn't start at 0 Y-axis. Because of this, the 2nd object overlaps the canvas' limit.

Before Resize (Objects Selected)
![1](https://user-images.githubusercontent.com/13817176/81766097-0686dc80-9508-11ea-92d4-0bc87656338f.png)

After Resize
![2](https://user-images.githubusercontent.com/13817176/81766122-169ebc00-9508-11ea-87c6-df23389acaae.png)

Sorry I'm still using FabricJS 1.14.13. I did a project 5 years ago and I need to add this feature. getActiveGroup() doesn't work anymore in the current version. Actually a lot of what I did before don't work anymore in the current version so I can't switch to the new version.

https://github.com/fabricjs/fabric.js/issues/6113

The link mentioned seems to have the same problem as mine and I tried the code. It still leaves the previous bounding box or am I doing something wrong? Thank you so much.

**Comment by virror** [comment]
The easiest/quickest solution is probably to:
-Discard the selection from code
-Do your modifications
-Create the selection again from code

**Comment by christechno25** [comment]
> 
> 
> The easiest/quickest solution is probably to:
> -Discard the selection from code
> -Do your modifications
> -Create the selection again from code
> 
> Edit, also you offset issue is because when you have a selection, 0 is not the top/left corner, its the center of the selection. So to get the correct position, you need to use 0 - selection height / 2.
> See my updated fiddle here:
> https://jsfiddle.net/k18xoLbz/
> This does not solve the selection issue though, the first solution should work for both issues.

Thank you so much for this Sir. At least it partially solves the issue. Any idea why the selection issue occurs?

**Comment by asturur** [comment]
fabric 1.4 is so old, i m not even sure i remember the constrains of working with group there.

This is how you can do it with current fabric
https://jsfiddle.net/zdvbmpsj/
