### ISSUE TITLE
Problems with deserialisation - continuation of https://github.com/fabricjs/fabric.js/issues/5949

### ISSUE THREAD

**Issue by rbulph** [fabricjs/fabric.js#6335]
This is a continuation of thread [https://github.com/fabricjs/fabric.js/issues/5949](https://github.com/fabricjs/fabric.js/issues/5949) which stalebot again, in its wisdom decided to close.

I have now essentially got this working. It seems that firstly the arrow's fromObject method gets called. Then the reviver function returns the non-customised objects (that don't have their own fromObject) which I must add to the canvas.

The arrow needs to have references to the other objects. But these haven't been added when the Arrow's fromObject gets called. So I have to create an Arrow there, store a reference to it, then after loading has completed, set up the references to the other objects, and add the Arrow to the Canvas later. 

It seems to work although no doubt further issues will arise once I start looking at it in more depth.

**Comment by asturur** [comment]
you can ask to reopen the issue, is better than opening a new one. Continuosly opening new issues is the reason why i added stale bot.

**Comment by rbulph** [comment]
Can  you reopen it now please?

**Comment by rbulph** [comment]
Surely stale bot is what is causing people to keep opening new issues? I don't understand your point in your last post.

**Comment by asturur** [comment]
i reopened the original
