### ISSUE TITLE
Polygon move update points (x,y)

### ISSUE THREAD

**Issue by alexmelo23** [fabricjs/fabric.js#6336]
Hi everyone,
I have some problem with my project I create a polygon and I try change points coordinates by object move event but something not works or I'm doing something wrong 

http://jsfiddle.net/alexmelo/vmw0s7k4/#&togetherjs=cUnpy7pIHI

``
any idea what I do wrong?

Thanks

**Comment by asturur** [comment]
the fabricJS code was fine,
Seems more  a problem of confusion with array/map and mutation.

http://jsfiddle.net/zc3g089o/

**Comment by alexmelo23** [comment]
> confusion

ok thanks but if I print object.points after the move I get same points before the change

**Comment by asturur** [comment]
object.points never change.

**Comment by alexmelo23** [comment]
> object.points never change.

Ok How I can change polygon positions after move event ?

**Comment by asturur** [comment]
Well the only safe thing to do is to create a new polygon, but that will reset the object bounding box rotation. Can you be more explict in what you need the updated points for? you can calculate them on demand, so you have them handy. What's next, why the polygon should be updated with them?
