### ISSUE TITLE
Please Help background image is not resizing with objects

### ISSUE THREAD

**Issue by azeemgujjar** [fabricjs/fabric.js#6337]
i have grid image in background which is base64 format, i want to resize it with according to other zoom objects. means everything should be zoom simultaneously.

Here is my code:

https://jsfiddle.net/azeemgujjar/xbh1pzkq/1/

Please help

**Comment by sponno** [comment]
Don't use a Background image if you want it to zoom in and out. 
Add the background to an Object/Image and then it will zoom in out and with everything else.

**Comment by azeemgujjar** [comment]
My requirement is not like that.. i want to display base64 image in background which is first requirement that's why use setBackgroundImage..

**Comment by azeemgujjar** [comment]
> Don't use a Background image if you want it to zoom in and out.
> Add the background to an Object/Image and then it will zoom in out and with everything else.

I tried like this, but not working
`var canvas = new fabric.Canvas('canvas');
var img = new Image();
img.onload = function() {
    // this is syncronous
    var f_img = new fabric.Image(img);
    canvas.setBackgroundImage(f_img);
    canvas.renderAll();
};
img.src = myDataURL;`

**Comment by mirzasaad** [comment]
this is not a fabricjs issue
it seems like u want to make guide grid, and snap objects to it, don1t use the background image, use canvas.contextContainer to draw it above the canvas after the render call.

**Comment by asturur** [comment]
@azeemgujjar your fiddle is very large and confusing.
It seems you are not using the canvas setZoom api but rather you are multiplying the scale of every object.

From my understanding of your request you should just use setZoom in order to have everything zooming simultaneously.
