### ISSUE TITLE
Error when using a group as clipPath with the stateful option enabled

### ISSUE THREAD

**Issue by SoenkeHu** [fabricjs/fabric.js#6340]
## Version
4.0.0

## Test Case
http://jsfiddle.net/9cehdr0s/

## Steps to reproduce
Clip using a group with the stateful option enabled

## Expected Behavior
Clips the object

## Actual Behavior
This will produce the following error:
"RangeError: Maximum call stack size exceeded"

This seems to be a problem in the extend function, which loops somewhere in the clipPath object. (When the stateProperties are saved) 

Is there some kind of workaround for now?

**Comment by dekok** [comment]
no one else?
