### ISSUE TITLE
Incorrect Gradient behavior of Textbox when resizing/scaling or setting big number of font size

### ISSUE THREAD

**Issue by munbart** [fabricjs/fabric.js#6342]
## Version
3.6.3

## Test Case
https://jsfiddle.net/3eav2nfp/

## Information about environment
Chrome browser, MacOS, Retina display

## Steps to reproduce
Run code
## Expected Behavior
All texts must be with gradient
## Actual Behavior
The second and third text fills with the first color - red. If set fontSize greater than 128 or do scale it happens. 

### Any updates or solutions on how to resolve it? Thanks!

**Comment by munbart** [comment]
Any updates or solutions on how to resolve it? Thanks!

**Comment by asturur** [comment]
I think is yet another chrome drawing bug.
![image](https://user-images.githubusercontent.com/1194048/82740081-a254eb80-9d45-11ea-808a-3bf4dff3e038.png)

firefox seems fine.

![image](https://user-images.githubusercontent.com/1194048/82740090-c31d4100-9d45-11ea-9db0-86b4c9fdd2cb.png)

safari is fine.

 We should reproduce in plain JS and open a chrome bug.

**Comment by munbart** [comment]
@asturur Thanks for the answer

**Comment by munbart** [comment]
@asturur How are things coming along with Chrome issues? Have you created a ticket? Could you share some updates?

**Comment by asturur** [comment]
i didn't manage to reproduce in js yet without fabric

**Comment by munbart** [comment]
@asturur Do you have some ETA when it can be done?

**Comment by asturur** [comment]
there is no guarantee chrome will fix anything. I sometimes open bug to them, some get fixed other never.

**Comment by munbart** [comment]
Here is a link where in plain js without fabric the same bug
https://jsfiddle.net/1toenj3z/

**Comment by asturur** [comment]
thank you!

**Comment by munbart** [comment]
@asturur Chrome devs already fixed that and it will come in new version v84 (checked on beta)

**Comment by asturur** [comment]
oh this is great. So i think i can close the issue?
