### ISSUE TITLE
Original Image Quality

### ISSUE THREAD

**Issue by anoopm7** [fabricjs/fabric.js#6343]
Hi Guys,

Scenario/What I am doing:  I load an image using Image.FromURL (datauri), scale it, add lines and/or shapes to it. No filters are applied.

Problem: When I export this (with multiplier) the image produced is of degraded (lesser) quality.

I'm using version 3.5.0 and facing issues with preserving original Image Quality while scaling. I've been scratching my head after this without any luck. After debugging I figured that scaleX and scaleY on Image.fromURL causes image to loose quality. Export of this scaled canvas (with multiplier) to original dimension results in a poor image quality of the original image. No other filters are applied to image. 

What is the right way to preserve the original image, after scaling?

https://jsfiddle.net/op8wLb9d/3/

**Comment by anoopm7** [comment]
![image](https://user-images.githubusercontent.com/7464396/82284756-19545200-99dd-11ea-9483-f4803bca7ae3.png)

**Comment by asturur** [comment]
Seems to me that the image starts as bad quality already:

![image](https://user-images.githubusercontent.com/1194048/82742288-7b55e400-9d5c-11ea-8b7a-8a6a73d5ef1e.png)

Scaling by 2.5 will cause more fuzzyness and scaling artifact.

Ca

**Comment by anoopm7** [comment]
Thanks asturur. I'm trying to scale down, not scale up. 
Yes the image is not the best of  quality, however I'm trying to preserve its original quality during scale down. Any suggestions how can I keep the image as is while using ScaleX (down) and ScaleY (down)?

**Comment by anoopm7** [comment]
I am trying to resize down to a scale of 0.4. I did a comparison in a jsfiddle (included in first message). IF using HTML5 canvas the scale down to 0.4 does not result in quality loss. But scale down to 0.4 using fabricjs results in quality loss. I would expect the resize (down) to 0.4 without losing any quality of the original image, This is apparent when I export or zoom (scaleup back to original with a multiplier) the image is not of same quality. Am I doing something wrong? If not, what is the way to preserve image quality while still using ScaleX, scaleY in fabricJS

const SCALE_F=0.4;

oImg.set({
                            oImg.scaleX = SCALE_F;
                            oImg.scaleY = SCALE_F;
                });

**Comment by minhncud** [comment]
when you download, did you try .toDataURL({format: 'png', quality:1}); ? 
Quality = 1 give you the best image it can while it's 'heavier' (KB size is higher).
