### ISSUE TITLE
where can I set freeDrawingBrush's properties ?

### ISSUE THREAD

**Issue by Bendjen** [fabricjs/fabric.js#6344]
"There's also 2 properties available to customize free drawing — freeDrawingBrush.color and freeDrawingBrush.width. Both are available on Fabric canvas instances through freeDrawingBrush instance. freeDrawingBrush.color can be any regular color value and represents the color of a brush. freeDrawingBrush.width is a number in pixels, and represents brush thickness"
in tutorial 4 Introduction to Fabric.js: Part 4.
But in docs ,I can not find where to set  freeDrawingBrush.color and  freeDrawingBrush.width.
By the way , I wonder if I can freedraw in different layers?

**Comment by asturur** [comment]
Hi @Bendjen.
this demo here http://fabricjs.com/freedrawing while a bit outdated, shows all kind of brushes that are available with fabricJS.
Is possible to create more of course.

The color and width are of the brush class itslef.

```js
var brush = new fabric.PencilBrush();
brush.color = 'red';
brush.width = 4;
canvas.freeDrawingBrush = brush;
```

**Comment by Bendjen** [comment]
thanks
