### ISSUE TITLE
EnterEditing doesn't run

### ISSUE THREAD

**Issue by sbraaa** [fabricjs/fabric.js#6345]
## Version
4.0.0 beta 11

## Information about environment
chrome and firefox latest versions available 

## Steps to reproduce
this code:

var text = new fabric.IText('mytext', {
	left: 100,
	top: 200,
	padding: 7,
});

canvas.add(text);
canvas.setActiveObject(text);
text.selectAll();
text.EnterEditing();
text.hiddenTextarea.focus();

always gives error on line text.EnterEditing(); saying that EnterEditing is not a function.

a lot of examples are available (e.g. http://jsfiddle.net/manodxqj/2/) which runs with with previous versions but with version 4 there's no way.

**Comment by melchiar** [comment]
It should be `enterEditing()`, not `EnterEditing()`

**Comment by sbraaa** [comment]
You are right! Sorry, my mistake
Thanks fot the answer.
