### ISSUE TITLE
Canvas Touch Not Working on Windows Tablet

### ISSUE THREAD

**Issue by dhirusarania** [fabricjs/fabric.js#6346]
I'm using a custom build of v3.6.3 with Gestures.

Canvas panning and pinch zoom are working on desktop and also working on mobile devices. But when I use a windows tablet, it only takes mouse input. And touch events are not triggered.

`canvas.on({`
`'touch:gesture': function(e) {
            // console.log("Touch gesture")
        },`
`'touch:drag': function(e) {
            // console.log("Touch gesture")
        }
    });`

The above two events are not triggered when using touch gestures on windows tablet.

**Comment by asturur** [comment]
It could be that the event library we hooked up is not coping with the windows tablet.
What browser? does it support touch events or just pointer?

Does the normal interaction work?
