### ISSUE TITLE
subTargetCheck not working: Cannot interact with children in group

### ISSUE THREAD

**Issue by iyobo** [fabricjs/fabric.js#6347]
## Version
<= 4.x

Cannot interact with children in group. group.subTargetCheck does not work like docs say.
http://jsfiddle.net/iyobo/bhpsfavr/4/

**Comment by asturur** [comment]
subTargetCheck will let you fire events, not interact with children in groups.
Please provide a fiddle that shows the broken feature, that fiddle is not exactly pointing to any problem.
