### ISSUE TITLE
Copy canvas maybe delay information - loadFromJSON(JSON.stringify(canvas)

### ISSUE THREAD

**Issue by minhncud** [fabricjs/fabric.js#6348]
## Version
3.6.1 (this is mine, not sure in test at jsfiddle.net)

## Test Case
http://jsfiddle.net/mobd9xp5/

## Information about environment
Firefox, Chrome

## Steps to reproduce (as test)
1) Maybe bug:
- I add an image to canvas, then add a rectangle (error stills happen if does not add rectangle)
- I copy current canvas to another (copy_canvas) by:
```
var strCanvasContent = JSON.stringify(canvas);
copy_canvas.loadFromJSON(strCanvasContent, copy_canvas.renderAll.bind(copy_canvas));
```
- Then I want to get informations of objects in copy_canvas. But when function fires at the 1st times, it shows **-undefined**. And at the 2nd times, it shows the right information. Why did it happen and how to fix it? 
 * Function: 
```
var o1 = copy_canvas.item(0);
console.log("item0 -" + JSON.stringify(o1));
```
At the test, you should click button "Copy Canvas" twice times and look at the console log.
---
2) Another question: 
I need a clone canvas to using clipPath and setDimensions it to download image after cropped. The only way i found is ".loadFromJSON (JSON.stringify(canvas))" . But this way i can not getActiveObject to remove (the crop rectangle) before using clipPath. :( Do you have any idea?

**Comment by asturur** [comment]
loadFromJSON is async, if you want to read objects on `copy_canvas` you have to do it in the callback where you are actually rendering.

I m not sure what are you actually trying to do, if you could be more specific, i could maybe help.

**Comment by minhncud** [comment]
Thank you, i try to make a small point to edit image using fabricjs. I have a problem when try to **resize and crop image after zoomed** more than 1 times (a version resized without crop and once is resized after cropped). I read tutorials and found clipPath to crop. But after resize and crop, I need download it without background. I think about 2 ways: 
1) setDimensions of canvas to fit cropped image. (this way makes "undo" can not get old size of canvas to edit more version after cropped)
2) Using a clone canvas to edit, resize, crop... but this way using ".loadFromJSON (JSON.stringify(canvas))" , so clone_canvas.getActiveObject() shows undefined. 
I crop by using canvas.clipPath(rect) so i need remove rect before clip. 
---
Images:
![dr1](https://user-images.githubusercontent.com/36953180/82772356-218f1000-9e69-11ea-963d-2d5fe67bcc99.jpg)

![dr2](https://user-images.githubusercontent.com/36953180/82772365-2784f100-9e69-11ea-93fe-03c5347dc80d.jpg)

---
Other, a small bug when i try to change size of a small rectangle, it shows old size and new size at the same times. Sample: http://jsfiddle.net/t3wy2mn5/ . And it won't happen when resize a large rectangle.

**Comment by minhncud** [comment]
Thank you, i try to make a small point to edit image using fabricjs. I have a problem when try to resize and crop image after zoomed more than 1 times (a version resized without crop and once is resized after cropped). I read tutorials and found clipPath to crop. But after resize and crop, I need download it without background. I think about 2 ways:

1)   setDimensions of canvas to fit cropped image. (this way makes "undo" can not get old version of canvas without clip frame)
2)   Using a clone canvas to edit, resize, crop... but this way using ".loadFromJSON (JSON.stringify(canvas))" , as i understand, it will copy rect to the clone, right? 
But this way make me can not get the rect of clone canvas to remove. 
I crop image by using canvas.clipPath(rect) so **i need remove rect before crop**.
---
![dr1](https://user-images.githubusercontent.com/36953180/82774165-476ae380-9e6e-11ea-9dbe-1a73128d9253.jpg)
![dr2](https://user-images.githubusercontent.com/36953180/82774172-4c2f9780-9e6e-11ea-8ab8-2a1239f237bd.jpg)

---
Other, a small bug when i try to change size of a small rectangle, it shows old size and new size at the same times. Sample: http://jsfiddle.net/t3wy2mn5/ . And it won't happen when resize a large rectangle.
![dr3](https://user-images.githubusercontent.com/36953180/82774183-5356a580-9e6e-11ea-8281-544827d53a8c.jpg)

**Comment by minhncud** [comment]
My problem is gone, but the last bug i post, i can not fix it by myself. Btw thank you very much :D
