### ISSUE TITLE
SVG size not set in to Clip Functionality

### ISSUE THREAD

**Issue by sagarvibrant** [fabricjs/fabric.js#6349]
http://jsfiddle.net/darshan0207/wantyo2f/
How can i change SVG Path Size ?

**Comment by asturur** [comment]
Hi @sagarvibrant  the clipTo functionality is deprecated since 2.4 and i encourage you to not use it.
Please try the clipPath functionality as described in docs here:
http://fabricjs.com/clippath-part1

**Comment by asturur** [comment]
If you need more help, continue to use this issue please.
