### ISSUE TITLE
Support adding control points to Text

### ISSUE THREAD

**Issue by juzhiyuan** [fabricjs/fabric.js#6350]
**Is your feature request related to a problem? Please describe.**
After searching on GitHub and StackOverflow, I'm not sure if fabric.js supports the ability to add control points to Text object, then the text is changed to SVG actually. 

**Describe the solution you'd like**
1. Convert Text to SVG Object;
2. Add control points to it;

**Describe alternatives you've considered**
None

**Additional context**
1. http://fabricjs.com/test/svg_export/text.html

**Comment by asturur** [comment]
Hi @juzhiyuan is very hard for me to understand what you are trying to do. Could you be please more clear?

**Comment by juzhiyuan** [comment]
sure, I will add a clear demo here tomorrow :)

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/82782743-a8ef7a00-9e8f-11ea-8a13-10736ec3dadf.png)

Hi @asturur, I'm not sure if the screenshot(from illustrator) above is clear for you? 🤔Type some text, and then convert it to SVG, then parse and show many control points.

**Comment by juzhiyuan** [comment]
I think it can be done by Pen tool 🤔 Illustrator make it possible to text and parse to control points directly.

**Comment by asturur** [comment]
In order to get those points you need to do some integration with openType.js, the first library that comes to my mind.
Once you have it, you can have the path information for each glyph, and with custom controls api, as taken from here:
http://fabricjs.com/custom-controls-polygon

you can write code to modify it. Is a long road and is a lot of code, but you can do it.

**Comment by juzhiyuan** [comment]
Thanks for your reply!!

**Comment by MillerRen** [comment]
@juzhiyuan You can do it with opentype.js. opentype.js render text, and then export to fabric.js.
