### ISSUE TITLE
IText origin center not placed correctly

### ISSUE THREAD

**Issue by jangelo** [fabricjs/fabric.js#6352]
## Version
3.6.3

## Test Case
https://jsfiddle.net/nk6pb8x3/1/

## Information about environment
browsers

## Steps to reproduce
Add an IText object to the canvas with both the originX and originY set to center.  Set the top and left both to 0.

const textObject = new fabric.IText('o', {
  fontSize: 200,
  fill: "#FF0000",
  left: 0,
  top: 0,
  originX: 'center',
  originy: 'center',
});
canvas.add(textObject);
canvas.renderAll();
 

## Expected Behavior
Both originX and originY are centered.
The center of the "o" would be in the top left corner.

## Actual Behavior
Only the originX is centered and not the originY.

Thank you and left me know if I am doing something wrong.

**Comment by melchiar** [comment]
Looks like you've got a lowercase y in originy (should be originY)

**Comment by jangelo** [comment]
@melchiar Thank you so much! Sorry about the user error.  I was so perplexed and spent way too long trying to figure out what was going on. This really saved me so I'm very grateful.
