### ISSUE TITLE
total canvas memory use exceeds the maximum limit

### ISSUE THREAD

**Issue by Lostbrokenkey** [fabricjs/fabric.js#6353]
The error occurs instantly by running the fiddle and
I could reproduce it on every iOS - simulator and device i ran the fiddle on

## Version
3.6.3

## Test Case
https://jsfiddle.net/sL7zp9bg/6/

## Information about environment
Safari (iOS 13.5, iPhone 8)

<img width="742" alt="Bildschirmfoto 2020-05-27 um 15 02 51" src="https://user-images.githubusercontent.com/5960337/83022055-3d421400-a02b-11ea-8e7b-7fbbedbf7eeb.png">

**Comment by awehring** [comment]
Have you tried to set a size for the canvas, like 

`<canvas id="c" width="600" height="600"></canvas>`

**Comment by Lostbrokenkey** [comment]
Thank you @awehring that was my issue, with setting height und width it's working well
