### ISSUE TITLE
Is there a wrapper for React native to use fabric js?

### ISSUE THREAD

**Issue by VishalTennyson** [fabricjs/fabric.js#6354]
Currently I want to integrate my website as an android application  and would require to use react native as frontend...So is there a way I can use fabric js???

**Comment by melchiar** [comment]
Support for react has actually been discussed recently and has an already open issue. I'm going to close this issue since it's a duplicate but feel free to contribute to the discussion there. 

https://github.com/fabricjs/fabric.js/issues/6208

**Comment by gigadeplex** [comment]
> Support for react has actually been discussed recently and has an already open issue. I'm going to close this issue since it's a duplicate but feel free to contribute to the discussion there.
> 
> #6208

React and React Native are not the same thing lol.

**Comment by asturur** [comment]
Does React Native gives you a Canvas? otherwise no
