### ISSUE TITLE
Borders of object blurring when scaling them.

### ISSUE THREAD

**Issue by proman24** [fabricjs/fabric.js#6355]
## Version
3.6.0

## Test Case
https://jsfiddle.net/gm2406/ajth1xqe/

## Steps to reproduce

Try to scale up the rectangle in the fiddle by corners or by sides.

## Expected Behavior

The Stroke width should be updated as we scale up without waiting for the mouse up event.

## Actual Behavior

The stroke width is getting blurred while scaling, the width of the stroke is not updated while we are scaling.
![scaling_issue](https://user-images.githubusercontent.com/18314265/83035960-b8b9ba80-a057-11ea-91e3-b2a3ee1684bb.gif)

**Comment by melchiar** [comment]
What you're seeing is object caching at work. You can disable this behaviour during scaling with the `noScaleCache` property. 

See http://fabricjs.com/fabric-object-caching for more info on caching.

**Comment by proman24** [comment]
Thank you @melchiar .
