### ISSUE TITLE
The eraser is not for all path objects

### ISSUE THREAD

**Issue by Mamikon95** [fabricjs/fabric.js#6356]
Hello, I have such a problem, there is an eraser, I want it to not work for all objects. For example, there is a red path and a green path. When using the eraser, I want the green color to be removed, and so that it does not hurt the red path, in this example, for example - http://prntscr.com/soyu6l. In the combat project, there are more colors and everything is dynamic.

Test Case - https://jsfiddle.net/hybumkcp/8/

**Comment by asturur** [comment]
Hi @Mamikon95 there is no official support for erasers and i won t be able to provide an example for you

**Comment by ShaMan123** [comment]
The eraser has moved https://github.com/ShaMan123/erase2d
