### ISSUE TITLE
Canvas loadFromJson is not being able to work with sprite objects

### ISSUE THREAD

**Issue by NeelDroid** [fabricjs/fabric.js#6358]
## Version
3.6.0

## Test Case
http://jsfiddle.net/hLqw7ms3/1/

## Information about environment
Google Chrome Version 83.0.4103.61 (Official Build) (64-bit)

## Expected Behavior
sprite should load just like other fabric elements

## Actual Behavior
gives error & entire loadFromJson call fails

**Comment by melchiar** [comment]
Sprite isn't actually a native fabric class, so you'll have to define it first. The [sprite demo](http://fabricjs.com/animated-sprite) includes a link to http://fabricjs.com/js/sprite.class.js as an example sprite class definition, although the example doesn't appear to include a `fromObject` method for deserializing the sprites from json strings so you would need to define that yourself.

https://github.com/fabricjs/fabricjs.com/issues/176

**Comment by asturur** [comment]
we should update the class or remove the
demo i guess. Also maybe check if the apng format is a modern alternative.
