### ISSUE TITLE
Large Rect Object render bug

### ISSUE THREAD

**Issue by SvenWangChina** [fabricjs/fabric.js#6359]
## Version
3.6.3

## Test Case
http://jsfiddle.net/tac0dwh4/

## Information about environment
Nodejs
Test on chrome v83.0.4103.61

## Steps to reproduce
add follow Rect object to canvas:
new fabric.Rect({
    fill: 'red',
    left: 100,
    top: 100,
    width: 18432,
    height: 12474,
})

## Expected Behavior
around rect opacity is 1

## Actual Behavior
the top of rect opacity is not 1

I create large Textbox and set backgroundColor, it have the same bug.

**Comment by melchiar** [comment]
Please see the following guide on object caching. http://fabricjs.com/fabric-object-caching

At that size, your objects are far larger than the cache canvas. If you really need them to be this large, you should probably disable `objectCaching`.

**Comment by SvenWangChina** [comment]
OK,thanks.
