### ISSUE TITLE
fabric.Control is not a constructor on V4.0.0-beta.12

### ISSUE THREAD

**Issue by CKitisak** [fabricjs/fabric.js#6361]
based on this tutorial http://fabricjs.com/custom-controls-polygon I stuck at this problem below when I clicked on a "Toggle editing polygon" button.
My `custom-control.js` file is exactly same like in the tutorial (copy/paste) and I'm using `fabric.js-4.0.0-beta.12` downloaded from https://github.com/fabricjs/fabric.js/releases. Please give me some advice on what I did wrong or missing. thank you.

```
Uncaught TypeError: fabric.Control is not a constructor
    at custom-control.js:101
    at Array.reduce (<anonymous>)
    at Edit (custom-control.js:100)
    at HTMLButtonElement.onclick ((index):11)
```

Update:
It works when I use fabric from the CDN https://unpkg.com/fabric@4.0.0-beta.11/dist/fabric.js.

**Comment by asturur** [comment]
ho @CKitisak i m not building the fabricjs dist folder every beta, only the npm publish process is building the file. This will go back to normal
as soon as we are out of beta. Please downloading from cdn or npm is the thing to do for now.

**Comment by dingguoqing513** [comment]
1. version > 4.0
2. Don‘ t use fabric.js file
so，you can execute this command: 
`sudo npm i fabric@4.0.0-beta.12`

**Comment by saninmersion** [comment]
I am using fabricjs 3.6.3 installed from npm and have the same issue. Any fixes? or should I upgrade it to a beta version?

**Comment by asturur** [comment]
@dingguoqing513 comment should work.
