### ISSUE TITLE
Freedrawing with no-rounded corners

### ISSUE THREAD

**Issue by Nevyn1975** [fabricjs/fabric.js#6362]
Hi.

I'm developing an editor for small images, so I'm simulating a pixel-size view by zooming the canvas content and by adding a grid.

The problem is that, when I activate the freedrawing mode and try to draw an "L" (e.g.) this is the result:

![L](https://user-images.githubusercontent.com/65671010/83422063-436c3200-a429-11ea-92d0-9a3bca941766.png)

The angle is not 90° but on mouseUp is rounded.

Is there a way to avoid this behavior?

I configured PencilBrush as following:

`this.canvas.freeDrawingBrush.strokeLineCap = 'square'
 this.canvas.freeDrawingBrush.strokeLineJoin = 'miter'
 this.canvas.freeDrawingBrush.strokeMiterLimit = 0`

I tried with many values for miter limit but I didn't noticed any difference...

"fabric": "^3.6.3"

Thanks for help.

**Comment by asturur** [comment]
There are 2 issues here.

One is that pencil brush is using quadratic curves and will probably always be roundy.

The other issue is that we have a 'decimate' parameter on the brush that is smoothing the curve, you can try to set it to 0 and see if things improve.

Alternatively you have to write your own brush

**Comment by Nevyn1975** [comment]
Thank you very much for your feedback!

By setting decimate value I had no improvements (as you supposed), so I tried to block the rendering on mouseUp.
I tried overriding _onMouseUpInDrawingMode handler of canvas and change it this way:

```
this.canvas._onMouseUpInDrawingMode = function(e) {
        if (this.clipTo) {
          this.contextTop.restore()
        }
        // var pointer = this.getPointer(e)
        this._isCurrentlyDrawing = false
        this.freeDrawingBrush.oldEnd = undefined
        // this._isCurrentlyDrawing = this.freeDrawingBrush.onMouseUp({ e: e, pointer: pointer })
        this._handleEvent(e, 'up')
      }
```
The result is much better: when I move the mouse slowly the line is like I expected, but when I accelerate the movement a little bit, the line is rounded.

![Schermata del 2020-06-03 11-20-57](https://user-images.githubusercontent.com/65671010/83620162-39fbda80-a58d-11ea-8e1c-f3825c61109c.png)

Any more little hints?

Thanks

**Comment by Nevyn1975** [comment]
Ok... as I guessed simply removing the standard brush mouseUp handler has too bad side effects...

At this point your proposed solution to implement a custom brush maybe is the only right way.

Could you please give some hints or example on how to implement a custom brush that acts correctly for my needs?

Thank you very much.

**Comment by Nevyn1975** [comment]
Hi.

I managed to implement a custom brush by taking as example the fabric code.
Thank you for your hint.
