### ISSUE TITLE
when I use the toDataURL,it has some problems

### ISSUE THREAD

**Issue by joylord2018** [fabricjs/fabric.js#6365]
![QQ图片20200603115249](https://user-images.githubusercontent.com/37334673/83594071-d07dcb00-a590-11ea-81a8-eadf64b87583.png)
![QQ图片20200603115311](https://user-images.githubusercontent.com/37334673/83594078-d378bb80-a590-11ea-902f-758863263909.png)

**Comment by asturur** [comment]
We can t support custom vue and react use cases. You are probably drawing before the canvas element is created and the context is null.

**Comment by itsrachelfish** [comment]
@asturur I am also getting this issue. But I'm pretty sure the canvas element has already been created. I am able to add text and image objects to the canvas, resize and move things around, but when I try to render the canvas with `toDataURL` it gives me this error. 

Everything was working in fabric v2 however after upgrading to v3 `toDataURL` no longer works. Everything else appears to be working as expected. Pretty confusing! 

Any advice on how to dig deeper into what's going on here would be appreciated.

**Comment by itsrachelfish** [comment]
@joylord2018 @asturur I was able to solve this problem by referencing the canvas element directly instead of trying to use the fabric.js `toDataURL` wrapper. 

`const jpegUrl = canvas.lowerCanvasEl.toDataURL('image/jpeg');`

**Comment by asturur** [comment]
is hard for me to figure out what is going on without local debugging.
