### ISSUE TITLE
How to draw dividing rule as coordinate in canvas with fabricjs ?

### ISSUE THREAD

**Issue by Bendjen** [fabricjs/fabric.js#6366]
How to draw dividing rule as coordinate in canvas with fabricjs ?

**Comment by asturur** [comment]
Hi @Bendjen sorry but is completely unclear what are you asking. Provide examples and a simple code built.

**Comment by Bendjen** [comment]
> Hi @Bendjen sorry but is completely unclear what are you asking. Provide examples and a simple code built.
![timg](https://user-images.githubusercontent.com/20695625/83605765-0f207f00-a5ab-11ea-8914-d129cfe52d42.jpg)
I want to draw the coordinate system like this.

**Comment by asturur** [comment]
If you want it to be a sort of dynamic ruler i should use the before:render event and draw it with native browser canvas api

There isn't such a thing in fabricjs although an external plugin would be a nice to have.

**Comment by Bendjen** [comment]
> If you want it to be a sort of dynamic ruler i should use the before:render event and draw it with native browser canvas api
> 
> There isn't such a thing in fabricjs although an external plugin would be a nice to have.
thanks
