### ISSUE TITLE
Crop Image after scaled image to resize because resized image has same state-size with original image.

### ISSUE THREAD

**Issue by minhncud** [fabricjs/fabric.js#6368]
I'm successful on resizing the original image (download-ok) or cropping the original image (download-ok) but I can not crop after resized image because rect's coordinates always work with original image width and height. 

- After i resize image by scaling, the resize image's width and height are as same as original's. So i can not crop it by rectangle. (wrong coordinates )
- Test on http://jsfiddle.net/ecz2q3xu/
- I want the resize image is real, not only a scale of original image.

- My question on SO is [https://stackoverflow.com/questions/62186822/how-to-scale-and-change-state-of-original-image-on-fabric-canvas](url) 

- My question can be same here: https://github.com/fabricjs/fabric.js/issues/6041 But his way does not resolve my problem.
- In fact, I have to zoom canvas before/after resize or crop but i think it's not the problem.

**Comment by minhncud** [comment]
what do you mean, bot?

**Comment by ramneet-chopra** [comment]
> what do you mean, bot?



> I'm successful on resizing the original image (download-ok) or cropping the original image (download-ok) but I can not crop after resized image because rect's coordinates always work with original image width and height.
> 
> * After i resize image by scaling, the resize image's width and height are as same as original's. So i can not crop it by rectangle. (wrong coordinates )
> * Test on http://jsfiddle.net/ecz2q3xu/
> * I want the resize image is real, not only a scale of original image.
> * My question on SO is [https://stackoverflow.com/questions/62186822/how-to-scale-and-change-state-of-original-image-on-fabric-canvas](url)
> * My question can be same here: #6041 But his way does not resolve my problem.
> * In fact, I have to zoom canvas before/after resize or crop but i think it's not the problem.

did you find solution.?
i am also facing same problem

**Comment by ramneet-chopra** [comment]
i figured out the solution by using following method
1. display crop rectangle over image which is resizable and movable accross image
2. crop image using following code where
selectionRect is dynamic reactangle behaving as cropper and fabric rect object,
imageToBeCropped is fabricjs image object
`let imageUrl = imageToBeCropped.toDataURL({
      left: selectionRect.oCoords.tl.x - image.oCoords.tl.x,
      top: selectionRect.oCoords.tl.y - image.oCoords.tl.y,
      width: selectionRect.width * selectionRect.scaleX,
      height: selectionRect.height * selectionRect.scaleY,
    });
    fabric.util.loadImage(imageUrl, (source) => {
      if (image.type !== "image") {
        image.setPatternFill(
          {
            source,
            repeat: "repeat",
          },
          null
        );
        image.setCoords();
        canvas.renderAll();
        return;
      }
      image.setElement(source)
     // replace dimensions below with required dimensions of container where image needs to be placed
      image.set({
        selectable: true,
        top: dimensions.top,
        left: dimensions.left,
      });
      image.setCoords();
      canvas.setActiveObject(image);
      canvas.remove(selectionRect);
      canvas.renderAll();
    });`
