### ISSUE TITLE
Problems with selecting objects from a group

### ISSUE THREAD

**Issue by clngkusnd** [fabricjs/fabric.js#6369]
I'm currently creating my own custom group class with extended group functionality. I've created a feature where objects in the group can be selected.

Everything works perfectly when the group hasn't been modified. However, there are some problems come when the group is scaling, rotating and skewing.

I already asked in the StackOverflow. I have included a link to jsfiddle there. I am very grateful if someone can help my problem.

Here's the link:
https://stackoverflow.com/questions/62186778/problems-with-selecting-objects-from-a-group

**Comment by asturur** [comment]
i added an answer thare
