### ISSUE TITLE
Loosing focus on edited textbox

### ISSUE THREAD

**Issue by jsprzybylski** [fabricjs/fabric.js#6370]
## Version
3.6.2

## Test Case
http://fabricjs.com/loadfonts

## Information about environment
Nodejs or browser?
Browser

Which browsers?
Probably all

## Steps to reproduce
1. Edit text
2. While in edit mode change font using select
3. Try typing text without clicking on anything
4. Click on textbox and edit text

## Expected Behavior
Unfocusing textbox element so that the user can't see the blinking cursor.

## Actual Behavior
Textbox seems focused while in reality it's not.

**Comment by asturur** [comment]
This is a known problem.
Detecting clicks outside fabricJS canvas is out of scope for the library and setting js events on focus loss on the textbox does not always brings the results we expect.

We should think of a way to explain how to possibly handle this.

**Comment by chenyiqiao** [comment]
you can mannualy set textbox into editing state after the action that cause textbox blur, if the action is a known one. In your case it's the select event.
```js
// after action
textbox.enterEditing();
textbox.hiddenTextarea.focus();
```

**Comment by ShaMan123** [comment]
> This is a known problem. Detecting clicks outside fabricJS canvas is out of scope for the library and setting js events on focus loss on the textbox does not always brings the results we expect.
> 
> We should think of a way to explain how to possibly handle this.

When not adding logic to canvas blur event?
