### ISSUE TITLE
typescript definition for Image.filters would not allow adding custom image filters

### ISSUE THREAD

**Issue by sheunglaili** [fabricjs/fabric.js#6373]
## Version
3.6.3

## enviroment 

Typescript / react

## Steps to reproduce

try to create image filter as mentioned in [tutorial](http://fabricjs.com/fabric-intro-part-2#image_filters) with typescript

## Expected Behavior
able to add image filters into the filters array

## Actual Behavior

The IAllfilters Interface will make the typing wrongs

**Comment by asturur** [comment]
This library does not support typescript as of today. We do not have an official type definition file yet.
If you have a better description and suggestion other than `The IAllfilters Interface will make the typing wrongs` i m happy to discuss the issue and reopen it.

**Comment by Zaynex** [comment]
@asturur , awe proejct!  do you have any plan about supporting typescript ?

**Comment by asturur** [comment]
i do not have time for it and since i m not a typescript user is hard. Also no one else seems really interested in doing it in an official way for now.
