### ISSUE TITLE
Mobile Scrolling is not working 

### ISSUE THREAD

**Issue by lynmije** [fabricjs/fabric.js#6374]
## Version
3.6.3

## Information about environment
Mobile devices

## Steps to reproduce
- I have a div scrollable with canvas on it. On mobile device i dont have an ability to scroll the canvas. Touch event is working but its just no scrolling, Added allowTouchScrolling but its still not working.

**Comment by melchiar** [comment]
Touch scrolling is actually a known bug. I'm going to close this issue since it's a duplicate but feel free to contribute to the discussion here: https://github.com/fabricjs/fabric.js/issues/5903
