### ISSUE TITLE
Custom control doesn't render correctly on FireFox

### ISSUE THREAD

**Issue by CKitisak** [fabricjs/fabric.js#6376]
regarding to this example http://fabricjs.com/custom-control-render
when I open with Google Chrome everything looks good but when I try with FireFox the clone icon doesn't seem to be render even I removed the delete icon.

when open on GoogleChrome
![Selection_003](https://user-images.githubusercontent.com/2785185/84108716-0a484900-aa4b-11ea-9e35-d1c3193f349f.png)

when open on FireFox
![Selection_004](https://user-images.githubusercontent.com/2785185/84108719-0e746680-aa4b-11ea-996a-c05eeb66a103.png)

commented out the delete icon
![Selection_005](https://user-images.githubusercontent.com/2785185/84108725-1502de00-aa4b-11ea-965a-fff1a8b459f4.png)

**Comment by asturur** [comment]
Was missing the width and height specs on the svg. Fixed, thanks.
