### ISSUE TITLE
iOS 13.4 and 13.5 : only one mouse:up event instead of two when double tapping

### ISSUE THREAD

**Issue by rlebosse** [fabricjs/fabric.js#6378]
## Version
2.6.0 and 2.7.0

## Test Case
* Using fabric 2.7.0 (bug is present) : https://codepen.io/rlebosse/pen/abdvQOO
* Using fabric 2.6.0 (bug is present) : https://codepen.io/rlebosse/pen/GRopwJM
* Using fabric 3.6.3 (for comparison) : https://codepen.io/rlebosse/pen/LYGpXPN

## Information about environment
* Safari on iOS 13.4 and 13.5

## Steps to reproduce
* Open codepen
* Double tap quickly on the red square

## Expected Behavior
* 2 objects events named **mouse:up** are supposed to be added below the red square

![Capture d’écran 2020-06-09 à 10 36 37](https://user-images.githubusercontent.com/2794137/84125640-1b8a5900-aa3d-11ea-9be7-49cdbb1572a5.png)

## Actual Behavior
* iOS 13.4 / 13.5 + fabric 2.6.0 / 2.7.0 : only one object event named **mouse:up** is added below the red square : **one event is missing** !

![image](https://user-images.githubusercontent.com/2794137/84125590-08778900-aa3d-11ea-8b16-0529697ce62b.png)

## For comparison

* iOS 13.4 / 13.5 + fabric 3.6.3 : the 2 mouse:up events are logged : OK 👍 
* iOS 13.3 + fabric 2.6.0 / 2.7.0 : the 2 mouse:up events are logged : OK 👍

**Comment by asturur** [comment]
hi @riebosse, thanks for the detailed issue.
Does fabric 3.6.3 work fine on all IOS version you could test?
If yes, is this a bug report for fabric version 2.x?
Because in that case we can't fix it, but you can backport the fix ( once we understood which is it ) by yourself in the 2.x branch
