### ISSUE TITLE
Group discardactiveobject internal object left top wrong

### ISSUE THREAD

**Issue by HDONGDeveloper** [fabricjs/fabric.js#6379]
After using the group package, use to move it, and then discard the group through discardactiveobject. At this time, the object top and left coordinates inside the group will become negative. Can you provide a function to correct it

![image](https://user-images.githubusercontent.com/31230864/84144014-24ede280-aa8a-11ea-9d16-0912492f9117.png)
![image](https://user-images.githubusercontent.com/31230864/84144048-2fa87780-aa8a-11ea-907d-7e3dc626e602.png)

**Comment by HDONGDeveloper** [comment]
![image](https://user-images.githubusercontent.com/31230864/84144731-57e4a600-aa8b-11ea-9e3e-be7735a52169.png)

**Comment by HDONGDeveloper** [comment]
After removing the first level group discardactiveobject

How to change the second layer to left 1.5 top 1.5

**Comment by asturur** [comment]
to get current top and left value you can:
```
//  create a point from it
var point = { x: left, y: top }
// get the object group transform matrix:
var matrix = object.group.calcTransformMatrix();
// multiply the point for the matri
var actual position = fabric.util.transformPoint(point,matrix);
```
