### ISSUE TITLE
Wrong charWidth with disabled antialiasing on windows 10

### ISSUE THREAD

**Issue by Rad1calDreamer** [fabricjs/fabric.js#6380]
## Version
3.6.0

## Test Case
http://jsfiddle.net/xm80gbco/

## Information about environment
Chrome win10

## Steps to reproduce
disable antialiasing in OS settings
enter in  editing text
hold "a"

## Expected Behavior
text cursour at the end of text

## Actual Behavior
text cursour missplaced
![2020-06-09 15-28-41](https://user-images.githubusercontent.com/7055577/84152076-dc73fc00-aa6c-11ea-8ddf-35b8747fa730.gif)
![2020-06-09 15-30-14](https://user-images.githubusercontent.com/7055577/84152084-ded65600-aa6c-11ea-8780-05fa11ed9d27.gif)

**Comment by asturur** [comment]
I think we can't do much for it.
We can't detect the setting, is probably not chrome or window specific too.
Or could be a chrome bug.

Did you know if on the same machine, different browser work as expect?
