### ISSUE TITLE
Object caching cuts of part of subclass instance

### ISSUE THREAD

**Issue by adriaanmeuris** [fabricjs/fabric.js#6383]
## Version
3.6.3

## Test Case
https://jsfiddle.net/adriaanmeuris/kcp0xu7t/33/

## Information about environment
all browsers

## Steps to reproduce
See jsfiddle, this is the setup:
- subclass that renders a circle that exceeds it's bounding box
- part of the circle gets cut off
- when object caching is disabled, this doesn't happen
- disabling object caching is not a solution, as I need to clip the instance in the future which requires object caching.

## Expected Behavior
the circle is shown in full and exceeds it's bounding box:
<img width="168" alt="Screenshot 2020-06-11 at 12 11 15" src="https://user-images.githubusercontent.com/16230038/84373390-ca18d000-abdc-11ea-93bc-5d22fc3cb6e7.png">

## Actual Behavior
the circle is cut off. Behaviour changes when the size of the circle is changed:
![ezgif com-resize](https://user-images.githubusercontent.com/16230038/84373503-f59bba80-abdc-11ea-950c-c91d30cfbfb2.gif)

## Question
how can i prevent the circle being cut off without disabling object caching?

**Comment by asturur** [comment]
hi @adriaanmeuris in order for caching to work correctly, fabric has to be able to calculcate how big the obejct is.
A simple solution would be you to understand how your object dimensions change with the properties and code it:
https://jsfiddle.net/asturur/3wx5npjy/

in this case i made a simple example based on your.
Maybe is a best practice that width and height, calculated from other properties or imposed by direct object props, do match the final size of the object ( unscaled )
