### ISSUE TITLE
render single object

### ISSUE THREAD

**Issue by Mamikon95** [fabricjs/fabric.js#6384]
Hello, please tell me if it is possible to render only one object?
There is a canvas where there are objects under 30,000. And there is an object that moves behind the cursor (mouse: move). and requestRenderAll is constantly happening in this event, so all objects are rendered, which leads to lags. And I need to render only the object that moves behind the cursor.

fabric version - 3.6.3

**Comment by asturur** [comment]
Hi mamikon95, as today this is not possible.
You could try to workaround it but that would require lot of code in lot of small parts of fabricJS.
The idea is that we can write a partial re render for single objects but that requires anyway looping through 30k of objects to understand which one is affected and which no.

Another idea would be to use the upper canvas for transformations, bringing the object visually on top for the time fo drag.

Another techinic would be the sandwich way, in which you split the canvas in 3 parts: below object, object, above object.

There is nothing ready now and won't be soon.
Can i ask you what are you doing with 30k of objects? i m very interested to find out

**Comment by Mamikon95** [comment]
> Hi mamikon95, as today this is not possible.
> You could try to workaround it but that would require lot of code in lot of small parts of fabricJS.
> The idea is that we can write a partial re render for single objects but that requires anyway looping through 30k of objects to understand which one is affected and which no.
> 
> Another idea would be to use the upper canvas for transformations, bringing the object visually on top for the time fo drag.
> 
> Another techinic would be the sandwich way, in which you split the canvas in 3 parts: below object, object, above object.
> 
> There is nothing ready now and won't be soon.
> Can i ask you what are you doing with 30k of objects? i m very interested to find out

I am using fabric js along with openseadragon. There are marked .svs .scn images with a size of, for example, 50000x50000px. Therefore, a lot of objects. Is there any solution in practice for such cases? to speed up

**Comment by asturur** [comment]
Are those objects on screen all at the same time? can you show what are you doing somewhere?

**Comment by Mamikon95** [comment]
> Are those objects on screen all at the same time? can you show what are you doing somewhere?

Yes, everything on the screen, unfortunately I can’t show (
