### ISSUE TITLE
Automatically apply styles properties in textbox when we directly edit text from canvas (4.0.0-beta.12)

### ISSUE THREAD

**Issue by shaktippatel** [fabricjs/fabric.js#6385]
Automatically apply styles properties in textbox when we directly edit text from canvas (Version 4.0.0-beta)

**Step for produce**

1. Select all text
2. Remove text
3. Enter any text
4. check console log for style

Version 3.6.3 textbox properties: [JSFiddle](https://jsfiddle.net/shaktipatel/wvo8c49g/)

> {
>   "type": "Textbox",
>   "version": "3.5.0",
>   "styles": {}
> }

Version 4.0.0-beta.12 textbox properties: [JSFiddle](https://jsfiddle.net/shaktipatel/53zhew8n/)

> {
>   "type": "Textbox",
>   "version": "4.0.0-beta.12",
>   "styles": {
>     "0": {
>       "0": {
>         "stroke": "transparent",
>         "strokeWidth": 0,
>         "fill": "#040404",
>         "fontFamily": "Arial",
>         "fontSize": 12,
>         "fontWeight": "normal",
>         "fontStyle": "normal",
>         "underline": false,
>         "overline": false,
>         "linethrough": false,
>         "deltaY": 0,
>         "textBackgroundColor": ""
>       },
>       "1": {
>         "stroke": "transparent",
>         "strokeWidth": 0,
>         "fill": "#040404",
>         "fontFamily": "Arial",
>         "fontSize": 12,
>         "fontWeight": "normal",
>         "fontStyle": "normal",
>         "underline": false,
>         "overline": false,
>         "linethrough": false,
>         "deltaY": 0,
>         "textBackgroundColor": ""
>       },
>       "2": {
>         "stroke": "transparent",
>         "strokeWidth": 0,
>         "fill": "#040404",
>         "fontFamily": "Arial",
>         "fontSize": 12,
>         "fontWeight": "normal",
>         "fontStyle": "normal",
>         "underline": false,
>         "overline": false,
>         "linethrough": false,
>         "deltaY": 0,
>         "textBackgroundColor": ""
>       }
>     }
>   }
> }

**Comment by asturur** [comment]
@shaktippatel  i see the difference in the output if i:

select all, do some typing.

I think this is the result of some recent fixes for styles of new lines.
What is the problem in your opinion here, apart having a different output in the style object?
Can you elaborate?

**Comment by wangyong991** [comment]
when styles properties exits, can't set the property (eg: fill, fontFamily) to work;
