### ISSUE TITLE
object.scale() func not trigger  object's scaling  event 

### ISSUE THREAD

**Issue by zhousheng1114** [fabricjs/fabric.js#6386]
## Version
3.6.0 or 4.0.0 beta

## Test Case
https://jsfiddle.net/zhousheng1216/txf6uh1d/1/

## Information about environment
browser
Chrome 83.0.4103.97

## Steps to reproduce
1. mouse wheel on canvas
2. checkout console output
## Expected Behavior
after scale function executed, object's scaling event should be triggered
## Actual Behavior
object scale function not trigger it's scaling evnet

**Comment by jhondge** [comment]
I think it's not a issue, fabric will not trigger scaling event on object's scale method, it's just called the `_set ` method to apply the new value, the object scaling event will be trigger by mouse move event. so if u want to receive the scaling change just override the `_set` method or manual trigger the event by yourself, e.g. `fabric.util.trigger(...) / object.fire(...)`

**Comment by zhousheng1114** [comment]
thanks.I choosed object.trigger(eventname) as an alternative
