### ISSUE TITLE
Text render error when object was scaled in node-canvas server side

### ISSUE THREAD

**Issue by jhondge** [fabricjs/fabric.js#6387]
## Version
3.6.0

## Description
When you scaled down/up your text object and use any fontFamily, it mean your object's scaleX/scaleY not 1, then load it in node-canvas and render it. so you will got the error kerned width like following screen shot:
scaleX = 1
![test-test1](https://user-images.githubusercontent.com/4192552/84459788-dc594380-ac9a-11ea-8233-dc17541321bc.png)
scaleX = 0.9
![test-test-0 9](https://user-images.githubusercontent.com/4192552/84459785-db281680-ac9a-11ea-9078-0c4347fe504e.png)
scaleX = 0.5
![test-text0 5](https://user-images.githubusercontent.com/4192552/84459776-d8c5bc80-ac9a-11ea-9a58-31f11a3b9ae8.png)

PS: I was debug that text source code, I figure out if set the `charSpacing` as non-zero value, it's work fine for example `charSpacing=0.0001`. when charSpacing non-zero it's will trigger `_renderChar` to render word by word,  the segment code as the following:
```
_renderChars: function(method, ctx, line, left, top, lineIndex) {
      // set proper line offset
      var lineHeight = this.getHeightOfLine(lineIndex),
          isJustify = this.textAlign.indexOf('justify') !== -1,
          actualStyle,
          nextStyle,
          charsToRender = '',
          charBox,
          boxWidth = 0,
          timeToRender,
          shortCut = !isJustify && this.charSpacing === 0 && this.isEmptyStyles(lineIndex);

      ctx.save();
      top -= lineHeight * this._fontSizeFraction / this.lineHeight;
      if (shortCut) {
        // render all the line in one pass without checking
        this._renderChar(method, ctx, lineIndex, 0, this.textLines[lineIndex], left, top, lineHeight);
        ctx.restore();
        return;
      }
      for (var i = 0, len = line.length - 1; i <= len; i++) {
       //////////////////////   HERE IS THE KEY  ISSUE /////////// ///////////  
        timeToRender = i === len || this.charSpacing;
        charsToRender += line[i];
        charBox = this.__charBounds[lineIndex][i];
        if (boxWidth === 0) {
          left += charBox.kernedWidth - charBox.width;
          boxWidth += charBox.width;
        }
        else {
          boxWidth += charBox.kernedWidth;
        }
        if (isJustify && !timeToRender) {
          if (this._reSpaceAndTab.test(line[i])) {
            timeToRender = true;
          }
        }
        if (!timeToRender) {
          // if we have charSpacing, we render char by char
          actualStyle = actualStyle || this.getCompleteStyleDeclaration(lineIndex, i);
          nextStyle = this.getCompleteStyleDeclaration(lineIndex, i + 1);
          timeToRender = this._hasStyleChanged(actualStyle, nextStyle);
        }
        if (timeToRender) {
          this._renderChar(method, ctx, lineIndex, i, charsToRender, left, top, lineHeight);
          charsToRender = '';
          actualStyle = nextStyle;
          left += boxWidth;
          boxWidth = 0;
        }
      }
      ctx.restore();
    }
```
### Why?
It's work in browser but node-canvas.

**Comment by asturur** [comment]
node-canvas is not a perfect canvas replacement and has issues.
Let me add a test to verify if this problem happens also on our CI testing

**Comment by asturur** [comment]
running this code in nodejs
```
    var text = new fabric.Text('Scaling down', {
      left: 10,
      top: 10,
      fill: 'red',
      fontSize: 300,
      scaleX: 0.2,
      scaleY: 0.2,
      fontFamily: 'Ubuntu'
    });
    canvas.add(text);
    canvas.renderAll();
```

give this result

![image](https://user-images.githubusercontent.com/1194048/85152993-f0321600-b255-11ea-9d71-3cc9cbdff4ec.png)


seems fine to me.
Am i getting something wrong?

**Comment by zxcvc** [comment]
@asturur
Set scaleX and scaleY to different values, such as scaleX=5 and scaleY=2.
