### ISSUE TITLE
Zoom broken in http://fabricjs.com/fabric-intro-part-5

### ISSUE THREAD

**Issue by maltewirz** [fabricjs/fabric.js#6388]
## Version
3.6.0

## Test Case
http://jsfiddle.net/ljerkhgbe2387r/u53fcaze/5/

## Information about environment
Chrome 83

## Steps to reproduce
When following the first example in http://fabricjs.com/fabric-intro-part-5, the scrolling works not correctly. When changing the line from `zoom *= 0.999 ** zoom;`to `zoom *= 0.999 ** delta;`  it works again. Please correct and thanks for your project.

## Expected Behavior
Using mousewheel to zoom.
## Actual Behavior
Mousewheel does not work correctly.

**Comment by asturur** [comment]
a recent pr broke it, i just merged a fix. Thanks
