### ISSUE TITLE
Wrong position after .set()

### ISSUE THREAD

**Issue by moayuisuda** [fabricjs/fabric.js#6393]
## Version
3.6.3

## Test Case
[codepen](https://codepen.io/moayuisuda/pen/rNxWoxo?__cf_chl_jschl_tk__=b1fb443de098b9a10e2c1bbafc918fd1efdc4388-1592461433-0-AW5y5jJxp9okuUIlnYdFlgXbFTZ_Sr52E4b7vvHETANFyLueARiASVBkUZI2CwJu7lCaCqi4EN08LpAsfAjGsIfggzBU5YnQy2rFqB6xV9CKGwVK42S_YHyLZFkoZ4erNUecA2xugFdmg64BELN2V6JusPl1zbLaQjvmJUS8NnNJlVhe58ZtNhMHBFPzN4j7vTmaMEPH8NNYDjiZn604UTLQat7qJB_jTNfAJqjjyGb020WA1JB-l_Tv8j1NtJwf1_KF5ybF3d6xZ5D1G0-1H2F0tp0pIp7WBmZCfaIZFf8I3TAnqjxnHkCqJBqYAv6mAbfaFEXv1TwvZ1TJx4LRZG0)

## Information about environment
latest chrome

## Expected Behavior
The text is in the upper left corner

## Actual Behavior
The text is in a wired position

**Comment by melchiar** [comment]
It appears to be working fine for me. Can you provide more info, such as where you expect the text to be and perhaps a screenshot of the result you're seeing?

**Comment by moayuisuda** [comment]
Exception:
<img width="238" alt="截屏2020-06-19 上午9 43 32" src="https://user-images.githubusercontent.com/37040897/85088203-1e8e0200-b212-11ea-8a94-b76fa59a4433.png">
Current:
<img width="300" alt="截屏2020-06-19 上午9 51 19" src="https://user-images.githubusercontent.com/37040897/85088324-7167b980-b212-11ea-8001-a2f1bd3a15a2.png">

**Comment by moayuisuda** [comment]
> It appears to be working fine for me. Can you provide more info, such as where you expect the text to be and perhaps a screenshot of the result you're seeing?

Exception:
<img width="238" alt="截屏2020-06-19 上午9 43 32" src="https://user-images.githubusercontent.com/37040897/85088504-dfac7c00-b212-11ea-9039-c888c2ec1133.png">

Current:
<img width="300" alt="截屏2020-06-19 上午9 51 19" src="https://user-images.githubusercontent.com/37040897/85088512-e3d89980-b212-11ea-9265-1a61654ae603.png">

**Comment by melchiar** [comment]
K, I think I understand the issue. When an object is grouped, its positional coordinates are no longer relative to the canvas but to the group, which is why your text isn't going where you want it to. Have you tried ungrouping, moving the text, then regrouping?

**Comment by moayuisuda** [comment]
> K, I think I understand the issue. When an object is grouped, its positional coordinates are no longer relative to the canvas but to the group, which is why your text isn't going where you want it to. Have you tried ungrouping, moving the text, then regrouping?

Tanks for your reply, but I'm still confused how do fabric caculate the coordinate of a text in a group, I have set all the coordinates to `0`, but why text still appears so far away from the origin point?

**Comment by moayuisuda** [comment]
> > K, I think I understand the issue. When an object is grouped, its positional coordinates are no longer relative to the canvas but to the group, which is why your text isn't going where you want it to. Have you tried ungrouping, moving the text, then regrouping?
> 
> Tanks for your reply, but I'm still confused how do fabric caculate the coordinate of a text in a group, I have set all the coordinates to `0`, but why text still appears so far away from the origin point?

**Comment by asturur** [comment]
in this case the text is inserted in a group, alone.
The text is wide X and high Y, its position will be (-X/2, -Y/2).
The created group is at 50,50.

When grouped with the circle, you create a large group that extends from the circle to the group that contains the text.
Setting the text position to 0,0 will just move it to the center of its container group, even more far away from the circle.

The final group has the 0,0 in the middle between the circle and the text.

Is very hard to move objects inside groups and nested group, there is for sure a simpler way to do what you want to do.

If you are still looking for help, trying to explain cleary what you want to do.

**Comment by moayuisuda** [comment]
> in this case the text is inserted in a group, alone.
> The text is wide X and high Y, its position will be (-X/2, -Y/2).
> The created group is at 50,50.
> 
> When grouped with the circle, you create a large group that extends from the circle to the group that contains the text.
> Setting the text position to 0,0 will just move it to the center of its container group, even more far away from the circle.
> 
> The final group has the 0,0 in the middle between the circle and the text.
> 
> Is very hard to move objects inside groups and nested group, there is for sure a simpler way to do what you want to do.
> 
> If you are still looking for help, trying to explain cleary what you want to do.

I am trying to use fabric.js to restore the json file exported by the design software, but the position information inside is relative to the upper left corner of its parent, which is inconsistent with the fabric.js group, I just want to figure out the behavior of the group, and then do some transformation to restore the position.
And I have tried your idea and draw a draft
![DC87285599A9E57F85DA89E3F25F0625](https://user-images.githubusercontent.com/37040897/85218010-d06f2f00-b3c8-11ea-9e3b-f5a7a38d5a7a.png)
, but the actual position is still far away from the [codepen](https://codepen.io/moayuisuda/pen/rNxWoxo), Is there something wrong with the draft I drew?

**Comment by asturur** [comment]
I'm not sure what design data you have, if you want to share that maybe i can understand better.

**Comment by moayuisuda** [comment]
> I'm not sure what design data you have, if you want to share that maybe i can understand better.

It's just like
```js
{
  "type": "group",
  "x": 10,
  "y": 10,
  "children": [
    {
     "type": "rect",
     "x": 0,
     "y": 0,
     "width": 50,
     "height": 50
    },
    {
      "type": "circle",
      "x": 50,
      "y": 50,
      "radius": 25
    }
  ]
}
```
The coordinates of all children are relative to the upper left corner of the parent.

**Comment by moayuisuda** [comment]
Just make the problem simpler, I just want to understand why empty call of `addWithUpdate` can change the position of text in this [codepen](https://codepen.io/moayuisuda/pen/YzwZpzp).

**Comment by asturur** [comment]
> > I'm not sure what design data you have, if you want to share that maybe i can understand better.
> 
> It's just like
> 
> ```js
> {
>   "type": "group",
>   "x": 10,
>   "y": 10,
>   "children": [
>     {
>      "type": "rect",
>      "x": 0,
>      "y": 0,
>      "width": 50,
>      "height": 50
>     },
>     {
>       "type": "circle",
>       "x": 50,
>       "y": 50,
>       "radius": 25
>     }
>   ]
> }
> ```
> 
> The coordinates of all children are relative to the upper left corner of the parent.

But do you know how large the group is?

The answer to your other question is that addWithUpdate will recalculate the group from scratch with the new objects you add. If you do not add any object, it will just ungroup/regroup, basically refitting the group to current object properties.

The best way to handle your problem is probably:
Starting from the innermost children, create all the objects, position them on the canvas with their group coords and group them. then move this new created group to its own x,y and proceed to group it with other siblings.

**Comment by asturur** [comment]
in the case of your data posted, create the rect and the circle, position the circle at 50,50 and group them together. Then move the resulting group to 10,10

**Comment by moayuisuda** [comment]
> > > I'm not sure what design data you have, if you want to share that maybe i can understand better.
> > 
> > 
> > It's just like
> > ```js
> > {
> >   "type": "group",
> >   "x": 10,
> >   "y": 10,
> >   "children": [
> >     {
> >      "type": "rect",
> >      "x": 0,
> >      "y": 0,
> >      "width": 50,
> >      "height": 50
> >     },
> >     {
> >       "type": "circle",
> >       "x": 50,
> >       "y": 50,
> >       "radius": 25
> >     }
> >   ]
> > }
> > ```
> > 
> > 
> > The coordinates of all children are relative to the upper left corner of the parent.
> 
> But do you know how large the group is?
> 
> The answer to your other question is that addWithUpdate will recalculate the group from scratch with the new objects you add. If you do not add any object, it will just ungroup/regroup, basically refitting the group to current object properties.
> 
> The best way to handle your problem is probably:
> Starting from the innermost children, create all the objects, position them on the canvas with their group coords and group them. then move this new created group to its own x,y and proceed to group it with other siblings.

group's size is basd on it's children, the real data is much more complicated than the example json(including style,mask,blending etc.), but it's not important. Now, I just want to figure out the behavior of group.
And sorry, I still can't understand why the position of the text changed in [codepen](https://codepen.io/moayuisuda/pen/YzwZpzp), maybe you can expain it more specificlly?

**Comment by moayuisuda** [comment]
Is it so difficult to dynamically add an element where I want it?

**Comment by asturur** [comment]
When the group is already done, yes is complicated if the item change the group size.

So the only way to reconstruct the group is starting from the children elements.
Start from the innermost children, group them, then position the resulting group where you want.
If you need to add an object later, ungroup the group, add the item, then regroup.

**Comment by moayuisuda** [comment]
Thanks for your answers, I'd better find another way to handle nested elements.

**Comment by asturur** [comment]
is the solution i described not working or not applicable because some other needs?
