### ISSUE TITLE
using fabricjs json object to drawing on cairo (c++) project

### ISSUE THREAD

**Issue by hoaily** [fabricjs/fabric.js#6394]
Dear all,
i am looking for a solution to loading the resource from json file created by fabricjs website.
Currently, my c++ program can load and draw almost object. but, when the object has been scale(scaleX or scaleY != 1), or object has been rotate. my program will be draw incorrect position.

below example for drawing Line.

	ctx.save();

/*
	ctx.translate(this->originPoint.x + this->width / 2, this->originPoint.y + this->height / 2);
	ctx.rotate(this->angle *(M_PI / 180));
	ctx.scale(this->scaleX, this->scaleY);
*/
	ctx.drawLine(this->x1, this->y1, this->x2, this->y2, this->lineWidth, this->lineCap, this->dash, this->numDash);

	ctx.restore();

**Comment by asturur** [comment]
hi @hoaily you have to check each fabricJS render method to verify extra transformations that are made.

Have a look at getCenterPoint logic, that is where you have to translate the object.
Cairo has has a transform or setTransform alternative, where you can pass the object transformMatrix ( you can see how is calculated in calcTransformMatrix ).

Javascript canvas is based on cairo ( at least for firefox ) so you should be able to replicate easily the canvas interface on top of cairo, and then call fabricJS code in a similar way.

You can also look at node-canvas sources that is based on canvas and where most of the context interface is already created.

https://github.com/Automattic/node-canvas/commits/master
