### ISSUE TITLE
Ability to toggle the vertical stretching of text when using the bottom middle and top middle object controls

### ISSUE THREAD

**Issue by kylekirkby** [fabricjs/fabric.js#6395]
**Is your feature request related to a problem? Please describe.**
It would be great if we can disable the vertical stretching of text inside a textbox when using the bottom middle and top middle controls. I haven't been able to find a solution to this.

**Describe the solution you'd like**
A textbox setting that allows users to disable the textbox stretching vertically. 

**Describe alternatives you've considered**
I've looked at customizing the textbox via prototypes but cannot find where I can toggle the stretching of text.

@asturur is this doable?

Best, 

Kyle

**Comment by melchiar** [comment]
Have you tried just disabling those controls using `setControlsVisibility()`? Or is there something else you'd prefer those controls do other than scaling?

**Comment by kylekirkby** [comment]
@melchiar I've removed the control points for now but I'd love to be able to resize the textbox without scaling the text inside it. This is so I can allow users to set a max height for their textboxes using the controls instead of a maxHeight input field.

**Comment by asturur** [comment]
@kylekirkby the custom control api should sole this problem.
look how the custom action handle for textbox width is done:

```js
  function changeWidth(eventData, transform, x, y) {
    var target = transform.target, localPoint = getLocalPoint(transform, transform.originX, transform.originY, x, y),
        strokePadding = target.strokeWidth / (target.strokeUniform ? target.scaleX : 1),
        newWidth = Math.abs(localPoint.x / target.scaleX) - strokePadding;
    target.set('width', Math.max(newWidth, 0));
    return true;
  }
```

You can easily create a changeHeight from this.

You have then to consider that textbox height depends from width + the text.
So unless you customized those functions somehow, setting the height is not useful since it will get back to the correct height every time you change text.

**Comment by kylekirkby** [comment]
> @kylekirkby the custom control api should sole this problem.
> look how the custom action handle for textbox width is done:
> 
> ```js
>   function changeWidth(eventData, transform, x, y) {
>     var target = transform.target, localPoint = getLocalPoint(transform, transform.originX, transform.originY, x, y),
>         strokePadding = target.strokeWidth / (target.strokeUniform ? target.scaleX : 1),
>         newWidth = Math.abs(localPoint.x / target.scaleX) - strokePadding;
>     target.set('width', Math.max(newWidth, 0));
>     return true;
>   }
> ```
> 
> You can easily create a changeHeight from this.
> 
> You have then to consider that textbox height depends from width + the text.
> So unless you customized those functions somehow, setting the height is not useful since it will get back to the correct height every time you change text.

Thank you @asturur - I’ll give this a go!!!

**Comment by kylekirkby** [comment]
@asturur I'm still getting the text stretched with the following changes:

```javascript
fabric.CustomTextBox.changeHeight = function (eventData, transform, x, y) {
  var target = transform.target,
    localPoint = this.getLocalPoint(
      transform,
      transform.originX,
      transform.originY,
      x,
      y
    ),
    strokePadding =
      target.strokeHeight / (target.strokeUniform ? target.scaleY : 1),
    newHeight = Math.abs(localPoint.y / target.scaleY) - strokePadding;
  target.set("height", Math.max(newHeight, 0));
  return true;
};

```
Could you point me to where the changeWidth function is in the fabric js source code?

**Comment by asturur** [comment]
is in version 4 beta, and is on the controls:

first wrapped here

Hooked up here: https://github.com/fabricjs/fabric.js/blob/master/src/mixins/default_controls.js#L101


```
fabric.CustomTextBox.prototype.controls.mb.actionHandler = changeHeight;
fabric.CustomTextBox.prototype.controls.mt.actionHandler = changeHeight;
```

I m writing an introduction to custom controls right now, also please look at the 2 available examples on fabricjs.com/demos/

**Comment by kylekirkby** [comment]
@asturur thank you for this I'll take a look now!

**Comment by kylekirkby** [comment]
Hi @asturur,

So the control works - sort of! Basically, the height/maxHeight of the TextBox changes however the object is not re-rendered to show this change. Upon clicking the TextBox to vertically again the height resets to what it is to begin with (because it hasn't re-rendered). I'm calling `canvas.renderAll()` and the TextBox doesn't change height. Any ideas?

**Comment by asturur** [comment]
Well, depending what the customObject is doing, remember that text is built to reset the height with the text content each time it feels like is necessary.

What is your custom object doing? can you paste the custom class somewhere?

**Comment by kylekirkby** [comment]
After months of trying to get this to work I have finally got it working!!! Thank you so much for getting the custom control features added! My custom TextBox class was setting the height to the height of the text using calcTextHeight

**Comment by kylekirkby** [comment]
It's more or less perfect! @asturur any idea as to how I could get the textbox to scale from the drop when clicking and draggin the `mt` control? I was thinking something like your reply to this SO post:
https://stackoverflow.com/questions/47590126/fabric-js-is-there-a-way-to-identify-the-direction-of-scaling

![textbox](https://user-images.githubusercontent.com/4564433/85211058-62315a80-b33d-11ea-9e67-557430bad42e.gif)

**Comment by asturur** [comment]
The `WrapWithAnchor` function should be solving that. I mentioned it in my answers, are you using it?

**Comment by asturur** [comment]
Ah my bad, i wrote `first wrapped here` but i did not past the link after it.
https://github.com/fabricjs/fabric.js/blob/master/src/controls.actions.js#L496

Look here, there is a utility function called `wrapWithFixedAnchor` that is made to solve this problem in a sort of general way.
Wrap your changeHeight with that, and should work.

I see is not exposed in the fabric object, for now just copy paste it, i will expose it somewhere.

**Comment by kylekirkby** [comment]
Arhh sweet thanks @asturur let me try it out! I did see that function on my searches through the almight source code and thought it looked like it was used to solve that (worked my way back from the changeWidth function since that works nicely!)

**Comment by kylekirkby** [comment]
Also getLocalPoint isn't exposed so I had to copy that utility over aswell!

**Comment by melchiar** [comment]
nice ui @kylekirkby 👍

**Comment by kylekirkby** [comment]
Thank you @melchiar - I've been working on this SaaS products for months trying to get it just right! This TextBox functionality is just what I've been looking for.

![ui-](https://user-images.githubusercontent.com/4564433/85211522-0fa66d00-b342-11ea-8ef1-86608d807f89.gif)

**Comment by asturur** [comment]
Can you open a new issue, that asks to make usable the utility functions used to create the default action handlers?

**Comment by CookedApps** [comment]
@kylekirkby Would you mind sharing the source code for your custom TextBox? I have the exact same use case and would really appreciate it!

**Comment by kylekirkby** [comment]
@CookedApps sorry but I can’t share this code!

**Comment by proYang** [comment]
> @CookedApps sorry but I can’t share this code!

Would you share some ideas for solving this problem? Please 🥺

**Comment by proYang** [comment]
> @CookedApps sorry but I can’t share this code!

Would you share some ideas for solving this problem? Please 🥺

**Comment by tneullas** [comment]
Sorry if I resurect this thread.
If it can help some people around here, what I understood is : 
- you have to redefined all `scalingEqually` controls (like `mb`) of your textBox (check fabric\dist\src\controls\commonControls.mjs)
- you have to get a correct implementation of the events with some functions (but right now they does not seems to be exposed like `wrapWithFireEvent`, `wrapWithFixedAnchor`, `getLocalPoint`)
- you have to implement your custom changeObjectHeight (check fabric\dist\src\controls\changeWidth.mjs) keeping in mind your height might be setted by default after modification. Use a fake line with fake huge font for bigger height ?

Is it something new that i missed ?
Now that fabric is v6, is there any plan in future implementations to have this feature as a boolean or to exposed thoses functions to help people implement such a feature ?
To be fair I think this feature is quite useless but some clients really wants it :)

**Comment by lavnishhh** [comment]
@tneullas any luck implementing this? I was able to do it but i come across a lot of flicker when it happens. 

```
const changeWidth = controlsUtils.wrapWithFireEvent('resizing', (eventData: TPointerEvent, transform: Transform, x: number, y: number) => {
    var target = transform.target, localPoint = controlsUtils.getLocalPoint(transform, transform.originX, transform.originY, x, y),
        strokePadding = target.strokeWidth / (target.strokeUniform ? target.scaleX : 1)
    let newWidth = Math.abs(localPoint.x / target.scaleX) * 2 - strokePadding;

    console.log(localPoint.x, target.left, target.top, x, y)

    if (transform.corner === 'ml') {
        const deltaX = target.width - newWidth;
        target.set('left', target.left + deltaX * target.scaleX);
    }
        
    target.set('width', Math.max(newWidth, 0));
    return true;
});
```

Using ```wrapWithFixedAnchor``` fixes the flicker but then the box scaling becomes symmetric :/

**Comment by asturur** [comment]
Guys if everyone wants it we can make it an control set in extensions. I think it should be a subclass too because there is some measurement to override here and there.

It make sense with a circle and a rect, i don't see how it make sense with text

**Comment by lavnishhh** [comment]
@asturur that would be really nice. I still havent been able to figure out how to make this work! The box height resets when I move the width,  the textbox flickers when i move the controls. Using wrapWithFixedAnchor makes the box expansion symmetric :/
