### ISSUE TITLE
Custom controls, polygon with stroke

### ISSUE THREAD

**Issue by ceverard9** [fabricjs/fabric.js#6400]
Version
4.0.0-beta.12

Example
![example](https://user-images.githubusercontent.com/28542042/85159783-c9062500-b212-11ea-87f8-37fa25e1ebaf.gif)

Description
Using the exact code from the custom controls demo on the website. Discovered that when the polygon has a stroke applied the controls or anchor wrapper do not take into account the offset of the stroke. Thus when you start dragging the polygon jumps away from you.

I know the custom controls demo is more of an example of what you can do vs an actual feature but any ideas on how to take into account the stroke offset?

**Comment by asturur** [comment]
Hi updated the demo to work with stroke and zoom! please check the updated code.

**Comment by ceverard9** [comment]
Wow such a simple solution. Works like a charm. Appreciate your help!
