### ISSUE TITLE
Make the utility functions usable to create default action handlers

### ISSUE THREAD

**Issue by kylekirkby** [fabricjs/fabric.js#6404]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Utility functions accessible from within a custom control handler
https://github.com/fabricjs/fabric.js/blob/f30de19229c310414de03c68a144d1da884c31a1/src/controls.actions.js#L120-L222

**Describe alternatives you've considered**
Copying the utility functions into my app source code to make use of them.

**Additional context**
https://github.com/fabricjs/fabric.js/issues/6395

**Comment by kylekirkby** [comment]
@asturur can we add a custom control for mouseover? I'm thinking it might be good to add custom controls when an object is selected/hovered. Use case - hover over a text box and modify the font size/styles.

**Comment by asturur** [comment]
there is the hover event for that.
Being no default action for hovering, the event is just fine. Isn'it?

**Comment by kylekirkby** [comment]
> there is the hover event for that.
> Being no default action for hovering, the event is just fine. Isn'it?

True! Sorry for the noise.
