### ISSUE TITLE
Is there any breaking changes in upgrading to 4.0 from 2.3.5

### ISSUE THREAD

**Issue by iamappmaker** [fabricjs/fabric.js#6406]
We using fabricjs from version 1.0. when we updated to 2.x we can't able to use old json files generated using v1.0 . So we not upgraded to 3.x also.

- Is there any breaking changes?
- will my json file generated using v2.x works in v4?
- is there any performance improvement in v4?

We are facing many performance issue. On continuous usage application become slow and by using shadows, blur , filters, etc makes application slow and sometimes browser crashes.

So i am planning to upgrade to latest version with the hope to increase the performance.

**Comment by melchiar** [comment]
There are quite a few breaking changes between v1.x and v4. Please see the following upgrade guide for an overview. 

http://fabricjs.com/upgrade-guide

**Comment by asturur** [comment]
Well it depends what are you doing with the app. on what 1.x are you?

The things that  got most of the performance update after 1.6 are:
1.7 => caching
1.7.x => skip rendering of objects that are offscreen
2.0 => webgl filters, text rewrite

those are the big one, there may have been minor non intentional performance improvements.

**Comment by iamappmaker** [comment]
Now i am using 2.4.2 
My canvas size is 1000*1000 and has some performance issue.
If possible consider improving performance.
Thanks for this awesome library

**Comment by asturur** [comment]
1000 by 1000 shouldn't be a problem, must be the quantity of objects or something else slowing you down.
Can you screenshot a canvas that is giving you performance problems, and of how much fps are we talking about?

**Comment by iamappmaker** [comment]
Canvas Size: 640*640
I use  fabricjs-customise-controls-extension.
System: i7 10th gen with 16gb ram

First i added text and dragging is very smooth.
Then i add image with resolution 2400*1600 
Now dragging is not smooth and becomes slow, even text dragging is slow
If i delete the image and text dragging is smooth.

Note: Image less than 1600*1600 resolution has somewhat acceptable performance and image less than 800*800 is good.

![localhost_4200_(Galaxy S5) (2)](https://user-images.githubusercontent.com/43312229/85843452-d09f6e00-b7be-11ea-8e0f-50e2a88eae90.png)

**Comment by asturur** [comment]
i would not expect one image and one text to be a problem ever. Are you using the integrated intel video card, may be a problem with textures bigger than 2048 pixels? Can you try if an image of 2048x2048 is smooth?

**Comment by iamappmaker** [comment]
I use Nvidia graphics card 2 gb 
I changed the image size to 2000*1280 still it does not drag smoothly. Only size less than 1000*1000 drags smoothly

These are the lines in my project related to performance

this.canvas = new fabric.Canvas('canvas', {
      hoverCursor: 'pointer',
      selection: true,
      selectionBorderColor: '#424242',
      renderOnAddRemove: false
    });

fabric.Object.prototype.objectCaching = false;
 fabric.Object.prototype.statefullCache = false;
 fabric.Object.prototype.noScaleCache = true;
fabric.Object.prototype.needsItsOwnCache = false;

object.hasRotatingPoint = false


Do i need to change anything?
This is graphic designer application,  user complains only about performance.

**Comment by asturur** [comment]
Is very strange! is this app live somewhere?

**Comment by iamappmaker** [comment]
@asturur Fixed the problem. I am using drag and drop for sorting the layers which caused the problem, while i am dragging the object in canvas drag&drop also listening to event in background and frame rate started to drop.

Now performance is awesome.

**Comment by iamappmaker** [comment]
@asturur After testing in various devices, While dragging there is no frame drop upto certain canvas size (varies by device).
In Android 9 ( 4GB Ram) :  Frame rate is between 50 to 58 when canvas size is 1400*1400, beyond this if i increase the resolution by 50px  frame rate drops to 10fps.
In Iphone 11 frame rate started to drop when canvas size higher than 1600. 
In older phones. with canvas size 1000*1000 i see 7 to 10 fps but with acceptable response.
All these are because the lower canvas size is 3x of original. 
When i set enableRetinaScaling:false performance increases.

//init
 this.canvas = new fabric.Canvas('canvas', {
      enableRetinaScaling:false
    });

// While Downloading

this.canvas.set({enableRetinaScaling:true});
this.canvas.toDataURL({format:'png', multiplier: 3});
this.canvas.set({enableRetinaScaling:false});

Will this be useful.


Generally users expect output in HD. How to manage both quality and performance.
I am creating a graphic designer like shutterstock. When i tried shutterstock, it was very smooth in old device also. 
Please give me a suggestion to configure.

**Comment by asturur** [comment]
The idea is more or less what you do.
Work on a small canvas, output a big one.

Ideally i would start a new canvas for download, still with retina scaling off, as big as needed with the multiplier. This to avoid resizing and invalidating the cache of your canvas.

We should work on a specific export logic that works around the limitation of caching. I do not have one that works with clippaths too.

**Comment by iamappmaker** [comment]
@asturur  What is the  purpose of enableRetinaScaling:true
Output is same with enableRetinaScaling:true and false.

As mentioned in previous reply, i tried the following code

var srcCtx = this.canvas.getContext("2d");
 var imageData = srcCtx.getImageData(0, 0,  this.canvas.width,  this.canvas.height);

 let temp =  document.getElementById('tempCanvas');
temp.width = imageData.width*5;
 temp.height = imageData.height*5;
temp.getContext("2d").putImageData(imageData, 0, 0);
temp.getContext("2d").scale(5, 5); 
temp.getContext("2d").drawImage(temp, 0, 0);
temp.toDataURL('image/png',1.0);

Quality is much better when using this.canvas.toDataURL({format:'png', multiplier: 5});  comparing to temp.toDataURL('image/png',1.0);  


It will be very helpful if you give me sample code for exporting image in high quality .
Thank you

**Comment by asturur** [comment]
is unclear what this.canvas and tempCanvas are.

Fabric.Canvas.toDataURL is made to loose as much as little detail as possible.
The eventual fuzzyness you see is because of caching and not pixel perfect alignment.

If you disabled caching for all objects before exporting, in theory you would get maximum quality.
