### ISSUE TITLE
Changing controls default action and rendering options (position, icons, mouse pointer)

### ISSUE THREAD

**Issue by sbraaa** [fabricjs/fabric.js#6407]
I'm using latest available beta (4 beta 11) , I found very useful new custom controls feature but I'm not able to change default action of standard controls.
I've found a lot of sample (codepen, jsfiddle, google group) and hacks to do this in older version but it seems that latest version doesn't support some methods anymore..
Any attempt using _getActionFromCorner has been ignored, property rotatingPointOffset seems to be ignored too .
I guess that something could be done using drawControls method or _renderControls but haven't found any recent sample.
Anyone could give me some advice to solve these problems?
Thanks

**Comment by asturur** [comment]
The new api is built to remove hacks on internal methods, so what you find online won't work.
If you do not like the standard action of a control ( example MT ) remove mt from the controls object and just add a new control in the same position that does what you want.

**Comment by asturur** [comment]
http://fabricjs.com/controls-api <--- this is not complete but will give you an introduction.

**Comment by sbraaa** [comment]
Grazie Andrea! ;-)
In the meanwhile I have tried to understand by myself how it works and I was able to change everything I need modifying object prototype. 
The most challenging task was to display custom icons for standard controls.
I develop by myself renderImageControl method (similar to renderSquareControl and renderCircleControl) which use drawImage instead of fillRect or arc.
I have only one problem left to solve : when I place the first object on the canvas only Custom controls are displayed immediately. All the other standard controls (which I display using custom icons) are not drawn until the user move the object.
This happend only for the first object place on the canvas. If the user deselect it then select again It will be displayed correctly.
I've tried to force redraw using setCoords(), renderAll() and even requestRenderAll() but nothing change.
How can I solve this strange behaviour?
Thank you again

**Comment by asturur** [comment]
Probably because your image isn't loaded yet.
Before placing thing on the canvas, you have to ensure yourself the image element is ready to be drawn.

**Comment by asturur** [comment]
Be aware i m probably doing some small tweaks to the api that is in beta yet!
Probably the position option in the init, the object with x and y, will be merged in the normal options .

**Comment by sbraaa** [comment]
The images are inline svg base64 encoded :  
```
        let controlIcon = '<my svg base64 encoded>';
	var imgIcon = document.createElement('img');
	imgIcon.src = controlIcon;    
	ctx.drawImage(imgIcon,-sizeBy2, -sizeBy2, size, size);
```
I've tried using js dirty blocking function (500ms) but it doesn't solve the problem.
Any suggestion? Maybe a setTimeout  or better  async await function on the right place?

N.B. : I know that I'm working on a beta version, unfortunately I couldn't wait. I hope a new release will be ready soon.

**Comment by sbraaa** [comment]
Ok Preloding images do to job! 
Thank you
