### ISSUE TITLE
Contributing to the frontend documentation!

### ISSUE THREAD

**Issue by pupubird** [fabricjs/fabric.js#6409]
Hi!
First of all, I love this library! And I am sure most of the others love this as well!
Thou I don't think I will be able to contribute directly to the source code, but I would like to help out as well.
May I know if it is possible for me ( or us ) to contribute to the frontend documentation?😎😍

**Comment by asturur** [comment]
Sure!
You can either decide to write a short tutorial on a high level functionality or a demo, or simply creating a first user guide, it mostly depend on what level of knowledge you have of the library so far.

The current website works with MD files, and we are doing a new one that we are building quickly enough where the content will be porte. Is also useful to just convert the today demos to the new website demos with codepen, is still a great help.

**Comment by pupubird** [comment]
Got it! Thanks for replying so quickly!
May I know how can I contribute to the website? Is there any repository that I can look into?🎉

**Comment by asturur** [comment]
if you have a computer with ruby setup you can clone the repo 
https://github.com/fabricjs/fabricjs.com

start it with `jekyll serve` and modify the files that generate the pages ( in the posts folders )

If you want to contribute to transferring content to the new website, you can clone this repo here:
https://github.com/fabricjs/fabricjs.github.io

look at this PR here:
https://github.com/fabricjs/fabricjs.github.io/pull/19/files

To figure out how to take demo files from fabricjs.com and submit them in the new website.
The submission requires you to:
convert html to md file and to covert the code you find in the old page in a codepen.

I can give you more info and make a conversion example to clarify.

**Comment by pupubird** [comment]
Thanks @asturur ! I will figure the process out by myself, very excited to contribute to this!
