### ISSUE TITLE
Pinch scale object on touch device

### ISSUE THREAD

**Issue by shaktis110** [fabricjs/fabric.js#6410]
First of all thanks for this awesome project sir 

I just want to know that if it possible to pinch to scale or zoom only fabric js object like text, shape not entire canvas

**Comment by asturur** [comment]
Hi, i m sorry no one answered you for so long.
Yes there is a gesture module available, is not the most advanced thing, but it does offer rotate and pinch to zoom.

**Comment by shaktis110** [comment]
Thank you for your response sir ..

**Comment by mspanish** [comment]
hello I was wondering how one can activate touch events for fabric 4+? The demos say it's a 'custom fabric" but that's not a lot of info - is there a different download with a version that works for touch? is this version fully compatible w/ everything else (a drop in replacement?) Thanks!

**Comment by asturur** [comment]
you can obtain our terrible gesture implementation using the custom build feature on the website or from the command line after cloning the repo.

**Comment by asturur** [comment]
Now the implementation is actually contained in the file 'canvas_gestures.mixin.js' that you can find in the repository. From there you could be able to abstrac an implementation for hammer.js too that to me seems better.


I do not have time to get into gesture handling cross browser and my understanding is that event.js is the most outdated.

**Comment by mspanish** [comment]
Thanks very much, it's at least a start.
