### ISSUE TITLE
How to scale an object around an arbitrary point?

### ISSUE THREAD

**Issue by celsoaguiar** [fabricjs/fabric.js#6412]
Folks, I'm trying to mimic a functionality that exists in Paper.js where you can scale objects around an arbitrary point, like:

object.scale(xRatio, yRatio, new Point(someX, someY));

You basically get what the example below is showing, where the object in red is the scaled version of the circle:

http://paperjs.org/tutorials/project-items/transforming-items/#scaling-around-a-point

How can I write such a function in FabricJS so I can get the same result? It would have to use something like:

object.set({
  scaleY: YRatio,
});

I'm just not sure how to make the object scale around an arbitrary point or if that's even possible w/ Fabric.
The only thing I can think of is creating a group w/ my object and a point at [0, 0] and scaling the group, pretty cumbersome.

Thanks for your help!

link to stackoverflow question:
https://stackoverflow.com/questions/62543510/how-can-i-get-fabricjs-to-scale-around-an-arbitrary-point

**Comment by melchiar** [comment]
This may help.

https://stackoverflow.com/questions/48290646/fabric-js-custom-rotation-point

**Comment by asturur** [comment]
Also look at the custom control api.

If you want to change the pivot point for rotation, you have to modify the values of transform.originX and transform.originY.

originX and originY = 0 correspond to the top left corner of the object, while 1 and 1 correspond to bottom right, higher or lower number will keep the pivot point outside the object.

in the mtr corner you can wrap the action handler on something different:

```javascript
  objectControls.mtr = new fabric.Control({
    name: 'mtr',
    x: 0,
    y: -0.5,
    actionHandler: (eventData, transform, x, y) => {
      // write code here to change transform.originX and transform.originY.
      controlHandlers.rotationWithSnapping(eventData, transform, x, y);
    },
    cursorStyleHandler: controlHandlers.rotationStyleHandler,
    offsetY: -40,
    withConnection: true,
    actionName: 'rotate',
  });

```

**Comment by celsoaguiar** [comment]
Sorry, how do I actually get an objectControls. From my Path fabric object? From fabric object straight?

I was poking around and found out that obj.aCoords does not change if I change obj.top. My problem was exactly having to keep tabs of the original top for every other object. So, it looks like I'll be fine if I do the below on every path: 
      fabricObj.set({
          top: fabricObj.aCoords.tr.y * this.scaleYRatio,
          scaleY: this.scaleYRatio,
      });
The object itself gets scaled and the distance from y=0 also gets scaled. 
Looks like this is pretty much what I need.

**Comment by asturur** [comment]
to update aCoords look here: http://fabricjs.com/fabric-gotchas
for more about object controls look here: http://fabricjs.com/controls-api
