### ISSUE TITLE
objectCaching does not maintain strokeUniformity while resizing

### ISSUE THREAD

**Issue by TrevorHinesley** [fabricjs/fabric.js#6413]
## Version
3.6.3

## Test Case
http://jsfiddle.net/qsxm8vrf/

## Information about environment
macOS Catalina 10.15.5

## Steps to reproduce
Scenario 1: Open the fiddle, click run. Select the Rect and resize it.

Scenario 2: Change objectCaching to false, click run. Select the Rect and resize it.

## Expected Behavior
While resizing, the stroke should maintain uniformity whether caching is enabled or not.

## Actual Behavior
While resizing in scenario 1, the stroke distorts and skews until resizing is completed (mouse:up). While resizing in scenario 2, the stroke maintains uniformity throughout.

This GIF shows scenario 1 and scenario 2 (takes a minute, wait until it flashes to see scenario 2):

![captured (1)](https://user-images.githubusercontent.com/1079481/85808719-5e298200-b71b-11ea-8637-1e0d7d4c8384.gif)

**Comment by melchiar** [comment]
You can use the property `noScaleCache` on your object to prevent caching during scaling. 

See http://fabricjs.com/fabric-object-caching

**Comment by asturur** [comment]
Do we have this on the gotcha page?
i wonder if having a prefille answer from the menu here, `link to the gotchas` would rise awarness that such page exist.

![image](https://user-images.githubusercontent.com/1194048/85852077-32a4a700-b7b0-11ea-9b61-d05a38475472.png)

**Comment by melchiar** [comment]
It looks like this is missing from the gotchas page. This would be a good one to add for sure. 

When I have some time I'll try to clean up that page and make some additions. It'll be nice to put some more polish on the docs, especially with the move to running on Gatsby.

**Comment by TrevorHinesley** [comment]
That actually doesn't correct the problem if I'm doing this correctly: http://jsfiddle.net/wftL6b3x/

**Comment by melchiar** [comment]
Sorry, I probably should have been more specific about the property. Here's the property definition from the docs:

> **noScaleCache :Boolean** - When `true`, cache does not get updated during scaling. The picture will get blocky if scaled too much and will be redrawn with correct details at the end of scaling. this setting is performance and application dependant. default to true since 1.7.0
http://fabricjs.com/docs/fabric.Object.html#noScaleCache

So in your example, noScaleCache should be `false`.

**Comment by TrevorHinesley** [comment]
Ohhh got it. Thank you! Works like a charm now.
