### ISSUE TITLE
如何在编辑图层的时候四个角增加按钮

### ISSUE THREAD

**Issue by 603507931** [fabricjs/fabric.js#6419]

**Comment by juzhiyuan** [comment]
Please use English here, https://www.deepl.com/translator may help you.

**Comment by asturur** [comment]
hi @603507931  is important to follow the issue template.
This seems a request around custom controls (title translation: How to add buttons to the four corners when editing a layer)
Fabricjs does not support `buttons` but let you customize what control and extra controls can do.
You can read more here:
http://fabricjs.com/controls-api
