### ISSUE TITLE
hasRotatingPoint not work 

### ISSUE THREAD

**Issue by phantomlution** [fabricjs/fabric.js#6420]
## Version
4.0.0-beta.12

## Test Case
https://codepen.io/phantomlution/pen/NWxvVMg

## Information about environment
mac-chrome

## Steps to reproduce
when i upgrade fabric@3.6.3 to fabric.4.0.0-beta.12.
in order to get ability to use custom controls.
But i find the property hasRotatingPoint does not work anymore?
any solutions? or is this remote permanently?

**Comment by phantomlution** [comment]
But i got a workaround here.

`const controls = fabric.Object.prototype.controls
const rotateControls = controls.mtr
rotateControls.visible = true`

I get this control element, and disable it globally.

**Comment by asturur** [comment]
the property is removed. If you do not want to have any rotation control you just set it as invisible for one object with `object.setControlVisibility` or you remove it from the object of controls `delete fabric.Object.prototype.controls.mtr`
