### ISSUE TITLE
isTripleClick not a function

### ISSUE THREAD

**Issue by shizhchen2** [fabricjs/fabric.js#6424]
## Version
3.6.3

## Information about environment

when i add a textbox/itext on canvas then i switch to Drawing mode will triggle the error below:

fabric.js?7a94:27940 Uncaught TypeError: this.isTripleClick is not a function
    at klass.onMouseDown (fabric.js?7a94:27940)
    at klass.fire (fabric.js?7a94:313)
    at klass._handleEvent (fabric.js?7a94:11580)
    at klass._onMouseDownInDrawingMode (fabric.js?7a94:11672)
    at klass.__onMouseDown (fabric.js?7a94:11729)
    at klass._onTouchStart (fabric.js?7a94:11359)

After reading the source code, i found the code in line 28 of itext_click_behavior.mixin.js didnt check if this.isTripleClick exist or not.
I suggest the code `this.isTripleClick && this.isTripleClick(newPointer)`  will be better

**Comment by melchiar** [comment]
Triple click is not a supported event in FabricJS. You'll find the full list of supported events at the link below. Not to say you couldn't add it yourself with some tweaking, it's just not built-in.

http://fabricjs.com/events

**Comment by asturur** [comment]
isTripleClick is an internal utility function used from fabricjs to support some functionality ( like triple click select the line ).
If you do not have it, something wrong happened. Is in the Itext prototype upward.
