### ISSUE TITLE
setGradient deprecated but doku of replacement missing

### ISSUE THREAD

**Issue by garbast** [fabricjs/fabric.js#6425]
Since version 3.4.0 the setGradient is deprecated and in the latest meta not working any longer.

The doku for a way on how to replace it is missing.

What is the solution to use a Gradient as fill of a rectangle?

An example would be https://codepen.io/garbast1/pen/mdVBMKa

**Comment by melchiar** [comment]
The `setGradient()` method was removed in [v4.0beta7](https://github.com/fabricjs/fabric.js/releases/tag/v4.0.0-beta.7). You can use `rect.set('fill', new fabric.Gradient(options))` instead for object fill.
