### ISSUE TITLE
`IText` doesn't get updated on canvas after style changes

### ISSUE THREAD

**Issue by cassiozen** [fabricjs/fabric.js#6426]
## Version
4.0.0-beta.12

## Test Case
In fabric 3.x.x, if I I change a style property on an IText (say, `myIText.set('fill', hslColor);`), and request a render, the element gets updated on the canvas. On 4.0 it does not. 

On 4.0, If I explicitly call `myIText.cleanStyle('fill')` before changing the style, the changes are applied.

## Information about environment
Browsers, tested on Chrome, Edge & Firefox

## Steps to reproduce
1. Create an IText and requestRender
1. After the object is in the canvas, change some visual property, such as font family or color.
1. Request a new render

## Expected Behavior
New style property should be visible on existing text

## Actual Behavior
No visible changes on existing text

**Comment by melchiar** [comment]
Can you provide a fiddle showing the issue?

**Comment by asturur** [comment]
Could be related on some code we added for adding new lines and preserving styles ( i knew i shouldn't have done it :( ) but yes we need a jsfiddle to understand what you mean.
