### ISSUE TITLE
on mouse:move exception after adding an element to group defined with subTargetCheck

### ISSUE THREAD

**Issue by feature-engineer** [fabricjs/fabric.js#6429]
## Version
3.6.0

## Test Case
https://jsfiddle.net/8zeytmsj/36/

## Information about environment
Using Chromium 83.0.4103.61

## Steps to reproduce
Create a group with one element in it and with the option {subTargetCheck: true}, and add another element to the group.

## Expected Behavior
Should behave the same way it does when creating the whole group in one go.

## Actual Behavior
Gives the following error:

> Uncaught TypeError: Cannot read property 'tl' of null
>     at i._getImageLines (fabric.min.js:1)
>     at i.containsPoint (fabric.min.js:1)
>     at i.containsPoint (fabric.min.js:1)
>     at i._checkTarget (fabric.min.js:1)
>     at i._searchPossibleTargets (fabric.min.js:1)
>     at i._searchPossibleTargets (fabric.min.js:1)
>     at i.findTarget (fabric.min.js:1)
>     at i._cacheTransformEventData (fabric.min.js:1)
>     at i.__onMouseMove (fabric.min.js:1)
>     at i._onMouseMove (fabric.min.js:1)

**Comment by asturur** [comment]
I m sure you probably solved after this long time.
You need to use addWithUpdate when adding to a group.
