### ISSUE TITLE
Adding objects to group then importing causes a crash

### ISSUE THREAD

**Issue by TheBird956** [fabricjs/fabric.js#6430]
## Version
3.6.3

## Test Case
https://jsfiddle.net/2w3xft5h/11/

## Information about environment
Any browser. Error originally found in Angular 9 project but exists outside of it.

## Steps to reproduce
1. Create an empty js object containing a `objects` property containing an empty array.
2. Create a new fabric group and save the value in a variable
3. Create an array of multiple fabric objects (rect in my example)
4. Push those object in the array created in step 1
5. Load the js object created in step 1 into FabricJs using `loadFromJSON`

## Expected Behavior
Should load the objects inside the group and display them without issue.

## Actual Behavior
FabricJs crash with this error in the log:
```
fabric.js:1972 Uncaught RangeError: Maximum call stack size exceeded
    at extend (fabric.js:1972)
    at extend (fabric.js:1989)
    at extend (fabric.js:1980)
    at extend (fabric.js:1989)
    at extend (fabric.js:1989)
    at extend (fabric.js:1980)
    at extend (fabric.js:1989)
    at extend (fabric.js:1989)
    at extend (fabric.js:1980)
    at extend (fabric.js:1989)
```

## Additional information/context
I am trying to create a structure I can build without integrating FabricJs too much in a specific class so I can later load that structure into FabricJs. I want to keep FabricJs and the application code decoupled for that specific class and when getting in the Angular context, generate and display the FabricJs canvas.

**Comment by asturur** [comment]
The error here is trying to load from JSON something that is a real group.

if you add in the objects the `group.toObject()` it works as expected
```javascript
canvasObject.objects.push(group.toObject());
```
