### ISSUE TITLE
Please help me achieve the wave effect

### ISSUE THREAD

**Issue by HDONGDeveloper** [fabricjs/fabric.js#6431]
![GIF 2020-07-03 13-07-29](https://user-images.githubusercontent.com/31230864/86433869-68a4d680-bd2e-11ea-8c1c-e93505dedafb.gif)
How to achieve this effect

**Comment by asturur** [comment]
You have to animate a path, is not that easy.
Do you an example of the animation somewhere? From scratch i cannot build it. I have no idea where to start.

**Comment by HDONGDeveloper** [comment]
https://jsfiddle.net/chujiu/uv628xwt/3/
I wrote an example of canvas.
Early on, I tried to use it fabric.Path To achieve.
But I can't draw it perfectly
