### ISSUE TITLE
Cannot read property 'textBackgroundColor' of null

### ISSUE THREAD

**Issue by faradey** [fabricjs/fabric.js#6433]
## Version
2.7.0
3.6.0

## Information about environment
browser
Chrome

## Steps to reproduce
if in JSON data is "styles": [],

## Expected Behavior
not error and pass putting style

## Actual Behavior
error 

Solution is change code by link
https://github.com/fabricjs/fabric.js/blob/09552e68f1aa460ba87c21a8a292430bee9b4b4c/dist/fabric.js#L26331
from
if (typeof obj[p1][p2][property] !== 'undefined') {
to
if (obj[p1][p2] && typeof obj[p1][p2][property] !== 'undefined') {

**Comment by asturur** [comment]
Can you reproduce the error in a fiddle? the code seems fine to me.

**Comment by faradey** [comment]
https://jsfiddle.net/gu94kzj6/

**Comment by asturur** [comment]
That is a wrong styles object.
Styles is an object not an array.
How did you end up with an array in styles?

**Comment by faradey** [comment]
https://jsfiddle.net/gu94kzj6/
I do canvas to json, save json to DB, json to canvas

**Comment by asturur** [comment]
When you do canvas.toJSON do you get that kind of value?

**Comment by faradey** [comment]
I can't repeat this case. It did a visitor of the site.
