### ISSUE TITLE
Question: Can we use react-fabric plugin with react-chartjs and overlay a draggable circle?

### ISSUE THREAD

**Issue by getnsv** [fabricjs/fabric.js#6437]
Hi there,

Am working on a usecase using reactjs, where I have a doughnut chart(chartjs plugin) and want to render a circle as an overlay. Can I use react-fabricjs plugin for this usecase... the circle overlay should be draggable within the div of this chart and visible on top for the users to move around and select a section of the donut chart.

Kindly let me know if this kind of usecase is feasible, so that I can dive deeper into achieving this with this flexible javascript library.

Many thanks,
Sreevani

**Comment by asturur** [comment]
Hi @getnsv sadly i do not know either react-chartjs or react-fabricjs plugin.
I see chartjs creates a canvas, so eventually you can use it outside of react, create your own chart, and add on top of a fabric StaticCanvas (if you do not need interaction) as an image ( created from a canvas ) and also add your circle.
