### ISSUE TITLE
loadFromJSON not working

### ISSUE THREAD

**Issue by shreyaHomelane** [fabricjs/fabric.js#6438]
## Version
3.6.3

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Nodejs or browser?
Which browsers? Chrome

## Steps to reproduce
Adding random objects like ellipse/line/arrow(group object) on different pages 
saving canvas objectJSON for each pages in backend(nodejs)
while fetching JSON from server, using loadFromJSON function to render json for each page

`       canvas.loadFromJSON(json, canvas.renderAll.bind(canvas), function(o, object) {
            console.log('rendered successfully')
            console.log(o,object)
            // `o` = json object
            // `object` = fabric.Object instance
            // ... do some stuff ...
        });
`

## Expected Behavior
each page should render all objects fetched. 

## Actual Behavior
but it fetches partially, acts randomly and weirdly, sometimes all objects are rendered sometime only one object.
though i can see in log there are 5 objects in json, but canvas loads only 2 objects.

**Comment by melchiar** [comment]
The fiddle in your post is empty. Can you please provide a working fiddle demonstrating the issue?
