### ISSUE TITLE
Zoom and pan, introduction to FabricJS part 5 issues

### ISSUE THREAD

**Issue by jasonsturges** [fabricjs/fabric.js#6439]
Think there are two issues with the zoom and pan documentation on your page:
http://fabricjs.com/fabric-intro-part-5

First, if I use your zoom pan methods, viewport transforms don't appear to be updated after move - objects that were offscreen are not selectable - coordinates are not updated.

![editor-transform-bug](https://user-images.githubusercontent.com/1213591/86872237-7b5a3b00-c0a1-11ea-88f1-0c0a20ec24e3.gif)

In your example code:

```
canvas.on('mouse:move', function(opt) {
  if (this.isDragging) {
    var e = opt.e;
    var vpt = this.viewportTransform;
    vpt[4] += e.clientX - this.lastPosX;
    vpt[5] += e.clientY - this.lastPosY;
    this.requestRenderAll();
    this.lastPosX = e.clientX;
    this.lastPosY = e.clientY;
  }
});
```

I believe you are missing setting the viewportTransform:

```
this.setViewportTransform(vpt);
```

Second, your final example is missing closure of the function scope:

```
canvas.on('mouse:wheel', function(opt) {
  var delta = opt.e.deltaY;
  var zoom = canvas.getZoom();
  zoom *= 0.999 ** delta;
  if (zoom > 20) zoom = 20;
  if (zoom < 0.01) zoom = 0.01;
  canvas.zoomToPoint({ x: opt.e.offsetX, y: opt.e.offsetY }, zoom);
  opt.e.preventDefault();
  opt.e.stopPropagation();
  var vpt = this.viewportTransform;
  if (zoom < 400 / 1000) {
    vpt[4] = 200 - 1000 * zoom / 2;
    vpt[5] = 200 - 1000 * zoom / 2;
  } else {
    if (vpt[4] >= 0) {
      vpt[4] = 0;
    } else if (vpt[4] < canvas.getWidth() - 1000 * zoom) {
      vpt[4] = canvas.getWidth() - 1000 * zoom;
    }
    if (vpt[5] >= 0) {
      vpt[5] = 0;
    } else if (vpt[5] < canvas.getHeight() - 1000 * zoom) {
      vpt[5] = canvas.getHeight() - 1000 * zoom;
    }
  })
```

This should end with:
```
    }
  }
});
```

**Comment by asturur** [comment]
The demo is specific about understanding the viewport and so all the selection related stuff is missing.
I'll update the doc using setViewportTransform and try to see if we can cover the coords logic without making the demo too long.

Nice app you built there! How are the performances with many object? how is your experience with fabricjs sofar?

**Comment by jasonsturges** [comment]
Setting the viewport transform back seemed to solve all problems.  Example was perfect, exactly what I needed.

Thanks.  I really enjoy Fabric, especially for its editing capabilities.  Performance is astonishing - diminishes a bit with text, but fantastic in general with very low idle.

Over 2,000 objects remains smooth and responsive, with instant loads leveraging Fabric JSON serialization to load different scene graphs into my editor.

![editor](https://user-images.githubusercontent.com/1213591/87066840-d6427e00-c1d8-11ea-9e4e-68b093e44b2f.gif)

Excited for the upcoming release.

Thanks, again - best.
