### ISSUE TITLE
Image.fromURL didn't work in electron app

### ISSUE THREAD

**Issue by de-don** [fabricjs/fabric.js#6440]
## Version
3.6.3

## Information about environment
Electron 9.0.4

## Steps to reproduce
Create simple app with Angular + Electron, and following code:
```
const imageUrl = "SOME_URL_HERE";
fabric.Image.fromURL(imageUrl, (img) => {
  const imageLoaded = Object.keys(img.getElement()).length > 0;
  alert(imageLoaded);
});
```

## Expected Behavior
Image loaded

## Actual Behavior
The image didn't load, but I see a successful request to the image in DevTools.
`crossOrigin` param didn't help

**Comment by asturur** [comment]
This is not a reproducible case.
Is there an online code sampler for electrons app?

**Comment by de-don** [comment]
> This is not a reproducible case.
> Is there an online code sampler for electrons app?

I don't know.

I solved my issue via manual creating img element, and adding `onloadend` handler.

Maybe need to add handler for `onloadend` event here:
https://github.com/fabricjs/fabric.js/blob/7f814c9cc1082b234537dc1842d98afb7dcd85ed/src/util/misc.js#L352
Like this:
```
img.onload = img.onloadend = onLoadCallback; 
```

**Comment by asturur** [comment]
image loading works in fabricJS and node with JSDOM.
on what side of electro are you running this code?

onloadend seems a pretty new thing.
![image](https://user-images.githubusercontent.com/1194048/87040569-2fb6a700-c1f1-11ea-805c-646969ed303c.png)
