### ISSUE TITLE
strokeUniform inside group create extra padding on scale

### ISSUE THREAD

**Issue by vince4** [fabricjs/fabric.js#6441]
## Version
3.6.3

## Test Case
https://jsfiddle.net/yc02pqhs/22/

## Steps to reproduce

1. Create a Rect with `strokeUniform` set to `true`
2. Create a Group with previous rect inside
3. Upscale the group

## Expected Behavior

If the selection has no padding defined, there should be no space between stroke and border. 
<img width="487" alt="Capture d’écran 2020-07-08 à 12 36 58" src="https://user-images.githubusercontent.com/1721591/86909030-ca42b780-c117-11ea-91eb-004d32468f00.png">

## Actual Behavior

There is an extra padding between stroke and border. 
<img width="487" alt="Capture d’écran 2020-07-08 à 12 36 11" src="https://user-images.githubusercontent.com/1721591/86909057-d169c580-c117-11ea-9ef4-3a8c312cd92d.png">

## Related Merge
This issue must be related to this merge request : #5950

**Comment by vince4** [comment]
The issue is not fixed.

**Comment by webceoboy** [comment]
+1，

**Comment by asturur** [comment]
Please check referenced issue and then remove your +1 if it apply

**Comment by asturur** [comment]
There is a workaround in 6.x for this issue
