### ISSUE TITLE
when object originX or originX is set to center it does not scale correctly when importing from JSON

### ISSUE THREAD

**Issue by human-a** [fabricjs/fabric.js#6442]
## Version
4.0.0-beta.12 and above

## Test Case
https://codesandbox.io/s/purple-star-0b0ik?file=/src/index.js
(press alt/option Z to toggle the word wrap to see the JSPON)

## Information about environment
browser
all

## Steps to reproduce
try to scale the rectangle using any of the mr, mb, ml or mt corners.

## Expected Behavior
Should scale correctly

## Actual Behavior
If you scale anything with origins set to center using mr, mb, ml or mt corners the objects loses its coords and jumps up out of the canvas. The appears to be only happening in the NPM copy of fabric.
I tried a fiddle getting fabric from cdnJS and it works there:
https://jsfiddle.net/human_a/3a9eLuk1/

This does not happen in 4.0.0-beta.11

---------------------------------------------
PS.
To resolve the issue temporarily, I tried setting the origins to 0 when importing, then setting left and top using the following, it also does not position properly if the object is rotated
```
object.set({
    originX: 0,
    originY: 0,
    left: object.left - (object.getScaledWidth() / 2),
    top: object.top - (object.getScaledHeight() / 2),
});
```

**Comment by asturur** [comment]
Hi @human-a, in the fiddle you posted everything works correctly.
While in the codesandbox version i notice a bug that i cannot reproduce on the fiddle.

I would ask you to tell me how do you trigger a bug because i did it with something that is not exactly what are you reporting.

Can you help me understand better?

**Comment by human-a** [comment]
Thanks for getting back to me.

As mentioned, the npm version appears to be having this bug, so in your fiddle if you can somehow use the npm version of fabricjs then you can reproduce the issue. I have also included a link to a fiddle where it uses the cdnJS link for fabricJs and it works fine there.

To reproduce the issue in the codesandbox, just try fiddling with any of mr, mb, ml or mt corners, and after a couple of times of dragging those points, it jumps out of the canvas and disappears.

I hope this makes sense, let me know if I can explain better.

**Comment by asturur** [comment]
There isn't npm vs cnd version of fabricJS.
The current cdn version of fabric 4 is made with unpkg that will take the files from npm packages.
So i guess the problem is related to codesandbox only.
Does this happen on your application too?
I wish i could reproduce it locally.

For me it happens almost immediately if i scale using the ml corner moving on the top left direction.

**Comment by human-a** [comment]
Yes of course, I am using CRA (create react app) on local, I tried reproducing the issue in jsfiddle, which I could not, then in codesandbox the behavior is the same as in my local machine.

If I downgrade to 4.0.0beta.11 everything works, any version above that breaks the scaling as explained.

**Comment by human-a** [comment]
By the way, when trying on local, use a JSON import, and make sure the originX and originX are set to "center", then it should break.

**Comment by asturur** [comment]
we can make a diff of what changed between beta.11 and rc1. Does beta12 works?

https://github.com/fabricjs/fabric.js/compare/v4.0.0-beta.11...v4.0.0-rc.1

**Comment by human-a** [comment]
it starts breaking from beta12 so I guess it's better to diff beta.11 and beta.12

**Comment by human-a** [comment]
it has to be either in object_geometry.mixin.js or controls.actions.js
Thoughts?

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/compare/v4.0.0-beta.11...v4.0.0-beta.12

Need time to look the changes in details
