### ISSUE TITLE
Adding custom controls does not work for textbox objects

### ISSUE THREAD

**Issue by human-a** [fabricjs/fabric.js#6444]
## Version
4.0.0

## Test Case
http://fabricjs.com/custom-control-render

## Steps to reproduce
in any of the codepens in the link above, try replacing the rectangle with a fabric.Textbox element, the custom controls disappear. It seems to be workign fine with fabric.Text and fabric.IText but not for the fabric.Textbox

## Expected Behavior
Text objects are inheriting from the fabric.Object element, but apparently they do not inherit the new controls object.

**Comment by human-a** [comment]
Alright, I got this working, adding ```fabric.Textbox.prototype.controls = fabric.Object.prototype.controls;``` seems to solve the issue. I also noticed the following in the source coude:

```
// this is breaking the prototype inheritance, no time / ideas to fix it.
// is important to document that if you want to have all objects to have a
// specific custom control, you have to add it to Object prototype and to Textbox
// prototype. The controls are shared as references. So changes to control `tr`
// can still apply to all objects if needed.
var textBoxControls = fabric.Textbox.prototype.controls = { };
```

Overriding this does not seem to be breaking anything in my code. Am I missing somethign or is it safe to override it as I did?

**Comment by human-a** [comment]
Scratch that, I realized what is breaking, I can no longer resize the textbox if I override the whole prototype. Have to be done one by one. You can close this issue :)

**Comment by asturur** [comment]
wait the `breaking the prototype inheritance` refer to the fact that adding a control to fabric.Object.prototype won't reflect on fabric.Textbox.prototype. You have simply to add it twice.

```javascript
 var customControl = new fabric.Control({ ... });
 fabric.Object.prototype.controls.custom = customControl;
 fabric.Textbox.prototype.controls.custom = customControl;
```

that's it.
