### ISSUE TITLE
problem removing object

### ISSUE THREAD

**Issue by sbraaa** [fabricjs/fabric.js#6447]
My project use fabric.js to place some "placeholder" on a canvas a let the user substitute those placeholder with newer fabric object.
When I substitute a placeholder I remove the object (canvas,remove(object)) then I place the new object in the same position and with the same size of placeholder object but it doesn't get rendered!
It looks like that removed object overlap the new one preventing his displaying.
I've tried with bringToFront to be sure that the new obj has a z-index greater then the removed obj but it doesn't work.
Doing the same thing without drawing original placeholder obj make everything working as expected.
Anyone faced a problem like this?
Thank you in advance

**Comment by asturur** [comment]
Hi @sbraaa, we need you to be able to reprdouce the problem in a jsfiddle or we can't see that happen we do not what to look at.

**Comment by juzhiyuan** [comment]
`Steps to reproduce` should be more attractive

**Comment by sbraaa** [comment]
Hi, I was preparing a jsfiddle to show you how it looks like and doing that I finally understand why object wasn't removed (problem with object references) which depends by my code.
My mistake, Thank you for your patience

**Comment by asturur** [comment]
This is one of the main reason why a fiddle save time. it either point you to the problem or us.
