### ISSUE TITLE
How to set up multiple active objects instead of grouping them

### ISSUE THREAD

**Issue by 13029678009** [fabricjs/fabric.js#6449]
I want to implement multiple object selection and highlight the currently selected object instead of grouping objects. In short, it is similar to **setActiveobjects** API. How can I do this? thanks🙂

**Comment by asturur** [comment]
you can't.
It is a wildly different behaviour
for which we do not have any code.

**Comment by 13029678009** [comment]
> you can't.
> It is a wildly different behaviour
> for which we do not have any code.


Oh, I see. Thank you for your reply. If it doesn't work, I'll do it in groups

**Comment by asturur** [comment]
You can still write all the code, but is a long process of understanding fabricJS internals.
