### ISSUE TITLE
how to use custom controls icon by 4.0.0-rc1

### ISSUE THREAD

**Issue by bulolo** [fabricjs/fabric.js#6450]
after read 
http://fabricjs.com/custom-control-render
http://fabricjs.com/controls-api

![image](https://user-images.githubusercontent.com/10026498/87143738-302a6d00-c2d9-11ea-9cc3-30751c3ebd54.png)
i want to custom control like this

but seem only can render one image,if i change the ml below,something error
![image](https://user-images.githubusercontent.com/10026498/87143925-84355180-c2d9-11ea-9504-b80b60878719.png)

this is my code :
https://codepen.io/bulolo/pen/LYGrpoJ

i just want to custom to replace the tl, mt, tr, mr, br, mb, bl, ml and mtr's icon with original resize function.
but seem after replace it ,the function is not used and the icon is not right with error

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/87149008-c053bc80-c2af-11ea-9629-7862dfa17ab3.png)

your icon is a white circle

**Comment by bulolo** [comment]
@asturur 

one is 
![image](https://user-images.githubusercontent.com/10026498/87149167-51438b80-c2e2-11ea-8dd8-ca3d96da30c3.png)

one is 
![image](https://user-images.githubusercontent.com/10026498/87149193-602a3e00-c2e2-11ea-9144-c8c6f867e831.png)

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/87149720-0eb58b00-c2b1-11ea-843b-f35e42dad097.png)
