### ISSUE TITLE
how to dynamically change the sharpening effect in the filter

### ISSUE THREAD

**Issue by wangyong991** [fabricjs/fabric.js#6455]
I want to dynamically change the Sharpen  in the filter , passing parameters through the user。in the examples
```
var filter = new fabric.Image.filters.Convolute({
  matrix: [ 0, -1,  0,
           -1,  5, -1,
            0, -1,  0 ]
});
object.filters.push(filter);
object.applyFilters();
canvas.renderAll();
```
I don't know how to change the matrix . Can you give some tips？ thanks.

**Comment by asturur** [comment]
i have no idea what gives a stronger or softer sharpening effect.

![image](https://user-images.githubusercontent.com/1194048/87779210-bb04ed80-c82c-11ea-875e-f0e8afaba130.png)

i found those 2 kernels here.

Di you try applyin the sharpen effect more than once?

**Comment by asturur** [comment]
also
![image](https://user-images.githubusercontent.com/1194048/87779385-fdc6c580-c82c-11ea-96d7-d41e9366683b.png)

from here http://www.globalsino.com/EM/page1371.html
