### ISSUE TITLE
Play audio in fabric.js

### ISSUE THREAD

**Issue by SridharRamasami** [fabricjs/fabric.js#6457]
Here is the Stackoverflow question:
https://stackoverflow.com/questions/62894018/how-to-add-audio-to-fabric-js-animation

I would like to play audio at certain times. How do I play audio in fabric.js. Example in the animation below (created with fabric.js) I would like to play an audio file when the character is talking.

![Toonclip - I thought I was having a bad day](https://toonclip.com/clientImages/7ecd79867b/toonclip.gif) 

Please let me know if further clarifications/details are needed.
Thanks

**Comment by Chienle** [comment]
You can play audio file when using callbank function after render facbricjs object.
