### ISSUE TITLE
Textbox text align center not working properly (Brave Browser)

### ISSUE THREAD

**Issue by salatielq** [fabricjs/fabric.js#6458]
## Version
3.6.3

## Test Case
https://codesandbox.io/s/determined-lehmann-s2pel?file=/src/index.js

## Environment
Brave Browser Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit)
macOS 10.15.3

## Steps to reproduce
- Create a new canvas
- Add a textbox center aligned

## Expected Behavior
To get a center-aligned text as in the Fabricjs kitchen sink:
![Screen Shot 2020-07-14 at 09 55 13](https://user-images.githubusercontent.com/6747627/87428176-56d9f380-c5b8-11ea-8920-e05d557b552b.png)

## Actual Behavior
But seems that the text is getting a kind of margin to the middle of the textbox:
![Screen Shot 2020-07-14 at 09 57 01](https://user-images.githubusercontent.com/6747627/87428267-7a9d3980-c5b8-11ea-81de-8e8bb5eed3e8.png)

**Comment by melchiar** [comment]
Seems to work fine for me. What device/browser are you running? (I'm testing on android Chrome)

**Comment by salatielq** [comment]
> Seems to work fine for me. What device/browser are you running? (I'm testing on android Chrome)

I'm using Brave/Mac and just found out that this is a Brave bug and is working fine on Chrome.

**Comment by asturur** [comment]
weird i use brave for everything and did not notice. Probably has been a bug in chrome too and brave is just a couple of patches behind? I ll check when i m home

**Comment by salatielq** [comment]
@asturur I don't know if is a patch problem. I tested on Chrome 83.0.4103.116 (same patch I tested Brave) and worked.

**Comment by asturur** [comment]
so if browser personalization can break core browsers features the new edge will be broken often i suppose. I hope we find a different explanation!
