### ISSUE TITLE
Hue, Sharpness and Blur properties are not available

### ISSUE THREAD

**Issue by ganeshpat** [fabricjs/fabric.js#6460]
## Version
3.6.2

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Google Chrome

## Expected Behavior
1. After importing the fabric.js, there should be property for hue, sharpness and blur

## Actual Behavior
1. after importing the fabric.js library, there is no suggestion for the hue, sharpness and blur under ' fabric.Image.filters ' option

**Comment by asturur** [comment]
Empty fiddle and unclear question.
Can you be more specific please?

Thanks.
