### ISSUE TITLE
Incorrect BlendImage filter operation when (left,top) not (0,0)

### ISSUE THREAD

**Issue by sjscotti** [fabricjs/fabric.js#6463]
## Version
3.6.3

## Test Case
https://codesandbox.io/s/blissful-frost-j8kw4

## Information about environment
browser
Which browsers? Firefox and Chrome

## Steps to reproduce
I used a gradient filled rectangle sized to the image to be shaded (a flower png which is all black).  I added a BlendColor/tint filter to make the flower white, and then I added the BlendImage/multiply filter with the filled rectangle converted to an image.   I applied the filters.  When the left, top of all the 3 object was at 0, 0, the flower was shaded as I expected and is shown in this fiddle.
https://codesandbox.io/s/fancy-river-j90hn

But when all 3 objects had left top at 200, 200 the shading was incorrect as can be seen in this fiddle
https://codesandbox.io/s/blissful-frost-j8kw4

## Expected Behavior
Gradient showing up in the flower as shown in 
https://codesandbox.io/s/fancy-river-j90hn

## Actual Behavior
Gradient incorrectly showing up in the flower as shown in 
https://codesandbox.io/s/blissful-frost-j8kw4

**Comment by asturur** [comment]
when you use an image as blend, the image gets positioned over the other one using the top left, angle, scaleX etc etc...
so if you want them to overlap you have to leave it at 0,0.

Does it sound strange?

**Comment by sjscotti** [comment]
Thanks for getting back to me.  Yes, I got it working when both the image and blendimage were located at (left, top) = (0,0) and they had the same dimensions.
I had assumed the images overlap and can be blended if you set the positions and dimensions to be the same, regardless of where on the canvas they appear since you can display either image in the exact same area of the canvas.  I only discovered the (0,0) trick by accident because my intuition was telling me that it shouldn't matter where they were positioned - as long as they occupied the same space on the canvas.  If the present behavior is what is desired, I suggest it be mentioned in the documentation.  Thanks again!

**Comment by asturur** [comment]
you can use the scaleX and scaleY to stretch the image if it is smaller or larger
