### ISSUE TITLE
Setting textbox textBackgroundColor directly doesn't reflect in canvas

### ISSUE THREAD

**Issue by luizcieslak** [fabricjs/fabric.js#6464]
## Version
3.6.3, 4.0.0-rc.1

## Test Case
https://jsfiddle.net/urs0nypm/14/

## Information about environment
Nodejs or browser? browser
Which browsers? Firefox and Chrome

## Steps to reproduce

Click on "change bg color" button

## Expected Behavior

`textBackgroundColor` be "red"

## Actual Behavior

textbox in canvas appear without bg color.

Hi! First of all, thanks for your work in this library! It is truly awesome.

I came up with this problem recently. It seems that changing the `textBackgroundColor` directly such as: 
```js
textbox.textBackgroundColor = "red"
canvas.renderAll()
```

doesn't show up in canvas. In `canvas.toJSON()` method the textbox appears with a background. When you resize it after pressing the button, the background also appears.

Perhaps it doesn't trigger a visual update in textbox when updated this way?

using `set()` solves the problem:
```js
textbox.set('textBackgroundColor', 'red')
canvas.renderAll()
```

So, reporting this here since it may be an unexpected behavior.

**Comment by asturur** [comment]
http://fabricjs.com/fabric-gotchas
