### ISSUE TITLE
Re-center canvas, with animation, after zoom/pan

### ISSUE THREAD

**Issue by TheMangoTrain** [fabricjs/fabric.js#6469]
Using fabric.js, I'm building animated re-centering for the canvas, where it springs back to center with an elastic effect.

**WORKS (default zoom):** The canvas springs back to center after the user clicks+drags (pans) the canvas in any direction, in default zoom.

**FAILS (zoomed-in):** When zoomed-in and the user pans the canvas to the point where the box disappears from view, the re-centering func is triggered, motion happens, but the canvas is moved to wrong coordinates.

On lines 183/184, the proper x,y coords are needed to animate the canvas to. I'm having lots of trouble figuring this out.

**Some side questions:**

Ultimately the movement is executed via canvas.setViewportTransform, but for this case, should I be using canvas.relativePan?

Is there a better way to animate multiple properties at once? Currently I'm using two separate .animate instances.

**Code:**
https://codepen.io/MarsAndBack/pen/MWKzYPe

**Also posted here on Stackoverflow:**
[https://stackoverflow.com/questions/62961768/fabric-js-re-center-canvas-with-animation-after-zoom-pan](https://stackoverflow.com/questions/62961768/fabric-js-re-center-canvas-with-animation-after-zoom-pan)

**Comment by asturur** [comment]
Is unclear to me what kind of effects and when you want to obtain it.
There are some things that you could change in your fiddle, for example in the animation, use 2 animations to animate the values, but just one of them would actually set the value in the canvas.

But apart from that i do not understand what you want to animate and where.

```

<!-- begin snippet: js hide: false console: false babel: false -->

<!-- language: lang-js -->

    // =======================================================
    // SETUP
    // =======================================================

    const canvas = new fabric.Canvas("myCanvas")
    const lastX = null
    const lastY = null
    canvas.backgroundColor="#222222"

    this.box = new fabric.Rect ({
      width: 240,
      height: 100,
      fill: '#fff28a',
      myType: "box"
    })

    canvas.add(this.box)
    this.box.center()


    // =======================================================
    // INTERACTIONS
    // =======================================================

    canvas.on({
      'mouse:down': (opt) => {
        
        // Capture mouse coords for mousewheel-zoom-to-cursor
        this.lastX = opt.pointer.x
        this.lastY = opt.pointer.y     
      },
      
      'mouse:up': (opt) => {
        
        // If we're zoomed out, we just spring the canvas back to center
        if (canvas.getZoom() <= 1) {
          this.reset(canvas)
        
        
        // If we're zoomed in and user pans to a point where
        // the box is no longer on-screen, then spring canvas back to center
        } else { 
          if (this.box.isOnScreen() == false) {
            this.reset(canvas)
          }
        }
      },

      'mouse:wheel': (opt) => {
        
        // For zoom-to-cursor
        
        
        // ------------------------------------------
        // Wheel speed/resolution adjustment
        // ------------------------------------------
        let delta = 0
        let wheelDelta = opt.e.wheelDelta
        let deltaY = opt.e.deltaY
        // CHROME WIN/MAC | SAFARI 7 MAC | OPERA WIN/MAC | EDGE
        if (wheelDelta) {
          delta = -wheelDelta / 120
        }
        // FIREFOX WIN / MAC | IE
        if(deltaY) {
          deltaY > 0 ? delta = 1 : delta = -1
        }
        // ------------------------------------------


        // SETUP
        let pointer = canvas.getPointer(opt.e)
        let zoom = canvas.getZoom() - delta / 10

        // limit zoom in
        if (zoom > 3) zoom = 3

        // limit zoom out and reset canvas to dead-center
        if (zoom < 1) {
          zoom = 1
          this.reset(canvas)
        }

        canvas.zoomToPoint({
          x: opt.e.offsetX,
          y: opt.e.offsetY
        }, zoom)

        opt.e.preventDefault()
        opt.e.stopPropagation()             

        canvas.renderAll()
        canvas.calcOffset()
      },

        
      'touch:drag': (opt) => {
        
        // For panning (click and drag anywhere)
        
        let startX = opt.self.start.x
        let startY = opt.self.start.y
        let currentX = opt.self.x
        let currentY = opt.self.y
        let xChange = currentX - this.lastX
        let yChange = currentY - this.lastY      
        let delta = new fabric.Point(xChange, yChange)
        
        console.log("canvas.getCenter.top: " + canvas.getCenter().top)
        console.log("canvas.getVpCenter.y: " + canvas.getVpCenter().y)

        canvas.relativePan(delta)
        canvas.requestRenderAll()
        this.lastX = currentX
        this.lastY = currentY
      }
    })



    // =======================================================
    // CANVAS CENTERING (with animation and easing)
    // =======================================================

    const panAnim = {};

    function reset(canvas) {
      
      let origZoom = canvas.getZoom()
      let origX = canvas.viewportTransform[4]
      let origY = canvas.viewportTransform[5]
     
      
      // For now, animating single X and Y props seperately.
      // Using fabric.util.animate() as that is what's available for canvas (unlike object.animate() )
      
      fabric.util.animate({
        startValue: origX,
        endValue: CenterCoord().x,
        duration: 500,
        easing: fabric.util.ease["easeOutElastic"],
        onChange: function(value) {
          panAnim.x = value;
          
          // Alternative?
          //canvas.relativePan( value , origY)
        },

        onComplete: function() {
          canvas.renderAll();
        }
      })

      fabric.util.animate({
        startValue: origY,
        endValue: CenterCoord().y,
        duration: 500,
        easing: fabric.util.ease["easeOutElastic"],
        onChange: function(value) {
          panAnim.y = value;
          canvas.viewportTransform = [origZoom, 0, 0, origZoom, panAnim.x, panAnim.y];
          canvas.renderAll();
          // Alternative?
          // canvas.relativePan( origX , value)
        },     
        onComplete: function() {
          canvas.setViewportTransform(canvas.viewportTransform);
        }
      })
    }


    function CenterCoord() {
      
      if (canvas.getZoom() > 1) {
        
        var vpt = canvas.viewportTransform    
        console.log("vpt[4]: " + vpt[4])
        console.log("vpt[4]: " + vpt[5])
        console.log("canvas.getCenter.top:" + canvas.getCenter().top)
        console.log("canvas.getVpCenter.y: " + canvas.getVpCenter().y)
        
        return canvas.getVpCenter();
        
      } else {
        
        // For default zoom, this is all we need
        return {
          x : 0,
          y : 0
        }
        
      }
    }

<!-- language: lang-html -->

    <script src="https://cdn.jsdelivr.net/npm/fabric-with-gestures@3.6.1/dist/fabric.min.js"></script>
    <canvas id="myCanvas" width="700" height="400"></canvas>

<!-- end snippet -->
```

**Comment by TheMangoTrain** [comment]
Hi asturur,

I apologize, this post has two distinct issues (centering and animation); I've made a separate issue for the centering aspect.

**Regarding animating the canvas:**

I understand objects have object.animate() where multiple props can be animated at the same time, for example:

`triangle.animate('left', animationDefinition.left, {duration: animationDefinition.duration, onChange:canvas.renderAll.bind(canvas)})`

Does canvas have the equivalent?

**Comment by TheMangoTrain** [comment]
Ok, I fixed my original issue.

It boils down to these two lines:
panX = ((canvas.getWidth() / zoom / 2) - (object.aCoords.tl.x) - (objWidth / 2)) * zoom
panY = ((canvas.getHeight() / zoom / 2) - (object.aCoords.tl.y) - (objHeight / 2)) * zoom

Perhaps these statements could be even simpler, but this works regardless.

Now with any zoom or pan position, as soon as the box leaves the screen, it springs back to center.

Codepen updated:
https://codepen.io/MarsAndBack/pen/MWKzYPe?editors=1111

**Comment by SridharRamasami** [comment]
Hi TheMangoTrain,

I am trying to something similar to what you did 
Starting: Canvas with images a reference point P1 (100, 100).
Want: Animated 2x zoomed with P1 as the view center.

I am not able to get the animation + zoom + pan to work correctly.  I am taking your  canvas.setViewportTransform approach.

As the panX, panY and zoom change are all linear, I am getting the delta and applying it each of the panX, panY and zoom, but its not working correctly.  I believe my understanding of the transform is wrong.  The code that animates is below.  Thanks in advance.

    var zoom = canvas.getZoom();
    let start = 0.0;
    let end = 1.0;

    fabric.util.animate({
        startValue: start,
        endValue: end,
        duration: 500,
        onChange: function(midvalue) {
            let factor = midvalue/(end-start);
            console.log(factor);
            self.canvas.setViewportTransform([
                zoom, 
                0, 
                0, 
                zoom*(1+factor),      
                canvas.viewportTransform[4],       
                100*factor   
            ]);

            self.canvas.renderAll();
        },
        onComplete: function() {
            self.canvas.renderAll();
        }
    });
