### ISSUE TITLE
Different render output in Browser vs Node when using shadow on PNG with transparency

### ISSUE THREAD

**Issue by akshatmittal** [fabricjs/fabric.js#6470]
## Version
3.6.3

## Test Case
NA

## Information about environment
Node v14.2, Chrome 83.0.4103.116, Windows 10 (1909)

## Steps to reproduce
Fabric Object:
`{
      type: "circle",
      version: "3.6.3",
      originX: "left",
      originY: "top",
      left: 675,
      top: 136,
      width: 200,
      height: 200,
      fill: {
        type: "pattern",
        source: "http://fabricjs.com/assets/printio.png",
        repeat: "no-repeat",
        crossOrigin: "",
        offsetX: 0,
        offsetY: 0,
        patternTransform: [1, 0, 0, 1, 0, 0],
      },
      stroke: "#FFFFFF",
      strokeWidth: 0,
      strokeDashArray: null,
      strokeLineCap: "butt",
      strokeDashOffset: 0,
      strokeLineJoin: "miter",
      strokeMiterLimit: 4,
      scaleX: 1,
      scaleY: 1,
      angle: 0,
      flipX: false,
      flipY: false,
      opacity: 1,
      shadow: { color: "rgba(0,0,0,0.2)", blur: 10, offsetX: 0, offsetY: 0, affectStroke: false, nonScaling: false },
      visible: true,
      clipTo: null,
      backgroundColor: "",
      fillRule: "nonzero",
      paintFirst: "fill",
      globalCompositeOperation: "source-over",
      transformMatrix: null,
      skewX: 0,
      skewY: 0,
      radius: 100,
      startAngle: 0,
      endAngle: 6.283185307179586,
    }`

Importing the same in Browser renders the correct output by adding shadows to the actual image contents instead of the entire circle. Importing it in Nodejs applies shadow to the entire circle instead of the actual image.

## Expected Behavior
![image](https://user-images.githubusercontent.com/1667481/87887091-8f0d8600-ca3f-11ea-8e30-9a7a1f8910bb.png)
Output of using `shadow` in browser, which is correct since the image has alpha transparency.

## Actual Behavior
![image](https://user-images.githubusercontent.com/1667481/87887093-95036700-ca3f-11ea-878e-b26f03a1b364.png)
EXACT same JSON when imported to fabric in Nodejs

**Comment by akshatmittal** [comment]
Any comments on this?

**Comment by asturur** [comment]
Sorry for not commenting.
I have to put up my node setup and verify if i can fix it in node canvas.

**Comment by akshatmittal** [comment]
@asturur I would really appreciate that. I tried a bunch of things, but wasn't able to figure out the issue.

**Comment by akshatmittal** [comment]
Hey @asturur, did you get a chance to look into it? Is there anything I can help with, maybe with log files or something?

**Comment by asturur** [comment]
i m sorry i did not yet.

What i need to do is reproduce the issue in plain javascript with a clear list of rendering steps, find the order of operations that trigger node canvas problem, see if it is something i can fix or not.

**Comment by akshatmittal** [comment]
@asturur Here's a gist of the fabric data along with the code I'm using. hope that helps. https://gist.github.com/akshatmittal/3865cfdb5f569eff7109c9e51bc64031

**Comment by akshatmittal** [comment]
@asturur Do you happen to have any update?

I kinda changed how I was doing things and moved away from this library, but if this issue ever has a solution I'd like to come back to it.

**Comment by asturur** [comment]
i m still on vacation Akshat

**Comment by akshatmittal** [comment]
Oh, didn't know that. Enjoy your vacation @asturur!

**Comment by jhondge** [comment]
@asturur I got the similar issue with shadow, as I debug the code, I was figure out the source code in the `object.class.js` as the following:
```
var fabric = global.fabric || (global.fabric = { }),
      extend = fabric.util.object.extend,
      clone = fabric.util.object.clone,
      toFixed = fabric.util.toFixed,
      capitalize = fabric.util.string.capitalize,
      degreesToRadians = fabric.util.degreesToRadians,
      supportsLineDash = fabric.StaticCanvas.supports('setLineDash'),
      objectCaching = !fabric.isLikelyNode,
      ALIASING_LIMIT = 2;

``` 
In the nodejs environment, `objectCaching = !fabric.isLikelyNode` will be set false, so if we use the shadow on the browser it's got expect result, but in the nodejs `objectCaching` is false, so `shouldCache` method will return `false` and shadow will be apply to all `_objects` with `group`     

Expected - [Browser]
-----
![expect](https://user-images.githubusercontent.com/4192552/92091801-d4c1ba80-ee03-11ea-9199-ea4c4a7c9bed.png)

Actual - [Node-Canvas]
-----
![actual](https://user-images.githubusercontent.com/4192552/92091812-da1f0500-ee03-11ea-8777-5237e11563dd.png)

**Comment by asturur** [comment]
if you force caching on in node, does render as expected?

The caching differences needs to be solved anyway, we have to decide if groups are merely containers or provide isolation of drawing operations.

**Comment by jhondge** [comment]
> if you force caching on in node, does render as expected?
> 
> The caching differences needs to be solved anyway, we have to decide if groups are merely containers or provide isolation of drawing operations.

@asturur  thanks for your quick response,  does  you finished your vacation?

Yes, it's does work fine after `shouldCache` return true when object have `shadow`, but that's another issue is objectCaching will use cache canvas to render, the `svg` will be draw to context with the non-scaled graphic, so it's means that can't be scale up in PDF mode.

**Comment by asturur** [comment]
yes it will be drawn with draw image and create pdf that are not what you want.

How does pdf mode handle shadows anyway?

did you try something else like pdfkit with svg to
pdf extensions? not sure it can solve your problem.

is rendering on node a feature or a side effect of wanting to use nodecanvas pdf mode?

i m still out tho.
