### ISSUE TITLE
Pan canvas so active object is in center of viewport

### ISSUE THREAD

**Issue by TheMangoTrain** [fabricjs/fabric.js#6471]
Hi,

Using fabric.js, I'd like to pan the canvas so that the active object is centered (ideally center of object) in the viewport.

Sample code here:
https://codepen.io/MarsAndBack/pen/PoZXpWQ

Problems:

1. Can't get the proper coordinates for centering to work. It comes close, but is always off.

2. If hitting the blue button many times in a row, the canvas seems to pan multiple times in varying amounts, however after the first pan, the next pan requests should be static because the object was already centered in viewport (in theory).

Note: This is similar to a previously asked question, however in that case the post included an animation aspect and was more complex.

Posted on SO here: https://stackoverflow.com/questions/62998674/fabric-js-pan-canvas-so-active-object-is-center-in-viewport

**Comment by TheMangoTrain** [comment]
Ok I came up with a solution, see updated CodePen here:
https://codepen.io/MarsAndBack/pen/PoZXpWQ

As far as I can tell this correctly accounts for any pan/zoom state, and ultimately simply pans the canvas to set an object in a desired position relative to the viewport.

Such a function is handy to bring into focus an active object, like a text field being edited, especially on mobile devices.

Ultimately had to make use of aCoords to get correct transform.

**Comment by OPY-bbt** [comment]
v5.2.1

const obj = canvas.getActiveObject();

const zoom = canvas.getZoom();
const vCenter = canvas.getVpCenter();
const mObj = calcTransformMatrix();

const dx = vCenter.x - mObj[4];
const dy = vCenter.y - mObj[5];

canvas.relativePan(new fabric.Point(dx * zoom, dy * zoom));
