### ISSUE TITLE
Error with custom build for fabric v4rc1 [ Module not found: Can't resolve 'child_process' in '...node_modules/jsdom/lib/jsdom/living' ]

### ISSUE THREAD

**Issue by thobn24h** [fabricjs/fabric.js#6473]
## Version
4.0.0-rc.1

## Information about environment
Nodejs or browser?
v10.16.0

Which browsers?
All browser

## Steps to reproduce
1. Check out v4rc1 branch
2. Build with command line:
**node build.js modules=ALL exclude=node no-strict no-svg-export**
3. Out in the fabric dist folder:
fabric.js
4. Import fabric.js to next.js project
5. Get error while build:
./node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js
Module not found: Can't resolve 'child_process' in '/Users/thobn/DEVELOP/Project/node_modules/jsdom/lib/jsdom/living'

## Expected Behavior
Working normally without error

## Actual Behavior
Get error while build:
./node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js
Module not found: Can't resolve 'child_process' in '/Users/thobn/DEVELOP/Project/node_modules/jsdom/lib/jsdom/living'

![error_fabric_custom_build](https://user-images.githubusercontent.com/8949278/88287838-151a1d00-cd1d-11ea-9cef-62754e080ad8.jpg)

**But when install this version by npm & using in the next.js project, It's working normally without errors.**
yarn add https://github.com/fabricjs/fabric.js.git#v4rc1
--> In this branch, in folder dis --> fabric.js is still old version 3.6.1 ( not new one for the v4rc1 ) 
@asturur : please update this file

**Comment by asturur** [comment]
fabricJS package.json has some directive to tell compilers to avoid certain deps on browsers.
Can you try to use the npm version and then in your npm post install script do:

```bash
cd node_modules/fabric
... your custom build command
```

**Comment by thobn24h** [comment]
@asturur , 
I tried to custom build version "4.0.0-rc.1" many times but no lucky ( build successed but error when using in reactjs project )

I wan to use your new feature: controls api with react.js project.
Could you give me a pre-build of this version with full function ( included : Gestures module ) ?

Thank you in advance!

**Comment by asturur** [comment]
i m do not think the custom gesture module works yet
anyway if you install with npm, asking for the latest tag, and then you build in the nodule_module folder with a post install script it should work. For me it works.

**Comment by thobn24h** [comment]
@asturur ,
If it's not take your time, could you attach a pre-build version 4 in this post for me ?
Thank you very much!

**Comment by asturur** [comment]
fixed with #6491.
here you find a copy of it built: http://fabricjs.com/lib/fabric_with_gestures.js
