### ISSUE TITLE
Does fabric.js attempt to reduce the number of points?

### ISSUE THREAD

**Issue by tdiprima** [fabricjs/fabric.js#6474]
Dear Friends,

Let's say I draw a line.  A squiggle or something like that.  Does fabric.js behind the scenes attempt to reduce the number of points that compose that line?  Could you please let me know?

Thank you,
Tammy

**Comment by asturur** [comment]
In the free drawing brush there is a parameter that will try to do so, removing all the points that are less than one pixel distant from one to another. You can reduce that parameter to 0 for no semplification.
The parametner is called decimation and is default at 0.4 pixels i believe.

**Comment by tdiprima** [comment]
@asturur Thank you so much! 😄
