### ISSUE TITLE
Fabric image.setsrc() method creating canvas element with  zero width and height with latest chrome version 

### ISSUE THREAD

**Issue by pradeepthikande** [fabricjs/fabric.js#6475]
Fabric "image.setsrc()" method return the canvas element with  zero width and height with latest chrome version.

Problems occur when upgrading Chrome.
Other browsers have no problems at all.

When we use the setsrc method in fabric js image, the image getting disappeared onhover on the canvas image object.

Updated chrome version

chrome 84.0.4147.89 - issue found

## Steps to reproduce

1)Add the image on canvas

2)use the setsrc method of image in fabricjs to replace/update the image with new url

3)Hover on the  image now ., its getting disappeared.

## Expected Behavior

Onhover of the  image should appear.

## Actual Behavior

Image is disappearing.

**Comment by asturur** [comment]
Is a change in chrome since chrome 83 and has been fixed i believe with this commit here:
https://github.com/fabricjs/fabric.js/commit/b53f87f8bf4cfff2c2dcf518b407d8fa89cafb0f

Can you download the lastest version of the master branch and see if is fixed?
