### ISSUE TITLE
ERROR transform.actionHandler is not a function when using only Custom controls

### ISSUE THREAD

**Issue by CKitisak** [fabricjs/fabric.js#6478]
## Version
4.0.0-beta.12

## Test Case
https://jsfiddle.net/ckitisak/kzd6Lufa/

## Information
Let say I have create a circle object and remove all default controls by replacing them with 2 custom controls call "save" and "cancel". When I clicked on the cancel control sometimes the error `Uncaught TypeError: transform.actionHandler is not a function` appears on console log before arrives to `mouseUpHandler` callback of the custom control as you can see in the screenshot below so how to prevent the error like this?

for more information please see in [SO here](https://stackoverflow.com/questions/63068680/fabricjs-error-transform-actionhandler-is-not-a-function-when-use-only-custom-co)

## Steps to reproduce
1. click on Edit button
2. (optional) Move the object
3. click cancel control (red with x)
4. repeat step 1 - 3 (if error does not appear)

**Comment by asturur** [comment]
you should add the action handler as a noop.
We could embed it too, but yes, controls are supposed to have an action as of now.

Maybe we can add noop in the prototype and call it fixed?

**Comment by CKitisak** [comment]
@asturur Thank you for a quick reply. I'm not sure about what you have mentioned "noop". Would you please explain a little bit more or guided me where to change or update?

**Comment by asturur** [comment]
noop = no operation. Is an empty function.  `() => {}` or `function() {}`

Is also available from lodash with this name.

**Comment by CKitisak** [comment]
After I added noop actionHandler like below. the error seem to be gone now. Thank you.

```
new fabric.Control({
    x: 1,
    y: -1.5,
    offsetY: 16,
    cursorStyle: 'pointer',
    mouseUpHandler: cancel,
    actionHandler: ()=>{},
    render: renderIcon,
    cornerSize: 24
  });
```

**Comment by asturur** [comment]
We can fix the control prototype so that this is not necessary.

**Comment by asturur** [comment]
@CKitisak i verified and in the version rc1, this empty action handler already exist.
So we already fixed, but you were using beta12 instead of the newer one.

**Comment by CKitisak** [comment]
@asturur thank you I will switch to the rc1 version.
