### ISSUE TITLE
How to set minimum object size while resizing?

### ISSUE THREAD

**Issue by mspace** [fabricjs/fabric.js#6481]
I want to achieve minimum allowed object size at canvas. For this, I used below code (included in stackoverflow post):

https://stackoverflow.com/questions/63080354/how-to-set-minimum-object-size

It works, but there is a problem if user tries to resize the object from left-middle or top-middle control point. The object is moved. The lastGoodLeft is applied, therefore the object is moved. I should remember the min left position somehow?

```

    var canvas = new fabric.Canvas('canvas');

    var rect = new fabric.Rect({
      left: 50,
      top: 50,
      fill: 'transparent',
      stroke: 'black',
      strokeWidth: 5,
      width: 60,
      height: 70,
      strokeUniform: false,
      lockScalingFlip: true
    });
      
    canvas.add(rect);

    // getScaledWidth = width + strokeWidth
    var minWidth = 40;
    var minScaleX = minWidth / rect.getScaledWidth();

    var minHeight = 20;
    var minScaleY = minHeight / rect.getScaledHeight();

    rect.on('scaling', function(e)
    {
      if( this.scaleX <= minScaleX) {
        this.scaleX = minScaleX;
        this.left = this.lastGoodLeft;
      }

      if(this.scaleY <= minScaleY) {
        this.scaleY = minScaleY;
        this.top = this.lastGoodTop;
      }

      // we have to remember last left and top, otherwise object
      // will be moved to the right when left middle resize control is used
      this.lastGoodTop = this.top;
      this.lastGoodLeft = this.left;
    });

```

I can demonstrate this with a video: https://streamable.com/a7sy4f or in case streamable link fails: [Fabric min size](https://drive.google.com/file/d/1YxO5C2VCZVEp-AGMBEkhuQ9AhTN33O3u/view?usp=sharing)

I also tried to use **minScaleLimit**, but this does not work if you have rectangle with for example width: 100, height: 30.
What are some other alternatives to fully support min object size while resizing. 

Additionally I tried with **lockMovementX, lockScalingX**, but with no luck.

**Comment by asturur** [comment]
can you make a fiddle showing that minscalelimit  does not work? because that is the tool for the job in this case.

**Comment by mspace** [comment]
I'll provide you with the minScaleLimit example, later today. Thnx for fast response.
