### ISSUE TITLE
Custom controls is not clickable 

### ISSUE THREAD

**Issue by iamappmaker** [fabricjs/fabric.js#6482]
Tried custom control as giving in demo. Both delete and clone icon visible but not clickable.
I clicked the area around the icon, randomly at some point it worked so tried to do the same again but it is not working.
When i hold and drag it get scaled which is default behavior.

I am using : fabric 4.0.0-rc.1

**Comment by asturur** [comment]
The demo that is here: http://fabricjs.com/custom-control-render looks fine to me.
What is wrong?

**Comment by juzhiyuan** [comment]
Those 2 demos are not shown on Windows, when I click Edit, just shows empty codes.

**Comment by TheAlemazing** [comment]
Latest version of fabric, I got error "fabric.Control is not a constructor" is something wrong?

**Comment by asturur** [comment]
yes. Where do you get it from?
if you cloned here the repo you need to build it before using it.
On NPM is built already.

**Comment by TheAlemazing** [comment]
I got from npm. That's weird.

**Comment by CodeNinjaUG** [comment]
https://github.com/fabricjs/fabric.js/issues/8612 this error has been open please dont mark it as stale

**Comment by shashank-brightness** [comment]
I have custom control and somehow i managed to positioned it correctly however i am not getting how to make it whole clickable. Only part of it is clickable and this is also few times, not sure what is the logic behind it.
It is infect very very harder to understand how it renders and how to make it clickable in whole area and not just part of it.

```
const sizeSmallControl = new fabric.Control({
    x: -0.5,
    y: -0.5,
    cornerSize: 32,
    offsetY: -40,
    offsetX: 0,
    
    mouseUpHandler: () => {self.scaleObjectAsPerSize(note,size)},
    cursorStyle: 'pointer',
    render: self.renderIcon(sizeIcon),
    
});
note.setControlsVisibility({
    sizeSmallControl: true,
})
fabric.Object.prototype.controls.sizeSmallControl = sizeSmallControl;
```

```
renderIcon(icon) {
    return function renderIcon(ctx, left, top, styleOverride, fabricObject) {
        var size = this.cornerSize;
        ctx.save();
        ctx.translate(left, top);
        ctx.rotate(fabric.util.degreesToRadians(fabricObject.angle));
        ctx.drawImage(icon, 0, 0, size, size);
        ctx.restore();
    }
},
```

I just noted that even in custom control [demo ](https://codepen.io/Shashank_bhatt1/pen/dyxoWoo)also, whole area is not clickable which is not good.
