### ISSUE TITLE
Can't use fabricjs which build from v4rc1 with gestures module

### ISSUE THREAD

**Issue by thobn24h** [fabricjs/fabric.js#6483]
## Version
4.0.0-rc.1
## Information about environment
Nodejs or browser?
v10.16.0
Which browsers?
All browser

## Steps to reproduce
1. Install fabricjs from v4rc1 branch
2. Build with command line:
```
node build.js modules=ALL no-strict no-svg-export
```
3. import to next.js project and use

## Expected Behavior
Import and use fabricjs library normally.

## Actual Behavior
 --> have error:
ReferenceError: window is not defined

## Notes:
But when exclude **gestures** module from build command line: --> it's working.
```
node build.js modules=ALL exclude=gestures no-strict no-svg-export
```

## Need Help:
@asturur , please help me resolve this problem:
1.  Is gestures module not ready for 4.xx version ?
2. Is there any way to make "gestures" module to work on version 4.xxx ?

**Comment by asturur** [comment]
not yet, many internals changed and the gesture module needs to be adapted. There are open issues describing this
