### ISSUE TITLE
Vertical Alignment of textbox text

### ISSUE THREAD

**Issue by kylekirkby** [fabricjs/fabric.js#6484]
**Is your feature request related to a problem? Please describe.**
My custom textbox class would be even more awesome if it could manage the vertical alignment / rendering of text. @asturur - any ideas how this is possible? Could you possibly point me in the right direction for changing the start position that text is rendered at?

**Describe the solution you'd like**
A textbox property `verticalAlignment` with accepted values of `top`, `bottom` or `center`

**Describe alternatives you've considered**
Overriding the _render method of the textbox class to toggle the alignment of text to the center or top (default) / bottom.

**Additional context**

**Comment by asturur** [comment]
how the final textbox should look like? What this alignment should do? do you have an idea with a picture?
