### ISSUE TITLE
FabricJS Custom Checkbox Mecanism

### ISSUE THREAD

**Issue by WebDices** [fabricjs/fabric.js#6485]
I'm trying to work on a custom fabric js checkbox mecanism. I display some rectangles on the canvas, and then for each of the rectangle I have a checkbox image that appear and dissapear each time I click on it.

How could I know which object have the image on and off? I want to make an alert message with those objects. The rectangle that I'm displaying have the coordinates taken from a json.

This is the function with the image:

function drawCheckbox(left, top, width, height){
    var imgClass = new fabric.Image.fromURL('https://image.flaticon.com/icons/svg/33/33281.svg',function(img){
        img.width = width;
        img.height = height;
        img.left = left;
        img.top = top;
        img.set({
            hoverCursor: 'default',
            selectable: true,
            opacity: 0

        })
        img.on('mousedown', function(e) {
            if(e.target.opacity <= 0.5){
                e.target.opacity = 1;
            }else{
                e.target.opacity = 0;
            }
            canvas.renderAll();

        });
        canvas.add(img);
        canvas.renderAll();

    })
}

And this is the function for the rectangle:

function addRect(left, top, width, height, id) {
    const o = new fabric.Rect({
        width: width,
        height: height,
        fill: tableFill,
        stroke: tableStroke,
        strokeWidth: 2,
        shadow: tableShadow,
        originX: 'center',
        originY: 'center',
        centeredRotation: true,
        snapAngle: 45,
        selectable: true
    })

    const t = new fabric.IText(number.toString(), {
        fontFamily: 'Calibri',
        fontSize: 14,
        fill: '#fff',
        textAlign: 'center',
        originX: 'center',
        originY: 'center'
    })
    const g = new fabric.Group([o, t], {
        left: left,
        top: top,
        centeredRotation: true,
        snapAngle: 45,
        selectable: true,
        type: 'table',
        id: id,
        number: number
    })
    canvas.add(g)
    number++
    g.on('selected', function () {
        
    })

    canvas.hoverCursor = 'pointer';
    canvas.discardActiveObject();
    canvas.renderAll();
    return g;
}

**Comment by asturur** [comment]
Is hard to understand what you are trying to achieve or doing.
Please create  a working fiddle or codepen that recreates your use case.
