### ISSUE TITLE
Can the path object generated by the PencilBrush during mouseup be returned to the outside to customize some attributes?

### ISSUE THREAD

**Issue by linrz** [fabricjs/fabric.js#6486]
I am using fabricjs to build a canvas for multi-person collaboration.
When one of the users is free drawing, the point obtained during mousemove is transmitted to other clients for drawing at the same time.

I hope that the path object generated by PencilBrush or other brushes in `_finalizeAndAddPath` will be exposed to the outside world to customize some attributes such as setting id through `.set`.

It is too late to set the id in the `path:created` event, because the `id` of this element needs to be kept the same for all clients. Because I can’t use `canvas.contains` on other clients to determine the element to unify the `id`.

So I expect whether the newly created path object can be exposed to the outside world during `onMouseUp`？ https://github.com/fabricjs/fabric.js/blob/6c28f5a0b6d0fd9d30d338770fbacce8f419c69f/src/brushes/pencil_brush.class.js#L90

Looking forward to your reply, thanks very much.

**Comment by asturur** [comment]
HI @linrz ,  the problem could be solved in many ways, one of those is to add an event before the path gets added to the canvas.
But you are not really explaining why the `path:created` is late.
You say something around clients that is unclear.

**Comment by linrz** [comment]
Thank you for your ideas, I will try to add a before create event.😁

**Comment by asturur** [comment]
You can open a PR for it on fabricJS. is just an extra line of code for the project and maybe can help other people.
Look where `.fire('path:created')` is in the codebase.

Add a little bit before, before the canvas.add, another fire statement with something like `'before:path:created'` should be enough

**Comment by linrz** [comment]
Okay, before I planned to extend it as a monkey patch in my own project. 🤓

**Comment by asturur** [comment]
if i monkey patched my project in 2014 i would never have been a fabricJS contributor.
