### ISSUE TITLE
fabric-with-gestures 4.0.0-rc.1. Gestures not working

### ISSUE THREAD

**Issue by kamejoko2** [fabricjs/fabric.js#6487]
Hi.

I tested with 2.3.2 gesture very smooth on chrome mobile, safari. 
I tested with 3.6.3 gestures very lag and wrong position when scale object.
I tested with 4.0.0. rc1 all gestures are not work.

**Comment by NielsHamelink-web** [comment]
Do you have a sample of your code and an error that gets triggered?

**Comment by TheMangoTrain** [comment]
To be more explicit, do you mean multi-finger gestures?

Could be the same as this:
https://github.com/fabricjs/fabric.js/issues/6377

**Comment by asturur** [comment]
fixed with #6491

**Comment by kamejoko2** [comment]
> Do you have a sample of your code and an error that gets triggered?
> 
> Also have you tried looking into the performance of you PC setup (RAM)?

Hi NielsHamelink-web

When I get triggered (pin 2 finger) to scale object on ipad and tablet android, version 2.3.2 scale very smooth.
On 3.6.1 so lag and object scaled random wrong postion or ranged out area of canvas.
4.0.0-rc.1 - 3.6.3 (pin 2 finger) no happening
