### ISSUE TITLE
Overriding click events

### ISSUE THREAD

**Issue by NielsHamelink-web** [fabricjs/fabric.js#6488]
## Version
3.6.0

## Information about environment
**Browser**: Chrome

## Steps to reproduce
Built the circles to an array so not every circle has not the same variable assigned but did not change anything.

## Expected Behavior
Every circle has it's own click event assigned, but it looks like that the object "circle" has 1 click event.
So if you make multiple circles and make them clickable with all it's own click event (or with a property like an ID). Sample code:
```
for (var key in data.items) {
    var circle = new fabric.Circle({
        'id': id,
        left: x_coord,
        top: y_coord,
        fill: '#015790',
        radius: 7,
        strokeWidth: 3,
        stroke: "#fff",
    });

    circle.on('mouseup', function(options) {
        console.log(id);
    }

    canvas.add(circle);
}
```

## Actual Behavior
When you click on 1 of the circles only the last event assigned gets fired.

**Comment by juzhiyuan** [comment]
I think you have to get id from options, not from the fr loop

**Comment by juzhiyuan** [comment]
https://davembush.github.io/why-does-javascript-loop-only-use-last-value/

**Comment by NielsHamelink-web** [comment]
> I think you have to get id from options, not from the for loop

Thanks, indeed this was the issue.

http://jsfiddle.net/56douw0y/
