### ISSUE TITLE
LoadFromJSON is used to redraw the drawing under different resolutions is not correct, please solve!!!!

### ISSUE THREAD

**Issue by lyxisblog** [fabricjs/fabric.js#6489]
This is the graph drawn under iPad Pro:
<img width="399" alt="7a9dbaaf11628071a8e9af1af7d4648" src="https://user-images.githubusercontent.com/46701017/88944152-f7215f00-d2be-11ea-9cae-a8f30944ff96.png">

When I save drawing in IP 7 or better than iPad Pro:
<img width="338" alt="b0778ba4adfd105454998dcfb48b966" src="https://user-images.githubusercontent.com/46701017/88943963-b6294a80-d2be-11ea-9b98-c222f3b679f1.png">

On the contrary, how to draw and save under the lower resolution of IP 7? If the resolution is larger than IP 7, there will be problems in redrawing. Could you please provide a solution?
The good person life peace, hundred poison not invade!!

**Comment by juzhiyuan** [comment]
Please use English here, deepl.com is your choice.

**Comment by lyxisblog** [comment]
> 请在此处使用英语，deepl.com是您的选择。

Thank you for your reminding. I have already used English. Could you please help me?

**Comment by TheMangoTrain** [comment]
My first guess is you need a listener for viewport size changes, and then resize the canvas. By default, any canvas stays in a fixed pixel position that it was first initiated in. You have to resize the canvas again of the viewport (or other container) changes size.

Something like:

 ```
window.addEventListener('resize', () => {
    this.setNewCanvasSize()
})

resizeCanvas(target) {

            let canvasContainer = document.getElementById("myContainer")
            let containerWidth   = canvasContainer.offsetWidth
            let containerHeight  = canvasContainer.offsetHeight
   
            canvas.setWidth(containerWidth)
            canvas.setHeight(containerHeight)

            // And maybe you want to do this too... re-center all of your objects at once (as a big group)
            let objects = canvas.getObjects()
            let selection = new fabric.ActiveSelection(objects, { canvas: canvas })
            selection.center()
            selection.destroy()
            
            canvas.requestRenderAll()
            canvas.calcOffset()

        },
```

**Comment by lyxisblog** [comment]
> 我的第一个猜测是您需要一个侦听器来更改视口的大小，然后调整画布的大小。默认情况下，所有画布都停留在最初启动时处于固定像素位置。您必须在更改视口（或其他容器）的大小时再次调整画布的大小。
> 
> 就像是：
> 
> ```
> window.addEventListener('resize', () => {
>    this.setNewCanvasSize()
> })
> 
> resizeCanvas(target) {
> 
>            let canvasContainer = document.getElementById("myContainer")
>            let containerWidth   = canvasContainer.offsetWidth
>            let containerHeight  = canvasContainer.offsetHeight
>   
>            canvas.setWidth(containerWidth)
>            canvas.setHeight(containerHeight)
> 
>            // And maybe you want to do this too... re-center all of your objects at once (as a big group)
>            let objects = canvas.getObjects()
>            let selection = new fabric.ActiveSelection(objects, { canvas: canvas })
>            selection.center()
>            selection.destroy()
>            
>            canvas.requestRenderAll()
>            canvas.calcOffset()
> 
>        },
> ```



> 我的第一个猜测是您需要一个侦听器来更改视口的大小，然后调整画布的大小。默认情况下，所有画布都停留在最初启动时处于固定像素位置。您必须在更改视口（或其他容器）的大小时再次调整画布的大小。
> 
> 就像是：
> 
> ```
> window.addEventListener('resize', () => {
>    this.setNewCanvasSize()
> })
> 
> resizeCanvas(target) {
> 
>            let canvasContainer = document.getElementById("myContainer")
>            let containerWidth   = canvasContainer.offsetWidth
>            let containerHeight  = canvasContainer.offsetHeight
>   
>            canvas.setWidth(containerWidth)
>            canvas.setHeight(containerHeight)
> 
>            // And maybe you want to do this too... re-center all of your objects at once (as a big group)
>            let objects = canvas.getObjects()
>            let selection = new fabric.ActiveSelection(objects, { canvas: canvas })
>            selection.center()
>            selection.destroy()
>            
>            canvas.requestRenderAll()
>            canvas.calcOffset()
> 
>        },
> ```

millions of thanks，I'll give it a try，you setNewCanvasSize() function Can you also provide some，thanks again！

**Comment by asturur** [comment]
i did not get through all the discussion, but did tou try using the zoom?

on lodFromJSON, make s temporary active selection with all objects, and get the size of it ( width, height, top and left), then you can destroy the selection.

then find the zoom ratio that let you fit the selection in the canvas size, and zoom accordingly, pan with top and left so that you can center the canvas view on the objects

**Comment by CrandellWS** [comment]
I gave this answer at https://stackoverflow.com/a/63511300/1815624
```

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<canvas id="canvas" width="1000" height="1000"></canvas>

    

<script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/4.0.0/fabric.min.js"></script>
   <script>
  var canvas = new fabric.Canvas('canvas');
  canvas.add(new fabric.Circle({ radius: 30, fill: '#f55', top: 100, left: 100 }));

  canvas.item(0).set({
    borderColor: 'gray',
    cornerColor: 'black',
    cornerSize: 12,
    transparentCorners: true
  });
  canvas.setActiveObject(canvas.item(0));
  canvas.renderAll();

 
function rescale_canvas_if_needed(){
    var optimal_dimensions = [400,400];
    var scaleFactorX=window.innerWidth/optimal_dimensions[0];
    var scaleFactorY=window.innerHeight/optimal_dimensions[1];
    if(scaleFactorX <  scaleFactorY && scaleFactorX < 1) {
        canvas.setWidth(optimal_dimensions[0] *scaleFactorX);
        canvas.setHeight(optimal_dimensions[1] *scaleFactorX);
        canvas.setZoom(scaleFactorX);
    } else if(scaleFactorX >  scaleFactorY && scaleFactorY < 1){
        canvas.setWidth(optimal_dimensions[0] *scaleFactorY);
        canvas.setHeight(optimal_dimensions[1] *scaleFactorY);
        canvas.setZoom(scaleFactorY);
    }else {
        canvas.setWidth(optimal_dimensions[0] );
        canvas.setHeight(optimal_dimensions[1] );
        canvas.setZoom(1);
    }

    canvas.calcOffset();
    canvas.renderAll();
}

 
function handle_resize(){
    $(".canvas-container").hide();
    rescale_canvas_if_needed();
    $(".canvas-container").show();               
     
}
var resizeId = null;
$(function() {
    $(window).resize(function() {
        if(resizeId != null)
        clearTimeout(resizeId);
        resizeId = setTimeout(handle_resize, 500);
     });
    console.log( "ready!" );
    /* auto size it right away... */
    resizeId = setTimeout(handle_resize, 500);
});
    </script>
```
