### ISSUE TITLE
Run React components with fabricjs in storybook error

### ISSUE THREAD

**Issue by fa10** [fabricjs/fabric.js#6490]
Hi,

I have project, where i created some components on top of fabricjs. It is a React project where I added storybook to showcase the components that uses fabricjs. I include the `fabric-pure-browser` package from npm. 

The issue i face is this.

```javascript
TypeError: Cannot read property 'fabric' of undefined
```

It seems like in the package `fabric-pure-browser` and the file `dist/fabric.js` on line `3341` the global is `undefined` in the attached code below.

```javascript
var fabric = global.fabric || (global.fabric = { }),
      extend = fabric.util.object.extend,
      clone = fabric.util.object.clone,
      toFixed = fabric.util.toFixed,
      parseUnit = fabric.util.parseUnit,
      multiplyTransformMatrices = fabric.util.multiplyTransformMatrices,
```
Hope to hear from you guys.

**Comment by juzhiyuan** [comment]
Why not import fabric from this module?

**Comment by asturur** [comment]
What happen if you try to import the normal module?
I do not exactly know what changes are done to to fabric in that module.
On npm we also publish a suffixed `-browser` version (`3.6.3-browser`)
Did you try that?

With what are you packaging?

**Comment by juzhiyuan** [comment]
Would better provide a jsfiddle or trying to import it from normal module.

**Comment by fa10** [comment]
@juzhiyuan @asturur I tried with both from the suffix `3.6.3-browser` and from also directly from the `fabric`. 

So storybook uses `webpack` for building and transpiling. What I can see is that, `fabric` is depending on the global (window) variable, and it seems not to be there when it tries to load the `fabric` from it.

**Comment by asturur** [comment]
in the repo fabricjs-webpack in this organization there is a sample config for building with normal fabric in webpack.

**Comment by fa10** [comment]
> in the repo fabricjs-webpack in this organization there is a sample config for building with normal fabric in webpack.

@asturur can you provide a link to that?

**Comment by asturur** [comment]
Yes i can, https://github.com/fabricjs/fabricjs-webpack, but was really one click away from this page.

`in the repo fabricjs-webpack in this organization ` was this sentence unclear? I try my best when answering from mobile phone, i cannot really go around and pick up links because with the pone is a pain.

**Comment by fa10** [comment]
@asturur can you for your responses it did not help either. It seems like the it is depending on a global variable that is not being defined...

**Comment by asturur** [comment]
i do not know how to help, i m packaging normal fabric in webpack with no problems.
