### ISSUE TITLE
Panning breaks ability to select objects

### ISSUE THREAD

**Issue by Nico321** [fabricjs/fabric.js#6493]
## Version
3.6.1

## Test Case
http://jsfiddle.net/6x2z5Ljd/

## Information about environment
node version v14.5.0
Chrome 64.0.4147.105

## Steps to reproduce

1. Select both elements
2. Drag in any direction using the ALT-key. Make sure to have the cursor on one of the objects, so selection does not get cleared.
3. Try to deselect one of the objects using the SHIFT-Key and click.

## Expected Behavior
The clicked object should be deselected.

## Actual Behavior
The object is not deselected. It is possible to deselect the object by SHIFT-clicking clicking on its original (before dragging) position.

**Comment by asturur** [comment]
seems broken to me indeed.
