### ISSUE TITLE
Fabric. Js function needs, please kneel down to ask the boss to help solve ~~~ (can give meters)

### ISSUE THREAD

**Issue by lyxisblog** [fabricjs/fabric.js#6495]
Function screenshots are as follows:
1: Similar to the code rule function, both sides of starting point - to node have arrow indication after starting drawing.Cut text (meters can not calculate can edit fill in line).
![1](https://user-images.githubusercontent.com/46701017/89293652-d5debb00-d690-11ea-971d-5b3f51e18650.jpg)
2: Text input function, the first is to write text with a box, the second is with a box on the right side of a line point, line point can be dragged to adjust the length;
![2](https://user-images.githubusercontent.com/46701017/89293699-e7c05e00-d690-11ea-9f93-13dca41f0cbd.jpg)
3: Polygon drawing is to draw the graph drawn by the user by clicking and selecting. It belongs to PS steel plate tool, and the corresponding graph can be drawn after clicking the node from the starting point.
![3](https://user-images.githubusercontent.com/46701017/89293718-f3ac2000-d690-11ea-8ad7-7de5e02e0f51.jpg)
4: Pentagram drawing (these are all algorithms...The circle logo and the direction logo are all the corresponding graphics as shown in the figure, except that the A can be edited is the text box, and the arrow of the direction logo can be adjusted by dragging.
![4](https://user-images.githubusercontent.com/46701017/89293749-01fa3c00-d691-11ea-9d78-2d197f175378.jpg)
Kneel for the big guys to help solve this problem, the project is anxious to on-line, kneel for the big guys to help, paid, please please please.Thank you. Thank you. Thank you. Thank you. Thank you.
Good person life peace ~ good person life peace ~ good person life peace ~

**Comment by juzhiyuan** [comment]
Please keep this issue simpler.

**Comment by melchiar** [comment]
Yes, please follow the issue template and use a  title that summarizes the bug. Be sure to include any relevant example code and a clear explanation of the problem.

**Comment by asturur** [comment]
To me seems a long series of 'how do i do this?'
Am i right?

**Comment by gxlinhai** [comment]
哥们，你是用是百度翻译的吗？哈哈

**Comment by juzhiyuan** [comment]
> 兄弟，你是用是百度翻译的吗？哈哈

Please use English here, thanks.

deepl.com would help you.
