### ISSUE TITLE
Can the path object generated by the freeDrawingBrush be converted to a polygon object?

### ISSUE THREAD

**Issue by tdiprima** [fabricjs/fabric.js#6496]
I let user draw a line around features on the canvas image.  I'd like to convert that line to a polygon object, so that I can have the array of points.  Is this possible yet?

Question on [stackoverflow](https://stackoverflow.com/questions/48653048/convert-a-path-to-a-polygon) from 2-1/2 years ago, offers a workaround.  But I was wondering if 4.0.0-rc.1 has a real solution?

Like:
```
canvas.on("path:created", function(e) {
    let lineObj = e.path;
    // convert line to polygon
    let polyObj = lineToPoly(lineObj); // user will pass line object
    // then i get the points... "points":[{"x":550,"y":450},{"x":455,"y":519},{"x":491,"y":631},{"x":609,"y":631},{"x":645,"y":519}]

    // OR
    // JUST convert the coordinates
    let oldCoords = e.path.path;
    let newCoords = convertCoords(oldCoords);
});
```

Thanks,
Tammy

**Comment by juzhiyuan** [comment]
Please refer to this one https://github.com/fabricjs/fabric.js/issues/100#issuecomment-665941606

**Comment by tdiprima** [comment]
@juzhiyuan Cool! Thanks!

**Comment by tdiprima** [comment]
p.s. @juzhiyuan I looked at https://yqnn.github.io/svg-path-editor/.  Very nice!  👍

**Comment by asturur** [comment]
Ideally you can create a polyline brush, seems to make more sense.

**Comment by tdiprima** [comment]
Hi @asturur, thank you for responding.  I'm looking thru fabric.js 4 code, and I see [Polyline](https://github.com/fabricjs/fabricjs.com/blob/gh-pages/lib/fabric4.js#L17990-L18001) as a line object, but I don't see it as a Brush style.  I'm having a lot of trouble finding an example of it as a brush style.  Could you please show me?

**Comment by tdiprima** [comment]
@asturur, oops never mind.  I see what you mean.  Thanks.

**Comment by asturur** [comment]
If you want to create your own brush i can help you, you should start from the pencil source code that is similar to what you need.

**Comment by tdiprima** [comment]
Ok, thank you!

**Comment by asturur** [comment]
i gave a quick look to the fiddle.
If the first part works, transform a path to polygon, why you do not remove it? It makes unnecessary noise on the codepen.
You have a codepen from fabricjs.com that will let you edit a polygon, in having a look at that codepen you may have missed something, just look twice. Can you replicate the official codepen in your codepen? If yes then you must be able to connect to your polygon, if no, we need to figure out why.

**Comment by tdiprima** [comment]
I fixed it.
https://codepen.io/tdiprima1/pen/MWybQOr

And yes, I would remove the path drawing, but for testing purposes, I left it.  I wanted to be absolutely sure that I was re-creating it.

I ended up re-writing the code.  I cleaned it up A LOT.

Thank you very much for looking at this. 🙏

**Comment by tdiprima** [comment]
Also, you know how we were discussing that you can't convert a Path to a Polygon without there being a bazillion points?  I did a small hack.  I only keep every 10th point, and create the polygon with that.  So far it works, I hope it will always work. 🤞

**Comment by asturur** [comment]
There is a parameter in the brush that will do that for you, is called `decimate` and it represent the minimum distance for a point from the previous, in order to be kept. Also, you should create a polygon brush instead of using the pencil brush and then convert. I think you can create one reading the pencilbrush and modify the code.
