### ISSUE TITLE
Can fabric.js coordinate calculation add background offset?

### ISSUE THREAD

**Issue by linrz** [fabricjs/fabric.js#6498]
I created an infinite canvas, by changing the offset of the background image to create a infinite scrolling effect.

![image](https://user-images.githubusercontent.com/33575974/89434017-9f2ea080-d775-11ea-802e-5324cad6ba4c.png)

I found that the origin of the coordinate system of the entire canvas is (0, 0) at the upper left corner.

If I scroll 500px to the left and use pencilBrush to paint, `canvas.backgroundColor.offsetX` is `-500`.
But when drawing with pencilBrush, his points are still the coordinate origin (0,0) in the upper left corner, not (-500,0), so when the mouse moves, the coordinates added to `pencilBrush._points` should all be minus 500.

![image](https://user-images.githubusercontent.com/33575974/89434169-ce451200-d775-11ea-9c8a-24e4625c819d.png)

I tried to override the `pencilBrush.addPoint` method and add the background offset in this method, as shown in the following code. 
![image](https://user-images.githubusercontent.com/33575974/89434379-0fd5bd00-d776-11ea-967e-a7011c1cb07a.png)

But when the mouse is upped and the path is added to the canvas, still not up to expectations, it is added to the left of the current window.

So I would like to ask if fabric.js can support changing the origin of the coordinate system? Hope it can be associated with the background offset.

I am a rookie in this field and I look forward to your reply, thank you very much.😁

**Comment by asturur** [comment]
If you want to use the infinite canvas, you have to use the proper tool, the viewportTransform.

Why aren't you using that?

**Comment by linrz** [comment]
Awesome, I solve it! Thanks very much.

**Comment by juzhiyuan** [comment]
> Awesome, I solve it! Thanks very much.

Hi @linrz, would you like to share your codes on jsfiddle or here? thanks!
