### ISSUE TITLE
Fabric on Android

### ISSUE THREAD

**Issue by sheriffMoose** [fabricjs/fabric.js#65]
First time I tried it was unsuccessful ,, I'm developing an application that depends mostly on alot of drag and drop action ... so it was too slow ,, suddenly I don't know why it acted fast ,, but still there's a problem : when dragging any object it moves ok but the original object position still filled with the object , it doesn't go until i touchmove on any empty space ,, so what's the problem?

**Comment by kaushikshamantha** [comment]
same prob.. any solution .. im using latest version!
