### ISSUE TITLE
4.0.0-release(Controls)how to custom cursorStyleHandler with my own png image or css class.

### ISSUE THREAD

**Issue by bulolo** [fabricjs/fabric.js#6502]
```
.myCursorStyle{
	width:20px;
	height:20px;
	background:red;
	
}
```

```
objectControls.mtr = new fabric.Control({
    x: 0,
    y: -0.5,
    actionHandler: controlsUtils.rotationWithSnapping,
    cursorStyleHandler: controlsUtils.rotationStyleHandler,
   // cursorStyle:"myCursorStyle",
    offsetY: -40,
    withConnection: true,
    actionName: 'rotate',
  });
```

![image](https://user-images.githubusercontent.com/10026498/89546400-2728af00-d837-11ea-86cd-4bd533d0955f.png)

how to custom my own cursorStyleHandler or cursorStyle.
i want to custrom mtr controls cursor with my own png image.
i don't want use  "crosshair"

codepen:https://codepen.io/bulolo/pen/LYGrpoJ?editors=0011

**Comment by juzhiyuan** [comment]
Could those links[1][2] help you?

[1] https://stackoverflow.com/questions/40881471/fabric-js-custom-cursor-style
[2] http://fabricjs.com/customization

**Comment by asturur** [comment]
hi @bulolo , the line you underlne says `Css cursor`.
The cursor has to be a valid CSS one.
I'm not sure a PNG is a valid cursor, i know .ico files and svg files are fine in many browsers.

**Comment by bulolo** [comment]
@asturur @juzhiyuan 

thanks,
i still can't use my custom cursor,
is that right below

```
defind my fireCursor cursor

.fireCursor {
   cursor: url(http://cur.cursors-4u.net/food/foo-1/foo98.cur), auto;
}

objectControls.mtr = new fabric.Control({
    x: 0,
    y: 0.5,
    cursorStyle: "fireCursor",  // is that right
});
```

**Comment by asturur** [comment]
because `fireCursor` is the name of a css class, not a valid css cursor.

Your cursorStyle needs to be `cursorStyle: "url(http://cur.cursors-4u.net/food/foo-1/foo98.cur), auto",`

**Comment by bulolo** [comment]
@asturur 

i make a test on https://codepen.io/bulolo/pen/LYGrpoJ?editors=1100

```
<div class="test">cursor</div>


.test {
    background:gray;
    width:200px;
    height:200px;
 cursor:url(http://www.javascriptkit.com/dhtmltutors/cursor-hand.gif), auto;
}
```

finally, the cursor change to the image cursor.


but in fabricjs, is disable. nothing change

```
cursorStyle: "cursor:url(http://www.javascriptkit.com/dhtmltutors/cursor-hand.gif), auto"
```

**Comment by asturur** [comment]
i have seen it working.... what did i do?

**Comment by asturur** [comment]
well it requires some extra eye, i m not sure is fixable. If you follow the code internally is very simple.
It just set the style property to that value.

**Comment by bulolo** [comment]
@asturur  gif
![2020-08-07 16 43 41](https://user-images.githubusercontent.com/10026498/89627346-4b36cf80-d8cd-11ea-9256-5c92ec1ab48f.gif)

**Comment by bulolo** [comment]
Is there an fix on 4.1.0

**Comment by asturur** [comment]
no or the issue would be closed. Could also be not fixable.

**Comment by asturur** [comment]
will be closed after proper investigation
