### ISSUE TITLE
Version 4 new gradient options format

### ISSUE THREAD

**Issue by GreenFootballs** [fabricjs/fabric.js#6510]
The changelog for version 4 notes that the options format for creating a Gradient object is "slightly different" than the old setGradient() function, but I can't figure out the correct way to do the colorStops. The Kitchen Sink example page also fails on the "Gradientify" button.

I tried passing the Gradient constructor an array of objects, each with offset and color properties, but that doesn't work either.

Can you please post an example of the correct format for the colorStops option?

**Comment by asturur** [comment]
Sure! i have to update kitchensink to work on 4.0 anyway and some old demos/docs too. That is why the website is still running on 3.6.3.

```js
var colorStops = [{ offset: 0, color: 'blue', opacity: 1 }, { offset: 0.5, color: 'red', opacity: 0.5 }, { offset: 1, color: 'rgba(0, 255, 0, 0.8)' }]
var myGradient = new fabric.Gradient({ colorStops: colorStops });
```

**Comment by GreenFootballs** [comment]
Hmm, I could swear I tried that. Is the opacity property required? Maybe I left that out.

**Comment by GreenFootballs** [comment]
No, it's still not working even with the opacity property. [Here's a Codepen example.](https://codepen.io/green_footballs/pen/poyjzvX?editors=0010)

Maybe there's a problem applying it to a stroke instead of a fill?

**Comment by asturur** [comment]
https://jsfiddle.net/k873e51t/

this is a fiddle with the stroke demo, minimal.

Compared to your codepen the coords format is different, and likely the cause of the problem.

In your codepen there is a lot of stuff going on that is not strictly gradient related, i m not sure what are you trying to render.

Consider that the gradient has also now a units property that let you specify if the coords are relative to the object size or absolute, i m not sure if that can help you in your custom logic.

**Comment by GreenFootballs** [comment]
The other stuff is to calculate the angle of the gradient, to follow the slope of the line.

**Comment by GreenFootballs** [comment]
Got it! The coordinates are now an object with the 'coords' key. That's the difference from the old setGradient() function.

[The fixed Codepen.](https://codepen.io/green_footballs/pen/poyjzvX?editors=0010)

**Comment by asturur** [comment]
I m not sure about your use case, but the gradient coords are always relative to object center, so a gradient that follow a line always start from -width/2, -height/2 and ends at width/2, height/2, with changing + and - depending in which corner the line starts. Does this information helps with your calculation? i see they works, i also see there is a lot of code there, not sure if you are looking for simplification opportunity.

**Comment by GreenFootballs** [comment]
Hmm, thanks for that tip. I'll check the logic and see if this can simplify the code.
