### ISSUE TITLE
Snap shapes to other shapes

### ISSUE THREAD

**Issue by arbalali** [fabricjs/fabric.js#6513]
I'm trying to implement this feature using Fabric.
This is a demo of this feature by Konva.js.
https://konvajs.org/docs/sandbox/Objects_Snapping.html
Anyone can help to implement it using Fabric?

**Comment by juzhiyuan** [comment]
https://gist.github.com/rlingineni/a77d4e7a3fcc2a1beb499baefa7a7b89

**Comment by asturur** [comment]
@arbalali i checked the link you posted, has all the  process described in the code. You should explain what part is unclear to you. What did you try? where did you stop?

A generic 'help me do this' usually receive little attention.

**Comment by CrandellWS** [comment]
he wants you to do it for him... I as well want that at the moment as my focus is elsewhere but later I may choose to try to implement this...that is me voting for this as a feature...
