### ISSUE TITLE
Trying to reduce impace of clipPath on blurryness

### ISSUE THREAD

**Issue by niels-van-den-broeck** [fabricjs/fabric.js#6515]
**Is your feature request related to a problem? Please describe.**

Right now x and y scale are separately handleable for objects. On the canvas this is not the case.
We are in a position where we render our canvas in a large format to then scale it back to fit on the screen. The zoom causes our images width and height times the zoomFactor to not be a whole number. Since the images have clipPaths, they need objectCaching. The _cacheCanvas's of our images look fine. The actual canvas implementation seems to be less sharp due to the pixel differences.
Allowing to scale the x and y axis separately would allow us to keep our width and height of our content to be whole numbers at any given time. Which would remove the inaccuracies

![Screen Shot 2020-08-12 at 4 18 56 PM](https://user-images.githubusercontent.com/39048448/90026452-9844e800-dcb7-11ea-8002-908db3d5c644.jpg)
![Screen Shot 2020-08-12 at 4 19 03 PM](https://user-images.githubusercontent.com/39048448/90026457-9a0eab80-dcb7-11ea-880b-e0903df7585f.jpg)

**Describe the solution you'd like**

Allow functions such as zoomToPoint, setZoom, etc to allow scaleY as a param. Using defaults, this change could be made in a non breaking way.

**Describe alternatives you've considered**

What I would do right now is do the viewport transformations myself. However I fear this would result in issues in other parts of the library. At first glance, my first concern is the getZoom function on StaticCanvas, which returns the x scale.

**Additional context**

If this is possible, I would certainly be willing to help implementing it.

**Comment by asturur** [comment]
Are you sure that x/y scaling will solve your issue?
You can actually experiment with it manually changing canvas.viewportTransform[0] and canvas.viewportTransform[3]. But i doubt will fix your blurriness problem.

So your _cacheCanvas is sharp, but is not sharp anymore when drawn in the canvas?

**Comment by niels-van-den-broeck** [comment]
I am pretty sure. I will try to setup an example but it's not an easy one to setup or explain via text

**Comment by niels-van-den-broeck** [comment]
The probleem I see at first glance with using the viewportTransform is that other parts of the library seem to rely on getZoom, which for now only take viewportTransform[0] into account.

**Comment by asturur** [comment]
in general the viewport transform is made to let you pan, zoom and rotate ( not yet ) your view. Is not meant to stretch your drawings or correct blurryness.

**Comment by niels-van-den-broeck** [comment]
That is correct. But by default zooming is allowed on 2 different axis when using ctx.scale, which is blocked off in fabricjs.

I suppose there is no way to set up some kind of call about this? I have a lot of things which I simply can not show without putting an immense amount of work into a sandbox environment. And our application isn't accessible without a proper license.

**Comment by asturur** [comment]
i m going on holiday in 3 days, for 2 weeks, and i m full up to the head of things to do.
We have to talk about this in september i guess.

Still sounds super weird to me that a cache that is not blurry,becomes blurry for incorrect placement ( this is a limitation and i know is true ) but then can be fixed changing the scale of one axis.

When created, the cache takes in account also canvas zoom, so if you change the zoom, the cache gets updated at the next render, and the problem you had with the different scale will appear again.

I'm really lost about how this can be explained.

**Comment by niels-van-den-broeck** [comment]
Problem is that the actual size of the image on the canvas is not a whole number. Cache canvas rounds the width/height as far as I can see since html elements can not get fractals as their height/width. So the size on the canvas is not completely equal to the size on the cache canvas at first glance.

**Comment by asturur** [comment]
So the cache canvas is rounded of course to the nearest integer, but there is always plenty of extra space around it ( 10% if i remember correctly )

Then the cache canvas is drawn on the main context in the position it should go, removing the scale of both object and zoom, that are included in the canvas size. so in THEORY you should have always a 1:1 match of pixels on canvas with cache on, but what could happen is that you have an offset of less than one pixel ( causing blurriness ). Ideally the offset could be countered, that with your application could be fine, while could be a problem for other.

**Comment by niels-van-den-broeck** [comment]
You are absolutely right :) Fractal offsets seem to be the underlying issue. I have setup an environment which confirms this. https://codesandbox.io/s/gallant-mestorf-y4jtw?file=/src/index.js
If you set the vpt to a whole number, the issue seems to be gone. However, this does feed into our need to be able to zoom on 2 different axis I think.

Problem is that the offsets are hard to guarantee. 
What we have is an application where we show books online. Books consist of pages which are images. 
these images are too large. They get rendered on the screen, and then the canvas is zoomed out. So the images get fit to the proper size of the canvas which looks like this. 
![Screen Shot 2020-08-18 at 9 08 11 AM](https://user-images.githubusercontent.com/39048448/90481681-75d92180-e132-11ea-9faa-1951818afe2b.jpg)

The left book page should always be fine since we transform our viewport so that our default 0/0 point is the top left of the left page. However, if we can't guarantee that the width of 1 page is a whole number after zooming, I don't see how we can fix the left position of the second page.

Also, as a heads up, the issue is more prevelent on non-retina screens.

On a side note: since this doesn't seem to affect images without clipPaths, is this something that we could take a look at? I surely am willing to take a look at the source code if you'd be willing to give some pointers

**Comment by asturur** [comment]
i was playing with the codepen
![image](https://user-images.githubusercontent.com/1194048/90504993-31f61480-e152-11ea-9d14-fda67b23c553.png)

This is the cacheCanvas of the image, after i did a bit of reveal.
Isn't as sharp as it could be.
On the canvas is similar
![image](https://user-images.githubusercontent.com/1194048/90505075-5520c400-e152-11ea-99c7-343cca4e6602.png)

( i removed the background image because otherwise i couldn't see anything.

There are a couple of things to take in consideration that may help you:
If you have a big image, and you zoom out, drawImage will do the resize work with nearest neighbour.
Can you keep zoom untouched and resize the images?

clippath cache using zoom

![image](https://user-images.githubusercontent.com/1194048/90505527-0de70300-e153-11ea-9471-4688089b2b27.png)

clippath cache using resize filters

![image](https://user-images.githubusercontent.com/1194048/90506420-8ac6ac80-e154-11ea-9d54-1572b48f7389.png)

and this is how i see it on the canvas:
![image](https://user-images.githubusercontent.com/1194048/90506486-a7fb7b00-e154-11ea-9ae5-192f230580fe.png)

All non retina

**Comment by niels-van-den-broeck** [comment]
First of all. Thank you very much for putting in so much work to help. It is greatly appreciated.

Problem for us with keeping zoom untouched is that we have loads of functionality atop these pages which has to move along with the image. 
So basically, changing this would affect our entire application and I think would require a rewrite of any functionality regarding the canvas. Also, it would break the currently stored drawings for our end users which get stored in JSON format since they are drawn on a smaller zoom level so in reality, their sizes are quite large..

Positioning and size of text boxes, drawings, hoverable areas on the book and some overlay icons would all have to be positioned and calculated separately according to the current zoomLevel.

**Comment by asturur** [comment]
There are 3 things a stake here:
1) canvas resize is not great quality, so big images rendered small are bad.
2) for some reason the clipPath ( image caching ) add a level of blurriness
3) if you use pannig/zooming you can eventually modify the top left of your images to obtain pixel alignment.

I think for 2 and 3 there is a solution.

Let me first give a look at 2.

**Comment by niels-van-den-broeck** [comment]
Thank you very much.

**Comment by niels-van-den-broeck** [comment]
Have you had time to take a look at this by any chanse?

**Comment by niels-van-den-broeck** [comment]
Or if I could be of any assistance, some pointers would be welcome

**Comment by asturur** [comment]
I really haven't. And i won't for a bit.
There are pointer to follow, for example, we understood that the cached image isn't really bad when you inspect it.
You could argue that you want the current cache aligned with the screen pixels to not loose clarity.

Now you could, override the image render method to do what does it do today, but before of doing it apply a sub pixel compensation for clarity.

```js
    /**
     * Paint the cached copy of the object on the target context.
     * @param {CanvasRenderingContext2D} ctx Context to render on
     */
    drawCacheOnCanvas: function(ctx) {
      fabric.util.setImageSmoothing(ctx, this.imageSmoothing);
      ctx.scale(1 / this.zoomX, 1 / this.zoomY);
      // new code
      // figure out subpixel code();
      ctx.translate(-subpixel.x, -supbixel.y);
      // end new code
      ctx.drawImage(this._cacheCanvas, -this.cacheTranslationX, -this.cacheTranslationY);
    },
```

Imagine you could, once per image and per render cycke, figure out this subpixel.

every pixel drawn go in this transformations: viewportTransform and object matrix.
The object matrix you get with object.calcTransformMatrix(), while the viewportTransform is a canvas property.

You can multiply them together with fabric.util.multiplyMatrices(zoom, object).
Then you have to add this too:

an additional zoom and translation. I'm not sure now how to factor this in ( i think you can simply compose it with the fabric.util.composeMatrix);

Once you got the final matrix, every image every render cycle, Take a point 1,1, multipliy it with the obtained matrix ( fabric.util.transformPoint(point, canvas.viewportTransform) ) and you obtain the current offset at which the pixels are, take the remainder of the division by 1, the float part.

that could be your subpixel. I m not sure i described the process with every detail and factor needed, but i think you can reasonably try it out to see if you get a bump in clarity between canvas and cacheCanvas.

If you do not support old browsers, i think that current browsers can help you with ctx.getCurrentMatrix or something similar, saving you all the calculations.

**Comment by niels-van-den-broeck** [comment]
I can only try my best but without any sight on the potential implications this might be a hard one to resolve for me in a correct manner. 
Do you have any time frame when you would be able to take a look at this?

**Comment by asturur** [comment]
I have tons of issues to read and i have to prioritize bugs and docs.
If you implement this suggestion wrong, at worse you do not get the extra clarity needed, your subpixel should always be a number between 0 and 1, and at worst you are off of a fraction of pixel.

If you try a browser hat has either
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/currentTransform
or
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getTransform

the test is done quickly.

**Comment by asturur** [comment]
i wanted to give it a shot but i have difficulties replicating the blurryness

**Comment by asturur** [comment]
ok, this code, to my eyes  solves the problem of a cached image being sharp and staying sharp on the canvas.
I'm sure something like this can be done at the moment of creating the clipPath to avoid adding blurryness.

```js
fabric.Image.prototype.shouldCache = fabric.Object.prototype.shouldCache;

fabric.Image.prototype.drawCacheOnCanvas = function (ctx) {
  fabric.util.setImageSmoothing(ctx, this.imageSmoothing);
  ctx.scale(1 / this.zoomX, 1 / this.zoomY);
  // new code
  const m = ctx.getTransform();
  const mg = [m.a, m.b, m.c, m.d, m.e, m.f];
  const p = fabric.util.transformPoint({ x: -this.cacheTranslationX, y: -this.cacheTranslationY }, mg)
  const finalX = p.x % 1;
  const finalY = p.y % 1;
  ctx.translate(-finalX, -finalY);
  // end new code
  ctx.drawImage(
    this._cacheCanvas,
    -this.cacheTranslationX,
    -this.cacheTranslationY
  );
};
```

**Comment by niels-van-den-broeck** [comment]
> I have tons of issues to read and i have to prioritize bugs and docs.

I understand that completely. I can not imagine the struggles of maintaining a library this large and complex. As I said before, I'd love to help in any way possible. Problem being that Math skills are often lacking to dig deep into fabric.js. 😄 

> If you implement this suggestion wrong, at worse you do not get the extra clarity needed, your subpixel should always be a number between 0 and 1, and at worst you are off of a fraction of pixel.

If given the time by my employer I will try to give it a try this week to take a look in the context of our application. If I get it to work as before there, it should only be a matter of replacing it to the right place inside a fork and adding some visual tests to make a PR.

**Comment by asturur** [comment]
The problem of this solution is that it solves your problem, but the usefulness is limited. Anyway maybe gave me some idea to solve issue with blurryness

**Comment by niels-van-den-broeck** [comment]
So I tried out the solution. Still seems to be off somehow 😞 

I have attached screenshots of the end result with clippath, without clippath and of the cache canvas with a clipPath which is a Group with a rectangle spanning the entire page. 

# NO CLIPPATH
![Screen Shot 2020-09-29 at 11 10 03 AM](https://user-images.githubusercontent.com/39048448/94538537-6aeed200-0244-11eb-81bf-671b010695b2.jpg)

# CLIPPATH
![Screen Shot 2020-09-29 at 11 10 10 AM](https://user-images.githubusercontent.com/39048448/94538541-6c1fff00-0244-11eb-8c48-5da301ebdc6c.jpg)

# CACHE CANVAS WITH CLIPPATH
![download (1)](https://user-images.githubusercontent.com/39048448/94538558-72ae7680-0244-11eb-9147-20870080206a.png)

Seems to me like copying the image with a clipPath to the canvas does seem to cause blurryness. Eventhough I still have no idea why. Canvas cache seems sharp to me.

**Comment by asturur** [comment]
My code was solving only the issue of added blurrynes from cache to canvas, clipPath not yet, but the solution would be similar probably.

**Comment by niels-van-den-broeck** [comment]
I have rechecked our application and I got the fix to work!

The problem was kind of obvious in hindsight. we rendered the image in a Group, which this fix does little to nothing for. 

Thank you very much, this has been an issue we've been chasing after for a very long time.

If there is any way I can contribute in the future, feel free to let me know 😉

**Comment by asturur** [comment]
If you start to like working on the library there are always small tasks ready around the issues.
