### ISSUE TITLE
Add `object:modifying` event

### ISSUE THREAD

**Issue by DanielPower** [fabricjs/fabric.js#6517]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to listen for an event that fires on every frame that a markup is being modified (moved, scaled, rotated, control points triggered).

**Describe the solution you'd like**
An additional event on the Canvas class `object:modifying`, that would behave like the `object:modified` event, except that it would trigger on every frame where a modification is occurring, not just when the modification has been completed.

Sort of like how for moving we have both `object:moved` and `object:moving`, and for scaling we have `object:scaled` and `object:scaling`.

**Describe alternatives you've considered**
A partial solution would be to listen to `object:moving`, `object:scaling`, and `object:rotating`. Though this would not catch custom control point events.

We could go one step further and have all of our control points dispatch a custom event in their action handler. And listen to that event in addition to the three events listed above.

Though I think it would be preferable to just have the `object:modifying` event as part of fabric.

**Comment by asturur** [comment]
Adding an extra event isn't an issue, it can be added right after the custom action handler is called ( if it returned true ).
The point is that in that moment of the code i m not sure if we have all the information to make an event useful.

https://github.com/fabricjs/fabric.js/blob/a4061ad5f7724851d78626a4607f7df2ad27539a/src/mixins/canvas_events.mixin.js#L928

This is the function that is the better host for this functionality. Something like

```js
if (actionPerformed) {
  this.fire('modifing', options);
}
```

should do the trick.

If you are willing to write the necessary unit tests you can open a PR for it.

**Comment by DanielPower** [comment]
I'll take a look into it this evening.
