### ISSUE TITLE
centeredScaling not observed for Textbox class

### ISSUE THREAD

**Issue by melchiar** [fabricjs/fabric.js#6518]
## Version
4.0.0

## Test Case
https://jsfiddle.net/melchiar/v0euyn8w/

## Information about environment
Browser

## Steps to reproduce
Add a textbox with `centeredScaling: true`

## Expected Behavior
Textbox should resize with a fixed center position when using the `mr` and `ml` controls

## Actual Behavior
Textbox seems to be ignoring the `centeredScaling` property with the `mr` and `ml` controls

**Comment by asturur** [comment]
right...
i ll see if is a quick fix.
