### ISSUE TITLE
4.0.0-align_guidelines for canvas.toDataURL() error

### ISSUE THREAD

**Issue by bulolo** [fabricjs/fabric.js#6519]
## Version
3.6.3 & 4.0.0

## Information 
https://github.com/fabricjs/fabric.js/blob/master/lib/aligning_guidelines.js
https://github.com/fabricjs/fabric.js/blob/master/lib/centering_guidelines.js

error like this :https://github.com/fabricjs/fabric.js/pull/392

![image](https://user-images.githubusercontent.com/10026498/90239044-81d69200-de59-11ea-915d-d44bfa7b4081.png)

![image](https://user-images.githubusercontent.com/10026498/90239087-90bd4480-de59-11ea-8e45-9c3c58547810.png)

![image](https://user-images.githubusercontent.com/10026498/90238869-3328f800-de59-11ea-87af-6f4f451016bb.png)

if i import and use the Guidelines to init
then i use canvas.toDataURL();
there is an error out.
![image](https://user-images.githubusercontent.com/10026498/90239162-ae8aa980-de59-11ea-9c51-a3d23c6d15b4.png)

when i delete the init Guidelines
![image](https://user-images.githubusercontent.com/10026498/90238979-69667780-de59-11ea-9fe4-92beac28a53b.png)

canvas.toDataURL();  run ok.

**Comment by juzhiyuan** [comment]
You’d better remove all guide lines before exporting it.

**Comment by bulolo** [comment]
@juzhiyuan 
in https://github.com/fabricjs/fabric.js/blob/master/lib/aligning_guidelines.js
there is code below
```
  canvas.on('before:render', function() {
    canvas.clearContext(canvas.contextTop);
  });
```
before render,seem i broken here
```
canvas.clearContext(canvas.contextTop);
```

**Comment by bulolo** [comment]
i use this to solve it 
it seem call canvas.toDataURL()
there is no contextTop
```
  canvas.on('before:render', function () {
    if (canvas.contextTop) {
      canvas.clearContext(canvas.contextTop);
    }
  });
```

**Comment by asturur** [comment]
must be an error of the order in which you run code. Can you reproduce the error in a fiddle?
