### ISSUE TITLE
Possibility to define individual submodules per module in build process

### ISSUE THREAD

**Issue by Kienz** [fabricjs/fabric.js#652]
The modules freedrawing and image_filters have many submodules (eg. brightness_filter, convolute_filter, gradienttransparency_filter etc.). 
So maybe it's useful to include/exclude only some of them. If the module is defined to include but no submodule is defined the complete module is included. Otherwise only the defined submodules have to be included/excluded.
##

**Comment by asturur** [comment]
i think i ll revive this thing.
The build script can be improved a bit.
Needs a nice way to specify deps between modules.

**Comment by ShaMan123** [comment]
moving to js/ts and replacing build tool
