### ISSUE TITLE
4.0.0-"shift" with left mouse click on object can add object selected,but "alt" with left mouse click can't unselected object

### ISSUE THREAD

**Issue by bulolo** [fabricjs/fabric.js#6520]
## Version
4.0.0

## 
"shift" with left mouse click on object can add object selected,
but "alt" with left mouse click can't unselected object

**Comment by asturur** [comment]
What do you mean? SHIFT is the selection key, you can swap it with alt.
Can you actually show a working fiddle?

**Comment by bulolo** [comment]
@asturur 
http://fabricjs.com/
we can use the website demo

for example:
keyboard "shift". +.  left mouse click always use to add selections, it's available in demo
keyboard "alt". +.  left mouse click always use to subtract selections,it's invalidin demo

Thank you for your reply 。

**Comment by asturur** [comment]
alt isn't used to subtract selection.
Alt is used to trigger different trasformations.

**Comment by bulolo** [comment]
in china,
 alt is always use to

**Comment by asturur** [comment]
i did not know that. With current code is not easily implementable but is not impossible.
