### ISSUE TITLE
How to tell if an object was created in free drawing mode

### ISSUE THREAD

**Issue by GreenFootballs** [fabricjs/fabric.js#6521]
I have a situation where it would be useful to know if an object/group was created in free drawing mode instead of by instantiating a built-in object. Is this possible?

**Comment by asturur** [comment]
you can flag the object during the path:created event. Is that enough?

**Comment by GreenFootballs** [comment]
Since freehand mode can use other brushes that don't create paths (circle and spray), I think object:added might work better. Is it OK to add a custom property to these objects, for example "isFreehandObject"?

**Comment by asturur** [comment]
does't path created fire for every brush? if not we should fix it. You can add the property by yourself in the event.

**Comment by GreenFootballs** [comment]
Just checked and it does fire path:created for any freehand objects, even if they don't contain paths. Oddly though, it doesn't fire when I create a path normally.

**Comment by asturur** [comment]
Path normally you mean canvas.add(new fabric.Path()) ?

That is fine. Users can't add paths with code, events are needed to react to user actions
