### ISSUE TITLE
Deselect object with "Shift+click" not working when apply zoomToPoint to Canvas

### ISSUE THREAD

**Issue by blucobalto** [fabricjs/fabric.js#6530]
Hi,
i have applyed setToZoom on Canvas. 
I select all objects.
Subsequently "Shift + click" for deselect object does not work.

Thanks a lot,
Blu

## Version
4.0.0

## Test Case
http://jsfiddle.net/8g74amye/

## Information about environment
Nodejs or browser? browser
Which browsers? Firefox, Chrome, Microsoft Edge

## Steps to reproduce
Select objects. 
## Expected Behavior
Deselect object with Shift + click
## Actual Behavior
Deselect object with Shift + click not working

**Comment by asturur** [comment]
seems a bug to me.

**Comment by asturur** [comment]
is it broken with 3.6.3?

**Comment by blucobalto** [comment]
No, in 3.6.3 is it working
