### ISSUE TITLE
How to import eps file into canvas?

### ISSUE THREAD

**Issue by manhthepixta** [fabricjs/fabric.js#6532]
I have a function which load eps from download url.
It returns blob file. I tried both `fabric.loadSVGFromString` and `fabric.loadSVGFromURL` but none work.

Does fabricjs support loading eps file?

**Comment by asturur** [comment]
no, we do not have an eps parser. But you can find tools to convert EPS or PDF to SVG and then import SVG.
Take care that EPS/PDF does not support many things, often effects and cool things are just plain rasterized images and will appear as images.

You can give a look at inkscape to convert on some linux command line.
