### ISSUE TITLE
Resizing textbox width doesn't fire the scaling event

### ISSUE THREAD

**Issue by melchiar** [fabricjs/fabric.js#6544]
## Version
4.1.0

## Information about environment
Browser

## Explanation of issue
Resizing a textbox with ml and mr isn't firing the scaling event as it did pre-4.0

**Comment by bulolo** [comment]
yes, the same

**Comment by asturur** [comment]
@bulolo can you reproduce the behavour in a js fiddle?

**Comment by bulolo** [comment]
> @bulolo can you reproduce the behavour in a js fiddle?


splitByGrapheme without controls
https://codepen.io/bulolo/pen/XWdMyMP

splitByGrapheme with controls
https://codepen.io/bulolo/pen/LYGrpoJ

**Comment by asturur** [comment]
The codepen has an error, i m not sure how much you are familiar with mutability concept in javascript.

So fabric.Object.prototype.controls is an object with keys and values: `{ tl, tr, bl, br, ml, mr, mt, mb, mtr}`.
fabric.Textbox.prototype.controls is another object with keys and values: `{ tl, tr, bl, br, ml, mr, mt, mb, mtr}`;
Each key, but not ml and mr has as a value a reference to the same instance of control, while ML and MR for the textbox are 2 different controls.

if you write this in the codepen:

```js
if (fabric.Textbox) {
	fabric.Textbox.prototype.controls = {
		...fabric.Object.prototype.controls
	}
}
```

You wipe out the old control set, and you create a new one, that is a different object but has the same keys and point to the same references of the standard fabric.Object.
In practice, you duplicate it, and doing so you wipe away MR and ML textbox special controls.

If you want to assign your special control that replace a standard controls you can do:



```js
fabric.Object.prototype.controls.tl = mySpecialControl;
if (fabric.Textbox) {
  fabric.Textbox.prototype.controls.tl = mySpecialControl;
}
```

if you need to change them all and you create a new control set, you can do shorter:

```js
myNewControlSet = { ...lotsOfControls };
fabric.Object.prototype.controls = myNewControlSet;
if (fabric.Textbox) {
  fabric.Textbox.prototype.controls = {
    ...myNewControlSet,
    // keep ML and MR working
    ml: fabric.Textbox.prototype.controls.ml,
    mr: fabric.Textbox.prototype.controls.mr,
  };
}
```

**Comment by bulolo** [comment]
> The codepen has an error, i m not sure how much you are familiar with mutability concept in javascript.
> 
> So fabric.Object.prototype.controls is an object with keys and values: `{ tl, tr, bl, br, ml, mr, mt, mb, mtr}`.
> fabric.Textbox.prototype.controls is another object with keys and values: `{ tl, tr, bl, br, ml, mr, mt, mb, mtr}`;
> Each key, but not ml and mr has as a value a reference to the same instance of control, while ML and MR for the textbox are 2 different controls.
> 
> if you write this in the codepen:
> 
> ```js
> if (fabric.Textbox) {
> 	fabric.Textbox.prototype.controls = {
> 		...fabric.Object.prototype.controls
> 	}
> }
> ```
> 
> You wipe out the old control set, and you create a new one, that is a different object but has the same keys and point to the same references of the standard fabric.Object.
> In practice, you duplicate it, and doing so you wipe away MR and ML textbox special controls.
> 
> If you want to assign your special control that replace a standard controls you can do:
> 
> ```js
> fabric.Object.prototype.controls.tl = mySpecialControl;
> if (fabric.Textbox) {
>   fabric.Textbox.prototype.controls.tl = mySpecialControl;
> }
> ```
> 
> if you need to change them all and you create a new control set, you can do shorter:
> 
> ```js
> myNewControlSet = { ...lotsOfControls };
> fabric.Object.prototype.controls = myNewControlSet;
> if (fabric.Textbox) {
>   fabric.Textbox.prototype.controls = {
>     ...myNewControlSet,
>     // keep ML and MR working
>     ml: fabric.Textbox.prototype.controls.ml,
>     mr: fabric.Textbox.prototype.controls.mr,
>   };
> }
> ```

@asturur 
you misunderstand it
i want to  custom control mr ml  and also the splitByGrapheme is effective
but whatever i do
if i custom any mr ml
the splitByGrapheme is invalid

new codepen:https://codepen.io/bulolo/pen/LYGrpoJ

**Comment by asturur** [comment]
i m sorry i did not misunderstand it. Your codepen is removing the textbox text wrap functionality, and that is a fact. With or without splitByGrapheme your codepen will scale the textbox instead of wrapping it. Yes the problem is with scalingX, since that is not meant to ne used on texboxes.

if you want to customize ml and mr too, you need 2 customized versions, one for objects with scale behaviour and one for textboxes. Or you have to write your own actionhandler that combines both behaviour.

**Comment by bulolo** [comment]
> i m sorry i did not misunderstand it. Your codepen is removing the textbox text wrap functionality, and that is a fact. With or without splitByGrapheme your codepen will scale the textbox instead of wrapping it. Yes the problem is with scalingX, since that is not meant to ne used on texboxes.
> 
> if you want to customize ml and mr too, you need 2 customized versions, one for objects with scale behaviour and one for textboxes. Or you have to write your own actionhandler that combines both behaviour.

not necessary for objects.only for textbox

sorry for my poor english :🥺
i want to use custom controls to custom the icon for ml mr (only icon) and with text wrap functionality.
but now if  custom any mr ml icon (only icon) ,text wrap functionality is invalid。

my codepen is only for textbox:https://codepen.io/bulolo/pen/LYGrpoJ

**Comment by asturur** [comment]
because you are not using the correct premade action:

https://github.com/fabricjs/fabric.js/blob/69a4be3bb96a8bc03fb2676feb0e8cb39090f037/src/mixins/default_controls.js#L101

the default action is scale, because is the most common, add the one you want from the premade one, or write one ( that is harder, but doable )

**Comment by asturur** [comment]
i think this was fixed no?
@buolo did you get the info you were looking for, was the problem settled?

**Comment by bulolo** [comment]
It OK.fixed
