### ISSUE TITLE
Text Stroke in other languages overlaping

### ISSUE THREAD

**Issue by brijeshcode** [fabricjs/fabric.js#6547]
Text stroke is overlaping currently when we use fabric js for other languages text on canvas apart from English.

I am achieving it buy adding same text twice, first with stroke and second without stroke and group it 
but this cause issue in Intractive text sections, 

So it will be very usefull you add this in core liberary so that we don't have to add two text to remove or hide the overlaping textstroke.

the issue is shown in the screen short.
![Screenshot (7)](https://user-images.githubusercontent.com/10355189/91383401-b4b15a80-e849-11ea-9849-acf7579a37ac.png)

in below two steps I am hiding the overlaping but it is not very flexible solution.

setp1: create 2 different text  one with stroke and second without stroke.
![Screenshot (8)](https://user-images.githubusercontent.com/10355189/91383558-0a860280-e84a-11ea-851c-bd01fbc5e1c9.png)

step2: put one on another to hide the overlaping strokes.
![Screenshot (9)](https://user-images.githubusercontent.com/10355189/91383671-55a01580-e84a-11ea-93ae-f2e46b4e6671.png)

**Comment by asturur** [comment]
Hi @brijeshcode, use the proper fabric.Object property
http://fabricjs.com/docs/fabric.Object.html#paintFirst

**Comment by brijeshcode** [comment]
Thank you. It worked !!
