### ISSUE TITLE
Text Alignment with Custom Font not working

### ISSUE THREAD

**Issue by true-eye** [fabricjs/fabric.js#6548]
## Version
3.6.3

## Information about the environment
Nodejs or browser? browser
Which browsers? Google Chrome

## Steps to reproduce
1. 
![image](https://user-images.githubusercontent.com/46362478/91439103-ca596b00-e8af-11ea-8098-e14d5057508f.png)

2. 
```
const activeObject = canvas.getActiveObject()
activeObject.set('textAlign', 'right')
activeObject.setCoords()
canvas.renderAll()
```

3.
![image](https://user-images.githubusercontent.com/46362478/91439299-14dae780-e8b0-11ea-9d9d-c89eb5cc4219.png)

## Expected Behavior
The above works with the default font. It's not working with a custom font. (for example, the above font is 'Babas Neue')

## Actual Behavior
So I think, it calculates the text width based on the default font, not the current font

Please help me
Thanks in advance!

**Comment by asturur** [comment]
you are porobably not loading the font correctly. Can you replicate in a fiddle?

**Comment by true-eye** [comment]
I just link the Google Font as following

```
<link rel="stylesheet"           href="https://fonts.googleapis.com/css?family=Bebas+Neue">
```

For fiddle, I will try to replicate. Meanwhile, could you let me know how to link google font?

**Comment by asturur** [comment]
on fabricjs.com there is in the demo section one that explain how to load custom fonts.

**Comment by CrandellWS** [comment]
http://fabricjs.com/loadfonts
