### ISSUE TITLE
different behavior in textbox,by controls and splitByGrapheme

### ISSUE THREAD

**Issue by bulolo** [fabricjs/fabric.js#6549]
> @bulolo can you reproduce the behavour in a js fiddle?

**splitByGrapheme without controls**
https://codepen.io/bulolo/pen/XWdMyMP
![2020-08-26 16 51 05](https://user-images.githubusercontent.com/10026498/91282815-643feb80-e7bc-11ea-9246-9c61f0faf7b2.gif)

**splitByGrapheme with controls**
https://codepen.io/bulolo/pen/LYGrpoJ
![2020-08-26 16 50 49](https://user-images.githubusercontent.com/10026498/91282825-6609af00-e7bc-11ea-9b87-4add4a3b4b2c.gif)

@asturur

_Originally posted by @bulolo in https://github.com/fabricjs/fabric.js/issues/6544#issuecomment-680748688_

**Comment by asturur** [comment]
Please do not open duplicate issues if we are already discussing the same thing in the other issue.
