### ISSUE TITLE
Hi all, Can you add "undo" and "redo".  Now we must save all canvas objects into arrary.  It is using memory so much.

### ISSUE THREAD

**Issue by AntonyHou616** [fabricjs/fabric.js#6551]

**Comment by asturur** [comment]
fabricjs offer serialization of single objects or whole canvas. Undo/redo is an application feature you can build on top of that or on top of events.

Won't be a fabricjs feature.

**Comment by AntonyHou616** [comment]
Thanks for your answer. Our project need this feature. Can you offer id for each canvas object in the future. We can scan diff by canvas object id.  Thanks.

**Comment by asturur** [comment]
you can add an object id on the added event on canvas, and save it in your json ( if you support saving ) using the additionaProperties argument

**Comment by AntonyHou616** [comment]
I have try but no result. Can you write a small demo. Thanks

**Comment by AntonyHou616** [comment]
canvas.add(
          new fabric.Line([10, 200, 300, 200], {
            ...cfg,
            fill: '#fff',
            stroke: '#fff',
            strokeWidth: 2,
          }),
        )
Where should I put the object id.

**Comment by juzhiyuan** [comment]
```js
new XX({
  id: "abc"
})
```

**Comment by AntonyHou616** [comment]
> ```js
> new XX({
>   id: "abc"
> })
> ```
It is  no effect.

**Comment by juzhiyuan** [comment]
works for me, you should use `obj.get(["id"])` to read the ID.

**Comment by asturur** [comment]
it should work out of the box, whatever you pass in the constructor goes in
the object.
