### ISSUE TITLE
Shadows stopped working on Chrome

### ISSUE THREAD

**Issue by codingdudecom** [fabricjs/fabric.js#6554]
## Version
3.6.6

## Test Case
http://fabricjs.com/shadows

## Information about environment
Browser: Google Chrome Version 85.0.4183.83 (Official Build) (64-bit)

## Steps to reproduce
**IMPORTANT NOTE** I have two computers with the same setup aside from the Windows build. One works fine, one doesn't.

The one that works:

Google Chrome | 85.0.4183.83 (Official Build) (64-bit) (cohort: 85_83_Win)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{# 1658}
OS | Windows 10 OS Version 2004 (Build 19041.450)

The one that doesn't:

Google Chrome | 85.0.4183.83 (Official Build) (64-bit) (cohort: 85_83_Win)
-- | --
Revision | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{# 1658}
OS | Windows 10 OS Version 1909 (Build 18363.1016)
JavaScript | V8 8.5.210.20

## Expected Behavior

Shadow should be shown.

## Actual Behavior

Screenshot: https://preview.redd.it/j7hycs9rgvj51.jpg?width=530&format=pjpg&auto=webp&s=dd01fc6ddcaba3bf6fb4e8b39df6c8f103e7e5af

Shadow is not visible. I believe it has to do with the `objectCaching`
When switched to `false` the shadow is shown. Funny thing is that this used to work until sometime last week. Not sure if it was a Chrome update or Windows update that messed things up.

I've checked the chrome://flags and they are the same on both machines. Please let me know if you need extra details about the environment. It's driving me crazy as I also get this in my tool based on FabricJS.

Is anybody else experiencing the same?

thanks!

**Comment by asturur** [comment]
can you try to disable hw acceleration in chrome just for a test?
Also let us know what videocard you have, and if is an integrated one, which cpu.

Chrome does lot of things with hw acceleration and they break things.

**Comment by codingdudecom** [comment]
first of all, IT WORKED! Turning off the hw acceleration did the trick!

second, that computer has an integrated Intel HD (core i5) video card (on my other computer with Intel HD 650 there was no problem)

A few extra remarks: besides shadows a few blending modes like Overlay were also not working 

Thank you for your quick response. I guess there's nothing to be done for this except kick some Chrome developer's arse :-)

**Comment by asturur** [comment]
it is useful to try to replicate in plain js and give them the gpu info from about:gpu. What i5 is it? is it old?

**Comment by codingdudecom** [comment]
yes, it's an old i5 650

any idea exactly what component is affected? not sure how to go about writing a small js example for reproducing the issue.

for completeness, here's the GPU info: https://drive.google.com/file/d/1NCZQOsz2f6laEVpwOiPjPX8bwsACZ5Zq/view?usp=sharing

I will try to submit the issue to the Chrome team

**Comment by asturur** [comment]
if is an i5 first generation, the first with integrated graphic, drivers are terrible and no one cares anymore. Lot of webgl things won't also work smoothly.
