### ISSUE TITLE
Cursor range on custom control does not extend to cornerSize of control

### ISSUE THREAD

**Issue by gloriousjob** [fabricjs/fabric.js#6556]
## Version
4.1.0

## Test Case
http://fabricjs.com/custom-control-render

## Information about environment
OS: Windows 10, 2004
Browser: Version 84.0.4147.135 (Official Build) (64-bit)

## Steps to reproduce
Move mouse over delete icon in either codepen. Move to top or bottom of X and note that the red area does not have the cursor icon but cursor icon is fine when within the X.

## Expected Behavior
Mouse should work over whole icon of control.

## Actual Behavior
Mouse only works within a certain range of the icon, likely tied to the object's corner size

## Potential fix?
Note that I was able to make this work better by replacing this code. I think it came originally from https://github.com/fabricjs/fabric.js/blob/master/src/mixins/object_interactivity.mixin.js
I also wonder if the touch corner should be handled but not sure on your thoughts. I also wasn't sure if this call was frowned upon (const controlObject = fabric.Object.prototype.controls[control]):
```js
    /**
     * Sets the coordinates of the draggable boxes in the corners of
     * the image used to scale/rotate it.
     * note: if we would switch to ROUND corner area, all of this would disappear.
     * everything would resolve to a single point and a pythagorean theorem for the distance
     * @private
     */
    _setCornerCoords: function() {
	var coords = this.oCoords,
		newTheta = fabric.util.degreesToRadians(45 - this.angle),
		cosTheta = fabric.util.cos(newTheta),
		sinTheta = fabric.util.sin(newTheta),
		/* Math.sqrt(2 * Math.pow(this.cornerSize, 2)) / 2, */
		/* 0.707106 stands for sqrt(2)/2 */
		cornerHypotenuse = this.cornerSize * 0.707106,
		touchHypotenuse = this.touchCornerSize * 0.707106,
		cosHalfOffset = cornerHypotenuse * cosTheta,
		sinHalfOffset = cornerHypotenuse * sinTheta,
		touchCosHalfOffset = touchHypotenuse * cosTheta,
		touchSinHalfOffset = touchHypotenuse * sinTheta,
		x,
		y;

	for (var control in coords) {
		x = coords[control].x;
		y = coords[control].y;
		// handle custom control corner sizes
		const controlObject = fabric.Object.prototype.controls[control];
		const cornerHyp = controlObject.cornerSize
			? controlObject.cornerSize * 0.707106
			: cornerHypotenuse;
		const cornerCosHalfOffset = controlObject.cornerSize ? cornerHyp * cosTheta : cosHalfOffset;
		const cornerSinHalfOffset = controlObject.cornerSize ? cornerHyp * sinTheta : sinHalfOffset;
		coords[control].corner = {
			tl: {
				x: x - cornerSinHalfOffset,
				y: y - cornerCosHalfOffset,
			},
			tr: {
				x: x + cornerCosHalfOffset,
				y: y - cornerSinHalfOffset,
			},
			bl: {
				x: x - cornerCosHalfOffset,
				y: y + cornerSinHalfOffset,
			},
			br: {
				x: x + cornerSinHalfOffset,
				y: y + cornerCosHalfOffset,
			},
		};
		coords[control].touchCorner = {
			tl: {
				x: x - touchSinHalfOffset,
				y: y - touchCosHalfOffset,
			},
			tr: {
				x: x + touchCosHalfOffset,
				y: y - touchSinHalfOffset,
			},
			bl: {
				x: x - touchCosHalfOffset,
				y: y + touchSinHalfOffset,
			},
			br: {
				x: x + touchSinHalfOffset,
				y: y + touchCosHalfOffset,
			},
		};
	}
};
```

**Comment by asturur** [comment]
Can you explicitly say what you want to change in the code, rather than pasting a block of which just a small part is changed?
Would help a lot in understanding.

Regarding your issue, this was one of the functionality postponed after 4.0 release. We wanted to make the control interaction area independent per controls, but we do not know how yet.

**Comment by asturur** [comment]
Isn't better if you open the PR with your proposed changes? since you have to add tests anyway.

**Comment by gloriousjob** [comment]
Completely reasonable. This is my first time contributing to a project not in my control so new to this.
https://github.com/fabricjs/fabric.js/pull/6562

**Comment by gloriousjob** [comment]
@asturur Have you been able to check out my changes? I tried consolidating the control code and also supporting rectangle controls.

**Comment by gloriousjob** [comment]
Hey

**Comment by Blazzze** [comment]
var size = 100;
 fabric.Object.prototype.cornerSize =size;
 fabric.Object.prototype.touchCornerSize = size;
