### ISSUE TITLE
The cursor doesn't render correctly when using Hoefler text in Mac book

### ISSUE THREAD

**Issue by rohitkatlaa** [fabricjs/fabric.js#6558]
## Version
3.6.0

The cursor is not properly rendered in the hoefler font family in the textbox and in itext. The cursor appears to be in middle of the alphabets while editing. This bug is observed in Mac book with google chrome.
![hoefler glitch](https://user-images.githubusercontent.com/42460632/91685689-b005e280-eb78-11ea-8ff5-44ab732d74e5.gif)

## Steps to reproduce
This error can be easily observed in the fabric js kitchensink.
- Add a textbox from the simple tab.
- Change the font family to Hoefler text in the objects tab.
- Try editing the text

## Expected Behavior
The cursor should appear correctly after the alphabets.

## Actual Behavior
The cursor appears inside the letters.

**Comment by asturur** [comment]
I'm not sure kitchensink is doing the correct job in lading fonts, anyway is not a bug, text is known to work ok with most fonts once fonts are loaded properly.
