### ISSUE TITLE
An object(rectangle,riangle,circle) with the ability to input text?

### ISSUE THREAD

**Issue by iamwc** [fabricjs/fabric.js#6559]
my project hopes the basic object(rectangle,riangle,circle) has the ability to input text ,like the shapes in excel,is there any good idea?thanks
![QQ截图20200831171553](https://user-images.githubusercontent.com/24369790/91704056-aa76bf80-ebad-11ea-8fd1-e9bb1380af90.png)

**Comment by bulolo** [comment]
fabric.util.createclass

**Comment by gloriousjob** [comment]
This isn't a Q&A... it's an issue board. An example of adding text to an object is in the fabric intro: http://fabricjs.com/fabric-intro-part-3

**Comment by asturur** [comment]
you can use groups to do so. A group with 2 object, where the object[0] is the shape, while object[1] is the text.
It requires some code on enter/exit edititing test to adapt the shape, but for all the rest is pretty much doable.
