### ISSUE TITLE
Crop repeatedly can't maintain the previous position

### ISSUE THREAD

**Issue by advcha** [fabricjs/fabric.js#6561]
Hello, 
Not sure if this a bug or not. I got some problems with FabricJS to crop an image repeatedly (multiple time). I manage to crop it by drawing a rectangle over the image then push it into a fabricjs group. Then I inverted the clipPath to show the image after it got cropped.
Here is the screenshot for the first cropped:
<img src="https://i.stack.imgur.com/bQhsN.png">

I repeat the process for another part to crop it multiple time. but somehow it can't maintain the previous cropped position. So the previous cropped is moved from the original position. I tried to use clone but still can't maintain the position.
Here is the screenshot for the second cropped:
<img src="https://i.stack.imgur.com/maQul.png">

## Version
3.6.6 (https://cdnjs.cloudflare.com/ajax/libs/fabric.js/3.6.6/fabric.min.js)

## Test Case
https://jsfiddle.net/advcha/xy7h8u40/14/

## Information about environment
Tested on chrome browser

## Steps to reproduce
Click 'Mask' button then draw a rectangle over the image then click 'Invert Crop' to show the image after cropped. Repeat this process for another crop. You can see the previous cropped position is moved 

## Expected Behavior
The previous cropped position supposed to be same (maintain)
## Actual Behavior
The previous cropped position is moved

**Comment by asturur** [comment]
The fiddle has a lot of code.
Can you remove the manual mask code and just add a single rect on to of the image that we pretend is the mask we created?
Let's try to isolate the problem to the invert crop button.

**Comment by advcha** [comment]
Hi @asturur, I managed to solve this issue. I made some changes on the invert crop event function. There was a thing make me confused. I found the position (left and top) of the previous crop (mask) has changed when I created the next crop object. so I need to store the crop or mask position in separate array (storedMaskArrayPosition) then when I create a new crop, I set the position of the old crop based on the array. it's a bit confusing. For example when first I crop at position (left, top) 10, 10 then I create another crop at another position, the first crop position no longer at 10, 10. it'd be different values. that's why I store the crop position in an array (storedMaskArrayPosition) then when I create another crop, I need to set back the previous crop postion based on the array. I also need to delay the clip action and put it in setTimeout function to make all correct. I created a fiddle for this: https://jsfiddle.net/advcha/zy4ao5bk/1/
Here is the changes on the new code from previous fiddle:
```
...
var storedMaskArrayPosition = [];
...
document.getElementById("invert_crop").addEventListener("click", function () {
    if (target !== null && mask !== null) {
      target.setCoords();

      if (storedMaskArrayPosition.length) {
        storedMaskArrayPosition.forEach(function (item, index) {
          maskArray[index].set({
            left: item.left,
            top: item.top
          });
        });
      }

      mask = rescaleMask(target, mask);
      mask.set({
        opacity: 1.0,
        dirty: false
      });
      //mask.setCoords();
      maskArray.push(mask);

      setTimeout(function () {
        storedMaskArrayPosition.push({
          left: mask.left,
          top: mask.top
        });

        var g = new fabric.Group(maskArray);

        g.inverted = true;
        target.clipPath = g;

        target.dirty = true;
        canvas.setActiveObject(target);
        canvas.bringToFront(target);
        target.selectable = true;
        canvas.remove(mask);
        canvas.renderAll();
      }, 1000);
    }
});
...
```      
Now it's working well. Pls try the new fiddle. Click 'Mask' button first then make a rectangle then click 'Invert Crop'. repeat this same process. But still wonder why the old crop can't maintain the position though.

**Comment by asturur** [comment]
i'm sorry this is completely custom code and i have no time to deal with it.
I will leave it open with `help wanted` label.

**Comment by advcha** [comment]
Hi @asturur, it's actually fixed like I said on the previous message. most probably the problem I got because the image is scaled again after it's cropped. I'll close this issue.
