### ISSUE TITLE
How can I  render the canvas lightweight after  the path object was updated

### ISSUE THREAD

**Issue by wubiandaxian** [fabricjs/fabric.js#6564]
Here's the thing, I create a path object without path point in it at init, then I add it to the canvas. 
In the mousemove event, I push these point which get from event options to the path and update it with "set" method.
For I can see the path when the mouse move, I set the path object with {dirty: true,objectCaching: false}, then render it with canvas.renderAll().
Then there's the problem, when the path object is more and more added to the canvas, renderAll will make a very obvious delay. I  have no idea  about how to deal this problem, I will very appreciate it if you can give me some tips.
Here's my code:
```javascript
canvas.on("mouse:down", function(options) {
	var addPath = new fabric.Path([], {
		fill: null,
		stroke: 'rgba(255, 0, 0, 0.4)',
		strokeLineCap: 'round',
		strokeLineJoin: 'round',
		strokeWidth: 100,
		dirty: true,
		objectCaching: false,
		evented: false,
	});
	canvas.add(addPath)
	var linePath = []
	var p = {x: options.absolutePointer.x, y:  options.absolutePointer.y}
	linePath.push(['M', p.x, p.y])
	var lx = p.x,
		ly = p.y
	canvas.on('mouse:move', function(options) {
		var mp = {x: options.absolutePointer.x, y:  options.absolutePointer.y}
		linePath.push(['Q', (mp.x+lx)/2, (mp.y+ly)/2, mp.x, mp.y])
		linePath.push(['Q', (mp.x+lx)/2, (mp.y+ly)/2, mp.x, mp.y])
		lx = mp.x
		ly = mp.y
		addPath.set('path', linePath)
		canvas.renderAll()
	})
	canvas.on('mouse:up', function(options) {
		var mp = {x: options.absolutePointer.x, y:  options.absolutePointer.y}
		linePath.push(['L', mp.x, mp.y])
		addPath.set('path', linePath)
		canvas.renderAll()
		canvas.off('mouse:move')
		canvas.off('mouse:up')
	})
})
```

**Comment by asturur** [comment]
Seems like you want to use the freedrawing brush, why are you reimplementing it from scratch?

**Comment by wubiandaxian** [comment]
> Seems like you want to use the freedrawing brush, why are you reimplementing it from scratch?

emmm……, there are two canvas, left and right. Now I move the mouse on the left, and I want the right one also can paint the moving path.

**Comment by wubiandaxian** [comment]
Can someone give me a hand

**Comment by asturur** [comment]
Someone will try, as people are trying in the other issues. The real question is how fast, and this i cannot know.
