### ISSUE TITLE
IE11 - object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by mk10391** [fabricjs/fabric.js#6565]
## Version
   4.1.0 

## Information about environment
browser?
Which browsers?
IE11

## Steps to reproduce

- add an image to Canvas.
- try to resize or drag (move) that image on canvas using mouse pointer.
- fbaric js 4.1.0 crashes in IE11 (works fine in Chrome)

## Expected Behavior

fabric JS should not crash in IE11.

## Actual Behavior

fabric js 4.1.0 crashes with error " object doesn't support property or method 'assign'". it works fine in Chrome.

i just shifted from fabric js 3.6.3 to 4.1.0. i simply updated the fabric js file and noticed this issue in IE11.

is there any way to fix it ?

Thanks

**Comment by mk10391** [comment]
i think i found the solution here 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

i had to use the condition mentioned on my pasted link for IE11 else use the code you have. 
FYI....its following line in version 4.1.0
canasOptions = Object.assign({}, options, { target: target });

**Comment by asturur** [comment]
Yes this shouldn't have get in. I need a ie11 compatibility test, unsure how to do it.

**Comment by asturur** [comment]
can you open a PR to fix it? the fix is:
```js
canvasOptions = fabric.util.clone(options);
canvasOptions.target = target;
```

**Comment by mk10391** [comment]
This was my solution that works for IE11 & Chrome

`canasOptions = checkIE11ObjectAssign(options, target );`

And the function is 

![image](https://user-images.githubusercontent.com/63499328/92072172-36d3de80-ed76-11ea-87dd-e23f28af9217.png)

**Comment by asturur** [comment]
we try to not add polyfills, or we could just add babel and move forward. Clone is sort of a simpler  assign polyfill and is already in the codebase. I probably
mistyped something

**Comment by mk10391** [comment]
i got it. This is the correct code you wanted to type. This one works in IE11 & Chrome 

`canasOptions = fabric.util.object.clone(options);`
`canasOptions.target = target;`

**Comment by asturur** [comment]
we need a PR to fix this.
