### ISSUE TITLE
export to JSON safe?

### ISSUE THREAD

**Issue by mdejong10** [fabricjs/fabric.js#6568]
Hi, I have a question: is it safe to let users export a canvas as JSON and send this to the server and let the server render it as a PNG in order to save bandwidth? Is this a safe thing to do or can malicious users somehow manipulate the JSON and inject code?

**Comment by asturur** [comment]
in fabric 4 we looked into removal of all functionalities that would restore functions ( patterns and clipTo ). I can't guarantee is safe, but we looked into it to be safer. Jsons are just key-values pars with strings and numbers, eventually. Is prototype injection possible? maybe. properties are not filtered, everything you add to the json gets attached to the 'this'. You should try yourself to hack it and see.
