### ISSUE TITLE
cannot download version 4 from custom builder

### ISSUE THREAD

**Issue by dani26381** [fabricjs/fabric.js#6569]
I'm trying to download custom code with Gestures, in the custom builder:
http://fabricjs.com/build/

But when I download, it downloads  the code with the version: 3.6.6
In the custom builder appears the version highlighted in yellow: 4.1.0

Thanks

**Comment by asturur** [comment]
i partially updated the website, i m sorry is still half and half.

**Comment by dani26381** [comment]
When do you think it can be available? Or how I can download full fabric 4.1.0, I just need with "gestures" module. But I doesn't have node.js to create the file.

Thanks in advance!

**Comment by dani26381** [comment]
finally downloaded with node.
