### ISSUE TITLE
using `canvas2.loadFromJSON(jdata);` not working

### ISSUE THREAD

**Issue by CrandellWS** [fabricjs/fabric.js#6570]
I have exported JSON from FabricJS and can not get it to load into jsfiddle...

I setup a jsfiddle page using the exact same js file I use on my server.. where it works sorta.. I have a different issue I wanted to show on jsfiddle but since I can't load the json data I am unable to show that issue so first I need to figure out why this is just not working...

In this fiddle:
http://jsfiddle.net/crandellws/zyfoLqu9/8/

you will find 2 canvases one that has shapes...just to make sure things are working...which this shows they are 

except with canvas2 I load the var jdata which is json  obtained by using `canvas.toJSON(['id'])` on another page...

please help me get the `jdata` to load into a FabricJS canvas thanks.

using `canvas2.loadFromJSON(jdata);` in the fiddle causes no errors

this same `jdata` json I can load on my system just not in jsfiddle again please help...

**Comment by melchiar** [comment]
it works fine for me, although your jdata has no background color defined, and the only object has a fill of #fcfcfc (almost white). try changing the background to black and you'll see it's loading just fine http://jsfiddle.net/melchiar/8efn2pc0/

**Comment by CrandellWS** [comment]
hmm white text ok I feel stupid thank you for pointing that out
