### ISSUE TITLE
bug when I output photos

### ISSUE THREAD

**Issue by arbalali** [fabricjs/fabric.js#6572]
Version 3.6.3

I use the initAligningGuidelines in my project and when I want to get a jpg output from canvas one (toDataURL)   
I encounter this error Uncaught TypeError: Cannot read property 'clearRect' of null

![image](https://user-images.githubusercontent.com/48292532/92303640-1ed5a800-ef8c-11ea-8391-8d963240aed0.png)

**Comment by asturur** [comment]
We need a reproducible case in order to help.

**Comment by GabrieleCicconetti** [comment]
I have the same issue this is the code that cause the problem
`canvas.on('before:render', function() {
        canvas.clearContext(canvas.contextTop);
      });`
i have just a simple project with fabric 4.2.0 and initAligningGuidelines function

**Comment by EdnaldoNeimeg** [comment]
Gabriele's answer did not work to me. Zoom in/out get bugged.

I my case the solution was:

```
canvas.on('before:render', function() {
  const ct = canvas.contextTop
  if(ct) canvas.clearContext(ct)
})
```
