### ISSUE TITLE
Apply newly uploaded font to rendered Canvas & Text layer

### ISSUE THREAD

**Issue by codihaus** [fabricjs/fabric.js#6573]
Hello,

Thank you for creating an amazing library!

I'm using FabricJS to create my custom image manager. I can upload the custom font and everything is going well.

The problem I'm facing is: apply the newly uploaded font to a rendered canvas & text layer.

Stackoverflow link: https://stackoverflow.com/questions/63754829/load-custom-font-while-at-canvas-fabricjs

I have attached an image so you can understand I want to achieve

![apply-newly-upload-font-to-the-current-text-layer](https://user-images.githubusercontent.com/68498487/92306912-e39f9d00-efbc-11ea-895d-c3f0451c0a22.png)

Thank you in advanced

**Comment by juzhiyuan** [comment]
1. upload the custom font;
2. load the font;
3. set({fontFamily: "xxx", fontStyle: "xxx"})

**Comment by codihaus** [comment]
Hi @juzhiyuan 

So, you mean we can set the font family and font style after the canvas is rendered?

**Comment by juzhiyuan** [comment]
Yep

**Comment by asturur** [comment]
font loading is asyncronous and you have to wait for it.
Check how we do here: http://fabricjs.com/loadfonts

**Comment by codihaus** [comment]
Thank you @asturur !
