### ISSUE TITLE
Monkeypatching toObject of fabric.Object.prototype

### ISSUE THREAD

**Issue by woniesong92** [fabricjs/fabric.js#6576]
This is not a problem with the library but a subtle issue I'm facing: how do I monkey-patch the fabric object so it has the properties such as `id` by default?

## Steps to reproduce

```
// Monkey patch additional properties to all Fabric object
fabric.Object.prototype.toObject = (function (toObject) {
  return function () {
    return fabric.util.object.extend(toObject.call(this), {
      // text: this.text,
      id: this.id,
    });
  };
})(fabric.Object.prototype.toObject);

// Add a Text element
const canvas = new fabric.Canvas('c')
const el = new fabric.Text(text, {})
canvas.add(el)
const serialized = JSON.toStringify(canvas)

// Try to load the serialized version
canvas.loadFromJSON(serialized)
```

## Expected Behavior
The canvas loads fine

## Actual Behavior
> Exception: calling undefined on the function "split"

This happens because after monkey patching, calling toObject() on the Text element returns an object without the expected property `text`. I think there's a subtle thing about patching a prototype that I'm missing here. The quick workaround is just to include `text` property when extending the object, but I'm afraid I might run into a similar issue with other objects later.

Would appreciate any help here! I can also add a reply here if I find the solution myself.

**Comment by asturur** [comment]
what about:

```js
const originalToObject = fabric.Object.prototype.toObject;
const myAdditional = ['id'];
fabric.Object.prototype.toObject = function (additionalProperties) {
    return originalToObject.call(this, myAdditional.concat(additionalProperties));
}
```

**Comment by woniesong92** [comment]
Thank you for being so responsive! A lot better than my version:

```js
fabric.Object.prototype.toObject = (function (toObject) {
  return function (additionalProperties) {
    const obj = additionalProperties.reduce((acc, key) => {
      acc[key] = this[key];
      return acc;
    }, {});

    return fabric.util.object.extend(toObject.call(this), {
      ...obj,
      id: this.id,
    });
  };
})(fabric.Object.prototype.toObject);
```

For posterity, the issue with the initial version was that the monkey-patched version was using an object that was missing the additional properties being passed in from `Text.toObject`. `text` was [one of such properties](https://github.com/fabricjs/fabric.js/blob/master/src/shapes/text.class.js#L1273), hence the exception was thrown.

@asturur this library is a delight to work with! Appreciate the help and very grateful that you open sourced this..

**Comment by asturur** [comment]
thank to you for the nice words!

**Comment by woniesong92** [comment]
Add this page just in case others run into this issue: https://github.com/fabricjs/fabric.js/wiki/How-to-set-additional-properties-in-all-fabric.Objects

**Comment by teewuane** [comment]
It would be nice if the docs were updated to point to that article, they currently show the old way, which does not work (at least with 5.3.0).

http://fabricjs.com/fabric-intro-part-3

**Comment by ShaMan123** [comment]
Indeed it would
You are welcome to contribute.
Ping us for instructions

**Comment by bobbyg603** [comment]
> Indeed it would You are welcome to contribute. Ping us for instructions

Hi @ShaMan123, @asturur, I'd be happy to submit a PR to update the instructions using the answer [here](https://github.com/fabricjs/fabric.js/issues/6576#issuecomment-688513187), is there anything I need to know before doing so?

**Comment by asturur** [comment]
Sadly the current website is being dismissed for a new one that is not ready yet, so submitting now documentation is a bit a waste of time. But as soon as it is ready it will be possible to open prs to update docs

**Comment by bobbyg603** [comment]
> Sadly the current website is being dismissed for a new one that is not ready yet, so submitting now documentation is a bit a waste of time. But as soon as it is ready it will be possible to open prs to update docs

No worries, excited to see the new website 🙂
