### ISSUE TITLE
update fabric 4.1.0 skipTargetFind set false  after the selected error: 

### ISSUE THREAD

**Issue by lyxisblog** [fabricjs/fabric.js#6577]
update fabric 4.1.0:
![image](https://user-images.githubusercontent.com/46701017/92426793-63945580-f1bd-11ea-97f6-30585b0b2aca.png)
skipTargetFind set false  after the selected error: 
chunk-vendors.af8e4d57.js:31 Uncaught TypeError: Cannot read property 'tl' of undefined
    at a._getImageLines (chunk-vendors.af8e4d57.js:31)
    at a._findTargetCorner (chunk-vendors.af8e4d57.js:31)
    at a.__onMouseDown (chunk-vendors.af8e4d57.js:31)
    at a._onTouchStart (chunk-vendors.af8e4d57.js:31)

![image](https://user-images.githubusercontent.com/46701017/92426932-bb32c100-f1bd-11ea-8747-ca2ef1510f4f.png)
Please tell me how to solve it and who can help me. thank you

**Comment by melchiar** [comment]
Please include a fiddle that demonstrates your issue.

**Comment by asturur** [comment]
I updated the description of skipTargetFind, the `hover` part was non accurate. It just kills selection
