### ISSUE TITLE
Can I get a state of "zooming" ?

### ISSUE THREAD

**Issue by MrMengJ** [fabricjs/fabric.js#6578]
### I am realizing a custom class extends fabric.Object and I want to get a state to know I am zooming. Is there any way ？

**Comment by asturur** [comment]
What does it mean `a state to know i m zooming`?
The only way to zoom is with some code you write, you can do whatever you want in that code.
What are you looking for?

**Comment by MrMengJ** [comment]
@asturur Thank you for your reply. I'm sorry for my unclear description.
There is a property "_scaling" that mean is scaling.
Is there something that mean is zooming? I just want to know I am zooming.
I am sorry for my bad english. Hope you can understand.

**Comment by asturur** [comment]
No there isn't, because the user cannot trigger a zoom without you writing some code.
So when your app is zooming, with your code, you can set this zooming state somewhere.

**Comment by MrMengJ** [comment]
@asturur I understand item. Thank you very much!
