### ISSUE TITLE
Offer opacity option for visual reference while keeping preserveObjectStacking to false

### ISSUE THREAD

**Issue by mspanish** [fabricjs/fabric.js#6580]
I like keeping preserveObjectStacking false, as it's quite cool to have the object I'm working on "pop to the top" so I can see it - but at times this obscures all other objects, making it hard to get the whole picture.

What would be really great is an option to have an opacity of maybe .7 rather than having to turn the feature off entirely. That way the selected element would come to the front for editing, but you could still see the elements that are temporarily placed behind it.

I know you can mimic this with mouse movements but it seems like since it's directly related to preserveObjectStacking being false, an opacity flag there might be really useful - even as a default as it's not all that useful for an item to pop to the front if it obscures everything else.

**Comment by melchiar** [comment]
This can actually be done quite easily with selection events.

https://jsfiddle.net/melchiar/ghb967pf/

**Comment by mspanish** [comment]
That's just lovely, thank you @melchiar !

**Comment by melchiar** [comment]
you're welcome!
