### ISSUE TITLE
Discard Active Object On Mouse Up

### ISSUE THREAD

**Issue by Mahmoud-Badr** [fabricjs/fabric.js#6581]
Can i change fabricjs behavior to Discard Active Object on mouse up event only?

**Comment by asturur** [comment]
is complicated. I did it in one app, but i regret it because i needed so many changes.
What is the use case actually?

**Comment by asturur** [comment]
having the selection code act on mouseup or mousedown would help a lot for some applications that make an extensive use of interaction with features like locked objects or particular objects. I wonder if this should be considered as a feature.
