### ISSUE TITLE
Path Object disappears when changing path property

### ISSUE THREAD

**Issue by andrewzolotukhin** [fabricjs/fabric.js#6583]
## Version
4.1.0

## Test Case
https://jsfiddle.net/0kb5oyp6/54/

## Information about environment
Chrome

## Expected Behavior
As you can see, I'm just slightly changing the path and object doesn't get rendered.
The same code is working in v3.6.6, here is the example: https://jsfiddle.net/tr4vse8p/
Does api changed?

**Comment by andrewzolotukhin** [comment]
It looks like now I have to call makePathSimpler prior to assign path to the "path" property. Will check it tomorrow.

**Comment by asturur** [comment]
Yes you are right, but we may want to avoid confusion having a dumb utility that call both.

**Comment by andrewzolotukhin** [comment]
Yes, we should probably embed this call into the setPath...

**Comment by asturur** [comment]
definetely

**Comment by sandro** [comment]
I'd like to add that I experienced disappearing paths while zooming in and out of the canvas, especially when moving one end of the path far away from the initially rendered canvas viewport. I seemed to fix the issue by calling this function after changing the path property:

```js
fabric.Polyline.prototype._setPositionDimensions.call(YOUR_PATH_OBJECT, {})
```

This function is called when initializing a new Path object. If you don't plan on creating a new path object every time the path coordinates change, try calling this function…it may help.

Note, the second parameter is an options object, representing the options set when initializing your Path, and you may need to include those options when updating your path coords, specifically `fromSVG`.
