### ISSUE TITLE
API to ungroup objects

### ISSUE THREAD

**Issue by jasonsturges** [fabricjs/fabric.js#6584]
Requesting programmatic implementation for ungrouping.

Similar to group, ideally an api to:
```js
objects.ungroup();
```

Both grouping and ungrouping seem tightly coupled to selection, but I'm attempting to leverage functionality outside of actual mouse interactions on the canvas.

For grouping, it requires an active selection vs objects:

```js
const selection = canvas.getActiveObject();
if (!selection || selection.type !== 'activeSelection') return;
    
selection.toGroup();
```

But more specifically for ungrouping, I want to recursively ungroup everything.

```js
const objects = canvas.getObjects();
traverser(objects);

traverser: function(objects) {
  objects.forEach(object => {
    if (object.type === 'group') {
      this.traverser(object.getObjects());
    }

    object.toActiveSelection();
  });
}
```

The above requires an active selection, whereas I'd simply prefer to walk the graph and call `ungroup()` on any group object.

It seems there should be an API here that doesn't directly involve selections, interactions, or side effects that might trigger render of the canvas such as adding / removing bounding boxes.

Apologies if I'm missing something - thanks.

**Comment by asturur** [comment]
I do not understand your concern.
If you have an activeSelection, you can do:
`activeSelection.toGroup()`, while if you have a bunch of objects you can do `new Group(objects)`.

To ungroup:
if you have a group you can do:
`group.destroy` and then canvas.add(objects). ( if i m not mistaken ) or the `toActiveSelection` and then a destroy again.

For the flattening i understand you have to write some extra code, but is also not exactly a feature we want to implement, is a custom need that people can implement in the application or can provide a small public library of utility methods if they want.

What would make this a fit in the library in your opinion?

**Comment by jasonsturges** [comment]
@asturur Hi, thanks for the reply.

My use case may be obscure, working with complex aggregates of assemblies - my concerns are:
- Not wanting to trigger active selections, updating the viewport
- Cumulative error within deeply nested groups, as each group defines its own coordinates

For example, if I have an assembly of parts in a machine and want to update a single entity within, I have to traverse each group downward such as:

![assembly](https://user-images.githubusercontent.com/1213591/92771259-56fc3280-f360-11ea-8ff5-ccd9f2f40c95.gif)

Just looking for a programmatic approach of:

(meta code, in my active selection finding each group and ungrouping such as)
```
for each object in object.objects
  if(object.type === "group")
    object.ungroup();
```

It's not so much the flattening to add to the library - more just programmatic functionality to work with the Fabric scene graph, as grouping / ungrouping seem like primitive functionality.  Coordinate spaces in groups are managed by Fabric, and `fractionDigits` accuracy results in minor offsets when I walk the JSON.

But yeah, another utility function for my app most likely here.  Also just noticed the `ungroupOnCanvas()` function - maybe I'm just missing an easier approach to what I'm trying to accomplish here.

**Comment by asturur** [comment]
ok so you want to avoid extra re-renders, that is clear.
for `Cumulative error within deeply nested groups, as each group defines its own coordinates` that seems like that once you create a nested group, even if you are able to  ungroup it with a single api call, the nested coordinate system still exist, and will calculated when you ungroup.

Now for interactions only, did you try `subTargetCheck` ? it will allow your mouse events to have a `targets` property that will find objects nested in groups.
This will solve your edit object property use case, but not aligning items between them.

Would this be a step forward for your app?

**Comment by jasonsturges** [comment]
@asturur This `subTargetCheck()` with `targets` property looks like exactly what I need.

Per the cumulative error, I think everything will be perfect with Fabric performing these operations.  There must be some subtle offset I'm not accounting for in my manual operations.  Outside of live editing, I have some utilities such as migration functions that leverage Fabric's serialization, and there I need to increase fraction digits fairly high when deeply nested.

Really appreciate this - it felt like I was missing something.  Sorry I missed this in the documentation.

Thanks again for the great product and insights.

**Comment by asturur** [comment]
I could have a demo called `interacting with complex objects` Documentation is definitely the weak spot here, but also the one that requires more time.
