### ISSUE TITLE
Is moving ActiveSelection not possible?

### ISSUE THREAD

**Issue by jaysridhar** [fabricjs/fabric.js#6592]
## Version
4.1.0

## Test Case
https://jsfiddle.net/xornqu20/

## Information about environment
Nodejs or browser? browser
Which browsers? Google Chrome (latest) Version 85.0.4183.102 (Official Build) (64-bit)

## Steps to reproduce
1. Run fiddle
2. Attempt to move the selection

## Expected Behavior
The selection should move

## Actual Behavior
Garbage. The selection does not move and garbage artifacts left on the screen.

**Comment by blucobalto** [comment]
Hi,
how to manage selections: http://fabricjs.com/manage-selection

In your case use: 
`let as = new fabric.ActiveSelection([a, b],{canvas: canvas, left: 200});`

New jsfiddle: https://jsfiddle.net/10rt3h7g/

Blu

**Comment by jaysridhar** [comment]
Thanks a lot. That resolved the issue.
