### ISSUE TITLE
Code fix placement for migrating pah-group to group

### ISSUE THREAD

**Issue by edmaybert** [fabricjs/fabric.js#6593]
I saw a code-fix for this issue here:

https://github.com/fabricjs/fabric.js/issues/4136

However I am uncertain where to inject this code.

I am upgrading from fabric 1.7.11 to 3.6.6

Any guidance as to where this fix is to be placed would be greatly appreciated.

**Comment by asturur** [comment]
there is no need to open a new issue if you already found the relevant one somewhere else.
