### ISSUE TITLE
i try to add path by points. but path box is incorrect, it becomes larger.

### ISSUE THREAD

**Issue by blue-skyyy** [fabricjs/fabric.js#6595]
Hi.  my code :
```js
 let path = new fabric.Path(p, {
        fill: null,
        stroke: "green",
        strokeWidth: 4,
        strokeLineCap: "round",
        strokeLineJoin: "round",
        originX: "center",
        originY: "top",
        pathOffset: null,
        evented: true,
        hasControls: false,
        hasBorders: false,
        selectable: false,
        isDrawingMode: false,
        className: "custom_path"
      });
      this.canvas.add(path);
```
p is pathstring. then i found path box is so big as picture.
<img width="780" alt="WechatIMG45" src="https://user-images.githubusercontent.com/23467537/93163156-fd717a80-f748-11ea-8b48-dd798991b3d8.png">

so how should i do? thanks

**Comment by asturur** [comment]
I'm sorry how are we supposed to help with an issue like this? Did you read the issue guideline?
You need to provide some kind of reproducible use case.

**Comment by blue-skyyy** [comment]
> reproducible

i'm sorry.  i sloved this question.  you can close the issue.
