### ISSUE TITLE
Discard active object not removing controls

### ISSUE THREAD

**Issue by jaysridhar** [fabricjs/fabric.js#6596]
## Version
4.1.0

## Test Case
https://jsfiddle.net/dL3x02hw/

## Information about environment
Nodejs or browser? browser
Which browsers? Chrome latest

## Steps to reproduce
1. Run fiddle
2. After 500ms, the active selection controls should disappear. It does not.

However, if you uncomment the text-addition code, the active selection handle does disappear.

## Expected Behavior
The active selection handle must disappear since discardActiveObject() is being invoked.

## Actual Behavior
The selection handle does not disappear even when invoking discardActiveObject().

**Comment by blucobalto** [comment]
Hello,
I believe you need the following instruction:
`canvas.renderAll();`

New jsFiddle:  https://jsfiddle.net/9p5frwnk/

Cheers,
Blu

**Comment by asturur** [comment]
right
