### ISSUE TITLE
Active selection showing weird artifacts when moving programmatically

### ISSUE THREAD

**Issue by jaysridhar** [fabricjs/fabric.js#6597]
## Version
4.1.0

## Test Case
https://jsfiddle.net/crispduty/moy2te53/

## Information about environment
Nodejs or browser? browser
Which browsers? Google chrome latest

## Steps to reproduce
1. Run the fiddle.
2. Click the "Click here" button a few times.
3. Behold the weirdness.

## Expected Behavior
The ActiveSelection should just move around without artifacts.

## Actual Behavior
Showing weird artifacts

**Comment by asturur** [comment]
You need to destroy the active selection when you are done and you do not add the activeSelection to the canvas.
https://jsfiddle.net/ybz2sj5k/

Look at the demo here:
http://fabricjs.com/manage-selection

**Comment by jaysridhar** [comment]
Many thanks. You guys are awesome!
