### ISSUE TITLE
'selected' and 'deselected' event's object return bad value in callback

### ISSUE THREAD

**Issue by DefeninMaxime** [fabricjs/fabric.js#6598]
## Version
4.1.0

## Test Case
https://jsfiddle.net/a6rLce2q/7/

## Information about environment
Chrome

## Steps to reproduce
Go to the jsfiddle then:
1 - Open chrome console developer
2 - Select object
3 - Deselect object
4 - Read log in console

## Expected Behavior
I wonder if this is expected behavior or if the value return by event callback must be have all of `opt` properties like 'selection:updated' event.

## Actual Behavior
Parameter `event` returns by the callback have not the good value when the even is fired. We can see it with the jsonify log of `event`. Why ? 

At this [line](https://github.com/fabricjs/fabric.js/blob/d120a468428c11a285724f8f15d38a1af82d267a/src/canvas.class.js#L1112): you fire 'deselected' event with `opt` passed to the callback. 
Then before this [line](https://github.com/fabricjs/fabric.js/blob/d120a468428c11a285724f8f15d38a1af82d267a/src/canvas.class.js#L1129) you edit `opt` properties. Javascript object reference behavior make the log in console have the good properties. But in reality (when I jsonify it), the properties doesn't exist at the moment we trigger the event.

**Comment by asturur** [comment]
the single object event just tells you that that object has be selected or deselected nothing else by design.
All the rest of the info can be found inspecting the canvas generic event.
