### ISSUE TITLE
Stroke Width increases

### ISSUE THREAD

**Issue by pradhap** [fabricjs/fabric.js#66]
when creating rectangle , side edges become larger when you increase the size of the box via the selection box.... the top and bottom don`t increase but the side size increases. it should stay the same like the top and bottom size. I am referring to the edges of the box that is black, the border.

**Comment by subhasishdash** [comment]
Please go through my stackoverflow question. I think my issue is related to this page : http://stackoverflow.com/questions/34265823/unable-to-maintain-thickness-of-strokewidth-while-resizing-in-case-of-groups-in/

**Comment by h3rb** [comment]
strokeUniform: true
