### ISSUE TITLE
layering fabric canvases on top of each other

### ISSUE THREAD

**Issue by tdiprima** [fabricjs/fabric.js#6601]
Hi!
I want to layer fabric canvases on top of each other, so that I can show/hide objects on a whole canvas quickly.  I would show/hide the canvas itself.
For some reason, it looks like css coding relative & absolute on the div don't work in the case of fabric.js.

Like -- here's my [HTML5 example](https://codepen.io/tdiprima1/pen/abNaLrW) -- works; canvases are stacked.
And here's my [fabric.js example](https://codepen.io/tdiprima1/pen/oNxPoNE) -- doesn't work; one canvas is below the other one.

I looked at a gazillion articles.  Including this [stackoverflow](https://stackoverflow.com/questions/45759866/fabric-canvas-on-top-of-another-canvas) (which did not answer the question anyway (regular html5 examples don't work) 🤯 ).

Can somebody please tell me how I can do the layering properly?

Thanks in advance.

**Comment by tdiprima** [comment]
**Update:** ok I found some css code to help me with the layering. 
I assume that z-indexing the canvas objects did not work because I suppose fabric.js has its own method of z-indexing.  As far as tagging it with absolute not working, well I guess it's probably the same thing.
Thanks.

**Comment by asturur** [comment]
```js
.wrapper .canvas-container {
  position: absolute !important;
  top: 0;
  left: 0;
}
```

Just in case you are still looking for it.
There is a style attribute that force a position on the .canvas-container element

**Comment by tdiprima** [comment]
You've saved the day once again @asturur! 😄 

That's _a lot cleaner_ than the example I found where they suggest:
```
#drawing-board>:nth-child(1) { /* :nth-child(2) z-index: 1, etc...... */
    z-index: 0;
   position: absolute !important;
}
```
Thank you!
