### ISSUE TITLE
Canvas gets smaller when rotating screen on iOS Chrome

### ISSUE THREAD

**Issue by Eltonfjunior** [fabricjs/fabric.js#6602]
Good afternoon, I have a problem when running my webpage on iOS with Canvas and FabricJs, when rotating the device screen the canvas is cut in half, has anyone had this same problem?
This only happens on Google Chrome on iOS.
Thankful.

**Comment by asturur** [comment]
you have at least to reproduce the problem outside your app.
When you can provide a fiddle link i can reopen the issue.
Also Ios version, device specs.
