### ISSUE TITLE
textureSize value for filtering big images does not correspond to image dimensions

### ISSUE THREAD

**Issue by advename** [fabricjs/fabric.js#6603]
I've read a bit through WebGL and what textureSize does. Apparently, a quick and dirty rule is that takes the biggest dimension of your image (width or height) and use that as the textureSize value.

Running `fabric.maxTextureSize` returns me that I have a maximum textureSize of which then should mean that my laptop should handle pictures of 16384x16384.

However, my canvas background image of 4000x4000, that has 16MB, takes at least 5 seconds to have a filter applied to it. On the other hand, using canvas2d as the backend takes effect within 1 second.

It might be possible that my assumptions are wrong, based on what I could find on the internet - but if not, then there might be something wrong? :/

Here is a small codesnippet how I use the filter function for the 4k image:
```js
fabric.textureSize = 5000;

function applyBrightnessFilter(value) {
      let filtersWithoutProp = canvas.backgroundImage.filters.filter(
        (filter) => !filter.hasOwnProperty("brightness")
      );
      canvas.backgroundImage.filters = filtersWithoutProp;
      const newFilter = new fabric.Image.filters.Brightness({ brightness: value });
      canvas.backgroundImage.filters.push(newFilter);
      canvas.backgroundImage.applyFilters();
      canvas.renderAll();
}
```

**Comment by asturur** [comment]
What GPU does your laptop have?
Try a textureSize of 4096 and see if it is any better.
Also please try to have a full example up in jsfiddle.

**Comment by asturur** [comment]
Anyway,no textureSize is just how big will be the webgl canvas that will host the final copy of the picture.
Also check if:
fabric.forceGLPutImageData is true/false

There can be a fault way of measuring performance that let you use the wrong copy method when finishing filters

**Comment by advename** [comment]
My laptop has a "Mesa Intel® UHD Graphics 620 (WHL GT2)" Graphic.
And i tried textureSize of 4096 but filters only covered 50% of large images.

**Comment by asturur** [comment]
Probably because your image was bigger than 4096 pixels? How big is your image?

**Comment by advename** [comment]
Thanks to another answer of yours, this issue has now been solved.
Ref: [#6805-solution](https://github.com/fabricjs/fabric.js/issues/6805#issuecomment-759542490)
