### ISSUE TITLE
toBuffer : serialize to an array of byte the canvas with objects

### ISSUE THREAD

**Issue by yboujraf** [fabricjs/fabric.js#6606]
Dear,

I need to generate bitmap buffer (1bit depth monochrome or 565 BGR (16 bits)) to send to an LCD button.

The size of the canvas (that means the LCD display) is fixed. For example width : 64 and height : 32.

I have different canvas

![image](https://user-images.githubusercontent.com/6151258/93659073-cd282580-fa41-11ea-8d6c-dee8891782fc.png).

I want to use for mixing, text area, rectangle area, ...

Then I need each time I update the properties of the objects of the canvas to get a new buffer of pixels (serialize).

I have seen in your 'Docs' toJson, toObject, toSVG but not toBuffer.

Thanks if you could give me the good path

Best Regards

**Comment by asturur** [comment]
you can use fabricJS to generate a B/W or color image of 32x64 and export it as a canvas element.

canvasEl = canvas.toCanvasElement().
Once you get the canvas element, you can get the imageData from it.

```js
var imageData = canvasEl.getContext('2d').getImageData(0, 0, canvasEl.width, canvasEl.height);
```

then you can loop over the image data and build a 1 bit buffer.

```js
var data = imageData.data;
var myBuffer = new Array(data.length/4);
for (var i  = 0; i < data.length; i+=4) {
  myBuffer[i/4] = data[1] > 128 ? 1 : 0;
}
```

Something on this path.

I'll close the issue, since there isn't much else i can say, please this is stuff for stackoverlow more than here.

**Comment by yboujraf** [comment]
Dear @asturur 

Thank for your reply.

**Trying your code, I have an issue :**

![image](https://user-images.githubusercontent.com/6151258/93963765-57cc9580-fd5e-11ea-82e4-57dbab160e3a.png)

**This is the sample code.**

```
            import { fabric } from 'fabric';

            // Arrange
            let canvas = new fabric.Canvas('c');
            canvas.width = 64;
            canvas.height = 32;

            // create a rectangle with angle=45
            let rect = new fabric.Rect({
                left: 16,
                top: 8,
                fill: 'black',
                width: 16,
                height: 16,
                angle: 45
            });

            canvas.add(rect);

            // Act

            // you can use fabricJS to generate a B / W or color image of 32x64 and export it as a canvas element.
            let canvasEl = canvas.toCanvasElement();
            // Once you get the canvas element, you can get the imageData from it.
            var imageData = canvasEl.getContext('2d').getImageData(0, 0, canvasEl.width, canvasEl.height);
            // Then you can loop over the image data and build a 1 bit buffer.
            var data = imageData.data;
            var myBuffer = new Array(data.length / 4);
            for (var i = 0; i < data.length; i += 4) {
                myBuffer[i / 4] = data[1] > 128 ? 1 : 0;
            }
```

Thanks if you could highlight

Best Regards

**Comment by yboujraf** [comment]
Dear,

 

I am still at the same position even I create the issue on stackoverflow.

 

BR

**Comment by asturur** [comment]
Try removing the type library.
