### ISSUE TITLE
Move action in custom controls api (4.1.0)

### ISSUE THREAD

**Issue by Timoostrich** [fabricjs/fabric.js#6607]
I just updated my project to 4.1.0 and recreated my custom controls using the built in custom controls api (which is great).

There is only one last thing, that is missing: A simple move action for my move icon.
Here you can see my move icon (old working version): https://lettering.org/lettering-generator/

I can't finde a move action here: https://github.com/fabricjs/fabric.js/blob/master/src/mixins/default_controls.js

The old custom controls plugin just needed the "action: move". Is there something similar in fabric.js?
I searched for move actions everywhere, but I did not find anything.

`	fabric.Object.prototype.controls.customMove = new fabric.Control({
		x: -0.5,
		y: -0.5,
		//actionHandler: move?,
		cursorStyle: 'pointer',
		render: renderIcon(icon_move),
		cornerSize: icon_size
	});`

Thanks for your help!

**Comment by asturur** [comment]
i think you can create one easily.

this is a function from Canvas that makes the drag action.
```js
    /**
     * Translates object by "setting" its left/top
     * @private
     * @param {Number} x pointer's x coordinate
     * @param {Number} y pointer's y coordinate
     * @return {Boolean} true if the translation occurred
     */
    _translateObject: function (x, y) {
      var transform = this._currentTransform,
          target = transform.target,
          newLeft = x - transform.offsetX,
          newTop = y - transform.offsetY,
          moveX = !target.get('lockMovementX') && target.left !== newLeft,
          moveY = !target.get('lockMovementY') && target.top !== newTop;

      moveX && target.set('left', newLeft);
      moveY && target.set('top', newTop);
      return moveX || moveY;
    },
```

and here is where it gets used.

```js
    /**
     * @private
     */
    _performTransformAction: function(e, transform, pointer) {
      var x = pointer.x,
          y = pointer.y,
          action = transform.action,
          actionPerformed = false,
          actionHandler = transform.actionHandler,
          // this object could be created from the function in the control handlers
          options = {
            target: transform.target,
            e: e,
            transform: transform,
            pointer: pointer
          };

      if (action === 'drag') {
        actionPerformed = this._translateObject(x, y);
        if (actionPerformed) {
          this._fire('moving', options);
          this.setCursor(options.target.moveCursor || this.moveCursor);
        }
      }
      else if (actionHandler) {
        (actionPerformed = actionHandler(e, transform, x, y)) && this._fire(action, options);
      }
      transform.actionPerformed = transform.actionPerformed || actionPerformed;
    },
```

Should be trivial to transform the canvas method `_translateObject` in a control action, and then change the original function ot use the control action rather than the canvas method.

**Comment by Timoostrich** [comment]
Thanks for your super fast answer!
I'm sorry but I don't get it how to combine these actions/functions to make them work on a custom control. Basically I'm a designer and my coding skills are not that good. :/
Adding a custom drag/drop function was no good idea either...

I wonder how https://pixolith.github.io/fabricjs-customise-controls-extension/ was doing it. I did not find a move action in the .js file.

I just created a pen, maybe you can add the move action? Probably that will be useful for many others, too?
(If it's possible, I'm happy to pay for the help!)

https://codepen.io/timothy90/pen/eYZPjjv

Thanks
Timo

**Comment by peracto** [comment]
I may have missed something ... but is it not as simple as specifying the actionName='drag' ...

```javascript
fabric.Object.prototype.controls.customMove = new fabric.Control({
  x: -0.5,
  y: -0.5,
  //actionHandler: move?,
  cursorStyle: 'pointer',
  render: renderIcon(icon_move),
  cornerSize: 30,
  actionName: 'drag'
});
```

**Comment by Timoostrich** [comment]
Damn, that is exactly what I was looking for. 
I searched for "move", "transform" etc. but never for "drag". :<

Thank you so much!!!

**Comment by asturur** [comment]
i did not know it would work out if you specify 'drag' :)
I still think we can move that code in a function to be reused for whatever reason.

**Comment by asturur** [comment]
i m making a PR, consider that in 4.2.0 you have to add the control handler to move the object. actionName='drag' won't work.

```js
fabric.Object.prototype.controls.customMove = new fabric.Control({
  x: -0.5,
  y: -0.5,
  //actionHandler: move?,
  cursorStyle: 'pointer',
  render: renderIcon(icon_move),
  cornerSize: 30,
  actionHandler: fabric.controlsUtils.dragHandler,
  actionName: 'drag'
});
```
