### ISSUE TITLE
How to set gradient on an object? The example in the documentation does not work.

### ISSUE THREAD

**Issue by jaysridhar** [fabricjs/fabric.js#6609]
## Version
4.1.0

## Test Case
https://jsfiddle.net/crispduty/zx290qrc/

## Information about environment
Nodejs or browser? browser
Which browsers? Chrome latest

## Steps to reproduce
1. Run the fiddle. Everything works fine because "setGradient()" call is commented out
2. Uncomment the "setGradient()" line and re-run. The error appears in the console: circle.setGradient is not a function

## Expected Behavior
Need to know how to set gradient since the example in the documentation does not work.

**Comment by melchiar** [comment]
See http://fabricjs.com/v4-breaking-changes

The docs haven't been updated yet for v4 so some of the information is out of date.

**Comment by asturur** [comment]
there are a couple of closed issue with the same question and an answer, also search for those.

**Comment by jaysridhar** [comment]
Hey sorry for not checking everywhere (changelog and previous issues). Will keep that in mind in the future.

**Comment by shajal-kumer** [comment]
I am a beginner in fabric.js. i am trying this bellow code but it does not work. 

`var rect = new fabric.Rect({
				left: 100,
				top: 100,
				width: 200,
				height: 200,
			});

			rect.set(
				"fill",
				new fabric.Gradient({
					type: "linear",
					coords: {
						x1: 0,
						y1: 0,
						x2: rect.width,
						y2: 0,
					},
					colorStops: { 0: "red", 1: "blue" },
				})
			);`
			
			and throwing this error 
![image](https://user-images.githubusercontent.com/24448450/105126612-5c853880-5b09-11eb-82fa-6d8d8d465463.png)

**Comment by semy** [comment]
@asturur Why don't you just change the documentation?

**Comment by asturur** [comment]
time constrains only

**Comment by asturur** [comment]
http://fabricjs.com/fabric-intro-part-2#gradients

updated.
