### ISSUE TITLE
[feature request] Json upgrade method

### ISSUE THREAD

**Issue by lk77** [fabricjs/fabric.js#6610]
Hello,

i have an issue with the upgrade of the json structure over time

**Is your feature request related to a problem? Please describe.**
JSON generated with a specific version of fabric.js may get outdated after a while and will need to be updated

**Describe the solution you'd like**
A method to update an old json to the current version

**Describe alternatives you've considered**
No solution was considered for now, appart from a migration server side, to adjust the json accordingly

**Additional context**
We store json in database, and we fear that this might not work over time due to json structure changes in the package, and we need a way to securely update old json.

thanks.

**Comment by asturur** [comment]
JSON format changed between v1 and v2 i think, V3 and V4 did not change it anymore.
What kind of changes did you encouter?

**Comment by lk77** [comment]
i did not encounter changes for now, i've started using fabric.js, i'm just preparing for future changes in the json format, json format may change, perhaps it will not change, but there is no guarantee of that

**Comment by asturur** [comment]
We usually deal with that with documentation and proposing functions to update in the doc.
Example:
http://fabricjs.com/v2-breaking-changes
We added the version property in the JSON exactly because we wanted everyone to be able to handle an update.

**Comment by asturur** [comment]
We won't add this in the code because that would mean conitnuing support old code forever. A breaking version is called breaking for a reason.

**Comment by lk77** [comment]
Not forever, at least the last version

**Comment by asturur** [comment]
well in that page there is the code to change the properties, there is for filters and for pathgroups and for text. And is version 1 to 2. Nothing is changed in 3 and 4. If something problematic will change we will think when it happens. I m not writing a feature because maybe in the future could be useful.
