### ISSUE TITLE
IText is not working properly when the Canvas is within a Bootstrap Modal

### ISSUE THREAD

**Issue by superstar1128** [fabricjs/fabric.js#6611]
## Version
3.6.0

## Test Case
http://jsfiddle.net/tzjtr09h/

## Information about environment
jquery, bootstrap, fabric.js

## Steps to reproduce
When I create canvas on the modal, I can't type text into canvas.

## Note
- I see similar reports with this, but can't find good solution.
- When I remove focus event from jquery, it could work well without any change on the fabric.js

**Comment by asturur** [comment]
The reports are identical, and there isn't a good solution.
If jquery swallow your keypresses, you can't do much other than modify fabricJS to have the hiddenTextarea inside the canvas container so that it is inside the modal also.
Until we support ie11 we can't do it.
