### ISSUE TITLE
How to use native code to draw graph?

### ISSUE THREAD

**Issue by GreatAuk** [fabricjs/fabric.js#6614]
![image](https://user-images.githubusercontent.com/20253809/94092145-8cb71600-fe4c-11ea-8266-67f76b0de269.png)

I want to draw a wave graph, I know how to implement it in native code(https://github.com/ZENGzoe/wave-progress)

**In fabric.js, how to write native code?**

**Comment by asturur** [comment]
in the draw method of a custom class. Take the rect class, check where the beginPath command, there is the place.

**Comment by GreatAuk** [comment]
Thanks , I will try

**Comment by GreatAuk** [comment]
By the way, It's a awesome project😆
