### ISSUE TITLE
How  to add the shapes dynamically from the json object

### ISSUE THREAD

**Issue by FahadRS** [fabricjs/fabric.js#6616]
Hello I am trying to find any way where I can create/initialize the list of an object from the JSON object here is what i have tried 

```
let rectJson = '{"type":"rect","left":100,"top":100,"width":60,"height":70,"fill":"red"}';
let object = new fabric.Object(JSON.parse(rectJson ));
fabricCanvas.add(object);

```

is there any way i can add the shapes dynamically from the JSON objects

**Comment by asturur** [comment]
yes you can, is call `fabric.util.enlivenObjects`
http://fabricjs.com/docs/fabric.util.html#.enlivenObjects
You can check in the current source code how is used. is ASYNC and requires a callback.
