### ISSUE TITLE
Question: Changing Textbox/IText value within a Group

### ISSUE THREAD

**Issue by BJJLangedijk** [fabricjs/fabric.js#6622]
I have a question regarding the edit mode of Textbox/IText objects in Fabric. 

How would I be able to use the Textbox edit mode while it is in a group? I'm unable to use Textbox objects directly in the canvas because in my application the Group would consist of multiple elements.

As you can see in the test jsfiddle, you can change the text on Textbox objects if they're added directly to the canvas, however you cannot change the text of Textbox objects that are part of a group.

Test case
======================
https://jsfiddle.net/c39kten7/2/

Code behavior
======================
I have seen in `fabric/src/mixins/itext_click_behavior.mixin.js` some behavior which might explain the things happening:

From what I can see, any mouseUp event is cancelled if the object is part of a group and/or if the object is not selected (in a group the group item would been selected).

This causes the `enterEditing` to never be called

```
mouseUpHandler: function(options) {
    this.__isMousedown = false;
    if (!this.editable || this.group ||
      (options.transform && options.transform.actionPerformed) ||
      (options.e.button && options.e.button !== 1)) {
      return;
    }

    if (this.canvas) {
      var currentActive = this.canvas._activeObject;
      if (currentActive && currentActive !== this) {
        // avoid running this logic when there is an active object
        // this because is possible with shift click and fast clicks,
        // to rapidly deselect and reselect this object and trigger an enterEdit
        return;
      }
    }

    if (this.__lastSelected && !this.__corner) {
      this.selected = false;
      this.__lastSelected = false;
      this.enterEditing(options.e);
      if (this.selectionStart === this.selectionEnd) {
        this.initDelayedCursor(true);
      }
      else {
        this.renderCursorOrSelection();
      }
    }
    else {
      this.selected = true;
    }
  },
```

**Comment by CrandellWS** [comment]
see this: https://stackoverflow.com/a/30713619/1815624

That provides a working start but i think it has a problem of adding everything in the canvas back to the group after editing although this answer seems to correct that:
https://stackoverflow.com/a/46076394/1815624

and this one combines them into a working solution:
https://stackoverflow.com/a/56955197/1815624

which points to:
http://jsfiddle.net/fd4yrxq6/2/

**Comment by CrandellWS** [comment]
also in the future you may want to just add the cdnjs link instead of selecting the outdated ones on jsfiddle:

see: http://jsfiddle.net/crandellws/1cad3e4o/

**Comment by asturur** [comment]
the problem with editing inside the group is that the group itself isn't able to handle growing objects inside. 

I wonder if we can create something like a shallow group that foes not have this problems.

**Comment by asturur** [comment]
anyway used solutions include ungrop and regroup evrything after editing, or try to manually call enterEditing() using subTargetCheck

**Comment by BJJLangedijk** [comment]
> see this: https://stackoverflow.com/a/30713619/1815624
> 
> That provides a working start but i think it has a problem of adding everything in the canvas back to the group after editing although this answer seems to correct that:
> https://stackoverflow.com/a/46076394/1815624
> 
> and this one combines them into a working solution:
> https://stackoverflow.com/a/56955197/1815624
> 
> which points to:
> http://jsfiddle.net/fd4yrxq6/2/

I have tried this and it _does_ seem to work as expected, I do however have some issues with reconstructing the group and its options as they are lost when making the new `fabric.Group`. These issues can however be overcome.

> try to manually call enterEditing() using subTargetCheck

I have tried this as well and though I can edit the text and the value of the text object seems to be updated, there's some issues where the updated text does not seem to trigger a re-render and of-course selection of texts does not work without catching those events as well (mouseUp event triggers a de-select because of the group/selected check in it)

**Comment by bilal-uforia** [comment]
> the problem with editing inside the group is that the group itself isn't able to handle growing objects inside.
> 
> I wonder if we can create something like a shallow group that foes not have this problems.

@asturur have you any idea how we can acheive this (handling growing objects inside canvas) ?
