### ISSUE TITLE
Drag and drop fabric objects to elements outside the canvas

### ISSUE THREAD

**Issue by GreenFootballs** [fabricjs/fabric.js#6623]
Is there any way to drag a fabricjs object and drop it on an HTML element outside the canvas, to store an object using its JSON representation? I've seen lots of examples going the other way and that's fairly straightforward.

**Comment by asturur** [comment]
i think not super easy, you could use a drag event and use setData on drag start with the json content. But can  you generate a drag event from the canvas itself? you would get the standard move operation.

**Comment by GreenFootballs** [comment]
Yes, I've been looking into this and I think it's probably not going to work because the dragstart event needs to be caused by user intent. Thanks for reply.

If you have a minute, I had a small unresolved styling issue with something we discussed recently and I think you might be able to figure it out easily with your knowledge of the library: https://github.com/fabricjs/fabric.js/issues/6523#issuecomment-685899555

**Comment by asturur** [comment]
can you bump up the topic from the issue? so i get an email that is visible
in my inbox.
