### ISSUE TITLE
Problem with pseudo-list generator

### ISSUE THREAD

**Issue by GreenFootballs** [fabricjs/fabric.js#6625]
I'm still having an issue with this - the code is correctly rendering everything now, EXCEPT when I enter editing mode, select some text, and change any of the styles.

[Here's a Codepen demonstrating the issue.](https://codepen.io/green_footballs/pen/bGppvyd)

Changing the font size for a selection works correctly ONLY on the very first line of the pseudo-list. If you select text anywhere else in the textbox and change the size, the display gets all messed up. Sometimes the text size changes but the width of the selection area doesn't - sometimes the size doesn't change but the selection width does.

If you just select the pseudo-list _without_ going into editing mode and change the font size for the whole thing, it works fine.

This example has both the pseudo-list and a normal Textbox object next to it, to show that changing a selection's font size works correctly in the normal Textbox. Do you have any idea what's going on here? I looked through the fabric code, but couldn't find a reason. It seems like it's missing a function call somewhere to regenerate the character widths/styles.

_Originally posted by @GreenFootballs in https://github.com/fabricjs/fabric.js/issues/6523#issuecomment-685899555_

**Comment by asturur** [comment]
Is enough to bump that issue up.

**Comment by GreenFootballs** [comment]
Sorry, I thought this was what you meant. What should I have done instead?

**Comment by asturur** [comment]
is fine to just add a message to the old issue. I get an email, i do not open it until i answer it and is there in my inbox. This is how i keep track of messages to deal with. Does not matter if the issue is open or close.
