### ISSUE TITLE
Emoji not rendered in color with nodejs server

### ISSUE THREAD

**Issue by LemarinelNet** [fabricjs/fabric.js#6626]
Hi,

I try to render fabricjs canvas  server side with node JS.
The canvas is made by the user, and he has a function to insert on the canvas custom text.
On the browser, the emojis are rendered correctly (with color), but when I render them with nodejs, they are only monochrome (thus adopting font color).

What am I missing ?

Thanks !

**Comment by asturur** [comment]
probably that node machine does not have the same emoji font.
Is it the same machine?

**Comment by LemarinelNet** [comment]
Yes, both are my dev machine : testing with chrome as browser, and nodejs with the same registered fonts.
BTW : do I need to register a special font so nodeJs can render colored emojis ?

**Comment by asturur** [comment]
I'm not sure. The emoji aren't for sure in the arial or timesnewroman font file. Are in another font file and there is a fallback system in the OS. I have no idea how this work in node with cairo.
If you look here:
http://fabricjs.com/fabric-intro-part-4#node
there is written how to use the font register system of not canvas.

**Comment by sebastianfast** [comment]
For anyone stumbling across this issue, check out [my reply here](https://github.com/Automattic/node-canvas/issues/760), where I'm overriding `fabric.Textbox` to render [twemoji-emojis](https://www.npmjs.com/package/twemoji-emojis) as SVGs
