### ISSUE TITLE
FabricJS in an Android Webview has Newlines showing as \n

### ISSUE THREAD

**Issue by CrandellWS** [fabricjs/fabric.js#6627]
FabricJS in an Android Webview has Newlines showing as \n
Not sure how to share a fully working snippet for Android Webview so let me know what I should do to better example this issue...

perhaps a full app that does only this? and it's source on GitHub...idk you tell me

here is the stack question
https://stackoverflow.com/questions/64140368/fabricjs-android-webview-newlines-showing-as-n

**Comment by asturur** [comment]
Was me on the comment 👋
