### ISSUE TITLE
Adding a video element to a canvas does not work

### ISSUE THREAD

**Issue by woniesong92** [fabricjs/fabric.js#6629]
Adding a video element to a canvas does not work as expected

## Version
4.2.0

## Expected
- [Expected](http://fabricjs.com/video-element)

## Actual
- [Actual](https://codesandbox.io/s/practical-cloud-kmqew?fontsize=14&hidenavigation=1&theme=dark&file=/src/index.js)
Notice how the text and the image elements were added to the canvas while the video element wasn't

**Comment by woniesong92** [comment]
I figured out what causes the unexpected behavior: if you don't set the `width` and `height` attributes in the html video element, it won't be rendered. Should we add this gotcha to the doc or comment in the codebase?

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/94989637-9b04e080-0576-11eb-8d16-e02679de23d6.png)

for me works out of the box.

**Comment by asturur** [comment]
we can add a comment in the demo indeed

**Comment by ariel-frischer** [comment]
@woniesong92 This worked for me I was lucky to stumble upon this issue please add this to the video demo page!

**Comment by sourabh-joshi** [comment]
This gotcha definitely needs some attention! Got me too.
