### ISSUE TITLE
Object moves forward after it's been moved

### ISSUE THREAD

**Issue by woniesong92** [fabricjs/fabric.js#6630]
## Version
4.2.0

## Steps to reproduce
1. Add one Text element A
2. Add another Text element B and bring it to the front
3. Move Text element A so that it overlaps with Text element B
4. Verify that Text element A is now more forward than text element B

## Expected Behavior
Text element A stays behind Text element B after having been moved

## Actual Behavior
Text element A is brought in front of Text element B after having been moved

## Similar issues
- https://github.com/fabricjs/fabric.js/issues/508
- https://github.com/fabricjs/fabric.js/issues/514

**Comment by woniesong92** [comment]
The exact behavior is actually the `activeObject` is at the forefront of the canvas. As a workaround, I could discard active object at the `object:moved` event.
I'm curious what's the rationale behind this default behavior. If there's a text element intersected on top of an image, the text element is hidden while the image is being moved. Is there any recommended way to get around this issue?

**Comment by asturur** [comment]
http://fabricjs.com/docs/fabric.Canvas.html#preserveObjectStacking
