### ISSUE TITLE
SVG render problem

### ISSUE THREAD

**Issue by iamappmaker** [fabricjs/fabric.js#6632]
## Version
3.6.6

## Information about environment
Which browsers?
Chrome

I have added a background image and a Text. 
Exported as SVG. It works correctly in chrome.
When i add this SVG to canvas, object positions are incorrect and few attributes are missing.

1. Canvas
![Image (61)](https://user-images.githubusercontent.com/43312229/95023927-748d9500-069d-11eb-9933-ff8d2bddffd1.png)

2. Exported SVG 
https://github.com/iamappmaker/files/blob/main/sss.svg

3. Adding above SVG to canvas
![Image (62)](https://user-images.githubusercontent.com/43312229/95024148-e9ad9a00-069e-11eb-93ba-6db2ba102c4c.png)

You can see object position is wrong and shadow is missing.

Other issues are:
1. if i add background color & text then exporting the svg and adding back to canvas background color become small square in top left corner.

![Image (63)](https://user-images.githubusercontent.com/43312229/95024304-c2a39800-069f-11eb-9135-5bf915480532.png)

**Comment by asturur** [comment]
you can't import back svg exported. If you want to import back canvas status you have to use JSON.

Shadow is not an svg feature, and we do not support tspan (text position)
