### ISSUE TITLE
Blurry image quality when exporting canvas

### ISSUE THREAD

**Issue by wpaholic** [fabricjs/fabric.js#6633]
Hi, i need help with exporting canvas into PNG. i created a canvas sized 200x250 which is 1:20 of an image sized 4000x5000 then i load that image into canvas and export back into another PNG. But the exported image look quite blurry compared to original image. When exporting image, i use blob and even set the quality to 1 when declaring new Blob it still looks blurry. am i missing something?

here the exported image (on the left) with original image:

![Image preview](https://i.imgur.com/RMo7O2E.png)

**Comment by melchiar** [comment]
See here for explanation of object caching http://fabricjs.com/fabric-object-caching

**Comment by asturur** [comment]
This happen because from a 250x200 canvas you will get only a 250x200 blurry png. The original 4000x 5000 pixels are gone.

You need to use the multiplier function when exporting in order to get back the bigger image

**Comment by wpaholic** [comment]
yes i did set the multiplier to 20 which is equal to original image, even tried disable object caching the result are still the same! any idea?

**Comment by melchiar** [comment]
Can you post a fiddle showing the issue?

**Comment by wpaholic** [comment]
I think i found it, this problem happens when you clip an image object using absolute clip path, exported image will be degraded significantly, like only 60% quality left.
