### ISSUE TITLE
object rect is not full show the left store and right store

### ISSUE THREAD

**Issue by zuliandri2** [fabricjs/fabric.js#6634]
## Version
2.3.3

## Test Case
https://jsfiddle.net/fabricjs/7gvJG/

## Information about environment
browser?
Mozilla and chrome

## Steps to reproduce
make object Rect witj properties:
left:= 50
top = 50
width = 300
height = 50
fill = transparent
strokeWidth = 2
stroke= green

make object group with properties
width= 50

## Expected Behavior
show all object rect in group

## Actual Behavior
object rect got intersect with object group

![image](https://user-images.githubusercontent.com/10961433/95069152-7ce2e000-0730-11eb-8325-1cba04fea226.png)

**Comment by asturur** [comment]
you can't choose the width of the group. The group size is determined by the objects contained in it
