### ISSUE TITLE
fabric js canvases(I have more than one) in an mp4 file with transitions

### ISSUE THREAD

**Issue by covationlabs** [fabricjs/fabric.js#6635]
I need to export the fabric js canvases(I have more than one) in an mp4 file with the same animation between each with some transitions.

I don't find anything related to this on the internet. My frontend is in angular and backend is in node.js.

Any help is highly appreciated.

**Comment by asturur** [comment]
We do not offer this kind of support here. Your question is fairly generic.

Look at the new media stream api on the browser, they are quite useful.

https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API
