### ISSUE TITLE
 Canvas Problem after resizing the canvas

### ISSUE THREAD

**Issue by arbalali** [fabricjs/fabric.js#6636]
After resizing the canvas, the canvas still has its original coordinates, and by adding the object in the middle of the canvas, the object goes to the wrong place.

Before resizing the canvas
![image](https://user-images.githubusercontent.com/48292532/95086009-d3e6b600-072c-11eb-9a97-945f0d8e0318.png)

After resizing the canvas
![image](https://user-images.githubusercontent.com/48292532/95086091-f082ee00-072c-11eb-91e2-e41ede4cc5da.png)

**Comment by asturur** [comment]
Unsure what center of canvas means, but without a clear simplified code fiddle for now i have to close. I'll reopen as soon a simple and clear fiddle is added.

**Comment by arbalali** [comment]
function setSizeBoard(width,height){
     canvas.setHeight(height);
     canvas.setWidth(width);
     canvas.renderAll();
}

**Comment by asturur** [comment]
please create a fiddle showing your problem clearly

**Comment by arbalali** [comment]
![report](https://user-images.githubusercontent.com/48292532/95184927-e6b4c580-07d4-11eb-8939-d126fec52f0c.gif)

**Comment by arbalali** [comment]
![report](https://user-images.githubusercontent.com/48292532/95184927-e6b4c580-07d4-11eb-8939-d126fec52f0c.gif)

**Comment by asturur** [comment]
@arbalali do you know what a fiddle or codepen is?
Did you see the standard fiddle posted in the issue opening template?

**Comment by arbalali** [comment]
https://jsfiddle.net/arbalali/t6drvyco/27/

**Comment by asturur** [comment]
https://jsfiddle.net/h2t3u586/

You are declaring width and height and not updating them when resizing the canvas.

**Comment by arbalali** [comment]
thank you
I also use initCenteringGuidelines and initAligningGuidelines how to change their values

**Comment by arbalali** [comment]
https://jsfiddle.net/arbalali/t6drvyco/28/
