### ISSUE TITLE
Transparent clippath

### ISSUE THREAD

**Issue by Koniciuaaa** [fabricjs/fabric.js#6637]
Is possibility to make fill object transparent when it has a clipPath?

**Comment by asturur** [comment]
Can you explain better what are you trying to achieve?

**Comment by Koniciuaaa** [comment]
I would like to have this grey background non visible.
https://ibb.co/yV4ZCPS

**Comment by wpaholic** [comment]
You can set `fill` to `rgba(0,0,0,0)` when creating a mask rectangle.

**Comment by Koniciuaaa** [comment]
I tried it and it doesn't work: https://ibb.co/VSXv9bq

Its strange, because on the left side I have main canvas (not work, its all transparent), but on right side it works (its static canvas - preview of main canvas).
