### ISSUE TITLE
Why is the strokeUniform variable remarked in the toObject function?

### ISSUE THREAD

**Issue by joyk1130** [fabricjs/fabric.js#6641]
I set the strokeUniform variable to true to fix the stroke size when increasing or decreasing the object scale.
When I use the clone function, the stroke result is different.
The strokeUniform value is not copied when creating a clone.

If you look at the fabric.js file, the strokeUniform value is remarked in the toObject function, but I wonder why!

This is my example : 
[http://jsfiddle.net/Nicky_Jo/zb6Lrvod/](url)

**Comment by asturur** [comment]
Unclear how to use the fiddle.

**Comment by joyk1130** [comment]
![image](https://user-images.githubusercontent.com/69443938/95616651-1dc0fa80-0aa5-11eb-955a-a090bbd2a208.png)

I mean this line.

This is my fiddle how to use.
1. Click a orange color rectangle.
2. scaleup select object.
3. ctrl+c -> orange rectangle
4. ctrl+v

Result:
![image](https://user-images.githubusercontent.com/69443938/95616940-988a1580-0aa5-11eb-82a1-928621e2f454.png)

**Comment by asturur** [comment]
that line shouldn't be commented. Is wrong. Should be fixed.

**Comment by jaltekruse** [comment]
@asturur I'm interested in getting this fixed. I see the TODO comment was added/removed in these PRs, but I'm not sure that it addressed any/all possible problems that were the reason it was commented originally.

added - https://github.com/fabricjs/fabric.js/pull/6118/files
TODO removed - commented line remains - https://github.com/fabricjs/fabric.js/pull/6280/files

Could you point me at some areas to test/fix to enable this to be safely uncommented? Happy to contribute fixes, just a pointer in the right direction would be helpful.

**Comment by asturur** [comment]
I think the issue was just me have a terrible test suite and need to update all the things manually.
Let's do that and let's get this thing solved.

**Comment by jaltekruse** [comment]
Got it, there are probably just tests that have hard-coded exports saved, and those need to be updated? Sounds like a good newbie task, I'll uncomment and try to get the tests all passing.

**Comment by asturur** [comment]
oh do not worry! i just started it. I needed to fix it too for work, but i
used a workaround and then i forgot.
