### ISSUE TITLE
pattern display different with different background color and repeat type

### ISSUE THREAD

**Issue by Jokcy** [fabricjs/fabric.js#6642]
## Version
4.2.0 but also in 3.x

## Test Case
http://jsfiddle.net/2ztdscL8/3/

## Information about environment
browser
chrome

## Steps to reproduce
as you can see in jsfiddle. if I put `repeat` to `repeat-x`, the `repeat` Image will display a little differently, like 1px smaller. you 
can toggle `repeat` to `repeat-x` I guess you will see the difference.

also if I set `repeat` to `repeat-x`, and put background to `white`, it seems fix the problem.

I also put these images into `<img>` to show what exact they are.

sorry for my poor english, if you can not understand what I mean, just ask me and I will try my best to make it clear

**Comment by asturur** [comment]
Sorry for not replying.
The images aren't visible anymore, i m not sure what is going here, is not of immediate understanding from the fiddle.
