### ISSUE TITLE
ZoomToPoint does not end with Point as the center

### ISSUE THREAD

**Issue by SridharRamasami** [fabricjs/fabric.js#6643]
I have gone through the discussions here and looks like the zoomToPoint method is named incorrectly.  Others have also run into the same problem.  However, the solution is not clear.

The summary:  I want to zoom to a point P1, so that after the zoom Point P1 is at the center of the canvas.  Github post here.
https://stackoverflow.com/questions/64294770/fabric-js-zoomtopoint-does-not-center-correctly

Thanks

**Comment by asturur** [comment]
why do you think is named incorrectly?

**Comment by SridharRamasami** [comment]
'Zoom to point' in normal English usage means the target point should be at the center.  However the way it seems to be behaving is 'zoom such that the point stays in the same relative position on the canvas'

"The name is misleading a bit." - statement made by you previously :-) https://github.com/fabricjs/fabric.js/issues/2446

**Comment by SridharRamasami** [comment]
I figured out how to do a zoom with a pan and get it to center around a point.  In the code below, newView is a fabric rectangle with the same aspect ratio as the canvas and the ending view will be zoomed in to fit newView and newView will be centered correctly on the canvas.


```

function zoom() {
    var zoom = canvas.getZoom();
    let startValue = newView.getScaledWidth();
    let endValue = canvas.getWidth();
    let totalGrowth = endValue/startValue;
    //console.log('startValue, endValue: '+startValue+", "+endValue);
    let deltaX = -1*newView.aCoords.tl.x;
    let deltaY = -1*newView.aCoords.tl.y;


    fabric.util.animate({
        startValue: startValue,
        endValue: endValue,
        duration: 1000,
        onChange: function(midvalue) {
            let factor = midvalue/(startValue);
            let xyFactor = (factor-1)/(totalGrowth-1)
            self.canvas.setViewportTransform([
                zoom, 
                0, 
                0, 
                zoom,           
                deltaX*xyFactor,
                deltaY*xyFactor
            ]);
            let newZoom = zoom*(factor);
            //console.log('zoomMultiple, xShift: '+factor+', '+deltaXY);
            self.canvas.setZoom(newZoom);
            self.canvas.renderAll();
        },
        onComplete: function() {
            self.canvas.renderAll();
        }
    });

}



```

**Comment by SridharRamasami** [comment]
My main aim was to get the zoom with pan centered on a point to work.  Was able to achieve this, so am going close the ticket.  However, I do think clarification on the docs will be very useful for other users.
