### ISSUE TITLE
object rect is not full show with nagative width or height config

### ISSUE THREAD

**Issue by zsyjx0115** [fabricjs/fabric.js#6647]
## Version
4.2.0

## Test Case
https://jsfiddle.net/jiaqn/msdb8zpx/16/

## Information about environment
chrome

## Steps to reproduce
make object Rect witj properties:
left= 100
top = 300
width = 60
height = -140
fill = transparent
strokeWidth = 2
stroke= red

## Expected Behavior
show entire rect shape

## Actual Behavior
The rectangle is missing two sides when width or height config is nagative number.
The reactagle is missing when both width and height config is nagative number.

**Comment by asturur** [comment]
width and height needs to be positive numbers.

**Comment by zsyjx0115** [comment]
> width and height needs to be positive numbers.

Canvas rect supports nagative numbers. I wonder why fabric doesn't support it?

**Comment by andrewzolotukhin** [comment]
What is the idea behind using negative numbers? I see no profit, but code sophistication.

**Comment by zsyjx0115** [comment]
> What is the idea behind using negative numbers? I see no profit, but code sophistication.

We create objects by mouse dragging event. The mouse operation will produce points in various directions, and in the coordinate system, the distance between two coordinate points may be negative. 
If negative numbers are not supported, when creating an object, we only can use the upper left corner as the reference point, instread of using the mouse operation starting point.

**Comment by asturur** [comment]
That read as: write more sophisticated code so i can write simpler mouse code.
No we should not.

The distance between 2 points is never negative as a concept. It can't. distances go from 0 up, right?

Your problem is findind the correct top, left for the newly created drag operation, and you can find it with simple math or using the setPositionByOrigin functionalities of fabric.js
