### ISSUE TITLE
v4: 'scaling' event triggered before object position is adjusted

### ISSUE THREAD

**Issue by SLKnutson** [fabricjs/fabric.js#6649]
## Version
4.2.0

## Expected Behavior
The 'scaling' event should be fired after the object position is adjusted to pin to a specific side/corner. That is how fabric behaved pre-v4, and in my opinion, what most people would expect.

## Actual Behavior
The 'scaling' event is triggered after the scale is changed but before the position is adjusted to pin to a specific side/corner.

Thanks!

**Comment by asturur** [comment]
i think you are rigth. this is changed and messy right now.

I m not sure how to fix it at this point.

Probably also half people prefer the old position, half the new. But i agree should be fixed.

**Comment by SLKnutson** [comment]
I'm also running into this issue with rotation. I think skewing also has this issue. I'll take a stab at fixing it.

**Comment by Eltonfjunior** [comment]
Good afternoon.
I am also having the same problem, do you already have any return on this demand?

**Comment by asturur** [comment]
We have a PR, that is fine, but we need to avoid breaking the interface and i did not have a time to sit down and see what is the solution.

https://github.com/fabricjs/fabric.js/pull/6650

**Comment by ShaMan123** [comment]
closed by #6650
