### ISSUE TITLE
Image Clip

### ISSUE THREAD

**Issue by TranQuangMinh** [fabricjs/fabric.js#6652]
Hi
Is there a way to do it like this

![ezgif com-gif-maker](https://user-images.githubusercontent.com/10704241/96289083-a2b09480-100e-11eb-9086-c81d02b26e2a.gif)

**Comment by TranQuangMinh** [comment]
- Dbclick to show image inside,
- Single click to select shape outside

**Comment by juzhiyuan** [comment]
See backgroundImage

**Comment by asturur** [comment]
@TranQuangMinh  you can build something like that using the controls api. and moving events
Is not extremely hard, but i do not have an open source example for it.

**Comment by sssning** [comment]
I have the same problem
