### ISSUE TITLE
Pattern crossOrigin issue

### ISSUE THREAD

**Issue by nasradin07** [fabricjs/fabric.js#6656]
## Version
4.2.0

## Test Case
https://jsfiddle.net/we372y9n/1/

## Information about environment
Google Chrome Version 86.0.4240.80 (Official Build) (x86_64)

## Steps to reproduce
When I use an object with image as pattern (crossOrigin is set for pattern image) object and pattern is loaded as it should. But if I try to use json from toJSON method pattern is not loaded and there is an error in the console (Access to image have been denied).
Also if I try to clone the same object (with pattern applied) I get the same error.
## Expected Behavior
Able to use load FromJSON or clone an object
## Actual Behavior
Error in the console (crossOrigin issue)

**Comment by asturur** [comment]
That image does not have a crossOrigin header set.
You are loading the image without crossOrigin header, but you are setting it on the pattern.
the next time you reload, the code use the crossOrigin value properly but the server does not put the header there.

If you load the pattern in this way, you will notice it errors immediately.
```js
const setPattern = (src, object, ) => {
  fabric.util.loadImage(
    src,
    image => {
      object.set(
        'fill',
        new fabric.Pattern({
          source: image,
          repeat: 'no-repeat',
          crossOrigin: 'anonymous',
        })
      );
      canvas.renderAll();
    },
    null,
    'anonymous'
  );
};
```

**Comment by ebigtm** [comment]
just popping in again with this topic, it worked ok for me on fabric 4.6.1 but when I started using the lastest build i noticed the problem again.

adding image.crossOrigin = 'anonymous' befomr object.set does the job for me!
