### ISSUE TITLE
onMouseMove event firing when no change in pointer (x, y) values (retina

### ISSUE THREAD

**Issue by sjscotti** [fabricjs/fabric.js#6659]
## Version
4.1.0

## Test Case
difficult to create standalone case, but it should be easy to check if it is a real bug

## Information about environment
Browser
Which browsers?
I use Chrome

## Steps to reproduce
I have a complex drawing app under development based on fabric.js where I have added some externally defined brushes to be called from fabric.js.  One brush recently added uses the prior pointer position value along with the current pointer position that are passed in from `onMouseMove` calls from fabric.js.  It works fine on desktop and laptop, but I was getting strange behavior on iPhone.  I have `enableRetinaScaling` set to `false` on mobile calls to the app.  I traced the problem to `onMouseMove` calls where the pointer value isn't changing.  

## Expected Behavior
I expected that `onMouseMove` would only be called when the pointer value passed to it changes.

## Actual Behavior
It was an easy fix by adding a check on the pointer passed into `onMouseMove`  to ensure it has changed from the last call before taking the next steps within the brush.  However, isn't this a bug that occurs when not using Retina Scaling, and shouldn't the check be within fabric.js so that `onMouseMove` isn't called when the value passed to `onMouseMove` hasn't changed?

**Comment by asturur** [comment]
probably because the high dpi setting, for a move event there isn't any css pixel movement. We can't do much about it, an event has been fired from the browser.
