### ISSUE TITLE
Can't hide `ml` and `mr` controls

### ISSUE THREAD

**Issue by ickata** [fabricjs/fabric.js#6660]
## Version
4.2.0

## Test Case
https://codepen.io/ickata/pen/LYZRgoz

## Information about environment
Latest Chrome

## Steps to reproduce
Try to hide all object controls:

```js
Object.values(fabric.Object.prototype.controls).forEach(c => c.visible = false);
```

## Expected Behavior
On object selection all controls are invisible

## Actual Behavior
On object selection middle left and middle right controls are still visible

**Comment by asturur** [comment]
The Textbox has its own control objects.
You can either cycle over that, or you can create your own object where you reference all the controls of all the prototype.
So far Textbox is the only exception
