### ISSUE TITLE
Json Generate standard ?

### ISSUE THREAD

**Issue by VincentVallee** [fabricjs/fabric.js#6662]
- I use fabric.js for an application with an api and Angular front.
 I trying to send at my API the canvas in JSON format, but  I would like to know if json is standard or is format specifically for fabric.js.

May I use with other library or other front device (mobile, etc ...)

Sorry for my english.

Thank you

**Comment by asturur** [comment]
those jsons are fabricjs specific. There isn't any standard out there for serializable object based canvas api.
