### ISSUE TITLE
image positioning 

### ISSUE THREAD

**Issue by sssning** [fabricjs/fabric.js#6663]
I only want to display a certain part of the image, but the size does not change. What should I do

**Comment by asturur** [comment]
Please try to explain what are you trying to do more clearly.

**Comment by sssning** [comment]
> Please try to explain what are you trying to do more clearly.

**Comment by sssning** [comment]
- 
![QQ图片20201025223314](https://user-images.githubusercontent.com/33438521/97110135-6a960980-1712-11eb-919f-8a1555e9e426.png)

The cropped image shows only the cropped part. I want to be able to automatically fill in the size of the original image. What should I do

**Comment by asturur** [comment]
You have to start showing how you are cropping the image, in a jsfiddle or a codepen.

**Comment by asturur** [comment]
Issue will be closed until a jsfiddle is added to this issue.
New issues for the same topic will be linked here and closed automatically.
