### ISSUE TITLE
loadSVGFromString v1.5.0 vs v4.2.0

### ISSUE THREAD

**Issue by wufangjian** [fabricjs/fabric.js#6664]
###  version: v4.2.0 not work
[http://jsfiddle.net/boyi/ewo6573u/136/](http://jsfiddle.net/boyi/ewo6573u/136/)
![image](https://user-images.githubusercontent.com/6982055/96839338-9e0b3680-147b-11eb-8b5c-c6870de63b0a.png)

### version: v1.5.0
[http://jsfiddle.net/boyi/xpz9dcbw/137/](http://jsfiddle.net/boyi/xpz9dcbw/137/)
![image](https://user-images.githubusercontent.com/6982055/96839070-410f8080-147b-11eb-9966-0365a592c6e0.png)

**Comment by asturur** [comment]
Can you provide a full SVG that loads in the browser?
That one can't load in chrome, or load invisible.
