### ISSUE TITLE
In multi-select  mode custom control doesn't work, when set canvas.perPixelTargetFind = true

### ISSUE THREAD

**Issue by gxlinhai** [fabricjs/fabric.js#6666]
## Version
4.2.0

## Test Case
http://jsfiddle.net/gxlinhai/x6ocarv5/#&togetherjs=43BOPyLI3u

## Information about environment
Nodejs or browser?
Which browsers?

## Steps to reproduce

- Add 2 rectangles.

- Select them

**Comment by sxq111** [comment]
I have this problem too

**Comment by asturur** [comment]
Let me see if i can dig into this and fix it today

**Comment by asturur** [comment]
this has been fixed with recent commits.
Please take care that controls actions were wrong, and had incorrect signature. This has been fixed and the demos updated to reflect that.
