### ISSUE TITLE
image size doesn't fit the fabric.image element since v4.1.0

### ISSUE THREAD

**Issue by zhengqingxin** [fabricjs/fabric.js#6667]
## Version
4.2.0

## Test Case
https://jsfiddle.net/25kn18jo/1/

## Information about environment
source image can't fit size with the fabric.Image  since version 4.1.0

## Steps to reproduce
![image](https://user-images.githubusercontent.com/18438156/97001652-4cda7000-156b-11eb-8849-8a50548cb40b.png)

**Comment by melchiar** [comment]
You're defining your image object with the dimensions 700x500 when your source image is only 500x330. You should use the `scaleX` and `scaleY` properties to size your object. 

See http://fabricjs.com/docs/fabric.Image.html#scaleToWidth
