### ISSUE TITLE
intermittent "null is not an object" error on Safari

### ISSUE THREAD

**Issue by SkyJedi** [fabricjs/fabric.js#6668]
## Version
3.6.0

We keep getting this intermittent error on Safari with calling canvas.renderAll().  There is a try/catch before to ensure that canvas has correctly initialized.

## Information about environment
Safari

http://jsfiddle.net/skyjedi/54w1eunL/

![image](https://user-images.githubusercontent.com/2967416/97087516-6245ad80-15f0-11eb-9f80-28dcc28176e5.png)

**Comment by melchiar** [comment]
Please post a fiddle demonstrating the problem as per the issue guidelines

**Comment by SkyJedi** [comment]
http://jsfiddle.net/skyjedi/54w1eunL/48/

**Comment by asturur** [comment]
The fiddle you opened is based on fabric 1.5, while the error you show here is with webgl, not available before 2.0
Are you sure the error happens in the fiddle in safari?
If it is, it may be something different.

**Comment by SkyJedi** [comment]
Hold up, that's me not understanding fiddle

**Comment by SkyJedi** [comment]
Simplified fiddle that is giving me a error when a filter is applied
```
Uncaught (in promise) DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': Tainted canvases may not be loaded.
    at WebglFilterBackend.createTexture 
```

http://jsfiddle.net/skyjedi/73wLtqp1/

**Comment by SkyJedi** [comment]
https://jsfiddle.net/skyjedi/fh0atru4/ me trying to hit the safari memory limit
