### ISSUE TITLE
unable to completely remove default text in an IText or TextBox

### ISSUE THREAD

**Issue by adrienpoly** [fabricjs/fabric.js#6670]
## Version
4.2.0

## Test Case
https://codesandbox.io/s/fabric-erase-default-text-udoww?file=/src/index.js

## Information about environment
browser?
Which browsers? all

## Steps to reproduce
I have a function to clear the default text on entering the the text box
```js
canvas.on("text:editing:entered", clearText);

function clearText(e) {
  if (e.target.type === "i-text") {
    if (e.target.text === "Tap and Type") {
      e.target.text = "";
      canvas.renderAll();
    };
  }
}
```
tap and type a new text

## Expected Behavior
the text should be erased and only the new text should be written in the textbox

## Actual Behavior
The old text keeps coming back
![Kapture 2020-10-30 at 08 02 46](https://user-images.githubusercontent.com/7847244/97670366-57729900-1a86-11eb-9635-a32bc2028067.gif)

I tried setting as per some issues I read but no luck

```js
e.target._forceClearCache = true
e.target.dirty = true
```

Thanks for your help

**Comment by adrienpoly** [comment]
I found a ugly hack to make it work by leaving and entering back into the box...

but I hope there is a better solution

```js
e.target.text = "";
e.target.exitEditing()
e.target.enterEditing()
this.canvas.renderAll()
```

**Comment by adrienpoly** [comment]
I found a cleaner solution by looking at the code of `enterEditing`
you need to set the `hiddenTextarea` value too

```js
function clearText(e) {
  if (e.target.type === "i-text") {
    if (e.target.text === "Tap and Type") {
      e.target.text = "";
      e.target.hiddenTextarea.value = '';  // NEW
      canvas.renderAll();
    };
  }
}
```

Closing this issue for now

**Comment by asturur** [comment]
Hi @adrienpoly, sorry for not answering before today.
When editing the hiddenTextarea value is the one that is driving the final value, so yes, you have to modify that or the next input will reset everything.

**Comment by adrienpoly** [comment]
Thanks for confirming it

**Comment by aguywastedtime** [comment]
oh.. this was taking me 4hrs to find this solution, thank you @adrienpoly 
I can't believe setting the text to empty is not clearing the text @@. This one should be documented well

**Comment by sn3p** [comment]
Would indeed expect clearing the text would clear the hidden input as well.
Thanks for the workaround!
