### ISSUE TITLE
Loosing pixels when copying parts of an image from a canvas

### ISSUE THREAD

**Issue by udgithub** [fabricjs/fabric.js#6673]
## Version
4.0.3

## Test Case
https://services.bibliothek.kit.edu/uwe/canvas/bug/bug-demo-1.html

## Information about environment
All browsers

## Steps to reproduce
click the demo1 .. demo4 buttons.

## Expected Behavior
The top canvas (copierd rect) should contain a rect with width == width of the original image and heigth = 200 pixel from the original image (top or bottom) 

## Actual Behavior
A couple of pixels from the right side and the bottom side are missing.
Depending on the screen resolution / it's DPI the number of missing pixels is higher or lower.

**Comment by melchiar** [comment]
Hi! Please provide a jsfiddle showing the problem as per the issue guidelines.
