### ISSUE TITLE
drag and drop working but not showing full image in cansav

### ISSUE THREAD

**Issue by subhash8108** [fabricjs/fabric.js#6676]
## Version
Fabricjs 4.2.0

## Test Case
https://jsfiddle.net/natchiketa/w8kkc/

## Issue
drag and drop working but not showing full image on cansav

## Working Version - 1.7.6
**It's working - 1.7.6 version**
<script src='https://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.7.6/fabric.min.js'></script>

## Not Working Version - 4.2.0
**Not working - 4.2.0 version**
<script src='https://cdnjs.cloudflare.com/ajax/libs/fabric.js/4.2.0/fabric.js'></script>

Please help me how to resolve this issue.

## Screen shot
![working](https://user-images.githubusercontent.com/542535/98081325-e9224200-1e9c-11eb-8f6c-f9e0478c619d.png)
![not-working](https://user-images.githubusercontent.com/542535/98081328-eb849c00-1e9c-11eb-8460-4c916dcfde6f.png)

**Comment by melchiar** [comment]
Version 2 changed the way image width/height is handled in order to support cropping.

See http://fabricjs.com/v2-breaking-changes#image

**Comment by subhash8108** [comment]
Thanks for reply.

Ok, I see the fabric.js file but how to handle without cropping image set in canvas.

My code:
fabric.Image.fromObject(img, function(obj) {
			  canvas.add(obj) // <- like this
			  console.log('newGroup', obj)
			  canvas.setActiveObject(obj).renderAll();
			  debugger;
			})

**Comment by subhash8108** [comment]
> Version 2 changed the way image width/height is handled in order to support cropping.
> 
> See http://fabricjs.com/v2-breaking-changes#image

Thanks for reply.

Ok, I see the fabric.js file but how to handle without cropping image set in canvas.

My code:
fabric.Image.fromObject(img, function(obj) {
			  canvas.add(obj) // <- like this
			  console.log('newGroup', obj)
			  canvas.setActiveObject(obj).renderAll();
			  debugger;
			})

**Comment by melchiar** [comment]
Image size is controlled using `scaleX` and `scaleY`. There are also methods to help scale an image to a desired width.

http://fabricjs.com/docs/fabric.Image.html#scaleToWidth
http://fabricjs.com/docs/fabric.Image.html#scaleToHeight
