### ISSUE TITLE
originX and originY used to support numeric values

### ISSUE THREAD

**Issue by virror** [fabricjs/fabric.js#6677]
## Version
4.2.0

## Steps to reproduce
set originX or originY to a numerical value.
Rotate the object.

## Expected Behavior
Object should rotate around the custom inputted value.

## Actual Behavior
Rotates around the top left (default)

My application relies on this for a lot of stuff and now it just stopped working when i upgraded : (

**Comment by asturur** [comment]
This is unexpected.
Can you open a fiddle to show the issue?

**Comment by virror** [comment]
Sorry, i was to quick to post this, it seems to work fine when i tested it again.
