### ISSUE TITLE
Setting "quality" when performing "cloneAsImage" has no effect

### ISSUE THREAD

**Issue by GillesVermeulen** [fabricjs/fabric.js#6678]
Hi,

When performing "[cloneAsImage](http://fabricjs.com/docs/fabric.Object.html#cloneAsImage)" on an object, the "quality" option is ignored, often leading to an increase in size compared to the original image.

I created a Codepen to illustrate the issue:
https://codepen.io/gillesv/pen/abZjLZG

As you can see, the cloneAsImage function respects the format ('jpeg'), but ignores the quality option.

Older versions of Fabric.js did seem to respect the quality setting, as seen in this JSFiddle I found and edited:
https://jsfiddle.net/uqh30rf2/3/

Am I doing something wrong? Or is the quality option not used anymore?

**Comment by GillesVermeulen** [comment]
I don't think this should be closed, because it's either an issue in the code or in the documentation. The quality option is most certainly ignored.

I updated my Codepen and added the Parcel v1 way of performing "cloneAsImage" next to the v2 way:
https://codepen.io/gillesv/pen/abZjLZG

In Parcel v2, the "cloneAsImage" method says it accepts the "quality" option, but the method mostly just calls "toCanvasElement" and passes the options object, but the "toCanvasElement" doesn't seem to do anything with the quality option.

**Comment by asturur** [comment]
cloneAsImage is cloning the object as an ImageObject, it does not say anything about the image being a jpg, a png or a canvas.
If quality is mentioned in the docs, it should be removed.

If you want to have a real image from the canvas, you will need then to call toDataUrl, that accept quality, and that before was done automatically on cloning.

**Comment by GillesVermeulen** [comment]
> cloneAsImage is cloning the object as an ImageObject, it does not say anything about the image being a jpg, a png or a canvas.
> If quality is mentioned in the docs, it should be removed.
> 
> If you want to have a real image from the canvas, you will need then to call toDataUrl, that accept quality, and that before was done automatically on cloning.

That makes sense. Thanks for clearing things up. In the meantime I had already started using toDataUrl to reach my goal. A change in documentation would indeed prevent further confusion.
