### ISSUE TITLE
centeredRotation is not taken into account for rotation handle

### ISSUE THREAD

**Issue by virror** [fabricjs/fabric.js#6679]
## Version
4.2.0

## Test Case
http://jsfiddle.net/qkpf3abu/1/

## Steps to reproduce
Run the fiddle
Select the Rect and rotate it

## Expected Behavior
Since centeredRotation is set to false, i expect it to rotate around the top/left corner.

## Actual Behavior
It always rotates around the center

**Comment by virror** [comment]
Seems to work correctly when setting the rotation from code though, just the rotation handle thats broken.

**Comment by asturur** [comment]
Your canvas has centeredRotation set to false too, right?

**Comment by asturur** [comment]
This seems a bug.
Would you try to remove this if condition here:

https://github.com/fabricjs/fabric.js/blob/f80dffc12abb8d9affadc8a774efb3f34355c862/src/canvas.class.js#L611

And see how it behaves for rotation?
In case you can open a PR.

**Comment by virror** [comment]
Yes, removing that whole block (3 lines) fixes the issue.
Thank you for looking into this : )
Will make a pr

**Comment by virror** [comment]
Investigating this some more it seems to be more issues related to centeredRotation.
When setting it to false, the handle behaves as expected, but then rotating from code is broken instead.
See this new fiddle with a rotate button:
http://jsfiddle.net/jtec0L2y/2/

Try and change centeredRotation to both true and false and you will see the button always rotates the cube with the corner as its center.

Should i still make a pr for the first issue?

**Comment by asturur** [comment]
Hi Victor,
the `code rotation` isn't a rotation. Is just changing the angle value, that may seems the same thing but it isn't.
When you change the angle, you are just changing the angle, i know is sounds dumb as statement.

Top and Left aren't changed, and they stay where they are, so what you see is a rotation by the origin of the position, that may be different from the transform origin.

In my opinion we should remove that 3 lines of code, and verify that manual interactions work as epxected.

**Comment by virror** [comment]
Ok!
I will make pr with that fix then.
So just to confirm, there is no api for rotating around the origin and thats correct?

**Comment by asturur** [comment]
There is object.rotate, that is essentially what you want i think.

```js
    /**
     * Sets "angle" of an instance with centered rotation
     * @param {Number} angle Angle value (in degrees)
     * @return {fabric.Object} thisArg
     * @chainable
     */
    rotate: function(angle) {
      var shouldCenterOrigin = (this.originX !== 'center' || this.originY !== 'center') && this.centeredRotation;

      if (shouldCenterOrigin) {
        this._setOriginToCenter();
      }

      this.set('angle', angle);

      if (shouldCenterOrigin) {
        this._resetOrigin();
      }

      return this;
    },
```

**Comment by virror** [comment]
Makes so much sense! No issue then : )

**Comment by virror** [comment]
See:
https://github.com/fabricjs/fabric.js/pull/6686
