### ISSUE TITLE
Arguments are incorrectly documented for mouseDownHandler in custom control point

### ISSUE THREAD

**Issue by DanielPower** [fabricjs/fabric.js#6682]
## Version
4.2.0

Docstring states this order of arguments.

#### fabric.js/src/control.class.js 
`mouseDownHandler: function(/* eventData, transformData, fabricObject */) { },`

However these arguments are actually passed in:

#### fabric.js/src/mixins/canvas_events.mixin.js
`mouseDownHandler = control && control.getMouseDownHandler(e, target, control);`

Additionally, `getMouseDownHandler` is documented as having the same arguments, despite being a simple getter, and not using any of the arguments.

**Comment by asturur** [comment]
oh needs to be fixed then.
You can open a pr if you want, or all i do at next occasion

**Comment by DanielPower** [comment]
@asturur could you add a documentation label to this so it doesn't get closed?
