### ISSUE TITLE
the Textbox can not set writingMode

### ISSUE THREAD

**Issue by heythanks** [fabricjs/fabric.js#6683]
the textbox may be mutil-line text, and i want to change this direction, the text can be top to bottom, just like the css attribute 【writingMode: 'vertical-lr'】, how can i do this feature, thanks for your help!
var mytxt =  new fabric.Textbox(text || 'Lorum ipsum dolor sit amet', {
          left: 50,
          top: 50,
          width: 20,
          fontSize: 20,
          writingMode: 'vertical-lr' //no any change
        });

**Comment by asturur** [comment]
textbox does not support vertical text. Implementing this isn't really trivial, you can try if you have some experience with fabricjs.
Putting up a pr for that is a complex process tho

**Comment by heythanks** [comment]
> textbox does not support vertical text. Implementing this isn't really trivial, you can try if you have some experience with fabricjs.
> Putting up a pr for that is a complex process tho

thanks for you replay!  I meeted a new  problem，I create a textbox and export tosvg, i use loadSVGFromString import svg content, this textbox's position has changed. this is a issue,  do you have a schedule for repairs, Looking forward to your reply！
