### ISSUE TITLE
Transform active selection without affecting specific objects

### ISSUE THREAD

**Issue by gkopowski** [fabricjs/fabric.js#6685]
Hello, is it possible to transform (scale, rotate, move) an Active Selection without affecting specific objects? For example I've selected four objects and one of them is locked in every way (lockScalingX, lockScalingY, lockScalingFlip, lockMovementX, lockMovementY, lockRotation, lockSkewingX, lockSkewingY all set to true), but when I'm for example moving that Active Selection, the locked object also moves. Instead of that I would like to keep that locked object in the same place and move only the rest of the selected objects (the same for rotating and scaling). Which parts of the fabric code should I override to achieve this? Or maybe it can be easily achieved using some object property?

I'm using fabric `3.6.6`.

Thanks!

**Comment by asturur** [comment]
when you lock an object selecting all the property for locking it, you can also give it a `onSelect` callback that will run some logic for the selection.
You can try to not have it selected in the multi selections for example, but once is on the group selection it will move with it.

**Comment by gkopowski** [comment]
I have such logic right now - I'm excluding these objects from multi selection but I need to change it in the way I described. The group selection is not a problem. I need to do this only for Active Selection. Thanks

**Comment by asturur** [comment]
Once they are active selected, they will move with the selection, no way around it.
Unless you want to rewrite a big chunk of the library.

**Comment by gkopowski** [comment]
Thanks @asturur 
This is how I handled it: on `before:transform` event I'm removing all locked objects from the active selection and after the transformation is complete I'm adding them back to the active selection. I did it for rotate, scale and drag actions and it works pretty good.
