### ISSUE TITLE
Best practice to modify single chars of itext

### ISSUE THREAD

**Issue by Timoostrich** [fabricjs/fabric.js#6687]
I need to manipulate the single letters of an itext box (position, rotation, size).
It's okay, if the text can not be edited after the manipulation anymore.

What I tried was to create a group with single char text objects, to work on with that group.
I used the __charBounds array to get the positions of the letters, but that does not seem to be the correct way to do it.
The group of chars does not look exactly like my itext box...

Before I keep on working on that I wanted to know, if it's the right way to do it?
Or is there a better way to handle that problem?

This is my current function:

`//Split word to single objects
function splitWord(){
	var obj = canvas.getActiveObject();

	//Get array of single chars and charbounds
	var array_of_chars = obj._text;
	var array_of_charbounds = obj.__charBounds[0];

	//Create group for the full word
	var group = new fabric.Group([],{selectable: true, evented: true, excludeFromExport: true, height: obj.height, fill: obj.fill, scaleX: obj.scaleX, scaleY: obj.scaleY});

	//Create chars as single objects in group
	for (let i = 0; i < array_of_chars.length; i++) {
		var char = array_of_chars[i];
		var text = new fabric.Text(char, {left: array_of_charbounds[i].left, top: 0, width: array_of_charbounds[i].width, fontFamily: obj.fontFamily});
		group.add(text);
	}
	
	//Update group to recalc dimensions
	group.addWithUpdate();

	//Add to canvas
	canvas.add(group);
}`

Thanks!

**Comment by asturur** [comment]
i would expect it to work more or less.
Can you post a working fiddle of what you tried so far?

**Comment by Timoostrich** [comment]
I just created a little pen: https://codepen.io/timothy90/pen/eYZPjjv
The first word is the original one, the second one is the group of single chars.
Thanks again for having a look!

**Comment by Timoostrich** [comment]
Any ideas on that? Or other ways to do it?
