### ISSUE TITLE
Dblclick event listener on fabric.Canvas parent container is not working on mobile

### ISSUE THREAD

**Issue by varyzheng** [fabricjs/fabric.js#6689]
## Version
4.2.0
## Information about environment
Browser

## Steps to reproduce
```html
<div id="container">
  <canvas id="canvas></canvas>
</div>
```
```js
const container = document.querySelector('#container')
const canvas = document.querySelector('#canvas')
const fabricCanvas = new fabric.Canvas(canvas);
container.addEventListener('dblclick', () => { alert(false); }, false);
container.addEventListener('dblclick', () => { alert(true); }, true);
```

## Expected Behavior
Alert true and alert false, works well on every platform
## Actual Behavior
It works well on PC, and not working on mobile.
But if I add the code below:
```js
fabricCanvas.removeListeners();
```
mobile can alert true and false. Seems that event system in fabric changed mobile touch event, so that mobile cannot fire dblclick event correctly.
But if I listen `touchstart`, `touchend`, or `touchmove`, It works well. Only `dblclick` is not working on mobile.

**Comment by asturur** [comment]
I m not sure how 'dblclick' fires on mobile. Are you executing it with a mouse on a phone ( on android is possible ) or doing it with the fingers?
On how many phones did you try and which operating systems?
