### ISSUE TITLE
Deep cloning of objects.

### ISSUE THREAD

**Issue by aleph1** [fabricjs/fabric.js#669]
When cloning an image the filters object is shared between clones. It would be nice if we could add the ability to do a deep clone like is possible with jQuery.extend to create a true clone of the object.

http://jsfiddle.net/LNhRR/2/

What if I modified the following functions in fabric.util.object:

extend ( destination, source, deep )
clone ( object, deep )

I suspect some of the shape classes would also need modifying to pass the deep parameter to the clone function.

Any guidance on this before I work on implementing it?

**Comment by abhi06991** [comment]
I have list of image filters check boxes through which users can apply different filters for an image and when a user clicks on a particular image in the canvas, I check whether there are any filters applied to that image and update the checkboxes accordingly. Here the problem is when an image is cloned, the image filters applied or removed is shared between the images,so I am not able to correctly update the checkboxes. Anything that can be done?

**Comment by asturur** [comment]
Can you share a jsfiddle with a image + filters and the cloning code? i think they should not be shared, filters have theyr own toObject() method.

**Comment by abhi06991** [comment]
This is the cloning code that I am using. I am using the latest version of Fabric.js
`
	var object = fabric.util.object.clone(_canvasObject.getActiveObject());
       object.set("top", object.top+10);
       object.set("left", object.left+10);
       _canvasObject.add(object);
       _canvasObject.renderAll();
		 `

**Comment by xRokco** [comment]
I am also having this issue. I have code to set the filters on an image, taken from the Fabric demo pages -

```
$('.filters').on("change", "input", function () {
    var isChecked = $(this).prop("checked");
    var filter = $(this).data("filter");
    var obj = canvas.getActiveObject();
        
    obj.filters[filter] = isChecked ? filters[filter] : null;
    obj.applyFilters(function () {
        canvas.renderAll();
    });
});
```

I also have some copy/cut and paste objects code, the copy code -
```
clipboard = [];
var o = canvas.getActiveObject();
clipboard[0] =  fabric.util.object.clone(o);
clipboard[0].id = clipboard[0].id + " copy";
```

I also have a version to copy groups which works in pretty much the same way.
Any copies of an image object share filters, though, meaning that the checkboxes to apply filters displays the wrong things, similar to @abhi06991, but also, exporting the canvas to JSON sets all copied objects to have the same filters.

Is there another/better way to clone images so this doesn't happen?
Thanks.
