### ISSUE TITLE
Copy / Paste text becomes blurry

### ISSUE THREAD

**Issue by cloke** [fabricjs/fabric.js#6691]
## Version
Tested on 4.2.0

## Test Case
http://fabricjs.com - I understand a fiddle is desired, but this can easily be seen from the main web page. See screenshot at bottom of issue. 

## Information about environment
Tested on latest versions of Safari and Chrome

## Steps to reproduce
1. Visit http://fabricjs.com
2. Place cursor in main text area of demo text.
3. Do command-a to select all text.
4. Do command-v to paste text. 
5. Continue to paste text and as th element has more text it becomes more blurry. This will also happen if you just paste in a lot of text from an external source. 
6. If I type the text by hand the issue does not appear to happen. 

## Expected Behavior
The text would remain crisp and clear as if I typed it in by hand. 

## Actual Behavior

Unreadable text
<img width="993" alt="Screen Shot 2020-11-13 at 2 00 10 PM" src="https://user-images.githubusercontent.com/15304/99111245-c1785b80-25b9-11eb-8abe-6742b4f3c799.png">

**Comment by asturur** [comment]
http://fabricjs.com/fabric-object-caching

Have a read at this page, and check which are the possible workarounds.

**Comment by asturur** [comment]
I'm closing the issue here, i m here to talk if you have questions/comments, but there isn't a bug or something to address for now.

**Comment by cloke** [comment]
Thank you for looking. FWIW our use case is we have a system that can play back text like credits that scroll by in a movie. Right now we put them in a Textbook and animate the textbox. When the user pastes 4000 names into the text box the blur became very noticeable. I'll play around with some of the stuff mentioned on the linked page. I also have an alternative option for solving this by requiring the text to be pasted into a text area and the we just programmatically stack a bunch of grouped text boxes that we generate behind the scenes.

**Comment by asturur** [comment]
You can just disable the caching or make the caching bigger using the properties in the doc i linked.

You can also just disable the caching and then use myTextbox.toImage(), and then animate the image that is faster compared to a textbox with 100k chars.
