### ISSUE TITLE
关于基于此框架开发出来的web平台的 室内平面地图编辑器，并利用canvas的toJSON()转成geojson数据格式

### ISSUE THREAD

**Issue by XieWuHen** [fabricjs/fabric.js#6692]
**我这提议很有挑战性，目前我正在往这个方向独自开发，希望能得到帮助，有没有人愿意帮忙？**

**Comment by asturur** [comment]
Hi @XieWuHen no one speak chinese here, would you mind using english? So someone can help

**Comment by XieWuHen** [comment]
Based on this framework, the indoor plane map editor of web platform is developed and transformed into geojson data format by using tojson () of canvas

**Comment by XieWuHen** [comment]
My proposal is very challenging, and I'm working on it alone in this direction

**Comment by asturur** [comment]
So i can close the issue. You can still post here updates or questions.
