### ISSUE TITLE
Need to have a drawable bounding-rect around text and other shapes

### ISSUE THREAD

**Issue by nbaua** [fabricjs/fabric.js#6693]
**Is your feature request related to a problem? Please describe.**
We are trying to accomplish drawing shapes with boundaries/borders around it.
our primary requirement was to have a rounded button, which we did with grouping 2 shapes.
now we want to have a similar feature with text labels where we need a border around it.
(we would be okay if there is no round border)

**Describe the solution you'd like**
We would like to have a property similar to stroke with width and color property,
say a property like **outline** : { **outlineWidth**: 2px, **outlineColor**:red, **outlineOpacity**:0.3}

**Describe alternatives you've considered**
We tried to use stroke, however it is not we are looking for.

**Additional context**
**We are getting** results like this (we can not share actual image because of the non-disclosure agreement on project)

![image](https://user-images.githubusercontent.com/17998763/99164403-446cf380-272b-11eb-8a43-a5b76412bb15.png)

OR
![image](https://user-images.githubusercontent.com/17998763/99177639-b3e5e180-2731-11eb-821d-c440b295d2bc.png)

**However what we need is something like WITHOUT combining multiple objects or shapes**

![image](https://user-images.githubusercontent.com/17998763/99177645-d1b34680-2731-11eb-8bfc-076c638901cf.png)
AND
![image](https://user-images.githubusercontent.com/17998763/99177652-db3cae80-2731-11eb-81bf-1222ca9ba8c2.png)

**Comment by asturur** [comment]
Not combining 2 shapes seems a requirement that dictates how code has to be written to get to the desired goal.
What's the point behind not having 2 shapes combined?

**Comment by asturur** [comment]
regarding this:
![image](https://user-images.githubusercontent.com/1194048/99180379-fdc8ca80-2725-11eb-8dda-2510a7185bf5.png)

This is because fonts aren't created for such big strokes. You can fix this using the property: `strokeLineJoin` set to round. That will eliminate the spikes.

**Comment by nbaua** [comment]
> regarding this:
> ![image](https://user-images.githubusercontent.com/1194048/99180379-fdc8ca80-2725-11eb-8dda-2510a7185bf5.png)
> 
> This is because fonts aren't created for such big strokes. You can fix this using the property: `strokeLineJoin` set to round. That will eliminate the spikes.

Hi,
Apologies for delayed reply, I am not worried about the spikes of the text here, What we require is the bounding rectangle as an OUTLINE to the entire shape.

If you refer to the example:
http://fabricjs.com/stroke-uniform

The stroke property is around each shape (see below).
![image](https://user-images.githubusercontent.com/17998763/99511589-7641bc80-29ae-11eb-9b43-f8c6a338299f.png)

However what we require is a little different,
We want to group these controls and want to have a OUTLINE property with width and color/opacity options.

![image](https://user-images.githubusercontent.com/17998763/99512124-20b9df80-29af-11eb-820f-efbbd09bf9e3.png)

same applies to text or any other shape

![image](https://user-images.githubusercontent.com/17998763/99512291-49da7000-29af-11eb-96a3-33c606617026.png)

Can you please suggest how we can extend the group with this custom property OUTLINE or something, which we can toggle when not needed?
Thanks
