### ISSUE TITLE
SVG does not have original animation/interaction after being converted to fabric object

### ISSUE THREAD

**Issue by liukexina** [fabricjs/fabric.js#6694]
## Version
4.2.0

## Test Case
https://codesandbox.io/s/twilight-haze-dw825?file=/src/App.js

## Steps to reproduce
In the project, I want to convert the svg into a fabric object, where the svg is an animated svg generated by the G2 chart library
```js
var svgEl = document.body.getElementsByTagName("svg")[0];
var serializer = new XMLSerializer();
var svgStr = serializer.serializeToString(svgEl);
var path = fabric.loadSVGFromString(svgStr, function (objects, options) {
      var obj = fabric.util.groupSVGElements(objects, options);
      obj
        .scaleToHeight(canvas.height - 10)
        .set({ left: 0, top: 0 })
        .setCoords();
      canvas.add(obj).renderAll();
});
```
## Expected Behavior
The converted fabric animation/interaction fails, causing the svg to not achieve the desired effect
![image](https://user-images.githubusercontent.com/37728461/99211489-5e7a0500-2803-11eb-8d59-acc1686a771d.png)

## Actual Behavior
Animation/interaction effects still exist after svg conversion, rendering is normal

**Comment by asturur** [comment]
We do not have a parser for animations, and we won't have for interactions.
We would not mind having one to import/export animations to svg

**Comment by liukexina** [comment]
Okay, thank you for your answer
