### ISSUE TITLE
store objects in a hashmap [suggestion]

### ISSUE THREAD

**Issue by JSmithOner** [fabricjs/fabric.js#6695]
Tell me if I'm wrong but Fabric.js is storing objects inside the `_objects` variable and removed via the `remove` function.
remove function is searching through each and every objects present in the array to find the particular index of an object which makes it's O(n) complexity time to remove 1 object.
I was wondering why the objects are not stored in an hashmap with a unique id per object.
Wouldn't this improve process especially for canvas with loads of objects. Just an idea and a suggestion as well if I'm correct.
This would also permit to make built-in functions such as `canvas.getObjectById(uid)`

**Comment by JSmithOner** [comment]
After thinking to this I realized thats objects where displayed depending on there position in the `_objects` array. Still isn't that possible to try to used ordered hashmap. tell me if I'm wrong but `Map()` object retrieves elements in the order they were added. In some sense this would perhaps be difficult to rebuild the map each time. Was that a stupid suggestion? I know you may have urgent issues to deal with but a short answer would be helpful. Thanks in advance!!!

**Comment by asturur** [comment]
The objects array is optimized for looping, and bottlenecks are a bit everywhere.
add/removing an object isn't a big issue for the library.
Adding an object in a particular part of the array is a simple task anyone can do, while i m not sure how would you do that with maps.

**Comment by JSmithOner** [comment]
@asturur thank you for your answer
