### ISSUE TITLE
why active object is always shown on top?

### ISSUE THREAD

**Issue by XieWuHen** [fabricjs/fabric.js#6696]
## Version
3.6.0

## my code:
`canvas.moveTo(bigObject, 0);`

**I have set the level of a large element to 0 in this way. However, after adding other elements and clicking on the large element, it will still be at the top level, blocking the elements added later. I want this large element to be at the bottom forever, but it can't be set as the background, because I have to move it.How to solve this problem?**

**Comment by melchiar** [comment]
The setting you want is `preserveObjectStacking = true`

http://fabricjs.com/docs/fabric.Canvas.html#preserveObjectStacking
https://stackoverflow.com/questions/61079849/in-fabricjs-how-do-i-stop-object-from-jumping-to-top-on-selection
