### ISSUE TITLE
[Documentation] Canvas.toJSON reported as returning string, actually returns object

### ISSUE THREAD

**Issue by DanielPower** [fabricjs/fabric.js#6697]
## Version
master

![Screen Shot 2020-11-16 at 3 03 56 PM](https://user-images.githubusercontent.com/12166320/99293972-f7b61500-281d-11eb-8005-649d047696e0.jpg)

Notice that `fabric.StaticCanvas.prototype.toJSON` is just an alias for `fabric.StaticCanvas.prototype.toObject`. Meaning it returns an object, not a string.

So either the documentation should be changed to report that it returns an object. Or, the function should be updated to actually return a JSON string instead of an object.

**Comment by asturur** [comment]
Definitely doc need fixes.

**Comment by DanielPower** [comment]
Out of curiosity, if toJSON is just an alias for toObject, should one of the functions be deprecated? Is one just being maintained for historical purposes? Or is there a difference that gets defined elsewhere or on a subclass?

**Comment by asturur** [comment]
the function is toObject, toJSON is an alias of convenience, because if you call JSON.stringify over a javascript object or class, the api will verify if a toJSON method exists and call it.
