### ISSUE TITLE
Need more events and states for fabric.Control

### ISSUE THREAD

**Issue by hamzawain7** [fabricjs/fabric.js#6699]
**Is your feature request related to a problem? Please describe.**
I can't change UI of controls on hover and when selected

**Describe the solution you'd like**
Maybe add mouse:over, mouse:out events and isActive flag to fabric.Control too

**Describe alternatives you've considered**
I tried using mousedown and mouseup for detecting whether a control was active but that can't be used as mouseup doesn't fire
if control loses activeness while mouse is outside the control

**Additional context**
Love your new control class, helps me alot to create custom controls

**Comment by asturur** [comment]
@hamzawain7 if you could explain clearly what are you trying to do, and that the api isn't flexible enough to allow you, i can then think of a solution with the current code or think of a change.
WIth this description isn't clear.

**Comment by hamzawain7** [comment]
I want to render buttons slightly differently on Hover and Active state. I think that is not achievable with current api.

My proposition is to add mouseOverHandler, mouseOutHandler functions and isActive property
