### ISSUE TITLE
a bug after image clippath

### ISSUE THREAD

**Issue by JSeasy** [fabricjs/fabric.js#6700]
## Version
3.6.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Nodejs or browser?
Which browsers?

**Comment by JSeasy** [comment]
if the image has clipPath attribute when i use the [setSrc(url,callBack)] to change  the image src in the fabric it cant effect it happend 
in the newest versionbut no in the version 2.4.4

**Comment by JSeasy** [comment]
fabric.Object.prototype.objectCaching = false
        console.log(fabric)
        const fabr = new fabric.Canvas('can')
        const a = [
            'https://image.s2bdiy.com/material/BtZ8EbSw2k.jpg?x-oss-process=image/resize,m_lfit,limit_0,w_550,h_550',
            'https://image.s2bdiy.com/style/995927502ce587b49dd54d70c125f22a.jpg?x-oss-process=image/resize,m_lfit,limit_0,w_550,h_550',
            'https://image.s2bdiy.com/style/588f9d253126b6f60fcf727506912ae9.jpg?x-oss-process=image/resize,m_lfit,limit_0,w_550,h_550',
            'https://image.s2bdiy.com/style/82811387fa41a24bc17bbabaff9d8088.jpg?x-oss-process=image/resize,m_lfit,limit_0,w_550,h_550',
            'https://image.s2bdiy.com/style/f7c75235033b67b54794f039f4a9c76f.jpg?x-oss-process=image/resize,m_lfit,limit_0,w_550,h_550',
            'https://image.s2bdiy.com/style/a5c03718573cb6a2350aecedf1ffffd2.jpg?x-oss-process=image/resize,m_lfit,limit_0,w_550,h_550']

        fabric.Image.fromURL(a[0], function (img) {
            img.set({
                originX: 'center',
                originY: 'center',
                // objectCaching: false,
                clipPath: new fabric.Path('m1,116.58409l113.82668,0l35.17332,-108.13487l35.17334,108.13487l113.82666,0l-92.08755,66.83026l35.17514,108.13487l-92.08759,-66.83208l-92.08757,66.83208l35.17515,-108.13487l-92.08758,-66.83026z0', {
                    originX: 'center',
                    originY: 'center',
                    left: 0,
                    top: 0,
                    // objectCaching: false
                })
            })
            fabr.add(img)
            fabr.renderAll()
        }, { crossOrigin: 'anonymous' })
        document.getElementById('bu1t').onclick = () => {
            fabr.item(0).set({
                clipPath: new fabric.Path('m150,73c61,-175 300,0 0,225c-300,-225 -61,-400 0,-225z', {
                    originX: 'center',
                    originY: 'center'
                })
            })
            fabr.renderAll()
        }
        document.getElementById('but').onclick = () => {
            // const now1 = fabr.getActiveObject()

            const r = Math.floor(Math.random(0, 1) * 6)
            console.log(r)
            fabr.item(0).setSrc(a[r], () => {
                fabr.renderAll()
            }, { crossOrigin: 'anonymous' })
        }

**Comment by JSeasy** [comment]
i had solvethis problem by  use  fabr.item(0).setSrc(a[r], () => {
img.set({dirty:true})
            fabr.renderAll()
        }, { crossOrigin: 'anonymous' })

but i dont know why?

**Comment by asturur** [comment]
@JSeasy can you make it work in the jsfiddle so that i can actually try it?
