### ISSUE TITLE
How to make the Text object not follow the fabric Canvas' zoom change?

### ISSUE THREAD

**Issue by Bendjen** [fabricjs/fabric.js#6703]
We want to keep the Text font-size at 12px after canvas' zooming in or zooming out , How to make the Text object not follow the fabric Canvas' zoom change?

**Comment by asturur** [comment]
Actually you can't.
You can keep the font-size at 12, since zoom won't change fontSize at all.
What you can do is on zoom, scale down the text with scaleX and scaleY by the inverse of the zoom.

**Comment by Bendjen** [comment]
> Actually you can't.
> You can keep the font-size at 12, since zoom won't change fontSize at all.
> What you can do is on zoom, scale down the text with scaleX and scaleY by the inverse of the zoom.

Thanks，that is worthy of having a try
