### ISSUE TITLE
Drag and Drop not working on mobile device

### ISSUE THREAD

**Issue by subhash8108** [fabricjs/fabric.js#6704]
## Version
4.2.0

## Test Case
https://codepen.io/Prebyter/pen/ggVxWo

## Desktop (Working)
Drag & drop functionality proper working on desktop

## Mobile (Not Working)
Drag & drop functionality not working, so I have add jquery touch but drag is working but canvas drop not working
Please help me, how to handle drag and drop image in canvas for mobile devices.

**Notes: It's working on canvas, but outer side image drag and drop issue on mobile device with jquery touch js**

**Comment by asturur** [comment]
Is unclear for what are you asking help.
We are not helping with jquery on mobile. nor with jquery, not with mobile separated.
Also handling JS drag and drop is not on our list of topics.
We have a demo here:
http://fabricjs.com/events

Where drag and drop event work.
