### ISSUE TITLE
The picture drawing is blurred

### ISSUE THREAD

**Issue by jackjixuyu** [fabricjs/fabric.js#6707]
## Version
3.6.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Nodejs or browser?
nodejs
Which browsers?

## Steps to reproduce
1、let image = new fabric.Image(imgObj);
2、 image.set({
          originX: "left",
          scaleX: 1,
          scaleY: 1,
          originY: "top",
          left: 0,
          top: 0,
          repeat: "no-repeat",
          crossOrigin: "Anonymous",
          toolType: "image", 
          selectable: false,
          selection: false,
          hasControls: false, 
          lockMovementX: true, 
          lockMovementY: true,
          moveCursor: "default",
          hasBorders: true,
        });
3、let canvas = new fabric.Canvas("canvas", {
      preserveObjectStacking: true, 
      isDrawingMode: false,
      hoverCursor: "default",
      selectionFullyContained: true, 
      // selectable: false,
      selectionLineWidth: 1,
    });
4、canvas.add(image);
5、canvas.requestRenderAll()

**Comment by asturur** [comment]
Please add a reproducible test case and i will reopen the issue.
