### ISSUE TITLE
Svg is cropped when it is loaded via data url with FromImage or setSrc

### ISSUE THREAD

**Issue by TFTomSun** [fabricjs/fabric.js#6709]
v4.2.0
here is a fiddle that demonstrates the problem.
https://jsfiddle.net/tftomsun/gaojy6t4/85/

The canvas.drawImage(...) function works well (see fiddle). Is there a way in fabric to create an image object that is based on this function?

**Comment by asturur** [comment]
Your svg is missing width and height and for that reason won't reander in fabric most of the time.
https://jsfiddle.net/j7kqxo19/
Try to add non percentage width and height to the  svg and it will work ok.

**Comment by TFTomSun** [comment]
@asturur thanks for the hint. Can you please answer the question? If possible, I would like to rely on the canvas.drawImage(...) function. I am afraid, that I will run into more issues using the fabricjs way of drawing SVGs.  Does fabricjs somehow support that?

**Comment by asturur** [comment]
The object that uses drawImage at its core is fabric.Image, but your svg has to have a width and height attribute

**Comment by TFTomSun** [comment]
@asturur Is there a workaround to pass the desired size into fabric.js? Background: I'm dealing with external images (so I can't modify them), but I know in which size I want to render them.
