### ISSUE TITLE
Bug with object's 'selected' and 'deselected' events.

### ISSUE THREAD

**Issue by VladGrigorovich** [fabricjs/fabric.js#6710]
## Version
4.2.0

## Test Case
https://jsfiddle.net/VladHryhorovych/jve6d2n9/20/

## Information about environment
Problem exists in all browsers.

## Steps to reproduce
1. Create any object.
2. Subscribe on 'selected' or 'deselected' events of this object.
3. Access 'selected' or 'deselected' properties in options object passed to a callback.

## Expected Behavior
Properties exist in options object passed to callback.

## Actual Behavior
Properties are set after calling the callback. So you can access them only with some delay.
For example, wrapping callback body into setTimeout resolves the issue.

It seems to me that it is not an expected behaviour. I think I can make a pull request fixing this issue. Thanks!

**Comment by asturur** [comment]
If you subscribe to rect for an event, the rect will be find in the `this` of that event function.

**Comment by VladGrigorovich** [comment]
The slight problem with this approach is that it does not work with arrow functions. What about attaching selected/deselected object to options? For example, as a 'target' field.

**Comment by asturur** [comment]
i'm not entirely opposed to it, but also, what stops you from using a normal function?
function and fat arrows functions are different and one is not replacing the other.
FabricJS does use binding on the event handlers, i m not sure if we should add the extra reference to help who uses the fat arrow all the time, or just clarify in the docs you have to use functions.

**Comment by Mat-thieu** [comment]
@asturur I and I reckon many others use these event listeners to write the intermediate changes to some state. Inside classes you want access to the class' `this`, and in Vue you want access to `this`, both for the same purpose.
Event.target is something very commonly seen in native browser apis as well, so I liked it for this purpose.

I don't suppose it's a major hassle, it just feels like I've gone back in time a couple years
```
const self = this;
activeHandler.on('scaling', function() {
   self.intermediateScaleX = this.scaleX
```

In the end I reckon it's a matter of preference, but at the moment it's not consistent, this still works;
```
activeHandler.on('moving', (e) => {
      let offseted = {
        top: e.target.top,
        left: e.target.left,
      }
```

**Comment by asturur** [comment]
@Mat-thieu  the Pr to restore
target in all events is very easy to do and is mostly code deleting. Do you want to open it?

**Comment by asturur** [comment]
i added target to single selection events, selected and deselected is not applicable.
