### ISSUE TITLE
Impossible to calculate a Line object's coordinates

### ISSUE THREAD

**Issue by advename** [fabricjs/fabric.js#6711]
## Version
3.6.0

## Test Case
https://jsfiddle.net/nx7vaLus/38/

## Information about environment
Browser, Chrome and Firefox

## Steps to reproduce
Use the jsfiddle from above, it has an interactive test case that demonstrates the issues.

## Expected Behavior
Calculate or get a line's true start and end coordinates at any time independently of moving, scaling and rotating it.

## Actual Behavior
Given several Stackoverflow answers and Github answers, i have till today not found any calculation, method or formula that was able to return the correct start and end coordinates of a line. Use the three test buttons from the jsfiddle to see some of these methods in action.

Additionally, of all the GitHub issues, contributors mentioned that this is expected behavior. As someone who does not work with the FabricJS codebase, I can't see why it is expected behavior. Nevertheless, given all parameters available to the end users, I was not able to calculate the correct coordinates as some values are never updated.

## References.
- https://github.com/fabricjs/fabric.js/issues/1749
- https://github.com/fabricjs/fabric.js/issues/4273
- https://github.com/fabricjs/fabric.js/issues/1018
- https://github.com/fabricjs/fabric.js/issues/4766

**Comment by asturur** [comment]
https://jsfiddle.net/ckm153gx/2/

I thought this was discussed at some point, but anyway this work 100% of the times

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/101221424-f3944f00-3687-11eb-8876-e5845ca11123.png)

This wasn't clear of course, but is exactly what i was doing in the fiddle now.

**Comment by advename** [comment]
Lovely! I was trying it on my own, failed and gave up after two days.

Thanks for your code snippet, I'll dump it here for archive reasons:
```js
  const points = line.calcLinePoints();
  const matrix = line.calcTransformMatrix();
  const point1 = fabric.util.transformPoint({ x: points.x1, y: points.y1 }, matrix);
  const point2 = fabric.util.transformPoint({ x: points.x2, y: points.y2 }, matrix);
```
