### ISSUE TITLE
version 4.2.0  Failed to execute 'toDataURL'

### ISSUE THREAD

**Issue by shuwenjunn** [fabricjs/fabric.js#6712]
## Version
4.2.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
browser
Which browsers?
chrome 86.0.4240.80

When loading remote pictures，Although the image is configured  as 
```
{crossOrigin:'anonymous'}
```
still has error: Uncaught (in promise) DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

version 3.6.3 config img `{crossOrigin:'anonymous'}` is work. but v4.2.0 unuse

**Comment by advename** [comment]
Please provide a valid Jsfiddle link with an example of your broken code.
But as extra info, I'm on 3.6.3 too and loading remote images works on this version.

**Comment by asturur** [comment]
There has been a change in v4 in crossOrigin.
If you could show how exactly are you using it. crossOrigin isn't an image option but an option of the image loader.

Also isn't clear if your image has the headers set correctly.

Did you try to load the image as an IMG html tag to verify?

**Comment by shuwenjunn** [comment]
use fabric.Image.fromURL
