### ISSUE TITLE
Adding image is replacing background image using fabricjs

### ISSUE THREAD

**Issue by abhimanusharma** [fabricjs/fabric.js#6713]
I am trying to add an image on a canvas with a background image set initially on load. which is loading an pdf using pdf.js and converting it to background image using `https://github.com/RavishaHesh/PDFJsAnnotations` this code.

Here is the jsfiddle of that code. https://jsfiddle.net/abhimanusharma/2exg64hr/27/

My issue is whenever I try to add image on fibreObj canvas, it replaces the background image with the image I am adding and I am left with white background with my newly added image on the top of it.

Posted my problem on stackoverflow that have no reply whatsoever.
https://stackoverflow.com/questions/65074701/add-multiple-images-on-lower-canvas-using-fabric-js

**Update** Here is the working codesendbox: https://codesandbox.io/s/hardcore-shape-gt8do

Background is removing for some canvas when add image by clicking on image icon than on canvas.

**Comment by abhimanusharma** [comment]
Any update on this?

**Comment by asturur** [comment]
Those are application issues that hardly you will find someone helping with.
Described in this way i see a  435 lines fiddle that i have to parse to figure out what is going wrong. Also i have to have knowledge of pdfjs and jspdf.

**Comment by abhimanusharma** [comment]
@asturur  Thanks for your reply I really appreciate it. I was asking to look at the output to see if its just a simple glitch with the implementation. Thanks for taking time to read the issue and reply it.

**Comment by pirey** [comment]
hi @abhimanusharma did you managed to solve it?
i'm having a similar issue.
