### ISSUE TITLE
Custom Controls polygon demo handler scope

### ISSUE THREAD

**Issue by jasonsturges** [fabricjs/fabric.js#6718]
In the Fabric.js [Custom Controls Polygon Demo](http://fabricjs.com/custom-controls-polygon), I'm not understanding how action and position handlers are being associated with that object.

If I fork the pen on that page, and add a second instance, both are affected:
https://codepen.io/jasonsturges/pen/VwKjbPN

![custom-controls](https://user-images.githubusercontent.com/1213591/101401735-5d834300-3898-11eb-99bd-a4e3d0bb35c6.gif)

In the example, the poly is assigned handlers:

```js
function Edit(poly) {
  poly.controls = poly.points.reduce(function(acc, point, index) {
    acc['p' + index] = new fabric.Control({
      positionHandler: polygonPositionHandler,
      actionHandler: anchorWrapper(index > 0 ? index - 1 : lastControl, actionHandler),
```

Shouldn't those handlers be scoped to one instance of the poly?

Why are multiple instances affected?

**Comment by jasonsturges** [comment]
Bah, I see - the underline `points` model is shared between instances.  

Not sure why I thought that would have been cloned or interpreted to new path data.

**Comment by kukudeshengge** [comment]
hi, If the effect is not a polygon, but a combination, can the same effect be achieved?
