### ISSUE TITLE
fabric-pure-browser  not found jsdom

### ISSUE THREAD

**Issue by daydayuphuan** [fabricjs/fabric.js#6721]
## Version
fabric-pure-browser@4.2.0

## Information about environment
webapck

## Expected Behavior
    ERROR in ./node_modules/fabric-pure-browser/dist/fabric.js
    Module not found: Error: Can't resolve 'jsdom' in '/node_modules/fabric-pure-browser/dist'
     @ ./node_modules/fabric-pure-browser/dist/fabric.js 24:14-30
     @ ./src/RenderWebGL.js
     @ ./src/index.js
    
    ERROR in ./node_modules/fabric-pure-browser/dist/fabric.js
    Module not found: Error: Can't resolve 'jsdom/lib/jsdom/living/generated/utils' in '/node_modules/fabric-pure-browser/dist'
     @ ./node_modules/fabric-pure-browser/dist/fabric.js 34:31-80
     @ ./src/RenderWebGL.js
     @ ./src/index.js
    
    ERROR in ./node_modules/fabric-pure-browser/dist/fabric.js
    Module not found: Error: Can't resolve 'jsdom/lib/jsdom/utils' in '/node_modules/fabric-pure-browser/dist'
     @ ./node_modules/fabric-pure-browser/dist/fabric.js 35:22-54
     @ ./src/RenderWebGL.js
     @ ./src/index.js

**Comment by asturur** [comment]
it shouldn't have any jsdom deps that version.

**Comment by daydayuphuan** [comment]
This code, should not appear in this package.

```
else {
  // assume we're running under node.js when document/window are not present
  var jsdom = require('jsdom');
  var virtualWindow = new jsdom.JSDOM(
    decodeURIComponent('%3C!DOCTYPE%20html%3E%3Chtml%3E%3Chead%3E%3C%2Fhead%3E%3Cbody%3E%3C%2Fbody%3E%3C%2Fhtml%3E'),
    {
      features: {
        FetchExternalResources: ['img']
      },
      resources: 'usable'
    }).window;
  fabric.document = virtualWindow.document;
  fabric.jsdomImplForWrapper = require('jsdom/lib/jsdom/living/generated/utils').implForWrapper;
  fabric.nodeCanvas = require('jsdom/lib/jsdom/utils').Canvas;
  fabric.window = virtualWindow;
  DOMParser = fabric.window.DOMParser;
}
```

![fabricjs](https://user-images.githubusercontent.com/7309887/101708195-bb49a200-3ac7-11eb-8de1-88245ad4e1c3.png)

**Comment by asturur** [comment]
Can you try the official one?
I remember we have a fabric@4.2.0-browser version

**Comment by asturur** [comment]
Anyway pure browser is not meant to be used in webpack. That is under node indeed.
If your problem is webpack installing those deps, there is a guide on how to avoid that using externals.
https://github.com/fabricjs/fabricjs-webpack/blob/master/webpack.config.js

**Comment by daydayuphuan** [comment]
> Anyway pure browser is not meant to be used in webpack. That is under node indeed.
> If your problem is webpack installing those deps, there is a guide on how to avoid that using externals.
> https://github.com/fabricjs/fabricjs-webpack/blob/master/webpack.config.js

thx.

**Comment by nicu-chiciuc** [comment]
@daydayuphuan I'm having the same problem with both fabric-pure-browser and the official fabric@4.3.0-browser. We're using it in a meteor application and I can't find a way to stop the errors during build
