### ISSUE TITLE
Need to have an Outline property around shapes and groups

### ISSUE THREAD

**Issue by nbaua** [fabricjs/fabric.js#6723]
**Is your feature request related to a problem? Please describe.**
We are trying to accomplish drawing shapes with boundaries/borders around it.
our primary requirement was to have a rounded button, which we did with grouping 2 shapes.
now we want to have a similar feature with text labels where we need a border around it.

**Describe the solution you'd like**
We would like to have a property similar to stroke with width and color property,
say a property like outline : { outlineWidth: 2px, outlineColor:black, outlineOpacity:0.9}

![image](https://user-images.githubusercontent.com/17998763/101858152-08dd1200-3b8f-11eb-94c9-ef6885ea6aac.png)

OR

![image](https://user-images.githubusercontent.com/17998763/101858399-886ae100-3b8f-11eb-8595-13a2820c0032.png)

**Describe alternatives you've considered**
We tried to use **stroke**, however it is not we are looking for.

**Comment by asturur** [comment]
there is a similar discussion in another topic.
without specifying what is wrong with the stroke and what is the difference with outline, we can't really understand the need

**Comment by nbaua** [comment]
> there is a similar discussion in another topic.
> without specifying what is wrong with the stroke and what is the difference with outline, we can't really understand the need

We need to show the objects (shapes and text) in a group and also each group we need to have a border (which can be toggled on/off). The current options like stroke does not work on groups and we do not want to apply stroke around each object separately (or for that matter in group too).

What nearly meets our requirement is, if we somehow apply border on groups bounding rectangle or add some lines mimicking the borders/outline on entire group.

Hope I am able to convey this clearly.

**Comment by nbaua** [comment]
> For me groups could have a fill and a stroke.

Could you please be kind enough to share a codepen or stackblitz?

Regards,
N Baua

**Comment by asturur** [comment]
`could` in the meaning that they do not have today, but it would make sense to let them have

**Comment by nbaua** [comment]
> `could` in the meaning that they do not have today, but it would make sense to let them have

Any idea on this?

**Comment by asturur** [comment]
This is a feature that should be built from scratch. Is not hard, but i do not want to build it in rush.
Can you open a discussion thread in the discussion forum, try to add as much as possible sketches of how the feature could look like.

**Comment by nbaua** [comment]
This issue become stale every time
@asturur  as per your suggestion I have already started the discussion
https://github.com/fabricjs/fabric.js/discussions/6757

for now we have implemented something on the following lines, where hasBorder, customType are extended properties

```
let group: any = this.canvas.getActiveObject();
		if (group.toObject().customType != "shape") {
			if (border && !group.toObject().hasBorder) {
				group.getObjects().forEach((obj) => {
					if (obj.toObject().customType == "circle" || obj.toObject().customType == "rect") { // polygon not working somehow
						obj.set("opacity", 1);
					}
				});
				this.extend(group, { hasBorder: true });
			} else {
				group.getObjects().forEach((obj) => {
					if (obj.toObject().customType == "text" || obj.toObject().customType == "cust_group_obj") {
						obj.set("opacity", 0);
					}
				});
				this.extend(group, { hasBorder: false });
			}
			this.canvas.renderAll();
		}

```

and when the hasBorder property is true

```

var rect = new fabric.Rect({
					type: "rect",
					left: group.left,
					top: group.top,
					width: group.width,
					height: group.height,
					fill: "",
					opacity: 0,
					stroke: "red",
					objectCaching: false,
					strokeWidth: 3 ,
					padding: 0,
					angle: group.angle,
				});
				this.extend(rect, { src: objGrpToDraw, groupId: rand_id, customType: "cust_group_obj" });
				group.addWithUpdate(rect);

```

This code has its sweet issues like on scale and zoom the rendering does not always work gracefully etc.

@asturur
Request you to prioritize it a little so we people can have a nice cool feature to use.
