### ISSUE TITLE
Fabric 4.1.0 Images can not be resized or moved in IE 11

### ISSUE THREAD

**Issue by OutrageousSoftware** [fabricjs/fabric.js#6728]
Fabric.js 4.1.0 will not let the user move or resize images in Internet Explorer 11.  Fabric.js version 3.6.6 and below work fine with IE 11.  Looks like it has to do with the "Object.assign()" method, which is being called from within fabric, not being supported in IE.

## Version
4.1.0

## Test Case
http://fabricjs.com/stroke-uniform

## Information about environment
Internet Explorer 11

## Steps to reproduce
Open this fabric demo link in IE 11...  http://fabricjs.com/stroke-uniform  Then try to move an object with your mouse. 

## Expected Behavior
The object should move fluidly around the canvas

## Actual Behavior
The object's position doesn't move (get updated) until you stop moving that object and click another object (or click the canvas somewhere)

**Comment by OutrageousSoftware** [comment]
It appears that adding the following polyfill towards the beginning of the fabric.js file fixes the issue.  Is this something that could be added to the official code?

if (typeof Object.assign != 'function') {
  Object.assign = function(target) {
    'use strict';
    if (target == null) {
      throw new TypeError('Cannot convert undefined or null to object');
    }

    target = Object(target);
    for (var index = 1; index < arguments.length; index++) {
      var source = arguments[index];
      if (source != null) {
        for (var key in source) {
          if (Object.prototype.hasOwnProperty.call(source, key)) {
            target[key] = source[key];
          }
        }
      }
    }
    return target;
  };
}

**Comment by OutrageousSoftware** [comment]
It appears that adding a polyfill (like the one shown in the link below) towards the beginning of the fabric.js file fixes the issue. Is this something that could be added to the official code?

[https://stackoverflow.com/questions/35215360/getting-error-object-doesnt-support-property-or-method-assign](url)

**Comment by OutrageousSoftware** [comment]
It appears that adding a polyfill (like the one shown in the link below) towards the beginning of the fabric.js file fixes the issue. Is this something that could be added to the official code?

https://stackoverflow.com/questions/35215360/getting-error-object-doesnt-support-property-or-method-assign

**Comment by asturur** [comment]
We left object.assign slip
in during release. Now is removed and 4.3 won't have it

**Comment by OutrageousSoftware** [comment]
Thank you so much for the quick turn around and for an amazing code library!
