### ISSUE TITLE
Resize filters work wrong, changing only scaleY (down) or scaleX (up) causes wrong ratio and undesired padding

### ISSUE THREAD

**Issue by rdsn** [fabricjs/fabric.js#6729]
## Version
4.2.0

## Test Case
http://fabricjs.com/lanczos-webgl

## Information about environment
Any browser

## Steps to reproduce
You can see this behavior on http://fabricjs.com/lanczos-webgl when you try to scale image up by dragging only horizontal handles or scale down by dragging vertical handles

## Expected Behavior
Image fills the whole selection box

## Actual Behavior
Some strange padding appears under the image its selection box

Also it is not clear why there are scaleX and scaleY instead of just scale, it is not clear what is the use case for having 2 and docs don't say anything about that.

**Comment by asturur** [comment]
thank you there was an error in plain sight: https://github.com/fabricjs/fabric.js/pull/6778/
