### ISSUE TITLE
Implement strokeDashArray for Path, Text, Circle, Ellipse (when no native)

### ISSUE THREAD

**Issue by zhangzhzh** [fabricjs/fabric.js#673]
<p>for the example <a href="http://jsfiddle.net/Sgudc/15/">http://jsfiddle.net/Sgudc/15/</a></p>

<p>in chrome<br><a href="https://f.cloud.github.com/assets/1575989/595167/b0fd0bfa-cae2-11e2-8e1e-37a742dad113.jpg" target="_blank"><img src="https://f.cloud.github.com/assets/1575989/595167/b0fd0bfa-cae2-11e2-8e1e-37a742dad113.jpg" alt="chrome" style="max-width:100%;"></a></p>

<p>in firefox 21.0<br><a href="https://f.cloud.github.com/assets/1575989/595168/b500b1d4-cae2-11e2-9a81-fc3f1f0ea7a2.jpg" target="_blank"><img src="https://f.cloud.github.com/assets/1575989/595168/b500b1d4-cae2-11e2-9a81-fc3f1f0ea7a2.jpg" alt="firefox" style="max-width:100%;"></a></p>

<p>in IE9 10<br><a href="https://f.cloud.github.com/assets/1575989/595169/b91b867c-cae2-11e2-9dbd-9339ee24a5b9.jpg" target="_blank"><img src="https://f.cloud.github.com/assets/1575989/595169/b91b867c-cae2-11e2-9dbd-9339ee24a5b9.jpg" alt="ie" style="max-width:100%;"></a></p>

##

**Comment by asturur** [comment]
i m unsure if 5 years after this still make sense.
I ll leave it open for now

**Comment by ShaMan123** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setLineDash#browser_compatibility
