### ISSUE TITLE
I want to find the method selecting the free draw line after mouse up event

### ISSUE THREAD

**Issue by OilPrince** [fabricjs/fabric.js#6735]
Thank you for introducing a good solution.

I have a question.

After drawing the shape(line, circle, rectangle, etc.) with the mouse(right after the mouse up event), the shape was immediately selected.

But after I draw a free line, that line is not selected right away!

The settings of the canvas for drawing free lines are as follows:

canvas.selection = true; 
canvas.isDrawingMode = true;
canvas.freeDrawingBrush.color = 'red';
canvas.freeDrawingBrush.width = 3; 

Even if I searched this site and various bulletin boards, I couldn't find a way to choose right after drawing a free line.

How can I draw a free line and make sure that the free line is selected right away?

Please tell me how to do it!

I really hope this problem is solved.

**Comment by peeley** [comment]
Listening on the `path:created` event might be what you're looking for. You can access any path created inside the event data, then programmatically make it the selected object like so:
```
canvas.on({
  'path:created': (event) => {
    canvas.setActiveObject(event.path);
  }
});
```

**Comment by OilPrince** [comment]
canvas.on('path:created', function(o) {
			console.log('path:created');

			canvas.setActiveObject(o.path);
		});

Thanks a lot!
I close this issue!
