### ISSUE TITLE
fabric.Pattern is not accepting the canvas element

### ISSUE THREAD

**Issue by kkbandaru** [fabricjs/fabric.js#6736]
fabric.Pattern is not accepting the canvas element

i am getting below error when 

"Type 'HTMLCanvasElement' is missing the following properties from type 'HTMLImageElement'"

i use below code

  var pattern = new fabric.Pattern({
                  source: patternSourceCanvas.getElement(),
                  repeat: 'repeat'
              });  

i am trying to follow this sample

http://fabricjs.com/dynamic-patterns

**Comment by kkbandaru** [comment]
https://github.com/fabricjs/fabric.js/issues/6479

Is it mentioned dynamic patterns are not supported, is this correct

**Comment by kkbandaru** [comment]
And I am using type script , it is not accepting canvas.getelement(), do I need to use specific version

**Comment by asturur** [comment]
you can't use anymore functions as sources for patterns,
While you can still use canvases.
Whatever is the typescript problem i m sure it can be solved.
