### ISSUE TITLE
Add object to nested group

### ISSUE THREAD

**Issue by jameszhong2008** [fabricjs/fabric.js#6738]
Hi, I use fabric's group recently, I understand when you want to add object to group and update it, you can use addWithUpdate, it works great when when the group is just under canvas.
like that: canvas->group        works

 but when the group(group1) is under another group, it doesn't work anymore, group and it's object's position will be wrong after use addWithUpdate
canvas->group->group1        does not work

check it here
https://jsfiddle.net/zhongjian2008/0re3hjyp/16/

Now i find a workaround it before add object to group in other group, ungroup it first, then group them back. but when there is many group, in deep structure, it makes things complex.

This issue is relate use ActiveSelection to group multi objects that already under a group or deep group. 
canvas->group->group01(node1, node2)
            ->group1->group02(node3, node4)            
var sel = new fabric.ActiveSelection([node1, node3]);     // does not work
canvas.setActiveObject(sel);
canvas.requestRenderAll();

Is there any other solution?  thanks a lot.

**Comment by andrewzolotukhin** [comment]
Actually does Fabric already has a support of nested groups?

**Comment by asturur** [comment]
yes nested groups are ok.
Did you try updating the innergroup first and then the outer group? You can call addWithUpdate() without addind anything

**Comment by jameszhong2008** [comment]
@asturur thank you for quick response, I use addWithUpdate(rect6), and call addWithUpdate() with the outer group. it still doesn't  work. (nested group's position change incorrectly), am i doing it wrong, could you please check it here.

 click AddNode Error and check it. 
 https://jsfiddle.net/zhongjian2008/0re3hjyp/37/

Thanks a lot!

**Comment by asturur** [comment]
Ok this is definitely broken i need to fix it.
I would expect something like that to work

**Comment by asturur** [comment]
This is way more complicated than i expected

i can get it to work from this
![image](https://user-images.githubusercontent.com/1194048/103456879-a513b800-4cfa-11eb-99ea-0263deeaf78c.png)

to this
![image](https://user-images.githubusercontent.com/1194048/103456886-b3fa6a80-4cfa-11eb-8638-91a044532e01.png)

Meaning that i m quite right, but usually those things are completely broken or perfect, and this quite right means that fixing it will be a pain of understanding.

**Comment by asturur** [comment]
I repopend my PR for this, i need a moment to recap what i did, and we can fix this.
