### ISSUE TITLE
Viewport depending on the window size

### ISSUE THREAD

**Issue by CharlesRA** [fabricjs/fabric.js#6743]
_[Stackoverflow question](https://stackoverflow.com/questions/65183234/fabricjs-set-vptcoords-depending-on-the-window-size)_

Hello !
I allow myself to ask my question here because no one could help me on stackoverflow.

Is it possible when the zoom is at 1 (default) that the viewport is not the full size of the canvas but is the size of the window ? I don't want one of the corner points to have a negative position or greater than the size of the canvas.

Thanks in advance for the help :)

**Comment by asturur** [comment]
i read your questions.
vptCoords are telling you which area of your canvas, at zoom 1, is currently visible.

So if you have a 5k by 5k canvas and a 200x200 window, when your are watching the bottom right corner vpt coords will be 4800,4800 to 5000,5000.

Is unclear to me what is your issue and what are you trying to achieve.
A jsfiddle with an example would help.
