### ISSUE TITLE
memory leak maybe 

### ISSUE THREAD

**Issue by caperso** [fabricjs/fabric.js#6746]
### What did you do?
I am using fabric to draw some rects above a picture. (in a react component)
1. picture is loaded as background in a fabric canvas

```js
    useEffect(() => {
      const initConfig = {
        stopContextMenu: true,
      };
      let infraredCanvas = new fabric.Canvas(infraredRef.current, initConfig);
      let lightCanvas = new fabric.Canvas(lightRef.current, initConfig);

      setInfraredCanvas(infraredCanvas);
      setLightCanvas(lightCanvas);
      return () => {
        console.log("UNLOAD");
        infraredCanvas?.dispose();
        lightCanvas?.dispose();
      };
    }, []);

```
2. pictures can be switch next/prev through setBackgroundImage Api
3. IMPORTANT : draw rects (we called these as defects), depend on `defects` array. 

```js
// create defectPaths
  useEffect(() => {
    if (infraredCanvas && lightCanvas && infraredRatio && lightRatio) {
      const { infraredPaths, lightPaths } = getDefectPaths(defects, infraredRatio, lightRatio);

      setInfraredPaths(infraredPaths);
      setLightPaths(lightPaths);

      console.log("[re-paint]", infraredPaths, lightPaths);
    }
  }, [defects, infraredCanvas, lightCanvas, infraredRatio, lightRatio]);

//  render paths
useEffect(() => {
  if (infraredCanvas && lightCanvas && infraredPaths && lightPaths) {
      infraredCanvas.remove(...infraredCanvas.getObjects().concat());
      lightCanvas.remove(...lightCanvas.getObjects().concat());

      infraredPaths.forEach((p) => infraredCanvas.add(p));
      lightPaths.forEach((p) => lightCanvas.add(p));
    }

}, [infraredCanvas, lightCanvas, infraredPaths, lightPaths]);
```

```js
const defaultPathConfig = {
  strokeWidth: 2,
  fill: "transparent",
  hasRotatingPoint: false,
  lockRotation: true,
  selectable: false,
  cornerSize: 6,
  transparentCorners: false,
  cornerColor: "white",
  borderColor: "white",
};

export function getDefectPaths(defects: Defect[], infraredRatio: CanvasImageRatio, lightRatio: CanvasImageRatio) {
  const infraredPaths = defects.map((d) => {
    // a region likes "200 100 400 600"
    const seq = d.region.split(" ").map((s) => +s);
    const drawPath: any = [
      ["M", seq[0] * infraredRatio.x, seq[1] * infraredRatio.y],
      ["L", seq[2] * infraredRatio.x, seq[1] * infraredRatio.y],
      ["L", seq[2] * infraredRatio.x, seq[3] * infraredRatio.y],
      ["L", seq[0] * infraredRatio.x, seq[3] * infraredRatio.y],
      ["L", seq[0] * infraredRatio.x, seq[1] * infraredRatio.y],
      ["z"],
    ];

    const pathObject = new fabric.Path(drawPath, {
      ...defaultPathConfig,
      data: d,
      objectCaching: false,
      stroke: SOLAR_DEFECT_TYPES[d.defect_type!].color,
    });
    pathObject.setControlsVisibility({ mtr: false });

    return pathObject;
  });
```
### What did you expect to happen?

memory should stay at a level when I switch a lot of pictures
and memory should be released when I unmount this component

### What happened instead?

memory goes up and never be released even I unload the component

### Screenshots and descriptions

1. compoent loaded and fabric functioning well
![20201222142830](https://user-images.githubusercontent.com/34877623/102856999-9c9dc080-4462-11eb-865b-6cf5783c4a95.jpg)

2. do a lot switch pictures ( setBackgroundImage )
   what happend is the background image and `defects` props changed
   then image switched and rects(defects) added on canvas (only once, as the log "re-paint" logged once)

3. but in memory snapshot the klass is increased and never goes down 
![20201222143018](https://user-images.githubusercontent.com/34877623/102857011-a0c9de00-4462-11eb-8094-71dd557a9ded.jpg)

4. even I closed Modal component, still the same
![20201222143115](https://user-images.githubusercontent.com/34877623/102857576-a4aa3000-4463-11eb-911e-8fde5006a923.jpg)

**Comment by caperso** [comment]
I do remove objects before paint  defect paths
like
`lightCanvas.remove(...lightCanvas.getObjects().concat());`
and it was not "removed from memory" as I expected

**Comment by asturur** [comment]
Did you try to use Image.dispose() method when removing the objects?
I'm not sure if it gets called automatically.

**Comment by caperso** [comment]
> Did you try to use Image.dispose() method when removing the objects?
> I'm not sure if it gets called automatically.

Thanks for your reply.

Code was updated

```js
    useEffect(() => {
      infraredImage && infraredImage.dispose();
      lightImage && lightImage.dispose();
    }, [ infraredImage, lightImage]);
```

It cleans up image everytime when image was changed.
Then I tried do some switches

Unfortunately,  this issue still the same

![image](https://user-images.githubusercontent.com/34877623/102952026-21431a00-4509-11eb-9d5f-b1bba521b726.png)

![image](https://user-images.githubusercontent.com/34877623/102952480-38ced280-450a-11eb-8bbc-75ab4799b1ae.png)

**Comment by asturur** [comment]
but when the GC kicks in, how much it collects?

**Comment by asturur** [comment]
You should try to start reproducong this outside your app in a jsfiddle. Investigating full apps is not possible. Try to reproduce the memory leak outside react in a plain html situation.

**Comment by caperso** [comment]
I clicked gc button everytime before I take a snapshot.

I move code to codesandbox and here is the 
[code](https://codesandbox.io/s/peaceful-williams-zy0ui)
and
[demo](https://zy0ui.csb.app/)
but still in react. hard for me to move all these codes into plain js , sorry for that .

![image](https://user-images.githubusercontent.com/34877623/103055715-fb377b80-45d5-11eb-8e94-abc9c3a8a3fa.png)

![image](https://user-images.githubusercontent.com/34877623/103055820-418cda80-45d6-11eb-9393-efbd88b2b87a.png)

**Comment by caperso** [comment]
update

reviewed my code again and I remove dependencise in canvas listener useEffect

**Comment by caperso** [comment]
closed for now , if i got anything i will update it
