### ISSUE TITLE
Text on path incorrect tangent angle

### ISSUE THREAD

**Issue by melchiar** [fabricjs/fabric.js#6750]
## Version
4.3.0

## Test Case
https://jsfiddle.net/melchiar/1vdjfLc8/

## Information about environment
Tested with Chrome, Firefox

## Steps to reproduce
The new text on path functionality seems to be calculating tangent angle incorrectly at certain points on a curve (note the angle of the l, i, and n characters)

![image](https://user-images.githubusercontent.com/9057412/103043693-a0007d00-4532-11eb-8a1b-743d06b87a3a.png)

**Comment by asturur** [comment]
I must have broke something quick, because in the PR looked good.
I think is because i lowered the precision on the step... probably some points become the same, and the angle is then 0. That is exactly what looks like here. The angles that look off, look also 0.

**Comment by asturur** [comment]
There should be a way to calculate the angle on those curves without using 2 near points, i need to find out.

**Comment by asturur** [comment]
i think here is the answer:
https://gist.github.com/pbeshai/72c446033a98f99ce1e1371c6eee9644

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/103104229-3d88a900-4626-11eb-8063-fb2cb6b28468.png)

After one our of coding...

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/103104403-39a95680-4627-11eb-8df7-ed9b350a9b07.png)

Ok was a dumb error, this seems smooth.

**Comment by asturur** [comment]
The changes are interesting because they remove one full iteration to find the angle, compared to before.
So is more accurate and is also, let's say, double fast.
