### ISSUE TITLE
canvas.loadFromJSON doesn't work when there is text on path on canvas

### ISSUE THREAD

**Issue by deocampoej** [fabricjs/fabric.js#6762]
Hi, I am implementing a redo/undo feature as well as saving of json data, the text on path json data seems to be unusable when exported

## Version
4.3.0

## Test Case
https://jsfiddle.net/deceive9/zef528vq/13/

## Information about environment
Google Chrome

## Steps to reproduce
Use "Add text on paths" demo on fabricjs site, draw a line
Use canvas.toJSON(['path']) function to export JSON data
Load that same json on the canvas

## Expected Behavior
canvas will be loaded

## Actual Behavior
Error:  Cannot read property 'x' of undefined

**Comment by asturur** [comment]
Path should be supported automatically.
If it isn't i forgot it and i will add it.

**Comment by deocampoej** [comment]
I noticed that pathOffset property of path is removed when loading the object from json

Yes, text.path needed to be included in toJson function, removing it generates no error but also no curve, using toDatalessJson doesnt include path on serialization
