### ISSUE TITLE
Fill and Stroke overlap which look as if element has 2 strokes

### ISSUE THREAD

**Issue by hemantandjaiswal** [fabricjs/fabric.js#6765]
Hey, I have been trying to make a small editor in fabric, I want a rectangle with features such as stroke, fill and  opacity. But when we set opacity and stroke at the same time, it looks as if the two color(fill and stroke) meet at a point.

This fiddle could better explain what I am trying to do

## Version
3.6.0

## Test Case
http://jsfiddle.net/7jmtu1z9/2/

## Information about environment
Browser
Chrome

## Steps to reproduce
Add a rectangle and set its stroke width >1 and opacity to < 1

## Expected Behavior
Stroke should be outside fill area
## Actual Behavior
half stroke is inside fill

**Comment by asturur** [comment]
This is how canvas works, and is complicated to make it work otherwise.
Stroke is across an imaginary line that define the shape.

There is an inconsistency between caching true and false that brings up the behaviour that you want, but that should be addressed too.
