### ISSUE TITLE
hasRotatingPoint: false not honored in 4.3.0

### ISSUE THREAD

**Issue by kenjim83** [fabricjs/fabric.js#6766]
## Version
4.3.0

## Test Case
https://codepen.io/kenjim83/pen/RwGxvjO

## Information about environment
Nodejs or browser?  Browser
Which browsers?  Chrome

## Steps to reproduce
pass `hasRotatingPoint: false` into any new Object and add to canvas.

## Expected Behavior
rotation control should not be present

## Actual Behavior
rotation control is present

**Comment by asturur** [comment]
Probably isn't clear enough on the breaking changes.
hasRotatingPoint has been remove in 4.0, if you do not want the rotating control, remove the rotating control from the control set.
If you want to remove it just for some use cases, make 2 control set and switch between them.

http://fabricjs.com/controls-api

**Comment by asturur** [comment]
I'll update the documentation to reflect this

**Comment by kenjim83** [comment]
Thanks for the info! Sorry for this non-issue.

**Comment by asturur** [comment]
docs needs to be inproved the issue is needed open

**Comment by asturur** [comment]
The v4 breaking changes doc has been  updated
http://fabricjs.com/v4-breaking-changes
