### ISSUE TITLE
Loading custom fonts broken on 4.3.0

### ISSUE THREAD

**Issue by hamzawain7** [fabricjs/fabric.js#6767]
## Version
4.3.0

## Test Case
http://fabricjs.com/loadfonts

## Information about environment
Nodejs or browser?
Which browsers?
Chrome browser

## Steps to reproduce
Changing the fonts no longer applies them. Need to scale the text to see the new font being applied

## Expected Behavior
Fonts should change when a new font is selected

## Actual Behavior
Fonts doesn't change when a new font is selected

**Comment by asturur** [comment]
found the bug!

**Comment by shulhi** [comment]
setting `textAlign` also doesn't work.

**Comment by asturur** [comment]
I think all of those have been fixed.
I can't really publish anything till i get the pipeline back and running.
