### ISSUE TITLE
There is a problem using the custom gesture plug-in

### ISSUE THREAD

**Issue by huzedong2015** [fabricjs/fabric.js#6770]
1. When the finger does not scale and rotate on the current active object, the current active object will lose focus,

2. The active object moves when the finger zooms and rotates on it

3. The activation object is on drop (touchstart), I want to activate it on click event

I would like to include gesture plug-ins in fabric

@asturur

**Comment by huzedong2015** [comment]
Now I want to know if the following points can be realized

1. Disable dragging and activate objects when dragging

2. Click to activate the object

**Comment by asturur** [comment]
@huzedong2015 our gesture plugin should provide a basic pinch to zoom and rotate.

In fabricJS objects gets selected on mousedown/touchstart. We wanted to get an option to select on mouseup/touchend, but for now we can't work on it. Isn't trivial at all.

**Comment by huzedong2015** [comment]
> @huzedong2015 our gesture plugin should provide a basic pinch to zoom and rotate.
> 
> In fabricJS objects gets selected on mousedown/touchstart. We wanted to get an option to select on mouseup/touchend, but for now we can't work on it. Isn't trivial at all.

When you talk about gesture plug-ins, do you mean controls that can be operated like hammerjs

**Comment by asturur** [comment]
well we use eventjs but hammerjs is perfectly fine too ( i think is better ).

What i was saying is that the touchstart event will always trigger a selection.

Your request disable dragging ( i suppose you want to drag  pan ) and click to select ( select on mouse up ) while are wanted feature are harder to implement ( i tried a bit )
