### ISSUE TITLE
Select object in isDrawingMode

### ISSUE THREAD

**Issue by chenyiqiao** [fabricjs/fabric.js#6780]
Is it possible to select object (as activeObject) in isDrawingMode? The hoverCursor is 'move' only if I exit isDrawingMode.

http://fabricjs.com/freedrawing

**Comment by asturur** [comment]
no, when you draw you can only draw. This is how the feature was built.

Drawingmode shortcircuit the selection process. You can try with the mousedown:before event to see if you can intervene

**Comment by chenyiqiao** [comment]
what is wanna achieve is,  in drawingMode, even when hovering over the object, the cursor could be 'move' so that it's obvious to user that objects can be selected and moved, so mousedown:before would not help. 

I think maybe drawingMode should not shortcircuit the selection process, so that it could be convenient to manipulate objects even in drawingMode.Do you agree?

**Comment by asturur** [comment]
I do not agree because this would break all the existing apps.
You can do the opposite.
You can be in drawing mode OFF, and you can activate drawing mode on `mousedown:before` if no objects are hovered.
