### ISSUE TITLE
Unexpected movement with default originX/Y after scaling object with touch gestures

### ISSUE THREAD

**Issue by Jsbbvk** [fabricjs/fabric.js#6781]
## Version
4.3.0

## Test Case
https://codepen.io/Jsbbvk/pen/KKgoJKL
By selecting the rectangle, you should be able to rotate/scale with 2 fingers. 

## Information about environment
Mobile

## Explanation
With object's `originX = 'center'` and `originY = 'center'`, everything works.
However, with the default origin: `originX = 'left'` and `originY = 'top'`, an unexpected movement occurs.

Let "prevX" and "prevY" be the x & y position of the rectangle before applying a 2-finger pinch. prevX & prevY should be the top left corner coordinate with `originX = 'left'` and `originY = 'top'`

## Expected Behavior
After rotating/scaling object AND lifting only 1 finger (so you still have 1 finger on the screen), you should move the object without any jitteriness. 
## Actual Behavior
After rotating/scaling object and keeping only 1 finger on the screen, when you move your finger (ever-so-slightly), the object jumps to prevX and prevY. If you look closely, the top left corner of the object always return to the top left corner position of where the object was before the rotate/scale.

**Comment by Jsbbvk** [comment]
Here is a video demonstration of this behavior

https://user-images.githubusercontent.com/22285438/103615439-70148a80-4edf-11eb-9119-149aa81d8cbf.mov

**Comment by asturur** [comment]
Sorry i thought i answered before i think i started then for some reason it did not get trough.
This is probably not great for our implementation, but we have no plan of quick fixes for it.

We should investigate if there is a way to avoid moving from a 2 finger gesture to a 1 finger gesture.

**Comment by Jsbbvk** [comment]
One thing I noticed while trying to debug was that the object's position (top/left) is set correctly while scaling/rotating. 

I think that the problem lies in the object's movement code for a 1 finger movement gesture (or object movement in general). I think that when a 1 finger gesture becomes a 2 finger gesture, the object still fires the 1 finger movement gesture (i.e. moving the object) and somehow isn't updating the new coordinates while the 2 finger gesture is rotating/scaling.

**Comment by asturur** [comment]
I m hesitant to put time in this because i know eventjs isn't a great choice for touch events anymore, hammerjs seems abandoned and i have no idea what are the alternatives for scaling and rotating

**Comment by Jsbbvk** [comment]
No worries, I found a temporary solution by setting the originX/Y to center. But when you do have the time, please see what you can do!
