### ISSUE TITLE
rx for the Triangle

### ISSUE THREAD

**Issue by dungeo** [fabricjs/fabric.js#6782]
Hey there,

is there some way to use **_rx_** attribute to get rounded corners on a triangle object? 

I am implementing a sign configurator and this is neccessary for the client. Maybe this could be somehow done with manually combining triangle object with circles, but this would be overly complicated when resizing the sign and changing the stroke width... Of course I googled the issue and found some workarounds, but none of them helped me to solve this problem.

If this is not possible in the moment, do you consider adding this feature?

**Comment by asturur** [comment]
If we would move all the simple shapes , triangle, rect, to generate Paths, this could be done, but this is not planned ofr now and you can already create a path for it by your own and checking what the rect does on the RX/RY cases.
