### ISSUE TITLE
Custom control is not working after release new version(4.3.0)

### ISSUE THREAD

**Issue by RistoBIn** [fabricjs/fabric.js#6783]
## Version
4.3.0

## Test Case
http://fabricjs.com/custom-control-render
https://codepen.io/pen/?&prefill_data_id=c1522b59-4f1e-4ef5-87a5-95cb74123230

## Information about environment
All browsers

**Comment by zuoyi615** [comment]
I have same problem.

`mouseUpHandler` provides different target object between 4.2.0 and 4.3.0

also Text.set('text', newText) can't render correctly

**Comment by beydeng** [comment]
function deleteAction(eventData, target) {
		
	var canvas = target.target.canvas;
	let ss = canvas.remove(target.target);

}

use target.target.canvas to get the canvas
