### ISSUE TITLE
Replace color in image (image filter) ?

### ISSUE THREAD

**Issue by mspanish** [fabricjs/fabric.js#6786]
I've been playing around with the image filters, which all seem to work very well and are not hard to implement - but I was hoping for relatively simple way to swap color inside an image (imported png) rather than applying a tint or whatever to the whole image. 

Assuming I've got a simple color picker tool to select the color I want to change in the image, does anybody have a custom filter built where I could pass that color along with the desired replacement color, and apply that to the activeObject?

**Comment by asturur** [comment]
I think a good way is:
- calculate hue of a color
- if hue match with a certain tolerance to hue of the color you want to swap, then swap the color with a similar one, but different hue ( bringing over hv or hl, depending on the space you use ).

won't probably work on gray scales

I'm not sure if in our code samples in filter there is hue calculation for webgl.

This could be a fun filter to implement

**Comment by mspanish** [comment]
I have some code that will detect the color at the mouse position, may be hacky but here is what I have:

```
const getColor = (e) => {
    // fetch once canvas data     
    var ctx = canvas.getContext(); 
    let imgData = ctx.getImageData(0, 0, canvas.width, canvas.height);

    var pointer = canvas.getPointer(e.e);
    var x = pointer.x;
    var y = pointer.y;
    // locate index of current pixel
    console.log('x and y are '+x + ' ,'+y)
    
    let index = (y * imgData.width + x) * 4;

    let red = imgData.data[index];
    let green = imgData.data[index+1];
    let blue = imgData.data[index+2];
    let alpha = imgData.data[index+3];
    // Output
    console.log('pix x ' + x +' y '+y+ ' index '+index +' COLOR '+red+','+green+','+blue+','+alpha);
    console.log('rgba(' +red+ ',' +green+ ',' +blue+ ','+alpha +')')
}  
```
I'll see what else I come up with in terms of trying to swap this for another color!

**Comment by asturur** [comment]
Choosing the color to swap is outside the scope of the filter that is going to swap it.
I can help you with the webgl code should be doable with the examples we have in the repo

**Comment by mspanish** [comment]
ok. I'll post when I have something based on the examples.

**Comment by mspanish** [comment]
Not finding an obvious way to do this - if you could point me to the filter you'd begin with to tweak into a color replacer I'd really appreciate it!

**Comment by mspanish** [comment]
My first non working attempt:

```
    fabric.Image.filters.Colorify = fabric.util.createClass(fabric.Image.filters.BaseFilter, {

        threshold: 5,
        type: 'Colorify',
        isNeutralState: () => false,
        applyTo: function(canvasEl) {
  

        var context = canvasEl.getContext('2d'),
            imageData = context.getImageData(0, 0, canvasEl.width, canvasEl.height),
            data = imageData.data;

            for (var i = 0; i < imageData.data.length; i += 4) {
                // is this pixel the old rgb?
                if (imageData.data[i] == this.oldRed && imageData.data[i + 1] == this.oldGreen && imageData.data[i + 2] == this.oldBlue) {
                    // change to your new rgb
                    imageData.data[i] = this.newRed;
                    imageData.data[i + 1] = this.newGreen;
                    imageData.data[i + 2] = this.newBlue;
                }
            } 

        context.putImageData(imageData, 0, 0);
        }
    });

   fabric.Image.filters.Colorify.fromObject = function(object) {
   return new fabric.Image.filters.Colorify(object);
   };
```

**Comment by asturur** [comment]
Do you want to swap a single color or a full range of it?
Can you show an example image on which you want to run it?

**Comment by asturur** [comment]
There is a tutorial now:
http://fabricjs.com/custom-filter-swap-color
Will receive additional improvement ( a tolerance and maybe a hue based swapping )

**Comment by vedatsozen** [comment]
> I have some code that will detect the color at the mouse position, may be hacky but here is what I have:
> 
> ```
> const getColor = (e) => {
>     // fetch once canvas data     
>     var ctx = canvas.getContext(); 
>     let imgData = ctx.getImageData(0, 0, canvas.width, canvas.height);
> 
>     var pointer = canvas.getPointer(e.e);
>     var x = pointer.x;
>     var y = pointer.y;
>     // locate index of current pixel
>     console.log('x and y are '+x + ' ,'+y)
>     
>     let index = (y * imgData.width + x) * 4;
> 
>     let red = imgData.data[index];
>     let green = imgData.data[index+1];
>     let blue = imgData.data[index+2];
>     let alpha = imgData.data[index+3];
>     // Output
>     console.log('pix x ' + x +' y '+y+ ' index '+index +' COLOR '+red+','+green+','+blue+','+alpha);
>     console.log('rgba(' +red+ ',' +green+ ',' +blue+ ','+alpha +')')
> }  
> ```
> 
> I'll see what else I come up with in terms of trying to swap this for another color!

this can change any pixel of an image or how it works ?
