### ISSUE TITLE
right click copy lower-canvas image

### ISSUE THREAD

**Issue by chenyiqiao** [fabricjs/fabric.js#6788]
when right click on fabric canvas, i can select 'copy image' and it ends up with a blank image. It is possibly because we need to select the canvas with className 'lower-canvas' but 'upper-canvas' is on the top actually. 

So what can i do to copy 'lower-canvas' as image?

**Comment by asturur** [comment]
either use a static canvas with no interaction or use the toDataUrl api to download the image.
Or find some trick to workaround the issue, like you can capture the contextmenu event and generate a syntetic one on the lower canvas?
