### ISSUE TITLE
set Bounding box rotation and dimension of fabric group same as it's objects

### ISSUE THREAD

**Issue by princ09** [fabricjs/fabric.js#6792]
![Screenshot from 2021-01-06 19-10-55](https://user-images.githubusercontent.com/47990313/103850538-808a5800-50cd-11eb-985a-40eb4ddc0497.png)
Version fabricjs 4.2.0

As You can see in picture I have Text and Rectangle in Group. Both text and Rectangle are rotated. So I Believe the Bounding Box of group should be rotated. But it isn't. Instead bounding box not rotated at all.

Note: I have added already Rotated text and rect to group. I tried using addWithUpdate() but doesn't work. I also tried giving angle to Group but its rotate child object again. What I want is bounding box of group should be same size of child object(Rectangle which acting as Border) and with same rotation angle of object.

**Comment by asturur** [comment]
we do not have code for that. You are creating groups on yourself, and you have all the functions to handle angles.
You can look at object angles, group them, counter rotate the group, ungroup them, group them again, and then rotate back in the correct position. This is more or less what we have to do to make this happen.
