### ISSUE TITLE
Aw, Snap! screen when try to load large canvas in Mobile device using Fabric JS

### ISSUE THREAD

**Issue by soumen-cn** [fabricjs/fabric.js#6793]
## Version
Fabric JS ^3.6.3
Angular ~8.2.14

## Information about the environment
Mobile browser Chrome, Firefox

## Issue Details
I am trying to load a large canvas from JSON data with a background image. On the desktop, it is loading properly. But on the mobile device, the browser crashed.
I have to load and fit the entire canvas within the canvas window.

## HTML Code
`<canvas id="myCanvas" width="600" height="600"></canvas>`

## TS code to prepare the canvas
```
// Calculate ratio of the canvas as per height and width
      prepareCanvas(width, height) {  // height = 3300, width = 2550
        let ratioHeight: any = Math.ceil((height / width) * 600);
        this.canvas = new fabric.Canvas("myCanvas", {
          backgroundColor: "#ffffff",
          selection: false,
          width: width <= 600 ? width : 600,
          height: width <= 600 ? height : ratioHeight
        });
        this.canvas.setDimensions(
          { width: width, height: height },
          { backstoreOnly: true }
        );
     }
```
## Code To load Canvas from JSON
```
loadTemplateFromData(canvasData: any) {        
    this.canvas.loadFromJSON(
      canvasData,
      this.canvas.renderAll.bind(this.canvas),
      (o, object) => {
        object.set("selectable", false);
      }
    );
  }
```
## Note
Using the above code the canvas loads properly in the desktop browser but crashed on the mobile browser. One thing I have noticed if the canvas width, height are small like 300 x 300 then it is loading properly in the mobile browser. How to load a large canvas in the mobile browser?

**Comment by asturur** [comment]
very large and mobile device are vague descriptions. Can you be more specific? You are likely hitting an hardware imposed limit on the browser

**Comment by soumen-cn** [comment]
Hi @asturur 

Thanks for your response.

When i set the width and height of the canvas to 2550 x 3300 it is showing the following screen on mobile chrome also for firefox the app crashes.
![mobile_error](https://user-images.githubusercontent.com/56528088/103997608-54500380-51c1-11eb-9d32-1bbae0855171.png)

I am using the following code

```
    this.canvas = new fabric.Canvas("myCanvas", {
      backgroundColor: "#ffffff",
      selection: false,
      width: 2550,
      height: 3300
});
```
Or

```
    this.canvas.setDimensions(
      { width: 2550, height:3300 },
      { backstoreOnly: true }
    );
```

But the same canvas working fine in the desktop browser.

**Comment by asturur** [comment]
Look you are not provinding the useful details.
What phone is that?
What OS is running?
What retina scaling does it have?

Please log out the fabric.devicePixelRatio and if you are using retina scaling.
If that phone has a scaling of 3 or more, that canvas is getting very big quickly.
