### ISSUE TITLE
Object event listeners recieve incomplete event information

### ISSUE THREAD

**Issue by Mountain-Programmer** [fabricjs/fabric.js#6796]
## Version
4.3.0

## Test Case
https://jsfiddle.net/4m7vwogx/

## Information about environment
Mozilla Firefox 84.0.1 (64-bit)

## Steps to reproduce
create a new Image, install event listener on new Image: 
`            var img = document.createElement('img')
            img.src = '<link to img>'

            var Image = new fabric.Image(img, {})

            Image.on('selected', (event) => {
                console.log("event", event);
                console.log(Object.keys(event));
                for(var i = 0; i < 10; i++)
                {
                    setTimeout(() => console.log(Object.keys(event)), 1000);

                }
            })

            this.canvas.add(Image)
`

## Expected Behavior
`console.log(Object.keys(event))` should print `Array(3) [ "e", "selected", "target" ]`

## Actual Behavior
`console.log(Object.keys(event))` prints `Array [ "e"]`

**Comment by asturur** [comment]
selected, deselected and target gets added only on the canvas event.
The target is the image itself and the THIS of the event handler.
