### ISSUE TITLE
[QUESTION] Save states of objects in Fabric.js

### ISSUE THREAD

**Issue by ilya2204** [fabricjs/fabric.js#6799]
I am developing an application for collaborative editing by multiple users using websockets and Fabricjs.
After each change of the object, I need to save its new state, for undo/redo operations.
I'm trying to save state like this:

 ```
const state = obj.toObject(); 
//or
const state = obj.toJSON(); 
```

And then I want to load the previous state of the object when need to cancel the operation:
 ```
obj.setOptions(state);
```

Everything works well, until the moment when several objects are selected and changed (for example, by rotation or scale). If you save the state of each individual object in the group and then return to it, the result is not what I expect. This is because the coordinates of objects start to be relative to their group. For example, the **angle** property of an object does not change when several objects are rotated, but the **angle** property of a group changes.

However, for correct undo/redo operations, I came to the conclusion that I need to save exactly the real state of objects not relative to a group, so that later I can easily return to them.

How can I save the state of an object that is in a group relative to the canvas (coordinates, angle, scale, etc.) so that you can return to it later?

P. S. I looked at the given answers from https://stackoverflow.com/questions/29829475/how-to-get-the-canvas-relative-position-of-an-object-that-is-in-a-group. This partially solves the coordinate problem, but does not work when group rotating and scaling. And I also looked at http://fabricjs.com/using-transformations, but did not fully understand how to apply this in solving my problem.

**Comment by asturur** [comment]
the result of `toObject` isn't meant to be used with `set` and the only way to save an object outside the group is to pull it out of the group itself.

There isn't a reliable way to deal with objects based state and groups.
Reliable solution i know of are either to save and restore full canvas state or to go by a change approach, saving with you just changed to restore it later.
