### ISSUE TITLE
[QUESTION] Performance issues in the mobile environment due to the difference of the canvas size(canvas-container vs lower-canvas and upper-canvas)

### ISSUE THREAD

**Issue by OilPrince** [fabricjs/fabric.js#6800]
Hello!
Fabric js is a great solution.
Thank you for developing this solution and releasing it as an open source.

I am using fabric js to test the drawing shapes(free line, circle, square, etc.), zooming and scrolling functions with the image as the background.

There is no problem in the desktop window environment.
However, mobile environments (such as Android smartphones and tablets, iPhones and iPads) have seen performance issues when zooming and drawing.

There was a decrease in performance when drawing shapes or pan moves(exactly, scrolling) when putting a large image in the background.

When I checked the cause of the problem, I found that the width/height of the canvas-container and the width/height of the lower-canvas and upper-canvas were different.

In a desktop window environment, the wide/height of the canvas-container and the wide/height of the lower-canvas and upper-canvas match exactly.
However, in a mobile environment, the size varies as shown below.

![image](https://user-images.githubusercontent.com/40879690/104308293-c3a45b00-5513-11eb-8e8a-345031b0e85a.png)

You can see this by switching from Dev Tools in Google Chrome to a mobile device.
Even on Android smartphones, the size difference was four times as different.

To solve this problem, I have arbitrarily adjusted the size attributes as follows.

var width = canvas.getWidth();
var height = canvas.getHeight();

canvas.setWidth(width);
canvas.setHeight(height);

$('.lower-canvas').attr('width', width);
$('.lower-canvas').attr('height', height);

$('.upper-canvas').attr('width', width);
$('.upper-canvas').attr('height', height);

canvas.renderAll();

If the size is set like that, there is no performance problem for zooming and scrolling.
However, the shape is drawn in the wrong location and the selection is also displayed in the wrong location when drawing a shape with the mouse!

![image](https://user-images.githubusercontent.com/40879690/104307630-d10d1580-5512-11eb-885a-8243831f2130.png)

How can I eliminate the degradation of performance due to the size differences between lower-canvas and upper-canvas in a mobile environment?

Let me know if there's a good way to solve this.

Thank you all.

**Comment by OilPrince** [comment]
I checked that there is the same phenomeno on fabric js homepage.

I used  Dev Tools of Google Chrome to check the size of canvas on my Android smartphone, which shows different sizes of canvas-container and lower-canvas and upper-canvas.(Difference by 4x difference)

![image](https://user-images.githubusercontent.com/40879690/104402430-9e5a3000-5599-11eb-88fc-ad4a2c54395d.png)

And when moving the shape, it is very slow.

You can easily check this phenomenon by opening the homepage on your android smartphone.

Is there anyone who can answer this question?

**Comment by OilPrince** [comment]
Somehow I solved this issue.

And when I checked again, the performance issue was occurring in Android-based devices.
There was no problems in iPhones and iPads!

While searching Google with the much-referred retina scale in this issue bulletin, I found the source code that checks for PIXEL_RATIO on the stackoverflow.

https://stackoverflow.com/questions/35820750/understanding-html-retina-canvas-support

When I checked the PIXEL_RATIO introduced here on the Android smartphone, the value was 4.

var PIXEL_RATIO = (function () {
    var ctx = document.createElement("canvas").getContext("2d"),
        dpr = window.devicePixelRatio || 1,
        bsr = ctx.webkitBackingStorePixelRatio ||
              ctx.mozBackingStorePixelRatio ||
              ctx.msBackingStorePixelRatio ||
              ctx.oBackingStorePixelRatio ||
              ctx.backingStorePixelRatio || 1;

    return dpr / bsr;
})();

console.log('PIXEL_RATIO=' + PIXEL_RATIO);


So I started to find fabric.devicePixelRatio in fabric.js, and overriding it with fabric.devicePixelRatio=1; in my JS!
Then the sizes of canvas-container and lower-canvas and upper-canvas are 

The performance issues and location errors were solved on Android smartphones.

The problem is solved so easily that it is somewhat embarrassing.
(Much do about nothing~~)

I want to know exactly why 'fabric js' use retina scale and whether or not there will be no problem with processing it this way, such as fabric.devicePixelRatio=1;

**Comment by Sooian** [comment]
> Somehow I solved this issue.
> 
> And when I checked again, the performance issue was occurring in Android-based devices.
> There was no problems in iPhones and iPads!
> 
> While searching Google with the much-referred retina scale in this issue bulletin, I found the source code that checks for PIXEL_RATIO on the stackoverflow.
> 
> https://stackoverflow.com/questions/35820750/understanding-html-retina-canvas-support
> 
> When I checked the PIXEL_RATIO introduced here on the Android smartphone, the value was 4.
> 
> var PIXEL_RATIO = (function () {
> var ctx = document.createElement("canvas").getContext("2d"),
> dpr = window.devicePixelRatio || 1,
> bsr = ctx.webkitBackingStorePixelRatio ||
> ctx.mozBackingStorePixelRatio ||
> ctx.msBackingStorePixelRatio ||
> ctx.oBackingStorePixelRatio ||
> ctx.backingStorePixelRatio || 1;
> 
> ```
>           return dpr / bsr;
> ```
> 
> })();
> 
> console.log('PIXEL_RATIO=' + PIXEL_RATIO);
> 
> So I started to find fabric.devicePixelRatio in fabric.js, and overriding it with fabric.devicePixelRatio=1; in my JS!
> Then the sizes of canvas-container and lower-canvas and upper-canvas match.
> 
> And then the performance issues and location errors were solved on Android smartphones.
> 
> The problem is solved so easily that it is somewhat embarrassing.
> (Much ado about nothing~~)
> 
> I want to know exactly why 'fabric js' use retina scale and whether or not there will be no problem with processing it this way, such as fabric.devicePixelRatio=1;

thanks, it works for me.

**Comment by asturur** [comment]
Sorry i m late to the party, setting the pixelRatio to 1 is equal to use `enableRetinaScaling: false` in the canvas options. without using custom code.
