### ISSUE TITLE
Textbox wrap text in cursor's position manually

### ISSUE THREAD

**Issue by chenyiqiao** [fabricjs/fabric.js#6803]
when text in textbox is about to be out of canvas, i need to wrap the text automatically, so that text would not just overflow and invisible. Here is code:
```js
// in text:changed event handler
const textboxRect = textbox.getBoundingRect();
if (textboxRect.left + textboxRect.width  >= textbox.canvas.width) {
  // no idea how to manually wrap text
}
```
Is there a way to wrap text in cursor's position manually?

**Comment by asturur** [comment]
I think you should constrain the width to do not grow, this will get you a wrap.
Did you try?
I'm not sure what the best event is to obtain that.
What did you try so far? can you replicate in a fiddle?

**Comment by chenyiqiao** [comment]
sure, https://jsfiddle.net/m320ed8r/3/ 

yeah, constrain the width is easy but the ultimate goal is that, textbox's width grows while input, at the same time, when it reaches the right boundary of canvas, it wraps. In the fiddle, i watch the text:changed event, found the boundary condition, but don't know how to wrap.

**Comment by chenyiqiao** [comment]
forget it, i chose the easy way and constrain the width

**Comment by gitgkk** [comment]
@chenyiqiao I have a similar issue. Could you please share the method you applied?
Thanks
