### ISSUE TITLE
how can I create a type of pdf canvas

### ISSUE THREAD

**Issue by sssning** [fabricjs/fabric.js#6804]
Hello,
When I use createPDFStream, wrong canvas type error occurs.
I found that getNodeCanvas to get the type of canvas for the image, how can I create a type of pdf canvas

**Comment by sssning** [comment]
I have solved this problem

**Comment by motyar** [comment]
> I have solved this problem

Can you please help? I am having same issue.

**Comment by sssning** [comment]
> > 我已经解决了这个问题
> 
> 你能帮忙吗？我有同样的问题。

fabric/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js 
` _getCanvas() {
    if (Canvas && !this._canvas) {
      this._canvas = Canvas.createCanvas(this.width, this.height,"pdf");
    }
    return this._canvas;
  }`
