### ISSUE TITLE
Filtering Big Images are only partially rendered or very laggish

### ISSUE THREAD

**Issue by advename** [fabricjs/fabric.js#6805]
## Version
3.6.0

## Test Case
https://jsfiddle.net/8mepkf2d/52/

## Information about environment
Browser: Firefox and Chrome (latest Jan. 2021)

## Description
I've been trying to apply filters on large background images (E.g. https://images.pexels.com/photos/2440079/pexels-photo-2440079.jpeg - 4000x5196px and 3.4MB) and even tried other large images (below 3000x3000px and 10MB in size).
However, using WebGL (My console notifies me my browser supports `"max texture size: 16384"`), only some 30% of the image is rendered after applying filters.
Using canvas2D as the filter backend is very slow and sluggish, with approx 0.5s - 1s delay (I could imagine because of the large size).

## Steps to reproduce
See interactive JSFiddle

## Expected Behavior
When applying filter on the image, the whole image should be rendered with the applied filter.
Moreover, the filters should be applied in near to real-time (below 0.1s delay and I guess this is only possible with WebGL for large images).

## Actual Behavior
Only a part of the image is rendered with applied filter on it.

**Comment by asturur** [comment]
your image is 4000x5196 and fabric texture size is 2048 by 2048.
Depending on your hardware you can filter bigger textures ( not sure for the consumer of your app tho )
https://jsfiddle.net/6t03wx7r/
Setting the texture size to bigger will solve the issue.
Most of it is explained here
http://fabricjs.com/fabric-filters

**Comment by advename** [comment]
@asturur Thanks for your reply and Fiddle!

At first i was very confused since I've used textureSize in the past (See issue #6603)

However, you used it too and it somehow worked.

After analysing both codes, I realized now, that you **must** set `fabric.textureSize` before calling the `fabric.initFilterBackend();` (Calling the filterbackend is an idea i got from your Filter demo http://fabricjs.com/image-filters).
It might be logical if you further analyze what `fabric.initFilterBackend();` and your Filter Demo do, but for the apprentice, this is not obvious nor do they have any resource that mentioned it.

So, setting textureSize first solves the problem of this and issue #6603!

**Comment by asturur** [comment]
be aware not all hardware supports 8k textures

**Comment by advename** [comment]
Yes, i did check that on my Macbook Pro 2015 (supports 8192) and my Huawei phone (supports 4096).
Any list of hardware texture support and percentages?

**Comment by asturur** [comment]
no idea. Old phones can be worse. that is why i put as starting 2k

**Comment by advename** [comment]
I see. I also noticed that the higher the value, the more laggy it gets.
E.g. for `textureSize = 20000` (20k), it doesn't matter if you have a 2k or 19k picture. Both lag the same way.

Now that I come to think, would it maybe be better to create a background image (`<img>`) and place the canvas on top of it? 
This way, one could use the CSS filter properties which don't seem to have any filtering issues with large images.

Or would it be impossible to precisely place the canvas on top of the image? My use case needs to be 100% precise.
(My thoughts are that I can simply take the image width and height and create a canvas using those dimensions and absolutely place it on top of the image)

**Comment by asturur** [comment]
If you all you need are filters covered from the native css or canvas filtering api, you can do that, sure.
It depends if then you need to export that in a different way.
a 20k texture won't work, because you can't create a 20k sided canvas that i know of.

**Comment by advename** [comment]
I mean I'm not moving or modify the background image any other way than only fill the back of the canvas with it and apply filters to it.
Is there anything to consider placing the canvas on top of an html img? Like scale/position wise (e.g. canvas has additional 4px margin nobody knows about)?

I see! My example was more meant that using a high textureSize value makes small and big images laggy.

**Comment by asturur** [comment]
i think that with 20k texture webgl fail, and fallback on the cpu version, you could notice a speed bump between 20k and the maximum supported value from your hardware.

No canvas has no borders, and can be styled anyway using the html classes that you see applied to the element inspecting it.

**Comment by umardev500** [comment]
I solve this just with icreate texture

`fabric.textureSize = 8192`

```
import { fabric } from 'fabric'
fabric.textureSize = 8192

const canvas = new fabric.Canvas('canvas', {
    backgroundColor: '#eee',
    width: 4058,
    height: 6086,
})

const image = new Image()
image.src = 'photo2.jpg'

image.onload = () => {
    const img = new fabric.Image(image)
    canvas.add(img)

    img.filters?.push(new fabric.Image.filters.Grayscale())
    img.applyFilters()
    canvas.renderAll()
}

```

**Comment by szeeshanali** [comment]
> I solve this just with icreate texture
> 
> `fabric.textureSize = 8192`
> 
> ```
> import { fabric } from 'fabric'
> fabric.textureSize = 8192
> 
> const canvas = new fabric.Canvas('canvas', {
>     backgroundColor: '#eee',
>     width: 4058,
>     height: 6086,
> })
> 
> const image = new Image()
> image.src = 'photo2.jpg'
> 
> image.onload = () => {
>     const img = new fabric.Image(image)
>     canvas.add(img)
> 
>     img.filters?.push(new fabric.Image.filters.Grayscale())
>     img.applyFilters()
>     canvas.renderAll()
> }
> ```

I think it will not work on mobile/tablet devices, could you please confirm?
