### ISSUE TITLE
Distorting images by dragging the corner control points, image resizes from center!

### ISSUE THREAD

**Issue by hoomanaskari** [fabricjs/fabric.js#6806]
## Version
4.3.0

## Test Case
https://codesandbox.io/s/image-distort-filter-for-fabric-clztr?file=/src/Photo.js

## Information about environment
Chrome latest

## Steps to reproduce
Try dragging the green custom control points to distort the image.

## Expected Behavior
Image should be resized without moving the object or other control points.

## Actual Behavior
Image resizes from center, moving other control points as well.

Hi, I hope this qualifies as an issue, if not feel free to close and I will ask on StackOverflow.

In any case here is the further info for the sandbox demo above.

I have created a subclass extending fabric.Image, this is in order to be able to use a fit layout mode, so that the image always fits in its bounds. `Photo.js -> this._renderFill(ctx)`

I have also created a custom filter, to distort the image using 4 coordinates.

I am trying to follow the example from http://fabricjs.com/custom-controls-polygon (slightly modified using the `Photo.js -> this._applyPointsOffset()` function).

The demo I have created is the closest I could get to the ideal scenario. The ideal being that by dragging any of the 4 corners, the image should distort only from that corner, keeping the rest of the control points in their places. In my example above, the effect is always resizing the image from center, moving other control points.

**Comment by asturur** [comment]
I can't load the example, it does not load for me.
Can you clarify more what are you doing?
is this an issue with something you created?
Is this an issue with the control api or you trying to use the control api?

**Comment by hoomanaskari** [comment]
Hi Andrea, thanks for the quick reply.

Sorry for the the demo not working, codesandbox does that sometimes, all you need to do is to click on the internal reload button to reload the demo. The preview works though, you can see the final results here as well: https://clztr.csb.app/

If neither worked, I will transform the code to older JS and put it on JSFilddle for you.

Basically what I wanna achieve is something similar to Photoshop free transform -> distort effect that you can see here: https://youtu.be/Pn-9qFNM6Zg?t=274

My demo also works in the similar fashion, the only issue is that fabric resizes the image from center every time I drag one of the control points.

**Comment by hoomanaskari** [comment]
In case the sandbox is not working still, here is a jsfiddle: https://jsfiddle.net/human_a/p6d71skm/

**Comment by asturur** [comment]
hi @hoomanaskari sorry for the late response.
To fix that you have to have your anchor point being the opposite of the one you are changing.
I see you have a setOriginByPosition that happens before the actions, while you have to have something that capture the current position and then apply it back after the transformation:

this is your current action wrapper:
```js
    _actionWrapper(anchorIndex, fn) {
        return function(eventData, transform, x, y) {
            if (!transform || !eventData) return;

            const { target } = transform;

            target._resetSizeAndPosition(anchorIndex);

            const actionPerformed = fn(eventData, transform, x, y);
            return actionPerformed;
        };
    }
```

while it should be something like:

```js
    _actionWrapper(anchorIndex, fn) {
        return function(eventData, transform, x, y) {
            if (!transform || !eventData) return;

            const { target } = transform;

            const position = target._getPositionByAnchor(anchorIndex);

            const actionPerformed = fn(eventData, transform, x, y);

            target._setPositionByAnchor(anchorIndex, position);
            return actionPerformed;
        };
    }
```

Now how those getPositionBy and setPositionBy should be written, i can't get into details because i don't have time to reverse the logic there.
I should have somewhere a very similar code to do this with steady positioning, i should ask if i can release it.
If you are still interested ping me mid next week i ll see if i have answers for my code

**Comment by hoomanaskari** [comment]
Thanks Andrea for getting back to this issue. I actually came up with another solution a while back, so no need to share your code here.

**Comment by asturur** [comment]
Cool! do you want to share how did you solve it?

**Comment by hoomanaskari** [comment]
The code went to production unfortunately, cannot share the exact code anymore. If I get some free time I might be able to solve it another way and then share.

I am also trying to make the Path objects editable (including curves etc.), and the same technic works for Paths as well (to keep them in their place when you drag points) Might also be able to share that one before it ships to production.

**Comment by asturur** [comment]
editable path are ok, between the control api and the polygon example people shoukd have all the need. You can improve the demo if you feel like

**Comment by hoomanaskari** [comment]
I have put a pin on that demo to come back to it and improve it later.

The main challenge right now is that with paths and polylines, scaling causes a lot of problems. In my case, I am actually reseting the scale, and instead move the points.

For image warping/perspective, the flipping is still causing some problems, once I fix them, I will publish a demo publicly.

**Comment by asturur** [comment]
one reason why i add path sinplification to fabricjs is becaus workink with only m,l c and Q you can actually transform the paths easily with matrices

**Comment by hoomanaskari** [comment]
Honestly the scaling is the smallest challenge I am having, I solved it with the following code:

```javascript
canvas.on('object:scaling', ({target}) => {
    if (!target) return;

    if (target.type === 'path') {
        resetPathScale(target);

        fabric.Polyline.prototype._setPositionDimensions.call(target, {});
    }
});

export function resetPathScale(object) {
    const { scaleX, scaleY } = object;
    const precision = fabric.Object.NUM_FRACTION_DIGITS;

    object.path.forEach(p => {
        const type = p[0];

        if (type.toLowerCase() === 'h') {
            p[1] *= scaleX;
            p[1] = Number(p[1].toFixed(precision));
        }

        if (type.toLowerCase() === 'v') {
            p[1] *= scaleY;
            p[1] = Number(p[1].toFixed(precision));
        }

        if (type.toLowerCase() === 'a') {
            // 1 -> rx
            // 2 -> ry

            // 3 -> x-axis-rotation

            // 4 -> large-arc-flag
            // 5 -> sweep-flag

            // 6 -> x
            // 7 -> y

            p[1] *= scaleX;
            p[2] *= scaleY;

            p[6] *= scaleX;
            p[7] *= scaleY;
        }

        if (type.toLowerCase() === 'm' || type.toLowerCase() === 'l') {
            p[1] *= scaleX;
            p[2] *= scaleY;

            p[1] = Number(p[1].toFixed(precision));
            p[2] = Number(p[2].toFixed(precision));
        }

        if (type.toLowerCase() === 'c') {
            p[1] *= scaleX;
            p[2] *= scaleY;
            p[3] *= scaleX;
            p[4] *= scaleY;
            p[5] *= scaleX;
            p[6] *= scaleY;

            p[1] = Number(p[1].toFixed(precision));
            p[2] = Number(p[2].toFixed(precision));
            p[3] = Number(p[3].toFixed(precision));
            p[4] = Number(p[4].toFixed(precision));
            p[5] = Number(p[5].toFixed(precision));
            p[6] = Number(p[6].toFixed(precision));
        } else

        if (type.toLowerCase() === 'q') {
            p[1] *= scaleX;
            p[2] *= scaleY;
            p[3] *= scaleX;
            p[4] *= scaleY;

            p[1] = Number(p[1].toFixed(precision));
            p[2] = Number(p[2].toFixed(precision));
            p[3] = Number(p[3].toFixed(precision));
            p[4] = Number(p[4].toFixed(precision));
        }
    });

    object.scaleX = 1;
    object.scaleY = 1;
}
``` 

The main challenge is finding the right control points, when you want to move them, or when you wanna convert a C to an L or M, what happens if the path is closed etc. There are too many different things to consider. The goal was eventually turning this into a Pen tool.

I created a Pen tool for fabric, based on [this prototype](https://github.com/mattdesl/path-illustrator) but then realized that now I have to take care of SVG imports and exports and fabric Path is doing a decent job in importing and exporting SVGs. So I scratched my Pen tool and now trying to make the Path objects fully editable.

The path simplification is helpful (though it does not cover H, V and A).

**Comment by asturur** [comment]
Which version of fabricjs are you working on? the 4.3.x has for sure the semplification. The path is mutated when loaded. At that point you have only L M C Q and the transformation ( from my limited tests ) consist in trasforming each point of the commanda for the matrix you want

**Comment by hoomanaskari** [comment]
I am using the latest version of fabricjs.

I created this SVG for testing the H, V, A and some other unexpected stuff for sub-standard SVG files our users might upload to our app. I am loading the SVG into the canvas, and when I try to add the controls to the path on double click, the H V and A are not simplified (it has both h and H, a and A, V and v)

I check the makePathSimpler function in fabric, thought there it is covering H V and A, in the case of the following SVG there were still there.

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 72 72"><defs><style>.cls-1{fill:#1d1d1b;}</style></defs><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><path class="cls-1" d="M50,0H22A22,22,0,0,0,0,22V50A22,22,0,0,0,22,72H50A22,22,0,0,0,72,50V22A22,22,0,0,0,50,0ZM27,18.18h0a10.94,10.94,0,0,1,7,4.5,10.83,10.83,0,0,0-2,5.32h-14A11,11,0,0,1,27,18.18Zm5,33.31a10.84,10.84,0,0,1-5,2.33h0A11,11,0,0,1,18,43a10.88,10.88,0,0,1,1.07-4.74A11.11,11.11,0,0,1,20.51,36,10.94,10.94,0,0,1,27,32.18h0A11,11,0,0,1,29,32H39v.75a11.12,11.12,0,0,0-3,1.76A11.65,11.65,0,0,0,34.51,36c-.18.22-.35.44-.51.68a10.22,10.22,0,0,0-1.39,2.71A10.77,10.77,0,0,0,32,43a10.9,10.9,0,0,0,2,6.32A10.84,10.84,0,0,1,32,51.49ZM54,43A11,11,0,0,1,43,54H34v-.42a10.87,10.87,0,0,0,4-2.09A11,11,0,0,0,42,43V29c0-.34,0-.67,0-1a11,11,0,0,0-8-9.58V18h9A11,11,0,0,1,54,28c0,.33,0,.66,0,1Z"/></g></g></svg>
```

If you are interested in this topic, another issue I have found was with optimized SVGs. I got the tiger SVG [from here](http://fabricjs.com/lib/tiger2.svg) and optimzied with [SVGOMG](https://jakearchibald.github.io/svgomg/) with it's default options and it broke the SVG when I imported it back into fabric (the original was working with no problem)

**Comment by asturur** [comment]
oh show me the optimized broken tiger please. Probably the semplification kicks in only on text on a path? i need to check the source code

**Comment by hoomanaskari** [comment]
Oh, I just tried it again to make a demo for you and it seems to be working. So either in the last update of fabricjs it's fixed, or the issue was from SVGOMG and they have fixed it. Last time I checked this was 2-3 weeks ago, but the issue is gone now.

Sorry if this wasted your time :(

**Comment by chenhuan360** [comment]
Hi @hoomanaskari, any updates in this feature ?

**Comment by GauravG8** [comment]
What was the solution you ended up with to bring image distort to FabricJS?

**Comment by noctivityinc** [comment]
@hoomanaskari please share your solution for this or something similar in the spirit of open source.  thanks.
