### ISSUE TITLE
Peer Dependency has security vulnerabilities on lodash@4.17.19

### ISSUE THREAD

**Issue by sj5677** [fabricjs/fabric.js#6816]
## Version
fabric@3.6.6 

## Issue
Hello there, our security scan has flagged issue regarding prototype pollution from lodash < 4.17.20
[https://snyk.io/vuln/SNYK-JS-LODASH-590103](https://snyk.io/vuln/SNYK-JS-LODASH-590103)

This lib is being brought it by jsdom@15.2.1 in fabric@3.6.6. 
➜  project git:(master) ✗ npm list fabric@3.6.6 lodash --prod
└─┬ fabric@3.6.6 
  └─┬ jsdom@15.2.1
    └─┬ request-promise-native@1.0.8
      └─┬ request-promise-core@1.1.3
        └── lodash@4.17.19

Wanted to check is there any way I can resolve the issue and will there be a new version with a fix for this? 

Thanks!

**Comment by asturur** [comment]
if package-lock can solve it we can solve it.
Id Jsdom is pinpointed to 4.17.19, no we can't.

**Comment by sj5677** [comment]
I see. Thanks for the info. Seem nothing much can be done unless request-promise-core upgrade it.
