### ISSUE TITLE
Set the background image, the size cannot be adjusted, and the online address cannot be set

### ISSUE THREAD

**Issue by jiaxiaon** [fabricjs/fabric.js#6817]
fabric.Image.fromURL(url, function(img, isError) {
        img.set({width: canvas.width, height: canvas.height, originX: 'left', originY: 'top'});
        canvas.setBackgroundImage(img, canvas.renderAll.bind(canvas));
    });

**Comment by melchiar** [comment]
Hello @jiaxiaon please follow the issue template and post in English so that we can help you - https://translate.google.ca/
