### ISSUE TITLE
TEXT BOX NO renderAll when we move fontWeight: 'bold' and fontStyle: 'italic'

### ISSUE THREAD

**Issue by matheuscamarques** [fabricjs/fabric.js#6819]
TEXT BOX NO renderAll when we move fontWeight: 'bold' and fontStyle: 'italic'

**Comment by melchiar** [comment]
Hi @matheuscamarques , can you please follow the issue template and provide a working fiddle so that we can try to help you?

**Comment by matheuscamarques** [comment]
I'm working with angular2,
but perhaps the error is not difficult to replicate
just change the bold of a text box or italics between turning these styles on and off and then calling canvas.updateAll (), the screen is ignoring changes to those styles ...
in version 4.2.0
works normally

**Comment by asturur** [comment]
Is there any particular reason why you do not feel like following the issue template?
Is it too hard or maybe is confusing how is written?
