### ISSUE TITLE
Any events for order movements (ie sendBackwards, bringForward, etc) ??

### ISSUE THREAD

**Issue by TheMangoTrain** [fabricjs/fabric.js#6822]
I'd like to listen for movement events (sendBackwards, bringForward, sendToBack and bringToFront), something along the lines of:

```
        canvas.on({
            'object:order': function () {
                console.log("An object changed order")
            }
        })
```

Does this exist?

Perhaps something undocumented, not listed here?
http://fabricjs.com/events

**Comment by asturur** [comment]
This is a common request, together with other similar. The issue is that there
is no way for the user to trigger a z order change without running some code from the developer. The developer, in this case you, should add the code that was thinking to add in an event, in the function that
empower the user to change the z-order.

Do you agree?

**Comment by TheMangoTrain** [comment]
Ok, I can agree that there is a subjective point where Fabric can stop holding a dev's hand, haha =P.  I was just curious since there's fine-grained events for everything else, much of which may originate either from an end-user or programmatically.

For context, I have a layer stack with thumbnails, synchronized with the canvas objects; it works. Looking ahead I had in mind that back/front movements could originate elsewhere in the app and wanted to account for that possibility. A Fabric event would have been super convenient. I suppose if the layer inputs occur app-wide then the layer management should be app-wide ie Managing the array in a global store (VueX in this case, being a Vue app), including listeners.

**Comment by asturur** [comment]
For me all boiled down to a function shared across components ( a button, a keyboard shortcut, a side effect ) that would execute the fabric code needed ( Object.moveForward for example ) and everything else i needed ( analytics, undo/redo stack changes, UI updates ).

We can't make an event for everything, events should be there just for things that the developer has no control over.
object:added and object:removed are for example 2 events that today do not make sense to me anymore.
