### ISSUE TITLE
How can apply pattern to the Image Object

### ISSUE THREAD

**Issue by nimulavani** [fabricjs/fabric.js#6824]
Hi,
First of all ,Thanks for your patience in answer the questions @Andrea Bogazzi and great npm.
I know my question is similar to https://github.com/fabricjs/fabric.js/issues/2112
Still I did not get answer for  that also.how can use fillForImage?
This is JSFiddle
http://jsfiddle.net/QT3pa/36/

**Comment by asturur** [comment]
Can you be more clear on what would you like to do?
 We do not have an extra fill for images today.
 What are you looking for exactly?
