### ISSUE TITLE
Object corner points in multiselection not calculated correctly

### ISSUE THREAD

**Issue by acdvs** [fabricjs/fabric.js#6826]
## Version
4.3.0

## Test Cases
https://jsfiddle.net/b20puesy/
https://jsfiddle.net/24a35vtj/

## Information about environment
Latest Chrome and JSFiddle

## Steps to reproduce
Explained in the JSFiddles above (reproduction depends on which way the code is written).

## Expected Behavior
When using `Object.isOnScreen` and `Canvas.remove` to remove objects outside the canvas bounds, objects in a multiselection should be removed when dragged outside canvas bounds.

## Actual Behavior
When using `Object.isOnScreen` and `Canvas.remove` to remove objects outside the canvas bounds, objects in a multiselection will either unexpectedly disappear or not be removed at all. See test cases above.

**Comment by acdvs** [comment]
After further investigation it looks like this is a problem with the underlying coordinate calculation and not the `Object.isOnScreen` method itself. Updating the issue to reflect this.

**Comment by asturur** [comment]
yes object in multi selections have the 4 main corners relative to the group they are in, isOnScreen could have a slower path to take that into account

**Comment by acdvs** [comment]
Could you explain what you mean? I'm not sure I understand.

[Here's another JSFiddle](https://jsfiddle.net/wz0ykqd9/28/) showing the bug. Select and move each group of objects. The left group is calculated correctly while the right group isn't.

**Comment by asturur** [comment]
i mean that object.isOnscreen should be fixed to work in the use case you are mentioning
