### ISSUE TITLE
[Question]Pinch to zoom in iOS UIScrollView (native)

### ISSUE THREAD

**Issue by FlashTang** [fabricjs/fabric.js#6827]
Hi , I'm creating a cross-platform mindmap app
and I'm trying to use fabric for the core feature  (other UI will use native iOS, Android ,window ...), so I think I can save a lot of work
First I try in iOS
when I load fabric html to WKWebView (this WKWebView is inside a UIScrollView)
the problem is I can not scroll and pinch to zoom-in zoom out the UIScrollView 
but I can zoom it if I DO NOT initialize the fabric (normal html)
how can I fix it ? I want the native UIScrollView can zoom the WKWebView(with a fabric html)
P.S. I know I can not scroll it when the fabric dragging etc enabled, but I think pinching to zoom is not in conflict
Thanks

**Comment by asturur** [comment]
My personal suggestion is to ignore
our gesture plugin and add hammer.js to detect a pinch to zoom gesture and then connect that to the canvas zoom.

unless you know a modern js library to deal with touch events.

I should have an example somwhere

**Comment by FlashTang** [comment]
@asturur Thanks for your suggestion, seems I need make a scrollview in canvas, I will check hammer.js
