### ISSUE TITLE
Set text is not properly rendered with 4.3.0

### ISSUE THREAD

**Issue by acorbel** [fabricjs/fabric.js#6836]
Hi,

First of all, thank you for your hard work and this library! It is awesome!
We spotted a little regression with the release **4.3.0**.

When using the **set** command for a text node (```set('text', newtext)```), it is not properly rendered.

The release 4.2.0 works well.

Another ref: https://github.com/fabricjs/fabric.js/issues/6783#issuecomment-754364970

**Comment by melchiar** [comment]
Hi, yes there's an issue for this already #6832. The fix for it is in this commit which should be published soon: https://github.com/fabricjs/fabric.js/commit/bd2d3226b8ef8d456d9222b7c89a08b98a065f8d

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/releases/tag/v4.3.1

published

**Comment by acorbel** [comment]
Awesome! Thank you!
