### ISSUE TITLE
Textpath character rotation issue

### ISSUE THREAD

**Issue by melchiar** [fabricjs/fabric.js#6838]
## Version
4.3.1

## Test Case
https://jsfiddle.net/melchiar/7v8j92sw/

## Information about environment
Browser

## Description
Looks like something in 4.3.1 broke text path character rotation
![image](https://user-images.githubusercontent.com/9057412/106086013-25e58a00-60d6-11eb-9500-50db986d32a7.png)

**Comment by asturur** [comment]
Of course the visual tests are the one i did not push on git hub actions yet. :(

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/106350140-e8e6e680-62d3-11eb-8379-ce7e7e0c6dcf.png)

Hey it works for me!
What's going on?

**Comment by asturur** [comment]
lol @melchiar mistake in plain view:

![image](https://user-images.githubusercontent.com/1194048/106350178-29466480-62d4-11eb-984d-5c9dec63cc18.png)

You linked the latest but also added a script with 4.3.0

nolink: https://jsfiddle.net/6pctzLo8/

not sure why the result is a mixed broken version, but i think we can close this.

**Comment by melchiar** [comment]
Oops!
