### ISSUE TITLE
Object order changes when grouping items selected individually (shift-clicked) with preserveObjectStacking: true

### ISSUE THREAD

**Issue by sjscotti** [fabricjs/fabric.js#6840]
## Version
4.3.1

## Test Case (use "current module view" to see graphics)
https://codesandbox.io/s/amazing-borg-5srzj?file=/src/index.js

## Information about environment
browser
Which browsers: chrome and firefox

## Steps to reproduce
In the test case, there are 3 overlapping colored rectangles - green on top, which overlaps blue, which overlaps red.  When you select the green one first, then shift-click the blue one, then shift-click the red one they are all members of an `activeSelection`.  The button on the bottom will change the `activeSelection` into a `group`.  Press the button and when the `activeSelection` converted into a `group`, the red rectangle changes position and now overlaps the blue rectangle - the order for display has changed

## Expected Behavior
After they are selected as described above and the button is pressed, the 3 rectangles should now become a `group` and the display order should not change.   It does not change when `preserveObjectStacking` is `false`, only when it is `true`

## Actual Behavior
When converted into a `group`, the red rectangle changes position and now overlaps the blue rectangle - the order for display has changed.  But this only happens when `preserveObjectStacking` is `true`

**Comment by asturur** [comment]
I see.
I assume this is how it is more than a bug.
Shift clicking objects put them in an active selection in click order, but are still rendered in canvas order.
When they get to become a group, the are moved in a sub array in click order and they can't be rendered anymore in the old stack.

Since we have the `toGroup` method, it shouldn't be hard to add an option to have it keep the canvas order.
I can't work on this right now, i ll mark this issue here as a feature easy for beginners and if someone wants can handle it.

It should be just about array manipulation in a single function ( and adding a test )

**Comment by sjscotti** [comment]
Here is the prototype I created that overwrites the `.toGroup` function to fix this problem.  It only added a single `sort` of the objects in the active selection (see statement after the comment).  It seems to work, but does it look OK?

```
fabric.ActiveSelection.prototype.toGroup = function() {
	var objects = this._objects.concat();
	// added this sort to maintain display order... 
	objects.sort(function(a, b){  
		return this.canvas._objects.indexOf(a) - this.canvas._objects.indexOf(b);
	});
	this._objects = [];
	var options = fabric.Object.prototype.toObject.call(this);
	var newGroup = new fabric.Group([]);
	delete options.type;
	newGroup.set(options);
	objects.forEach(function(object) {
	  object.canvas.remove(object);
	  object.group = newGroup;
	});
	newGroup._objects = objects;
	if (!this.canvas) {
	  return newGroup;
	}
	var canvas = this.canvas;
	canvas.add(newGroup);
	canvas._activeObject = newGroup;
	newGroup.setCoords();
	return newGroup;
  }
```

**Comment by asturur** [comment]
That would be ok, but should be optional.
`toGroup({ useCanvasStacking: true })` or something on this chords.
And you would need a test of course.

**Comment by sjscotti** [comment]
Thanks!
BTW, I also found another instance in my code where individually selected objects using shift-click were not following the canvas display order - when doing a copy of the `activeSelection` object to clipboard, the pasted order of the objects wasn't following canvas display order.  Since for my use, I always want the displayed objects to follow the original canvas display order, I abandoned the modified `fabric.ActiveSelection.prototype.toGroup` approach, and instead I do a sort (similar to what I added in the `.prototype.toGroup` in my above comment) of the `_objects` in the `activeSelection`  object from within the handler for the `selection:created` and `selection:updated` events that was already part of my code.  Less code and it seems to work in both the group and paste cases.

**Comment by asturur** [comment]
Let's leave it open, maybe someone comes with the idea of implementing it and this discussion is useful

**Comment by sharvy** [comment]
@asturur Can I take this issue?

**Comment by asturur** [comment]
sure!

**Comment by andz89** [comment]
I hope someone  or from fabric js team to answer this issue.

**Comment by asturur** [comment]
There is also the code posted with the solution here in the thread

**Comment by asturur** [comment]
@ShaMan123 @melchiar if you have time, this should be really straight forward

**Comment by asturur** [comment]
or @stefanhayden may has a comeback for a quickfix.
or @rileygowan that is on PTO right now, plenty of free time

**Comment by ShaMan123** [comment]
I have triaged this issue to https://github.com/fabricjs/fabric.js/blob/887a745b5943492478b12a79519f381a23758e4d/src/mixins/canvas_grouping.mixin.js#L63
