### ISSUE TITLE
Hebrew Text with special character display at wrong side

### ISSUE THREAD

**Issue by soumen-cn** [fabricjs/fabric.js#6848]
## Version
Fabric js version: 3.6.3

## Information about environment
Angular version: 8.2.3
The issue coming in all desktop and mobile browser

## Steps to reproduce

I have a canvas with Hebrew text (Fabric` type : "text"`) and a text input field. onkeyup of the input field the text will be updated to the canvas object. As it is Hebrew text direction is set to rtl in the input field. If I put any special character at the end or start of the string the special character shows in the wrong direction. For example, If in the input field shows **,/.הקלד כאן טקסט עבר** it will display on canvas **הקלד כאן טקסט עברי./,**  
Special characters in the middle of Hebrew text works properly.

## Code
Html

```
<input class="txtbox" style="direction: rtl;"
type="text" [value]="item.text"
(input)="inputChange($event, i)">
```

TS code
```
inputChange(event: any, i) {
this.canvas.setActiveObject(this.canvas.item(i));
let obj = this.canvas.getActiveObject();
  if (obj) {
      obj.set({
        text: event.target.value
      });
      this.canvas.renderAll();
    }
}
```

## Screenshots

Input field Screenshot
![Screenshot 2021-02-03 at 6 08 20 PM](https://user-images.githubusercontent.com/56528088/106748417-37391400-664b-11eb-9f2a-f889a4eadf84.png)

Canvas screenshot
![Screenshot 2021-02-03 at 6 08 06 PM](https://user-images.githubusercontent.com/56528088/106748462-43bd6c80-664b-11eb-99a2-a821fe90de35.png)

**Comment by asturur** [comment]
hi @soumen-cn, we know RTL text is not working properly yet.
I have been given an implementation by someone but i did not have time to look into it yet.

**Comment by asturur** [comment]
duplicate of #2374

**Comment by mistriel** [comment]
watching

**Comment by asturur** [comment]
#2374 is the correct issue to watch. This should be closed as a duplicate

**Comment by chiragbytes** [comment]
@soumen-cn  
Having the same issue of hebrew text flipped when try to add charSpacing property to text, can you please help me what specific settings I need to apply to stop flipping of character with 'charSpacing'

_ "fabric": "^3.6.3",_

**Comment by pini85** [comment]
> @soumen-cn Having the same issue of hebrew text flipped when try to add charSpacing property to text, can you please help me what specific settings I need to apply to stop flipping of character with 'charSpacing'
> 
> ` "fabric": "^3.6.3","@types/fabric": "^3.6.2",`

how did you get rtl direction before charSpacing?
