### ISSUE TITLE
Borders enter transparent state immediately on select

### ISSUE THREAD

**Issue by dellvolk** [fabricjs/fabric.js#6853]
Version
2.4.1+

Test Case
http://jsfiddle.net/d8bmvp4s/1/

Information about environment
Newest version of Chrome w/ Windows 7

Steps to reproduce
The fiddle automatically sets the object as active in which case the border is completely black.. When clicking off and setting the box as active again with the cursor, the border either highlights back to black or remains in a transparent state. It's completely random, and if you click off and back onto it several times, it will alternate between states. This behavior now occurs in all fabricjs examples.

Expected Behavior
The border should be black when selected, and grey when being altered.
defaultstate

Actual Behavior
The border states seem to alternate between the black and grey version on select. One moment it will select with a black border, and another moment it will be grey.
reproduction

![48216067-bdbdf880-e351-11e8-9636-985edd4ef098](https://user-images.githubusercontent.com/65287041/107122230-27b20900-689f-11eb-9a67-5860041e5c02.gif)

**Comment by asturur** [comment]
This was already reported and the complete randomness makes super hard to understand what is going on.

**Comment by dellvolk** [comment]
> h

Are there any ways to solve this problem?

**Comment by dellvolk** [comment]
> This was already reported and the complete randomness makes super hard to understand what is going on.

Are there any ways to solve this problem?

**Comment by GhostNA** [comment]
@asturur can you disable randomness?

**Comment by asturur** [comment]
Well reproduce it reliably would lead to a fix, i m sure.
I get it to happen 3 clicks over 20 more or less.

**Comment by dellvolk** [comment]
@asturur And it is possible to take away this transparency in general, or to change color at object: scaling?

**Comment by asturur** [comment]
did you check in the docs for properties that  have the word opacity/transparency in the name? i can't remember on top of my head.

**Comment by asturur** [comment]
http://fabricjs.com/docs/fabric.Object.html#borderOpacityWhenMoving

You can set this to 1 to remove the issue.

**Comment by asturur** [comment]
@dellvolk did you copy paste #5378?
