### ISSUE TITLE
Parsing SVG Shadow filters

### ISSUE THREAD

**Issue by andreafalzetti** [fabricjs/fabric.js#6855]
I am trying to load an SVG containing shadows which uses the feGaussianBlur filter. I found from the [FabricJS PR 2349](https://github.com/fabricjs/fabric.js/pull/2349) that Fabric is able to create SVG with shadows, however when you load the same SVG ouput into the canvas again, the shadow is not rendered.

I was wondering if this is a bug, missing funcionality, or it's not doable?

Thanks!

## Version
4.3.1

## Test Case
https://jsfiddle.net/andreafalzetti/s6rvdxzw/8/

## Information about environment
Browser
Tested on Firefox and Chrome

## Steps to reproduce
Load an SVG which contains shadow effects such as feGaussianBlur

## Expected Behavior
The

**Comment by asturur** [comment]
We do not have a filter parser for svgs.
And if we had, it won't be translated in a simple shadow.

On the other hand we have an open PR for appling filters on objects and that could allow simple svg filters to be imported in fabricJS.

SVG filters are much elaborated and allow for defining a pixel pipeline that we do not intend to support, and also please take in account that SVG is not meant to be used as a format for import and export
