### ISSUE TITLE
Cannot resize active object when Canvas is assigned to Vue component data

### ISSUE THREAD

**Issue by Gavin-Dreyer** [fabricjs/fabric.js#6863]
Hi, this is the first time I've ever opened a github issue. I was hoping for some guidance in solving this issue. I apologize if this is the wrong place to bring this concern. 

## Version
fabric.js 4.3.0
Vue 3.0.5

## Test Case
https://codesandbox.io/s/fragrant-sky-87umm?file=/src/components/Canvas.vue

## Information about environment
Chrome/Mozilla

## Steps to reproduce
When you have assigned a Fabric Canvas to a Vue component and are hovering an active object's corner you cannot resize the object because of the first if statement inside _findTargetCorner.

## Expected Behavior
Resize an active object on the canvas

## Actual Behavior
In _findTargetCorner the first if statement does not pass this.canvas._activeObject !== this and you cannot resize your active object.

**Comment by asturur** [comment]
Ok i have to say, i know nothing of VUE.
But this is an interesting issue.
Probably VUE does some magic under the hood that is breaking something.

I managed to get it to work doing this:

https://codesandbox.io/s/shy-rain-nvfzk?file=/src/components/Canvas.vue

But i realize how this could be totally outside what you want to do.

I would need to understand better VUE to help you. Maybe you can open an issue on the VUE issue tracker and ping me there? maybe we can understand it better.

**Comment by asturur** [comment]
Closing this issue, should be moved on the VUE board.
