### ISSUE TITLE
Modify objects in a group 

### ISSUE THREAD

**Issue by idealstudija** [fabricjs/fabric.js#6864]
## Version
3.0.0

## Test Case
https://jsfiddle.net/idealstudija/mj6Ls7z3/

## Information about environment
Browser

## Steps to reproduce
There is a group consisting of three objects. This group can be resized, rotated, and so on.

You can use the buttons to select objects individually. 
https://www.dropbox.com/s/vs3fvgtnza77iai/%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D1%8C_2021_02_12_18_15_24_191.mp4

## Expected Behavior
When each object is selected separately, but they don't have the ability to resize, rotate, etc.

## Actual Behavior
Individually, each object can be selected and moved, and you also need to change the size and rotate

**Comment by asturur** [comment]
fabricJS does not support transforming objects inside a group.
Not yet and is not on the roadmap yet.

**Comment by nhatnd2206** [comment]
I am using Fabric JS to draw a arrow. I've combined a line and a triangle into one group. How can I update the properties of objects in the group when the user enters from the screen?
