### ISSUE TITLE
Canvas objects deleted when video seeking

### ISSUE THREAD

**Issue by shadrech** [fabricjs/fabric.js#6873]
## Version
3.6.0

## Test Case
https://jsbin.com/riqaqig/1/edit?html,js,output

## Information about environment
On chrome browser. Also brave browser

## Steps to reproduce
When I try integrate a video background into a canvas, then add objects. When seeking the video the canvas either displaces other objects or in my projects case deletes the other objects altogether.

## Expected Behavior
When seeking video other objects should not be effected

## Actual Behavior
When seeking video other objects are rendered weird or removed from canvas

**Comment by asturur** [comment]
I have been looking into this 2 times, and seems like the loop with requestRenderAll or renderAll is breaking object movements, a thing i would not expect at all.
I need to see if this is a bug, you code is simple and i think is ok.

**Comment by ShaMan123** [comment]
You have created endless instances of `fabric.Canvas` attached to the same HTMLCanvas.
That's why everything went crazy.
I am not sure about attaching to `oncanplay` but anyways I've added a flag to prevent endless intializations.

**Comment by ShaMan123** [comment]
closing.
If you think we should reopen comment below.

**Comment by ShaMan123** [comment]
@asturur should we added an attribute on the canvas html object to avoid this?
