### ISSUE TITLE
Fabric Pattern : repeat-x, repeat-y not working using in firefox

### ISSUE THREAD

**Issue by umangvyas** [fabricjs/fabric.js#6875]
## Version
4.3.1

## Test Case
https://jsfiddle.net/rhq8f6nx/
Even it is not working on http://fabricjs.com/patterns (Firefox)

## Information about environment
Nodejs
Firefox

## Steps to reproduce
1. Apply pattern on rect object or canvas background.
2. Set the repeat option to 'repeat-x' or 'repeat-y'.

## Expected Behavior

The pattern should be repeated in only one direct either X or Y

## Actual Behavior
The pattern is repeating in both directions X and Y.

**Comment by asturur** [comment]
Yes is a firefox old bug, 12 years old.
I'm not sure they are gonna ever fix it.

**Comment by umangvyas** [comment]
Hello Asturur,

Thank you for your reply.

The same concern I am facing in Nodejs as well.

**Comment by asturur** [comment]
that is a limitation of node-canvas. I think they both use cairo as a backend
