### ISSUE TITLE
Objects move on touch select

### ISSUE THREAD

**Issue by billensley** [fabricjs/fabric.js#6877]
## Version
4.1.0

## Test Case
http://jsfiddle.net/y2rdL6s4/

## Information about environment
Chromium Based Mobile Browsers, the issue does not seem to effect Mozilla Based Mobile Browsers as much

## Steps to reproduce
Touch an object and it moves fractionally

## Expected Behavior
Touch an object to select it and with a slight delay or touch again for movement

## Actual Behavior
Touch an object and it moves fractionally.  Is there any way to stop this movement on an object when selected by touch?

If it were possible to select with one touch and then touch again to move it would completely solve the issue.

**Comment by melchiar** [comment]
Hi, this is a known issue and a new property is coming in the next release to address it. 

#6807 - the object level property `activeOn` will have a value of `down` by default, but you can set it to `up` so that objects are only made active on mouseup/touchend

**Comment by billensley** [comment]
Fantastic, I've been meaning to reach out on it for a while, seems like someone beat me to it.
 
 -Bill Ensley
 BearPrinting.com
 
 
On 2/19/2021 2:08 PM, Steve Eberhardt wrote:
 
 

Hi, this is a known issue and a new property is coming in the next release to address it.

 

#6807 - the object level property activeOn will have a value of down by default, but you can set it to up so that objects are only made active on mouseup/touchend
