### ISSUE TITLE
Your Polygon node dragging examples doesn't work when flipped or mirrored

### ISSUE THREAD

**Issue by biggestdickus** [fabricjs/fabric.js#6886]
## Version
3.6.0

## Test Case
http://fabricjs.com/custom-controls-polygon

## Information about environment
Nodejs or browser?
Doesn't matter

## Steps to reproduce
mirror Flip the polygon

## Expected Behavior
the nodes should work when dragged

## Actual Behavior
The thing ODs
The node's index or whatever should be reversed when flipped, mirrored

Want I really need: The repositions of corner nodes on lines, polyline and polygons should be done by the plugin.

**Comment by asturur** [comment]
while the demo should be fixed, the answer to 'why should i write 50 lines of code' is because that is not a fabricjs feature, and won't be.
Why people should have extra 50 lines of code in an already big library because once in a while someone has to change polygon points?

We can't add everything.

**Comment by biggestdickus** [comment]
"The waiting is the hardest part" - T. Petty

**Comment by asturur** [comment]
Guys alone is hard to keep track if everything to do. I have at least 150 issue to take care of. And i have to continuosly postpone new features to keep the issue tracker at least managed

**Comment by hoomanaskari** [comment]
I am currently working on fixing this, if you can point me in the right direction, as of where to look for the culprit, I can help as well. If I do, I will post the solution here for others as well.

**Comment by asturur** [comment]
Something here has been oversimplified.

```js
function actionHandler(eventData, transform, x, y) {
		var polygon = transform.target,
		    currentControl = polygon.controls[polygon.__corner],
		    mouseLocalPosition = polygon.toLocalPoint(new fabric.Point(x, y), 'center', 'center'),
        polygonBaseSize = polygon._getNonTransformedDimensions(),
				size = polygon._getTransformedDimensions(0, 0),
				finalPointPosition = {
					x: mouseLocalPosition.x * polygonBaseSize.x / size.x + polygon.pathOffset.x,
					y: mouseLocalPosition.y * polygonBaseSize.y / size.y + polygon.pathOffset.y
				};
		polygon.points[currentControl.pointIndex] = finalPointPosition;
		return true;
	}
```

Quick fixes could include:
- flipping the sign of mouseLocalPosition x/y depending on flipX/flipY of the polygon
OR
- fipping the +/- in front of polygon.pathOffset.x/y depending on flipX/flipY
That is a tentative i would do.

I'm sure there is a more concise way to describe this action, but i do not have the strength to find it.

Probably working with a mouse movement dx/dy and then transforming that movement vector for the inverse of object transform would be easier to read and make it work. But i'm not sure there is a standard well supported way to get the current movement from eventData

**Comment by dahui4dev** [comment]
@hoomanaskari Hey, man, have you solved this problem?

**Comment by hoomanaskari** [comment]
@dahui4dev I ended up disabling flipping all together since I have subclassed all my shape objects and they don't use scaling anymore.

**Comment by ShaMan123** [comment]
duplicate #7029

**Comment by graphics-et-al** [comment]
Hi, just hit this problem in my project.
@asturur : The issue seems to be that when a polyline is flipped, it's only **rendered** flipped, the underlying points are not updated. Example: I make a line
![image](https://user-images.githubusercontent.com/61042543/195058178-ea95f5db-f9ef-4ff1-af6f-43154badd1f5.png)
and inspect the properties
![image](https://user-images.githubusercontent.com/61042543/195058502-bbb4d9bd-16b4-468d-b550-da1e1430705b.png)
Then flip it and inspect the properties again:
![image](https://user-images.githubusercontent.com/61042543/195058703-1ae7e2e8-a40a-4db2-8a02-b2c908c4346b.png)

Note that only the flipX has changed, not the points array.

**Comment by graphics-et-al** [comment]
Workaround until proper fix: 

`        // 'Flip' a poygon by swapping around the points- massive hack (and probably can be simplified) but ¯\_(ツ)_/¯
        const flipPoly = (polygon, x_or_y) => {
            // difference between x and y
            switch (x_or_y) {
                case 'x':
                    let max_x = Math.max(...polygon.points.map((el) => el.x));
                    let min_x = Math.min(...polygon.points.map((el) => el.x));
                    let mid_x = ((max_x - min_x) / 2) + min_x;
                    polygon.points.forEach((element) => {
                        let diff = Math.abs(element.x - mid_x)
                        element.x = (element.x <= mid_x) ? mid_x + diff : mid_x - diff
                    });
                    break;
                case 'y':
                    let max_y = Math.max(...polygon.points.map((el) => el.y));
                    let min_y = Math.min(...polygon.points.map((el) => el.y));
                    let mid_y = ((max_y - min_y) / 2) + min_y;
                    polygon.points.forEach((element) => {
                        let diff = Math.abs(element.y - mid_y)
                        element.x = (element.y <= mid_y) ? mid_y + diff : mid_y - diff
                    });
                    break;
                default:
                    // do something neutral here if x or y is not set/correct. Tell my wife I said... hello
                    break;
            }
            // update display
            polygon.dirty = true;
            canvas.requestRenderAll();
        }`

**Comment by ShaMan123** [comment]
We are planning to add polygon controls to core
Once we do that they will be fixed for this case as well

**Comment by biggestdickus** [comment]
4/15/2024 : Here's an excellent work around that can be drawn, resized, moved, rotated, edited on a single or multiple polygons.
http://codepen.io/Rstewart/details/VwNBZwJ

**Comment by graphics-et-al** [comment]
> 4/15/2024 : Here's an excellent work around that can be drawn, resized, moved, rotated, edited on a single or multiple polygons. http://codepen.io/Rstewart/details/VwNBZwJ

That's brilliant. I'll see if it's compatible with my stuff

**Comment by biggestdickus** [comment]
Graphics et al: Thank Yah, I only wish the Polygons/Polylines didn't have to be redrawn is order to get an offset when moved or edited (too much extra coding). I ready wanted to add a convert polyline to curve and/or add remove a nodes functions. Having to redraw the polygon each time makes it too complicated to add additional features. I also have an example that uses Path rather than an XY Points array. However, again too many variables required to redrawing of the Bezier controls handles, etc.. Hopefully a total new polygon function will be added in the future so they don't have to be redrawn from scatch each time. Must put CorelDraw and Illustrator to shame.    On Sunday, May 19, 2024 at 11:49:17 PM EDT, Graphics et al ***@***.***> wrote:  
 
 



4/15/2024 : Here's an excellent work around that can be drawn, resized, moved, rotated, edited on a single or multiple polygons. http://codepen.io/Rstewart/details/VwNBZwJ


That's brilliant. I'll see if it's compatible with my stuff
