### ISSUE TITLE
Event handling in Angular

### ISSUE THREAD

**Issue by Utsav-Sharma33** [fabricjs/fabric.js#6887]
Hi all,
I am finding difficulty in handling fabric js object event in angular 8 application. Whenever I use on method and add event in it, the function attached to it is not fired at all.

**Comment by Utsav-Sharma33** [comment]
Please guide me how to handle events ofgabric js objects in Angular 2+ versions.

**Comment by asturur** [comment]
You should show what are you doing in a codepen, start a simple angular 8 powered app with a canvas and where the issue is.
I have no angular expertise.
