### ISSUE TITLE
make an object selectable but not draggable.

### ISSUE THREAD

**Issue by suvamkundu** [fabricjs/fabric.js#6891]
Hi,
I was looking through the docs but couldn't find any reference to it. I want to make a polygon object selectable (ActiveObject) but I don't want to make it draggable or movable. Is there any way to achieve it?

**Comment by melchiar** [comment]
See the docs:

[lockMovementX](http://fabricjs.com/docs/fabric.Object.html#lockMovementX)
[lockMovementY](http://fabricjs.com/docs/fabric.Object.html#lockMovementY)
