### ISSUE TITLE
Incorrect render position of svg inside a scaled fabric.Group with uniform stroke

### ISSUE THREAD

**Issue by dannmalik** [fabricjs/fabric.js#6900]
## Version
4.3.1

## Test Case
http://jsfiddle.net/DaniyalMalik/xjLmup6r/68/

## Information about environment
Javascript on Chrome

## Steps to reproduce
Just scale the group item and see how the position of the svg gets away from selector boundary. If you disable uniform scaling, the position of svg renders correctly. I'm adding it inside a fabric.Group because I want to add other items in the group and I want to keep the uniform scaling while keeping the svg inside the box. The top left of the svg should be at the top left of the selector box.

## Expected Behavior
![Expected Behavior](https://user-images.githubusercontent.com/79746305/109384462-ba7a1c80-790e-11eb-9afc-eca0a3166ed9.png)

## Actual Behavior
![Actual Behavior](https://user-images.githubusercontent.com/79746305/109384974-345fd500-7912-11eb-8097-d287476952b3.png)

**Comment by asturur** [comment]
https://jsfiddle.net/1s4huktv/
If you do not add custom code to the group it seems to work fine. That fiddle is not good to show a bug since too much is going on there.
Try to simplify it and i will reopen the issue.

**Comment by dannmalik** [comment]
In my custom code, I was trying to scale svg according to the group scale. Let's just forget about the custom code. What you have done is that you created a group with an svg in it. In my task, I have to add the svg later on and scale it according to the group dimensions (not vice versa). 

When you add the svg later on, you have to give it coordinates of where you want to add it in the group with default being center of the group. So I want it to stay on top left of the bounding box. How to do that? 

Okay let's even forget about scaling. How to ensure that svg stays to the top left of the bounding box? Here's the jsfiddle:
https://jsfiddle.net/DaniyalMalik/bh59qs3e/19/

I gave it the coordinates of left: -dimension_group.width/2 and top: -dimension_group.height/2 to get it to top left of the group. How to keep svg to the top-left of bounding box?

**Comment by dannmalik** [comment]
In my custom code, I was trying to scale svg according to the group scale. Let's just forget about the custom code. What you have done is that you created a group with an svg in it. In my task, I have to add the svg later on and scale it according to the group dimensions (not vice versa).

When you add the svg later on, you have to give it coordinates of where you want to add it in the group with default being center of the group. So I want it to stay on top left of the bounding box. How to do that?

Okay let's even forget about scaling. How to ensure that svg stays to the top left of the bounding box? Here's the jsfiddle:
https://jsfiddle.net/DaniyalMalik/bh59qs3e/19/

I gave it the coordinates of left: -dimension_group.width/2 and top: -dimension_group.height/2 to get it to top left of the group. How to keep svg to the top-left of bounding box?

**Comment by asturur** [comment]
Well the issue was titled as 'incorrect render of a svg in a scaled group'
and that does not seem to be the case.

The only way of adding things to a group for now is using addWithUpdate but
all the positioning issues yours.

If you want an object to stay in a particolar corner of the group you need
first to know how big the group is, the calculate your object position as
-group.width/2 -group.height/2.

Stroke uniform will make everything more complicated because the inner
group will change size while scaling and its position won't be modified
again.

**Comment by dannmalik** [comment]
Okay so I tried scaling up the group from your fiddle and it gives the same result of svg not staying to the top left. But as you said, the stroke uniform make things more complicated. If the inner group with uniform scale changes size, shouldn't its scale/ dimensions be updated? I checked with the 'scaling' event on the outer group, the inner group's scale and width/height remains the same.

**Comment by asturur** [comment]
Yes the inner objects do not get modified during a scaling event, only the container gets changed, that is why as today this functionality isn't supported. Doing the inverse calculation to reposition everything is complicated and we never implemented it.

**Comment by hamzawain7** [comment]
Js fiddle better elaborating the problem:
https://jsfiddle.net/hamzawain7/b45L8pk7/

The whole item seems to move on scaling which is bad for user experience. Will putting a bounty on this task escalate it?

![Scaling of uniform stroke svg in a group](https://user-images.githubusercontent.com/20171624/109484353-28a31880-7aa2-11eb-955a-cb778cee7e35.gif)

**Comment by hamzawain7** [comment]
Can you atleast open this and add it to bugs?

**Comment by asturur** [comment]
We already have a bug for this, is the other issue you found and linked the fiddle
