### ISSUE TITLE
Event Object:Selected is not firing on latest fabric.js version

### ISSUE THREAD

**Issue by Utsav-Sharma33** [fabricjs/fabric.js#6902]
Hi,
I am trying to bind object:selected event on canvas but it's not firing. I read that it's deprected in latest version. Why? What's the alternative for that. How can I add this event in latest version. I am working in Angular.

`this.canvas.on('object:selected', this.onObjectSelected.bind(this));`

**Comment by asturur** [comment]
http://fabricjs.com/v4-breaking-changes
