### ISSUE TITLE
Text curved - last version.

### ISSUE THREAD

**Issue by fran1990Web** [fabricjs/fabric.js#6904]
hi!
First. Thanks for fabric.js. Im so glad for using this library. Im learning fabricjs and react a lot :).
I have a question. Does anyone know how I could do this effect with fabricjs?

<img width="399" alt="Captura de pantalla 2021-03-03 a las 17 48 20" src="https://user-images.githubusercontent.com/66871629/109841633-87ef5d00-7c49-11eb-98bf-f8cd40706f8a.png">

I found this url: http://fabricjs.com/quadratic-curve and im trying to get this path and apply on the object fabric.textbox but it isnt works :(
I was researching and came across something like Fabric.curved Text but the performance was not good to implement.

Does Fabricjs have something like this to implement?

Thanks you so much

**Comment by fran1990Web** [comment]
https://github.com/fabricjs/fabric.js/pull/6543

**Comment by asturur** [comment]
You have to create a path with the shape you want, in this case a curve, and set it to the textbox object, but editing does not work properly yet.

**Comment by fran1990Web** [comment]
Thanks you @asturur.

**Comment by fran1990Web** [comment]
This issue can be closed

**Comment by wajipk** [comment]
> You have to create a path with the shape you want, in this case a curve, and set it to the textbox object, but editing does not work properly yet.

Can you please share without editing. I need it in some project. It will be testing phase for curve text too.

**Comment by melchiar** [comment]
@wajipk here's a simple example of how to achieve curved text 

https://jsfiddle.net/melchiar/7v8j92sw/
