### ISSUE TITLE
How to add custom attributes to Fabric objects and retain my new attributes when the objects are converted to JSON?

### ISSUE THREAD

**Issue by Ezr1al** [fabricjs/fabric.js#6917]
After converting the object to JSON, I lost some of my custom attributes, such as' id ', 'tabId', etc., and the JSON file kept only the standard attributes
![image](https://user-images.githubusercontent.com/36941749/110269030-c5633a00-7ffd-11eb-8306-e8a0f21217c0.png)

**Comment by melchiar** [comment]
See https://github.com/fabricjs/fabric.js/issues/3318

and in the docs here: http://fabricjs.com/docs/fabric.Canvas.html#toJSON

and here:
https://stackoverflow.com/a/54541356/7693185
https://stackoverflow.com/a/33417507/7693185
https://stackoverflow.com/a/54541422/7693185
