### ISSUE TITLE
OnMouseDown causing an error: Cannot read property 'e' of undefined

### ISSUE THREAD

**Issue by mSenad** [fabricjs/fabric.js#6923]
## Version
4.3.1

## Test Case
https://codesandbox.io/s/fabricjs-onmousedown-issue-ryhbp?file=/src/App.js

## Information about the environment
Nodejs or browser?
Browser

Which browsers?
Google Chrome, v88.0.4324.192

## Steps to reproduce
Hi guys, I'm trying to draw on the second canvas while drawing on the first one and I'm having an issue but I'm not sure what's causing it... Check out the fiddle in order to investigate and help me out with it. 

## Expected Behavior
Drawing on the first canvas element should be mirrored on the second one. When I switch from v4.3.1 to v2.7.0 everything works as expected.

## Actual Behavior
When I try to draw on the first canvas I get an error "Cannot read property 'e' of undefined".

**Comment by asturur** [comment]
the signature of brush methods changed between fabric 2 and fabric 4.
Please check the function on fabric 4 and add the missing arguments.
