### ISSUE TITLE
Moving a group results in incorrect SVG not fixed.

### ISSUE THREAD

**Issue by aharms24** [fabricjs/fabric.js#6932]
## Version
3.6.3

## Test Case
http://jsfiddle.net/WSeGV/3/

## Information about environment
Chrome
Firefox
Safari

## Steps to reproduce
See the fiddle, select group, move group, then click Do SVG. Group is not placed correctly.

**Comment by asturur** [comment]
Can you elaborate a bit better on the issue?

**Comment by aharms24** [comment]
It's pretty obvious in the fiddle. Select the three red squares all together, making sure they stay selected and click the "Do SVG" button. Notice how they are now positioned incorrectly in the bottom blue container. Now, deselect the squares and click the button. They will be positioned in the bottom blue container correctly, according to how they are in the top blue container.

**Comment by aharms24** [comment]
(to summarize), The problem is if objects are selected as a group when exporting as SVG, they are positioned incorrectly.

**Comment by asturur** [comment]
i used 30 minutes to investigate an issue opened on fabricJS 1.1.0.
Why in the issue you report 3.6.3 and in the fiddle you use 1.1.0?
