### ISSUE TITLE
Hit detection issue. Can't select object when using CSS body.zoom

### ISSUE THREAD

**Issue by JoeGarcia2** [fabricjs/fabric.js#6933]
**Version**
4..0

**Test Case**
https://jsfiddle.net/vdu3esf0/1/

**Steps to reproduce**
Try to drag element -- mouse cursor events are all off

**Details**
I am setting the body.zoom of my page is CSS to account for Retina displays.  
document.querySelector('body').style.zoom = '66.6667%';
This breaks the ability to select and scale objects correctly.

**Comment by melchiar** [comment]
Why not just keep retinaScaling enabled?

**Comment by asturur** [comment]
zoom seems like being a non standard css property.
If you apply external css transforms you will likely throw off the mouse position calculations. If your aim is supporting retina scaling use the enableRetinaScaling in rhe fabric Canvas and use fabric.devicePixelRatio to determine how much scaling you want.

**Comment by lk77** [comment]
I have the same issue, and it's because i'm using css zoom property to scale on 4k / 5k screens
