### ISSUE TITLE
Possible bug in Object.toDataURL()

### ISSUE THREAD

**Issue by GreenFootballs** [fabricjs/fabric.js#6934]
I ran into what looks like a serious bug in the Object.toDataURL() method. If the object has a shadow, the size of the resulting image is calculated incorrectly, sometimes by a huge amount. I created a Codepen to demonstrate the issue:

https://codepen.io/green_footballs/pen/ZEBwrww?editors=0011

Click the button on that page to toggle the shadow on and off. When the shadow is on, the data URL's image size is wildly wrong.

**Comment by GreenFootballs** [comment]
I dug into the code a bit and I suspect the problem is in fabric.utils.toCanvasElement(). It creates a canvas DOM element, and the code for calculating the width and height if there's a shadow looks wrong.

I found this code somewhere in stackoverflow a while back (maybe it was yours), and it calculates the object's bounding rect with a shadow much better.

`getObjBounds = obj => {
	let bounds = obj.getBoundingRect(),
		shadow = obj.shadow

	if (shadow && shadow !== null) {
		const
		blur = shadow.blur,
		mBlur = blur * Math.abs(obj.scaleX + obj.scaleY) / 4,
		signX = shadow.offsetX >= 0.0 ? 1.0 : -1.0,
		signY = shadow.offsetY >= 0.0 ? 1.0 : -1.0,
		mOffsetX = shadow.offsetX * Math.abs(obj.scaleX),
		mOffsetY = shadow.offsetY * Math.abs(obj.scaleY), 
		offsetX = mOffsetX + (signX * mBlur),
		offsetY = mOffsetY + (signY * mBlur)

		if (mOffsetX > mBlur) {
			bounds.width += offsetX
		} else if (mOffsetX  < -mBlur) {
			bounds.width -= offsetX
			bounds.left += offsetX
		} else {
			bounds.width += mBlur * 2
			bounds.left -= mBlur - mOffsetX
		}

		if (mOffsetY > mBlur) {
			bounds.height += offsetY
		} else if (mOffsetY < -mBlur) {
			bounds.height -= offsetY
			bounds.top += offsetY
		} else {
			bounds.height += mBlur * 2
			bounds.top -= mBlur - mOffsetY
		}
	}
	return bounds
}
`

**Comment by GreenFootballs** [comment]
Here's a forked Codepen that demonstrates a fix for this bug - it overrides the Object.prototype.toCanvasElement() method, and replaces the current shadow calculations with the code above. This one generates a dataURL that matches the real size of the object.

https://codepen.io/green_footballs/pen/wvoOpoZ?editors=0010

The new toCanvasElement() method looks like this:

```
fabric.Object.prototype.toCanvasElement = function(options = { }) {
    let utils = fabric.util, origParams = utils.saveObjectTransform(this),
        originalGroup = this.group,
        originalShadow = this.shadow, abs = Math.abs,
        multiplier = (options.multiplier || 1) * (options.enableRetinaScaling ? fabric.devicePixelRatio : 1);

    delete this.group;
    if (options.withoutTransform) {
        utils.resetObjectTransform(this);
    }
    if (options.withoutShadow) {
        this.shadow = null;
    }

    let el = fabric.util.createCanvasElement(),
        boundingRect = this.getBoundingRect(true, true),
        shadow = this.shadow;

    if (shadow) {
        const
        blur = shadow.blur,
        mBlur = blur * Math.abs(this.scaleX + this.scaleY) / 4,
        signX = shadow.offsetX >= 0.0 ? 1.0 : -1.0,
        signY = shadow.offsetY >= 0.0 ? 1.0 : -1.0,
        mOffsetX = shadow.offsetX * Math.abs(this.scaleX),
        mOffsetY = shadow.offsetY * Math.abs(this.scaleY), 
        offsetX = mOffsetX + (signX * mBlur) + mOffsetX,
        offsetY = mOffsetY + (signY * mBlur) + mOffsetY;

        if (mOffsetX > mBlur) {
            boundingRect.width += offsetX;
        } else if (mOffsetX < -mBlur) {
            boundingRect.width -= offsetX;
            boundingRect.left += offsetX;
        } else {
            boundingRect.width += mBlur * 2;
            boundingRect.left -= mBlur - mOffsetX;
        }

        if (mOffsetY > mBlur) {
            boundingRect.height += offsetY;
        } else if (mOffsetY < -mBlur) {
            boundingRect.height -= offsetY;
            boundingRect.top += offsetY;
        } else {
            boundingRect.height += mBlur * 2;
            boundingRect.top -= mBlur - mOffsetY;
        }
    }

    el.width = Math.ceil(boundingRect.width);
    el.height = Math.ceil(boundingRect.height);
    let canvas = new fabric.StaticCanvas(el, {
        enableRetinaScaling: false,
        renderOnAddRemove: false,
        skipOffscreen: false,
    });
    if (options.format === 'jpeg') {
        canvas.backgroundColor = '#fff';
    }
    this.setPositionByOrigin(new fabric.Point(canvas.width / 2, canvas.height / 2), 'center', 'center');

    let originalCanvas = this.canvas;
    canvas.add(this);
    let canvasEl = canvas.toCanvasElement(multiplier || 1, options);
    this.shadow = originalShadow;
    this.set('canvas', originalCanvas);
    if (originalGroup) {
        this.group = originalGroup;
    }
    this.set(origParams).setCoords();
    canvas._objects = [];
    canvas.dispose();
    canvas = null;
    return canvasEl;
}
```

**Comment by asturur** [comment]
seems broken indeed.
can you extract what you think is the fix and open a PR?

**Comment by GreenFootballs** [comment]
Can I open a PR without having write permission? I'm not sure how to do that.

**Comment by asturur** [comment]
you can fork and open a pr with a branch on your fork, then when you visit the pr page it will propose you to open a pr.

If you never opened a pr on a public repository, get ready for some challenge between code reviews and tests. Do things at your best i ll be happy to help

**Comment by GreenFootballs** [comment]
Thanks - pull request is opened.

**Comment by GreenFootballs** [comment]
Yes, there are several issues. The code style stuff is no problem, but I'm not sure how to address the other ones.

**Comment by GreenFootballs** [comment]
The Lint issues are all fixed, but some of the visual unit tests are apparently failing because they don't account for the shadow, either.

**Comment by GreenFootballs** [comment]
It's passing everything but the visual unit test issues, not sure how to proceed.

**Comment by asturur** [comment]
Sorry it took me a while to properly investigate everything. I took my time because at work i m full of things to do and i m trying to not code all the weekends too.

So when the code changes started to grow i got suspicious that the issue was somewhere else.
I found this in your fiddle:

```js
	if (rect.shadow) {
		rect.shadow = ''
	} else {
		rect.shadow = {
			"color": "#666666",
			"blur": "15",
			"offsetX": "15",
			"offsetY": "15",
		}
	}
```

While this is how you should add a shadow to an object:
```js
	if (rect.shadow) {
		rect.shadow = ''
	} else {
		rect.shadow = new fabric.Shadow({
			"color": "#666666",
			"blur": 15,
			"offsetX": 15,
			"offsetY": 15,
		})
	}
```

If added in this way there is no issue with image.
I think that with blur and offsetX being string, adding them becomes:
'15' + '15' = '1515' instead of 30 and here is where the image grow too much.

I'm sorry that i let you dig in the code before spotting this, but i think there isn't a actual bug to fix.

**Comment by GreenFootballs** [comment]
I didn't think about that because the shadow is created correctly even with string properties, but I looked into it and you are quite right - when the properties are ints there's no problem. Thanks for checking.

**Comment by asturur** [comment]
When i arrived here Shadow was already a class and i think the idea is because so it can host a toJSON method and a toSVG at least.
I will close this issue since we found the issue and there are no action items on my side.
I'm sorry we had to go through a full PR to find it out.
Thanks for trying to help
