### ISSUE TITLE
canvas.clear() does not remove "canvas" property of the canvas's objects

### ISSUE THREAD

**Issue by Basa0** [fabricjs/fabric.js#6936]
The "clear" function of a Canvas does not apply the same cleanup to its objects that the "remove" function does. I would expect that the objects no longer have their "canvas" property after clear, because they are no longer on that canvas.

Until I discovered that _canvas.clear_ does not remove this property, I expected that it was safe to verify if _object.canvas_ is defined to tell if that object is (still) on a canvas (rather than something like _canvas.getObjects().includes(object)_).

I would be open to attempting a fix and creating a PR, if you agree that this is a bug (unexpected behavior).

## Version
4.3.1

## Test Case
http://jsfiddle.net/mL3z25dp/

## Information about environment
browser (latest Chrome)

## Steps to reproduce
1. Add at least 1 object to a canvas
2. Call canvas.clear()
3. Verify the canvas property of one of the objects previously added

## Expected Behavior
1. object.canvas is not defined (same as if I were to call canvas.remove on each of its objects)

## Actual Behavior
1. object.canvas is defined - reference to the canvas that no longer contains that object

**Comment by asturur** [comment]
I would assume you are right, to be honest i have to think if there is a reason why this done in this way.

**Comment by Basa0** [comment]
Fixed in #6937
