### ISSUE TITLE
How to control the animation effect through the timeline？

### ISSUE THREAD

**Issue by wangyong991** [fabricjs/fabric.js#6938]
I want to add a timeline to the animation to control different animation effects at different points in time. Is there any way to achieve it?

**Comment by suncha-ng** [comment]
Hi,

Any response ?

**Comment by asturur** [comment]
This has nothing to do with fabricjs. This is a UI issue

**Comment by wangyong991** [comment]
I want to implement a function similar to this example, can someone provide some suggestions？ https://animejs.com/documentation/#TLcontrols

**Comment by asturur** [comment]
#6390 probably can support your request with more work
