### ISSUE TITLE
i can't understand where is other options in this document?

### ISSUE THREAD

**Issue by lvan-zhang** [fabricjs/fabric.js#6945]
example：
where is other options of defaultCursor？
![image](https://user-images.githubusercontent.com/17745287/111938620-5dd0e280-8b05-11eb-8873-50f4dcc36ff0.png)

http://fabricjs.com/docs/

**Comment by melchiar** [comment]
Cursor is a standard css property. You'll find a list of cursor types here

https://developer.mozilla.org/en-US/docs/Web/CSS/cursor
