### ISSUE TITLE
There is no event that signals end of 'touch:gesture'

### ISSUE THREAD

**Issue by jpfs1** [fabricjs/fabric.js#6950]
## Version
4.3.1

## Test Case
https://jsfiddle.net/s710zfoj

## Information about environment
latest Firefox, Chrome

## Steps to reproduce
1. Subscribe to 'touch:gesture' event of the canvas
2. Do a touch gesture, like pinch zoom
3. log event.self.state of the touch event

## Expected Behavior
For one gesture, the events of the event sequence should have:
1 time: event.self.state = 'start
n times: event.self.state = 'change'
1 time event.self.state = 'end'

## Actual Behavior
For one gesture, the events of the event sequence are:
1 time: event.self.state = 'start
n times: event.self.state = 'change'

I can't find any way to detect that a touch gesture had ended. I would expect there to be an event that indicates that, because this is the case for other touch listeners like 'touch:drag' ('down' - 'move' - ' up') and 'touch:longpress' ('start' - 'end')

**Comment by asturur** [comment]
Sorry for not getting back here.
No there isn't such support of touch events.
Our touch event support is very small and needs improvements.
