### ISSUE TITLE
Free Drawing Brush with decimate can remove the end of the line

### ISSUE THREAD

**Issue by BinaryMoon** [fabricjs/fabric.js#6951]
## Version
Latest

## Test Case
http://jsfiddle.net/BinaryMoon/z1kbepwq/

## Information about environment
This happens in all browsers.

## Steps to reproduce
Setup free drawing with a high decimate value, and then do some drawing. The line will draw fine until you release the pointer, and then the line will shorten. I assume this is because of the decimate feature.

## Expected Behavior
The line ends where I release the mouse.

## Actual Behavior
This lines gets shorter.

My suggestion is to stop decimate from deleting the last point on the line.

**Comment by asturur** [comment]
yes is probably because of that.

**Comment by asturur** [comment]
I mark this as beginner friendly so that anyone can jump in.

This function is inside the file pencil_brush.class.js

```diff
    /**
     * Decimate points array with the decimate value
     */
    decimatePoints: function(points, distance) {
      if (points.length <= 2) {
        return points;
      }
      var zoom = this.canvas.getZoom(), adjustedDistance = Math.pow(distance / zoom, 2),
          i, l = points.length - 1, lastPoint = points[0], newPoints = [lastPoint],
          cDistance;
+     // acting on the liimit of this loop can probably solve the issue,
+     // keeping in mind that a brush stroke an have also just 2 commands and points.lenght-2 can get to 0.
      for (i = 1; i < l; i++) {
        cDistance = Math.pow(lastPoint.x - points[i].x, 2) + Math.pow(lastPoint.y - points[i].y, 2);
        if (cDistance >= adjustedDistance) {
          lastPoint = points[i];
          newPoints.push(lastPoint);
        }
      }
      if (newPoints.length === 1) {
        newPoints.push(new fabric.Point(newPoints[0].x, newPoints[0].y));
      }
      return newPoints;
    },
```

**Comment by BinaryMoon** [comment]
Hi - I was going to attempt to fix this myself but I'm having trouble building the code locally.

If I run `npm run build:watch` then I get the error:

`cp: ../fabricjs.com/lib/fabric.js: No such file or directory`

And if I run `node build.js` I get the error:

`Command failed: uglifyjs  --compress --mangle --output fabric.min.js fabric.js`

I have downloaded all the things to my computer and run npm install. Is there something I have missed?

**Comment by BinaryMoon** [comment]
I found it worked if I ran `npm run build:fast` so that's what I did. :)

I ended up editing the file on github itself since my code editor is setup to use my coding standards on save and I didn't want to change all the coding standards for this one fix.

Hopefully I did it ok :)

**Comment by asturur** [comment]
Just FYI:
- take a folder of your choice and clone both fabricjs.com and fabric.js repo in the same parent folder. That will allow you to run the local website and keep it updated while you update the code
- you need to run npm install before building because of uglifyjs

**Comment by asturur** [comment]
this is solved

**Comment by BinaryMoon** [comment]
Thanks - it's really good to see this in the latest release
