### ISSUE TITLE
Selection draw bug

### ISSUE THREAD

**Issue by hamzawain7** [fabricjs/fabric.js#6953]
## Version
4.3.1

## Test Case
https://jsfiddle.net/hamzawain7/va1r79fc/

## Information about environment
Nodejs or browser?
Chrome

## Steps to reproduce
![Copy of A New Design](https://user-images.githubusercontent.com/20171624/112371091-08acf080-8d00-11eb-89d9-450d76a1ee69.gif)

## Expected Behavior
The selection opacity shouldn't change

## Actual Behavior
The selection opacity changes

## Some debug info
In canvas.setDimensions function hasLostContext is set to true which is used in renderAll of canvas to determine whether to renderTopLayer or not, but for such case contextTop is not cleared first causing redraw of selection box on existing and causing it to go full opaque

**Comment by melchiar** [comment]
Setting the canvas dimensions during initialization seems to resolve this issue, so it definitely seems to be a bug with changing the dimensions after initialization.

https://jsfiddle.net/melchiar/me07f4g6/

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/issues/6112

I think this is the same issue as #6112

please @hamzawain7 have a look, in case is different i will reopen it.
