### ISSUE TITLE
itext and textbox inputs crash chrome 89 when creating a new line

### ISSUE THREAD

**Issue by diydan** [fabricjs/fabric.js#6956]
## Version
4.3.1 (also repeatable in earlier versions)

## Test Case
https://jsfiddle.net/danielo/bw2rmynj/16/

Also repeatable in the following text demos:
http://fabricjs.com/super-sub-script (first text object)
http://fabricjs.com/test/misc/itext.html (last 2 text object examples)

## Information about environment
Affects Chrome 89

## Steps to reproduce
Create an interactive text object (or click an existing one)

Type "better" followed by enter key to create a new line then type "what"

## Expected Behavior
A new line is created with the inputted text

## Actual Behavior
Chrome crashes with error 11

**Comment by asturur** [comment]
can't replicate on macos chrome 89.0.4389.90

![image](https://user-images.githubusercontent.com/1194048/112479822-ad1d4a00-8d75-11eb-9d38-839a427d5189.png)

**Comment by asturur** [comment]
i can see it happen, not reliably 100%, on the jsfiddle.
Did you open a bug on chromium too?

**Comment by diydan** [comment]
Thanks for looking into this so quickly, your right it is in fact intermittent.  

I can occasionally reproduce here: http://fabricjs.com/super-sub-script   (also on mac os chrome 89.0.4389.90)

Haven't logged on Chromium but happy to do so if issue on their side.

Thanks

**Comment by brianjfinnerty** [comment]
https://user-images.githubusercontent.com/24569759/112480650-27e26700-8d6e-11eb-8ec1-bc6937660a5e.mov

**Comment by asturur** [comment]
Well it wasn't happening before, and you can't see much in the console.
As a javascript library i can crash spam console errors, but crash the whole window seems more the task for a browser fault.

**Comment by diydan** [comment]
Interestingly works on a fresh Chrome install, but if you log in to Chrome problem returns even without syncing. Seems some settings get applied namely "Minimum font size".

Setting "Minimum font size" above 0 seems to solve chrome://settings/fonts

So far I haven't been able to replicate with vanilla html canvas or other frameworks, nor with other Chromium based browsers (Edge/Brave/Opera). 

But I have been able to replicate in Canary and Beta Chrome builds.

**Comment by diydan** [comment]
FYI  issue confirmed with Chromium:

https://bugs.chromium.org/p/chromium/issues/detail?id=1193025

However not fixed until Chrome 91+

For us the following css seems to be a work around workaround:

::-webkit-scrollbar {
  min-height: 1px;
  display: none;
}

**Comment by asturur** [comment]
i also noticed that the text patterns do not work in chrome, i hope that is another chrome issue. Thanks for digging into

**Comment by diydan** [comment]
@asturur I haven't been able to replicate an issue with text patterns.

However Chromium have pushed a fix for the other issue above in "beta" Version 90.0.4430.61 (https://www.chromium.org/getting-involved/dev-channel) if you want to test it also fixes text patterns.

**Comment by asturur** [comment]
yes i ll download and test it
