### ISSUE TITLE
Text bounding box with emoji

### ISSUE THREAD

**Issue by GreenFootballs** [fabricjs/fabric.js#6959]
Yes, it's me again, and this time I'm fairly sure it's a real bug although I don't have a suggestion to fix it.

If a Textbox contains emojis, they overflow the top of the object's bounding rect:

![491](https://user-images.githubusercontent.com/3990430/112534245-126a3e80-8d68-11eb-85ed-6baa85b516b5.jpg)

And toDataURL() cuts off the image:

![492](https://user-images.githubusercontent.com/3990430/112534509-607f4200-8d68-11eb-98b6-dedb45de1faf.jpg)

Here's a Codepen to demonstrate:

https://codepen.io/green_footballs/pen/wvoOpoZ?editors=1010

**Comment by asturur** [comment]
what font are you using for emoji?

**Comment by asturur** [comment]
Let's categorize this bug as issue with emoji and text bounding box, because dataUrl issue is just a consequence of the bounding box issue

**Comment by asturur** [comment]
So for me works after the reload:
![image](https://user-images.githubusercontent.com/1194048/112536070-4d429580-8dad-11eb-8cd4-878f3b328d3d.png)

Hinting a bit at the fact that the emoji font isn't loaded initially and gets loaded by the browser/os at the moment of use.

**Comment by melchiar** [comment]
This is actually the same issue as https://github.com/fabricjs/fabric.js/issues/6432. It isn't specific to emojis since it affects any font character where the ascenders/descenders extend outside of the bounding box. 

As a workaround you can always manually adjust the height and top values when outputting your dataURL to allow for some extra space. 

Something like this
`emojis.toDataURL({height: 150, top: -10})`

**Comment by GreenFootballs** [comment]
The images are of the Mac OS built in emoji font. I'm not sure what you mean by:

> So for me works after the reload:
> 
> Hinting a bit at the fact that the emoji font isn't loaded initially and gets loaded by the browser/os at the moment of use.

That's interesting - what did you reload? When I refresh the page nothing changes. But somehow you managed to get the bounding box adjusted?

**Comment by asturur** [comment]
the second time i run the codepen everything was ok.
How much consistent is the issue for you?

**Comment by GreenFootballs** [comment]
I've tried reloading the codepen several times and it never fixes the issue. Maybe it's a Mac OS problem? I can't find any way to pre-load the built-in emoji font.

**Comment by asturur** [comment]
i m on macos and i m fine.
Tu load the custom emoji font the only way i know of is prime on the canvas sone emoji text. You can also just add a text like you did and with a setTimeout later clear the fabricjs cache for dimensions and do it again? is a weird issue anyway.

How doea firefox behave?

**Comment by GreenFootballs** [comment]
Very strange. Firefox acts the same way for me - the bounding box never adjusts, even after a setTimeout. How do I clear the cache for dimensions?

**Comment by asturur** [comment]
sorry the cache for dimensions keeps only the width of the fonts.
Just try to invalidate the object cache, add another char to it so it redraw.
