### ISSUE TITLE
build of 3.6.6 is 3.6.4

### ISSUE THREAD

**Issue by peernohell** [fabricjs/fabric.js#6961]
## Version
3.6.6

## Test Case
http://jsfiddle.net/t5sfbgao/
version used is from cloudflare cdn `https://cdnjs.cloudflare.com/ajax/libs/fabric.js/3.6.6/fabric.min.js`
## Information about environment
Any

## Steps to reproduce
move your mouse over the text and fabric version will show up

## Expected Behavior
to show the `3.6.6`

## Actual Behavior
show `3.6.4`

**Comment by asturur** [comment]
3.6.6 is a republished 3.6.4 because we had some issue with publish, no actual changes happened
