### ISSUE TITLE
Underline colour does not render correctly in a mixed colour textbox

### ISSUE THREAD

**Issue by LenkouAndrei** [fabricjs/fabric.js#6965]
## Version
4.3.1

##Environment
Electron 11.2.1 Windows10

## Steps to reproduce
1. Type several words into a text box
2. Use textbox.styles to assign a specific color to each word
3. Select all text and underline
4. Change font color of the last character to red

## Expected Behavior
The change affects last character only, its underline color matches the font color.

## Actual Behavior
The underline color for all text is changed to red.

**Comment by ickata** [comment]
Maybe issue is related to #6970 ?

**Comment by asturur** [comment]
duplicate of #6818
