### ISSUE TITLE
Custom controls won't work when object is flipped

### ISSUE THREAD

**Issue by hoomanaskari** [fabricjs/fabric.js#6979]
## Version
4.3.1

## Test Case
https://jsfiddle.net/human_a/knu9t3xc/

## Information about environment
Nodejs or browser? Browser
Which browsers? Any

## Steps to reproduce
Click on the "toggle editing polygon" button and try to move a point.

## Expected Behavior
When the object is flipped, this should work as normal, there is something missing in the actionHandler function or it's wrapper function, but I could not find out what.

=======
The only difference between this fiddle and the [official demo](http://fabricjs.com/custom-controls-polygon) of fabric.js is that the polygon has flipY set to true (same issue if flipX is set to true as well)

**Comment by asturur** [comment]
duplicate of #6886

**Comment by biggestdickus** [comment]
4/15/2024 : Here's an excellent work around that can be drawn, resized, moved, rotated, edited on a single or multiple polygons.
http://codepen.io/Rstewart/details/VwNBZwJ
