### ISSUE TITLE
FabricJS Mobile Support

### ISSUE THREAD

**Issue by GerwinFleurop** [fabricjs/fabric.js#6980]
Edit; Using Fabric 4.3.1
FabricJS doesn't seem to work well on Mobile.

Open for example:
http://fabricjs.com/kitchensink

On mobile,

If you try to type text it barely works - IE you need to tap numerous times for it to register (see JSFiddle at the bottom), if the tap does register the browser will zoom in on the text, and once zoomed in you can no longer zoom out, because the convas is 100% the width / height of the screen..
I've seen posts where people attempt:

var canvas = new fabric.Canvas("id", {
			allowTouchScrolling: true
		});
But this doesn't seem to resolve the issue where:
1. the user is zoomed, and tries to zoom out (as the pinch movement on the canvas doesn't zoom the user back out)
and 2. the user can no longer swipe out of the canvas to then zoom out, as swiping on the canvas doesn't do anything.

Are there solutions for this?

See: http://jsfiddle.net/trf1bcyg/

Also see - [StackOverflow](https://stackoverflow.com/questions/61642479/fabric-js-zooming-into-selected-text-on-mobile-similar-to-a-text-input-selectio)

The functionality of zooming in on the text is fine, aslong as you can zoom out - which right now, you sadly can't - is there a fix for this issue?

**Comment by GerwinFleurop** [comment]
Also see - https://stackoverflow.com/questions/61642479/fabric-js-zooming-into-selected-text-on-mobile-similar-to-a-text-input-selectio

The functionality of zooming in on the text is fine, aslong as you can zoom out - which right now, you sadly can't - is there a fix for this issue?

**Comment by sjscotti** [comment]
I had this trouble too, and I almost resigned myself to not allowing zooming on mobile.  
The workaround I came up when in the situation you mentioned was not to try to use touch navigation on the canvas, but to use it on a normally hidden `<div>`  that overlaps the canvas - where the `<div>` initially has `style='display: none; touch-action:manipulation;'`.  The `div` visibility is controlled using the hammer.js library.  (BTW, I fill the `<div>` with a crosshatch pattern so it is obvious when it is available for touch navigation.)

So I start by using hammer.js to listen for a long press or a tripletap on the fabric upper canvas.  When this was detected, the `display` on the `<div>` is changed from `none` to `block`, and I can pinch-zoom or pan when over the canvas using touch navigation on this `<div>`.   After I recover from the state mentioned in the issue, I use a hammer.js listener on the `<div>` to let you hide the `<div>` again.

My code isn't elegant, but here it is for reference...

```
//hammer.js touch controls for pan/zoom <div> to appear - using listener on upper canvas
var myUpperCanvasEl = document.querySelector('.upper-canvas');
var touchBackEl = document.getElementById("touchback");  // touchback is the id for the hidden <div>
var myUCanManager = new Hammer.Manager(myUpperCanvasEl);
var myUCanPress = new Hammer.Press({
	time: 1500   // detect 1.5 second long press 
  });
var myUCanTripleTap = new Hammer.Tap({event: 'tripletap', taps: 3 });
myUCanManager.add([myUCanPress, myUCanTripleTap]);
myUCanManager.on('press tripletap',function(e) {
	touchBackEl.style.display = "block";
  });

//hammer.js touch controls for pan/zoom <div> to disappear - using listener on touchback <div>
var myTBManager = new Hammer.Manager(touchBackEl);
var myTBPress = new Hammer.Press({
	time: 1500   // detect 1.5 second long press 
 });
var myTBTripleTap = new Hammer.Tap({event: 'tripletap', taps: 3 });
myTBManager.add([myTBPress, myTBTripleTap]);
myTBManager.on('press tripletap',function(e) {
	touchBackEl.style.display = "none";
 });
```

**Comment by GerwinFleurop** [comment]
I've been able to fix both issues, by enabling 'gestures' in the builder:

http://fabricjs.com/build/

@sjscotti

**Comment by sjscotti** [comment]
Great @GerwinFleurop !
I tried the gestures build for my drawing app, however my app includes custom pens that use drawing mode (i.e., `canvas.isDrawingMode = true;` ).  I found situations where I could be stranded over the canvas when in drawing mode, and I could not pan/zoom using the gestures build.  For example, using multiple fingers to pinch-zoom would just create zig-zag paths between my two fingers when I tried to pinch-zoom.   I couldn't figure out how to recover from these "stranded" situations other than my above suggested approach, but I am open to other suggestions.

**Comment by GerwinFleurop** [comment]
Yeah that might be an issue, I just tried it out and seem to run into the same issue, @sjscotti perhaps someone else could chime in here?

@asturur are you aware of the issue mentioned by @sjscotti and if so - is there a fix for said issue?

**Comment by asturur** [comment]
Guys if you are invested time and money in the touch support, we could sit talk decide a way to go, create fabric 5.0 with revamped pointer api support, breaking with the past if necessary. But some developers has to sit down and work on it.
Is not something i can do alone. I have a pen device ( ms surface ) and a touchpad and a mouse, i do not have tablets and i want to leave my personal phone outside of work stuff. I'll give you me free support, handholding you on the codebase, telling you how to split up prs in a way we can merge and test them, you just need to put someone to work on it  for the time that is required to get it to the finish line.
Mobile and touch support has multiple issue: the brushes, the text handling, gesture recognition, pencil and finger recognition, and other that interactions will bring up.

**Comment by asturur** [comment]
To answer @GerwinFleurop no, therisn't a fix since the brush works on mousedown or pointerstart or touchstart and i think the difference between a pen and a finger isn't recognized. When you start your gesture with the finger the events still go down to the brush code and draw. We should look into blocking the event once is recognized as a gesture.

**Comment by kopgzdevth** [comment]
> I had this trouble too, and I almost resigned myself to not allowing zooming on mobile. The workaround I came up when in the situation you mentioned was not to try to use touch navigation on the canvas, but to use it on a normally hidden `<div>` that overlaps the canvas - where the `<div>` initially has `style='display: none; touch-action:manipulation;'`. The `div` visibility is controlled using the hammer.js library. (BTW, I fill the `<div>` with a crosshatch pattern so it is obvious when it is available for touch navigation.)
> 
> So I start by using hammer.js to listen for a long press or a tripletap on the fabric upper canvas. When this was detected, the `display` on the `<div>` is changed from `none` to `block`, and I can pinch-zoom or pan when over the canvas using touch navigation on this `<div>`. After I recover from the state mentioned in the issue, I use a hammer.js listener on the `<div>` to let you hide the `<div>` again.
> 
> My code isn't elegant, but here it is for reference...
> 
> ```
> //hammer.js touch controls for pan/zoom <div> to appear - using listener on upper canvas
> var myUpperCanvasEl = document.querySelector('.upper-canvas');
> var touchBackEl = document.getElementById("touchback");  // touchback is the id for the hidden <div>
> var myUCanManager = new Hammer.Manager(myUpperCanvasEl);
> var myUCanPress = new Hammer.Press({
> 	time: 1500   // detect 1.5 second long press 
>   });
> var myUCanTripleTap = new Hammer.Tap({event: 'tripletap', taps: 3 });
> myUCanManager.add([myUCanPress, myUCanTripleTap]);
> myUCanManager.on('press tripletap',function(e) {
> 	touchBackEl.style.display = "block";
>   });
> 
> //hammer.js touch controls for pan/zoom <div> to disappear - using listener on touchback <div>
> var myTBManager = new Hammer.Manager(touchBackEl);
> var myTBPress = new Hammer.Press({
> 	time: 1500   // detect 1.5 second long press 
>  });
> var myTBTripleTap = new Hammer.Tap({event: 'tripletap', taps: 3 });
> myTBManager.add([myTBPress, myTBTripleTap]);
> myTBManager.on('press tripletap',function(e) {
> 	touchBackEl.style.display = "none";
>  });
> ```

i don't understand for tag div have example can understand pls

**Comment by brightertools** [comment]
> I've been able to fix both issues, by enabling 'gestures' in the builder:
> 
> http://fabricjs.com/build/
> 
> @sjscotti

Do the standard npm package include gestures? and also the previews eg 6.0.0-beta9 ?
