### ISSUE TITLE
[textbox] styles not cleared out when out of sync

### ISSUE THREAD

**Issue by lk77** [fabricjs/fabric.js#6982]
## Version
4.3.1

## Test Case
http://jsfiddle.net/lk77/sp0owcr2/10/

## Information about environment
On browser (chrome 89)

## Steps to reproduce

Unsure about reproduction, but by copy/pasting multiple times, i ended up with a broken textbox object with out of sync styles array

## Expected Behavior

styles is cleared out when out of sync, ie if length of styles array does not match length of text string

## Actual Behavior

Styles can be corrupted and changing color / font won't do anything anymore.

in the fsfiddle i change the color of the text every second with a random one, but to see that you must uncomment the `delete parsedJson.objects[0].styles` line

reproduction video  (http://jsfiddle.net/lk77/sp0owcr2/20/) :

nb : download the video if you have color issues, i have stripes on the left which are not part of the video

https://user-images.githubusercontent.com/9606882/113177541-ebbb7480-924d-11eb-80e4-adab92da2dff.mp4

thanks.

**Comment by asturur** [comment]
There are 256 style objects in the textbox, and as a developer you own cleaning them up.

Try to use Text.cleanStyle everytime you change a text property, this will allow the same value style to be removed.

**Comment by lk77** [comment]
Ok so i need to clear the style everytime i'm changing the text
