### ISSUE TITLE
Image Dimension Changes after loading from json

### ISSUE THREAD

**Issue by MoinDhattiwala-iFlair** [fabricjs/fabric.js#6983]
Hello,
  I have created canvas and converted in json format and save in db. When i load the data from json the dimension of images is changed. Can you please suggest what is the issue.\

**Comment by asturur** [comment]
hi @MoinDhattiwala-iFlair as asked in the issue, please create a reproducible test case.
Once the test case is available, i'll reopen the issue.
Do not open another issue for the same topic.

**Comment by MoinDhattiwala-iFlair** [comment]
Hello,
Thanks for replay.
I am not able to create a reproducible test case but with the help of this video you can get idea the video link is given below
https://we.tl/t-47UFyh7xeg

**Comment by asturur** [comment]
What does stop you from recreating the issue that you show in the video with a html + javascript example? Can you try to explain.
