### ISSUE TITLE
not work 'rotatingPointOffset' options

### ISSUE THREAD

**Issue by lja1018** [fabricjs/fabric.js#6986]
## Version
3.6.0

## Test Case
http://fabricjs.com/controls-customization

## Information about environment
Nodejs or browser?
* browser
Which browsers?
* chrome latest

## Steps to reproduce

![rotatingPointOffset](https://user-images.githubusercontent.com/28647773/113377452-47e9da00-93af-11eb-98cd-49c5cd534573.gif)

## Expected Behavior

work `rotatingPointOffset` options

## Actual Behavior

not work `rotatingPointOffset` options

**Comment by asturur** [comment]
fixed in the website. thanks for reporting this.
