### ISSUE TITLE
Shadows not redered on objects 

### ISSUE THREAD

**Issue by pramitsawant** [fabricjs/fabric.js#6987]
Here is my code.

https://codesandbox.io/s/node-js-forked-9019l

The JSON is loaded correctly on the browser.

but when I try to generate it in the backend. shadows are not rendered.

**Comment by asturur** [comment]
Please try to create a reproducible case either on jsfiddle or codepen.
I will reopen this issue when you can create one.
Do not open more issues for the same topic.

**Comment by pramitsawant** [comment]
Step to reproduce.

https://codesandbox.io/s/node-js-forked-9019l

> open the node sandbox

> open terminal and run the file `node index.js`

> it will create a file text1.png

you can see the shadow is not rendered
