### ISSUE TITLE
[textbox] Entering a long line of text in textbox makes the text look blurry

### ISSUE THREAD

**Issue by yuzfds** [fabricjs/fabric.js#6988]
## Version
4.3.1

## Test Case
enter 700 characters in Textbox

## Information about environment
Which browsers?
chrome 89

![1617353172(1)](https://user-images.githubusercontent.com/19660461/113400806-ff451780-93d4-11eb-8839-3c5f6c24ad86.png)

**Comment by asturur** [comment]
http://fabricjs.com/fabric-object-caching

Have a look at object caching.
Either increasize your max size and max area for the cache or disable it.
