### ISSUE TITLE
Problem with lineWidths textbox

### ISSUE THREAD

**Issue by luongtu996** [fabricjs/fabric.js#6991]
## Version
3.6.3, 4.3.1

## Test Case
It ok with v1.7.9: 
 https://jsfiddle.net/ejfuxzpc/1/
but not with newer version: 
 https://jsfiddle.net/zLayw4xb/

## Information about environment
Nodejs or browser?
Which browsers?

## Steps to reproduce

https://user-images.githubusercontent.com/26574116/113550120-c0a19e00-961c-11eb-958e-69bb630c8391.mov

## Expected Behavior
Show array of linewidths

## Actual Behavior
 linewidths array has only 1 valid value, the remaining values ​​are underfine

**Comment by luongtu996** [comment]
Can i get any help?

**Comment by asturur** [comment]
i m not able to replicate it at all.
Can we get a list of steps rather than a video?

**Comment by luongtu996** [comment]
You can try this link. 
[https://jsfiddle.net/luongtu996/quL69o0c/14/](url)
Step to reproduces
write until the text jumps to the bottom line. Then __lineWidths undefined

**Comment by asturur** [comment]
ok i see it now. Not sure why it happen. Did you check if the code that write __lineWidth is easily understandable?

**Comment by luongtu996** [comment]
i checked and it is easily understandable
