### ISSUE TITLE
How can clipPath make the nested elements rotate and zoom together with the outer nested box

### ISSUE THREAD

**Issue by pushuo** [fabricjs/fabric.js#6993]
## Version
4.3.1

## Test Case
https://codepen.io/pushuo/pen/bGgRmee

## Information about environment
browser

## Steps to reproduce
Manipulate the outer nesting box

## Expected Behavior
If you want to rotate and scale the nesting box, the pictures inside will also rotate and scale.
Similar to this question: https://github.com/fabricjs/fabric.js/issues/6585
The picture is used in the nesting box

## Actual Behavior
Not like this

### Please help me improve the code, or give me an example, thank you.

**Comment by ShaMan123** [comment]
`absolutePositioned:false` is what you're looking for
