### ISSUE TITLE
Draw shadow different with angle in node canvas

### ISSUE THREAD

**Issue by Saberjsd** [fabricjs/fabric.js#6995]
Hi, I may have the problem because of node-canvas when I use fabricjs
```js
// in browser CanvasRenderingContext2D
ctx.shadowOffsetX = 0;
ctx.shadowOffsetY = 20;
ctx.drawImage(img,100,100);
// ctx.getTransform() = [0,1,-1,0,0,0]
// this ctx is rotate 90deg, and the shadow is just on bottom.
```
* This is result image in browser:
![image](https://raw.githubusercontent.com/Saberjsd/assets/main/comments/canvas/shadow_in_browser.png)

```js
// in node canvas CanvasRenderingContext2D
ctx.shadowOffsetX = 0;
ctx.shadowOffsetY = 20;
ctx.drawImage(img,100,100);
// ctx.currentTransform = [0,1,-1,0,0,0]
// this ctx is rotate 90deg, but the shadow is just on left!!!
```
* This is result image in node-canvas:
![image](https://raw.githubusercontent.com/Saberjsd/assets/main/comments/canvas/shadow_in_node_canvas.png)

Why don't they draw the same?

**Comment by Saberjsd** [comment]
This is result image
* Browser:
![image](https://raw.githubusercontent.com/Saberjsd/assets/main/comments/canvas/shadow_in_browser.png)

* Node-Canvas:
![image](https://raw.githubusercontent.com/Saberjsd/assets/main/comments/canvas/shadow_in_node_canvas.png)

**Comment by asturur** [comment]
Why are you using ctx directly? how this is related with fabricJS?

**Comment by Saberjsd** [comment]
I used fabricJS in my work. I locate the problem, and I find the problem here.
I guess maybe you know how to solve this problem.
Now I fix this by trick. But It is not the final solution. 
```js
drawCacheOnCanvas: function (ctx) {
  if(fabric.isLikelyNode){
    let { shadowOffsetX, shadowOffsetY } = ctx;
    let needRadians = fabric.util.degreesToRadians(360 - (this.angle || 0) + (this.flipX && this.flipY ? 180 : 0))
    let newOffset = fabric.util.rotatePoint(
      new fabric.Point(shadowOffsetX, shadowOffsetY), 
      new fabric.Point(0,0), 
      needRadians
    )
    ctx.shadowOffsetX = newOffset.x
    ctx.shadowOffsetY = newOffset.y
  }
}
```

**Comment by asturur** [comment]
can you produce a simple js snippet where the issue appear? so that we can replicate it
