### ISSUE TITLE
Graphics drawn by Fabric. Js will disappear on the phone.

### ISSUE THREAD

**Issue by Ezr1al** [fabricjs/fabric.js#6996]
I drew a rectangle on the canvas, and it would look fine on the computer, but on the phone, when I moved the canvas, it disappeared.

in default:
![image](https://user-images.githubusercontent.com/36941749/113829269-e020fe00-97b7-11eb-8f1d-f56e7645ef00.png)

When I move the canvas around on my phone:
![image](https://user-images.githubusercontent.com/36941749/113829296-e911cf80-97b7-11eb-8a22-709e1623f61f.png)

**Comment by asturur** [comment]
@Ezr1al please follow the guidelines for opening an issue.
If the guidelines are unclear, please make question on the guidelines in this thread.

**Comment by Ezr1al** [comment]
Sorry, I'll follow the instructions
