### ISSUE TITLE
Problem with video fabirc.Image capture  

### ISSUE THREAD

**Issue by alexmelo23** [fabricjs/fabric.js#7008]
Hi,

I try to capture frame images from the video and display the frame like a list.
But when I click to capture a new image it is override existing frames to new images just now capture.

Does something know what the problem is?

https://codepen.io/alex-malin/pen/ZELvjdR

thanks.

**Comment by sandro** [comment]
Try this:

```js
    btn.addEventListener('click', () => {
      const objectLength = canvas.getObjects().length;
      console.log("objectLength",objectLength);
      const imgInstance = new fabric.Image(video);
      
      imgInstance.cloneAsImage(i => {
          i.set({width: 300, height: 300, left: 300 * objectLength})
          canvas.add(i)   
      })
    })
```

**Comment by asturur** [comment]
hi Alex, the video element is always the same element and gets repainted every time, you basically create a series of images that wrap the same video element, a series of images with the same pixel data.

You need to clone that video element, possibly in a quick way with a drawImage

```
    btn.addEventListener('click', () => {
          const objectLength = canvas.getObjects().length;
          const copyCanvas =   fabric.utils.copyCanvasElement(video);
          const imgInstance = new fabric.Image(copyCanvas , {width: 300, height: 300, left: 300 * objectLength});
          canvas.add(imgInstance);
      })
```
