### ISSUE TITLE
Object controls not working in Vue3

### ISSUE THREAD

**Issue by siaikin** [fabricjs/fabric.js#7012]
## Version
4.4.0

## Test Case
https://codesandbox.io/s/black-field-ft51t?file=/src/App.vue

## Information about environment
browser, Vue3.0

## Steps to reproduce
move mouse over  the object control

## Expected Behavior
the default cursor(this.defaultCursor) is always displayed no matter where you move it

through [this](https://github.com/fabricjs/fabric.js/issues/6680#issuecomment-724276188) tips, I found one possible reason.

[link](https://github.com/fabricjs/fabric.js/blob/2eabc92a3221dd628576b1bb029a5dc1156bdc06/src/mixins/object_interactivity.mixin.js#L15)
```javascript
if (!this.hasControls || this.group || (!this.canvas || this.canvas._activeObject !== this)) {
  return false;
}
```

in my test case, because Vue3 [reactivity system](https://v3.vuejs.org/guide/reactivity.html#how-vue-tracks-these-changes),  ​variable `_activeObject` is a `Proxy` object. 
let the value of the expression `this.canvas._activeObject !== this` is false.

**Comment by siaikin** [comment]
Judge whether the variable type is `Proxy` it is possible solution?

**Comment by asturur** [comment]
there is a way to wrap objects in a way that are not proxy. One guy came here with the same issue
https://github.com/vuejs/vue-next/issues/3236
You should have checked in the vue3 issues/docs too

**Comment by siaikin** [comment]
thanks.
if anyone sees this, [vue3 markraw](https://v3.cn.vuejs.org/api/basic-reactivity.html#markraw) is answer.

**Comment by lk77** [comment]
Thanks, same issue here after update to vue3

**Comment by jsshapiro** [comment]
So markRaw definitely works, but there are a number of reasons to want the object instances to be reactive. As one example: it makes it straightforward to build Vue components that use (e.g.) the Rect() object directly as their v-model.

The change to object_interactivity.mixin.js seems like a good idea. Using the supporting functions for proxies:

```
function unpackProxy(x) {
  if isRaw(x) {
    return x
  }
  return toRaw(x)
}

function proxeq(x, y) {
  return unpackProxy(x) == unpackProxy(y)
}
```

FabricJS may not want to bake in a dependency on isRaw and toRaw from Vue, but their implementation is straightforward.

**Comment by ShaMan123** [comment]
Since vue issues have been surfaced the last month I want to ask if anyone is willing to [create a vue template for fabric that works in codesandbox](https://github.com/fabricjs/fabric.js/tree/master/.codesandbox)

**Comment by ReonKovalchuk** [comment]
I recently encountered the same problem, but I noticed, that custom controls, which allow to transform polygon by it's points are working fine.
Maybe there's a way to make a custom control (I only need rotation) that would also work?
I tried to reassign controls with an object like this 
```
{
      rotate: new fabric.Control({
        x: 0,
        y: -0.5,
        offsetY: -25,
        cursorStyle: "crosshair",
        actionHandler: fabric.controlsUtils.rotationWithSnapping,
        cursorStyleHandler: fabric.controlsUtils.rotationStyleHandler,
        actionName: "rotate",
        render: renderIcon,
        cornerSize: 20,
        withConnection: false,
      }),
    };
```
but it still disappears on click.

**Comment by guda-art** [comment]
Is JavaScript's proxy API a destructive update to the language ?!

**Comment by siaikin** [comment]
> Is JavaScript's proxy API a destructive update to the language ? ! Is JavaScript's proxy API a destructive update to the language ?

It's hard to understand what you mean, have you met any problems?

**Comment by ReonKovalchuk** [comment]
> I recently encountered the same problem, but I noticed, that custom controls, which allow to transform polygon by it's points are working fine. Maybe there's a way to make a custom control (I only need rotation) that would also work? I tried to reassign controls with an object like this
> 
> ```
> {
>       rotate: new fabric.Control({
>         x: 0,
>         y: -0.5,
>         offsetY: -25,
>         cursorStyle: "crosshair",
>         actionHandler: fabric.controlsUtils.rotationWithSnapping,
>         cursorStyleHandler: fabric.controlsUtils.rotationStyleHandler,
>         actionName: "rotate",
>         render: renderIcon,
>         cornerSize: 20,
>         withConnection: false,
>       }),
>     };
> ```
> 
> but it still disappears on click.

by the way, I later noticed that controls work only if i create new object and assign it to the ref right away like this:
```
polygon.value = new fabric.Polygon(...)
```
but like this the controls wont work 

```
const polygon = new fabric.Polygon(...)
polygon.value = polygon
```

**Comment by asturur** [comment]
I have zero experience with the VUE3 framework and i do not know if some of the issue you encounter are because of the framework itself.

**Comment by pramod-praella** [comment]
Is there anyone have solution on the control selection not working with vue 3

**Comment by asturur** [comment]
It was something to do with the proxy objects in vue3, you have to pass the variables ar raw or something like that.
I really do not know vue

**Comment by natuan62** [comment]
I'm not sure but you can remove proxy by ```JSON.parse(JSON.stringify(value))``` @pramod-praella
toRaw seem not working

**Comment by asturur** [comment]
You can't do that if variables are instances. correct?
