### ISSUE TITLE
Missmatched rotationCursor property

### ISSUE THREAD

**Issue by Rad1calDreamer** [fabricjs/fabric.js#7013]
## Version
4.3.0
## Information about environment
any

## Steps to reproduce
Canvas has propery "rotationCursor " by docs http://fabricjs.com/docs/fabric.Canvas.html#rotationCursor , but this option has moved to Control class and in Canvas it usless

![image](https://user-images.githubusercontent.com/7055577/114520633-52775f80-9c4a-11eb-8c37-2bdf85874823.png)

**Comment by asturur** [comment]
Yes that property + doc should me removed.
Do you want to open a PR for that?

**Comment by asturur** [comment]
http://fabricjs.com/v4-breaking-changes
This page should be updated too, saying that the properties has been removed.

**Comment by Rad1calDreamer** [comment]
if i donty fogget, i'll do it
