### ISSUE TITLE
Discord for fabricjs

### ISSUE THREAD

**Issue by niels-van-den-broeck** [fabricjs/fabric.js#7018]
Hi there!

First of all, a great thanks for maintaining this library as you have.

As people in the google group raised their concern about no one answering questions, a discord group has been setup for people who need help with fabricjs. (Not by me)
As I've been working with the library for some time I wanted to give back in some way to try and help people in need.
It might be nice for you to be able to redirect people there if they need help with some implementation so I just thought I'd give you a heads up.

https://discord.gg/CJ6ZSX9Apy

EDIT: thought this was the easiest way to let you know. Feel free to close the issue immediately

**Comment by asturur** [comment]
i think i should close the google group  since i can pay attention to github and not much else. Github discussions do replace the google group in mu opinion. Not sure how to close it since i have no rights over it

**Comment by niels-van-den-broeck** [comment]
See it as a community effort to help people who have issues which are not related to issues on fabric

**Comment by asturur** [comment]
yes but is google group something that people in general use? i understand discord is a modern thing that people do use

**Comment by asturur** [comment]
yes but is google group something that people in general use? i understand discord is a modern thing that people do use
