### ISSUE TITLE
Image tag in svg not loading properly

### ISSUE THREAD

**Issue by hamzawain7** [fabricjs/fabric.js#7020]
## Version
4.4.0

## Test Case
http://jsfiddle.net/hamzawain7/rbu52zad/

## Information about environment
Nodejs or browser?
Chrome

## Steps to reproduce
Open js fiddle, only the circle tags in svg render and not the image
![example](https://user-images.githubusercontent.com/20171624/115218039-91605600-a11f-11eb-9edb-fc98723d7da8.png)

## Expected Behavior
Svg should render the same in fabricjs as it does in browser

**Comment by asturur** [comment]
Could be that the image can't load because of some crossOrigin issues.
Can you load a fabric Image using that URL inside the SVG?
this one

```
https://mdn.mozillademos.org/files/6457/mdn_logo_only_color.png
```
