### ISSUE TITLE
Built-in fabric filter overriding custom filter in WebGL when using Composed filter.

### ISSUE THREAD

**Issue by ygongdev** [fabricjs/fabric.js#7022]
## Version
3.6.0

## Test Case
TODO: Custom filter is confidential, will work on reproducing it with another texture example.

**Code**
```
fabric.Image.filters.Foo = fabric.util.createClass(
  fabric.Image.filters.Composed,
  {
  type: 'Foo',
  subFilters: [
    new fabric.Image.filters.CustomFilter({ ... }),
    new fabric.Image.filters.Saturation({ saturation: .8 }),
  ]
});
```
I have a feeling it has to do with textures, but `Fabric`'s internal got too  confusing for me to understand.

I use the following code in `sendUniformData` for my `CustomFilter` since I'm not sure where else to hook it up without overriding too many important internals.
```
  const texture = gl.createTexture();
  gl.activeTexture(gl.TEXTURE1);
  gl.bindTexture(gl.TEXTURE_2D, texture);
  const arr = new Uint8Array(256 * 4);

  ...

  gl.uniform1i(textureLocation, 1);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
  gl.texImage2D(
    gl.TEXTURE_2D,
    0,
    gl.RGBA,
    256,
    1,
    0,
    gl.RGBA,
    gl.UNSIGNED_BYTE,
    arr
  );
  ```

## Information about environment
Nodejs

## Steps to reproduce
1. Create a new `Composed` filter with a custom filter that deals with `texture` and a built-in fabric filter like `Saturation`.
2. Notice that the final output only shows `saturation` applied.
3. With WebGL disabled, filter works fine.

## Expected Behavior
Expecting both filters get applied in WebGL.

## Actual Behavior
Only `Saturation` filter was applied in WebGL. Works fine with WebGL disabled.

**Comment by ygongdev** [comment]
Closing because I decided to implement all the filter operations in a single filter for performance.
But I think the solution for this problem is to  override `applyToWebGL` and reset the texture
```
    applyToWebGL(options) {
      const gl = options.context;
      this.callSuper('applyToWebGL', options);
      gl.bindTexture(gl.TEXTURE_2D, null);
      gl.activeTexture(gl.TEXTURE0);
    },
```

**Comment by asturur** [comment]
Did not have time to look at this entirely, but i would like to know what kind of issue sis you encounter. Was it loading many textures?

**Comment by ygongdev** [comment]
No I think it was the opposite of that. When applying the texture from `Saturation`, the texture supplied from the `Custom` version was either ignored or overriden?

I think it has to be with proper texture management, like resetting and activating the correct texture when working with different filters.

**Comment by ygongdev** [comment]
Yeah can verify that the code snippet I shared solved the issue for me.

**Comment by asturur** [comment]
withou a full example of what you tried before is not easy to understand if there is a flaw in our filter logic.
