### ISSUE TITLE
Version 4.4.0 has a breaking API Change

### ISSUE THREAD

**Issue by alleyj** [fabricjs/fabric.js#7033]
## Version
4.4.0

## Test Case
I wasn't able to come up with a minimal test case easily. I'm using another library that directly uses fabric so my experience with fabric is minimal.

## Information about environment
Browser, Chrome 90

## Steps to reproduce
Upgrade to Fabric 4.4.0 from prior version. In my case from 4.2.0.

## Expected Behavior
There would be no breaking API changes.

## Actual Behavior
Calling realizeTransform on objects from an active selection crashes. In https://github.com/fabricjs/fabric.js/commit/a298d85f03f767d73d46cbe27b758da85958a67d the signature of realizeTransform in src/shapes/group.class.js was changed so that another parameter is required. Failure to pass the new parameter results in a crash.

**Comment by asturur** [comment]
yes an error. We need to add a default value for the missing argument

**Comment by janvanstiphout** [comment]
What should the default value be?

**Comment by asturur** [comment]
I think should be the identity matrix.

**Comment by janvanstiphout** [comment]
I think the parent object's matrix, since I use it for an element of a group, I use parentGroup.calcTransformMatrix() - it seems to work, but I doubt you can get the transformation matrix of the parent from the object itself, so I wouldn't know how you could implement it in the function.
