### ISSUE TITLE
Objects added via group don't fire 'added'

### ISSUE THREAD

**Issue by VanillinT** [fabricjs/fabric.js#7037]
## Version
4.4.0

## Test Case
https://jsfiddle.net/67y5jco8/1/

## Information about environment
Chrome 89.0.4389.128

## Steps to reproduce
Call addWithUpdate on a group with any fabric object as a parameter

## Expected Behavior
Objects fire 'added' when added to a group

## Actual Behavior
They don't fire 'added' when added to a group

**Comment by asturur** [comment]
We had a PR for this somewhere to fix it.

**Comment by ShaMan123** [comment]
+1

**Comment by ShaMan123** [comment]
If I am not mistaken this happens because group doesn't call `Collection#add` and instead pushes the object to `_objects`:
https://github.com/fabricjs/fabric.js/blob/master/src/shapes/group.class.js#L167

**Comment by ShaMan123** [comment]
#6619
