### ISSUE TITLE
loadFromJSON removed already added object in canvas

### ISSUE THREAD

**Issue by robinflyhigh** [fabricjs/fabric.js#704]
When you add few objects into canvas and then try and reload a JSON data then all previously added objects are removed. Below are the steps to reproduce it:

1.) Go to http://fabricjs.com/kitchensink/
2.) Add any 2 object or element
3.) Go to Execute Tab and clear all the content from it.
4.) Copy past the code from http://sharetext.org/VSOM
5.) This would add the first two element added to the canvas and replace it with the Thumbs Up object with text as '333 33'

When even a JSON data is loaded into canvas it tries to add it from index 0 which overwrites the existing object on the canvas

:)

**Comment by MULLAINATHAN** [comment]
Hi robinflyhigh,

How could you merge two JSON data ? I'm struggling on this. Please help me.

**Comment by robinflyhigh** [comment]
@MULLAINATHAN Why don't you load both the JSON separately two times?
