### ISSUE TITLE
Node JS Fabric does not apply bold or italic to text

### ISSUE THREAD

**Issue by idealstudija** [fabricjs/fabric.js#7040]
## Version
4.4.0

## Test Case
N/A

## Information about environment
Nodejs and browser
Chrome 89.0.4389.128

## Steps to reproduce
```
var fs = require('fs'),
    fabric = require('fabric').fabric,
    out = fs.createWriteStream(__dirname + '/helloworld2.png');

fabric.nodeCanvas.registerFont('/fonts/Anton.ttf', { family: 'Anton' });

var canvas = new fabric.StaticCanvas(null, { width: 400, height: 400 });

var text = new fabric.Text('Hello world!!!', {
  left: 100,
  top: 100,
  fontFamily: 'Anton',
  fontWeight: 'bold',
  fontStyle: 'italic',
  fill: '#ff0000'
});
canvas.add(text);

canvas.renderAll();

var stream = canvas.createPNGStream();
stream.on('data', function(chunk) {
  out.write(chunk);
});
```

## Expected Behavior
Node JS Fabric does not apply bold or italic to text, but the browser applies. How do I fix the problem without loading the font family? 

## Actual Behavior
Node JS
![helloworld2](https://user-images.githubusercontent.com/61463435/115898204-f68cb200-a465-11eb-9855-8d9ece31a397.png)

Browser
![Screenshot_7](https://user-images.githubusercontent.com/61463435/115898944-d7425480-a466-11eb-9fa7-ecb41a1c4003.png)

**Comment by asturur** [comment]
@idealstudija you need to have an italic font too.
Usually you have 4 fonts file for an object: regular, italic, bold, and any combination of style and weight together.
Chrome makes a fake italic skewing the font, but you will see that firefox does not.
Node-canvas does not either.
