### ISSUE TITLE
clipPath will reveal the background color of the border

### ISSUE THREAD

**Issue by pushuo** [fabricjs/fabric.js#7041]
## Version
4.3.1

## Test Case
https://codepen.io/pushuo/pen/ZEBqVOx

## Information about environment
Google Chrome

## Steps to reproduce
Please open the Test Case to view the problem

## Expected Behavior
Will not leak the background color of the nesting box

## Actual Behavior
The edge of the nesting box is shown in red, it shouldn’t be like this

**Comment by asturur** [comment]
There is no easy way to fix this.
The hearth shape has a border and antialiasing.
The aliasing is creating a clip with transparency and that makes the shape below appear a bit behind transparent pixels. We can't fix this because there is no way to remove the aliasing when drawing the clipPath
