### ISSUE TITLE
Path incorrect bbox values

### ISSUE THREAD

**Issue by ShaMan123** [fabricjs/fabric.js#7042]
## Version
Latest

## Test Case
https://codesandbox.io/s/fervent-sunset-5d2x8?file=/src/App.tsx

## Information about environment
Chrome

## Steps to reproduce /  Actual Behavior
```js
var path;
path.strokeWidth = 20 // manipulate this
var coords = path.calcCoords();
var badSize = {
  width: path.width,
  height: path.height
};
var size = {
  width: coords.br.x - coords.tl.x,
  height: coords.br.y - coords.tl.y
};
console.log(badSize.width === size.width, badSize.height === size.height);

// output false, false
```

## Expected Behavior
`width` and `height` should reflect the bounding box regardless of `strokeWidth` property

**Comment by ShaMan123** [comment]
#6727

**Comment by asturur** [comment]
Is unclear what are you trying to do in the codepen seems like you want to add a clipPath to the drawing, but you can't find out the correct size of the path.

Try to look for the patth bounding box using
http://fabricjs.com/docs/fabric.Object.html#getBoundingRect

**Comment by ShaMan123** [comment]
Sorry for not being clear enough.
If filed the bug because `width` and `height` don't reflect the path's actuals bounding box.
**For the EXAMPLE:**
Once a path is created and added to the canvas a rect clip path of the size of the path will be added to the path.
The desired result would be that the clip path will not clip any part of the path because it's size is the same as the path. That means the bounding box was calculated correctly.
Click the different buttons to see how results vary between calculations showing that `width | height` properties are incorrect for the path.
I have patched `fabric.Path` to fix this. You can try it by clicking `Patch Path class`.

**Comment by ShaMan123** [comment]
> Is unclear what are you trying to do in the codepen seems like you want to add a clipPath to the drawing, but you can't find out the correct size of the path.
> 
> Try to look for the patth bounding box using
> http://fabricjs.com/docs/fabric.Object.html#getBoundingRect

This works. But again the width and the height properties of the path are different from the result of `getBoundingRect`

**Comment by ShaMan123** [comment]
> > Is unclear what are you trying to do in the codepen seems like you want to add a clipPath to the drawing, but you can't find out the correct size of the path.
> > Try to look for the patth bounding box using
> > http://fabricjs.com/docs/fabric.Object.html#getBoundingRect
> 
> This works, thanks. However, the width and the height properties of the path are different from the result of `getBoundingRect`


I've updated the example

**Comment by ShaMan123** [comment]
`getBoundingRect` produces a bug when used on clipped object, look at the image at the bottom right corner
source: https://codesandbox.io/s/peaceful-kalam-6zjx7
![image](https://user-images.githubusercontent.com/34343793/116532772-4d244100-a8e9-11eb-93cf-1221deecde61.png)

**Comment by ShaMan123** [comment]
Then try clicking `from JSON` and you'll see that if you erase the scaled image it doesn't produce the error

**Comment by ShaMan123** [comment]
I have changed the code I am using to run with `obj._getNonTransformedDimensions();`
But still this is what I get. It seems to be occurring only in paths.
See how the bounding rect that is used for the eraser mismatches the actual size of the path (marked in yellow)

![tst](https://user-images.githubusercontent.com/34343793/116840973-675b6900-abe0-11eb-81f1-e2d3ed80643e.png)

To reproduce:
1. https://codesandbox.io/s/focused-christian-7s5gx?file=/src/App.tsx
2. click `from JSON`
3. click `to SVG` `to Image`
