### ISSUE TITLE
Objects disappear when canvas width and height is more than 4096 and reappear when width is 16385

### ISSUE THREAD

**Issue by mdjoe97** [fabricjs/fabric.js#7047]
## Version
4.4.0

## Test Case
http://jsfiddle.net/y8ap4o3v/13/

set the width to 4097 and object will disappear
set the width to 16385 and object will appear
set the width to 4096 and object will appear

## Information about environment
chrome version `90.0.4430.93`

Firefox version `78.10.0esr`

## Steps to reproduce
I'm using fabricJs to add images to the canvas, And i'm changing the canvas width and height with `canvas.setWidth(width,{backstoreOnly:true})` and `canvas.setHeight(height,{backstoreOnly:true})`,
 but when canvas width or height are more than `4096px`, all object disappears in chrome but when I reach `16385px` or above the objects reappear, I tested it in Firefox everything works fine I can add width up to `20000px` or more, but in chrome I can't add more than `4096px`

## Expected Behavior
Objects should still show

## Actual Behavior
Objects disappear in chrome when width or height exceeds 4096 and appears when width is 16385 or above

**Comment by asturur** [comment]
Probably hardware limit issues.
On my laptop firefox works ok up to 4097, 16384 or 16385 won't work.
on my brave ( chromium derivate ) everythings works ok.
I do not think there is a bug here, canvas has different implementation on browsers. Great you could reach 20.000 somewhere. With what hardware specs?

**Comment by mdjoe97** [comment]
@asturur Thank you for your reply, I can only reach 200000 or higher on firefox only.

 my hardware specs are, RAM: 8gb, CPU: Intel(R) Core(TM) i5-8250U @ 1.60GHz.

so I can't do anything about it right?

**Comment by asturur** [comment]
in my opinion you should get consisten canvas sizes. Do you have an hidpi screen? is that a notebook?
