### ISSUE TITLE
`canvas.setOverlayImage` accepts shape as the first param.

### ISSUE THREAD

**Issue by taoning2014** [fabricjs/fabric.js#7050]
## Version
4.3.1

## Test Case

http://jsfiddle.net/k9hzfLqx/

## Information about environment
Nodejs or browser? Browser
Which browsers? Chrome

## Steps to reproduce
Please see the jsfiddle link above.
1. Create a shape object and an image object.
2. Add the shape object as the overlay by calling `canvas.setOverlayImage`.

## Expected Behavior
The `setOverlayImage` method should not work if the passed-in object is not an image.

## Actual Behavior
Could we can a new method on canvas to set the shapes as the overlay? This will be useful when we try to draw the cropzone by using `fabric.Path`, and we want the cropzone always set on top of the image. 

While the current method `canvas.setOverlayImage` works when a shape instead of an image is passed in. The method names look a bit confusing (also, in TypeScripe, it will display a lint error if the passed-in param is not a type of fabric.Image).

Before call `setOverlayImage`: 

https://user-images.githubusercontent.com/8691648/117062857-f99f6200-acf1-11eb-8fb2-8bdd67c682cc.mov

After call `setOverlayImage`:

https://user-images.githubusercontent.com/8691648/117062868-fc01bc00-acf1-11eb-9e3d-2770920162d1.mov

**Comment by asturur** [comment]
canvas.overlayImage can be any fabric drawable object that is meant to be on the canvas.
Is just bad named and to do not break many app we did not renamed it.
