### ISSUE TITLE
Canvas background will occasionally not appear on page reload - Safari iOS

### ISSUE THREAD

**Issue by iyerusad** [fabricjs/fabric.js#7054]
## Version
^4.3.1

## Test Case
http://jsfiddle.net/g6tkn2cq/1/ <- Unable to reproduce via JSfiddle interface, tried on iPad and no luck.

## Information about environment
Nodejs or browser? Browser
Which browsers? Safari on iPad OS

This one was a weird one to chase down. Possible race condition? Was unable to repro in Chrome 90+ on desktop, only fairly consistently on Safari iPad.

## Steps to reproduce

1. Set canvas background using `fabric.Image.fromURL`.
2. Within callback of `fabric.Image.fromURL`  execute `setBackgroundImage()`
3. Load the page. Reload the page 10 times. Observe 20-60% of time canvas background not appear.
    - Clicking on the canvas background would activate/show the canvas background.
      - Injecting `renderAll()` (in various places) did not fix the issue. 

This code appears to be problematic:
```js
fabric.Image.fromURL(this.thisHref + "static/myimg.jpg", img => {
  this.canvasObj.setBackgroundImage(
    img,
    this.canvasObj.renderAll.bind(this.canvasObj),
    { //probably irrelevant but included)
      top: 10,
      left: 10
    }
  );
  this.canvasObj.renderAll();
});
```
I read that `Image.fromURL` and `setBackgroundImage()` are async commands, not sure if having the second async command in the callback of first command is causing this behavior. What throws me off is that unable to repro anywhere except Safari on iPad, and even then on after spamming page reloads.

## Expected Behavior
Canvas background shows up every time.

## Actual Behavior
Canvas background would only render 80->40% of the time. Notably, objects add on top of the background (e.g. from restoring state via localstorage) would show up, just not the background. Waiting for a period of time did not have the canvas background reappear.
Clicking/tapping the canvas would activate the background.
Reloading the page would sometimes render the background, sometimes not.

## Workaround (attempt)
Switching the image to b64 - **EDIT:** Doesn't work consistently either.
```js
this.canvasObj.setBackgroundImage(
  myImg, //var holding b64 string value
  this.canvasObj.renderAll.bind(this.canvasObj),
  { //probably irrelevant but included)
    top: 10,
    left: 10
  }
);
```

I know this isn't a perfect bug report (particularly lack of good repro via a JSfiddle) but thought would put it here to document this odd behavior on specific browser.

**Comment by asturur** [comment]
i wound go for something simpler like
```js
fabric.Image.fromURL(this.thisHref + "static/myimg.jpg", img => {
  img.top = 10;
  img.left = 10;
  this.canvasObj.backgroundImage = img;
  this.canvasObj.renderAll();
});
```

This shouldn't fail ever.

**Comment by iyerusad** [comment]
> ```js
> fabric.Image.fromURL(this.thisHref + "static/myimg.jpg", img => {
>   img.top = 10;
>   img.left = 10;
>   this.canvasObj.backgroundImage = img;
>   this.canvasObj.renderAll();
> });
> ```

^^ Hmm that does seem to work consistent. My b64 attempt actually ended up failing as well.

Any deeper insight on why? From what I can gather, attempting to use `setBackgroundImage()` is problematic here, but it setting the canvas object's `backgroundImage` works consistently.

**Comment by asturur** [comment]
Hey i m sorry if i never replied.
I m not sure why the b64 attempt wasn't working reliably.
I have lot of issues/emails to answer, and i won't be able to try to find out why on the ipad does not work, i'm sorry, i have to prioritize what i do.

I will probably deprecate all those  async loading methods and leave to developers how to load resources like images, so that we do not have to maintain different way to do things.
