### ISSUE TITLE
fabric.util.rotatePoint mutates partially the given point but returns a new one

### ISSUE THREAD

**Issue by polco-gelato** [fabricjs/fabric.js#7055]
Hello!
The function `fabric.util.rotatePoint` is mutating the given point (first argument) by calling `point.subtractEquals(origin)`, but then returns a new point. So you end up having a 'useless' previous point and a new one to use.
I think it should either mutate the given point the whole way, or not at all. I'd be happy to do the PR for that change !

PS: thank you for maintaining and improving such an awesome library.

**Comment by asturur** [comment]
yes this seems a bug if true. Can you please show it in a fiddle?

**Comment by polco-gelato** [comment]
sorry for taking a long time to create the fiddle: https://jsfiddle.net/7fypgw6k/

**Comment by polco-gelato** [comment]
the bug is still alive and well :)

**Comment by asturur** [comment]
ok this is bad and needs to be fixed.

**Comment by polco** [comment]
Thank you!

**Comment by polco-gelato** [comment]
Thank you!
