### ISSUE TITLE
clipPath picture misaligned when zoomed

### ISSUE THREAD

**Issue by pushuo** [fabricjs/fabric.js#7060]
## Version
4.3.1

## Test Case
https://codepen.io/pushuo/pen/VwpewqE

## Information about environment
browser

## Steps to reproduce
When dragging the large layer, the small image will change

## Expected Behavior
When dragging a large layer, the small image will not change and will not flicker

## Actual Behavior
When dragging large layers. Problems such as flickering of the small picture

**Comment by pushuo** [comment]
![Uploading Kapture 2021-05-12 at 12.40.54.gif…]()

**Comment by pushuo** [comment]
![Kapture 2021-05-12 at 12 40 54](https://user-images.githubusercontent.com/21018378/117919377-75fff980-b31f-11eb-85aa-8147266a1404.gif)

**Comment by pushuo** [comment]
@asturur

**Comment by asturur** [comment]
hi @pusho, i m sorry there are so many questions i m behind.
