### ISSUE TITLE
fabric.Image is not render video without width and height in the <video>

### ISSUE THREAD

**Issue by dDenysS** [fabricjs/fabric.js#7063]
## Version
4.4.0

## Test Case
https://codesandbox.io/s/github-fabric-js-issue-with-video-element-forked-q4xw9?file=/index.html

## Information about environment
Browser
Chrome 90.0.4430.212

## Expected Behavior
Video will be render in the fabric.Image element.
## Actual Behavior
The fabric.Image element is empty.

Case1
If width and height attributes are added to the `<video>` then the video will be displayed

Case2
If `<video>` has a width attribute 200 (px), then the video will be render 200px in fabric.Image , but fabric.Image has  `width: 960`

**Comment by i-prikot** [comment]
Element with display none parameter cannot be got dimensions via Element.getBoundingClientRect(). Try to improve your code to compute the dimensions.

```
fabric.Image.prototype.initialize = (function (originalFn) {
  return function (element, options) {
    const { width, height } = options || {};
    const _display = element.style.display;
    
    element.style.display = "block";
    
    const clientRect = element.getBoundingClientRect();
    
    element.style.display = _display;

    if (width) {
      element.setAttribute("width", width);
    } else {
      element.setAttribute("width", clientRect.width);
    }

    if (height) {
      element.setAttribute("height", height);
    } else {
      element.setAttribute("height", clientRect.height);
    }

    originalFn.call(this, element, options);    
    return this;
  };
})(fabric.Image.prototype.initialize);
```

**Comment by dDenysS** [comment]
> Element with display none parameter cannot be got dimensions via Element.getBoundingClientRect(). Try to improve your code to compute the dimensions.
> 
> ```
> fabric.Image.prototype.initialize = (function (originalFn) {
>   return function (element, options) {
>     const { width, height } = options || {};
>     const _display = element.style.display;
>     
>     element.style.display = "block";
>     
>     const clientRect = element.getBoundingClientRect();
>     
>     element.style.display = _display;
> 
>     if (width) {
>       element.setAttribute("width", width);
>     } else {
>       element.setAttribute("width", clientRect.width);
>     }
> 
>     if (height) {
>       element.setAttribute("height", height);
>     } else {
>       element.setAttribute("height", clientRect.height);
>     }
> 
>     originalFn.call(this, element, options);    
>     return this;
>   };
> })(fabric.Image.prototype.initialize);
> ```

Hi. The solution is not very good, because I want to render the video to canvas and hide the video

**Comment by i-prikot** [comment]
> > Element with display none parameter cannot be got dimensions via Element.getBoundingClientRect(). Try to improve your code to compute the dimensions.
> > ```
> > fabric.Image.prototype.initialize = (function (originalFn) {
> >   return function (element, options) {
> >     const { width, height } = options || {};
> >     const _display = element.style.display;
> >     
> >     element.style.display = "block";
> >     
> >     const clientRect = element.getBoundingClientRect();
> >     
> >     element.style.display = _display;
> > 
> >     if (width) {
> >       element.setAttribute("width", width);
> >     } else {
> >       element.setAttribute("width", clientRect.width);
> >     }
> > 
> >     if (height) {
> >       element.setAttribute("height", height);
> >     } else {
> >       element.setAttribute("height", clientRect.height);
> >     }
> > 
> >     originalFn.call(this, element, options);    
> >     return this;
> >   };
> > })(fabric.Image.prototype.initialize);
> > ```
> 
> Thk. Hi. The solution is not very good, because I want to render the video to canvas and hide the video

Video remains hidden.

```
element.style.display = "block";
const clientRect = element.getBoundingClientRect();   
element.style.display = _display;
```


https://codesandbox.io/s/github-fabric-js-issue-with-video-element-forked-vi4mw?file=/src/index.js

**Comment by dDenysS** [comment]
> > > Element with display none parameter cannot be got dimensions via Element.getBoundingClientRect(). Try to improve your code to compute the dimensions.
> > > ```
> > > fabric.Image.prototype.initialize = (function (originalFn) {
> > >   return function (element, options) {
> > >     const { width, height } = options || {};
> > >     const _display = element.style.display;
> > >     
> > >     element.style.display = "block";
> > >     
> > >     const clientRect = element.getBoundingClientRect();
> > >     
> > >     element.style.display = _display;
> > > 
> > >     if (width) {
> > >       element.setAttribute("width", width);
> > >     } else {
> > >       element.setAttribute("width", clientRect.width);
> > >     }
> > > 
> > >     if (height) {
> > >       element.setAttribute("height", height);
> > >     } else {
> > >       element.setAttribute("height", clientRect.height);
> > >     }
> > > 
> > >     originalFn.call(this, element, options);    
> > >     return this;
> > >   };
> > > })(fabric.Image.prototype.initialize);
> > > ```
> > 
> > 
> > Thk. Hi. The solution is not very good, because I want to render the video to canvas and hide the video
> 
> Video remains hidden.
> 
> We store the state of the property `_display = element.style.display;`
> 
> ```
> const _display = element.style.display;
> element.style.display = "block";
> const clientRect = element.getBoundingClientRect();   
> element.style.display = _display;
> ```
> 
> https://codesandbox.io/s/github-fabric-js-issue-with-video-element-forked-vi4mw?file=/src/index.js

Thk. It is good solution, but I think it must be added to the library

**Comment by zhenghy123** [comment]
I has the problem too, if you not set the video width and height , the canvas.renderAll() can not get correct result 
I try to find something in the source and get this:
` /**
     * Returns original size of an image
     * @return {Object} Object with "width" and "height" properties
     */
    getOriginalSize: function() {
      var element = this.getElement();
      return {
        width: element.naturalWidth || element.width,
        height: element.naturalHeight || element.height
      };
    },`

the are so many code like this too, it not consider compatibility with video
like this:
` /**
     * Returns original size of an image
     * @return {Object} Object with "width" and "height" properties
     */
    getOriginalSize: function() {
      var element = this.getElement();
      return {
        width: element.naturalWidth || element.width || element.videoWidth,
        height: element.naturalHeight || element.height || element.videoHeight
      };
    },`

**Comment by zhenghy123** [comment]
from the source ,I find this method :
```
  /**
     * Constructor
     * Image can be initialized with any canvas drawable or a string.
     * The string should be a url and will be loaded as an image.
     * Canvas and Image element work out of the box, while videos require extra code to work.
     * Please check video element events for seeking.
     * @param {HTMLImageElement | HTMLCanvasElement | HTMLVideoElement | String} element Image element
     * @param {Object} [options] Options object
     * @param {function} [callback] callback function to call after eventual filters applied.
     * @return {fabric.Image} thisArg
     */
    initialize: function(element, options) {
      options || (options = { });
      this.filters = [];
      this.cacheKey = 'texture' + fabric.Object.__uid++;
      this.callSuper('initialize', options);
      this._initElement(element, options);
    },
```
`Image class` support {HTMLImageElement | HTMLCanvasElement | HTMLVideoElement | String} element 
it should be adapter for HTMLVideoElement width videoWidth and videoHeight
thanks:

**Comment by asturur** [comment]
we should remove the videoElement support from the doc.
There are different things that go against video in the current code:
- textures and filter
- caching
- width/height

**Comment by zhenghy123** [comment]
> 

you can add a new API to support videoElement. 
if you can add some transitions for video it is much better
