### ISSUE TITLE
When generating multiple line using nested array, drawing line error

### ISSUE THREAD

**Issue by beblank** [fabricjs/fabric.js#7064]
## Version
4.3.1

## Test Case
https://jsfiddle.net/beblank/7sj2at8g/31/

## Information about environment
Node 12.17.0
Chrome Version 90.0.4430.212

## Steps to reproduce
Create nested array which add points (x,y) then map it to draw the line
The points is in the right position but the line error 

## Expected Behavior
Line should be on the points (start and end)

## Actual Behavior
Line not on the points (start and end)

**Comment by i-prikot** [comment]
Hi.

You have a space between coordinates.

![image](https://user-images.githubusercontent.com/21138391/118764399-a4dc1980-b8a3-11eb-8089-7f0a35667ad5.png)

If the coordinates take integer coordinates, then apply `parseInt()`. You can also remove spaces.

```
const draw = () => {
  allData.map(data => {
  	data.map( point => {
    	const [x, y] = point.split(',');      
    	drawLine(parseInt(x), parseInt(y))
    })
  })
}
```

**Comment by beblank** [comment]
thanks for this ill close this issue
the solution is the parse int
