### ISSUE TITLE
Integrating rough.js for hand-drawn appearance

### ISSUE THREAD

**Issue by GreenFootballs** [fabricjs/fabric.js#7069]
Has anyone ever adapted the [rough.js](https://roughjs.com/) library to work with fabric, maybe as a set of custom objects? If not, is there anything that would prevent this from working? I may want to give it a try.

**Comment by asturur** [comment]
No, but has always been in my list of todos as an example.
I think one way would be to override the basic fabric.Circle and in the circle render method, where we do ctx.arc to be clear, you would do something like:

```
const rc = rough.canvas(ctx.canvas);
rc.circle(0, 0, radius * 2);
```

unless rough reset the canvas transform for some reason.

**Comment by GreenFootballs** [comment]
I just set up a quick Codepen to test it and it seems to work fine!

https://codepen.io/green_footballs/pen/ZEeLvGP?editors=1011

**Comment by GreenFootballs** [comment]
One problem immediately comes up, though - when I add a normal fabric Rectangle in addition to the rough circle, then click on the rectangle to select it, the circle disappears. But if I set its objectCaching to false, it doesn't disappear, but then it redraws the circle as I drag the rectangle - and since it's a random drawing it looks well, strange.

**Comment by i-prikot** [comment]
Hi.

I hope this helps )

```
const _render = circle._render,
roughRender = function(ctx) {
	if (!this.rough) {
		_render.call(this, ctx)
		return
	}
	
	const rc = rough.canvas(ctx.canvas);
	
	if (!this._circle) {
		this._circle = rc.circle(0, 0, this.radius * 2, {
			strokeWidth: this.strokeWidth,
			fill: this.fill,
			fillWeight: this.fillWeight,
			fillStyle: this.fillStyle,
			hachureGap: this.hachureGap,
			roughness: 2,
		})
	} else {		
		rc.draw(this._circle);
	}
}
circle._render = roughRender
```

fabric.Circle set property objectCaching = false,

https://codepen.io/i-prikot/pen/BaWpbKj

**Comment by GreenFootballs** [comment]
That's great, thanks! You're saving the rough circle as a property of the object, and simply redrawing it if it already exists, instead of creating a new one.

**Comment by GreenFootballs** [comment]
I may have hit a show-stopper, because fabric's toDataURL() methods don't like these rough objects at all. [Here's the latest Codepen showing the issue](https://codepen.io/green_footballs/pen/ZEeLvGP?editors=1011) - you can toggle between the native canvas toDataURL() method (which works) and the fabric method (which fails in odd ways). Apparently there's something different about the rendering process for these methods.

**Comment by i-prikot** [comment]
Hi.

I would do it like this.

@GreenFootballs https://codepen.io/i-prikot/pen/QWpvNKo

**Comment by GreenFootballs** [comment]
Brilliant, thanks. Creating custom objects was actually the next thing I was going to try. Is there a reason why you put the createClass() code inside an IIFE? It seems to work fine without that.

**Comment by i-prikot** [comment]
@GreenFootballs, there is no reason. You can use without IIFE. It worked reflexively )

**Comment by GreenFootballs** [comment]
Just for completeness, I wanted to mention that the custom objects also need to have toObject() and fromObject() methods, to work correctly with serialization.

[The updated Codepen](https://codepen.io/green_footballs/pen/ZEeLvGP?editors=0011) shows how to do this.

**Comment by asturur** [comment]
this seems nice, would you like to transform your codepen in a fabricjs demo/tutorial with a bit of text explanation? That would be a great way to help the project, giving people examples from which they can learn

**Comment by GreenFootballs** [comment]
Sure, I could do that. Where would it go, and what's the procedure?
