### ISSUE TITLE
Lines are moved after line.set(line.toJSON())

### ISSUE THREAD

**Issue by kirill-konshin** [fabricjs/fabric.js#7072]
## Version
4.4.0

## Test Case
http://jsfiddle.net/dfuse/sum69g72/11/

## Steps to reproduce

```js
const canvas1 = window._canvas1 = new fabric.Canvas('c1');
const canvas2 = window._canvas2 = new fabric.Canvas('c2');

const line1 = new fabric.Line([10, 10, 90, 90], {stroke: "#000000"});
const line2 = new fabric.Line([10, 10, 90, 90], {stroke: "#000000"});

canvas1.add(line1);
canvas1.renderAll();

canvas2.add(line2);

line2.set(line1.toJSON());
line2.setCoords();
canvas2.renderAll();
```

## Expected Behavior

Both lines should be the same on both canvases.

## Actual Behavior

![image](https://user-images.githubusercontent.com/1530410/119213504-5e89e480-ba74-11eb-8e98-64504c90d712.png)

Second line is moved from it's original position, `toJSON` of both lines is different:

![image](https://user-images.githubusercontent.com/1530410/119213568-ed96fc80-ba74-11eb-955a-94dd3395736d.png)

**Comment by kirill-konshin** [comment]
Solution for now is to set `{left: line1.left, top: line1.top}` after first `set`.

**Comment by kirill-konshin** [comment]
Not stale, and still no solution.

**Comment by i-prikot** [comment]
Hi.

@kirill-konshin, look in this [issues](https://github.com/fabricjs/fabric.js/issues/7099)

**Comment by i-prikot** [comment]
@asturur, here you need to pass the `this` to the method `this._setWidthHeight()`
![image](https://user-images.githubusercontent.com/21138391/120996054-2c84bc00-c7b0-11eb-9f5f-6f4687dbd7d9.png)

**Comment by i-prikot** [comment]
Hi.

@kirill-konshin, I hope this helps you http://jsfiddle.net/i_prikot/Ly7ec3p2/33/

This is bad code:

```
fabric.Line.prototype._set = function(key, value) {
  const coordProps = { x1: 1, x2: 1, y1: 1, y2: 1 }
  this.callSuper('_set', key, value);
  
  if (typeof coordProps[key] !== 'undefined') {  
    this._setWidthHeight(this);
  }
  
  return this;
}
```

**Comment by asturur** [comment]
@kirill-konshin  did you understand the issue behind your problem?

**Comment by kirill-konshin** [comment]
@asturur @i-prikot sorry, I was on vacation and missed the last stale comment. Issue is not stale, it's still an issue, and I have no resolution... What should I do with the bad code snippet? I guess it's a patch for fabric.js? Shouldn't it be the part of the codebase then?

**Comment by i-prikot** [comment]
> @asturur @i-prikot sorry, I was on vacation and missed the last stale comment. Issue is not stale, it's still an issue, and I have no resolution... What should I do with the bad code snippet? I guess it's a patch for fabric.js? Shouldn't it be the part of the codebase then?

Hi, @kirill-konshin.

```
function getProperties(fabricObject, copyProperties = ["left", "top", "stroke", "height", "width"]) {
  const properties = {};
  
  copyProperties.forEach(prop => {
  	properties[prop] = fabricObject[prop];
  });
  
  return properties;
}

canvas1.add(line1);
canvas1.renderAll();
canvas2.add(line2);
line2.set(getProperties(line1))
```

or 

`canvas2.loadFromJSON(canvas1.toJSON());`

**Comment by kirill-konshin** [comment]
I wonder why this obviously buggy behavior is not fixed at lib level? Win-api bug-features, that nobody dare to touch? ;) No offense just in case, just curious.
