### ISSUE TITLE
Text decoration (undeline, linethrough) is wrong when direction is set to 'rtl' and align is not right

### ISSUE THREAD

**Issue by hoomanaskari** [fabricjs/fabric.js#7076]
## Version
4.5.0

## Test Case
https://jsfiddle.net/human_a/epfjmbot/

## Information about environment
Which browsers? Chrome latest

The text decorations (undeline, linethrough) are being drawn wrong. I think the `_getLineLeftOffset` and `getLineWidth` functions are calculating it wrong. The results vary when changing text alignment too.

**Comment by asturur** [comment]
Thanks i ll look into this asap

**Comment by baras** [comment]
> The results vary when changing text alignment too.

Yup, cursor position and text selection are also off when `textAlign` is not `right`.

**Comment by asturur** [comment]
For now RTL works with text-align right only.
Going to implement center and left later.
Or anyone can start o have a look at it.

Are you RTL users/writers? how does the implementation look like to you?

**Comment by asturur** [comment]
Ok now i checked the issue code sample.
Yes this is a part that hasn't been implemented yet, but we can actually fix quickly as soon as possible.
So i will mark it as feature and change the title. Was on the roadmap anyway

**Comment by asturur** [comment]
Ok there is also a bug
![image](https://user-images.githubusercontent.com/1194048/120932931-16b3c000-c6f8-11eb-8b4e-9c08b61fbe73.png)

i have a fix for the rtl/align-right with rtl text.
i can't fix for now a rtl text that then is handled as LTR from the canvas because is english text.

**Comment by asturur** [comment]
this pr https://github.com/fabricjs/fabric.js/pull/7104 fixes the bug.
