### ISSUE TITLE
How to enable touch events ? 

### ISSUE THREAD

**Issue by afnanz7634** [fabricjs/fabric.js#7077]
i'm using fabric js in my react application on zooming it works fine on desktop but touch is not working on ipad iphone ?????

**Comment by melchiar** [comment]
Which touch events are you referring. Fabric.js does allow touch interaction with objects. Do you mean gesture support?

**Comment by afnanz7634** [comment]
yes exactly found that thanks

**Comment by yuxiao-chen** [comment]
> yes exactly found that thanks

Can you share how it was done?  thanks

**Comment by yuxiao-chen** [comment]
> yes exactly found that thanks

@afnanz7634  Can you share how it was done? thanks
