### ISSUE TITLE
Textbox edit focus error after loadSVGFromString maybe because Event "text:editing:exited" not firing

### ISSUE THREAD

**Issue by sagiadinos** [fabricjs/fabric.js#7078]
When loaded svg via  loadSVGFromString the edit curser remains on last textbox when selecting another textbox.

The new textbox will be marked, but typing on keyboard edits the previous textbox

That is strange because export the svg as JSON and then reloading via loadFromJSON shows not this behaviour.

https://jsfiddle.net/sagiadinos/mwefdjt0/

Reproduced with:
Chrome, Safari, Firefox on macOS Big Sur
Chrome on Linux
Edge Windows 10

![Bildschirmfoto 2021-05-26 um 17 11 00](https://user-images.githubusercontent.com/16494822/119685146-66b39c80-be45-11eb-860b-50be63187b84.png)

**Comment by melchiar** [comment]
Here's the problem. 

Your SVG contains `Text` objects, but your code is creating a bunch of `Textbox` objects by passing all of the properties of the `Text` objects into the `Textbox` constructor. The result is you're getting weird hybrid objects that are created using the `Textbox` constructor but have a bunch of properties and the type value of a `Text` object.

Try this approach instead:
https://jsfiddle.net/melchiar/h7yu3c10/

**Comment by sagiadinos** [comment]
Thank you melchiar.

I fixed my code. A "delete textobj.type" is not even necessary.

**Comment by melchiar** [comment]
No problem, just a note that if you don't delete the textobj.type attribute the object will be serialized as a regular `text` object rather than a `textbox` object.
