### ISSUE TITLE
`Object.selectable()` does not handle an edge case

### ISSUE THREAD

**Issue by taoning2014** [fabricjs/fabric.js#7079]
## Version
4.3.1

## Test Case

http://jsfiddle.net/Lcf4wyzs/

## Information about environment
Nodejs or browser? Browser
Which browsers? Chrome

## Steps to reproduce
Please see the jsfiddle link above.
Case 1:
1. Run the code, move the rectangle by mouse.
2. Click the button.
3. The rectangle can still be moved by mouse even the click event handler set `selectable` to `false`.

Case 2:
1. Run the code
2. Click the button
3. The rectangle can not be moved by the mouse.

## Expected Behavior
In both case 1 and 2, after clicking the button which set `selectable` to `false`, the rectangle shouldn't be moveable anymore.

## Actual Behavior
In case 1 where the user moves the rectangle before set `selectable` to `false`. After setting `selectable` to `false`, it is still movable.

**Comment by melchiar** [comment]
The `selectable: false` property doesn't deselect an object that's already selected, or prevent an object from being selected programmatically. It only disables the behavior where an unselected object can be clicked to select it, which in your fiddle works just fine.

When you change an object to `selectable: false` you should deselect it with `canvas.discardActiveObject()`

**Comment by taoning2014** [comment]
Thank you very much @melchiar, calling `canvas.discardActiveObject()` perfectly solve my problem. Thanks for the timely response.
