### ISSUE TITLE
getPointer method throwing exception in firefox

### ISSUE THREAD

**Issue by jcteague** [fabricjs/fabric.js#708]
I am dropping items onto the canvas.  In order to know where the user is dropping the item, I am calling getPointer() to get the mouse coordinates.  this is not working on firefox -- mac (fine in chrome and safari).  Firefox is complaining the "event is not defined".

I'm executing the code like this:

``` javascript
mouse_position = _this.stage.getPointer();
```

it is failing here:

``` javascript
function getPointer(event, upperCanvasEl) {
  event || (event = fabric.window.event);
  var element = event.target || (typeof event.srcElement !== 'unknown' ? event.srcElement :   null),
  body = fabric.document.body || {scrollLeft: 0, scrollTop: 0},
  docElement = fabric.document.documentElement,
  orgElement = element, 
  scrollLeft = 0,
  scrollTop = 0,
  firstFixedAncestor;
```

I'm not sure what I would pass as the event object.

I'm happy to help resolve if I can get some pointers on where to start

**Comment by FeaRCODE** [comment]
@asturur Oddly enough i am running into this same issue in Firefox. I cant remember what I added in my code, but only Firefox gives an error here. Any ideas? (Latest version).

**Comment by FeaRCODE** [comment]
Here is what i could manage to get right when i selected two object, again, by drag selection.

![image](https://cloud.githubusercontent.com/assets/6901336/16167356/90c5cc3e-34b9-11e6-92f6-d38613f1d1f0.png)

![image](https://cloud.githubusercontent.com/assets/6901336/16167360/99bde18c-34b9-11e6-8454-c79c2afcb09a.png)

Not sure what causes this, but it's only in Firefox from what I know.

**Comment by asturur** [comment]
you should check what you have in containsPoint. if you have some overriden code i think that i changed parameters of some internal methods.

**Comment by FeaRCODE** [comment]
To my knowledge I haven't touched a thing. And it's only in Firefox which is more odd.

**Comment by butch2k** [comment]
Could you post your __mouseMove() function ?

**Comment by FeaRCODE** [comment]
@butch2k That isn't my method. That is part of the FabricJS source code. Something in there is breaking for some reason.

**Comment by butch2k** [comment]
Sorry, i'm out of coffee today...
Are you on mac like the OP ?

**Comment by butch2k** [comment]
It tested on FF on a Mac but i was not able to reproduce on 1.6.2.
Is it something special you manipulate ?

**Comment by FeaRCODE** [comment]
Nope I don't even call any methods in mouse move or mouse down. I am on Windows 10 FF on 1.6.2

**Comment by FeaRCODE** [comment]
When I drag select two or more items and move my mouse or click I get an error. Event is undefined.

**Comment by awehring** [comment]
I stumbled about this too and discovered the reason.

With Firefox you must supply an event parameter: `point = canvas.getPointer(evt);`
Chrome and IE11 work without `point = canvas.getPointer();`

Watch the console with this simple example: http://jsfiddle.net/Da7SP/170/
(Tested with FF 47, Chrome 52, Win10; IE11 Win7)

Honestly, the fabricjs documentation requires the parameter. So no one to blame.

**Comment by FeaRCODE** [comment]
@awehring I actually didn't even see this. And thank you for finding a solution. Ill let you know if this works!
