### ISSUE TITLE
Some images with filter load partially into the canvas

### ISSUE THREAD

**Issue by hoomanaskari** [fabricjs/fabric.js#7084]
## Version
4.5.0

## Test Case
https://jsfiddle.net/human_a/2s6bmog9/

## Information about environment
NodeJS or browser? Browser
Which browsers? Chrome latest

## Steps to reproduce
Once you load the fiddle you can see that image is only partially rendered, compare it to the original image below the canvas. Duplicating images with filter sometimes cause the same issue. I could not find out exactly what sort of images break, so I only showcased the broken type. Removing the filter will fix the issue and the image will load properly. This happens regardless of what type of filter is used.

## Expected Behavior
All images must load fully even when they have a filter.

**Comment by melchiar** [comment]
This is addressed in the image filter guide under Common Errors and Problems. 

http://fabricjs.com/fabric-filters

**Comment by hoomanaskari** [comment]
Thanks for writing back, I already knew about the article. But as you can see in the fiddle, I have set the `fabric.textureSize = 4096;` and the image I am using is `3840x2160`. So the fabric.textureSize option does not have any effects?

**Comment by melchiar** [comment]
I've found the problem. Remove this line: `fabric.filterBackend = new fabric.WebglFilterBackend();`

You should not need to create a filter backend instance after changing the texture size.

**Comment by hoomanaskari** [comment]
Yes, that was it, thank very much for your help.
