### ISSUE TITLE
All contents of the canvas rotate around the center

### ISSUE THREAD

**Issue by 521707** [fabricjs/fabric.js#7087]
- I annotate a lot of information at the specified position of the picture. When I rotate the picture, how do I make the annotation information rotate with the picture. Make the text fixed on the picture.

- I want to change the size of the picture and the label will also change the size
similar: [Using transformations, Introduction to Fabric.js Part 6 ?](http://fabricjs.com/using-transformations)

fabricjs version:"1.4.13"
## My expected result
- When the picture is rotated, the text on the picture will rotate or move with it, etc.

```
changeText: [],
writeText(textList = []) {
    const { canvas, image, sourceImage } = this.darkroom
    const changeText = this.changeText
    for (const item of textList) {
        const { location, words } = item
        const textInstance = new fabric.IText(String(words), {
            top: image.top + location.top * image.scaleX,
            left: location.left * image.scaleY,
            fontSize: Math.floor(location.width / words.replace(/[^\u0000-\u00ff]/g, "aa").length * 2 * image.scaleX),
            fill: '#fff',
            // lockUniScaling: true,
            // hasRotatingPoint: false,
            backgroundColor: `rgba(0,0,0,0.8)`,
            // originX: 'center',
            // originY: 'center',
            // lockMovementX: true,
            // lockMovementY: true
        });
        canvas.add(textInstance)
        changeText.push(textInstance)
    }
},
watchCanvas(type) {
    const { canvas, sourceImage, image } = this.darkroom
    if (type === 'rotate') { // picture is rotating
        const changeText = this.changeText
        console.log(canvas.getWidth() / 2, '<=canvas.getWidth()', sourceImage.angle)
        const canvasCenter = new fabric.Point(canvas.width / 2, canvas.height / 2); // 画布的中心位置
        setTimeout(() => {
            changeText.forEach(obj => {
                const objectOrigin = new fabric.Point(obj.left, obj.top);
                const new_loc = fabric.util.rotatePoint(objectOrigin, canvasCenter, sourceImage.angle);
                obj.top = new_loc.x
                obj.left = new_loc.y
                obj.angle = sourceImage.angle
                obj.bringToFront()
            })
        });

    }
},
const  textList= [
  {
    words: "商务服务业",
    location: {
      top: 587,
      left: 378,
      width: 91,
      height: 18,
    },
  },
  {
    words: "方平",
    location: {
      top: 536,
      left: 378,
      width: 36,
      height: 18,
    },
  },
  {
    words: "200万元",
    location: {
      top: 431,
      left: 1043,
      width: 150,
      height: 19,
    },
  },
]
```

![123](https://user-images.githubusercontent.com/37111718/119973593-4111c900-bfe6-11eb-81c2-4cd2943699ca.png)
![6666](https://user-images.githubusercontent.com/37111718/119973598-4242f600-bfe6-11eb-8335-fbe0c6271534.png)

## Is it possible to select a large number of objects and then rotate them?
![xz](https://user-images.githubusercontent.com/37111718/119974807-b9c55500-bfe7-11eb-883d-6c2a1208ed5b.gif)

**Comment by asturur** [comment]
Can you give more informations? there are generic ways to do so, but require to understand the interactioin.
Will the user rotate the image freely and scale it? drag it?
What is your expected UX?

i would assume you could use the custom control api on the image in order to execute different code when interacting with the image.
But how many things are on the canvas? how many are supposed to follow the image in the movement?

**Comment by 521707** [comment]
> Can you give more informations? there are generic ways to do so, but require to understand the interactioin.
> Will the user rotate the image freely and scale it? drag it?
> What is your expected UX?
> 
> i would assume you could use the custom control api on the image in order to execute different code when interacting with the image.
> But how many things are on the canvas? how many are supposed to follow the image in the movement?

1、I want all the elements in the image to rotate automatically when I rotate the image. 
tips：The position of the element in the image remains the same
2、The number of elements on the canvas is determined by the complexity of the picture.
