### ISSUE TITLE
Extreme letter spacing when scaled using toDataURL multiplier

### ISSUE THREAD

**Issue by BE-CH** [fabricjs/fabric.js#7090]
## Version
FabricJS 4.4.0
Node-Canvas 2.7.0

## Information about environment
Happens in NodeJS v16.1.0

CharSpacing is set to 0 on all iText's. 

Happens only on longer text. Haven't tested exact amount but around +30 character. 

## Steps to reproduce
1. Create canvas JSON with iText.
2. Load canvas from JSON in node
2. Convert canvas to DataURL in node with multiplier set to 20x
3. Save the base64 on the server using fs.writeFile()

## Expected Behavior
The iText not having its letter spacing changed when scaled with the multiplier.

## Actual Behavior
The letter spacing of the iText's is getting huge and making the parts of the text go out the canvas.

**Image with multiplier 1.5 (No big difference in letter spacing)**
![image](https://user-images.githubusercontent.com/1050050/120072358-d323db00-c093-11eb-913d-c7fcabd88701.png)

**Image with multiplier 20 (Big difference in letter spacing compared to 1.5x multipler)**
![2av5cxkp9skro1-min](https://user-images.githubusercontent.com/1050050/120072372-eb93f580-c093-11eb-849a-771e1505c96a.jpg)

**Image from the canvas after loading the canvas from JSON (Looks perfect. How it ideally should look even if scaled.)**
![fromcanvas](https://user-images.githubusercontent.com/1050050/120072394-01091f80-c094-11eb-935e-f046096ada4e.png)

**Comment by BE-CH** [comment]
Doing further research, I found out that it is related to the ``charSpacing`` setting. 

**Solution:**
Do not set ``charSpacing`` to 0. That will not work.
Instead calculate charSpacing by doing this:
```
const charSpace = 0.001;
const parsedSpacing = (fabric.util.parseUnit(charSpace, Math.floor(fontSize)) / Math.floor(fontSize)) * 1000;
```

This fixed it for me. Make sure you load custom fonts correctly as well. More information can be found here: http://fabricjs.com/fabric-intro-part-4#custom-fonts

**Comment by asturur** [comment]
charSpacing set to 0 should leave it untouched. Did you manage to understand what was going on?

**Comment by BE-CH** [comment]
> charSpacing set to 0 should leave it untouched. Did you manage to understand what was going on?

Never managed to completely understand what was going on - but setting ``charSpacing`` to ``0`` didn't quite do it for me. 

When calculating the charSpacing (into _em_ i think?) as my reply above, then I had no problems at all. Its quite weird. 

**Though, i don't know for sure. I am pretty sure that the problem lies on node-canvas / fabric on node.js. The charspacing is not weird in the actual js canvas - but once scaled up in node.js that is where the charSpacing 0 acts weirdly.**

**Comment by asturur** [comment]
in theory when charspacing is 0, the code for charspacing is skipped all together by fabricjs
Unless maybe it was a 0 in string and messing it up.

**Comment by niketaOptimumnbrew** [comment]
> in theory when charspacing is 0, the code for charspacing is skipped all together by fabricjs Unless maybe it was a 0 in string and messing it up.

Hi @asturur 
Do you know how to solve above problem with charSpacing 0 instead of 0.001?

**Comment by asturur** [comment]
@niketaOptimumnbrew charspacing as implemented by fabricJS will break ligatures for sure.
Do you have an understanding of unicode points and graphemes?

Also you continue to open very low quality questions.
You post me a jpeg of a text i do not know of a language i do not understand with a font i have no idea how is supposed to look. What do you want me to find out with a screenshot?

You have to use a grapheme splitter if you want to work with languages that have complex graphemes. are you using one?
