### ISSUE TITLE
Text box bounding render incorrectly on Chrome 

### ISSUE THREAD

**Issue by duydodevgithub** [fabricjs/fabric.js#7094]
When load canvas from json, the bounding rectangle box render incorrectly on Chrome and Safari, there is no issue with Firefox.

![image](https://user-images.githubusercontent.com/28528569/120532701-25555b00-c40a-11eb-9c24-9a12ea54d4b7.png)

## Version
Fabricjs: 2.7.0

## Information about environment
Chrome: Version 91.0.4472.77 (Official Build)
Firefox: Version 88.0.1 
Safari: Version 14.1.1 (16611.2.7.1.4)

Not sure if this is a fabric bug. Or do you have any ideas for this issue I am really appreciate.

**Comment by melchiar** [comment]
Can you share your code?

**Comment by asturur** [comment]
If your example is based on fabricJS 2.7.0 update to 4.5.0 to post the example.

**Comment by duydodevgithub** [comment]
Thank you for your response. I find out that the issue is because of custom fonts wasn't loaded correctly when using chrome, that cause incorrect width/height. The problem is fixed when adding code to force the fonts to load before JSON.  This is not a fabric js bug. Ticket is closed.
