### ISSUE TITLE
Is there any way to double click to iText to edit?

### ISSUE THREAD

**Issue by manhthepixta** [fabricjs/fabric.js#7095]
Currently just click to the text to place the cursor. Is double click possible?
I also want text can be moved while editing like Google presentation. Is that possible?

Thanks in advance.

**Comment by asturur** [comment]
Hi, currently there is no way to do either.
You can disable editing and try to activate it on doubleclcik event. That is doable for sure.

moving while editing is a bit more complicated but probably you can get away with a move control with the custom control api. While editind a drag action will select text.

**Comment by manhthepixta** [comment]
> Hi, currently there is no way to do either.
> You can disable editing and try to activate it on doubleclcik event. That is doable for sure.
> 
> moving while editing is a bit more complicated but probably you can get away with a move control with the custom control api. While editind a drag action will select text.

Thanks
