### ISSUE TITLE
Grouped objects do not render properly

### ISSUE THREAD

**Issue by harm-less** [fabricjs/fabric.js#7098]
## Version
4.5.0

## Test Case
http://jsfiddle.net/23fjcbLh/9/

**Comment out from line 30 to disable the scaling animation to handle the group manually**

## Steps to reproduce
I'm trying to scale a group containing a rectangle and a text. After the group is being scaled, the width and height is set to the scaled width and height and the scale itself is reset back to 1. This will result in the content of the group returning back to their original size. The text indicates this is properly happening as it stays the same size.
However, for the rectangle I'm actually setting a new width and height based on the new width and height of the group. But this somehow does not happen when the group is small and all of a sudden at a seemingly random width/height it fits the group (make sure you notice the first time the Fiddle scales up). Scaling back down it will not shrink down further when it reaches this seemingly magic width/height once more.

## Expected Behavior

I expect the rectangle to always have the same size as the group it is contained in, even when the group us small.

## Comments

I'm not sure if I'm missing something, but it feels like a bug if I'm not.

Thanks in advance,
Harm

**Comment by harm-less** [comment]
Oh no... I think it solved the issue 😅 
http://jsfiddle.net/d50uj36v/

I changed 
```ts
rect.width = newWidth
rect.height = newHeight
```
to
```ts
rect.set('width', newWidth)
rect.set('height', newHeight)
```

But still, why does this work and the original does not?

**Comment by i-prikot** [comment]
Hi. 

This text is from the guide http://fabricjs.com/fabric-gotchas

Object does not update after changing property - objectCaching

A common source of confusion is when a developer assigns a new property to fill and the objects does not update after a renderAll.
FabricJS does cache objects as images to speed up rendering. If you want fabricJS to know that something changed and that a particular object needs to be redrawn, use the `set` method.

```
rect.set('fill', 'red');
canvas.requestRenderAll();
```

or, as an alternative:

```
rect.fill = 'red';
rect.stroke = 'blue';
rect.set('dirty', true);
```

Example for you http://jsfiddle.net/i_prikot/5shu71nk/1/

**Comment by harm-less** [comment]
Thanks for the detailed description @i-prikot. This helped me to better understand how it works under de hood. I should've read the [gotchas](http://fabricjs.com/fabric-gotchas) while doing this I guess 😉
