### ISSUE TITLE
Fabric js objects to be responsive in all the screens

### ISSUE THREAD

**Issue by dennisideaonce** [fabricjs/fabric.js#7108]
I have two circles in a fabric js canvas (screen resolution is 1440*768 px) -
[![enter image description here][1]][1]

The left circle is 69.33552631578948% from the leftmost corner of the grey area (actual canvas) and the right is at 69.33552631578948% from the leftmost corner.

```
let percentageFromLeft = (o.left / olderBoard.main_canvas_width) * 100;
```

This is how I place the object:

```
const canvas: any = document.querySelector('#canvas');
const vpW = canvas.offsetWidth;
o.set('left', vpW * percentageFromLeft/100 );
```

This is the formula I have used from finding the percentage position of the circle from the left-most corner of the canvas.

When when I on ca smaller mobile or tab resolutions:

![tabs[2]][2][![mobile resolution][3]][3]

How can I make them all consistent on all the screens?
Do you find a problem with the above formula?

  [1]: https://i.stack.imgur.com/BJpod.png
  [2]: https://i.stack.imgur.com/MansR.png
  [3]: https://i.stack.imgur.com/J3No1.png

**Comment by ramsesndame237** [comment]
hey did you solve this problem ? im having the same issue
