### ISSUE TITLE
fractionated gain ?

### ISSUE THREAD

**Issue by QJesus** [fabricjs/fabric.js#7111]
a rect or circle, whatever, moving with cursor, Zoom in to display a local area of the canvas

something like below:

![image](https://user-images.githubusercontent.com/9971413/121636033-e08c8c80-cab9-11eb-9c4c-6f0d9e9fd16a.png)

**Comment by melchiar** [comment]
Please try to put some more effort in when writing your issue. There is an issue template for a reason.

Perhaps this will help
https://stackoverflow.com/a/23977061/7693185
