### ISSUE TITLE
OBJECT’S POSITION MOVES WHEN SELECTING MULTIPLE IN FABRIC.JS

### ISSUE THREAD

**Issue by dennisideaonce** [fabricjs/fabric.js#7115]
## Version
4.4.0

## Test Case
https://stackoverflow.com/questions/67614579/objects-position-moves-when-selecting-multiple-in-fabric-js

## Information about the environment
Chrome

## Steps to reproduce
I am unable to create a fiddle for this problem, the problem is weird.  My code is tightly coupled with other components.

It's exactly the same as shown in the above stackoverflow link.

For one object everything is fine but for more than an object, the same thing happens.

https://user-images.githubusercontent.com/81302013/121796424-806f2500-cc36-11eb-8f57-f296be7e0e89.mp4

**Comment by melchiar** [comment]
You should try to reproduce this with a fiddle. The process of creating a minimal example of an issue usually shows exactly where the bug lies, whether it's in your application, or a specific combination of library properties.

**Comment by dennisideaonce** [comment]
Yes I agree with you, I am doing this right now, I thought it has came to many people in the past so it is some something related to configurations

**Comment by dennisideaonce** [comment]
@melchiar You are a genius, while creating the fiddle I found the issue and it is fixed!
