### ISSUE TITLE
How do you make the lines stay the same thickness as you stretch them？

### ISSUE THREAD

**Issue by Ezr1al** [fabricjs/fabric.js#7122]
## Version
4.3.1

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Chrome  89.0.4389.90

## Description 
When I stretch a graphic object, if the object is a face, the border of the face will also be stretched.If the object is a line, the line itself will stretch.This will result in the same 6px border with a different visual size.I want the line or border size not to be stretched when I stretch the shape. What should I do?
![image](https://user-images.githubusercontent.com/36941749/121988565-22287a80-cdcd-11eb-846f-b7b2bd0b1d24.png)

**Comment by i-prikot** [comment]
Hi. 

Take a look at the guide http://fabricjs.com/stroke-uniform
