### ISSUE TITLE
Text's control box's dimentions doesn't match the real text dimentions when text has a 'path' property.

### ISSUE THREAD

**Issue by EdnaldoNeimeg** [fabricjs/fabric.js#7123]
You can clearly see that the text's control box matches the path dimmentions, not the text itself.

It causes some rendering issues (text clipping) when i zoom in/out  

https://jsfiddle.net/Neimeg/L8bw14fv/

![path1728](https://user-images.githubusercontent.com/6233059/122059342-e7214980-cdc2-11eb-8ebb-096a640d829e.png)

**Comment by EdnaldoNeimeg** [comment]
I temporarely solved it by increasing the width/height of the text with the fontSize * 2

Eg:
`object.set('width', object.width + object.fontSize * 2)`

![Captura de tela de 2021-06-15 12-04-16](https://user-images.githubusercontent.com/6233059/122077154-ddeba900-cdd1-11eb-99fc-6af05a62d656.png)

**Comment by asturur** [comment]
yes text on a path is a new beta feature and we did not solve all the issuses yet.
