### ISSUE TITLE
Ctrl+Z on removed text is not return correct styles

### ISSUE THREAD

**Issue by LenkouAndrei** [fabricjs/fabric.js#7124]
## Version
4.4.0

## Test Case
http://jsfiddle.net/andlen/twm9vxbo/1/

## Information about environment
Issue is platform agnostic

## Steps to reproduce
1. Create an IText Object with different styles for letters
2. Remove some letters with 'Delete', 'Backspace' or Ctrl+X
3. Return the previous state with Ctrl+Z

## Expected Behavior
All letters have the same styles (ex. color) like it was before 'Delete', 'Backspace' or Ctrl+X

## Actual Behavior
All letters, that returned, have the same styles (ex. color) as the letter before the cursor

**Comment by asturur** [comment]
i think that ctrl+z and ctrl+y do not trigger any event we can capture.
I could be wrong, but i remember this was an issue we did not know how to solve.
If is just a simple bug would be great to fix it.
