### ISSUE TITLE
Object geometry methods for grouped objects

### ISSUE THREAD

**Issue by ShaMan123** [fabricjs/fabric.js#7130]
## Version
latest

## Test Case
http://jsfiddle.net/mkdve1x9/15/

## Information about environment
Browser.

## Steps to reproduce
1. Create a `Group`/`ActiveSelection`
2. Try using a method from [`object_geomerty`](https://github.com/fabricjs/fabric.js/blob/2eabc92a3221dd628576b1bb029a5dc1156bdc06/src/mixins/object_geometry.mixin.js#L191) on an object that belongs to the group

## Expected Behavior
Should work for nested objects without additional code

## Actual Behavior
It returns wrong values because the object's transform matrix is used and is relative to the group

**Comment by ShaMan123** [comment]
I suggest enhancing `calcTransformMatrix`.
https://github.com/fabricjs/fabric.js/blob/2eabc92a3221dd628576b1bb029a5dc1156bdc06/src/mixins/object_geometry.mixin.js#L584
```js
matrix = multiplyMatrices(this.group.calcTransformMatrix(true), matrix); 
```
This will open the door for many fixes.

**Comment by asturur** [comment]
Yes.
The more i look at it and the more i think all the whole aCoord,oCoord is, excuse me the term, fucked up.
Fix it is a mess, it requires a full rewrite of so many internals and a ton of regression test/unit tests.

Ideally we want to get rid of oCoords entirely and all that absolute: true/false on those kind of geometry functions.
The only way to fix this is to add inside a 
```
if (this.group) {
// take group transform matrix
// multiply the points for group transform matrix
}
// proceed with normal checks
```

**Comment by ShaMan123** [comment]
Man I absolutely agree.
You rock.

**Comment by ShaMan123** [comment]
#7599
