### ISSUE TITLE
`absolutePositioned` with objects nested in groups

### ISSUE THREAD

**Issue by ShaMan123** [fabricjs/fabric.js#7142]
## Version
latest

## Test Case
http://jsfiddle.net/2185reh6/19/

## Information about environment
browser chrome

## Steps to reproduce
Add an `absolutePositioned` clip path to an object inside a group

## Expected Behavior
Clip path should be positioned relative to canvas, http://fabricjs.com/docs/fabric.Object.html#absolutePositioned

## Actual Behavior
Because group manages it's own plane the clip path is relative to the group

**Comment by ShaMan123** [comment]
This is a part of the major problem that group creates on it's objects.
I think the solution should handle changing `calcTransformMatrix` so it can calculate the matrix  relative to the canvas as well with a flag.
Related #7130 #6776

**Comment by ShaMan123** [comment]
I think the problem is that `calcTransformMatrix` is called from within a the clipPath. This call is unaware of the context it is running in, meaning it doesn't know it is a clip path transformed to a relative plane, therefore, it can't account for the transform matrix of the containing object.

**Comment by i-prikot** [comment]
Hi. I think it works as intended.
http://jsfiddle.net/i_prikot/fgkyns8z/

**Comment by ShaMan123** [comment]
http://fabricjs.com/docs/fabric.Object.html#absolutePositioned

**Comment by asturur** [comment]
this is a though one.
Both use cases are fine, and discerning between the 2 with more options is not that much convenient.
The absolute positioned idea was to be able to have a clipPath on the canvas that would influence only an object.

It is working as intented from what i can see in the fiddle, but the point is that it does not invalidate the group cache on movement.

Not sure if this in an edge case that deserve fixing or not.
https://jsfiddle.net/qzo7r3y9/
you can also just set objectCaching: false on the group when you create it.

**Comment by ShaMan123** [comment]
I found a work around
```js
            const __drawClipPath = fabric.Object.prototype._drawClipPath;
            fabric.util.object.extend(fabric.Object.prototype, {
                _drawClipPath: function (ctx: CanvasRenderingContext2D) {
                    __drawClipPath.call(this, ctx);
                    //  render stuff here
                }
            })
```

Now I am able to render many clip paths with varying `absolutePositioned` value.

**Comment by ShaMan123** [comment]
fixed by the rewrite 
https://codesandbox.io/s/0d1pbh
Once caching is resolved this is gone for good
