### ISSUE TITLE
textbox use google font,The cursor position is incorrect

### ISSUE THREAD

**Issue by shuwenjunn** [fabricjs/fabric.js#7149]
## Version
v4.5.1

## Test Case
http://jsfiddle.net/ao7y8qdL/14/

## Information about environment
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

## Steps to reproduce
[video](https://youtu.be/5c2yGC4Mk-I)
## Expected Behavior
the textbox cursor position is incorrect。
## Actual Behavior
the cursor position should be  behind the text。

**Comment by melchiar** [comment]
Custom fonts need to be preloaded first or Fabric isn't able to properly measure the character widths. See here for an example of how to do this: http://fabricjs.com/loadfonts

**Comment by sanheng** [comment]
> Custom fonts need to be preloaded first or Fabric isn't able to properly measure the character widths. See here for an example of how to do this: http://fabricjs.com/loadfonts

The demo is not work.

**Comment by sanheng** [comment]
> Custom fonts need to be preloaded first or Fabric isn't able to properly measure the character widths. See here for an example of how to do this: http://fabricjs.com/loadfonts

[http://fabricjs.com/loadfonts](http://fabricjs.com/loadfonts) demo is not work

![image](https://user-images.githubusercontent.com/13793256/126292493-66e5ff56-6455-434f-86ac-52ef378e9991.png)

**Comment by melchiar** [comment]
It looks like your browser is throwing a PROXY_CONNECTION_FAILED error when it tries to load the fontfaceobserver.js resource, which is loaded from [this url](https://rawgit.com/bramstein/fontfaceobserver/master/fontfaceobserver.js). Are you connecting through a proxy server?

**Comment by asturur** [comment]
Also unblock ads from fabricjs.com thanks!
