### ISSUE TITLE
Shadows not rendering in node enviroment

### ISSUE THREAD

**Issue by pramitsawant** [fabricjs/fabric.js#7150]
Here is a sample code  

Shadows are correct in the browser 
https://codepen.io/pramit-sawant/pen/poexoav?editors=1011

![image](https://user-images.githubusercontent.com/18174055/122925519-c2295b00-d31b-11eb-9d5c-410e3d8eb816.png)

but when I try to export it from the node it doesn't render shadow.
the code example in the link below
https://gist.github.com/pramitsawant/b09bd36ab42070a8d3721b334a08a744
dependencies
"canvas": "^2.8.0",
"fabric": "4.3.1",
"fs-extra": "^9.1.0"

![image](https://user-images.githubusercontent.com/18174055/122925568-d0777700-d31b-11eb-9b28-294ff7d8a8e1.png)

**Comment by asturur** [comment]
can you try to remove `"globalCompositeOperation":"source-atop",` and see if it works correctly? then we can narrow down the root cause

**Comment by pramitsawant** [comment]
Removed `"globalCompositeOperation":"source-atop",`  result is completely different.

![image](https://user-images.githubusercontent.com/18174055/123502769-a9fb5980-d603-11eb-8f21-6b1ea414ae3f.png)

**Comment by asturur** [comment]
So it could be because in nodejs the objectCaching is disabled by default.
Try to force it on, with `fabric.Object.prototype.objectCaching=true` before creating your objects.
If it doesn't work, well then the issue is how node-canvas do those things and i m not sure i can help much there

**Comment by pramitsawant** [comment]
Hey @asturur,
This solution worked for all default objects.
setting `fabric.Object.prototype.objectCaching=true` at the start.

I had a few custom objects as well. and setting `objectCaching `to true did not work for custom objects.
for Custom objects I deleted ` "globalCompositeOperation":"source-atop",` and it works now.

here is the preview of both

Node Generated
![image](https://user-images.githubusercontent.com/18174055/124472555-1fc59a80-dd53-11eb-8a26-fb95a8c6a00b.png)

Canvas Preview
![image](https://user-images.githubusercontent.com/18174055/124472613-2f44e380-dd53-11eb-8351-7b965cb34393.png)
