### ISSUE TITLE
SVG caching page not seem to be working

### ISSUE THREAD

**Issue by hamzawain7** [fabricjs/fabric.js#7157]
## Version
4.5.1

## Test Case
http://fabricjs.com/svg-caching

## Information about environment
Nodejs or browser?
Chrome

## Steps to reproduce
1. Goto http://fabricjs.com/svg-caching
2. SVG caching doesn't seem to animate it smoothly 
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/20171624/123407890-e4460600-d5c5-11eb-9575-6e782443ace3.gif)

## Expected Behavior
The tiger SVGs should be animating smoothly

**Comment by asturur** [comment]
Something is invalidating the cache periodically, a bug for sure.

**Comment by asturur** [comment]
This has been fixed, thanks for spotting this
