### ISSUE TITLE
LongPress FabricJS 4.0.0 & 4.5.1

### ISSUE THREAD

**Issue by Gerwin-prog** [fabricjs/fabric.js#7159]
## Version
4.0.0 & 4.5.1 (versions between these 2 most likely suffer from the same issue

## Test Case
http://jsfiddle.net/d71exfr9/

## Information about environment
Browser
Which browsers?
Chrome, FireFox, Samsung Browser

## Steps to reproduce
If you longpress before scrolling it works
But if you then drag the element down & longpress again it doesn't work

## Expected Behavior
LongPressing on an object with a window scroll position not set to 0 should still fire the longpress event

## Actual Behavior
LongPress event is not fired when the window position isn't 0 (so the window is scrolled down or sidewards)

**Comment by GerwinFleurop** [comment]
Suggested fix:

in event.js changing:

var x = (touch.pageX - bbox.x1);
var y = (touch.pageY - bbox.y1);

To:

var x = (touch.pageX - bbox.x1 - parseInt(window.scrollX));
var y = (touch.pageY - bbox.y1 - parseInt(window.scrollY));

should fix the issue

**Comment by GerwinFleurop** [comment]
Is there an update for this issue?

**Comment by asturur** [comment]
No because i did not have time to test it.
I do not have a touch device where i can comfortably test those things.
I have a surface pro 4 but is KO and i need to understand why.

**Comment by GerwinFleurop** [comment]
What do you mean with "KO" ? Sorry

**Comment by asturur** [comment]
is dead, it doen't switch on anymore.

**Comment by GerwinFleurop** [comment]
aha, if I need to test something on my phone - let me know

**Comment by Gerwin-prog** [comment]
Anything I can help with?

**Comment by Gerwin-prog** [comment]
Could this be stopped from being marked as stale - the issue is quite important & multiple people are experiencing it (ie on the post I initially replied on)

**Comment by Gerwin-prog** [comment]
Anyone who could confirm this issue?

**Comment by asturur** [comment]
hi @Gerwin-prog i m so sorry that we are so behind with issues.
We are few contributors and testing touch hardware takes longer than necessary.
I ll try to see if i can resurrect my surface this weekend or test on my android old phone.

**Comment by Gerwin-prog** [comment]
Hey, no problem if there's anything I can help with let me know

**Comment by Gerwin-prog** [comment]
@asturur Are there plans to re-work the editing on mobile? - using 2 fingers to re-scale or rotate elements sometimes causes them to jump off-screen.

**Comment by Gerwin-prog** [comment]
Is there a status update regarding this ticket?

**Comment by asturur** [comment]
Sadly no. Working on touch devices has the inherit problem of needing a touch device to play around that support debugging.
You seem to have identified a fix here:
https://github.com/fabricjs/fabric.js/issues/7159#issuecomment-868466724

would it be possible for you to open a pr with this fix and a fabricJS built with gesture so that we can just try it around?

My backlog of fabricJS never clear up sadly, and i m not sure when i ll go to this issue.

**Comment by Gerwin-prog** [comment]
@asturur see my PR -> https://github.com/fabricjs/fabric.js/pull/7595

**Comment by Gerwin-prog** [comment]
fixed in the pr
