### ISSUE TITLE
Underline has no respect to fontSize

### ISSUE THREAD

**Issue by LenkouAndrei** [fabricjs/fabric.js#7160]
## Version
4.4.0

## Test Case
http://jsfiddle.net/x65ja70r/2/

## Information about environment
Issue is platform agnostic

## Steps to reproduce
1. Create an IText Object with different styles for letters (different fontSize)
2. Apply underline to every letter

## Expected Behavior
underline has a different width

## Actual Behavior
The width for the underline is the same everywhere

**Comment by asturur** [comment]
Yes it is, i think we choose the size of the font of the main object.
Different line thickness get ugly fast.
I understand this isn't beautiful either.

How do you think multi font-size text should look like when underlined?

**Comment by LenkouAndrei** [comment]
I supposed that it can have different widths with respect to fontSize. But if it is your idea to have the same width, that is good. Thank you for your clarification.

**Comment by asturur** [comment]
What isn't great as of now is that the underline is not aligned and has that scaling effect. That isn't nice at all.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/123512302-05226000-d687-11eb-9405-28016ee0f00f.png)

this is how google doc does
