### ISSUE TITLE
How to add Erasing with Eraser Brush from Fabric.js to Next.JS(React.JS) project

### ISSUE THREAD

**Issue by iamibrahimkholil** [fabricjs/fabric.js#7171]
I need to add an eraser to my fabric js canvas from fabric js Eraser Brush in the following link. [http://fabricjs.com/erasing](url). Now I the documentation it is mentioned that it's not included in the default build of fabric js. So I googled a lot about how to add that to my NextJS project. Can anyone please help with this? Now to add to this problem I tried to download a custom build  JS file from fabric js website both Dev Build and Production Build and paste it in node_modules/fabric/dist/ folder but then I'm getting Reference Error: Window is not defined. I get it, Its Next.JS project and code do run on server side so window will be undefined. So how can I solve this problem. I need to use Erasing with Eraser Brush from fabric js.

## Version
4.5.1

## Information about environment
Next.JS

**Comment by ShaMan123** [comment]
try `node build.js modules=ALL requirejs exclude=gestures,accessors` from `fabric` directory

**Comment by asturur** [comment]
@iamibrahimkholil does your project has an npm install step?
If yes, you can define a postinstall script in your package.json.

In your post install part add a script that change directory to fabric js ( node_modules/fabric ) and that run `npm run build.js modules=ALL requirejs exclude=gestures,accessors`. In this way the build you need will be prepared every time you install a new version or when you deploy your app.

**Comment by iamibrahimkholil** [comment]
[https://codesandbox.io/s/focused-christian-7s5gx?file=/src/EraserBrush.js](url) I used this link and imported Eraser Lib as an ES6 module. Is it a good solution to follow?

**Comment by ShaMan123** [comment]
I suggest you file a bug report for the `fill.render` issue (I thought I pushed a commit that fixed it but apparently not) after you read this carefully http://fabricjs.com/erasing, there's a section about bg/overlay

**Comment by Sounav-unstudio** [comment]
@iamibrahimkholil  how did you exactly manage to install the custom build of fabric in your dev environment as well as in production ? I am also using Next,js and am facing issues. Whenever I try to run the node build.js modules=ALL requirejs exclude=gestures,accessors, it gives the following error
`Built distribution to dist/fabric.js (requirejs-compatible)
Minification failed using uglifyjs with uglifyjs  --compress --mangle --output fabric.min.js fabric.js
Minifier error output:
Error: Command failed: uglifyjs  --compress --mangle --output fabric.min.js fabric.js
'uglifyjs' is not recognized as an internal or external command,
operable program or batch file.`
Any help would be much appreciated!

**Comment by ShaMan123** [comment]
Next use ssr, fabric support ssr fron v6.
Eraser needs migrating to v6.
Good luck

**Comment by Sounav-unstudio** [comment]
Wait , so I'm using Next js v12.3.1 and fabric version 5.3.1. So you are saying I have to upgrade to version 6 in fabric? But v6 of fabric is still under development isn't it?

**Comment by Sounav-unstudio** [comment]
Until then how can I use the custom build in my Next.js project? Also I am dynamically importing the component in which I am using fabric with the ssr set to false, hence ssr shouldn't be a problem. But as I mentioned earlier, I am having trouble installing the custom fabric build in my project. Any help would be much appreciated!

**Comment by Sounav-unstudio** [comment]
@ShaMan123  how am I supposed to install the custom fabric build in my Next js project then? I am dynamically importing the component using fabric, so SSR is not an issue. But I am not able to integrate the custom build into my project as it keeps throwing up import trace errors.

**Comment by ShaMan123** [comment]
I said v6 supports ssr.
We worked hard to make that happen.
If you want to redo all that work count me out

**Comment by Shashank-Bhatt1** [comment]
@ShaMan123  How someone can use `Eraser` if he has used fabric via cdn way? Does he need to build manually and then add script built this way? Looks not proper to me. 
I have built using `npm run build` by removing eraser from exclude list and found it includes that code at last in file which we might include as separate file as an extension called `erasor.js` but i am not sure if we can.

**Comment by ShaMan123** [comment]
The eraser has been extracted to ShaMan123/erase2d
Needs fabric v6

**Comment by Shashank-Bhatt1** [comment]
I am using v5.3.0 and used everywhere so many things of it. how complex it would be to upgrade to v6? is there any guide available to do it step by step ?
