### ISSUE TITLE
loadFromJSON with Text that follows a Path

### ISSUE THREAD

**Issue by BE-CH** [fabricjs/fabric.js#7173]
## Version
FabricJS 4.4.0

## Test Case
http://jsfiddle.net/k5quhmjd/

## Information about environment
Browser
Tested on Chrome

## Steps to reproduce
*Look at the jsfiddle above*
1. Add Textbox
2. Create a fabric.Path
3. Set the ``path`` setting of the Textbox to follow the path.
4. Add the text to the canvas
5. Save the canvas as JSON with ``toJSON()``
6. Load the JSON to a new canvas with ``loadFromJSON()``

## Expected Behavior
That the text should follow the same path after being loaded from JSON.

## Actual Behavior
It throws the exception below when loading text with a path.
```
Uncaught TypeError: Cannot read property 'x' of undefined
    at i._measureLine (fabric.min.js:1)
    at i.measureLine (fabric.min.js:1)
    at i.getLineWidth (fabric.min.js:1)
    at i._getLineLeftOffset (fabric.min.js:1)
    at i._renderTextCommon (fabric.min.js:1)
    at i._renderTextFill (fabric.min.js:1)
    at i._renderText (fabric.min.js:1)
    at i._render (fabric.min.js:1)
    at i.c [as callSuper] (fabric.min.js:1)
    at i._render (fabric.min.js:1)
```

**Comment by melchiar** [comment]
Text on a Path is currently in beta and right now only supports Text objects. It'll probably be awhile before the Textbox class properly supports paths.

**Comment by BE-CH** [comment]
> Text on a Path is currently in beta and right now only supports Text objects. It'll probably be awhile before the Textbox class properly supports paths.

Okay thank you for your reply! I just tested, and it does indeed work as expected with just ``Text`` objects.

Do you know if it is possible to exclude the ``Path`` property from ``Textbox`` when exporting as JSON? That way I could simply add the path after the textbox has been loaded.

**Comment by asturur** [comment]
Maybe we can support it easily, the point is that text on a path does not have the concept of multiline or changing the width.
First we should understand what do we expect by a box that wrap a text that is positioned over a path.

take a circle.
You start to squeeze the box and a sector of the circle gets cut out.
How do you think it should behave?

**Comment by asturur** [comment]
also this is cool:
```js
const shapeString = `m 0 0 a ${angle} ${angle} 0 0 1 ${textLength.width} 0`;
```
Probably most people that want text on curve need just this formula here.

**Comment by BE-CH** [comment]
> also this is cool:
> 
> ```js
> 
> const shapeString = `m 0 0 a ${angle} ${angle} 0 0 1 ${textLength.width} 0`;
> 
> ```
> 
> Probably most people that want text on curve need just this formula here.

Thank you. One thing to mention, is that this doesn't work perfectly with a non mono-spaced font. 😃

**Comment by melchiar** [comment]
Can you share an example?

**Comment by BE-CH** [comment]
> Can you share an example? 

Example of my path working only with mono-spaced font can be seen when you add spaces or big letters to my text in the JSFIDDLE linked in the original post. 😃

**Comment by melchiar** [comment]
The kerning looks pretty good to me.

![image](https://user-images.githubusercontent.com/9057412/124412438-5bd10f00-dd03-11eb-8b7f-447003d49dfa.png)
http://jsfiddle.net/melchiar/ab609xsv/

I'm on Windows 10 which I believe uses Times New Roman as the default font, so perhaps you're seeing issues with a different font. Could you share a fiddle of the exact text where you're having kerning issues, and maybe a screenshot?

**Comment by melchiar** [comment]
@BE-CH are you able to post an example or at maybe a screenshot of the kerning issue, or is it okay if we close this issue?

**Comment by BE-CH** [comment]
> @BE-CH are you able to post an example or at maybe a screenshot of the kerning issue, or is it okay if we close this issue?

Sorry. Haven't been home. I see that you are using ``Text`` in your jsFiddle, and that seems to be working no problem. I was referring to ``Textbox`` that has some issues as seen in the JSFiddle below. _I am aware that Textbox is not yet supported. Just wanted to mention it._

http://jsfiddle.net/zegvrcb1/

**Comment by BE-CH** [comment]
> Maybe we can support it easily, the point is that text on a path does not have the concept of multiline or changing the width.
> First we should understand what do we expect by a box that wrap a text that is positioned over a path.
> 
> take a circle.
> You start to squeeze the box and a sector of the circle gets cut out.
> How do you think it should behave?

That is a good question. What I am currently doing in my project is simply calculating a new path with the correct width and applying that each time the text of the _Textbox_ changes. 

If i am understanding correctly, then I think that parts of text not fitting inside the box (_the width of the path_) should either be cut off or not be effected by the path. That way when working with the new ``Path``-feature, it can easily be understood that the box (_width of the path_) is not wide enough and therefore cant' apply to the entirety of the text.

![image](https://user-images.githubusercontent.com/1050050/125175356-d26e8080-e1cb-11eb-950b-555906967565.png)


Does this makes sense?

**Comment by asturur** [comment]
It does make sense for some cases, but not for all.
Text on paths is a party of edge cases and i m not sure if dynamic/editable text make sense at all.
