### ISSUE TITLE
Drawing 1px lines, the actual display size of the browser is 2px.

### ISSUE THREAD

**Issue by Ezr1al** [fabricjs/fabric.js#7174]
## Version
4.3.1

## Description 
draw a 1px line in Fabric.js that actually appears as 2px in the browser.compared to other drawing software, Fabric. Js draws lines at twice the size, for example, 5px is equivalent to 10px in other software

**Comment by asturur** [comment]
Can you show it somehow in a way we can reproduce it?
Are you sure is not simply retina scaling having an effect?
