### ISSUE TITLE
whats with all the BLM stuff? 

### ISSUE THREAD

**Issue by stenmuchow** [fabricjs/fabric.js#7176]
Cant we have something thats not political.

**Comment by melchiar** [comment]
If by "all the BLM stuff" you mean the one homepage banner, it was added in June 2020 in the wake of the George Floyd killing. It was relevant, and is relevant today. I really don't understand your objection.

**Comment by asturur** [comment]
I'm sorry if you have some problem with that statement, that is not directly related to BLM movement. Is a generic statement about human rights, far from politics.

I know most of other libraries removed that kind of support statements, but i don't feel like doing so.
