### ISSUE TITLE
Problems building fabric with certain includes

### ISSUE THREAD

**Issue by HustleTrader** [fabricjs/fabric.js#7180]
Have the latest repo, have built with my desired includes: Text, iText, Animations, Gestures, Interaction, Serialization and this seems to be the result no matter what I try, unless I use modules=ALL. If ALL is included, it works fine. @asturur

fabric.min.js:1 Uncaught TypeError: Cannot read property 'prototype' of undefined
  at fabric.min.js:1
  at fabric.min.js:1

**Comment by asturur** [comment]
i replied in the other thread.
