### ISSUE TITLE
Resetting canvas size causing fabricjs to forget image's original sizes.

### ISSUE THREAD

**Issue by desumer** [fabricjs/fabric.js#7188]
Hello, I'm trying to develop responsive canvas. I'm not sure this is by design. But, resetting canvas size subsequently using canvas.setHeight or canvas.height according to screen size and scaling image accordingly causing fabricjs to change original image sizes.  Therefore, object.todataurl generates smaller (width, height) images. But, this does not happen when first canvas initiliazed small or bigger then the image. fabricjs object.todataurl still generates correct image sizes.

Thank you for your help,

**Comment by i-prikot** [comment]
I am assuming that you need to reset the scale before saving. You can do an example in https://jsfiddle.net/ ?

**Comment by desumer** [comment]
Scaling is not the problem. canvas.setHeight changes the image's original with and height. Basically this is what I'm doing:

    var canvas = this.__canvas = new fabric.Canvas('canvas', {
      width: 1887, // these sizes actually calculated sizes
      height: 640,
    });

    function scaleToFit(obj) {
      // get the scale
      const imgWidth = parseFloat(obj.width);
      const imgHeight = parseFloat(obj.height);
      const canvasWidth = canvas.width;
      const canvasHeight = canvas.height;
      if (imgWidth > imgHeight) {
        const newHeight = (canvasWidth * imgHeight) / imgWidth;
        if (newHeight > canvasHeight) {
          obj.scaleToHeight(canvasHeight);
        } else {
          obj.scaleToHeight(newHeight);
        }
      } else {
        const newWidth = (canvasHeight * imgWidth) / imgHeight;
        if (newWidth > canvasWidth) {
          obj.scaleToWidth(canvasWidth);
        } else {
          obj.scaleToWidth(newWidth);
        }
      }
      obj.setCoords();
      canvas.requestRenderAll();
    };

    function setNevImage(imageData) {
      canvas.clear();
      var newPreImage = new fabric.Image(imageData, { id: 'fgImage' });
      canvas.add(newPreImage).setActiveObject(newPreImage);
      scaleToFit(newPreImage);
      canvas.centerObject(newPreImage);
    }

    var img = new Image();
    img.src = 'your image';
    img.onload = function () {
      setNevImage(img);
      canvas.renderAll();
    };

At this point object.todataurl exports image with original correct sizes.

As soon as when screen sizes changes, below functions reset the canvas sizes. After that using object.todataurl totally useless. Because, Fabricjs changes images original (natural) with and height.  

    const resizeCanvas = function () {
      canvas.setWidth($('.img-container').width());
      canvas.setHeight($('.img-container').height());
      const object = canvas.getActiveObject();
        scaleToFit(object);
        canvas.centerObject(object);
      }
      canvas.requestRenderAll();
    };

    $(window).resize(function () {
      resizeCanvas();
    });

**Comment by i-prikot** [comment]
Take a look at an example https://jsfiddle.net/i_prikot/8q0a7ry1/

**Comment by desumer** [comment]
Yes, In your example you are exporting the canvas itself plus canvas size does not change relation to changing screen/window .  If you can edit your code:
 
Add these two line of the code into resizeCanvas function to react to change in screen size. When you do that you get whatever the scaled size of the image in export file.

      canvas.setWidth($('.img-container').width());  
      canvas.setHeight($('.img-container').height());

 .img_container is the div includes canvas container or yo can just give some static value different than the initial canvas sizes.

Also I need the export specifically the image itself that way I don't have to crop it out to remove the empty transparent areas. I can resize and regenerate the original image sizes with a temp canvas but doing that totally screw up the resolution.
  
 tag.href = canvas.getActiveObject.toDataURL()

Thank you for your help,

**Comment by desumer** [comment]
Is anyone knows scaleToWidth or  scaleToHeight suppose to change actual image dimensions?  What I mean by that if uploaded image dimensions is 400x400 after scaling it (down or up) I still should able to export ( using toDataUrl) with same sizes.  If this is by design how developing responsive canvas is posibble?

**Comment by i-prikot** [comment]
I still don't understand your idea. But I added a resize to the example. https://jsfiddle.net/i_prikot/8q0a7ry1/73/

**Comment by desumer** [comment]
Is anyone knows scaleToWidth or  scaleToHeight suppose to change actual image dimensions?  What I mean by that if uploaded image dimensions is 400x400 after scaling it (down or up) I still should able to export ( using toDataUrl) with same sizes.  If this is by design how developing responsive canvas is posibble?

**Comment by desumer** [comment]
Hello i-prikot, Let's say you have an image in regular html image tag. You can make that image tag responsive.  And it can adjust depending on screen size. But, even though width and height of the image on the screen is totally different than the actual image sizes that uploaded on the browser, browser still keeps the natural original image sizes. Let's say you uploaded 600x600 image and in browser you can show that image let's say 800x800, but you still can download that image with its natural size of 600x600. So, this is what I'm trying to achieve, whatever the screen representation size of the image in canvas should not change the actual  width and height of the image or there should be some way of doing that way.  I hope, I was able to explain what I'm trying to do. 
Only thing I was able to find so far to achieve this, using zoom instead of any kind of scaling.

**Comment by desumer** [comment]
Finally figured out. in toDataUrl options withoutTransform needs to be false.
