### ISSUE TITLE
Null is not an object on Safari

### ISSUE THREAD

**Issue by SkyJedi** [fabricjs/fabric.js#7195]
This issue pops up a lot for Safari Users.  We already have a try/catch to ensure that canvas initializes correctly but this still pops up every once and a while.

![image](https://user-images.githubusercontent.com/2967416/97084318-c447e800-15db-11eb-9ceb-54303450bca3.png)

**Comment by asturur** [comment]
Would be nice to have a reproducible case

**Comment by SkyJedi** [comment]
https://jsfiddle.net/qmwdbxv5/2/

this is a duplicate of the code we run and get the error.  The error occurs pretty much exclusively on ios safari.  It looks like byt the time we load up all our images and before we build the final image safari has dumped one loaded images and we get the error like we haven't loaded the image at all

https://jsfiddle.net/qmwdbxv5/2/

**Comment by SkyJedi** [comment]
https://jsfiddle.net/skyjedi/1k5rfxsg/

with the preload of all the base images

**Comment by asturur** [comment]
So you initialize at least 600 canvases. I wouldn't be surprised if the iphone / ipad errors out, apple restrict the memory a canvas can use in the browser.

**Comment by SkyJedi** [comment]
well, we have 50ish.  and it would be nice to have the error caught in the library instead of having to try/catch it in the code

**Comment by asturur** [comment]
clearRect is an operation on the context, we should try catch every context operation and that isn't doable.
The event for the context gone wild is available for webgl only.

https://jsfiddle.net/4aupygn3/4/

I m trying to simplify the fiddle to figure out if removing extra layers of canvas creations helps, but now i'm stuck with a 429 from heroku

**Comment by asturur** [comment]
Also take in consideration it could be the high number of filtered images creating too many textures in memory. Tomorrow i will try this reduced version on my iphone and see if it works or gets stuck

**Comment by asturur** [comment]
https://jsfiddle.net/4aupygn3/4/show

keep this here for reference
