### ISSUE TITLE
Fabricjs does not support rotation

### ISSUE THREAD

**Issue by LazyYed** [fabricjs/fabric.js#7196]
Integrating openseadragon, fabric JS does not support rotation, while openseadragon view can. I don't need to rotate all the objects, but the entire canvas rotates with openseadragon. Similar to the absolutepan method in fabric JS, you can set the translation. Is there a solution at present?

**Comment by asturur** [comment]
It depends if you need controls for objects.
If you don't we had a PR that was allowing for supporting a generic viewport transform that would also allow for rotating
