### ISSUE TITLE
Group size is not update correct when child Text object update fontSize

### ISSUE THREAD

**Issue by airarm** [fabricjs/fabric.js#7199]
Hi guys,

I create text object with fontSize 20 and add that to group.
After change text object fontSize (set 40) group size is not changed.
I try use method `_calcBounds` on group but that not help.
[See this screenshot](https://www.screencast.com/t/EwR6aEFF7QU)

What can you advise?

**Comment by ShaMan123** [comment]
try:
```js
group.addWithUpdate()
```

**Comment by asturur** [comment]
Adding an object to a group, and then change the size of that object is going to cause problems.
You have to ungroup and regroup, this will reset the bounding box

**Comment by i-prikot** [comment]
Can this approach be used https://github.com/fabricjs/fabric.js/discussions/7203 ?
