### ISSUE TITLE
Textbox control Underlined function resetting the color

### ISSUE THREAD

**Issue by umanda** [fabricjs/fabric.js#7202]
## Version
4.3.1

## Test Case

https://codepen.io/umanda/pen/qBmNBxM?editors=1111

## Information about environment
Nodejs or browser? Browser
Which browsers? Tested only Chrome and Firefox 

## Steps to reproduce

I have made a Codepen demo and please follow the URL below

https://codepen.io/umanda/pen/qBmNBxM?editors=1111

1. Change Color of full text ( Hello Fabric )
2. Select "Fabric" and click the Underline button to make "Fabric" underline
3. Selected text get underlined but colours get reset to black

## Expected Behavior

Once do the underline for selected text, colours shouldn't be reset

## Actual Behavior

![image](https://user-images.githubusercontent.com/368338/124886101-8ec01f00-dff1-11eb-9bc9-de7e7c3ce427.png)

**Comment by i-prikot** [comment]
Hi, @umanda.

Perhaps your problem is that your function does not distinguish where the styles, and where properties.

Try like this.

```
// Get the style
function getStyle(object, styleName) {
    return object.getSelectionStyles && object.isEditing
        ? object.getSelectionStyles()[styleName] || ""
        : object[styleName] || "";
}

// Set the style
function setStyle(object, styleName, value) {
    if (object.setSelectionStyles && object.isEditing) {
      var style = { };
      style[styleName] = value;
      object.setSelectionStyles(style);
    } else {
      object.set(styleName, value)
    }
  
    object.setCoords();
    canvas.requestRenderAll();
}
```

Example https://codepen.io/i-prikot/pen/rNmLaYo

**Comment by i-prikot** [comment]
I used the latest version 4.5.1
Can the problems in your version 4.3.1
