### ISSUE TITLE
help!! how to realize photo frame?

### ISSUE THREAD

**Issue by qq1241852688** [fabricjs/fabric.js#7204]
how to realize photo frame？how to realize photo frame？how to realize photo frame？
i want to use some photos to make the canvas photo frame,there is  no api, i don't konw how do it.use the new fabric Rect?or new fabric Image? canvas.add()?

**Comment by i-prikot** [comment]
See http://fabricjs.com/polaroid, http://fabricjs.com/clipping

**Comment by qq1241852688** [comment]
> 见http://fabricjs.com/polaroid， http://fabricjs.com/clipping

i want to make the canvas photo frame,can it do？

**Comment by i-prikot** [comment]
> > 见[http://fabricjs.com/polaroid，](http://fabricjs.com/polaroid%EF%BC%8C) http://fabricjs.com/clipping
> 
> i want to make the canvas photo frame,can it do？

You can do it.

**Comment by qq1241852688** [comment]
> > > 见[http://fabricjs.com/polaroid，](http://fabricjs.com/polaroid%EF%BC%8C) http://fabricjs.com/clipping
> > 
> > 
> > i want to make the canvas photo frame,can it do？
> 
> You can do it.

thanks,i need study it.

**Comment by asturur** [comment]
@qq1241852688 this is not how we handle issues. Please use the discussion section on the Q/A
