### ISSUE TITLE
Textbox: wrapping text with different font sizes works wrong

### ISSUE THREAD

**Issue by KateOrient** [fabricjs/fabric.js#7207]
## Version
4.5.1

## Test Case
http://jsfiddle.net/orientks/4795eqkr/61/

## Information about environment
Chrome browser

## Steps to reproduce
Select first long word in the Textbox and clock 'Set font size' button.

## Expected Behavior
Textbox wrap text according to the char width when text contains parts with different font sizes.

## Actual Behavior
Text doesn't fit the textbox size and goes out of bounds. 
![image](https://user-images.githubusercontent.com/31737885/124954580-e88b0e00-e01e-11eb-87e1-49e6d785a632.png)

Also something strange happens after resizing this textbox multiple times.
![image](https://user-images.githubusercontent.com/31737885/124954728-12443500-e01f-11eb-8efa-901a3ec40657.png)

**Comment by asturur** [comment]
ok this is weird.
I thought those kind of issues were gone for good.

**Comment by KateOrient** [comment]
Any news on this one?

**Comment by asturur** [comment]
no from me. I m very busy last 2 months at least.

**Comment by asturur** [comment]
The bug seems to be realted to splitByGrapheme, that makes investigation at least simpler.

**Comment by warsngl** [comment]
Font size change like this 
canvas.getActiveObject().set({fontSize: 36});

**Comment by KateOrient** [comment]
@warsngl the method you mentioned is used to set the font size for the whole Textbox. This issue occurs when font size for different parts of text is different.  And _setSelectionStyles_ is the way to set style for the selected part of text in the Textbox

**Comment by TijanaMarj** [comment]
Any movement here? I have the same issue, but its not triggered by changing of font size. Some characters stay on canvas even after removing them.  Can someone help??
![Screenshot 2024-08-21 143430](https://github.com/user-attachments/assets/3e4c678a-1c5d-48e6-99e1-675a8054fd6c)

**Comment by asturur** [comment]
Are you able to replicate the issue with simple code so that it can be checked?

**Comment by asturur** [comment]
Yes most of the time is just that, especially in safari that needs extra handling after loading.
