### ISSUE TITLE
Reviver function for loadFromJSON

### ISSUE THREAD

**Issue by ghost** [fabricjs/fabric.js#722]

**Comment by snq** [comment]
This doesn't seem to work for a json that has multiple images on it. It doesn't wait for images to load onto the canvas

**Comment by sudiptokush** [comment]
In my case the reviver function is getting called multiple times for the same object. Can anyone please point the reason?

temporaryCanvas.loadFromJSON(json, async () => {
  // logic here
  canvas.renderAll();
  canvas.onHistory();
}, (o: unknown, object: fabric.Object) => {
  console.log(o); // Each object getting printed twice hence had to check before pushing 
  if(allObjects.indexOf(object) === -1) allObjects.push(object);
});

JSON Structure
![image](https://github.com/fabricjs/fabric.js/assets/6592374/ddd5ecb5-b018-414f-9adf-7171358ccb37)


Output of the reviver console.log
![image](https://github.com/fabricjs/fabric.js/assets/6592374/bb7f880a-8231-475d-8814-9cf90991444f)

Note- If I load another image using loadFromJSON the reviver it gets called 4 times per object then 8 times and so on
