### ISSUE TITLE
When I copy an object through Cloe, the object's scale loses precision

### ISSUE THREAD

**Issue by Ezr1al** [fabricjs/fabric.js#7229]
## Version
4.4
## Test Case
```
   let target = canvas.getActiveObject(); //the target object ScaleX =0.23124789412, ScaleY =0.23124789412
   target.clone(cloned => {
        this.clipboard = cloned; //the cloned  object ScaleX =0.2, ScaleY =0.2
     }) 
```

## Information about environment
chrome

## Steps to reproduce
I cloned an object by selecting the target object. The cloned object name is cloned.the target object ScaleX =0.23124789412, ScaleY =0.23124789412
## Expected Behavior
the cloned  object ScaleX =0.23124789412, ScaleY =0.23124789412
## Actual Behavior
the cloned  object ScaleX =0.2, ScaleY =0.2

**Comment by i-prikot** [comment]
Hi.

See what is specified in the `NUM_FRACTION_DIGITS` property of the object. This is property defines the number of fraction digits to use when serializing object values. You can use it to increase/decrease precision of such values like left, top, scaleX, scaleY, etc. When you call the `clone` (`toObject()`, `fromObject()`) method, the object's values are serialized / deserialized.

**Comment by asturur** [comment]
correct! If you need to work with high precision, please consider using it set as 8 or 10 or more.
2 is a conservative value to do not have unnecessary big objects export on JSON.
I see how this is edgy and maybe clone should skip that parameter.

**Comment by i-prikot** [comment]
Try like this `fabric.Object.NUM_FRACTION_DIGITS = 16`

**Comment by asturur** [comment]
Yes is like a static property is not on the prototype

**Comment by Ezr1al** [comment]
yes，It's a static property. Thank you. I set it wrong.
