### ISSUE TITLE
Why use two canvas to handle interaction and drawing ?

### ISSUE THREAD

**Issue by surprisingwu** [fabricjs/fabric.js#7234]
## Version
3.6.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Nodejs or browser?
Which browsers?

**Comment by melchiar** [comment]
@surprisingwu I'm going to close this issue for now since this is not a bug report. Feel free to post a question in the discussion section if you'd like to discuss a specific topic.
