### ISSUE TITLE
Textbox inserChars with style are not working

### ISSUE THREAD

**Issue by xorb** [fabricjs/fabric.js#7253]
## Description

Textbox inserChars with style are not working. It works using styles = null `textbox.insertChars("Super ",null, 0,0  );`
	

## Version
4.5.1

## Test Case
https://jsfiddle.net/xorbmoon/j094xn6L/9/

## Information about environment
Nodejs or browser? 
-- Browser

Which browsers?
-- All

## Steps to reproduce
1. Start in editing mode and exit from it

## Expected Behavior
-- Styles should be applied

## Actual Behavior
-- No changes (text nor styles)

**Comment by i-prikot** [comment]
Hi.

if style array is provided, it must be as the same length of text in graphemes.
http://fabricjs.com/docs/fabric.Textbox.html#insertChars

https://jsfiddle.net/i_prikot/L5o9hzpf/

**Comment by xorb** [comment]
Closing issue since it is a regular behavior when requirements are not satisfied.
