### ISSUE TITLE
Move Text object. but clickable area was did not move.

### ISSUE THREAD

**Issue by nomoto-neo** [fabricjs/fabric.js#7260]
obj.hasControls = false;
And move Text object. but clickable area was did not move.

Using setControlsVisibility instead of hasControls does not reproduce the problem.
//obj.setControlsVisibility({ tl: false, tr: false, br: false, bl: false, ml: false, mt: false, mr: false, mb: false, mtr: false});

## Version
4.5.0

## Test Case
https://codepen.io/nomoto-neo/pen/NWjYaNp

![rapture_20210730113307](https://user-images.githubusercontent.com/32568169/127591735-b419e341-f3a4-47e7-b780-f299cc2007cf.png)

**Comment by i-prikot** [comment]
Hi.

http://fabricjs.com/fabric-gotchas
After `obj.set({ top: 50 });` call `obj.setCoords();`

**Comment by nomoto-neo** [comment]
Oh! This is most populer gotcha, Thank you.
