### ISSUE TITLE
Bug when selecting multiple objects? (incorrect object data)

### ISSUE THREAD

**Issue by naomei** [fabricjs/fabric.js#7270]
Faced with some strange behavior.

```
1. Place two or more objects
2. Select multiple of them and move them
```

### ~~Some events do not fire~~

~~Events such as `object:moving` and `object:modified` do not fire even if moved.
Is this a bug? Is it correct?~~

I'm sorry, this seems to work correctly

### Object information is incorrect

Some of the information you can get with `getObjects` has strange values.
Especially `left` `top` etc.
Obviously a positive value should be returned, but a negative value is returned.

**Comment by melchiar** [comment]
Hi. Is this 2 separate issues? Without seeing your code we can't really help. Please add a clear minimal codepen or jsfiddle reproducing the problem as indicated in the issue template.

**Comment by naomei** [comment]
@melchiar 

> Some events do not fire

I'm sorry, I just tried it, this seems to work correctly. Ignore it.

> Object information is incorrect

It is a reproduction on code-sandbox.

https://codesandbox.io/s/fabric-js-multi-selection-3upw8

1. select two objects
2. and, moving
3. see "console"

I don't think it's what expected data.

**Comment by melchiar** [comment]
Can you be more specific? How exactly is the result different than what you're expecting?

**Comment by naomei** [comment]
@melchiar 

> Can you be more specific

In the sample, two objects are initially placed.(line: 28)

```
object1(fill: red) : {left: 0, top: 0}
object2(fill: green): {left: 100, top: 0}
```

And, **select all objects(red+green)**, move to the right in the horizontal direction.
Since we moved it to the right, the expected value is left + amount(`left: 100 + α`).
However, the actual value will be an unexpected value, such as `left: 0.5, top: -0.5`.
(In addition, `object1(fill: red)` can get mysterious negative values such as `left: -101.5, top: -100.5`.)

Again, this is the case for "multiple selections".
(There is no problem with the data when single selection.)

**Comment by naomei** [comment]
As an additional note, This is a capture.

![スクリーンショット 2021-08-04 16 08 09](https://user-images.githubusercontent.com/32318534/128137251-270d9ab9-45cc-4b0d-b67c-5896f36720ef.png)

**Comment by melchiar** [comment]
This should help with understanding the group coordinate system. 

https://github.com/fabricjs/fabric.js/issues/4206

**Comment by naomei** [comment]
thank you help!
I will read it from now on.
