### ISSUE TITLE
Bounding area is not update in Textbox like iText

### ISSUE THREAD

**Issue by umanda** [fabricjs/fabric.js#7276]
## Version
4.5.1

## Test Case

https://codepen.io/umanda/pen/qBmyKvJ

## Information about environment
Nodejs or browser? Browser
Which browsers? Tested only Chrome and Firefox 

## Steps to reproduce

I have made a Codepen demo and please follow the URL below

https://codepen.io/umanda/pen/qBmyKvJ

## Expected Behavior

When removing or deleted text from the text box using the backspace key, its is original width not update. However, I checked with the iText object which is working perfectly. ( I can not use iText but I have to use TextBox)

## Actual Behavior

When removing or deleted text from the text box using the backspace key Textbox width should be updated, like iText.

![image](https://user-images.githubusercontent.com/368338/128326124-ef3da80e-da8e-4a4e-ae12-2a956ca206a6.png)

![image](https://user-images.githubusercontent.com/368338/128326392-2d27ef9c-e1ef-4a70-973f-674d229c94f5.png)

![image](https://user-images.githubusercontent.com/368338/128326561-80a02f2d-73b7-47ab-965f-bb5a9e4bbf0d.png)

**Comment by asturur** [comment]
Yes this is how textbox works.
The user is supposed to set the textbox width as large has he/she wants.
Probably you can mimic the behaviour.

You can look at all the `textbox.__lineWidths[lineIndex]` and check which is the biggest.
Then set the textbox to that size.
You can do that on certain text events, like end of editing.

**Comment by umanda** [comment]
@asturur Great thank you for your hint.

I tried with your suggestion however When the textbox size is increased or if I hit enter ( next line ) entire object get vanished. What would be the issue or mistake I am doing here 

https://codepen.io/umanda/pen/xxdQmyv

**Comment by umanda** [comment]
@asturur Great thank you for your hint.

I tried with your suggestion however When I edit I get **undefined** for width and it will sometimes not working as expected. What would be the issue or mistake I am doing here

https://codepen.io/umanda/pen/xxdQmyv
