### ISSUE TITLE
Fabric.js Eraser not working properly if canvas is zoom in or zoom out

### ISSUE THREAD

**Issue by iamibrahimkholil** [fabricjs/fabric.js#7277]
## Version
4.5.1

## Test Case
https://codesandbox.io/s/sparkling-dew-2e038

## Information about environment
Although I am using it in NextJS application. I made the test case in Vanilla JS
Which browsers?
Chrome, Firefox etc.

## Steps to reproduce
First, draw something on the board then zoom in a lot then try to Erase. 
## Expected Behavior
It Should erase the drawing.

https://user-images.githubusercontent.com/79884206/128333869-cf06abde-3bb5-4286-82f2-83f34df51d32.mp4

## Actual Behavior
it won't work. It mostly happening while I am trying to eraser around the corner of the drawing. It is also happening if I zoom out the canvas a lot.

**Comment by ShaMan123** [comment]
This error is related to `intersectsWithObject`
https://github.com/fabricjs/fabric.js/blob/master/src/mixins/eraser_brush.mixin.js#L940

**Comment by ShaMan123** [comment]
seems to fix:
https://codesandbox.io/s/keen-bohr-eji1l?file=/src/index.js
