### ISSUE TITLE
Background color doesn't scale when zoom out on fabric build with eraser

### ISSUE THREAD

**Issue by alperen** [fabricjs/fabric.js#7278]
## Version
4.1.0 (Erasing enabled)

## Test Case
[https://codesandbox.io/s/pedantic-leaf-7kvkh](https://codesandbox.io/s/pedantic-leaf-7kvkh)

## Information about the environment
All major browsers with the latest versions

## Steps to reproduce
- Click to "Draw" button
- Draw something into the canvas
- Click to "Erase" button
- Erase some part of that you drawed (bug isn't based on your drawed)
- Click to "Zoom Out" button
- Click to "Export" button

Exported image (it opens in a new tab) has no background color over the image, on the standard builds of the fabric, the background color is spreading over the exported image. I spread the background color by setting `backgroundVpt: false` over the canvas but it doesn't affect exporting.

You can see the difference between the standard build and with the eraser build by changing `index.html:25` to 

```html
<script
      id="fabric-build"
      src="src/fabric-builds/standart-build.js"
    ></script>
```

## Expected Behavior
Background color spread over the export image, for example:

![image](https://user-images.githubusercontent.com/3244438/128335160-9a251424-ac82-4944-8af5-cdc7435758d2.png)

## Actual Behavior
Background color doesn't spread over the exported image, it doesn't scale when the zoom out on the exported image.

![image](https://user-images.githubusercontent.com/3244438/128335253-499dab16-c6bc-443f-bff0-807516150f99.png)

**Comment by asturur** [comment]
The eraser brush uses a rect to emulate a color, that is an hack.
@ShaMan123  why someone would want the background color to be erasable?
Why the developer shouldn't use an object as background if erasing is needed, and decide on his own how large this background is?

**Comment by alperen** [comment]
Here is additional information, once you'll comment out line 32 to 34, it will erase the background color, makes it transparent

**Comment by ShaMan123** [comment]
@asturur It is definitely a hack, explained here http://fabricjs.com/erasing.
So if I understand you, you vote for removing the ability to erase bg/overlay color?
This can be fixed for sure but there are more pit falls such as #7220.

**Comment by ShaMan123** [comment]
I think someone would want to erase the background color in case they want to reveal something underneath. But it is in the scope of adding an object.

**Comment by alperen** [comment]
I forked the sandbox with the new build which includes #7289, it seems the pr fixed by problem well. You can check out it from: https://codesandbox.io/s/aged-resonance-doied

Also, I removed backgroundVpt property, with this version it became more backward compatible.

We can close that issue but first, imo, I'd like to wait for the new version. When it is going to be upgraded?

**Comment by asturur** [comment]
There are a lot of fixes in, and some new small feature. We can publish 4.6.0 today or tomorrow

**Comment by alperen** [comment]
fixed, thanks.
