### ISSUE TITLE
Object Width/Height are not updated in event object (while top/left are)

### ISSUE THREAD

**Issue by abusedmedia** [fabricjs/fabric.js#7282]
## Version
4.5.1

## Test Case
https://codepen.io/abusedmedia/pen/RwVqGZa

## Information about environment
Chrome

## Steps to reproduce
Create an object (Rect, Triangle, etc), listen for updates with 'object:moving', 'object:scaling' events, the width/height props in event object are not updated after a user interaction while top/left are correctly set.

## Expected Behavior
Width/height properties in event object should reflect the current object dimension values.

## Actual Behavior
Width/Height properties in event object are not updated after changes from the user.

**Comment by melchiar** [comment]
Hi. Scaling an object with controls updates the object's scaleX/scaleY values, not the width/height values. If you want to get an object's actual scaled width or height there are these helper methods you can use.

obj.getScaledWidth()
obj.getScaledHeight()

**Comment by abusedmedia** [comment]
Hi @melchiar,

thanks for the heads-up.

I'm having another issues and I'm woldering if there's something similar to get the right coordinates.
Object top/left props are correctly updated during controls update.
But when the user makes a group selection to move/scale, the group element has the right coordinates but the inner objects contains weird top/left values.

I've tried different workarounds to get the object coordinate during a group selection without success.

Any tips?
Thanks!

**Comment by melchiar** [comment]
This should help with understanding the group coordinate system.

#4206

**Comment by abusedmedia** [comment]
Thank you again!! 
I'm going to close this issue.

**Comment by loveRandy** [comment]
this problem is not resolved and make me crazy.How can i get the inner klass's correct left\top when i use Object:moving and select goup ?

**Comment by loveRandy** [comment]
@melchiar 

> This should help with understanding the group coordinate system.
> 
> #4206

i'm sorry.you alway say issue #4206 can help us to  understanding the group coordinate system,but it didn't help us to get the inner klass's correct left\top

**Comment by asturur** [comment]
i think we have in the work direct method to access the top and left properties you are looking for, but in general, you have to multiply the object top and left as a point, by the matrix of the group.

```
var point = new fabric.Point(obj.left, obj.top);
var newPoint = fabric.util.transformPoint(point, obj.group.calcTransformMatrix());
```
Now i typed this without double checking the correctness of the methods,  but apart a spelling mistakes, that's it.
