### ISSUE TITLE
loadSVGFromString svgString parse textContent space error

### ISSUE THREAD

**Issue by KayShi** [fabricjs/fabric.js#7283]
## Describe the bug
When I used fabric to parse SVG, I encountered some unexpected problems.
When there are multiple spaces in SVG text, multiple spaces are treated as one space.

Through the analysis of the source code, I found a strange processing logic here.
in /dist/fabric.js
`textContent = textContent.replace(/^\s+|\s+$|\n+/g, '').replace(/\s+/g, ' ');`

I don't quite understand why we should filter multiple spaces into one, which seems to directly affect the original SVG expression

Is this a bug? I sincerely look forward to your answer

**Comment by asturur** [comment]
I think we remove the text spans and that is the issue with positioning.
I do not think more than one space is represented at all in SVG.
Do you have an example SVG that is failing?

**Comment by asturur** [comment]
reference #1280

**Comment by KayShi** [comment]
In our scenario, an SVG description is obtained according to the user's input, and we generate a picture according to the user's SVG description
Effect of multi space svg：
![foo](https://user-images.githubusercontent.com/7475350/128670550-5163df02-e5c5-4a3b-bcff-4c93218302c7.png)
Actual effect after fabricjs parsing：
![foo3](https://user-images.githubusercontent.com/7475350/128670633-f3c8eeac-f202-4688-9098-62b8d9fa7378.png)
This is my svgString：
`<svg xmlns="http://www.w3.org/2000/svg" version="1.1" xml:space="preserve" width="661" height="93.45100000000001">
<text xml:space="preserve" x="0" y="82" fill="#421904" font-size="82" letter-spacing="21" font-weight="400">元送      元</text>
        </svg>`
At present, we have achieved the effect through hack NPM package. Will you consider dealing with it？

**Comment by KayShi** [comment]
The input box of GitHub also filters multiple blanks in the middle of the text. You can try adding a few more spaces in the middle of the local SVG text to see the results
