### ISSUE TITLE
Moving focus away from canvas while painting with left-click causes 'stuck' painting state

### ISSUE THREAD

**Issue by glangstonb** [fabricjs/fabric.js#7292]
## Version

4.4.0

## Test Case

http://jsfiddle.net/epfhw2az/1/

This bug also repros easily in the free drawing demo:

http://fabricjs.com/freedrawing

## Information about environment

This shows up in Chrome (version 92.0.4515.131) and Edge, running on Windows 10. I have not tested in Firefox or on any other operating system.

## Steps to reproduce

Initiate a FabricJS canvas and PencilBrush so that you can paint on the canvas. Press and hold the left mouse button on the canvas to start drawing. While the left button remains pressed, do any of the following:

- Click the right mouse button (you should see a context menu appear); release the left button; left-click on the window title bar (or any other focusable UI element outside the canvas, presumably).
- (On Windows) press Windows+D to minimize the browser window; release the left button; maximize the browser window again.
- Press Alt+Tab to move focus to a different window; release the left button; return to the browser window.

Now move the pointer back over the canvas and observe the incorrect behavior.

## Expected Behavior

Presumably, the painting should stop when the left mouse button is released, and the stroke already created should be saved onto the canvas.

## Actual Behavior

The brush continues to paint despite no mouse buttons being pressed. Left-clicking on the canvas at this stage causes the entire stroke to disappear, and a single dot is painted at the final pointer position.

**Comment by Tennyleaz** [comment]
Any solution to this issue? Having same problem in the latest demo also.
