### ISSUE TITLE
fabricjs custom subclass disappear when zoom in

### ISSUE THREAD

**Issue by keelii** [fabricjs/fabric.js#7296]
## Version
3.6.0

## Test Case
https://jsfiddle.net/ko7sfqmd/

## Steps to reproduce

![1](https://user-images.githubusercontent.com/458894/129339601-5dc3a38a-1a06-4e2c-abce-96f05518a01a.gif)

**Comment by asturur** [comment]
Hi @keelii in the fiddle i cna't see anything

**Comment by keelii** [comment]
@asturur How about this one: https://jsfiddle.net/8hg0b47t/

**Comment by asturur** [comment]
Your subclass is incomplete, it does not have width and height at all, those are required.

https://jsfiddle.net/0L1z8u2m/2/

**Comment by asturur** [comment]
It disappear because the width/height is 0, so the object is really small.
As soon as you zoom the first time the object goes out of screen and fabric stops rendering it.
If fabric knows how much the object is big, it can handle it
