### ISSUE TITLE
Inconsistent text position in Chrome vs Firefox

### ISSUE THREAD

**Issue by shulhi** [fabricjs/fabric.js#7303]
## Version
4.5.1

## Test Case
https://app.usestencil.com/viewer/ee08ac4d-aba4-4695-afa4-d5dae2a64e20/sync/SFMyNTY.g2gDbQAAACw0U0g0c056R2duQldRaWFSdEs3czdGaFM5VjgydXBVUnB2OUJLYzdjWDZpTG4GAAaXoEl7AWIAAVGA.xMrB1P-_FD1NzrDGscqUnguAIHjpoiT82zXrqMs74OE

I made a simple test case here,

https://jsfiddle.net/8wnopav6/1/

## Information about environment
Nodejs or browser? Browser
Which browsers? Chrome and Firefox

## Steps to reproduce
Open the link in both Chrome and Firefox

## Expected Behavior
Expected the text to be in similar position

![image](https://user-images.githubusercontent.com/913103/129520770-b49a2ef6-2687-41e6-9082-e6a0e4c49111.png)

## Actual Behavior
Textbox moved to the right in Firefox by significant margin

![image](https://user-images.githubusercontent.com/913103/129520722-6d1786ab-1a86-4c3f-9108-fd6b50d56403.png)

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/129554508-c568420f-a261-4486-8df4-15aaf7b7e581.png)
this is what i see in the fiddle.

**Comment by shulhi** [comment]
> ![image](https://user-images.githubusercontent.com/1194048/129554508-c568420f-a261-4486-8df4-15aaf7b7e581.png)
> this is what i see in the fiddle.

One in firefox and one in chrome?

![image](https://user-images.githubusercontent.com/913103/129555023-1a6ba46a-642d-4aa6-a439-c0266bf6dc21.png)

This is what I'm seeing. Left is chrome, right is Firefox. What OS are you using?

**Comment by asturur** [comment]
i'm on macos, firefox + brave ( that is chromium/chrome )

**Comment by asturur** [comment]
Is verdana font an universally available font? if not you have to load it before painting the canvas

**Comment by shulhi** [comment]
> Is verdana font an universally available font? if not you have to load it before painting the canvas

I thought it is a web safe font. I'm not actually using Verdana in my production. I was loading google fonts in my actual app and trying to reproduce the issue.

**Comment by shulhi** [comment]
![image](https://user-images.githubusercontent.com/913103/129557415-2062a132-f253-4fe1-9f28-c0f7879b9cd2.png)

I think it just have to do with how kerning differences in Chrome vs Firefox? Do you know how can I standardize this behavior? @asturur 

I sort of figure out what is the issue right now, the fonts are loading right but I have the text centered aligned and because of the differences in kerning (I think), the position is off.

**Comment by asturur** [comment]
Sorry i don't have any solution for this.
I m not sure how much the differences are, maybe you could set a kerning of 1 ( charSpacing property ) and while slower it could be that each char gets positioned correctly across browsers.

**Comment by shulhi** [comment]
> Sorry i don't have any solution for this.
> I m not sure how much the differences are, maybe you could set a kerning of 1 ( charSpacing property ) and while slower it could be that each char gets positioned correctly across browsers.

No worries and there's no need to apologize. This is a really great project and you've done a really good job maintaining it.

I will definitely try that. Thank you!
