### ISSUE TITLE
Inconsistency between render result and toDataURL() result

### ISSUE THREAD

**Issue by wjx008** [fabricjs/fabric.js#7308]
## Version
4.5.0

## Test Case
https://jsfiddle.net/2w5n67eb/16/

## Information about environment
browser
Chrome
13' M1 Mac (devicePixelRatio: 2)

## Steps to reproduce
The code is in the above jsfiddle
The main issue is the output of `toDataURL()` differs from what is rendered in the browser

## Expected Behavior
The result of `toDataURL()` matches what is rendered in the browser

## Actual Behavior
The dimension and size and fontsize are the same for the result of `toDataURL()` and what's rendered in the browser, but the text is noticably blurry in the base64 returnde by `toDataURL()`

Left is what's being rendered in the browser, right is the result of `toDataURL()`
![image](https://user-images.githubusercontent.com/17431742/129661436-76ec6612-ab7c-4b20-b201-897f1cf0144a.png)

Edit 1: I guess it's better to describe my hypothesis on what's causing the issue. When enableRetinaScaling is enabled, the canvas size is `size * devicePixelRatio` but because the css size is the actual `size`, so it renders fine on screen. But when `toDataURL()` is used, in order to output an image of same size as canvas actual size (css size), canvas didn't zoom out the good picture instead it somehow rerender it with smaller size but since it's hidpi device, the result is blurry.

**Comment by asturur** [comment]
What you can do is add the multiplier:
https://jsfiddle.net/Lsm6brvn/
Also disabling caching should help with fuzzyness anyway on exports
