### ISSUE TITLE
i-text object, when the text is styled, save the json, load it through loadFromJSON, and report an error

### ISSUE THREAD

**Issue by pushuo** [fabricjs/fabric.js#7311]
## Version
4.5.1

## Test Case
https://jsfiddle.net/pushuo/k4btv5do/48/

## Information about environment
Below is a screenshot of the error message。 
![image](https://user-images.githubusercontent.com/21018378/129885133-1cf1dea8-c8b4-4b2e-ba0f-241287a6c054.png)

#### Use this json data to load the canvas through loadFromJSON and report an error
`var json = {"version":"4.5.1","objects":[{"type":"i-text","version":"4.5.1","originX":"left","originY":"top","left":192.058631922,"top":53.700306134,"width":390,"height":336.1072,"fill":"#333","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeDashOffset":0,"strokeLineJoin":"miter","strokeUniform":false,"strokeMiterLimit":4,"scaleX":0.652649037,"scaleY":0.652649037,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","skewX":0,"skewY":0,"text":"发似懂非懂师傅\n个电饭\n锅\n\nhfgh h\n换个饭还好风九分裤大叔链接付款\n光好风光\n\n\n","fontSize":26,"fontWeight":"normal","fontFamily":"有字库龙藏体","fontStyle":"normal","lineHeight":1.16,"underline":false,"overline":false,"linethrough":false,"textAlign":"left","textBackgroundColor":"","charSpacing":0,"path":null,"direction":"ltr","evented":true,"styles":[[{"fill":"#280D0D"},{"fill":"#280D0D"},{"fill":"#280D0D"},{"fill":"#280D0D"},{"fill":"#280D0D"},{"fill":"#280D0D"},{"fill":"#280D0D"}],[{"fill":"#4B2020"},{"fill":"#4B2020"},{"fill":"#4B2020"},{"fill":"#4B2020"}],[{"fill":"#4B2020"},{"fill":"#4B2020"}],[{"fill":"#4B2020"}],{"6":{"fill":"#0E0606"}},[{"fill":"#0E0606"},{"fill":"#0E0606"},{"fill":"#0E0606"},{"fill":"#0E0606"},{"fill":"#0E0606"},{"fill":"#0E0606"},{"fill":"#0E0606"},{"fill":"#0E0606"},{"fill":"#0E0606"},{"fill":"#0E0606"},{"fill":"#0E0606"},{"fill":"#0E0606"},{"fill":"#0C5263"},{"fill":"#0C5263"},{"fill":"#0C5263"},null,null,null,null,null,null,null,null],[{"fill":"#0C5263"}]]}],"background":"#fff"};`

## Expected Behavior
Normal home

## Actual Behavior

Cannot load the canvas,

**Comment by pushuo** [comment]
@asturur  Please take a look, this question is very urgent, thank you very much

**Comment by i-prikot** [comment]
Hi.

How did you achieve this weird `styles` structure?

**Comment by pushuo** [comment]
> Hi.
> 
> How did you achieve this weird `styles` structure?

Hi
I selected different texts in a text box to set the color, and then enter and wrap the text in the middle of the text, and there are operations such as spaces. This BUG must exist.
The important point is that there was no error reported during the operation, but when I converted the data to json through canvas.toJSON and saved it, and then reloaded it through loadFromJSON, there was a problem.

**Comment by pushuo** [comment]
> Hi.
> 
> How did you achieve this weird `styles` structure?

I tested it again, and the styles of the picture below are the data exported through canvas.toJSON.
I selected part of the text in the middle of the fourth line and set the color, and then used carriage return to wrap the line in the middle, and canvas.toJSON came out and that’s it.

![image](https://user-images.githubusercontent.com/21018378/130006158-2f1f249e-2ff4-4b7f-a6e0-f0dedb9717ff.png)


Then reload the page, load the data just saved through loadFromJSON, an error is reported, the screenshot below is wrong

![image](https://user-images.githubusercontent.com/21018378/130006492-c691be84-0422-4606-a9b7-6132d1f6423a.png)

**Comment by i-prikot** [comment]
It seems that the case in the properties with a value of null. In the source code is not checking for the existence of the object or type.

```
function parseDecoration(object) {
    if (object.textDecoration) {
      object.textDecoration.indexOf('underline') > -1 && (object.underline = true);
      object.textDecoration.indexOf('line-through') > -1 && (object.linethrough = true);
      object.textDecoration.indexOf('overline') > -1 && (object.overline = true);
      delete object.textDecoration;
    }
  }
```

It looks like a bug.

**Comment by i-prikot** [comment]
I was unable to reproduce your error.  https://jsfiddle.net/i_prikot/fp4gLeks/

**Comment by pushuo** [comment]
> I was unable to reproduce your error. https://jsfiddle.net/i_prikot/fp4gLeks/
> 
> Maybe if you show the code that is executed before exporting to json, then I will get a better understanding of the problem.


Hello.
This error can only be reproduced after the json is exported and loaded.
I recorded a GIF image of an operation that may make mistakes. It is probably that different texts are selected to set different colors, and there are blank lines in the middle. . .

![Kapture 2021-08-19 at 14 56 17](https://user-images.githubusercontent.com/21018378/130022507-0b0f498c-220d-4552-9f30-6c49435274ca.gif)

**Comment by i-prikot** [comment]
![image](https://user-images.githubusercontent.com/21138391/130038764-b4936296-5988-4ca1-bc99-ba21de8f445c.png)

As much as I tried, but could not get the styles with a null.

**Comment by pushuo** [comment]
> ![image](https://user-images.githubusercontent.com/21138391/130038764-b4936296-5988-4ca1-bc99-ba21de8f445c.png)
> 
> As much as I tried, but could not get the styles with a null.

To try some more formats, you can follow my picture.
You can set a lot of text in a certain line, and then select the color in the latter part, and then press Enter in the middle of the latter part to the next line, etc.

![image](https://user-images.githubusercontent.com/21018378/130041453-7c8b5af3-de3a-4762-be83-50c6b2efc2ef.png)

**Comment by i-prikot** [comment]
I tried different options, including yours. Have you tried to reproduce the error yourself at https://jsfiddle.net/i_prikot/fp4gLeks/?

**Comment by pushuo** [comment]
> I tried different options, including yours. Have you tried to reproduce the error yourself at https://jsfiddle.net/i_prikot/fp4gLeks/?

Thank you very much. After entering my inspection and testing for a few days, I found that the problem lies with us.
When we save the data to the back-end database, php will convert the styles object type to an array type. When the styles is loaded for the second time, it becomes an array. Then there is a problem during editing, which has nothing to do with the fabric.
