### ISSUE TITLE
Canvas has problems when use "perPixelTargetFind = true" with fabric.Image.fromURL

### ISSUE THREAD

**Issue by blucobalto** [fabricjs/fabric.js#7322]
Hi,
Canvas has problems when use "perPixelTargetFind = true" with fabric.Image.fromURL.

Best regards,
Blu

## Version
4.5.1

## Test Case
http://jsfiddle.net/hvqntupe/1/

## Information about environment
Nodejs or browser? Browser
Which browsers? Firefox / Chrome / Edge

## Steps to reproduce
Run fiddle with "perPixelTargetFind = true". This code has problems .
Run fiddle with "perPixelTargetFind = false". Ok.

## Expected Behavior
Canvas works fine 

## Actual Behavior
Canvas has problems

**Comment by i-prikot** [comment]
![image](https://user-images.githubusercontent.com/21138391/130387220-ae435b00-6769-4f6e-a40a-08fe0a57dda3.png)

The problem is in crossOrigin. Try to do like this.

```
const img = new Image();
img.crossOrigin = "Anonymous";
img.onload = () => {
	const fabricImage = new fabric.Image(img);
	canvas.add(fabricImage);
}
img.src = 'http://fabricjs.com/assets/pug_small.jpg'
```

**Comment by blucobalto** [comment]
Hi i-prikot,
you're right, your code solves the problem.

Thanks a lot,
Blu
