### ISSUE TITLE
Disable triggering object:added for one type of shape

### ISSUE THREAD

**Issue by amirking59** [fabricjs/fabric.js#7323]
i want to add just lines without triggering object:added. 
but other things should work normal.

my problem: 
i use fabric history. and i want to create a feature that when user move object to middle of canvas, it should snap to middle then show some dotted lines like photoshop and ... . 
but adding these lines will trigger object:added so fabric history detect it as added element and fabric history will not work correctly.

is there any way to disable this event only for Line?

**Comment by i-prikot** [comment]
Hi.

I understand correctly that you are using `fabric.Line` for the guides? I think it's better to use native line drawing. There is an after: render event that conveys the context of the canvas. See how it is done in the example https://github.com/fabricjs/fabric.js/blob/master/lib/aligning_guidelines.js

**Comment by asturur** [comment]
You can't disable the event from firing, but you can:
- make the event handler return early if the target is a specific line
- do not add lines on the canvas but just draw them like we do in the align guidelines plugin in the repo
