### ISSUE TITLE
Cannot change the text color in the TexBox object

### ISSUE THREAD

**Issue by Ezr1al** [fabricjs/fabric.js#7324]
## Version
4.3.1
## Information about environment
chrome
## Steps to reproduce
  I've created a TextBox object, and I've written text inside it, and WE'll call it TextBox1.I copied the text from Texbox1 and pasted it into another newly created Texbox object. This new texbox object cannot change the color of the text that I copied.You can change the color if you use the keyboard to write text inside the new Textbox.
## Expected Behavior
  You can change the color by pasting text copied from the TexBox object into the new Texbox object
## Actual Behavior
Cannot change the color

## example
Change the color of the text in the Texbox object. The color cannot be changed when copied from other Texboxes. You can change the color by typing new text
![image](https://user-images.githubusercontent.com/36941749/130414585-11c177c5-529d-4edd-8344-6aba9efa2b98.png)

**Comment by melchiar** [comment]
Copy/Pasting text from one textbox to another uses the `styles` property to apply a style override to that specific text. You can disable this behavior if you want.

`fabric.disableStyleCopyPaste = true;`

http://fabricjs.com/docs/fabric.html#.disableStyleCopyPaste
