### ISSUE TITLE
Path Distance Measurement Inconsistency

### ISSUE THREAD

**Issue by melchiar** [fabricjs/fabric.js#7327]
## Version
4.5.1

## Test Case
https://jsfiddle.net/melchiar/br06s23p/

## Information about environment
Browser

## Description

It looks like the path distance calculation for the text on path code can be a bit inconsistent at times when measuring curves. This results in uneven text kerning in some cases. 

Note how the distance between some dots can jump a bit near the tops and sides of curves when adjusting the pathStartOffset. Maybe something to do with the path simplification?

![path-distance-wiggle](https://user-images.githubusercontent.com/9057412/130657249-599a6d2a-5e92-4d50-bd71-ff7f45fcfce6.gif)

**Comment by melchiar** [comment]
It looks like the jumps occur at the connection point between two curves. Since we're simplifying arcs and quadratic arcs into bezier curves, an arc ellipse like this:

`M 50 0 a 50 100 0 1 1 1 0 Z`

Gets converted into an ellipse composed of 4 bezier curves, with joints at the middle of each edge.

`M 50 0 C 22.48472060094895 -0.5503331053242485 0.3630400233350102 -45.46238353072359 0.5006250195322721 -100.49500612526722 C 0.6382100157295341 -155.52762871981085 22.9833447337881 -199.99499987499377 50.5 -199.99499987499377 C 78.0166552662119 -199.99499987499377 100.36178998427046 -155.52762871981088 100.49937498046773 -100.49500612526725 C 100.636959976665 -45.46238353072362 78.51527939905108 -0.5503331053242809 51.00000000000004 0`

![image](https://user-images.githubusercontent.com/9057412/130662606-f385f89c-7a4b-46df-8891-ed7d2f0edcbf.png)

It's at these joints that the distance calculation loses accuracy.

**Comment by melchiar** [comment]
I'm still not exactly sure what's going on here, but I've been able to eliminate this issue by changing the default value of `nextStep` in the `findPercentageForDistance` function from 0.01 to 0.1. I'm thinking this is another floating point error but I haven't figured out exactly why yet.

**Comment by asturur** [comment]
i can look into this now

**Comment by TheAlemazing** [comment]
I changed the condition from 1 to 1.1 and it's worked

```
while (tmpLen < distance && perc < 1.1 && nextStep > 0.0001) {
...
}
```
