### ISSUE TITLE
Can the sides of a rectangle be stretched horizontally or longitudinally?Not the middle control point of the edge.

### ISSUE THREAD

**Issue by Ezr1al** [fabricjs/fabric.js#7346]
## Version
4.5.1
## Information about environment
chrome

## Expected Behavior
 When selecting a rectangle, I want to stretch it horizontally or vertically by stretching its four edges, because I need to hide the control points in the middle of the edges

![image](https://user-images.githubusercontent.com/36941749/131824140-d071f664-8ac9-471e-9a03-f74c980fdc84.png)

**Comment by asturur** [comment]
i think you can use a custom control.
For the Rect class define a control similar to controls.mr, but the define an empty render method.
At the same time make its size dependant from the rect height.

Did you check the custom control api?
