### ISSUE TITLE
Object's control box size doens't match the text size

### ISSUE THREAD

**Issue by EdnaldoNeimeg** [fabricjs/fabric.js#7354]
![image](https://user-images.githubusercontent.com/6233059/132251474-c3c21547-2c67-4083-b17b-3d7e9ae320bc.png)

## Version
4.6

## Test Case
http://jsfiddle.net/7pt4f2wq/

## Information about environment
Tested on Chrome browser only

## Steps to reproduce
Just load the page

## Expected Behavior
All the text inside the control box.

## Actual Behavior
Accent is out of the control box area

**Comment by i-prikot** [comment]
Hi. What language is the word written in? 

![image](https://user-images.githubusercontent.com/21138391/132282624-5395a8f3-8128-48d5-9141-c40ee2b37833.png)

**Comment by EdnaldoNeimeg** [comment]
> Hi. What language is the word written in?
> 
> ![image](https://user-images.githubusercontent.com/21138391/132282624-5395a8f3-8128-48d5-9141-c40ee2b37833.png)

I think the language is french, but the same thing happens with portuguese, as you can see here:
[](http://jsfiddle.net/Neimeg/6vL40o2a/10/)

**Comment by i-prikot** [comment]
> > Hi. What language is the word written in?
> > ![image](https://user-images.githubusercontent.com/21138391/132282624-5395a8f3-8128-48d5-9141-c40ee2b37833.png)
> 
> I think the language is french, but the same thing happens with portuguese, as you can see here:
> http://jsfiddle.net/Neimeg/6vL40o2a/35/

I think the font doesn't support these languages.  Google lists the languages it supports. You can see the list in the font comments.

**Comment by EdnaldoNeimeg** [comment]
The same problem whith well known fonts like Roboto, Lato and Ubuntu

http://jsfiddle.net/Neimeg/6vL40o2a/54/

I noticed that for some font families it happens only when you set fontFamily to 'bold'

**Comment by asturur** [comment]
Sadly the text measurment does not return accurate values for text height.
And we have no control over that. we can get only the width.
