### ISSUE TITLE
Shadow for underlined text not working properly when object caching is false

### ISSUE THREAD

**Issue by hamzawain7** [fabricjs/fabric.js#7356]
## Version
4.5.0

## Test Case
https://jsfiddle.net/hamzawain7/9v7e5j1n/2/

## Information about environment
Nodejs or browser?
Which browsers?
chrome

## Steps to reproduce
1. Open fiddle.
2. Toggling the Underline button renders shadow incorrectly
![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/20171624/132326105-a407d9be-3af3-45a2-b56e-c4d8b604d63f.gif)

## Expected Behavior
Both text and underline should have shadow

## Actual Behavior
Only underline has shadow

**Comment by melchiar** [comment]
Yes, objectCaching is necessary for a lot of things including clipPaths, underline + shadow, stroke + shadow, etc. Any particular reason why you're disabling caching?

**Comment by asturur** [comment]
mmmm this shadow should be fixed!
Once it worked.
The only issue is that the underline will cast a shadow over the text too.

**Comment by niketaOptimumnbrew** [comment]
> mmmm this shadow should be fixed! Once it worked. The only issue is that the underline will cast a shadow over the text too.

Hi @asturur ,
I'm using fabric.js version 5.3.0 and have the same issue.
Can you please give me the correct solution for that?

**Comment by asturur** [comment]
closing this since is reported on 4.5.0
There is a modern issue i ll track on that
