### ISSUE TITLE
Properties set by the object do not take effect in real time

### ISSUE THREAD

**Issue by Ezr1al** [fabricjs/fabric.js#7357]
I use the set property of an object on the canvas, and changing the properties of the object doesn't work in real time. For example, I change the radius and fill color of a circle: when I mouse over the circle, I want the radius of the circle to be 20 and the fill color to be red.When the mouse leaves the circle, I want the radius of the circle to be 5 and the fill color to be black.The specific code is as follows:
```
circle.on("mouseover",(e)=>{
    circle.set({
           radius:20,
           fill:'red',
        })
    })
circle.on("mouseout",(e)=>{
    circle.set({
        radius: 5,
        fill:'black'
     })
})
```
In fact, when I mouse over to remove, the radius and fill color of the circle do not change.But when I scale the canvas, it's going to change.

**Comment by melchiar** [comment]
Please, the issue tracker is for bug reports. You'll find the answer to your question in the docs.

http://fabricjs.com/fabric-intro-part-1
