### ISSUE TITLE
Use stroke to affect object position

### ISSUE THREAD

**Issue by Wulawa** [fabricjs/fabric.js#7368]
## Version
3.6.0

## Test Case
http://jsfiddle.net/d9u204rx/

## Information about environment
browser?
Which browsers?

## Expected Behavior
In the fiddle, can see that the position of  image has changed after the mouseover. 
Expected that the border does not occupy space like active object border

**Comment by asturur** [comment]
You can base object position on the center of the object if you don't like this.
```
fabric.Object.prototype.originX = 'center'
fabric.Object.prototype.originY = 'center'
```

In this way when you set top/left you are actually saying where the center of the image will be.
