### ISSUE TITLE
freedraw on ios cutt corners

### ISSUE THREAD

**Issue by Rad1calDreamer** [fabricjs/fabric.js#7370]
Version
the latest

## Test Case
on freedraw if we draw small angle  the corner will cutting
https://user-images.githubusercontent.com/7055577/132808319-594e2c6a-2ae7-41ca-8b64-047f3a943088.MP4

## Information about environment
IOS 14. chrome\safari

**Comment by asturur** [comment]
I do not think we can do much for that.
Can you dump the data of one of those paths that get cut?

**Comment by bigxixi** [comment]
There should be a line-join setting, then set it to 'round'.
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineJoin
