### ISSUE TITLE
why textbox Line feed width space？is it bug？

### ISSUE THREAD

**Issue by JSeasy** [fabricjs/fabric.js#7374]
## Version
3.6.3

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Nodejs or browser?
Which browsers?

## Expected Behavior
the textbox line feed width space

https://user-images.githubusercontent.com/44748591/133409719-0c95ffe4-5bda-4db9-ae17-4ffac5051459.mp4

**Comment by JSeasy** [comment]
may i change the line feed rules width config?

**Comment by asturur** [comment]
You are supposed to create a reproducible case.
Please reproduce your issue correctly.
