### ISSUE TITLE
Fabric 4.6 dots after selection click

### ISSUE THREAD

**Issue by mike667** [fabricjs/fabric.js#7375]
Hi, thanks for fabric.js, we love it. Can you look at this problem?

## Version
4.6

## Information about environment
Browser: Chrome Version 93.0.4577.63 (Official Build) (arm64), another browsers same.

## Steps to reproduce
Hard to reproduce. 

## Actual Behavior
With version 4.5 everything works well, only 4.6
After the click, points remain, as I understand it, these are the remnants of the selection.
![Screen Shot 2021-09-15 at 18 33 11](https://user-images.githubusercontent.com/9371245/133464199-d03e9f41-7e31-400d-86f0-ea37f9fc0b25.png)
They remain on the upper-canvas.
![Screen Shot 2021-09-15 at 18 34 17](https://user-images.githubusercontent.com/9371245/133464263-5bcf34f2-e7b4-4981-973a-65420eebee22.png)

https://user-images.githubusercontent.com/9371245/133464453-0309f0cd-109f-450b-a519-b53c63ec1ca8.mov

This code fixes this issue
```js
fabricCanvas.addEventListener('mouse:up', function(){
    this.clearContext(this.getSelectionContext());
})
```

https://user-images.githubusercontent.com/9371245/133464858-f803d98a-185a-4d3c-bb95-785daf49c4dc.mov

## Expected Behavior
Don't make a points. This is probably some kind of problem with caching, but in version 4.5 there was no such problem. Maybe you know what has changed in version 4.6 with caching?

Thanks!

**Comment by eltaiguer** [comment]
I'm having the same issue, can we reopen this?
