### ISSUE TITLE
Object.lockUniScaling is removed. Alternatives to get the same identical functionality with less code are being evaluated. breaking:

### ISSUE THREAD

**Issue by TimLiu1** [fabricjs/fabric.js#7378]
which function I can do same thing?

**Comment by melchiar** [comment]
`Canvas.uniformScaling`

see http://fabricjs.com/v4-breaking-changes

**Comment by asturur** [comment]
Which is the `same thing`? what function are you after?

**Comment by basielsmitz** [comment]
@TimLiu1 

this is my current workaround


```
fabricObject.setControlsVisibility({
    mb: false,
    ml: false,
    mr: false,
    mt: false
})

let timer;

fabricObject.on('scaling', e => {
  if (['bl', 'br', 'tr', 'tl'].indexOf(e.transform.corner) !== -0) {
    clearTimeout(timer)
    canvas.uniformScaling = true;
    timer = setTimeout(() => {canvas.uniformScaling = false}, 500);
  }
})
```

**Comment by TimLiu1** [comment]
> @TimLiu1
> 
> this is my current workaround
> 
> ```
> fabricObject.setControlsVisibility({
>     mb: false,
>     ml: false,
>     mr: false,
>     mt: false
> });
> 
> let timer;
> 
> fabricObject.on('scaling', e => {
>   if (['bl', 'br', 'tr', 'tl'].indexOf(e.transform.corner) !== -0) {
>     clearTimeout(timer);
>     canvas.uniformScaling = true;
>     timer = setTimeout(() => {canvas.uniformScaling = false}, 500);
>   }
> });
> ```

thank you very much

**Comment by TimLiu1** [comment]
> Which is the `same thing`? what function are you after?

by control  canvas.uniformScaling = true/false to resolve

**Comment by TimLiu1** [comment]
> `Canvas.uniformScaling`
> 
> see http://fabricjs.com/v4-breaking-changes

I think object uniformScaling overwrite canvas uniformScaling is make sense
