### ISSUE TITLE
text is covered when object zooming in or out

### ISSUE THREAD

**Issue by SilvaQ** [fabricjs/fabric.js#7379]
## Version
^4.6.0

---
I am a novice and have encountered some problems when reading documents to learn：
the code i learn is from  [The most appropriate subclass inherits part](http://fabricjs.com/fabric-intro-part-3#subclassing)。
 I want my label to be displayed right above and in the middle of the object，So I wrote code like this：
```js
var LabeledRect = fabric.util.createClass(fabric.Rect, {
    type: "labeledRect",
    // initialize can be of type function(options) or function(property, options), like for text.
    // no other signatures allowed.
    initialize: function (options) {
      options || (options = {});

      this.callSuper("initialize", options);
      this.set("label", options.label || "");
    },

    toObject: function () {
      return fabric.util.object.extend(this.callSuper("toObject"), {
        label: this.get("label"),
      });
    },

    _render: function (ctx) {
      this.callSuper("_render", ctx);
      ctx.font = "20px Helvetica";
      ctx.fillStyle = "#333";
      ctx.fillText(
        this.label,
        -this.width / 2 + ctx.measureText(this.lebel).width / 2 - 20 / 2,
        -this.height / 2
      );
    },
  });

  var canvas = new fabric.Canvas("canvas", {
    width: 500,
    height: 500,
  });

  var labeledRect = new LabeledRect({
    width: 100,
    height: 50,
    left: 100,
    top: 100,
    label: "test",
    fill: "#faa",
  });
  canvas.add(labeledRect);
```
The effect was exactly what I expected，The renderings are as follows：
![image](https://user-images.githubusercontent.com/46706370/133871585-ca099d87-62c4-41a9-980f-188ce1cc1339.png)
The problem starts when I zoom in and out，Part of my text was covered up，The renderings are as follows：
![image](https://user-images.githubusercontent.com/46706370/133871686-f7bfbc0d-a75f-4879-a854-0651731d2efb.png)

Is this a bug or do I need to do something special?

**Comment by SilvaQ** [comment]
I found that there was a configuration of whether to use cache or not, I rewrote it and set it to do not go cache drawing and it worked as I expected, the problem mentioned above disappeared, I suspect it occurred during cache redrawing。
```js
 _render: function (ctx) {
      this.callSuper("_render", ctx);
      ctx.font = "20px Helvetica";
      ctx.fillStyle = "#333";
      ctx.fillText(
        this.label,
        -this.width / 2 + ctx.measureText(this.lebel).width / 2 - 20 / 2,
        -this.height / 2
      );

       // let him dont use cache
      this.shouldCache = function () {
        return false;
      };
    },
  });
```

**Comment by melchiar** [comment]
generally you want to contain your objects within the bounding box to prevent clipping, but if sure you want to draw it this way you can disable caching with `obj.objectCaching = false`

**Comment by SilvaQ** [comment]
> generally you want to contain your objects within the bounding box to prevent clipping, but if sure you want to draw it this way you can disable caching with `obj.objectCaching = false`

Do you have any suggestions if I want to do this with subclasses and also want to use caching capabilities？

**Comment by melchiar** [comment]
you could modify your _render method to leave a gap at the top for the text when it draws the rect. To do that, remove `this.callSuper("_render", ctx);` which calls the standard Rect render method and write your own rect render method with room for the text. 

Something like this (not tested)

```
var gap = 20;
var w = this.width,
h = this.height - gap,
x = -this.width / 2,
y = -this.height / 2 + gap;

ctx.beginPath();
ctx.rect(x,y,w,h);
this._renderPaintInOrder(ctx);
```

This really isn't a bug report though so I'm going to close it from the issue tracker.
