### ISSUE TITLE
Mouse events are invalid after changing position

### ISSUE THREAD

**Issue by Ezr1al** [fabricjs/fabric.js#7380]
## Version
4.5.1 

## Test Case
http://jsfiddle.net/o6hxa0cg/1/

## Information about environment
chrome

## Steps to reproduce
  1. Create a circle and add mouse events: mouseover, mouseDown, mouseout.
 2. Change the position of the circle.
## Expected Behavior
  Mouse events are valid.
## Actual Behavior
Mouse events are invalid after changing position.

**Comment by melchiar** [comment]
You need to call `setCoords()` after programmatically changing an object's position.

See 
http://fabricjs.com/fabric-gotchas
https://github.com/fabricjs/fabric.js/wiki/When-to-call-setCoords

**Comment by Ezr1al** [comment]
Thank you, this document is very timely for beginners.
