### ISSUE TITLE
strokeWidth change unexpected behaviour. 

### ISSUE THREAD

**Issue by pneves001** [fabricjs/fabric.js#7384]
## Version
I've tried Latest version in github but version 4.6.0 also does it. Which is the latest on the fabricjs.com website. 

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Nodejs or browser?
Which browsers?
Chorme, Brave
## Steps to reproduce

create a shape (circle, rect, triangle or polygon) with no fill with a stokeWidth of one.  
add shape to the canvas so that its visible
set the strokeWidth to 5
redraw  

## Expected Behavior
The border line of the shape should be thicker.  

## Actual Behavior
It resizes the control box and the shape to an astronomical size.

**Comment by pneves001** [comment]
An additional note. I was unable to reproduce this on JS Fiddle. However, JS fiddle didn't change the line thickness at all. So its still not behaving the way its supposed to.

**Comment by melchiar** [comment]
You'll need to add a fiddle demonstrating the issue if we're to be of any help (the current fiddle link is empty)

**Comment by pneves001** [comment]
I'm unable to reproduce the issue on JS Fiddle. its specifically happening with the npm install of the library. I don't know what version of the library exists with JS fiddle. As soon as I change the strokeWidth to anything but 1 the size of the object I'm applying the change to changes to some weird amount and int fails to render the object. The controls just expand to a massive size. It could be a setting I'm setting or not setting I don't know. But this is not the behaviour that is advertised in all the examples.

**Comment by pneves001** [comment]
So I managed to pinpoint when the problem is happening. Right after I create an object for the strokeWidth to work correctly I have to resize the object manually. Otherwise it resizes the whole object to some random size. Where the sizing goes right off the screen. Is there some setting I need to set to make it not do that? Seems like some variable might not be properly initialized or something.

**Comment by asturur** [comment]
if it does not happen in the fiddle, the issue is probably in your application.
