### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [fabricjs/fabric.js#7385]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by asturur** [comment]
You can write me an email, my email is in my profile.

**Comment by asturur** [comment]
@JamieSlome was it you pointing me out to a security report for fabricJS? i lost the link for it

**Comment by JamieSlome** [comment]
@asturur - here you go:

https://huntr.dev/bounties/b9488714-5b55-4ac3-bc53-4123c106dd02/

**Comment by asturur** [comment]
thank you
