### ISSUE TITLE
Async method for applyFilters() function

### ISSUE THREAD

**Issue by cyril88888** [fabricjs/fabric.js#739]
Hello,

I'm using fabricJS with images so I plan to do extensive usage of filters. However, if many filters are applied at same time (to emulate Instagram for example), it can freeze the browser and trigger the "stop running this script" message.
Hence, I modified a bit the code to implement this solution: http://www.picnet.com.au/blogs/guido/post/2010/03/04/how-to-prevent-stop-running-this-script-message-in-browsers/

I'm not a very good coder, but maybe this code can be enhanced and released in future version of fabricJS.

**1) I modified _applyFilters()_ function (in fabricJS main code) as follow:**

``` javascript
applyFilters: function(callback) {
  if (this.filters.length === 0) {
    this.setElement(this._originalImage);
    callback && callback();
    return;
  }

  var imgEl = this._originalImage,
      canvasEl = fabric.util.createCanvasElement(),
      replacement = fabric.util.createImage(),
      _this = this;

  canvasEl.width = imgEl.width;
  canvasEl.height = imgEl.height;

  canvasEl.getContext('2d').drawImage(imgEl, 0, 0, imgEl.width, imgEl.height);

  // Get numbers of filters to be applied
  var nbFilter = this.filters.length;
  var i = 0, that=this;

  // this function will be called every second and check if the current filter is applied
  // Then proceed to the next one if nbFilter > 1, or simply render the image
  var startFilter = setInterval(function(){

    var current = i;

    // All filters are done, we end the interval and render image
    if((current >= nbFilter && !doFilter) || !nbFilter) {
      clearInterval(startFilter);

      // Below is the orignal code for applyFilter to render
      replacement.width = imgEl.width;
      replacement.height = imgEl.height;
      if (fabric.isLikelyNode) {
        // cut off data:image/png;base64, part in the beginning
        var base64str = canvasEl.toDataURL('image/png').substring(22);
        replacement.src = new Buffer(base64str, 'base64');
        // onload doesn't fire in some node versions, so we invoke callback manually
        _this._element = replacement;
        callback && callback();
      }
      else {
        replacement.onload = function() {
          _this._element = replacement;
          callback && callback();
          replacement.onload = canvasEl = imgEl = null;
        };
        replacement.src = canvasEl.toDataURL('image/png');
      }
      return that;
      // End of orignal code
    }

    // If no filters are being applied (but there are some to be applied)
    else if(!doFilter){
      that.filters[i].applyTo(canvasEl);
      i++;
    }
  }, 1000);
}
```

**2) In my main script, I define my own filters, for example a Contrast filter:**

``` javascript
fabric.Image.filters.Contrast = fabric.util.createClass( {
  type: "Contrast",
  initialize: function(options) {
    options || (options = { });
    this.adjust = options.adjust || 0;
  },

  applyTo: function(canvasEl) {      

    doFilter = true; // Set this global var to true (no other filter can be applied while true)

    var context = canvasEl.getContext('2d'),
        imageData = context.getImageData(0, 0, canvasEl.width, canvasEl.height),
        data = imageData.data,
        adjust = Math.pow((this.adjust + 100) / 100, 2);

    var i = 0;
    var ro = new RepeatingOperation(function() {

      // Below is the code of filter modifications
      var r = data[i], g = data[i+1], b = data[i+2];
      r /= 255;
      r -= 0.5;
      r *= adjust;
      r += 0.5;
      r *= 255;
      g /= 255;
      g -= 0.5;
      g *= adjust;
      g += 0.5;
      g *= 255;
      b /= 255;
      b -= 0.5;
      b *= adjust;
      b += 0.5;
      b *= 255;
      data[i] = r;
      data[i+1] = g;
      data[i+2] = b;
      // End of filter code

      i = i+4;
      if (i < data.length) { ro.step(); }
      else { 
        doFilter = false; // Filter is now fully applied, can proceed to next one if any
        context.putImageData(imageData, 0, 0);
      }
    }, 10000); // Every 10'000 loop, the script will stop for 1ms ==> to avoid the "stop running this script" browser message
    ro.step();
  },

  toJSON: function() {
    return {
      type: this.type,
      adjust: this.adjust
    };
  }
});
```

**3) finally, in my main script, I declare the interval functions and global var:**

``` javascript
var doFilter = false;
RepeatingOperation = function(op, yieldEveryIteration) {
  var count = 0;
  var instance = this;
  this.step = function(args) {
    if (++count >= yieldEveryIteration) {
      count = 0;
      setTimeout(function() { op(args); }, 1, []);
      return;
      }
    op(args);
  };
};
```

So far It's working fine, even if the filter is not "built" for async mode (i didn't rewrite builtin filters of fabricJS). 
An other advantage of this method, is now we can have a clue of the progression of the filter => so we can show to user a progress bar of each filter being applied. 
*Unfortunatelly, my application is not yet public so I can't show you a working example for now :/ \*

**Comment by onassar** [comment]
@kangax any thoughts into integrating a callback/async approach to filters? running into the same problem, but I doubt this code here will work with recent version.

**Comment by kangax** [comment]
@onassar I'm hesitant to add more complexity/options, so unless this becomes a common request (which it hasn't been so far) I'd rather it be implemented on an application level.

**Comment by onassar** [comment]
Gotcha @kangax
I've seen it in a couple places eg. https://groups.google.com/forum/#!topic/fabricjs/yNXmttQNd-c

The advantage being that I could develop fabric filters that make use of Caman's library (http://camanjs.com/examples/)

I understand the reluctance though
If you find some time to throw at it, let me know

Looks like this right here would need to be restructured to recursively pass callbacks to all filters, in order to accommodate this async approach: https://i.imgur.com/qb50f5q.png

**Comment by onassar** [comment]
Any progress made here @kangax since I last posted?

**Comment by asturur** [comment]
i don't think so. This let a lot to the user to do, is not a built in function.

```javascript
var doFilter = false;
RepeatingOperation = function(op, yieldEveryIteration) {
  var count = 0;
  var instance = this;
  this.step = function(args) {
    if (++count >= yieldEveryIteration) {
      count = 0;
      setTimeout(function() { op(args); }, 1, []);
      return;
      }
    op(args);
  };
};
```

we declare a global "var outside" and calling it during the applyfilter is not the best approach. Fabricjs will not fullfill every developer needs, as @kangax said if  you need to implement this you can still subclass image or override it and be compatible 99% with future updates.

**Comment by onassar** [comment]
I'm not following what you're trying to show me with this code. My issue is that some filters I want to run are very slow, and I therefore want to either pass in a callback, or pass over the operation to a worker. However I cannot do that if the filters in fabric do not support callbacks.

Do you have any example on how to update the filters class to allow this?

**Comment by mbarwick83** [comment]
@onassar you ever find a way to build custom filters using caman.js library? I would love to peek at the code. Drumming my head right now.

**Comment by onassar** [comment]
Hey @mbarwick83 I did manage to get it working by extending fabric, but the problem is it's so deeply coupled with my application-code that I can't really abstract it out to show you. @asturur any progress on this?

**Comment by asturur** [comment]
i waitin some permission to release some webgl filtering work on fabricjs. that will solve most of the problems of speed.
filters in plainjs are slow anyway and more than optimizing then as much as possible i do not want to do much more.

**Comment by onassar** [comment]
Yah I agree it's pretty slow, but depending on your application use-cases, it might still be fine.
@asturur any timeline?

**Comment by asturur** [comment]
i depend on third parts for webgl.

On Dec 10, 2016 02:19, "Oliver Nassar" <notifications@github.com> wrote:

Yah I agree it's pretty slow, but depending on your application use-cases,
it might still be fine.
@asturur <https://github.com/asturur> any timeline?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kangax/fabric.js/issues/739#issuecomment-266166885>,
or mute
the thread
