### ISSUE TITLE
Unable to convertPointsToSVGPath exception in the getSmoothPathFromPoints method

### ISSUE THREAD

**Issue by abnersouza** [fabricjs/fabric.js#7390]
## Version
4.6.0

## Information about environment
Any browser

## Steps to reproduce
1. Create a pencil brush
```
// Create a pencil brush
let pencil = new fabric.PencilBrush(this.freeHandControl); // Here I'm this.freeHandControl is a fabric.ICanvas

// Convert array of points to svg path
let svgPath = pencil.convertPointsToSVGPath(arrayOfPoints); // arrayOfPoints is array like: [ { x: 169, y: 10 }]
```

## Expected Behavior
It should convert the array of points to SVG Path

## Actual Behavior
It throw an exception inside the convertPointsToSVGPath => getSmoothPathFromPoints

Added the code below that shows where it breaks.
 if (!p1.eq(p2) -> Exception here in the second interaction because eq funcion is undefined.
 p1 = points[i]; -> Cause 1 - It should be = new fabric.Point(points[i].x, points[i].y);
p2 = points[i]; > Cause 2  - It should be = new fabric.Point(points[i + 1].x, points[i + 1].y);

```
function getSmoothPathFromPoints(points, correction) {
        var path = [], i,
            p1 = new fabric.Point(points[0].x, points[0].y),
            p2 = new fabric.Point(points[1].x, points[1].y),
            len = points.length, multSignX = 1, multSignY = 0, manyPoints = len > 2;
        correction = correction || 0;

        if (manyPoints) {
            multSignX = points[2].x < p2.x ? -1 : points[2].x === p2.x ? 0 : 1;
            multSignY = points[2].y < p2.y ? -1 : points[2].y === p2.y ? 0 : 1;
        }
        path.push(['M', p1.x - multSignX * correction, p1.y - multSignY * correction]);
        for (i = 1; i < len; i++) {
            if (!p1.eq(p2)) { // HERE IS THE EXCEPCTION IN THE SECOND LOOP
                var midPoint = p1.midPointFrom(p2);
                // p1 is our bezier control point
                // midpoint is our endpoint
                // start point is p(i-1) value.
                path.push(['Q', p1.x, p1.y, midPoint.x, midPoint.y]);
            }
            p1 = points[i]; // Here is the root cause -> it should be = new fabric.Point(points[i].x, points[i].y);
            if ((i + 1) < points.length) {
                p2 = points[i]; // Here is the root cause again => it should be = new fabric.Point(points[i + 1].x, points[i + 1].y);
            }
        }
        if (manyPoints) {
            multSignX = p1.x > points[i - 2].x ? 1 : p1.x === points[i - 2].x ? 0 : -1;
            multSignY = p1.y > points[i - 2].y ? 1 : p1.y === points[i - 2].y ? 0 : -1;
        }
        path.push(['L', p1.x + multSignX * correction, p1.y + multSignY * correction]);
        return path;
    }
```

**Comment by asturur** [comment]
Feel free to open a PR to fix it, thanks!

**Comment by ShaMan123** [comment]
You can fix this with a simple call
```diff
-  if (!p1.eq(p2)) { // HERE IS THE EXCEPCTION IN THE SECOND LOOP
+  if (!fabric.Point.prototype.eq.call(p1, p2)) { 
```

**Comment by OilPrince** [comment]
Thank you very much for your post.

I was using PencilBrush's convertPointsToSVGPath method and was panicking because a JavaScript error occurred in fabric.js(version 5.3.1).

After checking and understanding the contents of the error and how to take action in your post, we corrected the fabric.js source directly to resolve the error.

It's strange that it's been quite a while since the posting date of this post, and yet this action hasn't been applied to fabric.js!

Should it be a source correction and action for errors only through PR?

I hope there will be more active action from the management team.

**Comment by ShaMan123** [comment]
Provide a repro in v6 and we can look into it
And yes, if you have fixes PR.
