### ISSUE TITLE
strokeUniform not working on text

### ISSUE THREAD

**Issue by klavsbuss** [fabricjs/fabric.js#7391]
`strokeUniform` not working on `text` object.
Reproduced here: [jsfiddle](https://jsfiddle.net/2suy1nva/13/)

Expected result: fixed strokeWidth even if object scaled by X,Y

![Screenshot 2021-09-23 at 10 17 28 AM](https://user-images.githubusercontent.com/18184893/134468191-15e42e8e-f4ad-42aa-8ae6-8ddb15a57965.png)

### Discussed in https://github.com/fabricjs/fabric.js/discussions/7389

<div type='discussions-op-text'>

<sup>Originally posted by **klavsbuss** September 22, 2021</sup>
Hi.
1. Is there a way I can apply text scaling `scaleX` without affecting `strokeWidth` scale?
2. Why do some letters for [Inter](https://fonts.google.com/specimen/Inter) has this weird outline applied? Only solution i found was using `paintFirst: 'stroke',` but is there solution that includes **transparent fill**?

Help much appreciated! 🙏

![Screenshot 2021-09-22 at 9 33 14 PM](https://user-images.githubusercontent.com/18184893/134401950-8a2be95c-2056-49e2-b71e-fbc63b82c59c.png)

</div>

**Comment by asturur** [comment]
I do not think this can work for text at all.
