### ISSUE TITLE
loadFromJSON loses background image after toJSON.  

### ISSUE THREAD

**Issue by pneves001** [fabricjs/fabric.js#7393]
## Version
4.6.0 

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Nodejs or browser?
Which browsers?

## Steps to reproduce
Create Image and Set Scaling like SO

  fabric.Image.fromURL( this.background_image, function (img)
                      {
                      obj.canvas.setBackgroundImage(img, 
                                                    obj.canvas.renderAll.bind(obj.canvas),
                                                   { scaleX: obj.canvas.width / img.width,
                                                     scaleY: obj.canvas.height / img.height });

                      obj.canvas.renderAll();
                      });

Save JSON image 

this.canvas.toJSON();

Load JSON IMAGE 

this.canvas.loadFromJSON(JSON.parseimage_json), this.canvas.renderAll.bind(this.canvas));

## Expected Behavior

Background image should load with proper sizing covering the background. . 

## Actual Behavior

While the background image loads. It doesn't properly size the image to cover the background screen. This worked in older versions of the API but now it doesn't.

**Comment by Gerwin-prog** [comment]
@asturur A similair issue occurs when saving json & rendering it again - a regular image isn't added to the canvas.getObjects() list, but I assume it should be?

	loadJSON(json){
		var canvas = canvas;
		canvas.loadFromJSON(json, canvas.requestRenderAll.bind(canvas), function(json, object){ renderJsonSettings(thisClass, json, object) });
	}

so 'object' in the function above is every object within fabricjs but the image(s).

**Comment by xor83** [comment]
Any updates on this this issue?

**Comment by TimoA200** [comment]
Any updates, or workarounds?
I feel like the object states should also be saved in the JSON, otherwise, this feature doesn't make much sense in many cases.

**Comment by asturur** [comment]
toJSON/toObject takes care of the visual part of the canvas only. If you want to add more properties you have to add that with the extra properties parameter.

**Comment by vaynevayne** [comment]
hello,  Is there any follow-up?
I have two questions
1.   toJSON() return below
![image](https://github.com/user-attachments/assets/092f0856-a2cf-4882-8437-5d6a42fc7313)

 it has BackgroundImage, but look like  loadFromJSON don't use it 

2. Manually restore background images, does image support json data
```jsx
   canvasRef.current.setBackgroundImage(
    json.backgroundImage,
    )

or

  canvasRef.current.setBackgroundImage(
    new Iamge(json.backgroundImage),
    )
```
both not work 
@asturur
