### ISSUE TITLE
The line that goes to the rotation control is not correctly placed with fabric 4.6.0

### ISSUE THREAD

**Issue by flexeo** [fabricjs/fabric.js#7396]
The line that goes to the rotation control is not placed correctly when you drag the object until you get its mirror.
### 
![mirror](https://user-images.githubusercontent.com/22362051/134707038-fa2d4d8b-7b52-4dd2-8209-ce6e97e43328.png)
### 

## Version
4.6.0

## Test Case
http://fabricjs.com/custom-control-render

## Information about environment
All browsers

**Comment by asturur** [comment]
oh you are right. flipX breaks it.

**Comment by Gerwin-prog** [comment]
duplicate of -> https://github.com/fabricjs/fabric.js/issues/7387 @asturur

**Comment by asturur** [comment]
ok

**Comment by virtualb2b** [comment]
hi im new in Fabric version 4.6.0 im trying to customized controller in Rotate & Scale & Clone & Remove clone & delete working fine Rotate & Scale not working code link blow please anyone help me out thanks 

http://virtualb2b.net/f/

**Comment by asturur** [comment]
this has been solved
