### ISSUE TITLE
Unable to get true coordinates / angle when objects are selected and modified

### ISSUE THREAD

**Issue by kirill-konshin** [fabricjs/fabric.js#7407]
## Version
3.6.0

## Test Case
http://jsfiddle.net/9x7hrf2y/17/

## Steps to reproduce
Use the code in JS Fiddle and rotate the selection.

## Expected Behavior
Console logged angles should be the same

## Actual Behavior
Since lines are part of `activeSelection` group, which has `angle` their own angles are `0`.

As you can see in the fiddle, I tried to make JSON of the entire canvas and get position from there, it kinda works, but looks awkward because I have to find the needed object in the pile of JSON.

What is the reliable method to get true object position after modification but while selection is not cleared?

**Comment by kirill-konshin** [comment]
Not stale!

**Comment by kirill-konshin** [comment]
Not stale! And still no resolution!

**Comment by asturur** [comment]
http://jsfiddle.net/5nkm8wed/1/
I updated the jsdfiddle.

@kirill-konshin the stale bot will put the stale label if there is not interaction on the issue.

**Comment by kirill-konshin** [comment]
@asturur thank you! And in case of nested groups this has to be called recursively, I presume?

**Comment by asturur** [comment]
no it should work out of the box.
calcTransformMatrix will go up recursively on its own.

**Comment by kirill-konshin** [comment]
@asturur Found some more things here. The problem is that `angle` works as expected, but if I need true `left` and `top` coords, some more coding is needed. I went ahead and found this solution:

```js
const calcCoords = (obj) => {
    const jsonOwn = obj.toJSON();
    const mat = obj.calcTransformMatrix();
    const { translateX, translateY, ...qr } = fabric.util.qrDecompose(mat);
    const coords = fabric.util.transformPoint(obj.getPointByOrigin(obj.originX, obj.originY), mat);
    return {
        ...jsonOwn,
        ...qr,
        left: coords.x,
        top: coords.y,
    };    
}
```

As suggested here https://stackoverflow.com/a/69602919/5125659 **but in some cases I see 1-2 pixels difference**. My main question here: is the code above OK? And how to beat this small discrepancy?

Also a great explanation from the same SO question: https://stackoverflow.com/a/29926545/5125659.

P.S. Your solution seems to be this one, which I failed to find earlier: https://stackoverflow.com/a/39001310/5125659 so I'm leaving the link here, just in case.

**Comment by kirill-konshin** [comment]
@asturur after digging even deeper in Fabric sources I've found a way by mimicking how `canvas.toJSON()` works:

```js
const json = obj.canvas._toObject(obj, 'toObject');
```

This always gives proper coordinates with proper angles and offsets.

**Comment by asturur** [comment]
hi @kirill-konshin , this is a known issues, and we are working around it.
We want to restructure group so that swapping coordinates is no more needed.

**Comment by kirill-konshin** [comment]
> hi @kirill-konshin , this is a known issues, and we are working around it. We want to restructure group so that swapping coordinates is no more needed.

Can you reopen the issue to keep track of this?

**Comment by asturur** [comment]
@kirill-konshin i know you solved this issue your way.
I think  the correct way to solve this is this one:

https://jsfiddle.net/5mj82y07/

you extract the angle from the current transform matrix of the object that takes in account all the transformations from containers.

**Comment by kirill-konshin** [comment]
@asturur yes, I've tried `qrDecompose` but it had some issue in more complicated scenarios, like I said here https://github.com/fabricjs/fabric.js/issues/7407#issuecomment-997037091

**Comment by asturur** [comment]
Can you point out those extra scenarios? it may be helpful to understand why wasn't working.
This should be the way to do it, so if it does not work we should understand why

**Comment by kirill-konshin** [comment]
> But neither solution works when objects with different originX and originY are in selection...

This one.

**Comment by asturur** [comment]
Ok i ll extend my fiddle to find out left and top of the lines, just to see where the issue is.
