### ISSUE TITLE
OnClick Animation Issue

### ISSUE THREAD

**Issue by tanzyy96** [fabricjs/fabric.js#7408]
## Version
3.6.0

## Test Case
http://fabricjs.com/customization

## Information about environment
Google Chrome

## Steps to reproduce
For *Modification on move*, the animation seems to be non-blocking or something? Clicking quickly in succession will cause the object to scale infinitely larger.  Is there a way to prevent this?

**Comment by tanzyy96** [comment]
Any solutions on how to overcome this?

**Comment by ShaMan123** [comment]
https://github.com/fabricjs/fabricjs.com/commit/c324a0219ad7de2dca02cdaa829164759379e464
