### ISSUE TITLE
Aspec ratio mantain on different screen dimension

### ISSUE THREAD

**Issue by albanx** [fabricjs/fabric.js#741]
I notice that toJSON method send objects coordinate in pixels (absolute). This means that if I load these objects on a different screen size, the coordinates will be wrong.

Is there any options, or method, to make the way that coordinates and dimension to be saved in ratio/relative mode? example
canvas size 300x200,
rect size 50x50, rect position x:30 y:20

When  save the Rect coors and position, this will be better:
rect size 50/300 x 50/200, rect pos x:30/300 y:20/200

So If I load this Rect in a canvas 600x400 it will be displayed correctly.

**Comment by astw** [comment]
I wonder has this been implemented?

**Comment by asturur** [comment]
There is an easy trick for this, you do not need to make a fabric feature.

Group all the canvas in a group
enlarge the canvas
scale the group proportionally to fit the new canvas
put the group in the center of canvas 
ungroup everything

that will give you the best between bad and perfect.

**Comment by yanzhou-share** [comment]
@asturur 
Thanks for your solution, can U share me a demo.
For example 
two clients A and B.
A is drawing on 2000*1000px canvas
B is drawing on 1000*500px canvas 

A and B  is synchronous 
How can load these objects on a different screen size.

Do you understand, Thanks.

**Comment by albanx** [comment]
The above JS snippet made for me the trick (years ago)

**Comment by asturur** [comment]
that is easy.
But imagine 2 user,
one on a window that is 2000x1000
and another that is  500x800 ( wide vs tall )

depends on how your application is setup and how you are redrawing from a screen to another.

Are you reloading the screen in realtime in collaboration app? ora are you reloading a design on a different computer?

**Comment by yanzhou-share** [comment]
Thanks for your help, mine is first kind realtime reload. 
@asturur

**Comment by albanx** [comment]
It does not really matter the screen size of the users involved, the `loadFromJSONRel` and `toJSONRel` methods use relative coordinates in %, so the the drawings will be fine everywhere

**Comment by yanzhou-share** [comment]
I try what you said but it doesnt work.

(function() {
fabric.util.object.extend(fabric.Canvas.prototype,{
loadFromJSONRel: function(json, callback, ratio)
{
if (!json) return;

        // serialize if it wasn't already
        var serialized = (typeof json === 'string') ? JSON.parse(json) : json;

        var canvas_w = this.getWidth();
        var canvas_h = this.getHeight();
        var objs_rels = [];
        for(var i=0;i<serialized.objects.length;i++)
        {
            var o = serialized.objects[i];
            o['width'] *=canvas_w;
            o['height'] *=canvas_h;
            o['left'] *=canvas_w;
            o['top'] *=canvas_h;
            if(o['rx']) o['rx'] *=canvas_w;
            if(o['ry']) o['ry'] *=canvas_w;
            objs_rels.push(objs_rels);
        }

        var _this = this;
        this._enlivenObjects(objs_rels, function () {
          _this._setBgOverlayImages(serialized, callback);
        });
        this.renderAll();
        return this;
    },
    toJSONRel: function()
    {
        var canvas_w = this.getWidth();
        var canvas_h = this.getHeight();

        var objs = this.getObjects();
        var objs_rels = [];
        for(var i = 0; i<objs.length;i++)
        {
            var o = objs[i];
            o['width'] /=canvas_w;
            o['height'] /=canvas_h;
            o['left'] /=canvas_w;
            o['top'] /=canvas_h;
            if(o['rx']) o['rx'] /=canvas_w;
            if(o['ry']) o['ry'] /=canvas_w;
            objs_rels.push(o);
        }
        return objs_rels;
    }
});
})();

**Comment by yanzhou-share** [comment]
this.canvas.loadFromJSONRel(json, this.canvas.renderAll.bind(_this.canvas), 16/9);

Is it right?  wide/tall = 16/9

**Comment by asturur** [comment]
so the relative coordinates won't help.

My personal experience is that a design is mantained when the distance between object does not change.
If i m designing a face with a triangle and 2 circles, and i reload it on a much wider area, i do not want the circles and triangle to be spread all over the sceen.

Probably the user want to see the same design, shrinked or zoomed, to fit its own canvas.
virtually like if for a moment it become an image, and transferred as an image.

To do that you have to group before outputting json, and resize and ungroup right a after restoring.
I can help, not from scratch.

Prepare a fiddle with a canvas and 3 objects, and 2 destinations canvas with different dimensiosn, and 2 buttons to copy design there. We can discuss solutions starting from there.

**Comment by astw** [comment]
This is my code roughly like, I tried both zoom and scale the location/size,  they don't always work well.  
So I don't what need to do to fix it. 

function restoreDedicatedPage(book) {
      var scale = vm.dedicatePageCanvas.width / vm.PhotoBook.dedicatedPage.width;
      vm.dedicatePageCanvas.setZoom(scale);
      vm.dedicatePageCanvas.loadFromJSON(vm.PhotoBook.dedicatedPage.imageData, function () {
        vm.PhotoBook.dedicatedPage.previewImage = vm.dedicatePageCanvas.toDataURL();
        vm.dedicatePageCanvas.renderAll();
      }); 
    }

......
And: 
  
     var xscale = width / imageWidth;
      var yscale = height / imageHeight;

       canvas.loadFromJSON(data.imageData, canvas.renderAll.bind(canvas), function (o, object) {
          object.left = object.left * xscale;
          object.width = object.width * xscale;
          object.height = object.height * yscale;
          object.top = object.top * yscale; 
     });

**Comment by TeniSoftTechnologies** [comment]
> There is an easy trick for this, you do not need to make a fabric feature.
> 
> Group all the canvas in a group enlarge the canvas scale the group proportionally to fit the new canvas put the group in the center of canvas ungroup everything
> 
> that will give you the best between bad and perfect.

Good idea but it will not work as expected. Objects with some parts off the canvas will fully show after implementing your suggestion.
