### ISSUE TITLE
onmousedown, onmousemove,onmousemove for simulation not working with latest version, working with 1.6.7 version only

### ISSUE THREAD

**Issue by abhinavOmni** [fabricjs/fabric.js#7430]
## Version
3.6.0

## Test Case
http://jsfiddle.net/3svfwgzc/

## Information about environment
Nodejs or browser?
Which browsers?

## Steps to reproduce
current version in  jsfiddle is https://cdnjs.cloudflare.com/ajax/libs/fabric.js/1.7.19/fabric.min.js

change the version to 
https://cdnjs.cloudflare.com/ajax/libs/fabric.js/460/fabric.min.js it will not work, pls help
![image](https://user-images.githubusercontent.com/71629015/136974170-64fc733b-85b5-4eb6-85eb-87a7e4819791.png)
## Expected Behavior

Required free-drawing simulation programmatically using points..

**Comment by lebornjose** [comment]
`import { useEffect } from 'react';
import fabric from '@/pages/customize/utils/newFabric';
import './index.scss';

let canvas = null;
const Fabric = () => {
  useEffect(() => {
    canvas = new fabric.Canvas(document.getElementById('canvasId'), {
      controlsAboveOverlay: true,
      enableRetinaScaling: true,
      selection: false
    });
    canvas.isDrawingMode = true;
    canvas.freeDrawingBrush.width = 5;
    canvas.freeDrawingBrush.color = '#00aeff';

    let isDrawing = false;
    canvas
      .on('mouse:down', function (options) {
        isDrawing = true;
        onMouseDown(options);
      })
      .on('mouse:up', function (options) {
        isDrawing = false;
        onMouseUp(options);
      })
      .on('mouse:move', function (options) {
        if (isDrawing) {
          const pointer = canvas.getPointer(options.e);
          drawRealTime(options, pointer);
        }
      });

    var canvas2 = new fabric.Canvas(document.getElementById('canvasId2'), {
      controlsAboveOverlay: true,
      enableRetinaScaling: true,
      selection: false
    });
    canvas2.isDrawingMode = true;
    canvas2.freeDrawingBrush.width = 5;
    canvas2.freeDrawingBrush.color = '#00aeff';

    // function drawOnCanvas(json) {
    //   canvas2.loadFromJSON(json);
    // }

    function onMouseDown(options) {
      const pointer = canvas.getPointer(options.e);
      canvas2.freeDrawingBrush.onMouseDown(pointer, options);
    }

    function onMouseUp(options) {
      const pointer = canvas.getPointer(options.e);
      canvas2.freeDrawingBrush.onMouseUp(options);
    }

    function drawRealTime(options, pointer) {
      canvas2.freeDrawingBrush.onMouseMove(pointer, options);
    }
  }, []);
  return (
    <div>
      <canvas id='canvasId'></canvas>
      <canvas id='canvasId2'></canvas>
    </div>
  );
};

export default Fabric;
`

Try this
