### ISSUE TITLE
custom-controls is supported corner hover Style ?

### ISSUE THREAD

**Issue by alexmelo23** [fabricjs/fabric.js#7436]
Hi,
I want to know if custom-controls supported Hover corner style?

I using custom-controls for polygon edit and I want if the user over top of the point to change the color It's possible?

I using this demo [http://fabricjs.com/custom-controls-polygon](url) 

thanks.

**Comment by asturur** [comment]
i have to ask to owners, i asked, i m waiting an answer

**Comment by MaxHXie** [comment]
I would like to reopen this issue.
