### ISSUE TITLE
EraserBrush doubles the opacity of semi-transparent non-erasable shapes during free drawing

### ISSUE THREAD

**Issue by porterde** [fabricjs/fabric.js#7445]
## Version
4.6.0 with eraser module

## Test Case
[requires custom build of fabric with eraser brush]

## Information about environment
Browser

## Steps to reproduce
1. Create a custom build of fabric including EraserBrush
2. Add a non-erasable Rect with fill black and opacity 0.2
3. Set EraserBrush as the free drawing brush and enable isDrawingMode
4. When you press down the mouse button, the rectangle gets darker
5. You can "erase" the darkness, to reveal the lighter rectangle underneath
5. When you release the mouse button, the entire rectangle returns to normal

## Expected Behavior
Non-erasable shapes which are semi-transparent do not change during free drawing erasing
Semi-transparent shadows of non-erasable shapes should not change darkness during free drawing erasing

## Actual Behavior
Non-erasable shapes which are semi-transparent get darker during free drawing erasing
This also affects the semi-transparent shadows of non-erasable shapes

The logic in `renderBottomLayer` and `renderTopLayer` in https://github.com/fabricjs/fabric.js/blob/master/src/mixins/eraser_brush.mixin.js means non-erasable objects are rendered on both the top and bottom canvases, so the opacity of the semi-transparent areas is doubled.

For the special case where the non-erasable object has no erasable objects beneath it, I imagine this issue could be fixed by filtering out such objects during `renderTopLayer`. Is there a solution for the general case?

**Comment by ShaMan123** [comment]
@porterde look at #7470

**Comment by ShaMan123** [comment]
eraser v2 is now stable

**Comment by ShaMan123** [comment]
The eraser has moved https://github.com/ShaMan123/erase2d
