### ISSUE TITLE
fabric.Image wrong src attribute in toObject

### ISSUE THREAD

**Issue by Kienz** [fabricjs/fabric.js#745]
If you call `img.setElement(imgEl)` the _element property is set. The method `fabric.Image.getSrc()` returns the src attribute of `fabric.Image._element`. 
But if you call `fabric.Image.toObject` the src attribute of the originalImage is used.
`fabric.Image.toSVG` works correct - uses getSrc().

**Comment by saran110313** [comment]
I'm receiving this error originating from fabric.js

Uncaught TypeError: Cannot read property 'apply' of undefined

function klass() {
(ln: 1690) --> this.initialize.apply(this, arguments);
}
