### ISSUE TITLE
Control objects do no receive mouseup correctly

### ISSUE THREAD

**Issue by k1w1** [fabricjs/fabric.js#7452]
## Version
4.5.0

During MouseUp event handling the control `corner` is looked up again based on the current mouse position https://github.com/aha-app/fabric.js/blob/v4.5.0/src/mixins/canvas_events.mixin.js#L459. This is a problem in any case where the mouse is not over the control when it is released - in those cases the `mouseUpHandler` function on the control is never called.

Why might the mouse not be over the control? In any situation where the motion of the control is constrained, e.g. with snap to grid, or some other constraint, where the control does not move perfectly in sync with the mouse.

The simple solution appears to be to use the corner that was computed during the mouse down, e.g.

```var corner = target.__corner;```

**Comment by asturur** [comment]
i think you are perfectly right.
It sounds correct that both controls should fire a mouseup.
Maybe we can add a property to the event to signal which one is under the corsor and which one is just `released`
