### ISSUE TITLE
`canvas.viewportTransform` (scale bug)

### ISSUE THREAD

**Issue by suncs2001** [fabricjs/fabric.js#7471]
## Version
3.6.0

## Information about environment
Nodejs or browser?
browser
Which browsers?
chrome
## Steps to reproduce
1、
canvas = document.getElementById('canvas')
let context = this.canvas.getContext('2d')
context.transform(1, 0, 0, -1, 0, canvasHeight)
2、 zoom in or zoom out the canvas 
3、 mouse move
## Expected Behavior
when mouse move，in mouse move listener , the pos obtained by getPointer  is canvas pos
## Actual Behavior
pos.x is actual canvas position and it is correct,  but pos.y is incorrect

**Comment by ShaMan123** [comment]
Your issue doesn't provide enough context.
However, it seems you are directly manipulating the context. Which can cause many things if you don't own it 100%.
For example which context are you transforming? the top or the bottom/main? which is another way of asking which canvas did you obtain.
You should use `canvas.viewportTransform` or `setViewportTransform`

**Comment by suncs2001** [comment]
hi ShanMan, thanks for your replay. 
yes ,i should not use context transform but instead of  using fabricjs viewportTransform, and after that, the getPointer() function return the right value.
but i found that zoomToPoint() function did not support transform change, because vpt[1] and vpt[3] all use param 'zoom, that means if i call zoomToPoint() after viewportTransform([1,0,0,-1,0,height]), its transform back to [1,0,0, 1,0,0] again.
so i had to implement zoomToPoint() myself, i copy the source code of zoomToPoint(),  just modify "vpt[3] = value"  to "vpt[3] = -1 * value",   but there is a strange thing,  sometimes the object  added to canvas can not display.

i test it in codepan
https://codepen.io/suncs2001/pen/BadbyBP
i found that in fabricjs 1.6.2, it worked well, but in fabricjs 4.5.0, the circle can not display

**Comment by ShaMan123** [comment]
It's still unclear.
You should provide steps to reproduce.
I have no idea what your pen should show.
You should look at the demos to see how zoomToPoint works

**Comment by suncs2001** [comment]
i edit my pen again, and  it is easier to understand . from my pen , i do two things.  
1) make viewportTransfrom,  flip y axis.  
`canvas.setViewportTransform([1,0,0,-1,0, 400]);`	
2) draw a circle in (50,50)    
`  var circle = new fabric.Circle({
        top :  50, 
        left : 50, 
        radius : 50, 
        fill : 'red', 
        stroke: 'orange', 
        strokeWidth: 0.5 
      });
      canvas.add(circle);`

but in fabric4.5.0,  the circle can not display,   in fabric 1.6.2,  the circle can display correctly.   you can import different fabric version in setting->js

**Comment by ShaMan123** [comment]
Now I understand.
Take a look https://codepen.io/shaman123/pen/LYjojpE.
The bug lies in [`isOnScreen`](https://github.com/fabricjs/fabric.js/blob/eee20adc95c37beb4223ac61d3e6093510d52b58/src/mixins/object_geometry.mixin.js#L191). 
Logically, because you flip the y axis, I assume all `<` `>` calculations are broken.

**Comment by suncs2001** [comment]
thanks shaman123, it worked!
there is another FR as i had write before,  zoomToPoint() can not support flip y axis,  because in the implement of zoomToPoint(), 
`    zoomToPoint: function (point, value) {
      // TODO: just change the scale, preserve other transformations
      var before = point, vpt = this.viewportTransform.slice(0);
      point = transformPoint(point, invertTransform(this.viewportTransform));
      vpt[0] = value;
      **_vpt[3] = value;_**
      var after = transformPoint(point, vpt);
      vpt[4] += before.x - after.x;
      vpt[5] += before.y - after.y;
      return this.setViewportTransform(vpt);
    },`
  whether it is zoom in or zoom out, the zoom(by getZoom()) is always positive, so the parameter 'value' of  zoomToPoint function will also positive too. so if vpt[3]=value, it means vpt[3] change to positive (before that, vpt[3] = -1 when i set viewPortTransform), and my flip y will fail

**Comment by ShaMan123** [comment]
I don't understand completely.
Try to PR

**Comment by asturur** [comment]
The issue is that we don't support flipping the viewport.
We support zoom > 0 and translate.

If we would add generic transform for viewport we could look into this.
