### ISSUE TITLE
Download canvas as image with online object image

### ISSUE THREAD

**Issue by samikoja** [fabricjs/fabric.js#7481]
## Version
3.6.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Steps to reproduce
add image with https src to canvas and try to download it, but it failed with the below error:
Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

**Comment by samikoja** [comment]
Thank you I find a solution

**Comment by harryngdev** [comment]
@samikoja  Hi! What is your solution?

**Comment by asturur** [comment]
That error message is a CORS issue.
https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

**Comment by railway17** [comment]
> Thank you I find a solution

Hey, @samikoja 
Seems like you found a solution, but it was a long time ago.
Could you please share your solution with us here?

**Comment by samikoja** [comment]
Hey, what I did is save the image on S3 or any online server that stores files, then add permission to let our domain access this server, or you can keep it public; it is up to you how you want. 

I’ve updated the workflow to handle images as follows:

- Upload the image directly to S3 (or any external file storage).
- Configure permissions to allow access from our domain (or keep it public, depending on preference).
- Retrieve the image from S3 and render it on the canvas.
- Process the image and download it without any issues.

Everything is working smoothly with this setup.

**Comment by asturur** [comment]
@railway17 https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CORS
Please get a primer on CORS here too. You will need for images and canvas processing

**Comment by samikoja** [comment]
> [@railway17](https://github.com/railway17) https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CORS Please get a primer on CORS here too. You will need for images and canvas processing

if the s3 is public or have access to specific domain the cors error didn't appear

**Comment by asturur** [comment]
Yes but from how @railway17 posted the question it looks like this is his first contact with CORS issues. better to have a larger understanding of what `public` ( anonymous ) means, and what `useCredentials` is
