### ISSUE TITLE
Cannot resize objects, unless they are interactively grouped with another object first

### ISSUE THREAD

**Issue by tardisx** [fabricjs/fabric.js#7485]
## Version
4.6.0

## Test Case
https://jsfiddle.net/gtkjmuqb/10/

## Information about environment
Reproduced with Chrome and Safari.

## Steps to reproduce
See jsfiddle above.

If I create a single text object, it can be selected, but only moved, not resized or otherwise edited.

If I create another object, then group the two (and then ungroup them again), the resize controls work correctly.

I feel sure this is some sort of bad interaction with alpine.js, but I don't have any idea how, or how I might debug it. The test case is very simple, both with respect to alpine and fabric.js.

## Expected Behavior

I can resize new objects.

## Actual Behavior

Objects cannot be resized unless I group them with another object, then ungroup them again.

**Comment by asturur** [comment]
Hi @tardisx the fiddle shows the issue clearly.
What alpinejs is doing? there is no link no explanation.
Can you try to explain what alpinejs is doing without me having to do a research?

**Comment by tardisx** [comment]
I don't know, to be honest. 

The entire code is so basic I can only assume that somehow alpine is causing a problem - there's no other complexity there at all. I use alpine to create the fabric objects on button press, that's all.

**Comment by asturur** [comment]
my question was more, what is alpine.js? i don't know it, i think is fine not knowing it, i was expecting you to give me some context.

**Comment by tardisx** [comment]
Sorry @asturur.

Alpinejs is a JavaScript framework for creating dynamic web pages. 

I don't have any particular reason to suspect it, but the rest of the code is so trivial that it is my only real suspect. 

Of course I could use jquery or just JavaScript to trigger fabric object additions, but the rest of my app uses alpine and I would like to have them work together. 

It's also possible that this is unrelated to alpine, but as you can see, the actually fabric related parts of the code are completely trivial. 

So - in my example, alpine is simply used to watch for button clicks to add text objects.

**Comment by tardisx** [comment]
I have dug further and discovered that this only occurs if the canvas object is managed by alpine (ie in the x-data component).

In this fiddle I have moved it out to a global variable and as you can see things work correctly.

https://jsfiddle.net/6negfhv0/3/

I am guessing that something that alpine attaches to the canvas object to observe for changes is subtly breaking it.

I'm still unsure where this bug might be and whether it's worth investigating.

**Comment by asturur** [comment]
Sorry for not being responsive. Probably alpine wrap the canvas in a proxy and break something.
Glad you figured it out.

**Comment by Faseeh-Hassan** [comment]
```
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="//unpkg.com/alpinejs" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/fabric@4.6.0/dist/fabric.min.js"></script>
  </head>

  <body class="">
    <main role="main" class="" style="height:100%;" x-data="editor()" x-init="setup_canvas();">
      <p>
        Click to add a text object. You can move but not resize that object until you add a second text object, group them (click drag) and ungroup them again:<br>
        <button type="button" id="Add_Text" @click="add_some_text()" class="btn btn-primary">Add text</button>

      </p>
      <canvas id="c"></canvas>
    </main>
    <footer class="mastfoot mt-auto">
      <div class="inner">

      </div>
    </footer>
    <script>
      const canvas = new fabric.Canvas('c');
      document.getElementById("Add_Text").addEventListener("click", function() {
        const text = new fabric.IText("My Text", {
          left: 70,
          top: 200,
          fontSize: 30,
          fill: 'black'
        });
        canvas.centerObject(text);
        canvas.add(text);
        canvas.renderAll();
      }, false);

    </script>
  </body>

</html>
```

I have fixed your code You can use this code for add text

**Comment by neylwalecki** [comment]
Tks! You saved me! Claude code, Gemini and Codex, no AI was able to find this issue by themselves!
