### ISSUE TITLE
Image.fromURL doesn't load image sometimes

### ISSUE THREAD

**Issue by IgorSamer** [fabricjs/fabric.js#7487]
I have an Ionic (Angular) app and I noticed that the image I load from an URL seems to doesn't load sometimes. This behavior occurs in several devices that use the app and I don't know why.

I simply load the image, apply a clipPath to round the image and add to the fabric canvas element. I have already tried to add the image with only `this.canvasFabric.add(image)` and with `this.canvasFabric.add(image).requestRenderAll()` too, but both seems to have the same behavior that is: sometimes the image is loaded and shown, but sometimes doesn't.

In most commonly cases, when the image stops loading I have to uninstall and reinstall the app a couple times to get it back to load properly again. In my code I simply load the canvas and call `fabric.Image.fromURL` function exactly like the following code:

```
fabric.Image.fromURL(url, (image) => {
  image.scaleToHeight(50);

  image.set({
    top: 0,
    clipPath: new fabric.Rect({ width: image.height, height: image.height, rx: image.width, ry: image.height, originX: 'center', originY: 'center' }),
    shadow: new fabric.Shadow({ color: 'rgba(0, 0, 0, 0.5)', blur: 100 })
  });

  this.canvasFabric.add(image).requestRenderAll();
  image.centerH();
}, { crossOrigin: 'anonymous' });
```

Could it be a problem related to cache or something like this? (since uninstalling and reinstalling the app a couple times it works again)

Any ideia how can I solve this or how can I handle with any errors that can occur in `fromURL` method?

Any additional information I can give to solve this, let me know. Thanks in advance.

**Comment by SalahAdDin** [comment]
@IgorSamer Did you solve this issue?

**Comment by yogaaltariz** [comment]
@SalahAdDin it happened to me too, but I got around it by using the constructor of fabric.Image instead of fabric.Image.fromURL

**Comment by asturur** [comment]
Guys if you can't load an image you get a network error somewhere. What does the error says?

**Comment by yogaaltariz** [comment]
@SalahAdDin  here is the code

` 

    const img = new Image()

    img.onload = () => { 
        const imgObj = new fabric.Image(img, {
            centeredRotation: true,
            centeredScaling: true,
            scaleX: 1,
            scaleY: 1,
            perPixelTargetFind: false
        });


        canvas.add(imgObj);
    }

    if (crossOrigin) { 
        img.crossOrigin = crossOrigin;
    }

    img.src = src;`

**Comment by yogaaltariz** [comment]
@asturur in my case it won't work in UC Browser, there is no error shows, only blank canvas

**Comment by asturur** [comment]
Well that is not how loading images works, something went wrong or you didn't load the image or you didn't wait for it to load.

**Comment by SalahAdDin** [comment]
> Well that is not how loading images works, something went wrong or you didn't load the image or you didn't wait for it to load.

can you elaborate it more in detail, please?

**Comment by asturur** [comment]
Where are you loading the image from?
A file on the disk? or an http link? a base64 encoded url?

Those either load or fail. If they fail they leave a track.
If there is no trace of failure the image loaded.

Coming in a issue of 2021 in 2024 and saying 'me too' is not helpful for you.
You didn't provide a snippet of code or what are you doing or what your code looks like.
Not even what version of fabricJS you are using.

**Comment by SalahAdDin** [comment]
> Where are you loading the image from? A file on the disk? or an http link? a base64 encoded url?
> 
> Those either load or fail. If they fail they leave a track. If there is no trace of failure the image loaded.
> 
> Coming in a issue of 2021 in 2024 and saying 'me too' is not helpful for you. You didn't provide a snippet of code or what are you doing or what your code looks like. Not even what version of fabricJS you are using.

I am not working on this anymore, I don't have access to the code or remember the specific case. I would like to help people which the same issue.

**Comment by asturur** [comment]
Yes i was answering to @yogaaltariz i think

**Comment by sudolee** [comment]
> [@SalahAdDin](https://github.com/SalahAdDin) here is the code  这是代码
> 
> `
> 
> ```
> const img = new Image()
> 
> img.onload = () => { 
>     const imgObj = new fabric.Image(img, {
>         centeredRotation: true,
>         centeredScaling: true,
>         scaleX: 1,
>         scaleY: 1,
>         perPixelTargetFind: false
>     });
> 
> 
>     canvas.add(imgObj);
> }
> 
> if (crossOrigin) { 
>     img.crossOrigin = crossOrigin;
> }
> 
> img.src = src;`
> ```

this work for me with "fabric": "^6.5.3"
