### ISSUE TITLE
A group containing a video does not play the video

### ISSUE THREAD

**Issue by graphics-et-al** [fabricjs/fabric.js#7496]
Version
4.6.0

Test Case
https://jsfiddle.net/wilheim/ju4y3az7/4/

Information about environment
Browser

Steps to reproduce
Insert a video as per instructions at http://fabricjs.com/video-element, add something else, group them.

Expected Behavior
Video (or other animation) continue to play in the group

Actual Behavior
Video stops/pauses

Note- this seems to happen with the Lottie plugin too. Basically anything that's moving on the screen stops when it's part of a group. See https://jsfiddle.net/wilheim/breg1v7k/12/ for another example

**Comment by Hammer-Inc** [comment]
Disabling object caching on the group should fix this :)
```
document.querySelector("#groupBtn").onclick = () => {
   const group  = canvas.getActiveObject().toGroup();
   group.set('objectCaching', false)
}
```

**Comment by graphics-et-al** [comment]
> Disabling object caching on the group should fix this :)
> 
> ```
> document.querySelector("#groupBtn").onclick = () => {
>    const group  = canvas.getActiveObject().toGroup();
>    group.set('objectCaching', false)
> }
> ```

Hey, it works! Thanks Internet Stranger!
