### ISSUE TITLE
How to achieve multiple selection of objects in fabric version ( 1.7.3 )

### ISSUE THREAD

**Issue by meetgoyani007** [fabricjs/fabric.js#7512]
fabricr.js version(s):
- 1.7.3

**The browser and operating system version(s):**
- **OS**:All

- **Browser:** All

I try below code for multiple object selection.

```
var sel = new fabric.ActiveSelection(canvas.getObjects(), {
          canvas: canvas,
        });
        canvas.setActiveObject(sel);
        canvas.requestRenderAll();
```
 
But this method return error that ActiveSelection is not constructor.

Please let me know how can I resolve this error or any other solution for select multiple objects.

Thanks

**Comment by asturur** [comment]
There wasn't ActiveSelection in 1.7.3, there was just Group, and was create with some flags.
We can't offer support for this old version, try to read in the events-mixin files how this was done
