### ISSUE TITLE
canvas.off() with a handler does not remove that listener

### ISSUE THREAD

**Issue by nickatrons** [fabricjs/fabric.js#7513]
When unassigning an event with a handler, it does not work as intended.

_removeEventListener looks in __eventListeners with .indexOf with a function, and it cannot do that, so it will return -1 as array position, thus resulting in the event not being taken out

Ive edited the function so it works, with this

`/**
   * @private
   * @param {String} eventName
   * @param {Function} handler
   */
  function _removeEventListener(eventName, handler) {
    debugger
    if (!this.__eventListeners[eventName]) {
      return;
    }
    var eventListener = this.__eventListeners[eventName];
    if (handler) {
      console.log(eventListener.indexOf(handler)) //Returns -1 
      console.log(eventListener[eventListener.indexOf(handler)]) //Cannot find the handler
      console.log(eventListener.map(f => f.name).indexOf(handler.name)) // Will find the correct position
      // eventListener[eventListener.indexOf(handler)] = false;
      eventListener[eventListener.map(f => f.name).indexOf(handler.name)] = false;
    }
    else {
      fabric.util.array.fill(eventListener, false);
    }
  }
`
<img width="875" alt="Screen Shot 2021-11-22 at 9 45 31 PM" src="https://user-images.githubusercontent.com/8882518/142936544-a3643fed-6024-4b83-818d-51e7ef973281.png">

<img width="1032" alt="Screen Shot 2021-11-22 at 9 55 18 PM" src="https://user-images.githubusercontent.com/8882518/142936073-20a60749-577b-48d0-8f45-b3f5d3f155fe.png">

## Version
4.6.0

## Test Case
http://jsfiddle.net/x6u4wyb5/

## Information about environment
Nuxt 2.15.7
All browsers

## Steps to reproduce
See fiddle 

## Expected Behavior
example
canvas.off('mouse:down', handler) removes the eventlistener with this handler

## Actual Behavior
It does not remove it

**Comment by asturur** [comment]
You are generating new events functions every time you click on the button, so if one click presses down and add events, the other presses up, you can't remove the events anymore.

You have to use a pattern like useEffect from react, where the function that register events, will return a callback that will cancel the current event, that are still in scope.
