### ISSUE TITLE
Clone object in Version(1.7.3)

### ISSUE THREAD

**Issue by meetgoyani007** [fabricjs/fabric.js#7519]
Hello,

I use fabric version 1.7.3 and i want to clone objects which are selected in group.But when I resized that group and try to clone that time I get objects as before the resizing.

So please let me know where I am wrong?

**Comment by asturur** [comment]
We support only the last version.
Please try to migrate to 4.6.0
Or at least try to show how are you cloning things.
I will reopen the issue if better description comes.
