### ISSUE TITLE
Issue with object id and canvas undo

### ISSUE THREAD

**Issue by Shilpa-K07** [fabricjs/fabric.js#7521]
I'm assigning id to objects in canvas like this,
 this.canvas.add(
          new fabric.Rect({
            id: "rect",
            left: 10,
            top: 10,
            width: 100,
            height: 50,
            fill: "",
            strokeWidth: 1,
            stroke: "gray",
         })
 );
But I'm loosing this id after performing canvas.undo();
How can I retain this id ?

**Comment by lagmanzaza** [comment]
Please provide step to reproduce

**Comment by Shilpa-K07** [comment]
Steps to reproduce:
----------------------

1> Create canvas instance:

<canvas ref="canvas"></canvas>

var canvas = this.$refs.canvas;
this.canvas = new fabric.Canvas(canvas, {
      width: 390,
      height: 560,
      backgroundColor: "white",
      top: 20,
      left: 20,
      preserveObjectStacking: true
    });
	
2> Add objects to canvas

	this.canvas.add(
	new fabric.Rect({
	id: "rect-1",
	left: 10,
	top: 10,
	width: 100,
	height: 50,
	fill: "",
	strokeWidth: 1,
	stroke: "gray",
	})
	);
	
	this.canvas.add(
	new fabric.Rect({
	id: "rect-2",
	left: 10,
	top: 10,
	width: 100,
	height: 50,
	fill: "",
	strokeWidth: 1,
	stroke: "gray",
	})
	);
	
3> Get all the objects and you can see Id property
	var objects = this.canvas.getObjects();
	objects.forEach((obj) => {
	console.log(obj.id)     // prints id ( rect-1 , rect-2)
	});
	
4> Then do this.canvas.undo();
	var objects = this.canvas.getObjects();
	objects.forEach((obj) => {
	console.log(obj.id)     // prints undefined. Id property is missing
	});

**Comment by lagmanzaza** [comment]
As I know fabricjs doesn't have feature to undo, do you use another plugin?

**Comment by Shilpa-K07** [comment]
No, I'm not using any other plugin.

**Comment by Shilpa-K07** [comment]
This issue is not specific to undo operation. Whenever canvas.on("object:modified") event is called, object looses its custom properties.

**Comment by Shilpa-K07** [comment]
'fabric-history' is used to perform undo

**Comment by asturur** [comment]
@Shilpa-K07 you can rewrite the toObject method to always include your properties.

```
const original = fabric.Object.prototype.toObject;

 fabric.Object.prototype.toObject = function(additionalProps) {
   return original([...additionalProps, 'my', 'id', 'and', 'other', 'stuff'])
}
```
