### ISSUE TITLE
How to select the right area of the polygon

### ISSUE THREAD

**Issue by zjlzlr** [fabricjs/fabric.js#7527]
## Version
4.2.0

## Test Case
http://fabricjs.com/custom-controls-polygon

## Information about environment
Nodejs or browser?
Which browsers?
chrome
## Steps to reproduce
<img width="660" alt="11" src="https://user-images.githubusercontent.com/8189294/144173105-eb9d983c-ae9e-445c-bd4e-a636d9a63298.png">

## Expected Behavior
I hope select the box when I click the point in the box

## Actual Behavior
When I click the white area of the box side,the box can be chosen

**Comment by asturur** [comment]
Can you epxlain a little bit better what is not working. Those are the actual constrains:

You can select a shape where is not EMPTY pixels using `perPixelTargetFind: true`
if not, the object selection will happen in the bounding box of the object.

**Comment by ShaMan123** [comment]
Are you looking for the ray casting algorithm?

**Comment by heaxo** [comment]
> 您正在寻找射线投射算法吗？

Hi, I'm looking for a ray casting algorithm

> Are you looking for the ray casting algorithm?

Hi, I'm looking for a ray casting algorithm
