### ISSUE TITLE
Error using unicodes "0x1f5a7" and "0x1f517" in Textbox

### ISSUE THREAD

**Issue by Shilpa-K07** [fabricjs/fabric.js#7539]
I'm trying to use unicodes "0x1f5a7" (Three Networked Computers) and "0x1f517"(Link Symbol) inside TextBox of fabric.js. While doing so I'm getting below error:

"High surrogate without following low surrogate"

Link to StackOverflow 
https://stackoverflow.com/questions/70245822/error-using-unicodes-0x1f5a7-and-0x1f517

**Comment by Shilpa-K07** [comment]
Unicode: 0x1f517
![image](https://user-images.githubusercontent.com/70196456/144965099-e1715199-2a1d-460a-bbe2-5342f4ba81bc.png)
 
Unicode: 0x1f5a7
![image](https://user-images.githubusercontent.com/70196456/144965181-e376c452-2ee7-4985-87d0-c08252cbf309.png)

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/145115757-355e3591-4605-4525-bc17-c76c8f9cbb2e.png)

seems working to me

**Comment by Shilpa-K07** [comment]
I'm facing issue if these two unicodes are added without any space, dot or character in between

**Comment by asturur** [comment]
can you show me how they render in normal web page and how those render in fabric in the same browser?
