### ISSUE TITLE
Impact Font not loading on mobile devices

### ISSUE THREAD

**Issue by Jsbbvk** [fabricjs/fabric.js#7543]
## Version
3.6.0

## Test Case
Visit codepen on mobile device
https://codepen.io/Jsbbvk/pen/KKXNPYO

## Information about environment
Mobile device (Browser)

## Steps to reproduce
Create IText with Impact font

## Expected Behavior
Impact font displayed on mobile

## Actual Behavior
Times New Roman font displayed on mobile

**Comment by asturur** [comment]
Are you sure the Impact font is available in your mobile device?
Can you render an HTML file with the IMPACT font?
