### ISSUE TITLE
Browser default font applied in text

### ISSUE THREAD

**Issue by vijaygurjar** [fabricjs/fabric.js#7546]
Hi,
I applied Byzantine font to text and its style is differ than which is visible on canvas. a-z characters style are proper but when i use number or special characters it is not applied properly. Browser default font applied on numbers and special characters. How can i stop default font apply
I am attaching screen shot of both case. Please guide me if any solution

1) below image is actual font looks like
![Byzantine1](https://user-images.githubusercontent.com/15196898/145839363-875d9d8c-a1e7-4e88-95f1-eab7d70f13e9.png)

2) Below image fabricjs canvas font rendering
![Byzantine](https://user-images.githubusercontent.com/15196898/145839367-ce92d3fc-0c8d-4f78-97f7-e5dae0a80545.png)

**Comment by asturur** [comment]
Those numbers are very weird to be part of the bizantine font.
Do you have a link to the font?
