### ISSUE TITLE
fabric.js issues running in shadow DOM

### ISSUE THREAD

**Issue by eliasewel** [fabricjs/fabric.js#7555]
I'm currently working on a drawing tool in form of a web component encapsulated in a Shadow DOM. I have a problem with initiating the fabric canvas. I have tried to pass both the id as a string and the html element but nothing happens. 
When I turn of the Shadow DOM encapsulation it works.
Is there a way to get around this?

canvas = new fabric.Canvas('canvas', {});

**Comment by asturur** [comment]
@eliasewel not sure if you solved it or not.
Sadly i m not great with the Shadowdom.
Can you provide a code sample that fails?

**Comment by eliasewel** [comment]
Hi! I have solved the issue. Had nothing to do with fabric. Closing the issue
