### ISSUE TITLE
Getting a.colorProperties is undefined issue with text animation.

### ISSUE THREAD

**Issue by ssubham** [fabricjs/fabric.js#7560]
## Version
>4.1.0

## Test Case
https://codepen.io/ssubham/pen/bGoRJJP

## Information about environment
Nodejs or browser? browser
Which browsers? firefox(mozilla)

## Steps to reproduce
Try to give any animation to the text.

## Expected Behavior
Text should get some animation.

## Actual Behavior
Getting Error of a.colorProperties is undefined

**Comment by ssubham** [comment]
> ## Version
> 
> > 4.1.0
> 
> ## Test Case
> 
> https://codepen.io/ssubham/pen/bGoRJJP
> ## Information about environment
> 
> Nodejs or browser? browser Which browsers? firefox(mozilla)
> ## Steps to reproduce
> 
> Try to give any animation to the text.
> ## Expected Behavior
> 
> Text should get some animation.
> ## Actual Behavior
> 
> Getting Error of a.colorProperties is undefined

Got it working with latest fabric.js
Please close this.

**Comment by asturur** [comment]
please setup your fiddle with the animation already set up, and let the error happen, so we can read it.
