### ISSUE TITLE
An error is reported after the canvas setting width and height are too large

### ISSUE THREAD

**Issue by simplte** [fabricjs/fabric.js#7562]
## Version
3.6.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment

mobile browsers

## Steps to reproduce
set canvas width  5000
set canvas height 5000
canvas.toDataURL()

error mssage:
Array.from requires an array-like object - not null or undefined

I hope the author will help me, this is very important to me, and I look forward to receiving your reply

**Comment by asturur** [comment]
hi @simplte without a reproducible use case we can't do much.
5000 is well inside the canvas allowed sizes.
