### ISSUE TITLE
Canvas toSvg gets wrong matrix calculations on Windows device only (creates white space)

### ISSUE THREAD

**Issue by AivarsA** [fabricjs/fabric.js#7563]
Hello! Maybe this has already been discussed before but I was not able to find an solution for this strange issue.

I have created 2 identical canvases and then converted them both to SVG (canvas.toSVG()) - one on Linux and the other on Windows devices.
Linux result - 
![Screenshot from 2021-12-27 19-05-20](https://user-images.githubusercontent.com/16277153/147492951-d6f8af1b-6bcb-4b2e-b064-5d600ed37e25.png)
Windows result -
![Screenshot from 2021-12-27 19-05-43](https://user-images.githubusercontent.com/16277153/147492953-3405ccdc-c358-414a-ba0b-bdc0769a3b67.png)

Can see that in the Linux result this generated SVG image starts at the top of the page but for Windows device, there is a slight gap between the top and where the canvas really starts (In screenshot see where browser scrollbar is and where canvas starts in both cases). Can see that there is white space created. I noticed that everything is identical for both canvas, except the only difference is between <g transform="matrix(....) (also can be seen in screenshot).

Can someone please explain how to solve this? Like I said - this issue is only if I save my canvas to SVG from Windows device and the only difference is in calculated matrix values, everything else is identical. What is the reason why from Windows device it calculates it differently and creates this "white space" and how to remove it?

Fabricjs Version: 4.3.1.

Thank you!

**Comment by asturur** [comment]
hi @AivarsA , you should provide the canvas data to generate this SVG.
a loadable JSON would be enough.
