### ISSUE TITLE
Why does the line of the rotation point become like this after I set flipX?

### ISSUE THREAD

**Issue by maoweifan** [fabricjs/fabric.js#7565]
## Version
`fabric@4.6.0`

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Nodejs or browser? browser 
Which browsers? chrome@ 96.0.4664.110 (arm64) 

## Actual Behavior

<img width="288" alt="Snipaste_2021-12-30_15-55-09" src="https://user-images.githubusercontent.com/51221758/147732681-f331d1dc-b415-4b01-b7f3-b06a45dd174b.png">

**Comment by ShaMan123** [comment]
You didn't provide a repro.
If you are using flipX on canvas vpt that is the reason #7515

**Comment by asturur** [comment]
the control flip is fixed via 
https://github.com/fabricjs/fabric.js/commit/d277016c491be8367cc052739b5deccd4733cf20
