### ISSUE TITLE
Custom Controls in Typescript

### ISSUE THREAD

**Issue by dmdum** [fabricjs/fabric.js#7569]
Hello, I'm new to fabricjs. I'm referring to this Custom controls, polygon demo (http://fabricjs.com/custom-controls-polygon) to create an editable polygon in angular. I'm having trouble converting this to TS, specifically when it adds the **pointIndex** property to the Control class, and accessing it in the **polygonPositionHandler** function. I get the error: `Object literal may only specify known properties, and 'pointIndex' does not exist in type 'Partial<Control>'.`

Any kind of help/links to read would be greatly appreciated. Thanks!

**Comment by dmdum** [comment]
I was able to add properties to other object by extending the interface they were implementing but I can't really do that with the Control class

**Comment by dmdum** [comment]
The workaround we did for this was to bind the variable like this:
`positionHandler: this.polygonPositionHandler.bind({ positionIndex: index })`

**Comment by asturur** [comment]
mmm ok is because Typescript forbid you to add random properties to objects?
I m sure there is a way to solve that, maybe overriding the control as any.
Not sure what the bind statement is doing here.
