### ISSUE TITLE
Different with opacity of object and object in group

### ISSUE THREAD

**Issue by rkawkxkdwlq** [fabricjs/fabric.js#7570]
## Version
4.3.1

## Capture
![image](https://user-images.githubusercontent.com/24672968/147905987-b1abfc96-6291-4800-a5e5-aefb2b05363b.png)
ungrouped!

![image](https://user-images.githubusercontent.com/24672968/147905991-5b32db84-ecf4-4358-9dc7-573664d9c179.png)
grouped!

## Comment
the squre's opacity is 0.5
and when i make group with other object rect's color opacity view be changed.
but that rect's opacity value still 0.5 and group's opacity is 1.
only view changed.
and it will go back to correct opacity view when ungrouped

**Comment by ShaMan123** [comment]
This is interesting
please provide a working repro
