### ISSUE TITLE
Problem between versions about _renderChars function of yours

### ISSUE THREAD

**Issue by okeoke85** [fabricjs/fabric.js#7571]
It is probably occurs in more functions of latest version, i installed latest version of fabric and i constatntly get the error below when i try to load canvas from json, it is a basic json which includes just fabric.Text, i added below, i delibaretly downgrade my fabric version to 3.6.4 to get rid of 'ctx.canvas.setAttribute(...)' calls and it worked fine, but i want to use latest version of fabric, i'm trying to load canvas from JSON on node side, canvas is already installed on node. 

JSON:

`{"version":"4.6.0","objects":[{"type":"text","version":"4.6.0","originX":"left","originY":"top","left":100,"top":100,"width":55.61,"height":45.2,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeDashOffset":0,"strokeLineJoin":"miter","strokeUniform":false,"strokeMiterLimit":4,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","skewX":0,"skewY":0,"fontFamily":"Arial","fontWeight":"normal","fontSize":40,"text":"foo","underline":false,"overline":false,"linethrough":false,"textAlign":"left","fontStyle":"normal","lineHeight":1.16,"textBackgroundColor":"","charSpacing":0,"styles":{},"direction":"ltr","path":null,"pathStartOffset":0,"pathSide":"left"}]}`

Error:
```
>  TypeError: ctx.canvas.setAttribute is not a function
>      at klass._renderChars (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:26297:20)
>      at klass._renderTextLine (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:25877:12)
>      at klass._renderTextCommon (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:26222:14)
>      at klass._renderTextFill (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:26244:12)
>      at klass._renderText (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:25829:14)
>      at klass._render (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:25814:12)
>      at klass.drawObject (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:15176:12)
>      at klass.render (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:15034:14)
>      at klass.callSuper (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:2810:22)
>      at klass.render (C:\Development\hemsor\ticore\node_modules\fabric\dist\fabric.js:26764:12)
```

it is about 

 ctx.canvas.setAttribute(...) call

fabric 4.6.0 call of 

```
    _renderChars: function(method, ctx, line, left, top, lineIndex) {
      // set proper line offset
      var lineHeight = this.getHeightOfLine(lineIndex),
          isJustify = this.textAlign.indexOf('justify') !== -1,
          actualStyle,
          nextStyle,
          charsToRender = '',
          charBox,
          boxWidth = 0,
          timeToRender,
          path = this.path,
          shortCut = !isJustify && this.charSpacing === 0 && this.isEmptyStyles(lineIndex) && !path,
          isLtr = this.direction === 'ltr', sign = this.direction === 'ltr' ? 1 : -1,
          drawingLeft;

      ctx.save();
      top -= lineHeight * this._fontSizeFraction / this.lineHeight;
      if (shortCut) {
        // render all the line in one pass without checking
        // drawingLeft = isLtr ? left : left - this.getLineWidth(lineIndex);
        ctx.canvas.setAttribute('dir', isLtr ? 'ltr' : 'rtl');
        ctx.direction = isLtr ? 'ltr' : 'rtl';
        ctx.textAlign = isLtr ? 'left' : 'right';
        this._renderChar(method, ctx, lineIndex, 0, line.join(''), left, top, lineHeight);
        ctx.restore();
        return;
      }
```

fabric 3.6.4 call that doesnt include  'ctx.canvas.setAttribute(...) call'

```
    _renderChars: function(method, ctx, line, left, top, lineIndex) {
      // set proper line offset
      var lineHeight = this.getHeightOfLine(lineIndex),
          isJustify = this.textAlign.indexOf('justify') !== -1,
          actualStyle,
          nextStyle,
          charsToRender = '',
          charBox,
          boxWidth = 0,
          timeToRender,
          shortCut = !isJustify && this.charSpacing === 0 && this.isEmptyStyles(lineIndex);

      ctx.save();
      top -= lineHeight * this._fontSizeFraction / this.lineHeight;
      if (shortCut) {
        // render all the line in one pass without checking
        this._renderChar(method, ctx, lineIndex, 0, this.textLines[lineIndex], left, top, lineHeight);
        ctx.restore();
        return;
      }
```

## Version
3.6.0

## Test Case
http://jsfiddle.net/fabricjs/Da7SP/

## Information about environment
Nodejs or browser?
Which browsers?

**Comment by asturur** [comment]
That is weird.
We do execute tests on node and we do use RTL/LTR in testing that should trigger that setAttribute.
Can you provide a complete index.js that produce the error?
with requires and working code.

**Comment by okeoke85** [comment]
Thank you i will continue with 4.4.0 version for now.

Best Regards.

**Comment by asturur** [comment]
but we do need a test case. Do you have one?

**Comment by okeoke85** [comment]
Basically if try to load any json you will get the error on node side, with the latest version, if you cant get the error maybe it is about my environment, but with 4.4.0 i cant get the error, i dont know what can i say more. Just try to load below json on node side with fabric latest version and you shuld get the error; i hope it helps

`{"version":"4.6.0","objects":[{"type":"text","version":"4.6.0","originX":"left","originY":"top","left":100,"top":100,"width":55.61,"height":45.2,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeDashOffset":0,"strokeLineJoin":"miter","strokeUniform":false,"strokeMiterLimit":4,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","skewX":0,"skewY":0,"fontFamily":"Arial","fontWeight":"normal","fontSize":40,"text":"foo","underline":false,"overline":false,"linethrough":false,"textAlign":"left","fontStyle":"normal","lineHeight":1.16,"textBackgroundColor":"","charSpacing":0,"styles":{},"direction":"ltr","path":null,"pathStartOffset":0,"pathSide":"left"}]}`
