### ISSUE TITLE
feat(ci): PR git actions

### ISSUE THREAD

**Issue by ShaMan123** [fabricjs/fabric.js#7593]
I was thinking of adding git actions on PRs:
1. ~~when committing to the PR - build dist and commit to the PR, or use [codesandbox PR builder]~~ #8135 (https://codesandbox.io/docs/ci)
2. ~~when merging to master - checkout dist~~ new build, dist might be out for good
3. ~~lint commit action~~
4. ~~`Code Coverage Summary` comment bot - should remove it's prior comment from thread to avoid spamming, [action]~~(https://github.com/marketplace/actions/delete-comment)
5. action to update/build website on release - https://github.com/fabricjs/fabric.js/issues/7593#issuecomment-1086645759

**Comment by asturur** [comment]
if the git history does not get extremely polluted, that is fine for me. If deleting the branch after merge deletes the history with it.
Not sure if you can checkout dist when merging.

Not sure how the additional commit will eventually trigger new git actions that will trigger another build and so on.
Is the aim to have always a built file available somewhere?

**Comment by ShaMan123** [comment]
yes it is.
and not to do it manually.
3. lint commit action

**Comment by ShaMan123** [comment]
https://about.gitlab.com/blog/2018/06/07/keeping-git-commit-history-clean/

**Comment by ShaMan123** [comment]
a repo with outstanding ci 
https://github.com/bubkoo/html-to-image/blob/master/.github/workflows

**Comment by asturur** [comment]
Label your own issues if you want to avoid the stale bot to bother you

**Comment by ShaMan123** [comment]
I'm talking about the PR bots they have

**Comment by asturur** [comment]
i meant this thing here
![image](https://user-images.githubusercontent.com/1194048/152777503-7907ddf4-f274-43a4-993f-de34504cc8e5.png)

When you want to rise something you know is worth, give it a label so stale-bot does not come here

**Comment by ShaMan123** [comment]
great thanks

**Comment by ShaMan123** [comment]
https://github.com/marketplace/actions/trigger-workflow-and-wait

Triggering updates to fabricjs.com from fabric.js release workflow.
What do you think?
