### ISSUE TITLE
feat(ICollection): Deal with deselection after drag of multiple objects

### ISSUE THREAD

**Issue by ebigtm** [fabricjs/fabric.js#7597]
after the fix i presented yesterday a new issue popped, after dragging the objects it casts ray on the object the mouse up was on and selects it, the fix i found is a bit rough:
`var result = object.type == 'iCollection' ? object.onSelect({
        e: e,
        object: activeObject,
        subTargets: this.targets.filter(function (object) { return object.isSelectable(); }),
        activeSubTargets: object._objects.length > 0 ? true : subTargets && subTargets.filter(function (object) { return object.isSelectable(); })
      }) :
      object.onSelect({
        e: e,
        object: activeObject,
      });`

maybe it can be done differntly but generally i added a condition regarding the type, maybe we can use isCollection var instead?
https://github.com/fabricjs/fabric.js/blob/5571a3a597abae989ec872efb64583afa3e978f6/src/canvas.class.js#L1192-L1197

**Comment by ShaMan123** [comment]
I think we should try to maintain a list a features that need work regarding selection.
