### ISSUE TITLE
Editing text inside groups

### ISSUE THREAD

**Issue by kirill-konshin** [fabricjs/fabric.js#7598]
## Version
4.6.0

## Test Case

http://jsfiddle.net/pce9h6fv/6/

## Steps to reproduce

1. Open fiddle
2. Click "edit" (calls `text.enterEditing()`)
3. Type something

I am aware that IText editing is not supported when it's in groups https://github.com/fabricjs/fabric.js/issues/3787 and there are custom solutions like here: https://stackoverflow.com/questions/24449481/fabric-js-grouped-itext-not-editable, for example to create a temporary text node https://stackoverflow.com/a/67689690/5125659. 

But this is not very optimal.

I am wondering, if there's a way to route events from a group to particular text node, given that I know, there will be only one such node per group, or it will be more work that fake text node way?

I also attempted to set custom SVG background to IText node, in order to avoid groups at all, but this is not supported either: https://github.com/fabricjs/fabric.js/discussions/7297.

## Expected Behavior

Text is properly shown

## Actual Behavior

Text input is missing, yet the cursor is moving.

Additionally if group is rotated/moved during editing it leaves a cursor trail:

![image](https://user-images.githubusercontent.com/1530410/148826234-1739ba68-bbd6-4177-9e96-51e34e1ddbd6.png)

**Comment by ShaMan123** [comment]
Your barging through an open door.
Take a look at #7473 #7599 
They should fix your issues (I saw you raised another regarding group).
The plan is to rewrite group to support interacting with nested objects.

**Comment by kirill-konshin** [comment]
@ShaMan123 yep, I've had another ticket regarding groups, I'm glad you saw it too :)

What is the projected timeline for the collections? Are we talking months or weeks? It would be great to cleanup all our own hacks and workarounds...

**Comment by ShaMan123** [comment]
I saw weeks, hopefully quicker.
I would appreciate it if you would test it.
The more testers the faster it evolves.

**Comment by kirill-konshin** [comment]
@ShaMan123 sure, if you can provide some instructions how to migrate old code to new proposal, and the NPM build I can test it in my app.

**Comment by ShaMan123** [comment]
You can try 
```bash
npm i --save fabricjs/fabric.js/#layer-proposal
```

**Comment by kirill-konshin** [comment]
Surprisingly, I had a slightly better results with objectCaching: false on group/collection.

Group started to work exactly as intended, collection produced super weird results when rotated and text edited, seems like the sync between collection rotation and text rotation was broken: http://jsfiddle.net/dfuse/wampvrgn/48/

**Comment by kirill-konshin** [comment]
Here's the combined example: http://jsfiddle.net/dfuse/wampvrgn/77/

With `subTargetCheck:false` collection "kinda works" but I need to set it back to true while editing, but this allows to drag rect away from text...

https://user-images.githubusercontent.com/1530410/149010744-83035437-2364-4a30-80c6-ac3ada0f54f7.mp4

With `subTargetCheck:true` (middle) it works, but it's impossible to select the whole collection (if `strokeWidth > 0` then area around is clickable).

**Comment by kirill-konshin** [comment]
Please disregard previous comments, I was exploring and writing as I go, so here's the proper summary of my experience.

After quite some time of reverse-engineering your PR, I've created a small fiddle for experiments first: http://jsfiddle.net/dfuse/wampvrgn/113/ (CDN used for fabric: https://cdn.jsdelivr.net/gh/fabricjs/fabric.js@layer-proposal/dist/fabric.js) but the problem is all items in the Layer (and ICollection) move as separate (I guess that's intentional).

With `group.subTargetCheck = false` collection "works" as `Group` (e.g. rotates/moves as one) but I need to set it back to `true` dynamically in order to edit text.

But then I need to set `group.evented = false` because click on group/rect will cause a JS error, and `group.objectCaching = false` to prevent text to appear in random place during editing.

Also I've figured that I have to call `.set({...})` instead of assigning those properties directly.

The only issue now is that selection box around the collection is larger after text editing, even if `group.strokeWidth = 0`:

![image](https://user-images.githubusercontent.com/1530410/149018482-6cab8fce-c59b-4d9c-b73a-e58e2a7ecf80.png)

P.S. Surprisingly, I had a good results with `group.objectCaching = false` on regular `Group`: works OK, only cursor glitches and inability to select text/move cursor (since mouse events are not propagated to text).

**Comment by ShaMan123** [comment]
You are right about assigning via `set`
I will take a look.

**Comment by ShaMan123** [comment]
I will explain
Basically `subTargetCheck` is an optimization for edge cases such as `SprayBrush` when the collection contains thousands of objects and selection isn't needed. In this cases most of the logic is then skipped.
`objectCaching` and the fact that it seems that the nested objects chase the collection is to do with logic executing a frame after it should. I hope to get it fixed soon.
If you want to explore group try the branch of #7599 (`ShaMan123:coords`)

Try this:
http://jsfiddle.net/k1xoLtgv/8/

**Comment by ShaMan123** [comment]
What error was raised?

**Comment by ShaMan123** [comment]
And if you want to try an alpha this is branch: `ShaMan123/group-selection`

**Comment by kirill-konshin** [comment]
> I think I fixed most of itext issues inside group.
> Could you test it?
> http://jsfiddle.net/ewzj24vy/

I don't see the code for editing, double click on group/text does not produce any effect :( so text is not editable in the demo.

I've added `collection.on('mousedblclick', () => text.enterEditing())` and it has all the same issues as in my fiddle (http://jsfiddle.net/dfuse/k9w8sdfy/ 3rd object — no ability to move cursor or make selection via mouse due to events capturing by the group).

> I have updated the fiddle:
> http://jsfiddle.net/cuv3b4o1/
> Tell me if it behaves as expected

Bounding box is still bigger as soon as I dragged the text.

![image](https://user-images.githubusercontent.com/1530410/149165171-4a4ae88e-f9d0-452c-b30f-ef204b6348af.png)

Expected behavior is shown in my fiddle http://jsfiddle.net/dfuse/k9w8sdfy/ (left shape) — double click to edit, click outside to exit editing, move/rotate/scale as one object (both text and rect). So user should not be able to drag text/rect individually.

> What error was raised?

If you comment `evented: false` in first `Rect` of my fiddle http://jsfiddle.net/dfuse/k9w8sdfy/ it used to produce error. Not anymore... did you change anything?

> And if you want to try an alpha this is branch: ShaMan123/group-selection

What is in there?

> ShaMan123:coords

And what's there? :) Sorry, I'm a bit confused, which branch contain which fix... :)

**Comment by ShaMan123** [comment]
There's no need to call `enterEditing`. It works out of the box.
I have changed many things. I guess the error was `setCoords` not being called at time.

Regarding branches and PRs, I think you got it mixed up.
#7599 is ShaMan123#coords. `ShaMan123/group-selection` is a fork for alpha dedicated to nested selection of objects inside groups.
#7473 is fabricjs#layer-proposal and is the PR that suggests a replacement for Group.

Now if you don't want the textbox to move use `lockXXX` where XXX is the property/action like `lockMovementX`
And if you've had it with collections/groups and need only a specific use case consider creating your own object that is cimposed of a rect and a textbox. It might save you time.

**Comment by kirill-konshin** [comment]
> There's no need to call enterEditing. It works out of the box.

Did not work for me... I was not able to enter editing. Can you elaborate?

> Now if you don't want the textbox to move use lockXXX where XXX is the property/action like lockMovementX

I've modified your fiddle http://jsfiddle.net/dfuse/t6L1msew/ — I wanted to make text non-selectable, same as regular group, by default, unless user double-clicks a group, it has to move/rotate/behave as one. So instead of locking, I just set `text.selectable = false` by default and on double click on collection I set it back to `true`, and the after editing back to `false`.

Now everything works exactly as intended w/o hacks with `subTargetCheck` and `objectCaching`.

The only issue is bounding box.

**Comment by ShaMan123** [comment]
Now I understand.
The cdn didn't update:
This works with Group: http://jsfiddle.net/tr2qh4vj/

Now you can use ICollection's `getLayoutStrategyResult` to decide how to calculate the bounding box

**Comment by ShaMan123** [comment]
I'd appreciate it if you keep track of issues/bugs and report to the relevant PR

**Comment by kirill-konshin** [comment]
> I'd appreciate it if you keep track of issues/bugs and report to the relevant PR

Sure, just add link to PR to fiddle as a comment for example?

> This works with Group: http://jsfiddle.net/tr2qh4vj/

When I drag text around it leaves artifacts:

![image](https://user-images.githubusercontent.com/1530410/149193413-12950d74-5397-4e6c-a39a-ebca5f3494fc.png)

I've forked your fiddle http://jsfiddle.net/dfuse/8vm0Leun/ and did the same as http://jsfiddle.net/dfuse/t6L1msew/ (collection). Works like charm, but I've added `objectCaching:false` to get rid of artifacts. And group version does not have the bounding box issue.

**Comment by ShaMan123** [comment]
> Sure, just add link to PR to fiddle as a comment for example?
yes with explanation and context, would help a lot

The artifacts are related to caching as you mentioned.
Another approach if caching is needed:
```js
text.on('changed', () => collection.set({dirty: true}));
```

**Comment by ShaMan123** [comment]
should close this issue once the PRs are merged

**Comment by kirill-konshin** [comment]
Tried `text.on('changed', () => collection.set({dirty: true}));` — it does the trick, but at some point artifacts still appear around the borders.

![image](https://user-images.githubusercontent.com/1530410/149195724-383faf34-c0bf-4e25-89d0-cad8646314ef.png)

In [your fiddle](http://jsfiddle.net/tr2qh4vj/) artifacts appear if text is either edited or moved around, so either same approach to set dirty on group is needed for other transformation (move,rotate,skew,scale) events or simple `objectCaching:false` to beat them all at once.

**Comment by kirill-konshin** [comment]
Overall, quite a solid solution with groups, thanks a lot. Solution with ICollection has only one issue with bounding box and also is very solid looking. Great job, thank you so much. Waiting for the merges...

We also will use layers extensively for other things, also very much awaited change.

@asturur tagging you just in case.

**Comment by kirill-konshin** [comment]
> Yes, I can see how these changes will unlock endless possibilities and make things much more simpler.

Layers at a very least make it possible to divide objects on helpers (visual cues, alignment helpers, various handles and so on) and actual interact-able objects (boxes, lines, shapes, etc). Possibilities are looking great.

Also simple Collections will allow to group/ungroup objects in a transparent way, w/o coordinates recalculation and so on. So it's just an actual semantic collection of things.

Groups on the other hand allow to combine objects and lock them together to act as one, and it's quite handy to work in relative coordinates sometimes.

After all it leaves ample amount of choice for developers to pick the best suitable solution.

**Comment by ShaMan123** [comment]
interesting, I was aiming to deprecate Group.
I'm looking into the relative coords.
I was against it surviving and still are. But the rendering process might need them.

**Comment by ShaMan123** [comment]
BTW ICollection should respect non-selectable objects and there's a possibility to override `onSelect` which is the function who decides what happens.

**Comment by kirill-konshin** [comment]
> I'm looking into relative coords.
> I was against it surviving and still am. But the rendering process might need them.

It's very handy because if you'll need to sync a state of a group to server, then in case of relative coords you will only sync own group properties, not touching children.

And in case of absolute coords all children will have to sync, so if group has 100 elements, it will be a huge update.

**Comment by ShaMan123** [comment]
That's a good point. Hmm, it is complicated. I'll give it another thought.

**Comment by kirill-konshin** [comment]
I've also noticed in group fiddle http://jsfiddle.net/dfuse/8vm0Leun/ that when I select both group and green box and drag green box — multiple selection breaks.

**Comment by kirill-konshin** [comment]
Not stale. Also, are there any updates?

**Comment by kirill-konshin** [comment]
Tried [v6](https://github.com/fabricjs/fabric.js/tree/v6) branch — http://jsfiddle.net/dfuse/fymku4zq/ working fine!

**Comment by ShaMan123** [comment]
@kirill-konshin try #7669 
I think we can close this off

**Comment by kirill-konshin** [comment]
Not stale, let's keep it open until V6 releases.

**Comment by joduplessis** [comment]
At least in the jsfiddle & 5.x version it still has a problem with making a selection of a subsection of the text. That's because the x & y point incorrectly references the textbox coordinates relative to the group (instead of an "absolute" position as is the case with standalone textbox) [here](https://github.com/fabricjs/fabric.js/blob/5c1240d8b4662e45868dd33f385f941de21c8e9c/src/shapes/Object/ObjectGeometry.ts#L790). Will get a fiddle together when I get a chance!

**Comment by asturur** [comment]
In v6 this should work just fine. Doesn't it?

**Comment by joduplessis** [comment]
@asturur haven't thoroughly checked - however the jsfiddle from [kirill-konshin](https://github.com/kirill-konshin) it doesn't make that sub-selection correctly.
