### ISSUE TITLE
Fabric object:added listener giving wrong value for top and left

### ISSUE THREAD

**Issue by Alexbitar1** [fabricjs/fabric.js#7604]
when duplicating a group of object using clone method the new objects are clone in the right places by giving them left and top but when the listener of object:added fires it return wrong values of top and left

var _clipboard=null;

canvas.getActiveObject().clone(function(cloned) {
		_clipboard = cloned;
	});
	// clone again, so you can do multiple copies.
	_clipboard.clone(function(clonedObj) {
		canvas.discardActiveObject();
		clonedObj.set({
			left: clonedObj.left + 10,
			top: clonedObj.top + 10,
			evented: true,
		});
		if (clonedObj.type === 'activeSelection') {
			// active selection needs a reference to the canvas.
			clonedObj.canvas = canvas;
			clonedObj.forEachObject(function(obj) {
				canvas.add(obj);
			});
			// this should solve the unselectability
			clonedObj.setCoords();
		} else {
			canvas.add(clonedObj);
		}
		_clipboard.top += 10;
		_clipboard.left += 10;
		canvas.setActiveObject(clonedObj);
		canvas.requestRenderAll();
	});
	
canvas.on("object:added", function (obj) {
//over here we get wrong values of top and left
      console.log("object:added", obj)
    })
## Version
3.6.0

## Steps to reproduce
run this function with while creating a selection of group of objects
## Expected Behavior
getting right values of top and right in object:added listener
## Actual Behavior
getting **NEGATIVE** values of top and right in object:added listener

**Comment by samikoja** [comment]
@Alexbitar1 Same here!!

**Comment by ShaMan123** [comment]
Group is very confusing because it translates it's objects relative to it's center.
This is why you are getting negative value.
This is horrible, confusing, frustrating. 
We are looking into replace it entirely.
But for the time being keep this in mind.
What you did in your code is how I would think fabric should work, it is the intuitive way.
However because of group's misbehavior you should:
```js
group.removeWithUpdate(obj); 
// or if you dont need the group:
group.destroy(); // or maybe group.ungroupOnCanvas()
canvas,add(obj);
```

**Comment by ShaMan123** [comment]
closing.
feel free to open a new issue and check out [discussions](https://github.com/fabricjs/fabric.js/discussions) for Q&A

**Comment by asturur** [comment]
a way to get the right top and left, is this:

```
fabric.util.transformPoint({ x: object.left, y: object.top }, object.group.calcTransformMatrix())
```
