### ISSUE TITLE
Polygon points editing with `strokeUniform: true`

### ISSUE THREAD

**Issue by goodbot13** [fabricjs/fabric.js#7605]
Set strokeUniform: true on polygon.
Scale it.
Try to edit points - polygon moves.

Source copied from http://fabricjs.com/custom-controls-polygon

## Version
4.6.0

## Test Case
https://jsfiddle.net/5jtu48n2/

**Comment by goodbot13** [comment]
> please provide an immediate repro

added. https://jsfiddle.net/5jtu48n2/

**Comment by ShaMan123** [comment]
You are right.
The example didn't take that into mind.
Welcome to PR.
It is probably a confusion between canvas/object coordinate plane (many bugs like this are)
Closing.

**Comment by ShaMan123** [comment]
So if understand correctly it's the calculation of `absolutePoint` and/or `setPositionByOrigin`.
Something there doesn't account for scaling.
But it's a guess.

**Comment by asturur** [comment]
Issues like this can be labelled as DOCS so they don't get harvested by the stale bot

**Comment by asturur** [comment]
yeah that example can use so much improvements

**Comment by goodbot13** [comment]
> yeah that example can use so much improvements

can we have some published? :)

**Comment by ShaMan123** [comment]
#7029 duplicate? Is this a bug?

**Comment by asturur** [comment]
is labeled as docs and probably the example should be fixed for the sake of showing that it should be doable

**Comment by goodbot13** [comment]
I came up with this solution.
The original source from fabric.js 4.6.0
```
/*
 * Calculate object dimensions from its properties
 * @private
 * @return {Object} .x width dimension
 * @return {Object} .y height dimension
 */
_getNonTransformedDimensions: function() {
  var strokeWidth = this.strokeWidth,
      w = this.width + strokeWidth,
      h = this.height + strokeWidth;
  return { x: w, y: h };
}
```

changed to this:
```
/*
 * Calculate object dimensions from its properties
 * @private
 * @return {Object} .x width dimension
 * @return {Object} .y height dimension
 */
_getNonTransformedDimensions: function() {
    var strokeWidth = this.strokeWidth,
        strokeUniform = this.strokeUniform,
        w = this.width + strokeUniform ? (strokeWidth / this.scaleX) : strokeWidth,
        h = this.height + strokeUniform ? (strokeWidth / this.scaleY) : strokeWidth;
    return { x: w, y: h };
},
```

And everything works fine.

**Comment by ShaMan123** [comment]
@goodbot13 is this a general fix for all fabric, could you PR?

**Comment by graphics-et-al** [comment]
This fix breaks polygon editing for me when applied. Is there an example where it works?

**Comment by ShaMan123** [comment]
indeed the fault is `_getNonTransformedDimensions` which should be deprecated ASAP.
I have updated the demo.
