### ISSUE TITLE
How to add snapping and guidelines in fabricjs?

### ISSUE THREAD

**Issue by hiteshrawat** [fabricjs/fabric.js#7613]
does anyone have script to implement snapping and guidelines like in https://posterilove.com/ for fabrcjs?

I am using fabricpublishertools.js but it is not like the above website.

asked on stackoverflow:
https://stackoverflow.com/questions/70727237/how-to-add-snapping-and-guidelines-in-fabricjs

**Comment by asturur** [comment]
there is a lib folder that contains a guidelines script i don't remember if those also provide snapping.
object has a snapping functionality on rotation you can enable on the properties

**Comment by graphics-et-al** [comment]
@hiteshrawat : [](https://github.com/yassilah/fabric-extensions/) is what you want. Plus bonuses!

**Comment by asturur** [comment]
yeah that seems good too

**Comment by hiteshrawat** [comment]
can

> @hiteshrawat : https://github.com/yassilah/fabric-extensions/ is what you want. Plus bonuses!

please provide pure js file or minified.js file as i am running directly in browser

**Comment by graphics-et-al** [comment]
> can
> 
> > @hiteshrawat : https://github.com/yassilah/fabric-extensions/ is what you want. Plus bonuses!
> 
> please provide pure js file or minified.js file as i am running directly in browser

https://cdn.jsdelivr.net/npm/@yassidev/fabric-extensions@1.1.13/dist/fabric-extensions.umd.js for full version or
https://cdn.jsdelivr.net/npm/@yassidev/fabric-extensions@1.1.13/dist/fabric-extensions.umd.min.js for minified.

https://www.jsdelivr.com/ is an awesome resource for pure in-browser stuff.

Hope that helps!
