### ISSUE TITLE
Free drawing on iPad creates deformed strokes

### ISSUE THREAD

**Issue by beeirl** [fabricjs/fabric.js#7637]
https://user-images.githubusercontent.com/9655723/151426441-af837eea-5ae7-44bb-808e-68ac7619f312.mov

I am currently testing fabric.js on mobile (on my iPad Air in particular) and I am experiencing a weird bug where the strokes are getting deformed sometimes when you stop drawing (as you can see in the video).

## Information about environment
- iPad Air 4
- iOS 15.2
- Safari Browser

## Steps to reproduce
- Open http://fabricjs.com/freedrawing demo on an iPad
- Start drawing
- Eventually the bug will occur (it could take a few attempts though)

**Comment by ShaMan123** [comment]
Trying to triage...
Could you try reproduce this issue by creating a fabric.Path with valid path data (best to have an image of the path from another os for comparison) and seeing if that is broken?

**Comment by asturur** [comment]
This is hardware acceleration issue, and i bet that if you extra the path and you render it the same, you will get the same exact issue.
We can't fix it, meaning that, is the list of command of the path that will generate it on that particular hardware/driver combination.

**Comment by asturur** [comment]
Another thing you can check is if that path, exported to SVG has the same issue.

**Comment by alizaidi606** [comment]
@beeirl were you ever able to solve this issue?? I am having the same issue.
