### ISSUE TITLE
animate object is not updating in kclass

### ISSUE THREAD

**Issue by dennisideaonce** [fabricjs/fabric.js#7650]
I want to save the fabric js animation in my database. I followed this fiddle: http://jsfiddle.net/c8azmypf/
to create different animations like:
1: Moving
2: Scaling
3: Fading
4: wobble 
5: Shake etc.

I have done that in the canvas. Now I want to save this animation in my database so that it comes animated when reloaded or when I convert the animation into mp4 or gif.

I was expecting the done animation to be in canvas.getObjects(). But it doesn't have anything for animation.

Can you please help? http://jsfiddle.net/c8azmypf/

**Comment by asturur** [comment]
Hi @dennisideaonce animations aren't saved.
What you want is probably this:
https://github.com/fabricjs/fabric.js/pull/6390
But wasn't ready/finished ( works decently tho)
and an example repository here 
https://github.com/asturur/animation-ui

This was a test to verify if it was convenient to create an animation state that could be serialized.

**Comment by dennisideaonce** [comment]
Not exactly, but that is helpful!
