### ISSUE TITLE
custom type object toGroup position dislocation

### ISSUE THREAD

**Issue by rolitter** [fabricjs/fabric.js#7660]
## Version
4.6.0

## Test Case
https://codepen.io/rolitter/pen/GROryPM?editors=0010

## Information about environment
browser
Chrome  97.0.4692.99

## Steps To Reproduce

create custom type object,  canvas add custom type object, and  group its

![fabricjs2](https://user-images.githubusercontent.com/27326998/152906667-4781cda4-938b-4fd3-b5c1-e96a8ca411bc.gif)

## Expected Behavior
the groups child element positional dislocation

## Actual Behavior
the groups child element correct position

**Comment by ShaMan123** [comment]
So I have no idea what's wrong
Could you try to update your example to use #7669 ?
I am interested to see what will happen

**Comment by rolitter** [comment]
https://codepen.io/rolitter/pen/GROryPM?editors=1010
using a  custom element, the position is correct. After group, the position of the self-defined child element in the combination is wrong, After ungroup, the position of the child element is the original position

1.before group, the child position
![bgroups](https://user-images.githubusercontent.com/27326998/153783408-15050ee1-cc63-4653-8dd5-8558b5fd38e2.gif)

2. group, the child position
![bafgroups](https://user-images.githubusercontent.com/27326998/153783463-3d9bb7fa-6f3a-40f5-8c90-f03736cb2e48.gif)


![groups](https://user-images.githubusercontent.com/27326998/153783368-cc85c62d-e79a-41bb-ae5e-100d948e0901.gif)
