### ISSUE TITLE
Image tearing in nodejs environment

### ISSUE THREAD

**Issue by maoweifan** [fabricjs/fabric.js#7663]
## Version
5.0.0

## Test Case
```javascript
const fabric = require('fabric').fabric,
    fs = require('fs'),
    out = fs.createWriteStream(__dirname + '/test1.png')

const canvasContext = new fabric.StaticCanvas(null, {width: 4348, height: 2836})

/**
 * amazon California S3
 * > https://diy-product-01.s3.us-west-1.amazonaws.com/test/1a664eadc339a30b1f467b0fce272582+(1).png
 * alibabaCloud China OSS
 * > https://diy-image-01.oss-cn-shenzhen.aliyuncs.com/large/1a664eadc339a30b1f467b0fce272582.png
 */

const url =  'https://diy-product-01.s3.us-west-1.amazonaws.com/test/1a664eadc339a30b1f467b0fce272582+(1).png'

//const url = 'https://diy-image-01.oss-cn-shenzhen.aliyuncs.com/large/1a664eadc339a30b1f467b0fce272582.png'

fabric.Image.fromURL(url, img => {
    canvasContext.add(img)
    canvasContext.renderAll()

    console.log(canvasContext.getObjects().length)

    const stream = canvasContext.createPNGStream()
    stream.on('data', function (chunk) {
        out.write(chunk);
    })
})
```

## Information about environment
Nodejs or browser? nodejs@v14.17.4

## Actual Behavior

The following figure is a screenshot of the generated image

<img width="577" alt="test" src="https://user-images.githubusercontent.com/51221758/153146347-e4bc6f31-f3de-46a6-a645-35b777d735e2.png">

This is the screenshot of the image added to canvas
`https://diy-product-01.s3.us-west-1.amazonaws.com/test/1a664eadc339a30b1f467b0fce272582+(1).png`
![image](https://user-images.githubusercontent.com/51221758/153146558-0d753cd6-fbdc-4677-a986-b7ea4e3ed44f.png)

**Comment by maoweifan** [comment]
Only some pictures will tear, and most of them are the expected effect

**Comment by maoweifan** [comment]
@asturur

**Comment by maoweifan** [comment]
Image tearing does occur in windows
Not in Linux

**Comment by asturur** [comment]
Sems a native lib install to me.
Nothing we can fix from here.
You should try to reproduce this in plain node js + node-canvas without fabric, and post it on the node-canvas repo

Someone can help you figure out what it is
