### ISSUE TITLE
Error calling toDataUrl() after upgraded to 5.0.0

### ISSUE THREAD

**Issue by Tennyleaz** [fabricjs/fabric.js#7664]
## Version
5.0.0

## Test Case
https://pastebin.com/in8ySZnG

## Information about environment
Nodejs server v16.13.2

## Steps To Reproduce

1. Create a canvas
```js
const canvas = new fabric.Canvas(null, { width: 100, height: 100 });
```
2. Create an object and add to canvas
```js
const rect = new fabric.Rect({width: 20, height: 50, fill: "#ff0000"})
canvas.add(rect)
canvas.renderAll()
```
3. Call toDataURL()
```js
const imageData = rect.toDataURL()
```
<details><summary>Error Message & Stack Trace</summary><p>

```txt
 ERROR  Cannot set property parentRule of #<CSSStyleDeclaration> which has only a getter

  at Object.setStyle (node_modules/fabric/dist/fabric.js:3158:42)
  at klass.dispose (node_modules/fabric/dist/fabric.js:10524:19)
  at klass.toCanvasElement (node_modules/fabric/dist/fabric.js:16082:14)
  at klass.toDataURL (node_modules/fabric/dist/fabric.js:16105:41)
  at server/index.js:32:29
  at klass.__setupCanvas (node_modules/fabric/dist/fabric.js:14158:17)
  at node_modules/fabric/dist/fabric.js:14124:31
  at klass._setBgOverlay (node_modules/fabric/dist/fabric.js:14175:19)
  at node_modules/fabric/dist/fabric.js:14116:13
  at node_modules/fabric/dist/fabric.js:14235:19
```
</p></details>

## Expected Behavior
`toDataURL()` would succeed at fabric 4.6.0.

## Actual Behavior
`toDataURL()` fail with error `Cannot set property parentRule of #<CSSStyleDeclaration> which has only a getter` at fabric 5.0.0

**Comment by ShaMan123** [comment]
I think I understand where it's coming from.
How do I run you repro??
Can you create one that works on 4.6.0 as well?
I need to see it in action.
@asturur seems to be caused by #7181 (I didn't take into account node behavior - what happens in node dispose?)

**Comment by ShaMan123** [comment]
see this https://codesandbox.io/s/j0y7h

**Comment by ShaMan123** [comment]
excellent I'll give a look.
I think this is the line your stack tract point to
https://github.com/fabricjs/fabric.js/blob/3c00740e00889920140b2c7bd6620ca0992a5117/src/static_canvas.class.js#L1779
try seeing what's happening there, what object is `lowerCanvas`

**Comment by SLKnutson** [comment]
I don't think this is related to jsdom, I'm getting this in regular chrome/firefox in 5.2.1.
For me it is happening in `fabric.Object.toCanvasElement`
The simplest way to reproduce is to do this
```
const tempCanvas = new fabric.StaticCanvas('');
tempCanvas.dispose();
```

**Comment by SLKnutson** [comment]
I get errors when it is setting the following fields on the style `"0" "1" "length", and "parentRule"`. According to https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration, `length` and `parentRule` are readonly. I tried a stackblitz with my reproduction, and for some reason that doesn't throw errors. I don't know why.

**Comment by asturur** [comment]
hi @SLKnutson let me see if i can dig deeper
So in browser, standard code, those 2 lines should trigger an error?

**Comment by southernangel** [comment]
Same thing happened with me.  I was trying to extract a crop portion of an image.  Failed with version 5, had to revert to the previous version where it works.  This is the code that the failure occurred at.  Please forgive me if I'm not posting correctly or haven't got enough info, I'm a newbie at issue posting :-)

const croppedArea = this.sourceImage.toDataURL({  left: croppingRect.left, top: croppingRect.top, 
                                                                                    width: croppingRect.width, height: croppingRect.height });

The image is a screen shot of the chrome console.

<img width="422" alt="Error on crop" src="https://user-images.githubusercontent.com/26886652/155882736-00573033-b567-4c4e-b816-e3d7d0c30ed3.png">

**Comment by ShaMan123** [comment]
@southernangel is this happening in the browser or in node (as originally posted)?

**Comment by southernangel** [comment]
Yep, in the Chrome browser console.  I forgot to mention that this is part of an Angular 13 application so I'm not exactly a javascript expert as such.  I'm more comfortable in the pure OO environment.  I needed an SVG/PNG canvas platform and fabricjs was and still the best around.

**Comment by ShaMan123** [comment]
fixed
![image](https://user-images.githubusercontent.com/34343793/157195052-cfad8837-8b35-4d5d-b24c-1bdf772ffec3.png)
