### ISSUE TITLE
Could not load img - Unsupported image type

### ISSUE THREAD

**Issue by maoweifan** [fabricjs/fabric.js#7677]
## Version
5.0.0

## Test Case
https://codesandbox.io/s/damp-voice-wiqsp?file=/src/index.js

## Information about environment
Nodejs or browser? nodejs
Which browsers? node@14

## Steps To Reproduce
image url : `https://diy-image-01.s3.us-west-1.amazonaws.com/1C/fa7a2788a9a325a206815c13f549aa08.jpg`

**Comment by maoweifan** [comment]
https://github.com/Automattic/node-canvas/issues/1709

**Comment by maoweifan** [comment]
Does node-canvas not support other file formats (non-jpeg, png)
I suspect that this image may not be png or jpeg, like webp, but the suffix of the file has been changed to jpeg

**Comment by asturur** [comment]
Yes this is `RIFFeWEBPVP8`.
I know node canvas had some work for it, but i think you need to have some libraries installed for that to work.

**Comment by maoweifan** [comment]
`fabric.Image.from`  Can it be like nodejs, (err, imageObject) => {};
I want this way I can catch the error

**Comment by maoweifan** [comment]
static fromURL(url: string, callback?: (image: Image) => void, imgOptions?: IImageOptions): Image;
=> 
static fromURL(url: string, callback?: (error:Error,image: Image) => void, imgOptions?: IImageOptions): Image;

**Comment by asturur** [comment]
Is a promise soon!

fromURL().then().catch()
