### ISSUE TITLE
After the fabric.ActiveSelection object is selected, the object cannot be moved without releasing the mouse.

### ISSUE THREAD

**Issue by Ezr1al** [fabricjs/fabric.js#7730]
## Version
4.3.1

## Test Case
https://jsfiddle.net/xf3pruea/

## Information about environment
chrome

## Steps To Reproduce
I created a fabric.ActiveSelection object, and once it was created, I could not move it by clicking on it (mouse not released). I need to release the mouse after selecting the object and then selecting the object again to move.

## Expected Behavior
 When selected for the first time, mouse down moves it without releasing it.

**Comment by asturur** [comment]
There is a  lot of code in that fiddle
Can you explain the logic behind that code? what are you trying to do?

**Comment by Ezr1al** [comment]
When I click the group button to group the two objects, I click the selected object and cannot drag the object without releasing the mouse. See the operation of the video。
https://user-images.githubusercontent.com/36941749/155455976-02903437-53c4-443e-9bb2-b89360888e98.mov
