### ISSUE TITLE
When `target` removed, what's another way to get `target` with version > 4.6.0

### ISSUE THREAD

**Issue by natuan62** [fabricjs/fabric.js#7731]
- With pull request `remove deprecated code`  
   - https://github.com/fabricjs/fabric.js/pull/7630

![image](https://user-images.githubusercontent.com/10808157/155093539-53af3354-0caa-46f8-83f6-c345f5633c49.png)

Hi @asturur, when `target` removed, what's another way to get `target` with version > 4.6.0 

`selection:created` event
![image](https://user-images.githubusercontent.com/10808157/155094224-cd73efa0-3831-485c-acd6-9494e48fe87c.png)

version 4.6.0
![image](https://user-images.githubusercontent.com/10808157/155094248-5147ceeb-9524-4c62-aa30-02de50d9bf37.png)

version 5.0.0
![image](https://user-images.githubusercontent.com/10808157/155094271-aad9b396-7966-4bff-923c-de8952ba1c8a.png)

**Comment by ShaMan123** [comment]
> selection event won't keep firing informations with the format of fabric 3 and lower ( use seelcted and deselected and not updated or target

If you need the active object then `canvas.getActiveObject()`

**Comment by ShaMan123** [comment]
closing
