### ISSUE TITLE
Strange behaviour when using flipX on selected object

### ISSUE THREAD

**Issue by southernangel** [fabricjs/fabric.js#7741]
No idea what's causing this behaviour and it's purely cosmetic I suppose but I guess its some sort of minor bug.

If I use flipX on the active object the rotation line goes to the bottom of the object for some reason.  The second image is after the flipX.

<img width="110" alt="before flipX" src="https://user-images.githubusercontent.com/26886652/155884002-8135e485-ec16-4f39-830a-49a41edc925d.png">

<img width="139" alt="after flipX" src="https://user-images.githubusercontent.com/26886652/155884009-4f2b44cc-ef16-4468-afc9-b017372deea9.png">

**Comment by melchiar** [comment]
This has been fixed in v5

https://github.com/fabricjs/fabric.js/issues/7565

**Comment by southernangel** [comment]
Thanks, good to know.  Can't upgrade until other issues with 5.0 resolved, unfortunately

**Comment by melchiar** [comment]
Well, you could just backport the fix to v4.6. It's literally 3 lines of code.

https://github.com/fabricjs/fabric.js/commit/d277016c491be8367cc052739b5deccd4733cf20
