### ISSUE TITLE
`absolutePositioned` clipPath in group

### ISSUE THREAD

**Issue by pushuo** [fabricjs/fabric.js#7745]
## Version
5.1.0

## Test Case
https://jsfiddle.net/pushuo/5fyevkz8/54/

## Information about environment
Google Chrome

## Steps To Reproduce

Please operate according to the jsfiddle example, use the mouse to select the picture and clipPath of the canvas, and then click the above button addGroup

## Expected Behavior
The picture and clipPath of the canvas, normally added to the group

## Actual Behavior
The picture and clipPath in the canvas are displayed in confusion,

**before group ：**
<img width="601" alt="image" src="https://user-images.githubusercontent.com/21018378/155937858-104afd67-6053-42ad-ad86-336f8f55d9e0.png">

**after group**
<img width="477" alt="image" src="https://user-images.githubusercontent.com/21018378/155937876-43a456a8-e8be-4cf6-9082-7f0964c6f274.png">

This seems to be a bug, please help me to solve it, thanks.

**Comment by ShaMan123** [comment]
duplicate #7142

**Comment by pushuo** [comment]
> 放心，这很快就会解决，看看#7669

Looking forward to it, thanks

**Comment by ShaMan123** [comment]
https://jsfiddle.net/n7wcpzhL/4/

**Comment by pushuo** [comment]
It seems that the effect is still not ideal, I temporarily try to use the method mentioned in this link http://fabricjs.com/using-transformations.
It also seems to be a kind of "group", he can "combine" the clipPath and the group together.
Solved my problem so far
