### ISSUE TITLE
How to get info about selection in v5?

### ISSUE THREAD

**Issue by av01d** [fabricjs/fabric.js#7746]
## Version
5.2.1

## Test Case
Working test case, fabric.js v4.6.0:
https://jsfiddle.net/av01d/41v3yn5g/

Same code, now with fabric.js v5.2.1, not working (yet):
https://jsfiddle.net/av01d/53sqgv7o/

## Information about environment
All browsers

## Steps To Reproduce

We use Fabric.js in many popular websites (a.o. postermaker.com, photocollage.com). When users select objects on a fabric canvas, we display some info about the selected object(s): width, height, left, top, angle. See the first fiddle: https://jsfiddle.net/av01d/41v3yn5g/
Works like a charm on fabric versions 4.x.

How do I implement the same behavior on fabric version 5?
The second fiddle (https://jsfiddle.net/av01d/53sqgv7o/) has the code, I don't know how to make it work.

The changelog (http://fabricjs.com/v5-breaking-changes) mentions that the `target` property of the `selection:updated` and `selection:created` events have gone. What is the new way of retrieving info about the current selection???

**Comment by av01d** [comment]
You need to explicitly query the active selection:
```
fabricCanvas.on({
   'selection:created': () => {
      const target = fabricCanvas.getActiveObject();
      ...
   },
   'selection:created': () => {
      const target = fabricCanvas.getActiveObject();
      ...
   }
});
```

The 5.2.1 fiddle has been updated with this new insight.
Leaving this here for future reference.

**Comment by melchiar** [comment]
@av01d The event also has a `selected[0]` property you can look at.

https://github.com/fabricjs/fabric.js/issues/7731
