### ISSUE TITLE
docs(): Some spelling correction in documentation

### ISSUE THREAD

**Issue by akaAbdullahMateen** [fabricjs/fabric.js#7748]
URL: http://fabricjs.com/fabric-intro-part-4
Section: Customizing selection
Line: There's 4 properties on canvas that control its presentation — "selectionColor", "selectionBorderColor", "**selectionLikeWidth**", and "selectionDashArray". 
Correction: selectionLikeWidth -> selectionLineWidth

Note: I found a lot of spelling and grammar mistakes in the documentation, tutorial, and comments in source code. If someone can explain me how to edit them, I can correct them. Have a nice day everyone :)

**Comment by akaAbdullahMateen** [comment]
URL: http://fabricjs.com/test/misc/itext.html
Source code -> Line 41: _// very retarted fix but fuck it_
Correction: This comment should be rephrased into a suitable, professional tone.

**Comment by akaAbdullahMateen** [comment]
URL: http://fabricjs.com/docs/fabric.Canvas.html#backgroundImage
Line: Otherwise the image cannot detect the zoom **vale**.
Correction: _vale_ -> _value_

**Comment by akaAbdullahMateen** [comment]
URL: http://fabricjs.com/docs/fabric.Canvas.html#overlayImage
Line: Otherwise the image cannot detect the zoom **vale**.
Correction: _vale_ -> _value_

**Comment by akaAbdullahMateen** [comment]
URL: http://fabricjs.com/fabric-object-caching
Section: When does the cache gets updated with a new version?
Line: Fabric has **an** hardcoded trigger to update cache during ...
Correction: _an_ -> _a_

**Comment by akaAbdullahMateen** [comment]
URL: http://fabricjs.com/fabric-object-caching
Section: When does the cache gets updated with a new version?
Line: **In all other cases is** the developer that is changing some property ...
Correction: _In all other cases is_ -> _In all other cases, it is_

**Comment by melchiar** [comment]
Thanks! Feel free to open a PR if you find any more issues (create a fork of the fabricjs.com repo -> create a branch in your fork for the corrections -> open a PR to merge those corrections back to the official repo)

**Comment by melchiar** [comment]
> URL: http://fabricjs.com/test/misc/itext.html Source code -> Line 41: _// very retarted fix but fuck it_ Correction: This comment should be rephrased into a suitable, professional tone, such as, _not the best fix but it gets the job done_.

sheesh...that's awful.

**Comment by akaAbdullahMateen** [comment]
Thanks, I am learning fabricjs, so as I find anything I will do as your described :)
