### ISSUE TITLE
IText setSelectionStyles() does not accept multiple font families.

### ISSUE THREAD

**Issue by Tennyleaz** [fabricjs/fabric.js#7749]
# Version
5.0.0

## Test Case
https://jsfiddle.net/Tenny1/mfag1chb/22/

## Information about environment
Browser (Firefox/Edge)

## Steps To Reproduce

1. Create an IText without font family argument.
2. Set the font family list through `setSelectionStyles()`.
IText `setSelectionStyles()` could only accept single font family style, but the IText object style could accept multiple font families.

## Expected Behavior
IText font should change corresponding to the given font list.

## Actual Behavior
IText font doesn't change at all.

[https://imgur.com/jKpYFO2.png](https://imgur.com/jKpYFO2.png)

**Comment by ShaMan123** [comment]
Does this solve your use case?
https://jsfiddle.net/dv27xapL/

**Comment by ShaMan123** [comment]
https://github.com/fabricjs/fabric.js/blob/70943e726fb1889ea02359a828443f1bbcee33b9/src/mixins/text_style.mixin.js#L225

**Comment by ShaMan123** [comment]
Does this solve your use case?
https://jsfiddle.net/dv27xapL/

**Comment by ShaMan123** [comment]
https://jsfiddle.net/Lfomngxz/3/

**Comment by Tennyleaz** [comment]
Thank you. Is it required to wait some time then render again?

**Comment by ShaMan123** [comment]
No. I just used `setTimeout` for the example.
