### ISSUE TITLE
vue3/production: canvas initialization error

### ISSUE THREAD

**Issue by Zero-Qi** [fabricjs/fabric.js#7755]
在vue3下 vite打包的项目没有报错 ，开发环境也没错 
部署到项目上，无法绘制，事件监听失效，在画布上停止响应事件，捆绑到函数可以正常执行
![image](https://user-images.githubusercontent.com/50648661/156767545-8406caac-1b1b-44f8-aba1-b8c16321b197.png)

![image](https://user-images.githubusercontent.com/50648661/156767610-b183c0f8-8583-487e-8085-2c4b8123ab86.png)
 
dom异常
![image](https://user-images.githubusercontent.com/50648661/156786614-3281a768-cccb-4f4e-a50c-2b35d5fe2b65.png)
正常dom如下
![image](https://user-images.githubusercontent.com/50648661/156786697-b819dadd-764b-4286-baad-6798492b0ab7.png)

**Comment by Zero-Qi** [comment]
第一次加载组件没问题，第二次的时候canvas的事件全部失效

**Comment by Zero-Qi** [comment]
![Uploading image.png…]()
在这期间，浏览器只有输出这些警告

**Comment by Zero-Qi** [comment]
在这期间浏览器只有输出这些警告
] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.

**Comment by Zero-Qi** [comment]
dom少绘制了一层

**Comment by Zero-Qi** [comment]
封装的fabricjs组件，是通过el-dialog打开的，给canvas的id加个随机值，就解决问题了，
问题大概出在没有这个dom上，有可能是v-if的问题

**Comment by ShaMan123** [comment]
@Zero-Qi please provide a working repro. And I kindly ask of you to write in English

**Comment by ShaMan123** [comment]
I am able to see that the exception is very strange. There is no canvas el, only upper canvas.

**Comment by Zero-Qi** [comment]
first，I thought was&nbsp;something wrong with the vite packaging，because&nbsp; in development environment is normal，no&nbsp; this bug。
later，i&nbsp; use vuecli&nbsp; &nbsp;packaning，the&nbsp; bug&nbsp; again。in F12 Console ，i&nbsp; don`t&nbsp; &nbsp;understand&nbsp; no&nbsp; any error message。today，i&nbsp; try to give&nbsp; dom&nbsp; canvas&nbsp; id&nbsp; &nbsp;add&nbsp; &nbsp;random number。Everything is back to normal&nbsp; but that&nbsp; is not&nbsp; good idea




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fabricjs/fabric.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月6日(星期天) 晚上10:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fabricjs/fabric.js] vue3 use vite build  in brower not error，but not handle canvas (Issue #7755)





 
I am able to see that the exception is very strange. There is no canvas el, only upper canvas.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShaMan123** [comment]
It's really hard to understand your comment

**Comment by Zero-Qi** [comment]
my english is not good ,lol~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fabricjs/fabric.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月6日(星期天) 晚上10:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fabricjs/fabric.js] vue3 use vite build  in brower not error，but not handle canvas (Issue #7755)





 
It's really hard to understand your comment
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ShaMan123** [comment]
It's not your English, it's the gibberish added to your English. Now it's better

**Comment by Zero-Qi** [comment]
> It's really hard to understand your comment

sorry，i just saw it，i use QQ mail phone, There is a problem with the message format，i I have corrected it

**Comment by Zero-Qi** [comment]
> It's not your English, it's the gibberish added to your English. Now it's better

I'll provide code examples tomorrow. Sorry to interrupt late at night

**Comment by ShaMan123** [comment]
Under `div.canvas-container` should exist 2 canvas elements.
For some reason the main canvas which is the one that has the id property set on it is missing.
It's very weird.
I guess there's something trying to initialize canvas more than once **or** something trying to dispose canvas during initialization.
This looks like another bug that was filed a few days back.

**Comment by ShaMan123** [comment]
related #7693 ?

What version of fabric are you using? Did you try upgrading/downgrading?

**Comment by Zero-Qi** [comment]
> related #7693 ?
> 
> What version of fabric are you using? Did you try upgrading/downgrading?

no, version 3.5.1,What I don't understand is that the development environment is normal, there is a problem after packaging, and the console doesn't report an error，Moreover, the encapsulated components are normal only when they are opened for the first time, and cannot be rendered when they are opened for the second time

**Comment by Zero-Qi** [comment]
> related #7693 ?
> 
> What version of fabric are you using? Did you try upgrading/downgrading?

Didn't the fabric be completely destroyed when the components were destroyed? I added a random number to the canvas ID, so it's no problem. Is it global pollution

**Comment by ShaMan123** [comment]
> 
> no, version 3.5.1,What I don't understand is that the development environment is normal, there is a problem after packaging, and the console doesn't report an error，Moreover, the encapsulated components are normal only when they are opened for the first time, and cannot be rendered when they are opened for the second time

This is a good description
What do you mean by `encapsulated components`?

**Comment by ShaMan123** [comment]
And what do mean by *opened for the second time*?

**Comment by Zero-Qi** [comment]
> And what do mean by _opened for the second time_?

url: https://github.com/Zero-Qi/fabricjs-vue.git
After the package is completed, the problem can be seen when it is deployed on the server
1.only fist, click 'edit', is ok,but later click other "edit",the canvas no render
2.if you refresh page,no problem
so, if you add the canvas id random number，it ok,That's how I solved it


```
  <canvas :id="'canvas' + randomNumber" style="display: block; width: 100%; height: 100%"></canvas>
    canvas = new fabric.Canvas('canvas' + randomNumber.value)    //vue3 grammar
```

**Comment by ShaMan123** [comment]
Can you put it into a codesandbox so it's runnable without setup?
Try checking if this function is called more than once
https://github.com/Zero-Qi/fabricjs-vue/blob/8cbf2bed36702001fa47da5ce6598e945bbbd34a/src/components/TheFabric.vue#L108

**Comment by ShaMan123** [comment]
> I guess there's something trying to initialize canvas more than once **or** something trying to dispose canvas during initialization. This looks like another bug that was filed a few days back.

I was right
You can see in the console you are initializing the same canvas again and again.

![image](https://user-images.githubusercontent.com/34343793/157207606-af260f3a-a419-4228-85ec-2c4a1bd4daaa.png)
