### ISSUE TITLE
Why top and left properties become negative after selection?

### ISSUE THREAD

**Issue by coxato** [fabricjs/fabric.js#7756]
## Version
5.2.1

## Test Case
https://jsfiddle.net/kj7qy6a8/

## Information about environment
Chrome Version 98.0.4758.102

## Steps To Reproduce

1. click the "check top and left" button
2. select both object (text1 and text2)
3. once the objects have been selected, press the button again.
4. now you can see the top and left values are negative or wrong

## Expected Behavior
Know the actual top and left and detect when the entire selection has been moved

## Actual Behavior
the top and left values for the objects inside the selection are wrong, and I don't know which event is the correct for detect when the entire selection has been moved

There is a test case 
https://jsfiddle.net/kj7qy6a8/

Also I made a question on stackoverflow
https://stackoverflow.com/questions/71356612/why-top-and-left-properties-become-negative-after-selection-fabricjs

**Comment by ShaMan123** [comment]
It's group behavior.
http://fabricjs.com/fabric-intro-part-3#groups

Objects become relative to group's center.
This is addressed in #7669 with methods such as `getX` which will return the value you expect
