### ISSUE TITLE
Line: 29278 in fabric.js: this.isTripleClick is not a function

### ISSUE THREAD

**Issue by akaAbdullahMateen** [fabricjs/fabric.js#7757]
I am not really sure how to write a complete bug report, but I was getting this error message, so I made the following changing in fabric.js file and the error is gone :).
Line 29278: this.isTripleClick(newPointer) -> this.isTripleClick
Some backstory: This error occurred when I was overriding HTML body's context menu with my custom context menu. Everything was fine, but when I right click on any object on the canvas - such as a rectangle or free drawn path. I was getting this error message.

**Comment by ShaMan123** [comment]
It seems to me your context menu callback collides somehow with the triple click checks.
So I'm not sure it's a bug in fabric, but the way you configured it.
The fix doesn't make sense.
You should provide a working online reproduction of the problem and another for the solution.

**Comment by akaAbdullahMateen** [comment]
Let me try to reproduce the error.

**Comment by akaAbdullahMateen** [comment]
Alright. I am closing this. I am unable to reproduce the error on fiddle. I can't share my complete code, and can't find the problematic lines in it.

**Comment by ShaMan123** [comment]
Once you manage to find an error don't hesitate to reopen
