### ISSUE TITLE
send backwards

### ISSUE THREAD

**Issue by vinit2209** [fabricjs/fabric.js#776]
Dear all,
I am using rectangle with text object where rectangle is bind with text so if there is an image over rectangle , i want to send this image behind rectangle so i made changes in sendBackwards method 

```
              sendBackwards: function (object, intersecting) {
                var idx = this._objects.indexOf(object);
                  removeFromArray(this._objects, object);
                  this._objects.splice(idx-2, 0, object);(back it by 2 index)
                  this.renderAll && this.renderAll();
                  return this;
                }
```

But now image is not selectable I also tried this.calcOffset(); and this.deactivateAll().renderAll(); Although it can be rotated.

**Comment by lastobelus** [comment]
@biswajitch: one problem with your fiddle is that you can't send the image to the back before it exists, you need to do it in the callback. Secondly, you are calling `bringToFront` on `canvas.text`, which is undefined. You created a var `text`, you need to call `canvas.bringToFront(text)`. There does seem to be an issue with fabric where calling bringToFront (etc) on an `undefined` or `null` value puts fabric into a state from which it cannot recover.
