### ISSUE TITLE
[5.x] Invisible circle when loading from 4.5.0 json due to endAngle (6.283185307179586)

### ISSUE THREAD

**Issue by lk77** [fabricjs/fabric.js#7769]
## Version
5.x (5.2.1 at least but likely >5.0)

## Test Case
http://jsfiddle.net/lk77/jmsbyvoz/2/

## Information about environment
Nodejs or browser? browser
Which browsers? chrome 99

## Steps To Reproduce

1. load with that json
```
{"objects":[{"id":191619,"top":0,"fill":"#00bbe1","left":0,"type":"circle","angle":0,"flipX":false,"flipY":false,"skewX":0,"skewY":0,"width":150,"height":150,"radius":75,"scaleX":1,"scaleY":1,"shadow":null,"stroke":"#00bbe1","opacity":1,"originX":"left","originY":"top","version":"4.5.0","visible":true,"endAngle":6.283185307179586,"fillRule":"nonzero","customData":{"name":"circle"},"paintFirst":"fill","startAngle":0,"strokeWidth":1,"strokeLineCap":"butt","strokeUniform":false,"strokeLineJoin":"miter","backgroundColor":"","strokeDashArray":null,"strokeDashOffset":0,"strokeMiterLimit":4,"globalCompositeOperation":"source-over"}],"version":"4.5.0","background":"#fff"}
```
2. see that circle is invisible

![Screenshot from 2022-03-07 18-12-45](https://user-images.githubusercontent.com/9606882/157083778-5bb81876-24d5-41be-a6c7-90474a6acf33.png)

4. call .toJSON() on the circle
```
{
    "type": "circle",
    "version": "5.1.0",
    "originX": "left",
    "originY": "top",
    "left": 0,
    "top": 0,
    "width": 150,
    "height": 150,
    "fill": "#00bbe1",
    "stroke": "#00bbe1",
    "strokeWidth": 1,
    "strokeDashArray": null,
    "strokeLineCap": "butt",
    "strokeDashOffset": 0,
    "strokeLineJoin": "miter",
    "strokeUniform": false,
    "strokeMiterLimit": 4,
    "scaleX": 1,
    "scaleY": 1,
    "angle": 0,
    "flipX": false,
    "flipY": false,
    "opacity": 1,
    "shadow": null,
    "visible": true,
    "backgroundColor": "",
    "fillRule": "nonzero",
    "paintFirst": "fill",
    "globalCompositeOperation": "source-over",
    "skewX": 0,
    "skewY": 0,
    "radius": 75,
    "startAngle": 0,
    "endAngle": 6.283185307179586
}
```
5. see the endAngle property
6. remove endAngle and see that circle is visible (http://jsfiddle.net/lk77/jmsbyvoz/4/)

![Screenshot from 2022-03-07 18-11-40](https://user-images.githubusercontent.com/9606882/157083604-d0bf0f6d-ccfb-450b-93eb-50831e27f8c7.png)

## Expected Behavior

circle is visible

## Actual Behavior

circle is invisible

i never added that endAngle property myself to that circle object in the first place, something seems to have changed since 4.5.0, which is adding that weird 6.283185307179586 endAngle

i don't know in which scenario that endAngle property is added,
i don't have full history of the lifecycle of that json, but i have many instances of missing/invisible circles with json created with 4.5.0 when trying to load on 5.2.1

perhaps it was an issue with 4.5.0 which created faulty jsons, in which case we will need to fix those jsons.
new 5.2.1 circles seems to be working fine

it seems 6.28 radians is 360 degrees, does the unit of endAngle changed from radians to degrees ?

i don't see any mention to such

thanks.

**Comment by melchiar** [comment]
Yes, v5 has changed from radians to degrees. See http://fabricjs.com/v5-breaking-changes where you'll find some helper code for dealing with the change.

**Comment by lk77** [comment]
Ok thanks !
