### ISSUE TITLE
Get padding of the text

### ISSUE THREAD

**Issue by nguyenctu** [fabricjs/fabric.js#7774]
Hi, I'm trying to get the padding-left of the text in bounding box but don't know how to. Everytime I scale the text, the padding change so I can't have any redefined number.
The red arrow is the "padding-left" I'm talking about:
![Capture](https://user-images.githubusercontent.com/66686403/157184463-8e9ad10f-0956-4721-b1a1-22982eeebea9.PNG)
How can I achieve this? thank you

**Comment by melchiar** [comment]
I'm not sure I fully understand your question. In Fabric, an object's `padding` is unaffected by scale, and Fabric does not have separate padding values for each side, just one `padding` property which affects all sides equally. 

Am I misunderstanding?

**Comment by nguyenctu** [comment]
@melchiar Thanks for responding to my issue. My Fabricjs version is 4.6.0, everytime I scale the text the padding change and look like top-bottom padding and left-right padding are different values. Is this because of my Fabricjs version or is there any config that could cause this?

https://user-images.githubusercontent.com/66686403/157822080-ab588bbc-c128-435e-ac36-cb8249ad8ea7.mp4

**Comment by melchiar** [comment]
can you share a fiddle showing the issue?
