### ISSUE TITLE
fabric 4.6.0 build `enlivenObjectEnlivables`

### ISSUE THREAD

**Issue by yogeshdecodes** [fabricjs/fabric.js#7787]
## Version
4.6.0

## Test Case
http://jsfiddle.net/yogeshdecodes/3vbs4p0m/43/

## Information about environment
Nodejs- v17.3.0

## Steps To Reproduce

1.  Once image has loaded, click the to JSON button, throws the error "Uncaught TypeError: e.shouldCache is not a function" in console.
2. Toggle between `toJSON` and `toDatalessJSON` and you will find out error is only occurring when we're using `toDatalessJSON`

## Expected Behavior
svg should load correctly as it is loading when we're using `toJSON`

## Actual Behavior
``` 
Uncaught TypeError: e.shouldCache is not a function
    at i._drawClipPath (fabric.min.js:1)
    at i.drawObject (fabric.min.js:1)
    at i.renderCache (fabric.min.js:1)
    at i.render (fabric.min.js:1)
    at i._renderObjects (fabric.min.js:1)
    at i.renderCanvas (fabric.min.js:1)
    at i.renderAll (fabric.min.js:1)
    at i.renderAndReset (fabric.min.js:1)
```

**Comment by ShaMan123** [comment]
I am not sure but I think this is intentional.
You can see the diff between the objects is that dataless has `sourcePath` prop while the other has a `path` prop.

**Comment by ShaMan123** [comment]
Did you try to update to v5?

**Comment by ShaMan123** [comment]
Alright I think I understand what happened.
https://jsfiddle.net/ap8g4mjd/1/

@asturur the build files are outdated. `enlivenObjectEnlivables` is stale. We need to publish a version.

**Comment by ShaMan123** [comment]
@yogeshdecodes this issue will be resolved once we publish a new version.
For now I suggest you run `npm run build` from your fabric node module directory. Or use the cdn from my repro (which is extremely **breaking** vs. v4.6)

**Comment by yogeshdecodes** [comment]
@ShaMan123 Thank you so much.

**Comment by ShaMan123** [comment]
I see the 5.2.1 version has somehow got mixed with outdated code.
I suggest you install fabric's latest version directly from github.
```bash
npm i --save github:fabricjs/fabric.js
```

@asturur URGENT

_Originally posted by @ShaMan123 in https://github.com/fabricjs/fabric.js/pull/7657#issuecomment-1079840725_

**Comment by asturur** [comment]
reproduced on 5.2.1 with the minimal code.
http://jsfiddle.net/6pjtbwq3/
I have a bugfix but i need to work on the test a bit
