### ISSUE TITLE
[NODE]: using custom fonts outputs blank png (unsupported char)

### ISSUE THREAD

**Issue by mengsumin** [fabricjs/fabric.js#7789]
## Version
5.2.0

## Test Case
https://github.com/mengsumin/testfabric

## Information about environment
Nodejs v14.18.1
Which browsers?
*
## Steps To Reproduce

here is my code:
```
const fabric = require("fabric").fabric;
const fs = require('fs');
const path = require('path');
let textStringUsed = '啊';
fabric.nodeCanvas.registerFont(path.resolve(process.cwd(), `assets/fonts/804d99ffec4649489c5fd443848f6d06.ttf`), {
    family: '804d99ffec4649489c5fd443848f6d06',
    weight: 'regular',
    style: 'normal'
});
var textFabric = new fabric.Text(textStringUsed, {
    left: 0,
    top: 0,
    fill: 'red',
    angle: 0,
    fontSize: 160,
    fontFamily: '804d99ffec4649489c5fd443848f6d06'
});

// console.log(textFabric.width, textFabric.height)
var canvas = new fabric.StaticCanvas(null, { width: textFabric.width, height: textFabric.height });
canvas.add(textFabric);
console.log("textJSON", JSON.stringify(textFabric))
canvas.renderAll();
const imgBase64 = canvas.toDataURL({
    format: "image/png",
    left: 0,
    top: 0,
    width: textFabric.width,
    height: textFabric.height
})
saveImgToLoacal(imgBase64, 'test.png')

function saveImgToLoacal(base64, fileName) {
    return new Promise((resolve, reject) => {
        base64 = base64.replace(/^data:image\/\w+;base64,/, "")
        const dataBuffer = Buffer.from(base64, 'base64')
        fs.writeFile(path.resolve(process.cwd(), `temps/${fileName}`), dataBuffer, (err) => {
            if (err) {
                console.log(err)
                reject(err)
            } else { resolve() }
        })
    })
}

```

it alse can saw in my test case link:https://github.com/mengsumin/testfabric

i am a web coder and using fabricjs of v5.2.1 on node environment. 
i am in china,and there are a lots of different words in chinese
so ,
when i use costom fonts in fabic, i found if the world  no in the family file(ttf file), the  finally text png of canvasData  is blank.
how can i do that can avoid this condition, i want default font-family world or system font-family style 
,i can be any one font-family style ,but not to be blank.  how can i do?
I am looking forward to hearing from you
using costom fonts in fabricjs can gennerate blank png .

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```
</p></details>

## Expected Behavior
i want default font-family style after canvas renderering if ttf file can not contains the word.
## Actual Behavior
after canvas rendering ,generate a blank png.

**Comment by ShaMan123** [comment]
I don't know enough regarding font loading but I suggest the following:
- Look at [previous issues](https://github.com/fabricjs/fabric.js/issues?q=is%3Aissue+blank+png+is%3Aclosed)
- Create a codesandbox (server template) so it's easy to test what you've built

**Comment by mengsumin** [comment]
> I don't know enough regarding font loading but I suggest the following:
> 
> * Look at [previous issues](https://github.com/fabricjs/fabric.js/issues?q=is%3Aissue+blank+png+is%3Aclosed)
> * Create a codesandbox ([nodejs server template](https://codesandbox.io/s/exciting-browser-ytb701)) so it's easy to test what you've built
> * Look at this http://fabricjs.com/loadfonts. It's a browser example but might be helpful.
> * What about fallback fonts?

i register the account and create a demo based on yours，but i do not know how to add the font-file,and the path is not working.
https://codesandbox.io/s/flamboyant-mclaren-tlye38?file=/src/index.js
here is my demo.
the font file style is 源界明朝.ttf  you can download anyway in networld.  i just renamed it.
i used text "啊1“ to test the case, and gennerate the png , the part of first word in png is blank ,but the second word of 1  is saw.
i know that the reason, that is the ttf do not contains the word by ’啊‘, but why blank, it can be rendered by system default font-family .  in anyway we can see but not canbe blank.

**Comment by ShaMan123** [comment]
https://codesandbox.io/s/agitated-varahamihira-dq89xk?file=/src/index.js

**Comment by mengsumin** [comment]
> https://codesandbox.io/s/agitated-varahamihira-dq89xk?file=/src/index.js

yes，like this demo，on the png image， we can see 1and 2，but can not see the first world。dose any way to result it ？or dose had any api to check the ttf file has world，then used default font-family to renderer this word.

**Comment by ShaMan123** [comment]
Seems to be an issue not related to fabric, but to node canvas

**Comment by ShaMan123** [comment]
@melchiar am I right?

**Comment by ShaMan123** [comment]
As you can see in the [browser](https://jsfiddle.net/gv3j4bdu/) it works with default fonts and in [node](https://codesandbox.io/s/crazy-swirles-jgg6se?file=/src/index.js) as well.
Try registering a couple of fonts. I can't do it in the sandbox because it's too heavy

**Comment by ShaMan123** [comment]
Managed to get it up and running
https://codesandbox.io/s/agitated-varahamihira-dq89xk?file=/src/index.js

node canvas issue.

**Comment by ShaMan123** [comment]
https://github.com/Automattic/node-canvas/issues/1997

**Comment by mengsumin** [comment]
i tried use 'custom family1, custom family2' in this way , but not work. why closed ?

**Comment by mengsumin** [comment]
i tried use 'custom family1, custom family2' in this way , but not work. why closed ?

**Comment by mengsumin** [comment]
not working,sir.  @ShaMan123

**Comment by ShaMan123** [comment]
> [Automattic/node-canvas#1997](https://github.com/Automattic/node-canvas/issues/1997)

**Comment by mengsumin** [comment]
what does this mean? i am using fabricjs, and use fabricjs to register font faimly, why give the node-canvas link? does it help for me ? i  @ShaMan123    could you say more something about this. i am not smart.

**Comment by ShaMan123** [comment]
Sorry. I'll explain. Fabric runs on top of canvas. If you're using it in the browser it use native HTMLCanvasElement. If running on node it uses the canvas implementation of node-canvas. Fabric doesn't handle anything related to how the native canvas works.
What you need is exactly a change to the native canvas. So you need to submit an issue there. Someone has opened an issue (https://github.com/Automattic/node-canvas/issues/1997) so stay tuned there.

**Comment by mengsumin** [comment]
i tried to use node-canvas to draw text on canvas ,it working. 
i regist list of custom fonts , every words can be saw.
 but no line-height and no column-dirction-text  as so on , so finally  i chosed to use fabricjs on node。but fabric does not show, it be blank, do you want to check the source of fabricjs one again ?  @ShaMan123

**Comment by ShaMan123** [comment]
Please add a working reproduction of the node-canvas example
