### ISSUE TITLE
regist dynamic font file always show error：argument isrequired

### ISSUE THREAD

**Issue by mengsumin** [fabricjs/fabric.js#7804]
## Version
5.0.0

## Test Case
*

## Information about environment
Nodejs or browser?
node
Which browsers?

## Steps To Reproduce

i wrote a function to register custom font file , but show errory, here is my funtion

function registDynamicFontFile(fileName) {
    console.log(path.resolve(process.cwd(), `temps/${fileName}.ttf`))
    const fileAddress = path.resolve(process.cwd(), `temps/${fileName}.ttf`)
    console.log(fs.existsSync(fileAddress))     
    fabric.nodeCanvas.registerFont(fileAddress.toString(), {
        family: fileName,
        weight: 'regular',
        style: 'normal'
    });
}

  
fs.existsSync(fileAddress), is true  , but still show error,i dont't know why?
<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```
</p></details>

## Expected Behavior
 will register success
## Actual Behavior
console error :(node:15904) UnhandledPromiseRejectionWarning: Error: The second argument to registerFont is required, and should be an object with at least a family (string) and optionally weight (string/number) and style (string).

**Comment by ShaMan123** [comment]
This is another node canvas issue

**Comment by mengsumin** [comment]
@ShaMan is this node-canvas issue resolved by theire owner ？

**Comment by ShaMan123** [comment]
You need to check there.
The libraries are not related.
