### ISSUE TITLE
Typescript access to 'selected' property on canvas selection:created event

### ISSUE THREAD

**Issue by dseaver** [fabricjs/fabric.js#7809]
Is there an event type I can use to access the 'selected' property on the canvas' selection:created event?

When I try to access it via:
`layoutCanvas.on('selection:created', (event: fabric.IEvent<Event>) =>
        console.log('CANVAS: selection:created', event, event.selected)
      )`

I get a typescript error:
TS2339: Property 'selected' does not exist on type 'IEvent<Event>'.

**Comment by ShaMan123** [comment]
#7596 
Hopefully, soon there will be.
I think v5 broke the selection events, not sure.
http://fabricjs.com/changelog

http://fabricjs.com/events

**Comment by mortezasabihi** [comment]
I'm using version **5.2.1**, but I didn't find any type for this event.

**Comment by ShaMan123** [comment]
@mortezasabihi types are in planning, not yet implemented
