### ISSUE TITLE
Mouse position bug when canvas is in a scrolled div

### ISSUE THREAD

**Issue by raichu** [fabricjs/fabric.js#781]
When the div is scrolled a bit, if I apply transformations (setting top/left, angle and scaleX/Y), canvas.setWidth/Height (followed by calcOffset, of course), the pointer doesn't pick objects.

http://jsfiddle.net/TJ63A/3/
Steps to reproduce: scroll the div to the right-most. Click on "Double" button. Scroll back to the left and try to select the rect object.

(The bug #82 and #123 are marked as closed even though this bug still exists, so I making this new issue)

In issue #123, Kienz made some changes (to version [1.1.19](https://github.com/kangax/fabric.js/blob/2f1383a713e4f0a56d4db51a8201f4f738abf61e/dist/all.js), and [here](https://gist.github.com/raichu/6128354)'s the modified version), and these changes seem to have fixed the problem except for a few cases:

-When I test my program is a larger screen, the program initially starts with a "buggy state" (ie, mouse cursor has some vertical offset); when I minimize & maximize the browser window, it gets fixed.
-I scale down the maximized window to a smaller size (which probably causes div to scroll), and the mouse position is wrong again.

BTW, my canvas object is inside 3 levels of divs.

**Comment by joshribakoff** [comment]
I'm getting this issue. I tried doing this:

```js
canvas.on('mouse:move', function() {
                console.log('mouse:move');
                canvas.calcOffset().bind(canvas);
            });
```

No change, other than lots of printing to the console, which confirms the code is running. If I scroll down by about 100px, I have to click about 100px "above" my objects to select them. If I scroll back up by the same amount, I can click directly on my objects. The work around(s) provided do not seem to do anything.

**Comment by husainfazel** [comment]
@kangax has there been a resolution to this problem? I'm currently using 1.5.0 and having the same problem as @joshribakoff above (i.e. the scroll of the window) affects the position where I need to click to "activate" the objects on the canvas.

**Comment by devhak2** [comment]
This is still broken in 1.5.0. In my case, calcOffset is substituted with raichu's suggestion. Then works fine.

**Comment by asturur** [comment]
we are on 1.6.0 now.scrolled div should work
