### ISSUE TITLE
fabric not able to deal with large virtual canvas sizes (like 14000x14000 pixel)

### ISSUE THREAD

**Issue by TFTomSun** [fabricjs/fabric.js#7818]
## Version
4.6.0

## Test Case
https://jsfiddle.net/0wksnp7t/27/

## Information about environment
Nodejs or browser?
browser
Which browsers?
chrome

## Steps To Reproduce

1.  create a big canvas (like 14000x14000 pixel)
2. add a circle

## Expected Behavior
the rendering works 
## Actual Behavior
a sad smiley will be display, the canvas rendering fails

## Workaround available?
Is there a workaround to virtualize such a large screen? like specifying only 1400x1400 but passing in a virtual screen factor so that the internal fabric coordinate system will always work with 14000x14000 pixel?

**Comment by melchiar** [comment]
The maximum size of a canvas is limited by the browser, not by Fabric.

https://stackoverflow.com/a/11585939/7693185

**Comment by TFTomSun** [comment]
I see, so is there a possibility to work with a virtual coordinate system that simulates larger canvas?

**Comment by melchiar** [comment]
You can look into [panning](http://fabricjs.com/fabric-intro-part-5) as a way to only render part of the canvas at a given time. 

Keep in mind that any objects using [objectCaching](http://fabricjs.com/fabric-object-caching) will generate an offscreen canvas at whatever that object's actual size is, so that canvas will also be subject to the browser's size limit.

**Comment by TFTomSun** [comment]
I meant something like a virtual canvas handling. So that I could add shapes for example at 12000x12000 but and fabric would also return that location, but physicaly they are rendered e.g. at 1200x1200 because of a virtual canvas factor of 10 in this example

**Comment by melchiar** [comment]
Sure, you could just do as you've said. Create a 1200x1200 canvas, then have your application convert the size values by a factor of 10 when necessary.

eg. `obj.getScaledWidth() * 10`

Let me know if I'm missing something.

**Comment by ShaMan123** [comment]
You can use `canvas.setViewportTransform` as well.
IMO you don't need the canvas to be so big. Objects are positioned regardless of canvas size and if they are off screen they don't get rendered unless you flag it `canvas.skipOffscreen = false`
