### ISSUE TITLE
Fabric rendering lagging on 8k, even with just one object and other 2 other canvas' without changes

### ISSUE THREAD

**Issue by TFTomSun** [fabricjs/fabric.js#7819]
## Version
4.6.0

## Test Case
https://jsfiddle.net/0wksnp7t/37/

## Information about environment
Nodejs or browser?
browser
Which browsers?
chrome
## Steps To Reproduce

1.  create 3 canvas - two are used as rulers, the 3rd one is the main canvas
2. add a circle to the main canvas
3. move the main canvas around 

## Expected Behavior
it's fluently moving
## Actual Behavior
it's lagging sometimes for a half second

**Comment by TFTomSun** [comment]
There was a bug in the fiddle ... the redraw of the rulers was called on mouse up. Closing

**Comment by asturur** [comment]
But don't expect fabricJS canvas to be extremely performing on 8k resolution. It works, but you can't make a 30fps video stream easily on standard machines
