### ISSUE TITLE
Rotation origin to be separate from position origin

### ISSUE THREAD

**Issue by ckosmowski** [fabricjs/fabric.js#782]
The way objects rotate seems inconsistent to me. I can't find a way to affect the point of rotation of an object directly.

If i change the origin of an object to be "top, left" like it is in most other graphics libraries, the object rotates around the "top, center" point and not the top, left point what feels inconsistent.

However, i just wanted to tell an object that its origin is top, left so i can easily use coordinates relative to the canvas or a group. But this shouldn't affect the point of rotation for this object. Wouldn't it be better to have these settings seperately?

Maybe i missed something.

**Comment by redlive** [comment]
Anybody can help me to understand what I'm doing wrong here [http://jsfiddle.net/juu826k3/2/](url) ? Basically, I'm trying to move and rotate a red element and get yellow element placed exactly in the same position as a background image of the red one.
Probably I'm doing something wrong with originX and Y but now sure what would be a solution.
Tnx in advance.
