### ISSUE TITLE
Testing library fabric.Text

### ISSUE THREAD

**Issue by CheekiBreaker** [fabricjs/fabric.js#7820]
When I test the text creation class, when I run the tests I get the error cannot set property 'textBaseline' of null. And I did not find methods for adding this in the list

Сlass creation code
![image](https://user-images.githubusercontent.com/74696977/158923098-88015439-ad2c-4a9a-b1c1-4f02d9e7bb12.png)
Test code
![image](https://user-images.githubusercontent.com/74696977/158923191-59eff9e3-f55d-4562-ac8e-8bfcfc221261.png)
 Console log: 
 
![image](https://user-images.githubusercontent.com/74696977/158923225-a1487071-4a85-4b2a-8c65-8795d2346cd9.png)

I testing with a jest.

**Comment by ShaMan123** [comment]
```diff
- const d = new Text();
+ const d = new fabric.Text();
```

??

**Comment by CheekiBreaker** [comment]
> - const d = new Text();
> + const d = new fabric.Text();

Text is class, which drawing this. 
>Class Text{
>draw(){
>---
>}
>}
The first screenshot

**Comment by ShaMan123** [comment]
Sorry, your comment is unclear

**Comment by ShaMan123** [comment]
closing.
edit your comments and reopen.
