### ISSUE TITLE
how to import pdf?

### ISSUE THREAD

**Issue by KiDeokKim** [fabricjs/fabric.js#7826]
when i created pdf file from Adobe Illustrator, and i'm trying to import pdf file in FabricJS.

i readed Demo in http://fabricjs.com/import-pdf

but when i tring to upload pdf file, it doesn't work.

and i have some question. when i upload PDF file, all object is grouped?

**Comment by ShaMan123** [comment]
As you can see in the demo a fabric.Image is created for the PDF.
You should put an effort in writing an issue if you want someone to put an effort in answering.
I am closing until you do so.
