### ISSUE TITLE
[v5] canvas doesn't load image on nodejs 

### ISSUE THREAD

**Issue by felahdev** [fabricjs/fabric.js#7828]
## Version
5.2.1 bug on node but it works perfectly on browser

## Test Case
http://jsfiddle.net/felahdev/2aet8p7j/

## Information about environment
node on windows 10 pro
15.14.0  64-bit
14.3.0  64-bit
10.24.1  64-bit
 8.9.0  64-bit
fabric package.json
 "optionalDependencies": {
    "canvas": "^2.8.0",
    "jsdom": "^19.0.0"
  }
## Steps To Reproduce

1. I have used all kind of loading image :
2. fabric.Image.fromURL( path || file://, (img) => { });
3. fabric.util.loadImage( path, (img) => { });
4. even fs, create element with jsdom, drawing with canvas loadImage(path).then((img) => {
    ctx.drawImage(image, 0, 0, 50, 00);
    canvas.add(canvasImage.toDataURL());
    ....
})

<details><summary>Error Message & Stack Trace</summary><p>
C:\www\fabric\node_modules\fabric\dist\fabric.js:9544
      obj._set('canvas', this);
          ^

TypeError: obj._set is not a function
    at klass._onObjectAdded (C:\www\fabric\node_modules\fabric\dist\fabric.js:9544:11)
    at klass.add (C:\www\fabric\node_modules\fabric\dist\fabric.js:379:14)
    at C:\www\fabric\image.js:30:12
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
</p></details>

## Expected Behavior
load image to use it as a pattern
## Actual Behavior
displaying error or when i save the canvas on png or jpg the output image will be emty 

![image](https://user-images.githubusercontent.com/34005624/159933021-7ff67d04-80c3-4111-bbd1-947fdb37f6de.png)
![image](https://user-images.githubusercontent.com/34005624/159933157-f9fac974-6d96-4dcd-98e0-8c9197493a23.png)

**Comment by ShaMan123** [comment]
v5+ has migrated to promises and dumped callbacks.
e.g.
```js
fabric.util.loadImage(path).then(img =>{})
```

**Comment by felahdev** [comment]
a lot of thx Mr shachar

**Comment by felahdev** [comment]
a lot of thx Mr ShaMan123 for ur quick response but I think it doesn't work :(

fabric.util.loadImage('imgs/1b72a5.png').then(img =>{
                                        ^

TypeError: Cannot read property 'then' of undefined
    at Object.<anonymous> (C:\www\fabric\image.js:8:41)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
![image](https://user-images.githubusercontent.com/34005624/159954152-113dff3d-dc45-486a-b62c-398946ad4be2.png)
![image](https://user-images.githubusercontent.com/34005624/159953956-925172b7-1f5b-4ecc-b710-e5617a964176.png)

**Comment by ShaMan123** [comment]
Your repro is not fit for node.

https://codesandbox.io/s/exciting-browser-ytb70

**Comment by felahdev** [comment]
there is my code [https://codesandbox.io/s/load-image-from-node-oqm32s?file=/index.js](url)

**Comment by felahdev** [comment]
Hey Mr Shachar,

there is a repo
https://codesandbox.io/s/load-image-from-node-oqm32s?file=/index.js
