### ISSUE TITLE
Textbox: changing props while editing

### ISSUE THREAD

**Issue by gerardwilson1** [fabricjs/fabric.js#7836]
## Version
3.6.0, 4.6.0, 5.2.1 (These are the versions I tested this issue against) 

## Test Case
- [ ] [Browser Issue Template](https://jsfiddle.net/Lcp2h3nv/)
- [ ] [Node Issue Template](https://codesandbox.io/s/exciting-browser-ytb701)

## Information about environment
Nodejs: v16.13.0
Browser: Chrome v99.0.4844.83

## Steps To Reproduce
This issue is happening in a separate React application, but this [JS fiddle ](https://jsfiddle.net/GWilson1/wpx4ju9z/7/)is a simplified version which shows the issue I'm facing. 

1. Unlock the X and Y axis by clicking on the Lock x axis and Lock y axis checkboxes.
2. Move the text around (expected behaviour)
3. Click in the text so it is editable.
4. Click on the Lock x axis and Lock y axis checkboxes
5. Now uncheck the Lock x axis and Lock y axis checkboxes
6. Click anywhere on the canvas
7. Then click on the text and try moving it.The text does not move even though the Lock x axis and Lock y axis are unchecked

<details><summary>Error Message & Stack Trace</summary><p>. No error message

```txt
<!-- Provide a log message if relevant -->
```
</p></details>

## Expected Behavior
If you click off the text and back on it, it should allow the user to move the text due to the lockMovementX and LockMovementY options being set to false.

## Actual Behavior
If you click off the text and then back on it, the text does not move, the lockMovementX and lockMovementY options get set to true. It seems that when the text goes into edit mode, e.g. isEditable the lockMovementX and lockMovementY options are set to true by default, but then do not change when looking to move the text.

**Comment by ShaMan123** [comment]
You are right.
Internally iText uses these lockMovementX /Y
This is why it's happening

as a workaround you can listen to the `editing:exited` event and restore state there.

I will PR to fix this.

**Comment by ShaMan123** [comment]
@gerardwilson1 Try the fix and report back

**Comment by gerardwilson1** [comment]
Hi @ShaMan123 I tried creating an event listener for `editing:exiting` and checking an isElementLocked function I have that checks if the element is locked by checking if the following is true (I have a lock function that sets these options like so): 
 ```
 element.hasControls = false;
  element.hasBorders = false;
  element.lockMovementX = true;
  element.lockMovementY = true;
  element.lockRotation = true;
  element.lockUniScaling = true;
```
This didn't work. 

So In the event listener for `selection:created` I check isElementLocked and either lock it again if true or unlock if false. 
But then I saw strange behaviour where if I was in edit mode when I locked the text, then clicked on the canvas and then clicked on the text, it was unlocked and moveable. 
So I have a `before:selection:cleared` event listener that checks isElementLocked and either lock it again if true or unlock if false.

I ended up changing my isElementLocked function to only check if   `element.lockRotation = true`. 

The above fixes have worked for me.

**Comment by ShaMan123** [comment]
Take notice to details `editing:exited`
lock will take affect only if set to true so if your checkbox doesn't reflect the state of the object ofcourse it won't work.
visible prop is probably overriden by active selection, call `discardActiveObject`

https://jsfiddle.net/rtjkf6w0/1/
