### ISSUE TITLE
Cannot add id to fabric objects

### ISSUE THREAD

**Issue by Sayan-dev** [fabricjs/fabric.js#7843]
First of all there is no defined type id for object.
There is a need to add custom ID for identification of objects, and that is not possible. 
There is no id parameter defined in Image class or any other classes, and thus I assume id has been removed.
Please look into the issue.
Any help welcome

**Version: 5.2.1**

**Comment by asturur** [comment]
no id never existed, you can add it if you want it, manually, and then taking care it is exported to object, using the `additionalProperties` option.
