### ISSUE TITLE
Bug or feature ?  Nested subclass group Maximum call stack size exceeded

### ISSUE THREAD

**Issue by JeanMeche** [fabricjs/fabric.js#7854]
## Version
5.2.1

## Test Case
[Stackblitz](https://stackblitz.com/edit/fabricjs-testing-msjx5x?file=rack.ts)

## Steps To Reproduce

I'm looking to create subclasses using groups (with fabric.util.createClass). 

But when I'm trying to add one of these subclass into a group subclass, I get a  `Maximum call stack size exceeded` error. 

It this a bug or a desired behaviour that we don't need to add the the subclass in a group subclass ? 

Thanks in advance for the heads-up !

**Comment by ShaMan123** [comment]
Definitely a bug on your side.
https://stackblitz.com/edit/fabricjs-testing-nzhjet?file=rack.ts

Take into account that we are rewriting group completely so internals will change #7670

**Comment by JeanMeche** [comment]
Awesome,  thanks for the help and the work you put into this lib !
