### ISSUE TITLE
Cannot add custom control to Textbox

### ISSUE THREAD

**Issue by GiorgioBaldelli** [fabricjs/fabric.js#7856]
## Version
5.2.1

## Test Case
- [Codepen](https://codepen.io/giorgiobaldelli/pen/wvpPZOg)

## Information about the environment
Nodejs or browser? Browser
Which browsers? All

## Steps To Reproduce

1.  Check this example in [the documentation](http://fabricjs.com/custom-control-render). Please note the remove control that is rendered with a red icon when selecting a rectangle.
2. After that, run [this example](https://codepen.io/giorgiobaldelli/pen/wvpPZOg). 
3. Click on the textbox element. Result: the remove control icon is not rendered.

## Expected Behavior
- Correct rendering of the remove control icon after selecting a Textbox element.

## Actual Behavior
- The remove control icon is not rendered after selecting a Textbox element
--

**Comment by ShaMan123** [comment]
I dislike the fact the controls are a shared object. It's too confusing.
https://codepen.io/shaman123/pen/xxpPvVj

```diff
- fabric.Object.prototype.controls.deleteControl
+ fabric.Textbox.prototype.controls.deleteControl
```

**Comment by ShaMan123** [comment]
+1 @asturur to make controls not shared once migrating js/ts (we can test perf to see it isn't damaging)
I override all controls for each instance
