### ISSUE TITLE
Error "Cannot read properties of null (reading 'save')" for `renderTopLayer` method calling

### ISSUE THREAD

**Issue by vitonsky** [fabricjs/fabric.js#7876]
## Version
4.6.0

## Information
In some cases we get error "Cannot read properties of null (reading 'save')".
I don't know why it is, but as i see, we don't check type of object `ctx` in the `renderTopLayer` method.

Let's insert type guard there or will review calls to `renderTopLayer` and insert condition there.

<img width="749" alt="image (49)" src="https://user-images.githubusercontent.com/86191922/163015393-0f6f6d18-d27a-465b-9b4a-040105679a44.png">
<img width="526" alt="image (50)" src="https://user-images.githubusercontent.com/86191922/163015397-28b31732-51e8-4ca6-b49c-10a069ca3aa3.png">

**Comment by kirill-konshin** [comment]
@asturur looks like additional check is needed if `ctx` is available. I've noticed that such check exist in other places in the code, but not here.

**Comment by ShaMan123** [comment]
This usually happens when your app doesn't cleanup properly in debug mode. For example react fast refresh will reach this if you don't cleanup your `runningAnimations` from a `useEffect`

**Comment by kirill-konshin** [comment]
Does it still make sense to add a check to renderTopLayer?

We will look for unfinished animations and timers in the mean time.

**Comment by ShaMan123** [comment]
I don't think so.
Maybe we should check all preconditions at the beginning of the rendering cycle in DEV mode only and warn about stuff.
That could be useful.
Otherwise it might be counter productive.
On the same topic, take a look at a draft I made for a [`useCanvas` hook](https://github.com/fabricjs/fabricjs-react-sandbox/blob/main/common/template/src/fabric/useCanvas.ts)

**Comment by kirill-konshin** [comment]
We use similar mechanism in our implementation of `useCanvas` hook.

I'd say it would be useful to check preconditions before rendering cycle AND warn in DEV mode.

**Comment by asturur** [comment]
renderTopLayer isn't called alone, if not inside events with the mouse.
We can safeguard renderTopLayer wrapping it in the dev mode, and add a stackTrace so that people, without getting the error, can still see where the error is coming from.

I don't like defensive javascript that much, but is true that the situation thend to become complex with react/hooks/rerender and eventually the canvas element removed and re-added in the dom.

**Comment by ShaMan123** [comment]
I think proper errors is not something we should worry about.
Rewriting to typescript with source maps will give proper context of the error out of the box.

**Comment by kirill-konshin** [comment]
If the error happens in internal loop, it would be quite hard to trace which listener/effect has caused this. It feels like the loop is not aborted in time and one last render attempt is happening after unmount.

**Comment by ShaMan123** [comment]
That's why I have exposed `fabric.runningAnimations.cancelXXX`

**Comment by kirill-konshin** [comment]
I don’t think we even have any running animations…

**Comment by vitonsky** [comment]
I've checked `fabric.runningAnimations` and it is `undefined`.

I can't even found defining of `runningAnimations` in the code, https://github.com/fabricjs/fabric.js/search?q=runningAnimations is give 4 results when 2 is tests and 2 is usages.

I suggest to add condition which will check `ctx` object and skip render when it is empty.

As i see, we don't use fabric animations in our code base, but we got this error. We also don't call `renderTopLayer` manually, so, according to the stack trace on my screenshot, we have problem on the library side.

@asturur i agree with you about defensive javascript, but this is other case, we should implement minimal required validations to ensure library API will work and will not thrown unexpected exceptions. When users of fabric is call `requestRenderAll`, and then do something (i don't know what user did, but for example user will unmount canvas) they shouldn't get any exceptions.

**Comment by ShaMan123** [comment]
I found a race condition.
When you call canvas.dispose and meanwhile `requestRenderAll` starts rendering then this bug occurs.

**Comment by ShaMan123** [comment]
> I've checked fabric.runningAnimations and it is undefined.

> I can't even found defining of runningAnimations in the code, https://github.com/fabricjs/fabric.js/search?q=runningAnimations is give 4 results when 2 is tests and 2 is usages.

https://github.com/fabricjs/fabric.js/blob/1b99e620dc02827bf10157d90064ac3cc66f9eb7/src/util/animate.js#L267

**Comment by vitonsky** [comment]
> > When users of fabric is call requestRenderAll, and then do something (i don't know what user did, but for example user will unmount canvas) they shouldn't get any exceptions.
> 
> There is a race condition. When you call `canvas.dispose` and meanwhile `requestRenderAll` starts rendering then this bug occurs.

Understood. I think we may fix it, we should just check `ctx` and use early return for `undefined` objects. It's very cheap and safety for all. Can we implement this logic?

**Comment by ShaMan123** [comment]
Perhaps we should add an `AbortController` to `requestRenderAll`, sounds good to me - complementing #7827

**Comment by ShaMan123** [comment]
> Perhaps we should add an `AbortController` to `requestRenderAll`, sounds good to me - complementing #7827

This is bollocks.

I think the race condition should be solved by waiting will the dispose until the rendering has finished. But that might cause other race conditions... We could return ap romise that resolves once disposing has finished

**Comment by ShaMan123** [comment]
> Understood. I think we may fix it, we should just check ctx and use early return for undefined objects. It's very cheap and safety for all. Can we implement this logic?

Sounds the best solution

**Comment by ShaMan123** [comment]
I gave another look to the dispose method and a test I wrote.
Try testing your cases with the PR. My test passed. But there might still be an edge case.
Adding to @asturur I prefer to understand where this is coming from before adding checks

**Comment by asturur** [comment]
let me read that PR

**Comment by kirill-konshin** [comment]
Is the fix planned for v5 or v6? We're still stuck on v4 btw.
