### ISSUE TITLE
Setting strokeUniform:true breaks polygon points editing when the polygon is scaled

### ISSUE THREAD

**Issue by graphics-et-al** [fabricjs/fabric.js#7881]
## Version
5.0.0

## Test Case
[http://jsfiddle.net/wilheim/q7brhmcn/1/](http://jsfiddle.net/wilheim/q7brhmcn/1/)

## Information about environment
Browser and Svelte

## Steps To Reproduce

1. In the points editing example at [http://fabricjs.com/custom-controls-polygon](http://fabricjs.com/custom-controls-polygon), set the polygon's strokeUniform property to true
2. Hit 'Toggle editing polygon' button
3. Move a control point

## Expected Behavior
Only the control point moves

## Actual Behavior
The whole polygon moves in unexpected ways

There's an inelegant workaround available by toggling the strokeUniform property when starting and stopping editing, but it's aesthetically terrible.

I suspect it has to do with some internal line weight not updating when scaled. The editing polygon works as expected when the polygon is not scaled.

**Comment by ShaMan123** [comment]
duplicate #7605 
check out #7639
