### ISSUE TITLE
Unselectable(selectable: false) object does not fire mouse down or mouse up event

### ISSUE THREAD

**Issue by SergiiMarkin** [fabricjs/fabric.js#7894]
### I would like to achieve following things

1. Set object (image object) to 'selectable: false'.
2. Support Unselectable object of event fire to catch 'mouse:up' or 'mouse:down' event

**Here is code snippet.**

```
- Define Image object

      fabric.Image.fromURL(imageUri, (img) => {           
                const fbImg = img.set({
                  ...
                  selectable: false
                });
                fbImg.setControlVisible('mtr', false);
                canvas.add(fbImg);
                canvas.sendToBack(fbImg);
      });

- Listen mouse:up event on canvas, and print undefined when catching 'mouse:up' event by clicking on unselectable image.

     canvas.on('mouse:up', (e) => {
           console.log('event target', e.target) // log undefined when triggering 'mouse:up' event by clicking on unselectable image on canvas.
      })
```

**Expected behavior**

When user clicks to trigger mouse:up event by clicking on 'unselectable' image on canvas, I would like to get the image object from event.target if user clicks on unselectable image.
console.log(event.target) // Log Image object

**Actual behavior**
console.log(event.target) // Log undefined

Thanks in advance

**Comment by ShaMan123** [comment]
Add working reproductions.
