### ISSUE TITLE
Object is removed if top left corner is moved out of viewport

### ISSUE THREAD

**Issue by gtorf** [fabricjs/fabric.js#7905]
## Version
4.5.0 (since jsfiddle only supports 4.5.0 but it happens also in 4.6.0)

## Test Case
- [ ] [Browser Issue Template](https://jsfiddle.net/swq47gyx/2/)

## Information about environment
Nodejs or browser? => Browser
Which browsers? => Chrome Version 100.0.4896.127

## Steps To Reproduce

1. use the jsfiddle
2. click the "rect" button
3. hold the left mouse key and draw a new rectangle (keep the mouse key pressed) - this will create a yellow rect
4. press and hold the "alt" key on your keyboard and move the mouse (the mouse key is still pressed) - you are panning around now
5. move the view, so that the top left corner of the rect will be outside the canvas - the yellow rect will disappear

## Expected Behavior
the rectangle you stay visible

## Actual Behavior
the rectangle disappears, if the top left corner is moved out of current view port

**Comment by ShaMan123** [comment]
can't reproduce

https://user-images.githubusercontent.com/34343793/165221985-944fe348-7ee1-469d-bc61-73768c79c76c.mp4

**Comment by gtorf** [comment]
Please reopen.
You released the mouse before you moved the rect.
The rect has to be yellow during moving

**Comment by ShaMan123** [comment]
Add a video and a better explanation and I'll reopen

**Comment by ShaMan123** [comment]
Your code is messed up.
It's not fabric.

**Comment by gtorf** [comment]
https://user-images.githubusercontent.com/87463071/165244149-a24aed8a-6abd-4cd5-a45b-30729774941a.mp4

1. I am drawing the rect, keeping the left mouse button pressed
2. now additionally press the Alt Key and drag the rect around

you can see, that if the top left corner is moved out of the visible area, the hole rect disappears

**Comment by ShaMan123** [comment]
AFAICT it is a problem with your logic.
You should take into consideration that I plan to merge #7713 which will render your code even more broken I presume.
Anyways... it's not fabric. And you probably need to call `setCoords` and if that doesn't fix it your logic needs much more work or you could simply disable the perf opt by `canvas.skipOffscreen=false`

**Comment by asturur** [comment]
as @ShaMan123 said, you can still remove the optimization if you don't plan to have many objects on screen and using zoom extensively. The result will be the same

**Comment by gtorf** [comment]
Thanks a lot for your answers!
The skipOffscreen option worked for me. But I will test it also with many objects.

**Comment by asturur** [comment]
Important is that you understand why it wasn't behaving as expected.
Disabling  skipOffScreen is a patch/workaround that is fine as long as you
got it.

Il giorno mar 26 apr 2022 alle ore 16:19 gtorf ***@***.***>
ha scritto:
