### ISSUE TITLE
svg render suggestion

### ISSUE THREAD

**Issue by incaluce** [fabricjs/fabric.js#7909]
hi,
Howdy I'm importing an svg file created with Inkscape, this immagne is on firefox:
<img width="491" alt="Immagine 2022-04-27 184201" src="https://user-images.githubusercontent.com/104519871/165574969-b534ec99-4381-4c13-8a0a-8f2ac824472a.png">

when I add it to the canvas I have this result:
<img width="340" alt="Immagine 2022-04-27 184516" src="https://user-images.githubusercontent.com/104519871/165576485-535e7e02-a77e-4b38-9ce8-3a7489993456.png">

does anyone have any suggestions to help me understand why it happens?

regards,
Maurizio

**Comment by ShaMan123** [comment]
@incaluce we have an issue template for a reason.
Please fill it out. No one can do anything with this issue. Nor would they want to.
Finding bugs can be difficult, why make it even more difficult by guessing your svg file?
Add that and a working reproduction and then I'll reopen.

**Comment by incaluce** [comment]
ok, I understand, 
I am sorry

**Comment by asturur** [comment]
Provide at least the SVG, for svg parsing issues if the error appear the same in the fabricjs.com/kitchensink demo using the load SVG tab, that is enough for us to replicate

**Comment by incaluce** [comment]
Hi thanks,
for the reply.
In my case the problem seems to have been due to the file.svg itself.
After some operation of opening and re-saving the representation in the canvas has become correct.
The strange thing is that even before through the various browsers or svg viewers online I saw it well.

**Comment by asturur** [comment]
if you parse the SVG with fabricJS you don't get a perfect 1:1 drawing. some effects are not supported.
Differently if you use it as an image it works.
It is for sure the svg file and that is why i wanted to see the broken one.
Happy you solved it tho
