### ISSUE TITLE
Custom fonts not rendering in Arch based linux distros

### ISSUE THREAD

**Issue by xorb** [fabricjs/fabric.js#7910]
NOTE: It works fine with debian based distros. Are there missing dependencies ?

## Version
5.2.1

## Test Case
- [ ] [Browser Issue Template](https://jsfiddle.net/Lcp2h3nv/)
- [x]  [Node Issue Template](https://codesandbox.io/s/fabric-custom-font-9gcufi)

## Information about environment
Nodejs or browser? NodeJS
Which browsers? - 

## Steps To Reproduce

1. Download sample project: `git clone git clone https://github.com/xorb/fabric-custom-font`
2. Install dependencies; `npm install`
3. Run project: `npm start`

<details><summary>Error Message & Stack Trace</summary><p>

## Expected Behavior

It should render custom fonts

## Actual Behavior

Rendering system default font

![alt text](https://i.ibb.co/mDW4c1Y/customfont.png "image Title")

**Comment by ShaMan123** [comment]
This sounds like an issue in node canvas.
Try creating a repro without fabric and report back.
I suggest you add visual of expected/actual

**Comment by asturur** [comment]
Shouldn't be related, but definitely if is something distro specific we can't really solve it.
I won't have time to get a Arch based distro a poke around.
Please open an issue on the node-canvas repo and let us know.
You have to reproduce with plain node-canvas first, i can help to write a snippet for that if you need.

**Comment by xorb** [comment]
Yeah, seems like node-canvas issue. Created issue there. https://github.com/Automattic/node-canvas/issues/2058
