### ISSUE TITLE
object scaled not clearly ( low quality )

### ISSUE THREAD

**Issue by rkawkxkdwlq** [fabricjs/fabric.js#7911]
when i scaled down object, object become not clear ( low quality )

it's group with path objects

![image](https://user-images.githubusercontent.com/24672968/165874620-ee91e00b-8fa0-4850-9f64-aaf99d500c83.png)

**Comment by ShaMan123** [comment]
We have an issue template for a reason.
Please fill it out. No one can do anything with this issue. Nor would they want to.
Add a working reproduction and then I'll reopen.
