### ISSUE TITLE
Can I update the vertex of the polygon?

### ISSUE THREAD

**Issue by zjlzlr** [fabricjs/fabric.js#7912]
![image](https://user-images.githubusercontent.com/8189294/165880314-3e5ca9ac-f23d-4499-9a75-411221b438c6.png)

When I update the point of the polygon the bounding is misplace,How can I update one of the points?

**Comment by ShaMan123** [comment]
@zjlzlr call `_setPositionDimensions` before `setCoords`. Should fix.

@asturur maybe we should call `_setPositionDimensions` from `setCoords`. Does that make sense?
It is likely that most devs will encounter this poor design, as did I.
