### ISSUE TITLE
[MacOSX Monterey+Safari 15.4] It seems rendering works with extra huge delay

### ISSUE THREAD

**Issue by solomax** [fabricjs/fabric.js#7926]
We are using 4.6.0, but the issue is reproducible with 5.2.1 as well (would appreciate if fixed 4.x.x can be released :)))

## Version
4.6.0
5.0.0

## Test Case
https://codepen.io/solomax/pen/abqOMWO

## Information about environment
browser: Safari 15.4 at MacOS 12.3.1

everything works as expected at 
1. any browser at Ubuntu
2. FF100 at MacOS 12.3.1

## Steps To Reproduce

1. Load test case
Result: image might not be loaded
3. in case image was loaded, try to move it
Result: there is no visual effect
4. Switch to another browser tab
5. wait 15-30 seconds
6. Switch back
Result: moved image is displayed at new position

ps canvas at http://fabricjs.com/ is not being displayed momentally

**Comment by solomax** [comment]
Just have performed additional tests:

Everything works as expected at "real" `iPad iOS 15.2.1, 15.4.1`
as well as at `MacOS: 11.6.5, Safari: 14.1.2`
but fails at `MacOS 12.3.1, Safari 15.4`

I got MacOS 11 and 12 using https://github.com/sickcodes/docker-osx
not sure if this info is useful ... :(

**Comment by ali-alhaidary** [comment]
see the video please
https://issues.apache.org/jira/browse/OPENMEETINGS-2730

**Comment by greenes2** [comment]
I'm not sure if I understood the question. But my test on Monterey 12.3.1 with Safari 15.4 is this:
Everything works as expected except to share desktop FF or Chrome to Safari. Yes works right
from Safari to FF or Chrome.

Is a video moving an image as expected. The same works as expected the recordings
on WB.

https://issues.apache.org/jira/secure/attachment/13043479/Safari%20154%20Monterey%201231.mov

Excuseme please if this is not it you are asking for.

**Comment by sebawagner** [comment]
Works fine for me too. Including moving on WB 

![image](https://user-images.githubusercontent.com/5152064/167777817-e4a55c8d-f41f-4388-9dec-d9c167a055e9.png)

**Comment by solomax** [comment]
Seems to be the problem with my VM :(
sorry for the noise :((

**Comment by sebawagner** [comment]
Recording also seems fine

![image](https://user-images.githubusercontent.com/5152064/168028452-12121316-435e-48ca-a68e-385bb016ea6c.png)
