### ISSUE TITLE
The objects inside a group - controls are not working

### ISSUE THREAD

**Issue by dennisideaonce** [fabricjs/fabric.js#7927]
## Version
4.6.0

## Problem

The objects inside a group - controls are not working.

### The problem: 
![Coming as](https://user-images.githubusercontent.com/81302013/166970302-a74486cc-775f-40d6-907b-2833dbf88d4b.gif)

### The expectation:

![Expectation](https://user-images.githubusercontent.com/81302013/166971155-1c6bbc9f-ce2c-4c6b-8253-f9a93adfd7f5.gif)

### In the actual application:

https://user-images.githubusercontent.com/81302013/166972608-0447c208-c5fe-4d83-b6b2-1a4589ea19eb.mov

The controls of the selected object are not at the right position. It should be above the selected group object. I am sure I am missing something.

Jsfiddle: http://jsfiddle.net/e3j40v6d/28/

## Description
I am trying to build a simple image editing tool using fabric js. I have created a group of active selections by using the below code:

```
group() {
    const object = this.canvas.getActiveObject();
    if (object.type != 'activeSelection') {
        return;
    }
    let isTextboxInGroup = false;
    for (let obj of object.getObjects()) {
        if (obj.type === 'textbox') {
            isTextboxInGroup = true;
        }
    }

    const newgroup = object.toGroup();
    newgroup.perPixelTargetFind = true;
    newgroup.objectCaching = false;
    newgroup.id = this.randomId();
    newgroup.lockUniScaling = isTextboxInGroup ? true : false;
    this.canvas.discardActiveObject();
    this.canvas.setActiveObject(newgroup);
    this.canvas.requestRenderAll();
}
```

I want to click on a button and select an object from the group and use its controls like scaling up and down rotate freely. Right now the controls and selected objects are not at the right position. I am not able to  use the controls at all.

```
makeCurrentObjectActive($event, object) { // object is an object from the group
    // this.ungroup();
    if (!object) {
      return true;
    }

    $event.preventDefault();
    $event.stopImmediatePropagation();
    // delete object.group; // If I add this the object box sorounding it goes into too left, I understand that deletes the group
    this.canvas.discardActiveObject();
    this.canvas.setActiveObject(object);
    this.canvas.requestRenderAll();
  }
```

Any help is highly appreciated, Thank you!

**Comment by ShaMan123** [comment]
Dude you're looking for v6.
#7670

**Comment by dennisideaonce** [comment]
Yes I just noticed the same. One quick question is there any estimated date of release for this?

I hope it will also work for .toGroup(); @ShaMan123
