### ISSUE TITLE
onComplete doesn't called after stop animation

### ISSUE THREAD

**Issue by Drapaliuk** [fabricjs/fabric.js#7931]
## Version
5.2.1

## Information about environment
Browser Version 101.0.4951.54 (Official Build) (64-bit)

## Steps To Reproduce
Our team has updated fabric to 5.2.1 and our logic of animation is built on calling onComplete callback into the fabric.util.animate function (we should resolve promise here) but now this logic is broken because in the new version after aborting animation you just remove animation from the animation list and don`t call onComplete.
Please return the previous logic with a call onComplete or explain why it is not possible.
As a proposal,  you can add callback onStop/onAbort/onInterrupt (up to you)  and call it when animation was stopped to get more accurate control over the animation cycle
## Expected Behavior
Call onComplete after stop animation
## Actual Behavior
onComplete doesn`t called after animation stop

![Screenshot_464](https://user-images.githubusercontent.com/36817736/167422411-52427844-c224-48ba-9153-83ec6a1021c0.jpg)

**Comment by ShaMan123** [comment]
This is intentional, aborting should not trigger the completed callback.

**Comment by ShaMan123** [comment]
Should be written in CHANGELOG

**Comment by ShaMan123** [comment]
https://github.com/fabricjs/fabric.js/pull/7528/files#diff-4c788168c81ce977ee91d228587e70e438fdd375b832462bcc998fa1e111ff4aL57

**Comment by Drapaliuk** [comment]
> This is intentional, aborting should not trigger the completed callback.

Okay, but how we can know that a user aborted animation to reset values of animation?

**Comment by ShaMan123** [comment]
It depends on your logic. Fabric doesn't handle anything regarding imperative aborting.

**Comment by Drapaliuk** [comment]
> It depends on your logic. Fabric doesn't handle anything regarding declarative aborting.

And you will not add a new callback for the case of aborting?
