### ISSUE TITLE
fabricCanvas.toDatalessJSON() why the line.x1,x2,y1,y2 is changed

### ISSUE THREAD

**Issue by 737261520** [fabricjs/fabric.js#7935]
example：
  `const line = { left: 100,  top: 100，x1:  100,  y1: 100, x2:  200, y2: 200 };
   const objToJson =  fabricCanvas.toDatalessJSON();  //{ left: 100,  top: 100，x1:  0,  y1: 0, x2:  100, y2: 100 }
`

**Comment by ShaMan123** [comment]
This is design.
When you initialize an object you pass values in the canvas coordinate plane. 
Then the object handles values in it's own coordinate plane, ref:
https://github.com/fabricjs/fabric.js/blob/e80ca902dfd4c25bb8fb9d6597a73f3668a54560/src/shapes/line.class.js#L216

**Comment by ShaMan123** [comment]
You can use `fabric.util.sendPointToPlane` to get the point in the canvas coordinate plane as follows:
```js
const point = line.x2;
fabric.util.sendPointToPlane(point, line.calcTransformMatrix(), null);

```
