### ISSUE TITLE
duplicate canvas container and upper canvas

### ISSUE THREAD

**Issue by qingwufong** [fabricjs/fabric.js#7968]
## Version
3.6.4

## Test Case
- [ ] [Browser Issue Template](https://jsfiddle.net/Lcp2h3nv/)
- [ ] [Node Issue Template](https://codesandbox.io/s/exciting-browser-ytb701)

## Information about environment
Nodejs or browser?
Which browsers?
 Chrome 101.0.4951.54
## Steps To Reproduce
 reproduce in our vue project and business scenario
1. init fabric canvas and pencil brush is ok
2. destory component
3. new component and reinitialize frabic canvas

<details><summary>Duplicate canvas container and upper canvas</summary>
dom structure disorder, and duplicate upper canvas make draw brush not working.
<p>
![1653442353(1)](https://user-images.githubusercontent.com/6860888/170159749-606f4b17-4d7d-4bff-aa1f-8478f55a0645.png)
</p>
</details>
Screenshot as follow:
![1653442353(1)](https://user-images.githubusercontent.com/6860888/170159749-606f4b17-4d7d-4bff-aa1f-8478f55a0645.png)

**Comment by ShaMan123** [comment]
This is a known issue. Your app is initializing canvas more than once.
Once you upgrade to the latest version you will get an error.
