### ISSUE TITLE
Default easing is not linear

### ISSUE THREAD

**Issue by marekburiak** [fabricjs/fabric.js#797]
The tutorial says: "By default, animate uses linear function for animation".

The animate function defines this default easing function:
function(t, b, c, d) {return -c \* Math.cos(t/d \* (Math.PI/2)) + c + b;}

which is not linear. Linear should be:
function (t, b, c, d) {return c*t/d + b;}

So please either update the tutorial or change the default easing function in animate or add fabric.util.ease.linear function.

**Comment by amkazan** [comment]
still a problem. When you make a sequence - next animation in OnComplete the default easing is like a tramway - goes, stops,goes stops - just doesn't go without a rest

**Comment by thebolet** [comment]
Hi,

Is there a linear function ?

**Comment by gpxlBen** [comment]
I couldn't find a linear function, and default seems to ease, so I wrote one:

`function easeLinear(t, b, c, d) {
    return (c/2)+(-c + ((c/d)*t));
  }`

**Comment by mbaierl** [comment]
@kangax - how about adding this linear easing option to the code?

**Comment by erikaadvisser** [comment]
Hmm, the linear ease function suggested by @gpxlBen seems to be broken. Use this one instead:

function easeLinear (t, b, c, d) {
    return b + (t/d) * c;
}
