### ISSUE TITLE
Problem with setting offsetY attribute for the mtr control

### ISSUE THREAD

**Issue by Devika-Keni** [fabricjs/fabric.js#7978]
There seems to be an issue with setting the offsetY attribute for the mtr control of an object. Although the offsetY gets set correctly for the object in question, it also seems to override the offsetY property of all other object 'mtr' controls.

Issue observed in version :  "fabric@5.2.1",
Code used 👎 
As per the latest guidelines for usage (for fabric version 4 and above) I  am following the above link
http://fabricjs.com/controls-customization.
In the code on that page ,pls refer to the line 👎    canvas.item(0).controls.mtr.offsetY = -parseFloat(this.value);
In the above demo, since there is only one rectangle the problem is not identifiable. Pls add another element to the canvas, and try execute the line above.. You will fin that it changes the offset for all the objects, rather than only the one

**Comment by ShaMan123** [comment]
@asturur 
#7914
