### ISSUE TITLE
getElementOffset is broken when used with shadow DOM

### ISSUE THREAD

**Issue by emabiz** [fabricjs/fabric.js#7979]
## Version
5.2.1

## Description
Inside the function getElementOffset, line 164 is:
`docElem = doc.documentElement;`
it should be:
`docElem = doc.documentElement || doc.host;`

It is similar to this:
[https://github.com/fabricjs/fabric.js/issues/2461](url)

**Comment by ShaMan123** [comment]
I encourage you to PR

**Comment by YashasviChaurasia** [comment]
@ShaMan123 @emabiz, can I contribute using this if it is still open?

**Comment by emabiz** [comment]
Hi, 
I simply put a workaround in my code like this:
`
if(!!this.canvas_draw.ownerDocument.host){
    this.canvas_draw.ownerDocument.documentElement=this.canvas_draw.ownerDocument.host;
}
`
but it is better for sure to create a pull request if nobody can quickly fix it.
Also there is the 2461 issue that basically is the same issue.

Thank you

**Comment by YashasviChaurasia** [comment]
issue#2461 has been resolved maybe as I am unable to find it

**Comment by emabiz** [comment]
merged with this:
https://github.com/fabricjs/fabric.js/pull/2462

**Comment by YashasviChaurasia** [comment]
I have submitted the PR a for issue #7979

**Comment by emabiz** [comment]
thank you
