### ISSUE TITLE
Can not fill color in path with canvas.loadFromJSON()

### ISSUE THREAD

**Issue by twin-92** [fabricjs/fabric.js#7985]
I use canvas.loadFromJSON().
When I fill color in object "rect": it's ok. (blue color)
But when i fill color in object "path": it not working.
Code is in Test Case.
Thank you for your help
## Version
5.2.1

## Test Case
- http://jsfiddle.net/qk8zhj7n/17/

## Information about environment
Nodejs or browser?
Which browsers?

## Steps To Reproduce

1. 

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```
</p></details>

**Comment by ShaMan123** [comment]
I have no idea what you are trying to accomplish but it is not an issue on our side.
You are misusing `globalCompositeOperation`
