### ISSUE TITLE
I want to disable selection of object on multi finger touch like on Pinch

### ISSUE THREAD

**Issue by Rajdeepc** [fabricjs/fabric.js#7986]
@asturur 
My use case:

I have a full canvas image and few stickers on top of it on a canvas. 
User comes for the first time and none is selected.

users does two finger pinch on the image and wants to zoom.

I have the following code:
```
canvas.on({
      'selection:created': updateActiveObject,
      'selection:updated': updateActiveObject,
      'selection:cleared': onSelectionCleared,
      'object:moving': onObjectMoving,
    });
```
Whenever I am touching an object with two fingers selection:created: updateActiveObject is getting called but e.touches have only 1 element. It never pushes more than 1 element.

Currently:
On clicking of any finger on image it is getting selected

Expected:
When more than one finger is places at a time on any object it should not select anything on multi touch.

**Comment by Rajdeepc** [comment]
Technically I need the below functionality

on tap on an object - object selected show freeform controls
on pinch anywhere on the canvas with objects - zoom in and zoom out
on tap + pinch on an object - resize the object

**Comment by ShaMan123** [comment]
You should provide a reproduction
Overriding `Canvas#__onMouseDown` should solve the issue
