### ISSUE TITLE
    "postinstall": "cd node_modules/fabric && yarn build_with_gestures" is giving window not defined

### ISSUE THREAD

**Issue by Rajdeepc** [fabricjs/fabric.js#7995]
@ShaMan123 
trying to build fabric with gestures in a postinstall script
while doing so getting window not defined on the following path
```
ReferenceError: window is not defined
    at /Users/rajdeepc/Documents/Projects/loop/create-together/node_modules/fabric/dist/fabric.js:563:2
```

I checked the path and it is failing due to null check on window in several instances.
How can i solve this.

fabric: ^5.7

I am installing this fabric on a nextjs project.

**Comment by KKzLEO** [comment]
I encountered the same issue, I installed custom build and there's somewhere using `window`, any workaround for it?

**Comment by ShaMan123** [comment]
duplicate #8444 ?
