### ISSUE TITLE
Issue while clipping an image with a mask

### ISSUE THREAD

**Issue by ashok-damani** [fabricjs/fabric.js#7999]
## Version
5.2.1

## Test Case
https://jsfiddle.net/3904Lqon/3/

## Information about environment
Google Chrome

## Steps To Reproduce

1. Click on add frame to canvas button
2. Click on clip button 

## Expected Behavior
I want to clip the image with a mask, same as the added frame to the canvas.
Clipping mask should be have the same width, height & angle of the frame added to the canvas

## Actual Behavior
Not keeping the same size (width & height) of the clipping mask as frame's

**1. When image & frame added to the canvas**
![image](https://user-images.githubusercontent.com/73891255/173008943-1e027e31-492d-4c21-8933-67ed6417110b.png)

**2. When I clip the image**
![image](https://user-images.githubusercontent.com/73891255/173009069-f98b7c8f-4748-42ac-b637-fdedd0c453dd.png)

**Comment by ShaMan123** [comment]
Please don't span the repo.
You have the discussion and that's where you should continue.
Read relevant docs about group, relative coordinate systems and check out `fabric.util.sendObjectToPlane`.
You should read my previous comments for other devs facing the same trouble.
