### ISSUE TITLE
`Canvas._absolutePointer` stale state

### ISSUE THREAD

**Issue by carterw485** [fabricjs/fabric.js#8009]
## Version
5.2.0

## Test Case

- fabric 2.2.4 - Working well: https://jsfiddle.net/carter485/r5eoc8Lx/4/

- fabric 5.2.1 - buggy behavior: https://jsfiddle.net/carter485/2v8gamLq/4/

## Information about environment

Chrome 102

Macbook m1 pro

## Steps To Reproduce

1. Ensure there is whitespace next to the canvas so that it has room to grow wider
2. Zoom in while the canvas grows to fill the width available (with your cursor on the right side of the canvas for most obvious results)
4. Pay attention to the crosshair that's following the cursor as you zoom in and out
5. The crosshair lags behind while scrolling on newer versions of fabric
6. The crosshair does NOT lag behind the cursor on fabric 2.2.4.

More details:

I am trying to upgrade a project from an old version of fabric to a newer version. I was originally trying to upgrade to 4.6.0, but then found this issue. I saw that a notable fix in fabric 5 was "performance fix after canvas resize". I thought that this might fix the issue, but unfortunately the issue is still present. 

An very interesting hacky almost fix is to uncomment lines 177, 178, and 179. That will fix the behavior in jsfiddle. What makes this very interesting is that this "fix" only works when the dev-tools are open. If the dev-tools are closed, it will not prevent the crosshair from lagging behind. I think you'd need to copy the code into an html file and open it up in order to test w/o the dev-tools open.

I have also tried updating the position of the crosshair lines rather than redrawing them. I still see them lag behind the cursor the same way.

## Expected Behavior

Crosshair tracks cursor while zooming in and out

## Actual Behavior

Crosshair lags behind cursor while zooming in and out

**Comment by ShaMan123** [comment]
I don't understand what version of react you are using but there were a few bugs that surfaced relating react@18 I think that caused strange stuff

**Comment by carterw485** [comment]
My project is on React 16.8.22. The js-fiddles may be react 18, but the issue only exists in newer versions of fabric and does not exist in fabric 2.2.6. I'll try to create a fiddle without react and post it here later.

**Comment by carterw485** [comment]
Here are 2 more fiddles, no longer using React. Behavior is consistent with or without using React

- Fabric 5.2.1 (Buggy) - https://jsfiddle.net/carter485/Lodj7w4v/11/
- Fabric 2.2.4 (Not buggy) -  https://jsfiddle.net/carter485/bqo0uzcs/1/

**Comment by ShaMan123** [comment]
I don't understand what you mean.
Add a video

**Comment by carterw485** [comment]
Password: fabric

https://vimeo.com/722096612

**Comment by ShaMan123** [comment]
Excellent. I now see.
I heard of a regression caused by caching + viewportTransform. But it's a rumor.
This might be related

**Comment by ShaMan123** [comment]
I think it's not performance at all.
It's the calculations.
If I zoom a lot the cross hair loses position. Even if a move the cursor.

**Comment by ShaMan123** [comment]
feel free to repoen

**Comment by carterw485** [comment]
Removing the roundingOperation didn't seem to fix the issue for me. Here's a video demonstrating that the behavior remains the same and that the crosshair does not stick to the cursor.

Password: fabric
https://vimeo.com/722323188


Something that might help get to the bottom of the difference is that `canvas.getPointer(e);` returns a different result between the two fabric versions. I have tested sending the exact same mouse:wheel event using cypress.js. The crosshair ends up in a different position after sending the same cypress mouse:wheel event between the 2 fabric versions.


If using `canvas.getTopContext()` is the proposed best solution, could you please fork the fiddle and create an example using `canvas.getTopContext()` to render the crosshair and have it follow the cursor?

Thank you for your help!

**Comment by carterw485** [comment]
I suspect that when the canvas is being resized while zooming, `canvas.getPointer(e)` is returning the value of where the pointer used to be, prior to the canvas resize occurring. In older versions of fabric, it seems that `canvas.getPointer(e)` returns the location of the pointer following the canvas resize, reflecting the true location of the pointer.

**Comment by ShaMan123** [comment]
Good point.
Does this https://jsfiddle.net/xcetrpuk/ behave as you expect?
Changed `roundingOperation`, `canvas#setDimensions`.
Of course setting canvas dimensions so frequently is bad practice IMO. Why don't you set it from the start to a big canvas a draw only on part of it?

**Comment by ShaMan123** [comment]
> canvas.getTopContext()

This might not be available on v5.2.1 yet so use `canvas.contextTop`

I see 2 ways to do it:
1. [Listen to canvas mouse move](https://jsfiddle.net/xcetrpuk/1/)
2. subclass base brush

**Comment by carterw485** [comment]
> Of course setting canvas dimensions so frequently is bad practice IMO. Why don't you set it from the start to a big canvas and draw only on part of it? I would do that.

I need to be able to display the entire image on page load. Some images are larger than the available window space, so they need to be shrunk until both their height and width fit within the available space. In most cases, this is going to leave unused whitespace around the canvas on one dimension.

By scrolling to zoom in, I can get a closer look at the image, as well as utilize the whitespace that is currently unused.


__________

> [Listen to canvas mouse move](https://jsfiddle.net/xcetrpuk/1/)

The crosshair is also listening to 'mouse:move'. The 'mouse:move' event does not fire while scrolling. Only the 'mouse:wheel' event (at least that is how the events behave on my machine). Both the 'mouse:move' and 'mouse:wheel' events trigger a call to CrosshairTool.handleCrosshair

![image](https://user-images.githubusercontent.com/12389084/174716575-f75d9bbf-3abf-4d4b-95b8-807dcc743bfc.png)


__________

Here is a video of me demonstrating the desired behavior from v. 2.2.4, then opening up the 2 fiddles you sent and comparing.

The crosshair still lags behind in the fiddles that you sent

Password: fabric

https://vimeo.com/722421143

**Comment by carterw485** [comment]
I did not mean to mark it completed. Please

**Comment by carterw485** [comment]
I did notice that the 'mouse:wheel' event in newer versions of fabric had an 'absolutePointer' value, while 2.2.4 did not have that attribute.

Is it possible that whatever is setting the absolute pointer is setting it prior to the canvas resize occurring?

![image](https://user-images.githubusercontent.com/12389084/174717233-99e9f9b3-943b-4813-b363-f057403439c6.png)

**Comment by ShaMan123** [comment]
> Is it possible that whatever is setting the absolute pointer is setting it prior to the canvas resize occurring?

Try this
https://jsfiddle.net/ho71p64g/

**Comment by carterw485** [comment]
Thanks! I was able to go through the diff and found that I was able to resolve the issue just by adding `canvas._absolutePointer = null;` to line 62 right above the call to `canvas.getPointer(e);`. I did not need to use the `topContext`, remove the `roundingOperation`, change the callback in `onEventStop`, or switch to `canvas.setDimensions(...)` (though I think I'll probably do that in my project anyway.).

I appreciate you taking the time to help find a workaround for the issue.

https://jsfiddle.net/carter485/mc652kpd/5/

I think that there may be something wrong with the way that fabric is setting _absolutePointer while the canvas is being resized. I think that _absolutePointer might be getting defined before the `vptCoords` have been updated.

**Comment by ShaMan123** [comment]
> I think that there may be something wrong with the way that fabric is setting _absolutePointer while the canvas is being resized. I think that _absolutePointer might be getting defined before the vptCoords have been updated.

The actual bug

**Comment by ShaMan123** [comment]
@asturur this is a subtle bug related to event caching.

**Comment by ShaMan123** [comment]
I think I have found the bug and I want to test the fix.

Could you try this out and report back?
https://jsfiddle.net/9sgb7Lp6/
