### ISSUE TITLE
Issue when trying to use Eraser

### ISSUE THREAD

**Issue by fr0mpy** [fabricjs/fabric.js#8012]
Hi all,

I've created a custom fabric build which includes the Eraser functionality. I've replaced the initial fabric.js & fabric.min.js files in node modules with the custom files, however as I'm also using typescript, when trying to use the EraserBrush constructor, I'm getting a TS error back saying "Uncaught TypeError: fabric__WEBPACK_IMPORTED_MODULE_2__.fabric.EraserBrush is not a constructor".

I've also tried using new (fabric as any).EraserBrush(canvas) and still receive the error, so I'm unsure whether it's a TS issue or to do with how I've set up the custom build. 

Any help would be hugely appreciated. Thanks.

**Comment by ShaMan123** [comment]
It's not typescript.
You did something wrong.
It's not able to find it because it's not there.
Of course you must use it with `new`.

**Comment by ShaMan123** [comment]
If you only need the eraser then run the following
```bash
cd node_modules/fabric && node build.js modules=ALL exclude=accessors,gestures requirejs minifier=uglifyjs
```

**Comment by ShaMan123** [comment]
The eraser has moved https://github.com/ShaMan123/erase2d
