### ISSUE TITLE
ci() test(): Disable resizing tests under firefox

### ISSUE THREAD

**Issue by asturur** [fabricjs/fabric.js#8014]
Those tests often crash firefox in the ci environment.
We can try to detect the browser in the test suite and disable those few tests for firefox.
Seems easier to understand why they crash.

**Comment by ShaMan123** [comment]
What is the reason? Too much memory used?

**Comment by asturur** [comment]
I m not sure.
Probably they are incredibly slow because we don't have a GPU in the CI.

I made this commit here in the build tool PR
https://github.com/fabricjs/fabric.js/pull/8013/files#diff-f847874e9287ff09a9cec2356ee85e647b14f1a24c1828bc11e9b1a992a98f91R14

and i m trying to disable 4 tests

**Comment by ShaMan123** [comment]
What if we make the timeout longer?
