### ISSUE TITLE
SVG coordinates are off after importing SVG and exporting to JSON...

### ISSUE THREAD

**Issue by tiptronic** [fabricjs/fabric.js#8026]
## Version
5.2.1

If I import a simple SVG and look at the values exported from the canvas, the values are off and (at least for me) unpredictable..

```svg
<svg xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink" width="200" height="100" viewBox="0 0 100 50">
    <rect id="background" x="0" y="0" width="100" height="50" fill="green" />
    <text x="8" y="11">My Title</text>
    <text text-anchor="end" x="90" y="40" font-size="20">Hello</text>
</svg>
```

using this snippet:

```javascript
fabric.loadSVGFromString(dialAction.svg, function(objects, options) {
    for(var i = 0;i < objects.length;i++) {
        canvas.add(objects[i]);
    }
  ....canvas.renderAll();
});
```

and export to JSON (without any modification):
(here I used:   `this.includeDefaultValues = false;`)

The coordinates are off (and also don't keep there original values):

```json
{
    "version": "5.2.1",
    "objects": [
        {
            "type": "rect",
            "version": "5.2.1",
            "left": -1,
            "top": -1,
            "width": 100,
            "height": 50,
            "fill": "green",
            "scaleX": 2,
            "scaleY": 2
        },
        {
            "type": "text",
            "version": "5.2.1",
            "left": 15,
            "top": 3,
            "width": 36,
            "height": 11,
            "fill": "#ffffff",
            "scaleX": 2,
            "scaleY": 2,
            "fontFamily": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
            "fontWeight": "bold",
            "fontSize": 10,
            "text": "My Title",
            "styles": {}
        },
        {
            "type": "text",
            "version": "5.2.1",
            "left": 127,
            "top": 44,
            "width": 26,
            "height": 23,
            "fill": "#ffffff",
            "scaleX": 2,
            "scaleY": 2,
            "fontFamily": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
            "fontWeight": "bold",
            "fontSize": 20,
            "text": "Hello",
            "styles": {}
        }
    ]
}
```

when setting the coordinates to top/left:

```javascript
   fabric.Object.prototype.originX = true;
   fabric.Object.prototype.originY = true;
```

 I still get:

```json

{
    "version": "5.2.1",
    "objects": [
        {
            "type": "rect",
            "version": "5.2.1",
            "left": 201,
            "top": 101,
            "width": 100,
            "height": 50,
            "fill": "green",
            "scaleX": 2,
            "scaleY": 2
        },
        {
            "type": "text",
            "version": "5.2.1",
            "left": 88,
            "top": 28,
            "width": 36,
            "height": 11,
            "fill": "#ffffff",
            "scaleX": 2,
            "scaleY": 2,
            "fontFamily": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
            "fontWeight": "bold",
            "fontSize": 10,
            "text": "My Title",
            "styles": {}
        },
        {
            "type": "text",
            "version": "5.2.1",
            "left": 181,
            "top": 91,
            "width": 26,
            "height": 23,
            "fill": "#ffffff",
            "scaleX": 2,
            "scaleY": 2,
            "fontFamily": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
            "fontWeight": "bold",
            "fontSize": 20,
            "text": "83",
            "styles": {}
        }
    ]
}
```

I tried playing with settings, e.g.:

```javascript
fabric.Object.NUM_FRACTION_DIGITS = 0; // used for the snippet above

fabric.Object.NUM_FRACTION_DIGITS = 2; // etc... but things got worse the higher the number was
```

All rendered to an external 5K retina display (devicePixelRatio = 2) using a Macbook Pro (INTEL) 2020

(Please note, I have to use older SVG `<text>`elements  (so no `<tspan>`) elements possible)

Any ideas how I can keep the coordinates intact (or what I'm doing wrong here)?

**Comment by ShaMan123** [comment]
First of all this is wrong:
```js
fabric.Object.prototype.originX = true;
fabric.Object.prototype.originY = true;
```

Second create a repro if you want us to test it. It's on you to make it easy for us to help/triage

**Comment by ShaMan123** [comment]
> The coordinates are off

What does this mean?
fabric is not svg complaint. It parses it and handles logic in a different manner

**Comment by tiptronic** [comment]
@ShaMan123 First of all thanks for your reply.

`coordinates are off` means:

when I import: 

```svg
 <text x="8" y="11">My Title</text>
```

and and export the canvas with toJSON()
It ends in:

```json
{
      "type": "text",
       "left": 15,
        "top": 3,
       "text": "My Title",
}
```
So there's exactly 1 simple question:

What does it need to keep "x" and "x" coordinates intact in the JSON output?

As far as `fabric.Object.prototype.originX` is concerned:
It doesn't change anything, if I use:

```javascript
    fabric.Object.prototype.originX = 'left';
    fabric.Object.prototype.originY = 'top';
```

Btw: I don't want you to test anything - I am just looking for an answer to the question what it needs to keep x and y coordinates intact. That's easier than any repo or anything... (no need to be SVG compliant)

**Comment by ShaMan123** [comment]
Are you seeing a visual difference?

**Comment by tiptronic** [comment]
Hm - I didn't look closely to the visual state, but I can't re-create the svg from a canvas, because the original coordinates are gone. The only way I found is to save the deltas (after editing/nudging objects) and re-apply those deltas to the original svg, which is somewhat cumbersome...

**Comment by ShaMan123** [comment]
![image](https://user-images.githubusercontent.com/34343793/176105841-5e630e1a-974d-4a5c-9682-5cf6758f8898.png)


I don't see any problem

```html

<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="800" height="600" viewBox="0 0 800 600" xml:space="preserve">
<desc>Created with Fabric.js 5.2.1</desc>
<defs>
</defs>
<g transform="matrix(2 0 0 2 100 50)">
<rect style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(0,128,0); fill-rule: nonzero; opacity: 1;" x="-50" y="-25" rx="0" ry="0" width="100" height="50"></rect>
</g>
<g transform="matrix(2 0 0 2 71.88 11.98)" style="">
		<text xml:space="preserve" font-family="Times New Roman" font-size="16" font-style="normal" font-weight="normal" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1; white-space: pre;"><tspan x="-27.94" y="5.03">My Title</tspan></text>
</g>
<g transform="matrix(2 0 0 2 135.56 67.47)" style="">
		<text xml:space="preserve" font-family="Times New Roman" font-size="20" font-style="normal" font-weight="normal" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1; white-space: pre;"><tspan x="-22.22" y="6.28">Hello</tspan></text>
</g>
</svg>

```

**Comment by tiptronic** [comment]
Ok - thanks for closing... I was talking about exporting JSON and then getting back the original coordinates, e.g. the 'x' and 'y' values.

If you don't see any problem, that's okay for you, but I can't unfortunately re-create the original values from the export (except for `<rect>`. So it seems it's just the wrong tool for the job...

**Comment by ShaMan123** [comment]
Perhaps you didn't define your need appropriately.
It is possible to get coords, position, whatever in relation to any plane.

> I was talking about exporting JSON and then getting back the original coordinates, e.g. the 'x' and 'y' values

I understand. My response shows a canvas that was loaded from json and exported to svg.
That's the reason I closed this issue.



> ![image](https://user-images.githubusercontent.com/34343793/176105841-5e630e1a-974d-4a5c-9682-5cf6758f8898.png)
>

**Comment by ShaMan123** [comment]
use discussion to ask how tos

**Comment by tiptronic** [comment]
> Perhaps you didn't define your needs appropriately.

What is unclear in the question: `What does it need to keep "x" and "y" coordinates intact in the JSON output?`?

> I understand. My response shows a canvas that was loaded from json and exported to svg.

Jep - exactly the opposite from what I was asking  ;) 

I'll try again in discussions

**Comment by ShaMan123** [comment]
Writing **SVG coordinates are off after importing SVG and exporting to JSON** means to me:

OHH NO there's a bug in object positioning after import/export

So consider the title. It's as important as the body. Perhaps much more.
