### ISSUE TITLE
Scaling up very small image behaves differently in browser vs Node

### ISSUE THREAD

**Issue by savy** [fabricjs/fabric.js#8030]
## Version
Fabric 5.0.0
Node 18.3.0
Chrome Version 103.0.5060.53 (Official Build) (x86_64)
Macbook Pro, Big Sur, Retina Display

## Test Case
- [X] [Browser Issue Template](https://jsfiddle.net/5qc6dvgx/)
- [X] [Node Issue Template](https://codesandbox.io/s/winter-currying-0nrsl4)

## Information about environment
Nodejs or browser? Issue is in Node
Which browsers? Chrome Version 103.0.5060.53 (Official Build) (x86_64)

## Steps To Reproduce

1. Create 1x1 solid color png
2. Use Image.fromURL() to load image onto canvas. In the test code, I converted the png to base64 format to isolate the example, however the issue occurs if you retrieve the image file via http as well.
3. Generate png of the canvas using toDataURL() on Node

## Expected Behavior
I expect both the browser and Node to generate the same solid image like below:
![download (15)](https://user-images.githubusercontent.com/749574/176298794-4f3207a4-185e-4abb-9071-aa81849c8a89.png)

## Actual Behavior
Chrome generates the expected solid image, but Node generates the following image:
![download (14)](https://user-images.githubusercontent.com/749574/176299294-e7ac1573-f07b-42f1-b852-102bdc2c5782.png)

I tried various combinations of enabling/disabling imageSmoothing, objectCaching, and enableRetinaScaling, since I know some defaults are different on Node, but I wasn't successful at getting Node to output the same image as the browser.

I also investigated to see if this was due to Fabric using node-canvas on Node, however if I make a similar example directly via node-canvas, the output is a solid color as expected [node-canvas example](https://codesandbox.io/s/exciting-shirley-eilvn8?file=/src/index.js)

**Comment by ShaMan123** [comment]
[node-canvas example](https://codesandbox.io/s/awesome-perlman-lyf2cb?file=/package.json) - fixed deps.

Excellent issue!

**Comment by ShaMan123** [comment]
![image](https://user-images.githubusercontent.com/34343793/176311763-a407da15-f85c-4afa-9486-1dce4205f1a0.png)

I have managed to reproduce on node-canvas with the following 
https://codesandbox.io/s/gifted-perlman-jw6o4h

**Comment by ShaMan123** [comment]
It is a strange bug 
Try 
```diff
-  ctx.drawImage(image, 0, 0, 1, 1);
+ ctx.drawImage(image, 0, 0, 1, 1.00000000001);
```

It solved it on my end. Have no idea why... Only guesses

**Comment by savy** [comment]
Wow @ShaMan123, that was fast - thank you for looking at it! 

Your example with `1.00000000001` seems to resolve the issue with node-canvas. I'm not sure why either.

Do you think there's a way to work around this in Fabric?

**Comment by ShaMan123** [comment]
> that was fast - thank you for looking at it!

Seeing such a detailed issue, time and effort spent trying to solve and triage it means to me a respect to maintainers' time and effort. So it drives me to respond. This is how a community I want to take part in behaves.

After looking more into I do think it's `imageSmoothing` after all and to be more precise `patternQuality` setting logic of node-canvas.

https://github.com/Automattic/node-canvas/blob/0bccc05b384cc1f3e969cd9ed7859a95376ec88c/src/CanvasRenderingContext2d.cc#L1343 or https://github.com/Automattic/node-canvas/blob/0bccc05b384cc1f3e969cd9ed7859a95376ec88c/src/CanvasRenderingContext2d.cc#L1392

I think we can fix it on our side by setting
`ctx.patternQuality = 'best'`
e.g.
```js
canvas.on('before:render', ({ ctx }) => {
  ctx.patternQuality = 'best';
})
```

It is also fixed by setting `image.imageSmoothing = false`

https://codesandbox.io/s/nice-lamport-m4cyjd?file=/src/index.js

Could you file an issue on node-canvas referencing this? 


@asturur ?

**Comment by savy** [comment]
@ShaMan123 Sure, I can open an issue on node-canvas. But first, I have a question with your node-canvas example. Thanks to Fabric, I never had to use node-canvas or HTML5 canvas directly.

Is it appropriate to scale the context like this in your example when we just want to scale the loaded image?
```js
ctx.scale(100, 100);
ctx.drawImage(image, 0, 0, 1, 1);
```

Instead of doing this (which works as expected)
```js
ctx.drawImage(image, 0, 0, 100, 100);
```

I do think there is a bug as you identified. I just want to make sure the example I give uses node-canvas correctly so that it's clear to them.

**Comment by ShaMan123** [comment]
Both are fine and produce the same outcome if I am not mistaken

**Comment by savy** [comment]
I opened an issue in node-canvas. I made a slight tweak to your example to hopefully make the code I copy+pasted into the Github issue easier to follow.
