### ISSUE TITLE
Drawing blurs when zooming

### ISSUE THREAD

**Issue by Mamorial** [fabricjs/fabric.js#8035]
## Version
5.2.1

## Test Case
- [ ] [Browser Issue Template](https://jsfiddle.net/Lcp2h3nv/)
- [ ] [Node Issue Template](https://codesandbox.io/s/exciting-browser-ytb701)

## Information about environment
Nodejs or browser?
Which browsers?

## Steps To Reproduce

1. 当图形的高度比较小时，选中图形调整宽高，边界会有模糊效果

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```
</p></details>

## Actual Behavior
实际效果如图：https://zjzj-oss.zhijiasoft.com/test/1.png

**Comment by ShaMan123** [comment]
`objectCaching`
