### ISSUE TITLE
Stroke for Path gets cut off

### ISSUE THREAD

**Issue by thipham196** [fabricjs/fabric.js#8036]
## Version
5.2.1

## Test Case
https://codepen.io/uea30475/pen/ExExOEO

## Information about environment
Chrome Version 103.0.5060.66 (Official Build) (64-bit)

## Steps To Reproduce

create path
add stroke information and large strokeWidth (i.e. 100)
stroke is cut off.

## Actual Behavior
stroke gets cut off
stroke shows unexpected artifacts and borders

![image](https://user-images.githubusercontent.com/108052664/176409818-6a025da8-35c3-49e0-8a89-1be8821bc7a4.png)

**Comment by ShaMan123** [comment]
duplicate #8025

**Comment by ShaMan123** [comment]
`strokeLineJoin` isn't taken into account
