### ISSUE TITLE
Triangle or Polygon cut off issue. exactBoundingBox can not work correctly

### ISSUE THREAD

**Issue by senschen** [fabricjs/fabric.js#8038]
last issue was closed https://github.com/fabricjs/fabric.js/issues/8022
I tried more, but issue not be resolve by use Poly : 

![image](https://user-images.githubusercontent.com/8544826/176432396-d19f0b1c-6ed4-4742-95d1-7beabac55033.png)

## Version
5.2.1

**Comment by ShaMan123** [comment]
`exactBoundingBox=true`

**Comment by senschen** [comment]
> `exactBoundingBox=true`

sorry, picture is wrong in question content.
in fact, I used true:
https://codepen.io/senschen/pen/abYzZQP

**Comment by ShaMan123** [comment]
`strokeMiterLimit: Infinity`
