### ISSUE TITLE
uneven line thickness when zooming

### ISSUE THREAD

**Issue by LemonYaoCW** [fabricjs/fabric.js#8043]
I had a problem with the grid showing uneven line thickness when zooming. This problem also exists in the official example, how can I fix this problem?
[http://fabricjs.com/fabric-intro-part-5](url)
When the normal
![QQ截图20220701163114](https://user-images.githubusercontent.com/86453463/176857258-aea44ace-fe82-4a4b-9397-a03ec2ec2253.png)
Abnormal display when zooming
![QQ截图20220701163138](https://user-images.githubusercontent.com/86453463/176857363-0699c2f6-1a00-49ab-826b-bd94d466cc66.png)
![QQ截图20220701163150](https://user-images.githubusercontent.com/86453463/176857382-829d9f29-25ee-40a6-9034-76a2a1ef0994.png)

**Comment by ShaMan123** [comment]
Change the backgroundImage's pattern to something better or handle it with a resize filter
