### ISSUE TITLE
Canvas "backgroundColor" and "overlayColor" don't support gradient color with "percentage"

### ISSUE THREAD

**Issue by Fennec-hub** [fabricjs/fabric.js#8045]
Gradient with `gradientUnits` set to `percentage` don't work as expected with `canvas.backgroundColor` and `canvas.overlayColor`. 

## Version
5.0.0

## Test Case
Live example: [jsfiddle](https://jsfiddle.net/j1ht3ou5/)
Code example:
````javascript
canvas.backgroundColor = new fabric.Gradient({
  type: "linear",
  gradientUnits: "percentage",
  coords: { x1: 0, y1: 0, x2: 1, y2: 0 },
  colorStops: [
    { offset: 0, color: "rgba(0,0,0,1)" },
    { offset: 1, color: "rgba(255,255,255,1)" },
  ],
});
````

## Information about environment
Tested with Chrome and Firefox on Linux Ubuntu.

## Steps To Reproduce
1. Set `gradientUnits` to `percentage`
2. Use it with `canvas.backgroundColor`

## Expected Behavior
`1` should be converted to `100%` or the canvas full width/height, the same behavior with `fabric.Object`s.

## Actual Behavior
`coords` values are not converted to percentage but translated to pixels, the value of `1` is translated to `1px`.

**Comment by ShaMan123** [comment]
As a workaround use `backgroundImage` as set it a rect with the gradient
We are thinking of dropping `backgroundImage` `backgroundColor` etc. in future releases

**Comment by ShaMan123** [comment]
PRs are welcome

**Comment by Fennec-hub** [comment]
First of all, thanks a lot for creating and maintaining such a great library :pray:

I looked into  [_renderBackgroundOrOverlay](https://github.com/fabricjs/fabric.js/blob/12e048103737b603aeb22c3d83a25c7f83c19c29/src/static_canvas.class.js#L819), not sure if it's the right approach, but I made this changes.

``` javascript
  ....
  // Check "gradientUnits" and get the canvas size
  const scale = fill.gradientUnits && fill.gradientUnits === "percentage" 
       	? [this.getWidth(), this.getHeight()] 
        : [1, 1];
  // Apply the scale to the transform matrix
  ctx.transform(1 * scale[0], 0, 0, 1 * scale[1], fill.offsetX || 0, fill.offsetY || 0);
  ....

  // Complete code: https://jsfiddle.net/zbweyaLd/
````

And it seems to work as expected with both linearGradient [jsfiddle](https://jsfiddle.net/zbweyaLd/), and radialGradient [jsfiddle](https://jsfiddle.net/06czt4j1/5/).

**Comment by ShaMan123** [comment]
Happy you found a solution. It's not bad at all.
Try using `gradientTransform` instead of applying a transform to `ctx`, I saw it in the source code. That can be the official fix

**Comment by Fennec-hub** [comment]
Glad to be of help.

Using `gradientTransform` seems straightforward but there is a catch, you need to either copy or cache/restore the `gradientTransform` array in order to not permanently alter its value for subsequent use with other objects.

````javascript
  ...
  // Check "gradientUnits" and apply matrix transform to `gradientTransform`
  let scale = [1, 1];
  let gradientTranform = fill.gradientTranform;
  if(fill.gradientUnits && fill.gradientUnits === "percentage") {
    scale = [this.getWidth(), this.getHeight()];
    // Copy the `gradientTranform` value or create a new one
    gradientTranform = gradientTranform ? [...gradientTranform] : [1, 0, 0, 1, fill.offsetX || 0, fill.offsetY || 0]
  }

  ctx.transform(1, 0, 0, 1, fill.offsetX || 0, fill.offsetY || 0);
  var m = gradientTranform || fill.patternTransform;
  m && ctx.transform(m[0] * scale[0], m[1], m[2], m[3] * scale[1], m[4] * scale[0], m[5] * scale[1]);
  ...

  // Complete code : https://jsfiddle.net/msecuqrv/
````

Linear gradient test : [jsfiddle](https://jsfiddle.net/msecuqrv/1/)
Radial gradient test : [jsfiddle](https://jsfiddle.net/msecuqrv/2/)

PS: Edited the first solution, applying the scale to `offsetX` and `offsetY` since they are also affected by `gradientUnits`.
