### ISSUE TITLE
Text underline/overline/linethrough affects rendering of empty newline when using charSpacing

### ISSUE THREAD

**Issue by FabianElsmer** [fabricjs/fabric.js#8050]
## Version
4.6.0

## Test Case

Can be reproduced in the FabricJS kitchensink demo: http://fabricjs.com/kitchensink

[Kitchensink _ Fabric.webm](https://user-images.githubusercontent.com/9722121/177567280-d3a94994-32e9-43d8-9c54-2abb7d28b6ce.webm)

## Information about environment
Environment: Browser Chrome

## Steps To Reproduce

1. Create a text element
2. Set the text of the text element and include some newlines without additional characters
3. Set both `charSpacing` to a value above 0 and enable `underline` / `overline` or `linethrough`

## Expected Behavior
Newline without characters should not draw any line styles

## Actual Behavior
Each newline leads to drawn lines with the width of `charSpacing`, placed to the left of the element.

![Screenshot from 2022-07-06 15-47-26](https://user-images.githubusercontent.com/9722121/177565408-1cc04948-9ccd-4570-a693-70b10fb56d1b.png)

**Comment by snowuly** [comment]
@FabianElsmer Hello~ I encounted the same problem, have you solved it?

**Comment by asturur** [comment]
just tested this on current master and does not seem to happen

**Comment by snowuly** [comment]
> just tested this on current master and does not seem to happen

The problem still happens on the version 5.3.0.

**Comment by asturur** [comment]
Not sure anyone will have time to fix 5.3.0, but if you find the root cause open a  PR on the branch 5.x to fix it

**Comment by asturur** [comment]
compare what changed in master to find a clue of differences, maybe is a small change

**Comment by snowuly** [comment]
> compare what changed in master to find a clue of differences, maybe is a small change

I found a solution (but not solve the root cause):
In text.class.js file:
![image](https://github.com/fabricjs/fabric.js/assets/5939337/72b139a8-c06d-4dd6-9a20-fa4e3ecd7050)

The solution is not applying text decoration to empty line.

I didn't find the root cause that why fabric.js render extra underlines outside the text box.

**Comment by asturur** [comment]
is probably what the fix in master looks like

**Comment by snowuly** [comment]
> is probably what the fix in master looks like

Thanks!
