### ISSUE TITLE
Handles for text object don't get zoomed

### ISSUE THREAD

**Issue by brianp70x** [fabricjs/fabric.js#8051]
when zooming a SVG from within the loadSVGFromString function, Text objects handles stay at original location.

[https://jsfiddle.net/brianp70/xybgpcz2/167/](url)
Just select any of the lower txt, notice the handles are above and to the left.

I'm new to JavaScript. Can I restructure the code to work properly? when zooming outside the loadSVGFromString,  zoom seems to work fine, but since the SVG has not yet loaded I have no values to calculate it from. thanks for the time and patience!

**Comment by ShaMan123** [comment]
Discussions are meant for these kinds of questions
https://jsfiddle.net/uv102sjy/

I suggest you work on v6 (master branch if you want to work with objects nested in groups)

**Comment by brianp70x** [comment]
thanks ill check out v6. i was not looking to group the svg i need to edit the text on the fly.

**Comment by ShaMan123** [comment]
This is why I pointer out v6

**Comment by brianp70x** [comment]
Looking at the v6-alpha file…
***@***.***

Shouldn’t version be 6.0.0a or something like that… this make it tough to know which version I have in use.

Thanks
bpp

**Comment by ShaMan123** [comment]
Well yes... you are right.
