### ISSUE TITLE
RGBA radial gradient looks completely different in different browsers

### ISSUE THREAD

**Issue by An-Eugene** [fabricjs/fabric.js#8052]
I tried to make glowing effect by using RGBA gradient, and it works fine for me until I checked result in Firefox. Seems like it is the only browser that have such problem.
## fabric.js version
5.2.1
## Sample
https://jsfiddle.net/76xvm5zo/8/
## Where it works fine
Google Chrome 102 (Windows 11)
Vivaldi 5.2 (Windows 11)
Opera 88 (Windows 10)
Safari latest (MacOS)
![Screenshot_3](https://user-images.githubusercontent.com/63323569/177733989-4919b414-ec39-47a7-9cf8-72860b1ec223.png)
## Where it works wrong
Mozilla Firefox 102 (Windows 11)
![Screenshot_4](https://user-images.githubusercontent.com/63323569/177734267-2fdc039c-9e6c-45d8-936f-ad3c206e4cfb.png)
## Steps to reproduse
Just make a new Gradient with RGBA colorStops with different alpha channel and place it on circle or rectangle. Gradient must be radial, linear gradient works just as expected.

**Comment by ShaMan123** [comment]
please create a repro without fabric that works on firefox.
If you can't it means it's not on our side and you should then file a bug report to them

**Comment by An-Eugene** [comment]
https://jsfiddle.net/y843pzwq/
Well, I used pure js and got the same problem. Seems like this is firefox-side bug
