### ISSUE TITLE
RTL text rendering issue when text wraps in new line

### ISSUE THREAD

**Issue by CookedApps** [fabricjs/fabric.js#8058]
Hey guys, 
We recently updated from fabric.js 4.6.0 to version 5.2.1 and noticed that `Textbox` RTL support is broken since version 5.0.0. 

You can see on the screenshots below that the text gets rendered right to the Textbox if it encounters a line break. 
Using `direction: "rtl"` and `textAlign: "right"` worked well in fabric 4.6.0 but know it leads to a rendering issue.

## Version
5.2.1 (since 5.0.0)

## Test Case
- [x] [Browser Issue - Fiddle demonstrating the bug](https://jsfiddle.net/nv4w2d8s/23/)

## Information about environment
Browser
Tested in Chrome and Firefox

## Steps To Reproduce

1. Create a Canvas
2. Create a fabric.Textbox with RTL text like Arabic or Hebrew
3. Set Textbox `direction: "rtl"` and `textAlign: "right"`
4. Add Textbox to Canvas

<details><summary>Error Message & Stack Trace</summary><p>

```txt
No error messages.
```
</p></details>

## Expected Behavior
Text should wrap normally and stay inside the Textbox:
<img title="a title" alt="RTL in 4.6.0" src="https://i.imgur.com/5zoRoXq.png">

## Actual Behavior
Text moves outside the Textbox as it wraps and is only partly rendered:
<img title="a title" alt="RTL in 5.2.1" src="https://i.imgur.com/SHTR2O2.png">

**Comment by ShaMan123** [comment]
This is known. There are PRs waiting to be merged that fix this.
v6-alpha has these included

**Comment by ShaMan123** [comment]
https://jsfiddle.net/hxuym725/

**Comment by raphilevine** [comment]
We have found as well that RTL support does not work well after version 4.6.  
Is there any updates for this?
