### ISSUE TITLE
can't save pdf

### ISSUE THREAD

**Issue by hudeaki** [fabricjs/fabric.js#8074]
## Version
5.0.0

## Test Case
- [ ] [Browser Issue Template](https://jsfiddle.net/Lcp2h3nv/)
- [ ] [Node Issue Template](https://codesandbox.io/s/exciting-browser-ytb701)

## Information about environment
Nodejs or browser?
Which browsers?

## Steps To Reproduce

1. 

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```
</p></details>

## Actual Behavior

I use code 

	
	var inst = this;

	var canvas = inst.fabricObjects[inst.active_canvas]

// Real Url
fabric.util.loadImage('https://d1hdtc0tbqeghx.cloudfront.net/sites/536207e0e52e306190000002/theme/images/sd-laravel-icon.png', function(img) {
    if(img == null) {
        alert("Error!");
    }else {
        var image = new fabric.Image(img);
        canvas.add(image).setActiveObject(image);
        canvas.renderAll();
    }
}, { crossOrigin: 'anonymous' });

can't save

**Comment by ShaMan123** [comment]
write a proper issue 
it's Q&A should it belongs to discussions
v5 is promises and not callbacks.
