### ISSUE TITLE
File cannot be downloaded via yarn and npm

### ISSUE THREAD

**Issue by jee-zh** [fabricjs/fabric.js#8075]
<img width="557" alt="20220722162103" src="https://user-images.githubusercontent.com/29367368/180397276-0118f5a4-b122-42e7-a37c-8e584a30ad53.png">

## Version
5.2.1

When I use yarn to install, it stays on canvas and waits for a long time without response, what should i do please?

**Comment by jee-zh** [comment]
<img width="187" alt="1" src="https://user-images.githubusercontent.com/29367368/180398193-d85518b3-5635-4184-a6f7-0f4bbe5632b8.png">
Stopped here for a long time

**Comment by ShaMan123** [comment]
it's trying to download node-canvas
if you use fabric only for the web you don't need it at all
if you do need it look at node-canvas installation guide
