### ISSUE TITLE
Dynamic patterns createPattern bug

### ISSUE THREAD

**Issue by duonanjian** [fabricjs/fabric.js#8082]
when I use Dynamic patterns, once i delete the image src, then will appear this bug 

Uncaught TypeError: Failed to execute 'createPattern' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLCanvasElement or HTMLImageElement or HTMLVideoElement or ImageBitmap or OffscreenCanvas or SVGImageElement or VideoFrame)'.

**Comment by ShaMan123** [comment]
provide a repro

**Comment by ShaMan123** [comment]
and fill out a proper bug report
