### ISSUE TITLE
ReferenceError: updateCanvasContext is not defined

### ISSUE THREAD

**Issue by enjoyWeb** [fabricjs/fabric.js#8086]
react 16.8.6
`import React, {useEffect, useRef} from 'react'
import {fabric} from 'fabric'

const FabricJSCanvas = () => {
  const canvasEl = useRef(null)
  useEffect(() => {
    const options = { ... };
    const canvas = new fabric.Canvas(canvasEl.current, options);
    // make the fabric.Canvas instance available to your app
    updateCanvasContext(canvas);
    return () => {
      updateCanvasContext(null);
      canvas.dispose()
    }
  }, []);
  
  return (<canvas width="300" height="300" ref={canvasEl}/>)
});
export default FabricJSCanvas;`

**Comment by ShaMan123** [comment]
updateCanvasContext is undefined.
That's just a how to
define the function
