### ISSUE TITLE
Video not fix inside fabric.image object

### ISSUE THREAD

**Issue by HunzlaSheikh** [fabricjs/fabric.js#8088]
I am adding video in canvas using fabricjs 521 version. But facing issue that video is not fit inside fabric.image object. Its working fine with older version (1.6.0-rc.1). 
Following is the code to add video using fabricjs

`var video1El = document.getElementById('videoid');
var video1 = new fabric.Image(video1El, {
        left: 425,
        top: 0,
        angle: 0,
        originX: 'center',
        originY: 'top',
        objectCaching: false,
        width: canvas.width,
        height: canvas.height,
        lockMovementX: true,
        lockMovementY: true,
        selectable: false,
        crossOrigin: 'anonymous'
    });
    canvas.add(video1);`

Result I am getting (with 521 version and low resolution)
![image](https://user-images.githubusercontent.com/61582976/181239996-57be613f-5abb-49ed-988c-9c9503169eb0.png)

Result (with 1.6.0-rc.1 version and low resolution) - Expecting this result with 521 version
![image](https://user-images.githubusercontent.com/61582976/181238732-89c4d30b-7458-4631-979d-2ae58cf24831.png)

Result I am getting (with 521 version and high resolution)
![image](https://user-images.githubusercontent.com/61582976/181240263-1f6ed2d8-3d94-45b8-9ab3-d836bf0ac81c.png)

Result (with 1.6.0-rc.1 version and high resolution) - Expecting this result with 521 version
![image](https://user-images.githubusercontent.com/61582976/181240674-b353f8a2-6b3a-4ac9-8e29-76fa7229d601.png)

With low resolution, whole video is showing but its not fit in fabric image object. And with high resolution, it showing specific part of the video and not fit whole video inside fabric image object.

**Comment by ShaMan123** [comment]
Please create a reproduction

**Comment by xorb** [comment]
I think you are not updating properly your video element width/height after metadata loaded.
https://github.com/layerhub-io/react-editor

**Comment by chloe-bm** [comment]
Make sure you are updating your fabric video element dimensions after video metadata has loaded.
https://github.com/layerhub-io/react-editor
