### ISSUE TITLE
image use video tag rotate 3 degrees to 5 degrees, and the sawtooth is particularly obvious

### ISSUE THREAD

**Issue by lyz1005** [fabricjs/fabric.js#8089]
image set element a video tag，default anlge is 0，display normal. rotate 3 degress or 5 degress, jagged edges appear on the image

This demo has the same problem  http://fabricjs.com/video-element

**Comment by lyz1005** [comment]
sawtooth ：
![image](https://user-images.githubusercontent.com/16696143/181464706-9c8938a7-dd6f-4ae3-a977-4a30985825f5.png)
normal：
![image](https://user-images.githubusercontent.com/16696143/181464959-ef72e8e5-739d-4bde-9c68-3d7f0c8a76b1.png)

**Comment by ShaMan123** [comment]
I don't see it in the demo
create a repro

**Comment by melchiar** [comment]
@lyz1005 What type of device are you using?

**Comment by lyz1005** [comment]
> @lyz1005您使用的是什么类型的设备？

I use fabric in Vue project and Chrome browser

**Comment by lyz1005** [comment]
> 我在演示中没有看到它 创建一个复制品



> I don't see it in the demo create a repro
http://fabricjs.com/video-element This is the demo of playing video on fabric. There are jagged on this demo, which can be seen from the screenshot
![image](https://user-images.githubusercontent.com/16696143/182350469-2063dd62-e6e5-45ef-8b00-6f1a4ab5bea6.png)

**Comment by lyz1005** [comment]
Now there are jagged edges and border lines. I set imagesmoothing to have no effect of removing jagged edges

![image](https://user-images.githubusercontent.com/16696143/182351361-6fdf2c47-dfb9-47da-85a1-709b832216d4.png)
