### ISSUE TITLE
Inconsistent object layering

### ISSUE THREAD

**Issue by bodydisplaynone** [fabricjs/fabric.js#8091]
Hi,

not sure if this was mentioned before but I'm having trouble with the layering of objects. Thing is, it kinda works with the default behaviour, but it does not when examined closely. When clicking the objects they seem to be grouped for some reason even if they are not. The same goes when clicking the canvas, the order gets mixed up. You can see an example here:
https://sharing.clickup.com/clip/p/t4623004/0c59b302-577e-4b3a-8fae-6578a5bf2a83/screen-recording-2022-07-28-10%3A24.webm

Whenever I click the red box, the black box is brought to the front too. Same with the blue box. If I click the blue box the black box also comes on top of the yellow box. This applies to every object, rectangles, polygons, images etc.

I tried to fix this myself with preservestacking and calling events when a selection is updating, bringing the active object to the front. However, this also produces some interesting results as it seems that clicking the canvas will not clear the active object and when clicking back to the pics the last clicked object remains active and I have to click around to make it work and engage the layering mechanism again. Example code and video:

`this.fabric = new fabric.Canvas(this.params.canvasId, {
      preserveObjectStacking: true,
    });`
`this.fabric.on("selection:updated", function (event) {
      this.bringToFront(this.getActiveObject());
    });`
https://sharing.clickup.com/clip/p/t4623004/7c15fc22-fe70-4aca-98f9-c62e143b66a0/screen-recording-2022-07-28-10%3A30.webm

Another thing I noticed and maybe this is related to why my workaround does not work is that the event is failing to trigger whenever clicking the first object after init or coming back from the canvas.
https://sharing.clickup.com/clip/p/t4623004/7bc85822-8cdd-4cf0-8eb2-4532fc6f467d/screen-recording-2022-07-28-10%3A38.webm

I tried different events for the above but nothing seems to work, I also tried to getObjects and then call the event:selected on each object but getObjects returns an empty array.

Any idea what I'm doing wrong? The first example seems like a bug though (default order issues).

**Comment by bodydisplaynone** [comment]
I think I just solved it for now.
https://sharing.clickup.com/clip/p/t4623004/2f1de8a1-bbbb-4967-9622-349b615c84c5/screen-recording-2022-07-28-11:41.webm

working code:
    //add two objects
    var circle = new fabric.Circle({
      radius: 20,
      fill: "green",
      left: 100,
      top: 100,
    });
    var circle2 = new fabric.Circle({
      radius: 20,
      fill: "red",
      left: 200,
      top: 200,
    });
    var objects = [];
    objects.push(circle, circle2);

    //push each object to canvas and also bind the event
    objects.forEach((element) => {
      this.fabric.add(element);
      element.on("selected", function () {
        canvas.setActiveObject(this);
        canvas.bringToFront(this);
      });
    });

**Comment by ShaMan123** [comment]
It seems you are working on v5 
V6 solved grouping and layering.
See the pinned issue #7670

**Comment by bodydisplaynone** [comment]
Cool, thanks for pointing it out! I'll keep using my fix until then.
