### ISSUE TITLE
"stateful:true" trigger drag action on "mouse:up"

### ISSUE THREAD

**Issue by Rqplo** [fabricjs/fabric.js#8109]
Hello guys,

I am currently experiencing a strange behavior when an object's clipPath property is set.

I actually need to know the original state of an object, for that, I pass the stateful property when initializing the canvas to true, and it works correctly, since it gives me the initial state. The problem is that at the same time, when I click on an object that has been clipped, when I release the click, a drag action is initiated, even if I haven't moved the object. For an object that is not clipped, it works perfectly, no drag action is initiated.

For now, I am comparing the original and current state for clipped objects, but I would like to know if this behavior is expected ?

## Version
5.2.1

## Test Case
- [&#10003; ] [Drag action fired with stateful:true on objects mouse:up](https://jsfiddle.net/freaksevening/Lpkbxfgv/)

## Information about environment
Every browsers

## Steps To Reproduce

1.  Just click both images without moving the mouse and take a look at the log

**Comment by ShaMan123** [comment]
Your repro isn't straight forward
However we plan to deprecate the stateful concept altogether #7920 
it does do something strange with nested objects because it was written with flat object in mind which is WRONG

**Comment by ShaMan123** [comment]
I suggest you impl something by yourself

**Comment by Rqplo** [comment]
> I suggest you impl something by yourself

Oh I see ! Thanks man 😄 , I'll try to implement my own solution then !
