### ISSUE TITLE
Can we click through a layer in fabric?

### ISSUE THREAD

**Issue by Rajdeepc** [fabricjs/fabric.js#8119]
I am currently having multiple assets on canvas like a background, a sticker and an artwork. Is there any way I can click through the artwork and select the background.
The issue is I need to adjust the artwork to click into the background.
I am using png as background, gif as stickers/artwork.

I am not sure this is an issue with fabric or not but some help or guidance on this issue is helpful.

Like this if you see I cannot click on 4K image whenever I click through the upper layer I can only select the upper layer.
Is there any way I can select the inner layers too.

<img width="376" alt="Screenshot 2022-08-04 at 6 59 01 PM" src="https://user-images.githubusercontent.com/8790510/182859034-2e2a5fed-57ab-46c9-87e6-c24ebcc49060.png">

**Comment by ShaMan123** [comment]
you really need to read docs or look at source code
and I would like you to start using [discussions](https://github.com/fabricjs/fabric.js/discussions) **instead of** opening issues which are for bug reporting

`evented` prop is the answer

**Comment by Rajdeepc** [comment]
preserveObjectStacking: true. worked for me. Thanks

**Comment by kalnode** [comment]
How does `preserveObjectStacking` solve this?

I thought your original question had to do with clicking-through _TRANSPARENT_ areas of an object?
