### ISSUE TITLE
我在使用多个fabricjs 实例的时候修改一些canvas出现问题

### ISSUE THREAD

**Issue by w934423231** [fabricjs/fabric.js#8124]
我的网站有 tabs 切换的功能，在每个tab 页里都有一个fabricjs 实例， 当我只有一个 fabricjs 实例的时候，修改canvas的属性是没有问题的，但是出现两个实例的时候，不渲染，我看过fabricjs的实例，他里边的参数是修改了的，也执行了renderAll

**Comment by w934423231** [comment]
![image](https://user-images.githubusercontent.com/38958128/182992654-61743eb7-e0fd-420d-85b6-d461c803404f.png)
![image](https://user-images.githubusercontent.com/38958128/182992716-9a7ed609-f70c-4aa0-a989-df7843aaa512.png)
![image](https://user-images.githubusercontent.com/38958128/182992784-d20380e0-a37b-4cee-8b7d-2171f7e6737b.png)

**Comment by ShaMan123** [comment]
We need an English description

**Comment by ShaMan123** [comment]
And you **MUST** follow the issue template.
Closing until you do
