### ISSUE TITLE
ActiveSelection remove object cause removed object change location?

### ISSUE THREAD

**Issue by Tennyleaz** [fabricjs/fabric.js#8140]
## Version
5.2.1

## Test Case
 [My js fiddle code](https://jsfiddle.net/oq09kt7y/20/)

## Information about environment
Browser, firefox and edge.

## Steps To Reproduce

1. Add an `selection:created` event handler.
2. In the handler, I try to remove an object from multi-selection on given condition.
```javascript
const activeSelection = canvas.getActiveObject();
const selecteds = activeSelection.getObjects();
for (let i=0; i<selecteds.length; i++) {    	
  if (/*some given condition*/) {
    activeSelection.remove(selecteds[i]);
  }
}
canvas.requestRenderAll();
```
3. The removed object suddenly change its location.

</p></details>

## Expected Behavior

I expect the removed object staying at the same position as before selection.

## Actual Behavior

1. Before select:
![Before](https://user-images.githubusercontent.com/7089271/183807087-0a07e3c3-3fe9-4391-8301-e5c44f411fe7.png)

2. After select:
![After](https://user-images.githubusercontent.com/7089271/183807157-53e43dd3-e706-4644-82bb-24bbf41c66e0.png)
We can see the blue rectangle went to top left position.

**Comment by ShaMan123** [comment]
fixed by #7670

**Comment by ShaMan123** [comment]
as a workaround
```js

fabric.util.sendObjectToPlane(object, activeSelection.calcTransformMatrix())
```

**Comment by ShaMan123** [comment]
https://jsfiddle.net/e7c1Ljbn/1/
`fabric.util.sendObjectToPlane` is v6 as well I see

**Comment by ShaMan123** [comment]
no it is not
the fiddle is on v4.5

**Comment by Tennyleaz** [comment]
Got it. Waiting for v6 release.
