### ISSUE TITLE
V4.6.0 The rendered image is too large, rendering is stuck

### ISSUE THREAD

**Issue by Charley-liu** [fabricjs/fabric.js#8142]
The rendered image is too large, with a size of 3M. When drawing graphics, it gets stuck abnormally, and the CPU reaches 80%. What is the solution?

**Comment by ShaMan123** [comment]
no repro
no context
**ISSUE TEMPLATE NOT FILLED**

**Comment by Charley-liu** [comment]
> no repro no context **ISSUE TEMPLATE NOT FILLED** 版本未更新
The version has been updated to the latest version 5.3.1, but after adding more than one text box, it will get stuck abnormally
