### ISSUE TITLE
When I want to add a Textbox, it is not controlled by default

### ISSUE THREAD

**Issue by arctichotpot** [fabricjs/fabric.js#8143]
## Version
5.2.1

## Test Case
- [ ] [Node Issue Template](https://codesandbox.io/s/exciting-browser-ytb701)
- [x] [Browser Issue Template](https://jsfiddle.net/Lcp2h3nv/)

## Information about environment
The development environment is vite +react18.
Browser is Chrome

## Steps To Reproduce

 When I want to add a Textbox, it is not controlled by default

https://stackblitz.com/edit/react-ts-tcpb5y?file=App.tsx

It doesn't work when I add hasControls, but it does work when I create it in useEffect

https://stackblitz.com/edit/react-ts-zvfqbj?file=App.tsx

**Comment by ShaMan123** [comment]
you are not using refs in react as you should
but even though there is something strange happening

**Comment by ShaMan123** [comment]
so except the wrong way you use refs
canvas is initialized more than once (probably because of bad reffing - you must dispose a useeffect) 

https://stackblitz.com/edit/react-ts-jm4jun?file=App.tsx,package.json,style.css

**Comment by arctichotpot** [comment]
When I use this approach in my projects,I get an error " Uncaught TypeError: Failed to set an indexed property on 'CSSStyleDeclaration': Indexed property setter is not supported".

Error:
![image](https://user-images.githubusercontent.com/36844445/185271456-c444761e-b923-4b95-bf6c-9e3be2499594.png)

Code :
![image](https://user-images.githubusercontent.com/36844445/185271755-67beef91-f05d-4637-9b28-5ba905162001.png)



> 所以除了你使用 refs 画布的错误方式被初始化了不止一次（可能是因为糟糕的 refing - 你必须处理一个 useEffect ）
> 
> [stackblitz.com/edit/react-ts-jm4jun?file=App.tsx,package.json,style.css](https://stackblitz.com/edit/react-ts-jm4jun?file=App.tsx,package.json,style.css)
