### ISSUE TITLE
new Rect: width is exceed 10000，stroke is fuzzy

### ISSUE THREAD

**Issue by donotloveshampo** [fabricjs/fabric.js#8147]
## Version
5.0.0

## Test Case

`<canvas id="canvas" width="600" height="600" style="border:1px solid #000000;">`
` var canvas = new fabric.Canvas("canvas"); 

    var rect = new fabric.Rect({
      width: 10000,
      height: 10000,
      strokeUniform: true,
      stroke: "blue",
      strokeWidth: 2,
      fill: null,
    });
    canvas.add(rect);`

![image](https://user-images.githubusercontent.com/19325275/184601829-38278f61-606d-4024-b39c-97a9d4913cd0.png)

<details><summary>Error Message & Stack Trace</summary><p>

## Information about environment
Nodejs or browser?

browser
Which browsers?
chrome 104
## Steps To Reproduce

```txt
<!-- Provide a log message if relevant -->
```
</p></details>

## Expected Behavior

strokewidth is 2px,

## Actual Behavior

it's fuzzy and more than the 2px;

**Comment by ShaMan123** [comment]
`fabric.perfLimitSizeTotal`

it makes no sense to cache such an abnormally large simple shape...

The true bug here might be `strokeWidth` or `strokeUniform` in case of a limited cache size

Turn off caching if you don't need it and you won't experience the problem.

**Comment by donotloveshampo** [comment]
> caching

It solved my big doubt, thank you
