### ISSUE TITLE
Too many text boxes are added, and dragging the text box causes a jam

### ISSUE THREAD

**Issue by Charley-liu** [fabricjs/fabric.js#8149]
![20220816-102228](https://user-images.githubusercontent.com/23217036/184784858-bf9d8e7c-4346-4062-89ab-c7d7e682e9fc.gif)

I found it had nothing to do with the pictures，The version has been updated to the latest version 5.2.1, but after adding more than one text box, it will get stuck abnormally

_Originally posted by @Charley-liu in https://github.com/fabricjs/fabric.js/issues/8142#issuecomment-1216059003_ @kangax

**Comment by ShaMan123** [comment]
I will continue closing your issues unless you fill out the issue template nd follow my instructions
