### ISSUE TITLE
Cursor is behaving strange, two cursors are showing on browser

### ISSUE THREAD

**Issue by amneeshsoftobiz** [fabricjs/fabric.js#8151]
he check here when i type how cursor is behaving on canvas.

https://www.loom.com/share/aec761086f254e6a985f18ea95fecc80

## Version
5.2.1

## Test Case
- [ ] [Browser Issue Template](https://jsfiddle.net/Lcp2h3nv/)
- [ ] [Node Issue Template](https://codesandbox.io/s/exciting-browser-ytb701)

## Information about environment
Nodejs or browser? browser
Which browsers? chrome

## Steps To Reproduce

1.  just typing text fast.

<details><summary>Error Message & Stack Trace</summary><p>

```txt
it is visible error
```
</p></details>

**Comment by ShaMan123** [comment]
provide a repro then I will reopen.
