### ISSUE TITLE
Bug in texts when using fonts from Google Fonts

### ISSUE THREAD

**Issue by LuisE23** [fabricjs/fabric.js#8159]
## Version
5.2.1

## Test Case
- [ ] [Issue in texts with google fonts](https://jsfiddle.net/LuisE23/rja6mocw/13/)

## Expected Behavior
Display the text correctly

## Actual Behavior
The text is not displayed correctly, depending on the font it is shown as a cut or elongated, and sometimes it shows well. Even if the width is calculated, sometimes it varies. In previous versions I did not have this problem, it was displayed correctly (https://jsfiddle.net/LuisE23/0r3kg4cn/5/).

**Comment by ShaMan123** [comment]
1. The difference is not related to fonts, rather to `objectCaching` https://jsfiddle.net/2dxsogz4/
2. The reason this is happening in the first place is that you load the fonts after fabric has measured the text, meaning that you should first load the fonts, then create the IText objects https://jsfiddle.net/2dxsogz4/1/

**Comment by LuisE23** [comment]
Thank you very much @ShaMan123
