### ISSUE TITLE
Not interactive in React and Mext

### ISSUE THREAD

**Issue by Seun-Oyediran** [fabricjs/fabric.js#8162]
When i add basic things to my canvas, there is no cursor to drag or interact with it

**Comment by chloe-bm** [comment]
Maybe try here: https://github.com/layerhub-io/react-design-editor
We are using React and Fabric.js.

**Comment by ShaMan123** [comment]
[CONTRIBUTING](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)

**Comment by darimuhittin** [comment]
Same problem here in React does anyone knows the cause ?

**Comment by ShaMan123** [comment]
add a repro
