### ISSUE TITLE
Can't install latest vesion of fabric - dist folder contains old build

### ISSUE THREAD

**Issue by Talb2005** [fabricjs/fabric.js#8163]
## Version
I'm trying to install the latest version 5.2.1 via npm, but keep getting version 5.1.0 which was released 6 months ago. 

## Steps To Reproduce

1. npm i fabric@latest
2. package.json shows we installed v5.2.1 - **but that's not correct**.
3. open node_modules/fabric/CHANGELOG.md and see that we're infact on version 5.1.0.

## Expected Behavior
When installing fabric, the latest version should be installed.

## Actual Behavior
When installing fabric, an old version is installed.

**Comment by ShaMan123** [comment]
you are correct
duplicate #7830 
@asturur
