### ISSUE TITLE
left and top = null when i add text

### ISSUE THREAD

**Issue by khaledmndev** [fabricjs/fabric.js#8165]
## Version
5.2.1

## Test Case
- [ ] [Browser Issue Template](https://jsfiddle.net/Lcp2h3nv/)

## Information about environment
Nodejs or browser? Browser
Which browsers? Edge 104.0.1293.63 (Official build) (64-bit)

## Steps To Reproduce

1. for short: i can add custom text on computer on cursor position but not on touch devices like mobile or tablet

## Expected Behavior
Here you can see on computer it's working hen i add text
![alt text](https://i.ibb.co/PwKRMHr/Screenshot-2022-08-21-184627.png)

## Actual Behavior
And here's what happens when i try to add on mobile or tablet:
![alt text](https://i.ibb.co/gzyLjc2/Screenshot-2022-08-21-185006.png)

**Comment by ShaMan123** [comment]
https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker
