### ISSUE TITLE
blur/background color border around clipped image. 

### ISSUE THREAD

**Issue by sushilronghe99** [fabricjs/fabric.js#8171]
If we have a colored rect and draw a clipped image over it - the image gets a colored border or blur border after moving the image. We don't have to scale the image at all (I saw somewhere that the issue related to " the blurred border on clipped images when they are scaled using controls" is still open). 

Here is the fiddle - just move the image and you will notice the green color border around image. 
fiddle link : [https://jsfiddle.net/resdquh2/](https://jsfiddle.net/resdquh2/)

I also tried adding a strokeWidth of 0 after each renders to the image but it did not help. Let me know if this is a bug or if there is any workaround for this. 
<img width="1151" alt="Screenshot 2022-08-22 at 11 15 27 PM" src="https://user-images.githubusercontent.com/104120825/185989996-731dba59-a29a-4749-afc6-32c1bf0efafa.png">

Thanks

**Comment by asturur** [comment]
it may have to do with thet fact that the rect may not be positioned pixel perfect anymore.
I ll dig into it, but i can't see the tiny green border for now
