### ISSUE TITLE
Blank pixels when using freeDrawingBrush

### ISSUE THREAD

**Issue by abaransy** [fabricjs/fabric.js#8173]
## Version
4.0.0

## Test Case
- Please make sure to use FireFox, I'm using version 91.12.0esr (64-bit)
- Visit https://jsfiddle.net/9rycenhb/13/

## Information about environment
FireFox, I'm using version 91.12.0esr (64-bit)

## Steps To Reproduce

1. Try drawing, you will sometimes see a gap where pixels are left blank. I've found that it happens more often when I draw a line by very quickly dragging my mouse from one side to another.

## Expected Behavior

All pixels should be filled with the specified color.

## Actual Behavior

Some are not filled with the specified color, they are left blank. Zoom in and you will see a slim white line.

<img width="1446" alt="bug_1" src="https://user-images.githubusercontent.com/57848320/186269946-4aa64990-6002-4c52-8dde-3b0f17f8a86a.png">
<img width="1105" alt="bug_2" src="https://user-images.githubusercontent.com/57848320/186269786-be1c87c8-f36a-4a2c-8446-e0281a0a6850.png">

**Comment by abaransy** [comment]
> let's eliminate a few things:
> 
> 1. version - update fabric's version and see what happens (you can downgrade as well)
> 2. browser - reproduce with bare HTMLCanvas. Use the path data output (`path.toJSON()`) to draw the line.

@ShaMan123 

Thanks for the prompt response.

1. The issue seems to be present in 4.5.0 and 4.6.0 so it's not specific to this version.
2. 2. How do I use the path data to draw the line? 

Here's a drawing with the path 
```JavaScript
[["M", 38.8, 149], ["Q", 39, 149, 39.5, 149], ["Q", 40, 149, 40.5, 149], ["Q", 41, 149, 41.5, 149], ["Q", 42, 149, 43, 149], ["Q", 44, 149, 46, 149], ["Q", 48, 149, 51.5, 148], ["Q", 55, 147, 61, 145], ["Q", 67, 143, 75, 140], ["Q", 83, 137, 92.5, 132.5], ["Q", 102, 128, 114.5, 122.5], ["Q", 127, 117, 140, 111], ["Q", 153, 105, 167, 98], ["Q", 181, 91, 196.5, 83], ["Q", 212, 75, 224, 69], ["Q", 236, 63, 242.5, 59.5], ["Q", 249, 56, 255.5, 52.5], ["Q", 262, 49, 267.5, 46.5], ["Q", 273, 44, 276, 42.5], ["Q", 279, 41, 283, 39], ["Q", 287, 37, 289.5, 36], ["Q", 292, 35, 293.5, 34], ["Q", 295, 33, 296, 33], ["L", 297.2, 33]]
```
<img width="1361" alt="Screen Shot 2022-08-24 at 11 09 35 AM" src="https://user-images.githubusercontent.com/57848320/186491851-9666225c-0764-40ee-b155-174e22f7584e.png">

Here's the fiddle: https://jsfiddle.net/bxwv5j48/5/

Thanks, 

-Aatef

**Comment by ShaMan123** [comment]
1. bumping a minor is not enough. bump a major
2. see `_renderPathCommands` or https://developer.mozilla.org/en-US/docs/Web/API/Path2D/Path2D to draw a path

**Comment by abaransy** [comment]
> 1. bumping a minor is not enough. bump a major
> 2. see `_renderPathCommands` or https://developer.mozilla.org/en-US/docs/Web/API/Path2D/Path2D to draw a path

1. Bumped to 5.2.3, same issue is present.
<img width="665" alt="Screen Shot 2022-08-25 at 2 55 13 PM" src="https://user-images.githubusercontent.com/57848320/186776047-0dee36d5-4234-4ee5-90fc-58bf9a8b3050.png">
2. Still not sure how to generate a path to draw the line. Here's the path: 
```JavaScript
[
["M", 185.8, 145.2],
["Q", 186, 145, 187, 145],
["Q", 188, 145, 256.5, 133.5],
["L", 325.2, 121.8],
]
```

**Comment by abaransy** [comment]
@ShaMan123 See the screenshot below. When cloning the original object, the pixels are still blank.


<img width="716" alt="Screen Shot 2022-08-29 at 1 56 02 PM" src="https://user-images.githubusercontent.com/57848320/187297538-bdd0054b-395f-40cd-bce3-f18d8d85184a.png">

code:

```JavaScript
window.onload = function() {
  var canvas = this.__canvas = new fabric.Canvas("input-canvas", {
    isDrawingMode: true
  });

  canvas.on("after:render", function() { canvas.calcOffset(); });
	
  let flag = false;
  
  canvas.freeDrawingBrush.width = 200;
  canvas.freeDrawingBrush.color = "orange";
  canvas.on({
  	'object:added': (options) => {
      if (flag) return;
      
      flag = true;

      clone();
    },
  })
  
  const clone = () => {
    const object = canvas.getObjects()[0];   
    const clonedObject = fabric.util.object.clone(object);
    clonedObject.set({ top: 0, left: 0 });
    canvas.add(clonedObject);
  }

  document.getElementById("clearButton").onclick = function() { canvas.clear(); };
}
```

fiddle: https://jsfiddle.net/8twjvgp6/87/

**Comment by abaransy** [comment]
@ShaMan123 any updates on this?

**Comment by ShaMan123** [comment]
No
Low priority for me
Maybe aliasing related
