### ISSUE TITLE
Dynamic patterns : Image pattern will change with the polygon's ScaleX and ScaleY

### ISSUE THREAD

**Issue by duonanjian** [fabricjs/fabric.js#8174]
When i use img.scaleToWidth() or img.scaleX to set the img width,they will not incorrect display

**Comment by duonanjian** [comment]
![image](https://user-images.githubusercontent.com/55785073/186330422-2c1dcfb0-637f-45b1-b95f-791bd293bb31.png)
I set the polygon with scaleX: 0.5, scaleY: 0.8, and now the rect and polygon has the same width,
however, the polygon's image pattern will change with his scalex, but the rect will not.
i want them to be the same

**Comment by duonanjian** [comment]
![image](https://user-images.githubusercontent.com/55785073/186331442-73b5f93c-93f1-426f-913f-e9d8bd1cbfb9.png)
This image will be more clear

**Comment by ShaMan123** [comment]
reproduction!

**Comment by duonanjian** [comment]
> reproduction!

I need to set scalex or scaley to change the polygon,once I set the property,the fill pattern will also change

**Comment by asturur** [comment]
@duonanjian can you create a simple jsfiddle or codesandbox where this issue is actually visible? screenshots are not enough
