### ISSUE TITLE
Image resizes slightly after loadFromJSON

### ISSUE THREAD

**Issue by AlvesJorge** [fabricjs/fabric.js#8178]
Fiddle:
https://jsfiddle.net/qm30r1bp/33/

Image changes size slightly when loaded from JSON. 
I tried checking image scaledheight before and after and it says it is still the same height.
Steps to reproduce:
Notice how the image covers the window top to bottom
Open fiddle
Click on the photo to clear it and load it from json
Notice the red bar under the photo

**Comment by ShaMan123** [comment]
http://fabricjs.com/fabric-gotchas

NUM_FRACTION_DIGITS

```js
fabric.Object.NUM_FRACTION_DIGITS=15

```

https://jsfiddle.net/wj9omh8q/

**Comment by AlvesJorge** [comment]
Worked like a charm.
Thank you so much, didn't think that I would need to look into the caveat section so early on.

**Comment by ShaMan123** [comment]
Good point...
We are working on v6, making fabric modular so ugly global/shared constants like `NUM_FRACTION_DIGITS` will hopefully fade out in favor of better practice.
