### ISSUE TITLE
setPositionByOrigin after use getBoundingRect Data error

### ISSUE THREAD

**Issue by yirandidi** [fabricjs/fabric.js#8181]
## Version
5.0.0

## Test Case
- [x] [Browser Issue Template](https://jsfiddle.net/Lcp2h3nv/)
- [ ] [Node Issue Template](https://codesandbox.io/s/exciting-browser-ytb701)

## Information about environment
Nodejs or browser?
Which browsers?

## Steps To Reproduce

1. 

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```
</p></details>

**Comment by ShaMan123** [comment]
follow [CONTRIBUTING](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md) and then I'll reopen

**Comment by ShaMan123** [comment]
probably you need to call `setCoords`
http://fabricjs.com/fabric-gotchas

**Comment by yirandidi** [comment]
> probably you need to call `setCoords` http://fabricjs.com/fabric-gotchas

I used setcoords, but it was still wrong.
My code is as follows:
`objs.setPositionByOrigin(point, 'center', 'center')
objs.setCoords()
objs.set({ dirty: true })
canvas.renderAll()
canvas.setActiveObject(objs)`

I call getBoundingRect contents later and it is wrong

![image](https://user-images.githubusercontent.com/57606461/190836229-77a09278-b57e-4dd4-bc81-a43c1ffa1edd.png)

**Comment by yirandidi** [comment]
这是我调用左对齐的结果，他的left确实是0，但是getBoundingRect确实-1.77

**Comment by yirandidi** [comment]
This is the result of my call to left align. Its left is indeed 0, but getBoundingRect is indeed -1.77

**Comment by ShaMan123** [comment]
#7670 the object is on a group
