### ISSUE TITLE
cursor position error when there is some emoji in TextBox

### ISSUE THREAD

**Issue by senschen** [fabricjs/fabric.js#8213]
## Version ##
5.2.1

## Test Case ##
https://codesandbox.io/s/fabric-cursor-emoji-issue-forked-ps7brs

## Information about environment ##
Win Chrome, IOS & MAC Chrome, Safari

## Steps To Reproduce ##
Open sandbox on IOS, Mac or Win
Start editing text
Enter several of emoji  (win + . or paste emoji 🤷‍♂️)

## Expected Behavior ##
The cursor is after last symbol. Textbox width is not correct.

![image](https://user-images.githubusercontent.com/8544826/187323847-2a1c9707-e374-4d55-a625-5aba4a70ae42.png)
## Actual Behavior ##
The cursor is somewhere before last symbol.

**Comment by zhe-he** [comment]
I also encountered this issue and found that it only occurs with emojis that are composite symbols (combinations of multiple Unicode code points).

**Comment by asturur** [comment]
You have to use a grapheme splitter that can understand emojis, and that supports the latest version of emojis.
I used this last time ( is now read only ) and is good ( is still good )
https://github.com/flmnt/graphemer?tab=readme-ov-file

Consider also that now modern browser are supporting this natively slowly, so at some point it will just work
