### ISSUE TITLE
Group doesn't change border size and crop item images.

### ISSUE THREAD

**Issue by adriankrawczyk** [fabricjs/fabric.js#8217]
## Version
5.2.1

## Test Case
https://jsfiddle.net/fqptdycz/24/

## Information about environment
Browser

## Steps To Reproduce

1. Create any shape
2. Create fabric group with this shape
3. Make the size of the shape bigger 
4. It gets cropped

## Expected Behavior
The borders should update when items in group change size and the item should not be cropped.

## Actual Behavior

When item in group grows in size, it's image gets cut.

## Screenshots

![Screenshot_20220830_112054](https://user-images.githubusercontent.com/59731629/187400239-e5a175be-69b0-4e76-a436-64fe6cd03966.png)
![Screenshot_20220830_103842](https://user-images.githubusercontent.com/59731629/187400269-9f5860aa-731a-48a2-9c2c-9ea9198e1e57.png)

**Comment by ShaMan123** [comment]
#7670
