### ISSUE TITLE
Revert strict typing on toObject methods and pick

### ISSUE THREAD

**Issue by asturur** [fabricjs/fabric.js#8219]
In recent code changes we added:

```js
toObject(propertiesToInclude?: (keyof this)[]) {
```
compared to
```js
toObject(propertiesToInclude?: string[]) {
```

And we added the pick util that has this signature:
```js
export const pick = <T>(source: T, keys: (keyof T)[] = []) => {
    return keys.reduce((o, key) => {
        if (key in source) {
            o[key] = source[key];
        }
        return o;
    }, {} as Partial<T>);
}
```

Before the toObject function allowed you to pass any array of strings, either if those had a place in the current object, or were completely new and custom.
This behavior should stay since developers may want to add new properties to the objects and this should be legit, without the need of subclassing.

Either the toObject should return a type that contains a part of the class and an extra bag of random properties, or directly a wild any.
also pick shouldn't return a Partial<T> since it could potentially be not overlapping at all with T.

Imagine  i do pick(['name']) on a rect, there is no overlap between what i return  from pick.

**Comment by asturur** [comment]
@ShaMan123 and @melchiar  FYI

**Comment by ShaMan123** [comment]
`pick` is not part of the game. `T` will become anything you pass as `source`. So the only option for a return value is a `Partial<T>` unless I am missing something.
`toObject` type is the issue here. It will become stricter if we apply the type to it. I agree.
