### ISSUE TITLE
Editing text is broken in the child window

### ISSUE THREAD

**Issue by sunsetninja** [fabricjs/fabric.js#8228]
## Version
5.2.1

## Test Case
https://codesandbox.io/s/fabric-new-window-rcpz1u

## Information about environment
MacOS 12.5.1, Chrome 105.0.5195.52 (Official Build) (x86_64)

## Steps To Reproduce

In the test case above:

1. Click on open window button
2. Close an opened window
3. Click on open window button
4. Try to edit text in text box in open window

## Expected Behavior

Text can be edited normally

## Actual Behavior

Editing text is broken

<img width="577" alt="image" src="https://user-images.githubusercontent.com/13559663/187878749-16260b7f-94be-476d-89a4-f48d17813517.png">

**Comment by sunsetninja** [comment]
I think I found what the problem is

the thing is that the `fabric._measuringContext` instance lives in the root window

and when opening the first child window, we write this context, which remains there after the child window is closed

and when opening the second window, we use the same context to measure the length of the characters, which results in a zero character length

**Comment by kirill-konshin** [comment]
@ShaMan123 @asturur can you please take a look a this issue, quite a nasty bug...

**Comment by asturur** [comment]
Hello @sunsetninja it looks to me that  adding fabric._measuringContext = null; while opening the new window fix the issue.
Not sure how we can detect this to be honest, this is the first case in which i see using fabric through popups.
