### ISSUE TITLE
docs(): wiki `gotchas` link is broken

### ISSUE THREAD

**Issue by ShaMan123** [fabricjs/fabric.js#8236]
### Discussed in https://github.com/fabricjs/fabric.js/discussions/8234

<div type='discussions-op-text'>

<sup>Originally posted by **leszekhanusz** September  1, 2022</sup>
It seems the Gotcha's [https://github.com/fabricjs/fabric.js/wiki/Fabric-gotchas](https://github.com/fabricjs/fabric.js/wiki/Fabric-gotchas) link is broken.</div>

**Comment by ShaMan123** [comment]
Anyone needing it until the PR is merged follow the [link](https://github.com/fabricjs/fabric.js/blob/38dabda56612077d5cd65a75ba30640c3e833bbe/GOTCHAS.md)

**Comment by asturur** [comment]
i m all for closing the wiki, is an extra thing to maintain on top of the website

**Comment by ShaMan123** [comment]
Great
