### ISSUE TITLE
Convert FabricJS json to image

### ISSUE THREAD

**Issue by marcpre** [fabricjs/fabric.js#8243]
## Version
    "fabric": "^5.2.4"

## Test Case
When trying to convert my fabricjs json back I do not get the original image:

Original Image:
![image](https://user-images.githubusercontent.com/30902582/188271900-dc6e91c8-2013-4a13-b890-5bba76dfd224.png)

Created Image:
![image](https://user-images.githubusercontent.com/30902582/188271921-22258822-8f62-43b0-a667-68bb1d665b8a.png)

I created the following codesandbox for my script:

[https://codesandbox.io/s/stupefied-lalande-d6qn3b?file=/output.png:0-68082](https://codesandbox.io/s/stupefied-lalande-d6qn3b?file=/output.png:0-68082)

## Information about environment
Nodejs

## Steps To Reproduce

Just run the script below (its also in the above codesandbox link):
```
var fs = require("fs"),
  fabric = require("fabric").fabric,
  out = fs.createWriteStream(__dirname + "/output.png");

let jsonstr = fs.readFileSync(__dirname + "/json/test_json.json", "utf-8");
let json = JSON.parse(jsonstr);

// var canvas = new fabric.StaticCanvas(null, { width: wh.width, height: wh.height });
var canvas = new fabric.StaticCanvas(null, { width: 800, height: 1200 });

canvas.loadFromJSON(json, function () {
  //first render
  canvas.renderAll.bind(canvas);

  //save the canvas as SVG in server
  // var svgoutput = canvas.toSVG();
  var dataUrlOutput = canvas.toDataURL(); // png is default format
  console.log(dataUrlOutput);
  fs.writeFile(__dirname + "/output.png", dataUrlOutput, function (err) {
    if (err) {
      console.log(err);
      throw err;
    }
  });
});
```

## Expected Behavior

Get the following image correctly rendered from the fabricjs json:
![image](https://user-images.githubusercontent.com/30902582/188271900-dc6e91c8-2013-4a13-b890-5bba76dfd224.png)

## Actual Behavior

I currently get the following image:
![image](https://user-images.githubusercontent.com/30902582/188271921-22258822-8f62-43b0-a667-68bb1d665b8a.png)

I appreciate your replies!

**Comment by ShaMan123** [comment]
not a bug
loadFromJSON is a promise in v5+

**Comment by ShaMan123** [comment]
your reproduction isn't good enough (for next time). Not immediate
