### ISSUE TITLE
Canvas.calcOffset() not working after setting zoom

### ISSUE THREAD

**Issue by afnanz7634** [fabricjs/fabric.js#8265]
Hello !
I've implemented the zooming feature . on Initializing the canvas when i  add object in it and change the position of object to right it works fine . the code i use is 
`let canvas = this.getActiveCanvas;
      var activeObject = canvas.getActiveObject();
      activeObject.set({
          left: canvas.width - (activeObject.width * activeObject.scaleX),
          originX: 'left',
          originY: 'top',
        })
      canvas.renderAll();`
to set object on right side;
![image](https://user-images.githubusercontent.com/49157938/189440261-19a31f34-131f-43df-8a9f-f5fce81b8f5e.png)

but when i zoom in the canvas and then click on the right position to change the position of text to the right of canvas it doesn't work 

![image](https://user-images.githubusercontent.com/49157938/189441442-9c8ec647-865a-4655-9442-97176522e645.png)

how to set the right position after zoom ????

**Comment by chloe-bm** [comment]
Here is how we are handling it: 
https://github.com/layerhub-io/layerhub-io/blob/d5a0e65b28465d5fc51e1bc477992cc98c1fa9de/packages/core/src/controllers/Objects.ts#L673

Demo here: https://editor.layerhub.io/
Source code: https://github.com/layerhub-io/react-design-editor

**Comment by ShaMan123** [comment]
Use discussions for Q&A please
