### ISSUE TITLE
Right Alignment issue for SVG

### ISSUE THREAD

**Issue by pratikshap31** [fabricjs/fabric.js#8288]
Hello, 

Version : 1.6.0-rc.1
JS: Fabric.js
Issue: Tosvg coordinates value not correct
TestCase: 
site: **https://text.flyerco.dev/**
Editor URL: https://text.flyerco.dev/flyers/3238/edit
Email Id: text@mailinator.com
Password: text@123
Snap Video: https://www.loom.com/share/b3ebff187fa14c45bdce3d1e6a1bb008 
editor snap: https://www.awesomescreenshot.com/image/32390859?key=02a66fe1d846ef7a1a6b9158fb635cad
SVG snap: https://www.awesomescreenshot.com/image/32391978?key=f168d78065042113ae973f0dfc50a00a
PDF snap: https://www.awesomescreenshot.com/image/32390792?key=d950ff35e614901d3a136563236e301a 

Description:
I am facing an issue while converting JSON objects to toSvg using fabric JS. It occurs in some cases with the right text alignment.
I don't understand the calculation of the SVG converter.
Does anyone know how to solve it?
`<tspan xml:space="preserve" x="152.8" y="319.92" fill=" #000000">ius.2</tspan>`
I have checked SVG data and the issue was found in X value when text right alignment for some font size.
This issue occurs when the last line of the paragraph has 1-2 words.
**P.S: In my case, it occurs for some font sizes only. for example, 18,22 etc.**
![fly](https://user-images.githubusercontent.com/62551138/190112711-edb424a5-516b-41f2-b41a-7ddad558facb.svg)
The attached file of SVG code

Let me know if any code, version, or anything needs to solve it

**Comment by ShaMan123** [comment]
upgrade to latest and I will reopen

**Comment by pratikshap31** [comment]
@ShaMan123 

I can't upgrade to the latest version. Its methods and all connected with other JS. also it is minified and mapped with other JS.
https://i.imgur.com/i7xsIGP.png
