### ISSUE TITLE
fabric.Textbox in <dialog> element can not be edited

### ISSUE THREAD

**Issue by sn3p** [fabricjs/fabric.js#8289]
## Version

5.2.4

## Test Case

https://codepen.io/snap/pen/BaxQdPj?editors=1010

## Information about environment

All browsers: Chrome, Firefox, Edge, ... (tested on MacOS)
Safari is an exception, where the textbox only accepts a single character.

## Steps To Reproduce

1. Open the dialog containing the canvas
2. Focus and edit the textbox
3. Try and edit the textbox
4. Fail

## Expected Behavior

The textbox inside a `<dialog>` element should be editable.

## Actual Behavior

The textbox inside a `<dialog>` element can not be edited.
Safari is an exception, where it only accepts one character after the cursor changes position (using the mouse).

I also tried inserting the canvas after the dialog was opened, but that didn't resolve the issue:
https://codepen.io/snap/pen/oNdYoWW?editors=1010

**Comment by ShaMan123** [comment]
Pass the dialog element as `hiddenTextareaContainer` .
I think scrolling is buggy.

**Comment by ShaMan123** [comment]
So I'm closing this ticket as solved.
I scrolling is bad submit another issue

**Comment by sn3p** [comment]
@ShaMan123 thank you! Setting the dialog as `hiddenTextareaContainer` did the trick 🎉 

But like you said, the dialog scrolling gets a bit wonky due to the textarea positon:
https://codepen.io/snap/pen/ExLNGyw?editors=1010

Setting `position: fixed` for the textarea seems to fix it.
In the demo that is, I'm not sure if this works for other case.

https://codepen.io/snap/pen/ExLNGXo

```css
textarea[data-fabric-hiddentextarea] {
  position: fixed !important;
}
```
