### ISSUE TITLE
bug(): options overriding args

### ISSUE THREAD

**Issue by sn3p** [fabricjs/fabric.js#8294]
## Version

5.2.4

## Test Case

https://codepen.io/snap/pen/poVRgvJ?editors=1010

## Information about environment

All major browsers (tested in Chrome, Firefox, Safari on MacOS)

## Steps To Reproduce

1. Add extended Textbox (as Textarea in my case) to the canvas
2. Save the canvas to JSON
3. Load the JSON back to the canvas
4. Create and add another extended Textbox instance (with another text) to the canvas
5. The added instance "inherits" the text from the loaded instance instead of the passed text

## Expected Behavior

After saving and loading an extended Textbox instance from JSON, and creating a new instance passed with a text, it should set and display the passed text.

- Without instance in loaded JSON it works as expected: https://codepen.io/snap/pen/RwyKrgE?editors=0010
- Without saving and loading from JSON it works as expected: https://codepen.io/snap/pen/bGMgVXy?editors=0010

## Actual Behavior

When adding a new extended Textbox instance after loading another instance from JSON, it will "inherit" the text of the loaded instance instead of the newly passed text.

Demo: https://codepen.io/snap/pen/poVRgvJ?editors=0010

## Workaround

Setting the text after calling super on "initialize" fixed it for me:

```js
this.callSuper("initialize", text, options);
this.set("text", text);
```

Fixed: https://codepen.io/snap/pen/PoeWPOe?editors=0010

**Comment by ShaMan123** [comment]
Please use bug reports for BUGS.
I understand that fabric's learning curve is a tough but we want to be able to maintain this repo.
Start discussions instead.

You are passing the text prop once as `text` and once in the options object. Delete it from the options object.

**Comment by sn3p** [comment]
@ShaMan123 sorry about that, I will start a discussion next time.
I missed the text attribute in the object.. that was indeed my error.

**Comment by ShaMan123** [comment]
IMO it should be considered a bug that the text arg is overridden by the optons arg.
It should repect it or we should change the signature to accept only an optons object.
@asturur this is why I want strict assignments intead of a generic set

**Comment by ShaMan123** [comment]
Reopened for v6 related discussion

**Comment by ShaMan123** [comment]
@sn3p look at #8295 
I suggest you make your subclass as suggested there

**Comment by asturur** [comment]
i am sorry, but isn't the bug this one?
```
      options = fabric.util.object.extend(
        fabric.Textarea.defaultOptions,
        options
      );
```

Or this was just clarified and i arrived late?
we are mutating defaultOptions with options, so we inser text there, and from that moment on, you are broken forever.

(this is probably a **paid bug** from @ShaMan123 to demonstrate prototype mutation is bad )

I m not sure which is the exact intention of that code, if it is to ensure default options are always present, then it should be:
```js
      const newOptions = fabric.util.object.extend({}, 
        fabric.Textarea.defaultOptions,
        options
      );
```

(extend is mutating the first object, it was an equivalend ot Object.assign)

but in general i would have just done:

```js
  fabric.Textarea = fabric.util.createClass(fabric.Textbox, {
    type: "textarea",
    width: 200,
    fontWeight: 800,
    fontFamily: "Verdana",
    initialize: function(text, options = {}) {
      this.callSuper("initialize", text, options);
    }
  });
```

following the patterns of other classes that sets defaults in that way.

**Comment by ShaMan123** [comment]
> (this is probably a **paid bug** from @ShaMan123 to demonstrate prototype mutation is bad )
Haha LOL, I burst into laughter!

**Comment by ShaMan123** [comment]
Don't you think it is a good case showing why set options should be stricter?

**Comment by ShaMan123** [comment]
I am still laughing

**Comment by ShaMan123** [comment]
IMO it is a good case showing that fabric is too sensitive, "breaks" with the slightest offense.
Because fabric isn't strict enough the dev has to be very strict in writing exactly as fabric is written so it won't get offended and that is nonsense.
It is exactly my experience and other devs I have talked (my strict js coalition 😈) to surfaced the same concern

**Comment by sn3p** [comment]
> @sn3p look at #8295
> I suggest you make your subclass as suggested there

Are you suggesting I copy the logic from `fabric.Object._fromObject` in your PR to the subclass?

**Comment by asturur** [comment]
@sn3p there are 3 ways to fix your current issue. ( on top of the one you used as workardound ).
The simplest is to use extend correctly:

```js
      const newOptions = fabric.util.object.extend({}, 
        fabric.Textarea.defaultOptions,
        options
      );
```
adding an extra empty object and passing newOptions to the super initializer.
that would be fixing your bug.

The second way of fixing it would be refactor your subclass to have the default properties declared in the class:

```
  fabric.Textarea = fabric.util.createClass(fabric.Textbox, {
    type: "textarea",
    width: 200,
    fontWeight: 800,
    fontFamily: "Verdana",
    initialize: function(text, options = {}) {
      this.callSuper("initialize", text, options);
    }
  });
```
unless you need those to be dynamic for some reason ( so if you are changing the defaultOptions in your app following some logic )

Fiddling with the fromObject function fixes the issue at the root, but would have left you unaware of what was going wrong.
Sachar fix avoids the breakage when using loadFromJson, but your code is still vulnerable to someone passing text in the options manually.

**Comment by sn3p** [comment]
@asturur thanks for the suggestions! I got the impression extend wasn't mutating but it does.

> ```js
>       const newOptions = fabric.util.object.extend({}, 
>         fabric.Textarea.defaultOptions,
>         options
>       );
> ```
> 
> adding an extra empty object and passing newOptions to the super initializer.
> that would be fixing your bug.

I tried this, but it looks like [`extend`](https://github.com/fabricjs/fabric.js/blob/master/src/util/lang_object.ts#L18) util doesn't support multiple sources.

So would either have to do:

```js
options = fabric.util.object.extend(
  fabric.util.object.extend({}, fabric.Textarea.defaultOptions),
  options
);
```

Or use [`Object.assigns`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign):

```js
options = Object.assign({}, fabric.Textarea.defaultOptions, options);
```

Both work fine. Or is the `extend` util is preferred for merging options?
