### ISSUE TITLE
Video in webm format flickers when looped in Firefox

### ISSUE THREAD

**Issue by 7Ds7** [fabricjs/fabric.js#8308]
Opening the testcase below in Firefox (canvas on the left, video tag on the right) one can see that the video element plays correctly, while the video inside the canvas blanks/flickers with every loop. As opposed to opening it Chrome/Safari in which both the video element and the canvas video loop properly.

## Version

5.2.4

## Test Case
https://jsfiddle.net/cuzb37rn/

## Information about environment

Nodejs or browser?
Browser

Which browsers?
Firefox

## Steps To Reproduce

Add a looped video to the canvas in webm format in Firefox

## Expected Behavior
Expect the video to loop without blanking for one frame

## Actual Behavior
Canvas video blanks/flickers with each loop

**Comment by rolitter** [comment]
you can createClass with  video dom
https://codepen.io/rolitter/pen/yLjzJKo?editors=1010
![image](https://user-images.githubusercontent.com/27326998/191876757-44c27007-f131-4c0a-a520-3a6cb5ab7288.png)

**Comment by ShaMan123** [comment]
My second suggestion:
You shouldn't use `requestRenderAll` inside a requested animation frame. It's doubling the request and therefore the delay and that might be causing the glitch. Use `renderAll`.
We should document it...

**Comment by ShaMan123** [comment]
actually #8298 provides enough context for use to warn the dev.

**Comment by 7Ds7** [comment]
Thank you both for the input

@rolitter your example does work https://jsfiddle.net/o3kmny1c/5/ and loops the video without the blank frame on loop, but i believe that is just because it is playing in regular DOM and not inside the canvas, like so one looses relation to other objects inside the canvas ex: index, bounds etc... 

@ShaMan123 I recorded a video but as it is only one blank frame/quick flicker it is not noticeable in the recording.
Although i have tried renderAll instead of requestRenderAll does not help here https://jsfiddle.net/g8s7Lpyq/

What is weird to me is that it was a specifically webm problem with  firefox but it turns out that is all sort of video formats in firefox as long as they are in the canvas, for example mp4 https://jsfiddle.net/bom0jrn7/ any other browser that is not firefox the loops goes trough without flickering.
The reason for it to be webm or mov is to preserve transparency but it seems that it has nothing to do with the format after all.

I will try and debug it more and will be leaving feedback here

**Comment by ShaMan123** [comment]
related #8382 ?
