### ISSUE TITLE
perPixelTargetFind = true , mouse:over event error

### ISSUE THREAD

**Issue by nailuox** [fabricjs/fabric.js#8324]
## Version

4.6.0

## Test Case

- [ ] [Browser Issue Template](https://jsfiddle.net/07dkce4r/)

## Information about environment

Nodejs or browser?
browser
Which browsers?
chrome105.0.5195.127

## Steps To Reproduce

1. The mouse has been on the object during loading
2. During the loading process, the mouse moves quickly back and forth on the position of the object

![image](https://user-images.githubusercontent.com/49058926/192932031-a161a476-15ca-42e5-8313-e1b003b45f54.png)

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

**Comment by ShaMan123** [comment]
Can't reproduce
Seems like good old `setCoords`
See the gotchas guide http://fabricjs.com/fabric-gotchas
