### ISSUE TITLE
rendering wrong font family when applying bold/italic (if text object dimensions do not increase).

### ISSUE THREAD

**Issue by KevinUK** [fabricjs/fabric.js#8329]
## Version
5.2.4

## Test Case
https://jsfiddle.net/75kxLdvo/

## Information about environment
The test case shows 2 working scenarios and 2 broken scenarios. The bug occurs when the dimensions of the text object are not changed when pressing bold (due to the bold font not always needing more width/height).

## Steps To Reproduce

1.Choose font Arsenal or Advent Pro from the drop down list.
![image](https://user-images.githubusercontent.com/1001172/193141930-19b14656-1e47-4f1d-8ae4-8465de1dfa3d.png)
2. Press 'apply bold'

## Expected Behavior
Applying bold should not change the font family.
![image](https://user-images.githubusercontent.com/1001172/193142009-f0ad56d7-3b74-4bb2-b95a-8626b056651f.png)

## Actual Behavior
Applying bold removes the applied font family.
![image](https://user-images.githubusercontent.com/1001172/193141985-6f3658e1-1ea2-4402-a6b3-9800dd6e6586.png)

If you remove the font-weight bold, then apply it again, the original correct font-family then shows in bold.

## Working Scenario
Choose fonts Acme or Arimo. These correctly keep the font family as the bold font is wider than the object dimensions.

**Comment by ShaMan123** [comment]
https://jsfiddle.net/5zy9gjcp/

```diff
- object['fontWeight'] = boldState;
- object.set({ dirty: true });
+ object.set({ fontWeight: boldState });
```

**Comment by KevinUK** [comment]
Thanks for the code snippet @ShaMan123 . I tried your jsfiddle in Brave and Edge but the bug still happens for me.

**Comment by ShaMan123** [comment]
Maybe try clearing the `fontCache` by calling `clearFontCache`

**Comment by KevinUK** [comment]
@ShaMan123 clearing font cache didn't work either. Can you please re-open this bug.

The fix is to call whatever code runs when the object dimension changes:

Select bold and font changes to wrong font:
![image](https://user-images.githubusercontent.com/1001172/193446374-fe47d88b-99a0-452c-b3ba-529fcafbad9e.png)
Drag the object dimension by any size and the font corrects itself:
![image](https://user-images.githubusercontent.com/1001172/193446395-59188e1d-1812-4b80-b721-f0527f398ecb.png)

**Comment by ShaMan123** [comment]
Provide a video showing it happening in the relevant browsers and I'll reopen.


Regarding triaging:
https://github.com/fabricjs/fabric.js/blob/0830cdb24cc3c2004f3885a40cc1c91542343240/src/shapes/text.class.ts#L1685

There are more references, but the same logic applies.
So try flagging the text object with `_forceClearCache`

**Comment by KevinUK** [comment]
Hi @ShaMan123, this did not work either:
object._forceClearCache = true;

Here is a gif based on your jsfiddle (I chose the font from the dropdown list before recording as jsfiddle had issues with the recorder on that step). I did ctrl + F5 first to clear any cached fonts.
![Animation](https://user-images.githubusercontent.com/1001172/193450820-123fb795-d182-4bbb-8540-210366942082.gif)

**Comment by ShaMan123** [comment]
Managed to reproduce on chrome!
As you mentioned:
- refresh page
- chose font
- clicked bold
- did a resize with the control
- only then it changed


I wonder if it's because of edit mode

**Comment by ShaMan123** [comment]
Can you try these 2:
https://jsfiddle.net/g0u69rhb/24/
https://jsfiddle.net/xuLafy3d/

**Comment by KevinUK** [comment]
Neither of those work, I still need to resize the control to see the correct font-family.

Doing this instead of resizing the control also works:
![Animation](https://user-images.githubusercontent.com/1001172/193466689-0c30906b-1018-4ed0-81be-7c554faef4fb.gif)

**Comment by asturur** [comment]
@KevinUK sorry for being late here.
a bold font is a different font from the non bold one.
You have to load both, for each variation of family,weight and style.

Loading AdventPro does not mean you loaded AdventPro BOLD yet.
