### ISSUE TITLE
Bug: Video element shows as blank box in Android Firefox

### ISSUE THREAD

**Issue by codeAdrian** [fabricjs/fabric.js#8332]
## Version

5.2.4

## Test Case

- [ ] [Codepen example - open on Firefox on Android](https://codepen.io/AdrianBece/pen/eYrMrNz?editors=1010)

## Information about environment

Android (any version)
Firefox (latest version)

## Steps To Reproduce

1. Create video element (autoplay, muted)
2. Create canvas
3. Append video element as image to canvas

## Expected Behavior

Video should render and play as expected on Android FIrefox

![Screenshot 2022-09-30 at 12 14 35](https://user-images.githubusercontent.com/11479290/193248570-071dcd32-6fa7-4c29-9806-f00ea99e6648.png)

## Actual Behavior

Video shows up as a blank box

![Screenshot 2022-09-30 at 12 07 39](https://user-images.githubusercontent.com/11479290/193247412-d18a9f72-8274-4c8e-9c08-099163a73ac5.png)

**Comment by ShaMan123** [comment]
This seems duplicate to me #8088 

> Make sure you are updating your fabric video element dimensions after video metadata has loaded.

Reopen if you disagree

**Comment by codeAdrian** [comment]
Codepen has been updated with dimensions update but the issue still persists. I don't think that dimensions are the issue. Box is selectable and correct size, but nothing renders inside it in Android Firefox

**Comment by codeAdrian** [comment]
Hello. Are there any updates on this ticket?

**Comment by Man-0-waR** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1526207

**Comment by ShaMan123** [comment]
Thanks @Man-0-waR

**Comment by codeAdrian** [comment]
Is it okay to close this issue as the bug is still present and fabric might need to be updated once the issue is fixed in Firefox?

**Comment by ShaMan123** [comment]
It is unrelated to fabric so I closed it
