### ISSUE TITLE
Fabric.Path Setting perPixelTargetFind to true will report an error

### ISSUE THREAD

**Issue by joeyer** [fabricjs/fabric.js#8342]
code
![image](https://user-images.githubusercontent.com/11498128/193464418-52f624bf-03d1-49de-8d96-f495f4bde520.png)

chrome browser:
![image](https://user-images.githubusercontent.com/11498128/193464291-42192ce6-7c73-48dc-8c4e-3d3858369c8a.png)

version:5.2.4
Err:
Uncaught TypeError: Cannot read properties of undefined (reading 'x')

**Comment by joeyer** [comment]
When you draw a line on the canvas, you're reporting an error

**Comment by joeyer** [comment]
I tested version 5 and version 4, both have problems, version 3 is OK

**Comment by ShaMan123** [comment]
Did you try setCoords?

**Comment by joeyer** [comment]
@ShaMan123 yes,I Did, Don't work
![image](https://user-images.githubusercontent.com/11498128/193498730-a4955ef4-9829-4ed5-9f3a-2e9994cfb742.png)

**Comment by ShaMan123** [comment]
Please provide a reproduction and another using master

**Comment by ShaMan123** [comment]
BTW are you aware there's an eraser brush?

**Comment by joeyer** [comment]
@ShaMan123 Yeah, it's an eraser, erasing objects, so I need to find the actual location, not the control location

**Comment by joeyer** [comment]
When I set the perPixelTargetFind property, I make a random stroke on the artboard and immediately get an error

**Comment by ShaMan123** [comment]
I am not sure you are aware of the built in eraser from your comments.
http://fabricjs.com/erasing
There's a checkbox that produces similar UX
![image](https://user-images.githubusercontent.com/34343793/195046237-4cf81443-ef1a-4f53-8db8-f40218f2ff8d.png)

Anyways

> Please provide a reproduction and another using master

2 reproductions are **required** for me to look into this issue elsewise I will close it.
