### ISSUE TITLE
Blurry PNG images after zoom

### ISSUE THREAD

**Issue by DavidFucsko** [fabricjs/fabric.js#8343]
## Version

5.2.1

## Test Case

https://jsfiddle.net/szocsyke/kgm6L9b4/1/

## Information about environment
When using zoomToPoint, or any zoom, the PNG images get blurry. 

## Steps To Reproduce

1. Create image from file
2. canvas zoomToPoint

## Expected Behavior
Images are not blured
## Actual Behavior
Images are blured

![blurry](https://user-images.githubusercontent.com/42489885/193478197-180db9fb-d44e-4ac1-af3e-cc6b5e59f0a0.PNG)

![not_blurry](https://user-images.githubusercontent.com/42489885/193478188-d8726064-6a92-4e9a-906f-36392eea78eb.PNG)

**Comment by asturur** [comment]
0.95 is an unfortunate value for zooming on top of that your top/left aren't matching pixels anymore.
Outside that fiddle, wht are you trying to do? Knowing why blurriness worries you may help suggesting a different way to work with fabricjs
