### ISSUE TITLE
[typescript] getObjects return type does not allow to call methods like image.getSrc

### ISSUE THREAD

**Issue by lk77** [fabricjs/fabric.js#8355]
## Version

5.2.4

## Test Case

This is a typescript issue, so there is no test case

## Information about environment

Node js

## Steps To Reproduce

This is the signature of getObjects method :
```
getObjects(type?: string): Object[];
```
see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/29d4592066a1587254230035f5fbb7c5af46ef19/types/fabric/fabric-impl.d.ts#L292 

Methods that are not part of Object can't be used, example with Image.getSrc method :

```
// retrieve images
let images = canvas.getObjects('image');

// typescript will complain about this
images.shift().getSrc();
```

i've tried to cast it :

```
// typescript will refuse to cast because of return type Object[]
let objects: Array<Image> = canvas.getObjects('image');
```

with the following error :

```
Type 'Object' is not assignable to type 'Image'.
        The types returned by 'setControlsVisibility(...)' are incompatible between these types.
          Type 'Object' is missing the following properties from type 'Image': getElement, setElement, removeTexture, dispose, and 8 more
```

## Expected Behavior

Method signature allow for Image and other types that can be returned by getObjects

## Actual Behavior

Method signature only allow base Object type and not Images or other types, which means methods like getSrc can't be called, without using an ugly `@ts-ignore`

# Solution

Modify signature with something like :

```
getObjects(type?: string): Array<Object || Image || ... other possible types ...>
```

thanks

**Comment by ShaMan123** [comment]
That repo should be abandoned...
See #7596

**Comment by lk77** [comment]
@ShaMan123 i read it already, i don't see where you conclude that

**Comment by ShaMan123** [comment]
not this repo, the types...
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62668

**Comment by ShaMan123** [comment]
You are welcome to contribute.
Collection hasn't been migrated yet because of a complication with class properties we haven't agreed on yet.

**Comment by lk77** [comment]
Ah ok thanks i understand
