### ISSUE TITLE
task(): `Point.swap`

### ISSUE THREAD

**Issue by ShaMan123** [fabricjs/fabric.js#8358]
I wanted to use `swap` but then realized it is very different that what I expected.

https://github.com/fabricjs/fabric.js/blob/0830cdb24cc3c2004f3885a40cc1c91542343240/src/point.class.ts#L337

I would expect it to return a new point:
```ts
new Point(a, b).swap() 
// should eq to
new Point(b, a)
```

Any objections?

**Comment by ShaMan123** [comment]
Or we can simply deprecate this odd method

**Comment by asturur** [comment]
did we have swap? what is it used for? which is the utility?

**Comment by ShaMan123** [comment]
Nothing uses it as of now.
I came across it since I wanted to use it in #8344 and then opened this issue.

**Comment by ShaMan123** [comment]
it can be dropped
