### ISSUE TITLE
Polyline/polygon editing breaks when flipped

### ISSUE THREAD

**Issue by graphics-et-al** [fabricjs/fabric.js#8359]
## Version

5.2.4 (also affects earlier versions)

## Test Case

-  [https://codepen.io/graphics-et-al/pen/JjvwNgE](https://codepen.io/graphics-et-al/pen/JjvwNgE)

## Information about environment

Browser: Chrome, Firefox

## Steps To Reproduce

1. Use the code at [http://fabricjs.com/custom-controls-polygon](http://fabricjs.com/custom-controls-polygon) or the fabric-extensions library at [https://github.com/yassilah/fabric-extensions ](https://github.com/yassilah/fabric-extensions )to make an editable polygon or poyline

2. Set either flipX or flipY to 'true' to flip the object
3. Enable polyline editing, drag a point

## Expected Behavior
Dragging point to modify the editable polygon/line

## Actual Behavior
Madness- object randomly repositions in odd ways

**Comment by ShaMan123** [comment]
Will be addressed by complementary work of #8344

**Comment by ShaMan123** [comment]
I guess you never tried skewing.

**Comment by ShaMan123** [comment]
I guess we will make polygon controls part of the source code

**Comment by ShaMan123** [comment]
duplicate #6886

**Comment by graphics-et-al** [comment]
Thanks @ShaMan123 ! Look forward to the results.

If you're interested: I have developed editable curves: see [https://forum.dev.graphicsetal.com/fabricjs/curve.html](https://forum.dev.graphicsetal.com/fabricjs/curve.html)

The limitations in this bug still apply :(

Source is open, have a look :)

**Comment by ShaMan123** [comment]
> If you're interested: I have developed editable curves: see https://forum.dev.graphicsetal.com/fabricjs/curve.html

Great stuff.
Consider contributing to upstream. I think it can be part of it.
