### ISSUE TITLE
How do I make the strokeWidth look inside the existing rectangle instead of increasing the strokeWidth and making it bigger?

### ISSUE THREAD

**Issue by yirandidi** [fabricjs/fabric.js#8360]
## Version

5.0.0

## Test Case

- [ ] [Browser Issue Template](https://jsfiddle.net/Lcp2h3nv/)
- [ ] [Node Issue Template](https://codesandbox.io/s/exciting-browser-ytb701)

## Information about environment

Nodejs or browser?
Which browsers?

## Steps To Reproduce

1.

<details><summary>Error Message & Stack Trace</summary><p>

```txt
<!-- Provide a log message if relevant -->
```

</p></details>

**Comment by yirandidi** [comment]
Let stroke use inside

**Comment by ShaMan123** [comment]
open a discussion
