### ISSUE TITLE
[Bug]: Caching in Firefox just makes worse

### ISSUE THREAD

**Issue by Ch1sKey** [fabricjs/fabric.js#8382]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.2.4

### In What environments are you experiencing the problem?

Firefox

### Link To Reproduction

(SW ⚠️  A lot of moving colorful squares) https://codesandbox.io/s/jovial-tristan-2ztgys

### Steps To Reproduce

1. Use Firefox
2. Open the link
3. Check out the FPS counter 
4. Check "enable caching"

### Expected Behavior

Performance(FPS) is expected to be improved.is 

### Actual Behavior

FPS is dropped down to *50%*

This is surprising, but fabric objects in firefox render slower while being rendered from the cache.
I'm sure this is related to multiple bug reports of the `drawImage` function performance in Firefox. Seems like a bug exists for years and won't be fixed in the nearest future. 

Looks like the orange browser just can't handle the rapid calling of the drawImage procedure on each frame for every object. 
Are there any strategies or ideas on how to deal with caching in FF? Maybe some other caching technic that does not involve so must drawImage invocation?

**Comment by asturur** [comment]
@Ch1sKey can you provide your use case apart drawing many rectangles?
If for some reason caching is behaving bad sometimes is better to not having it as you said.
What is doing your app that is going slow on firefox?

**Comment by Ch1sKey** [comment]
> can you provide your use case apart drawing many rectangles?
> What is doing your app that is going slow on firefox?

Our use case is kind of the same as described. A lot of objects are on canvas, and the user is allowed to move the viewport, which triggers lots of re-renders.
