### ISSUE TITLE
toDatalessJSON doesn't export complex SVGs fills [Bug]: 

### ISSUE THREAD

**Issue by enriqueerrando** [fabricjs/fabric.js#8407]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.2.4

### In What environments are you experiencing the problem?

Firefox, Chrome, Microsoft Edge

### Link To Reproduction

https://codepen.io/enriqueerrando/pen/abKbpBL?editors=1010

### Steps To Reproduce

1. Create canvas
2. Add a complex SVG (with groups and paths) and a simple SVG (just a path)
3. Change the color of any path of both SVGs
4. Save canvas data with toDatalessJSON to a var
5. Load canvas data from that var with loadFromJSON
6. At least on my end, the loaded data does only kept the simple SVG color change, but not the complex one

### Expected Behavior

As far as I know, the advantage of using toDatalessJSON is to keep saved data lighter by replacing the whole SVG code by a reference URL to the original SVG, right?

I expected it to keep color changes too, but I cannot manage it to work.

Is it not supported? Could be an issue of my SVGs config? Does a SVG need to be coded in a particular way?

Thanks in advance!

### Actual Behavior

After applying color changes to complex SVGs (with groups and paths), saving them with toDatalessJSON and load them with loadFromJSON, those color changes are not kept.

**Comment by ShaMan123** [comment]
I think you are correct to assume that
However the logic indeed doesn't update the exported path
You can set that yourself.
https://codepen.io/enriqueerrando/pen/abKbpBL
```ts
canvas.forEachObject(obj=>{
      obj.sourcePath=o.toSVG()
    })
```
This is a bug.

**Comment by ShaMan123** [comment]
actually I am not sure what `sourcePath` is supposed to be.
The word `source` indicates one or the other.

**Comment by enriqueerrando** [comment]
Hi ShaMan123,

I'm not sure that 'source' means one or the other, just that is going to reference a SVG instead of saving the whole SVG data, but despite that the FabricJS documentation doesn't mention any other diference between the two methods. So if one can keep color changes, the other should too. 

There is another issue that mentions something pretty similar but with gradients [#3989](https://github.com/fabricjs/fabric.js/issues/3989). This issue had something to do with pathGroups, which was deprecated because with groups is already possible to achieve the same. But mine is using groups and paths, so I don't understand why isn't working.

Thanks ;)

**Comment by ShaMan123** [comment]
I have found the source for this behavior
It isn't Path it is Group, as you said (PathGroup)
https://github.com/fabricjs/fabric.js/blob/v5.2.4/src/shapes/group.class.js#L570

And in particular this:
If you iterate over each object at this point and set fill/stroke that will fix your issue
https://github.com/fabricjs/fabric.js/blob/c4f80cd9df02fecf24be63760bc464394c9569d9/src/shapes/group.class.js#L574

This is no longer supported in v6
We removed this behavior for good.
And now I understand what it did and why we removed it.

You can impl your own logic for this

**Comment by enriqueerrando** [comment]
Hi @ShaMan123,

First of all, sorry for the delay, I was on vacation last week and had no wifi at all.

Thanks a lot for taking the time to look into my issue.

It's too bad that u removed that feature, but I understand why ;)

**Comment by ShaMan123** [comment]
A vacation w/o wifi sounds a true vacation

**Comment by enriqueerrando** [comment]
Yeah!! It was!! No mobile, no calls or whatsapp, just the nature and us ;)
