### ISSUE TITLE
[Bug]: Download empty SVG for ForceGraph2D output

### ISSUE THREAD

**Issue by irusriAZ** [fabricjs/fabric.js#8429]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.2.4

### In What environments are you experiencing the problem?

Firefox, Chrome, Safari, Opera, Microsoft Edge

### Node Version (if applicable)

18.11.0

### Link To Reproduction

Export empty SVG output

### Steps To Reproduce

1. Initialise and add data into the React ForceGraph2D  network
```<button onClick={() => { handleCanvasButtonClick(fgRef);}}> Download SVG </button>
<ForceGraph2D ref={fgRef}  ...
```
2. Then download the SVG using fabricJS
```const options = {  };
let canvas = document.querySelector(".force-graph-container canvas");
let context = canvas.getContext("2d");
const fabricCanvas = new fabric.Canvas(context.current, options);
console.log(fabricCanvas.toSVG())
```   

3. This return an empty SVG

### Expected Behavior

We need to get the full canvas SVG

### Actual Behavior

Just an empty SVG
```

<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="300" height="150" viewBox="0 0 300 150" xml:space="preserve">
<desc>Created with Fabric.js 5.2.4</desc>
<defs>
</defs>
</svg>
```

**Comment by ShaMan123** [comment]
no reproduction

**Comment by irusriAZ** [comment]
Here is an example of the reproduction. Thanks for the quick reply.
https://codesandbox.io/s/react-force-graph-test-forked-bj6w2x?file=/src/App.js

**Comment by ShaMan123** [comment]
It seems you are not drawing anything on it.
How can the canvas be aware of what you are doing somewhere else??

**Comment by irusriAZ** [comment]
Thanks for the quick reply. I am trying to generate the SVG by using `fabriCanvas.toSVG()` method. But it gives me an empty SVG. Did I do anything wrong?

**Comment by ShaMan123** [comment]
You are not doing anything with the canvas so it is empty

**Comment by irusriAZ** [comment]
I thought I am accessing the canvas generated by the ForceGraph2d. If I am doing how can I easily access the canvas from ForceGraph2d and export it as SVG using fabricJS. Appreciate if you could provide some example. Thanks
