### ISSUE TITLE
[Bug]: custom render on Textbox for ml and mr controls being ignored

### ISSUE THREAD

**Issue by Ragers** [fabricjs/fabric.js#8435]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.2.4

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

18.9.1

### Link To Reproduction

Fabric text shapes ignores ml and mr render over-rides

### Steps To Reproduce

set the prototypes for ML and MR controls to render nothing:
```
fabric.Object.prototype.controls.ml.render = () => {};
fabric.Object.prototype.controls.mr.render = () => {};
```

### Expected Behavior

For any other control this works fine on the Textbox, I-Text, Text, it is just being ignored on ml and mr for some reason.
Al other shapes, they respect this render (to render nothing) for ALL controls including ml and mr rendering and works as expected.

Textbox, I-Text and Text does not respect:

`fabric.Object.prototype.controls.ml.render `

### Actual Behavior

due to sensitivity of the work being done I am not able to share screenshots, actual behaviour is that fabric still renders the rectangle on the ml and mr for Textbox, I-Text and Text shapes although it should not.

### Error Message & Stack Trace

```bash
no, errors being logged, just straight up ignores my over-ride
```

**Comment by iocoker** [comment]
For some reasons, you have to explicitly set it on the text prototype:

`fabric.Textbox.prototype.controls.ml.render = () => {}`
`fabric.Textbox.prototype.controls.mr.render = () => {}`

Perhaps this??
https://github.com/fabricjs/fabric.js/blob/a0bb500e460ca0087cadf1038f1d193c2ff3a4d1/src/controls/default_controls.ts#L119-L123

**Comment by Ragers** [comment]
> `fabric.Textbox.prototype.controls.ml.render = () => {}`
> `fabric.Textbox.prototype.controls.mr.render = () => {}`

indeed... this does work.. interesting. thanks for the clarification
