### ISSUE TITLE
[Bug]: textboxes move to the right when using canvas.toSVG(...). Using JSON to save and load, all OK. 

### ISSUE THREAD

**Issue by Milner99** [fabricjs/fabric.js#8439]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.2.4

### In What environments are you experiencing the problem?

Firefox, Chrome, Safari, Microsoft Edge

### Link To Reproduction

https://jsfiddle.net/Milner99/fe7ksvb9/3/

### Steps To Reproduce

1. Add textbox to canvas
2. Call canvas.toSVG(..) <-- with parameters within example
3. Examine the output SVG (either in console or as file)
4. Text will not be in the same position

### Expected Behavior

I would expect the text to stay in the same relative position to the canvas.

### Actual Behavior

Text seems to move to the right

**Comment by mostafasalloumm** [comment]
hello did you find any solution
>?

**Comment by Milner99** [comment]
No I have not yet. Are you experiencing a similar issue @mostafasalloumm ?

**Comment by Milner99** [comment]
Nice addition. I will see if that helps me. Thank you :0) 

Ultimately though of course, I feel this functionality shouldn't be required as this is possibly a bug on the toSVG routine. Be good to get an official comment on this and see if a resolution can be added to the roadmap for a future version of fabricjs (not to far away ideally lol!)

**Comment by ShaMan123** [comment]
please revise the repro so the output is visible w/o any effort

**Comment by Milner99** [comment]
An approx timeline could be very useful. Happy to provide as many code samples as required to get this resolved. It's a blocker for my project.

**Comment by ShaMan123** [comment]
**I didn't see you revised the repro.**

#8420 has been merged, #8421 will be merged soon enough. 
I will then port this PR and related ones.
And then you can promote a fix.
I can back you

**Comment by asturur** [comment]
hi @Milner99 i updated your fillder
https://jsfiddle.net/0xoaer3y/6/

The text moves to the right because you are fiddling with the svg viewport and is behaving as expect.
You are constraining the SVG to count the space of the first 480px in width and height, while the canvas is 600px.
At that point a piece of your canvas in the svg gets cropped out and it seems that it moved, while is still at the correct position.

**Comment by asturur** [comment]
<img width="647" alt="image" src="https://user-images.githubusercontent.com/1194048/202895890-8b9bb477-e8ec-451f-8ca2-8b1a317baf38.png">

if you see a clearer example you will realize is not moved, is cropped, exactly what the viewBox is meant to do.
