### ISSUE TITLE
[Feature]: Add optional background removal toCanvasElement 

### ISSUE THREAD

**Issue by dfvgbh86** [fabricjs/fabric.js#8442]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

Hi, we are using your library for colocation on the board and would like to remove the background for the mini map. So we suggest adding a third parameter toCanvasElement. Which will specify whether to make the canvas without or with a background.
For example, the final set of parameters will look like this:
toCanvasElement(multiplier, cropping = {}, withBackground = true)
<img width="516" alt="image" src="https://user-images.githubusercontent.com/58677110/202202496-42c27222-6a14-4bd4-8e0d-d6ed4ac60640.png">

### Current State

Now you can do this only with a monkey patching of the original toCanvasElement, which is not very nice and elegant

**Comment by ShaMan123** [comment]
- It can be part of the second arg
- You are welcome to PR
- You can create a wrapper around the method, removing and adding the background once you are done.

**Comment by asturur** [comment]
Hi @dfvgbh86 , i think the easiest solution since toCanvasElement is syncronous is to just toggle the visibility of the background to false before exporting and but it back to true.
Is exactly what we would do with said option
