### ISSUE TITLE
[Bug]: FabricJS does not work with NextJS 13 and the new appDir

### ISSUE THREAD

**Issue by HMilbradt** [fabricjs/fabric.js#8444]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.2.4

### In What environments are you experiencing the problem?

Node.js

### Node Version (if applicable)

16.14.2

### Link To Reproduction

https://github.com/HMilbradt/next-13-fabric

### Steps To Reproduce

1. yarn install
2. yarn dev 
3. http://localhost:3000

Note that I've just used the Next13 playground example.  The only relevant files are `/app/page.tsx` and `/app/dynamic-fabric.tsx`.

Completely removing the import for `/app/dynamic-fabric.tsx` will allow the app to run properly.

### Expected Behavior

The app should be able to load, if not normally then at least using the NextJS dynamic component with SSR turned off.

### Actual Behavior

The app refuses to load, as server rendering fails due to the Node canvas files being loaded.

I've opened a report on NextJS as well here https://github.com/vercel/next.js/issues/43050.  Not sure if this issue is entirely on that framework, or it's now an issue that needs to be addressed in Fabric.

For the time being, I will likely be forking fabric and removing the NodeJS code.  

### Error Message & Stack Trace

```bash
error - ./node_modules/canvas/build/Release/canvas.node
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```
```

**Comment by ShaMan123** [comment]
#8208
duplicate #8258

If you think I should reopen comment

**Comment by ShaMan123** [comment]
specifically https://github.com/fabricjs/fabric.js/commit/30f5a0451e80388e663bc51cd909f0a3da666159

**Comment by asturur** [comment]
@HMilbradt to avoid those issues fabric gets published in 2 versions

<img width="810" alt="image" src="https://user-images.githubusercontent.com/1194048/202905836-7e5d725f-33a0-4dbc-84b5-d5a816d54eaa.png">

https://www.npmjs.com/package/fabric?activeTab=versions

Please try the version 5.2.4-browser you shouldn't have any node-canvas code.

Alternatively you have to stub out the node dependencies, but i have an example for webpack and i m not sure the latest next.js what is using.

**Comment by lmachens** [comment]
@asturur 

I tried 5.2.4-browser, but this leads to another error:

``` 
./node_modules/fabric/dist/fabric.js:24:0
Module not found: Can't resolve 'jsdom'
``` 

Dynamically importing fabric or the component doesn't help too.
Do you have another idea?

**Comment by ShaMan123** [comment]
What I suggested works in next 12
I didn't try next 13, 
https://beta.nextjs.org/docs/rendering/server-and-client-components#keeping-server-only-code-out-of-client-components-poisoning
https://beta.nextjs.org/docs/rendering/server-and-client-components#convention

Next stuff is enough to resolve this issue

**Comment by lmachens** [comment]
@ShaMan123 

Thx, I was trying out several things (except patching fabric.js).

`use client` is already added. I tried to dynamically import `fabric`, but I have the same issue like in:
https://github.com/vercel/next.js/issues/43050

Same issues with [`serverComponentsExternalPackages` ](https://beta.nextjs.org/docs/api-reference/next.config.js#servercomponentsexternalpackages).

Still no luck.

**Comment by ShaMan123** [comment]
Using dynamic in next 12 works, but it must import a component so that is annoying but doable

**Comment by lmachens** [comment]
This discussion is helpful:
https://github.com/vercel/next.js/discussions/42319

But the main difference between fabric.js and other libraries like leaflet is, that fabric assumes it can be running on Node:
https://github.com/fabricjs/fabric.js/blob/391eb998ba87b0f5c183c7e58712e0cc15f68f48/HEADER.js#L34
The server is trying to bundle/pack fabric.js, but thinks it's required to bundle jsdom/canvas too.
This was changed in Next 13.

I think the best solution is to remove the Node related code for the `-browser` releases.

**Comment by ShaMan123** [comment]
That is inaccurate.
At the moment fabric guesses the environment once imported.
And in ssr it fails because it doesn't guess at the right time. 
We are going to address this in v6. And stop guessing altogether hopefully.

**Comment by lmachens** [comment]
I patched the HEADER.js and removed the `else`. This solves my issue, because it allows me to import `fabric`  in my components, without the need of dynamic import or similar.
And I am already using `-browser` tag.
https://github.com/fabricjs/fabric.js/blob/391eb998ba87b0f5c183c7e58712e0cc15f68f48/HEADER.js#L32-L52

Maybe this helps others until you address this in v6. 
Thx and good job! Looking forward to test it.

**Comment by ShaMan123** [comment]
I don't know how you use fabric but I would expect you'd encounter fabric.window, fabric.document is undefined errors

**Comment by lmachens** [comment]
No it's fine. After rendering my React component , I initialize it, which is only run on client side.

**Comment by ShaMan123** [comment]
Awesome.
So it is the next bundling logic perhaps

**Comment by ShaMan123** [comment]
Update
#8632 should fix SSR out of the box

**Comment by ZhengRui** [comment]
Is there a way to get fabricjs v5 work with Nextjs 13, without using dynamic import? I am able to get it work using dynamic import but it encrease the loading time significantly and causing other issues. I tried to use fabric@5.3.0-browser, but it has  `Can not resolve 'canvas'` issue. I tried to remove `else` part in `HEADER.js` as mentioned above, but it didn't help. 

Really hope there could be a classrification on this issue, I've been baning head on this issue for two weeks. And none of discussions about this issue provides a clear solution.

**Comment by ShaMan123** [comment]
We made v6 SSR resilient.
V5 isn't.
If you must work on v5 look at the SSR support pr and follow it.

**Comment by ZhengRui** [comment]
thanks for clarification @ShaMan123 , will adapt my code to v6 then

**Comment by adarsh-drishya** [comment]
is there any way i could skip installing jsdom and canvas , it mentions it as required dep but since i am working in browser in react frontend project. i dont want to install canvas and jsdom

**Comment by asturur** [comment]
5.3.0-browser has this package.json

https://www.npmjs.com/package/fabric/v/5.3.0-browser?activeTab=code

with no dependencies.
How is that you are installing them?

Are you sure those aren't stuck in your yarn.lock or package.lock files from previous attemptes?

**Comment by ShaMan123** [comment]
I will repeat myself.
Using SSR is possible only in v6
v5 will assume you are in node and import the deps

**Comment by asturur** [comment]
yes that i know, but i was oh i was answering the part in which @adarsh-drishya doesn't want to install the deps on 5.3.0, seems unrelated to the original question.
He is using react ( not nextjs ).
