### ISSUE TITLE
[Bug]: Image in v.5.1.0 loads incorrectly compared to v1.5.0

### ISSUE THREAD

**Issue by noctivityinc** [fabricjs/fabric.js#8456]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.1.0

### In What environments are you experiencing the problem?

Chrome

### Link To Reproduction

https://jsfiddle.net/wecora/vukoy4c0/6/

### Steps To Reproduce

1. Load the JSON below using version 1.5.0.  Works fine. (fiddle: https://jsfiddle.net/wecora/tqdu3xca/1/)
2. Load the same JSON using version 5.1.0.  Scaling is all off.  Same object. (fiddle: https://jsfiddle.net/wecora/vukoy4c0/6/)

var obj = {
    "type": "group",
    "version": "5.1.0",
    "originX": "left",
    "originY": "top",
    "left": 378.13,
    "top": 418.24,
    "width": 171.13,
    "height": 171.13,
    "fill": "rgb(0,0,0)",
    "stroke": null,
    "strokeWidth": 1,
    "strokeDashArray": null,
    "strokeLineCap": "butt",
    "strokeDashOffset": 0,
    "strokeLineJoin": "miter",
    "strokeUniform": false,
    "strokeMiterLimit": 10,
    "scaleX": 1,
    "scaleY": 1,
    "angle": 0,
    "flipX": false,
    "flipY": false,
    "opacity": 1,
    "shadow": null,
    "visible": true,
    "backgroundColor": "",
    "fillRule": "nonzero",
    "paintFirst": "fill",
    "globalCompositeOperation": "source-over",
    "skewX": 0,
    "skewY": 0,
    "objects": [
        {
            "type": "image",
            "version": "5.1.0",
            "originX": "left",
            "originY": "bottom",
            "left": -68.06,
            "top": 68.06,
            "width": 147.63,
            "height": 147.63,
            "fill": "rgb(0,0,0)",
            "stroke": "#f0eee4",
            "strokeWidth": 1,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeDashOffset": 0,
            "strokeLineJoin": "miter",
            "strokeUniform": false,
            "strokeMiterLimit": 10,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": {
                "color": "rgba(50, 50, 50, 0.5)",
                "blur": 2,
                "offsetX": 0,
                "offsetY": 2,
                "affectStroke": false,
                "nonScaling": false
            },
            "visible": true,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "paintFirst": "fill",
            "globalCompositeOperation": "source-over",
            "skewX": 0,
            "skewY": 0,
            "cropX": 0,
            "cropY": 0,
            "src": "https://cdn-production.wecora.com/items/media/000/036/081/large/open-uri20140519-29182-1p9q36w",
            "crossOrigin": "anonymous",
            "filters": []
        },
        {
            "type": "circle",
            "version": "5.1.0",
            "originX": "center",
            "originY": "center",
            "left": -68.06,
            "top": 68.06,
            "width": 24,
            "height": 24,
            "fill": "rgb(255,255,255)",
            "stroke": "#dddddd",
            "strokeWidth": 1,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeDashOffset": 0,
            "strokeLineJoin": "miter",
            "strokeUniform": false,
            "strokeMiterLimit": 10,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": false,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "paintFirst": "fill",
            "globalCompositeOperation": "source-over",
            "skewX": 0,
            "skewY": 0,
            "radius": 12,
            "startAngle": 0,
            "endAngle": 6.283185307179586
        },
        {
            "type": "text",
            "version": "5.1.0",
            "originX": "center",
            "originY": "center",
            "left": -68.06,
            "top": 68.06,
            "width": 6.82,
            "height": 13.56,
            "fill": "#272822",
            "stroke": null,
            "strokeWidth": 1,
            "strokeDashArray": null,
            "strokeLineCap": "butt",
            "strokeDashOffset": 0,
            "strokeLineJoin": "miter",
            "strokeUniform": false,
            "strokeMiterLimit": 10,
            "scaleX": 1,
            "scaleY": 1,
            "angle": 0,
            "flipX": false,
            "flipY": false,
            "opacity": 1,
            "shadow": null,
            "visible": false,
            "backgroundColor": "",
            "fillRule": "nonzero",
            "paintFirst": "fill",
            "globalCompositeOperation": "source-over",
            "skewX": 0,
            "skewY": 0,
            "fontFamily": "Roboto",
            "fontWeight": "normal",
            "fontSize": 12,
            "text": "E",
            "underline": false,
            "overline": false,
            "linethrough": false,
            "textAlign": "left",
            "fontStyle": "",
            "lineHeight": 1,
            "textBackgroundColor": "",
            "charSpacing": 0,
            "styles": {},
            "direction": "ltr",
            "path": null,
            "pathStartOffset": 0,
            "pathSide": "left",
            "pathAlign": "baseline"
        }
    ],
    "metatype": "imageGroup",
    "url": "/ideas/51999",
    "id": 51999,
    "item_id": 36081
};

### Expected Behavior

The object should load correctly in version 5.1.0.

### Actual Behavior

It appears that the group is fine but the image is not scaled properly to the dimensions:

https://jsfiddle.net/wecora/vukoy4c0/6/

### Error Message & Stack Trace

```bash
none with version 5.1.0
```

**Comment by asturur** [comment]
1.5.0 was around 2015, a lot of things have changed.
There are some migration guides to update your old JSON saves to newer versions.
I think the biggest one is that before width and height were determining the size of the image like a rect.
Then at some point we changed it to accomodate cropping, so that you have to convert your old width/height in a scale factor. Compare your json width/height for the image to the image element native width and height, then apply the ration as a scale factor.

**Comment by asturur** [comment]
Look at this page: http://fabricjs.com/v2-breaking-changes
There is a section dedicated to image that also provide you a compatibility fromObject function

**Comment by noctivityinc** [comment]
That worked!!  Thank you.

Best,

Josh
