### ISSUE TITLE
[Bug]: selection:updated not returning all object if Shift + click is used

### ISSUE THREAD

**Issue by naydenovAnton** [fabricjs/fabric.js#8495]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.2.4

### Node Version (if applicable)

None

### Link To Reproduction

http://fabricjs.com/events

### Steps To Reproduce

1. Select object
2. Select second one with shift + click
3. Observe log. Only one object is added to array. 

If selection is made with mouse all elements was returned. 

### Expected Behavior

To return all elements

### Actual Behavior

Only one element is returned

**Comment by ShaMan123** [comment]
This is intentional.
The `selected`/`deselected` values contain the added/removed objects
