### ISSUE TITLE
How to use Custom Build file in angular project?

### ISSUE THREAD

**Issue by Saqib92** [fabricjs/fabric.js#8535]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

I want to use Eraser in my Angular Project, I am creating Custom build file `fabric.min.js` how can i use this file in my angular project?
Adding this file to angular.json to load is not working.

### Current State

Not Compiling

**Comment by Saqib92** [comment]
Issue fixed by update import statement on editor Page:

Before (when using npm package):
```
import 'fabric';
declare const fabric: any;
```
After (using custom build file imported in angular.json file): 
```
import 'fabric' // removed this line
declare const fabric: any;
```

**Comment by ShaMan123** [comment]
eraser has moved to https://github.com/ShaMan123/erase2d

**Comment by vc-vraj** [comment]
Hello @Saqib92, leveraging Fabric.js in my Angular project, encountered any production build errors?

**Comment by Saqib92** [comment]
> Hello @Saqib92, I'm using custom build of Fabric.js in my Angular project, encountered any production build errors?

No, it is working perfectly fine. Check you are including files properly. Also check error logs.

**Comment by vc-vraj** [comment]
@Saqib92, Thank you for the prompt response. Could you please share how you managed TypeScript support with your custom build of Fabric.js? Any specific configurations or steps you followed would be greatly appreciated.

**Comment by Saqib92** [comment]
> @Saqib92, Thank you for the prompt response. Could you please share how you managed TypeScript support with your custom build of Fabric.js? Any specific configurations or steps you followed would be greatly appreciated.

this is how i am using fabricjs in my angular project:

https://github.com/Saqib92/ionic-fabricjs-editor

this is demo project. 

i added fabric file in my angular.json.

**Comment by vc-kevin** [comment]
@Saqib92 I have reviewed your code and noticed that TypeScript isn't utilized as expected, with the `any` type being used extensively. If you have any insights or steps on how to properly integrate TypeScript support using a `custom.d.ts` file for type definitions, I would greatly appreciate your guidance.

**Comment by vc-kevin** [comment]
> > @Saqib92, Thank you for the prompt response. Could you please share how you managed TypeScript support with your custom build of Fabric.js? Any specific configurations or steps you followed would be greatly appreciated.
> 
> this is how i am using fabricjs in my angular project:
> 
> https://github.com/Saqib92/ionic-fabricjs-editor
> 
> this is demo project.
> 
> i added fabric file in my angular.json.

@Saqib92  I have reviewed your code and noticed that TypeScript isn't utilized as expected, with the `any` type being used extensively. If you have any insights or steps on how to properly integrate TypeScript support using a `custom.d.ts` file for type definitions, I would greatly appreciate your guidance.

**Comment by Saqib92** [comment]
> properly integr

Version below 6 is not typescript supported. TypeScript support added in v6+ 
Please check documentation.

**Comment by Saqib92** [comment]
> > > @Saqib92, Thank you for the prompt response. Could you please share how you managed TypeScript support with your custom build of Fabric.js? Any specific configurations or steps you followed would be greatly appreciated.
> > 
> > 
> > this is how i am using fabricjs in my angular project:
> > https://github.com/Saqib92/ionic-fabricjs-editor
> > this is demo project.
> > i added fabric file in my angular.json.
> 
> @Saqib92 I have reviewed your code and noticed that TypeScript isn't utilized as expected, with the `any` type being used extensively. If you have any insights or steps on how to properly integrate TypeScript support using a `custom.d.ts` file for type definitions, I would greatly appreciate your guidance.

Version below 6 is not typescript supported. TypeScript support added in v6+
Please check documentation.
