### ISSUE TITLE
Custom Control in Polyline is not working as desired

### ISSUE THREAD

**Issue by kartiksolanki** [fabricjs/fabric.js#8541]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.0.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://codepen.io/pen?editors=0010

### Steps To Reproduce

I am trying to implement custom controls for polyline object in Fabric.js. I am taking the reference for the control from one of their demo for polygon as found here: http://fabricjs.com/custom-controls-polygon

I am new to the fabric js and trying to understand how can I define the custom control inside my Angular app. So far I have tried structuring the code as below:
```
constructor () {
fabric.Object.prototype.addControlPoints = function() {
      var lastControl = this.points.length - 1;
      this.cornerStyle = 'circle';
      this.cornerColor = 'rgba(255,255,255,1)';
      this.cornerSize = 12;
      this.cornerStrokeColor = 'rgba(255,255,255,1)';
      this.controls = this.points.reduce(function(acc, point, index) {
        acc['p' + index] = new fabric.Control({
          positionHandler: polygonPositionHandler,
          actionHandler: anchorWrapper(index > 0 ? index - 1 : lastControl, actionHandler),
          actionName: 'modifyPolygon',
          pointIndex: index
        });
        return acc;
      }, { });
      console.log("Done")
    };

    function polygonPositionHandler(dim, finalMatrix, fabricObject) {
      var x = (fabricObject.points[this.pointIndex].x - fabricObject.pathOffset.x),
          y = (fabricObject.points[this.pointIndex].y - fabricObject.pathOffset.y);
      return fabric.util.transformPoint(
        { x: x, y: y },
        fabric.util.multiplyTransformMatrices(
          fabricObject.canvas.viewportTransform,
          fabricObject.calcTransformMatrix()
        )
      );
    }

    function getObjectSizeWithStroke(object) {
      var stroke = new fabric.Point(
        object.strokeUniform ? 1 / object.scaleX : 1, 
        object.strokeUniform ? 1 / object.scaleY : 1
      ).multiply(object.strokeWidth);
      return new fabric.Point(object.width + stroke.x, object.height + stroke.y);
    }

    function actionHandler(eventData, transform, x, y) {
      var polygon = transform.target,
          currentControl = polygon.controls[polygon.__corner],
          mouseLocalPosition = polygon.toLocalPoint(new fabric.Point(x, y), 'center', 'center'),
          polygonBaseSize = getObjectSizeWithStroke(polygon),
          size = polygon._getTransformedDimensions(0, 0),
          finalPointPosition = {
            x: mouseLocalPosition.x * polygonBaseSize.x / size.x + polygon.pathOffset.x,
            y: mouseLocalPosition.y * polygonBaseSize.y / size.y + polygon.pathOffset.y
          };
      polygon.points[currentControl.pointIndex] = finalPointPosition;
      return true;
    }

    function anchorWrapper(anchorIndex, fn) {
      return function(eventData, transform, x, y) {
        var fabricObject = transform.target,
            absolutePoint = fabric.util.transformPoint({
                x: (fabricObject.points[anchorIndex].x - fabricObject.pathOffset.x),
                y: (fabricObject.points[anchorIndex].y - fabricObject.pathOffset.y),
            }, fabricObject.calcTransformMatrix()),
            actionPerformed = fn(eventData, transform, x, y),
            newDim = fabricObject._setPositionDimensions({}),
            polygonBaseSize = getObjectSizeWithStroke(fabricObject),
            newX = (fabricObject.points[anchorIndex].x - fabricObject.pathOffset.x) / polygonBaseSize.x,
            newY = (fabricObject.points[anchorIndex].y - fabricObject.pathOffset.y) / polygonBaseSize.y;
        fabricObject.setPositionByOrigin(absolutePoint, newX + 0.5, newY + 0.5);
        return actionPerformed;
      }
    }
}

addPolyLine() {
    var poly = new fabric.Polyline(points, {
      strokeWidth: 2,
      fill: '',
      stroke: 'red',
      originX: 'center',
      originY: 'center',
      hasRotatingPoint: false,
      selection: true,
      hasBorders: false,
      hasControls: true,
      perPixelTargetFind: true,
      lockUniScaling: true,
      cornerColor: '#FFF',
      cornerSize: 10,
      cornerStyle: 'circle',
      lockMovementX: true,
      lockMovementY: true,
      lockScalingX: true,
      lockScalingY: true,
      hidden: false
    });
    this.canvas.selection = false;
    
    poly.addControlPoints();  // <----- THIS IS WHERE I AM APPLYING THE CUSTOM CONTROL
    
    this.canvas.add(poly);
    
    this.canvas.sendToBack(poly);
    
    poly.setCoords();
    
    this.canvas.renderAll();
  }
```

The problem I am facing is whenever I draw the polyline, the controls are not showing but after drawing when I click on the polyline, the controls appear. Any idea how can I show the controls upon polyline draw ????? Is the structuring of my custom control correct ??? Please help. The codepen attached is the Polygon version as shown in demo using JS. I am using Angular.

### Expected Behavior

Custom controls should appear upon polyline add to the canvas.

### Actual Behavior

Custom controls are appearing after polyline add and after selecting that polyline.

**Comment by asturur** [comment]
Hi @kartiksolanki , there is not exactly a polyline `draw`.
You can add an object to your canvas and you can select them.
By default controls are drawn only on ONE selected object at a time.

So in this case when you add the object to the canvas, you can also add it as activeObject using  this.canvas.setActiveObject(poly)

I'm sure you will find more edge cases when working with polygon editing, please provide a fiddle/codepen when that happens and do not link an empty one.
