### ISSUE TITLE
[Bug]: Sometime cannot load image from base64

### ISSUE THREAD

**Issue by huy-lv** [fabricjs/fabric.js#8555]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

14.19.3

### Link To Reproduction

https://jsfiddle.net/huylv177/62rwofk5/12/

### Steps To Reproduce

1. I use fabric.Image.fromURL(base64) to add image to canvas, but sometime its show empty page. I logged callback from fromURL function below:
- When website show empty canvas
<img width="808" alt="image" src="https://user-images.githubusercontent.com/7688070/210175638-5b9f8b47-d717-425d-add5-83b03f73b69a.png">

- When website show correct image
<img width="800" alt="image" src="https://user-images.githubusercontent.com/7688070/210175678-d8ae2ec6-b445-42cc-9e1f-fb7cf267bb20.png">

### Expected Behavior

Show correct image

### Actual Behavior

Show nothing

**Comment by ShaMan123** [comment]
I can reproduce but not sure what is going on.
Workaround: https://jsfiddle.net/g2h6mn41/

**Comment by melchiar** [comment]
@huy-lv you're referencing the base64 variable before you've defined it

https://jsfiddle.net/melchiar/65jecvxt/
