### ISSUE TITLE
[Bug]: New group object's position changes just before dragging

### ISSUE THREAD

**Issue by iocoker** [fabricjs/fabric.js#8562]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

current master

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

http://jsfiddle.net/2c3a8w9n/29/

### Steps To Reproduce

Mousedown on any of the objects, then drag to reposition. You will observe the item jumps to a large negative left / top and off the screen. You will have to drag down and right to view it again.

JS Fiddle: http://jsfiddle.net/2c3a8w9n/29/

Here's sample video:

https://user-images.githubusercontent.com/81635623/210308847-35be8c2b-94fc-4359-8588-c0df2916db00.mp4

### Expected Behavior

Maintain its initial position

### Actual Behavior

Provided above in steps

### Error Message & Stack Trace

```bash
This uses the current Fabricjs master 6
```

**Comment by ShaMan123** [comment]
Another great catch!
https://codesandbox.io/s/custom-control-poly-fix-flip-forked-97y0be?file=/src/index.js

**Comment by iocoker** [comment]
Thank you @ShaMan123 🙏 I think, it affected the scaling of items.

Try resizing any of the shapes or text inside the group:
https://codesandbox.io/s/custom-control-poly-fix-flip-forked-97y0be?file=/src/index.js

https://user-images.githubusercontent.com/81635623/210316037-8e72e08f-c2d5-4bba-8511-f7764d223a46.mp4

**Comment by ShaMan123** [comment]
I just noticed that I didn't fix it
I am investigating

**Comment by ShaMan123** [comment]
try now

**Comment by iocoker** [comment]
Works fine now. Thanks!

**Comment by ShaMan123** [comment]
Great
