### ISSUE TITLE
[Bug]: iText.selectAll() doesn't work if called in "editing:entered" handler

### ISSUE THREAD

**Issue by sunsetninja** [fabricjs/fabric.js#8566]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/s/elated-jones-uo3b5q?file=/src/index.js

### Steps To Reproduce

1. Create an `iText` object
2. Add a listener on `"editing:entered"` event, in which do `this.selectAll()`
3. Start editing the `iText` object by double click on it

### Expected Behavior

Whole text should be selected

### Actual Behavior

Only one word is selected (but `this.getSelectedText()` returns the whole text)

**Comment by sunsetninja** [comment]
for me it works only if I make dblick really slow

https://user-images.githubusercontent.com/13559663/210574701-2efc78fb-2a9d-4839-8788-8fcdb35a35cc.mov

**Comment by ShaMan123** [comment]
enter editing happens after another click is received on the active object.
It is a question of UX. That is how it is defined by fabric.
Seems you want something else.
You can use `setActiveObject` and then on click wil do the job, or subscribe to `selected` and call `enterEditing`
