### ISSUE TITLE
[Bug]: fill attribute always undefined when import from SVG

### ISSUE THREAD

**Issue by annibuliful** [fabricjs/fabric.js#8570]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

import svg file

### Steps To Reproduce

1. use this file
![test-fit-template](https://user-images.githubusercontent.com/5283709/210952284-099d8189-773c-4f43-9977-d33531774224.svg)
3. call `loadSVGFromURL` to load SVG file

### Expected Behavior

imported SVG paths must have fill attribute.

### Actual Behavior

<img width="1512" alt="Screenshot 2566-01-06 at 14 30 32" src="https://user-images.githubusercontent.com/5283709/210952188-4e4c272c-b3c1-4894-8d2e-9b0e411488e1.png">

**Comment by ShaMan123** [comment]
provide a link to a repro and I will reopen

**Comment by annibuliful** [comment]
It works now, I did something wrong when set some metadata for each path.

<img width="1313" alt="Screenshot 2566-01-06 at 20 30 57" src="https://user-images.githubusercontent.com/5283709/211022198-8aac7d9d-5983-48b5-bf11-aaa0072ffb77.png">
