### ISSUE TITLE
Moving object programmatically doesn't update the upper canvas

### ISSUE THREAD

**Issue by MeLight** [fabricjs/fabric.js#858]
When moving an object through code, like this:

```
object.left += 100;
canvas.renderAll();
```

it will move the object, but it's activation box (the place which reacts to click, drags etc) remains in the location where it was last active place.

A plunkr: http://plnkr.co/edit/y4ekCjabR9494RFG6TD4?p=preview

**Comment by AnurajRicky** [comment]
activeSelection coords not updating while changing the object position. 


`key('left', function (e) {  
                let activeObject = canvasFabric.getActiveObjects();  
                if(activeObject.length !== 0){
                    e.preventDefault();
                    activeObject.forEach(function (object) {
                        object.left -= 5; 
                        object.setCoords(); 
                        canvasFabric.renderAll();
                    });
                  }               
            });`
