### ISSUE TITLE
[Bug]: Canvas created inside the class by new fabric.Canvas(id), missing the zoom function

### ISSUE THREAD

**Issue by mrzhouxl** [fabricjs/fabric.js#8592]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

4.6.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/s/autumn-field-xzewvd

### Steps To Reproduce

1. Create class
```
import { fabric } from "fabric";

export class EditScene {
  init() {
    const canvas = new fabric.Canvas("canvas");
    // this.canvas.setHeight(600);
    // this.canvas.setWidth(300);
    const rect = new fabric.Rect({
      width: 200,
      height: 100,
      fill: "#FF4D4F",
      stroke: "#dedede",
      selectable: true
    });
    canvas.add(rect);
  }
}
```
2.Use inside vue
```
<template>
  <div style="display: flex">
    <canvas id="canvas" style="border: 1px solid #ccc"></canvas>
  </div>
</template>

<script setup>
import { onMounted, ref, nextTick } from "vue";
import { EditScene } from "./editScene";
import { fabric } from "fabric";
  nextTick(() => {
    edit.value = new EditScene();
    edit.value.init();
  });
};

onMounted(() => {
  init();
});
</script>

<style lang="scss" scoped>
</style>
```
The created canvas lacks functions such as zooming in

if this
```
    const c1 = new fabric.Canvas("canvas");
    edit.value = new EditScene();
    edit.value.init(c1);
```
Get it on the outside and pass it in (normal)

### Expected Behavior

I hope it will work properly inside the class

### Actual Behavior

![image](https://user-images.githubusercontent.com/44352991/212060209-88b39e65-3134-4430-91cf-b7c2309a66ff.png)

No action box

**Comment by mrzhouxl** [comment]
> Can you check if this is your issue? [#7012 (comment)](https://github.com/fabricjs/fabric.js/issues/7012#issuecomment-818363453)
Thanks, I solved my problem.

**Comment by asturur** [comment]
related to #7012
