### ISSUE TITLE
[Feature]: There should be an option to auto delete an object. 

### ISSUE THREAD

**Issue by Saqib92** [fabricjs/fabric.js#8596]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

There Should be an option to pass on objects to get deleted automatically!!
something like:
`autoDelete: true` // if true Time out will take effect. 
`autoDeleteTimeOut: 5000` // gets deleted after 5 seconds.

```
let img = new fabric.Image(imag, { //initializing the fabric image.
  top: e.layerY - 20 || y - 10,
  left: e.layerX - 20 || x - 10,
  hasControls: false,
  erasable: false,
  id: data,
  autoDelete: true, // enable auto delete of object
  autoDeleteTimeOut: 5000  // this can delete object after 5 seconds.
});
```
By default `autoDelete` will be false.

### Current State

Current solution is have added these options manually and Checking if they exists inside `setInterval()`. which i doubt if i have many objects this will become performance issue.

**Comment by melchiar** [comment]
Thanks for posting! 

This type of specialized behavior is best left to the app though. There's far too many possible ways a dev might want to implement something like this to make it a native feature.
