### ISSUE TITLE
[Bug]: I am trying to deserialize canvas with custom class in angular

### ISSUE THREAD

**Issue by zmiju** [fabricjs/fabric.js#8634]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://angular-mzoqtk.stackblitz.io

### Steps To Reproduce

1. Click "ADD" to add a custom Textbox
2. The canvas is saved to JSON
3. Click "LOAD" to retreive objects from JSON.
4. Error occures telling: Cannot read properties of undefined (reading 'fromObject')

### Expected Behavior

The canvas should be refreshed with data from JSON.
I know that how to do this in plain javascript, but the problem is with angular/typescript.

### Actual Behavior

The canvas is not refreshed cause it doesn't read custom class object.

### Error Message & Stack Trace

```bash
Cannot read properties of undefined (reading 'fromObject')
```

**Comment by zmiju** [comment]
Here is the link to editable version in stackblitz: https://stackblitz.com/edit/angular-mzoqtk?file=src%2Fmain.ts

**Comment by ShaMan123** [comment]
handled in the discussion
