### ISSUE TITLE
[Bug]: zooming doesn't work on iPhone browser

### ISSUE THREAD

**Issue by emilio1118** [fabricjs/fabric.js#8636]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Safari

### Node Version (if applicable)

None

### Link To Reproduction

No reproduction

### Steps To Reproduce

<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
  <title>Canvas</title>
</head>

<body>
  <canvas id="c" width="300" height="300">
</body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/5.3.1/fabric.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.2.146/pdf.min.js"></script>

<script>
  /*
  const canvas = this.__canvas = new fabric.Canvas('c', {
    backgroundColor : '#000',
    allowTouchScrolling: true, // <-- this is what you're after
  });
  const text = new fabric.Text('Upload PDF');
  canvas.add(new fabric.Circle({ radius: 100, fill: 'green' }), text);
  
  canvas.on('mouse:wheel', function(opt) {
	  var delta = opt.e.deltaY;
	  var zoom = canvas.getZoom();
	  zoom *= 0.999 ** delta;
	  if (zoom > 20) zoom = 20;
	  if (zoom < 0.01) zoom = 0.01;
	  canvas.setZoom(zoom);
	  opt.e.preventDefault();
	  opt.e.stopPropagation();
	})
  */

  var canvas = new fabric.Canvas('c');

  var dia1 = new fabric.Circle({
    radius: 12,
    originX: 'center',
    originY: 'center',
    fill: 'transparent',
    strokeWidth: 5,
    stroke: "red",
  });
  var dia2 = new fabric.Circle({
    radius: 5,
    originX: 'center',
    originY: 'center',
    fill: 'red',
  });
  var targetEl = new fabric.Group([dia1, dia2], {
    originX: 'center',
    originY: 'center',
  });
  canvas.centerObject(targetEl);
  canvas.add(targetEl);
  canvas.renderAll();

  //mouse zoom
  canvas.on('mouse:wheel', function(opt) {
    var delta = opt.e.deltaY;
    var pointer = canvas.getPointer(opt.e);
    var zoom = canvas.getZoom();
    zoom = zoom - delta / 200;
    // limit zoom to 4x in
    if (zoom > 4) zoom = 4;
    // limit zoom to 1x out
    if (zoom < 1) {
      zoom = 1;
      canvas.setViewportTransform([1, 0, 0, 1, 0, 0]);
    }
    canvas.zoomToPoint({
      x: opt.e.offsetX,
      y: opt.e.offsetY
    }, zoom);
    opt.e.preventDefault();
    opt.e.stopPropagation();
  });

  //touch zoom
  canvas.on({
    'touch:gesture': function(e) {
      debugger;
      if (e.e.touches && e.e.touches.length == 2) {
        pausePanning = true;
        var point = new fabric.Point(e.self.x, e.self.y);
        if (e.self.state == "start") {
          zoomStartScale = canvas.getZoom();
        }
        var delta = zoomStartScale * e.self.scale;
        canvas.zoomToPoint(point, delta);
        pausePanning = false;
        // limit zoom to 4x in
        if (delta > 4) delta = 4;
        // limit zoom to 1x out
        if (delta < 1) {
          delta = 1;
          canvas.setViewportTransform([1, 0, 0, 1, 0, 0]);
        }
      }
    }
  });
</script>
</html>

This is my code

### Expected Behavior

In chrome browser at windows machine, it works well. Also, I have tested that code on safari browser. At that time, it works well too.
Only, it doesn't work on iPhone's browser.

### Actual Behavior

In iPhone's browser, zooming should be worked.

### Error Message & Stack Trace

```bash
There is no error message
```

**Comment by ShaMan123** [comment]
Sorry, this issue has no reproduction
Will open once it has

**Comment by emilio1118** [comment]
@ShaMan123 Could you please check my code?

**Comment by ShaMan123** [comment]
No
You can create a working live demo
