### ISSUE TITLE
[Bug]: y-axis flip phenomenon when creating lines

### ISSUE THREAD

**Issue by jhjeong510** [fabricjs/fabric.js#8639]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.2.4

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

14.8.0

### Link To Reproduction

https://jsfiddle.net/n1Lg6p80/
(* In jsfiddle, it appears on the screen normally through drawing, but an error occurs when creating a line through the value stored in the db. It's not easy to reproduce via jsfiddle.)
### Steps To Reproduce

1.  After creating a line through mouse down on the canvas -> mouse drag -> mouse over, the coordinates (x1, y1, x2, y2) of the line are saved in the database.
2. Line rendering with coordinates (x1, y1, x2, y2) stored in the database through a rendering-only component

The coordinate information of the line I used is x1, x2, y1, y2 among the object information of the line.
`aCoords
: 
{tl: Point, tr: Point, bl: Point, br: Point}
cacheHeight
: 
486
cacheTranslationX
: 
346
cacheTranslationY
: 
265
cacheWidth
: 
644
dirty
: 
false
fill
: 
"red"
hasBorders
: 
false
height
: 
479
id
: 
1
isMoving
: 
false
left
: 
621.53125
lineCoords
: 
{tl: Point, tr: Point, bl: Point, br: Point}
oCoords
: 
{ml: Point, mr: Point, mb: Point, mt: Point, tl: Point, …}
originX
: 
"center"
originY
: 
"center"
ownCaching
: 
true
ownMatrixCache
: 
{key: '445.1875_993.03125_1_1_0_0_0_center_center_637_479_5falsefalse', value: Array(6)}
selectable
: 
true
stroke
: 
"yellow"
strokeDashArray
: 
(2) [10, 10]
strokeWidth
: 
5
top
: 
659.6875
width
: 
637
x1
: 
674.53125
x2
: 
1311.53125
y1
: 
684.6875
y2
: 
205.6875
zoomX
: 
1
zoomY
: 
1
__corner
: 
0
_cacheCanvas
: 
canvas
_cacheContext
: 
CanvasRenderingContext2D {canvas: canvas, globalAlpha: 1, globalCompositeOperation: 'source-over', filter: 'none', imageSmoothingEnabled: true, …}
_cacheProperties
: 
{}`

### Expected Behavior

Using the coordinates of the starting point (mouse down) and ending point (mouse over) of dragging, a line should be created according to the path drawn by the user.

### Actual Behavior

When rendering after line creation, the y-axis is flipped and displayed
![issue](https://user-images.githubusercontent.com/82925400/216249269-87fe3805-db9f-4eb8-8cbb-0456e5015f9d.gif)

The odd thing is that the issue doesn't happen consistently. Sometimes lines are created normally.

**Comment by ShaMan123** [comment]
Line is really horrible...
Did you try using polyline?

**Comment by zlristovski** [comment]
I am facing with the same issue, on line creation FlipX and FlipY are false, even if you create line from bottom left position. After saving the line in database and reloading than it works fine, but for new object we have an issue. Anyone to suggest something?

**Comment by asturur** [comment]
Please @zlristovski open a new issue with your own case and your own code.
