### ISSUE TITLE
[Feature]: API to center an Object origin

### ISSUE THREAD

**Issue by VikasAgarwal1984** [fabricjs/fabric.js#8644]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

By default when user selects multiple objects, we can get activeSelection through 
`canvas.getActiveObject() as fabric.ActiveSelection`

ActiveSelection can be converted toGroup() if there are multiple Objects
Reference:
http://fabricjs.com/docs/fabric.ActiveSelection.html
`activeselection.toGroup();`

By default group is left origin.
In my codebase, Rest all the objects are currently maintained as center origin for ease of calculations.

While going through fabric js code, i see there is a private function _setOriginToCenter
https://fabricjs.com/docs/fabric.js.html#line16526

I could not locate any other function that provides me same functionality.
I see one more function 
http://fabricjs.com/docs/fabric.Object.html#adjustPosition

But thats sets only originX .

Can you please suggest any other alternatives already available or you think this can be a taken as feature request?

### Current State

Using private function _setOriginToCenter();

**Comment by asturur** [comment]
What does it happen if you set the default prototype of Group to have originX and originY to center?
Doesn't that work out of the box for all objects?

**Comment by VikasAgarwal1984** [comment]
Thanks for the approach. Where can I find the help for setting defaults for objects globally?

**Comment by VikasAgarwal1984** [comment]
Thanks, I will look into it.

**Comment by ShaMan123** [comment]
stale it is
v5 and under
