### ISSUE TITLE
Let me CSS-scale the canvas [$20 awarded]

### ISSUE THREAD

**Issue by miracle2k** [fabricjs/fabric.js#868]
There seem to be two issues with this:

1) Canvas.setWidth() insists on setting the CSS width/height attributes. This is unfortunate, but I can overwrite this.

2) The mouse handling does not take into account the CSS scaling. Once the canvas is scaled, hit testing etc. stops working right.
##

**Comment by Guiladg** [comment]
Any news abaout this guys?
I'm with miracle2k, css-scaling is expected for smaler devices and it is the simpliest way to make any web site cross-device. 
I really need it for my project, I want to draw in a PC, in a tablet and in a phone. I'm having this mouse issue on smaller screens.
Thanks
