### ISSUE TITLE
[Feature]: use of 'fabric.util.createClass' in v6?

### ISSUE THREAD

**Issue by shubaoliu** [fabricjs/fabric.js#8689]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

Hi, I have been using 'fabric.util.createClass' function in my web app with v5.3.1. However, when testing it with v6.0-beta, I get this error 'Uncaught TypeError: createClass is not a function'. 

### Current State

I tried to modify 'fabric.ts' to add 'createClass' in util variable, but it didn't work. I'm not familiar with the new design of v6.0, could someone help me on this? Thanks!

**Comment by ShaMan123** [comment]
I has been removed
v6 uses native classes

**Comment by ShaMan123** [comment]
#8299
