### ISSUE TITLE
[Bug]: I had a bug using aligning_guidelines.js

### ISSUE THREAD

**Issue by tetap** [fabricjs/fabric.js#8746]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/3mbw80jc/2/

### Steps To Reproduce

1.  Add three rectangles
2. Lines will appear when there are rectangles that are too close together, but only one will be aligned

### Expected Behavior

Only applies to line segments that align elements

### Actual Behavior

Only the line of the current aligned element is displayedUnaligned elements were added, resulting in extra line segments

![image](https://user-images.githubusercontent.com/57606461/221752873-91c59fd5-f559-4072-b625-301c05dd9cf7.png)

**Comment by ShaMan123** [comment]
can you try with #8141 and report back?

**Comment by tetap** [comment]
> #8141

It's not a matter of clearing, it's a matter of the fact that both lines are within the error, but the alignment will only follow the end.
