### ISSUE TITLE
Error while loading Subclasses from jSON

### ISSUE THREAD

**Issue by EffEPi** [fabricjs/fabric.js#876]
While working on the my version of curvedText (https://github.com/EffEPi/fabric.curvedText) I have noticed that when trying to loadFromJSON a subclass an error shows up:
- TypeError: Cannot read property 'async' of undefined 

You can replicate it here:
- http://jsfiddle.net/EffEPi/pbPRC/ (with subclass example from fabric docs)
- http://jsfiddle.net/EffEPi/qpJTz/ (with my curvedText)

**Comment by umanda** [comment]
@EffEPi  @asturur I'm excited to utilize this fantastic FabricJs 5x implementation. However, it seems that it does not support the latest version of Fabricjs. Is it possible to migrate it to the never version, or can you advise me on how to do so?
