### ISSUE TITLE
node-canvas scale cuts off image when using aws lambda

### ISSUE THREAD

**Issue by chrismeats** [fabricjs/fabric.js#8771]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Node.js

### Node Version (if applicable)

18.14.0

### Link To Reproduction

https://codesandbox.io/s/boring-minsky-j3jxi1?file=/src/index.js

### Steps To Reproduce

I am not sure if this is an issue with fabricjs, aws lambda, node-canvas, or I am not setting this up correctly on lambda.

1. Install lambda-layer-canvas-nodejs layer on lambda function
2. Utilize scaling to adjust image inside of canvas
3. height of image is then cut off
4. I have tried using scaling by directly editing json and using loadfromjson as well as using fabric.Image.fromURL and then using scaleToWidth(1000); to scale image.
This works correctly in browser, and in nodejs example on codesandbox.io
https://codesandbox.io/s/boring-minsky-j3jxi1?file=/src/index.js
However, in lambda the image is cut off.
If I leave the scaling at the original setting of .09 then it loads correctly

### Expected Behavior

![exampleCorrect](https://user-images.githubusercontent.com/3507007/224338569-e4e0de00-d5f0-45d4-be01-bbe80fd94597.png)

### Actual Behavior

Example of code from lambda:
```
import { fabric } from 'fabric';
export const handler = async(event, context, callback) => {
    var data = '{"version":"3.6.2","objects":[{"type":"image","version":"3.6.2","originX":"left","originY":"top","left":0,"top":0,"width":5400,"height":5400,"fill":"rgb(0,0,0)","stroke":null,"strokeWidth":0,"strokeDashArray":null,"strokeLineCap":"butt","strokeDashOffset":0,"strokeLineJoin":"miter","strokeMiterLimit":4,"scaleX":0.18,"scaleY":0.18,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"crossOrigin":"","cropX":0,"cropY":0,"src":"https://printtech-builder.s3.amazonaws.com/tmp/27afaa61-5c7e-4307-8620-7faf14a3789d.jpeg","filters":[]},{"type":"text","version":"3.6.2","originX":"left","originY":"top","left":123,"top":125,"width":150,"height":45,"fill":"#000000","stroke":null,"strokeWidth":1,"strokeDashArray":null,"strokeLineCap":"butt","strokeDashOffset":0,"strokeLineJoin":"miter","strokeMiterLimit":4,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"shadow":null,"visible":true,"clipTo":null,"backgroundColor":"","fillRule":"nonzero","paintFirst":"fill","globalCompositeOperation":"source-over","transformMatrix":null,"skewX":0,"skewY":0,"text":"Some text goes here","fontSize":26.21919234397663,"fontWeight":"normal","fontFamily":"aguafina_script-regular","fontStyle":"normal","lineHeight":1.16,"underline":false,"overline":false,"linethrough":false,"textAlign":"left","textBackgroundColor":"","charSpacing":0,"styles":{}}]}';
    var canvas = new fabric.StaticCanvas(null, { width: 1000, height: 1000 });
    const resultsOf = await new Promise((resolve, reject) => {
        canvas.loadFromJSON(data, function() {
            canvas.renderAll();
            resolve('done');
        
        });
    });
    const response = {
        statusCode: 200,
        body: JSON.stringify(canvas.toDataURL()),
    };
    return response;
};

```
Generated Image:
![example cut off](https://user-images.githubusercontent.com/3507007/224339544-5b3064a7-a51d-4910-96c2-5903c1cc7c5d.png)

**Comment by ShaMan123** [comment]
This seems a node canvas issue so you should open it there
There are many implication when running on servers.
A quick search reveals:
https://awstip.com/node-canvas-in-aws-lambda-3eed41ec36c3
https://github.com/jwerre/node-canvas-lambda
And node canvas has an installation wiki...
You can also look at our `.github` folder that run ci for config.

**Comment by ShaMan123** [comment]
If you proof it isn't I will reopen.
This can be done by rendering the image without using fabric, only using node canvas
