### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by surendhar-palanisamy** [fabricjs/fabric.js#8772]
Additional values from the hook to tell us the editor state

Const {val1,val2} = usefabricjseditor()
IsReady,
 isUpdating 
Isupdated
IsRebuilding - when we swap the input for the canvas we could know whether the canvas is rebuilding itself with new input

**Comment by ShaMan123** [comment]
not clear what this is about
please update description

**Comment by surendhar-palanisamy** [comment]
> not clear what this is about
> please update description 

Thanks for the reply, i have updated the description

**Comment by ShaMan123** [comment]
wrong repo
