### ISSUE TITLE
loadFromJson Ignores Text Height and Width 

### ISSUE THREAD

**Issue by chrismeats** [fabricjs/fabric.js#8773]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

http://jsfiddle.net/cuqx3fpy/1/

### Steps To Reproduce

1. Add text object to fabric js and center text
2. export fabric json
3. create new fabric canvas and use loadFromJson
4. The text object is added to the canvas but is not centered and does not seem to get the correct Height and Width properties from the json

### Expected Behavior

Text should be added to canvas and displayed like the original:
<img width="509" alt="image" src="https://user-images.githubusercontent.com/3507007/224480651-e6808de7-3546-42c7-8b95-3af9f7e4c673.png">

### Actual Behavior

Text is not centered, and height and width are not set.
<img width="511" alt="image" src="https://user-images.githubusercontent.com/3507007/224480755-e8263c6a-15b3-4033-a39e-73bf50f0bb80.png">

**Comment by melchiar** [comment]
Your example is running on Fabric v1.5, which is many years out of date. Please upgrade to the current release.

**Comment by chrismeats** [comment]
@melchiar Sorry about that. Here is an example using the current release with the same issue:
https://jsfiddle.net/t5njgz0v/

**Comment by melchiar** [comment]
@chrismeats can you explain your usecase?

Fabric's Text class isn't designed to allow for arbitrary width/height values since these are calculated based on the size of the text content (in the [initDimensions ](https://github.com/fabricjs/fabric.js/blob/8f5363260c39ca4e1f94584dc9f12193eec12963/src/shapes/text.class.js#L429)method)

You can use the Textbox class instead of Text if you want arbitrary widths, though none of the included text classes are built to allow a custom height value.

**Comment by chrismeats** [comment]
@melchiar 
Thank you for the clarification. 

My particular use is that the text object is added onto another image. One user sets up placeholder text and another user later enters another text string, that could be longer or shorter, and that user does not have any controls other than a text input box. The text still has to fit within the parameters based on the image that the text is placed on top of. Therefore the height and width of the original text box is set, and then the actual font size is adjusted programmatically based on the length of text entered by the user. Depending on the layout of the original image the text is also either positioned left, center, or right.

Hopefully that make sense conceptually... It sounds like I just may not be able to load from json and will just need to add the text fields independently as it works doing it that way.
