### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by egshyam10** [fabricjs/fabric.js#8785]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

I would like to request you explicitly declare or document - if Fabric Js is compatible with ReactNative, Flutter, Ionic instead of we researching and making trial and error work to avoid any confusions in the engineering team who used already with React.

### Current State

No idea if Fabric Js works with the above mentioned frameworks or not. So, kindly update the documentation and provide some starter kits 

I will be glad to shell out more details if needed

**Comment by ShaMan123** [comment]
You are more than welcome to read discussions or start one with your findings.
Or PR docs! The readme should contain a sentence about it.
It is vanilla js. Should work on every js engine/framework. Web workers not yet. Hence the name fabric.**js**
Open source requires contributions, thanks
