### ISSUE TITLE
[Bug]: Negative value for rect.top and rect.left while exporting cavas to json

### ISSUE THREAD

**Issue by Sreesanth46** [fabricjs/fabric.js#8796]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Firefox

### Node Version (if applicable)

None

### Link To Reproduction

https://stackblitz.com/edit/vue-uebuht?file=src/App.vue

### Steps To Reproduce

1. Open stackblitz
2. Draw a rectangle by dragging mouse
3. Draw a rectangle overlapping the rectangle drawn first 
4. Open the console
5. Canvas is exported as json
6. Check the left and top values of second object

### Expected Behavior

Both the rect objects top: and left: values should be positive  

### Actual Behavior

rect.left, rect.top are not always positive. (Sometime less than the expected value or negative) 

### Error Message & Stack Trace

```bash
-------- JSON EXPORT --------
{
  "version": "5.3.0",
  "objects": [
    {
      "type": "rect",
      "version": "5.3.0",
      "originX": "left",
      "originY": "top",
      "left": -46.23,
      "top": -147.54,
      "width": 96.42,
      "height": 229.7,
      "fill": null,
      "stroke": "red",
      "strokeWidth": 4,
      "strokeDashArray": null,
      "strokeLineCap": "butt",
      "strokeDashOffset": 0,
      "strokeLineJoin": "miter",
      "strokeUniform": true,
      "strokeMiterLimit": 4,
      "scaleX": 1,
      "scaleY": 1,
      "angle": 0,
      "flipX": false,
      "flipY": false,
      "opacity": 1,
      "shadow": null,
      "visible": true,
      "backgroundColor": "",
      "fillRule": "nonzero",
      "paintFirst": "fill",
      "globalCompositeOperation": "source-over",
      "skewX": 0,
      "skewY": 0,
      "rx": 0,
      "ry": 0
    },
    {
      "type": "rect",
      "version": "5.3.0",
      "originX": "left",
      "originY": "top",
      "left": -54.19,
      "top": -38.63,
      "width": 21.87,
      "height": 182.18,
      "fill": null,
      "stroke": "red",
      "strokeWidth": 4,
      "strokeDashArray": null,
      "strokeLineCap": "butt",
      "strokeDashOffset": 0,
      "strokeLineJoin": "miter",
      "strokeUniform": true,
      "strokeMiterLimit": 4,
      "scaleX": 1,
      "scaleY": 1,
      "angle": 0,
      "flipX": false,
      "flipY": false,
      "opacity": 1,
      "shadow": null,
      "visible": true,
      "backgroundColor": "",
      "fillRule": "nonzero",
      "paintFirst": "fill",
      "globalCompositeOperation": "source-over",
      "skewX": 0,
      "skewY": 0,
      "rx": 0,
      "ry": 0
    }
  ]
}
```

**Comment by ShaMan123** [comment]
Please make your repro simpler and scoped.

**Comment by Sreesanth46** [comment]
> Please make your repro simpler and scoped.

Hi, Ive updated the reproduction link.

**Comment by Sreesanth46** [comment]
> Please make your repro simpler and scoped.

Hi Ive

**Comment by ShaMan123** [comment]
It is because they are still grouped on mouseup
