### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by goldy1234** [fabricjs/fabric.js#8797]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

1: Cropping of active object is required what canva.com has.
2: Changing the layer of image (which element should come on top or bottom, can be changed anytime).

### Current State

1: Cropping and layer changing is not feasible

**Comment by ShaMan123** [comment]
This is not clear. Put more effort into it.

**Comment by ShaMan123** [comment]
closing until then

**Comment by goldy1234** [comment]
Description:
Just like we are able to resize or rotate an image with the movement of cursor using dragmove, why there isn't any inbuilt function like above to crop the image at any angle or any position and also to edit the cropped at any point of time just like resizing.

**Comment by ShaMan123** [comment]
There will be in the upcoming versions
