### ISSUE TITLE
Cannot disable rotation on rectangle

### ISSUE THREAD

**Issue by hathemi** [fabricjs/fabric.js#8799]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/testeur_H12/hangfybo/1/

### Steps To Reproduce

1.     create rectangle
```
var rect = new fabric.Rect({
      left: 100,
      top: 50,
      width: 150,
      height: 30,
      fill: '#8ed1fc80',
      hasRotatingPoint: false,
      centeredRotation: false,
      lockRotation:true
    });

    var rectGroup = new fabric.Group([rect], {
      name: 'Rectangle',
    });
```
   
2.  `canvas.add(rectGroup);`
3.  `canvas.renderAll();
`

### Expected Behavior

disable rotation on rectangle created.

### Actual Behavior

rotation still exists
![Sans titre](https://user-images.githubusercontent.com/23275040/226875989-078aebd7-ce74-4226-8e4a-a16afba76677.png)

**Comment by ShaMan123** [comment]
You are rotating the group. Disable that.
https://jsfiddle.net/1oy9ngzr/
