### ISSUE TITLE
[Bug]: Unable to select the resize and rotate handlers 

### ISSUE THREAD

**Issue by roelVerdonschot** [fabricjs/fabric.js#8810]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Firefox, Chrome, Safari, Opera, Microsoft Edge

### Node Version (if applicable)

None

### Link To Reproduction

https://www.dropbox.com/s/i1srfyoq5oic5g2/Schermopname%202023-03-30%20om%2010.46.44.mov?dl=0

### Steps To Reproduce

1. Add line
2. Canvas toJSON
3. Load the json canvas.loadFromJSON
4. Corner selectors don't work anymore

### Expected Behavior

Corner selector handlers always work

### Actual Behavior

Selectors don't work anymore

**Comment by yamakrane** [comment]
how did you fix it ?

**Comment by roelVerdonschot** [comment]
We use VueJS and I solved this by placing the canvas outside of the component so it doesn't get observed by the framework.

```
<script>
const canvasses = []

export default {
name: 'Canvas',
}
```

**Comment by ShaMan123** [comment]
This issue has been reported in several tickets already.
I do not use vue.
I suggest the community to add a vue starter app. I can help doing that.

**Comment by huanghaiyang** [comment]
mark

**Comment by huanghaiyang** [comment]
like tihis
import { markRaw } from 'vue';
![image](https://github.com/fabricjs/fabric.js/assets/5448818/5fabf3cc-c045-4a65-ae07-b959a7109160)
![image](https://github.com/fabricjs/fabric.js/assets/5448818/d806b560-6d4d-4e82-b28a-9184887b284b)
![image](https://github.com/fabricjs/fabric.js/assets/5448818/17d6a693-5187-49b5-a9cc-6d8a15890de9)
