### ISSUE TITLE
[Bug]: How to use IEvent in v6

### ISSUE THREAD

**Issue by more-strive** [fabricjs/fabric.js#8813]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta1

### Node Version (if applicable)

None

### Link To Reproduction

no link

### Steps To Reproduce

How to use IEvent in v6.0.0-beta1?

### Expected Behavior

![image](https://user-images.githubusercontent.com/113762408/229048026-2d334675-52f9-43df-a304-6f318910e22f.png)
Module 'fabric' has no exported member 'IEvent'

### Actual Behavior

Obtain an object through IEvent

**Comment by ShaMan123** [comment]
IEvent isn't part of fabric
It is part of the definately typed @types/fabric dead package
That said, we still need to fix type exports

**Comment by more-strive** [comment]
thanks! I am using the any type instead

**Comment by ShaMan123** [comment]
#8868
