### ISSUE TITLE
[Bug]: I tried to add a video above, but it didn’t fully display its content.

### ISSUE THREAD

**Issue by gitForZjj** [fabricjs/fabric.js#8814]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta1

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

no

### Steps To Reproduce

addCanvasVideo(url,width,height,x,y) {
      let videoEl = document.createElement('video');
      videoEl.src = url
      videoEl.autoplay = true
      videoEl.loop = true
      let w = width?width:500
      let h = height?height:360
      videoEl.width = w
      videoEl.height= h
      videoEl.addEventListener('loadeddata', ()=> {
        let video = new fabric.Image(videoEl,{
          left: x?x:0,
          top: y?y:0,
          objectCaching: false});
        video.scaleToWidth(w);
        this.canvas.add(video)
        video.getElement().play();
        console.log(video.getElement())
      });
      videoEl.load();
    }
run this method

### Expected Behavior

![9E5296CC-27CF-4178-92D6-19B738F6A9CC](https://user-images.githubusercontent.com/48214115/229071733-bf9e846c-a9b5-4b23-bed6-1a57d1598f67.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/48214115/229071904-734d687d-ff7c-4cfe-832f-269b700990d4.png)

**Comment by ShaMan123** [comment]
no reproduction
