### ISSUE TITLE
[Bug]: First draw on touch monitor is not working.

### ISSUE THREAD

**Issue by urbanekpj** [fabricjs/fabric.js#8819]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta1

### In What environments are you experiencing the problem?

Chrome, Opera

### Node Version (if applicable)

None

### Link To Reproduction

mainTouchId

### Steps To Reproduce

1.  try draw on touch device
2.  first line is not showned/ empty path added
3.  next one works 

### Expected Behavior

drawing on touch monitor should work from first draw.

### Actual Behavior

draw working after second try. i debugged it and it turns that mainTouchId i 'undefined' initially. but in code compare with null https://github.com/fabricjs/fabric.js/blame/master/src/canvas/Canvas.ts#L609.
after adding 
```
   canvas.mainTouchId = null;
```
after creation fixed issue. 
i can't log codesand box so i will not create demo.

**Comment by ShaMan123** [comment]
> i can't log codesand box so i will not create demo.

What do you mean?

**Comment by urbanekpj** [comment]
i open [vanila](https://codesandbox.io/p/sandbox/fabric-vanillajs-sandbox-forked-e5r48u?file=%2FREADME.md) 

try fork -> login page is opened i use google/github auth. but in see 401 errors  i console logs. and page not go any futher.

![image](https://user-images.githubusercontent.com/34157776/230017055-06450797-e950-4523-a75c-873b213b305a.png)

but as raised issue is straight forward i didn't follow any further due to lack of time.

**Comment by ShaMan123** [comment]
no repro
