### ISSUE TITLE
[Feature]: Scroll feature in the canvas. 

### ISSUE THREAD

**Issue by sejalaroraa1234** [fabricjs/fabric.js#8823]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

In case of rendering the canvas inside a webview in the mobile app, scrolling problem is faced. Due to limited device height & width, we are not able to see the full canvas. 

Case1: If we provide appropriate height & width to the canvas, some rendered objects are trimmed.  
Case2: If we wrap it inside a div, and scroll through it, a case arrives when the canvas height exceeds the device height & due to overflow of the canvas objects, we are not able to perform the scroll event on div as it is not accessible. 

### Current State

Current State of the canvas is that it is able to recognise the touch events but is not scrollable. It only renders according to the height & width provided to it & trims the other objects exceeding that size. This causes trouble in the small devices as we are not able to see the whole canvas and the objects inside it.

### Additional Context

Addressing the same problem mention above, it would be useful to have a scroll feature inside canvas so we can access the same & see the whole canvas on the small devices as well.

**Comment by ShaMan123** [comment]
Best practice is to use panning, transforming the viewport

**Comment by ShaMan123** [comment]
See #8780 for fitting the canvas
