### ISSUE TITLE
[Feature]: RTL SUPPORT

### ISSUE THREAD

**Issue by ikilane** [fabricjs/fabric.js#8828]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

We need to add support for RTL on v6 when using i-text or text box  

### Current State

theres no support for rtl and when you use rtl, the alignment not working good

**Comment by ShaMan123** [comment]
https://github.com/fabricjs/fabric.js/pull/7864
You are welcome to join the effort
I need to revive that PR
