### ISSUE TITLE
[Feature]: coords after rotating

### ISSUE THREAD

**Issue by LarryHangFan** [fabricjs/fabric.js#8831]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta1

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

16.14.0

### Link To Reproduction

https://jsfiddle.net/LarryLuo/g6m7cjxa/4/

### Steps To Reproduce

1.  run test, look at console;  

### Expected Behavior

 In fact, the rotation should not change its left and top

### Actual Behavior

After the element is rotated, its left and top are changed incorrectly.

**Comment by ShaMan123** [comment]
I think I understand your point.
tl coord is relative to the rotation, it is not the actual tl left point viewed by the viewer.
You can run a calculation to find the min values of the coords.
related to #8767

**Comment by LarryHangFan** [comment]
In css, the rotation does not affect the tl coord. the rotation of this library is not handled the same as the css?

**Comment by ShaMan123** [comment]
I can't understand your question w/o reading the docs about css, so try to explain w/o making me do that

**Comment by LarryHangFan** [comment]
When an element is rotated using the CSS transform property, the element's width and height usually don't change, so neither do the element's top and left values. This is because the transform property applies a rotation transformation within the element itself, rather than altering the element's external layout. I think the rotation of fabric should be similar to css.

**Comment by ShaMan123** [comment]
So you mean that if top left was 0,0 it still is after rotating?
It can be achieved with #8767
