### ISSUE TITLE
Module parse failed: Unexpected character '�' (1:2)

### ISSUE THREAD

**Issue by MyDesignGit** [fabricjs/fabric.js#8836]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

I'm trying to integrate Fabric Canvas in nextjs using npm install fabric. But getting Unexpected errors. I have tried to configure next.config.js, but the same error

### Current State

error - ./node_modules/canvas/build/Release/canvas.node
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders       
(Source code omitted for this binary file)

**Comment by ShaMan123** [comment]
you must migrate to v6 to use SSR

**Comment by Shubham-731** [comment]
Hey @MyDesignGit! Did you get the solution to this error? Please let me know about that.
