### ISSUE TITLE
[Feature]: updated variable not showing in canvas.on function

### ISSUE THREAD

**Issue by BinaConcept** [fabricjs/fabric.js#8864]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

I have array with different parameters in it. When I load it into my component for the first time, it comes in fine. But if I want to make changes to an existing array, I see changes via console.log outside the canvas.on function, but not in the canvas.on itself.

### Current State

useEffect(()=>{
console.log (correct custom parameters can be read)
canvas.on(in it I don't see any custom parameters where I see above in console.log)

})

**Comment by ShaMan123** [comment]
A terrible description

**Comment by BinaConcept** [comment]
> ### CheckList
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
> * [x]  I have searched and referenced existing issues, feature requests and discussions
> * [x]  I am filing a **FEATURE** request.
> 
> ### Description
> I have array with different parameters in it. When I load it into my component for the first time, it comes in fine. But if I want to make changes to an existing array, I see changes via console.log outside the canvas.on function, but not in the canvas.on itself.
> 
> ### Current State
> useEffect(()=>{ console.log (correct custom parameters can be read) canvas.on(in it I don't see any custom parameters where I see above in console.log)
> 
> })
> 
> ### Additional Context
> _No response_

**Comment by BinaConcept** [comment]
Is it a bit clearer now

**Comment by ShaMan123** [comment]
Not related to fabric.
Description is the same for me.
It is a js issue so it seems.
You are ptobably mutating the array before the event is fired........
Create a copy.
Polish your js  🥸

**Comment by BinaConcept** [comment]
import React, { useEffect, useState } from 'react';
import { fabric } from 'fabric';
import { Button } from '../atomic/molecules/button';
import axios from 'axios';
export const PolyFabric = (props) => {
	const [obj, setobj] = useState([]);
	const [objectDetection, setObjectDetection] = useState([
		{
			id: 0,
			selected: 0,
			polygon: [],
		},
	]);

	const apiCall = () => {
		const url =
			'http://192.168.0.11/control/control?read&section=event_ima&ima';

		const data = {
			username: 'admin',
			password: 'meinsm123',
		};
		axios
			.get(url, data)
			.then((response) => {
				const txt = response.data;
				const reTx = txt.replace(/:/g, ' ');
				const spTx1 = reTx.split('ima=');

				setobj([
					...obj,
					{
						id: 0,
						name: 'Kies object',
					},
				]);
				for (let i = 1; i < spTx1.length + 1; i++) {
					if (spTx1[i - 1].indexOf('_profilename') > -1) {
						let nuberP = spTx1[i - 1].indexOf('_profilename');
						let nuberL = spTx1[i - 1].indexOf('vm_list');
						let subL = spTx1[i - 1].substring(nuberL + 8);
						let reL = subL.replace(/\n/g, '');

						setobj((objData) => [
							...objData,
							{
								id: i - 1,
								name: spTx1[i - 1].substring(
									nuberP + 13,
									spTx1[i - 1].indexOf('ima_dead')
								),
								value: parseInt(reL),
							},
						]);
					}
				}
			})
			.catch((error) => {
				console.log(error);
			});
	};

	useEffect(() => {
		apiCall();
	}, []);

	const createObject = (objData) => {
		const newItems = [
			{
				id: objectDetection.length + 1,
				selected: objData.selectedIndex,
				polygon: [],
			},
			...objectDetection,
		];
		console.log('new items');
		newItems.sort((a, b) => (b.id !== 0 ? a.id - b.id : null));

		setObjectDetection(newItems);
	};

	const editObject = (i, objData) => {
		const updatedArray = [
			...objectDetection.slice(0, i),
			{
				// here update data value
				...objectDetection[i],
				selected: objData.selectedIndex,
			},
			...objectDetection.slice(i + 1),
		];
		setObjectDetection(updatedArray);
	};

	const deleteObject = (index) => {
		setObjectDetection(objectDetection.filter((item, i) => i !== index));
	};

	const objectList = obj.map((data, i) => {
		return (
			<option key={i} value={i}>
				{data.name}
			</option>
		);
	});

	const addObjectDetection = () => {
		const obDetect = () =>
			objectDetection.map((data, i) => (
				<div className="row" key={i}>
					<div className="col-lg-6">
						<div className="input-group mb-3">
							{objectDetection.length !== i + 1 ? (
								<Button className="btn-warning" onClick={() => deleteObject(i)}>
									-
								</Button>
							) : null}
							<select
								className="form-select"
								aria-label="Default select example"
								value={data.selected === 0 ? 0 : data.selected}
								onChange={(e) =>
									data.selected === 0
										? createObject(e.target)
										: editObject(i, e.target)
								}
							>
								{objectList}
							</select>
						</div>
					</div>
					<div className="row">
						<div className="col-lg-6"></div>
					</div>
				</div>
			));

		return obDetect();
	};

	var canvas;
	useEffect(() => {
		canvas = new fabric.Canvas('c');
		canvas.setWidth(747);
		canvas.setHeight(450);
	});

	useEffect(() => {
		console.log('demo', objectDetection);
		canvas.on('mouse:down', (e) => {
			console.log('downClick', objectDetection);
		});
	});

	return <>{addObjectDetection()}</>;
};
