### ISSUE TITLE
reviver and options are no longer optional for loadSVGFromString

### ISSUE THREAD

**Issue by tushuhei** [fabricjs/fabric.js#8867]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta3

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/p/sandbox/fabric-nextjs-sandbox-forked-jrrhjd?file=%2Fpages%2Findex.tsx

### Steps To Reproduce

1. Prepare a SVG string
2. Parse it with `loadSVGFromString`

### Expected Behavior

I don't need to specify the 3rd (reviver) and the 4th (options) args because they used to be optional as the name suggests.

### Actual Behavior

I need to pass a blank function and a blank object at least because they're not optimal.

### Error Message & Stack Trace

```bash
TypeScript build error
```

**Comment by tushuhei** [comment]
I believe the root causation is that https://github.com/fabricjs/fabric.js/blob/master/src/parser/elements_parser.ts has not been typed.

**Comment by asturur** [comment]
I noticed it as well and i need to fix it indeed.

**Comment by ShaMan123** [comment]
@tushuhei welcome to PR as you did before!

**Comment by ShaMan123** [comment]
@asturur I don't think the bug label should be used on a type issue

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/pull/8869

I started a PR, but we should expect those high level functions to become promise based, since i think those are the last callback based.
At least at an higher level even if the internal parser is all callbacks yet
