### ISSUE TITLE
[Bug]: I can't edit the text inside the textbox by double clicking on Vue3+Vite4+TS.

### ISSUE THREAD

**Issue by trouvaille2023** [fabricjs/fabric.js#8880]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta3

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

18.14.0

### Link To Reproduction

https://github.com/trouvaille2023/classic.git

### Steps To Reproduce

1. Demo link:  https://github.com/trouvaille2023/classic.git
2. Clicking the TextBox button, It will drew a section of text using a text box.
3. Double click on the text, I want to enter editing mode.
4. But I cannot enter editing mode by double-clicking on the text box.
5. I cannot solve this problem by switching between the Node version and the Fabric.js version.

### Expected Behavior

I can  enter editing mode by double-clicking on the text box.

### Actual Behavior

After clicking the TextBox button, I drew a section of text using a text box, but I was unable to enter editing mode by double-clicking the text box.

### Error Message & Stack Trace

```bash
No Error.
```

**Comment by ShaMan123** [comment]
We state that a repro is something that works when you click it.
Until then closing
