### ISSUE TITLE
[Bug]: Rename Object to make it specifically fabricObject (v6)

### ISSUE THREAD

**Issue by prabh-62** [fabricjs/fabric.js#8885]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta3

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

19.8.1

### Link To Reproduction

Not applicable

### Steps To Reproduce

1. `import { Object } from 'fabric';`
2. ESlint gives a warning `Don't use "Object" as a type. The "Object" type actually means "any non-nullish value", so it is marginally better than "unknown".`
3. ESlint ban-types wiki: https://typescript-eslint.io/rules/ban-types/#examples 
4. <img width="532" alt="fabric_v6_bantypes_object" src="https://user-images.githubusercontent.com/13006107/236361175-2a7b8de9-262c-480b-932e-f357c7da87a2.png">

### Expected Behavior

There should be no ESlint warnings by default

### Actual Behavior

ESlint raises `ban-types` warnings on import of `Object` from `fabric`

**Comment by ShaMan123** [comment]
import { Object as FabricObject } from 'fabric';

**Comment by ShaMan123** [comment]
same applies for Text and Image
