### ISSUE TITLE
[Bug]: TypeError when adding Blur to Image

### ISSUE THREAD

**Issue by jasonkang14** [fabricjs/fabric.js#8891]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta1

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

codesandbox keeps asking me to sign in. the reproducable code is attached below

### Steps To Reproduce

```typescript
// change pages/index.tsx to below

import * as fabric from 'fabric';
import { NextPage } from 'next';
import { useCallback } from 'react';
import { Canvas } from '../components/Canvas';

const IndexPage: NextPage = () => {
  const onLoad = useCallback(async (canvas: fabric.Canvas) => {
    canvas.setDimensions({
      width: window.innerWidth,
      height: 500,
    });
    const image = await fabric.Image.fromURL('https://bookriot.com/wp-content/uploads/2022/08/penguin-random-house-logo-1280x720.png', {crossOrigin: 'anonymous'});
    canvas.add(image);
    const filter = new fabric.filters.Blur({ blur: 0.8 });
    image.filters.push(filter);
    image.applyFilters();
    canvas.renderAll();
  }, []);

  return (
    <div className="position-relative">
      <Canvas onLoad={onLoad} />
    </div>
  );
};

export default IndexPage;
```

you would get a type error like below
<img width="914" alt="Screenshot 2023-05-07 at 5 17 59 AM" src="https://user-images.githubusercontent.com/45306565/236644984-c9c2723b-4505-4e93-ad41-74074b79d991.png">

however when you add `// @ts-expect-error` like below

```typescript
    const image = await fabric.Image.fromURL('https://bookriot.com/wp-content/uploads/2022/08/penguin-random-house-logo-1280x720.png', {crossOrigin: 'anonymous'});
    canvas.add(image);
    const filter = new fabric.filters.Blur({ blur: 0.8 });
    // @ts-expect-error
    image.filters.push(filter);

```

it works just fine. 

### Expected Behavior

blur should be added and ready to be used without an error

### Actual Behavior

There is a TypeError

### Error Message & Stack Trace

<img width="914" alt="Screenshot 2023-05-07 at 5 17 59 AM" src="https://user-images.githubusercontent.com/45306565/236644984-c9c2723b-4505-4e93-ad41-74074b79d991.png">

**Comment by jasonkang14** [comment]
how would you like me to make a PR in order to fix this? should I change the type of `Blur` ? or should i change the type of `Image.filters`?

**Comment by ShaMan123** [comment]
change `Image.filters`
But this is really strange because Blur is intanceof BaseFilter...
Ohh I think I got it
It is because of this line:
https://github.com/fabricjs/fabric.js/blob/d37c7f74737e13833823ad7a63972de410acb75b/src/filters/BaseFilter.ts#L42

TS is really annoying and not smart regarding inheritance of `this`, `keyof this`

**Comment by ShaMan123** [comment]
redeclaring mainParam on blur might be the simple way to solve this TS annoyance

**Comment by jasonkang14** [comment]
sounds good. i'll make a pr with this!

**Comment by asturur** [comment]
mainParameter was an hack to avoid repeating simple code for all the filters.
I m not sure is worth, but also i don't want to see the quantity of code blow up.
When typing filters i noticed that mainParameter with TS was being an issue.

Let us know how the pr goes.

**Comment by kyun** [comment]
Is there any updates?

**Comment by hamzawain7** [comment]
Hi, I tried to take a jab at this, but simply redeclaring the mainParam in child classes didn't fix the TS errors. I think I can remove the mainParameter easily without duplicating the code significantly. This mainParameter seems to add code smell and make the readability/scalability of the code unnecessarily worse while adding little value. 

From what I understand, mainParameter is only used in the isNeutralState function of baseFilters. I can change this function to return false and override it in child classes to return value relative to their defaults. Doing so will also eliminate the 'defaults' class static property in basefilter. This property should be removed, too, as it can have 'any' value. Also, the getMainParameter/setMainParameter aren't used anywhere. Can I remove those, too?

May I make a PR for this?

**Comment by hamzawain7** [comment]
Created a PR (https://github.com/fabricjs/fabric.js/pull/9930). Please check and leme know, thanks.

**Comment by asturur** [comment]
> Hi, can you help me out with something? I have made the changes in the code, but before doing a PR, I want to test all the filters at something similar to http://fabricjs.com/image-filters manually. How can I do that? All the jest tests have passed. Also, I have read the contributions document and related stuff; please guide me with anything I need to know to make contributions. I will try to contribute more to the library in the future, as It has been a great help at my job for the past decade.
> 
> FYI, I have minimum experience in git as we use svn at my workplace so pardon my naivety regarding it.

Sadly the old website won't work with 6.0 and i didn't translate the demo filter yet.
I ll take the occasion to add a test per filter if we don't have one yet.

Regarding your PR, while is fine, i want to see if we can fix the TS code for it rather than changing the underlying code.
The code in your PR is more clear, 100%, i ll re run the PR from an internal branch to measure code size changes, if they are not too many we also move in that direction.

**Comment by hamzawain7** [comment]
Regarding demos, I see a demo folder in the website folder. Will this website be launched in the future? Would you like me to add an image filters demo there and maybe make the demo page a bit better (the UI seemed unfinished)? If you would like, I can move these react demo files to ts/tsx, too.

**Comment by asturur** [comment]
i m exploring a couple of alternatives to solve the issue and add less code or remove code.

I think the simplest one would be to just type mainParameter as string and move on. But i don't dislike the idea of getting rid of it

**Comment by asturur** [comment]
This is so far my favorite solution:
https://github.com/fabricjs/fabric.js/pull/9933

But i didn't test it yet. comments are welcom.

**Comment by hamzawain7** [comment]
Hmm, 

- I don't like having (defaults: Record<string, any>). It is too vague and would probably be complicated to replace that 'any' in there later.

Your modified version of toObject in BaseFilter causes a few problems:

```
...defaultKeys.reduce<Record<string, unknown>>((acc, key) => {
        acc[key] = this[key as keyof this];
        return acc;
      }, {})
```
      
- You can't strongly type the returns of toObject. 
- I don't like the unnecessary coupling of defaults & toObject functiosn; the coder needs to make sure they add keys to defaultKeys; otherwise, those will not appear in the toObject. What if a property can have an undefined value? The coder won't put it in defaultKeys, resulting in that property missing from toObject.

**Comment by asturur** [comment]
in that case you write your own toObject function, exactly how has been written for some of the embedded filters where it was necessary.
Correctly typing toObject is an issue in all fabricJS also for the canvas objects, at some point we will nail it down.

Let me see if i get any type issue with the current code

**Comment by asturur** [comment]
i can strongly type the toObject functions by doing

```
export class BaseFilter<Name extends string, OwnProps extends object> {
```

and then

```
  /**
   * Returns object representation of an instance
   * @return {Object} Object representation of an instance
   */
  toObject(): { type: Name } & OwnProps {
    const defaultKeys = Object.keys(
      (this.constructor as typeof BaseFilter).defaults
    ) as (keyof OwnProps)[];

    return {
      type: this.type,
      ...defaultKeys.reduce<OwnProps>((acc, key) => {
        //@ts-expect-error TS doesn't get i want an object that looks like this
        acc[key] = this[key as keyof this];
        return acc;
      }, {} as OwnProps),
    };
  }
```

Some edge case require to silence an error in which TS can't accept that a property is missing from the toObject function by design, but i think all in all is better since toObject has a clear output.

**Comment by asturur** [comment]
i think the PR https://github.com/fabricjs/fabric.js/pull/9933 fixes the bug and is an overall improvement in code size and stricter typings.

Let me know if you see options for better types or lesser code.

Regarding:

```
I don't like the unnecessary coupling of defaults & toObject functiosn; the coder needs to make sure they add keys to defaultKeys; otherwise, those will not appear in the toObject. What if a property can have an undefined value? The coder won't put it in defaultKeys, resulting in that property missing from toObject.
```
The coder/developer has a lot of options here:
- read how other classes are made
- write his own toObject method
- use public member to assign defaults if they want in their own code

A developer that develops a filter needs anyway to understand that every parameter needs to be bound to a uniform location in webgl and then sendUniform call of the correct type. Is not that toObject is the only tricky part.
