### ISSUE TITLE
[TS]: setVisibility function in Control.ts has unnecessary required params

### ISSUE THREAD

**Issue by hamzawain7** [fabricjs/fabric.js#8920]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta5

### Node Version (if applicable)

None

### Link To Reproduction

https://github.com/fabricjs/fabric.js/blob/master/src/controls/Control.ts#L265

### Steps To Reproduce

1.  Go to https://github.com/fabricjs/fabric.js/blob/master/src/controls/Control.ts#L265
2.  You see unnecessary required params "name" & "fabricObject"
3.  Either make them optional or remove them. I get TS error for not specifying these when using them

### Expected Behavior

Only visibility should be the required param

### Actual Behavior

All three params are marked as required

**Comment by ShaMan123** [comment]
this is the interface...
I am guessing you are subclassing... are you? If so pass them to super.
It shouldn't bother in other cases I think.

**Comment by hamzawain7** [comment]
I was using the function to hide some of the controls by default i.e

fabric.Object.prototype.controls.ml.setVisibility(false);
fabric.Object.prototype.controls.mt.setVisibility(false);
fabric.Object.prototype.controls.mr.setVisibility(false);
fabric.Object.prototype.controls.mb.setVisibility(false);

I thought maybe those two params were left there by mistake during migration, as they weren't there in fabric v5.

**Comment by ShaMan123** [comment]
I understand.
AFAIK it was the same in v5 but TS wasn't there to warn you.
The args are there for subclassing so I assume you can safely disregard the TS error or pass the params.
However controls are created for each instance so you can't use the mentioned way any longer.
Instead try to override this method:
https://github.com/fabricjs/fabric.js/blob/f2090db2afcedc36ef5f0d4fb97e85eef1469a62/src/shapes/Object/InteractiveObject.ts#L150-L156
