### ISSUE TITLE
Add support for `canvas.clipTo` in SVG output

### ISSUE THREAD

**Issue by NaGeL182** [fabricjs/fabric.js#894]
I asked help about SVG clipping mask  in zjr google groups:
https://groups.google.com/forum/#!topic/fabricjs/LRLn2zEZt8E

basically, if i use clipping mask on the canvas, it wont be exported to the SVG. I would be nice if that would be supported.
##

**Comment by AlexanderTserkovniy** [comment]
Any updates on this so far? It would be great to have it.

**Comment by asturur** [comment]
first we need to remove the clipTo entirely and rewrite it so its' exportable.
As of now you can enter a random function in clipTo and that means that is not exportable in svg.

The plan is import clipPaths from SVG, probably remove the clipTo functionality and allow devs to do something similar with a clipPath that is attached to object or to canvas. then export.

At least that is my plan unless someone can suggest something better.

**Comment by asturur** [comment]
this will be part of the new clipping API but it won't export clipTo.

This is then closed without fixing.

**Comment by nitin-bc** [comment]
Hi @asturur @kangax , Do you have a fix for canvas.toclip with SVG export now?
Thanks

**Comment by asturur** [comment]
clipTo is unsupported and going to be removed soon
You can try clipPath now?

**Comment by nitin-bc** [comment]
Hi @asturur I have just tried with clipPath but toSVG() output is not working with clipped object if we use SVG masking image. We have tried with version 2.7, 3.0, 3.1, 3.2. Would you please let me know what can be done?
Thanks

**Comment by nitin-bc** [comment]
> Hi @asturur I have just tried with clipPath but toSVG() output is not working with clipped object if we use SVG masking image. We have tried with version 2.7, 3.0, 3.1, 3.2. Would you please let me know what can be done?
> Thanks

It works well with clipPath using circle, rect, etc. But with SVG it doesn't

**Comment by asturur** [comment]
can you make a non working example so i can understand what you mean?

**Comment by nitin-bc** [comment]
Hi @asturur I have created a [jsfiddle example](https://jsfiddle.net/g4wnqvL5/) to review the issue. Would you please check it? You will need to install [cors add-on](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en) in your chrome browser to check the issue as I have set some of the 3rd party masking and jpg images in the example. Once you will click on "Console Data" for first clipped object then the generated SVG output will be without clipping as I have used the custom mask in the same but once you will click on "Console Data" for 2nd clipped object (clipped by the circle) then we will get clipped output for SVG.

Looking forward to hearing from you soon!

**Comment by asturur** [comment]
Can we have something that does not requires an add-on.
Just put them in a cors allowed domain.
Display both the canvas and the SVG output in the fiddle without button clicks, so everyone can check.

Try to put people that wants to help in condition to do not have to mess around and go straight to the point.
