### ISSUE TITLE
[Bug]: rect.set() works incorrectly Inside group (v6)

### ISSUE THREAD

**Issue by bladerunner2020** [fabricjs/fabric.js#8957]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta6

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/s/fabric-rect-bug-9q62s9?file=/src/index.ts

### Steps To Reproduce

1.  Create a rect 
```js
     const rect = new Rect({ left: 50, top: 50, width: 100, height: 100, fill: 'green', stroke: 'red', strokeWidth: 1 });
```

2. Create a group
```js
const group = new Group([], { backgroundColor: '#add8e6' }, false);
```

3. Add the rect to the group
```js
canvas.add(group);
group.add(rect);
```

4. Set new coordinates and dimensions for the rect and call setCoords()
```js
rect.set({ 
  left: 25, top: 25, width: 200, height: 200
})
rect.setCoords();
```

### Expected Behavior

Expected rect to be displayed  at new coordinates 25, 25  (or 75, 75 ?)  with new dimensions and group is updated accordingly. 

### Actual Behavior

The rect is displayed at 125.1, 125.1 coordinates and clipped outside of the group. The group is unchanged.

<img width="822" alt="image" src="https://github.com/fabricjs/fabric.js/assets/13632647/007ace29-99d1-464f-91be-ef17869d2a17">

BTW
Probably this issue has somehting common with wrong (?) left, top coordinates of rect after adding to group.

**Comment by ShaMan123** [comment]
This is a direct continuation of #8944.
You are looking to set the position in the canvas plane while the object is positioned relative to the group plane (coordinate system)
Doesn't #7670 speak about setXY? That is what you want in this case

**Comment by ShaMan123** [comment]
https://codesandbox.io/s/fabric-rect-bug-forked-n8qdig?file=/src/index.ts

**Comment by bladerunner2020** [comment]
Thank you again! Please excuse my wrong issues, but without your help it would be impossible to find the answer. I did read the most of issues you mentioned (missed some information though). 

I have one more question regarding triggerLayout() - if we have group in group then should we go down along the tree and all triggerLaoyout() on all parents as well?

**Comment by ShaMan123** [comment]
You mean up the tree?
Once called it traverses up the tree by itself.
Down is not needed.
But might be I call it up and you call it down

**Comment by bladerunner2020** [comment]
> You mean up the tree?
> Once called it traverses up the tree by itself.
> Down is not needed.
> But might be I call it up and you call it down

Canvas is a root in my opinion => so I called it down )))
