### ISSUE TITLE
[Feature]: Would like to have feature like offset path or offset svg image bounding box

### ISSUE THREAD

**Issue by Shashank-Bhatt1** [fabricjs/fabric.js#8976]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

Nice library for canvas operations.

I would like to have a feature called offset path similar to what is available in illustrator to create another clippath which is offset (plus or minus) from current object whether it is image, path or whatever.

Similar question i have also found on stackoverflow but with no answer
https://stackoverflow.com/questions/59515009/offsetting-paths-in-fabricjs

I am adding images for how it is from illustrator.
![Screenshot 2023-06-02 122700](https://github.com/fabricjs/fabric.js/assets/24728257/0801bc13-5928-46b4-8df9-4521ff86e3ac)
![Screenshot 2023-06-02 122640](https://github.com/fabricjs/fabric.js/assets/24728257/7401a591-51f8-4841-b689-124333693e47)

This is in need to create clippath where i don't want to have my objects and other stuff. Background can go up to outer path and other stuff should be limited to inner path.

### Current State

Couldn't find anything exactly similar to this.

**Comment by ShaMan123** [comment]
that is on you to do that in your app
