### ISSUE TITLE
[Bug]: text stroke hit different output in ubuntu and window

### ISSUE THREAD

**Issue by RathodAnnu13** [fabricjs/fabric.js#8977]
### CheckList

- [ ] I agree to follow this project's Code of Conduct
- [ ] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [ ] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [ ] I have searched and referenced existing issues and discussions
- [ ] I am filing a **BUG** report.
- [ ] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [ ] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Firefox, Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://codepen.io/Annu-Valand/pen/bGmXwxp

### Steps To Reproduce

Getting different output on window and Ubuntu for text stroke with same value.

Run below attached HTML file on  window and ubuntu environment
[canvasCopy.zip](https://github.com/fabricjs/fabric.js/files/11632876/canvasCopy.zip)

### Expected Behavior

![windowOutput](https://github.com/fabricjs/fabric.js/assets/60641656/d985c62d-b5b7-4c74-95d2-3623418414fd)

### Actual Behavior

![ubuntuOutput](https://github.com/fabricjs/fabric.js/assets/60641656/7a3cf0fe-5bcd-46bf-ae29-fdf398770f0f)

### Error Message & Stack Trace

```bash
Ubuntu behave different from windows for same stroke value.
```

**Comment by ShaMan123** [comment]
not fabric related
node canvas
