### ISSUE TITLE
[Bug]: Creating a component using fabric.Group, the stateProperties property will not trigger _ Render

### ISSUE THREAD

**Issue by rolitter** [fabricjs/fabric.js#8991]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://codepen.io/rolitter/pen/mdQbNXz

### Steps To Reproduce

1. Creating a component using fabric.Group, the stateProperties property will not trigger _ Render
3.

### Expected Behavior

trigger  _ Render

### Actual Behavior

not trigger _ Render

**Comment by ShaMan123** [comment]
1. We do not accept bugs related to group of version < 6
2. state props do not trigger rendering of an object, only of the containing group

test on v6 and if it exists reopen
