### ISSUE TITLE
[Bug]: 6.0.0-beta8 groupSVGElements return width, height incorrect like 5.3.0

### ISSUE THREAD

**Issue by natuan62** [fabricjs/fabric.js#8996]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta8

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/s/throbbing-glitter-ii73g1?file=/src/App.vue:92976-92992

### Steps To Reproduce

1. **loadSvgFromString** with fabric.loadSVGFromString
2. **groupSVGElements** with fabric.util.groupSVGElements
3.  result return width, height incorrect like 5.3.0

My test svg: [my-svg](https://github.com/fabricjs/fabric.js/assets/10808157/887d1962-7106-471d-9b12-aa9d99aadde2)

- fabric 5.3.0 demo
   https://playcode.io/1498135

- fabric 6.0.0-beta8 demo
   https://codesandbox.io/s/hardcore-scott-585bnq?file=/src/App.vue

What I'm wrong or missing something!

### Expected Behavior

Fabric 6.0.0 return width, height of svg group same 5.3.0 version

### Actual Behavior

6.0.0 It return not same width, height like 5.3.0

**- fabric 5.3.0 demo**

![image](https://github.com/fabricjs/fabric.js/assets/10808157/8dc58fae-8b3d-4a79-8b24-5812df51fcfc)

**- fabric 6.0.0-beta8 demo**

![image](https://github.com/fabricjs/fabric.js/assets/10808157/a0a008e5-9c18-4021-8e2f-417876037117)

**Comment by ShaMan123** [comment]
the repro is not useful enough, I want to see the parsed svg on canvas

**Comment by natuan62** [comment]
> the repro is not useful ~enough~, I want to see the parsed svg on canvas

Thanks for your replay. I updated demo link

![image](https://github.com/fabricjs/fabric.js/assets/10808157/d127f5a8-bed2-41af-8a83-7934b822d901)

**Comment by ShaMan123** [comment]
I don't see a problem, the bounding box is precise

**Comment by natuan62** [comment]
Yes. the bounding box is correct
But I want the width, height of groupSVGElements is like 5.3.0 version to calc another things

my svg dims original
 
```
<svg
   width="744.09448819"
   height="1052.3622047"
   ...
>
```

in 5.3.0 after groupSVGElements it's still return dims 
   https://playcode.io/1498135

```
{ "width": 744.09448819, "height": 1052.3622047 }
```

so why in 6.0.0 return another dims number ?
   https://codesandbox.io/s/hardcore-scott-585bnq?file=/src/App.vue

```
{ "width": 248.97280891005425, "height": 1023.4334199894143 }
```

**Comment by ShaMan123** [comment]
#7670
You can access the parsed elements and run custom logic
See loadSVGFromString etc.

**Comment by ShaMan123** [comment]
#7670
You can access the parsed elements and run custom logic
See loadSVGFromString etc.
Or not use groupSVGElements and create a Group with custom layout
