### ISSUE TITLE
toDataURL shows blank page when there is image on canvas

### ISSUE THREAD

**Issue by yusufcan141** [fabricjs/fabric.js#900]
toDataURL method works properly except when there is a image on canvas. When i add an image to canvas and call toDataURL it shows me a blank page.

//When i call it from chrome console
canvas.toDataURL();
//It returns a working data url with no problem.
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPAAAAGkCAYAAAAPPajHAAAgAElEQ…fpmwgogX1TrjoqP0FACewngtZh+iYCSmDflKuOyk8Q+H+CKCqUW0spTgAAAABJRU5ErkJggg=="

//When i execute same code in a .js file it returns a data url which shows a blank image.
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPAAAAGkCAYAAAAPPajHAAAKC0lEQ…sBAmEBAw6XJzoBA/YDBMICBhwuT3QCBuwHCIQFDDhcnugEHt/IAaW9dzALAAAAAElFTkSuQmCC"

It's interesting that it's working on chrome dev console but not works in .js file even if it's same code. I noticed that working data url finishes with '==' but other one not. However i don't know what this means.

**Comment by inkxe-subratS** [comment]
var url = "image_url";
fabric.Image.fromURL(url, function(img) {
  canvas.add(img);
  // call toDataURL after image gets loaded
  console.log(canvas.toDataURL());
});

I have a image url and able to add this on canvas. On toDataUrl() it returns undefined as it shows CROS issue. What to do ? 
I used the above code. Its working if i use local images. When i try to use image present in another sever this issue occurs.
Any help on this ?

**Comment by asturur** [comment]
Yes set cors. Is the server serving the image allowing sharing of resources? can you set headers?

**Comment by inkxe-subratS** [comment]
Is there any way so that i can only deal this within this code ?

**Comment by asturur** [comment]
fabric.Image.fromURL(url, function(img) {
canvas.add(img);
// call toDataURL after image gets loaded
console.log(canvas.toDataURL());
},{crossOrigin: 'anonymous'});

try this, and please check the docs before posting www.fabricjs.com/docs

**Comment by inkxe-subratS** [comment]
Thank you for this source. It works :+1:

**Comment by swatians** [comment]
Need help below code 
 
I have same issue toDataURL shows empty transparent how to fix .. 

<script>

         var video = document.querySelector("#video");
         if (navigator.mediaDevices.getUserMedia) {
              navigator.mediaDevices.getUserMedia({ video: true })
                .then(function (stream) {
                  video.srcObject = stream;
                })
                .catch(function (err0r) {
                  console.log("Something went wrong!");
                });
         }
         var resultb64="";
         function capture() {        
            var canvas = document.getElementById('canvas');     
            var video = document.getElementById('video');
            canvas.width = 450;
            canvas.height = 850;
            canvas.getContext('2d').drawImage(video, 0, 0, 450,850);  
            
            resultb64 = canvas.toDataURL();
            var imageData = canvas.toDataURL('image/png');
            document.getElementById('my_hidden').value = canvas.toDataURL('image/png');

**Comment by swatians** [comment]
Hi

I have same error below code toDataURL shows blank empty transparent image.

Need help how to fix base64 image 

`<script>

         var video = document.querySelector("#video");
         if (navigator.mediaDevices.getUserMedia) {
              navigator.mediaDevices.getUserMedia({ video: true })
                .then(function (stream) {
                  video.srcObject = stream;
                })
                .catch(function (err0r) {
                  console.log("Something went wrong!");
                });
         }
         var resultb64="";
         function capture() {        
            var canvas = document.getElementById('canvas');     
            var video = document.getElementById('video');
            canvas.width = 450;
            canvas.height = 850;
            canvas.getContext('2d').drawImage(video, 0, 0, 450,850);  
            
            resultb64 = canvas.toDataURL();
            var imageData = canvas.toDataURL('image/png');
            document.getElementById('my_hidden').value = canvas.toDataURL('image/png');`

**Comment by swatians** [comment]
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAcIAAANSCAYAAAD24c4vAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAABwqADAAQAAAABAAADUgAAAABbBxkyAABAAElEQVR4AXS92ZIkSZYl5xHhEblUVzX1MgN8FwiE/ycaPADzAExNVWZGxgpmPiLmntUNMVdTVZG7nLvIompq5m/+9//jf/v++fPnp7ff3zy9e/P26euXb0+fPn15+vW3355++fjr02+ffn968/bt05/+9Oen79++0f756fv3p6fPX748vX1+9/T16enp3fMz7294PT295/jzx4/R/vTDD09v4f0G3xsav379+vT5K/xP357evX/P/t3Tty9fn97C9xbdb6h58+Z7Mp7fvo+eU+S/e3r37t3Tx0+fnv7n3/729PffwQT/V+i/fPv69OH5/dOHN9BA++0Ttd+ewPid7QsUvjh/h20cfaPx+zcJwcTu+a1akfMVJjA8//T+6V/+7V+f/uVf/jX7/vt//+9Pv3/87el//a//9emf//IXfPTu6f3b5/ylXcr7yuvtM7wYad3vv398+r//r//76Rew/tu//uvTf/n3f8MPuggdooHmq/iw/Ps77EAvHoj3l19/ffr111+efvjxw9Off/7x6cM7vQpWcL5F/md8+O0bvgKDfn9G8FvEPoOLCBIfIpLtyGf/BXp2T8b4M23v8ds3DP/K9gaffNfvtL/RJ2qSF5V4Kf4PHz6gV3Sn0G6kv5EHX9ie3z0TL2istY3tl1/+/vTf/s//9vTTzz89/fM//8vT3//2y9Nf//pX8upTMt9kb56YDzSxgkc4foOdxvUrmzjEp9/fYfM34rTYQqtT+SumxOAZX5mT5sNX7P2OvXrF1/OH90//+u///vRf/5f/8vSXP//p6ecfPiwntYN4fMF+X185Vr7lvbLePxe27+h9R4zfouM7MTdfvpnUyJb6DfnpqTF6hxFlFQ1vjRM+Mr+/ocP8+P4VTYTJuh/oIx/pY7+SM2+RYZ7Xz4rzdChbHfkPvdqt5mfi/wH+T9jw+fdP+e0tuuEivya//KRPm/P1MfDpX8sz9uncr1+/dG4+vDHfyFPz5gt9SU36kwDg4S/kH/rJWbc3xMS+Ju03YmU47P9vqfzGGPKMfT/h56+I/IzB+lhDno3jZzAxhjy/xW/of8Pxu6+fnj7+9X88/f3/+X/pcx+fflfu8w9P33748ekzsr6iwOzDheg3F8hvZWDHDz++z+/f4fnq2IQtlt+/fHqiuzy9AZdF/1veofe9vgDPGxL+K3Z9Ie7fqTOHygXqIuBMn+vDxhry/dsn8gtZ5o5xfUafY9mvv/zy9JvjHzrevyd/fnj/9PM//VwOfAWv46vjoDzv33+A6g1x/YgPGasOth+JqePf59+/4HNyBv/9Trt99u1bRs3yiwyD3n7r2BAO5P/4/kfizFiL3er7jm1fep0xxNzRbjQ3PnymFX+9IWY/1tehp+84CDzbj9DxzsDqG+qMucxvdRx19ndtle4tPv76/W38yn+HT8p7808iKhGRj+s1VDq2O+4uJ4mDfQtZ7+mv5vHnz7/Xr98Tr5Ia+e/rT8bRXKQeeJ+wwdhh8tNH+pJz2U/IEF9jGtT2TXOyOYnjj/DY79T5XKfXMWx3ANCImQezTrCN4NWe/VqlH9hDbHI5uL0VLCVHmzgc1/E5sINb/40OAXXH0tapFUObAbYjO/GqPznUu1fXxSefck32Z+TaWdce1JxNxUPH5bsy5H2n3PCzPzhgKNlNVPWPb4OXPMrUM9nE6eczGbxhgHzPwGAgxKpN145r93cT5xST5jMDxRsD6oAi/iTPD/LLlz8Bp33qvUV69Ygnm2gw2A5AYQ7niYN0x5baCGc+k53NwdyBYImtyCGRS9ax643FqlY6n+UOrM`

**Comment by gvpratap1997** [comment]
downloadflowchart(node, workflowName) {
    const s = document.getElementById(node);
    if (s != null && s !== undefined) {
      const image = new Image();
      const xml = new XMLSerializer().serializeToString(s);
      image.src = 'data:image/svg+xml;base64,' + window.btoa(xml);
      image.onload = function () {
        const canvas = document.createElement('canvas');
        canvas.width = $($('#' + node)[0]).width();
        canvas.height = $($('#' + node)[0]).height();
        const context = canvas.getContext('2d');
        context.drawImage(image, 0, 0);
        const a = document.createElement('a');
        a.download = workflowName + '.png';
        a.href = canvas.toDataURL('image/png');
        document.body.appendChild(a);
        a.click();
      };
    }
  }



See this output with blank image:
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAXoAAAgHCAYAAAA1hMhcAAAL3ElEQVR4nO3BMQEAAADCoPVPbQdvoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDTAHQgAAHgH4FnAAAAAElFTkSuQmCC

**Comment by akash2408** [comment]
> `Hi`
> 
> I have same error below code toDataURL shows blank empty transparent image.
> 
> Need help how to fix base64 image
> 
> `<script>
> 
> ```
>      var video = document.querySelector("#video");
>      if (navigator.mediaDevices.getUserMedia) {
>           navigator.mediaDevices.getUserMedia({ video: true })
>             .then(function (stream) {
>               video.srcObject = stream;
>             })
>             .catch(function (err0r) {
>               console.log("Something went wrong!");
>             });
>      }
>      var resultb64="";
>      function capture() {        
>         var canvas = document.getElementById('canvas');     
>         var video = document.getElementById('video');
>         canvas.width = 450;
>         canvas.height = 850;
>         canvas.getContext('2d').drawImage(video, 0, 0, 450,850);  
>         
>         resultb64 = canvas.toDataURL();
>         var imageData = canvas.toDataURL('image/png');
>         document.getElementById('my_hidden').value = canvas.toDataURL('image/png');`
> ```

iam also facing the similar issue

**Comment by asturur** [comment]
from the code posted, without seeing the svg is not possible to understand what is going wrong

**Comment by techtic30naitik** [comment]
Thank you very much @kangax

**Comment by aabidkhan0786** [comment]
i m using reactjs... how to handle this error ??
