### ISSUE TITLE
[Bug]: Something wrong with object coordinates inside a group after sibling element removed

### ISSUE THREAD

**Issue by vinkovsky** [fabricjs/fabric.js#9001]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta8

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/s/fabric-rect-bug-forked-czrlfk?file=/src/index.ts

### Steps To Reproduce

Run codesandbox
Wait until the red rectangle is removed
Now you can't select the green circle because the group isn't updating its coordinates.

### Expected Behavior

The green circle must have current coordinates

### Actual Behavior

After removing the red rectangle and setting group top position, the green circle is not selected.

**Comment by vinkovsky** [comment]
I'm sorry, I found a solution. Just added "setCoords()" to the group and the problem went away. But I have another problem related to the group. if I add a rectangle to a nested group, remove it, and add it again, the position of the child group and the objects inside it changes. Please, see https://codesandbox.io/s/fabric-rect-adding-bug-yyg72r?file=/src/index.ts

**Comment by ShaMan123** [comment]
Why are you adding both groups to canvas?
It shouldn't be possible - BUG
https://codesandbox.io/s/fabric-rect-adding-bug-forked-lkxqh4?file=/src/index.ts

Did I achieve what you wanted?

**Comment by ShaMan123** [comment]
Anyways consider using `setXY(100, 100)` from now on if you want an object to really be at 100, 100 instead of relative to the parent

**Comment by vinkovsky** [comment]
> Did I achieve what you wanted?

**Comment by vinkovsky** [comment]
Thanks for the response, @ShaMan123.

> Why are you adding both groups to canvas?
This is my mistake, I didn't mean to do it.

> Did I achieve what you wanted?
Not really. I'll add a little. At the moment I'm using the react-reconciler pkg to write fabric.js logic in a declarative react style.  
For instance, you might have a lot of technical code to create an react app: 

``` const App = () => {
  const [canvasEl, set] = useState(null);
  const fc = useRef(null);
  const circleRef = useRef(null);
  const groupRef = useRef(null);
  const [radius, setRadius] = useState(30);

  useEffect(() => {
    if (!canvasEl) return;
    if (canvasEl.hasAttribute("data-fabric")) return;

    const canvas = (fc.current = new fabric.Canvas(canvasEl, {
      preserveObjectStacking: true,
      enablePointerEvents: true,
      width: window.innerWidth,
      height: window.innerHeight
    }));

    return () => {
      canvas.dispose();
    };
  }, [canvasEl]);

  useEffect(() => {
    const canvas = fc.current;
    if (canvasEl && canvas) {
      const yellowRect = new fabric.Rect({
        fill: "yellow",
        width: 10,
        height: 300,
        left: 370
      });

      const redRect = new fabric.Rect({
        fill: "red",
        width: 10,
        height: 200,
        left: 200
      });

      const circle = (circleRef.current = new fabric.Circle({
        fill: "green",
        left: 200
      }));

      const group = (groupRef.current = new fabric.Group([], {
        objectCaching: false,
        subTargetCheck: true,
        interactive: true
      }));

      const log = console.log;

      group.on("moving", log);
      group.add(circle, redRect);

      canvas.add(yellowRect, group);
      canvas.requestRenderAll();

      return () => {
        group.off("moving", log);
      };
    }
  }, [canvasEl]);

  useEffect(() => {
    const canvas = fc.current;
    const circle = circleRef.current;
    const group = groupRef.current;

    if (circle && group && canvas && canvasEl) {
      circle.set("radius", radius);
      group.triggerLayout();
      canvas.requestRenderAll();
    }
  }, [radius, canvasEl]);

  return <canvas ref={set} />;
};
```jsx

Now you can write this Instead :

```
 const App = () => {
    const [radius, setRadius] = useState(30)      return (         <Canvas
           options={{ preserveObjectStacking: true, enablePointerEvents: true }}
        >
            <rect fill="yellow" width={10} height={300} left={370} />
            <group 
               objectCaching={false} 
               subTargetCheck 
               interactive 
               onMoving={(e) => {console.log(e}}
            >
                <circle
                    fill="green"
                    radius={radius}
                    left={200}
                />
                <rect fill="red" width={10} height={200} left={200} />
            </group>
       </Canvas>     );
}; ```jsx

  So, the problems start when the user updates different values depending on the same variable.   
  
  ```
  <group  top={visible ? 100 : 0}>
     <circle
        fill="green"
        radius={30}
     />
    {visible && <rect fill="red" width={10} height={200} />}
</group>  ```jsx

Under the hood it works exactly like in this [example](https://codesandbox.io/s/fabric-rect-adding-bug-yyg72r?file=/src/index.ts) .

What if I still want to set the position of the group depending on the removed object?
Could you please explain to me whats the difference between left/right opts and setXY? 

`[I tried using Point](https://codesandbox.io/s/fabric-rect-adding-with-point-yp23pq?file=/src/index.ts)`. Group position works as expected but not for red rectangle.

**Comment by ShaMan123** [comment]
This is very elaborate but your problem is not described well enough.
You don't describe the desired result.
How should it look like?
I am guessing.
https://codesandbox.io/s/fabric-rect-adding-bug-forked-lkxqh4?file=/src/index.ts


```jsx
<group top={visible ? 100 : 0}>
  <circle fill="green" radius={30} />
  {visible && <rect fill="red" width={10} height={200} />}
</group>
```


This this  related #8986

**Comment by ShaMan123** [comment]
@bladerunner2020 is [this](https://codesandbox.io/s/fabric-rect-adding-bug-forked-lkxqh4?file=/src/index.ts) what you want?

**Comment by vinkovsky** [comment]
> I am guessing.
> https://codesandbox.io/s/fabric-rect-adding-bug-forked-lkxqh4?file=/src/index.ts

Yes, that's exactly what I need. I updated my reconciler and now it works like a charm. Thank you. But the difference between the setY(100) method and the { top: 100 }  option is still unclear to me :(

**Comment by ShaMan123** [comment]
I think that actually `set('top', 100)` is correct for your use case since it is relative to the parent and not to the canvas.
It means that if the group is not nested under another group it will produce the same outcome but if it is `set('top', 100)` will set the group to 100 as measured inside the parent and not 100 on the canvas.

**Comment by bladerunner2020** [comment]
> @bladerunner2020 is [this](https://codesandbox.io/s/fabric-rect-adding-bug-forked-lkxqh4?file=/src/index.ts) what you want?

Nope. After lot of time spent we put away Fabtic, IDEs and debugging took a pencil and paper. Then we discovered the rea root of our issue and solution.

We are building React wrapper so our needs are:
- we want to use groups to build complex object. Those objects should be used as basic primitive - they can be added to canvas or be part of other objects (groups). So we should be use all features like setting originX/Y when dealing with these objects.
- Objects inside our complex objects (groups) should use relative coordinates. Again we want to use originX/Y when adding objects to a group.
- Objects inside group could be added in an arbitrary order.
- Objects can be removed from a group and then added back based on React props

The key question is how to build a relative coordinate system? If we we add an object using originX = left and group is changed then what is staring point for the next object? If we are adding object with originX = center, but group width is not yet known, how to deal with this?

Our solution looks simple and quite obvious - use "fixed" layout for groups. KISS! :-))

**Comment by ShaMan123** [comment]
I would argue that using the fixed css will deem your solution unworthy for fitting only a single use case.
What happens if you use relative css position??
It is not well defined imo.
Also, fabric is operating on a relative coord system so I don't think you need to code that.
You should read my discussion regarding group layout

**Comment by ShaMan123** [comment]
Since you are using react anyways I would use this concept 
https://github.com/fabricjs/fabric.js/discussions/8986

**Comment by bladerunner2020** [comment]
I read this already. I am not sure if I understand this concept correctly (some examples would be very useful). Though we are using Fabric in React but we want to be able to position objectify precisely by given coordinates. For example, we show office maps and need to accurately put furniture, meeting rooms, desks, POIs, etc. on the map, and show/hide objects based on different filters. We have a JSON which describe our maps, where we specify object locations in mm. 
When we are talking about CSS and html, their main purpose is to show neat pages, adaptive to resolution of user screen.  

So if we are talking about using something like DOM to manage z-order, that I think would be very-very useful, as we badly lack convenient z-order in Fabric. If you want to use CSS-approach to represent objects then I have some doubts. In any case some sample would very useful...

**Comment by bladerunner2020** [comment]
> I would argue that using the fixed css will deem your solution unworthy for fitting only a single use case.
> What happens if you use relative css position??
> It is not well defined imo.
> Also, fabric is operating on a relative coord system so I don't think you need to code that.
> You should read my discussion regarding group layout

I know and we do use relative coordinates in Farbric.
Here is the picture to explain what I meant:

<img width="896" alt="image" src="https://github.com/fabricjs/fabric.js/assets/13632647/440328ba-1134-462b-8ecd-7cc13a281224">

We have a group of 3 rectangles.  In React we have something like this:
```typescript
   <Group id="group1" options={{x: 100, y: 100}}>
       <Rect id="rect1" options={{ x: 0, y: 0, w: 100, h: 50 }}>
       <Rect id="rect2" options={{ x: 200, y: 0, w: 100, h: 50 }}>
      <Rect id="rect3" options={{ x: 200, y: 200, w: 100, h: 50 }}>
   </Group>
```

The group1 coordinate is (100, 100)

Then we removed Rect1 on some user's action:
```typescript
   <Group id="group1" options={{x: 100, y: 100}}>
       <Rect id="rect2" options={{ x: 200, y: 0, w: 100, h: 50 }}>
      <Rect id="rect3" options={{ x: 200, y: 200, w: 100, h: 50 }}>
   </Group>
```
React sees that only one item is removed and unmount event will be called to Rect1. The group itself is unattached. So we just remove rect1 from group (parent container) and call triggerLayout. We get the situation on right picture. The group's coordinates are (300, 0).

So far everything works fine.

But now we want to return rect1. React understands that only one object is added and calls mounting event for rect1.
Now we are in the situation we need to add Rect1 with relative coordinates (0, 0) to the group on right picture.

**Comment by ShaMan123** [comment]
reproduction please

**Comment by bladerunner2020** [comment]
> reproduction please

I just explained why we decided to use fixed group layout. It's not a bug in fabric. So I don't know what kind of reproduction I can do)))

After we spent some time elaborating different approaches we decided to use fixed group layout in our React wrapper.
