### ISSUE TITLE
Text style bug?

### ISSUE THREAD

**Issue by ShaMan123** [fabricjs/fabric.js#9010]
https://github.com/fabricjs/fabric.js/blob/8536cb6149337ac30443d3931b648f136a85dea1/src/shapes/Text/Text.ts#L1609-L1629

Is this a bug?

```diff

- family = this.fontFamily, 
+ family = style.fontFamily, 

```

@asturur ?

**Comment by asturur** [comment]
eh...
so the first bug seems that even if we pass a `styleObject`, this `styleObject` could not have a fontFamily.
For me the correct logic is that fontFamily is either `styleObject.fontFamily` || `this.fontFamily`, and this is valid for everything else, fontStyle, fontWeight and fontSize.

I don't remember the story of this function, please do a deep git blame and try to recover the history of it.

**Comment by asturur** [comment]
i would rather have `styleObject` not optional
and do something like
```
const { fontSize = this.fontSize, fontFamily = this.fontFamily, fontWeight = this.fontWeight, fontStyle = this.fontStyle } = styleObject;
```

But recovering the history is better.

It could totally be me that i have seen an opportunity to save some repetition and i did this `style = styleObject || this`

**Comment by VardaQuraishi** [comment]
@ShaMan123 is this issue available to work on?

**Comment by VardaQuraishi** [comment]
I have made the changes and opened a pull request to it.

**Comment by asturur** [comment]
```
I don't remember the story of this function, please do a deep git blame and try to recover the history of it.
```

Did anyone did a deep git blame to see how this function changed in time?

**Comment by ShaMan123** [comment]
I didn't

**Comment by ShaMan123** [comment]
A bug

BEFORE
https://github.com/fabricjs/fabric.js/commit/b112b3405f75702c5bd1a20dc0e756321d0f9a31#diff-9ba978ec9931806800697f52edd5e63429cd10aad6a5da2d6081cc0d46e44881L832-L839

BLAME
https://github.com/fabricjs/fabric.js/compare/0c65644..abe813f#diff-9ba978ec9931806800697f52edd5e63429cd10aad6a5da2d6081cc0d46e44881R1205-R1210
