### ISSUE TITLE
NS_ERROR_NOT_AVAILABLE: Component not available in Firefox

### ISSUE THREAD

**Issue by andrewtch** [fabricjs/fabric.js#903]
I have canvas object with image patterns; when I try to save canvas (to JSON, to DatalessJSON and toObject) and then load the state (both data/dataless ways) I get the following error in firefox:

NS_ERROR_NOT_AVAILABLE: Component not available in Firefox

this error happens in Pattern.toLive method:

```
toLive: function(ctx) {
    var source = typeof this.source === 'function' ? this.source() : this.source;
    return ctx.createPattern(source, this.repeat);
  }
```

unfortunately, this error happens even if I create a pattern from base64 string which makes me unable to load the canvas from object. I'd be happy to preload the images, but in doesn't work even with base64 encoded images which does not need loading.

Any help?

**Comment by asturur** [comment]
@effepi i got same issue, if  you add width and heigth to the svg this does not happen.
I think i-m goin to pull a fix for this.
