### ISSUE TITLE
[Bug]: Selection shouldn't work outside clipPath

### ISSUE THREAD

**Issue by mariusrak** [fabricjs/fabric.js#9034]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta9

### In What environments are you experiencing the problem?

Firefox, Chrome, Safari, Opera, Microsoft Edge

### Node Version (if applicable)

None

### Link To Reproduction

http://fabricjs.com/clipping

### Steps To Reproduce

1. Hover part of an image that is outside of its `clipPath`, i.e. not visible
2. Cursor changes to "move"
3. After click, the image is selected

### Expected Behavior

Cursor and events should behave as if there is no object on that position.

Cut - invisible parts should not fire events.

### Actual Behavior

Object is selected even if that part is cut.

If this is expected behavior, then we need a way to alter it.

**Comment by ShaMan123** [comment]
perPixelTargetFind

**Comment by ShaMan123** [comment]
however with area selection it is not respected

https://github.com/fabricjs/fabric.js/assets/34343793/9128b88b-1829-4a10-af13-ea7b0631a1fe

**Comment by ShaMan123** [comment]
If you want it to you will need to override `collectObjects` and do pixel testing after clipping the shape with the area
look at `isTargetTransparent`

**Comment by diegosystem32** [comment]
Can you post an example of a case that worked, I also need this solution?
