### ISSUE TITLE
[Bug]: Cloning elements to new canvas with v6?

### ISSUE THREAD

**Issue by orenlwsc** [fabricjs/fabric.js#9049]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta9

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/s/recursing-goodall-9vp5rf?file=/src/exporter.ts

### Steps To Reproduce

1. create a new canvas on load (auto-adding items into it)
2. export it to PNG
3. image is scaled correctly, but the original canvas is also being modified

I tried to use cloneDeep from `lodash`, but it doesn't work. And since the `fabric.object.utils.clone` is deprecated in v6, I'm not sure what the proper way to clone items to a new canvas in v6. [Attached codesandbox to demonstrate the issue](https://codesandbox.io/s/recursing-goodall-9vp5rf?file=/src/exporter.ts)

I must be overlooking something, any help appreciated.
Thank you!

### Expected Behavior

create a new canvas, copy over items, scale them without touching the original canvas

### Actual Behavior

scaling both canvases (the visual and the shadow one made for exporting)

**Comment by ShaMan123** [comment]
Why are you reimplementing toCanvasElement instead of using fabric's?
Your impl is wrong. I can detail what etc. but I don't think there is a reason.
Use fabricCanvas.toCanvasElement

**Comment by orenlwsc** [comment]
@ShaMan123 ok, gotcha. Was hard to find this method exists. However, from what I understand, it creates a new native canvas with the copied elements.

My final goal (not mentioned in the ticket, my bad) is to scale the given elements before turning them into images. Say I want to work on graphics for a Vertical Full HD image (1080x1920), but my workspace is also the same size so that I can see only half of the canvas. My idea is to create a smaller scale canvas (540x960), and once exporting, I'm multiplying the parameters of each element by the correct scale (2 in our case)

I imagine there are much easier ways to achieve it. Maybe zoom?

**Comment by ShaMan123** [comment]
I believe so

**Comment by orenlwsc** [comment]
@ShaMan123 still needs to resolve my problem - how can I create a clone of active fabric canvas? I need a fresh new copy of fabric which I can manipulate without touching the original noe

**Comment by ShaMan123** [comment]
Canvas#clone?
