### ISSUE TITLE
[TS]: Incorrect canvas backgroundImage type

### ISSUE THREAD

**Issue by hamzawain7** [fabricjs/fabric.js#9050]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta9

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

20.2.0

### Link To Reproduction

https://github.com/fabricjs/fabric.js/blob/master/src/canvas/StaticCanvas.ts#L114

### Steps To Reproduce

1.  Go to https://github.com/fabricjs/fabric.js/blob/master/src/canvas/StaticCanvas.ts#L114
2.  Type is FabricObject instead of Image

### Expected Behavior

Canvas backgroundImage should be of type Image

### Actual Behavior

Canvas backgroundImage is of type FabricObject

**Comment by ShaMan123** [comment]
This is because it can be an object of any kind.
A bad prop with a bad name IMO
