### ISSUE TITLE
[Bug]: Unable to retrieve active selection in fabricjs v5 from "selection:created" event

### ISSUE THREAD

**Issue by flexeo** [fabricjs/fabric.js#9053]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

Unable to retrieve active selection in fabricjs v5 from "selection:created" event

### Steps To Reproduce

Before v5 it was possible to dynamically change the visibility of controls during a multiple selection, but this is no longer possible as the **target** property no longer exists.

```
 canvas.on({
      'selection:created': (e, j) => {
        const activeSelection = e.target
        activeSelection.setControlsVisibility({
                mb: false,
                ml: false,
                mr: false,
                mt: false,
        });
      }
  })
```

### Expected Behavior

The **target** property should be accessible.

### Actual Behavior

Is there another way of retrieving the active selection to interact with controls?

**Comment by ShaMan123** [comment]
Provide a repro in v6 and then reopen

**Comment by flexeo** [comment]
Do you have a solution for Fabricjs v5? 

How to retrieve the current selection when the user selects several objects on the scene?

**Comment by ShaMan123** [comment]
I do
But I asked you to reproduce so we can address your ticket if the bug is real
This is open source, we do not work for anyone
getActiveObject
