### ISSUE TITLE
[Bug]: when a char‘s deltay too large, the char out of textbox and is splited when using toDataURL 

### ISSUE THREAD

**Issue by Source-Code-Sivir** [fabricjs/fabric.js#9056]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta9

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

set large deltay to a char, and it will excedd textbox and disappear in todataurl

### Steps To Reproduce

1. set a large deltay to a char in styles 
![image](https://github.com/fabricjs/fabric.js/assets/50519354/c515dfea-d736-48d0-a548-4a85e9bb13af)

2. in broswer, the char exceed textbox 
![image](https://github.com/fabricjs/fabric.js/assets/50519354/e9a405fe-de69-48a3-bb9d-6f3c7969e4b7)

3.when use toDataURL() the char will be splited by text box 
![image](https://github.com/fabricjs/fabric.js/assets/50519354/c553b547-a825-4bec-a635-3ed9e954fd95)

### Expected Behavior

i read the relative code, it seems that when calculate the text box the deltay is not considered, and when toDataURL, only width and height of the text box is used, deltay is related to the char y pos, but when calculate text box height it is ignored,is it reasonable？

### Actual Behavior

![image](https://github.com/fabricjs/fabric.js/assets/50519354/3ca02d63-970f-461c-8709-f647a2cebf10)
![image](https://github.com/fabricjs/fabric.js/assets/50519354/e015b37d-8748-435e-91f9-8a877bb5b060)

**Comment by ShaMan123** [comment]
easy as it is to reproduce (seems straight forward) I am closing until you provide the mandatory reproduction
