### ISSUE TITLE
[Bug]: when the object has Padding or strokeWidth, when scaling it to be small , the object size is not correct

### ISSUE THREAD

**Issue by senschen** [fabricjs/fabric.js#9057]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

16.20.0

### Link To Reproduction

http://fabricjs.com/controls-customization

### Steps To Reproduce

1.  go to the demo page: http://fabricjs.com/controls-customization
2. set the padding to a big value
![image](https://github.com/fabricjs/fabric.js/assets/8544826/ace88401-2cbc-4e71-aebb-eb9d10a9ca65)

3. scale it to small
![image](https://github.com/fabricjs/fabric.js/assets/8544826/1160b8d1-ea44-445b-91b7-0fd097b35623)

### Expected Behavior

object resize to be small

### Actual Behavior

object is small first , then it return to be big,  then start to be small again 
(fabricjs before v4.0.0 could works well)

### Error Message & Stack Trace

```bash
no error message throwed
```

**Comment by ShaMan123** [comment]
Add a repro and a video
