### ISSUE TITLE
[Bug]: when set activeselection to select multi objects ,then drag or click to sleect this activeselection, it will unset this activeselection or select one of this area objects

### ISSUE THREAD

**Issue by m3360202** [fabricjs/fabric.js#9063]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta9

### Node Version (if applicable)

None

### Link To Reproduction

Next template >= v6

### Steps To Reproduce

1.  use new activeselection() ,const target = new activeselection(canvas.getObjects(),{canvas});
2. setActiveSelection(target); canvas.requestRenderAll()
3.click this area or drag,the activeselection will be unseted

### Expected Behavior

this activeselection can run well

### Actual Behavior

![QQ截图20230705214646](https://github.com/fabricjs/fabric.js/assets/36294167/ef3b07a3-7595-406b-a867-44e662e23164)
![QQ截图20230705214703](https://github.com/fabricjs/fabric.js/assets/36294167/dbbd5a0b-9151-4b44-8e32-ffc4d8da8539)

### Error Message & Stack Trace

```bash
no error message
```

**Comment by ShaMan123** [comment]
Provide a reproduction and reopen
