### ISSUE TITLE
[Bug]: Setting imageSmoothingEnabled to false seems to be ignored

### ISSUE THREAD

**Issue by greentfrapp** [fabricjs/fabric.js#9065]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Firefox, Chrome, Safari

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/p/sandbox/imagesmoothingenabled-bug-65vyqr

### Steps To Reproduce

**Steps**
1. Set `imageSmoothingEnabled: false` when initializing a new fabric.Canvas
2. Add an image using `fabric.Image` and zoom in via `zoomToPoint` or scale up the image
3. Image is still smoothed despite `imageSmoothingEnabled: false`

**Additional Notes**
Using `fabric.util.setImageSmoothing` seems to work but only if image is added directly to the canvas context. Adding an image via `fabric.Image` still shows the same bug.

The image used in the example is from this 2017 StackOverflow post
https://stackoverflow.com/questions/43385264/keep-pixels-sharp-after-zoom-with-fabricjs
Unfortunately, the code snippet provided in that post no longer works as expected.

The CodeSandbox sample above is on fabric v5, which I am more interested in.
But the same bug appears in v6, see sample here https://codesandbox.io/p/sandbox/fabric-vanillajs-sandbox-forked-kx3gjx

### Expected Behavior

Image should clearly show well-defined pixels when zoomed in or scaled up.

![image](https://github.com/fabricjs/fabric.js/assets/13292973/b74bcb2b-cafc-4cc5-b10b-aecc7a473f17)

### Actual Behavior

Image is smoothed when zoomed in or scaled up.

![image](https://github.com/fabricjs/fabric.js/assets/13292973/da8a02bd-c0ee-47f8-8dc3-b0516b02d7ca)

**Comment by ShaMan123** [comment]
did you try setting on the image instance?

**Comment by ShaMan123** [comment]
![image](https://github.com/fabricjs/fabric.js/assets/34343793/8c9a779e-7365-480b-8c23-5ae7e1914985)

https://codesandbox.io/p/sandbox/fabric-vanillajs-sandbox-forked-mfsczt?file=%2Fsrc%2Findex.ts%3A17%2C35

**Comment by greentfrapp** [comment]
That works, thanks @ShaMan123 let me know if there's somewhere I can help to add documentation on this
