### ISSUE TITLE
[Bug]: SVG Images loaded as HTML Image and passed to fabric.Image constructor then scaled display differently in Firefox than Chrome

### ISSUE THREAD

**Issue by glennflanagan** [fabricjs/fabric.js#9074]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Firefox

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/s/delicate-star-mp25rg

### Steps To Reproduce

1. Create a canvas 
2. Load an image as an `img` element using `fabric.util.loadImage`
3. Create a new `fabic.Image` instance passing the `img` element as the ImageSource
4. Scale the image instance in non-uniform values using the `.scaleX` and `.scaleY` properties
5. Add the image to the canvas
6. Observe the image on the canvas displays differently in Firefox than in Chrome or Safari. (e.g. https://mp25rg.csb.app/)

### Expected Behavior

The image on the canvas should be scaled non-uniformly to the values set by the `scaleX` and `scaleY` properties.

### Actual Behavior

It seems the visual in Firefox is scaled uniformly and doesn't respect the scale properties.

### Error Message & Stack Trace

```bash
No errors.
```

**Comment by glennflanagan** [comment]
Screenshot of Chrome (left) and Firefox (right)
<img width="2560" alt="Screenshot 2023-07-06 at 15 17 27" src="https://github.com/fabricjs/fabric.js/assets/5485364/bf7c3238-5521-44c0-9b0d-9c57437e62e8">

**Comment by glennflanagan** [comment]
So turns out its a flipping browser bug. Firefox is respecting the default value for `preserveAspectRatio` SVG attribute (`xMidYMid meet`) when the CanvasRenderingContext2D drawImage method is used to paint the image source on the context. 

This is an example without using fabric

https://codesandbox.io/s/eager-cartwright-ksm22w?file=/src/index.js

**Comment by ShaMan123** [comment]
So if it is not us I am closing
You should open on chromium

**Comment by glennflanagan** [comment]
Yes of course. I forgot to close the issue myself.
