### ISSUE TITLE
[Bug] ActiveSelection changes objects position

### ISSUE THREAD

**Issue by ShaMan123** [fabricjs/fabric.js#9087]
### Discussed in https://github.com/fabricjs/fabric.js/discussions/9084

<div type='discussions-op-text'>

<sup>Originally posted by **xorb** July 10, 2023</sup>
ActiveSelection moves objects randomly.  

Demo:
https://codesandbox.io/p/sandbox/fabric-artboard-forked-rxkvm4?file=%2Fsrc%2FApp.tsx%3A110%2C10

Steps to reproduce: 
1. Select multiple objects
2. Rotate active selection
3. Create a new selection either using pointer or using button: select all objects
 
[active-selection-issue.webm](https://github.com/fabricjs/fabric.js/assets/39509710/9ba062b6-8ca1-44a6-8217-cba8ad2dbc5a)

@ShaMan123 can you take a look ?</div>

**Comment by ShaMan123** [comment]
select all objects
rotate selection
deselect
select all object
objects have moved

https://codesandbox.io/s/k9p2dt

**Comment by ShaMan123** [comment]
@xorb try #9088

**Comment by xorb** [comment]
Seems to be working fine now
