### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by JessYan0913** [fabricjs/fabric.js#9126]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

16.14.2

### Link To Reproduction

https://codesandbox.io/p/sandbox/fabric-vanillajs-sandbox-forked-ngdv8d?file=%2Fsrc%2Findex.ts%3A13%2C25

### Steps To Reproduce

When I added control points to the vertices on the Polyline, I found that when the vertices were moved outside the original bounding box through the control points, the bounding box did not change
1. Customize a Polyline inherited from fabric.Polyline
2. Rewrite the onSelect method of Polyline, and realize the logic of adding control points according to the vertices
3. Render the polyline instance in Canvas and select the polyline
4. Select one of the control points and drag out the initial bounding box

### My full code is as follows:

```typescript
import { fabric } from 'fabric';

export class Polyline extends fabric.Polyline {
  public onSelect(options: { e?: Event | undefined }): boolean {
    const points = this.points ?? [];
    this.controls = points.reduce<Record<string, fabric.Control>>(
      (controls, point, index) => {
        controls[`p${index}`] = new fabric.Control({
          actionName: 'modifyPolyline',
          positionHandler: (dim, finalMatrix, fabricObject: Polyline): fabric.Point => {
            const x = point.x - fabricObject.pathOffset.x;
            const y = point.y - fabricObject.pathOffset.y;
            return fabric.util.transformPoint(
              new fabric.Point(x, y),
              fabric.util.multiplyTransformMatrices(
                fabricObject.canvas?.viewportTransform ?? [],
                fabricObject.calcTransformMatrix()
              )
            );
          },
          actionHandler: (eventData, transformData, x, y): boolean => {
            const polyline = transformData.target as Polyline;
            const invertedMatrix = fabric.util.invertTransform(polyline.calcTransformMatrix());
            const transformedPoint = fabric.util.transformPoint(new fabric.Point(x, y), invertedMatrix);
            // 更新点的位置
            points[index].x = transformedPoint.x + polyline.pathOffset.x;
            points[index].y = transformedPoint.y + polyline.pathOffset.y;
            // 重新设置points
            polyline.points = points;
            // 更新坐标
            polyline.setCoords(true);
            polyline.canvas?.renderAll();
            return true;
          },
        });
        return controls;
      },
      { ...this.controls }
    );
    return super.onSelect(options);
  }
}

export default Polyline;
```

### Expected Behavior

When dragging the vertices of the polyline, the bounding box should update accordingly

![Kapture 2023-07-26 at 22 55 47](https://github.com/fabricjs/fabric.js/assets/52144974/d9b92ce4-6a3e-4045-956e-fdd85f94d8d8)

### Actual Behavior

But when I drag the vertices, I found that although the vertices are moved, the bounding box is not updated

![Kapture 2023-07-26 at 22 58 51](https://github.com/fabricjs/fabric.js/assets/52144974/1c62cb89-bb38-4902-b234-f35ca7f4703f)

**Comment by ShaMan123** [comment]
Solved in v6, createPolyControls
