### ISSUE TITLE
[Bug]: `Polyline` will be offset when the mouse draws Polyline

### ISSUE THREAD

**Issue by JessYan0913** [fabricjs/fabric.js#9127]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta9

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

16.14.2

### Link To Reproduction

https://codesandbox.io/p/sandbox/fabric-vanillajs-sandbox-forked-ngdv8d?file=%2Fsrc%2Findex.ts%3A51%2C19

### Steps To Reproduce

I'm trying to draw a `Polyline` with the mouse, but I found that when the mouse is moved to the far left of the point set of `Polylien`, the `Polyline` moves to the right. When the mouse moves to the top of the point set of `Polyline`, `Polyline` will move down.

1. Create polyline on mousedown
2. Add new points to polyline points when the mouse moves
3. Double-click the mouse to end the polyline drawing

### Expected Behavior

![Kapture 2023-07-27 at 21 52 37](https://github.com/fabricjs/fabric.js/assets/52144974/d52e51f2-be13-49e3-8faf-fa36f0cf8752)

### Actual Behavior

![Kapture 2023-07-27 at 21 41 38](https://github.com/fabricjs/fabric.js/assets/52144974/05865781-8a28-4b3a-bc51-087bdf02b7f4)

**Comment by ShaMan123** [comment]
#8430
