### ISSUE TITLE
[Feature]: Accesing selected canvas adding elements in the multiple fabricjs canvas 

### ISSUE THREAD

**Issue by Suriyasanjay** [fabricjs/fabric.js#9131]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

 useEffect(() => {
    // const canvas = new fabric.Canvas(canvasRef.current)
    for (var i = 0; i < canvasList.length; i++) {

   
   
      const canvasId: any = document.getElementById(canvasList[i]) 
   
    const canvas = new fabric.Canvas(canvasId ,{
      // preserveObjectStacking:true,
      // selectionBorderColor:'green',
      // isDrawingMode:true

      
    })
    
    fabric.Object.prototype.cornerColor='green'
  // canvas.calcOffset()
 

    console.log(canvas)
    
    fabric.Object.prototype.transparentCorners = false;
    // canvas.loadFromJSON(initialJson, canvas.renderAll.bind(canvas))
    canvas.on('object:modified', handleObjectModified);
    const handleSelection = () => {
      const activeObject = canvas.getActiveObject();

      console.log(activeObject?.type)
      console.log(line)
    }
    setCanvas(canvas)
    canvas.on('selection:created', handleSelection);
    canvas.on('selection:updated', handleSelection);
    canvas.on('selection:cleared', handleSelection);
    return () => {
      canvas.off('selection:created', handleSelection);
      canvas.off('selection:updated', handleSelection);
      canvas.off('selection:cleared', handleSelection);
      canvas.off('object:modified', handleObjectModified);

      canvas.dispose();
     
    };
  
  
    }
  }, []);

### Current State

I have tired passing values  currently selected canvas but cound not  it is enetering in first canvas alone i cannot  add elements in the second add canvas in react ?? what is solution for adding shapes in the current selelcted canvas ......

**Comment by ShaMan123** [comment]
This is not a valid ticket
Open a discussion, add repro links as we state is a MUST and write a description

**Comment by Suriyasanjay** [comment]
i can't understand

**Comment by ShaMan123** [comment]
Same here
A live working reproduction is a must
A description that is not code
Following the template
