### ISSUE TITLE
[Feature]: How to select members in the group？

### ISSUE THREAD

**Issue by zhe-he** [fabricjs/fabric.js#9138]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

I will operate the members in the frame(extends group), and drag the sub-element a of frame A into frame B.

This requirement will be fulfilled if it is possible to support the selection of member a in group A.

### Current State

The following is the bug video that appears after the child elements in the group are forced to be selected.
```
import { useEffect, useRef } from "react";
import { Canvas, Rect, Group, ActiveSelection } from "fabric";

let canvas: Canvas;
export function Test() {
    const ref = useRef(null);

    const select = () => {
        const g = canvas.getObjects()[0] as Group;
        const a = g.getObjects()[0];
        const b = g.getObjects()[1];
        const c = new ActiveSelection([a, b]);
        canvas.setActiveObject(c);
        canvas.renderAll();
    };

    useEffect(() => {
        if (!ref.current) return;
        canvas = new Canvas(ref.current);
        canvas.setDimensions({ width: 800, height: 600 });

        const rect1 = new Rect({ top: 10, left: 10, width: 100, height: 100, fill: "red" });
        const rect2 = new Rect({ top: 20, left: 20, width: 100, height: 100, fill: "yellow" });
        const rect3 = new Rect({ top: 30, left: 30, width: 100, height: 100, fill: "blue" });
        const g = new Group([rect1, rect2, rect3]);
        canvas.add(g);

        return () => {
            canvas.dispose();
        }
    }, []);

    return (
        <div>
            <button onClick={select}>select</button>
            <canvas ref={ref}></canvas>
        </div>
    )
}

```

https://github.com/fabricjs/fabric.js/assets/11306583/720c821e-4ca2-4edb-8d82-36e27efc7fcb

**Comment by ShaMan123** [comment]
#7670
subTragetCheck, interactive props of group must be true
V6 only
