### ISSUE TITLE
[TS]: originX & originY number values

### ISSUE THREAD

**Issue by wc19950724** [fabricjs/fabric.js#9150]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [x] I have searched and referenced existing issues, feature requests and discussions
- [x] I am filing a **FEATURE** request.

### Description

In fact, the types of originX and originY can be numbers, but on type declarations, they can only be strings

### Current State

I hope to support the number type in the type declaration

### Additional Context

![image](https://github.com/fabricjs/fabric.js/assets/59589936/ae66ab38-b397-45db-a315-70fe14f5ba65)

**Comment by ShaMan123** [comment]
You are right, this is a type error.

**Comment by ShaMan123** [comment]
> ~You are right, this is a type error.~

After looking at the codebase I do not see this so I conclude you are using an old version of fabric.
Please do NOT open tickets on regarding versions

**Comment by mattevans-dev** [comment]
Hi @ShaMan123, I've just seen this and wanted to double check. Can you only use strings for originX/Y in v6?

In v5 you could set numeric values relative to the object (e.g 0.5 being the same as 'center').
In our case we're building an animation app and having a numeric value is very useful as it allows the user to set a custom anchor point outside the bounds of the object (e.g rotating around a point, or scaling from a point.)
Is this something that may be supported in the future?

**Comment by ShaMan123** [comment]
Please disregard this ticket.
It was written by someone confused by versiins or the dead definitelytyped package
