### ISSUE TITLE
[Bug]: svg parsed result's position is wrong

### ISSUE THREAD

**Issue by poi-mashiro** [fabricjs/fabric.js#9156]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Microsoft Edge

### Node Version (if applicable)

None

### Link To Reproduction

https://codepen.io/poooooi/pen/QWzLvZP

### Steps To Reproduce

1. parse svg with `loadSVGFromString`
2. new group with parsed result
3. add group to canvas

sorry, I don't know how to reproduction it in v6-beta

### Expected Behavior

fabric's render result  should same with html svg

### Actual Behavior

![image](https://github.com/fabricjs/fabric.js/assets/29301772/8358dab3-e749-4dfb-9296-9fcb30cdcee9)

**Comment by ShaMan123** [comment]
please try v6

**Comment by poi-mashiro** [comment]
I tried，but I don't know how to set right position due to  v6 return `fabric.Object` by each obj uses callback once.
In v5, I find this case can be avoid by 
```
            fabric.loadSVGFromString(svgString, (obj, opt) => {
                const rect = new fabric.Rect({
                    left: 0,
                    top: 0,
                    width: opt.width,
                    height: opt.height,
                    fill: 'transparent',
                });
                obj.unshift(rect);
                const group = new fabric.Group(obj, {
                    ...opt,
                    left: 0,
                    top: 0,
                });
                canvas.add(group);
            });
```

**Comment by ShaMan123** [comment]
I can't understand your comment

**Comment by poi-mashiro** [comment]
In v6
viewBox="0 0 1242 2208"
```css
            svg {
                background: #f00;
            }
```
```js
            var canvas = new fabric.Canvas('canvas', { preserveObjectStacking: true });
            const group = new fabric.Group();
            canvas.setZoom(400 / 1242);
            fabric.loadSVGFromString(svgString, (element, obj) => {
                group.add(obj);
                canvas.add(group);
            });
```
As a result, space on the outside of the shape is lost.
![image](https://github.com/fabricjs/fabric.js/assets/29301772/15fff46c-9d6b-4b6d-87c7-393da120552f)

I find a way to aviod this case  like v5.
```js
            var canvas = new fabric.Canvas('canvas', { preserveObjectStacking: true });

            const group = new fabric.Group([], {
                borderColor: '#00f',
            });
            const size = svgString
                .match(/viewBox=".+"/g)[0]
                .replace(/(viewBox=")|(")/g, '')
                .split(' ');
            console.log(size);
            const rect = new fabric.Rect({
                left: 0,
                top: 0,
                width: Number(size[2]),
                height: Number(size[3]),
                fill: '#0f0',
            });
            group.add(rect);

            canvas.setZoom(400 / 1242);

            fabric.loadSVGFromString(svgString, (element, obj) => {
                group.add(obj);
                canvas.add(group);
            });
```
![image](https://github.com/fabricjs/fabric.js/assets/29301772/07c36542-1a7f-4bee-a64c-894f6600d92e)

**Comment by asturur** [comment]
if you limit to add the object to canvas, the position is correct:

<img width="1162" alt="image" src="https://github.com/fabricjs/fabric.js/assets/1194048/822d0bcb-d82a-43a0-8b79-fce03d1f60d0">

**Comment by asturur** [comment]
also not using opt seems to work fine

```js
            fabric.loadSVGFromString(svgString, (obj, opt) => {
                const group = new fabric.Group(obj);
                canvas.setZoom(400 / opt.width)
                canvas.add(group);
            });
```

**Comment by poi-mashiro** [comment]
In this svg case, after SVG parsing, if you do not use opt, it is directly added to a group, which will make it difficult to replicate the same scaling of the SVG DOM, that sets scale to the group. In the actual use of SVG, usually add all shapes to the group to facilitate operation, at this time, the size of the group should be the same as the size of the SVG DOM, which is more in line with expectations, in this svg case, if the parsed results are directly added to the group, it will cause the loss of a circle of transparent space between the shape and the entire SVG DOM. I think using opt is a must. 

Will you add a shape to represent the size of the entire SVG DOM when parsing SVG in the future?

**Comment by asturur** [comment]
this was never the case with fabricjs. I understand you want to preserve the whitespace, for now you can just create a transparent rect with width and height taken from opt, strokewidth set to 0 and add it to the group together with the other objects, bottom of the stack. Should so the trick.

**Comment by poi-mashiro** [comment]
OK. You can close this issue.

**Comment by asturur** [comment]
let us know if that solution works, then we can close

**Comment by poi-mashiro** [comment]
After using opt to create a rectangle and add it to the group, it solves the problem in this SVG case. I think you can close this issue.
