### ISSUE TITLE
[Feature]: bundle all the d.ts files to a single file.

### ISSUE THREAD

**Issue by BD-Joy** [fabricjs/fabric.js#9158]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

Currently, I upgrade the fabric  to version 6.0.0-beta10 in my project, but I found the DefinitelyTyped only support the 5.3.
[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/fabric/index.d.ts)

So, I must build the version 6.0.0-beta10 to generated the `@types` files, but I found so many d.ts files in the `dist` folder.
![image](https://github.com/fabricjs/fabric.js/assets/7828364/c65498e9-489f-4d14-9f5e-ca25c9d35003)

So, please bundle all the d.ts files to a single file, such as using by the [@microsoft/api-extractor](https://api-extractor.com/).

### Current State

Many d.ts files generated in the `dist` folder.

**Comment by ShaMan123** [comment]
You should stop using DefinitelyTyped

**Comment by BD-Joy** [comment]
@ShaMan123  

Yes, I have discard the DefinitelyTyped. and use the types of the version 6.0.0-beta10.  but it contains so many d.ts files.

My question is how to bundle all the d.ts files to a single file.

**Comment by ShaMan123** [comment]
read TS docs
