### ISSUE TITLE
[Bug]: Nothing is rendered on IOS WeChat browser when the canvas is too large

### ISSUE THREAD

**Issue by chuyun** [fabricjs/fabric.js#9159]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Safari

### Node Version (if applicable)

14.21.3

### Link To Reproduction

none

### Steps To Reproduce

```
  const canvas = new fabric.StaticCanvas('c', {
      width: 3165,
      height: 844,
      backgroundColor: 'red',
    });
    const rect = new fabric.Rect({
      width: 40,
      height: 40,
      top: 0,
      left: 0,
      fill: 'green',
    });
    canvas.add(rect);
```
open width  IOS WeChat browser

### Expected Behavior

rendering normal

### Actual Behavior

do not render

**Comment by ShaMan123** [comment]
This is not our fault so it seems, out of memeory error probably,
If you manage not to reproduce without fabric (bare html canvas) I will reopen
