### ISSUE TITLE
Customized object initialization in fabric.js?

### ISSUE THREAD

**Issue by flexeo** [fabricjs/fabric.js#9170]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://stackoverflow.com/questions/65202589/customized-object-initialization-in-fabric-js

### Steps To Reproduce

I have an older fabric.js project that I want to modernize.
In this project there are user defined attributes that should be considered during object initialization.
The following example should show how it was solved in the original project:

```
fabric.Object.prototype.initialize = (function (initialize) {
    return function (element, options) {
        let lock = element.lock;
        element.lockMovementX = lock; 
        element.lockMovementY = lock;
        return fabric.util.object.extend(initialize.call(this, element, options), {});
})(fabric.Object.prototype.initialize);
```

But that doesn't work anymore.

I don't find the problem myself and haven't found any examples of customized object initialization.

I would be happy if someone could help me. Thanks!

### Expected Behavior

Initialization in fabric.js

### Actual Behavior

Initialization in fabric.js

**Comment by lh-sn** [comment]
This should work for you.

```ts
 fabric.Object.prototype.initialize = (function (initialize) {
    return function (_options) {
      const options = {...yourCustomOptions, ...(_options ?? {})}
      
      return initialize.apply(this, [options]);
    };
  })(fabric.Object.prototype.initialize);
```

**Comment by lh-sn** [comment]
Also, maybe consider upgrade to V6 instead of 5.x.

**Comment by flexeo** [comment]
It works perfectly ! Thanks !
