### ISSUE TITLE
[Bug]: Textbox input seems completely off

### ISSUE THREAD

**Issue by asturur** [fabricjs/fabric.js#9190]
In current master textbox input seems completely broken.
Adding new lines does not add  new lines after the first one.

- double check that is actually broken after a night of sleep
In case is broken:
- identify the commit that broke it
- revert the commit
- re-evaluate what to do

**Comment by ShaMan123** [comment]
Strange.
I am working on latest beta
Tested last time thoroughly beta10 and it was as expected

**Comment by asturur** [comment]
testing commit by commit it looks like this pr broke it
https://github.com/fabricjs/fabric.js/pull/9097

Now i have to find where. hopefully is evident.

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/pull/9097/files#diff-25ec98d446b9f1934b6a36a8784e77fed6b0bf5304a0f95fc7155ad93dfd6d33

There are enough changes here to grant a breakage for sure

**Comment by asturur** [comment]
update the issue is for splitByGrapheme only, that makes it still important but not critical at least
