### ISSUE TITLE
[Bug]: The eraser's erasure path is displaying abnormally

### ISSUE THREAD

**Issue by boomsi** [fabricjs/fabric.js#9203]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

116.0.5845.140 (arm64)

### Steps To Reproduce

You can see https://codesandbox.io/s/stupefied-germain-m8hy6x?file=/index.js

When using erasing.

<img width="475" alt="image" src="https://github.com/fabricjs/fabric.js/assets/39713960/1f7095d8-3592-44ee-b2fd-f2e45091e68a">

But if you uncomment line 88, you will notice that the issue disappears.

### Expected Behavior

<img width="454" alt="image" src="https://github.com/fabricjs/fabric.js/assets/39713960/4ba8be14-511e-4559-a74e-c9232024f2b9">

### Actual Behavior

<img width="475" alt="image" src="https://github.com/fabricjs/fabric.js/assets/39713960/1f7095d8-3592-44ee-b2fd-f2e45091e68a">

**Comment by ShaMan123** [comment]
What is line 88 referring to?
This is a known aliasing issue

**Comment by ShaMan123** [comment]
please try this with the new package [erase2d](https://github.com/ShaMan123/erase2d) and report there for issue
it still has the aliasing issue
