### ISSUE TITLE
Image applyFilters is slow and after loadFromJSON it fixes

### ISSUE THREAD

**Issue by yusufcan141** [fabricjs/fabric.js#923]
I use image.applyFilters feature of fabricjs. When i first load image on canvas and applied an image filter, browser blocks for a couple seconds especially for large size images upper than 2 MB. But, when i clear canvas and load it back with loadFromJSON, the problem gets fixed and image filters start to work properly without blocking browser.

Is it about fabricjs or my code, i couldnt figure out. I'll apreciate any help.

**Comment by hemant-manwani** [comment]
Hello, applyfilters is taking more time. Thanks
