### ISSUE TITLE
[Bug]: The Shape's left position changed when I flip it from right side

### ISSUE THREAD

**Issue by ritali4912** [fabricjs/fabric.js#9258]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta12

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://codepen.io/ritali4912/pen/JjwbPYG

### Steps To Reproduce

1.  Create a rectangle
2.  Click the mr control point then flip the rectangle **several times**. Notice: keep holding the mouse down during your several time flip from right to left then back to right then to left again, something like that.

P.S, it is correct on V5.

### Expected Behavior

The Left position should not change during I flip it from right side.

### Actual Behavior

At beginning:
![image](https://github.com/fabricjs/fabric.js/assets/67466090/a777dccf-56dd-4ada-99f4-8ac96a291e9e)

After several times flip:

![image](https://github.com/fabricjs/fabric.js/assets/67466090/52861165-cfb6-4d4d-af90-e28771aa3a8f)

**Comment by asturur** [comment]
thanks for reporting it, i ll test this tomorrow

**Comment by ShaMan123** [comment]
#8767

**Comment by ritali4912** [comment]
Thanks for quickly response.
Looking forward to the V6 final release. :)

**Comment by asturur** [comment]
@ShaMan123 that PR isn't related to this fix. if it is extract the fix in a new PR please.

**Comment by ShaMan123** [comment]
It is related.
Try reproducing in [this demo](https://codesandbox.io/p/sandbox/fabric-vanillajs-sandbox-forked-7cyh76?file=/src/index.ts:18,3) and you will see.

**Comment by ShaMan123** [comment]
I will not and can not extract the fix.

**Comment by ShaMan123** [comment]
Notice that in the repro, when the rect is scaled it seems to be drawn wrong while the coords are positioned correctly.
Which proves that the PR fixes this issue and needs to look into rendering as well

**Comment by asturur** [comment]
so this is another regression to fix before release, in this case is triggered by flipping a lot but there could be other scaling behaviour broken?

**Comment by ShaMan123** [comment]
no it is not.
check on fabricjs.com and you will see it

**Comment by asturur** [comment]
For me is clearly a bug. Working solid on fabricjs.com and broken in the reproduction and in current master with the vanilla template.

**Comment by asturur** [comment]
regression from commit: https://github.com/fabricjs/fabric.js/commit/d55fabcd671b183aa40091c9ed6d4b7fa24c87fa
