### ISSUE TITLE
[Bug]: When the zoom setting of the browser is less than 100%, the control points of the convenience sign and the selection area will deviate from the actual area

### ISSUE THREAD

**Issue by m3360202** [fabricjs/fabric.js#9316]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta5

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

16.18.0

### Link To Reproduction

https://dev.boardx.us/board/DhfR9K3vAeHJ5ZK9N

### Steps To Reproduce

1. set browser zoom less than 100%
2. select a object ，maybe you should click the right bottom of the object
3. see the controls offset the object

### Expected Behavior

object select area and controls should show correctly

### Actual Behavior

![image](https://github.com/fabricjs/fabric.js/assets/36294167/c316de4c-54f2-4c69-bad3-c54ec3214286)

**Comment by ShaMan123** [comment]
Can't repro in [a bare repro](https://e5r48u-1234.csb.app/)
meaning the bug is in your impl

**Comment by asturur** [comment]
One reason could be that you are manually using window.devicePixelRatio together with canvas isRetinaScaling.
isRetinaScaling is the devicePixelRatio, but when you manually change the zoom and the canvas is already initialized those will have a different relationship.

Look in your code if you are using devicePixelRatio first of all

**Comment by asturur** [comment]
I can't reproduce on the link you gave tho.
