### ISSUE TITLE
[Bug]: After upgrading from v6 beta1 to v6 beta12, the style adaptation for custom controls was not possible

### ISSUE THREAD

**Issue by more-strive** [fabricjs/fabric.js#9317]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta12

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

18.16.0

### Link To Reproduction

https://github.com/dromara/yft-design

### Steps To Reproduce

1.   git clone -b beta12 https://github.com/dromara/yft-design
2.   npm install
3.   npm run dev

### Expected Behavior

The master branch (beta1) is possible, and beta12 annotates the controls before it can run
![image](https://github.com/fabricjs/fabric.js/assets/113762408/91aa58f6-7e71-48a3-b6c1-2a975ca0cd99)

### Actual Behavior

![image](https://github.com/fabricjs/fabric.js/assets/113762408/45d9a5f5-7b97-4bbd-b8b2-e2dae700a098)
![image](https://github.com/fabricjs/fabric.js/assets/113762408/0e517703-143f-47f6-9f44-1e6586c448ff)
![image](https://github.com/fabricjs/fabric.js/assets/113762408/7cabd545-f3d4-4677-bdca-487010fb63f2)
![image](https://github.com/fabricjs/fabric.js/assets/113762408/e1b2f5ba-4de4-4077-a1cb-d5406236a0cb)

**Comment by ShaMan123** [comment]
#8299 
controls are not on the prototype any longer, as well as all properties

**Comment by asturur** [comment]
We made the change in a way is still possible to have controls on the prototype with a couple of lines of code, i should have left it on the original pr.

**Comment by more-strive** [comment]
How to do it? Is there a case?

**Comment by asturur** [comment]
for this part here:
<img width="266" alt="image" src="https://github.com/fabricjs/fabric.js/assets/1194048/11d048ee-56f7-46aa-a58c-445b91dbadd3">

just do:

```js
import { Object as FabricObject } from 'fabric' // or import * as fabric from 'fabric';

FabricObject.ownDefaults.borderColor: 'blue';
FabricObject.ownDefaults.cornerColor:'white';
... and so on
```

Otherwise you can do the following to restore default values on prototype:
```
import { Object as FabricObject } from 'fabric' // or import * as fabric from 'fabric';

Object.assign(FabricObject.prototype, FabricObject.ownDefaults);
FabricObject.ownDefaults = {};
```
And then you continue to set up the things as you were doing before on the prototype.

For the control set is slightly more complicated i ll continue to expand this example

**Comment by more-strive** [comment]
Thank you for your reply
