### ISSUE TITLE
Better support for clipping to a group in canvas.clipTo

### ISSUE THREAD

**Issue by butch2k** [fabricjs/fabric.js#932]
Hi,

i noticed something odd when using a group as a clipping mask, it contains several Paths but only the last added one is used for masking.

Regards,
Olivier
##

**Comment by asturur** [comment]
Support for groups as clippers should be added with some things in mind:
1) clip rule
2) clip shape support for svg
3) clipping output to SVG

We should find a way to use _render(ctx, noTransform, forClipping: true) and make this works. Also clipTo function is too much generic. I would prefer to switch over a clipTo => fabricObject ( group , rect or whatever ). in this way exporting to svg would be still possible.

**Comment by asturur** [comment]
i'm marking clipTo as deprecated.
Gonna  remove full clipTo functionalities in favor of clippingPaths.
That means you will loose the ability to put a free function but you will clip directly with fabric shapes.

**Comment by aggrosoft** [comment]
So clipTo is deprecated now in 2.x - what is the preferred method now?

**Comment by asturur** [comment]
There is nothing new now, there will be the first feature in fabric 2.1, that i start to develop as soon as i decide to wrap 2.0 in a package and get it out.

**Comment by elvvynn** [comment]
Is there currently another way to clip a single image with another one/a path with 2.0? Or do I have to use an older version?

**Comment by asturur** [comment]
the new way is not built in yet. not started apart a prototype.

**Comment by Aubron** [comment]
FYI @asturur - There is a $50 bounty on this issue that I set back in December, but never showed up on this end. It's not much, but it's something. 🤷‍♂️

**Comment by asturur** [comment]
i think the integration with bounty source is broken. I'll add the label. I really like clipping, i m just need to fix some fresh text bugs and merge an old PR from a contributor and then i want to start it

**Comment by DaltonNotetech** [comment]
how to use clippingPaths in latest fabric 2.3

**Comment by DaltonNotetech** [comment]
I need marquee of textbox within group

**Comment by asturur** [comment]
i think i can close this now! clipping to group works with clipPath in 2.4.0
