### ISSUE TITLE
[Bug]: Image resize corrupts files on version 6

### ISSUE THREAD

**Issue by cosbgn** [fabricjs/fabric.js#9330]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta9

### In What environments are you experiencing the problem?

Firefox

### Node Version (if applicable)

18.15.0

### Link To Reproduction

code below

### Steps To Reproduce

I'm trying to resize images from an input as they get uploaded. I do this:

```js
import { Image } from 'fabric';
let file = event?.target?.files?.[0]
let image_file = await Image.fromURL( URL.createObjectURL(file) )
const {width, height} = image_file.getOriginalSize()
const max_height_and_width = 2048

if (width > max_height_and_width || height > max_height_and_width){
	if (width > height){
		await image_file.scaleToWidth(max_height_and_width)
	}
	else {
		await image_file.scaleToHeight(max_height_and_width)
	}
	const blob = await fetch(image_file.toDataURL()).then(it => it.blob())
	const resized_file = new File([blob], file.name, {type:file.type})
	file = resized_file
	console.log("Image resized")
}

```

The new file is correctly resized but it appears corrupted, it seems ok, but several image tools can't read it properly. 
This is a comment I got from another image tool which can't process the file:

```
I... can't tell you what, but there's something deeply weird about that file. It does not appear to have been saved by a program that is properly obeying .png file format spec
I'd guess whatever 'fabric' is that you're using, has some core format issues that might need to be addressed there
among other things, it has data chunks in non-permissible orders (there's exif metadata after the image idat, which is not allowed), it also has at least 0.5 MiB more filesize than if i just... open it and resave it using a properly implemented image program
somehow resaving it didn't suffice to solve the bug, so something's persistently broken deeper than that
however, resaving as .jpg seems to work fine
alternately if i remove the (empty) alpha channel and resave to .png that seems to work fine too
```

### Expected Behavior

The file would work perfectly and saved correctly

### Actual Behavior

The file has something weird in it, and other tools can't read it correctly.

**Comment by ShaMan123** [comment]
no repro and really no way of doing anything with this.
add arepro and I will reopen

**Comment by ShaMan123** [comment]
and do not dump chatGPT on us please

**Comment by cosbgn** [comment]
> and do not dump chatGPT on us please

That's not chatGPT, it's an actual comment from a human who actually took a look at the file.
Anyways, for who finds this issue via search: 

I managed to solve using:

```js
const canvas = image_file.toCanvasElement()
const blob = await new Promise(resolve => canvas.toBlob(resolve, file.type))
file = new File([blob], file.name, {type:file.type})
```

Thanks for this library. So far looks great! The bug was probably just me doing something wrong.
