### ISSUE TITLE
[Feature]: Fitting a photo into an object

### ISSUE THREAD

**Issue by mozhn** [fabricjs/fabric.js#9332]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

Is it possible to place a photo inside an object based on its frame? When I enlarge the camera image, I want to hide the parts that go outside the heart. I tried a lot of things with clipPath but without success.

<img width="695" alt="Screenshot 2023-09-13 at 18 44 52" src="https://github.com/fabricjs/fabric.js/assets/25257157/1c40b5a9-45e1-4c3f-8edf-729d3e59cbd2">

### Current State

I need your support on how to do this.

**Comment by ShaMan123** [comment]
cropX/Y

**Comment by asturur** [comment]
@mozhn your description is really generic.
If the object is a rect, you can use cropX and cropY as suggested.
If is something else you can use patterns or clipPath, but without a reproducible SMALL example is really unfair use of time on our side.

**Comment by mozhn** [comment]
I'm sorry if I didn't explain my problem correctly. What I'm trying to do is to place a footage inside any object. I finally did it, but now I have another problem (maybe I did it wrong). After creating a group, unfortunately, the bag that should appear at the back does not appear.

My code:
https://jsfiddle.net/2uabcyt6/8/

**Comment by asturur** [comment]
Issue open or closed we check them anyway, there is no action item for us here as bugfix or code working as not intended but rather and help request.
