### ISSUE TITLE
[Feature]: The toObject method of the group should not return the size and position.

### ISSUE THREAD

**Issue by zhe-he** [fabricjs/fabric.js#9354]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

The size and location of the group are determined by the child elements, but the size and location of the group can be exported through toObject. Shouldn't toObject output the size and position of the group? If I modify the metadata of exported child elements, the size calculation of the group will be incorrect when importing, or it will not recalculate the size when importing.

### Current State

```javascript
const rect1 = new Rect({ top: 100, left: 100, width: 50, height: 50, fill: "red" });
const rect2 = new Rect({ top: 200, left: 200, width: 50, height: 50, fill: "yellow" });
const g = new Group([rect1, rect2]);
canvas.add(g);

const data = canvas.toObject();
data.objects[0].objects[0].left -= 10;
canvas.loadFromJSON(data).then(() => {
   canvas.requestRenderAll();
}
```
<img width="272" alt="image" src="https://github.com/fabricjs/fabric.js/assets/11306583/8d34b320-7b03-4a68-a16f-0d6ad40fed74">

### Additional Context

Could it be changed to output without returning the position and size of the group, and return the actual position of the child element instead of the relative position of the group?

```javascript

const rect = new Rect({ top: 100, left: 100, width: 50, height: 50, fill: "red" });
const g = new Group([rect]);

console.log(g.toObject()); // {  left: 100, top: 100, width: 51, height: 51, layout: "fit-content", objects:[{ left: -25.5, top: -25.5, width: 50, height:50  }] }
↓↓↓↓↓↓↓↓↓↓↓↓↓
console.log(g.toObject()); // { layout: "fit-content", objects:[{ left: 100, top: 100, width: 50, height:50  }] }

```

**Comment by asturur** [comment]
the main focus of toObject and fromObject is to be able to save and restore a canvas.
Modification of saved content is possible learning how to do it.
I m not sure what is blocking you from doing the changes you want with the current structure.
You probably have more than one option at your disposal, including writing your own toObject and fromObject function.

What are you trying to do exactly? moved objects inside the group when the group is just a plain javascript object and not a fabric.group instance?

**Comment by zhe-he** [comment]
I collaborate with others to modify graphics within a group. When group A has three subelements b, c, and d, I modify the position of b and send a socket notification to others. They will also modify the position of c to notify me. I won't send A's new size and location to others, and others won't send it to me. We should be atomically separated.

Currently, I flatten the data, and the multi-layer nested structure of sub-elements within the group becomes a single-dimensional data, which is then packaged into a multi-dimensional structure during import. So what I think is that if a group is like the one in Figma, where the group is a dynamic object that retains only the rotation angle of the group, and the other dimensions and positions are determined based on the child elements, the group will have a width and height during runtime, but it cannot be modified or exported.

**Comment by zhe-he** [comment]
Perhaps my needs are too business-oriented, and they should not be handled by the Group, but by my own custom Group

**Comment by ShaMan123** [comment]
It is a real question what plane you should send your data in.
Object data is relative to the parent/group plane. But as you said since the group size changes and therefore its center point as well relative positioning will be invalidated or stale.
On the other storing data in the canvas plane is bad for persisting action such as moving the group because then you will need to update all the children's positions as well.
The last week or so I am dealing with this and my concept is to have the server move from one state to the other according to the app's state. I haven;t tried it, just a thought. But take into account that you could easily compute transform matrices in the server and decide what to do there... 
So maybe the winning approach would be to send the data in the canvas plane and have the server transform it to relative or non relative as it needs to.

**Comment by zhe-he** [comment]
Thank you for your ideas. I will try them seriously offline. Only send the status of the movement and calculate the location through the statu
