### ISSUE TITLE
[Bug]: Invisible text when a gradient or pattern is applied

### ISSUE THREAD

**Issue by u-blusky** [fabricjs/fabric.js#9355]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/yrpuqvec/

### Steps To Reproduce

1. Create Text object
2. Apply gradient
3. The text is invisible

### Expected Behavior

Text fill with gradient and visible

### Actual Behavior

![gradient_text_chrome_problem](https://github.com/fabricjs/fabric.js/assets/131244197/100904da-91de-4b60-a4ed-cc100e9f708d)
![gradient_text_firefox_ok](https://github.com/fabricjs/fabric.js/assets/131244197/1d1124f5-78f7-4a0e-9aff-83245875a0cb)

**Comment by ShaMan123** [comment]
I think it is a priblem is chrome, our tests also fail in this aspect.
Try seeing if toggling objectCaching makes adifference

**Comment by u-blusky** [comment]
Hi,
I tried with objectCaching, statefullCache, dirty but, unfortunately, it doesn't solve the problem.

**Comment by u-blusky** [comment]
Maybe I found:
In Chrome, Use hardware acceleration when available = false
and the text is drawn correctly.

**Comment by tonycaso** [comment]
changing gradientUnits to pixels makes text visible(no need to disable objectCaching), but gradient isn't displayed correctly

**Comment by ShaMan123** [comment]
Thanks for reporting
Reproduction will be great, a pr even more

**Comment by u-blusky** [comment]
@tonycaso, @ShaMan123 
thanks a lot.
Using "pixels" works.
I created a new fiddle to test this:
https://jsfiddle.net/y30ge8fx/1/

**Comment by u-blusky** [comment]
Unfortunately the "linear" type is not right for how I set up the code.
I tried to debug but I don't understand where the problem could be.
The gradient is created correctly and I don't receive any error messages.
It works in Firefox. I don't understand what could cause problems if I use the "percentage" type in Chrome; and also because it works with the "linear" type.
If anyone can give me an idea.

Thanks a lot,
Blu

**Comment by ShaMan123** [comment]
I managed to triage the bug to fabric:
`_applyPatternGradientTransformText`

I remeber this...
Disabled the entire block in `Text#handleFiller` and it seems to work

Needs investigation

**Comment by asturur** [comment]
must be a recent regression of chrome, we should open a bug to them i suppose.

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/issues/8829
Seems it happens after chrome 111 onward

**Comment by carior** [comment]
、
`text.set('fill', new fabric.Pattern({
                source: img,
                repeat: 'repeat',
                patternTransform: [1, 0, 0, 1, 0, 0]
            }));
`
No correctly drawn text，And show blank。

**Comment by sk65cool** [comment]
Hi,
Any solution for fill Text with patterns in chrome, yet?

**Comment by carior** [comment]
Try this property?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月27日(星期五) 下午5:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fabricjs/fabric.js] [Bug]: Invisible text when a gradient or pattern is applied (Issue #9355)





 
你好，
 有什么解决方案可以用 Chrome 中的图案填充文本吗？
 
—
直接回复此电子邮件、在 GitHub 上查看或取消订阅。
您收到此消息是因为您发表了评论。消息 ID：<fabricjs/fabric 。js/issues/9355/1782638223 @ github 。com&gt;

**Comment by ShaMan123** [comment]
duplicate #9414
