### ISSUE TITLE
control flags scope

### ISSUE THREAD

**Issue by ShaMan123** [fabricjs/fabric.js#9365]
I am working on some controls and was wondering about the scope of the control flags
e.g. uniScaling, uniScaleKey which sit on Canvas, snapAngle which sits on object....
What about we move them to the control itself? 
Scaling stuff on the scale control etc.
It is quite messy like this.

 @asturur  Thoughts?

**Comment by ShaMan123** [comment]
![image](https://github.com/fabricjs/fabric.js/assets/34343793/38978266-2bc5-483b-bf7e-d3fa0ec1207b)

**Comment by asturur** [comment]
Those are kind of changes that can grant their own release.
The situation is bad, and the scope is not the only issue.

Those flags were added when control class didn't exist and controls were just names 'tl', 'tr' ...
The optimal situation would be that we deprecate all of those now and we add a counter part on the control.

Then who wants canvas level flags can share the control set with all the objects, who wants per object flags can have a control set per object.
Setting a single control set per object is still hard today tho.

There are some semantic issues, like uniScaleKey doesn't make sense on a change width control.

as a first step we can collect all property names we think are involved and describe where are those today and how would we like them to be?

**Comment by ShaMan123** [comment]
- snapAngle
- snapThreshold
- uniScaleKey
- uniformScaling
- all the `lockXXX` can be handled by `shouldActivate`

That is what I have found.
I can easily make the control respect both canvas setting and Control setting, The Control setting taking precedence over the rest.
But for now I just wrote an ugly patch that sets and unset these values in my app.

**Comment by asturur** [comment]
## snapAngle
today defined on object only

## snapThreshold
today defined on object only

uniScaleKey
uniformScaling
lockMovementX
lockMovementY
  lockRotation,
  lockScalingX,
  lockScalingY,
  lockSkewingX,
  lockSkewingY,
  lockScalingFlip,

Edit: i was editing but i have a strong nausea, i ll finish later

**Comment by ShaMan123** [comment]
centeredScaling
centeredRotation

**Comment by ShaMan123** [comment]
IMO the drag action should become a control (now possible thanks to #9374 and move `moveCursor` to it

**Comment by ShaMan123** [comment]
most or all the props in `src/shapes/Object/types/ControlProps.ts`
cornerSize: number;
  touchCornerSize: number;
  transparentCorners: boolean;
  cornerColor: string;
  cornerStrokeColor: string;
  cornerStyle: 'rect' | 'circle';
  cornerDashArray: number[] | null;
  padding: number;

**Comment by ShaMan123** [comment]
minScaleLimit
