### ISSUE TITLE
[Bug]: i-text render different in ubuntu and window

### ISSUE THREAD

**Issue by RathodAnnu13** [fabricjs/fabric.js#9379]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta9

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/69d8h0ta/

### Steps To Reproduce

1. Run above HTML On Windows and Linux browser. 

### Expected Behavior

On Both platform output should be same. 

### Actual Behavior

![windows_output](https://github.com/fabricjs/fabric.js/assets/60641656/3ba47523-e2c6-4e82-906b-4693709f5343)
![linux output](https://github.com/fabricjs/fabric.js/assets/60641656/6dc44b1a-dad3-40bf-82f8-2e012995fdda)

**Comment by asturur** [comment]
you linked a fiddle with 17.000 lines of code.
So i won't read it.
Please consider to answer this issue ( and 99.9% is not a bug ) the example needs to show which fonts are you using and how are you loading them.

All the rest is not necessary.
So write a minimal reproduction case, should be around 20-40 lines at worst considering the above.

**Comment by RathodAnnu13** [comment]
> you linked a fiddle with 17.000 lines of code. So i won't read it. Please consider to answer this issue ( and 99.9% is not a bug ) the example needs to show which fonts are you using and how are you loading them.
> 
> All the rest is not necessary. So write a minimal reproduction case, should be around 20-40 lines at worst considering the above.

Kindly review the updated code, please.
https://jsfiddle.net/69d8h0ta/

**Comment by asturur** [comment]
So you are using fabricJS 1.7.22 and that is already a red flag.

I see the roboto-regular font you are using is 127kb while the one that google offers is 168kb.
Possibly you downloaded a non complete version of it and ubuntu and windows are falling back on different characters?

as a starting point try to use the same browser in different OS to compare and swap the font with the complete one
https://fonts.google.com/specimen/Roboto/glyphs

**Comment by gloriousjob** [comment]
@RathodAnnu13 can you please update your fiddle to v6, as you were claiming in your issue? Otherwise, this issue will be marked invalid (only v6 is getting fixes so using a very old version isn't going to be helpful to get a fix).

**Comment by RathodAnnu13** [comment]
@gloriousjob 
By default, the i-text system utilizes system fonts. In Linux, various FontFamily fonts are installed, which was the primary reason for the issue I encountered. However, I have successfully resolved this problem.
