### ISSUE TITLE
[Bug]: blurred text in zoom if use paintFirst: "stroke"

### ISSUE THREAD

**Issue by Jonnas123** [fabricjs/fabric.js#9390]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta9

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://codepen.io/jonnas123/pen/poqVQoG

### Steps To Reproduce

Hello, I'm new here, not sure if it's a bug or new feature request. Please go to the link and zoom the text. You will see the text is blurred. After I remove the paintFirst: "stroke" the blurred is gone. How to go with paintFirst: "stroke" without blurred? I need to use paintFirst: "stroke".

### Expected Behavior

After removing paintFirst: "stroke"

![sctwo](https://github.com/fabricjs/fabric.js/assets/90570681/52c1e563-7b46-403e-9611-2b2c58e5a590)

### Actual Behavior

Before removing paintFirst: "stroke"

![scone](https://github.com/fabricjs/fabric.js/assets/90570681/5efc6044-61f2-4d2a-9e75-a8b75b01e296)

**Comment by asturur** [comment]
Hi @Jonnas123 what do you mean by zoom the text?

**Comment by Jonnas123** [comment]
I mean use mouse wheel to zoom in.

**Comment by asturur** [comment]
Yes there is a simple bug.

```
    if (
      this.paintFirst === 'stroke' &&
      this.hasFill() &&
      this.hasStroke() &&
      typeof this.shadow === 'object'
    ) {
      return true;
    }
```

we are running this condition to determine if the object needs the cache forced on.
Somehow since some change, this.shadow is an object even if we are not setting it.

This is probably an easy fix ( i didn't look at it ).

If you look at it is also possible you can open a PR to fix it.

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/blob/master/src/shapes/Object/defaultValues.ts#L79

Here the shadow is set as 'null' as a default.

I sincerly do not remember why we have the shadow property typed as `Shadow | null`, it could just be `?: Shadow` and then fix the code to actually work with this change.

A simpler and more direct fix is to update that condition to say:

```
this.paintFirst === 'stroke' &&
      this.hasFill() &&
      this.hasStroke() &&
      this.shadow !== null 
```

Probably less involved

Would require adding a jest test anyway in both cases

**Comment by Jonnas123** [comment]
Could you give a hint on where to place the codes? I 've tied both codes inside and outside the zoom function  but not working.

**Comment by ShaMan123** [comment]
start using codesandbox for repro
https://codesandbox.io/p/sandbox/fabric-vanillajs-sandbox-forked-y3kryw?file=%2Fsrc%2Findex.ts%3A14%2C24

**Comment by asturur** [comment]
> Could you give a hint on where to place the codes? I 've tied both codes inside and outside the zoom function but not working.

if you do a full search for `this.paintFirst === 'stroke'` you shouldn't get more than one or two results.
One of those results is 'needsItsOwnCache' that is the one you need to fix.

Even better, if you just look for `typeof this.shadow === 'object'` you find the exact bug and code.

**Comment by gloriousjob** [comment]
@asturur Do you have a recommendation for testing? This looks like a visual test (i.e., pixelmatch to see if the blur occurs) but I'm not sure that there's an example for jest. Is something like this needed?
https://github.com/americanexpress/jest-image-snapshot

Or did you have a simpler idea?

**Comment by ShaMan123** [comment]
We use playwright for that.
Look at https://github.com/fabricjs/fabric.js/tree/master/e2e/tests/template-with-node

**Comment by asturur** [comment]
I don't think a visual test is a good idea.
For a visual test is hard to determine if something is blurry or not.
We just need to test the output of 'needsItsOwnCache' function for a text object with different combination of properties.
The bug is not being blurry, that is not a bug itself, the bug is that it force cache on, against your request without a valid reason.
