### ISSUE TITLE
dragHandler => Control?

### ISSUE THREAD

**Issue by ShaMan123** [fabricjs/fabric.js#9391]
With recent changes to the contrlo logic it is now possible to move the dragHandler logic to its own control (overriding `shouldActive` and `calcCornerCoods`).
I raise this because in the projects I work on it is needed or will make developing a lot easier.
This way fabric will not default to an action handler, rather the drag control will be one of the controls as any other, easily disabled, removed or customized.
This will scope a few more things such as `moveCursor` etc., all moving to their control counter part.
It also makes the Control API a standard of interaction in fabric w/o exceptions. That is important for DX.

**Comment by ShaMan123** [comment]
related to #9365

**Comment by asturur** [comment]
This sounds a reasonable improvement that can be discussed, i though of creating a gigantic control for dragging more than once, but this is definitely lower priority compared to finding time to understand and finish group layout.
There are weird use cases in which sometimes i have been asked to drag an object just by the outer border, like an hollow control.

**Comment by asturur** [comment]
It also needs to be checked if it is possible to move the current drag code in a function and not in canvas methods and just make it possible to add this incrementally so that it can be exported as an optional control but doesn't have to immediately replace the old code.

**Comment by ShaMan123** [comment]
all sounds possible and reasonable

**Comment by ShaMan123** [comment]
I implemented a control that is the entire side of an object, so guessing I could replicate that for the entire box.
But could be easier than that with Intersection and containsPoint latest improvements
