### ISSUE TITLE
[Bug]: Cropped image after running toSVG

### ISSUE THREAD

**Issue by aparzi** [fabricjs/fabric.js#9412]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

4.4.0

### Node Version (if applicable)

16.20.2

### Link To Reproduction

no link

### Steps To Reproduce

1. Load file svg in canvas
2. Execute toSvg fabric.Image.fromURL

### Expected Behavior

The expected result is to see the uncut svg file after the toSvg fabric.Image.fromURL function is called. Inside the Canvas the file is displayed correctly after applying a scaling factor. Details:

CANVAS:
width 275
height 348

Image:
14990 width
13883 height

### Actual Behavior

The current behavior is that the file is cut in width, after executing the function

**Comment by gloriousjob** [comment]
You've checked "I have created an accurate and minimal reproduction" but there's no link to a reproduction. This will probably be ignored/closed without a repro.

**Comment by ShaMan123** [comment]
> You've checked "I have created an accurate and minimal reproduction" but there's no link to a reproduction. This will probably be ignored/closed without a repro.

Thanks @gloriousjob 
I am closing this ticket until it complies with our guidelines.
Adding a repro means a repro in v6.

**Comment by aparzi** [comment]
Hi I created a sandbox (I leave the link):
https://pgmpzs-46527.csb.app/

Specifically, the generated svg file is printed in the console when open the link and you can see that it is cut compared to the display that occurs in the canvas. 
I believe that the problem may be with the rounding of the scaling that occurs during the svg creation phase because it is rounded to two decimal places. In my case the calculation is 0.018 and in the svg it is equal to 0.02

**Original Canvas:**

<img width="331" alt="Screenshot 2023-10-23 alle 10 46 28" src="https://github.com/fabricjs/fabric.js/assets/16490359/5a5f79e9-6a79-4e48-b3b2-15e413b484bf">

**Canvas generated**

<img width="382" alt="Screenshot 2023-10-23 alle 10 46 35" src="https://github.com/fabricjs/fabric.js/assets/16490359/2378a06a-852e-43f8-aa95-a262dc232e13">

**Comment by ShaMan123** [comment]
Did you try to increase the rounding percision?
I forget the const name
fabric.config.something

**Comment by ShaMan123** [comment]
But that should only handle exporting, not importing
Weird

**Comment by aparzi** [comment]
No. Can you explain me what to me change?

**Comment by ShaMan123** [comment]
Testing your repro all looks fine
The canvas starts undet the textarea  that is all

**Comment by aparzi** [comment]
have you seen my code?

**Comment by aparzi** [comment]
But my image after canvas generation is not whole. How is it possible that everything is ok?

**Comment by gloriousjob** [comment]
> have you seen my code?

No... your link just shows us the compiled result of what looks like angular code. Another thing that will be asked is if you can make the code in vanilla js but it would help to at least see the code.

**Comment by gloriousjob** [comment]
Also, if you think it's a precision issue, you can try setting the precision value near the beginning of your code.
fabric.Object.NUM_FRACTION_DIGITS = 10;

fabric defaults to 2. I have a hard time thinking this might fix it but worth a shot.

**Comment by aparzi** [comment]
Thanks @gloriousjob.
Yes I think this is the problem. Maybe I'll try this setting.
Where should I set the option when configuring fabric?

**Comment by gloriousjob** [comment]
I usually set it right after creating the canvas (I.e., before anything is added). I think technically you could do it before the to SVG call but if you just want one value for precision, better to set it up front

**Comment by aparzi** [comment]
Setting the property it works

**Comment by ShaMan123** [comment]
Guys, @asturur should we consider to remove the default  value of 2 in favor of max value?
I am for, it is there as a database optimization which is not the scope of fabric.
Then if someone needs it they can configure it.

**Comment by ShaMan123** [comment]
duplicates #9438 #9432

**Comment by asturur** [comment]
let me read the root cause of the
mismatch, the default value should be higher probably, around 6 or 8

**Comment by aparzi** [comment]
I agree with @asturur, in my opinion even 5 would be enough with the possibility of configuring it as desired. Even 5 would be enough

**Comment by ShaMan123** [comment]
@aparzi are you willing to PR?

**Comment by aparzi** [comment]
@ShaMan123 yes, as soon possible.

**Comment by ShaMan123** [comment]
I will help, any failing test we can convert to a jest snapshot and be done with it

**Comment by aparzi** [comment]
@ShaMan123 okay, I should just change the variable and do some tests. Right?

**Comment by ShaMan123** [comment]
yes
```
npm run build -- -f -w
npm test -- -a  // this will fail horribly
npm run test:jest -- -u
npm run test:e2e -- -u
```

**Comment by ShaMan123** [comment]
I am for removing it from the global config and adding it to the relevant exporting methods as a config object but that can be done later on I guess

**Comment by aparzi** [comment]
okay I'll take a look. If I have difficulty, can I write to you somewhere?

**Comment by ShaMan123** [comment]
yes, I suggest you open a WIP PR and we continue there

**Comment by aparzi** [comment]
Okay thanks a lot.

**Comment by aparzi** [comment]
Hi @ShaMan123,
but in version 6 beta NUM_FRACTION_DIGITS config is already upgrade  at 4 value

**Comment by ShaMan123** [comment]
I forgot we did that, so maye all this is resolved in v6.
Another reason to migrate ASAP

**Comment by aparzi** [comment]
Yes, sure
