### ISSUE TITLE
[Bug]: Fast dragging control box moves control points in v6

### ISSUE THREAD

**Issue by B4rtware** [fabricjs/fabric.js#9417]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta9

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://fabricjs.github.io/demo/simple-test/

### Steps To Reproduce

1. Open the official new website
2. Select any shape
3. Start dragging fast on one end

### Expected Behavior

The control points which aren't moving should stay stationary.

### Actual Behavior

![fabricjs](https://github.com/fabricjs/fabric.js/assets/34386047/47c21e95-72c5-409e-ab22-68db400d600c)
![fabricjs2](https://github.com/fabricjs/fabric.js/assets/34386047/f31665ec-49c7-49a2-94da-fed626fed6a5)

**Comment by houssameddine-h** [comment]
The website uses beta10
It was fixed in beta13 => [https://jsfiddle.net/ku4jzet7/](url)
Not sure in what commit though.

**Comment by asturur** [comment]
Also consider that `website` is really just the scratchpad of trying to create a new website.
