### ISSUE TITLE
[Feature]: How to add some custom property in Object

### ISSUE THREAD

**Issue by vijaygurjar** [fabricjs/fabric.js#9420]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

Needed some extra property in Object. Can any one help me. There are number of objects in my application and i don't want to add same property in every object. I like to add once which is accessible by all object.
Old Version it is possible via prototype but now toObject is protected
Older version code:
fabric.Object.prototype.toObject = (function (toObject) {
    return function (propertiesToInclude) {

      propertiesToInclude = ['XYZ'].concat(propertiesToInclude);

      return toObject.call(this, ['ABC'].concat(propertiesToInclude));
    };
})(fabric.Object.prototype.toObject);

how to achieve this functionality in new version

### Current State

In current version toObject is protected

**Comment by ShaMan123** [comment]
you can still mutate the prototype
https://github.com/fabricjs/fabricjs.github.io/blob/development/src/content/docs/core-concepts.md#customization-subclassing--mutation

**Comment by vijaygurjar** [comment]
Hello @ShaMan123 ,
Thanks for your reply i will try this way
