### ISSUE TITLE
[Feature]: Add the ability to have arrows at the start and/or end of a line.

### ISSUE THREAD

**Issue by ShawnMarxent** [fabricjs/fabric.js#9421]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

I would like to be able to create a line with an arrow head at the start or end of the line or have a line with double arrows. I would like to set the size and color of the arrows as well. 

### Current State

Right now I need to create a line and a triangle shape to be able to create an arrow that points to something. I would to be able to create a line with a one or more arrow heads and only manage one object.

```
 const lineWithArrow  = new fabric.Line([0, 0, length, 0], {
            left,
            top,
            width: length,
            strokeUniform: false,
            strokeWidth: strokeWidth,
            lockScalingY: true,
            originX: 'right',
            originY: 'center',
          //
          // new options for creating an arrow at the start and end of the line.
          //
           startArrow: {
               size: 5,
               fillColor: '#ff0000',
           },
           endArrow: {
               size: 5,
               fillColor: '#ff0000',
           } 
        })
```

**Comment by ShaMan123** [comment]
Line is a bad implementation and is planned to be deprecated in favor of polyline/polygon.
Override the `_render` method and add your arrow

**Comment by asturur** [comment]
Please consider those are use cases for custom implementation that may fit
or not fit in the library itself. An Arrow can be a custom class that lives in the fabricJs org, and that you import as a custom package.

arrow have different styles and behaviours, different way to bend when are not straight, it is not reasonable for this library to cover that all
