### ISSUE TITLE
[Bug]:  Issue with font mark of Asean font only for Text on Path

### ISSUE THREAD

**Issue by Jonnas123** [fabricjs/fabric.js#9422]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta9

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://codepen.io/jonnas123/pen/poqXGbe

### Steps To Reproduce

I have this font mark issue only for text on path. I tested some Asean fonts with same result. Here is a case of Thai font. In Adobe Illustrator we solve this by putting a check on "Middle Eastern & South Asian Every-line Composer"

```
var path = new fabric.Path('M207.1,400.5c0-104.4,84.6-189,188.9-189s188.9,84.6,188.9,189');
path.set({fill:"transparent"});
var CurveText = new fabric.IText('พื้นที่สวยงาม', {
  path: path,
  fontSize: 80,
  textAlign:'center',
  left:100,
  top:200
});
canvas.add(CurveText);
```

### Expected Behavior

Normal text: พื้นที่สวยงาม

### Actual Behavior

![marktextonpath](https://github.com/fabricjs/fabric.js/assets/90570681/7995053a-6272-44ee-9ed6-e07c6e76c716)

**Comment by asturur** [comment]
can you please log here the CurveText._text property? should be an array of glyphs

**Comment by Jonnas123** [comment]
![log](https://github.com/fabricjs/fabric.js/assets/90570681/b36556d5-ca21-4754-889c-bf2f247ae169)

**Comment by Jonnas123** [comment]
(13) ['พ', 'ื', '้', 'น', 'ท', 'ี', '่', 'ส', 'ว', 'ย', 'ง', 'า', 'ม']
0: "พ"
1: "ื"
2: "้"
3: "น"
4: "ท"
5: "ี"
6: "่"
7: "ส"
8: "ว"
9: "ย"
10: "ง"
11: "า"
12: "ม"
length: 13

**Comment by asturur** [comment]
ok so the issue is that for your language our basic grapheme splitter isn't good enough, and that is a known issue.

take this library here: https://github.com/flmnt/graphemer

And replace the text method for IText or Textbox:

i do in this way:

```ts
import { config, Textbox } from 'fabric6';
import Graphemer from 'graphemer';

export function newGraphemeSplit(value: string): string[] {
  const splitter = new Graphemer();

  return splitter.splitGraphemes(value);
}

export const configureFabric = () => {
  Textbox.prototype.graphemeSplit = newGraphemeSplit;
};
```

you can also use subclassing if you prefer.

Using a better grapheme splitter will solve your issue. You will notice that the obj._text array will be shorter then.

**Comment by ShaMan123** [comment]
Shouldn't we use that in the repo then?

**Comment by asturur** [comment]
Is a dependency to keep up with, you never know who and when will update to newer versions and when will be tired of doing it.
Some library recognizes emoji, some other doesn't.
At the time of design grapheme splitting was build with overriding in mind, you take the grapheme splitter of your choice and you add it, a choice of simplicity for us too.

**Comment by Jonnas123** [comment]
Thank you [asturur](https://github.com/asturur) For my case I use this version https://github.com/orling/grapheme-splitter (as I don't use TypeScript) and with this works for me.

```
var splitter = new GraphemeSplitter();
fabric.util.string.graphemeSplit = function(txtString) {
     return splitter.splitGraphemes(txtString);
};
```

![ct](https://github.com/fabricjs/fabric.js/assets/90570681/0fa5a9e9-9530-4815-9314-9a696e21930d)

I need the bottom text to be in this way (not vertically flipped) but it stays inside, making it different in size to the top. Could you point me out how to position the text horizontally to the edge (or outside, same to the top one) so that the curved texts stay in same size?

**Comment by ShaMan123** [comment]
pathAlign property

**Comment by Jonnas123** [comment]
Wow, pathAlign: "center",  pathAlign: "ascender". Actually, it's also there in the  article https://stackoverflow.com/questions/76910089/fabric-js-handle-object-text-along-with-its-path-when-converting-to-svg but I didn't notice. Thanks [ShaMan123](https://github.com/ShaMan123)  for pointing out.
