### ISSUE TITLE
[Bug]: broken / unconnected lines of SVG with multiple paths

### ISSUE THREAD

**Issue by val3n71na** [fabricjs/fabric.js#9432]
### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/IoanaBraica/m4n8uoex/78

### Steps To Reproduce

1. Load a svg having multiple <path elements using fabric.loadSVGFromString and fabric.util.groupSVGElements on a canvas
2.  Export canvas content using canvas.toSVG() and check the result (insert it in a html element or just copy the result and save it as .svg)

Expected results: the svg lines remain unbroken as the svg is initially 
Actual results: the svg lines are broken, this is visible when using zoom in 

More details and screenshots: https://groups.google.com/g/fabricjs/c/O1HtbMOnOck
![screenshot_fiddle](https://github.com/fabricjs/fabric.js/assets/26135080/8e864613-f82d-4077-8d79-63d9cfc3f43d)
  & https://stackoverflow.com/questions/77345197/fabric-js-broken-svg-with-multiple-paths

### Expected Behavior

Expected results: the svg lines remain unbroken as the svg is initially 

### Actual Behavior

Actual results: the svg lines are broken, this is visible when using zoom in 

### Error Message & Stack Trace

```bash
no error message
```

**Comment by gloriousjob** [comment]
This sounds like a precision issue. I think you should add this into your code (use a larger number if you want more precision... fabric defaults low to reduce data/memory):
fabric.Object.NUM_FRACTION_DIGITS = 8;

**Comment by val3n71na** [comment]
thank you, @gloriousjob!! that was the problem!

**Comment by val3n71na** [comment]
Is it another option that can be changed for even more precision? The result is a lot better than previously, but there is still room for improvement. There are still some pixels missing. Please check the attached picture. 
![Screenshot 2023-10-24 115744](https://github.com/fabricjs/fabric.js/assets/26135080/35f98df0-908c-43db-8d72-1fa4e9e78706)
