### ISSUE TITLE
[Bug]: The bounding box disappear if drag point of a vertical or horizontal polyline.

### ISSUE THREAD

**Issue by ritali4912** [fabricjs/fabric.js#9436]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta13

### In What environments are you experiencing the problem?

Microsoft Edge

### Node Version (if applicable)

None

### Link To Reproduction

https://codepen.io/ritali4912/pen/PoVogxQ

### Steps To Reproduce

In my case, I need to create a horizontal polyline with strokeWidth = 0.
1. Create the polyline with points {100, 100}, {200. 100}, {300, 100}
2. Active select it.
3. Drag one of the points horizontally.

In above CodePen, you need to select the top-left region through mouse to active the transparent polyline.

### Expected Behavior

The bounding box is here.

### Actual Behavior

The bounding box disappear because the point change to NaN.

**In the beginning,**
![image](https://github.com/fabricjs/fabric.js/assets/67466090/934147c5-9150-406e-bb91-03f9978d703e)

**Drag one of the points**
![image](https://github.com/fabricjs/fabric.js/assets/67466090/f78df77c-c980-4029-abdd-ed20d44d3504)

You can see the sizeFactor.y got NaN because the height is 0 which was divided. No matter I enable or not the exactBoundingBox.

After I add one more logic as:
sizeFactor = new fabric.Point(Number.isNaN(sizeFactor.x) ? 1 / poly.scaleX : sizeFactor.x, Number.isNaN(sizeFactor.y) ? 1 / poly.scaleY : sizeFactor.y);
it works.

Please evaluate the correct fix.

**Comment by ShaMan123** [comment]
Please PR, your fix seems valid

**Comment by gloriousjob** [comment]
As can be seen in commit [650bcaa0f429ad5543b9de2d2ba42d42b83c7faa](https://github.com/fabricjs/fabric.js/pull/9496/files/abdf5cccee03ad85a4bef6b582b394ff239d7496), I found an issue in factoryPolyActionHandler as well. But there's some concern about this fix. The PR was doing double duty and there's concern about this fix so I'm simplifying the PR to the other issue. A new PR can be opened if the concerns can be addressed.

I'm not sure how much concern there is about this use case since it means starting with a flat line and then adding more points.

**Comment by ShaMan123** [comment]
> I'm not sure how much concern there is about this use case since it means starting with a flat line and then adding more points.

I think it is a valid use case, especially since we are planning to deprecate `Line`.
I handle these edge cases in my apps but adding a small epsilon.

**Comment by asturur** [comment]
i think this has been closed with #9575
