### ISSUE TITLE
[Bug]:  Upper Canvas and Lower Canvas not working together well after zooming

### ISSUE THREAD

**Issue by shahzodjonweb** [fabricjs/fabric.js#9442]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/qsz2n0f4/1/

### Steps To Reproduce

1. Open The Fiddle ( https://jsfiddle.net/qsz2n0f4/1/ )
2. Draw (See if it is working)
3. Zoom in or out
4. Draw (Now the image is scaling  moving after the draw)

### Expected Behavior

I am implementing a custom Brush for drawing without noisy colors and using canvas.contextTop (upperCanvas). When I draw without zooming it works and draws the image to the exact place and noise free. After zooming and using Lower Canvas pointer events, drawing at Upper Canvas rendering will be far from the pointer but puts the drawn image to Lower Canvas perfectly ( https://jsfiddle.net/qsz2n0f4/3/   zoom canvas to see the issue). When I use Upper Canvas pointers, It draws well in Upper Canvas but It will not put the drawn image in the same place  ( https://jsfiddle.net/qsz2n0f4/1/   zoom canvas to see the issue). When I scale the image and put it into Lower Canvas,  it will create redundant colors with alpha.

### Actual Behavior

 Upper Canvas and  Lower Canvas zooming should work together synced and After Drawing drawn content should not contain other noise colors (same color but with alpha).

**Comment by ShaMan123** [comment]
seems you did not account for the viewwportTransform/dpr
https://jsfiddle.net/fg3rnc8a/5/
```js
    const dpr = this.canvas.getRetinaScaling()
    fabric.util.addTransformToObject(img, fabric.util.invertTransform(fabric.util.multiplyTransformMatrices([dpr, 0, 0, dpr, 0, 0], this.canvas.viewportTransform)))
```

**Comment by ShaMan123** [comment]
it is bad design that brushes are affected by vpt

**Comment by asturur** [comment]
We have a plan to look at brushes as soon as 6.0 is out.

**Comment by asturur** [comment]
> it is bad design that brushes are affected by vpt

Brushes have to work with vpt in mind, they take vpt at minimum, they work with the standard canvas/design coordinates and do transform the context before drawing because the upper canvas is usually not transformed.

To not be affected by vpt they should capture the points in html coordinates and then transform them before finalizing the operation.

In this case @shahzodjonweb had a peculiar design, to take whatever was on the upper canvas and add it as an image, if the brushes were or weren't affected by VPT i think he would have the same exact issue because he is mixing two things that live in different spaces by design

**Comment by ShaMan123** [comment]
> if the brushes were or weren't affected by VPT i think he would have the same exact issue because he is mixing two things that live in different spaces by design

I agree

> Brushes have to work with vpt in mind

I disagree that brushes are affected by vpt. 
After adding them to canvas we must invert the vpt, true, but while using a brush if the vpt changes it will not be handled properly and will cause an offset in visuals that is not expected or desired.

**Comment by shahzodjonweb** [comment]
> seems you did not account for the viewwportTransform/dpr https://jsfiddle.net/fg3rnc8a/5/
> 
> ```js
>     const dpr = this.canvas.getRetinaScaling()
>     fabric.util.addTransformToObject(img, fabric.util.invertTransform(fabric.util.multiplyTransformMatrices([dpr, 0, 0, dpr, 0, 0], this.canvas.viewportTransform)))
> ```

Hi, thanks for your response. The drawing is working as expected. But there is still one issue, it is adding color noise while drawing in Zoom. I need to draw with colors without alpha , because later I need to extract the drawn image from the canvas which should be free from unwanted colors. Is there anything you can advise on this?

**Comment by shahzodjonweb** [comment]
> > it is bad design that brushes are affected by vpt
> 
> Brushes have to work with vpt in mind, they take vpt at minimum, they work with the standard canvas/design coordinates and do transform the context before drawing because the upper canvas is usually not transformed.
> 
> To not be affected by vpt they should capture the points in html coordinates and then transform them before finalizing the operation.
> 
> In this case @shahzodjonweb had a peculiar design, to take whatever was on the upper canvas and add it as an image, if the brushes were or weren't affected by VPT I think he would have the same exact issue because he is mixing two things that live in different spaces by design

Because my requirement is drawn part should correspond with the image pixels in the background canvas while and after drawing. It should not add unwanted alpha noises. Adding Paths didn't work that way, it is adding alpha colors when converted to image. If you have a better solution, I appreciate it).
