### ISSUE TITLE
[Bug]: When freeDrawingBrush is set to string

### ISSUE THREAD

**Issue by lz1834career** [fabricjs/fabric.js#9452]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta9

### Node Version (if applicable)

None

### Link To Reproduction

no

### Steps To Reproduce

Inadvertently setting freeDrawingBrush to a numeric string resulted in strange offsets in its drawing

### Expected Behavior

I hope to verify the data type and report an error when it does not match or use the default value

### Actual Behavior

![66](https://github.com/fabricjs/fabric.js/assets/29910537/2a7811da-b6b6-4c68-9f78-18ec91242948)

**Comment by ShaMan123** [comment]
I have no idea what you are doing but it makes no sense
freeDrawingBrush is instance of BaseBrush

**Comment by lz1834career** [comment]
I didn't make it clear, it was the width of freeDrawingBrush, which was accidentally set to a string

**Comment by ShaMan123** [comment]
Indeed not clear
It is your responsibility to use the repo correctly

**Comment by asturur** [comment]
Typescript should warn you plently in this case.
Where you using JS or TS?

You have both JSDocs or automatic type checking that should inform you of something being wrong

```ts
 /**
   * Width of a brush, has to be a Number, no string literals
   * @type Number
   * @default
   */
  width = 1;
```
