### ISSUE TITLE
Using custom build file with nodejs throws window undefined error

### ISSUE THREAD

**Issue by shreyasnair02** [fabricjs/fabric.js#9457]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.2.1

### In What environments are you experiencing the problem?

Node.js

### Node Version (if applicable)

16.20.0

### Link To Reproduction

https://codesandbox.io/s/nervous-sunset-5269pt

### Steps To Reproduce

1. initialize nodejs project
2. download a custom build (ex. build containing eraser) from fabricjs website
3. import the custom build into nodejs application

### Expected Behavior

fabricjs should work the same way it works when installing it via npm 

### Actual Behavior

fabricjs imported via the custom build file throws a window undefined error, even though jsdom is correctly being used

### Error Message & Stack Trace

```bash
/sandbox/src/fabric.js:546
        if (window.navigator.msPointerEnabled) {
        ^

ReferenceError: window is not defined
    at /sandbox/src/fabric.js:546:2
    at /sandbox/src/fabric.js:555:3
    at Object.<anonymous> (/sandbox/src/fabric.js:683:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/sandbox/src/index.js:3:20)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by asturur** [comment]
eventJS is a touch event library that little has to do in node.
Please do not add it to the build when using fabric in node, you can still import it just in the browser side of your project
