### ISSUE TITLE
[Bug]: Regression: creating a polyline/polygon with skewX at initialization time creates wrong bounding box

### ISSUE THREAD

**Issue by asturur** [fabricjs/fabric.js#9459]
## Description

adding to a canvas a polyline with this code in lastest master

```js
var pts = [
  {
    x: 300,
    y: 200,
  },
  {
    x: 440,
    y: 340,
  },
  {
    x: 520,
    y: 220,
  },
  {
    x: 580,
    y: 280,
  },
];

var polyObj = new fabric.Polyline(pts, {
  fill: 'transparent',
  stroke: 'black',
  strokeWidth: 10,
  originX: 'center',
  originY: 'center',
  scaleX: 1.4,
  scaleY: 1.1,
  skewX: 10,
  strokeUniform: false, // doesn't change
  objectCaching: false,
});

canvas.add(polyObj)
```

Produces this polyline

<img width="614" alt="image" src="https://github.com/fabricjs/fabric.js/assets/1194048/4828928a-d333-4337-a575-5b1851fa2892">

while executing the same code on the execute tab of http://fabricjs.com/kitchensink produces this other polyline

<img width="494" alt="image" src="https://github.com/fabricjs/fabric.js/assets/1194048/0b510ff6-4bd0-4f22-812e-ece571d30c45">

## Notes

strokeUniform value does not seems to affect anything
Adjusting skew with the controls in latest master produces the correct bounding box
Adding skewX after the polyline has been initialized produces the correct bounding box

**Comment by asturur** [comment]
I didn't search for the the breaking commit yet

**Comment by asturur** [comment]
Tracked down the breakage to this PR:
https://github.com/fabricjs/fabric.js/pull/8344
Very old, and i will read as soon as i can.

**Comment by ShaMan123** [comment]
https://github.com/fabricjs/fabric.js/pull/8344#issuecomment-1279799561

**Comment by asturur** [comment]
This is unrelated to that comment, that is about skewing controls, while this is about the initial bounding box is wrong.

**Comment by asturur** [comment]
Regarding this bug in particular, the lines causing it are those here:

https://github.com/fabricjs/fabric.js/pull/8344/files#diff-bd205e7c97c6ebe6fe74b159d74584b926d43a2177e60f525237aeda203f9c30R134-R137

The code in setDimensions ( and so _calcDimensions ) is at fault.

Removing those line there fix the issue, but of course would break the exactBoudingBox use case.

If we add skewX on a polyline after creation, all is good until we call setDimensions again, at that point the wrong pathOffset come back again.

simply the extra skew calculation for pathOffset needs to be added only in the case we are using the exactBoundingBox.
