### ISSUE TITLE
[Bug]: Single or first StaticCanvas on page is blurry / doesn't respect enableRetinaScaling

### ISSUE THREAD

**Issue by pkl** [fabricjs/fabric.js#9464]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta14

### In What environments are you experiencing the problem?

Firefox, Chrome, Safari

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/klevendev/quywt9ev

### Steps To Reproduce

1. Initialize two instances of StaticCanvas with enableRetinaScaling = true
2. Add some text to them
3. Display on a Retina screen

### Expected Behavior

I expected to see crisp text on both canvas elements.

### Actual Behavior

I saw blurry text on the first

<img width="220" alt="image" src="https://github.com/fabricjs/fabric.js/assets/1681423/428580f1-012a-476a-91ef-4e4b664815a0">

---

The first StaticCanvas is always blurry on Retina. 

You can uglyhack around it by writing: 

`const foo = new StaticCanvas();`

Before your "proper" canvas. But that probably needs to be disposed and managed in some way.

**Comment by asturur** [comment]
oh well this is strange indeed.
The reproduction seems clean to me and seems a bug.
As a lesser workaround you can just call setDimenions twice the first time and will autofix.

**Comment by ShaMan123** [comment]
weird indeed, chaning to Canvas fixes it https://jsfiddle.net/klevendev/quywt9ev

**Comment by AdamMerrifield** [comment]
It looks like the issue is that the config does not have `devicePixelRatio` set until `getEnv` is ran for the first time to initialize.

Adding a single call to `getEnv()` inside the constructor for `StaticCanvas` resolves this.
