### ISSUE TITLE
[Feature]: no able to load svg using loadsvgfromurl and add into canvas

### ISSUE THREAD

**Issue by vijaygurjar** [fabricjs/fabric.js#9468]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

Not able to add svg. Below is my code to add simple svg element on canvas
Object is added on canvas but not visible.

### Current State

var canvas = new Canvas("canvas", {
      height: 720,
      width: 1080,
    });
    loadSVGFromURL("sampleurl").then((res:any)=>{
      let g = new Group(res.objects, res.opts);
      canvas.add(g);
      canvas.requestRenderAll();
    })

**Comment by gloriousjob** [comment]
This doesn't really tell us anything. What fabric version are you using? What's the svg you're trying to load? Where's a repro?

**Comment by vijaygurjar** [comment]
Fabric version: 6.0.0-beta15
 samle svg in my local system
 
 <?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="267.101px" height="267.068px" viewBox="16.981 16.95 267.101 267.068"
	 enable-background="new 16.981 16.95 267.101 267.068" xml:space="preserve">
<path id="_x23_585858fe" fill="#020202" d="M139.45,17.56c46.479-4.71,94.06,18.2,120.489,56.5
	c13.49,19.16,21.689,42.02,23.529,65.39c4.73,46.5-18.26,94.05-56.529,120.489c-20.42,14.371-45.041,22.74-69.989,23.801
	c-53.2,3.65-106.391-29.11-127.83-77.801c-9.46-19.811-12.811-42.119-12.03-63.93C20,94.7,49.9,50.02,93.01,30.05
	C107.52,22.97,123.38,18.91,139.45,17.56z"/>
</svg>

**Comment by ShaMan123** [comment]
Please avoid spamming the repo,
It is not ta feature and most probably not a bug on our side.
https://github.com/fabricjs/fabric.js/discussions/9467#discussioncomment-7443804
