### ISSUE TITLE
willReadFrequently: true dosent wonk in Chrome Version 119.0.6045.106

### ISSUE THREAD

**Issue by rafipatel93** [fabricjs/fabric.js#9473]
willReadFrequently: true dosent wonk in Chrome Version 119.0.6045.106
Is there another way to make Text with a pattern fill appear?

_Originally posted by @sk65cool in https://github.com/fabricjs/fabric.js/issues/9414#issuecomment-1790258902_

**Comment by ShaMan123** [comment]
it is not our problem, report to chromium
and read the thread that explains how to change some browser flags
