### ISSUE TITLE
[Bug]: The bounding box disappear if scaling Y for a Rectangle whose strokeWidth = 0 and initial height = 0

### ISSUE THREAD

**Issue by ritali4912** [fabricjs/fabric.js#9475]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta15

### In What environments are you experiencing the problem?

Microsoft Edge

### Node Version (if applicable)

None

### Link To Reproduction

https://codepen.io/ritali4912/pen/PoVogxQ

### Steps To Reproduce

In my case, I create a rectangle with strokeWidth = 0 and initial its height = 0.

1. Create the rectangle with strokeWidth = 0 and initial its height = 0.
2. Active select it.
3. Drag the 'mt' or 'mb' to scaling Y.

P.S. In above CodePen, you need to select the top-left region through mouse to active the transparent rectangle.

### Expected Behavior

The rectangle successfully scale the Y.

### Actual Behavior

The bounding box disappear because the scaleY change to Infinity.

**In the beginning**
![image](https://github.com/fabricjs/fabric.js/assets/67466090/9c7b2234-5bae-4ce1-a2fd-453ba45f0de0)

**Drag the control mt or mb**
![image](https://github.com/fabricjs/fabric.js/assets/67466090/05e59c6f-d28c-4561-9046-84222e9687e6)

You can see the scaleY got Infinity because the dim.y is 0.

I got correct behavior if I adjust the target.height in the beginning logic of scaleObject(): 
target.height = target.height === 0 ? 1/target.scaleY : target.height;
Same for target.width.

But I believe there is more reasonable place to adjust it.
Please check it.
Thanks.

**Comment by ShaMan123** [comment]
you already opened a ticket for this 
duplicate #9436

**Comment by gloriousjob** [comment]
Just noting that https://github.com/fabricjs/fabric.js/issues/9436 is a similar but different issue. My PR addresses the issue in this bug report.

**Comment by gloriousjob** [comment]
@ritali4912 There's a little discussion on the PR about this. On one hand, it is thought that we should not allow scaling on a 0 height shape. On the other hand, scaling could be allowed and we could scale from 0 to 2. But I think the question is why is the height 0 in that case. What are your thoughts regarding this?

**Comment by ritali4912** [comment]
@gloriousjob 
Thanks for look back on this issue. And sorry I'm not notice your message in time.
The **background** we use FabricJS is: 
In our product, we split the Interactive layer (which focus on object scale and object moving based on FabricJS) and Render layer which sync the fabric object's bounding box (Left, Top, Width, Height) to corresponding DOM element.

So all the fabric.Rectangle we created with StrokeWidth = 0, only fill it.

Then 
Case 1) when we scale the rectangle by x or y (means flip), it has chance get width or height to 0, and then continue scale it.
Case 2) The Left, Top, Width, Height are configurable, and we allow the 0 value.
