### ISSUE TITLE
[Feature]:  How to non proportionally scale the four diagonal angles of a dragging rectangle？ 

### ISSUE THREAD

**Issue by hengyuli** [fabricjs/fabric.js#9476]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

I want to adjust the diagonal angle of the created rectangle as smoothly as it is created, with non proportional scaling and free scaling. How should I set it?

### Current State

<!DOCTYPE html>
<html lang="zh">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	
  <title>FabricJS 右键菜单</title>
  <style>
    .box {
      position: relative;
    }

    #canvas {
      border: 1px solid #ccc;
    }
  </style>
</head>
<body>

<div class="box">
  <canvas id="canvas" width="600" height="600"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/fabric"></script>
<script>
  // 文档加载后执行
  window.onload = function() {
    // 初始化画布
    init()
  }

  // 菜单 DOM
  const menu = document.getElementById('menu')

  // 画布实例
  let canvas = null

  // 当前选中的元素
  let activeEl = null

  // 初始化
  function init() {
    canvas = new fabric.Canvas('canvas', {
    })

    // 矩形
    const rect1 = new fabric.Rect({
		left: 100,
       top: 100,
       width: 200,
       height: 100,
       fill: 'red',
    })

    // 将矩形添加到画布中
    canvas.add(rect1);

  }

</script>
</body>
</html>

### Additional Context

thanks
![1](https://github.com/fabricjs/fabric.js/assets/19280147/704f9322-ade5-4fb9-ac63-aa23b8698234)

**Comment by gloriousjob** [comment]
This isn't a feature request and you really should open this elsewhere, like in discussions. But this doesn't seem to be easy to figure out/find. When you create the canvas, do this:
canvas = new fabric.Canvas('canvas', {uniformScaling: false })

**Comment by hengyuli** [comment]
> This isn't a feature request and you really should open this elsewhere, like in discussions. But this doesn't seem to be easy to figure out/find. When you create the canvas, do this: canvas = new fabric.Canvas('canvas', {uniformScaling: false })

very thank u! very very thank u!!!!

**Comment by ShaMan123** [comment]
@gloriousjob a glorious job indeed :)
