### ISSUE TITLE
[Feature]: I want to eidt rect like add rect freely！ help me ，i paste code and image in bottom

### ISSUE THREAD

**Issue by hengyuli** [fabricjs/fabric.js#9477]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

I want to adjust the diagonal angle of the created rectangle as smoothly as it is created, with non proportional scaling and free scaling. How should I set it?

### Current State

i want eidt rect like  add rect.
![errorstate](https://github.com/fabricjs/fabric.js/assets/19280147/aceda2d8-1f0a-4b4d-858b-ab477ac1ac37)

![want](https://github.com/fabricjs/fabric.js/assets/19280147/183b2f2e-d3cb-4f66-b2c1-eba752ad496a)

### Additional Context

<!DOCTYPE html>
<html lang="zh">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	
  <title>FabricJS 右键菜单</title>
  <style>
    .box {
      position: relative;
    }

    #canvas {
      border: 1px solid #ccc;
    }
  </style>
</head>
<body>

<div class="box">
  <canvas id="canvas" width="600" height="600"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/fabric"></script>
<script>
  // 文档加载后执行
  window.onload = function() {
    // 初始化画布
    init()
  }

  // 菜单 DOM
  const menu = document.getElementById('menu')

  // 画布实例
  let canvas = null

  // 当前选中的元素
  let activeEl = null

  // 初始化
  function init() {
    canvas = new fabric.Canvas('canvas', {
    })

    // 矩形
    const rect1 = new fabric.Rect({
		left: 100,
       top: 100,
       width: 200,
       height: 100,
       fill: 'red',
    })

    // 将矩形添加到画布中
    canvas.add(rect1);

  }

</script>
</body>
</html>

**Comment by gloriousjob** [comment]
This looks like a duplicate of https://github.com/fabricjs/fabric.js/issues/9476

**Comment by hengyuli** [comment]
> This looks like a duplicate of #9476

thank u!
