### ISSUE TITLE
[Bug]: Border of clipping Group (with layout: 'clip-path') don't equal limits of group if clipPath have params another then {left: 0, top: 0}.

### ISSUE THREAD

**Issue by CCTVcalc** [fabricjs/fabric.js#9482]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [x] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta15

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/s/group-clippath-fabric-js-6-0-0-beta-14-cyrmp7?file=/src/index.js

### Steps To Reproduce

1. Set clipPat.left non-zero.
2. Border don't equal limits of group (outImg).

### Expected Behavior

Border equal limits of group (outImg).

### Actual Behavior

![ClipPath](https://github.com/fabricjs/fabric.js/assets/107500152/b09b54b0-b3d0-4fa8-991b-e0545173a266)

**Comment by CCTVcalc** [comment]
Sorry my Eglish very little.
Maybe its normal behaviour, but look loke a bug.

**Comment by CCTVcalc** [comment]
I clear code in sandbox and change picture.

**Comment by ShaMan123** [comment]
Please try your repro with #9152

**Comment by CCTVcalc** [comment]
feature 'layout: "clip-path"' don't worked.
example in this [repo](https://codesandbox.io/p/devbox/fabric-vanillajs-sandbox-forked-myx57m?file=%2Fsrc%2Findex.ts%3A28%2C15)

**Comment by ShaMan123** [comment]
your repro didn't change anything apart from the branch

https://codesandbox.io/p/devbox/fabric-vanillajs-sandbox-forked-gf3fh8
