### ISSUE TITLE
[Feature]: Allow passing custom Canvas instance on NodeJs instead of using node-canvas

### ISSUE THREAD

**Issue by ShivamJoker** [fabricjs/fabric.js#9487]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

It would be great if we had the ability to switch the canvas library/instance which fabric.js internally uses on NodeJS.
We can use a better canvas library like - https://github.com/Brooooooklyn/canvas

### Current State

Right now I don't see any API where we can pass our custom canvas instance.

**Comment by ShaMan123** [comment]
I don't know that repo.
But that does not matter.
As long as it exposes a canvas API it should work
Take a look at [index.node.ts](https://github.com/fabricjs/fabric.js/blob/5be981ebe8ee919718ee3b2580908cf48177e5da/index.node.ts) which is the node bindings file
You should do the same.

1.  call `setEnv`
2. `export * from './fabric'`
3. override for specific bindings

I would appreciate you adding a comment here with a working example or better of add a demo to the [new website](https://github.com/fabricjs/fabricjs.github.io)

**Comment by ShaMan123** [comment]
I think we can close this ticket, correct me if i am wrong

**Comment by ShivamJoker** [comment]
@ShaMan123 thanks for the quick followup but I am not sure I understand how to pass my own canvas.
If you could elaborate a bit more, it will be helpful.

**Comment by ShaMan123** [comment]
Ahh yes, sorry.
Currently fabric relies on JSDOM for some minor stuff (I think it is not a must)
Including `window.createElement('canvas')` and  `window.createElement('image')`
Look into JSDOM and how to instruct it to pull your impl.
Hopefully that will be straight forward.
