### ISSUE TITLE
[Feature]: how can i  cancel  shadow when scaling

### ISSUE THREAD

**Issue by hengyuli** [fabricjs/fabric.js#9509]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

<!DOCTYPE html>
<html lang="zh">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	
  <title>FabricJS</title>
  <style>
    .box {
      position: relative;
    }
    #canvas {
      border: 1px solid #ccc;
    }
  </style>
</head>
<body>

<div class="box">
  <canvas id="canvas" width="1300" height="600"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/fabric"></script>
<script>
  // 文档加载后执行
  window.onload = function() {
    // 初始化画布
    init()
  }

  // 画布实例
  let canvas = null
  // 当前选中的元素
  let activeEl = null

  // 初始化
  function init() {
    canvas = new fabric.Canvas('canvas', {
		uniformScaling: false
    })
    // 矩形
    const rect = new fabric.Rect({
	  left: 100,
      top: 100,
      width: 200,
      height: 100,
      fill: 'transparent',
	  borderColor: '#666666',
	  hasBorders: true, // 控制边框
	  fill: 'transparent', // 填充色
	  cornerColor: '#00FF00', // 控制角颜色
	  cornerSize: 12, // 控制角大小
	  cornerStyle: 'circle',
	  transparentCorners: true, // 控制角填充色透明
	  stroke: '#050505',
	  strokeWidth: 2, // 设置边框宽度
	  strokeUniform: true
    })
	rect.setControlsVisibility({ 
	  mtr: false,
	  mt: false,
	  mb: false,
	  ml: false,
	  mr: false
	})

    // 将矩形添加到画布中
    canvas.add(rect);
  }

</script>
</body>
</html>

### Current State

![errorstate](https://github.com/fabricjs/fabric.js/assets/19280147/c73cd8f2-dfe4-463a-abef-39169f54634f)

### Additional Context

when i scaling rect , i want stroke no shadow 
thanks!

**Comment by melchiar** [comment]
`rect.set('noScaleCache', false);`

http://fabricjs.com/docs/global.html#noScaleCache

**Comment by hengyuli** [comment]
thanks!!!!
