### ISSUE TITLE
[Bug]: dynamic draw polyline will disappear after move canvas

### ISSUE THREAD

**Issue by a873054267** [fabricjs/fabric.js#9530]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.2.4

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/p/devbox/fabric-vanillajs-sandbox-forked-yfyl89?file=%2Findex.html%3A252%2C8

### Steps To Reproduce

1. left click to start draw
2. left down to move canvas
3. when move out of init canvas boundary,line will disappear 

### Expected Behavior

line will show;

### Actual Behavior

line disappear 

### Error Message & Stack Trace

```bash
no error;
maybe clipped by Frustum；
```

**Comment by asturur** [comment]
there is no code in the sandbox
