### ISSUE TITLE
[Bug]: What is the situation where a group composed of two polygons in fabricjs is restricted to a rectangular area when dragging points, and graphics are not displayed outside the rectangular area?

### ISSUE THREAD

**Issue by qingwenje2008** [fabricjs/fabric.js#9534]
### CheckList

- [ ] I agree to follow this project's Code of Conduct
- [ ] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [ ] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [ ] I have searched and referenced existing issues and discussions
- [ ] I am filing a **BUG** report.
- [ ] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [ ] I have created an accurate and minimal reproduction

### Version

6.0.0-beta9

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

16.13.1

### Link To Reproduction

The company's products are currently unavailable

### Steps To Reproduce

1. What is the situation where a group composed of two polygons in fabricjs is restricted to a rectangular area when dragging points, and graphics are not displayed outside the rectangular area?
2. Some of the codes are as follows：
` getPolyBox(points, ishole) {
        const boxAttr = this.configuration.boxAttr[BoxTypes.PolyBox] || {};
        const { default_line_color, line_width, point_size, default_point_color } = boxAttr || {};
        const polyboxes = [];
        let params;

        if (ishole) {
            params = {
                stroke: default_line_color,
                strokeWidth: Number(line_width) / this.canvas.getZoom(),
                fill: "rgba(0, 0, 0, 0)",
                name: BoxTypes.PolyBox,
                hasBorders: false,
                hasControls: true,
                objectCaching: false,
                originX: 'center',
                originY: 'center',
                cornerStyle: 'circle',
                cornerSize: point_size,
                cornerColor: default_point_color,
            }
            const polyBox1 = new fabric.Polygon(points, params);
            const params2 = { ...params }
            params2.globalCompositeOperation = 'destination-out'
            params2.fill = "rgb(22, 222, 0)"
            params2.isData = true
            const polyBox2 = new fabric.Polygon(points, params2);
            polyboxes.push(polyBox2)
            polyboxes.push(polyBox1)
        } else {
            params = {
                stroke: default_line_color,
                strokeWidth: Number(line_width) / this.canvas.getZoom(),
                fill: "rgba(0, 0, 0, 0)",
                name: BoxTypes.PolyBox,
                hasBorders: false,
                hasControls: true,
                originX: 'center',
                originY: 'center',
                cornerStyle: 'circle',
                objectCaching: false,
                cornerSize: point_size,
                cornerColor: default_point_color,
                transparentCorners: false,
                isData: true
            }
            const polyBox = new fabric.Polygon(points, params);
            polyboxes.push(polyBox)
        }
        return polyboxes
    }

    createGroup(polyboxes) {
        const boxAttr = this.configuration.boxAttr[BoxTypes.PolyBox] || {}
        const { default_line_color, line_width } = boxAttr || {}
        const group = new fabric.Group(polyboxes, {
            stroke: default_line_color,
            statusColor: default_line_color,
            strokeWidth: Number(line_width) / this.canvas.getZoom(),
            name: BoxTypes.PolyHole,
            noScaleCache: false,
            originX: 'center',
            originY: 'center',
            hasBorders: false,
            hasControls: false,
            // objectCaching: false,
            strokeUniform: true,
            centeredScaling: true,
            padding: 0,
            lockScalingFlip: true,
        });
        return group;
    }`
3.
<img width="239" alt="CA3AB690-1FC5-45d8-B490-C00FC6C5B77B" src="https://github.com/fabricjs/fabric.js/assets/8563448/cb5ae494-894e-4cfc-b9d9-5de1a1f7a491">
<img width="279" alt="74805A2E-606B-4c61-9CEA-640D3455EAD9" src="https://github.com/fabricjs/fabric.js/assets/8563448/caa4f5fb-4960-43a8-b324-02041d29cc73">
<img width="234" alt="B5972982-D165-4fb5-9961-4EE6F3249D8B" src="https://github.com/fabricjs/fabric.js/assets/8563448/459df485-4855-4ce4-93e6-52477662f5c7">
<img width="230" alt="2AC86103-1E4A-4681-B0EE-902BA8B43BAA" src="https://github.com/fabricjs/fabric.js/assets/8563448/2e683cbc-4fc9-4a97-b3fd-f61dc487c9ae">

### Expected Behavior

Expect polygons to render properly

### Actual Behavior

As shown in the figure

**Comment by ShaMan123** [comment]
I missed this, I will PR
We need to subscribe to the poly change event 

https://github.com/fabricjs/fabric.js/blob/7154d143f0e34bf3e779b5b9592ca98e704ea2fd/src/LayoutManager/LayoutManager.ts#L68-L75

Regardless I recommend using `PolyLine#exactBoundingBox`

**Comment by qingwenje2008** [comment]
Thank you for your reply，but It didn't take effect. I changed it to polyline and used the exactBoundingBox attribute. Both true and false are the same as before

**Comment by qingwenje2008** [comment]
> I missed this, I will PR We need to subscribe to the poly change event
> 
> https://github.com/fabricjs/fabric.js/blob/7154d143f0e34bf3e779b5b9592ca98e704ea2fd/src/LayoutManager/LayoutManager.ts#L68-L75
> 
> Regardless I recommend using `PolyLine#exactBoundingBox`

Thank you for your reply，but It didn't take effect. I changed it to polyline and used the exactBoundingBox attribute. Both true and false are the same as before

**Comment by ShaMan123** [comment]
The PR fixes it but it still is WIP
