### ISSUE TITLE
[Feature]: In a multi-select scenario, when a subset is selected, the parent element should be deselected.

### ISSUE THREAD

**Issue by zhe-he** [fabricjs/fabric.js#9542]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

1. Create a red rectangle A and a yellow rectangle B.
2. Create a group G with A and B.
3. Create a blue rectangle C.
4. Select G and C by dragging a selection box.
5. While holding down the shift key for multi-selection, select rectangle B.

### Current State

Both G and C and B are selected, G should be deselected, leaving only C and B selected. The following two videos show the actual result and the expected result, respectively. The last link is the test URL.

### Additional Context

https://github.com/fabricjs/fabric.js/assets/11306583/4bc8f6ed-f2a0-483d-933a-a4a5e0a53112

https://github.com/fabricjs/fabric.js/assets/11306583/dc2d7ef5-d9a1-436a-8681-c99ad609c4f0

[demo](https://codesandbox.io/p/devbox/multiple-selection-639h79?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq1sij7y00073b6i7lejmm2a%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq1sij7x00023b6inuawv0tp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq1sij7x00043b6iiezg25ja%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq1sij7x00063b6i0u8nabsa%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq1sij7x00023b6inuawv0tp%2522%253A%257B%2522id%2522%253A%2522clq1sij7x00023b6inuawv0tp%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clq1sij7x00063b6i0u8nabsa%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq1sij7x00053b6ilijg3e7x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clq1sij7x00063b6i0u8nabsa%2522%252C%2522activeTabId%2522%253A%2522clq1sij7x00053b6ilijg3e7x%2522%257D%252C%2522clq1sij7x00043b6iiezg25ja%2522%253A%257B%2522id%2522%253A%2522clq1sij7x00043b6iiezg25ja%2522%252C%2522activeTabId%2522%253A%2522clq1sij7x00033b6ibqbb44f4%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq1sij7x00033b6ibqbb44f4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clq1siyrm007f3b6i9t68ewil%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clq1siyzr00rueeipfu61de3v%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by ShaMan123** [comment]
Your UX involves ungrouping?

**Comment by zhe-he** [comment]
Sorry, I thought all the group-related functionalities had already been developed, but it turns out they haven't, so I opened this issue. I made some modifications to the source code locally, hoping it can be helpful for you.

```typescript
handleMultiSelection: function(e: TPointerEvent, target?: FabricObject) {
    // ...
     if (isAS) {
        // ...
        if (target.group === activeSelection) {
                // `target` is part of active selection => remove it
        } else {
+               const objects = activeSelection.getObjects();
+                // Remove the parent set of `target` => remove it's parent
+                let p = target.parent;
+                while (p) {
+                    if (objects.includes(p)) {
+                        activeSelection.remove(p);
+                        break;
+                    }
+                   p = p.parent;
+                }
+                // Remove the subset of the `target` => remove it's children
+                if (target instanceof Group) {
+                    for (const obj of objects) {
+                        let p = obj.parent;
+                        while (p) {
+                           if (target == p) {
+                                activeSelection.remove(obj);
+                                break;
+                            }
+                            p = p.parent;
+                        }
+                    }
+                }

               //  `target` isn't part of active selection => add it
         }
      }
   // ... 
}
```
