### ISSUE TITLE
[Bug]: lowerCanvas is set to different size than upperCanvas when emulating mobile device on Chrome

### ISSUE THREAD

**Issue by avnermosh** [fabricjs/fabric.js#9546]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/avnerm/Lk2hmq1o/73/show

### Steps To Reproduce

In the example: https://jsfiddle.net/avnerm/Lk2hmq1o/73/show
1. click F12 in Chrome (to get the debugger)
2. click on the "Toggle device toolbar" button and selecting one of the simulated devices (e.g. iPhoneSE).
3. Reload the page in this configuration (by pressing F5)
4. Draw on Canvas0 (the left canvas) using mobile emulation

### Expected Behavior

lowerCanvas and upperCanvas should have the same size

### Actual Behavior

The lowerCanvas **sometimes** shows up as 512x512

In my code, I set the size of the fabricCanvas via fabricCanvas.setDimensions({width:256, height:256});
The upperCanvas gets the correct size but the lowerCanvas gets a size of 512x512 (could this be a default size? becuase I don't instruct 512 anywhere in the code).
Is there a way to specifically set the size of the lowerCanvas, to fix this problem?
I also filed a question with example code in here 
https://stackoverflow.com/questions/77642825/fabricjs-does-not-render-properly-when-simulating-a-mobile-touch-device
Thanks

**Comment by avnermosh** [comment]
Based on [this link](https://stackoverflow.com/questions/60350747/fabric-js-patterns-how-create-pattern-for-canvas-background-from-rects-without) I set fabric.devicePixelRatio, e.g. `fabric.devicePixelRatio = 1; ` before initializing the canvas and this solved the problem.

**Comment by ShaMan123** [comment]
First of all - a VERY cool demo. VERY.
Second, you pointed out the source of the issue. I believe a complete solution is to apply the retina scaling factor on your canvas, I am not sure you did that. I just saw you were manipulating canvas dimensions so I assume that.


https://github.com/fabricjs/fabric.js/blob/e4ac8b5284b2c1be80b6174d9b8d31e41136e8ce/src/canvas/DOMManagers/util.ts#L10-L23

**Comment by ShaMan123** [comment]
Do you mind to post the demo in the show and tell section
It is great
