### ISSUE TITLE
[Bug]: Fabric.js is not defined

### ISSUE THREAD

**Issue by omatheusant** [fabricjs/fabric.js#9549]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Node.js

### Node Version (if applicable)

20.10.0

### Link To Reproduction

https://github.com/omatheusant/ismafer-next

### Steps To Reproduce

1. clone the repo in your local machine with git clone 'https://github.com/omatheusant/ismafer-next'
2. npm install
3. npm run dev
4. open http://localhost:3000/tools/editor

### Expected Behavior

Load a Editor (like Canva) that allow the user to manipulate images, dragging, erasing, add text, etc.
![Screenshot_79](https://github.com/fabricjs/fabric.js/assets/136248023/65b9eee2-3e22-47ff-95eb-a25f2d09968c)

### Actual Behavior

In local, the pages run correctly, but the error "Fabric is not defined" appears on terminal.
When I try to deploy it on vercel, this error block the deployment to sucessfull.

On Vercel:
![Screenshot_80](https://github.com/fabricjs/fabric.js/assets/136248023/0b5450d9-0929-4d2c-96f4-9752cecb03a5)

### Error Message & Stack Trace

```bash
⨯ node_modules\fabric-history\src\index.min.js (1:0) @ fabric
 ⨯ ReferenceError: fabric is not defined
    at __webpack_require__ (C:\Users\PC CASA\Documents\Estudos-Programação\projetos\ismafer\ismafer-next\.next
\server\webpack-runtime.js:33:43)
    at eval (./src/app/tools/editor/page.jsx:11:72)
    at (ssr)/./src/app/tools/editor/page.jsx (C:\Users\PC CASA\Documents\Estudos-Programação\projetos\ismafer\
ismafer-next\.next\server\app\tools\editor\page.js:468:1)
    at __webpack_require__ (C:\Users\PC CASA\Documents\Estudos-Programação\projetos\ismafer\ismafer-next\.next
\server\webpack-runtime.js:33:43)
    at JSON.parse (<anonymous>)
null
```

**Comment by ShaMan123** [comment]
Did you build?

**Comment by omatheusant** [comment]
I need to run npm run build before deployment? I'm pretty new to nextjs and fabric, so I don't understand your question

**Comment by omatheusant** [comment]
> Did you build?


I need to run npm run build before deployment? I'm pretty new to nextjs and fabric, so I don't understand your question

**Comment by omatheusant** [comment]
I just use cd node_modules/fabric && node build.js modules=ALL exclude=accessors,gestures requirejs minifier=uglifyjs with patch package to create the custom build to EraserBrush and is working well in local (even with the error)

**Comment by ShaMan123** [comment]
> > Did you build?
> 
> I need to run npm run build before deployment? I'm pretty new to nextjs and fabric, so I don't understand your question

> I just use cd node_modules/fabric && node build.js modules=ALL exclude=accessors,gestures requirejs minifier=uglifyjs with patch package to create the custom build to EraserBrush and is working well in local (even with the error)

Use you r command as the `postinstall` script in your package.json and then it will run when needed
