### ISSUE TITLE
[Bug]: Canvas load from json, group nested objects invisible after changing position

### ISSUE THREAD

**Issue by dendrofen** [fabricjs/fabric.js#9552]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta16

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

20.10.0

### Link To Reproduction

https://codesandbox.io/p/sandbox/vigilant-dirac-forked-268ln7

### Steps To Reproduce

1. create group with objects
2. set objects and group with controls: false
3. export canvas to object, than convert to json
4. load canvas from json
5. move object outside of its original position to right
6. move group position

### Expected Behavior

Group should change it's bounding box, objects should be visible.

### Actual Behavior

Object after changing position become invisible, looks like group is not updating it's size.

**Comment by dendrofen** [comment]
https://github.com/fabricjs/fabric.js/issues/9331

looks like, same issue here

**Comment by ShaMan123** [comment]
seems to #9537 fixes this.

**Comment by dendrofen** [comment]
@ShaMan123 but it's still in pr, not merged..?

**Comment by ShaMan123** [comment]
true, should merge soon, a week max
the bug is that the layout manager doesn't subscribe your objects so if they move the group doesn't layout.

**Comment by ShaMan123** [comment]
you can work around by calling the LayoutManager#subscribe

**Comment by dendrofen** [comment]
> true, should merge soon, a week max the bug is that the layout manager doesn't subscribe your objects so if they move the group doesn't layout.

@ShaMan123 may you provide some code example? I'm still waiting for pr merge, but code example will be good temporary solution.
