### ISSUE TITLE
[Feature]: In mobile device lower-canvas height and width attribute value is greater then upper-canvas

### ISSUE THREAD

**Issue by niketaOptimumnbrew** [fabricjs/fabric.js#9553]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

![image](https://github.com/fabricjs/fabric.js/assets/126561906/be3a89c2-ad30-4830-8126-0d14473e81ab)
Why lower-canvas height and width is different from upper-canvas only in mobile device ?

### Current State

when I set the canvas height and width to 1500px then lower-canvas height will be 3000px.
can you please tell me why this happen?

**Comment by asturur** [comment]
Which version are you using? This was an old setup of fabricJS in which the upper canvas wasn't retina scaled

**Comment by niketaOptimumnbrew** [comment]
> Which version are you using? This was an old setup of fabricJS in which the upper canvas wasn't retina scaled

i'm using fabric.js version 1.7.22

**Comment by asturur** [comment]
is a version of from around 2016.
Yes top canvas wasn't retina scaled.
The difference in size is as much as the 'devicePixelRatio' value of your window object.

**Comment by niketaOptimumnbrew** [comment]
> is a version from around year 2016. Yes top canvas wasn't retina scaled. The difference in size is as much as the 'devicePixelRatio' value of your window object.

Thank you, @asturur , for your valuable contributions to this project!

Is their any solution for canvas retina scale in fabric.js version 1.7.22?
