### ISSUE TITLE
[Bug]:  Components uninteractable in deveoplment mode but work in production

### ISSUE THREAD

**Issue by ashmit-coder** [fabricjs/fabric.js#9554]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta9

### In What environments are you experiencing the problem?

Node.js

### Node Version (if applicable)

19.8.1

### Link To Reproduction

No Link

### Steps To Reproduce

1.  Create any react project  and utilize fabricjs library
2.  Run in development mode
3. Run after build

### Expected Behavior

The added components should be able to be interacted while in development mode, but are nor

### Actual Behavior

The added shapes or objects from fabricjs are uninteractable in development mode but seem to work just fine after build.

### Error Message & Stack Trace

```bash
Idk if this is a issue with react or fabric but running it with as well did not work. Resulting the same issue.
```

**Comment by ShaMan123** [comment]
This issue will be closed until a clear and concise **LIVE** reproduction is provided

**Comment by StringKe** [comment]
The reason could be that `React.StrictMode` schedules useEffect twice during development, which causes FabricJS to initialize twice.

**Comment by ashmit-coder** [comment]
> The reason could be that `React.StrictMode` schedules useEffect twice during development, which causes FabricJS to initialize twice.

Okay I do think so that's the case but is there anyway we could patch it 🤨

**Comment by StringKe** [comment]
> > The reason could be that `React.StrictMode` schedules useEffect twice during development, which causes FabricJS to initialize twice.
> 
> Okay I do think so that's the case but is there anyway we could patch it 🤨

There is no better way because fabric is currently initialized and destroyed asynchronously. Any ref-like state management is not comprehensive enough.

**Comment by ashmit-coder** [comment]
> > > The reason could be that `React.StrictMode` schedules useEffect twice during development, which causes FabricJS to initialize twice.
> > 
> > Okay I do think so that's the case but is there anyway we could patch it 🤨
> 
> There is no better way because fabric is currently initialized and destroyed asynchronously. Any ref-like state management is not comprehensive enough.

In my project I had to manage the state using both ref and effect hooks as sometimes the state would get lost without the ref and re rendering does not seem to provide any help

**Comment by ShaMan123** [comment]
It seems we must revert the async disposing
I want fabric to mutate the dom in a more subtle way without changing the canvas parent. Instead we should accept a container div and restrict all Dom mutations to that container.
I think the problem is the the context is nullified when the canvas element is removed from the dom, is that right?

**Comment by ShaMan123** [comment]
I no longer understand this bug report

Add clear and concise **LIVE** reproduction

**Comment by ShaMan123** [comment]
> This issue will be closed until a clear and concise **LIVE** reproduction is provided

I already requested that.

**Comment by ashmit-coder** [comment]
> > This issue will be closed until a clear and concise **LIVE** reproduction is provided
> 
> I already requested that.
> 

I will give a live in some time, this report was a hasty one cause the bug caused a lot of problems in our project while production
