### ISSUE TITLE
[Bug]: createPolyControls with two points (Line) has locked axis

### ISSUE THREAD

**Issue by vshepel** [fabricjs/fabric.js#9556]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta16

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/p/devbox/fabric-vanillajs-sandbox-forked-nfc5j4

### Steps To Reproduce

Try to move control points of red and green polygons (Lines)

### Expected Behavior

These points should not be fixed on the axis when approaching 0 values

### Actual Behavior

https://github.com/fabricjs/fabric.js/assets/14239290/abde23bf-4701-40af-860c-979d37122de3

**Comment by ShaMan123** [comment]
This is related to #9436 #9496 but I am curious if #9496 solves it

**Comment by vshepel** [comment]
@ShaMan123 I'm trying to migrate changes from #9496, but this error is not fixed, have you tested before?

**Comment by ShaMan123** [comment]
No
That is why I mentioned I am not sure

**Comment by gloriousjob** [comment]
This definitely looks different. The polygon would disappear if it was the issue from #9496. That said, I wouldn't be shocked if we could figure something out here that may help with that issue (NaN happening).

Something else to note is if you play around with the green line and leave it in a horizontal or vertical state, it sometimes locks in that similar to the red line. It sounds like some multiplication is causing an axis to 0 out but unclear since there's several math operations going on.

**Comment by asturur** [comment]
I m attempting to remove the size entirely from polyControl so we avoid issues with zero sizes, so assigning this to myself

**Comment by asturur** [comment]
https://github.com/fabricjs/fabric.js/pull/9575
This fixes the mentioned bug

**Comment by asturur** [comment]
This is solved, together with another bug 🎉

**Comment by vshepel** [comment]
@asturur I'm not sure if this fixes this bug. I just upgraded to beta17, but it looks worse now

https://codesandbox.io/p/devbox/fabric-vanillajs-sandbox-forked-nfc5j4

**Comment by ShaMan123** [comment]
https://codesandbox.io/p/devbox/fabric-vanillajs-sandbox-forked-v5wz9k?file=%2Fsrc%2Findex.ts%3A63%2C3

It is related to `exactBoundingBox: false`, if you flag as true it works
