### ISSUE TITLE
[Bug]: setBackgroundColor invalid

### ISSUE THREAD

**Issue by QC2168** [fabricjs/fabric.js#9557]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

18.0.0

### Link To Reproduction

None

### Steps To Reproduce

1. After calling canvas.setBackgroundImage() and rendering the canvas, it functions as expected.
2. However, when subsequently calling canvas.setBackgroundColor(), it does not take effect.
3. If you first call canvas.setBackgroundColor(), it functions as expected.

### Expected Behavior

it should replace current background

### Actual Behavior

It not work

### Error Message & Stack Trace

```bash
No error occurred in the console
```

**Comment by QC2168** [comment]
This is a mini demo. Start by clicking the `Set Background Image` button, and then proceed to click the `Set Background Color` . The issue will reoccur

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Fabric.js Demo</title>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fabric.js/3.6.3/fabric.min.js"></script>
</head>
<body>
  <canvas id="canvas" width="400" height="300"></canvas>
  <button onclick="setBackgroundColor()">Set Background Color</button>
  <button onclick="setBackgroundImage()">Set Background Image</button>

  <script>
    var canvas = new fabric.Canvas('canvas');

    function setBackgroundColor() {
      // Set background color to red
      canvas.setBackgroundColor('red', canvas.renderAll.bind(canvas));
    }

    function setBackgroundImage() {
      fabric.Image.fromURL('./bg.jpeg', function (img) {
        canvas.setBackgroundImage(img, canvas.renderAll.bind(canvas));
      });
    }
  </script>
</body>
</html>

```

**Comment by POKEZHANG** [comment]
It’s not that it doesn’t work, it’s that the background image covers the background color.

**Comment by ShaMan123** [comment]
These methods are deprecated in v6

**Comment by QC2168** [comment]
> These methods are deprecated in v6

How to fix these problem in v5.3？

**Comment by ShaMan123** [comment]
> It’s not that it doesn’t work, it’s that the background image covers the background color.

as @POKEZHANG said, is this a real bug?

**Comment by QC2168** [comment]
I have currently resolved this issue by resetting it, but there will be type warnings in typescript
```typescript
// @ts-ignore
canvas.setBackgroundImage(null, canvas.renderAll.bind(canvas))
```

**Comment by TM312** [comment]
@ShaMan123 how can I update the background color of my canvas in v6? The docs seem outdated: http://fabricjs.com/docs/fabric.Canvas.html#setBackgroundColor

**Comment by asturur** [comment]
`canvas.backgroundImage = fabricImage();`
