### ISSUE TITLE
[Bug]: font weight is not working

### ISSUE THREAD

**Issue by shivamItt** [fabricjs/fabric.js#9559]
### CheckList

- [ ] I agree to follow this project's Code of Conduct
- [ ] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [ ] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [ ] I have searched and referenced existing issues and discussions
- [ ] I am filing a **BUG** report.
- [ ] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [ ] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Node.js

### Node Version (if applicable)

18.18.2

### Link To Reproduction

Hi, I am registering a font family with normal weight, and then setting fontWeight in fabricjs object with bold. I don't see any difference with bold or normal fontWeight

### Steps To Reproduce

```
const jsonData = {
    "objects":
        [
            {
                "resourceId": "f884ca26-0edb-4547-88be-ae999fb09f2a",
                "fontWeightId": "3c64491a-2020-4e4b-b240-f30dbcc18847",
                "fontFamilyId": "da271878-db46-44c3-9297-f658918c0ea4",
                "type": "textbox",
                "version": "5.3.0",
                "originX": "left",
                "originY": "top",
                "left": 323.81,
                "top": 208.9,
                "width": 323.89,
                "height": 79.09999999999998,
                "fill": "rgba(255, 255, 255, 1)",
                "stroke": "#000",
                "strokeWidth": 0,
                "strokeDashArray": [],
                "strokeLineCap": "butt",
                "strokeDashOffset": 0,
                "strokeLineJoin": "miter",
                "strokeUniform": true,
                "strokeMiterLimit": 4,
                "scaleX": 0.39,
                "scaleY": 0.39,
                "angle": 0,
                "flipX": false,
                "flipY": false,
                "opacity": 1,
                "visible": true,
                "backgroundColor": "",
                "fillRule": "nonzero",
                "paintFirst": "stroke",
                "globalCompositeOperation": "source-over",
                "skewX": 0,
                "skewY": 0,
                "fontFamily": "Press Start 2P Regular123",
                "fontWeight": "bold",
                "fontSize": 70,
                "text": "Headline",
                "underline": false,
                "overline": false,
                "linethrough": false,
                "textAlign": "center",
                "fontStyle": "normal",
                "lineHeight": 1.16,
                "textBackgroundColor": "",
                "charSpacing": 0,
                "styles": [],
                "direction": "ltr",
                "path": null,
                "pathStartOffset": 0,
                "pathSide": "left",
                "pathAlign": "baseline",
                "minWidth": 20,
                "splitByGrapheme": false
            }
        ],
    "background": "rgba(0, 0, 0, 0)"
};

var fs = require("fs"),
    fabric = require("fabric").fabric,
    imageDataURI = require("image-data-uri"),
    out = fs.createWriteStream(__dirname + "/new.png");
fabric.nodeCanvas.registerFont(__dirname + '/Press_Start_2P/PressStart2P-Regular.ttf', {
    family: 'Press Start 2P Regular123', weight: "normal"
});

fabric?.Textbox?.fromObject(jsonData.objects[0], async function (obj) {
    try {
        const image = obj.toDataURL({ format: "image/png", withoutShadow: false });
        await imageDataURI.outputFile(image, "./stroke.png");
    } catch (error) {
        reject(error);
    }
});
```

### Expected Behavior

Above code should generate a bold text image

### Actual Behavior

It is generating regular text image

### Error Message & Stack Trace

```bash
There is no error
```

**Comment by shivamItt** [comment]
Hi,
Here is the working example for the same [Live code sample](https://codesandbox.io/p/devbox/fabric-js-text-xlqh8c)

2 images are generated by the above code sample

1. text-with-bold-font-weight.png :- this image is generated by object having fontWeight equal to bold
2. text-with-norma-font-weight.png :- this image is generated by object having fontWeight equal to normal

Still both the images are same.

**Comment by ShaMan123** [comment]
Your repro is broken, please follow this repro https://codesandbox.io/p/devbox/fabric-node-sandbox-forked-xewlhg
