### ISSUE TITLE
[Bug]: Hello, after using fabric.eraserbrush, the large image may become blurry. Why is this? How to solve it

### ISSUE THREAD

**Issue by ctheart** [fabricjs/fabric.js#9580]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.2.1

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

19.2.0

### Link To Reproduction

No reproduction

### Steps To Reproduce

1.       const canvas = this.__canvas = new fabric.Canvas('c')
    const img1 = new Image();
    img1.src = '../../../images/1.jpg'
    img1.onload = () => {
      const renderImage = new fabric.Image(img1, {
       width: 5000,
       height: 5000,
       left: 0, // 设置图像的水平位置  
       top: 0, // 设置图像的垂直位置  
       angle: 0, // 设置图像的旋转角度  
       opacity: 1, // 设置图像的透明度
       id: 'renderImage'
   })
      // 将图像添加到画布上  
    canvas.add(renderImage);  
    // 可选：使画布重新渲染，以确保图像正确显示  
    canvas.renderAll(); 
    }
2. canvas.freeDrawingBrush = new fabric.EraserBrush(canvas)
3. canvas.freeDrawingBrush.width = 50
4.

### Expected Behavior

after drawing，The img1 image displays normally without blurring

### Actual Behavior

After drawing a path, the img1 image becomes blurry in display

**Comment by ShaMan123** [comment]
This issue will be closed until a clear and concise **LIVE** reproduction is provided 
Please provide visuals as well
