### ISSUE TITLE
BUG: Textbox style initial layout

### ISSUE THREAD

**Issue by ShaMan123** [fabricjs/fabric.js#9589]
I am debugging some issue and came to think of the following:

I need styles ready when running text layout.
All that happens in initDimensions.
However text style map is generated in the same method after text has been wrapped
So it seems that this is a built in bug in design

Yet another reason to redo text styles.

https://github.com/fabricjs/fabric.js/blob/312cd1704ae1dc86e07291534f3f2e006ff23fbc/src/shapes/Textbox.ts#L120

Text wrapping occurs under `_splitText` and uses the style map?

**Comment by asturur** [comment]
What is the bug? what does not work properly?

**Comment by asturur** [comment]
The splitText function uses the non wrapped style to get text measurement,
once the text has been wrapped it creates a styleMap to reverse check from wrapped line to unwrapped.
What is that is not working?

**Comment by ShaMan123** [comment]
Ahh so maybe I got confused.
When we plan this I want the array of char to contain an object of the char, style, row, col, measurements etc. and that object to be referenced by all the arrays we used so then we update the object once.
