### ISSUE TITLE
[Bug]: strokeWidth false on rect

### ISSUE THREAD

**Issue by tgoeminne** [fabricjs/fabric.js#9590]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta9

### Node Version (if applicable)

None

### Link To Reproduction

dd

### Steps To Reproduce

I try set strokeWidth to false on rect but it does not work like it works with text

### Expected Behavior

stroke removed

### Actual Behavior

stroke stays

### Error Message & Stack Trace

```bash
d
```

**Comment by tgoeminne** [comment]
my suggestion is also change strokeWidth so setting it to 0 will remove stroke (instead of using false)

**Comment by tgoeminne** [comment]
ok apparently setting it to 0 did work can close this

**Comment by gloriousjob** [comment]
@tgoeminne agreed. The way I see this is the reverse of the report. Width is a number, not a boolean. If anything, maybe text shouldn't allow for false to reduce confusion if anything were fixed.

**Comment by ShaMan123** [comment]
Guys you need to use it properly
A shoe can fit my hand but why should I do that?
