### ISSUE TITLE
[Bug]: Controls are unclickable in the correct (visual) position

### ISSUE THREAD

**Issue by anig1scur** [fabricjs/fabric.js#9592]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [ ] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [ ] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [ ] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://r.piggy.lol/collage-poem/

The core code related to fabric can be found here: https://github.com/anig1scur/collage-poem/blob/master/src/core/fabric/FabricRelated/FabricContext.ts

### Steps To Reproduce

access  https://r.piggy.lol/collage-poem/ and click any imgs on the left, try to click the object in the canvas, resize or delete it. All the controls are unclickable on the visual position, instead, they could be clicked in the blue field as below.

![image](https://github.com/fabricjs/fabric.js/assets/52899668/06a6dff7-bab1-460b-abc3-53097c584a76)

### Expected Behavior

controls action in the correct postion 

### Actual Behavior

controls action in the invisible position

**Comment by Smrtnyk** [comment]
http://fabricjs.com/fabric-gotchas
maybe you got hit by the first gotcha in this list

**Comment by anig1scur** [comment]
I found that it was because I added border to the canvas. After I wrappered ( upper and lower ) canvas in div with border, the controls can work well.

![image](https://github.com/fabricjs/fabric.js/assets/52899668/e08956ce-3f06-4deb-88a5-6ed425f4efc6)

**Comment by ShaMan123** [comment]
Good catch, did you try to call `calcOffset`?

**Comment by anig1scur** [comment]
> Good catch, did you try to call `calcOffset`?

I haven't tried that yet. After your reminder, I attempted to use this API, but it still doesn't seem to be working. There is still some offset between the upper and lower canvas. You can check here:

https://stackblitz.com/edit/js-fabric-draw-cdojya?file=index.js
