### ISSUE TITLE
[Bug]: Obtain the vertex coordinate information of the deformed shape

### ISSUE THREAD

**Issue by Jinxishihenian** [fabricjs/fabric.js#9628]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### Node Version (if applicable)

None

### Link To Reproduction

http://fabricjs.com/custom-controls-polygon

### Steps To Reproduce

It is well known that fabricjs is very easy to create, round, rectangular, irregular shapes, and then we can flip, tilt, scale... These are convenient operations, but I want to get this shape information, deformation (flip, tilt, zoom... These operations) after the final coordinate information.

### Expected Behavior

The coordinate information of the deformed vertex can be obtained.

### Actual Behavior

At present, only the initial coordinate information before deformation can be obtained.

**Comment by ShaMan123** [comment]
duplicate #9629
