### ISSUE TITLE
[Bug]: util.groupSVGElements not parsing loadSVGFromString options

### ISSUE THREAD

**Issue by Cayllen** [fabricjs/fabric.js#9633]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta18

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

18.16.0

### Link To Reproduction

https://codesandbox.io/p/devbox/fabric-vanillajs-sandbox-forked-qlt7gj?file=%2Fsrc%2Findex.ts%3A18%2C24

### Steps To Reproduce

1. See codesandbox

### Expected Behavior

SVG is displayed

### Actual Behavior

Error is thrown. 
Tooltip in VSCODE:
```
Argument of type 'Element' is not assignable to parameter of type 'FabricObject<Partial<FabricObjectProps>, SerializedObjectProps, ObjectEvents>[]'.
  Type 'Element' is missing the following properties from type 'FabricObject<Partial<FabricObjectProps>, SerializedObjectProps, ObjectEvents>[]': length, pop, push, concat, and 35 more.ts(2345)
```

In browser console of codesandbox
`Uncaught TypeError: objects.slice is not a function`
and my local version
`Uncaught (in promise) TypeError: this._objects is not iterable
`

**Comment by Cayllen** [comment]
Solved it using another notation for anyone coming here but I guess this is still a bug

```
loadedSVG = await loadSVGFromString(mySVGCode);
var svgData = util.groupSVGElements(loadedSVG.objects);
```

**Comment by asturur** [comment]
hi @Cayllen the callback there is not a callback for the load process, is a function that you can optionally pass that will run for each object and will let you work on the object parsed and the original element in the SVG context.

Its usage is very rare, i personally use it to reconstruct groups from flattened svgs.

the code with wich you solved is the correct usage.

**Comment by Cayllen** [comment]
Ah I see, thanks! So in this case the example from the doc is for the old version I assume
![image](https://github.com/fabricjs/fabric.js/assets/27898791/a0cc2809-9d20-4264-bc1f-bda778c5d8e1)
