### ISSUE TITLE
[Bug]: Google Chrome (v122) draws Patterns wrong

### ISSUE THREAD

**Issue by NamVTran** [fabricjs/fabric.js#9638]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.0.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

http://fabricjs.com/patterns

### Steps To Reproduce

Chrome version 122 draws rect Pattern of demo [http://fabricjs.com/patterns](http://fabricjs.com/patterns) wrong.
Likely relate to combination of translate, rotate, beginPath, closePath, and clip APIs of CanvasRenderingContext2d.
[https://bugs.chromium.org/p/chromium/issues/detail?id=1520871#c3](https://bugs.chromium.org/p/chromium/issues/detail?id=1520871#c3)

### Expected Behavior

In Chrome 121:
<img width="1440" alt="image" src="https://github.com/fabricjs/fabric.js/assets/79432552/345b79d4-3ef1-43c6-b7f5-89da2083ea51">

### Actual Behavior

In Chrome 122:
<img width="1440" alt="image" src="https://github.com/fabricjs/fabric.js/assets/79432552/93fc3221-89c7-4ccb-9ea2-d8760d423fd8">

**Comment by ShaMan123** [comment]
probably related to #9414

**Comment by NamVTran** [comment]
> probably related to #9414

Bug https://github.com/fabricjs/fabric.js/issues/9414 works well on Chrome 121 MacOS.

**Comment by NamVTran** [comment]
> if you disable hardware acceleration for a moment, does it work?

No, it still bug like that.

**Comment by ShaMan123** [comment]
Our tests should pick this up if we run on the specified version I believe

**Comment by ShaMan123** [comment]
maybe we should add a weekly trigger to test, not that it will give us anything actionable apart from the ability to file bugs in browser trackers

**Comment by NamVTran** [comment]
Cause this bug was fixed on the latest build of Chrome 122, so I close this issue now.

Thank you for your kind attentions.
