### ISSUE TITLE
[Bug]: group select 2 rects as ActiveSelection which custom the originX and originY as 'center', but the ActiveSelection shift bboxLeftTop as center.

### ISSUE THREAD

**Issue by ritali4912** [fabricjs/fabric.js#9640]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta18

### In What environments are you experiencing the problem?

Microsoft Edge

### Node Version (if applicable)

None

### Link To Reproduction

https://codepen.io/ritali4912/pen/QWYKVpo

### Steps To Reproduce

I custom the **ActiveSelection default originX and originY as 'center'** through update classRegistry.
There are 2 rects with originX and originY as 'center'.
rect1: {left: 150, top: 150, width: 60, height: 60, originX: 'center, originY: 'center'}
rect2: {left: 250, top: 250, width: 60, height: 60, originX: 'center, originY: 'center'}

In the begin, 
![image](https://github.com/fabricjs/fabric.js/assets/67466090/a6291107-fa38-4d6b-b48b-9dcf5bd0cd0b)

After I group select them though press left mouse and move, **the position changed.**
![image](https://github.com/fabricjs/fabric.js/assets/67466090/c541faa9-d21e-4aba-beb1-6d2155f2e325)

But if I rollback the ActiveSelection originX and originY as **'left' and 'top'**
It is correct.
![image](https://github.com/fabricjs/fabric.js/assets/67466090/d69d26d9-6088-4acb-bffd-49650505b00a)

BTW, with custom ActiveSelection originX and originY to 'center'.
If I generate the ActiveSelection with step:
1. Click rect1
2. press 'Shift' and click rect2
3. I got correct position of the ActiveSelection.

### Expected Behavior

The ActiveSelection has correct position even I custom originX and originY to '**center**'

### Actual Behavior

The ActiveSelection has wrong location if I custom originX and originY to '**center**'

When I debugging I found in the LayoutStrategy.cs->calcBoundingBox, it got correct bboxCenter, but then after translate with originFactor, it got wrong center.

![image](https://github.com/fabricjs/fabric.js/assets/67466090/1b32d0f5-b739-4acc-99f3-6d7ede5db8dd)

**Comment by asturur** [comment]
thanks i'll look into this, this is a good bug

**Comment by asturur** [comment]
(by the way if you want to have all the active selections with origin center, you can also just change the vaules in the ActiveSelection ownDefaults without subclassing, unless you have other reasons to subclass.

**Comment by ritali4912** [comment]
> (by the way if you want to have all the active selections with origin center, you can also just change the vaules in the ActiveSelection ownDefaults without subclassing, unless you have other reasons to subclass.

Thanks. I will do that.

**Comment by asturur** [comment]
more context:
- changing both rect and active selection to origin center, or active selection only, change the results.
- is an initialization problem only, using ADD doesn't have the same issue
