### ISSUE TITLE
[Bug]: Image stroke applying wrong 'styles' in SVG

### ISSUE THREAD

**Issue by stevenhurth** [fabricjs/fabric.js#9644]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta18

### In What environments are you experiencing the problem?

Firefox, Chrome, Safari, Opera, Microsoft Edge, Node.js

### Node Version (if applicable)

None

### Link To Reproduction

[Reproduction](https://codesandbox.io/p/devbox/fabric-nextjs-sandbox-forked-5d44vt)

### Steps To Reproduce

1. Add an image to the canvas
2. Add a stroke to the image
3. Add a shadow to the image
4. Export the canvas using toSVG()
5. Open the SVG in a separate browser tab

### Expected Behavior

1. The stroke on the image appears around the image
2. The shadow is applied to the image itself
![canvas-image-stroke-shadow](https://github.com/fabricjs/fabric.js/assets/1882744/59e28d97-45e2-4f58-a15e-fd23df4a4b64)

### Actual Behavior

1. There is no stroke, and the image appears black. This is because the "rect" that gets added on top of the image is using "styles" instead of "style" for applying the CSS (line 416 of FabricImage).
2. The shadow is being applied to both the image and the "rect", which appears to render the shadow extra dark in the SVG output. I assume the "rect" that gets added for the stroke should be skipping the shadow styles (also line 416 of FabricImage).
![svg-image-stroke-shadow](https://github.com/fabricjs/fabric.js/assets/1882744/5de55b6a-8e71-4a26-9a19-85f2aa170e62)

Please see attached images for an example. One is for what the rendering looks like in the canvas, and the other is the SVG output. 

It shows the black rectangle (due to invalid style attribute) that is supposed to be used for the stroke, and a rectangle with shadow in the background, then the image with a brown shadow, which shows extra dark from being applied twice.

I assume line 416 of FabricImage should be: `style="${this.getSvgStyles(true)}"`

**Comment by asturur** [comment]
@stevenhurth if you can't access the templates can you at least make a jsfiddle or paste the code you with the properties of the image and the shadow you are using? Just a description of the problem won't help

**Comment by stevenhurth** [comment]
@asturur A reproduction has been added. Just click the "Render SVG" button on the bottom of the page.

Thanks for looking into this!

**Comment by asturur** [comment]
Seems a legit bug. Should be simple to fix i ll look into it.
Sorry for not coming back before, i don't look at lot a the issues

**Comment by asturur** [comment]
ok this is was a mistake during some migration
https://github.com/fabricjs/fabric.js/pull/9717 i ll have to add a test to be sure is catched if broken again
