### ISSUE TITLE
npm release files cleanup

### ISSUE THREAD

**Issue by ShaMan123** [fabricjs/fabric.js#9648]
> I also previously had this issue. From what I remember, the package from npm was not built with gestures, so in my `package.json` I have
> 
> ```json
>   "scripts": {
>     ...,
>     "postinstall": "cd node_modules/fabric && npm install && npm run build_with_gestures"
>   },
> ```

thats weird, I was expecting fabric to only ship with dist files and not source code

_Originally posted by @Smrtnyk in https://github.com/fabricjs/fabric.js/issues/8849#issuecomment-1923866292_

**Comment by ShaMan123** [comment]
@asturur we do not need the src files in the npm release right?

**Comment by asturur** [comment]
We ship everything in case you want to run post installs script and build differently.
Is that an issue for some case?

**Comment by asturur** [comment]
i think package.json should shield us from that happening.
We added:
```json
  "exports": {
    ".": {
      "import": "./dist/index.min.mjs",
      "require": "./dist/index.min.js",
      "default": "./dist/index.min.js",
      "node": null,
      "types": "./dist/index.d.ts"
    },
    "./es": {
      "import": "./dist/fabric.min.mjs",
      "require": null,
      "default": null,
      "node": null,
      "types": "./dist/index.d.ts"
    },
    "./node": {
      "import": "./dist/index.node.mjs",
      "require": "./dist/index.node.cjs",
      "default": "./dist/index.node.cjs",
      "node": "./dist/index.node.cjs",
      "types": "./dist/index.node.d.ts"
    }
  }
```
and that should tell your ide to not import from sources.

the ES folder that we added recently, sperimental, not suggested yet, should make the src folder not useful anymore.
On what ide and beta this import from src folder was happening? do you remember?

**Comment by Smrtnyk** [comment]
It was before you made these changes I think
I think 14 or 13 beta version IIRC
I am using intellij IDEA and webstorm in a typescript project

Another thing I noticed is that it pulls in everything, and final app bundle contains almost 800kb of fabric, although I am using just few elements and imports, but I guess that is a different issue than this one here
Here is the project https://github.com/Smrtnyk/Firetable/tree/master/packages/floor-creator
 in case you are interested in my fabric usecase

**Comment by asturur** [comment]
The 800kb i noticed too, and that is why i pointed now to the minified build.
Before you were importing the non minified.
If you switch to the lastest you should see the smaller version of the file, the  300kb one.

To pull in what you need only you should use the es folder but is not really safe right now, there are some issues with side effects that we are not ready to take care of, but if you know what you are doing, for example, i m not using svg, i m not using save and restore i just draw paths and text on canvas then you can use the es imports and import only what you need ( mostly )

**Comment by ShaMan123** [comment]
> We ship everything in case you want to run post installs script and build differently. Is that an issue for some case?

Is that common practice? I am not sure
I would say that if you need to run stuff then you probably need to install from github and not from npm.
I view npm as a production bundle holder so I don't think src belongs there

In the package we should fix the src imports by:

<img width="1512" alt="Screenshot 2024-02-06 at 18 40 39" src="https://github.com/fabricjs/fabric.js/assets/34343793/92fb68c9-dc91-4a9e-b779-078796c3e80b">

**Comment by ShaMan123** [comment]
maybe we can publish the beta with `src` and the main release without, also consider download size

**Comment by asturur** [comment]
> > We ship everything in case you want to run post installs script and build differently. Is that an issue for some case?
> 
> Is that common practice? I am not sure I would say that if you need to run stuff then you probably need to install from github and not from npm. I view npm as a production bundle holder so I don't think src belongs there
> 
> In the package we should fix the src imports by:
> 
> <img alt="Screenshot 2024-02-06 at 18 40 39" width="1512" src="https://private-user-images.githubusercontent.com/34343793/302708302-92fb68c9-dc91-4a9e-b779-078796c3e80b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczODA5NjMsIm5iZiI6MTcwNzM4MDY2MywicGF0aCI6Ii8zNDM0Mzc5My8zMDI3MDgzMDItOTJmYjY4YzktZGM5MS00YTllLWI3NzktMDc4Nzk2YzNlODBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDA4MjQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZDExMDQ1NGI4ZWI1NWNiYjY5ZDkwYmI2OWY1MzVkNzY2ZDJmOGYyZmE1YWU1NjNjMGJhNjM2ZjQ3YzQ4ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kmhWTNMimAoz40fc3pJVRMssqNA-RYp9jtD0R4JxKe8">

Common practice or not it doesn't matter, if is useful is useful, but i do not know the statistic of who ships dist only or also sources.
We can probably SRC as soon as the ES folder is workable, but sincerly if there are no real issues i wouldn't remove it.
There could be reasons to have SRC available anyway like transpiling differently or minimizing differently.
