### ISSUE TITLE
[Feature]: Add orientation to circle

### ISSUE THREAD

**Issue by lbordowitz** [fabricjs/fabric.js#9653]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

In some cases, it's more natural to program in a way where the start angle would be greater than the end angle. An additional property to the circle, `clockwiseOrientation`, would aid in making code more readable and straightforward.

### Current State

Currently, the circle will be drawn in a clockwise orientation, from `startAngle` to `endAngle`. If someone wants to use a circle in a counterclockwise orientation, they would need to set `endAngle` to their arc's beginning angle, and `startAngle` to the end of their arc's angle. The code, therefore, would have to separate "application logic" start/end angle and "drawing logic" start/end angle. This is possible, but has already tripped me up more times than I care to admit.

### Additional Context

`startAngle` and `endAngle` are not used in very many places internally. The switching logic would be pretty simple to implement.

**Comment by ShaMan123** [comment]
PR is welcome to introduce clockwise/counterclockwise

**Comment by lbordowitz** [comment]
@asturur I have added a screenshot in my pull request, #9670

**Comment by asturur** [comment]
close as completed
