### ISSUE TITLE
[Feature]: Share Controls between objects

### ISSUE THREAD

**Issue by jiayihu** [fabricjs/fabric.js#9660]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

We should optimise controls memory and CPU performance by maybe sharing the Control instances across objects

### Current State

Today I was analysing the memory usage of our canvas and a significant portion of memory is used by the Controls. Each object has it's own `.controls` and each control is its own istance. While each single control instance memory overhead may not be significant (around 1-4KB depending on the class prototype), that memory is quickly compounded by the number of controls per object and objects.

For instance:

```
KB per control: 3KB
controls per object: 10 
objects: 2000

Total memory: 2 x 10 x 2000 = 60MB
```

Having an instance of Control for each object also means that `setCoords` is more CPU intensive because control coords must be always updated, for all objects. `calcCornerCoords` impact is also not negligible when scaled by the number of controls and objects.

![Screenshot 2024-02-09 at 13 20 57](https://github.com/fabricjs/fabric.js/assets/10067273/b93b8eee-db47-46ef-b442-3ea4de6af5ef)

**Comment by ShaMan123** [comment]
I think I misled you
This is an app choice, and should remain like that.
The app should optimize for that, the control API was designed for sharing.
I don't understand how control sharing will reduce the impact of calcCornerCoords.
I do see how with a proper context passed through the controls we can reduce a lot of calculation.

**Comment by jiayihu** [comment]
Interesting, I did not thought of sharing controls by just sharing the instance. But it makes sense and it explains why the Control API gets the object as method param, instead of instance reference.
