### ISSUE TITLE
[Bug]: Content Security Policy : : unsafe-eval while using Fabric JS 

### ISSUE THREAD

**Issue by themallisetty** [fabricjs/fabric.js#9666]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Firefox, Chrome, Microsoft Edge

### Node Version (if applicable)

None

### Link To Reproduction

x

### Steps To Reproduce

We are using Fabric JS(v5.3.0) for one of the application. We are seeing the Content Security Policy issue while we remove unsafe-eval from the script-src.

Upon doing some check, we see that the same has been reported on https://github.com/fabricjs/fabric.js/issues/1621. But, it seems like all the CSP issues are not resolved. 

We are currently seeing issue from named_accessors.mixin.ts. But, this is removed on the https://github.com/fabricjs/fabric.js/pull/8493 and it is part of the Version 6.0.0-beta1. 

Is there anyway to get this one patched to v5 so that it will be CSP Compliant?
 

### Expected Behavior

Shouldn't see any CSP Issues

### Actual Behavior

![image](https://github.com/fabricjs/fabric.js/assets/24922189/ddbe805b-4588-49b3-82f9-d714c41edbac)

![image](https://github.com/fabricjs/fabric.js/assets/24922189/f400b26e-1044-42c2-80f0-6b3640442acf)

**Comment by ShaMan123** [comment]
This has been removed and is no part of v6
Also I think that if you build v5 you can specify `--exclude=accessors`

**Comment by ShaMan123** [comment]
closing now, add a comment if you disagree

**Comment by themallisetty** [comment]
we are using fabric js in a angular application and installing it via npm. 
may i know how can we exclude it via npm?

**Comment by ShaMan123** [comment]
I didn't think it was part of npm
run a postinstall script
```
cd node_modules/fabric && npm i && npm run build --exclude=accessors
```

**Comment by themallisetty** [comment]
I've used `npm run build_with_gestures` .

we see that https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/fabric is not having the types for eraser_brush.mixin.ts

may i know how can we generate the type definitions for the Fabric JS(v5.3.0) without depending on types/fabric package

**Comment by ShaMan123** [comment]
We introduced TS in v6.
`@types/fabric` is inaccurate to say the least
I have tried to shut it down several times
No types for eraser until it is part of v6 or until I publish it as a standalone

**Comment by ShaMan123** [comment]
So for types you can declare your own interface for now

**Comment by asturur** [comment]
i may be wrong but named accessors were anyway gone long before 5.x They could be still built in as optional but not shipping with the default package.
They were removed in 2.0
CSP was something that was noted long ago and fixed with the first major version available at the time

**Comment by bharat-bigscal** [comment]
This is annoying, as Due to one line, I need to allow unsafe-eval.
We are using Craft 3, and due to heavy things, it's not possible to upgrade it.

**Comment by asturur** [comment]
Not sure what you refer about, unsafe eval for getters is gone since long.
