### ISSUE TITLE
[Bug]: Image disappears when filter is applied on it in iOS devices

### ISSUE THREAD

**Issue by darshika-dev** [fabricjs/fabric.js#9671]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta9

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/dashboard/recent

### Steps To Reproduce

1. Add an image to canvas
2. Apply any Fabricjs filter on the image

### Expected Behavior

The respective filter should get applied to the image

### Actual Behavior

The image disappears

**Comment by ShaMan123** [comment]
#9663 related?

**Comment by ShaMan123** [comment]
This issue will be closed until a clear and concise **LIVE** reproduction is provided 
Also provide visual outputs like a video from iOS and macOS safari and chrome for comparison
