### ISSUE TITLE
[Bug]: Custom Controls after exporting JSON and `loadFromJson()` not working as expected

### ISSUE THREAD

**Issue by Saqib92** [fabricjs/fabric.js#9676]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.2.1

### In What environments are you experiencing the problem?

Firefox, Chrome, Safari, Opera, Microsoft Edge

### Node Version (if applicable)

None

### Link To Reproduction

https://stackblitz.com/edit/angular-ivy-jnxzuw?file=src%2Fapp%2Fapp.component.ts

### Steps To Reproduce

1. Add any object on canavs (in stackblitz click on Draw circle and then draw with mouse on canavs)
2. Set costum controls on object while adding.
3. Export json then Load from json.

### Expected Behavior

it should export customCustols data in JSON and load controls after loadFromJson. 

### Actual Behavior

it is not exporting custom controls and showing default controls when load from json.

**Comment by ShaMan123** [comment]
In v6 this is solved and easy

**Comment by Saqib92** [comment]
> In v6 this is solved and easy

how can i do in v5.x as my app is in production and i need to solve this!!!

**Comment by ShaMan123** [comment]
Try to assign the new control to 
fabric.Objrct.prototype.controls.myControl = myControl
