### ISSUE TITLE
[Bug]: selecting an object for the first time on mobile need two tap

### ISSUE THREAD

**Issue by jaweii** [fabricjs/fabric.js#9682]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta9

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

18.0.0

### Link To Reproduction

/

### Steps To Reproduce

1. const canvas = new fabric.Canvas(document.querySelector('canvas'))
2. const rect = new fabric.Rect({left:0,top:0,width:100,height:100,fill:'red'})
3. canvas.add(rect)

use above codes in chrome ios simulator

### Expected Behavior

active the object for the first time I click it.

### Actual Behavior

NOT active the object for the first time I click it.

**Comment by ShaMan123** [comment]
This issue will be closed until a clear and concise **LIVE** reproduction is provided

**Comment by ShaMan123** [comment]
I had the time so I accept this without a repro and created a PR

**Comment by jaweii** [comment]
@ShaMan123 Thank you very much! When will you release the new version?

**Comment by ShaMan123** [comment]
I am not in charge of release, it will be out on beta20

**Comment by asturur** [comment]
No one is specifically in charge of releases, if you want to flag master for the beta20 do it
