### ISSUE TITLE
[Bug]: canvas.freeDrawingBrush is undefined

### ISSUE THREAD

**Issue by Mikilll94** [fabricjs/fabric.js#9699]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta19

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/p/live/833aabcf-260e-4d87-be95-6f382193e4ad

### Steps To Reproduce

Open this CodeSandbox

https://codesandbox.io/p/live/833aabcf-260e-4d87-be95-6f382193e4ad

As you can see there are TypeScript errors and runtime errors. I don't understand why `canvas.freeDrawingBrush` is `undefined`.

![image](https://github.com/fabricjs/fabric.js/assets/17653648/a4cc620b-825f-421e-9c1d-d288c580a550)
![image](https://github.com/fabricjs/fabric.js/assets/17653648/d7b8046b-a65d-424f-995f-be5fbc8d396f)
![image](https://github.com/fabricjs/fabric.js/assets/17653648/9979b8b9-154d-4fe1-b35e-7863b4bcdcd9)

### Expected Behavior

`canvas.freeDrawingBrush` should not be `undefined`.

### Actual Behavior

`canvas.freeDrawingBrush` is `undefined`.

**Comment by ShaMan123** [comment]
It is written in #8299
