### ISSUE TITLE
[Feature]: Draw smooth circle line

### ISSUE THREAD

**Issue by Mikilll94** [fabricjs/fabric.js#9703]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

Currently the line which is drawn by CircleBrush is very torn.

![circle brush](https://github.com/fabricjs/fabric.js/assets/17653648/11e157a4-6443-48c0-98ca-58e5cbf2b1ba)

Instead I would like to draw a smooth line like that:

![smooth line](https://github.com/fabricjs/fabric.js/assets/17653648/8f802313-122f-40b3-bd55-fd557078fe8f)

### Current State

CircleBrush draws a torn line.

**Comment by asturur** [comment]
Hi @Mikilll94 can you clarify what you mean by torn?
Or can you better explain how would you like this line to be?

The circle brush is just a bunch of circles with random radius and opacity, is more of a funny thing than a full feature, it was made many many years ago

**Comment by Mikilll94** [comment]
Thanks @asturur for explanation. I didn't understand that `CircleBrush` draws circles with random radius and opacity. IMO this makes this brush unusable.

I would prefer to have a brush which draws circles with same radius and opacity.

**Comment by asturur** [comment]
but why? that would make just a line.
Can we try to look at the other point of view, if you take the pencil brush, the one that makes the line smooth as you described, what is missing to the pencil brush to look as you want?

**Comment by Mikilll94** [comment]
> but why? that would make just a line. Can we try to look at the other point of view, if you take the pencil brush, the one that makes the line smooth as you described, what is missing to the pencil brush to look as you want?

I checked pencil brush and that's what I want, thanks :)

**Comment by asturur** [comment]
you have various settings to have the line cap look like a round or a square, on top of a decimate option to decide how smooth should it be
