### ISSUE TITLE
[Feature]: Stretch and Skew Seats

### ISSUE THREAD

**Issue by blpraveen** [fabricjs/fabric.js#9704]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

How can I Stretch and Skew this https://codepen.io/trirandom/pen/poZdagp

### Current State

This Feature not available

**Comment by ShaMan123** [comment]
Please you discussions for Q&A
Hit the shift key and use one of the middle controls
