### ISSUE TITLE
[Bug]: Using a string-type for "strokeWidth" property of an object shifts the object's top/left attributes under certain conditions

### ISSUE THREAD

**Issue by athoag-sony** [fabricjs/fabric.js#9731]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Firefox, Chrome, Safari, Microsoft Edge

### Node Version (if applicable)

None

### Link To Reproduction

I tried but your vanilla template was read only even once I logged in

### Steps To Reproduce

Here is a minimal example in a single html file:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fabric.js Animation</title>
    <script src="https://unpkg.com/fabric@5.3.0/dist/fabric.min.js"></script>
    <style>
        canvas {
            border: 1px solid black;
        }
    </style>
</head>
<body>
    <canvas id="canvas" width="400" height="400"></canvas>

    <script>
        const canvas = new fabric.Canvas('canvas');

        // Create a rect with integer strokeWidth 
        const rect1 = new fabric.Rect({
            left: 10,
            top: 10,
            width: 50,
            height: 50,
            fill: 'red',
            strokeWidth: 2
        });
        canvas.add(rect1);

        
        const rect2 = new fabric.Rect({
            left: 10,
            top: 70,
            width: 50,
            height: 50,
            fill: 'blue',
            strokeWidth: "2"
        });
        canvas.add(rect2);

        canvas.renderAll();
    </script>
</body>
</html>
```
I have only changed two things between `rect1` and `rect2`:
- `rect2` has `top:70` (so that I can visually distinguish the two rects
- `rect2` has `strokeWidth: "2"` instead of `strokeWidth: 2`

If I run open this with a simple http server, e.g., 
```
python -m http.server
```
And open my browser to `localhost:8000` then I see the following:

![Screenshot 2024-03-13 at 4 08 28 PM](https://github.com/fabricjs/fabric.js/assets/156851457/5f8a9b96-cd85-4f5f-9793-5262b0d2d895)

### Expected Behavior

I would expect to see the red rect directly under the blue rect like this: 
![Screenshot 2024-03-13 at 4 11 25 PM](https://github.com/fabricjs/fabric.js/assets/156851457/7ba9dfed-27e1-43f3-b43b-edd62c209a40)

Or at the least I would expect an error to be thrown indicating that the `strokeWidth` attribute has the incorrect datatype. 

### Actual Behavior

`rect2` is shifted and it happens under these conditions: 
- `strokeWidth` has to be a string (in vanilla js)
- `width` and/or `height` have to be integer-like. I say integer-like because they can be `width: 1000` or `width:1000.0`. In both cases the bug occurs. 

This happens not just for rects but at least for polygons as well. There the issue is a little more insidious because you do not explicitly pass left and width attributes, but instead a `points` array, whose extremal points are used to calculate the width/height. 

Note that the shift happens to the `left` attribute if `width` attribute is the integer and to the `top` attribute if the `height` attribute is an integer, but `left` doesn't influence `height` nor vice-versa. 

When `strokeWidth: 2`, the shift to `left` appears to be `+4.5*width` (`+4.5*height` for top)

### Error Message & Stack Trace

```bash
No errors logged to the developer console.
```

**Comment by athoag-sony** [comment]
This is related to issue: https://github.com/fabricjs/fabric.js/issues/2187 but it was not resolved by the fix that resolved that issue.

**Comment by asturur** [comment]
@athoag-sony it is clearly documented which properties are numbers. If you pass strings you break the code.
that's it there is nothing we can do about that nor we want to add code to safeguard it or type check it at runtime.
