### ISSUE TITLE
Text not positioned correctly after loading SVG

### ISSUE THREAD

**Issue by bajalovic** [fabricjs/fabric.js#974]
I have an SVG image which is displayed correctly in browser ![image_1](https://f.cloud.github.com/assets/1307779/1521585/8edf0674-4b96-11e3-9a56-1b1c26bdab6d.jpg). 

However, when I use loadSVGFromURL position of the text is not correct
![image_2](https://f.cloud.github.com/assets/1307779/1521586/8ee110c2-4b96-11e3-96e0-d9fc075f5867.jpg)
![image_3](https://f.cloud.github.com/assets/1307779/1521587/8ee3bfac-4b96-11e3-87a0-27475e83cdb2.jpg)

Code that produces this first image is:

```
var group = []
fabric.loadSVGFromURL(_src, function(objects, options) {
  var loadedObjects = new fabric.Group(group);
```

Code that produces second image is:

```
fabric.loadSVGFromURL(_src, function(objects, options) {
  var loadedObjects = new fabric.util.groupSVGElements(objects, options);
```

Here is the SVG image I used: http://pastie.org/8474528

**Comment by Sashkan** [comment]
Sorry to re-open this one, but I have a question: last entry isabout originX not being set, is that the only fix ?

I'm loading a file including both images and text, and even though I set originX and originY on both of them, once my SVG is done loading, my images are correctly positionned, but my texts are completely out of place.

This is how I set my objects, once SVG is loaded:

```js
              // objects and options are the results of the loadSVGfromURL method
              // helper is a rect I use as a clipPath
              const helper = objects.find(o => o.id === 'printing-zone')
              // this.props.size is the size of the canvas
              const positionningRatio = this.props.size / options.width
              object.set({
                centeredScaling: true,
                lockScalingFlip: true,
                originX: 'left',
                originY: 'top',
                scaleX: design.scaleX * positionningRatio,
                scaleY: design.scaleY * positionningRatio,
                top: design.top * positionningRatio,
                left: design.left * positionningRatio,
                clipPath: helper,
              })

```

**Comment by asturur** [comment]
text with tspan is generally not reloaded correctly.
