### ISSUE TITLE
[Bug]: Textbox of Fabric.js does not wrap a long word

### ISSUE THREAD

**Issue by niketaOptimumnbrew** [fabricjs/fabric.js#9748]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Firefox, Chrome, Safari

### Node Version (if applicable)

14.20.0

### Link To Reproduction

https://jsfiddle.net/Niketa_patel/ckxuvjah/8/

### Steps To Reproduce

Please follow the steps below:
1. Use the provided code snippet:
```
var canvas = new fabric.Canvas("c");
var str = 'ADD HEADING TEXT';
var textbox = new fabric.Textbox(str, {
    width: 200,
    breakWords: true,
    fontSize:75
});
canvas.add(textbox);
```
2. Run the project.
3. Type continuously in the textbox, and you will notice that the text does not wrap into a new line when it exceeds the boundary of textbox.

### Expected Behavior

When the text exceeds the boundary, it should wrap to the next line instead of extending beyond the boundary.
Please check below link generate issue:
[https://jsfiddle.net/Niketa_patel/ckxuvjah/8/]

### Actual Behavior

When the text exceeds the textbox boundary, it'll not wrap in next line 
Please check attached video for better understanding.
[fabric-issue.webm](https://github.com/fabricjs/fabric.js/assets/126561906/0a938afb-7e78-4961-bba9-14d598d353f0)

**Comment by asturur** [comment]
@niketaOptimumnbrew breakwords is not a property of textbox. this is the same as the discussion you opened before. FabricJS does not break words unless you use splitByGrapheme.

**Comment by niketaOptimumnbrew** [comment]
> @niketaOptimumnbrew breakwords is not a property of textbox. this is the same as the discussion you opened before. FabricJS does not break words unless you use splitByGrapheme.

Thank you for correcting me, but can you please tell me how to wrap the text on a new line when it exceeds the boundary of a textbox?
My goal is to wrap text into new line when it's exceeds the textbox boundary
Let me know if you need further assistance!

**Comment by asturur** [comment]
There isn't a way apart 'spitByGrapheme: true', what you are asking is someone writing or adapting the break word code for you, maybe someone will do, maybe not.

**Comment by niketaOptimumnbrew** [comment]
> There isn't a way apart 'spitByGrapheme: true', what you are asking is someone writing or adapting the break word code for you, maybe someone will do, maybe not.

Adding 'splitByGrapheme: true' made my code run smoothly. Thank you for your guidance on the text wrapping issue in Fabric.js, it was very helpful!

**Comment by asturur** [comment]
Yes but be careful that splitByGrapheme will never wrap english text correctly because will count spaces as normal words.
splitByGrapheme will split the word even if the word could have fit in a line alone. It won't try to preserve latin/english way of wrapping text.

**Comment by niketaOptimumnbrew** [comment]
> Yes but be careful that splitByGrapheme will never wrap english text correctly because will count spaces as normal words. splitByGrapheme will split the word even if the word could have fit in a line alone. It won't try to preserve latin/english way of wrapping text.

@asturur Thank you for giving me this information related to splitByGrapheme() :)

Can you please tell me if wrapping the word in next line through splitByGrapheme() is a correct way in fabric.js?

Also, I have to support other languages like Hindi, Gujarati, etc. Will it work with those?

**Comment by asturur** [comment]
I m Italian and i speak English as extra language.
SplitByGrapheme was built as a naive way to support languages that do not use spaces ( like for example Chinese and Japanese ).
It has a lot of drawbacks for example with justify functionality.

I do not know about Hindi and Gujarati but i can only imagine that if the graphemeSplit function is not appropriate for those languages it will split bad for sure.

if you are on version 6 beta you have to customize this method with something better:

```ts
  /**
   * Override this method to customize grapheme splitting
   * @todo the util `graphemeSplit` needs to be injectable in some way.
   * is more comfortable to inject the correct util rather than having to override text
   * in the middle of the prototype chain
   * @param {string} value
   * @returns {string[]} array of graphemes
   */
  graphemeSplit(value: string): string[] {
    return graphemeSplit(value);
  }
```

Where something better means either using a library like 
https://www.npmjs.com/package/graphemer

or using the browser embedded grapheme splitter that is available in modern browsers

**Comment by niketaOptimumnbrew** [comment]
> I m Italian and i speak English as extra language, my understanding of languages outside europe is rudimental. SplitByGrapheme was built as a naive way to support languages that do not use spaces ( like for example Chinese and Japanese ). It has a lot of drawbacks for example with justify functionality.
> 
> I do not know about Hindi and Gujarati but i can only imagine that if the graphemeSplit function is not appropriate for those languages it will split bad for sure.
> 
> if you are on version 6 beta you have to customize this method with something better:
> 
> ```ts
>   /**
>    * Override this method to customize grapheme splitting
>    * @todo the util `graphemeSplit` needs to be injectable in some way.
>    * is more comfortable to inject the correct util rather than having to override text
>    * in the middle of the prototype chain
>    * @param {string} value
>    * @returns {string[]} array of graphemes
>    */
>   graphemeSplit(value: string): string[] {
>     return graphemeSplit(value);
>   }
> ```
> 
> Where something better means either using a library like https://www.npmjs.com/package/graphemer
> 
> or using the browser embedded grapheme splitter that is available in modern browsers

@asturur Thank you for spending your valuable time on it.
