### ISSUE TITLE
[Feature]: Possibility to define custom attributes per control

### ISSUE THREAD

**Issue by elerocks** [fabricjs/fabric.js#9752]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

I'd like to add custom style on per-control basis.

### Current State

Example:

Suppose there is polygon with custom control at every point, same as the official demo:

http://fabricjs.com/custom-controls-polygon

I add another set of points that will act as "add new point to the polygon just between these two points". That's fine, I can just do:

```
poly.controls = poly.points.reduce((acc, point, index) => {
    acc[`p${index}`] = new fabric.Control({
        positionHandler: this.polygonPositionHandler.bind(this, index),
        actionHandler: this.anchorWrapper(index > 0 ? index - 1 : lastControl, this.actionHandler.bind(this)),
        actionName: "modifyPolygon",
        cursorStyle: "grab"
    }, index);
    acc[`newPoint${index}`] = new fabric.Control({
        positionHandler: this.newPointPolygonPositionHandler.bind(this, index), // adds new point between existing two
        mouseUpHandler: this.newPointAnchorWrapper(index), // listener that will add new point to the polygon
        actionName: "newPointPolygon",
        cursorStyle: "copy"
    })
    return acc;
}, {});
```
But I'd like to define custom design of the circles just for the new points, e.g. do something like:

```
      acc[`newPoint${index}`] = new fabric.Control({
          positionHandler: this.newPointPolygonPositionHandler.bind(this, index),
          mouseUpHandler: this.newPointAnchorWrapper(index),
          actionName: "newPointPolygon",
          cursorStyle: "copy",
          cornerColor: "rgba(255,0,0,0.8)             // <<<<----- this is new
      })
```

I've searched the API, but couldn't find any workaround.

**Comment by asturur** [comment]
When doing the first version of the control api, that is the one that is still available today, there were 2 way to define controls properties. On the object and with styleOverrides.

The reasoning was that we would see what was the usage and we would change depending on feedback.
At the moment duplicating the setting on the object and on the control and then deciding which one has the priority didn't look good ( it doesn't to me also today ).

You can create a custom render function, let's say you want to render a circle, pass a render option to your control:

```ts
      acc[`newPoint${index}`] = new fabric.Control({
          positionHandler: this.newPointPolygonPositionHandler.bind(this, index),
          mouseUpHandler: this.newPointAnchorWrapper(index),
          actionName: "newPointPolygon",
          cursorStyle: "copy",
          render: function(
                          ctx: CanvasRenderingContext2D,
                          left: number,
                          top: number,
                          styleOverride: ControlRenderingStyleOverride | undefined,
                          fabricObject,
                       )  {
        renderCircleControl.call(
          this,
          ctx,
          left,
          top,
          styleOverride: {
             cornerColor: 'specialColorYouWant'
           }
          fabricObject,
        );
      }
  })
```

this is a way to do it.
You can also define this control as a subclass of the standard control and keep it as a preconfigured class

**Comment by elerocks** [comment]
thank you @asturur ! That's exactly what I needed.
Additional question, is it possible to catch right click event on `fabric.Control`? I've only managed to catch left click (using the `mouseUpHandler`)

**Comment by asturur** [comment]
ah. If it doesn't fire no, but i would agree it would sort of normal to have it?
It probably doesn't work because if the click is not left with let go the whole function and we stop checking.

Maybe you can use _findTargetCorner on the activeObject on a generic mouseUp/mouseDown on the canvas and call the control mouseUp handler manually?

This could be something we could support out of the box, you should open a separate feature request for it

**Comment by elerocks** [comment]
Thank you, separate feature request filed. I think this issue can be closed.
