### ISSUE TITLE
[Bug]: Textbox.enterEditing() cause selectable not applying.

### ISSUE THREAD

**Issue by Tennyleaz** [fabricjs/fabric.js#9766]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Firefox, Microsoft Edge

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/p/devbox/fabric-vanillajs-sandbox-forked-dz65w4?workspaceId=0933a778-123f-4f93-9849-b2a2e555d506

### Steps To Reproduce

1. Set `fabric.Textbox.prototype.selectable` to a value, for example `true` (or `false`)
2. Create some textboxes
3. Pick a textbox and call `enterEditing()`
4. Invert `fabric.Textbox.prototype.selectable`'s value, for example `false` (or `true`)
5. The textbox we called `enterEditing()` does not respect `fabric.Textbox.prototype.selectable`'s value, can still be selected (or cannot be selected). 
6. Other textboxes without calling `enterEditing()` are not affected.

### Expected Behavior

All textboxes should respect `fabric.Textbox.prototype.selectable`, even after calling `enterEditing()`, can be selected if selectable is `true` (or cannot be selected if `false`).

### Actual Behavior

The textbox stuck in the state of `fabric.Textbox.prototype.selectable` when calling `enterEditing()`.

**Comment by asturur** [comment]
What you can do is use the onSelect callback and make it return false when selectable is false.

```fabric.Object.prototype.onSelect = function() {  return this.selectable }```

this could reinforce the behavior how you want it

**Comment by Tennyleaz** [comment]
Thank you.
Could I using like this:
```javascript
fabric.Textbox.prototype.onSelect = function() {  
    return myTextboxSelectCondition;
}
```
Or should I use `fabric.Object.prototype.onSelect` instead?

**Comment by asturur** [comment]
it depends, you can also do it on a per object basis you don't need to do it to the prototype.
Does your selection change on a per class basis? if not go on object.
