### ISSUE TITLE
Object visibility properties are not serialized with canvas.toJSON method

### ISSUE THREAD

**Issue by jmlacroix** [fabricjs/fabric.js#978]
I'm using the new `setControlsVisibility` to remove the rotation point of an object. When exporting to JSON and loading a new canvas from the serialized JSON string, the rotation point is back.

http://jsfiddle.net/7ScM7/1/

It looks like there's no controls visibility information at all in the serialized data:

```
{
  "objects":[
    {
      "type":"rect",
      "originX":"left",
      "originY":"top",
      "left":10,
      "top":10,
      "width":50,
      "height":50,
      "fill":"rgb(0,0,0)",
      "stroke":null,
      "strokeWidth":1,
      "strokeDashArray":null,
      "strokeLineCap":"butt",
      "strokeLineJoin":"miter",
      "strokeMiterLimit":10,
      "scaleX":1,
      "scaleY":1,
      "angle":0,
      "flipX":false,
      "flipY":false,
      "opacity":1,
      "shadow":null,
      "visible":true,
      "clipTo":null,
      "backgroundColor":"",
      "rx":0,
      "ry":0,
      "x":0,
      "y":0
    }
  ],
  "background":""
}
```

**Comment by mohamad68** [comment]
hi
`JSON.stringify(this.canvas.toJSON(['_controlsVisibility']))
`not working.

**Comment by asturur** [comment]
JSON export  is tailored for primitive values.
_controlsVisibility is an object.
What are you exactly trying to do?

**Comment by tkachukcha** [comment]
I have the same problem. I'm implementing save function to localstorage via Object.toJSON, and this particular options is not serialized. Is there any solution for this?
