### ISSUE TITLE
[Bug]: There is a bug where drawing with the brush and erasing with the eraser leaves an afterimage.

### ISSUE THREAD

**Issue by skulter** [fabricjs/fabric.js#9781]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [ ] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://codepen.io/hoqcaeiq-the-animator/pen/MWROpwx

### Steps To Reproduce

1. draw a picture with the brush.
2. Use the eraser to erase the drawing with very slow movements.

### Expected Behavior

Normal behavior is that even if the eraser moves very slowly, the area it passes over should be cleanly erased.

### Actual Behavior

As you can see in the video, there is an afterimage and you can see the afterimage even if you change the color.

This bug is in 5.3, but the same bug occurs in 4.4.
I would like to know how to fix it.

In the official example, you can see that the same bug occurs if you set the width of the eraser brush to high and then move it very slowly to erase.

Thanks for listening

![MicrosoftTeams-image](https://github.com/fabricjs/fabric.js/assets/18344213/57b43202-2f8b-4e8e-b896-60c9ce4fedc7)
![eraser_bug](https://github.com/fabricjs/fabric.js/assets/18344213/19efc7d2-ef4d-449a-ad07-d3f62fc660f0)
![MicrosoftTeams-image (1)](https://github.com/fabricjs/fabric.js/assets/18344213/203a8507-26c4-4bcc-8a06-2107b47ef1ff)

**Comment by ShaMan123** [comment]
I have extracted the eraser to a standalone repo.
Please add your findings to the tracking bug https://github.com/ShaMan123/erase2d/issues/13
