### ISSUE TITLE
[Bug]: v6 Removing the last object out of a clipgroup does not update the canvas on render

### ISSUE THREAD

**Issue by niels-van-den-broeck** [fabricjs/fabric.js#9798]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta20

### In What environments are you experiencing the problem?

Firefox, Chrome, Safari, Opera, Microsoft Edge

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/p/devbox/fabric-vanillajs-sandbox-forked-qmtt84?file=%2Fpackage.json%3A21%2C16&workspaceId=afaa726c-2c79-4d5e-9768-e8a126470110

### Steps To Reproduce

1. click top left of the rendered image
2. click bottom left of the rendered image
3. click both images again

### Expected Behavior

- it shows the areas on first click
- it hides the areas on second click

### Actual Behavior

the last visible area is persistent until a new one is present.

**Comment by niels-van-den-broeck** [comment]
Some more side info, beta v9 seemed to not have this issue

**Comment by asturur** [comment]
the example seem legit.

**Comment by ShaMan123** [comment]
https://codesandbox.io/p/devbox/fabric-vanillajs-sandbox-forked-qmtt84?file=%2Fpackage.json%3A21%2C16

This is a known problem.
A clip path is not aware of its parent so it doesn't flag it as dirty as opposed to a regular descendant.

```diff
    if (existingClipObject) {
      clipGroup.remove(existingClipObject);
    } else {
      clipGroup.add(
        new Rect({
          id: rect.id,
          left: rect.left,
          top: rect.top,
          width: rect.width,
          height: rect.height,
        }),
      );
    }

+    revealImage.set('dirty',true);
+    clipGroup.set('dirty',true);
    canvas.requestRenderAll();
```

**Comment by asturur** [comment]
oh that is not even an issue then, i misunderstood the code.
Yes if you change the clipPath you have to set the object as dirty if you are using caching.

**Comment by asturur** [comment]
I think we can close this

**Comment by niels-van-den-broeck** [comment]
If this is known, fine by me. Thank you for the feedback
