### ISSUE TITLE
[Bug]: Flip object inside group whose interactive is true got wrong behavior.

### ISSUE THREAD

**Issue by ritali4912** [fabricjs/fabric.js#9801]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta20

### In What environments are you experiencing the problem?

Microsoft Edge

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/ritali4912/x6nd5e7k/11/

### Steps To Reproduce

There is a group whose subTargetCheck: true, interactive: true.
Then I flip one of its children, but got strange behavior. It seems the control after flip are wrong.
Refer to the below gif.

![FlipObjectInsideGroupWithWrong](https://github.com/fabricjs/fabric.js/assets/67466090/57ebf4e5-e9e4-4f3c-be02-122ae1e9bab5)

### Expected Behavior

The child object inside group can scale/flip as normal.

### Actual Behavior

The child object seems got wrong controls after flip.

**Comment by asturur** [comment]
i ll look into this tomorrow morning

**Comment by asturur** [comment]
Ok i looked at this, i have some code changes that improve the situation but do not fix it entirely.
I ll look more

**Comment by asturur** [comment]
I made a render control function to help me debugging the issue, it seems clear to me that the controls get wrongly placed

<img width="167" alt="image" src="https://github.com/fabricjs/fabric.js/assets/1194048/119b0b67-c9db-4e24-8bb3-5b1361328117">

But i m not entirely sure yet if is the cause of the error or just a side effect

**Comment by asturur** [comment]
Now the same issue can be hit in different ways.
In the case of the blue one the object is not flipped but the group is flipped Y and rotated of 90. that equal as a flipX applied on the object

<img width="294" alt="image" src="https://github.com/fabricjs/fabric.js/assets/1194048/30660dc2-c613-4fe3-ad0e-46d5afef2112">

**Comment by asturur** [comment]
This could be a reasonable change that fix the issue and is very scoped to this case.
It does not fix the arrows for now.

```diff
       positionMatrix = multiplyTransformMatrices(tMatrix, rMatrix),
       startMatrix = multiplyTransformMatrices(vpt, positionMatrix),
+      transformOptions = this.group
+        ? qrDecompose(this.calcTransformMatrix())
+        : undefined,
       finalMatrix = multiplyTransformMatrices(startMatrix, [
         1 / vpt[0],
         0,
@@ -245,14 +248,17 @@ export class InteractiveFabricObject<
         0,
         0,
       ]),
-      transformOptions = this.group
-        ? qrDecompose(this.calcTransformMatrix())
-        : undefined,
-      dim = this._calculateCurrentDimensions(transformOptions),
-      coords: Record<string, TOCoord> = {};
+      { x, y } = this._calculateCurrentDimensions(transformOptions),
+      coords: Record<string, TOCoord> = {},
+      correctedDims = new Point(Math.abs(x), Math.abs(y));

     this.forEachControl((control, key) => {
-      const position = control.positionHandler(dim, finalMatrix, this, control);
+      const position = control.positionHandler(
+        correctedDims,
+        finalMatrix,
+        this,
+        control
+      );
       // coords[key] are sometimes used as points. Those are points to which we add
       // the property corner and touchCorner from `_calcCornerCoords`.
       // don't remove this assign for an object spread.
```

**Comment by asturur** [comment]
Except this breaks with padding

**Comment by asturur** [comment]
Ok we have a PR for this

**Comment by asturur** [comment]
Assuming you are not using strokeUniform, rect.getCoords() should give you all you need, taking in account for group transform

```
[tl, tr, br, bl] = this.getCoords();
```

If you are not using a rect or you want know a specific point of a shape where it is in the scene coordinates, you have to calculate where that point is located respect to the center and get that point trasnformed.

For example, the center of a shape  inside any nested group, in scene coordinates is always at:

```
(new Point(0, 0)).transform(shape.calcTransformMatrix())
```

a point that is 5 unit left and 4 unit lower than the center ( usually pixels ) will be:

```
(new Point(-5, 4)).transform(shape.calcTransformMatrix())
```

calcTransforMatrix() take in account your shape scale and rotation, and the group properties.

If you have already accounted for the shape transformation and you want to know only the group transfromation you can use shape.parent.calcTransformMatrix() to get the transform done.

**Comment by ritali4912** [comment]
Thanks so much for the detail answer. :):)
