### ISSUE TITLE
strokeWidth with decimals

### ISSUE THREAD

**Issue by tgoeminne** [fabricjs/fabric.js#9803]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

seems like I can only use strokeWidth with integer values 1,2,3,4,5,6.... I want to use decimals on the strokewidth to have more control over it.

### Current State

no decimal allowed?

### Additional Context

...

**Comment by zhe-he** [comment]
You might need to set scaling to not affect the border size, rather than considering making the border size support decimals.

```typescript
// v6
import { FabricObject } from "fabric"
FabricObject.ownDefaults.strokeUniform = true;
```
```typescript
// v5
fabric.Object.prototype.strokeUniform = true;
```

**Comment by asturur** [comment]
Decimals are definetely allowed.
What are you seeing?
strokeUniform comes with its own can of worm and is an entirely different feature

**Comment by tgoeminne** [comment]
apparently e.target.value is of type string, I need to use the following

parseFloat(e.target.value)
