### ISSUE TITLE
[Bug]: During scaling Group from a very small size, the child act strangely radiant.

### ISSUE THREAD

**Issue by ritali4912** [fabricjs/fabric.js#9822]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-beta20

### In What environments are you experiencing the problem?

Microsoft Edge

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/ritali4912/51afjotp/39/

### Steps To Reproduce

I have a Group with two rectanges, and I set the group lockScalingFlip to true.
1. Scaling X the group to very narrow.
2. Then scaling X the group back to large.

### Expected Behavior

The children's bounds correct during scaling the group back.

### Actual Behavior

The children like radiant. But after finish scaling, the children change to correct.
![scaling-group-1](https://github.com/fabricjs/fabric.js/assets/67466090/0b2099dc-6d31-4b07-8cc0-b84d23806c3b)

**Comment by zhe-he** [comment]
The issue is related to caching; disabling the cache should resolve it.
```fabric.FabricObject.ownDefaults.objectCaching = false;```


https://github.com/fabricjs/fabric.js/assets/11306583/162adcb9-fb2b-4d57-9eab-58c3580a8437

**Comment by ritali4912** [comment]
Does set `objectCaching = false` impact on the performance? I mean slow down the performance.

**Comment by asturur** [comment]
this is the 'noScaleCache' option.
Is explained here: http://fabricjs.com/fabric-object-caching
You can set that to false and caching won't be used when you are scaling an object.

The behaviour you underline is an edge case and you shouldn't worry about it too much in my opinion.
You can set 'noScaleCache' to the opposite of what is now by modifying the FabricObject.ownDefaults objects

**Comment by ritali4912** [comment]
Thanks for the clearly answer. That is very helpful.
