### ISSUE TITLE
Text rendered on multiline using same path merges all the lines on one path.

### ISSUE THREAD

**Issue by Shashank-Bhatt1** [fabricjs/fabric.js#9826]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

Hi, I am using path for my text object to apply curvature for it and it works very nicely. However i need to use same path for when text is spanned across multiline.

when i do that, path is no longer working correctly and all of the lines following the path are combined as one line and overlapped.

Here is the snapshot how it comes.
![Screenshot 2024-04-26 184242](https://github.com/fabricjs/fabric.js/assets/24728257/09281465-2c05-46d2-9aa5-edaf31402a90)

It follows the correct path but the only problem is that it does not do that on individual line. If i remove path then it looks like this
![Screenshot 2024-04-26 184311](https://github.com/fabricjs/fabric.js/assets/24728257/74db1adf-2afa-42c6-b719-6aa78e88998b)

I have checked fewer native code (_measureLine function) but i am not able to figure out how the things work here so any help would be much appreciated. 

### Current State

One partial solution is to add individual text object from each line and then apply path for all of them 
Something like
```
const textLines = text.split('\n');
const textObjects = textLines.map(textLine => new fabric.Text(textLine))

textObjects.forEach((textObject,index) => {
    textObject.set('top', index * textObject.__lineHeights[0])
})


const textLinesGroup = new fabric.Group(textObjects);
textLinesGroup.name = 'label';
canvas.add(textLinesGroup);
```
but this also means that one has to apply all the other props to individual objects as well which i can't now as i already have taken text object everywhere in my project.

**Comment by asturur** [comment]
What you want to do here is complex. You should concatenate your path with a vertical offset and replicate the path on multi line. Text on a path and text wrapping do not work currently.

**Comment by Shashank-Bhatt1** [comment]
@asturur Noted. Thanks for the update.
