### ISSUE TITLE
[Feature]: Fabricjs V6 no longer have  fabric.textureSize = fabric.maxTextureSize

### ISSUE THREAD

**Issue by mtrabelsi** [fabricjs/fabric.js#9827]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

Hi, I have checked the docs for V6 not yet published, I searched in all issues before creating this.

in V5 I used this to bypass the limitation on filters:

//@ts-ignore
if (fabric.isWebglSupported()) {
	//@ts-ignore
	fabric.textureSize = fabric.maxTextureSize;
}

but in V6 even in the migration guide, there is no mention about deprecation or breaking changes for it, though trying importing it, it does not exists yet.

the documentation online still for V5.

now looking at the code, the only place I could find is the WebGLProbe class (https://github.com/fabricjs/fabric.js/blob/master/src/filters/GLProbes/WebGLProbe.ts)

which is not exported in V6.

is this forgotten or dismissed "feature" ?

### Current State

the V6 do not have any documented or non documented way to increase the textureSize!

**Comment by ShaMan123** [comment]
fabric.config.xxx

**Comment by mtrabelsi** [comment]
thanks! that is better now, but how about the 
isWebglSupported() and maxTextureSize ? any equivalent this

**Comment by mtrabelsi** [comment]
for now I created my own isWebglSupported() and set maxtexure size manually.....

**Comment by ShaMan123** [comment]
The config object is writable.
You can change values or set via a method IIRC.
isWebglSupported has been moved to webglProbe which is not exported IIRC
