### ISSUE TITLE
How should I individually set the left and right padding for a control?

### ISSUE THREAD

**Issue by cfmj** [fabricjs/fabric.js#9828]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

How should I individually set the left and right padding for a control?

### Current State

i cant find the sulotion in Doc

### Additional Context

How should I individually set the left and right padding for a control?

**Comment by ShaMan123** [comment]
Override Control#positionHandler
It accepts a dim param which includes object.padding so be sure to remove it or set it to 0 beforehand. Then you are free to pass the modified dim value to super.

**Comment by cfmj** [comment]
![`4)5P`8M@L($YW8)88VHSJ4](https://github.com/fabricjs/fabric.js/assets/33464433/fe20f1d4-c3a5-4c0d-85f8-ad969a455e95)
The blue arrow and the yellow arrow use different values.

**Comment by cfmj** [comment]
> Can you explain what is the individual left and right padding? Padding is a precise feature of the controlbox itself, then there is a control offse if you want that displaces the control from the standard position. What are you looking for?



> ![4)5P8M@L($YW8)88VHSJ4](https://private-user-images.githubusercontent.com/33464433/326273278-fe20f1d4-c3a5-4c0d-85f8-ad969a455e95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjI1NTcsIm5iZiI6MTcxNDMyMjI1NywicGF0aCI6Ii8zMzQ2NDQzMy8zMjYyNzMyNzgtZmUyMGYxZDQtYzNhNS00YzBkLTg1ZjgtYWQ5NjlhNDU1ZTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE2MzczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlMTcwNTBmMWQ5YmU4OGY1OTVmMjI0ZDI3MTE4ZmI0MjRlN2FkMzk4NjljZmE1MTQzNTVlNzlhYTcxNGFiZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y7-yCF3R9mlOANDb3RiVHf7okNZTyiJQgRxJX0fXvXk) The blue arrow and the yellow arrow use different values.

**Comment by asturur** [comment]
Ok this is not a supported feature is something you have to code yourself with overrides after getting a good understanding of how the control drawing works
But just to be clear:
padding is for the control box and not for individual controls, and the example is for left and top not left and right.
Your issue was a 1 line description, a copy of the title, that is now how we ask to open issues

**Comment by cfmj** [comment]
got it,thanks
