### ISSUE TITLE
[Feature]: i want to create a drawing tool which work like the attached video

### ISSUE THREAD

**Issue by mayank23jne** [fabricjs/fabric.js#9858]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

https://github.com/fabricjs/fabric.js/assets/11390130/04aa9ee6-c49b-479c-8e4c-08896155f9fb

### Current State

nothing have done yet.

**Comment by ShaMan123** [comment]
duplicate #6319 
look at #8430

**Comment by ShaMan123** [comment]
to change the poly vertex we have poly controls: `createPolyControls`
