### ISSUE TITLE
[Bug]: Main website SSL issue

### ISSUE THREAD

**Issue by seifsg** [fabricjs/fabric.js#9870]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-rc1

### Node Version (if applicable)

None

### Link To Reproduction

https://fabricjs.com/

### Steps To Reproduce

1. Open https://fabricjs.com/ on a web browser.
![image](https://github.com/fabricjs/fabric.js/assets/6075316/14e020f7-cc51-4640-acc0-c106f6d3a8d5)

### Expected Behavior

To show website SSL secure

### Actual Behavior

Showing that SSL issue. 
![image](https://github.com/fabricjs/fabric.js/assets/6075316/a8d7647c-9924-4df7-9d53-ee81244b542c)

### Error Message & Stack Trace

```bash
Certificate is not valid.
```

**Comment by asturur** [comment]
that old stack is http only

**Comment by seifsg** [comment]
If that is old stack. Can you please share new stack live url?
Or no plans to fix that url?

**Comment by seifsg** [comment]
> that old stack is http only, is strange that it load on https.

If that is old stack. Can you please share new stack live url?
Or no plans to fix that url? @asturur

**Comment by asturur** [comment]
https://fabricjs.github.io will move to fabricjs.com as soon as old pages are moved over, and then we  will start to add the actual new documentation
