### ISSUE TITLE
[Bug]: can not use fabricjs with web-worker 

### ISSUE THREAD

**Issue by Lpbzzz** [fabricjs/fabric.js#9873]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [x] I have created an accurate and minimal reproduction

### Version

6.0.0-beta16

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

[github link](https://github.com/Lpbzzz/my-app)

### Steps To Reproduce

1. When I send the data to worker.js 
2. Problems with new Textbox：can not use window in worker.js
3.When I build some new Rect new Group data, i can not use ``` postMessage ``` send fabric Object to main thread. Error:
```
Uncaught DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': (eventData, control, fabricObject) => {
  return isAltAction(eventData, fabricObject) ? skewCursorStyleHandler(...<omitted>...
} could not be cloned
```

### Expected Behavior

i create so many fabric Object，and i hope fabric no-blocking page.
extremely grateful

### Actual Behavior

Cannot compute graphs in worker.js

**Comment by Lpbzzz** [comment]
Or, how should I properly use fabric with webworker?

**Comment by asturur** [comment]
We worker support is not ready yet, is not even a priority for now.
We will first support offscreen canvas ( in the same thread ) and then hopefully a way to run it in a webworker. Fabricjs uses the window object often, so is not straight forward to do that. Events from inputs need to run in the main window and some sort of data needs to go in the web worker and run there. Also there is the question how do you move object programmaticaly  from the main window to the worker, you will have to setup a series of postMessage calls with the api, everything becomes async, is a bit of a large concept work

**Comment by asturur** [comment]
There was a demo around in some PRs if you want to look at it, but there are many open, you have to search for it

**Comment by Lpbzzz** [comment]
> We worker support is not ready yet, is not even a priority for now. We will first support offscreen canvas ( in the same thread ) and then hopefully a way to run it in a webworker. Fabricjs uses the window object often, so is not straight forward to do that. Events from inputs need to run in the main window and some sort of data needs to go in the web worker and run there. Also there is the question how do you move object programmaticaly from the main window to the worker, you will have to setup a series of postMessage calls with the api, everything becomes async, is a bit of a large concept work

I see, thanks for your work. You probably mean this：https://github.com/fabricjs/fabric.js/pull/8774  .My trouble is that it blocks the page when rendering a lot of data, is there any recommended way to optimize it at the moment?

**Comment by asturur** [comment]
i do not know which data are you rendering and which is your millisecond treshold for which it becomes a problem

**Comment by Lpbzzz** [comment]
> 我不知道您正在渲染哪些数据以及哪个毫秒阈值会成为问题

I'm building a chart: it's scrollable sideways. The axes are a rect every minute as a marker, and a text every hour. the data is some points, every minute possible, and there are about 10 groups that look like swim lanes overlooking. If I need to show 3 months at a time, the maximum limit is about 3*30*24*60 *11 objects. i know I should avoid rendering so many in some virtual way, but I can't do it right now. That's why I'm trying to calculate the new Rect in the worker and add them to the canvas.  
![image](https://github.com/fabricjs/fabric.js/assets/28721487/d3dbec3d-4459-4488-abe0-0b8adfffbf41)

**Comment by Lpbzzz** [comment]
> > 我不知道您正在渲染哪些数据以及哪个毫秒阈值会成为问题
> 
> I'm building a chart: it's scrollable sideways. The axes are a rect every minute as a marker, and a text every hour. the data is some points, every minute possible, and there are about 10 groups that look like swim lanes overlooking. If I need to show 3 months at a time, the maximum limit is about 3 * 30 * 24 * 60 * 11 objects. i know I should avoid rendering so many in some virtual way, but I can't do it right now. That's why I'm trying to calculate the new Rect in the worker and add them to the canvas. ![image](https://private-user-images.githubusercontent.com/28721487/329450449-d3dbec3d-4459-4488-abe0-0b8adfffbf41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMTMyMjMsIm5iZiI6MTcxNTMxMjkyMywicGF0aCI6Ii8yODcyMTQ4Ny8zMjk0NTA0NDktZDNkYmVjM2QtNDQ1OS00NDg4LWFiZTAtMGI4YWRmZmZiZjQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDAzNDg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ODJhN2Q0OWIwZTUzMWRlNWJlZjA0ZGExOGU2NzZmYmI5MTgzZmVjNDRkZmQzOTE4NTczODJkODk0MjBjYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wIAm961CsQZwy_t_1NdJtQS9bShXYwadBiqgy0hyB48)

This is just the limit of the test case, in most cases you don't need to worry about rendering issues
