### ISSUE TITLE
When I apply filters on canvas Image it reduce the image width

### ISSUE THREAD

**Issue by Muhammad-Shoaib-Official** [fabricjs/fabric.js#9878]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

21.7.2

### Link To Reproduction

https://social-health-frontend-one.vercel.app/

### Steps To Reproduce

Orginal image
![Screenshot_2](https://github.com/fabricjs/fabric.js/assets/94632204/8ebeafc1-f440-4b16-9e4d-a38ffe670a44)
filtered image
![Screenshot_1](https://github.com/fabricjs/fabric.js/assets/94632204/11ab5b93-b46b-4726-af76-8727ffe7fff3)

code 

export const useCustomCropImage = ({ src, onCropped, style }) => {
  const [zoom, setZoom] = useState(1);
  const [canvas, setCanvas] = useState();
  const [filter, setFilter] = useState('Original');
  const [activeTab, setActiveTab] = useState('crop');
  const [filterPreview, setFilterPreview] = useState([]);
  const [text, setText] = useState(defaultTextProperties);

  const loadImage = () => {
    canvas?.clear();

    fabric.Image.fromURL(src, function (img) {
      img.set({ id: 'main_canvas_image', hasControls: false });
      img.set({ scaleX: 1, scaleY: 1 });
      img.scaleToWidth(canvas.width);

      if (img.height < canvas.height) {
        img.scaleToHeight(canvas.height);
      }

      canvas.add(img);
      canvas.renderAll();
      loadFilterPreview();
    });

    handleImageMoving();
  };

  const handleImageMoving = () => {
    const zoneHeight =
      document?.getElementsByClassName('canvas-container')[0].clientHeight -
      document?.getElementsByClassName(style.cropperOverlay)[0].clientHeight *
      2 +
      60;

    const zoneWidth = canvas.width;

    canvas.on('object:moving', function (e) {
      let obj;
      obj = e.target;
      obj.setCoords();
      let boundingRect = obj.getBoundingRect();
      let zoom = canvas.getZoom();
      let viewportMatrix = canvas.viewportTransform;
      boundingRect.top = (boundingRect.top - viewportMatrix[5]) / zoom;
      boundingRect.left = (boundingRect.left - viewportMatrix[4]) / zoom;
      boundingRect.width /= zoom;
      boundingRect.height /= zoom;

      let ch = obj.canvas.height / 2 - zoneHeight / 2 + zoneHeight / zoom,
        cw = obj.canvas.width / 2 - zoneWidth / 2 + zoneWidth / zoom;

      if (obj.id !== 'main_canvas_image') {
        return;
      }

      if (boundingRect.top > obj.canvas.height / 2 - zoneHeight / 2) {
        obj.top = obj.canvas.height / 2 - zoneHeight / 2;
      }

      if (boundingRect.top < ch - boundingRect.height) {
        obj.top = ch - boundingRect.height;
      }

      if (boundingRect.left > obj.canvas.width / 2 - zoneWidth / 2) {
        obj.left = obj.canvas.width / 2 - zoneWidth / 2;
      }

      if (boundingRect.left < cw - boundingRect.width) {
        obj.left = cw - boundingRect.width;
      }
    });
  };

  const cropImage = () => {
    const img = document?.createElement('img');
    img.src = canvas?.toDataURL?.('image/png', 1);
    img.onload = () => {
      const tempCanvas = document?.createElement('canvas');
      tempCanvas.width = canvas?.width;
      tempCanvas.height =
        canvas.height -
        document?.getElementsByClassName(style.cropperOverlay)[0].clientHeight *
        2;

      tempCanvas
        .getContext('2d')
        .drawImage(
          img,
          0,
          document?.getElementsByClassName(style.cropperOverlay)[0]
            .clientHeight,
          canvas.width,
          canvas.height -
          document?.getElementsByClassName(style.cropperOverlay)[0]
            .clientHeight *
          2,
          0,
          0,
          canvas.width,
          canvas.height -
          document?.getElementsByClassName(style.cropperOverlay)[0]
            .clientHeight *
          2
        );
      onCropped(tempCanvas?.toDataURL('image/png', 1));
    };
  };

  const addText = () => {
    canvas.add(
      new fabric.Textbox(text.text, {
        left: 0,
        top: 100,
        editable: true,
        fill: text.color,
        fontFamily: text.family,
        fontSize: 30,
      })
    );
    setText(defaultTextProperties);
  };

  const loadFilterPreview = () => {
    const filtersList = [
      new fabric.Image.filters.Vibrance({ vibrance: 1 }),
      new fabric.Image.filters.Contrast({ contrast: 0.1 }),
      new fabric.Image.filters.Brightness({ brightness: 0.1 }),
      new fabric.Image.filters.Gamma({ gamma: [1, 2, 2] }),
      new fabric.Image.filters.HueRotation({ rotation: 90 }),
      new fabric.Image.filters.Brightness({ brightness: 0.5 }),
    ];

    const updatedPreviews = [
      { label: 'Original', preview: '', filters: [] },
      { label: 'Studio', preview: '', filters: [filtersList[0], filtersList[1]] },
      { label: 'Spotlight', preview: '', filters: [filtersList[2]] },
      { label: 'Prime', preview: '', filters: [filtersList[3]] },
      { label: 'Classic', preview: '', filters: [filtersList[4]] },
      { label: 'Edge', preview: '', filters: [filtersList[5]] },
      { label: 'Luminate', preview: '', filters: [filtersList[6]] },
    ];

    setFilterPreview(updatedPreviews.map(filterItem =>
      ({ ...filterItem, preview: canvas?.toDataURL?.() })
    ));
  };

  return {
    zoom,
    text,
    filter,
    canvas,
    setZoom,
    setText,
    addText,
    setFilter,
    activeTab,
    loadImage,
    cropImage,
    setCanvas,
    setActiveTab,
    filterPreview,
  };
};

  useEffect(() => {
    setCanvas(new fabric.Canvas(
      document.getElementById("cover_canvas"),
      {
        width: canvasWidth,
        height: canvasHeight,
        backgroundColor: "black",
        preserveObjectStacking: true,
        selection: false,
      }));
  }, []);

  useEffect(() => {
    canvas && loadImage();
  }, [canvas, src]);

  useEffect(() => {
    if (canvas) {
      canvas.getObjects()?.find((obj) => obj.id === "main_canvas_image")
        ?.scaleToWidth(canvas.width * zoom);
      canvas.renderAll();
    }
  }, [zoom]);

  useEffect(() => {
    const current = filterPreview.find((e) => e.label === filter);
    if (current && canvas) {
      const canvasImage = canvas?.getObjects()
        ?.find((e) => e.id === "main_canvas_image");

      canvasImage.filters = current.filters;
      canvasImage.applyFilters();
      canvasImage.scaleToWidth(canvas.width);
      canvas.renderAll();
    };
  }, [filter]);

          <canvas id="cover_canvas" />

### Expected Behavior

image width should be same to canvas width

### Actual Behavior

filtered image
![Screenshot_1](https://github.com/fabricjs/fabric.js/assets/94632204/11ab5b93-b46b-4726-af76-8727ffe7fff3)

### Error Message & Stack Trace

```bash
No error message it throw in consle
```

**Comment by asturur** [comment]
please have a look at the documentation, in particular:
http://fabricjs.com/fabric-filters
and the paragraph about webgl and texture size

**Comment by Muhammad-Shoaib-Official** [comment]
> please have a look at the documentation, in particular: http://fabricjs.com/fabric-filters and the paragraph about webgl and texture size

This doesn't work for me. 
Actually, I'm not facing an issue when I apply filters; it cuts the image width to half of the canvas, but I want filters implemented smoothly without losing the image width. I tried it, but it did not work for me. Here is my code.

**// intial image load**
const loadImage = () => {
    canvas?.clear();
    fabric.Image.fromURL(src, function (img) {
      img.set({ id: 'main_canvas_image', hasControls: false });
      img.set({ scaleX: 1, scaleY: 1 });
      img.scaleToWidth(canvas.width);

      if (img.height < canvas.height) {
        img.scaleToHeight(canvas.height);
      }

      canvas.add(img);
      canvas.renderAll();
      loadFilterPreview();
    });

    handleImageMoving();
  };

**// filters list with preview**
const loadFilterPreview = () => {
    const filtersList = [
      new fabric.Image.filters.Vibrance({ vibrance: 1 }),
      new fabric.Image.filters.Contrast({ contrast: 0.1 }),
      new fabric.Image.filters.Brightness({ brightness: 0.1 }),
      new fabric.Image.filters.Gamma({ gamma: [1, 2, 2] }),
      new fabric.Image.filters.HueRotation({ rotation: 90 }),
      new fabric.Image.filters.Brightness({ brightness: 0.5 }),
    ];

    const updatedPreviews = [
      { label: 'Original', preview: '', filters: [] },
      {
        label: 'Studio',
        preview: '',
        filters: [filtersList[0], filtersList[1]],
      },
      { label: 'Spotlight', preview: '', filters: [filtersList[2]] },
      { label: 'Prime', preview: '', filters: [filtersList[3]] },
      { label: 'Classic', preview: '', filters: [filtersList[4]] },
      { label: 'Edge', preview: '', filters: [filtersList[5]] },
      { label: 'Luminate', preview: '', filters: [filtersList[6]] },
    ];

    setFilterPreview(
      updatedPreviews.map(filterItem => ({
        ...filterItem,
        preview: canvas?.toDataURL?.(),
      }))
    );
  };

// useEffect for handle filter change
useEffect(() => {
    const current = filterPreview.find(e => e.label === filter);
    if (current && canvas) {
      const canvasImage = canvas
        ?.getObjects()
        ?.find(e => e.id === 'main_canvas_image');

      canvasImage.filters = current.filters;
      canvasImage.applyFilters();
      canvasImage.scaleToWidth(canvas.width);
      canvas.renderAll();
    }
  }, [filter]);

**Comment by asturur** [comment]
Please add a working reproducible case i can't really work with snippets of code that i have to find a way to run.
