### ISSUE TITLE
[Bug]: Textbox does not wrap word when their is no space in words.

### ISSUE THREAD

**Issue by niketaOptimumnbrew** [fabricjs/fabric.js#9881]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome, Safari

### Node Version (if applicable)

14.20.0

### Link To Reproduction

https://jsfiddle.net/Niketa_patel/fo5q1bzt/4/

### Steps To Reproduce

1. type text continusouly without space.
2. it'll increase textbox width even if textbox has static width.
3. it does not wrap word when words has no space.

### Expected Behavior

- should wrap word when their is no space.
- should not extend the width when object have static width.

### Actual Behavior

- it does not wrap word when their is no space in words.
- it automatically increase width on text addition event if static width is set.

Thanks.

**Comment by asturur** [comment]
@niketaOptimumnbrew there is not a wrapping method that behaves between the normal english wrapping and the option that is called 'splitByGrapheme'.
This is not a bug is a feature request and 5.x is no more in development.
What you call bug is how the text in fabricJS works for now.
