### ISSUE TITLE
[Feature]: Undo Redo for EraserBrush

### ISSUE THREAD

**Issue by quangduxng** [fabricjs/fabric.js#9883]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

I need new feature: undo redo 

### Current State

```
`  
                fabricRef.current.isDrawingMode = true;
                fabricRef.current.off("mouse:move");
                // @ts-ignore
                fabricRef.current.freeDrawingBrush = new fabric.EraserBrush(fabricRef.current);
                fabricRef.current.freeDrawingBrush.width = widthPoint;
        `
```

**Comment by quangduxng** [comment]
if (isErase && !isDraw && !isMove) {
                fabricRef.current.isDrawingMode = true;
                fabricRef.current.off("mouse:move");
                // @ts-ignore
                fabricRef.current.freeDrawingBrush = new fabric.EraserBrush(fabricRef.current);
                fabricRef.current.freeDrawingBrush.width = widthPoint;
       }

**Comment by asturur** [comment]
Undo redo is not something fabricJS ship with.
It has been discussed in various issues how to get there and different way to implement that, please have a search in past issues, closed or open
