### ISSUE TITLE
canvas.setBackgroundImage 1 px off

### ISSUE THREAD

**Issue by somecodemonkey** [fabricjs/fabric.js#990]
When i you use canvas.setBackgroundImage it renders the background image off by one pixel, barely noticeable. 

http://jsfiddle.net/darbs/dkDjL/3/

**Comment by jhundley9109** [comment]
I know this has been closed for a while, but it appears this may have come back again.

I am using fabric 1.6.0-rc.1. I have found that I need to set a strokeWidth = 0 on a background image to avoid a 1px transparent top and left line.

**Comment by asturur** [comment]
that is correct.
