### ISSUE TITLE
[Feature]: fabircjs Exports tiff files

### ISSUE THREAD

**Issue by LingYun** [fabricjs/fabric.js#9910]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [X] I am filing a **FEATURE** request.

### Description

I want to export tiff files directly through fabricjs, does fabricjs currently support this?
 

### Current State

Does fabricjs source code reserve extension space for exporting tiff files, can this be done on existing source code?
The current idea is to convert from canvas to jpeg image format, and then from jpeg to tiff file format, I wonder if this idea is feasible?

**Comment by asturur** [comment]
The browser do not support a TIFF file export. 
What you can do is pick up a library that supports TIFF encoding, export with toCanvaseElement, and use https://github.com/motiz88/canvas-to-tiff to create the TIFF.
I think i used that one or another with success in the past.

Be aware that TIFF support, unless you need multipage files, is usually a unnecessary requirement. TIFF has nothing better than PNG when it comes to image quality at 8 bit per pixel.
