### ISSUE TITLE
[Bug]: Textbox last line styles removed after pressing enter(splitByGrapheme=true)

### ISSUE THREAD

**Issue by dakshlohar1** [fabricjs/fabric.js#9927]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

18.19.0

### Link To Reproduction

https://jsfiddle.net/dakshlohar1/z5v9ebjf/5/

### Steps To Reproduce

1. Create a fabric canvas and add the Textbox object to the canvas with splitByGrapheme=true and fixed width for splitting and some styles applied to the last characters. 
2. Enable editing of Textbox, and press enter, now again start typing, before the character splits stop typing and press enter and the last line styling will be removed after pressing enter.
3. This happens for all kinds of styles like bold, italic, etc.

### Expected Behavior

It should not remove the styles of last line after pressing enter key
The most relevant issue I found are #5493 and #4243 

### Actual Behavior

The last line styles are removed when pressing enter removed

**Comment by dakshlohar1** [comment]
Moving to version 6.0 is a big headache for me, sorry but I can't do that.
But actually I found the code that is causing this, in the insertNewlineStyleBlock method we are removing the styles of previous line, so removing that line solved my bug.

**Comment by asturur** [comment]
i didn't ask you to upgrade your work to 6.0, but just if you can replicate the bug in 6.0

**Comment by dakshlohar1** [comment]
Okay I will try

**Comment by asturur** [comment]
please check if the build in this PR fixes the issue.
https://github.com/fabricjs/fabric.js/pull/9965
if i don't get feedback i won't publish it
