### ISSUE TITLE
[Bug]: reviver should be typed as optional on Path.toSVG(reviver: TSVGReviver)

### ISSUE THREAD

**Issue by cprcrack** [fabricjs/fabric.js#9929]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [x] I have created an accurate and minimal reproduction

### Version

6.0.0-rc2

### Node Version (if applicable)

None

### Link To Reproduction

https://github.com/fabricjs/fabric.js/blob/58ae572836f3d8b853ee964cc733fb7bb5c147e9/src/shapes/Path.ts#L259

### Steps To Reproduce

In your code editor with Typescript support and Fabric 6.0.0-rc2, type:

```
const p = new fabric.Path('');
console.log(p.toSVG());
```

### Expected Behavior

No Typescript errors.

### Actual Behavior

Typescript error:
```
Expected 1 arguments, but got 0. ts(2554)
Path.d.ts(103, 11): An argument for 'reviver' was not provided.
```

**Comment by cprcrack** [comment]
My current workaround: `path.toSVG(markup => markup)`

**Comment by asturur** [comment]
I was sure i fixed this recently. You can open a PR and change the type to optional
