### ISSUE TITLE
[Bug]: Line doesn't update x1,y1,x2,y2 inside object:moving event handler

### ISSUE THREAD

**Issue by maxerbubba** [fabricjs/fabric.js#9934]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

5.3.0

### In What environments are you experiencing the problem?

Chrome

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/pLco1yr2/2/

### Steps To Reproduce

1. Create a line
2. log event.target.x1 on object:moving event handler
3. user drags the line

### Expected Behavior

x1, y1, x2, y2 see new values in event handler.

### Actual Behavior

x1, y1, x2, y2 do not update.

Note that top and left update correctly.

**Comment by asturur** [comment]
Hi @maxerbubba this is a misconception with the Line object. the x,y properties are just for initialization. After that is only the left/top that count.

**Comment by asturur** [comment]
We know this is unoptimal and we plan to remove Line in favor of polyLine with only a single segment.

**Comment by maxerbubba** [comment]
Thanks. I was able to use Rect as a workaround but computing the angles
myself was tricky

**Comment by asturur** [comment]
Is not hard to get updated points in realtime from the line object.

**Comment by maxerbubba** [comment]
How does one get the updated points from a line in realtime?

**Comment by asturur** [comment]
get the poins relative from the center of the line.
```ts
const p1 = new Point(x1, y1);
const p2 = new Point(x2, y2);
const center = p1.lerp(p2);

const p1Relative = p1.subtract(center);
const p2Relative = p2.subtract(center);
```

use the moving or object:moving event and use the  `myLine.calcTransformMatrix()` function in the event to get the updated matrix. and transform the points

```ts
line.on('moving', () => {
  const m = myLine.calcTransformMatrix();
  const updatedP1 = p1Relative.transform(m);
  const updatedP2 = p2relative.transform(m);
});
```

**Comment by maxerbubba** [comment]
Nice. 
Please Consider this a feature request to add that to line implementation
