### ISSUE TITLE
[Bug]: rc2 break ActiveSelection if through group select

### ISSUE THREAD

**Issue by ritali4912** [fabricjs/fabric.js#9938]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-rc2

### In What environments are you experiencing the problem?

Microsoft Edge

### Node Version (if applicable)

None

### Link To Reproduction

https://jsfiddle.net/ritali4912/deartfzo/30/

### Steps To Reproduce

1. Create 2 rect
2. Make them in ActiveSelection through group select (mouse down then move to select them)
3. Check the Active Selection

![image](https://github.com/fabricjs/fabric.js/assets/67466090/6d317099-1d9a-4f6a-8623-dbd17b4893c4)

### Expected Behavior

In beta 20, it is correct.
![image](https://github.com/fabricjs/fabric.js/assets/67466090/1eb4c233-b680-465a-907d-42c3e26a3d4a)

### Actual Behavior

In rc2, the bounds of the ActiveSelection change to {left: 0, top: 0, width: 0, height: 0}
![image](https://github.com/fabricjs/fabric.js/assets/67466090/ee2d30c5-71df-4fd3-865e-5f44fc3c5447)

I check the code, and found **it caused by the improper set properties timing**. Especially If the user change the originX, originY which will impact on the layout result.
And with bellow change, I can get correct result. 
Please evaluate and help to fix it in next release.

![image](https://github.com/fabricjs/fabric.js/assets/67466090/62ded4c4-d844-469f-8087-2e898496ebfe)

**Comment by asturur** [comment]
i updated rc3, let me know if it changes anything, otherwise i ll mark as a bug and fix

**Comment by asturur** [comment]
ok i see the point, i have to uncomment the originX to actually make the issue happen with latest master.
Please make tidier reproduction case:

actual reproduction case
```ts
export async function testCase(canvas: fabric.Canvas) {
  const utahCommonDefaults = {
    originX: 'center' as const,
    originY: 'center' as const,
  };

  fabric.ActiveSelection.ownDefaults = {
    ...fabric.ActiveSelection.ownDefaults,
    ...utahCommonDefaults,
  };

  fabric.Rect.ownDefaults = {
    ...fabric.Rect.ownDefaults,
    ...utahCommonDefaults,
  };

  const rect = new fabric.Rect({ width: 500, height: 500, fill: 'blue' });
  const rect2 = new fabric.Rect({ width: 500, height: 500, fill: 'blue' });

  canvas.add(rect, rect2);
}
```

**Comment by ritali4912** [comment]
@asturur 
Yes, I just update to rc3, the issue still here. 
If you make the ActiveSelection through mouse click rect1 + shift click rect2, it is correct.
But group select is wrong.

As my above picture.
The below code initial the ActiveSelection with default properties, for example: originX: left, originY: top
and return with a bound based on {left, top}.
`
super(objects, {
      layoutManager: layoutManager ?? new ActiveSelectionLayoutManager()
    });
`

But then the follow code with set the bound to all 0.
`Object.assign(this, ActiveSelection.ownDefaults);
  this.setOptions(options);`

**Comment by ritali4912** [comment]
@asturur 
Ah, I'm sorry for the uncomment code.
Yes, in my case, I need the originX: 'center', originY: 'center'.

But from the logic, I think it is no matter what value of originX, originX.

**Comment by asturur** [comment]
@ritali4912 check the fix here: https://github.com/fabricjs/fabric.js/pull/9940 and please have a look that the added e2e test represent your use case

**Comment by ritali4912** [comment]
@asturur 
I verified the [9940](https://github.com/fabricjs/fabric.js/pull/9940https://github.com/fabricjs/fabric.js/pull/9940), it works.
