### ISSUE TITLE
[Docs]: v6 Documentation

### ISSUE THREAD

**Issue by mrienstra** [fabricjs/fabric.js#9955]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions

### Description

`README.md` needs a brief notice, calling out the docs being out of date, and letting new people know v6 has been released. And minor updates to relevant sections of [`./CONTRIBUTING.md#-improving-docs`](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#-improving-docs)

It would be great to link to the new docs repo, so contributors can find it easily, definitely in`CONTRIBUTING.md` and maybe in `README.md`.

I see activity happening here:
https://github.com/fabricjs/fabricjs.github.io
_(viewable at https://fabricjs.github.io/)_

And here:
https://github.com/fabricjs/fabricjs.com/tree/main
_(specifically `main` branch, `gh-pages` has not been updated since Jan 18, 2023)_

Happy to open a PR.

PS: I was going to post this as a Discussion, but an Issue seems better in terms of associating it with a possible `README.md` PR.

PPS: I love Astro, good choice!

**Comment by asturur** [comment]
As soon as the website on fabricjs.github.io has mirrored the same content of fabricjs.com, and is in a state in which a person can come and find the info in an easy way, i ll move it back to fabricjs.com and update contributing.md

The new website is not ready yet.
There is a lot to do yet and writing text is harder than writing code.

**Comment by x-tropy** [comment]
a lot of demos shown in previous doc site are gone. may i ask how to get it back?

**Comment by asturur** [comment]
I need to port them if they are still relevant.
Or you can port them too if you are interested.
The old website repo is here:
https://github.com/fabricjs/fabricjs.com
the new website repo is here:
https://github.com/fabricjs/fabricjs.github.io

Different stack, similar way to add a demo.

Looking at the new and old version of a demo you should be able to convert them for the new website if you want

**Comment by asturur** [comment]
For the time being you should use the local build imho. Most of the old documentation is on the new website too, slightly updated. I also do not think the 5.x documentation was particularly good either sadly.

**Comment by EragonJ** [comment]
got it, thanks for the information 👍

**Comment by asturur** [comment]
If anyone is interested, the old website will stay live as an archive only effort at 
https://fabric5.fabricjs.com
