### ISSUE TITLE
[Bug]: Blur filter and Pixelate filter not working after #9933

### ISSUE THREAD

**Issue by Sayene** [fabricjs/fabric.js#9960]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.0-rc3

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/p/devbox/fabric-nextjs-sandbox-forked-7lhfg6?file=%2Fpages%2Findex.tsx

### Steps To Reproduce

1. using fabric 6.0.0
2. blur and pixelate filters are not working anymore since changes in #9933

### Expected Behavior

filters working

### Actual Behavior

filters not working, no errors

**Comment by asturur** [comment]
Can you set up a blockSize higher than 1 in your example? like use 10
