### ISSUE TITLE
[Bug]: 6.0.1 version can't support an svg with an image

### ISSUE THREAD

**Issue by ZhangGuangXin** [fabricjs/fabric.js#9970]
### CheckList

- [x] I agree to follow this project's Code of Conduct
- [x] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [x] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [x] I have searched and referenced existing issues and discussions
- [x] I am filing a **BUG** report.
- [x] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [x] I have created an accurate and minimal reproduction

### Version

6.0.1

### Node Version (if applicable)

None

### Link To Reproduction

http://192.168.2.41:9000/examples/fabric/fabricTest.html

### Steps To Reproduce

I used 6.0.1 version to load an svg with an image, and the result on the web page was a black on image area. Does fabric support loading svg with images?

My code is below:
 `
        let svgUrl = 'http://localhost:9000/examples/resources/svg/11.svg';
        loadSVGFromURL(svgUrl).then((res: any) => {
              var obj = util.groupSVGElements(res.objects, res.opts);
              canvas.add(obj);
              canvas.requestRenderAll();
       })

`
       

The SVG content is below, it is too long, I just give screenshot:
![1720088538276](https://github.com/fabricjs/fabric.js/assets/8392363/86221c03-25b1-4a1c-9a67-59639a22ac73)

### Expected Behavior

I expect fabric can load svg with image on web page.

### Actual Behavior

it is black in the area of image.

**Comment by asturur** [comment]
Hi @ZhangGuangXin  yes the image should load properly.
Can you zip your svg and add it to the issue?

**Comment by ZhangGuangXin** [comment]
Ok, my svg file is below:
[11.zip](https://github.com/user-attachments/files/16105850/11.zip)

**Comment by asturur** [comment]
The issue is that is a pattern and patterns are not supported yet https://github.com/fabricjs/fabric.js/issues/476
