### ISSUE TITLE
[Feature]: I hope you can provide Chinese documentation

### ISSUE THREAD

**Issue by sushuier** [fabricjs/fabric.js#9985]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have searched and referenced existing issues, feature requests and discussions
- [ ] I am filing a **FEATURE** request.

### Description

I hope you can provide Chinese documentation.
中文：这个库很强大，然鹅缺少中文文档，翻译工具翻译过来很起来很蹩脚，而且文档内容非常多，教程也很长，学习难度因语言不通而提升，太可惜了.
chatgpt translate：This library is very powerful, but it lacks Chinese documentation. The translation provided by translation tools is quite awkward, and the documentation is extensive with long tutorials. The difficulty of learning increases due to the language barrier, which is a real pity.

### Current State

缺少中文文档；
it lacks Chinese documentation

**Comment by asturur** [comment]
The new stack supports translations in some way ( astro stralight and astro in general ).
So once some decent documentation is written, someone could translate the MD files.
I can't write chinese.

**Comment by sushuier** [comment]
thks
