### ISSUE TITLE
[Bug]: <FabricImage>.fromURL() simply does not work.

### ISSUE THREAD

**Issue by TimChinye** [fabricjs/fabric.js#9992]
### CheckList

- [X] I agree to follow this project's Code of Conduct
- [X] I have read and followed the [Contributing Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md)
- [X] I have read and followed the [Issue Tracker Guide](https://github.com/fabricjs/fabric.js/blob/master/CONTRIBUTING.md#%EF%B8%8F-issue-tracker)
- [X] I have searched and referenced existing issues and discussions
- [X] I am filing a **BUG** report.
- [X] I have managed to reproduce the bug **after** upgrading to the **latest** version
- [X] I have created an accurate and minimal reproduction

### Version

6.0.2

### In What environments are you experiencing the problem?

Node.js

### Node Version (if applicable)

None

### Link To Reproduction

https://codesandbox.io/p/devbox/fabric-node-sandbox-forked-lyrkjc?workspaceId=015bad26-68eb-4698-a728-aa124cb65760

### Steps To Reproduce

1. Just use `fabric.FabricImage.fromURL()`

See the reproduction, or this image:
![image](https://github.com/user-attachments/assets/2c8cf452-dbe0-4241-a564-248973ea9ce4)

### Expected Behavior

I'd expect to get the "test2" log, which is within the callback.

### Actual Behavior

I get "test1" and "test3" logs, but not the "test2" log.

### Error Message & Stack Trace

```bash
# There is none (that in itself is an issue).
```

### Additional Information

On my actual project I'm running v6.0.2, however that version isn't available on the dropdown when filling out the issue form (I just edited the message to change it from the highest version it would let me, "v6.0.1", to v6.0.2.

**Comment by TimChinye** [comment]
Update: I've tested this on v6.0.2, v6.0.1, v6.0.1, and even v6.0.0-beta1. They all didn't work.
v5.3.0, on the other hand, worked like a charm.

**Comment by mathieulesniak** [comment]
Callback methods has been removed from v6 as said on breaking changes issue : https://github.com/fabricjs/fabric.js/issues/8299

You can load image like that : 
```
const img = await fabric.FabricImage.fromURL(url);
console.log(img)
```

**Comment by asturur** [comment]
Please read at least this one before starting working with 6.0,
and then the first full post of the issue linked. https://github.com/fabricjs/fabric.js/issues/8299

**Comment by TimChinye** [comment]
> Callback methods has been removed from v6 as said on breaking changes issue : #8299
> 
> You can load image like that :
> 
> ```
> const img = await fabric.FabricImage.fromURL(url);
> console.log(img)
> ```

Makes sense, I saw that "upgrading to fabric" changelog and noticed that, but I assumed that if I tried to do it like that it just wouldn't work because none of the docs, tutorials, or demos were like that. I also couldn't find any fabric code out there using promises on github (sourcegraph - guess I'm bad at querying), and I just assumed since the stable v6 came out 2 weeks ago and the v6 beta came out 5 months, that the docs would've been updated by now.
